### ISSUE TITLE
Enhancement: Add a possibility to hide the warning "You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree."

### ISSUE THREAD

**Issue by enix79** [typescript-eslint/typescript-eslint#10016]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-estree

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Every time the Typescript creates a new release, we get the following warning, until typescript/eslint also migrates to the newest version:

`You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.`

While this message is useful at the very beginning to get sensitized for that fact, it gets annoying later and produces some noise every time we start our application.

Please add a possibility to optionally disable this warning.

**Comment by bradzacher** [comment]
https://typescript-eslint.io/packages/parser#warnonunsupportedtypescriptversion
