### ISSUE TITLE
Bug: [no-deprecated] Maximum call stack size exceeded when class implements itself

### ISSUE THREAD

**Issue by FWDekker** [typescript-eslint/typescript-eslint#10031]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

If you have a class in TypeScript that implements itself (i.e. `class Foo implements Foo`), inside which is a getter method (i.e. `get bar(): number { return 42; }`) that is used by another method (i.e. `baz(): number { return this.bar; }`), then upon running `npx eslint Foo.ts` I get the error "RangeError: Maximum call stack size exceeded" while running rule `@typescript-eslint/no-deprecated`, which occurs while linting the line containing `return this.bar`.

Now, why exactly you would want a class to implement itself is quite beyond me, but I accidentally had that in my code and it took me quite a while to figure out what was going on. TypeScript itself seems to have no problem with it at all. I have no problem at all if the resolution is to detect this and then give an error, but that error must be descriptive.

My reproduction repo is quite minimal, so I'm not sure why I was unable to reproduce it in the playground. I'm not too good with node-ish setups, I guess.

### Reproduction Repository Link

https://github.com/FWDekker/typescript-eslint-no-deprecated-bug

### Repro Steps

1) clone the repo
2) `npm install`
3) `npx eslint Foo.ts`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `8.6.0` |
| `@typescript-eslint/parser`            | `8.6.0` |
| `@typescript-eslint/scope-manager`     | `8.6.0` |
| `@typescript-eslint/typescript-estree` | `8.6.0` |
| `@typescript-eslint/type-utils`        | `8.6.0` |
| `@typescript-eslint/utils`             | `8.6.0` |
| `TypeScript`                           | `5.5.4` |
| `ESLint`                               | `9.11.0` |
| `node` (Debian package)                                 | `20.17.0` |

**Comment by kirkwaiblinger** [comment]
> My reproduction repo is quite minimal, so I'm not sure why I was unable to reproduce it in the playground. I'm not too good with node-ish setups, I guess.

I'm not sure either - it reproduces in the playground for me 😁 ([link](https://typescript-eslint.io/play/#ts=5.5.2&fileType=.tsx&code=MYGwhgzhAEBiD29oEsC2AHEBTVWB2ALjAkgN4BQ00A5lgdAEZgBOAFAJQBc0eArqgyzNoFKlWZ1ezPNAAsAJgDclaAF9yKpgC8O3PgKEiV4ydOgEAFsggA6Js2VV1qoA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oBNFjpEZAIb5E3dFADuQ6E0jgwAXxCKgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false))
```ts
class Foo implements Foo {
  get bar(): number {
    return 42;
  }

  baz(): number {
    return this.bar;
  }
}
```

**Comment by kirkwaiblinger** [comment]
Thanks for reporting!

**Comment by kirkwaiblinger** [comment]
Debugging breadcrumb: This is coming from the `symbol.getJsDocTags(checker)` call here while linting the `this.bar` expression 🤔:
https://github.com/typescript-eslint/typescript-eslint/blob/2a956b22451350588ca81ffa3442130f159dfbf5/packages/eslint-plugin/src/rules/no-deprecated.ts#L119-L121

**Comment by auvred** [comment]
This is an upstream TS issue. I filed https://github.com/microsoft/TypeScript/issues/60024.

I think this code is very rare in a wild, but to prevent runtime errors on older TS versions we can just wrap `getJsDocTags` call in a try-catch. (?)

**Comment by kirkwaiblinger** [comment]
+1 to try/catch to work around for existing TS versions
