### ISSUE TITLE
Docs: broken link about typed linting

### ISSUE THREAD

**Issue by markH5** [typescript-eslint/typescript-eslint#10047]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

<https://typescript-eslint.io/getting-started/typed-linting/>

> there is a yellow `Caution` box:
> Your ESLint config file may start receiving a parsing error about type information. See [our TSConfig inclusion FAQ](https://typescript-eslint.io/getting-started/troubleshooting/typed-linting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file).

`our TSConfig inclusion FAQ` link doesn't exist.

I think it might be a link to 

<https://typescript-eslint.io/getting-started/typed-linting/>

### Affected URL(s)

<https://typescript-eslint.io/getting-started/typed-linting/>

### Additional Info

Similar issues <https://github.com/typescript-eslint/typescript-eslint/issues/9645>

may code
https://github.com/typescript-eslint/typescript-eslint/blob/b88ea33f34e0b5f6fc5bd3463a5b32a5c9df8b7e/docs/getting-started/Typed_Linting.mdx?plain=1#L85-L88

**Comment by JoshuaKGoldberg** [comment]
Ah, thanks for this. It's meant to go to the Troubleshooting > Typed Linting FAQ: https://typescript-eslint.io/troubleshooting/typed-linting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file

Accepting PRs!
