### ISSUE TITLE
Bug: 'export type *' in output .d.ts files break TS<5

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#10065]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

Filing an issue for @monodop's https://github.com/typescript-eslint/typescript-eslint/pull/10006#issuecomment-2377787400: #10006 added `export type*` to our output `.d.ts`. But per https://typescript-eslint.io/users/dependency-versions#typescript we still support TS 4.8.4.

In TS 4.8.4, we now have these type errors if you don't use `skipLibCheck`:

```plaintext
node_modules/@typescript-eslint/scope-manager/dist/definition/index.d.ts:3:1 - error TS1383: Only named exports may use 'export type'.

3 export type * from './Definition';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@typescript-eslint/scope-manager/dist/scope/index.d.ts:13:1 - error TS1383: Only named exports may use 'export type'.

13 export type * from './Scope';
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@typescript-eslint/types/dist/index.d.ts:2:1 - error TS1383: Only named exports may use 'export type'.

2 export type * from './lib';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@typescript-eslint/types/dist/index.d.ts:3:1 - error TS1383: Only named exports may use 'export type'.

3 export type * from './parser-options';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is a bug on our end.

In the meantime, a workaround can be to either not update to 8.7.0 of our tooling, or use `skipLibCheck` in your TSConfig.

### Reproduction Repository Link

https://github.com/JoshuaKGoldberg/repros/tree/tseslint-export-type-ts-4

### Repro Steps

1) clone the repo and branch
2) `npm install`
3) `npm run tsc`

### Versions

a
| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/scope-manager`     | `8.7.0` |
| `@typescript-eslint/type-utils`        | `8.7.0` |
| `TypeScript`                           | `4.8.4` |

**Comment by auvred** [comment]
DT will drop support for `typescript@4` in mid-November, until then we will have to export types without a type specifier.
