### ISSUE TITLE
Rule proposal: ban `Record<string, ...>` and similar

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [typescript-eslint/typescript-eslint#10072]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

For some reasons `Record<string, ...>` behaves differently than `Record<'foo'|'bar', ...>`, first one allows you to create an object that doesn't have all possible properties, second one does not and is safer:

```ts
const v1: Record<string, string> = {}; // no ts error

v1['foo'].length; // no ts error, only runtime error

const v2: Record<'foo' | 'bar', string> = {}; // ts error - missing 'foo' and 'bar' keys

// v2['foo'] is always safe, because you can't create an object that doesn't have "foo" key
```

My proposal is to ban types where the key is an inifite set (string, number, symbol), `Record<string, ...>`, `{ [key in string]: ... }`, `{ [key: string]: ...}` etc

### Fail Cases

```TypeScript
const v: Record<string, string> = ...
type X = Record<string, string>
type Y = { [key in number]: ... }
type Z = { [key: `${string}-${string}`]: ... }
```

### Pass Cases

```TypeScript
const v: Record<'foo' | 'bar', string> = ...
type X = Record<'foo' | 'bar', string>
```

**Comment by Josh-Cena** [comment]
I'm -1 on this, but I'm curious to hear what others say. This simply bans you from expressing certain things, instead of pointing you to safer alternatives with the same expressivity—there's no "safe equivalent" of index signatures. I want to point out that `noUncheckedIndexAccess` will fix the soundness hole of `undefined` not being in the return type.

**Comment by bradzacher** [comment]
https://typescript-eslint.io/rules/no-restricted-types
This rule will let you ban `Record`

And this FAQ for banning other type syntaxes:
https://typescript-eslint.io/troubleshooting/faqs/general#how-can-i-ban-specific-language-feature

**Comment by kirkwaiblinger** [comment]
Yeah, the difference between infinite and finite keyed records and indices bothers me too... Is there anything that we could do with a lint rule, though, that `noUncheckedIndexAccess` doesn't just accomplish better? 

A rule banning _creation_ of `Record<string, string>` wouldn't protect you against already-declared signatures, for example
([playground](https://typescript-eslint.io/play/#ts=5.3.3&fileType=.tsx&code=MYewdgzgLgBATgUwOYIB4CUEQK4BtYC8MA9AA4CGUUCcYxSAdGgsABQDkAJiFmFALaVgAC3YBKAFABLAGYxWiFBix4oAfgZI4IbKQgwAhETB5cYmAG8JMGKEghcCBrhBIFyNJhz5N23RGcHBigQAFVSUhoAYXIIBFYxSQBfCSA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDAruuGAL4g9A&tokens=false))
```ts
const regexResult = /pattern/g.exec('doesntmatch')
if (regexResult?.groups != null) {
  // runtime error allowed by TS
  console.log(regexResult.groups.lol.toUpperCase())
}
```

`noUncheckedIndexedAccess` does protect you there, though.
