### ISSUE TITLE
Bug: [@typescript-eslint/naming-convention] Error while loading rule '@typescript-eslint/naming-convention': Cannot read properties of undefined (reading 'parent')

### ISSUE THREAD

**Issue by antonkulakov-it** [typescript-eslint/typescript-eslint#10099]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

no playground it is in console

### Repro Code

```TypeScript
after version 8.8.0

$ npm install
...
$ npm run lint -- --fix

> next-redux@0.1.0 lint
> next lint --fix      

Error while loading rule '@typescript-eslint/naming-convention': Cannot read properties of undefined (reading 'parent')
```

### ESLint Config

```javascript
{
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "extends": [
    "next",
    "next/core-web-vitals",
    "airbnb",
    "plugin:react/recommended",
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:react-hooks/recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier"
  ],
  "settings": {
  },
  "parserOptions": {
    "project": ["./tsconfig.json"],
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 11,
    "sourceType": "module"
  },
    {
      "files": [
        "**/labels.ts",
        "**/*.svg.tsx",
        "**/links.ts"
      ],
    },
],
  "plugins": [
    "react",
    "react-hooks",
    "@typescript-eslint",
    "simple-import-sort",
    "modules-newlines"
  ],
  "rules": {
    "@typescript-eslint/naming-convention": [
      "error",
      {
        "selector": "interface",
        "format": ["PascalCase"],
        "custom": {
          "regex": "^I[A-Z]",
          "match": true
        }
      }
    ],
  },
  "globals": {
    "JSX": true
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "downlevelIteration": true,
    "baseUrl": ".",
    "paths": {
      "@src/*": ["./src/*"],
    },
    "types": [
      "./node_modules/user-agent-data-types",
      "jest",
      "@testing-library/jest-dom"
    ]
  },
  "include": ["next-env.d.ts", "images.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

### Expected Result

eslint works without errors

### Actual Result

Error while loading rule '@typescript-eslint/naming-convention': Cannot read properties of undefined (reading 'parent')

### Additional Info

When I add into package.json
`"overrides": {
    "@typescript-eslint/parser": "8.7.0"
  }`
$ npm install
...
$ npm run lint -- --fix 
works fine

**Comment by bradzacher** [comment]
Could you provide a reproduction?
Either reproduce it in the playground or create a reproduction repository that we can checkout and use to reproduce.

Fragments of commands and snippets are not a reproduction -- for example you list a dozen configs in your attached eslint config.

We need a complete reproduction to help investigate.

**Comment by JoshuaKGoldberg** [comment]
One week without a response, and our issues count is dangerously close to 300 again. I'm going to go ahead and close this out. We can always reopen if someone can post a working reproduction. 🙂
