### ISSUE TITLE
Enhancement: RuleTester `before` and `after` hooks

### ISSUE THREAD

**Issue by RobinTail** [typescript-eslint/typescript-eslint#10107]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

rule-tester

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Previous discussion: https://github.com/typescript-eslint/typescript-eslint/issues/9770

> @JoshuaKGoldberg 
> Our RuleTester is a fork of the core ESLint one, and we've tried to avoid adding any features not present in core.

> @bradzacher 
> submit it to eslint core
> Once it's accepted upstream we will gladly bring it in here to our fork!

All right, I implemented the feature in the ESLint core:
https://github.com/eslint/eslint/pull/18771
It's accepted and released in ESLint v9.12.0:
https://github.com/eslint/eslint/releases/tag/v9.12.0

Since now it's the ESLint core feature, I'd like to see it in the TypeScript-ESLint RuleTester fork as well. Would you allow that?

## Brief explanation 

We're gonna add `before` and `after` properties both to `valid` and `invalid` test cases. If that property is assigned with a function, we execute that function before and after the test case accordingly and regardless the result of the test case itself. Consumers can use those functions for establishing individual environment for the case, for example mocking file system features.

I can help with the implementation.

### Additional Info

RFC: https://github.com/eslint/rfcs/tree/main/designs/2024-hooks-for-test-cases

**Comment by bradzacher** [comment]
great work getting the RFC merged!
we can now add the implementation to our fork!

**Comment by RobinTail** [comment]
Please review, @bradzacher : 

https://github.com/typescript-eslint/typescript-eslint/pull/10109
