### ISSUE TITLE
Docs: Update the State of the `order` Rule Alternative

### ISSUE THREAD

**Issue by manuth** [typescript-eslint/typescript-eslint#10102]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

With the most recent update of `eslint-plugin-import`, the `import/order` now supports ordering named imports:
https://github.com/import-js/eslint-plugin-import/pull/3043

I think it might make sense to change the state of `import/order` to "in another plugin".
What do you think?

### Affected URL(s)

https://github.com/typescript-eslint/typescript-eslint/blob/d6e0f6e7da7b81d1e4b70d3342651c0e7e29c000/packages/eslint-plugin/TSLINT_RULE_ALTERNATIVES.md

**Comment by JoshuaKGoldberg** [comment]
Sorry, what does _"in another plugin"_ mean here? It's already in another plugin: `eslint-plugin-import`, no?

**Comment by manuth** [comment]
Thanks for coming back at me! 😄 
Currently, the status of `ordered-imports` is "implementations differ or ESLint version is missing functionality".

I was assuming, that it's currently labelled like this instead of "in another plugin" because it was missing the `named-imports-order` of the `tslint` rule up until now.

**Comment by JoshuaKGoldberg** [comment]
Ah gotcha! Yes, a 🔌 would make sense. Thanks for mentioning. Accepting PRs!

**Comment by manuth** [comment]
Awesome, Thank you so much!
Will do
