### ISSUE TITLE
Docs: Separate typescript package installation in getting started page

### ISSUE THREAD

**Issue by rchandu** [typescript-eslint/typescript-eslint#10113]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Prior discussion: https://github.com/typescript-eslint/typescript-eslint/issues/9653#issuecomment-2399314640

I suggest we separate out typescript installation as part of the getting started page. This would allow us to handle 2 different kinds of users differently:
1. **Install typescript** - we provide code to install typescript along with the greatest supported version of typescript package
2. **Already have typesctipt** - We show information of what typescript versions are officially supported & others can use but no guarantees.

This would help users who are integrating this package first time & creating bugs. This currently happens because getting started page recommends installing latest typescript always.

### Affected URL(s)

https://typescript-eslint.io/getting-started

### Additional Info

Context for bugs created because of CLI message mentioning that typescript version is supported: https://github.com/typescript-eslint/typescript-eslint/issues?q=%22not+officially+supported+%22

**Comment by rchandu** [comment]
JoshuaKGoldberg Created this from prior discussion  at https://github.com/typescript-eslint/typescript-eslint/issues/9653#issuecomment-2400731827

**Comment by JoshuaKGoldberg** [comment]
Thanks for filing!

This is really only an issue when the current supported version range of typescript-eslint is behind the latest stable release of TypeScript. Which has been the case for longer than usual in TypeScript 5.6 (#9972 is blocked).

I'd be in favor of changing specifically the `typescript` version to a `major.minor`, like:

```diff
- npm install --save-dev ... typescript typescript-eslint
+ npm install --save-dev ... typescript@5.5 typescript-eslint
```

Thoughts @typescript-eslint/triage-team?

Note that we'd need to update the instructions in https://typescript-eslint.io/maintenance/pull-requests/dependency-version-upgrades#typescript.

**Comment by kirkwaiblinger** [comment]
ehhh, I feel like ensuring that you install compatible version of packages is sort of an implicit part of installing dependencies. I worry it would be overly prescriptive to put a specific version, and imply "we only support typescript 5.5" rather than "be sure to use something within the right range".

So, not saying there isn't room to change the wording, but I'm a little negative on putting a specific version number in there.

**Comment by bradzacher** [comment]
Yeah I'm -1 here too.

- It's another version we need to keep in sync as we do bumps.
- We *_GENERALLY_* support new TS releases the week after they release.
   - Meaning that generally there's a few days to a week where the docs are _technically_ suggesting the wrong version be installed.
- *_GENERALLY_* installing the newer TS version shouldn't cause an issue - things outright breaking are the rarer case.
- We log the warning about it to prompt someone to downgrade if things are actually broken.
- The cases where someone is truly bootstrapping a TS project from scratch using our docs as the only guide is going to be the rarer case.
    - i.e. generally someone already has TS setup and is using our guide to add ESLint (i.e. they would not do `npm install -D typescript typescript-eslint` and would just skip installing TS as it's already installed.)

I think we could update the docs to link to the TS Dep section, but I don't think we should update the command.

**Comment by JoshuaKGoldberg** [comment]
Following up: we're going to wontfix this for now as something that's not helpful _most_ of the time. But we'll keep an eye out. If we end up falling behind TypeScript often, we can revisit.

Thanks all!
