### ISSUE TITLE
[no-unnecessary-condition] Disable `no-constant-condition` in configs

### ISSUE THREAD

**Issue by ark120202** [typescript-eslint/typescript-eslint#1014]
Since `no-unnecessary-condition` is essentially a stricter version of `no-constant-condition` I don't see much reason to have both of them enabled at the same time. I've checked and it seems to report on all of the incorrect cases from [no-constant-condition](https://eslint.org/docs/rules/no-constant-condition#rule-details) documentation.

**Comment by bradzacher** [comment]
I didn't think about this much at the time - but the only place that we would do this is in the `all` config.

`no-unnecessary-condition` is not in the recommended set, so there's nothing breaking to do here. I'd almost say that it's only required to be documented.

**Comment by JoshuaKGoldberg** [comment]
This is documented already on https://typescript-eslint.io/rules/no-unnecessary-condition:

> ESLint: no-constant-condition - no-unnecessary-condition is essentially a stronger version of no-constant-condition, but requires type information.
