### ISSUE TITLE
Repo: internal lint rule for our code standards around `=== nullishLiteral`

### ISSUE THREAD

**Issue by kirkwaiblinger** [typescript-eslint/typescript-eslint#10186]
### Suggestion

We usually (intentionally) conflate `null` and `undefined` in this repo, and use `== null` or `== undefined` instead of `=== null` or  `=== undefined`. This pattern is generally adhered to pretty consistently, but it's surprising for some contributors, (ref, eg, https://github.com/typescript-eslint/typescript-eslint/pull/10003), and there are plenty of examples of deviations.

I propose let's lint for equality comparisons to nullish literals to enforce that only `== null`/`!= null` are used. We can autofix `== undefined` to `== null` and _suggest_ when a strict equality comparison is used, which might sometimes need to be disabled in rare cases.

Presumably it would be preferable if [eqeqeq](https://eslint.org/docs/latest/rules/eqeqeq) had a configuration to support this, but... it doesn't. And it's super trivial to write one ourself in this case.

**Comment by JoshuaKGoldberg** [comment]
Yeah I don't feel particularly strongly one way or another, and suspect you @kirkwaiblinger and @bradzacher do much more than me 😄. +1 from me on picking a style and linting for it.

**Comment by bradzacher** [comment]
I'd be happy if someone chucks in a `no-restricted-syntax` rule for it - should be enough to give people the heads up.

I doubt there'll be many if any exceptions that need disabling.
