### ISSUE TITLE
Following the Getting Started Guide enables 'no-undef'

### ISSUE THREAD

**Issue by dmurvihill** [typescript-eslint/typescript-eslint#10185]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

Following the steps in the [Getting Started Guide](https://typescript-eslint.io/getting-started/) enables the `no-undef` rule from eslint, which is [strongly discouraged](https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors).

The rule comes in from `eslint.configs.recommended` in `eslint.config.mjs`, l7. Commenting out that line fixes the errors.

### Reproduction Repository Link

https://github.com/dmurvihill/tseslint-bug-repro

### Repro Steps

1) clone the repo
2) `npm install`
3) `npx eslint`

The configuration file will emit the full expanded flatConfig before linting.

Errors:
```
/Users/dolan/IdeaProjects/typescript-eslint-bug/babel.config.cjs
  1:1  error  'module' is not defined  no-undef

/Users/dolan/IdeaProjects/typescript-eslint-bug/eslint.config.mjs
  11:1  error  'console' is not defined  no-undef

✖ 2 problems (2 errors, 0 warnings)
```

The `no-undef` rule is enabled despite being [strongly discouraged](https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors).

To see the full flat config:
`node eslint.config.mjs > eslint-config-expanded.json`

On line 49:
`"no-undef": "error",`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `typescript-eslint@8.10.0`  | `8.10.0` |
| `TypeScript`                           | `5.6.3` |
| `ESLint`                               | `9.13.0` |
| `node`                                 | `20.17.0` |

**Comment by Josh-Cena** [comment]
The guide also tells you to add `...tseslint.configs.recommended`, which should disable this rule?

https://github.com/typescript-eslint/typescript-eslint/blob/399a29c7ae3bd0e457d7229a3c89e8cd93a54c32/packages/eslint-plugin/src/configs/eslint-recommended-raw.ts#L38

**Comment by bradzacher** [comment]
Yeah this is working as intended.
The `no-undef` rule is not recommended **_on TypeScript files_**.

Your reports listed are on an MJS and CJS files - which are not fully checked by TS (most people DO NOT run TS on their JS files) and thus the `no-undef` rule can be valuable for them.

**Comment by dmurvihill** [comment]
The config that ultimately worked for me:

```javascript {
export default tseslint.config(
  {
    files: [ "**/*.js", "**/*.cjs", "**/*.mjs" ],
    languageOptions: {
      globals: {
        ...globals.node,
        /// ...globals.browser, etc.
      },
    },
    ...eslint.configs.recommended,
  },
  ...tseslint.configs.recommended,
);
```

This ought to be in the docs imo, as it's quite common to be linting js files with node globals at the top level.

**Comment by bradzacher** [comment]
> This ought to be in the docs imo

This concept is explained in the docs:

https://eslint.org/docs/latest/use/configure/language-options#predefined-global-variables

We just do not include it in our getting started guide - purposely so because it's not generally required to get started.

Ultimately we have to draw the line somewhere or else the guide will be too long and cover too many things and is no longer a short and quick guide!
