### ISSUE TITLE
Bug: [consistent-type-imports] can not support  when using DI of nest.js

### ISSUE THREAD

**Issue by tianyingchun** [typescript-eslint/typescript-eslint#10200]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play#ts=5.6.2&fileType=.tsx&code=MYGwhgzhAEBKCmBHArvCAXAwgewHbvgA90BleAJwDcBLYeaAbwCgmBfJ0SGAUUvnwBCyGMzYtOUaAAkAngAcKEeADV%2BAE2Tl4ABRDIA5tVyZyeRk2jQMYdLWjY5tvDAC8jaMFO4AXNADaALoANNAg2Pq8-OgQvgBmYCBK0KwA3BYezujkyMDo2OQAFOmWcuTUlDb08HyCwr6RtRBBxdCl5ZXQWihoWHgExGRUtPC%2BCN0YOPhEpBQ0dOkAlO7srEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUFuQAIBcBPABxQGNoBLY-AWhXkoDt8B6MgeyeUuX0Ra0ipWpQC2xDtHyoMAbXDYlkRNGhTIAGkVLgUACa8AhvHgcA7gBUSiAIJMmHfEfyUussADMTyRDuwAvv4AuopBAUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDArugDTg12ztM0dAFkAholYduvWkVgBJJKibI8AQSIBPVgDMxqEjJpR0AD0RZk8dETwGAIujiYxeWJjKVpPE5HTwak4ubh4i6PYAJm5iUpicvnwAblgARm7WIrCR7BgAylp2YmZxCbJQ9IzMAAqYsJaYeFoKRGrIBsgAXhnEegZGiXKKyqp4AEoRgqR9hsZ86UYAqpiorJAAdJCDUHWweA7ImGub25AC%2B4drkcj0W%2BWQN7CobuiRWTkYXmzxc7SIbgALL7AAC%2BvDBIKAA&tokens=false

### Repro Code

```TypeScript
import { schedule } from 'node-cron';
import { mergeOptions } from '@hyperse-hub/vendure-common';
import { Inject, Logger, type OnApplicationBootstrap } from '@nestjs/common';
import type { EventBus, RequestContextService } from '@vendure/core';
import {
  type DeepPartial,
  PluginCommonModule,
  type Type,
  VendurePlugin,
} from '@vendure/core';
import { loggerCtx, PLUGIN_INIT_OPTIONS } from './constants.js';
import { CronEvent } from './cron-event.js';
import {
  type PluginInitOptions as CronInitOptions,
  type PluginInitOptions,
} from './types.js';

@VendurePlugin({
  imports: [PluginCommonModule],
  providers: [
    {
      provide: PLUGIN_INIT_OPTIONS,
      useFactory: () => HyperseVendurePluginCron.options,
    },
  ],
  compatibility: '>=3.0.0',
})
export class HyperseVendurePluginCron implements OnApplicationBootstrap {
  static options: CronInitOptions = { cron: [], logEvents: false };

  constructor(
    @Inject(PLUGIN_INIT_OPTIONS)
    private options: PluginInitOptions,
    private eventBus: EventBus,
    private requestContextService: RequestContextService
  ) {}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
   '@typescript-eslint/consistent-type-imports': [
        'error',
        { disallowTypeAnnotations: false },
      ],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strict": true,
    "sourceMap": true,
    "noImplicitAny": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictPropertyInitialization": false,
    "importsNotUsedAsValues": "preserve",
    "noImplicitReturns": false,
    "baseUrl": ".",
    "rootDir": ".",
    "outDir": "dist",
    "isolatedModules": true,
    "paths": {}
  }
}
```

### Expected Result

import { EventBus, RequestContextService } from '@vendure/core';
should not convert into 
import  type { EventBus, RequestContextService } from '@vendure/core';

### Actual Result

import { EventBus, RequestContextService } from '@vendure/core';
to
import  type { EventBus, RequestContextService } from '@vendure/core';

### Additional Info

https://github.com/typescript-eslint/typescript-eslint/pull/5904
i found this PR , but it seems that above codes have been removed from latest typescript/estlint?

**Comment by tianyingchun** [comment]
I'll be tomorrow，prepare demo

**Comment by tianyingchun** [comment]
<img width="923" alt="image" src="https://github.com/user-attachments/assets/b145d112-f394-4578-97a6-e4af418f198e">

https://typescript-eslint.io/play/#ts=5.6.3&fileType=.ts&code=JYWwDg9gTgLgBAbzgSQHYCsCmBjGAaOGATzEzgHlUBBMMAG2GwEMZgJUAhCCGAZxihMwcAL5wAZlAgg4AcgACqTP3S8A9Nmkh2sgNwAoUJFiI4AUQBumVDA4BXXgQBKmAI53lMAMLsYmAB4wAMqYUBaMZGKS0nLyVqgAJnZQmBrQmHqG4NDwCPpwcAAKdHYA5sCoPiDaqACyEEl0mHj5cABq1kkpxWUVLVFSMgrxXamaKZn68h2JyZg95agAFHkFRjm8AFxwANoLFVU19Y2YALotBWBS4QmhW7utBasFL1cQN5jbsoUAMgCqAHFkAA5AD6IOQABVQeRCpDkORgUFZBcXgUHJgAGJMXDQIjbJYASjgAF4AHxwAASJDumBmo32lSkqAAdBAwKx2I5HqJUedWppwCxgAAjYAMYhfMkkgDMLIADAqUfoRIT9AFjPBsHQmLxeFSaVBeHTOnNGV5mXAjE0QNY%2BBRqLQGMxOZxuHwBEJEK1%2BMLsHB2a77kxUERSaZsMztjtznA6BBSpY7fdxEw6MbRAYBVyBHZcVAljz5GgsLglt9-kCwRDobD4YjkWq0VdgBYWGRA2xUMHQ6jLlBW%2B24Jh4rYHNskzZ7NzmwO2344Cl3J4fDYAsFQuFsJ84C5l-xV35AiEwhFWsSkDzNN2IE0WfHSksYAALYC8Fkju3TwkGNHX3i3pg94Jk%2Br7vkuHgHr464nlumBNqI%2BhIQUupEKg-rsDQ9CMMK7BcDw-CCGARLen%2BOYRsyBAPpO9piCShBgWyHJdrwv6ISI%2BhAA&eslintrc=N4KABGBEAOCGBOBnApvSAuKABALgT2mUQGN4BLaHAWiIBsyA7HAejiVUgBpwp4BXWkQxhQEbPkIlylGonpNmxAPYNEZRDmRMqE5FTIBbaEvg5EwgNo8xYyKngmu1scCgATdbFq0lAdwAqBMgAggwMSjiwOGQq5pgAZl4ozhAAvs4AujzpqUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDArugDTg2Tsl0AVSIBrIrADuRAJJEAwgEM80ABYA1RY0UAjDGUoduvWiVHJEAGWQ75q9NFGsjPGlABmsTNHTziJZHp0IjwlAKIAczkAMTR0ADlFeHQDNkxOVz4AKxIAD1ZITHRFZgBaHPzM0wYmPHj2VFQ7B1FUlxMoCRkkVCZkPABBIgBPZ3TjNzoa5mj2ImZCIgAVYcQUsYyOqcZmACFkIgATJUaBxERUUcNxqs7Ybou%2BvCXVQI2JvkVUSUVhkgBlaYsa6bSZdHpPABK6Dw7EwpHet0gEgACphYGtMHhhgNoD4SCRouj4HJDuhcv9kBEiMo4ehWO4voIkSkALKwQ4NdByPBYDGIrYCdAAEXQ7gO6GiXnkqEUBNi6FQh1SjNQzK2eC0ERhBRSACYAAyGyBI%2BAcrm6khEcksU3mjDQkiwVDsAjEArxDkJG0mrZFJ2oABu6AAUk6iOzORgBZMydBZZhlIsY3xAs7lOhDpGuW0bltg5gdEn4NmMP9hiFFPkQR9aOTMchkpXUKK4Im8F5c6C%2BOh4P1W15lF5WTDFIdlIoU9Udng0RisNi5P1kF9kAAvJPuyiq9WTRuILx4EievBCQSHAYkTQu9aUSCIf1YYO%2ByZfVBSMMMpm1u4AUT7wJgDuP6QAc0BFE2mqoO8vAAL4gLBQA&tokens=false

**Comment by kirkwaiblinger** [comment]
@tianyingchun This is a real weird one. The rule logic is pretty clear - if `experimentalDecorators` and `emitDecoratorMetadata` are both true, and any decorator is not present, do not report. 

After quite some poking around in the console, I noticed that you get several warnings about illegal options/combinations of options. When I remove the complained-about options down to the following, the false report goes away ([see in playground](https://typescript-eslint.io/play/#ts=5.6.3&fileType=.ts&code=JYWwDg9gTgLgBAbzgSQHYCsCmBjGAaOGATzEzgHlUBBMMAG2GwEMZgJUAhCCGAZxihMwcAL5wAZlAgg4AcgACqTP3S8A9Nmkh2sgNwAoUJFiI4AUQBumVDA4BXXgQBKmAI53lMAMLsYmAB4wAMqYUBaMZGKS0nLyVqgAJnZQmBrQmHqG4NDwCPpwcAAKdHYA5sCoPiDaqACyEEl0mHj5cABq1kkpxWUVLVFSMgrxXamaKZn68h2JyZg95agAFHkFRjm8AFxwANoLFVU19Y2YALotBWBS4QmhW7utBasFL1cQN5jbsoUAMgCqAHFkAA5AD6IOQABVQeRCpDkORgUFZBcXgUHJgAGJMXDQIjbJYASjgAF4AHxwAASJDumBmo32lSkqAAdBAwKx2I5HqJUedWppwCxgAAjYAMYhfMkkgDMLIADAqUfoRIT9AFjPBsHQmLxeFSaVBeHTOnNGV5mXAjE0QNY%2BBRqLQGMxOZxuHwBEJEK1%2BMLsHB2a77kxUERSaZsMztjtznA6BBSpY7fdxEw6MbRAYBVyBHZcVAljz5GgsLglt9-kCwRDobD4YjkWq0VdgBYWGRA2xUMHQ6jLlBW%2B24Jh4rYHNskzZ7NzmwO2344Cl3J4fDYAsFQuFsJ84C5l-xV35AiEwhFWsSkDzNN2IE0WfHSksYAALYC8Fkju3TwkGNHX3i3pg94Jk%2Br7vkuHgHr464nlumBNqI%2BhIQUupEKg-rsDQ9CMMK7BcDw-CCGARLen%2BOYRsyBAPpO9piCShBgWyHJdrwv6ISI%2BhAA&eslintrc=N4KABGBEAOCGBOBnApvSAuKABALgT2mUQGN4BLaHAWiIBsyA7HAejiVUgBpwp4BXWkQxhQEbPkIlylGonpNmxAPYNEZRDmRMqE5FTIBbaEvg5EwgNo8xYyKngmu1scCgATdbFq0lAdwAqBMgAggwMSjiwOGQq5pgAZl4ozhAAvs4AujzpqUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDArugDTg2Tsl0AVSIBrIrADuRAJJEAwgEM80ABYA1RY0UAjDGUoduvWiVHJEAGWQ75q9NFGsjPGlABmsTNHTziJZHp0IjwlAKIAczkAMTR0ADlFeHQDNkxOVz4AKxIAD1ZITHRFZgBaHPzM0wYmPHj2VFQ7B1FUlxMoCRkkVCZkPABBIgBPZ3TjNzoa5mj2ImZCIgAVYcQUsYyOqcZmACFkIgATJUaBxERUUcNxqs7Ybou%2BvCXVQI2JvkVUSUVhkgBlaYsa6bSZdHpPABK6Dw7EwpHet0gEgACphYGtMHhhgNoD4SCRouj4HJDuhcv9kBEiMo4ehWO4voIkSkALKwQ4NdByPBYDGIrYCdAAEXQ7gO6GiXnkqEUBNi6FQh1SjNQzK2eC0ERhBRSACYAAyGyBI%2BAcrm6khEcksU3mjDQkiwVDsAjEArxDkJG0mrZk6CyzDKRYCyaBZ3KdCHdmc-ShvgANywOmD8BjXP%2BwxCinyII%2BtHJmOQyWzqFFcCDeC8bRuW3Q8H65a8yi8rJhikOykU8eqOzwaIxWGxcn6yC%2ByAAXsH3ZRVerJl9UFIAFIqpn5u4AUQbwLAc-QvAAviBD0A&tokens=false))
```json
{
  "compilerOptions": {
    "strict": true,
    "useUnknownInCatchVariables": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react-jsx",
    "strictNullChecks": true,
    "noImplicitAny": true,
    "strictFunctionTypes": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noImplicitReturns": true,
    "noPropertyAccessFromIndexSignature": false,
    "esModuleInterop": true,
    "useDefineForClassFields": false,
    "target": "es2020",
    "module": "esnext",
    "moduleResolution": "NodeNext",
    "declaration": true,
    "isolatedModules": true,
    "verbatimModuleSyntax": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictPropertyInitialization": false,
    "allowJs": false,
    "noEmit": false
  }
}
```

So I wonder if somehow the options are not reported to our rule logic when an illegal combination of options is encountered by TS. Are you able to double-check and/or change the options in your project? _If_ this hypothesis is correct, I'm not sure whether it's really actionable for us. But if you're able to repro with an error-free tsconfig, we may be back to the drawing board. Curious for more data here!

**Comment by kirkwaiblinger** [comment]
Specifically, I'm greeted with this complaint: 

> Error: error TS5070: Option '--resolveJsonModule' cannot be specified when 'moduleResolution' is set to 'classic'.
error TS5074: Option '--incremental' can only be specified using tsconfig, emitting to single file or when option '--tsBuildInfoFile' is specified.
error TS5102: Option 'importsNotUsedAsValues' has been removed. Please remove it from your configuration.
  Use 'verbatimModuleSyntax' instead.

**Comment by kirkwaiblinger** [comment]
FWIW - it's also vaguely possible that this is a playground bug since the `moduleResolution` isn't set to 'classic', contrary to the error message??

**Comment by tianyingchun** [comment]
My project statement is as follows type:module nodenext，It works fine locally and doesn't prompt any configuration errors

**Comment by tianyingchun** [comment]
useDefineForClassFields": false,
    "target": "es2020",
    "module": "esnext",
    "moduleResolution": "NodeNext",
    "declaration": true,
    "isolatedModules": true,
    "verbatimModuleSyntax": true,
The configuration above should be fine if you use pure esm

**Comment by kirkwaiblinger** [comment]
> useDefineForClassFields": false, "target": "es2020", "module": "esnext", "moduleResolution": "NodeNext", "declaration": true, "isolatedModules": true, "verbatimModuleSyntax": true, The configuration above should be fine if you use pure esm

If I use literally this, I see the lint error, but, more importantly, I see a TS error, "decorators are not valid here" on the `@Inject`, since legacy decorators are not enabled ([playground](https://typescript-eslint.io/play/#ts=5.6.3&fileType=.ts&code=JYWwDg9gTgLgBAbzgSQHYCsCmBjGAaOGATzEzgHlUBBMMAG2GwEMZgJUAhCCGAZxihMwcAL5wAZlAgg4AcnHdZAbgBQoSLERwAogDdMqGBwCuvAgCVMAR2OZ%2BAYXYxMADxgBlTFF2MyYydJyAEZMUMpq4NDwCCpwcAAKdMYA5sCojiAg7ACyEAAmxnSYeLFwAGoGBVCYiSlpJf5SMrIhAF7hKgACFahVNUmpqAAUMXHqUbwAXHAA2rWDGVmouQVFALolcWBSPnleU7OlcaNxp9sQu5jTsvEAMgCqAOLIAHIA%2Bq-IACpv5PFfyHIL3csk2pzipkwADEmLhoERpkMAJRwAC8AD44AAJEj7TA9PrzNL2KSoAB0EDArHYZiOojBG1K2GkYBYwCCwAYxGu6NRAGYyQAGIWglQiJEqVwaeDYOhMXi8bG4qC8fGVYzVInpUlwdRFEAGPgUai0BjMamcbh8ARCRClfhs7BwSkWg5MVBENFabCk6YzDZwOgQZJ6Q0HcRMOiq0SqJk0gTGOFQIZ0zpoLC4IY3B7Pd6fH5-AFAkES8HbYC6FhkF1sVBuj1grZQCtVuCYfSGEwHUOd0yNuDlyvOODVGx2GCOQyuDxeHzYK5wSxjhxOaeeby%2BUoopB05l1iBFMlB5JDGAAC2AvDJ7cNXaRqnBe94B8wR%2BDp4vV9HthXU7c67nTBS1EFRQLieUiFQJ12BoehGDZdguB4fhBDAZE7UfeNvVJAhjx7I0xFRQhPwpKla14B8QJEFQgA&eslintrc=N4KABGBEAOCGBOBnApvSAuKABALgT2mUQGN4BLaHAWiIBsyA7HAejiVUgBpwp4BXWkQxhQEbPkIlylGonpNmxAPYNEZRDmRMqE5FTIBbaEvg5EwgNo8xYyAHcEDLtbHAoAE3WxatJXYAqBMgAggwMSjiwOGQq5pgAZt4oLhAAvi4AujzpqUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkAriegCLoBmyR6AYrJgMKoAhiRJdk6VABMylVoNSMANOBqQ8gzAHN0eClHQkATAAYTkZTSjxYkuhj2QDnAB66Lq67YwAlA7FR0BMQOAHI26CHoruYqtJLo0EKYgkFEeniYdOjutMgk-inokgCyNnYG6ZnZsVAAblgARinI8KVe6ADKAJ5E6s6VWTUA9EP6zohYLei98ixwyXi8MmAZWTlgI-rwyHhzvCm8xTqCkimCA%2BgqAL4gV0A&tokens=false))

If I add in experimental decorators and decorator metadata, the TS error and lint error go away ([playground](https://typescript-eslint.io/play/#ts=5.6.3&fileType=.ts&code=JYWwDg9gTgLgBAbzgSQHYCsCmBjGAaOGATzEzgHlUBBMMAG2GwEMZgJUAhCCGAZxihMwcAL5wAZlAgg4AcnHdZAbgBQoSLERwAogDdMqGBwCuvAgCVMAR2OZ%2BAYXYxMADxgBlTFF2MyYydJyAEZMUMpq4NDwCCpwcAAKdMYA5sCojiAg7ACyEAAmxnSYeLFwAGoGBVCYiSlpJf5SMrIhAF7hKgACFahVNUmpqAAUMXHqUbwAXHAA2rWDGVmouQVFALolcWBSPnleU7OlcaNxp9sQu5jTsvEAMgCqAOLIAHIA%2Bq-IACpv5PFfyHIL3csk2pzipkwADEmLhoERpkMAJRwAC8AD44AAJEj7TA9PrzNL2KSoAB0EDArHYZiOojBG1K2GkYBYwCCwAYxGu6NRAGYyQAGIWglQiJEqVwaeDYOhMXi8bG4qC8fGVYzVInpUlwdRFEAGPgUai0BjMamcbh8ARCRClfhs7BwSkWg5MVBENFabCk6YzDZwOgQZJ6Q0HcRMOiq0SqJk0gTGOFQIZ0zpoLC4IY3B7Pd6fH5-AFAkES8HbYC6FhkF1sVBuj1grZQCtVuCYfSGEwHUOd0yNuDlyvOODVGx2GCOQyuDxeHzYK5wSxjhxOaeeby%2BUoopB05l1iBFMlB5JDGAAC2AvDJ7cNXaRqnBe94B8wR%2BDp4vV9HthXU7c67nTBS1EFRQLieUiFQJ12BoehGDZdguB4fhBDAZE7UfeNvVJAhjx7I0xFRQhPwpKla14B8QJEFQgA&eslintrc=N4KABGBEAOCGBOBnApvSAuKABALgT2mUQGN4BLaHAWiIBsyA7HAejiVUgBpwp4BXWkQxhQEbPkIlylGonpNmxAPYNEZRDmRMqE5FTIBbaEvg5EwgNo8xYyAHcEDLtbHAoAE3WxatJXYAqBMgAggwMSjiwOGQq5pgAZt4oLhAAvi4AujzpqUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkAriegCLoBmyR6AYrJgMKoAhiRJdk6VABMylVoNSMANOBqQ8gzAHN0eClHQkATAAYTkZTSjxYkuhj2QDnAB66Lq67YwAlA7FR0BMQOAHI26CHoruYqtJLo0EKYgkFEeniYdOjutMgk-inokgCyNnYG6ZnZsVAAblgARinI8KVe6ADKAJ5E6s6VWTn6zohYLei98ixwyXi8MmAZgzWO8Mh407wpvMU6gpIpggPoKgC%2BIKdAA&tokens=false))

**Comment by kirkwaiblinger** [comment]
Actually, the part about "decorators are not valid here" is a red herring; ignore that. But, the point is, if you're not emitting decorator metadata, then... the types in the constructor parameters _are_ only used as types, no?

**Comment by tianyingchun** [comment]
for `@nestjs` it use `reflectMetada` it require us setup 
```json
"experimentalDecorators": true,
 "emitDecoratorMetadata": true,
```

**Comment by kirkwaiblinger** [comment]
> for `@nestjs` it use `reflectMetada` it require us setup 
> ```json
> "experimentalDecorators": true,
>  "emitDecoratorMetadata": true,
> ```

Understood. So what then is the expected and actual behavior here that you see?

My thought right now is: I expect the rule not to report with that config and it does not report.

**Comment by tianyingchun** [comment]
which configuration field of `tsconfig.json` issue you think?

**Comment by kirkwaiblinger** [comment]
I'm wondering if you've read https://typescript-eslint.io/blog/changes-to-consistent-type-imports-with-decorators?

**Comment by tianyingchun** [comment]
```import tseslint from 'typescript-eslint';

export default tseslint.config(
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      parserOptions: {
        emitDecoratorMetadata: true,
        experimentalDecorators: true,
      },
    },
  },
);
```
it works,  but why ? i have configed above fields in `tsconfig.json`

**Comment by kirkwaiblinger** [comment]
> it works,  but why ? 

Again, to help us out, could you be extremely specific about what "works" means, in terms of expected and actual behavior?

I am currently not understanding what expected vs actual behavior this issue is about in the first place.

**Comment by tianyingchun** [comment]
1. add  rules
```ts
  {
    languageOptions: {
      parserOptions: {
        emitDecoratorMetadata: true,
        experimentalDecorators: true,
      },
    },
  },
```
it works correct, the error message 
`Imports "EventBus" and "RequestContextService" are only used as type.eslint[@typescript-eslint/consistent-type-imports](https://typescript-eslint.io/rules/consistent-type-imports)` has gone

2. it not above code, it will give me above error 
3. keep tsconfig.json configs 
```json
"useUnknownInCatchVariables": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react-jsx",
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noPropertyAccessFromIndexSignature": false,
    "esModuleInterop": true,
    "useDefineForClassFields": false,
    "target": "ES2020",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "resolveJsonModule": true,
    "declaration": true,
    "newLine": "lf",
    "strict": true,
    "sourceMap": true,
    "noImplicitAny": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "importsNotUsedAsValues": "remove",
    "verbatimModuleSyntax": true,
    "strictPropertyInitialization": false,
    "noImplicitReturns": false,
    "rootDir": ".",
    "outDir": "dist",
    "isolatedModules": true,
    "baseUrl": "./",
    "allowJs": false,
    "noEmit": false,
    "incremental": true,
    "paths": {}
```. & without `parseOptions` the error will report

**Comment by tianyingchun** [comment]
BTW my tsconfig.json used `extends`  like 
```json
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
....
```

**Comment by kirkwaiblinger** [comment]
Aha! I think I understand a bit better now. I have an idea, but I will need to take a bit of time to play around with this on my computer. Thanks for providing more detail!

**Comment by kirkwaiblinger** [comment]
Btw, I'm assuming from the eslint config that you're _not_ [linting with type information](https://typescript-eslint.io/getting-started/typed-linting), is that correct?

**Comment by tianyingchun** [comment]
i have used like this 
```
    eslint.configs.recommended,
    ...tseslint.configs.recommended

```

**Comment by kirkwaiblinger** [comment]
Ok, makes sense! Here's what I think is happening:

So, without type information being set up, ie via `parserOptions.project` or `parserOptions.projectService` (whether or not any rules requiring type information are actually used), consistent-type-imports  has no way of knowing what's actually in your tsconfig. And it assumes by default that experimentalDecorators and emitDecoratorMetadata are false. Therefore, unless you manually specify those options in your parserOptions, it will report on the types used in the decorator. 

[This caveat is documented here](​​https://typescript-eslint.io/rules/consistent-type-imports#caveat-decorators--experimentaldecorators-true--emitdecoratormetadata-true).

Does that explain what you're seeing?

**Comment by bradzacher** [comment]
Kirk is correct.

If you set `parserOptions.emitDecoratorMetadata` then it changes how the rule functions so it won't report on your files.

If you use type-aware linting then we'll try to automatically infer the `emitDecoratorMetadata` value from your tsconfig.
But if you're not using type-aware linting then we default to off (because most people do not use the flag).

This is outlined in the docs:
https://typescript-eslint.io/rules/consistent-type-imports/#caveat-decorators--experimentaldecorators-true--emitdecoratormetadata-true
