### ISSUE TITLE
Bug: [no-unused-vars] ignore pattern does not work on catch statement

### ISSUE THREAD

**Issue by Sodik** [typescript-eslint/typescript-eslint#10206]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://eslint.org/play/#eyJ0ZXh0IjoiZnVuY3Rpb24gYXJncyhpZ25vcmVkLCBzZWNvbmQpIHtcbiAgXG59XG5cbnRyeSB7XG4gIHZhciBpZ25vcmVkID0gMjtcbiAgdmFyIHRlc3QgPSAzO1xuICBhcmdzKHRlc3QpXG59IGNhdGNoIChpZ25vcmVkKSB7XG4gIFxufSIsIm9wdGlvbnMiOnsicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOlsiZXJyb3IiXSwiZm9yLWRpcmVjdGlvbiI6WyJlcnJvciJdLCJnZXR0ZXItcmV0dXJuIjpbImVycm9yIl0sIm5vLWFzeW5jLXByb21pc2UtZXhlY3V0b3IiOlsiZXJyb3IiXSwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOlsiZXJyb3IiXSwibm8tY2xhc3MtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbXBhcmUtbmVnLXplcm8iOlsiZXJyb3IiXSwibm8tY29uZC1hc3NpZ24iOlsiZXJyb3IiXSwibm8tY29uc3QtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbnN0YW50LWJpbmFyeS1leHByZXNzaW9uIjpbImVycm9yIl0sIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6WyJlcnJvciJdLCJuby1jb250cm9sLXJlZ2V4IjpbImVycm9yIl0sIm5vLWRlYnVnZ2VyIjpbImVycm9yIl0sIm5vLWRlbGV0ZS12YXIiOlsiZXJyb3IiXSwibm8tZHVwZS1hcmdzIjpbImVycm9yIl0sIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6WyJlcnJvciJdLCJuby1kdXBlLWVsc2UtaWYiOlsiZXJyb3IiXSwibm8tZHVwZS1rZXlzIjpbImVycm9yIl0sIm5vLWR1cGxpY2F0ZS1jYXNlIjpbImVycm9yIl0sIm5vLWVtcHR5IjpbIm9mZiJdLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOlsiZXJyb3IiXSwibm8tZW1wdHktcGF0dGVybiI6WyJlcnJvciJdLCJuby1lbXB0eS1zdGF0aWMtYmxvY2siOlsiZXJyb3IiXSwibm8tZXgtYXNzaWduIjpbImVycm9yIl0sIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6WyJlcnJvciJdLCJuby1mYWxsdGhyb3VnaCI6WyJlcnJvciJdLCJuby1mdW5jLWFzc2lnbiI6WyJlcnJvciJdLCJuby1nbG9iYWwtYXNzaWduIjpbImVycm9yIl0sIm5vLWltcG9ydC1hc3NpZ24iOlsiZXJyb3IiXSwibm8taW52YWxpZC1yZWdleHAiOlsiZXJyb3IiXSwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOlsiZXJyb3IiXSwibm8tbG9zcy1vZi1wcmVjaXNpb24iOlsiZXJyb3IiXSwibm8tbWlzbGVhZGluZy1jaGFyYWN0ZXItY2xhc3MiOlsiZXJyb3IiXSwibm8tbmV3LW5hdGl2ZS1ub25jb25zdHJ1Y3RvciI6WyJlcnJvciJdLCJuby1ub25vY3RhbC1kZWNpbWFsLWVzY2FwZSI6WyJlcnJvciJdLCJuby1vYmotY2FsbHMiOlsiZXJyb3IiXSwibm8tb2N0YWwiOlsiZXJyb3IiXSwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjpbImVycm9yIl0sIm5vLXJlZGVjbGFyZSI6WyJlcnJvciJdLCJuby1yZWdleC1zcGFjZXMiOlsiZXJyb3IiXSwibm8tc2VsZi1hc3NpZ24iOlsiZXJyb3IiXSwibm8tc2V0dGVyLXJldHVybiI6WyJlcnJvciJdLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6WyJlcnJvciJdLCJuby1zcGFyc2UtYXJyYXlzIjpbImVycm9yIl0sIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjpbImVycm9yIl0sIm5vLXVuZGVmIjpbImVycm9yIl0sIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjpbImVycm9yIl0sIm5vLXVucmVhY2hhYmxlIjpbImVycm9yIl0sIm5vLXVuc2FmZS1maW5hbGx5IjpbImVycm9yIl0sIm5vLXVuc2FmZS1uZWdhdGlvbiI6WyJlcnJvciJdLCJuby11bnNhZmUtb3B0aW9uYWwtY2hhaW5pbmciOlsiZXJyb3IiXSwibm8tdW51c2VkLWxhYmVscyI6WyJlcnJvciJdLCJuby11bnVzZWQtcHJpdmF0ZS1jbGFzcy1tZW1iZXJzIjpbImVycm9yIl0sIm5vLXVudXNlZC12YXJzIjpbImVycm9yIix7InZhcnNJZ25vcmVQYXR0ZXJuIjoiW2lJXWdub3JlZCIsImFyZ3NJZ25vcmVQYXR0ZXJuIjoiW2lJXWdub3JlZCJ9XSwibm8tdXNlbGVzcy1iYWNrcmVmZXJlbmNlIjpbImVycm9yIl0sIm5vLXVzZWxlc3MtY2F0Y2giOlsiZXJyb3IiXSwibm8tdXNlbGVzcy1lc2NhcGUiOlsiZXJyb3IiXSwibm8td2l0aCI6WyJlcnJvciJdLCJyZXF1aXJlLXlpZWxkIjpbImVycm9yIl0sInVzZS1pc25hbiI6WyJlcnJvciJdLCJ2YWxpZC10eXBlb2YiOlsiZXJyb3IiXX0sImxhbmd1YWdlT3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19

### Repro Code

```TypeScript
function args(ignored, second) {
  
}

try {
  var ignored = 2;
  var test = 3;
  args(test)
} catch (ignored) {
  
}
```

### ESLint Config

```javascript
export default [
    {
        "rules": {
            "constructor-super": [
                "error"
            ],
            "for-direction": [
                "error"
            ],
            "getter-return": [
                "error"
            ],
            "no-async-promise-executor": [
                "error"
            ],
            "no-case-declarations": [
                "error"
            ],
            "no-class-assign": [
                "error"
            ],
            "no-compare-neg-zero": [
                "error"
            ],
            "no-cond-assign": [
                "error"
            ],
            "no-const-assign": [
                "error"
            ],
            "no-constant-binary-expression": [
                "error"
            ],
            "no-constant-condition": [
                "error"
            ],
            "no-control-regex": [
                "error"
            ],
            "no-debugger": [
                "error"
            ],
            "no-delete-var": [
                "error"
            ],
            "no-dupe-args": [
                "error"
            ],
            "no-dupe-class-members": [
                "error"
            ],
            "no-dupe-else-if": [
                "error"
            ],
            "no-dupe-keys": [
                "error"
            ],
            "no-duplicate-case": [
                "error"
            ],
            "no-empty": [
                "off"
            ],
            "no-empty-character-class": [
                "error"
            ],
            "no-empty-pattern": [
                "error"
            ],
            "no-empty-static-block": [
                "error"
            ],
            "no-ex-assign": [
                "error"
            ],
            "no-extra-boolean-cast": [
                "error"
            ],
            "no-fallthrough": [
                "error"
            ],
            "no-func-assign": [
                "error"
            ],
            "no-global-assign": [
                "error"
            ],
            "no-import-assign": [
                "error"
            ],
            "no-invalid-regexp": [
                "error"
            ],
            "no-irregular-whitespace": [
                "error"
            ],
            "no-loss-of-precision": [
                "error"
            ],
            "no-misleading-character-class": [
                "error"
            ],
            "no-new-native-nonconstructor": [
                "error"
            ],
            "no-nonoctal-decimal-escape": [
                "error"
            ],
            "no-obj-calls": [
                "error"
            ],
            "no-octal": [
                "error"
            ],
            "no-prototype-builtins": [
                "error"
            ],
            "no-redeclare": [
                "error"
            ],
            "no-regex-spaces": [
                "error"
            ],
            "no-self-assign": [
                "error"
            ],
            "no-setter-return": [
                "error"
            ],
            "no-shadow-restricted-names": [
                "error"
            ],
            "no-sparse-arrays": [
                "error"
            ],
            "no-this-before-super": [
                "error"
            ],
            "no-undef": [
                "error"
            ],
            "no-unexpected-multiline": [
                "error"
            ],
            "no-unreachable": [
                "error"
            ],
            "no-unsafe-finally": [
                "error"
            ],
            "no-unsafe-negation": [
                "error"
            ],
            "no-unsafe-optional-chaining": [
                "error"
            ],
            "no-unused-labels": [
                "error"
            ],
            "no-unused-private-class-members": [
                "error"
            ],
            "no-unused-vars": [
                "error",
                {
                    "varsIgnorePattern": "[iI]gnored",
                    "argsIgnorePattern": "[iI]gnored"
                }
            ],
            "no-useless-backreference": [
                "error"
            ],
            "no-useless-catch": [
                "error"
            ],
            "no-useless-escape": [
                "error"
            ],
            "no-with": [
                "error"
            ],
            "require-yield": [
                "error"
            ],
            "use-isnan": [
                "error"
            ],
            "valid-typeof": [
                "error"
            ]
        }
    }
];
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

I expected that the 9th line should not report the error "'ignored' is defined but never used"

### Actual Result

There was no error on the 9th line.

**Comment by bradzacher** [comment]
https://eslint.org/docs/latest/rules/no-unused-vars#caughterrorsignorepattern
