### ISSUE TITLE
Bug: [@typescript-eslint/no-unused-vars]  args: after-used is not working for destructured arrays

### ISSUE THREAD

**Issue by Tofandel** [typescript-eslint/typescript-eslint#10214]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.6.2&fileType=.tsx&code=PIIwVgpgxgLgdBAdjATgSwgZwBQG8CGAXAAQBMAvgJRwBmaANjBCttgNoDWANMQG4C6lYgF4AfH2LiAjJSA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tidmUQAmtAG4BDaKgwBtSImjQO0SABpM4bDkoBzTtEQAlFPgDKlAEaMmWyWHxxEy9RshiJASR2LEABVH58ckzoYLzw8I4aOOLWwZCiAGYB0Nz8AipO2HHQ1h66Pn5JQRih8BkAvgC66mUgZUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
Object.entries({a: 2}).filter(([k, v]) => v > 1)
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unused-vars": ["error", {
      "ignoreRestSiblings": true,
      "varsIgnorePattern": null,
      "args": "after-used",
      "argsIgnorePattern": null
    }],
  },
};
```

### Expected Result

No error because of the "args: 'after-used'" option

### Actual Result

'k' is defined but never used. 1:33 - 1:34

**Comment by bradzacher** [comment]
This is working as expected because array destructuring variables are optional. The correct code would be

```ts
Object.entries({a: 2}).filter(([, v]) => v > 1)
```
