### ISSUE TITLE
Configs: fix `TS2629` & `no-class-assign` duplicate

### ISSUE THREAD

**Issue by Rudxain** [typescript-eslint/typescript-eslint#10229]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

I followed [the official instrusctions](https://typescript-eslint.io/getting-started/), but still stumbled upon this ESL rule enabled by default

### Impacted Configurations

`recommended`

### Additional Info

`eslint.config.mjs`:
```js
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
	eslint.configs.recommended,
	...tseslint.configs.recommended,
);
```

`tsconfig.json`:
```json
{
"compilerOptions": {
	"target": "ES2023",
	"skipLibCheck": true
},
"exclude": [ "node_modules" ]
}
```

`package.json`:
```json
{
"name": "tsesl-min-repro",
"version": "0.0.0",
"main": "main.js",
"devDependencies": {
	"@eslint/js": "^9.13.0",
	"@types/eslint__js": "^8.42.3",
	"eslint": "^9.13.0",
	"typescript": "^5.6.3",
	"typescript-eslint": "^8.12.1"
}
}
```

`main.ts`:
```ts
class c { }
c = null
```

`npx eslint .`:
```
/home/rudxain/tsesl-min-repro/main.ts
  2:1  error  'c' is a class                          no-class-assign
  2:1  error  'c' is assigned a value but never used  @typescript-eslint/no-unused-vars

✖ 2 problems (2 errors, 0 warnings)
```

`npx tsc --noEmit`:
```
main.ts(2,1): error TS2629: Cannot assign to 'c' because it is a class.
```

**Comment by auvred** [comment]
This is also [reproducible on playground](https://typescript-eslint.io/play/#ts=5.5.4&fileType=.tsx&code=MYGwhgzhAECC0G8C%2BAoeBeRSg&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQHYHsBaAY3gENllCLkBLAc13SkWmn2knDAF8QegA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false).
