### ISSUE TITLE
Docs: enable `respectPrefersColorScheme` in docusaurus `themeConfig`

### ISSUE THREAD

**Issue by hyoban** [typescript-eslint/typescript-eslint#10237]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Currently, the website's theme does not follow the user's preferences. Every time the user changes their theme preferences, they need to modify the theme settings of the web page manually.

### Affected URL(s)

All URLs in the website

### Additional Info

https://docusaurus.io/docs/api/themes/configuration#color-mode---dark-mode

**Comment by JoshuaKGoldberg** [comment]
Ooh this has been bugging me for a while! +1, I'm in favor 🙂

**Comment by kirkwaiblinger** [comment]
+1
