### ISSUE TITLE
Bug: [no-deprecated] No warnings about usage of deprecated props in JSX components

### ISSUE THREAD

**Issue by alice-ep** [typescript-eslint/typescript-eslint#10275]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.4&fileType=.tsx&code=JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwCwAUI8AHYxZQF5ZwAKxYdAG9GcOAHoECUWKQABACZYwlXMnYKZicTKUqsajfwhgAXHFQworAOb0GAX0aNcEFpbgBhEmcxUYAHQAYp4APMaCAHxwALxwABRCcHqq6lgKEXAOAJSx0fEyoQrAAG4o1sgAtDZQyABGdemRWnAAEsCF4sUlzQzZ9i5uHsgsEDAAFhwAogAeyOAANjxxod7gycqpRgIxAEQQ43CjuxKRNEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oBNFjpEZAIb5E3dFADuQ6E0jgwAXxCKgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
import * as React from 'react';

interface Props {
  /**
   * @deprecated
   */
  deprecatedProp: string;
}

const Comp: React.FC<Props> = ({ deprecatedProp }) => (
  <div aria-grabbed>
    Hi
  </div>
);

const anotherExample = <Comp deprecatedProp="oh no" />;
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/no-deprecated": "warn"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

I expect to see a warning for the line that uses 'aria-dragged' and for the last line.

### Actual Result

No warnings, though TypeScript does recognize the deprecation.

### Additional Info

fwiw, seems like this was an issue in eslint-plugin-deprecated too. Someone tried to solve this separately (I haven't checked if it works): https://github.com/sebakerckhof/eslint-plugin-deprecated-jsx-props

**Comment by JoshuaKGoldberg** [comment]
Note that this isn't specific to React; it's all JSX libraries.
