### ISSUE TITLE
Docs: Update project license to explicitly say BSD-2-Clause

### ISSUE THREAD

**Issue by bryan-yager** [typescript-eslint/typescript-eslint#10280]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

•	Npm states that @typescript-eslint/parser uses the BSD-2-Clause license (https://www.npmjs.com/package/@typescript-eslint/parser)
•	The GitHub license has similar text (it appears to be cut-and-pasted from another project) but does not explicitly state BSD-2-Clause (https://github.com/typescript-eslint/typescript-eslint?tab=License-1-ov-file#readme)

Please correct your GitHub license file to explicitly be the BSD-2-Clause to assist with automated pipelines that rely on having an authoritative license for approval.

### Affected URL(s)

https://github.com/typescript-eslint/typescript-eslint?tab=License-1-ov-file#readme

**Comment by JoshuaKGoldberg** [comment]
👍 the license file is many years old and comes from a time before automated pipelines were common. I think it'd be reasonable to switch it to explicitly indicate it's [BSD-2-Clause](https://opensource.org/license/bsd-2-clause).

Here's what GitHub creates for a license when you go through the new repo flow at https://github.new:

```md
BSD 2-Clause License

Copyright (c) 2024, Josh Goldberg ✨

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

**Comment by bryan-yager** [comment]
Sounds good. Is there any additional action needed from me?

**Comment by JoshuaKGoldberg** [comment]
You could send the PR if you want 🙂

**Comment by bradzacher** [comment]
All of our new packages are MIT licensed.
Do we think it's about time to switch?

Back in the day when I took ownership of the projects I didn't like the licence, but I never bothered switching it becuase I wasn't sure about the implications of changing the licence, and I didn't care enough to bother investigating and learning. But now I know it's fine for us to change it if we want.

I'd like to propose that we just change all licenses to MIT.

**Comment by JoshuaKGoldberg** [comment]
I'd be up for that as a separate investigation, yeah. There's process to be done about relicensing existing code -especially from contributors- we'll need to follow.
