### ISSUE TITLE
I can't install the latest typescript/eslint on node 20.5.1

### ISSUE THREAD

**Issue by deser** [typescript-eslint/typescript-eslint#10331]
### Suggestion

When Im trying to install @typescript/eslint on node 20.5.1 I'm getting next error:
`error @typescript-eslint/eslint-plugin@8.14.0: The engine "node" is incompatible with this module. Expected version "^18.18.0 || ^20.9.0 || >=21.1.0". Got "20.5.1"`

I don't think there's a big difference between 20.5.1 and 20.9.0 versions of node affecting work of @typescript/eslint.
So, I think it makes sense to set expect version for any node higher 18.
And yes, I can't update my nodejs for now.

**Comment by bradzacher** [comment]
This is expected and mirrors ESLint's requirements
https://github.com/eslint/eslint/blob/fd33f1315ac59b1b3828dbab8e1e056a1585eff0/package.json#L217

The difference is that v20.9.0 is the first "LTS" version.
You can read more about their reasoning here: https://github.com/eslint/eslint/issues/17595

**Comment by bradzacher** [comment]
You can always try it with an older version using your package manager's engine checks opt-out.
But we provide no warranty for crashes caused by an older version

**Comment by deser** [comment]
So, the choice was based on just "this is the latest version we've got at the moment doing this"...
