### ISSUE TITLE
Bug: [@typescript-eslint/no-empty-function]  Cannot read properties of undefined (reading 'allow')

### ISSUE THREAD

**Issue by justnewbee** [typescript-eslint/typescript-eslint#10340]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://github.com/justnewbee/kcuf/tree/publish

### Repro Code

```TypeScript
Any TS file
```

### ESLint Config

```javascript
https://github.com/justnewbee/kcuf/blob/publish/packages-config/eslint-config/config-ts.js

used `eslintTs.configs.stylistic`
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "esnext",
      "dom"
    ],
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "strict": true,
    "skipLibCheck": true,
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "noUncheckedIndexedAccess": true,
    "declaration": true,
    "jsx": "react-jsx",
    "sourceMap": true,
    "baseUrl": "./",
    "outDir": "lib"
  }
}
```

### Expected Result

No Error

### Actual Result

 Cannot read properties of undefined (reading 'allow')

### Additional Info

Just updated eslint from 9.14.0 to 9.15.0, the bug only exists after the upgrade, I have to use version 9.14.0 explicitly to avoid this issue.

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/10338
