### ISSUE TITLE
Rule proposal: `no-redundant-destructuring`

### ISSUE THREAD

**Issue by OlivierZal** [typescript-eslint/typescript-eslint#10351]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Destructuring arguments can make code intentions clear, but sometimes it leads to unnecessary verbosity and complicates maintenance.

### Example where the rule would apply

Consider the following:

```ts
interface Config {
  propA: string;
  propB: number;
  propC: boolean;
}

function someFunction({ propA, propB, propC }: Config): void {
  // Function implementation
}
```

You might have:

```ts
function someOtherFunction({ propA, propB, propC }: Config): void {
  someFunction({ propA, propB, propC });
}
```

This can be more succinctly rewritten as:

```ts
function someOtherFunction(config: Config): void {
  someFunction(config);
}
```

By passing the entire config object directly, you **reduce redundancy and make the code easier to read, understand and maintain**. If the `Config` interface changes (e.g. adding or removing a property), you won’t need to update the parameter list in multiple places.

Suppose the `Config` interface is updated to include an additional property:

```ts
interface Config {
  propA: string;
  propB: number;
  propC: boolean;
  propD: Date;
}
```

By passing the entire config object, your function signatures remain unchanged:

```ts
function someFunction(config: Config): void {
  // New function implementation
}

function someOtherFunction(config: Config): void {
  someFunction(config);
}
```

This approach enhances maintainability since you don’t need to modify each function that uses `Config` when the interface changes.

### Examples where this rule wouldn't apply

However, the following examples cannot be rewritten in the same way, since destructuring remains appropriate:

```ts
function someOtherFunction({ propA, propB, propC }: Config): void {
  anotherFunction(propA); // Destructuring is necessary here
  someFunction({ propA, propB, propC });
}

function someOtherFunction({ propA, propB, propC }: Config): void {
  someFunction([propA, propB, propC]); // Can't directly infer from `config: Config`
}

function displayConfig({ propA, propC }: Config): void {
  console.log(`A: ${propA}, C: ${propC}`);
}

function sendWelcomeEmail({ email, name }: User): void {
  emailService.send(email, `Welcome, ${name}!`);
}
```

### Example where this rule _could_ apply:

If `someFunction` accepts multiple arguments:

```ts
function someFunction(argA: string, argB: number, argC: boolean) {
  // Function implementation
}
```

you could use rest parameters, but with some clarity loss:

```ts
function someOtherFunction(args: Config): void {
  someFunction(...args)
}
```

### Fail Cases

```TypeScript
interface User {
  id: number;
  name: string;
  email: string;
}

function updateUser({ id, name, email }: User): void {
  database.update({ id, name, email });
}

/* With `{ enforceRestParameters: true }` */

function someFunction(id: number, name: string, email: string) {
  // Function implementation
}

function someOtherFunction({ id, name, email }: User): void {
  someFunction(id, name, email)
}
```

### Pass Cases

```TypeScript
interface User {
  id: number;
  name: string;
  email: string;
}

function updateUser(user: User): void {
  database.update(user);
}

function someOtherFunction({ propA, propB, propC }: Config): void {
  anotherFunction(propA);
  someFunction({ propA, propB, propC });
}

function someOtherFunction({ propA, propB, propC }: Config): void {
  someFunction([propA, propB, propC]);
}

function displayConfig({ propA, propC }: Config): void {
  console.log(`A: ${propA}, C: ${propC}`);
}

function sendWelcomeEmail({ email, name }: User): void {
  emailService.send(email, `Welcome, ${name}!`);
}

/* With `{ enforceRestParameters: true }` */

function someFunction(id: number, name: string, email: string) {
  // Function implementation
}

function someOtherFunction(args: User: void {
  someFunction(...args)
}
```

**Comment by kirkwaiblinger** [comment]
Hi @OlivierZal !

Wouldn't this apply to JS in general, not just TS?

**Comment by OlivierZal** [comment]
Hi @kirkwaiblinger, I also was wondering but I think the approach should be type-related, since it's about handling objects with interfaces, and not only about raw objects.

I should have added this additional example (and I will):

```ts
function someOtherFunction({ propA: string, propB: string, propC: string }): ExtendedConfig): void {
  someFunction({ propA: string, propB: string }) // `Config`, extended by `ExtendedConfig` with additional `propD`
```

should also raise an error

**Comment by OlivierZal** [comment]
Yes, I thought about some unsafety if not relying on types (I edited my previous comment while you were replying), but you're right:
I'll rather propose this rule to `eslint`, with eventual extension for typescript if approved.

**Comment by kirkwaiblinger** [comment]
> Yes, I thought about some unsafety if not relying on types (I edited my previous comment while you were replying), but you're right: I'll rather propose this rule to `eslint`, with eventual extension for typescript if approved.

Yeah, I mean, I guess my more helpful thought is - in _both_ the TS and JS case, you'd probably want an option "enforceForExcessProperties". So the type information value-add still seems really marginal at best. Good luck with your proposal!

**Comment by Josh-Cena** [comment]
Definitely not new. Anything with stable browser implementations can be considered mature enough.

**Comment by OlivierZal** [comment]
Thanks @Josh-Cena, that is what I was thinking. Since the eslint new rule creation template requests to create an issue _only for "new ECMAScript feature"_, I didn't create it. Despite that, I was wondering if the rule proposal could be interesting and is worth being created though.

**Comment by Josh-Cena** [comment]
I personally don't think it's useful enough in general because it hinders future code addition that may use these variables, but ESLint already has several rules like that. So I would give it a try. eslint-plugin-unicorn may also be a good place to propose this.

**Comment by OlivierZal** [comment]
I agree about hinders: that's why I thought that something interface/type-related is more robust and could have its place in typescript-eslint. But I agree with all the arguments of the discussion.
