### ISSUE TITLE
Bug: "unsafe member access" errors when using exposed methods from Vue's template `ref`s

### ISSUE THREAD

**Issue by paveloom** [typescript-eslint/typescript-eslint#10359]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

This issue was moved from https://github.com/vuejs/core/issues/12433. It is specific to [Vue](https://vuejs.org), but *might be* coming from `typescript-eslint`. 

See the reproduction steps below. Here are the relevant source code files:

<details>
<summary><code>App.vue</code></summary>
<br>

```vue
<script setup lang="ts">
import { useTemplateRef } from "vue";

import Modal from "@/components/Modal.vue";

const modal = useTemplateRef<InstanceType<typeof Modal>>("modal");

function close() {
  modal.value?.close();
}
</script>

<template>
  <button @click="modal?.open!">
    Open modal
  </button>
  <button @click="close">
    Close modal
  </button>
  <Teleport to="body">
    <Modal ref="modal" />
  </Teleport>
</template>
```
</details>

<details>
<summary><code>Modal.vue</code></summary>
<br>

```vue
<script setup lang="ts">
import { ref } from "vue";

const isOpen = ref(false);

function open() {
  isOpen.value = true;
}

function close() {
  isOpen.value = false;
}

defineExpose({
  open,
  close
});
</script>

<template>
  <div v-if="isOpen">
    Modal
  </div>
</template>
```
</details>

The intent is to use the exported functions from an instance of the `Modal` component whenever needed. For that, I use Vue's [`useTemplateRef`](https://vuejs.org/api/composition-api-helpers.html#usetemplateref) function and the [`defineExpose`](https://vuejs.org/api/sfc-script-setup.html#defineexpose) compiler macro.

While running the lint script, I get the following errors:

```
src/components/App.vue
  9:3   error  Unsafe call of a(n) `any` typed value          @typescript-eslint/no-unsafe-call
  9:16  error  Unsafe member access .close on an `any` value  @typescript-eslint/no-unsafe-member-access
```

Note that there are two functions exported from the `Modal` component, namely, `open` and `close`. However, I use these functions differently in the `App` component. The `open` method is used directly in the `template` section, whereas for the `close` function I've created a wrapper of the same name in the `script setup` section. Note that the error of using an `any` value is reported only on the wrapper (specifically, on the call `modal.value?.close()`).

This issue is also eerily similar to https://github.com/vuejs/core/issues/6882.

### Reproduction Repository Link

https://github.com/paveloom-o/vue-playground/tree/use-template-ref

### Repro Steps

1) `git clone --branch use-template-ref https://github.com/paveloom-o/vue-playground.git`
2) `cd vue-playground`
3) `direnv allow` (OPTIONAL: if you have [`direnv`](https://direnv.net) and [`nix-direnv`](https://github.com/nix-community/nix-direnv) installed)
4) `npm install`
5) `npm run lint`

### Versions

vue-playground@
├── @eslint/js@9.15.0
├── @tsconfig/strictest@2.0.5
├── eslint-plugin-vue@9.31.0
├── eslint@9.15.0
├── typescript-eslint@8.15.0
├── typescript@5.6.3
├── vue-eslint-parser@9.4.3
├── vue-tsc@2.1.10
└── vue@3.5.13

Node: `23.1.0`

**Comment by bradzacher** [comment]
This is expected, I believe.
Because Vue doesn't use import/export semantics TS cannot analyse it by default and instead requires additional tooling from Vue to make it work.

You should have a chat to the Vue parser maintainers about this - there's likely existing issues on their repo or information about how to fix it in their docs.

Sorry if it sounds like in brushing you off - but we do not support custom languages and frameworks - adding handling for them and providing advice and support is up to the authors of the language/framework.

https://github.com/vuejs/vue-eslint-parser
