### ISSUE TITLE
Bug: prefer-nullish-coalescing Alerts when using optional booleans

### ISSUE THREAD

**Issue by moshest** [typescript-eslint/typescript-eslint#10356]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.6.2&fileType=.tsx&code=MYewdgzgLgBADgJxHCAuGBvAUDGAbEAQwBMBLMAcwH50AjEEPAU0LAG4cYyJDbniaMeoxbssAXxgBeTOI5ZQkWN179p8JCgB0Kvk2IwAPoY3IIWgiXIU2QA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WlqYSNkAC1pkA9gEMkyMswDm6KL2jjokcGAC%2BILUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
const props: {
  loading?: boolean;
  disabled?: boolean;
} = {};

const disabled = props.disabled || props.loading;
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/prefer-nullish-coalescing": "error",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
     "strictNullChecks": true
  }
}
```

### Expected Result

I expect the `||` to be allowed.

### Actual Result

Lint error to replace `||` with `??` which can produce a bug if `disabled = false` and `loading = true`

### Additional Info

```ts
undefined ?? true === true
false ?? true === false
```

**Comment by bradzacher** [comment]
https://typescript-eslint.io/rules/prefer-nullish-coalescing#ignoreprimitives

Specifically `ignorePrimitives: {boolean: true}` would be the behaviour you might like.

**Comment by kirkwaiblinger** [comment]
Related to https://github.com/typescript-eslint/typescript-eslint/issues/9080

You can ignore it with 

[Playground](https://typescript-eslint.io/play/#ts=5.6.2&fileType=.tsx&code=MYewdgzgLgBADgJxHCAuGBvAUDGAbEAQwBMBLMAcwH50AjEEPAU0LAG4cYyJDbniaMeoxbssAXxgBeTOI5ZQkWN179pMAEINmrABSJkEAHQq%2BTYjAA%2Bl%2BEhRGCJchQCUbIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WlqYSNkAC1pkA9gEMkyMswDm6MAG1IvaOOiQANJnDYcleU02IAQuPFJJTAMLjec8UyX44ifRAC%2BAXX1eQLyA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

### Code

```ts
const props: {
  loading?: boolean;
  disabled?: boolean;
} = {};

const disabled = Boolean(props.disabled || props.loading);
```

### Eslint config

```json
{
  "rules": {
    "@typescript-eslint/prefer-nullish-coalescing": ["error", {
      "ignoreBooleanCoercion": true
    }]
  }
}
```

**Comment by moshest** [comment]
I would like to see `ignorePrimitives: {boolean: true}` as the default behavior.

Replacing `x || y` with `x ?? y` should only be suggested when `x` is `true | null | undefined` and never for `boolean | null | undefined`.

**Comment by bradzacher** [comment]
`(x ?? false) || (y ?? false)` is a valid fix for this which also eliminates the `null | undefined` to `boolean` coercion.

The exact fix and code style is up to you, the user -- which is why the rule has a number of configuration options so that you can control the cases that are flagged
All of the options are documented in the rule's docs.

**Comment by Josh-Cena** [comment]
This suggestion has been brought up multiple times over the years, but the rule only really forces you to consider correct behaviors, which the current one may or may not been. The more errors it gives, the more bugs it may potentially catch, at the expense of more noise.
