### ISSUE TITLE
Rule proposal: no-function-length

### ISSUE THREAD

**Issue by omril1** [typescript-eslint/typescript-eslint#10382]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

It's possible to misuse `.length` when working with functions by forgetting to invoke the function before accessing its `.length` property.
This leads to subtle bugs because the `.length` property of a function returns the number of expected parameters, not the length of the result of the function call.
This mistake can lead to logical errors that are often hard to spot during code reviews or debugging sessions. A rule like no-function-length would prevent these mistakes by ensuring that .length is not accessed directly on functions.

### Fail Cases

```TypeScript
const getArray = () => [1, 2, 3];

if (getArray.length > 0) {
  console.log('Non-empty array');
}

const union = Math.random() > 0.5 ? [1, 2, 3] : getArray;
if (union.length) {
  console.log('Oops');
}
```

### Pass Cases

```TypeScript
const getArray = () => [1, 2, 3];

if (getArray().length > 0) {
  console.log('Non-empty array');
}
```

### Additional Info

Use cases include:

* Preventing bugs in projects with frequent use of higher-order functions or functions returning collections.
* Helping developers unfamiliar with JavaScript's .length behavior avoid subtle pitfalls.

I'm not sure if this rule should be on by default in a preset, but from my experience it's geared more towards less experienced developers from making the mistake, as they are less likely to need the property for meta-programming/reflection.

The mistake can also be indirect, like when using React's `useMemo` and `useCallback` incorrectly.

The rule requires TypeScript type information to differentiate between:
* Functions that are being accessed incorrectly.
* Objects or arrays where .length usage is valid.

**Comment by bradzacher** [comment]
> Many developers

Anecdotally this is literally the first time I've ever heard of this bug vector.

> Objects or arrays where .length usage is valid

This is _usually_ only arrays

---

My gut reaction to this is no because the bug vector is very niche and the rule would be VERY expensive -- you'd need to check every single `.length` access to see if it's on a function AND that that function returns something with `.length`.

cc @typescript-eslint/triage-team

**Comment by JoshuaKGoldberg** [comment]
> > Many developers
>
> Anecdotally this is literally the first time I've ever heard of this bug vector.

Same, I've only ever maybe vaguely heard of this being a possibility before. I've never seen it mistakenly done in practice.

I like the idea of the rule but agree with Brad that it seems very expensive for what it gives. My vote is to put it under `evaluating community engagement` for a while to see if a lot of folks want it.

**Comment by omril1** [comment]
Yeah, I agree that it's not that common, I shouldn't have written many

**Comment by Josh-Cena** [comment]
I would like to see a general rule called `no-restricted-instance-properties` that allows you to configure what property names should be banned when they  are accessed on the specified types.

**Comment by omril1** [comment]
Forgetting to call a function before using it is something that the typescript team did address in a few updates like in [3.9](https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/#uncalled-function-checks-in-conditional-expressions) they added "did you mean to call this function" in conditional expressions or "did you forget to use 'await'" in [4.3](https://devblogs.microsoft.com/typescript/announcing-typescript-4-3/#always-truthy-promise-checks).

I think this fits this sort of errors, but it doesn't fully fit to be part of the language because of false positives where you do want to use a function's length, it's more of a linter's role IMO.

**Comment by omril1** [comment]
> I would like to see a general rule called `no-restricted-instance-properties` that allows you to configure what property names should be banned when they are accessed on the specified types.

Do you have some examples? from the top of my head I can think of a function's name or the windows global name being used by accident, but not much more.

For most unwanted properties it's possible to mark as deprecated but in case of functions I don't think it's correct

**Comment by Josh-Cena** [comment]
Yeah that is in fact true—you can take advantage of `no-deprecated` to do this already. And I don't see how "forbid all accesses of Function.length" is different from "mark Function.length as deprecated (i.e. you should not use it)".

**Comment by bradzacher** [comment]
My 2c would be to just patch the `Function` type in TS itself and delete the entire property rather than just deprecate it.

**Comment by JoshuaKGoldberg** [comment]
I find it interesting that [`Function length` is not deprecated per MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length). The docs don't even recommend against it! It's just a good example of a _"why would you want to...?"_.

Closing out this specific request as a wontfix. But if someone wants to advocate for a more broad _"don't use these weird things"_ rule -perhaps with our standard [`TypeOrValueSpecifier` format](https://typescript-eslint.io/packages/type-utils/type-or-value-specifier)?- that would be an interesting separate discussion.

Cheers!
