### ISSUE TITLE
Rule proposal: `no-unnecessary-type-predicate`

### ISSUE THREAD

**Issue by elliotleelewis** [typescript-eslint/typescript-eslint#10398]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I think there would be value in having a rule to avoid extra type-predicate checks when they're not necessary. This can help clean up type-predicates around a repo as types are changed, and also avoid unnecessary CPU cycles at runtime.

This rule would work similarly to [`no-unnecessary-type-assertion`](https://typescript-eslint.io/rules/no-unnecessary-type-assertion).

### Fail Cases

```TypeScript
const test: "foo" = "foo";

const isFoo = (text: string): text is "foo" => {
    return text === "foo";
}

// Should error here: at compile time we know the else branch will never get hit
if (isFoo(test)) {
    console.log("FOO!");
} else {
    console.log("BAR!");
}
```

### Pass Cases

```TypeScript
const test: string = "bar";

const isFoo = (text: string): text is "foo" => {
    return text === "foo";
}

// Shouldn't error here: at compile time we cannot know if the else branch will be hit, and so the predicate usage makes sense.
if (isFoo(test)) {
    console.log("FOO!");
} else {
    console.log("BAR!");
}
```

**Comment by kirkwaiblinger** [comment]
[This exists](https://typescript-eslint.io/play/#ts=5.7.2&fileType=.ts&code=N4KABGD0lgZghgSwDZgMbwM4FNzoPYB2mALmCdqQFxgBEs%2B%2BtYAvHQ0wNwh5pGlhEmAGKNWYABQUAHiRqkATokIBzAJQ0ZZIe0bMWAPjCgIEBdhIBXBYXLZZrFm3p7uEAL48I0MAGUAFviWyAAmYNgKCvgKYP4R2DTwZHwAtgAOKNjkiClZAO5ZANaE%2BHnkceHIOGAARgrwhGj%2BYHkoqITYAG4RYCoWsYgkeIiwkkKi%2BFKUJGpqxngQfMT4yNgAdMj4KhK0wgDyewCEtGpuYO6V1SamS5gr65vbtABCAIIASseneJ6eINc%2BNJYTDoLCUXj8MgUahgRTKFTiWg1eAKWjcCHEbQiMRsKayeQkJSqDR2Bw6FxMVhGa5mCzWWxaRzODhon5eKAwAJBUKEADkZAiURicXMiWS%2BHSmWyuRaWQwhBKZGKpUEoxIFWwVSydQaTRabVqWX8gwANGAGmE7uUsmlzCFEBgKGBLJh4H0wCl4IVKLDsMR1sNRhJxowpqRZvNTARlqsNlsdvsjiczhdNVcFtG7rHHjs3p9k2yQO4gA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRgA2uGw5E0aB2iQANKrVY12SGQAW-ANYAVEogAK0RDLJD8KRfjiID2AL6%2BALqqAX5AA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)! 😁 

See https://typescript-eslint.io/rules/no-unnecessary-condition#checktypepredicates, https://github.com/typescript-eslint/typescript-eslint/pull/10009

**Comment by elliotleelewis** [comment]
Oh sweet, this is awesome stuff. I completely missed that. Thank you! You guys rock 🙏

**Comment by kirkwaiblinger** [comment]
Your kindness is appreciated! 🙂 

Note that the implementation of `checkTypePredicates` is rather conservative for now, so if you think deeply about this and find more cases that you think should be checked, do feel free to submit new issues! 🙂
