### ISSUE TITLE
Rule proposal: `no-dynamic-ts-file-import`

### ISSUE THREAD

**Issue by OlivierZal** [typescript-eslint/typescript-eslint#10393]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [x] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

TypeScript 5.7 provides a new tsconfig option `rewriteRelativeImportExtensions`, so now we can do:

```ts
import { something } from './somewhere.ts'
import { something } from './somewhere.mts'
import { something } from './somewhere.cts'
```

instead of:

```ts
import { something } from './somewhere.js'
import { something } from './somewhere.mjs'
import { something } from './somewhere.cjs'
```

However, dynamic imports are still looking for transpiled files, so that prohibiting typescript extensions (`.ts`, `.mts`, `.cts`) could prevent from issues which would appear only at run time.

### Fail Cases

```TypeScript
await import('./somewhere.ts')
await import('./somewhere.mts')
await import('./somewhere.cts')
```

### Pass Cases

```TypeScript
await import('./somewhere.js')
await import('./somewhere.mjs')
await import('./somewhere.cjs')
```

**Comment by bradzacher** [comment]
https://typescript-eslint.io/troubleshooting/faqs/general#how-can-i-ban-specific-language-feature

You can leverage `no-restricted-syntax` for this.
It's dependent on your runtime/bundler as to whether this is supported so we won't be building this as a general-purpose rule.

**Comment by OlivierZal** [comment]
Sounds better indeed, thanks!

**Comment by bradzacher** [comment]
Note that I think this should be handled by [TS 5.7's new `rewriteRelativeImportExtensions` compiler option](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/#path-rewriting-for-relative-paths)

But it looks like it's broken: https://github.com/microsoft/TypeScript/issues/60599
