### ISSUE TITLE
Enhancement: [no-unnecessary-condition] improve error message for statically analyzable literal type comparisons again

### ISSUE THREAD

**Issue by kirkwaiblinger** [typescript-eslint/typescript-eslint#10455]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-unnecessary-condition/

### Description

I've thought more about the error message change in https://github.com/typescript-eslint/typescript-eslint/issues/9643 / https://github.com/typescript-eslint/typescript-eslint/pull/10194, and I'm not happy with the current error message (changed in #10194). 

'Unnecessary conditional, comparison is always {{trueOrFalse}}. Both sides of the comparison always have a literal type.' is more helpful than the prior message was, yes, but it doesn't fully explain what we're flagging to the user. 

I propose we change it to 'Unnecessary conditional, comparison is always {{trueOrFalse}}, since `{{left}} {{operator}} {{right}}` is {{trueOrFalse}}.', so that something like `if (expressionResultingInMinus55 < expressionResultingIn23) {}` will report an error as 'Unnecessary conditional, comparison is always true, since `-55 < 23` is true.'. 

This would IMO make it clearer _what_ types we're seeing and _why_ that indicates the expression has a constant value, helping the user assess whether the types are correct before resolving the complaint.

I have successfully implemented this in https://github.com/typescript-eslint/typescript-eslint/pull/10454 and I find the reports to be a big improvement when experimenting with it in the playground.

### Fail

```TypeScript
// unnecessary condition; 1 === 2 is false
if (1 === 2) {}


declare const expressionResultingIn23: 23;
declare const expressionResultingInMinus55: -55;

// unnecessary condition; -55 < 23 is true.
if (expressionResultingInMinus55 < expressionResultingIn23) {}
```

### Pass

```TypeScript
n/a
```

### Additional Info

cc @StyleShit

**Comment by JoshuaKGoldberg** [comment]
I like this, +1!

IMO being clear and specific is almost always preferable.

**Comment by StyleShit** [comment]
I like it!
+1 from me 🚀
