### ISSUE TITLE
Configs: <a short description of my proposal>

### ISSUE THREAD

**Issue by pir0zh0k** [typescript-eslint/typescript-eslint#10468]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

Initialized the config for vue 3 and TypeScript, but ran into a problem.

For some reason, linter writes that "interface reserved", I searched for a solution to the problem on many sites, but I never found it.
![image](https://github.com/user-attachments/assets/69cd8bfb-d081-4780-9a22-9dce8186352e)

### Impacted Configurations

`
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";
import pluginVue from "eslint-plugin-vue";
import eslintConfigPrettier from "eslint-config-prettier";

/** @type {import('eslint').Linter.Config[]} */
export default tseslint.config(
    pluginJs.configs.recommended,
    tseslint.configs.recommendedTypeChecked,
    tseslint.configs.stylisticTypeChecked,
    ...pluginVue.configs["flat/essential"],
    eslintConfigPrettier,
    {
        plugins: {
            "@typescript-eslint": tseslint.plugin,
        },
        files: ["/resources/js/**/*.{js,ts,vue}"],
        languageOptions: {
            parserOptions: {
                parser: tseslint.parser,
                projectService: true,
                tsconfigRootDir: import.meta.dirname,
            },
        },
    },
    {
        rules: {
            "vue/multi-word-component-names": "off",
            "no-unused-vars": "error",
            "prefer-const": ["error", {ignoreReadBeforeAssign: true}],
            "no-useless-escape": "off",
        },
    },
);

`

**Comment by JoshuaKGoldberg** [comment]
👋 Hi! This looks like a _request for help_, not an _issue with typescript-eslint_. By "issue" we mean "something missing or wrong in the code of the typescript-eslint project". 

We don't use GitHub issues for support requests. Please see https://typescript-eslint.io/contributing/issues#questions-and-support-requests for options that'll work for you.

Btw, for when you do use GitHub issues, you'll want to:

* Fill in the title. The default _"a short description of my proposal"_ is not very information
* Use [Markdown code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to make the code easier to read

Cheers!
