### ISSUE TITLE
Bug: [no-unnecessary-condition] regression with types that include `undefined` under noUncheckedIndexedAccess

### ISSUE THREAD

**Issue by controversial** [typescript-eslint/typescript-eslint#10509]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.4&fileType=.tsx&code=C4TwDgpgBAysD2AnaBeKBvAUFKEB2wiAlhAM4D8AXFAEoQDGSAJgDymFF4DmANBlADMArnnoAKAJTUAbvCJMoAXwB8AbkyL1mRnnZR4AIwBW1OElQZsuAsTLUsOHPkIgAjPcEjxEjIqU8rRQDNTEwAejCoIVJOLn0wYCJ4PABDABsoegALFM5YwXTSCDSQKDBEeCYhejIoPHgAWhE8BjJSFMQQBp0mIkTkykxDIwA6Z1sKMZs3chHhUUl1R2XHCKgAPXIrFdXI%2BuBoYCzoZFJ4NOkIBVBIKE56NKEmWoAfKLxngU4r7Z2ocMiEEueCgR3gQi4WX0AFs%2BoluKDjvF%2BqkMtlcnh8kRSFAUqDwNAIIgKohBsMphwyLNxm45l5FpggA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRRE0aB2iRwYAL4gtQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDArugDTg2RGwAqkWgALdNADW6ACYBJIjPQAPWQEFo0dCTKUO6XgF8QhoA&tokens=false

### Repro Code

```TypeScript
type Store = {
  entries?: Record<string, { func(): void }>;
};

const obj: Store = {
  entries: {
    entry1: { func() {} },
  },
};

// using optional chaining falsely produces no-unnecessary-condition:
obj.entries?.entry1?.func();
// even though the type of the `entry1` property includes undefined

// but omitting the optional chaining produces a type error:
obj.entries?.entry1.func();
// 18048: 'obj.entries.entry1' is possibly 'undefined'.
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/no-unnecessary-condition": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strict": true,
    "noUncheckedIndexedAccess": true
  }
}
```

### Expected Result

I expected *not* to see a `noUncheckedIndexedError` when performing property access on a nested, possibly-undefined value

### Actual Result

no-unnecessary-condition raises an error on the optional chain in the last property access, even though using standard (non-optional) property access raises a type error (see playground) 

### Additional Info

This example worked correctly in 8.18.0 (before #10460)

**Comment by yeonjuan** [comment]
Should this be changed to always allow optional chaining when accessing a record or index signature as above?

**Comment by controversial** [comment]
> Should this be changed to always allow optional chaining when accessing a record or index signature as above?

for a record, the “unnecessary condition” in this case is one step beyond accessing the record—the optional chain in `myRecord.key?.key2`, because `myRecord.key` is possibly undefined.

However,`myRecord.key` is **only** considered possibly undefined when `noUncheckedIndexedAccess` is set. In my opinion, it’s *not* obvious that the rule should allow optional chaining in this case absent `noUncheckedIndexedAccess`, because the type of `myRecord.key` will not include `undefined`, so the “condition” *will* be unnecessary.

Without `noUncheckedIndexedAccess`, this optional chain is an unnecessary condition:
<img width="1000" alt="Screenshot 2024-12-17 at 11 55 22 AM" src="https://github.com/user-attachments/assets/69653239-2547-4904-aad6-94b2db697b3c" />
but *with* `noUncheckedIndexedAccess`, this optional chain is *not* an unnecessary condition:
<img width="1149" alt="Screenshot 2024-12-17 at 11 56 47 AM" src="https://github.com/user-attachments/assets/ac1fb366-4f9e-40dd-a430-4288cb6e6a3a" />

So I think this case *should* be a `no-unnecessary-condition` error when `noUncheckedIndexedAccess` is false, but *should not* be a `no-unnecessary-condition` error when `noUncheckedIndexedAccess` is true

**Comment by controversial** [comment]
@yeonjuan you beat me to the punch with your edit while I was writing my message!

I agree with you.
