### ISSUE TITLE
Bug: huge memory consumption

### ISSUE THREAD

**Issue by KostyaTretyak** [typescript-eslint/typescript-eslint#10516]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-eslint

### Repro steps

I have [an open-source monorepository][1] containing approximately 650 files and 42,000 lines of code. This project uses TypeScript Project References and Lerna, with each package having its own `tsconfig.json`. The total external direct `dependencies` and `devDependencies` across all projects is around 30. Work on Ubuntu 22.04.

[1]: https://github.com/ditsmod/ditsmod

### ESLint Config

```javascript
// @ts-check

import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      parserOptions: {
        project: [
          './packages/*/tsconfig.json',
          './examples/*/tsconfig.json',
        ]
      },
    },
  },
  {
    rules: {
      semi: ['error', 'always'],
      quotes: ['error', 'single', { avoidEscape: true }],
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-unused-expressions': 'warn',
      '@typescript-eslint/no-misused-promises': 0,
      '@typescript-eslint/no-empty-object-type': 0,
      '@typescript-eslint/no-non-null-assertion': 0,
      '@typescript-eslint/no-empty-function': 0,
      '@typescript-eslint/no-empty-interface': 0,
      '@typescript-eslint/explicit-function-return-type': 0,
      '@typescript-eslint/explicit-module-boundary-types': 0,
      '@typescript-eslint/no-explicit-any': 0,
      '@typescript-eslint/no-inferrable-types': 0,
      '@typescript-eslint/no-non-null-asserted-optional-chain': 0,
      '@typescript-eslint/no-unused-vars': 0,
      '@typescript-eslint/triple-slash-reference': 0,
      '@typescript-eslint/ban-types': 0,
      'no-async-promise-executor': 0,
      'no-prototype-builtins': 0,
    },
  },
  {
    ignores: [
      '**/dist*',
      '**/*.d.ts',
      'website/*',
      'node_modules/*',
      'eslint.config.mjs',
      '**/jest.config.ts',
    ],
  },
);
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

The `typescript-eslint` plugin should not consume so much memory.

### Actual Result

As soon as I activate the line `...tseslint.configs.recommended` in my `eslint.config.mjs`, restart VS Code, and open a file, for example, `examples/20-authjs/src/app/app.module.ts`, memory usage growing to 3.2 GB in one of the processes.

I tried using [EXPERIMENTAL_useProjectService: true][2] in `eslint.config.mjs`, but it didn't help.

[2]: https://github.com/typescript-eslint/typescript-eslint/pull/6754

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `8.18.1` |
| `@typescript-eslint/parser`            | `8.18.1` |
| `@typescript-eslint/rule-tester`       | - |
| `@typescript-eslint/scope-manager`     | `8.18.1` |
| `@typescript-eslint/typescript-estree` | `8.18.1` |
| `@typescript-eslint/type-utils`        | `8.18.1` |
| `@typescript-eslint/utils`             | `8.18.1` |
| `TypeScript`                           | `5.7.2` |
| `ESLint`                               | `9.17.0` |
| `node`                                 | `22.12.0` |

**Comment by JoshuaKGoldberg** [comment]
👋 thanks for trying out the project service and reporting! Just a few things to check before we dig in:

1. Since you're on the latest `8.18.1` (great!): just confirming, are you calling it `projectService: true` per https://typescript-eslint.io/getting-started/typed-linting? (the option has been renamed since its `EXPERIMENTAL_*` days)
2. Have you read through https://typescript-eslint.io/troubleshooting/typed-linting/monorepos?
2. Have you read through https://typescript-eslint.io/troubleshooting/typed-linting/performance?

**Comment by JoshuaKGoldberg** [comment]
Awesome, glad it's working! ⚡ 

Cross-linking to #7350 & #9571 as we've been looking for memory and performance comparisons that show the difference.

Aside: it would be nice if something told people they were using invalid/unknown settings. Tracked by our old friend #6403.
