### ISSUE TITLE
Bug: array-type automatic fix changes type logic when used with conditional types

### ISSUE THREAD

**Issue by lunedis** [typescript-eslint/typescript-eslint#10519]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.7.2&fileType=.tsx&code=C4TwDgpgBAKuEEYBCEBmB7ATtAvFAgppgIYgA8AzsJgJYB2A5gHwDcAUKJLPAvqsBExQ8VWowDaAXXYd43SACYUGbGRhNhBIqTVQIADwF0AJhSij6DKAH5z1S1ABcUOgFcAtgCNBrWVziKfAKYahp4MHqGECZmFow2dmJWzm5eglLsnNABEAoAovqQAMYCxqGaABQRBkamiQ62cckuHt6YAJQZQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AQ2mncNqNPRREXAPbRI4MAF8QUoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
type Type1Before = Array<string>;
type Type1After = string[];

type Type2Before<T> = Array<T extends string ? string : number>;
type Type2After<T> = T extends string ? string : number[];
type Type2Expected<T> = (T extends string ? string : number)[];
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/array-type": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

the automatic fix for
```TypeScript
type Type2Before<T> = Array<T extends string ? string : number>;
```
should result in
```TypeScript
type Type2Expected<T> = (T extends string ? string : number)[];
```

### Actual Result

it results in

```TypeScript
type Type2After<T> = T extends string ? string : number[];
```
which is a different type.

**Comment by ronami** [comment]
This seems like a bug to me, as the fixer changes the original type to be something else. I think the issue is around the [`typeNeedsParentheses`](https://github.com/typescript-eslint/typescript-eslint/blob/d24a82854d06089cbd2a8801f2982fd4781f3701/packages/eslint-plugin/src/rules/array-type.ts#L57-L73) function.

**Comment by lunedis** [comment]
Haha, I was 6 minutes too slow with my own pull request. But at least we made the same fix!
