### ISSUE TITLE
Docs: Deprecate `no-for-in-array`

### ISSUE THREAD

**Issue by kirkwaiblinger** [typescript-eslint/typescript-eslint#10558]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I'm wondering if `no-for-in-array` should be deprecated in favor of a trivial syntactic ban on `ForInStatement` in all cases.

For ordinary objects, `for...in` has pitfalls, too: see core rule [guard-for-in](https://eslint.org/docs/latest/rules/guard-for-in). `Object.keys()` is widely supported and addresses this use case.

For ordinary arrays, i.e. `for (const k in ["a", "b", "c"]) {}`, the statement works just fine and iterates over the indices as expected (EDIT: *except for holes). Even though the indices are string-keyed, [TS appears to have syntactic special-casing to allow indexing in this case](https://www.typescriptlang.org/play/?target=99&ts=5.8.0-dev.20241226#code/CYUwxgNghgTiAEYD2A7AzgF3rGUCeAXPAIIy54A8KArgLYBGIMAfANwBQoksCy6WsegEsMuGHgDKooSgDmRTDBmyO7AGZIY8ABR9M8RcoDSIPCGClyJvPBnYy+AJTwA3u3gf4Aei+ePAPQB+d089LAB3TQBrNHgAXntyAG1DOWtzS3xrAF0OPx8-IJCPMPhgJBA0FAxImCj4xPwkwRExSWk5XPYAXyA). So the rule isn't really helping here.

For regex arrays, which are mentioned as a motivation for the rule, [the rule doesn't even report](https://typescript-eslint.io/play/#ts=5.7.2&showAST=es&fileType=.ts&code=CYUwxgNghgTiAEYD2A7AzgF3rGUCeAXPJjAJYoDmA2gLoDcAUAwGZIzwAUy6Wp852GLjwBKeAG8G8RKjRIIIAHQQkFDjnxVSNEYwC%2BTbpnhwAgkPzwAvPAD0zELcUgAHuA4ByVkg8iAhIys7FyyWGYWeADSIHj8KCYg5sJiktJG8koqauHCVDn40Xg6DHpAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oDMPpbmtAIbRoQwuiiJRfSODABfEAqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false).

```ts
const reArray = /fe/.exec('foo')!;
for (const reArrayKey in reArray) {
  console.log(reArray[reArrayKey])
}
```

Taken together, it seems like

- we're not reporting where we really should
- where we do report, it's not so clear we even need to
- therefore, we're not really making very good use of type information
- and a syntactic total ban of `for...in` makes more sense to me anyway, since there aren't any common scenarios in which you'd _want_ `for...in`, and don't have a straightforward alternative to it.

The one argument I see against this is that `for...in` [seems to be the only way to get enumerable inherited properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties#traversing_object_properties) (EDIT: other than [manually iterating the prototype chain](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties#obtaining_properties_by_enumerabilityownership)). To which I'd say, if you need to do that for some reason, and know that you need to, then you probably are comfortable disabling eslint rules.

### Affected URL(s)

https://typescript-eslint.io/rules/no-for-in-array/

**Comment by kirkwaiblinger** [comment]
we also don't currently report on tuples at all, which can also be holey!

([playground](https://typescript-eslint.io/play/#ts=5.7.2&fileType=.ts&code=MYewdgzgLgBAZiEMC8MDaAiBIMBob4YBGAhgE4YC6MJEMokUA3AFAsJkwAUD0MAlgLDxEAShgBvFjHrg%2BANxQiQafpVYBfIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oDMPpbmtAIbRoQwuiiJRfSODABfEAqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false))

**Comment by bradzacher** [comment]
> I'm wondering if no-for-in-array should be deprecated in favor of a trivial syntactic ban on ForInStatement in all cases

IMO -- no because some codebases might be using it for other things and just want to ban it for the obviously wrong array case.
It's perfectly fine to use `for..in` for objects (though it should be guarded with a `Object.hasOwn` call, ofc).

It is old fashioned and _generally speaking_ it shouldn't be used in modern code. But that's a stylistic choice that we can't explicitly recommend, IMO. Also we can't add `no-restricted-syntax` to the recommended set.

So by removing the rule we'd lose recommended set coverage of this case.

**Comment by JoshuaKGoldberg** [comment]
:( I like this rule and think it's useful. I've personally been saved from mistakes by it before.

Not reporting on tuples feels like a straightforward bug to me?

**Comment by kirkwaiblinger** [comment]
I mean, I think it's good too! My main point is I'm just thinking it doesn't go far enough.

But it sounds like there's consensus against deprecating, so I'll close this and we can handle the tuple and RegexpArray points as separate issues
