### ISSUE TITLE
How do I know what version range of eslint is supported?

### ISSUE THREAD

**Issue by NickHeiner** [typescript-eslint/typescript-eslint#1065]
I'm stuck on ESLint 5 for the time being. I'd like to use the latest version of this package so I can use TS 3.6. However, I don't know if that'll work. I see that the dev dep on ESLint is `^6`, but I'm not sure what that means for this project's formal support goals.

I scanned the README but couldn't find any info about this there. That could be a good place to officially note this :smile:.

**Comment by bradzacher** [comment]
The best, most up-to-date place to see this is the package.json for the plugin:

https://github.com/typescript-eslint/typescript-eslint/blob/526d336adec7ae173fb259b18b7263859f61539b/packages/eslint-plugin/package.json#L60

Note that we do not test against eslint v5 any more, but there wasn't any breaking changes between v5 and v6 that should stop anything working for you.

**Comment by NickHeiner** [comment]
Thanks for the quick response! 

I would recommend putting noting in the README that `typescript-eslint/packages/eslint-plugin/package.json` is the place to look. That would have saved me from needing to bother you on this.

**Comment by bradzacher** [comment]
happy to accept a PR!

**Comment by NickHeiner** [comment]
Heh, fair enough.
