### ISSUE TITLE
IDE Persistent Parse does not handle tsconfigs with no "include" and no "files" with deeply nested folder structures

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#1110]
Spinning off of https://github.com/typescript-eslint/typescript-eslint/issues/1080#issuecomment-544198857

if you provide a tsconfig without "includes" (or "files"), I.e. an empty tsconfig: `{}`, then typescript uses a different codepath to setup the folder watchers.
Triggering a directory change does not work the same was as when the tsconfig has "includes".

It won't block the release on Monday, as it's an edge case of sorts, but I'll need to look deeper into it to figure out how it all works!

**Comment by AviVahl** [comment]
Should be noted that the default `tsconfig.json` generated by `tsc --init` doesn't have "includes".

I find myself having to change `tsconfig.json` files of more than 15 repositories to account for this issue.
My main fear is that will break one of the many other typescript integrations we have scattered around. And that's the "good" scenario. In the bad one, stuff silently breaks (IDEs, plugins etc).

**Comment by bradzacher** [comment]
There is another option which would be a little less cumbersome - do something similar to what we do in this repo: you can declare your tsconfigs directly via a `project` array glob:

https://github.com/typescript-eslint/typescript-eslint/blob/7a8cce6d4c7b3756a0267f57596b7204ca8c2566/.eslintrc.js#L117

That way you wouldn't have to modify the tsconfig, potentially breaking a build.

**Comment by AviVahl** [comment]
I really appreciate your suggestions, workarounds, and time. Seriously, thank you.

It's an annoying situation, where I either change all tsconfigs (and risk further breakage) or add new ones with maintainability burden. I'm not sure which is better. Some repos already have a separate tsconfig for the build (in each package!), and adding further ones feels wrong.

I'll try to assist and dive into the code a bit, hoping I won't drown... :)
