### ISSUE TITLE
CPU 100% when using WebStorm (or IDEA)

### ISSUE THREAD

**Issue by splincode** [typescript-eslint/typescript-eslint#1117]
**What did you expect to happen?**

![image](https://user-images.githubusercontent.com/12021443/67187672-63e40080-f3f3-11e9-8018-3db873a7d212.png)

```
cwd /Users/User/Downloads/Develop/my-project
txt /usr/local/Cellar/node/12.6.0/bin/node
txt /usr/local/Cellar/icu4c/64.2/lib/libicui18n.64.2.dylib
txt /usr/local/Cellar/icu4c/64.2/lib/libicuuc.64.2.dylib
txt /usr/local/Cellar/icu4c/64.2/lib/libicudata.64.2.dylib
txt /Users/User/Downloads/Develop/my-project/node_modules/@typescript-eslint/typescript-estree/node_modules/fsevents/fsevents.node
txt /usr/lib/dyld
```

Running on Intel Core i7-3615QM machine uses 40-70% CPU consistently, even when there are no client request and no changes to the project directory.

**What actually happened?**

I see problems with this

node_modules/@typescript-eslint/typescript-estree/node_modules/fsevents/fsevents.node

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | latest |
| `TypeScript`                           | latest |
| `node`                                 | latest |
| `npm`                                  | latest |

https://github.com/microsoft/vscode-eslint/issues/721

**Comment by bradzacher** [comment]
This is fixed in 2.5.0 which will be released today.
Please use the `canary` tag if you need it sooner

**Comment by ulrichb** [comment]
Hmmm since 2.5.0 the ESLint the `.eslintrc.js` configuration doesn't seem to get applied in WebStorm anymore. Had to revert to 2.4.0.

(In the CLI version ESLint, the configuration gets applied fine.)

**Comment by bradzacher** [comment]
We are just a parser, there should be no reason for the eslint config to be affected?

Have you got a repro? Is it always happening?
Help me to help you.
