### ISSUE TITLE
[2.5.0][Windows] 100% cache miss rate for CLI runs

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#1126]
Spinning off of #1079

For some reason every file is missing the caches on windows, and never getting found.
I cannot reproduce this on macos, so it makes me think that TS does something different between the two OS's.

Reported by: @doberkofler

**Comment by doberkofler** [comment]
Thank you for all your work!

I've just tested the `2.5.1-alpha.2` tag and there is a major improvement in speed.
Unfortunately `2.5.1-alpha.2` still seems to be perform about 30% slower then `2.3.3`.

I upload:

- `2.5.1-alpha.2.txt` -> the output of `2.5.1-alpha.2` with the `DEBUG=typescript-eslint:*` setting
- `perf_2.5.1-alpha.2.txt` -> the output of `2.5.1-alpha.2` with the `DEBUG=eslint:cli-engine` setting
- `perf_2.3.3.txt` -> the output of `2.3.3` with the `DEBUG=eslint:cli-engine` setting

[2.5.1-alpha.2.txt](https://github.com/typescript-eslint/typescript-eslint/files/3760621/2.5.1-alpha.2.txt)
[perf_2.3.3.txt](https://github.com/typescript-eslint/typescript-eslint/files/3760618/perf_2.3.3.txt)
[perf_2.5.1-alpha.2.txt](https://github.com/typescript-eslint/typescript-eslint/files/3760619/perf_2.5.1-alpha.2.txt)

**Comment by bradzacher** [comment]
We're making progress.

I think that this is because of the change in #1083 

There are use cases like Vue, or Markdown, wherein we get provided N distinct content strings for the same filename, where N is the number of `<script>` tags in the vue file, or the number of code blocks in a markdown file.

We used to not trigger a program sync if we hadn't been asked to parse the file yet, but for these use cases, the file contents TS reads are always different to the file contents eslint gives us, so we have to trigger a file sync on the first parse for a file.

I'll need to look at a solution for this, as invalidating the program for every single file in a CLI run for pure JS/TS codebases is pretty silly.
