### ISSUE TITLE
Rule proposal: import sorting rule which matches that of Organize Imports in TypeScript

### ISSUE THREAD

**Issue by aboyton** [typescript-eslint/typescript-eslint#113]
TypeScript has a wonderful feature "Organise Imports". To ensure that everyone orders imports the same way it's great to also have this as a lint rule as well (rather than someone reformatting the file who has "organise imports" turned on in their editor).

The TSLint rule [`ordered-imports`](https://palantir.github.io/tslint/rules/ordered-imports/) can almost be configured to support this ordering (there's a bug with the differences between `.toUpperCase` and `.toLowerCase` see https://github.com/palantir/tslint/issues/4063 and https://github.com/aboyton/tslint/commit/fa78d7ce1f9391e2cdce2bbc6e94551ef26bedf8).

Maybe I'm just incompetent, but I couldn't get [`import/order`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) as suggested in https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md#style to order things in the same order as TypeScript's "Organise Imports" feature.

It would be great to have a rule that orders in this order (which is basically case-insensitive by doing `x.toUpperCase`). Whether this comes from making a new rule or adding an option to `import/order` doesn't really both me.

**Comment by djskinner** [comment]
Seems related to https://github.com/typescript-eslint/typescript-eslint/pull/256

**Comment by alfaproject** [comment]
I have the same issue and I'm currently using `import/order` but I really dislike because I've tried so many different configuration options and can't really match TypeScript ordering.

Does anyone have working rules/plugins that can suggest here that might help other people?

**Comment by JoshuaKGoldberg** [comment]
We've been using [`eslint-plugin-simple-import-sort`](https://github.com/lydell/eslint-plugin-simple-import-sort) for a while internally and have been very satisfied with it. @typescript-eslint/triage-team what do you think about us wontfixing this issue and directing people to it?

As much as I would love to have an aligned-to-TypeScript auto-fixing import sorting rule, we really don't have the maintainer bandwidth to take on that surprisingly large rule.

**Comment by bradzacher** [comment]
Yeah I think that it's not something we're going to work on - there are plenty of other import sorting rules out there and I don't think adding another one to the pile really helps the ecosystem, esp when we would have to take on the maintenance burden of keeping it in-sync with the TS implementation for the user's installed version.

I'm happy to close this.

**Comment by JamesHenry** [comment]
👍

**Comment by cmalard** [comment]
For those who want to have this feature anyway: I'm using https://www.npmjs.com/package/prettier-plugin-organize-imports
That's not with ESLint but with Prettier... and according to Prettier team, this is not something that should be done by Prettier (ie, sorting things or changing the AST).
But it does the job how I want it... until someone finds the time & the motivation to do it through Prettier 🍻  (and if you have some Prettier plugins conflicts, [this one](https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins) can help ^^)
Best 🍻
