### ISSUE TITLE
Parser reports "Parsing error" for new files added to project (VSCode, IntelliJ)

### ISSUE THREAD

**Issue by maranomynet** [typescript-eslint/typescript-eslint#1137]
**What code were you trying to parse?**

Any newly added .ts files within the scope of my `tsconfig.json`'s `include` globs

My `.eslintrc.js` has these relevant lines:

```js
{
	overrides: [
		{
			files: ['*.ts', '*.tsx'],
			parser: '@typescript-eslint/parser',
			extends: [
				'plugin:@typescript-eslint/eslint-recommended',
				'plugin:@typescript-eslint/recommended',
			],
			parserOptions: {
				project: './tsconfig.json',
			},
			rules: {
				...
```

And the referenced `tsconfig.json` file has:

```js
	"exclude": ["node_modules"],
	"include": [
		"types/**/*.d.ts",
		"src/**/*.ts",
		"src/**/*.tsx"
	]
```

**What did you expect to happen?**

New `.ts` files inside the `src` folder should be parsed without an error

**What actually happened?**

New `.ts` files get the following error:

```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/new_file.ts.
The file must be included in at least one of the projects provided.
```

The files are only parsed once I do one of the following:

* Open a terminal and run `touch .eslintrc.js tsconfig.json`
* Restart my editor/reload my project
* Temporarily `import` the new `.ts` file in a file that is already being parsed.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.5.0` |
| `@typescript-eslint/eslint-plugin` | `2.5.0` |
| `TypeScript`                | `3.6.4` |
| `ESLint`                    | `6.5.1` |
| `node`                      | `12.11.1` |
| `npm`                       | `6.11.3` |

**Comment by maranomynet** [comment]
cc: #864

**Comment by bradzacher** [comment]
could you please run `DEBUG=typescript-eslint:* yarn lint` and post the output?

**Comment by maranomynet** [comment]
I don't have a "lint" npm/yarn script atm, so I just ran a simple `eslint src/*` command in the root of my (near empty) project folder. 

This appeared:

```
$ DEBUG=typescript-eslint:* eslint src/*
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /Users/mar/work/repos/sheet-api/src/example.tests.ts +0ms
  typescript-eslint:typescript-estree:createWatchProgram File did not belong to any existing programs, moving to create/update. /Users/mar/work/repos/sheet-api/src/example.tests.ts +0ms
  typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /Users/mar/work/repos/sheet-api/tsconfig.json. +0ms
Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /Users/mar/work/repos/sheet-api/src/example.ts +976ms
  typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /Users/mar/work/repos/sheet-api/src/example.ts +981ms
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /Users/mar/work/repos/sheet-api/src/testing.ts +25ms
  typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /Users/mar/work/repos/sheet-api/src/testing.ts +27ms
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /Users/mar/work/repos/sheet-api/src/types.ts +28ms
  typescript-eslint:typescript-estree:createWatchProgram Found existing program for file. /Users/mar/work/repos/sheet-api/src/types.ts +27ms
$
```

**Comment by maranomynet** [comment]
BTW, I amended the "What actually happened?" section above to include the full error message I'm seeing in my editor. This:

```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/new_file.ts.
The file must be included in at least one of the projects provided.
```

**Comment by maranomynet** [comment]
...since #864 is supposed to be fixed, then I wonder if the `overrides[n].files` globs might be somehow clashing with `tsconfig.json`'s `include` property.

**Comment by bradzacher** [comment]
ah sorry, I wasn't paying attention or reading properly, I was just popping into a meeting when I commented.
There's no way the CLI run logs are going to help here, because it's an IDE issue :)

---

> I wonder if the overrides[n].files globs might be somehow clashing with tsconfig.json's include property.

Shouldn't be - they're two different config domains: we don't have access to the eslint config (apart from what gets sent to us via `parserOptions`), and they don't have access to the tsconfig.

---

Two things for you:

- could you please post your full tsconfig?
    - Using `include` is expected and has many test cases within the repo (and works fine for me when working within this repo).
    - I wonder if there's something else in your tsconfig which is causing typescript to do something different with its file resolution.
- could you please try the latest `canary` tag version of the parser (make sure to close and reopen your IDE after installing it).
    - There have been a few fixes merged since the 2.5.0 release on Monday.

**Comment by maranomynet** [comment]
The tsconfig.json I'm using in my current project

```json
{
	"compilerOptions": {
		"target": "es5",
		"lib": ["dom", "esnext"],
		"skipLibCheck": true,
		"forceConsistentCasingInFileNames": true,
		"noEmit": false,
		"esModuleInterop": true,
		"module": "esnext",
		"moduleResolution": "node",
		"declaration": true,
		"declarationDir": "dist/__types",
		"newLine": "LF",

		"allowSyntheticDefaultImports": true,
		"jsx": "preserve",

		"isolatedModules": false,

		"strict": true,
		"strictBindCallApply": false,
		"noImplicitThis": false
	},

	"exclude": ["node_modules", "dist"],
	"include": ["types/**/*.d.ts", "src/**/*.ts", "src/**/*.tsx"]
}
```

I'll try the canary and report asap

**Comment by maranomynet** [comment]
```
$ grep 'version' node_modules/\@typescript-eslint/parser/package.json 
  "version": "2.5.1-alpha.3+1508670d",
```

...aaand it seems to do the trick.

Unable to reproduce the errors.

Revert back to version 2.5.0, reload IDE, and the errors show up as usual.

**Comment by bradzacher** [comment]
Awesome!
I'll go ahead and close this then.
