### ISSUE TITLE
Rule proposal: No multi non null assertion

### ISSUE THREAD

**Issue by negezor** [typescript-eslint/typescript-eslint#1170]
Currently, non null assertion can be written more than once without any errors.
```ts
const one: number | undefined = 1;

const result = one!!!!!!;
```
I propose to add a rule that will limit the number of characters to 1.

**Comment by a-tarasyuk** [comment]
@bradzacher what would the acceptable name for this rule?

**Comment by bradzacher** [comment]
probably something similar to
https://eslint.org/docs/rules/no-extra-semi

Maybe `no-extra-non-null-assertion`
