### ISSUE TITLE
Add fragment options to lint code fragment for Vue SFC performance

### ISSUE THREAD

**Issue by yoyo930021** [typescript-eslint/typescript-eslint#1180]
I think a solution for Vue SFC performance.
#### typescript-eslint/typescript-eslint project
1. add `fragment` boolean option in `@typescript-eslint/parser`.
2. if `fragment === true` use `createIsolatedProgram` in `@typescript-eslint/typescript-estree`.

#### vue-eslint-parser project
1. if parse ScriptFragment, add fragment options to parserOptions.

### Test result
I have 109 TypeScript files and 119 Vue SFC files in this tested project.
```
@typescript-eslint 2.6.0 && vue-eslint-parser 6.0.4:
real 261.93
user 306.04
sys 5.10

This Solution:
real 13.04
user 20.26
sys 1.27
```

### Test code project
[yoyo930021/typescript-eslint](https://github.com/yoyo930021/typescript-eslint/tree/fragment) [#commit](https://github.com/yoyo930021/typescript-eslint/commit/db796149a3193056e2233647041864606e0c8fe0)
[yoyo930021/vue-eslint-parser](https://github.com/yoyo930021/vue-eslint-parser/tree/typescript) [#commit](https://github.com/yoyo930021/vue-eslint-parser/commit/7e12592b9eadef51f87dfd5077bc9fc45eb5b91a)

**Comment by bradzacher** [comment]
`createIsolatedProgram` parses the file as if you ran `tsc --isolatedModules`.
This means that typescript parses the file as if every single import had type `any`.
IIRC it also means that it doesn't consume `@types` definitions.

Essentially, using `createIsolatedProgram` is pretty useless for rules that require type information - it's only marginally better than creating a ts `SourceCode` object.

**Comment by yoyo930021** [comment]
I try to `delete parserOptions.project` on before, but I will get a error when having needed type rules in  `.eslintrc.js`.
The eslint parser can't disable rules about needed type rules.

So I will be In trouble.

**Comment by bradzacher** [comment]
Yeah, so you have to use eslint overrides to disable rules requiring type information on vue files.

I think that's much better than silently not failing, and then potentially showing incorrect errors, or missing errors due to incomplete types.

**Comment by yoyo930021** [comment]
> Yeah, so you have to use eslint overrides to disable rules requiring type information on vue files.
> 
> I think that's much better than silently not failing, and then potentially showing incorrect errors, or missing errors due to incomplete types.

I think it's not and have some misunderstanding.

<img width="845" alt="Screen Shot 2019-11-10 at 12 53 47 AM" src="https://user-images.githubusercontent.com/9126398/68532144-eefe4980-0354-11ea-8279-a0fdd91ec94c.png">
This image is a Vue file.

The Typescript code is circled in this image.
The code fragment is yellow.
The main code is red.

The main code is needed about requiring type information,
but the code fragment isn't.

In `vue-eslint-parser`, will use `@typescript-eslint/parser` in every typescript code.

**Comment by bradzacher** [comment]
I'm with you now - sorry, I'm not all that familiar with vue, because I've never used it.

The problem still stands, however, that this will put you in a bad place with regards to those rules. If you create an isolated program for each of the fragments (yellow), essentially typescript will parse them and do this:

- parse `$style.container` in isolated mode
- lookup type of variable `$style`
- find it's not declared in the code fragment, and because the parse was isolated, it means there is no way it can resolve the type.
- set type of `$style` to `any`.
- set type of `$style.container` to `any`.

This means that, for example, many of the rules that require type information that currently exist (like `prefer-string-starts-ends-with`, `prefer-regexp-exec`, `prefer-includes`, `no-unnecessary-type-assertion`) will all be unable to function, because they all rely on the types being something substantial that can be inspected, which `any` is not.

**Comment by yoyo930021** [comment]
In `vue-eslint-parser`, have the same problem now,
because The `vue-eslint-parse` will use `@typescript-eslint/parser` for code fragment and main code.

<img width="845" alt="Screen Shot 2019-11-10 at 12 53 47 AM" src="https://user-images.githubusercontent.com/9126398/68532144-eefe4980-0354-11ea-8279-a0fdd91ec94c.png">
example by image:
- `0([$style['app-navbar'], { [$style['server-is-on-local']]: serverIsOnLocal }])`
- `0($style.container)`
- `0($style.left)`
- `0($style.right)`
- main code
will use `@typescript-eslint/parser`.

`vue-eslint-parser` will use `@typescript-eslint/parser` for typescript code,
and parser other code to combine complete AST.

The code fragment can't use the rules that require type information on now,
so replacing `createWatchProgram` to `createIsolatedProgram` on code fragment is no problem,
but the main code is needed `createWatchProgram`.
I can't custom by this in `.eslintrc.js`.

**Comment by bradzacher** [comment]
I don't think you're understanding me.

I'm saying that right now, typescript will do its best to consume globally defined types, etc in the fragments. That's what you get as part of the watch program.
This means anything defined in the vue typescript types will be used when resolving types for the fragments.
This means that typescript will be able to resolve a type for `$style` in this mode.

When in isolated mode, typescript will not use any globally defined types. This means that it cannot possibly resolve a type for `$style`, so it will default to `any`.

Sure if you're only doing very simple `$style.foo` expressions, then it doesn't matter too much, but if you do any more complex expressions, then you could potentially not get lint warnings/errors.

This is probably something that needs to be handled differently from the vue-eslint-parser side.
I suggest you open an issue there to discuss options for how the parser could handle fragments in such a way that it can pass something more conducive to an environment which wants to resolve full type information.

**Comment by yoyo930021** [comment]
The typescipt code is `this` properties about the main code of export default object in vue template.
Example by image:

- [this.$style['app-navbar'], { [this.$style['server-is-on-local']]: this.serverIsOnLocal }]
- this.$style.container
- this.$style.left
- this.$style.right

Unless the main code of export default object add code fragments and add `this` to code fragments  in `vue-eslint-parser`, The code fragment isn't have any type info on now.

The former is a big thing, and more difficult problem.
The [vetur](https://github.com/vuejs/vetur/) is realized and base on `vue-eslint-parser` to get Template AST on now.
[link](https://blog.matsu.io/generic-vue-template-interpolation-language-features)

**Comment by bradzacher** [comment]
Jeez, there's so much tooling, and hacks required to make vue work...

If there was some changes made to the way vue parser outputs the source code, then you could have full typing and make this work.

```ts
<template>
  <nav :class="[$style['app-navbar'], { [$style['server-is-on-local']]: serverIsOnLocal }]">
    <div :class="$style.container">
      <div :class="$style.left">
        <slot name="left" />
      </div>
      <div :class="$style.right">
        <slot name="right" />
      </div>
    </div>
  </nav>
</template>

<script lang="ts">
import { Component, Prop, Vue, Emit, Mixins } from 'vue-property-decorator'
import ConfigStorage  from '@/storages/ConfigStorage'
import AppMixin from '@/components/AppMixin'

@Component({
  name: 'AppNavbar'
})
export default class AppNavbar extends Mixins(AppMixin) {
  localeKey = 'AppNavbar' as const
  get serverIsOnLocal () {
    return ConfigStorage.getInstance().url.indexOf('localhost') >= 0
  }
}
</script>
```

transforms to

```ts
function fragments(this: AppNavbar) {
  propertyBind_class = [this.$style['app-navbar'], { [this.$style['server-is-on-local']]: this.serverIsOnLocal }];
  propertyBind_class = this.$style.container;
  propertyBind_class = this.$style.left;
  propertyBind_class = this.$style.right;
}

import { Component, Prop, Vue, Emit, Mixins } from 'vue-property-decorator'
import ConfigStorage  from '@/storages/ConfigStorage'
import AppMixin from '@/components/AppMixin'

@Component({
  name: 'AppNavbar'
})
export default class AppNavbar extends Mixins(AppMixin) {
  localeKey = 'AppNavbar' as const
  get serverIsOnLocal () {
    return ConfigStorage.getInstance().url.indexOf('localhost') >= 0
  }
}
```

---

It also seems like this is something that could be achieved via eslint processors:
https://eslint.org/docs/developer-guide/working-with-plugins#processors-in-plugins

given the file above, a `preprocessor` could output:

```ts
export = {
  processors: {
    'typescript-vue-preprocessor': {
      preprocess(text, filename) {
        const {fragments, script} = splitVueFile(text);
        return [
          fragments.map((frag, idx) => ({
            text: frag,
            filename: filename.replace(/.vue$/, `.${idx}.fragment.vue`,
          })),
          {
            text: script,
            filename,
          },
        ];
      }
    }
  }
}
```

Then eslint would pass each file to the parser(s) separately, and because of the filenames, you could do this in your config

```jsonc
{
  "overrides": [
    {
      "files": ["*.fragment.vue"],
      "parserOptions": {
        "parser": "vue-eslint-parser",
        "parserOptions": {
          "parser": "@typescript-eslint/parser"
          // note - no project
        }
      },
      "rules": {
        // disable typecheck rules
      }
    }
  ]
}
```

**Comment by yoyo930021** [comment]
You code have some problem about no use vue class component.
I think we need @mysticatea  to get some suggestion.

**Comment by armano2** [comment]
@bradzacher preprocessor is nice idea, but it has few drawbacks what you can do in `eslint-plugin-vue`.

some of rules do cross checking between vue template and script code, for example: https://eslint.vuejs.org/rules/no-unused-components.html, i'm unsure if this will be still possible.

`eslint-plugin-vue` (officail plugin that uses `vue-eslint-parser`) as for now does not support `vue-property-decorator`.
