### ISSUE TITLE
[camelcase] Add option to disable checking on library imports?

### ISSUE THREAD

**Issue by Zjaaspoer** [typescript-eslint/typescript-eslint#1210]
(As this is a feature request I didn't use the template. If you guys want me to fill it in, let me know and I will)

For the `camelcase` rule does it make sense to add an option to not check imports from 3rd party libraries? As you have no influence on their naming checking not checking those names would be a nice opt-out IMO.

I understand that you could rename the imports using the `... as ...` convention, but there are plenty of use cases where people prefer not to.

(BTW I tried if the `ignoreDestructuring` option works, as named importing is technically object destructuring, but alas!)

**Comment by bradzacher** [comment]
Happy to accept a PR

**Comment by Zjaaspoer** [comment]
👍

**Comment by dimabory** [comment]
@Zjaaspoer, @bradzacher  Seems like it has been [merged into eslint](https://github.com/eslint/eslint/pull/12528) a week ago.
