### ISSUE TITLE
[no-floating-promises] TypeError: Cannot read property 'kind' of undefined (when using void)

### ISSUE THREAD

**Issue by glen-84** [typescript-eslint/typescript-eslint#1222]
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-floating-promises": "error",
  }
}
```

```TS
void this.loadGames();
```

**Expected Result**

No error.

**Actual Result**

```
[Error - 09:45:35] TypeError: Cannot read property 'kind' of undefined
Occurred while linting ...\src\media\streams\services\test.ts:1
    at isUnhandledPromise (...\node_modules\@typescript-eslint\eslint-plugin\dist\rules\no-floating-promises.js:58:36)
    at ExpressionStatement (...\node_modules\@typescript-eslint\eslint-plugin\dist\rules\no-floating-promises.js:47:21)
    at ...\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (...\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (...\node_modules\eslint\lib\linter\node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (...\node_modules\eslint\lib\linter\node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (...\node_modules\eslint\lib\linter\node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (...\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:634:23)
    at ...\node_modules\eslint\lib\linter\linter.js:936:32
```

**Additional Info**

(see above)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.7.0` |
| `@typescript-eslint/parser`        | `2.7.0` |
| `TypeScript`                       | `3.4.5` |
| `ESLint`                           | `6.6.0` |
| `node`                             | `12.13.0` |
| `npm`                              | `6.12.0` |

**Comment by a-tarasyuk** [comment]
@glen-84 could you provide an extended example of how to reproduce the issue?

**Comment by glen-84** [comment]
@a-tarasyuk That one line is the only code in the file – are you not able to reproduce the error?

**Comment by a-tarasyuk** [comment]
@glen-84 unfortunately, no.

![Screenshot from 2019-11-18 18-00-02](https://user-images.githubusercontent.com/509265/69068385-5428fd80-0a2d-11ea-8884-aa196fa16832.png)
![Screenshot from 2019-11-18 18-00-20](https://user-images.githubusercontent.com/509265/69068388-5428fd80-0a2d-11ea-8a2e-997a8e711528.png)

**Comment by bradzacher** [comment]
Same error as #815?

I was unable to repro it last night as well.

**Comment by bradzacher** [comment]
The error your seeing is occurring here, on the second line of the condition:
https://github.com/typescript-eslint/typescript-eslint/blob/6a55921e2b9245102c4c373759dde4c36c3b4c08/packages/eslint-plugin/src/rules/no-floating-promises.ts#L65-L68

The `isBinaryExpression` function from typescript is shorthand for `node.kind === ts.SyntaxKind.BinaryExpression`.
If this returns true, the node _must_ be a `BinaryExpression` node from typescript, which is defined to always have an `operatorToken`.

So this either means that there's a bug in typescript, a bug in our node mapping algorithm, or the most likely:
You've probably got multiple typescript versions installed.

The `SyntaxKind` enum does not use fixed values, it relies upon values auto-generated by the compiler. With each typescript version, they do not respect backwards compatibility, and add enum values wherever it makes sense within the enum.

That means if your workspace has two different TS versions installed, it's possible the parser has resolved its TS version to an older one, and set the ts node kind to `208`; what that version thinks is `SyntaxKind.VoidExpression` (or one of the other nodes in your example.

Then the plugin picks up a newer version of typescript, and sees the node has kind `208`, and thinks this node is instead a `SyntaxKind.BinaryExpression`, which then causes this error for obvious reasons.

**Comment by glen-84** [comment]
I'm really sorry for wasting your time, this was indeed the problem.

When I use `npm link` to link my local shareable config, it won't run in the project unless I temporarily install `typescript` and `eslint`, and the TypeScript versions were different. 😟
