### ISSUE TITLE
[deprecation] Warns when deprecated APIs are used.

### ISSUE THREAD

**Issue by htho** [typescript-eslint/typescript-eslint#1223]
**Repro**
```JSON
{
  "rules": {
    "@typescript-eslint/deprecation": ["warn"]
  }
}
```

```TS
// CASE 1: for functions
/** @deprecated use f2 instead */
function f1(): void {return;}
function f2(): void {return;}

f1(); // WARN: "f1 is deprecated: use f2 instead

// CASE 2: for interfaces
interface Test {
  /** @deprecated use b instead */
  public a?: string;
  public b?: string;
}

const x: Test = {
  a: "foo"; // WARN: "Test.a is deprecated: use b instead
}
```
**Expected Result**
In both cases there should be a warning, that the function or property are depricated.

**Actual Result**
The `@depricated` comments are ignored.

**Additional Info**
There is a [TSLint Rule: `deprication`](https://palantir.github.io/tslint/rules/deprecation/) and a [long discussion at the TypeScript Bugtracker](https://github.com/microsoft/TypeScript/issues/390)

I did not check the implementation for TSLint, but there are many things to consider. They should be configurable.

1. For interfaces a depricated property must be optional (otherwise one could not not use the property)
2. There should be a warning if a `private` or `protected` property is marked as depricated. (at least private properties should be updated as soon as a property is depricated)
3. A `@depricated` tag must be followed by an explanation and/or alternative.

**Comment by ark120202** [comment]
Related: https://github.com/SonarSource/SonarJS/issues/1432, https://github.com/SonarSource/SonarJS/pull/1715

> Later we can contribute this rule to typescript-plugin for eslint.

**Comment by gund** [comment]
Now that this rule was implemented and merged in SonarJS - are there any plans to bring this to `typescript-eslint`?

**Comment by bradzacher** [comment]
We don't have any. If someone wants to PR it, we would be happy to review it.

**Comment by gund** [comment]
I believe it's just a matter of copy-pasting [this rule](https://github.com/SonarSource/SonarJS/blob/d628d5aacb421b6932373e460e9a3035c9d7f399/eslint-bridge/src/rules/deprecation.ts) from `sonarjs` repo?

**Comment by bradzacher** [comment]
It's not quite as simple as a copy paste job, as that code has its own licence.
Someone needs to discuss with the maintainers, and make sure they're okay with the port.

Also, the code would have to be updated to fit our coding standards in this repo, as the style is reasonably different.

**Comment by gund** [comment]
Well `SonarJS` repo uses LGPL which allows any redistribution of source code but under either GPL or LGPL licence. Which is not gonna work because this repo is using BSD like license.

However, it is possible to port that rule into eslint plugin (say `eslint-plugin-deprecation`) and licence it under LGPL and then use it here as external library.

Maybe it makes more sense to just create another repo for this rule?

**Comment by bradzacher** [comment]
If someone wants to port the rule to an independent eslint plugin, feel free!
If someone wants to simply document how to use the sonar rule, they can do that instead.
If someone wants to independently implement the rule based on [tslint's implementation](https://github.com/palantir/tslint/blob/master/src/rules/deprecationRule.ts), they can do that too.

**Comment by gund** [comment]
Alright, I've ported the rule into separate plugin https://github.com/gund/eslint-plugin-deprecation

**Comment by bradzacher** [comment]
happy if you update the docs to point at your plugin, and then we can consider this closed.
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md#maintainability

(note the docs currently point at an eslint-plugin-import rule, which is not as good as a rule using typescript types, like your ported rule does)

**Comment by webmaster128** [comment]
Thank you @gund!

If someone stumbles upon this, I think t would still be cool to have a port of the tslint implementation (as [suggested by](https://github.com/typescript-eslint/typescript-eslint/issues/1223#issuecomment-586665296) @bradzacher) in this repo due to licensing reasons and for fewer dependencies.

**Comment by nicmosc** [comment]
@gund looks like the plugin still doesn't trigger a warning (nor error) for interface properties: ran the same code as shown above by @htho , but only the function related warnings are triggered:
![image](https://user-images.githubusercontent.com/16778318/76073707-55f5dd00-5f9a-11ea-9775-79f9c9f84eb0.png)
Also, `public` cannot be added to the interface properties, it will not compile. Still, when removing the `public`, no eslint warning is thrown. Any idea why that might be?

**Comment by nicmosc** [comment]
Actually, let me rectify my previous comment. It seems that the warning works when using react components as such:
```tsx
interface DeprecatedRules {
  /** @deprecated blabla sdfs */
  something?: string;
}

const ComponentWithDeprecation = ({ something }: DeprecatedRules) => {
  console.log(something);
  return <div></div>;
};

export default function App() {
  return (
    <div className="App">
      <ComponentWithDeprecation something="" />
    </div>
  );
}
```
The issue now being that the warning is shown even when the deprecated `something` field is _not_ used in the component i.e. this will also trigger a warning:
```
<ComponentWithDeprecation something="" />
```
Which is kind of agains the purpose of deprecating individual fields in an interface, especially since they should always be optional anyway

**Comment by gund** [comment]
@nicmosc I think that warning report is correct because you do extract deprecated `something` in your components props - which by definition means that your code is using deprecated entity.

**Comment by bradzacher** [comment]
@nicmosc please don't use this issue for talking about issues with the rule.
There is a separate github repo within which you can create an issue and discuss with @gund.
https://github.com/gund/eslint-plugin-deprecation

Commenting here just creates noise for everyone who is watching this repo.
