### ISSUE TITLE
[restrict-template-expressions] Extend "allowNullable" to support undefined

### ISSUE THREAD

**Issue by juergenzimmermann** [typescript-eslint/typescript-eslint#1234]
`allowNullable` supports `null` inside a template expression: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/restrict-template-expressions.md#allownullable

I'd appreciate if also `undefined` would be covered either by `allowNullable` or by an additional option.

**Comment by bradzacher** [comment]
Ahhh.. I didn't pay enough attention to the naming vs the implementation when reviewing. Options with `nullable` should always include undefined.

**Comment by bradzacher** [comment]
Digging into this - it looks like it is supported.
Do you have a specific case that's not working?

**Comment by juergenzimmermann** [comment]
I was assuming that only null is supported because the sample in the docs doesn't mention `undefined`.

**Comment by bradzacher** [comment]
The docs do mention undefined though:

> // if true, also allow null and undefined in template expressions
