### ISSUE TITLE
[no-dynamic-delete] autofix make code error

### ISSUE THREAD

**Issue by shenshaohui1991** [typescript-eslint/typescript-eslint#1240]
Hi,

I just want to try '@typescript-eslint/no-dynamic-delete' rule, but after run `eslint src --ext .ts --fix`，it make my code run error

**Repro**

```JSON
{
    parser: '@typescript-eslint/parser',
    extends: [
        'alloy',
        'alloy/typescript',
    ],
    parserOptions: {
        ecmaVersion: 2018,
        sourceType: 'module'
    },
    rules: {
        '@typescript-eslint/no-dynamic-delete': "error"
    }
}
```

```TS
// your repro code case
let key = 'testKey';
let obj = { 'testKey': 1 };
delete obj[key];
```

**Expected Result**

```TS
let key = 'testKey';
let obj = { 'testKey': 1 };
delete obj[key];
```

**Actual Result**

```TS
let key = 'testKey';
let obj = { 'testKey': 1 };
delete obj.key;
```

**Versions**

{
    "@typescript-eslint/eslint-plugin": "latest",
    "@typescript-eslint/parser": "latest",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-config-alloy": "latest",
    "eslint-plugin-typescript": "^0.14.0",
    "typescript": "^3.6.3",
    "typescript-eslint-parser": "^22.0.0"
  }

**Comment by armano2** [comment]
fixed by #1244

-------

@shenshaohui1991 small note: `typescript-eslint-parser` and `eslint-plugin-typescript` is no longer maintained and you should avoid having them in dependencies
