### ISSUE TITLE
Add support for new suggestions API

### ISSUE THREAD

**Issue by SimenB** [typescript-eslint/typescript-eslint#1249]
**What did you expect to happen?**
To be able to use the new suggestions API released in `eslint@6.7`.
https://eslint.org/blog/2019/11/eslint-v6.7.0-released
https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions

**What actually happened?**
I get a type error - `Object literal may only specify known properties, and 'suggest' does not exist in type 'ReportDescriptor<"someRule">'`

**Versions**

| package                                 | version  |
| --------------------------------------- | -------- |
| `@typescript-eslint/experimental-utils` | `2.8.0`  |
| `TypeScript`                            | `3.7.2`  |
| `node`                                  | `13.2.0` |
| `npm`                                   | `6.11.2` |

**Comment by bradzacher** [comment]
I didn't know this was a thing! Super interesting.
Happy to accept a PR to add it in to the types!

We should do a review of our current rules to see what we fixers we never added due to their safety/stability/dev annoyance via auto-fixing.

So many possibilities...

**Comment by bradzacher** [comment]
okay. I got too excited about this feature and added types for it (and implemented it into our first rule)
#1250
