### ISSUE TITLE
respect `CLIEngine` cwd option in parser

### ISSUE THREAD

**Issue by Austaras** [typescript-eslint/typescript-eslint#1254]
currently in parser project is find relative to tsConfigRoot which defaults to `process.cwd()`, but it's better to default to `CLIEngine` option for better tool intergation

**Comment by bradzacher** [comment]
Unfortunately this is not possible.
ESLint does not pass this argument through to the parser.

ESLint calls into our parser via the `parseForESLint(code, options)` function we export.

`code` is ofc the raw code string.
`options` is the `parserOptions` from the user config, merged with some extra eslint options.
These are the options that are passed in when running a lint within this repo:
```json
{
    "ecmaVersion": 6,
    "ecmaFeatures": {
        "globalReturn": false,
        "jsx": false
    },
    "sourceType": "module",
    "project": [
        "./tsconfig.eslint.json",
        "./packages/*/tsconfig.json"
    ],
    "tsconfigRootDir": "/Users/bradzacher/github/typescript-eslint",
    "loc": true,
    "range": true,
    "raw": true,
    "tokens": true,
    "comment": true,
    "eslintVisitorKeys": true,
    "eslintScopeManager": true,
    "filePath": "/Users/bradzacher/github/typescript-eslint/packages/eslint-plugin/src/configs/eslint-recommended.ts"
}
```
