### ISSUE TITLE
Changes to the `eslint-recommended` ruleset for 3.0.0

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#1273]
Reviewing rules, we can add some new rules to this set in the next major.

- [`constructor-super`](https://eslint.org/docs/rules/constructor-super) (#1248)
    - [repl](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=7&pc=1#code/MYGwhgzhAECC0G8BQ1XQA4FcBGICWw0wA9gHYQAuATpsBcVQBQCUiKaHEm6Apk8wG52qAL5IxSUJBgAhaDwAeFHqQAmMeMg5ZcBImUo06DFmw4cA9BegA6O8OhiRQA)
    - `'super' can only be referenced in a derived class. (2335)`
    - `Constructors for derived classes must contain a 'super' call. (2377)`
- [`no-func-assign `](https://eslint.org/docs/rules/no-func-assign) (#983)
    - [repl](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMOcAUBKRBvAvgKBTkQF5EBGAbnyA)
    - `Cannot assign to 'foo' because it is not a variable. (2539)`
- [`no-setter-return`](https://eslint.org/docs/rules/no-setter-return)
    - [repl](https://www.typescriptlang.org/play/?ssl=6&ssc=18&pln=5&pc=2#code/MYGwhgzhAEBiD29oG8BQ0PQgUwC7QDNEAKMALmgEYBKFdTBgJzwFdGA7KgbnowF9UAoA)
    - `Setters cannot return a value. (2408)`
- [`no-obj-calls `](https://eslint.org/docs/rules/no-obj-calls) (#999 / #1000)
    - [repl](https://www.typescriptlang.org/play/?ssl=4&ssc=25&pln=3&pc=25#code/G4QwTgBAtiAuAWEC8ECyd4AoCUBuAUKJAFYDOA9gHbIQBSAygPIByOBREYApgGYA2XAMawaAJV4DhbIA)
    - `Type 'Math' has no call signatures. (2349)`
- [`no-unsafe-negation `](https://eslint.org/docs/rules/no-unsafe-negation) (#1146)
    - [repl](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=6&pc=1#code/MYewdgzgLgBAhjAvDAjAbgFCkrARkmAJkwBsBTWAMxBEwwEtKYAKAQgQB4ZcBKGAbwwxhMAPQAqcaIwBfDBgDuAC3rkW7GAD5ufQSLGTpcjNRAENHZLjqnzCTVbrZoMALYBPAPK4AVmWCwyPwymM6wANZk7gQARDGh4C4AwlAgAE4EAGIArmAB9OB0jOqR0fRgbl6+-lC6QiKiojAgAA5kaXCpGS1p-mQAJmR5ZG5wkRAw9LBkAI7Z9ABucORgsKklUXzlzdUB9cKN8GD9MFDubTDYC+0QBRWuY2QTUzCz80sra2bMpTAA-DAYpRlhAyDEYAAuQFQNLZMFbCogXZQWTyYpsDzePwBSY4ODDEBMFLpOr6Q6tdqddIwHp9QbDUbjSbTOaLZZDL7qJE+BHQfHAMiEmDEtL7MRNfEnF5vNmfU5mZYKODuCbAkigmC3Bm4GjkfEwD5wiZwXowMAgWDcmoQAB0siAA)
    - `Operator '<' cannot be applied to types 'boolean' and 'number'. (2365)`
    - `The left-hand side of an 'in' expression must be of type 'any', 'string', 'number', or 'symbol'. (2360)`
    - `The left-hand side of an 'instanceof' expression must be of type 'any', an object type or a type parameter. (2358)`

**Comment by wtgtybhertgeghgtwtg** [comment]
Will `prefer-optional-chain` and `prefer-nullish-coalescing` make the cut?

**Comment by bradzacher** [comment]
@wtgtybhertgeghgtwtg - the `eslint-recommended` set is different from the `recommended` set.

`eslint-recommended` is intended to be used with eslint's base `recommended` set, and it disables all rules that are known to be covered by the typescript typechecker.

---

It's highly likely that `prefer-optional-chain` and `prefer-nullish-coalescing` will make the cut into our recommended set though.

**Comment by glen-84** [comment]
1. I hadn't mentioned `no-setter-return` because I thought that this set only disabled recommended rules (and `no-setter-return` is not marked as recommended).
2. I'm not actually using this set, but I do wonder why this is considered a breaking change, since it is only used by TypeScript users, who will already be seeing the TypeScript errors. These users would either have broken code (because of the TS errors), or they would have neither TS errors nor the related ESLint errors.

**Comment by bradzacher** [comment]
> I do wonder why this is considered a breaking change

Some users do rely on linting to catch problems when using babel as their transpiler.
I've seen setups where people run eslint and babel via webpack, but not the typescript checker.
So adding rules to this would reduce their build safety, so it's best to make it breaking, just in case.

**Comment by moulikcipherX** [comment]
Hy, @bradzacher is there anything I can work on?

**Comment by bradzacher** [comment]
@moulikcipherX there's no shortage of issues to look at.
There are plenty tagged with "good first issue" which should be doable.
Pretty much any issue without the "has PR" is fair game.

https://github.com/typescript-eslint/typescript-eslint/blob/master/CONTRIBUTING.md#pull-requests
