### ISSUE TITLE
[restrict-template-expressions] Requires error.message to be typed

### ISSUE THREAD

**Issue by scottohara** [typescript-eslint/typescript-eslint#1278]
This is very minor nitpick, and not technically a bug.

To be clear: the rule is currently **working exactly as designed**.

I'm raising this issue because there may be an opportunity to slightly reconsider the design, to allow an exception for what I believe could be a common case.

Please feel free to close if this issue if the consensus is that the rule shouldn't be changed, as there are a number of trivial workarounds (see below).  

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/restrict-template-expressions": ["error", {
      "allowNumber": true,
      "allowBoolean": true,
      "allowNullable": true
    }]
  }
}
```

```TS
try {
  throw Error("an error");
} catch (error) {
  console.log(`Error: ${error.message}`);
}
```

**Expected Result**

Ideally, no errors?

**Actual Result**

```
Invalid type of template literal expression  @typescript-eslint/restrict-template-expressions
```

**Additional Info**

The problem is that Typescript doesn't allow the catch clause variable (`error` in this case) to have a type annotation, so it defaults to `any`.

Therefore, `error.message` is also `any`, and when used in a template expression triggers the warning.

Obviously this is very simple to workaround, either by:

1. Explicitly casting it to a string

```TS
catch (error) {
  console.log(`Error: ${String(error.message)}`);
}
```

2. Using a type assertion

```TS
catch (error) {
  console.log(`Error: ${error.message as string}`);
}
```

3. Extracting/destructuring to a typed variable

```TS
catch (error) {
  const message: string = error.message;
  console.log(`Error: ${message}`);
}
```

The question is: should the rule force developers to apply one of these workarounds to every similar usage of `error.message` in template strings throughout their projects; or should we consider this to be a known, valid exception to the rule?

Remember that the main difference between this and any other code that uses invalid types in template expressions is simply that it requires extra effort on the part of the developer to supply the correct type information, because the catch clause variable doesn't allow a type annotation.

I'm perfectly fine if the answer here is 'no, this shouldn't be an exception'.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.9.0` |
| `@typescript-eslint/parser`        | `2.9.0` |
| `TypeScript`                       | `3.7.2` |
| `ESLint`                           | `6.7.1` |
| `node`                             | `12.12.0` |
| `npm`                              | `6.12.0` |

**Comment by bradzacher** [comment]
I'm thinking that the answer is 'no, this shouldn't be an exception'.
The type of the variable is any, which means you don't actually know anything about it.

Depending on your environment, you can probably make a good assumption about the error, but you don't know for sure.

Here you're making the assumption that `error instanceof Error`, but you could just as easily have any other type, which would lead to an unexpected output (see examples below).

It is a bit of a pain, but it does highlight an inherent lack of safety in exception handling.

```ts
try {
  throw 'my error message';
} catch (error) {
  console.log(`Error: ${error.message}`); // Error: undefined
}

try {
  throw { };
} catch (error) {
  console.log(`Error: ${error.message}`); // Error: undefined
}

try {
  throw { message: () => 'my message here' };
} catch (error) {
  console.log(`Error: ${error.message}`); // Error: () => 'my message here'
}

try {
  throw { message: ['my', 'message', 'here'] };
} catch (error) {
  console.log(`Error: ${error.message}`); // Error: my,message,here
}

try {
  throw { message: { my: { message: 'here' } } };
} catch (error) {
  console.log(`Error: ${error.message}`); // Error: [object Object]
}

// Or the absolute stupidest thing, but it's possible:
try {
  throw undefined;
} catch (error) {
  console.log(`Error: ${error.message}`);
  // Uncaught TypeError: Cannot read property 'message' of undefined
}
```

**Comment by scottohara** [comment]
Yep, good points.

I hadn't considered that the `throw` statement takes an expression that can be anything (not just `instanceof Error`).

Given that, I think you're right that this shouldn't be an exception.

Closing.
