### ISSUE TITLE
"parserOptions.project" is stored incorrectly

### ISSUE THREAD

**Issue by manuth** [typescript-eslint/typescript-eslint#1286]
**Repro**
1. Create an eslint-configuration file with `parser` and `parserOptions.project` specified:  
***.eslintrc.js***
```js
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  }
}
```
2. Invoke following command:  
```sh
node -e "console.log(new (require('eslint').CLIEngine)({}).getConfigForFile('./index.js'))"
```

**Expected Result**
Just like the `parser`-option, `parserOptions.project` should be converted to an absolute path, too.

```js
{
  […]
  parser: 'E:\\Users\\Manuel\\Documents\\Projekte\\Node-Modules\\TypeScriptESLintPlugin\\node_modules\\@typescript-eslint\\parser\\dist\\parser.js',        
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
    project: 'E:\\Users\\Manuel\\Documents\\Projekte\\Node-Modules\\TypeScriptESLintPlugin\\tsconfig.json'
  }
  […]
}
```

**Actual Result**
The `parserOptions.project`-option remains relative (`./tsconfig.json`).

```js
{
  […]
  parser: 'E:\\Users\\Manuel\\Documents\\Projekte\\Node-Modules\\TypeScriptESLintPlugin\\node_modules\\@typescript-eslint\\parser\\dist\\parser.js',        
  parserOptions: { ecmaVersion: 2018, sourceType: 'module', project: './tsconfig.json' }
  […]
}
```

**Additional Info**
This issue causes `eslint` to act strangely if you're running the cli from a sub- or a parent-folder.  
Following error is reported if you run `eslint` from a subfolder called `src`:

```
E:\Users\Manuel\Documents\Projects\Node-Modules\TypeScriptESLintPlugin\src\index.ts
  0:0  error  Parsing error: File 'e:\users\manuel\documents\projects\node-modules\typescripteslintplugin\src\tsconfig.json' not found

✖ 1 problem (1 error, 0 warnings)
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.9.1-alpha.8` |
| `@typescript-eslint/parser`        | `2.9.0` |
| `TypeScript`                       | `3.7.2` |
| `ESLint`                           | `6.7.1` |
| `node`                             | `v12.4.0` |
| `npm`                              | `6.9.0` |

**Comment by manuth** [comment]
I just had a look at the source-code of `eslint` and as far as I can see there is no way for `eslint`-plugins to manipulate the configuration when the config-file is loaded:
https://github.com/eslint/eslint/blob/ca3b2a62c9e829dc4534bca3643d6bc729b46df0/lib/cli-engine/config-array-factory.js#L661-L670

Could you, in case this really is not possible, please update the configuration to suggest users to set the `project`-option to `path.join(__dirname, "tsconfig.json")` rather than `./tsconfig.json`?

Though, this might be a pity as this is only possible in `.js`-files.

**Comment by bradzacher** [comment]
As you have found, we do not know anything about the folder structure or config location.

As mentioned in #1254, eslint does not tell us anything at all at parse time - it essentially just gives us the location of the file, and that's it.
We don't know the directory of the config file, so we can't even work backwards from that (i.e. we can't do `path.join(configPath, parserOptions.project`).

This happens for good reason - you can put an eslintrc in every single folder if you want, and they are merged upwards until eslint finds a config with `root: true`.
So telling us the path of the eslintrc is meaningless, as there could be many in the chain, and any one of them could specify `parserOptions.project`.

Bit of a rant, but to your original point, have a look at the parser docs, which outline the available `parserOptions`:
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#configuration

Note the `tsconfigRootDir` option. This does exactly what you want.
