### ISSUE TITLE
Rule proposal: public async method requires try catch

### ISSUE THREAD

**Issue by JanFellner** [typescript-eslint/typescript-eslint#1293]
I am missing a rule to enforce coding style for async methods.

In our case we would like to enforce that **public async methods** in a module **always require a try catch** in order to have exceptions properly handled within the module and not having to deal with exceptions on the module "border".

**Bad**
```TS
	public async foo(): Promise<true> {
		return bar();
	}
```

**Good**
```TS
	public async foo(): Promise<boolean> {
		try {
			return await bar();
		} catch (error) {
			return false;
		}
	}
```

It´s basically a copy of the following rule idea but in the context of plain javascript with no public private access modifiers declarations it´s definitely hard to make use of it.
https://github.com/eslint/eslint/issues/7385

In the context with typescript i see a big benefit to enforce coding style and have properly defined module "borders".

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.9.0` |
| `@typescript-eslint/parser`        | `2.9.0` |
| `TypeScript`                       | `3.6.2` |
| `ESLint`                           | `6.7.1` |
| `node`                             | `12.13.0` |
| `npm`                              | `6.12.0` |

**Comment by bradzacher** [comment]
Why is a try/catch required in public async methods only?
Don't non async methods also throw exceptions that would need to be caught all the same?

I disagree with this rule on the premise that it swallows error messages and makes it literally impossible for the caller to get real feedback as to how/why a function failed.

And that's not a good coding practice to enforce.

I tend to agree with the comments on the original issue, that this rule can be implemented as a custom rule within your project.

**Comment by JanFellner** [comment]
If i have a promise returning function i would like to define results for the resolve (which is possible in typescript) but also for the reject case (which is from my point of view currently not possible). 

Thus i would like to wrap unhandled exceptions into dedicated result objects which let me define a proper interface for the module. 

This function will return X in resolve or Y in reject.

Sure, you could also handle that in the caller but tends to create ugly result checking methods. (if instanceof elif instanceof elif instanceof elif instanceof...)

Actually it would also be nice to have a rule to define that public methods also need to implement try catch but i do not see a rule for it. This rule would be enabled in the interface defining file for the module.

>I tend to agree with the comments on the original issue, that this rule can be implemented as a >custom rule within your project.
Never wrote one so the hurdle to do so is rather huge...

**Comment by bradzacher** [comment]
Raising an issue doesn't mean that a maintainer will do the work on your behalf (same with the eslint core repo). We are a community run project - we rely upon the community to raise PRs for features they want. The core maintainers exist to guide the project, and work on core functionality.

This rule seems like it is _very_ specific to your use case and code style, which means that you'd be the one that would have to implement it regardless.  

I just don't see anyone else getting much value, if any from this rule if it were implemented as part of this project. And for that reason, I'm going to reject this proposal.

---

It sounds daunting, but eslint rules are actually very simple to write. There's plenty of examples in this repo that you can learn from, and the eslint docs do a decent job of it as well.
