### ISSUE TITLE
how to parse pipeline-operator using babel

### ISSUE THREAD

**Issue by willin** [typescript-eslint/typescript-eslint#1304]
**What code were you trying to parse?**

```ts
let person = { score: 25 };

let newScore = person.score
  |> double
  |> add(7, ?)
  |> boundScore(0, 100, ?);
```

**What actually happened?**

```
Parsing error: /xxx/src/index.ts: Support for the experimental syntax 'partialApplication' isn't currently enabled (5:13):

  3 | let newScore = person.score
  4 |   |> double
> 5 |   |> add(7, ?)
    |             ^
  6 |   |> boundScore(0, 100, ?);
  7 |
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.10.0` |
| `TypeScript`                | `3.7.3` |
| `ESLint`                    | `6.7.2` |
| `node`                      | `13.2.0` |

ref: https://github.com/babel/babel-eslint/issues/543#issuecomment-561593382

**Comment by bradzacher** [comment]
Typescript doesn't support the pipeline operator.

I'm not sure why you're asking about parsing using babel here, we don't have anything to do with babel.
