### ISSUE TITLE
Allow to ignore certain file types

### ISSUE THREAD

**Issue by zedryas** [typescript-eslint/typescript-eslint#1323]
**What code were you trying to parse?**
Using `electron-forge` with template webpack, I need to specify an html file as template for later use by the CRA to feed the `HTMLWebpackPlugin`

The issue is when project is set within the eslint config, the html file is not recognized. If i had the `extraFileExtensions` option it then tries to parse the `html` file and produces the following error on `DOCTYPE` -> `Parsing error: '>' expected.`

**What did you expect to happen?**
Is it a way around that I did miss ? Is it possible to add an option to tell the parser to ignore certains files/files types ?

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.11.0` |
| `TypeScript`                | `3.7.3` |
| `ESLint`                    | `6.7.2` |
| `yarn`                      | `1.19.1` |

**Comment by bradzacher** [comment]
you can use a `.eslintignore`
https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories

Or you can use `overrides` in your eslint config.
https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns
