### ISSUE TITLE
[semi] is enabled by default therefore so should its replacement

### ISSUE THREAD

**Issue by villasv** [typescript-eslint/typescript-eslint#1334]
The `semi` rule is activated on ESLint by default, so even though I'm using the whole gang:

```
    "extends": [
      "eslint:recommended",
      "plugin:@typescript-eslint/eslint-recommended",
      "plugin:@typescript-eslint/recommended"
    ],
```

I still have to put that
```
      "semi": "off",
      "@typescript-eslint/semi": ["error"]
```

on my rules.

I understand that `semi` is not part of `eslint:recommended`, so it doesn't belong in `typescript-eslint/eslint-recommended`. It also doesn't belong in `typescript-eslint/recommended`. But it should be there somewhere. Maybe there should be another package like `typescript-eslint/default` that is equivalent of the default eslint rules but with the proper TypeScript overrides?

**Comment by platinumazure** [comment]
ESLint team member here. No rule is activated by default unless you're using ESLint 0.x or so. So if you are seeing it activated, there must be another config turning it on.

Make sure your top-level project config has `root: true` to avoid picking up other configurations in ancestor directories.

**Comment by villasv** [comment]
Hmm, sorry about the wrong assumptions. I’m going to hunt down where that rule is coming from.

I guess I should close things until I confirm there’s anything to be done in the scope of the plugin.

**Comment by bradzacher** [comment]
you can use the `--print-config` flag on eslint to see the entire resolved config for a file (it resolves all extended configs). This can help figure out what rules are actually turned on.
