### ISSUE TITLE
Can't find package @typescript-eslint/typescript-estree's version: 2.11.1-alpha.2

### ISSUE THREAD

**Issue by huminghao** [typescript-eslint/typescript-eslint#1339]
**What code were you trying to parse?**

```ts
none
```

**What did you expect to happen?**
npm install successfully

**What actually happened?**
npm install error
Error: [@umijs/fabric@1.2.4 › @typescript-eslint/parser@2.11.1-alpha.2 › @typescript-eslint/typescript-estree@2.11.1-alpha.2+f9a9fbfc] Can't find package @typescript-eslint/typescript-estree's version: 2.11.1-alpha.2

**Comment by bradzacher** [comment]
https://www.npmjs.com/package/@typescript-eslint/typescript-estree?activeTab=versions

We don't have a v2.11.1-alpha.2
