### ISSUE TITLE
Port rules from fimbullinter/wotan project

### ISSUE THREAD

**Issue by fobdy** [typescript-eslint/typescript-eslint#1359]
It seems that [wotan linter project](https://github.com/fimbullinter/wotan) has some [useful typescript rules](https://github.com/fimbullinter/wotan/tree/master/packages/mimir).
Could we take the best from there?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.11.0` |
| `@typescript-eslint/parser`        | `2.11.0` |
| `TypeScript`                       | `3.7.3` |
| `ESLint`                           | `6.7.2` |
| `node`                             | `12.12.0` |
| `yarn`                              | `1.19.1` |

**Comment by bradzacher** [comment]
Happy to accept PRs for any of those rules.
We are a community run project, so if people think there are any particularly good ones, happy to have them.

**Comment by bradzacher** [comment]
Rather than leaving this open - I'll close this.
As mentioned - if anyone wants to PR any of the rules - happy to have it.
