### ISSUE TITLE
Parser does not support @babel/plugin-proposal-optional-chaining

### ISSUE THREAD

**Issue by krousseau-cs** [typescript-eslint/typescript-eslint#136]
When using proposal-optional-chaining with babel, the typescript-eslint parser can not resolve the code. It throws the following error: "Parsing error: Expression expected"

err?.errors?.length

This parses correctly with babel-eslint parser.

More generally, is the plan to support all of the babel proposal plugins within typescript-eslint? Now that babel has first class support for typescript, using the 2 in conjunction will be a very common use case.

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | 1.1.0 |
| `TypeScript`                | 3.2.4 |
| `ESLint`                    | 5.12.1 |
| `node`                      | 10.13.0 |
| `npm`                       | 6.5.0 |

**Comment by armano2** [comment]
This is experimental feature, and its not supported by TypeScript. We are not extending capabilities of tsc.

**Comment by armano2** [comment]
This is experimental feature, and its not supported by TypeScript. We are not extending capabilities of tsc.

**Comment by krousseau-cs** [comment]
So basically there's still no way to use babel and typescript together and have it lint correctly? I can't use babel-eslint for a parser with typescript and typescript's parser is just not going to support proposals...

**Comment by JamesHenry** [comment]
Until last year, the TypeScript compiler was the way that TypeScript source code was parsed.

Now there are two ways:
- The TypeScript compiler
- `@babel/parser`

This is a fork in the road when it comes to parsing.

- `typescript-eslint` is a solution built on top of the TypeScript compiler "path"
- `babel-eslint` is a solution built on top of the babel "path"

It is great that we have more than one solution - but it is not possible to mix and match the parsing option from one and linting option from another right now (nor is there anything planned).

Please note, the TypeScript compiler is still the only way to type check your code. Babel parses and strips the type information, you still need the TypeScript compiler running if you want type checking.

**Comment by fatfatson** [comment]
I like this feature too.
actually the code could be compiled ok( by adding babel plugin to webpack),
just couldn't pass lint,
what a pity.
