### ISSUE TITLE
Rule suggestion: no unnecessary await

### ISSUE THREAD

**Issue by buu700** [typescript-eslint/typescript-eslint#1372]
Recent versions of vscode have been flagging occasional instances of unnecessary awaits in my code, where the value being awaited isn't actually a promise.

Having a rule to detect all of these while linting would be super useful. Aside from code cleanliness, this could also help catch a lot of bugs, e.g. someone might have accidentally awaited an observable without `.toPromise()`.

**Comment by bradzacher** [comment]
We already have a rule for this!

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/await-thenable.md

**Comment by buu700** [comment]
Ah, perfect, thanks!
