### ISSUE TITLE
Question: exposing types to ESLint?

### ISSUE THREAD

**Issue by amilajack** [typescript-eslint/typescript-eslint#1380]
Does this plugin expose the types of AST nodes to ESLint? Maybe by adding them as meta information?

**Comment by armano2** [comment]
expose the types of AST, can you clarify this?

ast nodes should be visible/traversable from eslint rules.
type definitions for ast nodes should be accessible from out package

----------------

unless by `types of AST nodes` you mean type-checking, if so than you can access it from parserServices. you can check how we accessing them in https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/util/getParserServices.ts

**Comment by bradzacher** [comment]
As Armano mentioned, your question is a bit vague.

If you want to consume type information from an eslint rule, then you can check out any of the number of examples within our plugin. If the user uses our parser `@typescript-eslint/parser`, then you can access the type information via `context.parserServices`.

If you're talking about types for help with building eslint rules, then you should again checkout how we do things within our plugin. You can consume `@typescript-eslint/experimental-utils` from your plugin, and in there you will find complete types for eslint and the typescript-estree AST.

Closing this as there's nothing actionable, but we can continue to discuss here.

**Comment by amilajack** [comment]
Thanks for the guidance! For context, I'm the author of `eslint-plugin-compat` which lints the compatibility of JS code. For accurate linting of code, we need to know the types of AST nodes.

For example:

```js
// type of foo is array, error
const foo = [];
foo.flatten()

// type of bar is obj, don't error
const bar = {};
bar.flatten()
```

Hopefully the extra context I added helps. Would love any recommendations or pointers!

**Comment by bradzacher** [comment]
So the problem you've got is that you need type information:
- which means they have to use our parser `@typescript-eslint/parser`,
- which means they have to setup their project for typescript,
- which means they will have typescript checking their project,
- which means this will be caught by their compiler `target`...

Which kind of devaluates the purpose of your plugin.

You can read through the docs of what's required for someone to use our parser here:
https://github.com/typescript-eslint/typescript-eslint/tree/master/docs/getting-started/linting

As an example of a rule that uses type information, you can have a look at [`strict-boolean-expressions`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/strict-boolean-expressions.ts#L59) and follow where `checker` is created and where it is used.
