### ISSUE TITLE
Lodash is deprecating per method packages

### ISSUE THREAD

**Issue by armano2** [typescript-eslint/typescript-eslint#1399]
Loadash is slowly deprecating "per module packages" in favor of single package that contains all of scripts.

currently we are using:
- `lodash.isplainobject` (dev) - droped in #1393
- `lodash.memoize`
- `lodash.unescape` - used in ts-estree

What are our plans for this? Do we want to drop `unescape` from dependencies or do we want to migrate to `lodash/unescape`.

### Reference:
- https://github.com/lodash/lodash/issues/3838
- https://lodash.com/per-method-packages

**Comment by bradzacher** [comment]
Do we need to drop the package or even upgrade it? What do we get from bothering to upgrade to v5?
It's not a large piece of code, so it's not like it's a security risk or anything.

**Comment by armano2** [comment]
keeping dependencies up to date reduces dependency tree of developers :> 

v5 is not yet live, this is just reminder that we should look into this
