### ISSUE TITLE
NodeJS v8 EOL at begin of Jan 2020

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#1420]
NodeJS v8 will fall out of maintenance at the end of Jan 2020.
ESLint will no doubt follow suit and drop support for it a few months after.

As we are planning on preparing a 3.0.0 release soon, we should consider dropping support as well, to save us being forced to do another major bump when ESLint drops support later.

https://github.com/nodejs/Release/blob/77fe085297e8d823f2475653e9eb2e9b2b2ffc3a/schedule.json#L34-L40

<p><img src="https://raw.githubusercontent.com/nodejs/Release/77fe085297e8d823f2475653e9eb2e9b2b2ffc3a/schedule.svg?sanitize=true" alt="LTS Schedule"/></p>

**Comment by glen-84** [comment]
It is already EOL (2019-12-31).

**Comment by bradzacher** [comment]
Note - eslint has dropped nodev8 https://github.com/eslint/eslint/pull/12700
It will be released in their 7.0.0 release.
