### ISSUE TITLE
[prefer-optional-chain] fixer produces wrong logic 

### ISSUE THREAD

**Issue by bradleyayers** [typescript-eslint/typescript-eslint#1438]
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/prefer-optional-chain": ["error"]
  }
}
```

```TS
declare const a: { b: string | null } | null;
a !== null && a.b !== null && a.b.length > 0;
/*
^^^^^^^^^^^^^^^^^^^^^^^^^^ Prefer using an optional chain expression instead, as it's more concise and easier to read.
*/
```

**Expected Result**

```TS
a?.b != null && a.b.length > 0;
```

**Actual Result**

```TS
a?.b !== null && a.b.length > 0;
/*
                 ^ Object is possibly 'null'.
*/
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.15.0` |
| `@typescript-eslint/parser`        | `2.15.0` |
| `TypeScript`                       | `3.7.3` |
| `ESLint`                           | `6.1.0` |
| `node`                             | `10.16.0` |
| `npm`                              | `6.9.0` |

**Comment by bradzacher** [comment]
interesting.
Types wise, this doesn't work because of the `!==`, `?.` produces an undefined. If you instead use `!= null`, then it's fine.

The root cause of this is due to a limitation in the logic that I have been wanting (needing) to fix in that it only allows `!=`/`!==` binary expressions.

**Comment by glen-84** [comment]
I have a similar issue, but I use strict `eqeqeq`, so I wouldn't want the fix to use `!=`.

```ts
if (coreStore.activeSiteSection && coreStore.activeSiteSection.backgroundImageUrl !== null) {}
```

Wants to change to:

```ts
if (coreStore.activeSiteSection?.backgroundImageUrl !== null) {}
```

... but this has different behaviour, because `undefined !== null`, so it would enter the block. It shouldn't flag this case.
