### ISSUE TITLE
(eslint-plugin) Bump ESLint major version in Peer Dependencies

### ISSUE THREAD

**Issue by adamelliotfields** [typescript-eslint/typescript-eslint#145]
When using ESLint v5, I've had no issues :+1:

However, with ESLint v4, I cannot get ESLint to locate the plugin. The following error is logged:

```
Oops! Something went wrong! :(

ESLint: 4.19.1.
ESLint couldn't find the plugin "eslint-plugin-@typescript-eslint".
```

I've tried a few variations of the naming, like "@typescript-eslint/eslint-plugin" and "@typescript-eslint/", to no avail.

**Since there's clearly a difference in the way ESLint v4 resolves plugins, would it be worthwhile to change the `peerDependencies` to `"eslint": ">=5 < 6"`?**

**Repro**

```bash
./node_modules/.bin/eslint src/**/*.ts
```

```JSON
{
  "extends": ["airbnb-base", "plugin:@typescript-eslint/recommended"],
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"],
  "settings": {
    "import/resolver": { "typescript": {} }
  }
}
```

**Versions**

| package                            | version  |
| ---------------------------------- | -------- |
| `@typescript-eslint/eslint-plugin` | `1.1.0`  |
| `@typescript-eslint/parser`        | `1.1.0`  |
| `TypeScript`                       | `3.2.4`  |
| `ESLint`                           | `4.19.1` |
| `node`                             | `8.4.0`  |
| `npm`                              | `5.3.0`  |

**Comment by bradzacher** [comment]
yeah they only added support for scoped plugins in eslint v5.
We talked about updating the dependency version, but forgot about it!

**Comment by adamelliotfields** [comment]
No worries Brad! I assume most people are running the latest version.

I’d be glad to submit a quick PR updating the `package.json` for each package, unless you want to wrap it into another feature you’re already working on.

**Comment by adamelliotfields** [comment]
I hear you!

I’ll get something up for review in a few hours - currently on the road.

Looks like I’ll need to update the plugin, parser, and tslint packages.
