### ISSUE TITLE
[@typescript-eslint/naming-convention] Fail with array spread syntax

### ISSUE THREAD

**Issue by bodinsamuel** [typescript-eslint/typescript-eslint#1466]
**Repro**

```JSON
{
  "rules": {
        "@typescript-eslint/naming-convention": [
          "error",
          { "selector": "variableLike", "format": ["camelCase"] },
        ],
  }
}
```

```TS
const [, shouldRender] = useState<object>({});
```

**Expected Result**
no error

**Actual Result**
```sh
TypeError: Cannot read property 'type' of null
Occurred while linting [...]/index.tsx:31
    at getIdentifiersFromPattern ([...]/node_modules/@typescript-eslint/eslint-plugin/dist/rules/naming-convention.js:458:21)
    at [...]/node_modules/@typescript-eslint/eslint-plugin/dist/rules/naming-convention.js:464:17
[...]
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.16.0` |
| `@typescript-eslint/parser`        | `2.16.0` |
| `TypeScript`                       | `3.7.4` |
| `ESLint`                           | `6.6.0` |
| `node`                             | `12.14.1` |
| `yarn`                              | `1.21.1` |

**Comment by armano2** [comment]
this issue got already addressed in #1450

**Comment by bodinsamuel** [comment]
oh closing then, this will be on next release I suppose ? ☺️ 💪

**Comment by armano2** [comment]
yes, (it should be monday) or you can use alpha version for now (for this few days)
https://github.com/typescript-eslint/typescript-eslint#package-versions
