### ISSUE TITLE
React Airbnb Styleguide setup

### ISSUE THREAD

**Issue by NikoMontana** [typescript-eslint/typescript-eslint#147]
I would like to know if it is possible to have a react / react-native typescript project with eslint and [airbnb-react](https://github.com/airbnb/javascript/tree/master/react) styleguide by using this lib?

**Comment by bradzacher** [comment]
Install the dependencies
```
yarn add -D eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-react @typescript-eslint/parser @typescript-eslint/eslint-plugin 
```

Then you can simply use the recommended config if you like:
```JSON
{
	"extends": ["airbnb", "plugin:@typescript-eslint/recommended"],
}
```

Otherwise, you can configure our plugin yourself:
```JSON
{
	"extends": ["airbnb"],
    "parser": "@typescript-eslint/parser",
	"plugins": ["@typescript-eslint"],
	"rules": {
		"@typescript-eslint/rule-name": "error"
	}
}
```

**Comment by jayychang** [comment]
I'm having trouble with a setup for a RN project.

Getting

```
error  Unable to resolve path to module 'src/*/*.ts' (any imports)
    import/no-unresolved
error  'react' should be listed in the project's dependencies. Run 'npm i -S react' to add it
    import/no-extraneous-dependencies
error  JSX not allowed in files with extension '.tsx'
    react/jsx-filename-extension
```

Not really sure whats causing this issue in the setup. Any help would be appreciated.

.babelrc
```
{
    "presets": ["module:metro-react-native-babel-preset"],
    "plugins": ["@babel/plugin-transform-runtime"]
}
```
.eslintrc.json
```
{
  "parser": "@typescript-eslint/parser",
  "plugins": [
    "react",
    "@typescript-eslint"
  ],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "useJSXTextNode": true,
    "project": "./tsconfig.json",
    "tsconfigRootDir": "./"
  },
  "extends": "airbnb",
  "rules": {
    "semi": "off",
    "quotes": "off",
    "no-underscore-dangle":"off",
    "comma-dangle":"off"
  }
}
```
rn-cli.config.js
```
module.exports = {
  getTransformModulePath() {
    return require.resolve('react-native-typescript-transformer');
  },
  getSourceExts() {
    return ['ts', 'tsx'];
  }
};
```
tsconfig.json
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "esModuleInterop": true,
    "jsx": "react-native",
    "lib": ["es6"],
    "moduleResolution": "node",
    "noEmit": true,
    "strict": true,
    "target": "esnext"
  },
  "exclude": [
    "node_modules"
  ]
}
```
package.json
```
    "@babel/runtime": "^7.2.0",
    ...
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@typescript-eslint/eslint-plugin": "^1.1.0",
    "@typescript-eslint/parser": "^1.1.0",
    "eslint": "^5.3.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.0",
    "eslint-watch": "^4.0.2",
    "metro-react-native-babel-preset": "0.51.1",
    "react-native-typescript-transformer": "^1.2.11",
    "typescript": "^3.2.2"
```

**Comment by bradzacher** [comment]
It would probably be good for us to document this considering it is probably a very common use case.

**Comment by aboyton** [comment]
I've added a PR that adds some instructions in #177. Feedback welcome.

To make it work on TSLint's codebase (you've got to try your instructions somewhere 😄) I had to disable `no-useless-constructor`, I'm guessing that this is due to #15.

```json
  "rules": {
    "no-useless-constructor": "off"
  }
```

**Comment by NikoMontana** [comment]
> ```
> yarn add -D eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-react @typescript-eslint/parser @typescript-eslint/eslint-plugin 
> ```

Sadly this did not work. I run that command after reverting the suggested commands.

```
npm install eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-react @typescript-eslint/parser @typescript-eslint/eslint-plugin --save -dev
```
Then I had to install some peer dependencies 

```
npm i -save -dev eslint-plugin-jsx-a11y@^6.1.1 acorn@^6.0.0
```

and extended .eslintrc.json with the suggestion

```
{
  "extends": ["airbnb", "plugin:@typescript-eslint/recommended"]
}
```

But the App.tsx does not get linted for airbnb styles. I setup VS-Code workspace settings with

```
```

**Comment by deskoh** [comment]
@bradzacher I refer to the following configuration.
```jsonc
{
	"extends": ["airbnb", "plugin:@typescript-eslint/recommended"],
}
```
This is allowing rules in `@typescript-eslint/recommended` to take precedence? In particular `indent`, `no-unused-vars` and `no-use-before-define` rules in `@typescript-eslint/recommended` are not similar to the equivalent ESLint rules in `airbnb`.

For TypeScript variant of Airbnb, I concluded that it would not be as straightforward, which is what I'm trying to achieve in my [repo](https://github.com/deskoh/eslint-ts-js).

**Comment by bradzacher** [comment]
No, it does work that way, because the base rule `indent` is a completely separate rule to our rule `@typescript-eslint/indent`.
So eslint doesn't share the config between them.

In our recommended, we do switch off the base rules that conflict, and turn on our version

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.json

however, note you'll lose airbnb's config for those rules, and it'll instead just use the default config for the rule.
