### ISSUE TITLE
[no-unused-vars] warnings for used vars

### ISSUE THREAD

**Issue by fairking** [typescript-eslint/typescript-eslint#1479]
**Repro**

```js
module.exports = {
	root: true,
	env: {
		node: true,
	},
	extends: ["eslint:recommended", "plugin:vue/recommended", "prettier", "prettier/vue", "@vue/typescript"],
	rules: {
		"no-console": process.env.NODE_ENV === "production" ? "error" : "off",
		"no-debugger": process.env.NODE_ENV === "production" ? "error" : "off",
		"no-unused-vars": "warn",
	},
	parserOptions: {
		parser: "@typescript-eslint/parser",
	},
	plugins: ["vue"],
	overrides: [
		{
			files: ["**/__tests__/*.{j,t}s?(x)"],
			env: {
				jest: true,
			},
		},
	],
};
```

```TS
import Vue, { DirectiveOptions } from "vue";
import AppSubmenu from "@/views/layouts/comps/AppSubmenu.vue";
Vue.directive("appsubmenu", <DirectiveOptions>AppSubmenu);
```

`warning: 'DirectiveOptions' is defined but never used (no-unused-vars)`

```TS
import { LoginTokenVm } from "@/services/index";
export class UserLoginStateVm {
	status: UserLoginStatus;
	user: LoginTokenVm;
	returnUrl: string;
}
```

`warning: 'LoginTokenVm' is defined but never used (no-unused-vars)`

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `^2.15.0` |
| `@typescript-eslint/parser`        | `^2.15.0` |
| `TypeScript`                       | `^3.7.4` |
| `ESLint`                           | `^6.8.0` |
| `node`                             | `12.14.1` |
| `npm`                              | `6.13.6` |

**Comment by fairking** [comment]
Might be related to https://github.com/typescript-eslint/typescript-eslint/issues/171

**Comment by fairking** [comment]
```TS
import Vue, { VNode } from "vue";

declare global {
	namespace JSX {
		// tslint:disable no-empty-interface
		interface Element extends VNode {}
		// tslint:disable no-empty-interface
		interface ElementClass extends Vue {}
		interface IntrinsicElements {
			[elem: string]: any;
		}
	}
}
```

`warning: 'Vue' is defined but never used (no-unused-vars)`
`warning: 'VNode' is defined but never used (no-unused-vars)`

**Comment by armano2** [comment]
`no-unused-vars` is not working for types at all, i was fixing it in #233 but i stopped because of time

**Comment by fairking** [comment]
ok, thanks @armano2. so I am probably going to disable the rule to suppress the noise and to be able to spot other important warnings. You can close the issue if you think it is not worth of spending time.

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-am-using-a-rule-from-eslint-core-and-it-doesnt-work-correctly-with-typescript-code

Please make sure you're using our version of the rule

**Comment by fairking** [comment]
Thanks @bradleyayers , Yeah, that's the `typescript-eslint`:
![image](https://user-images.githubusercontent.com/13495631/72776550-806a2180-3c0a-11ea-8394-8da3a59abc52.png)

**Comment by bradzacher** [comment]
This is a KP - the rule doesn't support things used in a type position well.
You should try the rule `no-unused-vars-experimental`, which uses typescript's tooling to report unused vars.

**Comment by bradzacher** [comment]
Merging into #1856
