### ISSUE TITLE
Add internal lint rule to guard against raw strings instead of `AST_NODE_TYPES`

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#1503]
We've gotten most of the cases, but it'd be good to guard against this explicitly in the codebase.

There are a few times where there were things like the following, which aren't strictly false at runtime, but we prefer to use the enums in the codebase.

```ts
if (node.type === 'Identifier') {}
```

An internal lint rule would mean we can add a fixer, and would save us ever having to mention this in code reviews.

**Comment by G-Rath** [comment]
Would love to be able to use this in `eslint-plugin-jest` as well (and my own custom TypeScript rules).

I've created such a rule for [my company's eslint configuration](https://github.com/squareweave/eslint-config-ackama/pull/19) - I'd welcome a review on it :)

If you've happy with that, I'll make a PR into here too.

**Comment by bradzacher** [comment]
hey man, that's literally the code that what I was going to write!
Happy to have it PR'd in here if you're willing. Thanks!!

**Comment by G-Rath** [comment]
@bradzacher No problem :)

I'll have a look at #315 for you as well, to see if I can get it across the line this weekend (or at least kick it a bit closer) :)
