### ISSUE TITLE
"Jest Test Current eslint-plugin Rule" does not trigger on Windows

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#1519]
**Repro**

1. `code .` in the root repository directory on a Windows 10 computer
2. Open an eslint-plugin rule
3. Press F5 to launch `Jest Test Current eslint-plugin Rule`

**Expected Result**

That rule's `.test.ts` file should be debugged.

**Actual Result**

On Windows, this does not happen.

**Additional Info**

Reverting the change in #432 fixes it 😄. This is a similar issue to #195. 

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | N/A |
| `@typescript-eslint/parser`        | N/A |
| `TypeScript`                       | N/A |
| `ESLint`                           | N/A |
| `node`                             | `12.0.0` |
| `npm`                              | `6.9.0` |

**Comment by armano2** [comment]
This seems to be an issue not only for eslint-plugin but also for other configurations 
- `Jest Test Current eslint-plugin-internal Rule`

you should try changing it to `"${fileBasename}"`
