### ISSUE TITLE
Rule proposal : no-unused-type-property - Creating a new rule 

### ISSUE THREAD

**Issue by eltonio450** [typescript-eslint/typescript-eslint#1529]
Hello everyone,

Following this post : https://stackoverflow.com/questions/59893208/find-unused-properties-in-destructured-parameter-object-in-typescript, I would like to propose my help to write a rule

I cannot find a rule that would work in this case, so I would like to implement and submit it, but the entry cost is a bit high so far, so if someone has a bit of experience and could show the direction, it would be very cool

### The Rule

The idea of the rule is to remove unused (local) type properties so that a fonction does not require unused params

For example:

```
//ts-error
const myIncompletelyRefactoredFunction = ({a, b}: {a: number, b: number, c: number}) => a + b
```

```
// ok
const myIncompletelyRefactoredFunction = ({a, b}: {a: number, b: number}) => a + b
```

```
//ts-error
type MyType = {
a: number, 
b: number, 
c: number
}

const myIncompletelyRefactoredFunction = ({a, b}: MyType) => a + b
```

```
//ok
export type MyType = {
a: number, 
b: number, 
c: number
}

const myIncompletelyRefactoredFunction = ({a, b}: MyType) => a + b
```

Our use case here is to catch the props that we forgot to remove from the type/interface of our react components (and from here, removing unused props along the React tree).

I guess this is not the only use case :)

### My questions :)

Would it be useful or did I miss something important about Typescript ?

Second, do you feel it is possible to implement with the current system ?

Third : it's very difficult to start writing rules, even testing them is not that easy :). I read some PR introducing rules, a few things on the ESLint repo too, but writing JS/TS code is not the same as working with AST/EStrees, etc. Could you please pin some good ressource to start with, which are compatible with the specificity of typescript-eslint ?

thank you very much for your help !

**Comment by bradzacher** [comment]
It sounds like an interesting rule, for sure, but it's hard to define exactly what it should do.

The examples you've provided suggest the rule only supports destructuring. What about usages of the object that aren't straight destructuring?
```ts
// property access
const myIncompletelyRefactoredFunction = (props: MyType) => props.a + props.b
// rest properties w/ access
const myIncompletelyRefactoredFunction = ({a, ...otherProps}: MyType) => a + otherProps.b
// arguments object usage
function myIncompletelyRefactoredFunction({a, b}: MyType) {
  return arguments[0].c + a;
}
// indirect usage
const myIncompletelyRefactoredFunction = (props: MyType) => Object.keys(props).reduce((acc, k) => acc + props[k], 0);
type MyType2 = { a: number, b: number, key: 'a' | 'b' }
const myIncompletelyRefactoredFunction = (props: MyType) => props[props.key]
```

What about if the type is used more than once, and different props are used in each location?
```ts
const myIncompletelyRefactoredFunction = ({a, b}: MyType) => a + b
const myIncompletelyRefactoredFunction = ({b, c}: MyType) => b + c
```
Does the rule report that `MyType.c` is unused in the first case, and `MyType.a` is unused in the second? Does it not report at all?

How would you expect that the rule would report an error. Would it report an error on the type, highlighting the unused properties on the type? Or would it report an error on the argument?
```ts
  type MyType = {
    a: number, 
    b: number, 
    c: number,
//  ^^^^^^^^^ Error: type property "c" is not used
  };

  const myIncompletelyRefactoredFunction = ({a, b}: MyType) => a + b
//                                          ^^^^^^ Error: Argument never uses MyType['c']
  const myIncompletelyRefactoredFunction = (props: MyType) => props.a + props.b
//                                          ^^^^^ Error: Argument never uses MyType['c']
```

> do you feel it is possible to implement with the current system

It depends on what you want. If you want to check a type across files and assert that all its properties are used, then no - that's not really possible AFAIK.

If you want to go with just ensuring an argument uses all of the properties on its type, then yes, parts of this is entirely possible. Though there are a lot of cases to handle (as I illustrated above).

> pointers to help

we don't have any documentation for writing rules. Any of the rules in our repo are good examples of writing rules. The readme points out rules that use type information, so you can look at rules that use types and rules that don't.

In terms of figuring out what an ast looks like. https://astexplorer.net/ is your best friend.
In terms of figuring out what types look like. https://ts-ast-viewer.com/# is your best friend.
In terms of writing rules and selectors, etc. The eslint docs are a good place to start. https://eslint.org/docs/developer-guide/working-with-rules

**Comment by eltonio450** [comment]
Hello,

thanks for the answer !

I'll have a look at the ressource, thanks

For the indirect usage, I guess it's not really possible to take them into account. 

For the direct usage : for me, exported types/interfaces must be excluded because of the complexity. Then, if the type is used more than once, I guess there could be a strict mode:

To comply with this mode, such functions
```
const myIncompletelyRefactoredFunction = ({a, b}: MyType) => a + b
const myIncompletelyRefactoredFunction = ({b, c}: MyType) => b + c
```

should be refactor in :

**Comment by eltonio450** [comment]
Hello,

thanks for the answer !

I'll have a look at the ressource, thanks

For the indirect usage, I guess it's not really possible to take them into account for now (as well as arguments object usage). 

For the direct usage : for me, exported types/interfaces must be excluded because of the complexity. Then, if the type is used more than once, I guess there could be a strict mode:

To comply with this mode, such functions
```
const myIncompletelyRefactoredFunction = ({a, b}: MyType) => a + b
const myIncompletelyRefactoredFunction = ({b, c}: MyType) => b + c
```
should be refactored in
```
const myIncompletelyRefactoredFunction = ({a, b}: Pick<MyType, 'a'|'b'>) => a + b
const myIncompletelyRefactoredFunction = ({b, c}: Pick<MyType, 'b' | 'c'>) => b + c
```

but I am not sure if it is relevant, especially because it could become difficult to work with excess properties

Anyway, I'll have a look at a simpler version, and from there, iterate

Thank you !

**Comment by moulikcipherX** [comment]
Hy @eltonio450 Are you working on this issue or can I proceed?

**Comment by bradzacher** [comment]
This one probably needs more discussion before implementation, as it looks to be a reasonably complex rule.
We should nail down the exact things it should report first.

**Comment by eltonio450** [comment]
@moulikcipherX I have still the motivation, but if you have time and want to take the lead, feel free. I'll be happy to contribute

@bradzacher we'll make a first try, and from there, iterate ?

I guess we can only apply the rule to non-exported interface/types

**Comment by bradzacher** [comment]
okay. well v0 lets just do this (keep it super simple):

1) check function parameters and parameter properties
1) if property is not an object destructuring, ignore it.
1) if destructuring has a rest parameter, ignore  it.
1) if the property's type is a union type, ignore it.
1) if the property's type is a non-object (or is an array) type, ignore it.
    - (this should always be true, but might as well double check)
1) for each property in the object type, ensure that the destructuring declares the properties in its object type.
    a) if the property is a destructuring `{a: {b}}`, goto (3)

That will catch the basic cases like this
```ts
type T = { a: string, b: { c: string, d: string } };
type T2 = { a: string };

// valid
function v1({ a, b } : T) {}
function v1({ a, ...rest } : T) {}
function v2({ a, b: { c, d } } : T) {}
function v3({ a } : T1 | T2) {}
function v1({ a } : Omit<T, 'b'>) {}
function v1(arg : T) {}

// invalid
function x({ a } : T) {}
function y({ a, b: { c } } : T) {}
```

I wouldn't worry about ensuring the type is not exported or anything; the error message can just say like
"Destructuring does not use all of the properties of the type `T`, you should either: remove the properties from the type, or use `Omit<T, ...>` to explicitly exclude the properties."

**Comment by eltonio450** [comment]
thanks for the guidance, I'll read a bit more about estree, etc, and start asap :)
