### ISSUE TITLE
@typescript-eslint/array-type Autofix

### ISSUE THREAD

**Issue by PSeitz** [typescript-eslint/typescript-eslint#1547]
In tslint this lint was available as quick fix, but here it is not available. Since it it is safe to autofix, I think this should be possible.
If someone points me in the right direction, I guess I could make an PR for this.

**Comment by armano2** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/array-type.ts

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/569259ef253048a0f9c69c83e3a91f501f1e19a7/packages/eslint-plugin/src/rules/array-type.ts#L226-L260

https://github.com/typescript-eslint/typescript-eslint/blob/569259ef253048a0f9c69c83e3a91f501f1e19a7/packages/eslint-plugin/src/rules/array-type.ts#L298-L300

https://github.com/typescript-eslint/typescript-eslint/blob/569259ef253048a0f9c69c83e3a91f501f1e19a7/packages/eslint-plugin/src/rules/array-type.ts#L322-L333


Unless I'm mistaken, this rule has a fixer. Could you let us know what's not working for you?

**Comment by PSeitz** [comment]
I'm using the "array-simple" option, where the fixer seems to be disabled/not implemented ?
https://github.com/typescript-eslint/typescript-eslint/blob/569259ef253048a0f9c69c83e3a91f501f1e19a7/packages/eslint-plugin/src/rules/array-type.ts#L306-L311

**Comment by bradzacher** [comment]
No, that if doesn't disable the fixer, that branches and stops reporting in a specific case.

As linked above, every single error report has a fixer.

Also look at the tests for the rule, all cases should have fixers. Search for your option, `array-simple` to see the error cases.

What specific cases are you finding are being reported on and not fixed?
Or what specific cases are you finding are not being reported?

**Comment by PSeitz** [comment]
Sorry, the auto-fix works. This is an issue with the vscode plugin. I didn't know it could fail only for some lints and work for others.
