### ISSUE TITLE
[camelcase] <Cannot disable for sending JSON requests>

### ISSUE THREAD

**Issue by maletor** [typescript-eslint/typescript-eslint#1554]
Often there is a need to send JSON in a request and inevitably that JSON has camel_case key names. One workaround is to convert the JS object to a string and calling JSON.parse or passing it as a raw string. Both not that great and error prone.

Are there any better workarounds?

**Comment by bradzacher** [comment]
Could you provide an example of what you mean?

**Comment by maletor** [comment]
`require("request-promise").post(body: { access_token: "asdf" })`

**Comment by bradzacher** [comment]
If you _have to have_ snake_case property names in your codebase, there are a few options.

1) add the names to the allowed names for properties - https://eslint.org/docs/rules/camelcase#options (the `allow` option)
1) disable the rule for properties - https://eslint.org/docs/rules/camelcase#options (`"properties": "never"`)
1) use an eslint disable comment on the line - https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments
