### ISSUE TITLE
Rule proposal: Prefer readonly member variables instead of getters that return literal values, or vice versa

### ISSUE THREAD

**Issue by c32hedge** [typescript-eslint/typescript-eslint#1556]
I'm finding a common pattern in our code:

```TS
  export class PageObject {
    get saveButton() {
      return '[data-testid="saveButton"]';
    }
  }
```

I would like to enforce using simple `readonly` members instead of getter functions:

```TS
  export class PageObject {
    readonly saveButton = '[data-testid="saveButton"]';
  }
```

This could also be applied to getter functions that return other literals, such as integers.

Some people prefer the reverse, so the rule should be bidirectional.

**Comment by sindresorhus** [comment]
I would prefer the inverse, as I make reusable packages that will be consumed by JS users too, and I want to ensure it can only be read from, not assigned.
