### ISSUE TITLE
'typedef/arrayDestructuring': impossible to follow this rule in `for/of` statement

### ISSUE THREAD

**Issue by TokugawaTakesi** [typescript-eslint/typescript-eslint#1564]
The rule `@typescript-eslint/typedef` with `arrayDestructuring` options tell me to annotate the type inside `for/of` statement:

![image](https://user-images.githubusercontent.com/41653501/73648718-80195e00-46c1-11ea-8528-550ad260bc3f.png)

However, it's impossible in TypeScript:

![image](https://user-images.githubusercontent.com/41653501/73648796-a6d79480-46c1-11ea-8c0d-3e9227966dbe.png)

It's required to define the exclusion for `for/of` (and, I suppose, `for/in`) statements.

```json
{
  "rules": {
    "@typescript-eslint/typedef": [
      "error",
      {
	  "arrayDestructuring": true,
	  "arrowParameter": true,
	  "memberVariableDeclaration": true,
	  "objectDestructuring": true,
	  "parameter": true,
	  "propertyDeclaration": true,
	  "variableDeclaration": true
	}
    ]
  }
}
```

```ts
const test: { 
  alpha: string, 
  bravo: string 
} = {
  alpha: "foo", 
  bravo: "bar"
};

for (const [ key, value ] of Object.entries(test)) {
  console.log(key);
  console.log(value);
}
```

**What did you expect to happen?**

Row `for (const [ key, value ] of Object.entries(test)) {` does not break the rule 'typedef/arrayDestructuring' because it's impossible to annotate types here in TypeScript.

**What actually happened?**
It is.

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`      | `2.19.0` (newest for the moment when I opened this issue) |
| `@typescript-eslint/parser`             | `2.19.0` (newest for the moment when I opened this issue) |
| `@typescript-eslint/typescript-estree`  | `2.19.0` |
| `@typescript-eslint/experimental-utils` | `2.19.0` |
| `TypeScript`                            | `3.7.5` (newest for the moment when I opened this issue) |
| `node`                                  | `12.14.1` |
| `npm`                                   | `6.3.14` |

**Comment by bradzacher** [comment]
The problem here is that the rule selects on `ArrayPattern` for `arrayDestructuring`, and doesn't check the parent like it does for `VariableDeclarator`.

Similar problem for the `objectDestructuring` option.

**Comment by TokugawaTakesi** [comment]
@bradzacher Thank you for the explanation about cause of this rule.
But also ask your team to fix this because it conflicts with TypeScript rules.

**Comment by bradzacher** [comment]
happy to accept a PR if you need it fixed urgently. It's a simple enough fix.

**Comment by TokugawaTakesi** [comment]
> happy to accept a PR if you need it fixed urgently. It's a simple enough fix.

I am very sorry to decline you invitation to `@typescript/eslint` development, but because of time shortage and fatigue, I have to do it FOR NOW. I want collaborate with you, but currently all can I do for you is bug reporting. Please understand, and see you next time.

**Comment by a-tarasyuk** [comment]
Additional cases 

```ts
for (const [[[key]]] of [[['key']]]) {}
for (const [[[{ key }]]] of [[[{ key: 'value' }]]]) {}

for (const {p1: {p2: { p3 }}} of {p1: {p2: {p3: 'value'}}}) {}
for (const {p1: {p2: { p3: [key] }}} of {p1: {p2: {p3: ['value']}}}) {}
```

```
const [[[{ key }]]]: [[[{ key: string ]]] = [[[{ key: 'value' }]]]
```

Taken from https://github.com/typescript-eslint/typescript-eslint/pull/1570#discussion_r377743287
