### ISSUE TITLE
Does this rule exist? Non-existent types

### ISSUE THREAD

**Issue by rodoabad** [typescript-eslint/typescript-eslint#1568]
<img width="945" alt="Screen Shot 2020-02-04 at 11 59 27 AM" src="https://user-images.githubusercontent.com/1240667/73772613-168f6300-4746-11ea-90f5-dc732ef81992.png">

Is there a rule that will prevent this? I'm currently using babel and eslint with the recommended rule but I want to enforce strictness here where the type has to be defined.

**Comment by bradzacher** [comment]
Sorry, what do you mean?

Are you are saying you want a lint rule for the typescript error?

**Comment by armano2** [comment]
no there is no rule like that, because typescript reports this error.

babel is **not supported**, we do not intend to add rules that will duplicate errors reported by typescript.

> *note:* most of rules that does not require type informations should work with babel as parser
> but as for now we are not testing this use case of plugin.
