### ISSUE TITLE
[Question]: error have been still reported after fixed

### ISSUE THREAD

**Issue by yoyo837** [typescript-eslint/typescript-eslint#1590]
First, sorry for my poor english.

**step:**
1.  Change the code to make some typing compilation errors.
2. `[tsl]` report errors
3.  Change the code to fix it.
4. `[tsl]` till report errors
5. stop `webpack-dev-server` and restart, it no longer reports any errors.

What did I miss？If anyone knows, please tell me, thanks!

**Versions**

| package                                   | version |
| ----------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin-tslint` | `2.19.2` |
| `@typescript-eslint/parser`               | `2.19.2` |
| `TypeScript`                              | `3.7.5` |
| `ESLint`                                  | `6.8.0` |
| `node`                                    | `12.15.0` |
| `npm`                                     | `6.13.4` |

**Comment by bradzacher** [comment]
What is `[tsl]`?

**Comment by yoyo837** [comment]
I guess it is `ts-loader`,  thanks for your reply.

**Comment by yoyo837** [comment]
Or it is means `typescript-eslint`. 🤔

**Comment by bradzacher** [comment]
I'm not sure. We don't use the acronym `tsl` anywhere, so if it does mean our project, it wasn't us that logged that message.

We don't own any integration with webpack.
`ts-loader` doesn't integrate with eslint afaik.
`eslint-loader` does, but that doesn't match the acronym.

you'll have to do some digging to figure out where the log messages are coming from.

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/74213709-6dacaf00-4cd5-11ea-936f-5f03a17a8f47.png)

If I remove `eslint-loader` from the `webpack` config file, it will not report any errors, even if the IDE reports lint errors for the `ts|tsx` file.

**Comment by yoyo837** [comment]
So, `tsl` is `typescript-eslint`, i think.

**Comment by bradzacher** [comment]
`TS2339` is a typescript error that's output via the typescript typechecker.
TypeScript is the only tool that attaches error codes.

So this is 100% not a TSLint or ESLint error.

**Comment by yoyo837** [comment]
Well, if so, I don't know what to do next.

Thanks your time.
