### ISSUE TITLE
new rule suggestion: force-return-await (opposite of no-return-await)

### ISSUE THREAD

**Issue by benny-medflyt** [typescript-eslint/typescript-eslint#1621]
Hello, I am copying this issue from <https://github.com/palantir/tslint/issues/4913> because tslint is deprecated in favor of this package.

The [no-return-await](https://palantir.github.io/tslint/rules/no-return-await/) rule explains that the benefit of omitting the "await" is increased performance.

However, despite the (minor) performance decrease, there is a major benefit to always use "return await": You get a correct full stack trace in recent versions of node and v8. If you omit the "await" then the stack frame disappears from the stack trace and it makes it very difficult to trace down where exceptions came from.

This benefit alone is worth it for some projects to always enforce usage of "return await".

There is another benefit that is a small subtle edge case, but when it does bite you it can hurt you hard:

Let's say I have code like this, where `dostuff` is an async operation (`dostuff` returns a Promise):

```typescript
async function foo(): Promise<number> {
    const x = await blah();
    return dostuff(x);
}
```

The above code behaves the same if I write either "return" or "return await" at the end. But let's say later on some other developer modifies the code to handle the case where `dostuff` might throw, so they change the code to this:

```typescript
async function foo(): Promise<number> {
    const x = await blah();
    try {
        return dostuff(x);
    } catch (err) {
        return 0;
    }
}
```

Now the code has a very serious but subtle bug. If `dostuff` throws while doing its async work, then the exception will actually be thrown from outside of this function(from whoever called `foo`), in other words the exception will "escape" the try/catch block.

This type of scenario is especially evil since try/catch blocks are usually not tested thoroughly enough, so the developer believes that the code is correct because she added a try/catch block, without realizing that it will be completely bypassed. If "return await" was used then the exception would be properly caught. This issue for me is also motivation enough to always use "return await" just to be sure I never have to worry about this or think about it at all.

**Comment by bradzacher** [comment]
See our rule, return-await.
It ha an option to do exactly this.

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/return-await.md
