### ISSUE TITLE
[no-unused-vars] does not handle JSX?

### ISSUE THREAD

**Issue by mightyiam** [typescript-eslint/typescript-eslint#1623]
From https://github.com/typescript-eslint/typescript-eslint/issues/1596#issuecomment-589170352.

**Repro**

Open source reproduction. Just remove [this disable comment](https://github.com/snabbdom/snabbdom/blob/9d0201d9975ee9755ee04117461387f8bf5bbc68/src/test/jsx.tsx#L3-L4).

**Expected Result**

No hit.

**Actual Result**

Hit.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.20.0` |
| `@typescript-eslint/parser`        | `2.20.0` |
| `TypeScript`                       | `3.7.2` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `12.10.0` |
| `npm`                              | Most likely `6.13.7` |

**Comment by bradzacher** [comment]
This is by design.
The `no-unused-vars` rule is not intended to understand the semantics of JSX.

You should consider adding the rules from eslint-plugin-react to augment the rule
https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-uses-react.md
