### ISSUE TITLE
[no-use-before-define] typedefs option must include `typeof value`

### ISSUE THREAD

**Issue by aravindanve** [typescript-eslint/typescript-eslint#1625]
**Repro**

I am trying to use a value as a **type** before it is defined. i.e. `typeof bar`

```JSON
{
  "rules": {
    "@typescript-eslint/<rule>": ["error", { "typedefs": false }]
  }
}
```

```TS
type Foo = ReturnType<typeof bar>;
const bar = (): string => 'baz';
```

**Expected Result**

ESLint should not throw an exception.

**Actual Result**

```bash
'bar' was used before it was defined. eslint(@typescript-eslint/no-use-before-define)
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.20.0` |
| `@typescript-eslint/parser`        | `2.20.0` |
| `TypeScript`                       | `3.7.5` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `12.8.0` |
| `npm`                              | `6.13.7` |

**Comment by bradzacher** [comment]
The typedefs option does exactly what you want.

Otherwise the rule is working exactly as expected - you are using a variable before it is defined.
The options exist so that you can configure the rule to ignore certain context in which you are okay with usage before defined.
