### ISSUE TITLE
Update ROADMAP with no-reference-import TSLint equivalent

### ISSUE THREAD

**Issue by KingDarBoja** [typescript-eslint/typescript-eslint#1627]
**What were you trying to do?**

I successfully ran the [tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config) but noticed there was a rule that hasn't an equivalent:

`tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-reference-import"`

This rule is defined at [`tslint:recommended`](https://github.com/palantir/tslint/blob/master/src/configs/recommended.ts), which was present on the extends array on my `tslint.json` file.
```
"no-reference-import": true
```

I think there is a rule already handling this one as discussed at #625.

However, would be great to update the roadmap with this rule equivalent and same applies for other rules.

Cheers!

**Comment by bradzacher** [comment]
cc @JoshuaKGoldberg
