### ISSUE TITLE
Need to exclude Angular .html template files from linting

### ISSUE THREAD

**Issue by Hermholtz** [typescript-eslint/typescript-eslint#1656]
Angular community is suggesting to move away from tslint in favor of eslint. However configuring eslint with Angular 8 or 9 project results in the following error (in VS Code) with first character of first line of HTML template file underlined in red.

```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: apps\myapp\src\components\my.component.html.
The extension for the file (.html) is non-standard. You should add "parserOptions.extraFileExtensions" to your config.
```

These packages were installed yesterday:

```
    "eslint": "^6.8.0",
    "eslint-plugin-angular": "^4.0.1",
    "angular-tslint-rules": "^1.20.3",
    "babel-eslint": "^10.1.0",
    "@typescript-eslint/eslint-plugin": "^2.21.0",
    "@typescript-eslint/eslint-plugin-tslint": "^2.21.0",
    "@typescript-eslint/parser": "^2.21.0",
```

How do I exclude Angular components (html and css files) from ESLint?

**Comment by bradzacher** [comment]
What does you're cli command look like when running the lint?

What does your eslint config look like?

**Comment by Hermholtz** [comment]
Sorry please delete this if you wish.
File name extensions handled by ESLint are set in VSCode settings.
I think this ESLint/TSLint/TypeScript/WebPack/NPM/VSCode thing with all its thousands parsers, rules, sub-packages, various kind of bridges and plugins has grown too big for me to grasp...
