### ISSUE TITLE
[custom rule] <How can I get declare type of one Identifier ? >

### ISSUE THREAD

**Issue by relign** [typescript-eslint/typescript-eslint#1671]
Now，I'm developing custom rules of `typescript-eslint/eslint-plugin`. I want get   declare type of a 
 Identifier.
Here are two files，I  define the type in `props.ts`.
```typescript
// props.ts
export interface UserInfo {
  name: string;
  id: number;
}
```

And I check code in `index.tsx`,  I want get  declare interface type of `userInfo`, and check type of `userInfo.name`.  How to do this? looking forward to help.

```typescript
// index.tsx
import { UserInfo } from './Props'
export class Demo extends Component {
  render () {
    const userInfo: UserInfo = {
      name: 'zhangsan',
      id: 123
    }

   return (
     <View>
      {  userInfo.name && <View></View>  } 
   </View>
  )
  }
}
```

**Comment by bradzacher** [comment]
Hey there @relign 

I'd suggest having a look at the rules we have implemented in this repo.
There's a list of rules here, and you can browse their source code. There's heaps of examples for how to consume type information.

https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules

**Comment by relign** [comment]
@bradzacher Can you recommend a rule related to getting a type defined by another file in one file? I'm going to read the code for this rule. Thanks~

**Comment by bradzacher** [comment]
Any of the rules with a 💭 next to them in the table use type information, and thus have code which pulls the type.

Another option for learning the API is via https://ts-ast-viewer.com
You can input code, and then open up your browser's console and play with the `checker` api that way.

**Comment by relign** [comment]
Thanks very much
