### ISSUE TITLE
Interactive examples / playground

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#168]
Spawning off of the discussions in #125, logging it separately for visibility

Would be good if we can setup an interactive playground like https://mysticatea.github.io/vue-eslint-demo/

Similarly it would be good if we can add interactive examples to our docs like eslint-plugin-es: https://mysticatea.github.io/eslint-plugin-es/rules/no-json-superset.html

Both of these would of course require us to generate and deploy some form of a website.

The former would definitely be helpful in having users give us concrete REPLs for their bugs, and the latter is nicer than having to manually annotate static markdown codeblocks.

**Comment by j-f1** [comment]
We could merge the `typescript-eslint.io` website as a package here, then deploy from it.

**Comment by mysticatea** [comment]
I'm working on this.

A prototype of playground is here: [https://mysticatea.github.io/typescript-eslint-demo/](https://mysticatea.github.io/typescript-eslint-demo/#eJyNlU1v2zAMhv+KoUtTLMqAYacGBQYUw3bvjr7IEpOqkSlPott6Rf/7KMlOV2BW60ss6yH18kPMs9DegLgS2qkYmx8BgCA0zy02/BzT0uLxqokU+HffYtnQHvnLqMmHTQ8xqiMszOVinB66s3G3eGmum5ndF+JlcZeJzRvLADQGbFrxE5zzW35pPr119+ok+3FAxQ/Lv24QHpdgNq149MGZVlzuF7AbiTwyZ7wee0Da6QCK4LuDtNpcFOAiWZTXHcET3Xgk3ma7VtyqqcnaWvEKedTO6hMDhxE1WY+vUSkHgTazxN0ccjogyz8L6byZdmoYAM3NnXVmU1xf7sVWhNFBFFfP4htNA0Qd7EASorNIn5W5V5odSP8AwXllZLRHVJzFZPJl+1+bENQk0/c1olOY91ddaNWD0yquesiNJZExyRjXbQ2Ep4FzZ0kuqZOlB6r6zkY99B0EqbTmFrOddZamNaMjIASrs+OkrCLKouGcru9yKQ+c9hLfEOBgn9bgWaEBZ3vLdjLS5FYDm+m6uhnywUCoYOilwqMD2QWlT0AlcC4LNyTnuWaWG+Sf215hoR9okueU1MilaApXa5QxCgrBj1HmJqqgFg/AUjuOsdqtjPY2jhGM5AlRoVI941APA7lFcXTuQ5n03T1oki5VXrmPV2BQgaWkdhmCHxJejS5NSKmcVVWI15ypyEm940vGqQOsRlrUvuN1xJzXBxWqVOQ2hIMPwDfhYLF2LLtieb9HWxlhQ9b/ftvN3Lmu8gQT/y2YNb6EjOhJ5VmUjMoVe9mKMhVu7R8+7uuy/JXHlChd8/IXkLSpng==)

Currently, there are some limitations:

- we cannot use JSX syntax in the playground.
- `@typescript-eslint/restrict-plus-operands` rule doesn't work.

**Comment by JamesHenry** [comment]
@mysticatea Awesome! When do you think you will be able to share the code?

**Comment by glen-84** [comment]
`typescript-eslint-demo` doesn't seem to include `no-floating-promises`, and the dependencies are outdated as well.
