### ISSUE TITLE
Specifying parserOptions.project in shared eslint configuration

### ISSUE THREAD

**Issue by alfechner** [typescript-eslint/typescript-eslint#1681]
We have a shared eslint config package in our mono repo. The structure like this:

```
shared-eslint-config
 |_ .eslintrc.js
package-a
 |_ .eslintrc.js
package-b
 |_ .eslintrc.js
```

The `.eslintrc.js` of `pacakge-a` and `package-b` both extend the configuration in `shared-eslint-config`.

If I configure the parser in `shared-eslint-config` it works for this package only. If I try to override the parser options in the `.eslintrc.js` files of  `pacakge-a` and `package-b` I see an error saying the parser options have been set.

How can I specify the parserOptions.project in `pacakge-a` and `package-b`?

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.22.0` |
| `TypeScript`                | `^3.7.4` |
| `ESLint`                    | `6.8.0` |
| `node`                      | `v12.14.1` |
| `npm`                       | `6.13.4` |

**Comment by bradzacher** [comment]
It would help if you dumped your current ESLint config, so I can better understand what your environment looks like, and what you've already tried.
Help me to help you.

----

Based on what you've given me, have you tried using `tsconfigRootDir`?
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#tsconfigrootdir

```
parserOptions: {
  project: ['./package-a/tsconfig.json', './package-b/tsconfig.json'],
  tsconfigRootDir: path.resolve(__dirname, '../'),
}
```

or if you are looking to isolate each project, just have each project's eslintrc specify the parserOptions itself:
```
parserOptions: {
  project: ['./tsconfig.json'],
  tsconfigRootDir: __dirname,
}
```

**Comment by alfechner** [comment]
Thanks @bradzacher , the later approach is pretty much what I was looking for.

However, `package-a` holds two TS config files: (1) `tsconfig.json` and (2) `tsconfig.stroybook.json`, `package-b` only `tsconfig.json`.

So specifying both will fail in `package-a` probably, right?

**Comment by bradzacher** [comment]
You can specify as many or as few tsconfigs as you need.
The only requirement is that the tsconfigs you provide `include` the complete set of files you want to lint _with type information_.

Example, our tsconfig, which includes every single tsconfig in a single root eslintrc:
https://github.com/typescript-eslint/typescript-eslint/blob/e5db36f140b6463965858ad4ed77f71a9a00c5a7/.eslintrc.js#L134-L135

---

It's perfectly valid to fragment your config such that `shared-eslint-config` doesn't need a tsconfig.json, and it doesn't need `parserOptions.project`, as long as you don't attempt to use lint rules on `shared-eslint-config` that require type information.

People often achieve this via `overrides`
https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns

**Comment by alfechner** [comment]
@bradzacher I understand.

The idea behind the shared config is of course to not repeat the configuration all the time. I'd like to configure as much as possible in my shared global config file.

The `project` setting is very project specific. The definition of the linting rules related to type information in turn is more general.

Regarding overrides: is there a way to tell eslint to not use any type information related rule for certain files? It feels pretty cumbersome to disable those rules one by one.

**Comment by alfechner** [comment]
I solved my use case indeed with using `tsconfigRootDir`. For any reason I assumed that I cannot override it in the inheriting eslint configs. I don't know why. It works though.

Thanks for the advice @bradzacher.

**Comment by bradzacher** [comment]
> Regarding overrides: is there a way to tell eslint to not use any type information related rule for certain files? It feels pretty cumbersome to disable those rules one by one

When you want to turn off a bunch of rules for specific files, you should look to invert the problem.
Have a minimal base config, and then use overrides to turn on the rules you want for specific files.
That way it's easier to maintain, as you don't have to remember to turn on a rule in one place, and turn off the same rule in another.
