### ISSUE TITLE
[type-annotation-spacing] Interprets arrow as colon

### ISSUE THREAD

**Issue by jens-duttke** [typescript-eslint/typescript-eslint#1687]
With version 2.22.0 a bug has been introduced which interprets `=>` as colon, and tells me, that there is an unexpected space before the `=>`.

If i set an override for `colon` this specific error is gone, but then it expects a space before all colons.

**Repro**
```
type WebpackWorker = new () => Worker;
```

```JSON
{
  "rules": {
    "@typescript-eslint/type-annotation-spacing": "error"
  }
}
```

**Additional Info**

Returns
```
Unexpected space before the '=>'. [Error/@typescript-eslint/type-annotation-spacing]
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.22.0` |
| `@typescript-eslint/parser`        | `2.22.0` |
| `TypeScript`                       | `3.8.3` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `13.6.0` |
| `npm`                              | `6.13.7` |

**Comment by bradzacher** [comment]
Please use the issue search.
#1663 this has been fixed in master.
