### ISSUE TITLE
[no-unused-vars] warning for used vars

### ISSUE THREAD

**Issue by jzilg** [typescript-eslint/typescript-eslint#171]
**Repro**

I get many alerts from eslint because I have supposedly unused variables. For Example in this File.

```TS
import React, { ReactElement } from 'react'
import Todo from '../../interfaces/todo.interface'
import TodoListItem from '../TodoListItem'
import style from './todo-list.scss'

interface ListProps {
    todos: Todo[]
    addTodo: Function
    saveTodo: Function
    removeTodo: Function
    isLoading: boolean
}

const TodoList = ({
    todos,
    addTodo,
    saveTodo,
    removeTodo,
    isLoading,
}: ListProps): ReactElement<{}> => {
    const createNewId = (): number => {
        if (!todos.length) {
            return 0
        }
        const ids = todos.map(todo => todo.id)
        const highestId = Math.max(...ids)
        return highestId + 1
    }

    const addNewTodo = (): void => {
        const id = createNewId()
        addTodo(id)
    }

    const todoElements = todos.map(todo => (
        <li key={todo.id} className={style['list-element']}>
            <TodoListItem
                todo={todo}
                saveTodo={saveTodo}
                removeTodo={removeTodo}
                isLoading={isLoading}
            />
        </li>
    ))

    return (
        <div className="container">
            <h1>
                Todo List
            </h1>
            <ul className={style.list}>
                {todoElements}
            </ul>
            <button
                type="button"
                className={style['add-todo-btn']}
                title="Add Todo"
                onClick={addNewTodo}
                disabled={isLoading}
            >
                +
            </button>
        </div>
    )
}

export default TodoList

```

**Expected Result**
no eslint warnings, scince all variables are used at some point.

**Actual Result**
   4:8   warning  'style' is defined but never used                @typescript-eslint/no-unused-vars
  17:5   warning  'saveTodo' is defined but never used             @typescript-eslint/no-unused-vars
  18:5   warning  'removeTodo' is defined but never used           @typescript-eslint/no-unused-vars
  19:5   warning  'isLoading' is defined but never used            @typescript-eslint/no-unused-vars
  30:11  warning  'addNewTodo' is assigned a value but never used  @typescript-eslint/no-unused-vars
  35:36  warning  'todo' is defined but never used                 @typescript-eslint/no-unused-vars

**Additional Info**
I just migrated from https://www.npmjs.com/package/eslint-plugin-typescript. While using that package, there was no warnings.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.1.1` |
| `@typescript-eslint/parser`        | `1.1.1` |
| `TypeScript`                       | `3.2.4` |
| `ESLint`                           | `5.12.1` |
| `node`                             | `10.14.1` |
| `npm`                              | `6.5.0` |

**Comment by runeh** [comment]
We have the same issue. Workaround is to lock `@typescript-eslint/parser` to version 1.1.0. Something changed in the 1.1.1 patch version.

**Comment by bradzacher** [comment]
As this has been fixed, I'll close this issue.

**Comment by gabemeola** [comment]
Still receiving this error as of `1.2.0`

**Comment by bradzacher** [comment]
@gabemeola there are a number of false positive cases for no-unused-vars.
Just commenting "still receiving this error" isn't very helpful when the OP listed 6 separate cases.
Which case exactly? One, or all of them?

Please open a new issue with a code sample, so we can investigate appropriately.
