### ISSUE TITLE
Question: implicit "any" from "yield" warning?

### ISSUE THREAD

**Issue by Vanuan** [typescript-eslint/typescript-eslint#1715]
Is it feasible to add a warning for yield result to be assigned to non-typed variable or as non-typed argument?

TypeScript doesn't always infer the yield return type:

https://github.com/microsoft/TypeScript/issues/26959

**Comment by bradzacher** [comment]
This will be handled more broadly by the `no-unsafe-*` set of rules I've been building.

- [no-unsafe-call](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unsafe-call.md)
- [no-unsafe-member-access](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unsafe-member-access.md)
- [no-unsafe-return](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unsafe-return.md)
- And the not yet merged no-unsafe-assignment https://github.com/typescript-eslint/typescript-eslint/pull/1694

**Comment by Vanuan** [comment]
Awesome! Would it also handle unsafe array indexing?

**Comment by bradzacher** [comment]
Yes, no-unsafe-member-access handles that as well.

**Comment by Vanuan** [comment]
Example:

```
const a: number[] = [];
const b: number | null = a[0] || null;
b.toFixed(); // runtime error, no type error
```

**Comment by Vanuan** [comment]
More complex example:

```
interface MyType { 
    id: string;
}
interface MyOtherType {
    arrayField: MyType[];
}
const myObject = {
interface SimpleType { 
    id: string;
}
interface ComplexType {
    arrayField: SimpleType[];
}
const myObject = {
    arrayField: [],
}
const a: SimpleType[] = myObject.arrayField;
const b: SimpleType | null = a[0] || null;
b.id; // runtime error, no type error, should be Object is possibly 'null'.


```

**Comment by Vanuan** [comment]
Well, it looks like the latter is a bug in TypeScript. The type error is working for primitive type, but not for user-defined types.

**Comment by bradzacher** [comment]
Ah that's what you meant by unsafe indexing.
No, there's no rule for that. That sort of thing ideally has to be built into typescript itself, as  it requires control-flow analysis of the variable.

You could also encode this in the types, and ban member expressions on non-tuple arrays.

```ts
function hasLength<T>(n: 1, arr: T[]): arr is [T, ...T[]];
function hasLength<T>(n: 2, arr: T[]): arr is [T, T, ...T[]];
function hasLength<T>(n: 3, arr: T[]): arr is [T, T, T, ...T[]];
// ....
function hasLength<T>(n: number, arr: T[]): arr is T[] {
    return arr.length === n;
};

declare const x: number[];

const y = hasLength(2, x); // typeof y === [number, number, ...number[]];

x[0] // hypothetical-lint-rule-error: No array index access, use hasLength to validate the length first
y[0] // no error, as it's provably safe
```
