### ISSUE TITLE
Review handling of generically constrained types across rules

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#1721]
@G-Rath noted in #1707 that a generic type is not really that useful, as it does not satisfy things like `checker.isArrayType`.

We should look to instead using `util.getConstrainedTypeAtLocation` in our codebase to ensure that we are properly fetching the constrained type from the generic type, instead of using the generic type directly.

I don't know if all rules care about if it's a generic type or not, so it'll take some eyeballing.

Depending on the result of the review, it might make sense to introduce an internal lint rule to help us remember as well.

**Comment by JoshuaKGoldberg** [comment]
Since this issue I think we've had a handful of reports that were solved by `util.getConstrainedTypeAtLocation`. Closing to trim out the issue queue.
