### ISSUE TITLE
[prefer-function-type] Quick fixing an interface using this causes tsc error

### ISSUE THREAD

**Issue by cherryblossom000** [typescript-eslint/typescript-eslint#1756]
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/prefer-function-type": 2
  }
}
```

```ts
interface Interface {(): this}
```

**Expected Result**
No error as `this` can only be used in a class or interface.

**Actual Result**

```
/path/to/file.ts
  1:22  error  Interface has only a call signature - use 'type Interface = () => this' instead  @typescript-eslint/prefer-function-type

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

**Additional Info**

Running eslint with `--fix` results in this code:
```ts
type Interface = () => this
```

which causes a `tsc` error:

```
file.ts:1:24 - error TS2526: A 'this' type is available only in a non-static member of a class or interface.

1 type Interface = () => this
                         ~~~~


Found 1 error.
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.24.0` |
| `@typescript-eslint/parser`        | `2.24.0` |
| `TypeScript`                       | `3.7.5` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `12.11.0` |
| `npm`                              | `6.11.3` |

**Comment by bradzacher** [comment]
Should be a real easy fix to check if the return type is the `TSThisType`, and ignore it in that case.
Happy to accept a PR!

**Comment by cherryblossom000** [comment]
@bradzacher Ok, I’ll work on this. I’ll also need to check if any of the parameter types is `TSThisType`.

**Comment by bradzacher** [comment]
Thinking about it, this _could_ be reported as an error still, but without an automatic fixer.
Instead of an automatic fixer, it could do a suggestion fixer, which can only be manually applied via an IDE.

The suggestion fixer could convert it to a "recursive type", i.e.:

```ts
interface Interface {(arg: this): this}

// fixed to

type Interface = (arg: Interface) => Interface;
```

Additionally, this functionaltiy could be put behind a flag which is default true (backwards compatible). So that codebases that are okay with interfaces with `this` methods, can opt out of reporting on them.

**Comment by cherryblossom000** [comment]
Could someone else work on this? Checking if the interface contains `this` is a bit more complicated than I anticipated.
