### ISSUE TITLE
Receiving Parsing error: not implemented on v2.24.0

### ISSUE THREAD

**Issue by biehlerj** [typescript-eslint/typescript-eslint#1759]
**What code were you trying to parse?**

```ts
import { app, ipcMain } from 'electron';
```

**What did you expect to happen?**

No error on the first line of code

**What actually happened?**

Received an error stating `Parsing error: not implemented`

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.24.0` |
| `TypeScript`                | `3.2.2` |
| `ESLint`                    | `^6.8.0` |
| `node`                      | `12.6.1` |
| `npm`                       | `6.13.4` |

When I manually pin my `@typescript-eslint/parser` dependency to `2.23.0` that error no longer happens and eslint uses the rules in the project's `.eslintrc.json`. If necessary I can post the debug log in a gist.

**Comment by bradzacher** [comment]
Could you provide some more information?
This by itself is not a lot to go on.

eg
What does your config look like?
What does the `eslint --debug` look like?

**Comment by biehlerj** [comment]
The config:

```json
{
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "extends": [
    "airbnb-typescript",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended"
  ],
  "globals": {
    "Atomics": "readonly",
    "SharedArrayBuffer": "readonly"
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json",
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 2018,
    "sourceType": "module"
  },
  "plugins": [
    "@typescript-eslint",
    "react"
  ],
  "rules": {
    "max-len": [
      2,
      {
        "code": 120,
        "tabWidth": 4
      }
    ],
    "indent": [
      "warn",
      4,
      {
        "FunctionDeclaration": {
          "parameters": "first"
        },
        "SwitchCase": 1
      }
    ],
    "@typescript-eslint/indent": [
      "warn",
      4,
      {
        "FunctionDeclaration": {
          "parameters": "first"
        },
        "SwitchCase": 1
      }
    ],
    "import/prefer-default-export": 0,
    "no-trailing-spaces": 2,
    "react/jsx-filename-extension": [
      1,
      {
        "extensions": [
          ".jsx",
          ".tsx"
        ]
      }
    ],
    "@typescript-eslint/no-unused-vars": "warn",
    "@typescript-eslint/no-use-before-define": 0,
    "@typescript-eslint/no-inferrable-types": 0,
    "import/no-extraneous-dependencies": 0,
    "import/no-cycle": 0,
    "no-underscore-dangle": "off",
    "comma-dangle": [
      2,
      {
        "arrays": "always-multiline",
        "objects": "always-multiline",
        "imports": "always-multiline",
        "exports": "always-multiline",
        "functions": "ignore"
      }
    ],
    "semi": [
      "error",
      "always"
    ],
    "object-curly-newline": [
      "error",
      {
        "ObjectExpression": {
          "multiline": true
        },
        "ObjectPattern": {
          "multiline": true
        },
        "ImportDeclaration": {
          "consistent": true
        },
        "ExportDeclaration": {
          "consistent": true
        }
      }
    ]
  }
}
```
The `eslint --debug`: https://gist.github.com/biehlerj/8151a81c3edb5dbb40bff3ab130589b2

**Comment by bradzacher** [comment]
Hmm. I see you're on typescript 3.2.2
That's a very old version of typescript.

having a quick dig around, it looks like #1693 broke this for you, as it switched to `ts.createAbstractBuilder`.
In TS 3.2.2, `ts.createAbstractBuilder` throws an error for all methods other than `getProgram`:

https://github.com/microsoft/TypeScript/blob/v3.2.2/src/compiler/builder.ts#L710-L730

cc @uniqueiniquity @sheetalkamat

**Comment by sheetalkamat** [comment]
I think abstract builder shouldnt throw but needs to redirect methods to program. Definitely issue with typescript here. But given that should we use abstract builder for 3.9 onwards in eslint and for rest semantic builder like before #1693

**Comment by sheetalkamat** [comment]
Oh and thats actually been fixed since 3.2.2 .. will figure out when abstract builder was fixed to redirect instead

**Comment by sheetalkamat** [comment]
Update typescript@3.3 has this fixed

**Comment by bradzacher** [comment]
@biehlerj can you update to TS3.3?
Is there something that's blocking you from that?

**Comment by biehlerj** [comment]
@bradzacher that's the requirement for a project which is a work-related project and I don't have control over what version of typescript we use. I'll bring it up to the team lead and see if we can upgrade, otherwise I've tested it and it looks like as long as `@typescript-eslint/parser` is < `2.24.0` our config works.
