### ISSUE TITLE
Add an action to automatically lock old, closed PRs and issues

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#1767]
As per the contributing guidelines, users should not comment on old, closed PRs and issues.
https://github.com/typescript-eslint/typescript-eslint/blob/master/CONTRIBUTING.md#commenting

Though most users (understandably) don't read the contributing guidelines before commenting (it's probably won't ever change without some "louder" UI from github to make it easier to find/read the doc).

It's great that people are using search to find things that are relevant, but we'd obviously rather a new issue with a link to the old issue instead of a comment on the old issue.
Sometimes I comment asking for an issue and lock the thread, some other times when I've been super busy, I've just ignored the comment.
Neither are a good experience for anyone, so lets leverage the github actions here to help manage this.

From the Github docs, it looks like it should be possible to create a scheduled action:
https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

So then it's just a matter of coding a script that will lock anything that's closed/merged and older than say, 1 month?

**Comment by anikethsaha** [comment]
there is a stale action !

here is [an implementation example you can refer](https://github.com/docsifyjs/docsify/blob/develop/.github/stale.yml)

**Comment by bradzacher** [comment]
That does seem like an interesting action. I've been thinking about maybe setting up a stale process, but that would require designing more concrete work flows.

For this issue, however, its not about closing issues that have been open for too long, it's about locking issues that are already closed to prevent necro comments.

**Comment by anikethsaha** [comment]
I think it can be configured to lock them as well. NOt sure though. I will check it soon
