### ISSUE TITLE
[unbound-method] throws error because Atomics global is not part of "globals" object

### ISSUE THREAD

**Issue by pennyshen** [typescript-eslint/typescript-eslint#1780]
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/unbound-method": "error"
  }
}
```

This repros when I edit any `.tsx` file, I see an error (see below).

**Expected Result**
Able to lint files.

**Actual Result**
Error:
```
[Error - 10:54:39 AM] TypeError: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json': Cannot convert undefined or null to object
Referenced from: /Users/penny/src/mono/ts/lite/.eslintrc.json
    at Function.getOwnPropertyNames (<anonymous>)
    at SUPPORTED_GLOBALS.map.namespace (/Users/penny/src/mono/ts/lite/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unbound-method.js:79:19)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/penny/src/mono/ts/lite/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unbound-method.js:77:48)
    at Object.<anonymous> (/Users/penny/src/mono/ts/lite/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unbound-method.js:208:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

**Additional Info**

Code snippet where it's failing:
```
    const object = global[namespace];
    return Object.getOwnPropertyNames(object)
        .filter(name => !name.startsWith('_') &&
        typeof object[name] === 'function')
        .map(name => `${namespace}.${name}`);
```

It's specifically failing when it's doing `global['Atomics']` - object is null/undefined and next line throws error. When I comment out `Atomics` from `SUPPORTED_GLOBALS` like below, it works correctly.
```
const SUPPORTED_GLOBALS = [
    'Number',
    'Object',
    'String',
    'RegExp',
    'Symbol',
    'Array',
    'Proxy',
    'Date',
    'Infinity',
    // 'Atomics',
    'Reflect',
    'console',
    'Math',
    'JSON',
    'Intl',
];
```

Looking at the `Global` interface in `@types/node`, I don't see `Atomics`. From [this PR](https://github.com/typescript-eslint/typescript-eslint/commit/0a110eb680749c8c4a2a3dc1375c1a83056e4c14#diff-83a7c70ad687f4357116f9a81bc614e4R1), it seems like you're extending the interface but looks like it may not 

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.20.0` |
| `@typescript-eslint/parser`        | `2.20.0` |
| `TypeScript`                       | `3.7.2` |
| `ESLint`                           | `6.2.2` |
| `node`                             | `8.12.0` |
| `npm`                              | `6.4.1` |

**Comment by bradzacher** [comment]
I'm unable to reproduce this.
We made sure the globals that were added were 100% compatible with the versions of Node we support.

As per below, `Atomics` is defined in node 8.12.0
![image](https://user-images.githubusercontent.com/7462525/77261237-65d41900-6c4a-11ea-8dba-80e491740806.png)

If you're seeing that error, it means you're not running the linter in the correct version of node.

**Comment by pennyshen** [comment]
Ah sorry, looks like ESLint server is running on an older version of node from what's installed locally. I didn't realize that.

[This is because my VSCode is outdated](https://github.com/microsoft/vscode-eslint/issues/818). Uninstalling it and re-installing with updated version fixed this. Hope this thread is helpful for anyone else running into the same problem ><
