### ISSUE TITLE
[object-curly-spacing] One-line object types do not adhere to spacing rules

### ISSUE THREAD

**Issue by mpsijm** [typescript-eslint/typescript-eslint#1784]
**Repro**

```JSON
{
  "rules": {
    "object-curly-spacing": "never"
  }
}
```

```TS
const foo = ({ status }: { status: int }) => console.log(status);
```

**Expected Result**
That running `eslint --fix` would fix this to:
```TS
const foo = ({status}: {status: int}) => console.log(status);
```

**Actual Result**
Instead, only the first curly brackets are fixed:
```TS
const foo = ({status}: { status: int }) => console.log(status);
```

**Additional Info**
This rule does not exist yet in `@typescript-eslint`, but should be extended from `eslint` like many other rules (e.g. [`brace-style`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/brace-style.md))

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.24.0` |
| `@typescript-eslint/parser`        | `2.24.0` |
| `TypeScript`                       | `3.6.3` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `13.11.0` |
| `npm`                              | `6.13.7` |

**Comment by mpsijm** [comment]
Sorry, accidentally clicked enter without completing the description, will update now!

**Comment by anikethsaha** [comment]
I will try to give it a shot tomorrow if no one is taking.

**Comment by sassanh** [comment]
@anikethsaha Gentle reminder in case it is an easy but forgotten ticket :-)
