### ISSUE TITLE
Parser does not have stard/end indicies on nodes.

### ISSUE THREAD

**Issue by NullVoxPopuli** [typescript-eslint/typescript-eslint#1788]
**Repro**
https://astexplorer.net/#/gist/658b2971791a4bfc7aed0041795e6207/3fe8035d7c717476cf83ed311133db0a0399ca35

![image](https://user-images.githubusercontent.com/199018/77358392-00922d80-6d07-11ea-93af-2ac1a9899b42.png)

Note that both the property and decorator have a start/end property.

Now with the TS Parser:
https://astexplorer.net/#/gist/cf94ce18c16723fb7b5cf33b450e6315/f9a06e90f622943642b192fc082f71b558f0bc7c

![image](https://user-images.githubusercontent.com/199018/77358490-2b7c8180-6d07-11ea-9c81-687915e347ea.png)

**Expected Result**

typescript parser has start/end properties

**Actual Result**

typescript parser does not have start/end properties

**Comment by bradzacher** [comment]
See #405

start/end are non-standard, and should not be used.
We will not be adding them.
