### ISSUE TITLE
no-unused-vars feature request arrayIgnorePattern

### ISSUE THREAD

**Issue by cyberixae** [typescript-eslint/typescript-eslint#1805]
It would be nice if the plugin would allow you to name things when unpacking an array.

```typesscript
/*eslint no-unused-vars: ["error", { "arrayIgnorePattern": "^_" }]*/

const [_a, b, _c] = 'a:b:c'.split(':');
console.log(b);
```

**Comment by bradzacher** [comment]
We extend the base rule to support TS features.
This would be a better feature request for the base eslint repo:
https://github.com/eslint/eslint

**Comment by cyberixae** [comment]
Ok. Thanks! I refiled it there eslint/eslint#13100
