### ISSUE TITLE
Roadmap missing ESLint's no-restricted-globals for TSLint's ban

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#1817]
* TSLint `ban`: https://palantir.github.io/tslint/rules/ban
* ESLint `no-restricted-globals`: https://eslint.org/docs/rules/no-restricted-globals
* ESLint `no-restricted-properties`: https://eslint.org/docs/rules/no-restricted-properties

https://github.com/typescript-eslint/typescript-eslint/blob/6bebb1dc47897ee0e1f075d7e5dd89d8b0590f31/packages/eslint-plugin/ROADMAP.md#L50

Copying discussion from https://github.com/typescript-eslint/tslint-to-eslint-config/pull/316/files#r370939820:

> I think this'll need some work. TSLint's `ban` rule bans both _globals_ and _properties_. ESLint splits those between `no-restricted-globals` and `no-restricted-properties`.

It looks like the roadmap should be updated to reflect this? Am I misreading the rules?

**Comment by bradzacher** [comment]
You're right I think, probs was just an oversight when the original list was created. Feel free to correct it 😄
