### ISSUE TITLE
[no-nested-ternary] rule was not found

### ISSUE THREAD

**Issue by Dan503** [typescript-eslint/typescript-eslint#1819]
ES Lint provides a "no-nested-ternary" rule:
https://eslint.org/docs/rules/no-nested-ternary

I tried implementing it into my config:

```JSON
{
  "rules": {
    "@typescript-eslint/no-nested-ternary": "error"
  }
}
```

I received the following error:

```
error  Definition for rule '@typescript-eslint/no-nested-ternary' was not found  @typescript-eslint/no-nested-ternary
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.25.1-alpha.6` |
| `@typescript-eslint/parser`        | `2.25.0` |
| `TypeScript`                       | `3.7.3` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `12.13.0` |
| `npm`                              | `6.12.0` |

**Comment by bradzacher** [comment]
You have misconfigured the rule.
drop the `@typescript-eslint/` from the key.

You only need the prefix if you're using one of our extension rules.
