### ISSUE TITLE
Integration with prettier

### ISSUE THREAD

**Issue by xeoneux** [typescript-eslint/typescript-eslint#182]
**Expected Result**
The extension should disable styling rules that will be handled by prettier

**Actual Result**
`prettier-config-eslint` and the extension both have conflicting style rules

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `latest` |
| `@typescript-eslint/parser`        | `latest` |
| `TypeScript`                       | `3.2.4` |
| `ESLint`                           | `latest` |
| `node`                             | `latest` |
| `npm`                              | `latest` |

**Comment by lewisflude** [comment]
Have you tried using  'prettier/@typescript-eslint'? I found that gave me the overrides I needed!

**Comment by JamesHenry** [comment]
Thanks @lewisflude!

@xeoneux We already have docs for this: https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#usage-with-prettier

**Comment by xeoneux** [comment]
Ah, my bad @JamesHenry, should have scrolled down further.
Thanks @lewisflude for the solution 😄
