### ISSUE TITLE
prefer-optional-chain autofix is not safe

### ISSUE THREAD

**Issue by jasonHzq** [typescript-eslint/typescript-eslint#1820]
The autofix of rule "prefer-optional-chain" in eslint-plugin is not safe in this case:

source code:

```js
// foo is null here
const value = foo && foo.value;

// value is null in source code
if (value === null) {
  // code here
}
```

autofixed code:

```js
// foo is null here
const value = foo?.value;

// value will be undefined in autofix code
if (value === null) {
  // code here
}
```

**Comment by bradzacher** [comment]
Happy to accept a PR to add an option to convert the fixer to a suggestion fixer.

---

My general suggestion is to avoid `=== null` in favour of `== null`, because `== null` catches both null and undefined.
It's _very_ rare that you want to handle the two cases differently, so this is the better check to use.

This is also very easy to enforce with the base [`eqeqeq`](https://eslint.org/docs/rules/eqeqeq) rule:

```
"eqeqeq": ["error", "always", { "null": "never" }],
```

**Comment by jasonHzq** [comment]
I think autofix should be completely logical equality. Shall autofix only open in IfStatement. Or if the optional chains is in 'Assign Expression'(BinarayExpression with EqualsToken), the autofix should be closed.

**Comment by jasonHzq** [comment]
Set both the the base eqeqeq rule to { "null": "never" } and optional chains cannot completely logical equality too. If there is a npm package use optional chains, all the project have depped the npm should fix the eqeqeq never null problems. It's dangerous.

**Comment by bradzacher** [comment]
It's only as dangerous as your types are.
If the module boundaries are poorly typed, then yes, it's dangerous.
But if it's strictly typed, then it's not dangerous, as typescript will fail your build.

The fixer in its current form may or may not cause type errors, depending on your codebase and the checks that are done on your code.

A suggestion fixer will let people manually apply the fix in their IDE, and will not let it be fixed automatically via `--fix`. This lets the developer choose when they want to correct the error automatically, and when they want to manually correct it.
