### ISSUE TITLE
Very slow linting with parserOptions.project (bug?)

### ISSUE THREAD

**Issue by nmatushevskiy** [typescript-eslint/typescript-eslint#1828]
**Repro**

.eslintc
```JSON
{
  "parserOptions": {
    "project": "tsconfig.eslint.json"
  }
}
```

tsconfig.eslint.json
```JSON
{
  "extends": "./tsconfig.json",
  "include": [
    "src/app/components/another-components/**/*.ts",
    "src/app/components/some-components/**/*.ts"
  ]
}
```

**Expected Result**
works faster
**Actual Result**
works slow
**Additional Info**
I'm working with big (800 000 lines of code) and hybrid angular application. Unfortunately, I can't give link to project, or code examples, but I created small repo which contains all the necessary examples.
repo: https://github.com/nmatushevskiy/typescript-eslint-parser-perfomance

after adding "project" to "parserOptions"and running npm run lint, linter start works very slow.
("includes" added to tsconfig.json)

then I tried to run npm run lint not for entire project, but for some directory. Without parserOptions.project lint check is performed in 2 minutes and with parserOptions.project lint check is performed in 10+ minutes.

by debugging I found out, that function "parseForESLint" from @typescript-eslint/parser works slower if "project" added in "parserOptions".

is this a bug or expected behavior?

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.19.2` |
| `TypeScript`                | `3.7.5` |
| `ESLint`                    | `6.8.0` |
| `node`                      | `10.16.0` |
| `npm`                       | `6.9.0` |

**Comment by bradzacher** [comment]
Have you had a look at our FAQ?
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#my-linting-feels-really-slow

Let me know if anything is unclear after reading it and the attached links.

**Comment by nmatushevskiy** [comment]
Yes I looked it up.
but I did not notice the section "Performance" from here: https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md
Sorry for the inattention.
This explains the long run time.

But I still think that  something wrong. (Maybe I make a mistake with some configuration)

I set console.log into function "executeOnFiles" from eslint/lib/cli-engine/cli-engine.js and run npm run lint

npm run lint without "parserOptions.project":
![withoutProject1](https://user-images.githubusercontent.com/56971144/78133398-0b477380-7427-11ea-87ae-5e3bea0a3886.gif)

npm run lint with "parserOptions.project":
![withProject](https://user-images.githubusercontent.com/56971144/78133432-1bf7e980-7427-11ea-98c1-5a3362e3140f.gif)

with "parserOption.project" works much slower.
Is this really the correct runtime?

**Comment by bradzacher** [comment]
Depends. How long is your build normally?

Essentially when you use typed linting, the total execution time should be lint time + build time.

> you are essentially asking TypeScript to do a build of your project before ESLint can do its linting.

There's no other way to gather a complete set of types for a project. It's a trade-off; longer lint times in exchange for powerful validation of your code.

**Comment by nmatushevskiy** [comment]
Build takes a long time.
Think this is correct runtime.
Thank you for your help!
