### ISSUE TITLE
documentation / get-started-guide

### ISSUE THREAD

**Issue by PutziSan** [typescript-eslint/typescript-eslint#183]
Hi,
I know the project and the 4 sub-projects only since the merge under this mono-repo. Is there a plan to document in the root-readme about what this package is and how best to start it? At the moment I am a bit overwhelmed how I should use which package here or with which I have to start to simply use eslint for my TypeScript files. Also, a migrations-guide from tslint would be very good. Since apparently the TypeScript team has announced ESLint [as new future](https://github.com/Microsoft/TypeScript/issues/29288), the case will come more and more.
Or does this new project have nothing to do with the announcements of the TypeScript team?

**Comment by JamesHenry** [comment]
Hi @PutziSan I agree we need to do better here. I created #36 for this reason, but I got a bit lost.

I have now pinned that issue using GitHub's new feature so that it is easier to find, and we'll use that one to track.

Stay tuned!
