### ISSUE TITLE
Can't get TypeScript Linting to work (tried everything)

### ISSUE THREAD

**Issue by dsomel21** [typescript-eslint/typescript-eslint#1834]
I put this on [Stackoverflow](https://stackoverflow.com/questions/60982344/cannot-get-any-highlighting-or-linting-in-vscode-espeically-typescript?noredirect=1#comment107889290_60982344) as well.

**What were you trying to do?**

Get some VSCode syntax highlighting and linting. 

Here's a new project `yarn init` with `yarn add -D @typescript-eslint/parser @typescript-eslint/eslint-plugin`

> **settings.json** (for my VSCode)

```json
{
    "editor.tabSize": 2,
    "editor.fontSize": 18,
    "editor.useTabStops": false,
    "explorer.compactFolders": false,
    "window.zoomLevel": 0,
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.formatOnSave": true,
        "editor.formatOnPaste": true,
    },
    "editor.renderIndentGuides": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "java.errors.incompleteClasspath.severity": "ignore",
    "java.configuration.checkProjectSettingsExclusions": false,
    "synthwave84.brightness": "0.05",
    "workbench.colorTheme": "SynthWave '84",
    "eslint.validate": [
        {"language": "typescript", "autoFix": true }
    ],
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true 
    }
}
```

> /tsconfig.json

```json
{
  "compilerOptions": {
    "noEmit": true,
    "strictNullChecks": true,
    "strict": true,
    "strictFunctionTypes": true,
    "strictBindCallApply": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false
  },
  "files": ["*.ts/*.tsx"]
}
```

**What did you expect to happen?**

![alt text](https://i.stack.imgur.com/dYTNy.png "Expect")

**What actually happened?**

![alt text](https://i.stack.imgur.com/9aR5M.png "Reality")

**Versions**

This is my list of Global NPM Packages:

├── babel-eslint@10.1.0
├── eslint@6.8.0
├── eslint-plugin-babel@5.3.0
├── eslint-plugin-react@7.19.0
├── npm@6.13.1
└── typescript@3.8.3

**Comment by bradzacher** [comment]
what do you mean by "typescript linting"?
There's ESLint reports, which is what our project deals with.
And there's typescript type checks.

Have you got an example repo or anything?

**Comment by dsomel21** [comment]
Pardon me, @bradzacher, I may be issuing in the wrong territory right now. 

I want those live errors and highlighting in my VSCode. I was under the impression it had something to do with my VSCode and ESLint. 

This is the affect that I am going for:
[this]: https://i.imgur.com/FJQT8bI.png "How to get this Tooltip"

as well as 

[this]: https://i.imgur.com/DkzVjUC.png "How to get this highlighting"

**Comment by bradzacher** [comment]
Without some more information, it's hard to provide much guidance.

I can see that your tsconfig is misconfigured.

```
"​files​"​: [​"​*.ts/*.tsx​"​]
```

This is not a valid glob, and also you should not be using `files` in this way. You should use `include` for globs, and you should make sure your globs are narrow and just match the files you want to check.

Eg something like
```
"include": ["src/**/*.ts", "src/**/*.tsx"]
```
