### ISSUE TITLE
Webstorm doesn't highlight errors and warnings

### ISSUE THREAD

**Issue by Manimall** [typescript-eslint/typescript-eslint#1848]
I created a `.eslintrc.js`  simple dumb file with these rules, - 

```JS
module.exports = {
	parser: '@typescript-eslint/parser', // Specifies the ESLint parser
	extends: [
		'plugin:@typescript-eslint/recommended', // Uses the recommended rules from the @typescript-eslint/eslint-plugin
	],
	plugins: ['@typescript-eslint'],
	rules: {
		'no-unused-vars': 'error',
		'semi': ['error', 'always'],
	},
};
```

- and in my index.ts write some dumb code - 

```
console.log('dsasda');

const a = 1;

const ada = {
	asdds: 'dsasds',
	dads: 'ad',
};

const b = {};
```

and it's not highlighted((((

but terminal told me - there is an errors and warnings - 
![2020-04-04_14-02-33](https://user-images.githubusercontent.com/2580719/78428796-109dfb80-767d-11ea-89a0-08572efc921c.png)

everything was done according to this article - https://www.jetbrains.com/help/webstorm/eslint.html#ws_eslint_linting_typescript_files_with_eslint

**Comment by bradzacher** [comment]
Not sure how to help you sorry, I don't use webstorm.
There's nothing that prevents this project from working with webstorm, as I know many users use it.
With that simple of a config, I would assume you're missing something (maybe a misconfigured extension in your IDE).

**Comment by Manimall** [comment]
> Not sure how to help you sorry, I don't use webstorm.
> There's nothing that prevents this project from working with webstorm, as I know many users use it.
> With that simple of a config, I would assume you're missing something (maybe a misconfigured extension in your IDE).

what IDE do you use?

P.S: I wrote to jetbrains issues tracker - and they helped me to find the solution - https://youtrack.jetbrains.com/issue/WEB-44693

**Comment by bradzacher** [comment]
VS Code. I've used it for a good 5 or so years.

Good to hear that they found a fix for you.
