### ISSUE TITLE
The changelog is full of broken links

### ISSUE THREAD

**Issue by lydell** [typescript-eslint/typescript-eslint#1849]
https://github.com/typescript-eslint/typescript-eslint/blob/7c11bd66f2d0e5ea9d3943e6b8c66e6ddff50862/CHANGELOG.md

<img width="996" alt="Screenshot 2020-04-04 at 15 21 19" src="https://user-images.githubusercontent.com/2142817/78451790-f3baf580-7687-11ea-85ad-1a4ddb980b9f.png">

It seems like all rule names have `[` `]` around them as if they were supposed to be links, but none of them link anywhere.

**Comment by bradzacher** [comment]
That's just a commit message format which I roughly try to stick to to make it easier to search PRs/issues, and to make it easier to understand what rule a change applies to.

I'd consider making them links, but they changelogs are auto-generated by lerna, and it doesn't support customising it at all AFAIK.

**Comment by lydell** [comment]
Ah, I see. You could also try to get rid of the `[` `]`, because to me they look like as if you’d make some text blue and underlined but it’s not a link. It looks, well, broken.

**Comment by bradzacher** [comment]
> You could also try to get rid of the [ ]

We could codemod the changelogs (all 8 of them) to remove it, but there's also there's the dozens of releases annotated on github (which would have to be fixed up manually).

Plus without some way to clean it from lerna, it's going to keep showing up as it's the commit style we've been using.

I think it's just something that we're going to have to live with.
