### ISSUE TITLE
[member-delimiter-style] Support "off" setting for interface or type

### ISSUE THREAD

**Issue by wnayes** [typescript-eslint/typescript-eslint#1851]
I would like to be able to use [`member-delimiter-style`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-delimiter-style.md) to enforce consistency of interface delimiters, but not enforce any particular style for types. It would be a nice enhancement to be able to use the existing overrides and set one of them to `"off"`. Currently, I think both interfaces and types are held to some standard no matter what the configuration is.

**Repro**

```JSON
// Hypothetical configuration that checks semis on interfaces, but disregards types.
{
   "rules":{
      "@typescript-eslint/<rule>":[
         "error",
         {
            "multiline":{
               "delimiter":"semi",
               "requireLast":true
            },
            "singleline":{
               "delimiter":"semi",
               "requireLast":true
            },
            "overrides":{
               "typeLiteral":{
                  "multiline":{
                     "delimiter":"off",
                  },
                  "singleline":{
                     "delimiter":"off",
                  },
               }
            }
         }
      ]
   }
}
```

```TS
// Would enforce semis on interfaces...
interface Foo {
    name: string;
    greet(): void;
}

// But not care about types.
type Bar = {
    name: string;
    greet(): void,
}
```

Posting this issue as a sort of proposal. I would be willing to implement if there is no disagreement.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.26.0` |

**Comment by bradzacher** [comment]
Could you please tell me why you want to treat the two different?
Ultimately the two are syntactic sugar for the same thing, so why do you want to treat them different?
Also if you treat them different then you get into weird situations like:

```ts
interface Foo {
  bar: { // this property is part of an interface
    baz: string; // this property is part of an object type
  };
}
```

**Comment by wnayes** [comment]
I have an existing codebase where interfaces have been pretty consistently created with semicolons, but types appear to vary more. I was hoping to be able to enforce semicolons on interfaces, without adding an enforcement for types at this time. I'm looking into a general transition to eslint from a previous linter, and trying to improve things where I can, but not go overboard and overwhelm with new errors.

**Comment by bradzacher** [comment]
The rule has a fixer though.
So you can turn it on, and run the fixer, and there will be zero errors in the codebase.

**Comment by wnayes** [comment]
That is true. I have not experimented with the fixer across this codebase yet, as it is 7500+ TypeScript files which cross multiple ownership boundaries. I have generally appreciated the flexibility of the rules here, just thought I'd throw this idea out there. I can understand not wanting to open the door to less consistency.

**Comment by bradzacher** [comment]
My advice to you, from somebody who touches linting in the facebook codebase, and fixes many people's code.
As long as you're doing it in chunks, and explain how you made changes - then people will be happy to stamp a PR.
Eg you can easily fix just this rule via the CLI without accidentally fixing any other rules in the process. Something along the lines of:

```
eslint \
  --ext ".ts" \
  --fix \
  --parser @typescript-eslint/parser \
  --plugin @typescript-eslint \
  --rule "{'@typescript-eslint/member-delimiter-style': ['error', <options>]}" \
  --no-inline-config \
  --no-eslintrc \
  <paths to fix>
```
https://eslint.org/docs/user-guide/command-line-interface

Change the ESLint config, run the command, and submit a PR - people will have a hard time opposing no-op linting changes.

---

I'm strongly against adding options for inconsistency into this, or any rule. As such - I am going to reject this change.
