### ISSUE TITLE
Documentation for [ban-ts-ignore], [camelcase], [class-name-casing], [generic-type-naming], [interface-name-prefix], [member-naming], and [no-untyped-public-signature] are all unlinked

### ISSUE THREAD

**Issue by isiahmeadows** [typescript-eslint/typescript-eslint#1854]
I went through the readme + `docs/rules` for both the latest release's tag and in the current `master` in the `@typescript-eslint/eslint-plugin`, and I noticed docs existed for each of these didn't have corresponding entries in the README.

**Comment by bradzacher** [comment]
This is on purpose.
All of these rules are deprecated.

- ban-ts-ignore has been replaced by `ban-ts-comment`
- camelcase, class-name-casing, generic-type-naming, interface-name-prefix, and member-naming have all been replaced by `naming-convention`
- no-untyped-public-signature has been replaced by `explicit-module-boundary-types`

The individual docs should probably be updated to reflect this.
