### ISSUE TITLE
[meta] Problems with the rules that use scope analysis [no-unused-vars][no-undef][no-shadow][no-redeclare][no-use-before-define]

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#1856]
I wanted to merge all of the scope analysis rule issues together into a single meta-issue. So I could centrally provide some context on what the problem is, and what needs to be done.

# The Problem

The `no-unused-vars` rule, as with many other rules in ESLint [[1]](https://github.com/eslint/eslint/search?q=%22context.getScope%22&unscoped_q=%22context.getScope%22)[[2]](https://github.com/eslint/eslint/search?q=%22context.getDeclaredVariables%22&unscoped_q=%22context.getDeclaredVariables%22) relies upon scope analysis. 

For context; an ESLint parser may additionally provide a `ScopeManager` alongside the AST it produces. A [`ScopeManager`](https://eslint.org/docs/developer-guide/scope-manager-interface) is a utility class which can be used to interrogate the variables available in a certain scope.

ESLint rules can then use this `ScopeManager` to gather information about the variables that are included in the current scope - i.e. what variables are defined.

Other parsers (such as babel-eslint) provide scope analysis, but most other parsers have a smaller scope of extensions to support, so they can just build on top of the existing scope manager, or they get around it via "extension" rules to either mark things as used, or to ignore things from rules entirely.

In TypeScript's case, in order for us to properly describe the scope and usage across TS's dual-scope system, it would require a large rewrite of the scope analyser (eg #1533).

This is never something we invested much time into for a number of reasons like:
- _most_ of the rules that use the scope manager are either infrequently used, or have analogous checks/options in the TypeScript itself,
- we wanted to be careful that we wouldn't implement something that would get outdated by changes to the underlying TS language,
- we explored other options that would not require scope analysis:
    - [manually marking nodes via `context.markVariableAsUsed`](https://github.com/typescript-eslint/typescript-eslint/blob/bed774320f4f9196c98351754f74fbdbbe9309d8/packages/eslint-plugin/src/rules/no-unused-vars.ts).
        - This got us a decent chunk of the way, but it's not a great way to handle all of the cases and scope boundaries.
    - [`no-unused-vars-experimental`](https://github.com/typescript-eslint/typescript-eslint/blob/bed774320f4f9196c98351754f74fbdbbe9309d8/packages/eslint-plugin/src/rules/no-unused-vars-experimental.ts).
        - This was a great idea in theory, but the `getSemanticDiagnostics` API is too slow for the rule to be usable on large codebases (~30ms per file) (#1335)
- the inner workings of eslint-scope are relatively poorly documented, so implementing TS scope into it was always a large task.

# The Solution

It's become very clear that we need to bite the bullet and just do this work.
We're currently building out a full scope manager (#1939), but it is not a small task, so please be patient.

**Comment by TheAkio** [comment]
Does this issue also adress, that "no-use-before-define" doesn't work properly in a decorator if the decorator is referencing it's own class? Or is this intended behaviour?
I didn't find another issue regarding this but to me it seems like the work done here might fix this.

```ts
@Directive({
    providers: [{
        provide: NG_VALIDATORS,
        useExisting: MyValidatorDirective, // 'MyValidatorDirective' was used before it was defined. eslint(@typescript-eslint/no-use-before-define)
        multi: true
    }],
})
export class MyValidatorDirective {}
```

Let me know if I should create a separate issue for this instead.
Thanks for your hard work regarding typescript-eslint!

**Comment by bradzacher** [comment]
The corrected scope analysis would only correct how `no-unused-variables` detects "variables" in the codebase.

It does not teach the rule about how new syntax may behave based on order of declaration.
This would have to be built as an option for the rule.

Though TBH (I don't want to get too off topic, and into the weeds here) I think that code being runtime valid is a lucky coincidence of TS's _current_ transpilation of decorators, and I don't know if it's actually compliant with the current spec, or something you should rely on as it may prevent your migration to a future version of TS.

TS's implementation hasn't changed at all (on purpose) because the spec is very much in flux (and also kind of dead right now). OTOH, I believe that Babel keeps its implementation updated, and currently generates code which will error at runtime for your example.

As mentioned, scope analysis will not address this; if you want to discuss this further, please file a new issue.

<details>
<summary>TypeScript transform of the given code</summary>

```js
var MyValidatorDirective_1;
let MyValidatorDirective = MyValidatorDirective_1 = class MyValidatorDirective {
};
MyValidatorDirective = MyValidatorDirective_1 = __decorate([
    Directive({
        providers: [{
                provide: NG_VALIDATORS,
                useExisting: MyValidatorDirective_1,
                multi: true
            }],
    })
], MyValidatorDirective);
```
[repl](https://www.typescriptlang.org/play/?experimentalDecorators=true#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwBEs5MsA3EACgA8AueKVATwEp7GmBueAKFElgIweAM4Z4AOQDiAfQBqAQQAyASQIKAKgHkASgGV2zTjx4ABIiWwVKAbx7wH8AA4wcZLKBgj6AbTuOA51d3UHppeWU1TV09ABp7QIdkERAAUWosMSxUAHN6AFkmOSgIDygMHBgLcCsQWPgAegb4AHJC4tLgcsrq0goW+AB3KBF4ZJBgeAAjEERKhCxxYdHQRGyJgDp4EBFS1AxKUwwmJx2wGCwnDABaHb2MBtQca-Hrmbm4a9X1lgTEgFtkBBsPQMDBkCA-vAAL4AXXi0N+IGoTkq4gEIlG7RKZQqVWINXICBsMJ4QA)

</details>

<details>
<summary>Babel transform of the given code</summary>

```js
let MyValidatorDirective = _decorate([Directive({
  providers: [{
    provide: NG_VALIDATORS,
    useExisting: MyValidatorDirective,
    multi: true
  }]
})], function (_initialize) {
  class MyValidatorDirective {
    constructor() {
      _initialize(this);
    }

  }

  return {
    F: MyValidatorDirective,
    d: []
  };
});
```
[repl](https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAERgJwKbRgNwwCgEpEBvAKEUQgQGc4AbDAOnrgHN8BDNNkAWwxgoNQgG4KiTFBBokoSLASIipCZWpg6jFuy49-g4WIkBfMmY00oiAHIBxAPoA1AIIAZAJLIXAFQDyAEoAyogAvIgAjOJkAAKomNh4-OSUlAAOaHA4MAAmGGg0AFyIANopqRUZWbkYxfbO7l6-gUEANGoViCA0GACiAB4wVjBgbMUAsgCeTpz0uZxQcGjxWLB4rYgA9JuIAORTM3M5C0sriRi7iADunDRdPTmIAEYYwEsYiDDWN3d5wCMYHJMRAYGhzIT4GJQSZpUEQNAwNJQAC0oPBUE2YDgyO6GGRLzemGRfwBhA6FT4IHosGKUDQIAwHRMAF12iYyRB6Lc7gdZvNFst0KtcB8SCYgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-2&prettier=true&targets=&version=7.9.0&externalPlugins=)

</details>

**Comment by TheAkio** [comment]
Interesting. It seems like the guys working on Angular will have to figure this out once decorators are finally standardized. Because this is the only way I know of how to do this (See: https://angular.io/api/forms/NG_VALIDATORS).

For now it doesn't really matter as simply disabling the rule for classes doesn't really affect things too much in our codebase, as a class is mostly directly exported anyway and not used additionally inside the same module file (except for decorators ofc).

I feel like currently discussing this further doesn't make sense as (like you already mentioned) it seems to just be a coincidence in the way TypeScript transpiles decorators.

Thanks for your quick response!

**Comment by snebjorn** [comment]
I was just hit by this

```ts
// 'Inject' is defined but never used. eslint@typescript-eslint/no-unused-vars
// 'Optional' is defined but never used. eslint@typescript-eslint/no-unused-vars
import { Inject, Injectable, Optional } from '@angular/core';
// 'FORMS_MANAGER_OPTIONS' is defined but never used. eslint@typescript-eslint/no-unused-vars
import { FormsManagerOptions, FORMS_MANAGER_OPTIONS } from './forms-manager-options';

@Injectable({
  providedIn: 'root',
})
export class MyClass {
  constructor(@Optional() @Inject(FORMS_MANAGER_OPTIONS) options: Partial<FormsManagerOptions>) {}
}
```

**Comment by ajmas** [comment]
Does this issue cover the problem reported here: https://github.com/eslint/eslint/issues/13388

**Comment by ajmas** [comment]
What is the current status of this ticket?

**Comment by bradzacher** [comment]
On the sidebar you can see the linked pull requests - it is being worked on.
As per the OP - it's a non-trivial change to do, as evidenced by the 214,968 lines of change required.

The maintainers of this project are volunteers that give their free time when they can. Big issues like this are going to take a lot of time to complete.

**Comment by jpike88** [comment]
You’d think Microsoft would find this eventually, eslint + ts is such a powerful combo

**Comment by sperezm97** [comment]
any updated ?

**Comment by bradzacher** [comment]
This has been released to NPM as part of the prerelease version for v4.

Try out the `rc-v4` tag on NPM.

We're working on finalising all the work for the v4 release so eta for full release is uncertain

https://github.com/typescript-eslint/typescript-eslint/milestone/5
https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.0.0-rc

**Comment by hiranya911** [comment]
Great job on landing this work. I wanted to know a bit more about how this affects the performance issues discussed in #1335. Does this work address the slow execution time in the `no-unused-var-experimental` rule? Is that available in the v4.0.0-rc packages?

**Comment by bradzacher** [comment]
I have marked `no-unused-vars-experimental` as deprecated as part of this change, and we will likely remove that rule in v5.

The underlying infra changes made for this work mean that `@typescript-eslint/no-unused-vars` rule now just works. It works with the same perf as the core `no-unused-vars` rule because it has no dependency on typescript or the typechecker, and instead uses a fork(/ complete rewrite) of ESLint's scope analyser.

**Comment by mckennapsean** [comment]
I tried out the RC - super excited for this release!

My company has (not in ESLint) custom format functions that auto-cleanup unused imports. I found this [unused imports plugin](https://github.com/sweepline/eslint-plugin-unused-imports), which relies wholly on `@typescript-eslint/no-unused-vars` rule. Hence my excitement finding this thread!

I tried out the RC, and I am getting a new error for the rule: "@typescript-eslint/no-unused-vars"

Minimally, here's a class which results in the error: "Cannot read property 'type' of undefined Occurred while linting .../test.ts:1"

```
export class Test {
    constructor(@Optional() value: number[] = []) {
        console.log(value);
    }
}

export function Optional<T>(): (targetClass: any, parameter: T, index: number) => void {
    return (klass: any, parameter: T, index: number) => {
        console.log(klass);
        console.log(parameter);
        console.log(index);
    };
}
```

If you remove the default parameter value `= []`, then no error.

In previous versions of ESLint, `Optional` was incorrectly reported as unused.

If a separate issue for this would help, happy to file one. Thanks!

**Comment by bradzacher** [comment]
@mckennapsean - please raise this as a new issue so we can track it appropriately.

**Comment by vegerot** [comment]
Is this still an issue in https://github.com/typescript-eslint/typescript-eslint/blob/v4.1.0/packages/eslint-plugin/docs/rules/no-use-before-define.md ?

**Comment by foucdeg** [comment]
@vegerot I'm still having this issue with typescript-eslint 4.4.0 and TS 4.0.3.

**Comment by bradzacher** [comment]
Please raise a new issue and fill out the template.
"I'm still having this issue" is pretty useless as it gives us no information to help you.
