### ISSUE TITLE
Update parserOptions.project README.md 

### ISSUE THREAD

**Issue by RichardSieg** [typescript-eslint/typescript-eslint#1862]
Hi there,

in the last bullet point in the `parserOptions.project` paragraph in the [README](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/parser/README.md#parseroptionsproject), you explain how to work with a custom `tsconfig.eslint.json`. It would be nice if you could add the information, that this file then needs to be used for the `project` variable in the eslint configuration. By reading the guide as it is now I falsely assumed, that `tsconfig.eslint.json` is used automatically.

Thanks,

Richard

**Comment by bradzacher** [comment]
Happy to accept a PR.
