### ISSUE TITLE
Feature request: Allow one root tsconfig

### ISSUE THREAD

**Issue by Shahaed** [typescript-eslint/typescript-eslint#1873]
The current behavior is eslint will only work on files _included_ in the tsconfig. I would like to add additional files (e.g. tests, to maybe the `eslintrc`) and have them covered by the linter. But still exclude them in the tsconfig.

**Comment by bradzacher** [comment]
You can add as many tsconfigs as you like via `parserOption.project` - https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#parseroptionsproject

The recommendation is to create and reference a separate catch-all config called `tsconfig.eslint.json` for these files.

Does this work for you?

**Comment by Shahaed** [comment]
@bradzacher That is the solution we went with per this documentation: https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/MONOREPO.md

However, for people that would only like to use one tsconfig to "rule them all", it would not. It might be worth tracking this issue for them.

**Comment by bradzacher** [comment]
It's not possible to do this though without some level of ambiguity.
When ESLint calls our parser, it doesn't give us any known directories apart from the path to the file being parsed.

So if we allowed a local tsconfig in the `.eslintrc`, then it would be contextless - we wouldn't know where `./file.ts` actually is. Which means we'd need config + a root dir, and at that point it's just easier to have an extra `tsconfig.eslint.json` which does this for free.
