### ISSUE TITLE
starting v2.24.0 I am getting JavaScript heap out of memory errors

### ISSUE THREAD

**Issue by hiro5id** [typescript-eslint/typescript-eslint#1879]
I don't know how to report this issue properly as it is blowing up with "JavaScript heap out of memory error.   This started happening after upgrading the  @typescript-eslint/eslint-plugin   and @typescript-eslint/parser to version 2.24.0.  the latest version does the same thing.  No configuration changes have been done since the last time it worked.

I have tried this on different machines and the same result occurs every time.

**Expected Result**
eslint scans my project successfully

**Actual Result**
blows up with out of memory errors

**Additional Info**
Following error output:
ccp-web-public-app: > npx eslint . --ext .ts
ccp-web-public-app: <--- Last few GCs --->
ccp-web-public-app: [12464:0x102892000]    56698 ms: Scavenge 2042.9 (2051.0) -> 2042.6 (2051.5) MB, 6.7 / 0.0 ms  (average mu = 0.144, current mu = 0.010) allocation failure
ccp-web-public-app: [12464:0x102892000]    57405 ms: Mark-sweep 2043.3 (2051.5) -> 2043.1 (2052.0) MB, 676.9 / 0.0 ms  (+ 69.5 ms in 19 steps since start of marking, biggest step 6.5 ms, walltime since start of marking 761 ms) (average mu = 0.140, current mu = 0.135) allocat
ccp-web-public-app: <--- JS stacktrace --->
ccp-web-public-app: ==== JS stack trace =========================================
ccp-web-public-app:     0: ExitFrame [pc: 0x100930c99]
ccp-web-public-app:     1: StubFrame [pc: 0x1008e7f56]
ccp-web-public-app: Security context: 0x2ecddb5408a1 <JSObject>
ccp-web-public-app:     2: fillSignature(aka fillSignature) [0x2ecd619d40a1] [/Users/roberto/dev/cnp/web/public-app/node_modules/typescript/lib/typescript.js:~16971] [pc=0x2a1b453ea910](this=0x2ecd4bbc04a9 <undefined>,56,0,0x2ecdf2f75121 <NodeObject map = 0x2ecd7b957ae1>)
ccp-web-public-app:     3: parsePropertyOrMethodDeclaration(aka parsePropertyOrMethodDeclaratio...
ccp-web-public-app: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
ccp-web-public-app: Writing Node.js report to file: report.20200411.003302.12464.0.001.json
ccp-web-public-app: Node.js report completed
ccp-web-public-app:  1: 0x10007e9b3 node::Abort() [/Users/roberto/.nvm/versions/node/v12.13.1/bin/node]
ccp-web-public-app:  2: 0x10007eb37 node::OnFatalError(char const*, char const*) [/Users/roberto/.nvm/versions/node/v12.13.1/bin/node]
ccp-web-public-app:  3: 0x100176337 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/roberto/.nvm/versions/node/v12.13.1/bin/node]
ccp-web-public-app:  4: 0x1001762d3 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/roberto/.nvm/versions/node/v12.13.1/bin/node]
ccp-web-public-app:  5: 0x1002fa485 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/roberto/.nvm/versions/node/v12.13.1/bin/node]
ccp-web-public-app:  6: 0x1002fbb54 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/roberto/.nvm/versions/node/v12.13.1/bin/node]
ccp-web-public-app:  7: 0x1002f8a27 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/roberto/.nvm/versions/node/v12.13.1/bin/node]
ccp-web-public-app:  8: 0x1002f6a0d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/roberto/.nvm/versions/node/v12.13.1/bin/node]
ccp-web-public-app:  9: 0x100302124 v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/roberto/.nvm/versions/node/v12.13.1/bin/node]
ccp-web-public-app: 10: 0x10030219f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/roberto/.nvm/versions/node/v12.13.1/bin/node]
ccp-web-public-app: 11: 0x1002ced97 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType) [/Users/roberto/.nvm/versions/node/v12.13.1/bin/node]
ccp-web-public-app: 12: 0x1005f83e5 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/roberto/.nvm/versions/node/v12.13.1/bin/node]
ccp-web-public-app: 13: 0x100930c99 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/roberto/.nvm/versions/node/v12.13.1/bin/node]
ccp-web-public-app: 14: 0x1008e7f56 Builtins_StoreIC [/Users/roberto/.nvm/versions/node/v12.13.1/bin/node]
ccp-web-public-app: 15: 0x2a1b453ea910
ccp-web-public-app: sh: line 1: 12462 Abort trap: 6           npm run build:lint
ccp-web-public-app: npm ERR! code ELIFECYCLE
ccp-web-public-app: npm ERR! errno 134
ccp-web-public-app: npm ERR! ccp-web-public-app@1.0.0 build: `npm run prettier:fix && npm run build:lint && npm run build:ng`
ccp-web-public-app: npm ERR! Exit status 134

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.24.0` |
| `@typescript-eslint/parser`            | `2.24.0` |
| `TypeScript`                       | `^2.6.2` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `12.13.1` |
| `npm`                              | `6.13.4` |

**Comment by bradzacher** [comment]
See discussion and workarounds in #1192.
