### ISSUE TITLE
Rule Detail Documentation

### ISSUE THREAD

**Issue by fishcharlie** [typescript-eslint/typescript-eslint#1883]
ESLint has [great documentation for each rule that exists in the linter](https://eslint.org/docs/rules/). This can be very helpful for learning about why a rule is suggested practice and the implications of disabling a given rule. It also helps understand any specific information about a given rule.

Is there similar documentation for typescript-eslint? Is this something that is on the roadmap or being considered?

**Comment by bradzacher** [comment]
We have a list of rules in the plugin readme: https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin

And that list links to the documentation for each rule. Is that what you're looking for?

**Comment by fishcharlie** [comment]
@bradzacher Yes that looks like what I'm looking for! Thank you. Was originally looking in the root README, not the sub folder README files. Might be worth it to add a link from the root README? Who knows. Just my experience. Thank you!!
