### ISSUE TITLE
NPM warns about "parser" requires eslint 5 peer error shown; I have eslint 6, no typescript!

### ISSUE THREAD

**Issue by rowild** [typescript-eslint/typescript-eslint#1892]
I don't know how to setup a repo anywhere that shows npm error/warning messages.

```JSON```

No JSON defined by myself

```TS```

I do not use Typescript!

**Additional Info**

I have a regular Vue project that was setup with vue-cli. Suddenly, obviously after an update, because I installed an additional plugin (@babel/plugin-syntax-dynamic-import), this error is thrown in the console:

```sh
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
```

(The mentioned plugin has no such dependency; but I assume that the project was update during the process of installing it...)

I do not even use Typescript! And I have eslint 6 installed.
Why is this error thrown?

It happens during installation of npm dependencies, so there is no linting process in action yet,

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `1.13.0` |
| `TypeScript`                | NONE!!! |
| `ESLint`                    | `6.7.2` |
| `node`                      | `v12.16.1` |
| `npm`                       | `6.14.4` |

EDIT:
After running
`npm ls '@typescript-eslint/parser@1.13.0'`
I get informed that prettier-eslint requires this extension:
```
└─┬ prettier-eslint@9.0.1
  └── @typescript-eslint/parser@1.13.0 
```
`prettier-eslint` is a dependency installed by vue-cli. It did not throw any warnings up until recently (at the time of writing this parser library was updated 6 hours ago according to its npm page).

**Comment by bradzacher** [comment]
> at the time of writing this parser library was updated 6 hours ago according to its npm page

We push a canary release for every commit to master. It's not released on the `latest` tag that you'd be using.
Also on the NPM page you looked at, you'll notice that the latest versions are `2.27.0`, which is a large leap away from the `1.13.0` that was installed for you.

----

I think you answered your own question here.
you've installed vue-cli, which installs prettier-eslint, which installs (an old version of) our parser.

**Comment by rowild** [comment]
Makes sense. Thank you for bringing that to my attention, @bradzacher !
