### ISSUE TITLE
[ban-getter-setter] Ban usage of getters/setters due to TS backwards compatibility

### ISSUE THREAD

**Issue by snebjorn** [typescript-eslint/typescript-eslint#1907]
# Proposal

**ban-getter-setter**: This rule bans the ES2015 syntax for class getters and setters.

## Reasoning

Usage of this syntax is breaking backwards compatibility with typescript definitions files (d.ts) prior to v3.7. See https://github.com/microsoft/TypeScript/issues/33939

Basically if you're compiling a library with >=3.7 then people using that library cannot use typescript <3.7 else they'll get this compile error
> error TS1086: An accessor cannot be declared in an ambient context.

This rules is not relevant as an ESLint rule as it's purely a typescript issue.

[A proposed fix](https://github.com/microsoft/TypeScript/issues/36207) but it's no way near finalized and it's not endorsed by the TS team. At least not yet.

[A workaround exists](https://github.com/sandersn/downlevel-dts) but it introduces more tooling complexity and errors will be hard to spot. Besides the library will be stuck at the downleveled d.ts. I'm thinking that'll introduce a bunch of other issues.

**Comment by bradzacher** [comment]
I don't think banning all getters and setters is the best solution for this.
It's not just a problem with getters and setters.
If you use most of the 3.8 features (`import type`, private class props, `export * from 'x'`), then your types won't work with older versions.

`downlevel-dts` seems like an adequate solution - it gives you a pathway to gracefully support breaking changes, and target specific versions of TS. This is the same thing almost all web build chains do with babel polyfills - allowing support of old browsers (old ECMAScript versions).

That being said, if you want to ban them, then you can use [`no-restricted-syntax`](https://eslint.org/docs/rules/no-restricted-syntax).
https://eslint.org/docs/developer-guide/selectors describes what a selector is.
https://astexplorer.net/ will help you inspect the AST structure so you can determine the selector to use, should you want to ban specific things.

Eg `Property[kind = "get"], MethodDefinition[kind = "get"]` will match getters.

Closing as a rule already exists for this.
