### ISSUE TITLE
[interface-name-prefix] Interface name should not prefix with I.

### ISSUE THREAD

**Issue by rakeshshubhu** [typescript-eslint/typescript-eslint#1915]
Rather than a bug, I need help about how I can use it. I understand what to do but I cannot make it work.
I tried to put the rules like that which doesn't work.

```
"overrides": [
        {
            "files" : "**/*.+(ts|tsx)",
            "parser" : "@typescript-eslint/parser",
            "parserOptions": {
                "project" : "./tsconfig.json"
            },
            "plugins" : ["@typescript-eslint/eslint-plugin"],
            "extends" : [
                "plugin:@typescript-eslint/eslint-recommended",
                "plugin:@typescript-eslint/recommended",
                "eslint-config-prettier/@typescript-eslint"
            ],
            "rules" : {
               "@typescript/interface-name-prefix" : "off"
            }
        }
    ]
```

after reading (interface-name-prefix rule)[https://github.com/typescript-eslint/typescript-eslint/blob/v2.28.0/packages/eslint-plugin/docs/rules/interface-name-prefix.md]
I tried but doesn't work where should I exactly keep the rules.
```
"overrides": [
        {
            "files" : "**/*.+(ts|tsx)",
            "parser" : "@typescript-eslint/parser",
            "parserOptions": {
                "project" : "./tsconfig.json"
            },
            "plugins" : ["@typescript-eslint/eslint-plugin"],
            "extends" : [
                "plugin:@typescript-eslint/eslint-recommended",
                "plugin:@typescript-eslint/recommended",
                "eslint-config-prettier/@typescript-eslint"
            ],
            "rules" : {
               "@typescript/interface-name-prefix" : {"prefixWithI" : "always"}
            }
        }
    ]
```

**Comment by bradzacher** [comment]
Two things:
1) notice the section at the top of the readme. This rule is deprecated, and will be removed in future versions - you should not be adding new usages of it.
2) please read the ESLint docs on configuring rules: https://eslint.org/docs/user-guide/configuring#configuring-rules

**Comment by rakeshshubhu** [comment]
@bradzacher yes I read it but currently in my project in my project I want to disable it. I went through the eslint docs about rules but I cannot figure out to disable typescript eslint rule.

**Comment by bradzacher** [comment]
`"@typescript/interface-name-prefix" : "off"` is all you need to disable a rule.
If it's not working, then likely your config is incorrect for the given file(s).
You can use the eslint CLI to help you figure out what config is resolved or a given file:
https://eslint.org/docs/user-guide/command-line-interface#print-config

**Comment by rakeshshubhu** [comment]
@bradzacher Thanks a lot.
