### ISSUE TITLE
vscode-eslint: Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser

### ISSUE THREAD

**Issue by Vishesh30** [typescript-eslint/typescript-eslint#1937]
What code were you trying to parse?

`import { Af } from "@common/models";`

What did you expect to happen?

no errors

What actually happened?
vscode-eslint yells at me. Running in cli is fine. Below is error message i get:-

**_Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/models/BankAccount.ts.
The file must be included in at least one of the projects provided._**

We have a Monorepo using "lerna" Our settings.json file has this config to support monorepo:-

`"eslint.workingDirectories": [{ "pattern": "./packages/*/" }],`

My configuration in .eslintrc.js file:-
```
module.exports = {
    env: {
        browser: true,
        es6: true,
        node: true
    },
    extends: [
        "eslint:recommended",
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "prettier",
        "prettier/@typescript-eslint", // Uses eslint-config-prettier to disable ESLint rules from @typescript-eslint/eslint-plugin that would conflict with prettier
        "plugin:prettier/recommended" // Enables eslint-plugin-prettier and eslint-config-prettier.
    ],
    parser: "@typescript-eslint/parser", // Specifies the ESLint parser
    parserOptions: {
        ecmaVersion: 2018, // Allows for the parsing of modern ECMAScript features
        project: "tsconfig.json",
        sourceType: "module"
    },
    plugins: ["@typescript-eslint", "prettier"],
    rules: {},
    settings: {}
};
```
My tsconfig file:-

```
{
    "compileOnSave": true,
    "compilerOptions": {
        "moduleResolution": "Node",
        "esModuleInterop": true,
        "module": "commonjs",
        "target": "es6",
        "sourceMap": true,
        "alwaysStrict": true,
        "outDir": "./build",
        "rootDir": "./src",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": true,
        "resolveJsonModule": true,
        "incremental": true,
        "tsBuildInfoFile": "./.tsBuildInfoFile"
    },
    "files": [
        "./src/common/models/DataTypes.ts"
    ],
    "include": ["./src/**/*", "tests/InternalRequest"],
    "exclude": ["./node_modules/", "./src/tests/**/*.gen.ts", "./src/**/models/"]
}
```

Error Message from eslInt:-
**_Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/models/BankAccount.ts.
The file must be included in at least one of the projects provided._**

However, when i include the "createDefaultProgram" in im .eslintrc.js file it start working fine.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `^2.20.2` |
| `@typescript-eslint/eslint-plugin` | `^2.20.0` |
| `TypeScript`                | `3.7.5` |
| `ESLint`                    | `^6.8.0` |
| `node`                      | `^10.15.3` |
| `npm`                       | `6.10.1` |

Reporting the issue as i have already looked into multiple issue but, couldn't find any solution.

**Comment by bradzacher** [comment]
It looks like you're explicitly excluding the `models` folder:

```
"exclude": ["./node_modules/", "./src/tests/**/*.gen.ts", "./src/**/models/"]
                                                          ^^^^^^^^^^^^^^^^^^
```

Which means that our tooling excludes it as well.

**Comment by Vishesh30** [comment]
@bradzacher  - Thanks a lot for your quick response. Sorry but, yes it was a mistake from my end i will correct it.
