### ISSUE TITLE
New rule: `no-inline-comments`

### ISSUE THREAD

**Issue by hbergren** [typescript-eslint/typescript-eslint#1942]
ESLint has a rule called [`no-inline-comments`](https://eslint.org/docs/rules/no-inline-comments) that disallows inline comments.

I think that it's a fairly useful rule for our coding style, _except_ that I would like to allow inline comments in `enum` and `interface` definitions.

It would be great to have a `@typescript-eslint` version of this rule that allowed for some configuration to allow inline comments in certain settings.

**Comment by bradzacher** [comment]
We don't like to break from ESLint when implementing extension rules - we endeavour to try to only enhance the rule such that it either supports TS syntax, or uses type information to do a better job, and we avoid adding extra options unless it makes sense.

In this case:
- there's nothing typescript-specific about the extension
- there's no type information required
- the new options don't make sense in the context of the existing rule which has no options.

I'd suggest either:
- file a request with eslint core to add option(s) to the base rule, which we can then enhance as required in this plugin
- implement yourself in another eslint plugin.

Thanks for the suggestion!
