### ISSUE TITLE
no-empty-interface rule does not work with utility types

### ISSUE THREAD

**Issue by richardenelson** [typescript-eslint/typescript-eslint#1951]
I have [no-empty-interface](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-empty-interface.md) turned on in my linting config, but it triggers when using [utility types](https://www.typescriptlang.org/docs/handbook/utility-types.html) to make new interfaces.  Is this working as intended?

```
interface IFoo {
  x: number;
  y: number;
  z: number;
}

interface IBar extends Pick<IFoo, "x" | "y"> { } // triggers linting issue
```

**Comment by bradzacher** [comment]
Yup, you can represent that type with simply

```ts
type IBar = Pick<IFoo, ...>;
```
