### ISSUE TITLE
Out of memory when syntax error in tsconfig.json

### ISSUE THREAD

**Issue by Karolusrex** [typescript-eslint/typescript-eslint#1952]
**Repro**

eslintrc.js:

```javascript
module.exports = {
  parser: '@typescript-eslint/parser',
  root: true,
  parserOptions: {
    project: './tsconfig.json',
  }
};
```

tsconfig.json:

```JSON
asd
```

**Expected Result**

Some kind of error message indicating that `tsconfig.json` is invalid.

**Actual Result**

A very long wait, then:

`Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

...and loads of other output regarding the OOM failure

**Additional Info**

Running Ubuntu over here

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.29.0` |
| `TypeScript`                | `3.8.3` |
| `ESLint`                    | `6.8.0` |
| `node`                      | `12.16.2` |
| `npm`                       | `6.14.4` |

**Comment by bradzacher** [comment]
I'm unable to repro this.
Could you please provide a repro repo?
