### ISSUE TITLE
 Definition for rule '@typescript-eslint/no-object-literal-type-assertion' was not found 

### ISSUE THREAD

**Issue by alanhg** [typescript-eslint/typescript-eslint#1967]
1:1  error  Definition for rule '@typescript-eslint/no-object-literal-type-assertion' was not found  @typescript-eslint/no-object-literal-type-assertion

```
    "@typescript-eslint/eslint-plugin": "^2.30.0",
    "@typescript-eslint/eslint-plugin-tslint": "^2.30.0",
    "@typescript-eslint/parser": "^2.30.0",
  "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jsdoc": "^24.0.0",
    "eslint-plugin-prefer-arrow": "^1.2.0",
```

**Comment by bradzacher** [comment]
need more information than that.
what does your config look like?

help me to help you

**Comment by sgarner** [comment]
This rule has been removed and replaced by [consistent-type-assertions](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-assertions.md), I believe.
