### ISSUE TITLE
[@typescript-eslint/no-unsafe-assignment] It's triggered on JS files where almost any assignment is unsafe

### ISSUE THREAD

**Issue by deser** [typescript-eslint/typescript-eslint#1975]
Hey, I'm having latest versions of everything. Rule `@typescript-eslint/no-unsafe-assignment` is triggered in JS files where I can't add types:
![image](https://user-images.githubusercontent.com/3010698/81057163-96a79f00-8ed4-11ea-9bc8-7701ad4e079c.png)

**Comment by bradzacher** [comment]
You can either:
- use jsdoc comments to specify types, and turn on JS checking in your tsconfig.
- use eslint [`overrides`](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) config to disable the rule on JS files.

**Comment by deser** [comment]
Ok, thx
