### ISSUE TITLE
[no-non-null-asserted-optional-chain] support 3.9's new interaction between optional chains and non-null assertions

### ISSUE THREAD

**Issue by fregante** [typescript-eslint/typescript-eslint#1976]
From: https://devblogs.microsoft.com/typescript/announcing-typescript-3-9-beta/#breaking-changes

> Specifically, in previous versions, the code
> 
> ```ts
> foo?.bar!.baz
> ```
> was interpreted to be equivalent to the following JavaScript.
> ```ts
> (foo?.bar).baz
> ```
> In the above code the parentheses stop the “short-circuiting” behavior of optional chaining, so if foo is undefined, accessing baz will cause a runtime error.

`@typescript-eslint/no-non-null-asserted-optional-chain` made sense in that case but TS 3.9 will change the behavior to this:

> ```ts
> foo?.bar.baz
> ```
> which just evaluates to `undefined` when `foo` is undefined.

So `foo?.bar!.baz` becomes perfectly reasonable to catch an undefined `foo` but ignore an undefined `foo.bar`

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.27.0` |
| `@typescript-eslint/parser`        | `2.27.0` |
| `TypeScript`                       | `3.9` (future) |
| `ESLint`                           | `6.8.0` |
| `node`                             | `12.15` |
| `npm`                              | `6.13.6` |

**Comment by bradzacher** [comment]
Interesting. When reading the release notes, I didn't quite understand that point correctly.

This makes it much clearer:

**TS 3.8**
```ts
type T = { a: { b: { c: string } } };
declare const x: T | null;

const a = x;       // typeof === T | null
const b = x?.a;    // typeof === T['a'] | undefined;
const c = x?.a!;   // typeof === T['a']
const d = x?.a.b;  // typeof === T['b'] | undefined
const e = x?.a!.b; // typeof === T['b']
const f = x?.a.b!; // typeof === T['b']
```
[repl](https://www.typescriptlang.org/v2/en/play?ts=3.8.3#code/C4TwDgpgBAKlC8UDeUCGAuZUBGmUGNMBnYAJwEsA7AcygF976BuAKABMJ8AbVU6fAPaUSUAB6Y4AHyiUArly6sWg4cDQIxTKNp1QA9HqihIAgGYJ4iKTPldlQkdg2iA-ADpUWnQaPgIZiysAbQByVBCAXShpWUoOUyoINlYVEXxnd1QAQi99Q2N-c0tgsMj7VSg2DI83bC8fAoDi2FDsSOioWPjEtnKRaERXDyzarQa-JssWkLaIvrUisUzanLzfEyKpmFbIoA)

**TS 3.9**
```ts
type T = { a: { b: { c: string } } };
declare const x: T | null;

const a = x;       // typeof === T | null
const b = x?.a;    // typeof === T['a'] | undefined;
const c = x?.a!;   // typeof === T['a']
const d = x?.a.b;  // typeof === T['b'] | undefined
const e = x?.a!.b; // typeof === T['b'] | undefined
const f = x?.a.b!; // typeof === T['b']
```
[repl](https://www.typescriptlang.org/v2/en/play?ts=3.9.0-beta#code/C4TwDgpgBAKlC8UDeUCGAuZUBGmUGNMBnYAJwEsA7AcygF976BuAKABMJ8AbVU6fAPaUSUAB6Y4AHyiUArly6sWg4cDQIxTKNp1QA9HqihIAgGYJ4iKTPldlQkdg2iA-ADpUWnQaPgIZiysAbQByVBCAXShpWUoOUyoINlYVEXxnd1QAQi99Q2N-c0tgsMj7VSg2DI83bC8fAoDi2FDsSOioWPjEtnKRaERXDyzarQa-JssWkLaomLiIBMokvrUisUzanLzfEyKpmFbIoA)

So if you're on TS 3.9, then it makes sense to remove the functionality that stops non-null assertions _within_ an optional chain.

HOWEVER, the rule isn't useless. It's still completely incorrect to use a non-null assertion at the end of an optional chain `x?.a.b!`.
This was actually the case that the rule was intended to catch.

I think it's reasonable to add a check to allow a non-null-assertion around an optional chain if, and only if _all_ of the following are matched:
- the TS version is 3.9
- the non-null-assertion parent is:
  - an `OptionalMemberExpression` with `optional: false`
  - an `OptionalCallExpression` with `optional: false`

That will allow `x?.a!.b` and `x?.a!()`, but it will still ban:
- `x?.a!?.b` and `x?.a!?.()`
- `x?.a!` and `x?.a()!`
- `(x?.a)!` and `(x?.a)!()`

**Comment by fregante** [comment]
Awesome!
