### ISSUE TITLE
[simple question] is it possible to leverage .d.ts declarations for linting of vanilla javascript?

### ISSUE THREAD

**Issue by fanick1** [typescript-eslint/typescript-eslint#1978]
Hi, I have a stupid question - would it be somehow possible to leverage typescript and its ecosystem (compiler, typescript-eslint etc.) to check code written in vanilla javascript? 

Let's assume I'd provide ambient declarations (in .d.ts files) for some library that I use. And I would like to use this for checking the code (written in javascript only) that uses the library.
Is this possible? I have this intuition that it should be possible, but I haven't found any conclusive answers on the internet.

The only thing that remotely resembles intended goal is the support for typescript in Intellij IDEA - if I drop a foo.d.ts file among javascripts, IDEA is able to pick the type information in the foo.d.ts and enhance its own "intelli sense" understanding of the source code - it can then recommend methods/properties etc.

**Comment by bradzacher** [comment]
TypeScript supports checking JS files out of the box!
https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html

The user can either opt in per file with a `// @ts-check` comment, or opt in at the config level with either a `jsconfig.json` or a `tsconfig.json` with `checkJs: true`.

TypeScript will then type check the JS code as if it was TS code - it'll load all definition files where possible, and it'll use JSDoc comments as if they were type declarations.

If your package includes types, typescript will automatically use them when the js code `require()`s your module.
The use can also use special jsdoc import syntax to consume your types:
```ts
/** @type {import('foo').bar} */
const x = someValue; // typed as "bar" from the foo package
```

Our type-aware lint rules just consume the type information provided by TS, so if you've set all of this up, they'll "just work"

**Comment by fanick1** [comment]
Thanks for the quick response. 
In the end it didn't work out that well for my use case. For example the typescript-eslint did not report usage of undeclared methods. 
In code like this:
```
define('mylib/Foo', [
 'mylib/Bar',
 'mylib/Baz'], 
function (
  Bar,
  Baz){
 Bar.unknownMethod(); 
});
```
When I provided type declaration for the 'mylib/Bar' module, the analysis did not report the usage of undeclared `Bar.unknownMethod`. I also had dropped in the declaration for the require.js library (copied from the DefinitelyTyped  project) that I use in the code, but I think this simply does not work the way I thought it would.

**Comment by bradzacher** [comment]
This should be able to be typed by

```
​define('mylib/Foo', [
 'mylib/Bar',
 'mylib/Baz'], 
function (
  /** @type {import('mylib/Bar')} */
  Bar,
  /** @type {import('mylib/Baz')} */
  Baz
){
 Bar.unknownMethod(); 
});
```

(I can't remember if it is `import('mod')` or `typeof import('mod')`)
