### ISSUE TITLE
eslint-plugin: peerDependency warning with eslint@7.0.0

### ISSUE THREAD

**Issue by AviVahl** [typescript-eslint/typescript-eslint#1994]
**Actual**
eslint@7.0.0 [has been released](https://github.com/eslint/eslint/releases/tag/v7.0.0) yesterday. `@typescript-eslint/eslint-plugin` gets a peerDependency warning:
```
npm WARN @typescript-eslint/eslint-plugin@2.31.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
```

**Expected**
Install without warnings when used with the latest eslint release.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.31.0` |
| `@typescript-eslint/parser`        | `2.31.0` |
| `TypeScript`                       | `3.8.3` |
| `ESLint`                           | `7.0.0` |
| `node`                             | `12.6.3` |
| `npm`                              | `6.14.4` |

**Comment by bradzacher** [comment]
This is valid.
We don't yet support ESLint v7 - we have not tested any of our project against it.

Once we support it, we will update the version numbers.
