### ISSUE TITLE
@typescript-eslint/parser for browser

### ISSUE THREAD

**Issue by mittalalok** [typescript-eslint/typescript-eslint#1995]
Hi All,

I want to use eslint in a browser-based editor. 

how can I use '@typescript-eslint/parser'?

I thought of generating bundle via require('@typescript-eslint/parser) but it's throwing an error 'Cannot read property 'EqualsToken' of undefined' in side "/@typescript-eslint/typescript-estree/dist/node-utils.js:20"

**Comment by bradzacher** [comment]
You will likely run into many problems just trying to use this tooling out of the box.
There are a lot of assumptions made in the ESLint world about the existence of a filesystem.

For our parser - you're going to need to ensure typescript is also bundled with your application.
Though note that again, type aware parsing assumes there is a file system.

**Comment by mittalalok** [comment]
> You will likely run into many problems just trying to use this tooling out of the box.
> There are a lot of assumptions made in the ESLint world about the existence of a filesystem.
> 
> For our parser - you're going to need to ensure typescript is also bundled with your application.
> Though note that again, type aware parsing assumes there is a file system.

Can you suggest how can I move on?  I am stuck :(

**Comment by bradzacher** [comment]
With the information you've given me: nope.

I don't know anything about what you're trying to do, or how you're trying to do it.

Help me to help you.

**Comment by mittalalok** [comment]
> With the information you've given me: nope.
> 
> I don't know anything about what you're trying to do, or how you're trying to do it.
> 
> Help me to help you.





> With the information you've given me: nope.
> 
> I don't know anything about what you're trying to do, or how you're trying to do it.
> 
> Help me to help you.

I have generated eslint bundle via browserify, same like in https://github.com/satya164/eslint-browser. (can see find details in browserify script) 

Now I need to generate bundle of '@typescript-eslint/parser’ which can be loaded in a browser. 

Once this parser available in browser, I will do something like: 

linter = new eslint();
linter.defineParser('@typescript-eslint/parser', ts_parser);

**Comment by bradzacher** [comment]
The only advice I can give you is to ensure all the dependencies are bundled with the correct versions.

`Cannot read property 'EqualsToken' of undefined` implies that there's something that was not imported from TypeScript.
