### ISSUE TITLE
How to enforce 2 lines not just one with [lines-between-class-members]

### ISSUE THREAD

**Issue by seanpmaxwell** [typescript-eslint/typescript-eslint#2014]
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/tslint/config": ["warn", {
      "rules": {
        "rule": "setting",
      },
      "rulesDirectory": [
        "node_modules/foo"
      ]
    }],
  }
}
```

```JSON
{
  "extends": "tslint:recommended",
  "rules": {
    "lines-between-class-members": [true, 2], <--- This right here, enforces 2 lines
  },
  "rulesDirectory": [
    "node_modules/tslint-lines-between-class-members"
  ]
}
```

// Valid
```TS
   
    public componentDidMount(): void {
        this._isMounted = true;
        this.getProjects();
        this.getPendingInvites();
    }

    
    public componentWillUnmount(): void {
        this._isMounted = false;
    }
```

// Invalid
```TS
    public componentDidMount(): void {
        this._isMounted = true;
        this.getProjects();
        this.getPendingInvites();
    }
    
    public componentWillUnmount(): void {
        this._isMounted = false;
    }
```

**Versions**

| package                                   | version |
| ----------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin-tslint` | `X.Y.Z` |
| `@typescript-eslint/parser`               | `X.Y.Z` |
| `TypeScript`                              | `X.Y.Z` |
| `ESLint`                                  | `X.Y.Z` |
| `node`                                    | `X.Y.Z` |
| `npm`                                     | `X.Y.Z` |

**Comment by bradzacher** [comment]
There is no option to do this.

If it's important to you - you should consider submitting a feature request (and a subsequent PR) to the rule in the [ESLint repository](https://github.com/eslint/eslint)
