### ISSUE TITLE
@typescript-eslint/eslint-plugin needs peerDependencies updated to support new eslint@7.0.0

### ISSUE THREAD

**Issue by nickharris** [typescript-eslint/typescript-eslint#2017]
**Repro**
eslint 7 was recently released https://www.npmjs.com/package/eslint/v/7.0.0 you take a peer dependency on 5 and 6 only.

1. update to the new eslint@7.0.0   `npm install --save eslint@7.0.0`
2. `npm install  @typescript-eslint/eslint-plugin-tslint@2.32.0`
2. Get error > *npm WARN @typescript-eslint/eslint-plugin@2.32.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.**.

looks like package.json peerDependencies needs to be updated to add `|| ^7.0.0` for eslint.

**Expected Result**
no warning on install 
**Actual Result**
npm WARN @typescript-eslint/eslint-plugin@2.32.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

**Additional Info**
looks like package.json peerDepenencies needs to be updated to add `|| ^7.0.0` for newly released eslint 7 https://www.npmjs.com/package/eslint/v/7.0.0

**Versions**

| package                                   | version |
| ----------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `^2.32.0` |
| `@typescript-eslint/parser`               | `^2.32.0` |
| `TypeScript`                              | `3.5.3` |
| `ESLint`                                  | `7.0.0` |
| `node`                                    | `12.13.0` |
| `npm`                                     | `6.13.6` |

**Comment by bradzacher** [comment]
See #1550

**Comment by nickharris** [comment]
ack
