### ISSUE TITLE
missing `json-schema` in dependencies

### ISSUE THREAD

**Issue by missing1984** [typescript-eslint/typescript-eslint#2019]
**Repro**
When using `@typescript-eslint` with yarn 2, it reported a missing dependency.

```
@typescript-eslint/experimental-utils tried to access json-schema, but it isn't declared in its dependencies
```
Looks like @typescript-eslint/experimental-utils is using  `json-schema` so it should declare `json-schema` as its dependency

**Expected Result**

declare `json-schema`  as its dependency

**Comment by existentialism** [comment]
@missing1984 check out https://github.com/typescript-eslint/typescript-eslint/issues/2012

**Comment by bradzacher** [comment]
See #2009 and many others
Please use the search next time

This has been fixed - update your version
