### ISSUE TITLE
Rule proposal: Prefer non-null assertion operator over type assertion

### ISSUE THREAD

**Issue by sindresorhus** [typescript-eslint/typescript-eslint#202]
I have the following code:

```ts
function foo(count: number) {}

// …

foo(count: lookup);
```

Where `lookup` is `number | undefined`.

In this code path, I know for sure that `lookup` will be a number, so I have done the following:

```ts
foo(count: lookup as number);
```

But a better solution would have been to use the [non-null assertion operator](https://stackoverflow.com/questions/42273853/in-typescript-what-is-the-exclamation-mark-bang-operator-when-dereferenci):

```ts
foo(count: lookup!);
```

I would like a rule that enforces this.

---

It should be noted in the rule docs that this conflicts with the `no-non-null-assertion` rule.

Alternatively, the `no-non-null-assertion` could be renamed to `non-null-assertion` and handle both ways. That might be even better.

**Comment by bradzacher** [comment]
this would probably be better suited being rolled into a rule like [`no-object-literal-type-assertion`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-object-literal-type-assertion.md)

**Comment by j-f1** [comment]
`type-assertion-style`?

**Comment by JoshuaKGoldberg** [comment]
Now that `no-object-literal-type-assertion` is renamed to [`consistent-type-assertions`](https://github.com/typescript-eslint/typescript-eslint/blob/af2c00d/packages/eslint-plugin/docs/rules/consistent-type-assertions.md), is it still preferable to add to that rule? This issue's proposal is a type system check whereas `consistent-type-assertions` is just a syntax standardizer.

**Comment by bradzacher** [comment]
because this requires type information, I'd lean towards this being a new rule.
there's a non-trivial number of users that don't use type-aware linting, which means introducing it into an existing rule is a breaking change which will cause a lot of pain for users as they won't be able to use the rule any more.
