### ISSUE TITLE
@typescript-eslint/eslint-plugin@3.0.0-alpha.23 requires a peer of @typescript-eslint/parser@^2.0.0

### ISSUE THREAD

**Issue by ankon** [typescript-eslint/typescript-eslint#2030]
https://github.com/typescript-eslint/typescript-eslint/blob/1d3a5ce20cbbc39672a78f744821a6cff6c96d5b/packages/eslint-plugin/package.json#L57

Shouldn't this require @typescript-eslint/parser@^3.mumble.mumble? Installing the 2.x variant otherwise will be complaining about the installed eslint 7.

**Comment by bradzacher** [comment]
It should!
I forgot that this needed to be updated. You can ignore the warning.

I was going to fix it last night, but npm had a mega outage.

**Comment by bradzacher** [comment]
2c709fcaae3f74a44d61c32c83c2ebc1c1838f65
