### ISSUE TITLE
Release note suggests support for TypeScript 3.9 but show warning

### ISSUE THREAD

**Issue by doberkofler** [typescript-eslint/typescript-eslint#2056]
**Repro**

The release notes for version 3.0.0 suggest multiple times that TypeScript 3.9 is supported but wa warning message is shown.

```bash
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <3.8.0

YOUR TYPESCRIPT VERSION: 3.9.3

Please only submit bug reports when using the officially supported version.
=============
```

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `3.0.0` |
| `TypeScript`                           | `3.9.3` |
| `node`                                 | `14.3.0` |
| `npm`                                  | `6.14.5` |

**Comment by bradzacher** [comment]
See pinned issue #1436

We "support" it in that it won't break, but we don't truly support it yet as we do not have support for private properties yet.

**Comment by bradzacher** [comment]
On second thought - #2075 - I'm just going to bump the version range for now.
It's not truly supported, but it won't break so it's supported enough.

We don't want to deter people from upgrading because 3.9 has performance improvements.

**Comment by doberkofler** [comment]
Thank you for caring. Maybe some distinction between supported as in "it will not break" and supported as in "it supports all new features" would be helpful for the future.
