### ISSUE TITLE
[naming-convention] How to configure to forbid I prefix for interfaces

### ISSUE THREAD

**Issue by simPod** [typescript-eslint/typescript-eslint#2065]
**Repro**

 I have been using this config with v2
```json
"@typescript-eslint/interface-name-prefix": [
    "error", {
        "prefixWithI": "never"
    }
],
```

The rule was removed in favor of `naming-convention`. I'm trying to configure the same

```json
"@typescript-eslint/naming-convention": [
    "error",
    {
        "selector": "interface",
        "format": ["PascalCase"],
        "prefix": ["I"]
    }
```

which requires `I` prefix now. I did not find a way to invert the condition though.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `3.0.0` |

**Comment by bradzacher** [comment]
It should be as simple as:

```
"@typescript-eslint/naming-convention": [
    "error",
    {
        "selector": "interface",
        "format": ["PascalCase"],
        "custom": {
            "regex": "^I[A-Z]",
            "match": false,
        }
    }
]
```

I'll add this to the docs

**Comment by simPod** [comment]
Works like a charm, thanks, much appreciated!
