### ISSUE TITLE
Docs error. getting-started still refers to plugin:@typescript-eslint/eslint-recommended rules

### ISSUE THREAD

**Issue by David-Else** [typescript-eslint/typescript-eslint#2069]
I thought with v3.0.0 `plugin:@typescript-eslint/eslint-recommended` was gone?

https://github.com/typescript-eslint/typescript-eslint/commit/729f2a219a46db49b1a5331bddaf37a59d2e1b1c

But https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md still refers to it many times. I assume this is a mistake.

I found the wording very confusing in the v3 release notes:

> Both of the recommended and recommended-requiring-typechecking sets now inherit from the eslint-recommended set. We noticed that the majority of the time, users were using the sets in tandem, so this just removes one line of config for everyone.

What does 'inherit from' in this context mean? How about a quick description of how to update your config instead?

**Comment by bradzacher** [comment]
It's not gone, it's just no longer explicitly required.

Now if you configure
```
extends: [
  "recommended",
  "plugin:@typescript-eslint/eslint-recommended",
  "plugin:@typescript-eslint/recommended"
]
```
It's the same as
```
extends: [
  "recommended",
  "plugin:@typescript-eslint/recommended"
]
```

I'll update the docs to match.
