### ISSUE TITLE
How to use Airbnb configuration?

### ISSUE THREAD

**Issue by iwis** [typescript-eslint/typescript-eslint#2072]
I try to use Airbnb for several days and I don't know how.

**Comment by iwis** [comment]
I think I finally installed and configured it correctly: https://stackoverflow.com/questions/61963749/how-to-use-eslint-typescript-airbnb-configuration/61965129

**Comment by bradzacher** [comment]
Do the getting started docs help out here?
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md#eslint-configs

**Comment by iwis** [comment]
It only helped me by pointing me to eslint-config-airbnb-typescript web page. Maybe I would have done this faster, if I had known more about npm. I had to learn about semantic versioning, npx, etc. I am not sure if Airbnb's ESLint config can be configured without saying explicitly which [major versions](https://docs.npmjs.com/about-semantic-versioning) of the packages should be installed. Maybe it can, but I haven't found such description.

**Comment by bradzacher** [comment]
You're unfortunately setting everything up at a bit of a transitional stage of the ecosystem. As ESLint v7 has only recently been released, it will take a few weeks before everything in the ecosystem is upgraded accordingly.

It's probably best to stay on v6 for now until all your required packages are upgraded to support v7
