### ISSUE TITLE
ESLint 7.1.0 no-loss-of-precision: false positives for values with numeric separators

### ISSUE THREAD

**Issue by merlinnot** [typescript-eslint/typescript-eslint#2076]
I originally created an issue against `eslint/eslint`, but I was told it might be an issue with `@typescript-eslint/parser`, so I'm cross-posting here. Original issue contains a detailed description: https://github.com/eslint/eslint/issues/13346. I'd like to understand where the responsibility lies.

**Repro**

See original issue.

**Expected Result**

See original issue.

**Actual Result**

See original issue.

**Additional Info**

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `3.00` |
| `TypeScript`                | `3.9.3` |
| `ESLint`                    | `7.1.0` |
| `node`                      | `14.0.0` |
| `npm`                       | `6.14.4` |

**Comment by bradzacher** [comment]
not a parser issue - the rule doesn't understand that `raw` can contain underscores.
this will require a base rule extension
