### ISSUE TITLE
Supported typescript version is wrong in readme

### ISSUE THREAD

**Issue by zraineri** [typescript-eslint/typescript-eslint#2087]
**Expected Result**
"The version range of TypeScript currently supported by this parser is >=3.3.1 <3.10.0"

[This ](https://github.com/typescript-eslint/typescript-eslint/blob/master/README.md#supported-typescript-version) is linked from the @typescript-eslint/typescript-estree readme [here](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/typescript-estree#supported-typescript-version)

**Actual Result**
"
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <3.8.0

YOUR TYPESCRIPT VERSION: 3.9.3
"

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `3.0.0` |
| `TypeScript`                           | `3.9.3` |

Really appreciate all the hard work, just thought I'd make you aware

**Comment by lgodziejewski** [comment]
I guess it's the same case as in #2066 - i.e. support for new range of TS versions is merged to master and will be released tomorrow (Monday 25.05), [see comment](https://github.com/typescript-eslint/typescript-eslint/issues/2066#issuecomment-632823017)

PR with update: https://github.com/typescript-eslint/typescript-eslint/pull/2057
