### ISSUE TITLE
Feature Request: Add support for "Solution Style" tsconfig.json file

### ISSUE THREAD

**Issue by xiaoxiangmoe** [typescript-eslint/typescript-eslint#2091]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#support-for-solution-style-tsconfigjson-files
```jsonc
// tsconfig.json
{
  files: [],
  references: [
    { path: "./tsconfig.shared.json" },
    { path: "./tsconfig.frontend.json" },
    { path: "./tsconfig.backend.json" },
  ],
}
```
We should add `references.map(x=>x.path)` in `parserOptions.project`.

**Comment by bradzacher** [comment]
Closing in favour of #2094
