### ISSUE TITLE
Loss of WebStorm integration

### ISSUE THREAD

**Issue by E-Kuerschner** [typescript-eslint/typescript-eslint#210]
When upgrading our parser from `typescript-eslint-parser` to `@typescript-eslint/parser` WebStorm lost its ability to detect linting errors.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `1.2.0` |
| `TypeScript`                | `3.3.1` |
| `ESLint`                    | `5.13.0` |
| `node`                      | `v8.10.0` |
| `npm`                       | `5.6.0` |

Any thoughts on what may be causing this?

With the following config:
![image](https://user-images.githubusercontent.com/10578578/52246116-26156b00-28aa-11e9-82ef-c4c39643404e.png)

We get linting errors caught in editor:
![image](https://user-images.githubusercontent.com/10578578/52246138-447b6680-28aa-11e9-914d-1e8dbc350533.png)

And with the newer recommended config:
![image](https://user-images.githubusercontent.com/10578578/52246171-6aa10680-28aa-11e9-9f54-191ed1b30bf5.png)

No linting errors caught in editor :(
![image](https://user-images.githubusercontent.com/10578578/52246196-7c82a980-28aa-11e9-8870-8a88537f9599.png)

**Comment by armano2** [comment]
Intelij is not yet supporting new package, if you are not using 2019EAP you have to add `--ext .ts,.tsx` in `extra options`

![image](https://user-images.githubusercontent.com/625469/52246366-dce30c80-28e5-11e9-89f8-fc2b8ec7b51b.png)

issue is tracked here: https://youtrack.jetbrains.com/issue/WEB-36988
