### ISSUE TITLE
How to create my own custom fule?

### ISSUE THREAD

**Issue by yantrab** [typescript-eslint/typescript-eslint#2144]
Hi , there is an option to make my own rule like tslint?
I want to force using validation decorators in the models - 
https://github.com/yantrab/class-validator-rule#readme

**Comment by bradzacher** [comment]
Check out the ESLint docs for more information on creating eslint rules
https://eslint.org/docs/developer-guide/

You can have a look at the source code in this repository for examples of how to structure code.
You can also leverage our utility package to help write the rules.

**Comment by joelday** [comment]
@bradzacher I suspect the implication of the question is whether or not it is possible to use the existing infrastructure/utils to make a TypeScript eslint rule without any duplication of effort.

**Comment by joelday** [comment]
Not knowing much about the codebase, if I were to create a fresh eslint plugin project, what are the bare minimum things I would need to set up in order to make it work with TypeScript, including semantic analysis.

**Comment by bradzacher** [comment]
Explicit documentation for writing rules is on the todo list still.

The code in our `eslint-plugin` is the best documentation out there right now.
Rules that use type information are explicitly documented in the readme table with a 💭

From there you can view each rule's source code and learn about how the typescript APIs work.

Other than that, there's nothing obscured or hidden within this project - the utilities exposed in `experimental-utils` provide everything you need to not only write a rule in typescript, but also to safely access the parser services.

**Comment by joelday** [comment]
Was playing around with stuff earlier, experimental-utils is indeed basically everything you need. The automated rule testing stuff is great.
