### ISSUE TITLE
[naming-convention] Where did the global list of exceptions go?

### ISSUE THREAD

**Issue by kaiyoma** [typescript-eslint/typescript-eslint#2147]
The old `camelcase` rule had a property called `allow` that let us define a global list of exceptions. I've looked over the docs for `naming-convention` and I don't see an equivalent. How do we specify global exceptions?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `3.0.2` |
| `@typescript-eslint/parser`        | `3.0.2` |
| `TypeScript`                       | `3.9.3` |
| `ESLint`                           | `7.1.0` |
| `node`                             | `12.16.1` |
| `npm`                              | `6.13.4` |

**Comment by bradzacher** [comment]
What do you want to ignore? Could you provide some more context on why you want to have a global ignore list?

**Comment by kaiyoma** [comment]
Sure. In our project, we carry over some snake case identifiers from another system. When we fetch data from the server, the resulting data objects have some snake case properties.

I suppose we could ignore each usage individually, but a quick grep of the repo reveals that we'd have to add about 300 separate eslint ignore directives. The global ignore list was super handy because we could declare our exceptions in one place.

**Comment by bradzacher** [comment]
You can use the `filter` option to ignore names from your selectors: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#filter

Something along the lines of:
```js
{
  selector: 'property', 
  format: 'camelCase',
  filter: {
    regex: '(name_one|name_two|name_three)',
    match: false,
  }
}
```

**Comment by kaiyoma** [comment]
Oh cool! Let me try this out today and get back to you.

**Comment by kaiyoma** [comment]
@bradzacher That config isn't working for me. Here's the rule definition I have right now (verified by running `yarn eslint --print-config`:

```
    "@typescript-eslint/naming-convention": [
      "error",
      {
        "selector": "default",
        "format": [
          "camelCase",
          "PascalCase",
          "UPPER_CASE"
        ]
      },
      {
        "selector": "property",
        "format": [
          "camelCase",
          "PascalCase",
          "UPPER_CASE"
        ],
        "filter": {
          "regex": "(_skipLogging_|delete_all|path_elements)",
          "match": false
        }
      }
    ],
```

When run the linter, I get lots of these errors:

```
   21:9   error  Property name _skipLogging_ must match one of the following formats: camelCase, PascalCase, UPPER_CASE @typescript-eslint/naming-convention
   27:9   error  Property name _skipLogging_ must match one of the following formats: camelCase, PascalCase, UPPER_CASE @typescript-eslint/naming-convention
   52:7   error  Property name _skipLogging_ must match one of the following formats: camelCase, PascalCase, UPPER_CASE @typescript-eslint/naming-convention
```

**Comment by bradzacher** [comment]
apologies - a better config would be:
```json5
{
  selector: 'property', 
  format: null,
  filter: {
    regex: '(name_one|name_two|name_three)',
    match: true,
  }
}
```

The original config I gave you before ignores the names from the `property` selector config, but they are still matched by the `default` one.

This new one will match those names and explicitly enforce no formatting.

**Comment by kaiyoma** [comment]
Cool, this seems to be working, but what if I want to enforce formatting? Ideally, I'd like to force all properties to be either camel case or upper case, with a short list of exceptions. Is that possible? This is where the global exception list of version 2 would come in very handy.

**Comment by bradzacher** [comment]
The rule will automatically order and apply the selectors based on how specific they are. Having a `filter` gives the selector the _highest_ priority.

When one a name matches and passes (or fails) a selector, the rule does not check any other selectors for that name.

So you should be able to achieve this with::
```json5
[
  {
    selector: 'property',
    format: [
      'camelCase',
      'PascalCase',
      'UPPER_CASE'
    ],
  },
  {
    selector: 'property', 
    format: null,
    filter: {
      regex: '(name_one|name_two|name_three)',
      match: true,
    }
  }
]
```

**Comment by kaiyoma** [comment]
Excellent, I'll do that. Thanks so much for all your help! Hopefully this thread will be helpful to others who have the same issue in the future.
