### ISSUE TITLE
[no-this-alias] Showing documentation links to no-unused-vars

### ISSUE THREAD

**Issue by Cloud7050** [typescript-eslint/typescript-eslint#2154]
**Repro**

```JSON
	"extends": [
		"plugin:@typescript-eslint/recommended", 
	],
```
^enables `'@typescript-eslint/no-this-alias': 'error',`

```TS
let that = this; //causes linter to report problem
```

**Expected Result**
Its linked documentation redirects to https://github.com/typescript-eslint/typescript-eslint/blob/v3.0.2/packages/eslint-plugin/docs/rules/no-this-alias.md

**Actual Result**
Its linked documentation redirects to https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md

**Additional Info**
No linter exception

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `3.0.2` |
| `@typescript-eslint/parser`        | `3.0.2` |
| `TypeScript`                       | `3.8.3` |
| `ESLint`                           | `7.1.0` |
| `node`                             | `12.16.2` |
| `npm`                              | `6.14.5` |

**Comment by bradzacher** [comment]
I'm unable to repro. The links to our rule documentation is automatically generated based on filenames, so there's no way this could happen.

Likely the variable was _also_ unused, and you clicked on the wrong link:

![image](https://user-images.githubusercontent.com/7462525/83549239-da80ca80-a4b9-11ea-9179-92be4a259595.png)

**Comment by Cloud7050** [comment]
![image](https://user-images.githubusercontent.com/44526554/83572659-88dd4c00-a55c-11ea-8a9d-7a9c2865f0aa.png)
I see, perhaps it is a bug with the eslint vscode extension.
