### ISSUE TITLE
rules in eslint-recommended.js is not working in extends

### ISSUE THREAD

**Issue by memao** [typescript-eslint/typescript-eslint#2171]
**Repro**

1. We have a typescript project with lots of existing lint issues. I used the following configuration in .eslintrc.json, with no other rules added in rule section. 
  
` "extends": [
         "eslint:recommended",
         "plugin:@typescript-eslint/eslint-recommended"
    ],`

2. In order to figure out how many errors each rule has, I pasted all rules in "eslint:recommended" (https://github.com/eslint/eslint/blob/master/conf/eslint-recommended.js) in the rule section. Also, I pasted all rules in "plugin:@typescript-eslint/eslint-recommended" (https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.ts) in overrides section. 

3. I found the number of errors in step 1 and step 2 are different. Specifically, if I use recommended settings in step 1, I got 23854 errors. If I copy all rules as I did in step 2, I got more errors than that.

4. Then I commented out all rules in step 2 and enable them one by one, just to figure out which rule wasn't run in step 1. I found that the below 4 rules in "plugin:@typescript-eslint/eslint-recommended"  were not run
`"no-var": "error", // ts transpiles let/const to var, so no need for vars any more`
`"prefer-const": "error", // ts provides better types with const`
`"prefer-rest-params": "error", // ts provides better types with rest args over arguments`
`"prefer-spread": "error", // ts transpiles spread to apply, so no need for manual apply`
          
I am wondering what did I miss? is this a known issue?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.23.0` |
| `@typescript-eslint/parser`        | `2.23.0` |

**Comment by bradzacher** [comment]
Need more information - could you provide the actual configs you were using?

**Comment by memao** [comment]
For step 1, I am using this config
`{
    "env": {
        "browser": true,
        "es6": true,
        "node": true
    },
    "extends": [
         "eslint:recommended",
         "plugin:@typescript-eslint/eslint-recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 6,
        "sourceType": "module"
    },
    "plugins": [
        "@typescript-eslint",
        "header",
        "msnews-experiences-rules"
    ],
    "ignorePatterns": [
        "node_modules/",
        "dist/",
        "rules/",
        "docs/",
        "*.config.js",
        "*.config.*.js",
        "setPolicies.js"
    ],
    "rules": {
        "no-unused-vars": "off",
        "@typescript-eslint/no-unused-vars": "error"
    },
    "noInlineConfig": true,
    "settings": {}
}`

For step 2, I am using this config
`{
    "env": {
        "browser": true,
        "es6": true,
        "node": true
    },
    "extends": [
     
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 6,
        "sourceType": "module"
    },
    "plugins": [
        "@typescript-eslint",
        "header",
        "msnews-experiences-rules"
    ],
    "ignorePatterns": [
        "node_modules/",
        "dist/",
        "rules/",
        "docs/",
        "*.config.js",
        "*.config.*.js",
        "setPolicies.js"
    ],
    "rules": {
         "constructor-super": "error",
         "for-direction": "error",
         "getter-return": "error",
         "no-async-promise-executor": "error",
         "no-case-declarations": "error",
         "no-class-assign": "error",
         "no-compare-neg-zero": "error",
         "no-cond-assign": "error",
         "no-const-assign": "error",
         "no-constant-condition": "error",
         "no-control-regex": "error",
         "no-debugger": "error",
         "no-delete-var": "error",
         "no-dupe-args": "error",
         "no-dupe-class-members": "error",
         "no-dupe-else-if": "error",
         "no-dupe-keys": "error",
         "no-duplicate-case": "error",
         "no-empty": "error",
         "no-empty-character-class": "error",
        "no-empty-pattern": "error",
         "no-ex-assign": "error",
         "no-extra-boolean-cast": "error",
         "no-extra-semi": "error",
         "no-fallthrough": "error",
         "no-func-assign": "error",
         "no-global-assign": "error",
         "no-import-assign": "error",
         "no-inner-declarations": "error",
         "no-invalid-regexp": "error",
         "no-irregular-whitespace": "error",
         "no-misleading-character-class": "error",
         "no-mixed-spaces-and-tabs": "error",
         "no-new-symbol": "error",
         "no-obj-calls": "error",
         "no-octal": "error",
        "no-prototype-builtins": "error",
         "no-redeclare": "error",
         "no-regex-spaces": "error",
         "no-self-assign": "error",
         "no-setter-return": "error",
        "no-shadow-restricted-names": "error",
        "no-sparse-arrays": "error",
         "no-this-before-super": "error",
         "no-undef": "error",
         "no-unexpected-multiline": "error",
        "no-unreachable": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "error",
        "no-unused-labels": "error",
        "no-unused-vars": "off",
        "@typescript-eslint/no-unused-vars": "error",
        "no-useless-catch": "error",
       "no-useless-escape": "error",
        "no-with": "off",
        "require-yield": "off",
        "use-isnan": "off",
        "valid-typeof": "off"
    },
     "overrides": [
        {
            "files": ["*.ts", "*.tsx"],
            "rules": {
               "constructor-super": "off", // ts(2335) & ts(2377)
               "getter-return": "off", // ts(2378)
               "no-const-assign": "off", // ts(2588)
               "no-dupe-args": "off", // ts(2300)
               "no-dupe-class-members": "off", // ts(2393) & ts(2300)
               "no-dupe-keys": "off", // ts(1117)
               "no-func-assign": "off", // ts(2539)
               "no-import-assign": "off", // ts(2539) & ts(2540)
               "no-new-symbol": "off", // ts(2588)
               "no-obj-calls": "off", // ts(2349)
               "no-redeclare": "off", // ts(2451)
               "no-setter-return": "off", // ts(2408)
               "no-this-before-super": "off", // ts(2376)
                "no-undef": "off", // ts(2304)
               "no-unreachable": "off", // ts(7027)
               "no-unsafe-negation": "off", // ts(2365) & ts(2360) & ts(2358)
               "no-var": "error", // ts transpiles let/const to var, so no need for vars any more
               "prefer-const": "error", // ts provides better types with const
               "prefer-rest-params": "error", // ts provides better types with rest args over arguments
              "prefer-spread": "error", // ts transpiles spread to apply, so no need for manual apply
               "valid-typeof": "off" // ts(2367)
            }
        }
    ],
    "noInlineConfig": true,
    "settings": {}
}`

**Comment by bradzacher** [comment]
I don't see anything that looks out of the ordinary based on an eyeball of those configs.

One good way to debug this further is via the [`--print-config`](https://eslint.org/docs/user-guide/command-line-interface#print-config) CLI flag.

This flag will resolve the config for a given file and dump it to the console. This will help you figure out exactly the config that ESLint is using to lint a given file.

**Comment by memao** [comment]
Thank you for pointing out this CLI flag. This is very useful since I can figure out which rules get run for a specific file. Now I can give a specific example of the issue I see. 

My configuration is 
```
{
    "env": {
        "browser": true,
        "es6": true,
        "node": true
    },
    "extends": [
         "eslint:recommended",
         "plugin:@typescript-eslint/eslint-recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 6,
        "sourceType": "module"
    },
    "plugins": [
        "@typescript-eslint",
        "header",
        "msnews-experiences-rules"
    ],
    "ignorePatterns": [
        "node_modules/",
        "dist/",
        "rules/",
        "docs/",
        "*.config.js",
        "*.config.*.js",
        "setPolicies.js"
    ],
    "rules": {
        "no-unused-vars": "off",
        "@typescript-eslint/no-unused-vars": "error"
    },
    "noInlineConfig": true,
    "settings": {}
}
```
From my understanding, the above config means a combination of two recommended rule sets from ESLint and Typescript-ESLint, https://github.com/eslint/eslint/blob/master/conf/eslint-recommended.js and https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/eslint-recommended.ts. 

After I use --print-config to check config, I found this:  Rule "prefer-spread" is set as "error" in https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/eslint-recommended.ts. But this rule is actually not run for any *.ts or *.tsx files in my project. Same as the following 3 rules
       ` 'no-var': 'error', // ts transpiles let/const to var, so no need for vars any more`
       ` 'prefer-const': 'error', // ts provides better types with const`
       ` 'prefer-rest-params': 'error', // ts provides better types with rest args over arguments`

Also, "constructor-super" is set as "off" in https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/eslint-recommended.ts for all .ts and .tsx files. But it still gets run for all .ts and .tsx files in my project. There are several other rules like this.

Is this an expected behavior? Or is there anything else going on beside combination of two recommended rule sets?

**Comment by bradzacher** [comment]
Looking at your OP, you're on `2.23.0`, which is rather old. You're viewing the configs in master, which is for our latest release. This is why there's a mismatch.

If you want to view the configs as they were for your version, we tag every release, so you can use the GH tag explorer to view the source for that release:
https://github.com/typescript-eslint/typescript-eslint/blob/v2.23.0/packages/eslint-plugin/src/configs/eslint-recommended.ts
