### ISSUE TITLE
[naming-convention] put identifiers in quotes in error messages

### ISSUE THREAD

**Issue by kaiyoma** [typescript-eslint/typescript-eslint#2178]
Here's an example of an error message I'm getting from eslint:

```
16:11  error  Property name AccessLeaf: HQ_IDF1 must match one of the following formats: camelCase, PascalCase, UPPER_CASE  @typescript-eslint/naming-convention
```

It would be clearer if `AccessLeaf: HQ_IDF1` (the offending property name here) was in quotes, because otherwise it looks like two separate tokens in the sentence.

Suggested:

```
16:11  error  Property name "AccessLeaf: HQ_IDF1" must match one of the following formats: camelCase, PascalCase, UPPER_CASE  @typescript-eslint/naming-convention
```

**Comment by bradzacher** [comment]
happy to accept a PR, shouldn't be too difficult to do.

**Comment by segeda** [comment]
I will try make PR, but:
Sometime is used "Something '{{name}}' format" https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts#L26

**Comment by bradzacher** [comment]
I would usually prefer backticks (`` ` ``) because in tools like vscode, the block for the error message is formatted with markdown, so it highlights the strict a bit nicer.

Note - this issue is specifically about the `naming-convention` rule.
