### ISSUE TITLE
Suggestion: create cli init script like `npx eslint --init`

### ISSUE THREAD

**Issue by Robbie-Cook** [typescript-eslint/typescript-eslint#2179]
**Repro**

Typing `npx @typescript-eslint/eslint-plugin --init` doesn't create a default eslint setup like `npx eslint --init` does.

**Expected Result**

* Creates .eslintrc.js file in the current dir
* Installs dev dependencies for typescript-eslint

**Actual Result**

Does nothing

**Additional Info**

See eslint's getting started guide for reference: https://eslint.org/docs/user-guide/getting-started

**Comment by Robbie-Cook** [comment]
I would be keen to do some code for this if this suggestion is something that is wanted

**Comment by bradzacher** [comment]
The eslint `--init` will do this themselves as part of their wizard:
![image](https://user-images.githubusercontent.com/7462525/83930079-b5ef5180-a74a-11ea-88e8-e78c43236ebd.png)

<details>
<summary>it generated this config</summary>

```js
module.exports = {
    "env": {
        "browser": true,
        "es6": true
    },
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 11,
        "sourceType": "module"
    },
    "plugins": [
        "@typescript-eslint"
    ],
    "rules": {
    }
};
```

</details>

What are the benefits of us providing our own CLI for this?
It's not common practice for plugins themselves to provide a CLI for initialisation (TBH I've never seen it done).

If you've installed our plugin, chances are you were following our docs, and have already installed all of the required peer dependencies (which is just our parser, and typescript), so there wouldn't be anything for the CLI to do.

**Comment by Robbie-Cook** [comment]
Hey,

Thanks @bradzacher, this is fine, it looks like it would be a better solution to do it they way you have described.

I think the benefit is in quickly whipping up a project with typescript-eslint set up, rather than having to copy the .eslintrc.js file in ourselves. This is like how `npx create-react-app --template typescript` quickly sets up a Ts repo. 

Am happy to close this. Thank you for your help!
