### ISSUE TITLE
Setting up a project using both JS and TS

### ISSUE THREAD

**Issue by Lectem** [typescript-eslint/typescript-eslint#2186]
I'm having issues configuring the linter on a project that has both .js and .ts source files.

**Repro**

I have a javascript file in a `bin` folder which is used to launch my typescript application which lies in `src`.

I wanted to lint both my src and bin folders, respectively using typescript and javascript parsers.
As mentioned by the FAQ I tried using ESLint overrides, but it seems this is incompatible with using the recommended rules?

```js
module.exports = {
  env: {
    es6: true,
    node: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: "tsconfig.json",
    sourceType: "module",
  },
  plugins: ["@typescript-eslint"],



  overrides: [
    {
      files: ["bin/*.js"],
      parser: "espree",
    }
  ]
};
```

I also tried without the overrides, but I got the following message:

```
bin/cli.js
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: bin\cli.js.
The file must be included in at least one of the projects provided
```

But since this is not a .ts file, I obviously can not put it in the `tsconfig`.

**Expected Result**

Easy way to configure a project with both js and ts files.

**Actual Result**

It seems typescript rules are kept even if you override the parser, I'm not sure how to prevent that.

**Additional Info**

```

Oops! Something went wrong! :(

ESLint: 7.1.0

Error: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting E:\progs\siliceum\calcite-ci-agent\bin\cli.js
    at Object.getParserServices (E:\progs\siliceum\calcite-ci-agent\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\getParserServices.js:16:15)
    at create (E:\progs\siliceum\calcite-ci-agent\node_modules\@typescript-eslint\eslint-plugin\dist\rules\await-thenable.js:42:37)
    at Object.create (E:\progs\siliceum\calcite-ci-agent\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\RuleCreator.js:13:24)
    at createRuleListeners (E:\progs\siliceum\calcite-ci-agent\node_modules\eslint\lib\linter\linter.js:758:21)
    at E:\progs\siliceum\calcite-ci-agent\node_modules\eslint\lib\linter\linter.js:928:31
    at Array.forEach (<anonymous>)
    at runRules (E:\progs\siliceum\calcite-ci-agent\node_modules\eslint\lib\linter\linter.js:873:34)
    at Linter._verifyWithoutProcessors (E:\progs\siliceum\calcite-ci-agent\node_modules\eslint\lib\linter\linter.js:1170:31)
    at Linter._verifyWithConfigArray (E:\progs\siliceum\calcite-ci-agent\node_modules\eslint\lib\linter\linter.js:1268:21)
    at Linter.verify (E:\progs\siliceum\calcite-ci-agent\node_modules\eslint\lib\linter\linter.js:1223:25)
npm ERR! code ELIFECYCLE`
``` 

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `3.1.0` |
| `TypeScript`                | `3.8.3` |
| `ESLint`                    | `7.1.0` |
| `node`                      | `12.16.3` |
| `npm`                       | `6.14.4` |

**Comment by bradzacher** [comment]
> It seems typescript rules are kept even if you override the parser, I'm not sure how to prevent that.

They are, because an override is not a brand new config - it inherits from the base config and _overrides_ it with whatever pieces you tell it to.

So by defining `overrides: [{files: ["bin/*.js"], parser: "espree"}]`, you've only overridden the parser, and all of the rules are turned on.

Please see our getting started guide: https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md#i-get-errors-telling-me-the-file-must-be-included-in-at-least-one-of-the-projects-provided

**Comment by Lectem** [comment]
> So by defining `overrides: [{files: ["bin/*.js"], parser: "espree"}]`, you've only overridden the parser, and all of the rules are turned on.

This is more or less what I understood, but can't figure a way to be able to use both a JS and TS linter. Using overrides the other way (ie, defaulting to js and then overriding with ts) yields other issues.

For example if I have a TS only eslint config, and move it all into overrides like this

```js
module.exports = {
  env: {
    es6: true,
    node: true,
  },
  overrides: [
    {
      files: ["src/*"],
      extends: [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
      ],
      parser: "@typescript-eslint/parser",
      parserOptions: {
        project: "tsconfig.json",
        sourceType: "module",
      },
      plugins: ["@typescript-eslint"],

      rules: {
        "semi": "error",
        "eqeqeq": ["error", "smart"],
        "curly": "error",
        "@typescript-eslint/no-explicit-any": "off",
        "@typescript-eslint/explicit-module-boundary-types": ["warn", { allowArgumentsExplicitlyTypedAsAny: true }],
      },
    }
  ]
};
```
while 

```js
module.exports = {
  env: {
    es6: true,
    node: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: "tsconfig.json",
    sourceType: "module",
  },
  plugins: ["@typescript-eslint"],

  rules: {
    "semi": "error",
    "eqeqeq": ["error", "smart"],
    "curly": "error",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/explicit-module-boundary-types": ["warn", { allowArgumentsExplicitlyTypedAsAny: true }],
  },
};
```
works.
(I'm getting a ton of errors such as ` 5:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'`).






> Please see our getting started guide: https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md#i-get-errors-telling-me-the-file-must-be-included-in-at-least-one-of-the-projects-provided

That's what I tried:

> 
> - If you do want to lint the file:
> 
>     - If you do not want to lint the file with type-aware linting:
>         - Use ESLint's overrides configuration to configure the file to not be parsed with type information.

But I do not see how one would use overrides here?
The [type-aware linting](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md) doc explains how to enable type aware linting, not how to suppress it.

**Comment by bradzacher** [comment]
solutions; invert your config
right now you're turning on type-aware linting by default and then attempting to turn it off for a single file. It's much easier to instead invert the config, so that it the overrides turns ***on*** type aware linting for TS files.

My advice is to follow the `tsconfig.eslint.json` suggestion in the docs to just enable you to use type-aware linting on files. Much, much easier.

**Comment by Lectem** [comment]
That's what I attempted (shown in the previous comment) but it failed because I used `["src/*"]` as value for `files`, which does not work recursively. Replacing to `["*.ts", "*.tsx"]` fixed the issue.
