### ISSUE TITLE
Incosistent AST for typeArgument and typeParameters

### ISSUE THREAD

**Issue by armano2** [typescript-eslint/typescript-eslint#220]
While doing #219 i notice that we have small inconsistency in AST, sometimes we are outputting `TSTypeParameterDeclaration` and `TSTypeParameterInstantiation`  without nodes and sometimes we are omitting this node completely.

https://github.com/typescript-eslint/typescript-eslint/blob/690bff322adbebe181b3efb33c46408e2b819b9d/packages/typescript-estree/src/convert.ts#L1364-L1368

https://github.com/typescript-eslint/typescript-eslint/blob/690bff322adbebe181b3efb33c46408e2b819b9d/packages/typescript-estree/src/convert.ts#L1643-L1647

https://github.com/typescript-eslint/typescript-eslint/blob/690bff322adbebe181b3efb33c46408e2b819b9d/packages/typescript-estree/src/convert.ts#L693-L697

https://github.com/typescript-eslint/typescript-eslint/blob/690bff322adbebe181b3efb33c46408e2b819b9d/packages/typescript-estree/src/convert.ts#L2093-L2097

we should align it, but i'm unsure if we should always have it or not

additionally we should handle #146 in update for it

**Comment by bradzacher** [comment]
We should document our property names so it's clear what each one means and when it should be put on a node

I.e.
- `typeArgument` = generic usage
- `typeParameter` = generic definition
- `typeAnnotation` = type on a node
- ....
