### ISSUE TITLE
Rule to specify class members in constructor or not

### ISSUE THREAD

**Issue by hornta** [typescript-eslint/typescript-eslint#2212]
I've looked through all rules but I couldn't find one that matched.
I want a rule that can warn me whenever I use the private/protected/public keyword along in my constructor signature. I would like the members access modifier to always be specified on the class level.

```ts
// Not OK
class Foo {
  constructor(private bar: number) {}
}
``` 

```ts
// OK
class Foo {
  private bar: number;
  constructor(bar: number) {}
}
```

**Comment by bradzacher** [comment]
We have [`no-parameter-properties`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-parameter-properties.md) but nobody has cared enough to do do an inverse of the rule.
