### ISSUE TITLE
Expose local typescript API

### ISSUE THREAD

**Issue by hediet** [typescript-eslint/typescript-eslint#2221]
## Context
I'm implementing a custom eslint rule that uses typescript type information.

It is very crucial that my eslint rule uses the same typescript API as the eslint code that created the node returned by `context.parserServices.esTreeNodeToTSNodeMap(node)`.

I'm using `yarn link` to link my rule to the project where the rule is used (this helps me developing the rule a lot).
However, now this happens:

## Problem
`require("typescript")` in the target project resolves to typescript 3.7.5, but `require("typescript")` in my rule project resolves to typescript 3.9.5.
`ts.isCallExpression(node)` does not work anymore since the node.kind ids changed (in ts 3.7, `SyntaxKind.CallExpression is I think 165, in 3.9. 166).

## Suggested Solution
Expose the typescript API in `context.parserServices.typescript: typeof import("typescript")`.

Then I could use `context.parserServices.typescript.isCallExpression(...)` over `ts.isCallExpression`.

**Comment by bradzacher** [comment]
Our projects only have a peer dependency on typescript. This means that they will use whatever version is installed locally. This is done on purpose to ensure that the type information is generated using the same version of TS that the user is using to build.

Note that TS doesn't follow semver, so a "minor" version bump can (and likely will) contain breaking changes. This means that using an older or newer version can be _very_ dangerous.

For example, [3.9 contained changes to how `Promise.all` resolved types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#improvements-in-inference-and-promiseall), if you're using 3.9 for your tool, but the user isn't, the type information returned  used by the rule could be different.

We develop this project against TS 3.9, but we support down to a minimum of TS3.3.1

This does mean there are certain APIs in newer versions that you cannot use. If you have a hard requirement to use a certain API, consider setting and documenting your own dependency requirement on TS.

**Comment by hediet** [comment]
Sorry for forgetting to answer!

> Our projects only have a peer dependency on typescript. This means that they will use whatever version is installed locally

This does not work with yarn workspaces though - "local" has weird meaning there.
If a project A is linked with yarn link into another project B and if A resolves a dependency, it will not consider any dependencies of B. This does not consider peerDependencies.

The problem I encountered, as described, (only) appears when working with yarn link.
