### ISSUE TITLE
Enforce readonly for static class fields

### ISSUE THREAD

**Issue by hornta** [typescript-eslint/typescript-eslint#2236]
This is a feature request.

I was looking for a rule that tells me if a static class field can be assigned as read only if it isn't assigned anywhere. Would is be possible to make such a rule?

**Comment by bradzacher** [comment]
It's possible, but not easy.
The type information will allow you to crawl every single file and look for usages of the field.
It will be a pretty slow rule because of the amount of processing it needs to do.

Happy to accept a PR.

**Comment by hornta** [comment]
Alright I see. Yes that requires some processing. What do you think about extending the ClassProperty with a prop called "canBeReadonly" that is set to true by the typescript eslint parser. Or perhaps a property "assignedFrom" which is a list of expressions where the class property is assigned? 
I'm quite new to Typescript so I may be stepping on thin ice now.

**Comment by bradzacher** [comment]
nope to both. the parser just has access to the same APIs and data you do in the rule.
so if it was done there, then every single lint run would get hit by it instead of just lint runs with the rule turned on.

The logic for this should live within its own rule.
