### ISSUE TITLE
[@typescript-eslint/naming-convention] Migration guide for deprecated rules

### ISSUE THREAD

**Issue by rbuckton** [typescript-eslint/typescript-eslint#2251]
In [3.0.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0) a number of rules were deprecated in favor of `naming-convention`, however the configuration for `naming-convention` is fairly different from that of the rules it subsumed. Migrating from the old rules to `naming-convention` is less than straightforward and the documentation for the old rules is not helpful:

> ![image](https://user-images.githubusercontent.com/3902892/85613795-187f9300-b60f-11ea-87ab-94cd417264d2.png)

It would be extremely useful to provide information in these older docs on how to migrate from usages of these old rules to the `naming-convention` rule.

**Comment by bradzacher** [comment]
Have you checked out the docs for `naming-convention` - the end of the doc contains an examples section which covers a few of the cases such as:
- Enforce that type parameters (generics) are prefixed with T,
- Enforce that interface names do not begin with an I, and
- Enforce the codebase follows ESLint's camelcase conventions

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#examples

**Comment by rbuckton** [comment]
I did see these, but it would be helpful to at least link to them from the deprecated docs.

**Comment by bradzacher** [comment]
`camelcase` is the only rule doc that I left behind when I deleted the rules in an attempt to "stave off" issues from people clicking into a docs to find a replacement for the base `camelcase` rule.

Happy to accept a PR to add a link directly to the mentioned example
