### ISSUE TITLE
[explicit-module-boundary-types] Add fixer for missing return type

### ISSUE THREAD

**Issue by ChaosinaCan** [typescript-eslint/typescript-eslint#2257]
When turning on `explicit-module-boundary-types` in a codebase where it wasn't used before, there are a huge number of "missing return type on function" warnings to fix. When using the eslint extension with VS Code, the only suggested fixes are to disable the rule for the line or file. It would be much more convenient if eslint could automatically infer the return type from the code and insert it for me.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/explicit-module-boundary-types": ["warn"]
  }
}
```

```TS
export function foo() {
    return 42;
}
```

**Expected Result**

Suggestions for fixing include rewriting to

```TS
export function foo(): number {
    return 42;
}
```

**Actual Result**

No fixes are suggested.

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `3.4.0` |
| `@typescript-eslint/parser`        | `3.4.0` |
| `TypeScript`                       | `3.9.5` |
| `ESLint`                           | `7.3.0` |
| `node`                             | `12.17.0` |
| `npm`                              | `6.14.5` |

**Comment by bradzacher** [comment]
We will not add a fixer.
See previous discussion - #59
