### ISSUE TITLE
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json': Cannot find module 'typescript'

### ISSUE THREAD

**Issue by nspeedzy** [typescript-eslint/typescript-eslint#2259]
I am creating an add-to-cart app in vuejs. I am using the typescript language in vuejs but the `babel-eslint` parser keeps giving me `unexpected token :` errors while i declare a variable with a type in typescript. So i switched to the typescript parser. I have installed it as a dev dependency for my project. But when i use the parser in the `.eslintrc.json` file, I don't get any errors. But when i compile the project i get the `failed to load parser` error. It also says that the module was not installed. Even though i have installed it. The code for my files are below 

**Repro**

#### `.eslintrc.json`
```JSON
{
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 6
    },
    "extends": [
        "plugin:vue/recommended"
    ],
    "rules": {
        "no-unused-vars": "warn",
        "vue/html-indent": "off"
    }
}
```
#### `package.json`
```json
{
  "name": "vuejs_app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@typescript-eslint/parser": "^3.4.0",
    "@vue/cli-plugin-babel": "~4.4.0",
    "@vue/cli-plugin-eslint": "~4.4.0",
    "@vue/cli-service": "~4.4.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {
      "no-unused-vars": "warn"
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```

**Expected Result**
The typescript eslint parser should have been installed properly

**Actual Result**
I get the `Failed to load parser` error because the module was not found. Here is the full error log:

**Additional Info**
I use vuejs version `2.6.11` and @vue/cli version `4.4.5`. And here is the error code thrown:
```log
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json': Cannot find module 'typescript'
Require stack:
- C:\Surya\projects\nodejs_apps\vuejs_app\node_modules\@typescript-eslint\typescript-estree\dist\parser.js
- C:\Surya\projects\nodejs_apps\vuejs_app\node_modules\@typescript-eslint\typescript-estree\dist\index.js
- C:\Surya\projects\nodejs_apps\vuejs_app\node_modules\@typescript-eslint\parser\dist\parser.js
- C:\Surya\projects\nodejs_apps\vuejs_app\node_modules\@typescript-eslint\parser\dist\index.js
- C:\Surya\projects\nodejs_apps\vuejs_app\node_modules\eslint\lib\cli-engine\config-array-factory.js
- C:\Surya\projects\nodejs_apps\vuejs_app\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js
- C:\Surya\projects\nodejs_apps\vuejs_app\node_modules\eslint\lib\cli-engine\cli-engine.js
- C:\Surya\projects\nodejs_apps\vuejs_app\node_modules\eslint\lib\cli-engine\index.js
- C:\Surya\projects\nodejs_apps\vuejs_app\node_modules\eslint\lib\api.js
- C:\Surya\projects\nodejs_apps\vuejs_app\package.json
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json': Cannot find module 'typescript'
```
I have checked [this](https://github.com/eslint/eslint/issues/13169) issue also, but it didn't help.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `3.4.0` |
| `TypeScript`                | `3.9.2` |
| `ESLint`                    | `6.7.2` |
| `node`                      | `13.8.0` |
| `npm`                       | `6.13.6` |

**Comment by yeonjuan** [comment]
@nspeedzy 
Hi:) Are you using `.eslintrc.json` , `package.json` on the same path?
If then the two separate configs will not be merged, eslint will use `.eslintrc.json` only.
And have you check whether `typescript` installed also?

**Comment by nspeedzy** [comment]
@yeonjuan I do have typescript installed. And yes, The `package.json` and the `.eslintrc.json` are on the same path

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#typescript-should-be-installed-locally

Typescript must be installed locally.

**Comment by nspeedzy** [comment]
Thanks! @bradzacher

**Comment by nspeedzy** [comment]
Hey guys! It says `tsc is not a recognized command or batch file`. How am i supposed to solve this issue?
