### ISSUE TITLE
Node 11.x unsupported?

### ISSUE THREAD

**Issue by drewlustro** [typescript-eslint/typescript-eslint#2264]
👋 Hello there.

I see that #1997 dropped support for node 8.

- node `10.x`: supported
- node `11.x`: unsupported :x:
- node `12.x`: supported

Why is node 11 unsupported? Is it particularly less stable, or is it because `11.x` is not an LTS release?

**Comment by bradzacher** [comment]
<p><img src="https://raw.githubusercontent.com/nodejs/Release/77fe085297e8d823f2475653e9eb2e9b2b2ffc3a/schedule.svg?sanitize=true" alt="LTS Schedule"/></p>

The odd-numbered versions are of a more ephemeral nature.
Node 8 ended its maintenance period Dec 31st 2019
In comparison, Node 11 ended its maintenance period April 22nd 2019.

You should avoid relying on odd-numbered versions for long, and should instead use the even numbered versions.

You can read more on node's release page: https://github.com/nodejs/Release/

**Comment by drewlustro** [comment]
Thanks for the guidance!
