### ISSUE TITLE
Rule Proposal 'prefer-enum-initializers'

### ISSUE THREAD

**Issue by kaisermann** [typescript-eslint/typescript-eslint#2268]
**Proposal**

```jsonc
{
  "rules": {
    "@typescript-eslint/prefer-enum-initializers ": ["off"]
  }
}
```

**Proposal Result**

![image](https://user-images.githubusercontent.com/12702016/86381151-5e69d600-bc63-11ea-9e80-3d00f55041a8.png)

The name and message are just an example.

**Actual Result**

n/a
![image](https://user-images.githubusercontent.com/12702016/86382007-0384ae80-bc64-11ea-8b18-d694616aa717.png)

**Additional Info**

Enum infers sequential numbers automatically when initializers are omitted:

```ts
enum Status {
  Open, // infer 0
  Closed, // infer 1
}

declare const updateStatus: (value: Status) => void

updateStatus(0) // same as updateStatus(Status.Open)
```

With this approach, if new values are declared without following the existing order and the value of the enum has been saved in an external source, we will have inconsistencies between the saved value and the new representation, example:

```ts
enum Status {
  Idle, // new value
  Open,
  Closed,
}

type Resource = { status: Status }

const resource = findResource(id) // previous have { status: Status.Open }

resource.status === Idle // returns true
```

And removing an option from the enum is not possible, unless it is the last option in the enum, otherwise the order will break as well.

For the my current company's eslint-preset we've implemented a simple version of this rule [here](https://github.com/vtex/typescript/blob/refactor%2Fenum-rule/packages/eslint-plugin-vtex/docs/rules/prefer-enum-initializers.md). As dealing with `enum`s in `typescript` can have its trade-offs, I'd like to know if this would be useful to others.

Oh and thanks for the great work with all these packages! They are being extremely useful and effective in guaranteeing the quality of our code 😁 🙌

**Comment by tiagonapoli** [comment]
I think this would be a great addition: this enum behavior subtlety can be source of bugs difficult to track
