### ISSUE TITLE
[strict-comparison] Can we merge this rule?

### ISSUE THREAD

**Issue by PachowStudios** [typescript-eslint/typescript-eslint#2269]
PR https://github.com/typescript-eslint/typescript-eslint/pull/314 was never merged for the strict-comparisons rule.

I really need this rule for warning against comparing dates with `===`. Can we re-open that PR and get it merged? I'm willing to help out if it needs to be updated.

**Comment by bradzacher** [comment]
No.

That PR was closed as the contributor was unable to finish it and stopped responding.
The branch is now over a year out of date, so it won't be merged in that state.

If you want to take their work and see it through to completion - then feel free.

**Comment by PachowStudios** [comment]
I'll try to make a PR next week. Thanks
