### ISSUE TITLE
Rule Proposal/Discussion: 'static-this'

### ISSUE THREAD

**Issue by TheAkio** [typescript-eslint/typescript-eslint#2271]
I was checking the [roadmap](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md) a few times and found the TSLint rule [`static-this`](https://palantir.github.io/tslint/rules/static-this/) still unimplemented and didn't find an issue regarding that rule.

I was wondering whether there is something else that's blocking people from creating this rule, or whether until now nobody really noticed. It might also be a rule that should not be in `@typescript-eslint/eslint-plugin` but rather in `eslint` itself, because it uses no features of the TypeScript AST (at least in the way I implemented it).

I could make a PR with my solution but I wanted to start a discussion first because of the mentioned things.

### Rule details
The rule I made works as follows:

```ts
class MyStaticClass {
    private name = 'Name';
    private static staticName = 'StaticName';

    getName() {
        return this.name; // Ok, because it's not a static method
    }

    static getStaticName() {
        return MyStaticClass.staticName; // Ok, because it references the class and doesn't use "this"
    }

    static getStaticName2() {
        return this.staticName; // Not ok, rule suggests fix to replace "this" with "MyStaticClass"
    }

    static getStaticNameWithConflict() {
        const MyStaticClass = null;
        return this.staticName; // Not ok, but the rule doesn't suggest an auto fix because of the naming conflict
    }

    static getSomeFunctions() {
        const arrowFn = () => {
            return this.staticName; // Eventually ok? This would probably be a case where it can be configured
        }

        function functionDecl() {
            return this.staticName; // Ok, because we don't know what "this" is (eventually also something to be configured)
        }
      
        const functionExpr = function() {
            return this.staticName; // Also ok, because we don't know what "this" is (eventually also something to be configured)
        };
      
        return { arrowFn, functionDecl, functionExpr };
    }
}
```

If I remember correctly, the TSLint rule `static-this` marked a `this` inside function expressions and declarations made inside a static method too, which is wrong in my opinion but could be something to be configured.

### Implementation Details
The way my implementation works is by getting all `ThisExpression`s of a file and first of all checking if the first `FunctionExpression` found is inside a `MethodDeclaration` (if there is none it also doesn't mark anything). After that it checks each scope upwards for things named identically to the class and if it finds something it won't suggest an autofix.

I am not 100% sure whether I dealt with every case and maybe there is also a better/more performant way of doing this.
Also I'm pretty new to developing ESLint rules and I don't really have any knowledge about writing TypeScript-ESLint rules.

**Comment by bradzacher** [comment]
> I was wondering whether there is something else that's blocking people from creating this rule, or whether until now nobody really noticed

Nobody noticed or cared really. The rule probs not really used.

Why do you want to not use the static `this`?
IMO a static `this` is straight up better than referencing via class name because it respects subchildren's overrides:

```ts
class A {
    static foo() { console.log('a') }
    static bar() { A.foo(); }
    static baz() { this.foo(); }
}
class B extends A {}
class C extends A{
    static foo() { console.log('c') }
}

console.log('B');
B.foo(); // > a
B.bar(); // > a
B.baz(); // > a

console.log('C');
C.foo(); // > c 
C.bar(); // > a - doesn't respect the subclass override
C.baz(); // > c - respects the subclass override
```
[repl](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8CwAoa7oQC5iwS2GgDMB7EgCgEpFpgSA7CEkAUwDoQSBzcgcjF7UAvqgyYc+QgCMwAJyo1YbUhUoBuaCLQZsuAtBkAvBQmhYAFngjKyVDVq2hIMAELQWADywt6AExjwCFqodIzM7Jw8vC6CaqguNqpxKAky8urxbEZ2qCHgUNAAwu5ePv5wyNroupLEttSmoUysHNx8wIKaqMEoTeGtUYWxqIWJOSijaeOTYMYZKEA)

**Comment by TheAkio** [comment]
> IMO a static this is straight up better than referencing via class name because it respects subchildren's overrides

That's a good point. I've personally never used static method overriding and completetely overlooked it here.

> Why do you want to not use the static this?

From the TSLint rule `static-this`:
```
Static this usage can be confusing for newcomers. It can also become imprecise when used with extended classes when a static this of a parent class no longer specifically refers to the parent class.
```

For me the first part is really what matters. You could argue that those people can just learn it, but if you work with multiple languages at the same time, only rarely with JS/TS and it just has `this` in static methods everywhere it might be confusing.
The second point is interesting too, as I said, I don't use static overriding and you might just want to straight out prevent this from happening.

In any way, the rule was inside TSLint and there was nothing I could find that pointed to a replacement or implementation. If now you decide the rule probably wasn't a good idea, then it could probably just be a plugin so people still have a replacement if they want to.

**Comment by bradzacher** [comment]
Note that there's not really a need to have a specific rule for this, you can get 99% of the way there with [`no-restricted-syntax`](https://eslint.org/docs/rules/no-restricted-syntax)

```json
{
  "no-restricted-syntax": ["error", {
    "selector": "MethodDefinition ThisExpression",
    "message": "whatever error"
  }]
}
```

**Comment by TheAkio** [comment]
> Note that there's not really a need to have a specific rule for this, you can get 99% of the way there with no-restricted-syntax

That sounds great for people who want the functionality of the original TSLint `static-this` rule. It might be good to add this to the roadmap and just tell people to use `no-restricted-syntax` when they want the `static-this` rule.

> then it could probably just be a plugin so people still have a replacement if they want to
>
> I disagree. Adding a rule into this codebase just so a small handful of people can use it is not worth the maintenance overhead.
> If a rule is being added, I would like to see enough people interested in it.

Isn't that the reason why it should be a plugin? If it's only used by a handful of people.

In any case, the main reason I started this discussion was because there was nothing mentioned and now that I (and other people who might search for this) have a place to start looking for information regarding this rule, it should be fine.

**Comment by bradzacher** [comment]
We have this documented in a way here:
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#how-can-i-ban-specific-language-feature
