### ISSUE TITLE
resolve "references" in tsconfig.json

### ISSUE THREAD

**Issue by ooyyloo** [typescript-eslint/typescript-eslint#2272]
I have a package "B" written in TS, which references package "A". When the package "B" references the variable from package "A", VSCode displays the right variable type, but the variable type got from "ParserServices" imported from @typescript-eslint/experimental-utils is always "any". It seems that typescript-eslint does not resolve the packages in "references" in tsconfig.json.
What I want is, when I'm writting code in package "B", I can use "parserServices.program.getTypeChecker().getTypeAtLocation(xxx)" to get the right type of the variable defined in package "A", rather than the "any" type.

```JSON
// tsconfig.json of package "B"
{
  ...,
  "references": [{ "path": "../A" }]
}

```

```JSON
// eslint config for package "A" and package "B"
{
  ...,
  parserOptions: {
    project: ["./A/tsconfig.json", "./B/tsconfig.json"],
    tsconfigRootDir: __dirname,
  },
}
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.34.0` |
| `TypeScript`                | `3.9.5` |
| `ESLint`                    | `7.2.0` |
| `node`                      | `12.13.1` |
| `npm`                       | `6.12.1` |

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/2094
