### ISSUE TITLE
turn off rules by shortname

### ISSUE THREAD

**Issue by nebulousdog** [typescript-eslint/typescript-eslint#2273]
is there a way to turn off rules by using the shortname? I'm using the eslint plugins for typechecking in Javascript, but am not seeing any location to turn these off in either the tsconfig, nor the eslintrc config.

Example `2339` shortname found in https://github.com/microsoft/TypeScript/blob/v3.6.3/src/compiler/diagnosticMessages.json#L1199-L1202.

Similar issue in Typescript repo https://github.com/microsoft/TypeScript/issues/29950.

**Comment by bradzacher** [comment]
Our tooling is unrelated to typescript errors.

Have a look at the docs for information on configuring eslint.
https://eslint.org/docs/user-guide/configuring

**Comment by nebulousdog** [comment]
thanks @bradzacher.
