### ISSUE TITLE
Remove lodash?

### ISSUE THREAD

**Issue by danielnixon** [typescript-eslint/typescript-eslint#2279]
Lodash has an [open security vuln](https://github.com/lodash/lodash/issues/4738) and shows [signs of being borderline unmaintained](https://twitter.com/jdalton/status/1272230153200885762).

**Repro**

1. Install typescript-eslint/eslint-plugin
2. Check your Snyk report (e.g. https://snyk.io/test/github/danielnixon/eslint-plugin-total-functions?targetFile=package.json)
3. Or run yarn audit / npm audit

**Expected Result**

No security vuln reported

**Actual Result**

Lodash security vuln reported

**Additional Info**

It looks like typescript-estree only uses lodash once, for `unescape`. `unescape` happens to be tiny and unlikely to evolve over time: https://github.com/lodash/lodash/blob/4.17.11/lodash.js#L15145

I'd be happy to raise a PR to inline `unescape` (or maybe replace it with https://www.npmjs.com/package/he or something) and remove the lodash dependency.

**Versions**

Latest

**Comment by bradzacher** [comment]
Sure - happy to remove it if you want.
TBH I'm not even sure if this is required - I don't know what this check even does:

https://github.com/typescript-eslint/typescript-eslint/blob/682eb7e009c3f22a542882dfd3602196a60d2a1e/packages/typescript-estree/src/convert.ts#L1917-L1919

Maybe we don't even need to inline it and can just delete it altogether? Unsure.
Worth having a play around with - happy to accept a PR!

**Comment by dman777** [comment]
I second that request to remove lodash bloat

**Comment by papb** [comment]
I think 'borderline unmaintained' is very exaggerated. He is just looking for new maintainers to help.

**Comment by danielnixon** [comment]
>I think 'borderline unmaintained' is very exaggerated. 

Perhaps, but

* [Vuln reported Oct 11 2019](https://hackerone.com/reports/712065)
* [Publicly disclosed Apr 27/28 2020](https://github.com/lodash/lodash/issues/4738)
* [Fix published July 8 2020](https://github.com/lodash/lodash/wiki/Changelog#july-8-2020--diff--docs)

seems to me like an intolerable timeline whatever you call it.

See also https://github.com/lodash/lodash/issues/4738#issuecomment-629698149 which I tend to agree with.

**Comment by JoshuaKGoldberg** [comment]
@danielnixon still planning on sending a PR for this? I can if not!

**Comment by danielnixon** [comment]
Please go for it @JoshuaKGoldberg

**Comment by JoshuaKGoldberg** [comment]
Fun fact: typescript-eslint actually uses _two_ lodash members: `memoize` and `unescape`.  I thought about this more, and a few thoughts against removing lodash come to mind:

* IMO there's still benefit to the "lodash ideology" of using the same stable functions & high quality docs across projects. Why bother recreating those methods internally when they're already available & well-documented?
* Lodash is already a transitive dependency many times over in `yarn.lock`, so removing it from _direct_ usage does very little.

**Comment by danielnixon** [comment]
`memoize` is in `eslint-plugin-tslint` which will hopefully die off one day so I didn't consider it a priority for this ticket (just `typescript-estree` here).

Your other points are good. 👍 🤔

**Comment by dman777** [comment]
> IMO there's still benefit to the "lodash ideology" of using the same stable functions & high quality docs across projects. Why bother recreating those methods internally when they're already available & well-documented?

The same applies to native JS and more so because JS is on everything and anything JS while lodash is not.

**Comment by armano2** [comment]
i did some digging for this, and it seem that our code is not correct anyway for this -> not same as in espree 

espree: https://astexplorer.net/#/gist/7b10da67f480914a47bfc2fec65a1d78/ee2bf2018a765a3618ce2baedae2b2bb4644f3f2
tsestree: https://astexplorer.net/#/gist/c62bd8fa3ddef9f1d9ef86acc7e7badd/a49bc43db12e8ef5894e1cb6030e67c7ca2a1aaa

this behaviour should be present only in jsx context

**Comment by bradzacher** [comment]
In the next release, typescript-estree will no longer have a dependency on lodash, thanks to @armano2.

**Comment by bradzacher** [comment]
There is still memoize in `eslint-plugin-tslint`

And in the interim one usage has been introduced into `eslint-plugin` (iirc this was due to a util from eslint that was inlined)

https://github.com/typescript-eslint/typescript-eslint/blob/f606846af2617a0d8ee3ad5ce7c10864161ebf53/packages/eslint-plugin/src/util/astUtils.ts#L2
