### ISSUE TITLE
tslint parity: strict-string-expressions

### ISSUE THREAD

**Issue by leighman** [typescript-eslint/typescript-eslint#2283]
Please provide an equivalent rule. `no-implicit-conversion` doesn't seem to take advantage of type information.

**Comment by glen-84** [comment]
```ts
const bar = 5;

"foo" + bar;
`foo ${bar}`;
```

`Operands of '+' operation must either be both strings or both numbers. Consider using a template literal.`
([restrict-plus-operands](https://github.com/typescript-eslint/typescript-eslint/blob/742b679339e5a16be684ba8949af3c773bfe6c04/packages/eslint-plugin/docs/rules/restrict-plus-operands.md))
`Invalid type "5" of template literal expression.`
([restrict-template-expressions](https://github.com/typescript-eslint/typescript-eslint/blob/742b679339e5a16be684ba8949af3c773bfe6c04/packages/eslint-plugin/docs/rules/restrict-template-expressions.md))

Are these rules not sufficient?

**Comment by leighman** [comment]
Ah, awesome, thanks. Don't know how I missed that. Searched for `string` and `template` 😓
