### ISSUE TITLE
Azure test flakiness

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#229]
I don't know much about the azure build platform, but is there a way we can setup auto-rerunning of tests?
I see a lot of times that a test fails because yarn throws a 5xx response during install.

Is this something we'd have to script up manually?

**Comment by bradzacher** [comment]
cc @typescript-eslint/core-team

**Comment by j-f1** [comment]
Probably something that’d have to be done manually.

**Comment by StefanSchoof** [comment]
There is support for [Flaky test](https://docs.microsoft.com/en-us/azure/devops/release-notes/2017/dec-11-vsts#identify-flaky-tests) in Azure DevOps. But as far as I know only for Visual Studio Test Task. So this properly does not help.

**Comment by JamesHenry** [comment]
We now use github actions
