### ISSUE TITLE
[explicit-function-return-type] Auto-fixable simple cases?

### ISSUE THREAD

**Issue by Svish** [typescript-eslint/typescript-eslint#2301]
Would it be possible to make simple cases of `explicit-function-return-type` errors auto-fixable?

Take for example this example:

```ts
export function test() {
  return 'foobar';
}
```

Here, the return type is missing, but when I hover over this function in VS Code it correctly reports the return type to be `string`. 

![image](https://user-images.githubusercontent.com/142162/87670343-dbbb3d80-c76f-11ea-9dfa-a5ac88acde02.png)

Would be really great if `@typescript-eslint` could hook into the same information VS Code uses here somehow and auto-fix this error.

I don't mind if it doesn't fix _all_ cases. It could for example be limited to primitives, or cases not inferred as `any`, or something like that. Point would be to make it easier to add this rule to an existing code base. We have added it here, but has to leave it as `warn` rather than `error` because there are 566 cases of it. If a larger percentage of those could be fixed automatically, which I assume they probably could, that would make it much more feasible to manually fix the rest and turn the rule back to `error` level.

Is this something that could even be possible? Is this information available to the linter rules/fixers? If not, could it be?

---

I tried looking at [a couple of functions](https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVxsAZxgEYAKAQwC44UkBbAI2CgEo4BvAKDh7imBhIoucnAB8cYgAY4AfjgByBBAgNyUBXGrkA3JwC+nTqEiw4aHETyEYAJjgBeOBWq1GzNg4miJ0uYuVVdU1tHSA) in the TypeScript AST Viewer, and when selecting the `FunctionDeclaration` and the `ArrowFunction`, there does seem to be a `Type` section which looks interesting, but I don't know how available/usable that section is within linter rules/fixers. 🤔

**Comment by bradzacher** [comment]
See: https://github.com/typescript-eslint/typescript-eslint/issues/59#issuecomment-621942695
