### ISSUE TITLE
(PHP|WEB)Storm - ESLint: Parsing error "parserOptions.project" has been set for @typescript-eslint/parser

### ISSUE THREAD

**Issue by SirMishaa** [typescript-eslint/typescript-eslint#2303]
Hello, 

I created a new [NestJS project](https://docs.nestjs.com/) which is a very popular NodeJS framework. But I have this error (see title) on my IDE (PHPStorm 2020.2-Beta) and ESLint doesn't work at all. 

I've used the NestJS CLI : 
```
nest new nestjs-micro
```

I don't seem to be the only one with this problem, so it would be nice to find the cause of this problem and **fix it once and for all.** 

**Repro**

```js
// .eslintrc.js
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: 'tsconfig.json',
    sourceType: 'module',
  },
  plugins: ['@typescript-eslint/eslint-plugin'],
  extends: [
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
    'prettier',
    'prettier/@typescript-eslint',
  ],
  root: true,
  env: {
    node: true,
    jest: true,
  },
  rules: {
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
  },
};

```

```TS
// tsconfig.json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true
  }
}

```

**Expected Result**

**Actual Result**

**Additional Info**
![Screenshot_20200716_233543](https://user-images.githubusercontent.com/42717232/87725198-1d260a00-c7bd-11ea-9520-fd0d69fd7790.png)

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `3.0.2` |
| `TypeScript`                | `3.7.4` |
| `ESLint`                    | `7.1.0` |
| `node`                      | `14.3.0` |
| `yarn`                       | `1.22.4` |

**Comment by bradzacher** [comment]
Have you read through our getting started guide?
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md

and our FAQ?
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md

**Comment by SirMishaa** [comment]
I didn't make the setup. The CLI did it for me, like when you use vue-cli.

I should point out that this is an error that appears only from PHPStorm. 
(It's still a well-known IDE, so it's kind of annoying.)

**Comment by bradzacher** [comment]
> I didn't make the setup.

That doesn't mean it's not your responsibility to understand what's being setup and debug it.
Once it's been generated, it's your codebase to own and maintain.

If the config is wrong, then that's feedback you can provide to the tool that generated it once you've debugged and solved it.

Our docs should help you figure out what's happening and what needs to be done.
In particular, this FAQ answer:
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-get-errors-telling-me-the-file-must-be-included-in-at-least-one-of-the-projects-provided

**Comment by SirMishaa** [comment]
Yes, I understand, but I think it's a problem with the integration with (PHP|WEB)Storm rather than a configuration error.

That's why I was asking if someone could test to confirm the problem.

Anyway, whatever, thank you...

**Comment by bradzacher** [comment]
It's not an error with your IDE from what I can see.
Your IDE is saying that `.eslintrc.js` is not included in any tsconfigs provided to the parser.

This documentation here explains how to fix that.
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md#i-get-errors-telling-me-the-file-must-be-included-in-at-least-one-of-the-projects-provided

**Comment by SirMishaa** [comment]
Indeed, I have a tsconfig.build.json file that contains "exclude" to exclude files from unit tests.
I also tried to add the "exclude" line directly in the tsconfig.json file but it still doesn't work.

I'm not sure how to debug this, as the configuration seems to be correct.
```js
{
  "extends": "./tsconfig.json",
  "exclude": ["node_modules", "test", "dist", "**/*spec.ts"]
}
```

Am I doing something wrong?

**Comment by bradzacher** [comment]
Two things:

First - as per the doc I linked - if you don't want to lint a file using ESLint:

> - If you **do not** want to lint the file:
>   - Use [one of the options ESLint offers](https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories) to ignore files, like a `.eslintignore` file, or `ignorePatterns` config.

Your tsconfig does not dictate which files get linted.

Second - from your OP, your `.eslintrc.js` contains:
```
  parserOptions: {
    project: 'tsconfig.json',
    sourceType: 'module',
  },
```

So changes to your `tsconfig.build.json` file will not affect your lint run, as you are telling our tooling to use your `tsconfig.json` file.

**Comment by SirMishaa** [comment]
Concretely, I don't know if I should exclude some files (certainly not). I also don't know how eslint works internally.

On the other hand, I know how it works and it's a great tool. 

The weird thing is that the command ``eslint "{src,apps,libs,test}/**/*.ts" --fix`` works. I only got the error from (PHP|WEB)Storm.

So I'm sorry, I guess I'll have to try to figure it out myself but I can't find the origin of the error.

Thank you for your help & time.

**Comment by bradzacher** [comment]
> Your IDE is saying that .eslintrc.js is not included in any tsconfigs provided to the parser.

So `eslint "{src,apps,libs,test}/**/*.ts" --fix` will work fine because:
a) it does not include files in the root of your project
b) it does not include `.js` files.

But your IDE doesn't use a CLI argument to select only some files, it lints everything that hasn't been explicitly ignored using one of the aforementioned eslint mechanisms.

**Comment by SirMishaa** [comment]
Indeed, I don't have the error when I add ``.eslintrc.js`` to the .eslintignore file.

But unfortunately, this seems to have the effect of completely disabling ESLint in the sense that Phpstorm doesn't display any errors.

**Comment by SirMishaa** [comment]
Hmh, maybe this is wokring. Fix on save doesn't seem to work.
Idk.

Thank you for your help !
![Screenshot_20200717_005245](https://user-images.githubusercontent.com/42717232/87730369-d853a080-c7c7-11ea-9904-cff7ad01a2e4.png)

**Comment by bradzacher** [comment]
Do not use that option.
That option is a hack that was added when we released v2 to help people migrate.
That option is deprecated and will be removed in a future version.

**Comment by SirMishaa** [comment]
Hmm.. I see :/

I need to make eslint understand that it must linte the files in ``src`` by default ? To avoid this error

**Comment by bradzacher** [comment]
As previously mentioned and stated in the docs

https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md#i-get-errors-telling-me-the-file-must-be-included-in-at-least-one-of-the-projects-provided

> - If you **do not** want to lint the file:
>    - Use [one of the options ESLint offers](https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories) to ignore files, like a `.eslintignore` file, or `ignorePatterns` config.
>- If you **do** want to lint the file:
>    - If you **do not** want to lint the file with [type-aware linting](./TYPED_LINTING.md):
>        - Use [ESLint's `overrides` configuration](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) to configure the file to not be parsed with type information.
>    - If you **do** want to lint the file with [type-aware linting](./TYPED_LINTING.md):
>        - Check the `include` option of each of the tsconfigs that you provide to `parserOptions.project` - you must ensure that all files match an `include` glob, or else our tooling will not be able to find it.
>        - If your file shouldn't be a part of one of your existing tsconfigs (for example, it is a script/tool local to the repo), then consider creating a new tsconfig (we advise calling it `tsconfig.eslint.json`) in your project root which lists this file in its `include`. For an example of this, you can check out the configuration we use in this repo:
>          - [`tsconfig.eslint.json`](https://github.com/typescript-eslint/typescript-eslint/blob/master/tsconfig.eslint.json)
>          - [`.eslintrc.js`](https://github.com/typescript-eslint/typescript-eslint/blob/master/.eslintrc.js)
