### ISSUE TITLE
[no-void] has conflict with [no-floating-promise] 

### ISSUE THREAD

**Issue by zheeeng** [typescript-eslint/typescript-eslint#2321]
**Repro**

If I want to send an async task without waiting result, I have to use `void` to bypass rule [no-floating-promises], but it triggers another rule [no-void]

```JSON
{
  "rules": {
        "@typescript-eslint/no-floating-promises": "error",
        "no-void": "error"
  }
}

```

**Comment by bradzacher** [comment]
https://eslint.org/docs/rules/no-void#allowasstatement
