### ISSUE TITLE
[method-signature-style] Using `property` breaks overloading for declared/global/merged types

### ISSUE THREAD

**Issue by milesj** [typescript-eslint/typescript-eslint#2340]
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/method-signature-style": "error"
  }
}
```

I'm aware of this PR that fixed some overloading issues (https://github.com/typescript-eslint/typescript-eslint/pull/1966), but I went down another rabbit hole that took me a while to fix. When I upgraded eslint and enabled a bunch of rules, one of my projects type's completely broke.

I have this one implementation that declares a global to merge with some of Jest's types. I do this as I'm providing new Jest functionality.

```ts
declare global {
  namespace jest {
    interface Matchers<R, T> {
      toBeChecked(): R;
      toBeDisabled(): R;
      toBeElementType(type: ElementType): R;
      toBeNodeType(type: NodeType): R;
      toContainNode(node: NonNullable<React.ReactNode>): R;
      toHaveClassName(name: string): R;
      toHaveKey(value: string | number): R;
      toHaveProp<K extends keyof PropsOf<T>>(name: K, value?: PropsOf<T>[K]): R;
      toHaveProps(props: Partial<PropsOf<T>>): R;
      toHaveRendered(): R;
      toHaveValue(value: unknown): R;
    }
  }
}
```

I also provide more implementations in other packages, like so.

```ts
declare global {
  namespace jest {
    interface Matchers<R, T> {
      // Add overloads specific to the DOM
      toHaveProp<K extends keyof DomPropsOf<T>>(name: K, value?: DomPropsOf<T>[K]): R;
      toHaveProps(props: Partial<DomPropsOf<T>>): R;
    }
  }
}
```

This works, as TS is smart enough to inherit, merge, and provide overloads for all these methods (note that `toHaveProp` is declared in both examples). Once I enabled `method-signature-style`, I opted to use `property` since it's suggested when using strict. However, this style changed the above to:

```ts
declare global {
  namespace jest {
    interface Matchers<R, T> {
      // Add overloads specific to the DOM
      toHaveProp: <K extends keyof DomPropsOf<T>>(name: K, value?: DomPropsOf<T>[K]) => R;
      toHaveProps: (props: Partial<DomPropsOf<T>>) => R;
    }
  }
}
```

While this syntax isn't invalid on its own, it completely breaks the overloading within the `jest` namespace. I had to explicitly disable the `method-signature-style` rule for these instances.

**Expected Result**

Rule takes into account declars/globals/namespaces/merging, etc.

**Actual Result**

Overloads no longer existed, causing type errors across many call sites in the code base.

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `3.3.0` |
| `@typescript-eslint/parser`        | `3.3.0` |
| `TypeScript`                       | `3.9.5` |
| `ESLint`                           | `7.2.0` |
| `node`                             | `12.16` |
| `npm`                              | `6.14` |

**Comment by bradzacher** [comment]
A few solutions to this:
1) accept that this is an advanced case, so you need to be wary and intentionally disable the rule with a comment.
1) we can remove the fixer when the type is in an module declaration context like this
1) we can use type information to inspect the parent type and ignore the properties appropriately.
   - This is "the most correct", but it's a rather large breaking change that I don't necessarily want to put into the rule - it will involve using type information, which limits the usability of the rule.

unsure of the best appraoch. leaning towards the second one.
happy to accept a PR!

**Comment by milesj** [comment]
The 2nd sounds reasonable enough. Maybe also an option like `ignoreDeclares` that completely avoids linting/fixing these scenarios.

**Comment by aggmoulik** [comment]
Hy, I was working on this issue for the removal of fix.

I have created this function so that I can find the `TSModuleDeclaration` but I am getting `RangeError: Maximum call stack exceeded`. Can you help me in this ?

```typescript
function isNodeParentModuleDeclaration(node: TSESTree.Node): Boolean {
      if (node.parent?.type === AST_NODE_TYPES.TSModuleDeclaration) {
        return true;
      } else {
        if (node.parent?.type !== AST_NODE_TYPES.Program) {
          isNodeParentModuleDeclaration(node);
        }
        return false;
      }
    }
```

**Comment by bradzacher** [comment]
> isNodeParentModuleDeclaration(node);

You have an unconstrained recursive call.
Try `isNodeParentModuleDeclaration(node.parent);` instead
