### ISSUE TITLE
[prefer-includes] Should not auto fix simple Regex

### ISSUE THREAD

**Issue by banyudu** [typescript-eslint/typescript-eslint#2349]
**Repro**
```javascript
// original
const pattern = new RegExp("bar")
function f(a) {
  return pattern.test(a)
}
// after fix
function f(a) {
  return a.includes("bar")
}
// f({}) is false before fix, while throw exception after fix
```

```JSON
{
  "rules": {
    "@typescript-eslint/prefer-includes": "error"
  }
}
```

```TS
const pattern = new RegExp("bar")
function f(a) {
  return pattern.test(a)
}
console.log(f({}))
```

**Expected Result**
`false`

**Actual Result**
`TypeError: xxx.includes is not a function`

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `3.7.1` |
| `@typescript-eslint/parser`        | `3.7.1` |
| `TypeScript`                       | `3.9.7` |
| `ESLint`                           | `7.6.0` |
| `node`                             | `12.13.1` |
| `npm`                              | `6.14.5` |

**Comment by bradzacher** [comment]
This rule probably should just be restricted to `string` types.

**Comment by sudalqueen** [comment]
I'll try this!😊

**Comment by bradzacher** [comment]
@sudalqueen - awesome thanks!

To be clear: the bug here is not that it's running on a non-`string` type.
The bug here is that it's fixing without making sure the fix is correct.

Before reporting an error for `.test`, the rule should first ensure that the type has a `.includes` method on it, so that we can make sure the fix is safe.

**Comment by sudalqueen** [comment]
Thank you for the kind explanation😊

So to fix the bug, What I'm have to do is make this rule report and fix a error when the type has the `.includes` method, right?
I'll do my best!

**Comment by banyudu** [comment]
I think `!!a.includes?.("bar")` is good for regex replacement.

**Comment by sudalqueen** [comment]
I made PR! 😊
