### ISSUE TITLE
Error: Cannot read config file

### ISSUE THREAD

**Issue by msmey** [typescript-eslint/typescript-eslint#2355]
Hi guys, I just have setup my env on MacOS globally using "getting started" guide and I'm getting the following error: 

(node:11767) UnhandledPromiseRejectionWarning: Error: Cannot read config file: /usr/local/lib/node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended
Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended'

This file of course is there...

ls /usr/local/lib/node_modules/@typescript-eslint/eslint-plugin/dist/configs/
all.js                                     eslint-recommended.js.map
all.js.map                                 recommended-requiring-type-checking.js
base.js                                    recommended-requiring-type-checking.js.map
base.js.map                                recommended.js
eslint-recommended.js                      recommended.js.map

Can you please help?

Thanks and Regards!

**Comment by bradzacher** [comment]
Could you please provide some more information?

There were a bunch of sections in the issue template which you deleted, they would help here.

Please don't ignore the issue template. Its there for a reason.

Help me to help you.

**Comment by msmey** [comment]
### Sure - sorry about that - and thanks again!
**Repro**
npm install -g eslint eslint-config-airbnb-base eslint-plugin-import eslint-config-prettier
@typescript-eslint/eslint-plugin @typescript-eslint/parser

```JSON
module.exports = {
  parser: "@typescript-eslint/parser",
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true,
  },
  plugins: ["@typescript-eslint"],
  extends: [
    "airbnb",
    "plugin:prettier/recommended",
    "plugin:@typescript-eslint/recommended",
  ],
  globals: {
    Atomics: "readonly",
    SharedArrayBuffer: "readonly",
  },
  parserOptions: {
    ecmaVersion: 2018,
  },
  rules: {},
};
```

## if I remove "plugin:@typescript-eslint/recommended" - everything works fine. 

```TS
export function sayHello() {
  console.log("hi");
}
export function sayGoodbye() {
  console.log("goodbye");
}
```

**Expected Result**

**Actual Result**

**Additional Info**

'''
ms@dragon src %  eslint  hi.ts --debug
  eslint:cli CLI args: [ '--ext', '.ts,.js', 'hi.ts', '--debug' ] +0ms
  eslint:cli Running on files +3ms
  eslint:glob-utils Creating list of files to process. +0ms
  eslint:ignored-paths baseDir = "/Users/ms/workspaces/vscode/janus/janus/packages/l/auth/src" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/node_modules/*"
  eslint:ignored-paths   cooked   = "/node_modules/*" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/bower_components/*"
  eslint:ignored-paths   cooked   = "/bower_components/*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = ".*"
  eslint:ignored-paths   cooked   = ".*" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "!../"
  eslint:ignored-paths   cooked   = "!../" +0ms
  eslint:ignored-paths Looking for ignore file in /Users/ms/workspaces/vscode/janus/janus/packages/l/auth/src +0ms
  eslint:ignored-paths Could not find ignore file in cwd +0ms
  eslint:ignored-paths contains: +1ms
  eslint:ignored-paths   target = "/Users/ms/workspaces/vscode/janus/janus/packages/l/auth/src/hi.ts" +0ms
  eslint:ignored-paths   result = false +0ms
  eslint:ignored-paths contains: +0ms
  eslint:ignored-paths   target = "/Users/ms/workspaces/vscode/janus/janus/packages/l/auth/src/hi.ts" +0ms
  eslint:ignored-paths   result = false +0ms
  eslint:cli-engine Processing /Users/ms/workspaces/vscode/janus/janus/packages/l/auth/src/hi.ts +0ms
  eslint:cli-engine Linting /Users/ms/workspaces/vscode/janus/janus/packages/l/auth/src/hi.ts +0ms
  eslint:config Constructing config file hierarchy for /Users/ms/workspaces/vscode/janus/janus/packages/l/auth/src +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/ms/workspaces/vscode/janus/janus/packages/l/auth/.eslintrc.js +0ms
  eslint:config-file Loading JS config file: /Users/ms/workspaces/vscode/janus/janus/packages/l/auth/.eslintrc.js +0ms
  eslint:plugins Loaded plugin @typescript-eslint (@typescript-eslint/eslint-plugin@3.8.0) (from /usr/local/lib/node_modules/@typescript-eslint/eslint-plugin/dist/index.js) +0ms
  eslint:config-file Loading plugin:@typescript-eslint/recommended +292ms
  eslint:config-file Attempting to resolve @typescript-eslint/eslint-plugin +0ms
  eslint:config-file Loading JS config file: /usr/local/lib/node_modules/@typescript-eslint/eslint-plugin/dist/index.js +1ms
  eslint:config-file Loading /usr/local/lib/node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended +10ms
  eslint:config-file Loading config file: /usr/local/lib/node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended +0ms
  eslint:config-file Error reading YAML file: /usr/local/lib/node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended +18ms
Error: Cannot read config file: /usr/local/lib/node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended
Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended'
Referenced from: /usr/local/lib/node_modules/@typescript-eslint/eslint-plugin/dist/index.js
Referenced from: /Users/ms/workspaces/vscode/janus/janus/packages/l/auth/.eslintrc.js
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at readFile (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:64:15)
    at loadLegacyConfigFile (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:141:44)
    at loadConfigFile (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:240:22)
    at loadFromDisk (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:523:18)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:587:20)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:453:36
    at Array.reduceRight (<anonymous>)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:431:26)
'''

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `3.8.0` |
| `@typescript-eslint/parser`        | `3.8.0` |
| `TypeScript`                       | `4.0.0` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `14.5.0` |
| `npm`                              | `6.14.7` |

**Comment by bradzacher** [comment]
You should upgrade your version of ESLint - ESLint 5.16 is a year and a half old.
I also notice that you're using global installation of plugins. This is not recommended as it works in really weird ways.

Could you please try both upgrading to ESLint 7, and installing the tooling locally?

**Comment by msmey** [comment]
Hi Brad, I've upgraded to 7.6 and now it can't find any plugins at all.
Running locally is not an option because I have a few multi-repos so I want
to have modules in a centralized place,

Thanks and Regards,
Mike

**Comment by bradzacher** [comment]
> Running locally is not an option because I have a few multi-repos so I want
to have modules in a centralized place

That's the point of adding it to your dependencies though?
You add it to your deps, `npm i` and it's installed. Then a simple script in your `package.json` and you can run the lint with the same command.

It's much more preferable. Global installations are in general not a great idea because it creates implicit dependencies that are impossible to track across computers.

You will also run into problems with global installs because you have to sync dependency versions between workspaces and global space. I.e. our tooling loads typescript, and that typescript version _must_ be the same version of typescript you're compiling your code with.

Additionally - we do not actively support global installs. If it works, great - otherwise it's not something we want to support due to the complexities it can introduce.

ESLint also is moving away from global installs for this reason as well.

https://eslint.org/docs/user-guide/getting-started#installation-and-usage

**Comment by msmey** [comment]
Thank very much you Sir, I'll try monorepo setup with lerna. Thanks again for your help!
