### ISSUE TITLE
indent -> ignored +Nodes JSXElement does not include <> (Fragments)

### ISSUE THREAD

**Issue by kyle-ssg** [typescript-eslint/typescript-eslint#2357]
**Repro**
Apologies if I should add this as an issue to eslint directly rather than this. Adding 

```
'@typescript-eslint/indent': [
      "error", 2,
      {
          'JSXElement',
       }
]
```

It works absolutely fine for almost all cases but does not ignore JSX that contains fragments
```
<div>x</div> works
```
```
<>x</> does not work
```

```JSON
{
  "rules": {
        '@typescript-eslint/indent': [
      "error", 2,
      {
        SwitchCase: 1,
        ignoredNodes: [
          'JSXAttribute',
          'JSXIdentifier',
          'JSXClosingElement' ,
          'JSXClosingElement',
          'JSXElement *',
          'JSXElement',
          'JSXElement > *',
          'JSXEmptyExpression',
          'JSXExpressionContainer',
          'JSXMemberExpression',
          'JSXNamespacedName',
          'JSXOpeningElement',
          'JSXSpreadAttribute',
          'JSXSpreadChild',
          'JSXText',
          'TemplateLiteral',
        ],
      },
    ],
    'react/jsx-indent': ["error", 4],
  },
  "parserOptions": {
    "...": "something"
  }
}
```

```TS
 <>
        <ButtonTertiary
            className="mr-2"
            onClick={() => openConfirm(<div>Confirm</div>, <div>Body</div>,
            () => {
              alert('Selected Yes');
            },
            () => {
              alert('Selected No');
            })}
          >
              Open confirm
          </ButtonTertiary>
        <ButtonTertiary
            onClick={() => openAlert(<div>Alert</div>, <div>Body</div>, () => {
            alert('Dismissed');
          })}
          >
              Open alert
          </ButtonTertiary>
    </>
```
**Expected Result**
Ignores (@typescript-eslint/indent) regardless of if starting element is a fragment

**Actual Result**
Fails ESLint: Expected indentation of 4 spaces but found 6.(@typescript-eslint/indent)

**Additional Info**

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.0.0-alpha.5` (tried with 3.7x) |
| `TypeScript`                | `3.8.3` |
| `ESLint`                    | `7.6.0` |
| `node`                      | `12.15.0` |
| `npm`                       | `6.13.4` |

**Comment by bradzacher** [comment]
They produce two different AST nodes.

You should use a tool like astexplorer.net to inspect the AST and find the node names you want to ignore.

**Comment by kyle-ssg** [comment]
Thanks @bradzacher very neat tool. It through me off because the ignoredNodes is typed to a certain set of strings. I think maybe adding the following to types would be good. 

```
          'JSXOpeningFragment' ,
          'JSXClosingFragment' ,
```


Regardless, adding these to the ignoredNodes helped, thanks!
