### ISSUE TITLE
[naming-convention] optional prefix

### ISSUE THREAD

**Issue by InsOpDe** [typescript-eslint/typescript-eslint#2359]
I'd like to be able to do something similar to this, i.e.:

```json
{
	"selector": "variable",
	"modifiers": ["const"],
	"format": ["StrictPascalCase"],
	"prefixOptional": true,
	"prefix": ["C"]
}
```
which would enable me to have an optional prefix on my `const`s.

My workaround for this is this:

```json
{
	"selector": "variable",
	"modifiers": ["const"],
	"format": ["StrictPascalCase", "strictCamelCase"],
	"prefix": ["C", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
}
```
This enables me that the letter `C` is optional

**Comment by bradzacher** [comment]
I believe that you can do this via a [`filter`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#filter)

I something along the lines of this will do the trick:

```json5
{
  selector: 'variable',
  modifiers: ['const'],
  format: ['strictCamelCase'],
  prefix: ['C'],
  filter: {
    regex: '^[A-Z]',
    match: true,
  },
}
```

**Comment by InsOpDe** [comment]
this will do!
