### ISSUE TITLE
NPM Registry 404 Not found error

### ISSUE THREAD

**Issue by NicoAiko** [typescript-eslint/typescript-eslint#2361]
When trying to do `npm i` to install dependencies, npm throws a Not found error.

![Bildschirmfoto 2020-08-06 um 11 37 06](https://user-images.githubusercontent.com/22343587/89516904-4db7fd00-d7d9-11ea-979d-1eb4221cb9ab.png)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `latest` |
| `node`                             | `12.16.1` |
| `npm`                              | `6.14.7` |

**Comment by konekoya** [comment]
Getting this as well but with yarn

**Comment by devalnor** [comment]
I confirm

**Comment by fgerschau** [comment]
Same here, I'm glad I found this issue 😄

**Comment by aa-deet-eeya** [comment]
Same here, 
I was just going to open an issue

**Comment by Nebulis** [comment]
Npm issue => https://status.npmjs.org/

**Comment by chris31389** [comment]
I had this on the build server.  I could replicate locally by clearing the cache

`npm cache clean --force`

**Comment by MaximeSarrato** [comment]
> Npm issue => https://status.npmjs.org/

Same for me!
Clean the cache does nothing :(

https://registry.npmjs.org/@typescript-eslint/parser is not accessible.

**Comment by NicoAiko** [comment]
@MaximeSarrato It seems there is some kind of outage at the NPM services.

We can only wait until these services work again.

Actually, this ticket can be closed again, as it's nothing the authors can do
