### ISSUE TITLE
Invalid Package in NPM

### ISSUE THREAD

**Issue by EduardoSimon** [typescript-eslint/typescript-eslint#2362]
**Repro**

**Expected Result**

Correctly install the npm package

**Actual Result**

npm i @typescript-eslint/eslint-plugin@canary                                                     1 ✘  12:12:43 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@typescript-eslint%2feslint-plugin - Not found
npm ERR! 404
npm ERR! 404  '@typescript-eslint/eslint-plugin@canary' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `node`                             | `12.16.4` |
| `npm`                              | `6.14.6` |

**Comment by mrestorff** [comment]
Can confirm. This is true for any version.

**Comment by NicoAiko** [comment]
See #2361

**Comment by EduardoSimon** [comment]
Closing this issue. As you mentioned in #2361 we have to wait until npm comes back up.
