### ISSUE TITLE
Package Missing from `npm registry` since few hours..

### ISSUE THREAD

**Issue by k-vikram** [typescript-eslint/typescript-eslint#2364]
**Repro**

ran `npm i --save-dev typescript @typescript-eslint/parser` in terminal.

**Expected Result**
Wanted the package to get installed and npm install to run successfully

**Actual Result**

`npm install` failed and CI build also collapsed.

Got this error below:

![image](https://user-images.githubusercontent.com/30444167/89521761-bca74d00-d7fd-11ea-8e42-719e283a0239.png)

**Additional Info**

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `N/A` |
| `TypeScript`              | `N/A` |
| `ESLint`                    | `7.5.0` |
| `node`                      | `12.8.0` |
| `npm`                       | `6.10.2` |

**Comment by k-vikram** [comment]
**IMPACT ALERT:**
This is critical I guess, build all the world may fail because of this. Do correct me if wrong here.

**Comment by olie-chan** [comment]
I just noticed this too. As a temporary fix can we point to the github repo in the package.json?

**Comment by VladTabaka** [comment]
Same issue here. Please prioritize.

**Comment by Krknv** [comment]
https://status.npmjs.org/

**Comment by untimid** [comment]
+

**Comment by k-vikram** [comment]
> I just noticed this too. As a temporary fix can we point to the github repo in the package.json?

@olie-chan Do post a small snippet here meanwhile.

**Comment by freddieerg** [comment]
This is causing massive build failure for many, many people. This is actually huge.

**Comment by NicoAiko** [comment]
#2361

**Comment by k-vikram** [comment]
Closing the issue as there nothing Authors can do.
