### ISSUE TITLE
Unexpected missing rules when upgrading from ^2.30

### ISSUE THREAD

**Issue by tom-sherman** [typescript-eslint/typescript-eslint#2372]
Hi! I see that you have released a 4.0RC, is this version supposed to work with TypeScript 4.0? I've attempted to upgrade in preperation for 4.0 and am getting lots of errors

```
  1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing
  1:1  error  Definition for rule 'unified-signatures' was not found                    unified-signatures
```

Have these rules been removed in a version between 2.30 and 4.0rc? I can't see anything about this in the changelog.

**Comment by bradzacher** [comment]
Please see the v3 release notes.

https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0
