### ISSUE TITLE
Any alternative of // @ts-ignore

### ISSUE THREAD

**Issue by anks333** [typescript-eslint/typescript-eslint#2390]
I just want to disable linter for next line or for the entire file for any type of error 

### Example
```ts
/**
* ERROR
* Property 'save' does not exist on type 'K'.ts(2339)
*/
const u = await d.save();
```
if I use // @ts-ignore, then it's fine, I tried using `// eslint-disable-next-line` but not working.

Any alternative for **// ts-ignore** ?

```JSON
{
    "env": {
        "browser": false,
        "es2020": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "prettier/@typescript-eslint",
        "plugin:prettier/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 2020,
        "sourceType": "module"
    },

    "rules": {
        "indent": ["error", 4, { "SwitchCase": 1 }],
        "linebreak-style": ["error", "unix"],
        "quotes": ["error", "double"],
        "semi": ["error", "always"]
    }
}

```

**Versions**

| package                                   | version |
| ----------------------------------------- | ------- |
| `TypeScript`                              | `3.9.7` |

**Comment by bradzacher** [comment]
What's not working?
Could you please give me some more information?
Also why did you not fill out the version table? What version of our tooling is there.
Please don't ignore the issue template - the template is there so you give me the information I need to help you.

***HELP ME TO HELP YOU***

`ban-ts-comment` has some information that might help you
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-ts-comment.md

**Comment by glen-84** [comment]
`ts(2339)` is a TypeScript error – you cannot suppress a TypeScript error with an ESLint directive.

You can suppress the error with `// @ts-ignore` or `// @ts-expect-error`, if you're not able to specify an appropriate type.
