### ISSUE TITLE
[no-unused-vars] Imports marked as unused if a method argument has the same name

### ISSUE THREAD

**Issue by ago1024** [typescript-eslint/typescript-eslint#2402]
- [X] I have first restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

We're using TypeScript in an AngularJS project. The AngularJS dependency injection uses the argument names to inject the service. The registered service names and implementations usually have the same name. This results in function like those:
```TS
import { SomeService } from "./service";
function foo(SomeService: SomeService) {}
```
The import will be marked as unused by typescript/no-unused-vars

**Repro**
https://github.com/ago1024/typescript-eslint-unused-vars-import

```JSON
{
    "env": {
        "browser": true,
        "es2020": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 11,
        "sourceType": "module"
    },
    "plugins": [
        "@typescript-eslint"
    ],
    "rules": {
        "no-unused-vars": "off"
    }
}
```

```TS
import { SomeService } from "./service";

export function query(SomeService: SomeService): string {
	return SomeService.query();
}
```

**Expected Result**

The imported SomeService type in test.ts:1 should not be marked as unused.

**Actual Result**

The SomeService import in line 1 is marked as unused
```
  1:10  warning  'SomeService' is defined but never used  @typescript-eslint/no-unused-vars
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `3.9.1` |
| `@typescript-eslint/parser`        | `3.9.1` |
| `TypeScript`                       | `3.9.7` |
| `ESLint`                           | `7.7.0` |
| `node`                             | `10.14.1` |

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/1856
