### ISSUE TITLE
Error while loading rule - @typescript-eslint/dot-notation

### ISSUE THREAD

**Issue by LcsGrz** [typescript-eslint/typescript-eslint#2429]
I investigated and tried solutions but I did not find the error, maybe when extending from so many libraries the error is produced.

**Repro**
When I try to use eslint it crash, the problem is in a rule, that even if I turn it off, it still crash.

```
{
  root: true,
  parser: '@typescript-eslint/parser',
  extends: ['@react-native-community', 'airbnb-typescript', 'prettier', 'prettier/@typescript-eslint', 'prettier/react'],
  plugins: ['@typescript-eslint', 'import', 'jsx-a11y'],
  rules: {  ... },
  settings: {
    "import/parsers": {
      "@typescript-eslint/parser": [".ts", ".tsx"]
    },
    "import/resolver": {
      typescript: {}
    }
  },
};
```

**Expected Result**

**yarn lint** or **lint-staged** to work as expected.

**Actual Result**

`Error while loading rule '@typescript-eslint/dot-notation': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser. Occurred while linting /react-native-app/.eslintrc.js`

**Extra info**
TSConfig

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs", 
    "lib": ["es6"],  
    "allowJs": true,
    "jsx": "react-native", 
    "noEmit": true,
    "isolatedModules": true, 
    "strict": true, 
    "moduleResolution": "node", 
    "allowSyntheticDefaultImports": true,  
    "esModuleInterop": true,        
    "baseUrl": ".",
    "experimentalDecorators": true,
    "noFallthroughCasesInSwitch": true,
    "paths": {
      "~/*": ["src/*"],
    },
    "removeComments": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strictNullChecks": true,
    "typeRoots": ["node_modules/@types", "@types"],
  },
}
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `3.10.1` |
| `TypeScript`                | `4.0.2` |
| `ESLint`                    | `7.7.0` |
| `node`                      | `X.Y.Z` |
| `@typescript-eslint/eslint-plugin`| `3.10.1` |
| `eslint-config-airbnb-typescript`| `9.0.0` |
| `eslint-config-prettier`| `6.11.0` |
| `eslint-import-resolver-typescript`| `2.2.1` |
| `eslint-plugin-import`| `2.22.0` |
| `eslint-plugin-jsx-a11y`| `6.3.1` |
| `eslint-plugin-react`| `7.20.6` |

**Comment by bradzacher** [comment]
Is the error message not self-explanatory enough?

> You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.

The docs include more information. Please give them a read.
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#parseroptionsproject

There's also the getting started guide, which also includes information which can help you.
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md#i-get-errors-telling-me-the-file-must-be-included-in-at-least-one-of-the-projects-provided
