### ISSUE TITLE
tsconfig referenced by .eslintrc  is ignored and root tsconfig.json is used instead (VS Code plug-in only, not a CLI bug)

### ISSUE THREAD

**Issue by lukewlms** [typescript-eslint/typescript-eslint#2434]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

We have a code base with both a server and a react client.  The server is at ./src and the client at ./client/src.  We have both a tsconfig.json and an .eslintrc in each directory.  

This setup works great from the CLI.  But when opening any client file (in the example below this is clientIndex.ts) in VS Code, we continually get the error:

```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: client/src/clientIndex.ts.
The file must be included in at least one of the projects provided.eslint
```

This minimal case repros:
https://github.com/lukewlms/eslint-typescript-client-eslintrc-error

**JSON and TSConfig**

```json
// ./src/.eslintrc

{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "parserOptions": { "project": ["./tsconfig.json"] },
  "plugins": ["@typescript-eslint"],
  "env": { "es6": true, "jest": true, "node": true },
  "extends": ["eslint:recommended", "plugin:@typescript-eslint/recommended"]
}

// ./src/client/.eslintrc
{
  "extends": ["../.eslintrc"],
  "parserOptions": { "project": ["./tsconfig.json"] },
  "env": {
    "browser": true
  }
}

// ./src/tsconfig.json
{
  "compilerOptions": {
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    "strict": true,                           /* Enable all strict type-checking options. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    "skipLibCheck": true,                     /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true  /* Disallow inconsistently-cased references to the same file. */
  },
  "include": ["src/**/*"]
}

// ./src/client/tsconfig.json

{
  "compilerOptions": {
    "target": "es5" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */,
    "module": "commonjs" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */,
    "strict": true /* Enable all strict type-checking options. */,
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,
    "skipLibCheck": true /* Skip type checking of declaration files. */,
    "forceConsistentCasingInFileNames": true /* Disallow inconsistently-cased references to the same file. */
  },
  "include": ["src/**/*"]
}
```

**Expected Result**

Plug-in with TS should be able to handle these files.  ESLint traverses up the directory tree, which means it should hit the client/.eslintrc file first, which references client/tsconfig.json, which includes the client files.  The client files should be found be ESLint in the VS Code plug-in (as they are in the CLI).

**Actual Result**

The error above appears at the top of any file under `./client`.

Note that if we add an additional include in the root tsconfig.json referencing the client directory, this error goes away.  So, it looks like typescript-eslint is always using the root tsconfig.json within VS Code, *not* the project file referred to by the relevant .eslintrc file:

`"include": ["src/**/*", "client/**/*"]`

Finally, if we add tsconfig.eslint.json at the root and point to it from .eslintrc, using the `include` value in the line above, it still doesn't work.  Again it appears the VS Code plug-in is ignoring whatever project is specified in the relevant .eslintrc and just using the root's tsconfig.json.

Here's the sample tsconfig.eslint.json:
```
{
  "include": ["src/**/*", "client/**/*"]
}
```

And relevant updated line from ./.eslintrc:
```
  "parserOptions": { "project": ["./tsconfig.eslint.json"] },
```

So, the *only* way to get `./client/src/**.*` files recognized is to reference them in the root tsconfig.json's `include` value.  But, that severely limits what we can do with ESLint because our React client has a different environment and needs different .eslintrc options than the server.

Are we doing something wrong?  How can we get files under ./client/src to be recognized per ./client/.eslintrc and ./client/tsconfig.json, separate from the root config files?

**Versions**

    "@typescript-eslint/eslint-plugin": "^3.10.1",
    "@typescript-eslint/parser": "^3.10.1",
    "eslint": "^7.7.0",
    "typescript": "^4.0.2"

    node: v12.18.3

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#parseroptionstsconfigrootdir

ESLint provides the parser with no context around the location of config files. This is because under the hood ESLint does its own merging and resolutions of config files.
We have one known - the CWD, which we will use if you provide a relative path.

Use `tsconfigRootDir` if you want to use a different path other than CWD.

**Comment by lukewlms** [comment]
Wow, ok - I'll take a look and see if I can suggest a tweak to the docs (or maybe we missed something there).  I definitely would have thought the project path would be relative to the .eslintrc file.

For reference: Fixed by updating the project value in ./client/.eslintrc to be relative to the root, not .eslintrc.

```
  "parserOptions": { "project": ["client/tsconfig.json"] },
```

**Comment by lukewlms** [comment]
Ok spoke too soon - this works for the VS Code plug-in but breaks linting in the CLI, which now can't find the tsconfig.json file (there is no nested client/client dir):

  0:0  error  Parsing error: Cannot read file 'client/client/tsconfig.json'

It looks like the CLI and VS Code plug-in are using different rules to resolve the location of `project`.  Can you confirm that and/or suggest a way to make them both work?

**Comment by bradzacher** [comment]
it's all about the CWD.
If your VSCode is open in the same directory as you run the CLI command, then they'll both work the same.
If you run the CLI command from a different folder, then it will work differently to VSCode.

Just use `.eslintrc.js` and use `__dirname` for `tsconfigRootDir` and it will always work as expected, no matter what folder is open or what folder you are in.

```js
module.exports = {
  parserOptions: {
    project: "./tsconfig.json",
    tsconfigRootDir: __dirname,
  },
};
```

----

Note, ESLint is going to deprecate json config files in a future version, so just switch to a js config file now to save you migrating later.
`.eslintrc` files are already kind of deprecated, as they are ambiguous.
