### ISSUE TITLE
[@typescript-eslint/explicit-function-return-type] got warning using plugin:@typescript-eslint/recommended

### ISSUE THREAD

**Issue by tianzhich** [typescript-eslint/typescript-eslint#2443]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

I'm using `plugin:@typescript-eslint/recommended` config for my typescript codebase. I got `Missing return type on function.` warning. But this rule was not listed as a recommendation [here](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules). 

Is this an expected behavior? If yes, can u provide more detailed docs which could distinguish error and warning when using 
`plugin:@typescript-eslint/recommended`

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.19.2` |
| `@typescript-eslint/parser`        | `2.19.2` |
| `TypeScript`                       | `3.9.7` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `14.3.0` |

**Comment by bradzacher** [comment]
> - [x] I have updated to the latest version of the packages.

The fact that you've listed v2.x when the latest release is 3.x suggests that you just ticked this box without actually doing it.
