### ISSUE TITLE
[eslint-plugin@4.0.0] need to update peer dependency range?

### ISSUE THREAD

**Issue by AviVahl** [typescript-eslint/typescript-eslint#2444]
Newly released `@typescript-eslint/eslint-plugin` has a `peerDependency` on `@typescript-eslint/parser`. It currently says:
`"@typescript-eslint/parser": "^3.0.0"`

Is it compatible with `@typescript-eslint/parser@4.0.0`?

FYI @bradzacher

**Comment by bradzacher** [comment]
fffffffffffffffffffffffffuck.
I forgot that we have this soft dependency range that lerna doesn't auto-update.

**Comment by AviVahl** [comment]
My team has been hit by the same lerna behavior in our projects (basically every time we release a major ;))

**Comment by bradzacher** [comment]
I'll try to get an out-of-band release done today.

**Comment by bradzacher** [comment]
4.0.1 has been released!
