### ISSUE TITLE
Feature request: [no-shadow] It would really help, if the error message would show where the original identifier has been defined

### ISSUE THREAD

**Issue by doberkofler** [typescript-eslint/typescript-eslint#2458]
In my experience, the `no-shadow` rule could greatly benefit from an error message that also describes where the identifier has already been defined and not only where the redefinition has occurred.

```TS
const a = 1;

if (a === 1) {
	const a = 5;
	console.log(a);
}
```

Instead of the current error:

`4:8  error  'a' is already declared in the upper scope  @typescript-eslint/no-shadow`

the following would be most helpful:

 `4:8  error  'a' is already declared in the upper scope (1:7)  @typescript-eslint/no-shadow`

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.0.1` |
| `@typescript-eslint/parser`        | `4.0.1` |
| `TypeScript`                       | `4.0.2` |
| `ESLint`                           | `7.8.0` |
| `node`                             | `14.8.0` |

**Comment by bradzacher** [comment]
Thanks for the request! Whilst our version of the rule is currently a reimplementation of `no-shadow`, I don't want to break parity with the base eslint rule.

Extension rules are intended to be extended versions with as few changes as possible to make them work for TS.

Please submit this as a request to eslint core. If they are aligned then happy to update our version to match.

**Comment by doberkofler** [comment]
I've created the sr https://github.com/eslint/eslint/issues/13646
