### ISSUE TITLE
Updating `@typescript-eslint/parser` breaks `eslint-plugin-jsdoc`

### ISSUE THREAD

**Issue by daviduzumeri** [typescript-eslint/typescript-eslint#2460]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

I've isolated it down to this: simply using `@typescript-eslint/parser` and `eslint-plugin-jsdoc` in tandem results in an error message (copied below). A repo to reproduce is here: https://github.com/daviduzumeri/ts-eslint-jsdoc-repro. The issue seems new with TS-ESLint 4, which is why I've reported it here, even though the exception is technically being thrown from eslint-plugin-jsdoc; if this is the wrong place I'll be happy to throw it over there instead :)

(This also obviously happens with `@typescript-eslint/eslint-plugin` in the mix but I wanted to reduce things down to the absolute minimum repro case)

Some initial digging suggests that this is due to having the options field on `scopeManager` now be a privately accessible field called `#options` rather than the previous `__options`. So it's possible that `eslint-plugin-jsdoc` shouldn't be accessing this field at all, but that's a fairly popular package that's been in use for a considerable period of time.

**Expected Result**

I would expect it to lint and not crash.

**Actual Result**

```
$ eslint main.ts --ext .ts

Oops! Something went wrong! :(

ESLint: 7.8.0

TypeError: Cannot read property 'nodejsScope' of undefined
Occurred while linting /Users/daviduzumeri/Documents/GitHub/ts-eslint-jsdoc-repro/main.ts:5
    at _default.iterateAllJsdocs (/Users/daviduzumeri/Documents/GitHub/ts-eslint-jsdoc-repro/node_modules/eslint-plugin-jsdoc/dist/rules/noUndefinedTypes.js:130:26)
    at iterate (/Users/daviduzumeri/Documents/GitHub/ts-eslint-jsdoc-repro/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:539:3)
    at /Users/daviduzumeri/Documents/GitHub/ts-eslint-jsdoc-repro/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:578:7
    at Array.forEach (<anonymous>)
    at callIterator (/Users/daviduzumeri/Documents/GitHub/ts-eslint-jsdoc-repro/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:573:16)
    at *:not(Program) (/Users/daviduzumeri/Documents/GitHub/ts-eslint-jsdoc-repro/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:626:11)
    at /Users/daviduzumeri/Documents/GitHub/ts-eslint-jsdoc-repro/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/daviduzumeri/Documents/GitHub/ts-eslint-jsdoc-repro/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/daviduzumeri/Documents/GitHub/ts-eslint-jsdoc-repro/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
error Command failed with exit code 2.
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.0.1` |
| `eslint-plugin-jsdoc` | `30.3.0` |
| `TypeScript`                | `4.0.2` |
| `ESLint`                    | `7.8.0` |
| `node`                      | `12.18.3` |

**Comment by bradzacher** [comment]
Looking at the field they're using (`nodejsScope`), I don't think it's doing what they think it's doing either. That option is incorrectly named; it has nothing to do with nodejs. Its value actually reflects the value of `parserOptions.ecmaFeatures.globalReturn`.

https://github.com/eslint/eslint/blob/82669fa66670a00988db5b1d10fe8f3bf30be84e/lib/linter/linter.js#L613

---

https://eslint.org/docs/developer-guide/scope-manager-interface#scopemanager

There is no field on the scope manager API called `__options` - `eslint-plugin-jsdoc` has tightly tied their implementation to private and undocumented protected api provided by the `eslint-scope` package.

When I built the new scope manager, I ensured it adhered to the documented API. I purposely made the decision to hide protected and private members where possible because the scope manager codebase was a mess that has grown organically and never really refactored since its initial implementation more than 8 years ago.

I don't think we should be mirroring the private internals of another package to allow a 3rd party package to dangerously breach encapsulation and reach into the implementation details.

**Comment by daviduzumeri** [comment]
> Looking at the field they're using (`nodejsScope`), I don't think it's doing what they think it's doing either. That option is incorrectly named; it has nothing to do with nodejs. Its value actually reflects the value of `parserOptions.ecmaFeatures.globalReturn`.
> 
> https://github.com/eslint/eslint/blob/82669fa66670a00988db5b1d10fe8f3bf30be84e/lib/linter/linter.js#L613
> 
> https://eslint.org/docs/developer-guide/scope-manager-interface#scopemanager
> 
> There is no field on the scope manager API called `__options` - `eslint-plugin-jsdoc` has tightly tied their implementation to private and undocumented protected api provided by the `eslint-scope` package.
> 
> When I built the new scope manager, I ensured it adhered to the documented API. I purposely made the decision to hide protected and private members where possible because the scope manager codebase was a mess that has grown organically and never really refactored since its initial implementation more than 8 years ago.
> 
> I don't think we should be mirroring the private internals of another package to allow a 3rd party package to dangerously breach encapsulation and reach into the implementation details.

That's a perfectly cromulent answer, and makes total sense to me (and sort of what I expected as soon as I started actually digging in). I can go ahead and reference this in an issue on `eslint-plugin-jsdoc` if you want me to kick the ball down the field over there.

**Comment by bradzacher** [comment]
Please do!

Thanks for raising this though. It's always interesting to see what the ecosystem is doing with the tooling, even if it's doing things wrong! It's a good learning experience.
