### ISSUE TITLE
[no-undef] No-undef error on user-defined Typescript type guards

### ISSUE THREAD

**Issue by victorgarciaesgi** [typescript-eslint/typescript-eslint#2462]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    '@typescript-eslint/no-useless-constructor': 'error',
    '@typescript-eslint/no-unused-vars': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-use-before-define': 'off',
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/no-var-requires': 'off',
    '@typescript-eslint/no-namespace': 'off',
    '@typescript-eslint/camelcase': 'off',
    '@typescript-eslint/no-empty-function': 'off',
    '@typescript-eslint/ban-ts-ignore': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/ban-ts-comment': 'off',
    '@typescript-eslint/no-non-null-assertion': 'off',
  }
}
```

```TS
@Component
export default class Column extends Vue {
  isColumnString(column: TableColumn): column is string {
                                   //   ^^^^^ 'column' is not defined (eslint: no-undef)
    return typeof this.column === 'string';
  }
}

```

**Expected Result**

**Actual Result**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.0.1` |
| `@typescript-eslint/parser`        | `4.0.1` |
| `TypeScript`                       | `4.0.2` |
| `ESLint`                           | `7.8.0` |
| `node`                             | `12.18.0` |

**Comment by jacekkarczmarczyk** [comment]
Is [this bug](https://github.com/vuejs/eslint-plugin-vue/issues/1293) related/duplicate?

**Comment by vvscode** [comment]
@jacekkarczmarczyk  in fact it's another problem, but it might be caused with same reason

**Comment by vvscode** [comment]
Repo with demo : https://github.com/vvscode/ts--eslint-parser-error-demo
