### ISSUE TITLE
parserOptions.ecmaVersion ignored / not linting 

### ISSUE THREAD

**Issue by GarfieldDeepClone** [typescript-eslint/typescript-eslint#2524]
Hi :)

I configured ecmaVersion 6 for my test files but it does not lint features that are not available in ecma6. Rules are working fine.

.eslintrc.js
```JS
module.exports = {
    root: true,

    extends: ['airbnb-base', '.eslintrc.airbnbonlywarnings.js'],

    parser: '@typescript-eslint/parser',

    parserOptions: {
        ecmaVersion: 6,
        ecmaFeatures: {
            blockBindings: false,
            forOf: false
        },
        project: 'tsconfig.json',
        tsconfigRootDir: __dirname
    },

    plugins: ['@typescript-eslint'],

    overrides: [{
        files: ['**/e2e/**/*.ts', '**/e2e/**/*.js'],
        parserOptions: {
            ecmaVersion: 6,
            project: 'tsconfig.e2e.json'
        }
    }]
}
```

tsconfig.e2e.json
```JSON
{
	"compilerOptions": {
		"rootDir": ".",
		"outDir": "build-e2e",
		"allowJs": true,
		"incremental": true,
		"moduleResolution": "node",
		"module": "commonjs",
		"target": "es6",
		"noEmitOnError": true,
		"strict": false,
		"typeRoots"	:[
			"./@types",
			"./node_modules/@types"
		],
		"removeComments": false,
		"sourceMap": false
	},
	"include": [
		"@types/**/*.d.ts",
		"test/protractor/**/*.ts",
		"test/protractor/**/*.js",
		"src/**/test/e2e/**/*.ts",
		"src/**/test/e2e/**/*.js",
		"grunt/users/**/fake.config.ts"
	],
	"exclude":[
		"./node_modules",
		"./customer_bundles"
	]
}
```

Example code:
```TS
const myObj = { a: 'somestring', b: 42, c: false };
const tmp = Object.values(object1);
```

**Expected Result**

Because Object.values() is a feature introduced in ecma 2017 it should lint that line because I specified ecmaVersion 6 aka 2015

**Actual Result**

It's not linting

**Additional Info**

It's not linting in IntelliJ and also not via console. No errors in console.
Upgraded @typescript-eslint/parser 2.25.0 to 4.1 but that didn't help.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.25.0` |
| `TypeScript`                | `3.9.2` |
| `ESLint`                    | `6.3.0` |
| `node`                      | `14.4.0` |

**Comment by bradzacher** [comment]
`ecmaVersion` is for syntax support only. It has nothing to do with runtime features.

> It's not linting

What's not working? I need more than that to be able to help you.

The issue template asked you to be as specific as possible. This is on purpose so I don't have to do exactly this... 

Tell me ***exactly what is happening***

**Comment by GarfieldDeepClone** [comment]
Not linting -> it's doing nothing. It's not throwing an error, it's not a false positive. Doing nothing means here it's a false negative. It should throw an eslint error because I'm using syntax that is not supported in the specified version.

**Comment by bradzacher** [comment]
As mentioned:

> ecmaVersion is for syntax support only. It has nothing to do with runtime features.

***The _syntax_ is valid.***
The runtime feature is not. ESLint does not check for runtime features.

If you want warnings about the features, you must use a plugin like https://github.com/mysticatea/eslint-plugin-es

**Comment by GarfieldDeepClone** [comment]
Ok, so what should ecmaVersion then should be used for? You say syntax support. Can you make an example? Arrow functions?

And why is it linting as soon as I'm removing @typescript-eslint/parser ?

**Comment by bradzacher** [comment]
Docs: https://eslint.org/docs/user-guide/configuring#specifying-parser-options-1

Set `ecmaVersion` based on the code that you are ***writing***, not the compilation target.

The exact functionality of the `ecmaVersion` feature is dependent on the parser. For our parser it mostly does nothing, aside from enabling some ES module features in the scope analyser.

For the base eslint parser it'll do some things like what syntax is allowed to be parser.
If you're curious what it does for that parser, you can play around with it in their demo page: https://eslint.org/demo

**Comment by GarfieldDeepClone** [comment]
Thanks for your help :)
