### ISSUE TITLE
dead link in release note v4.0.0

### ISSUE THREAD

**Issue by n1ru4l** [typescript-eslint/typescript-eslint#2539]
I won't fill in the template as it is only a documentation issue :)

https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.0.0

The following link leads to a 404 page: https://github.com/typescript-eslint/typescript-eslint/blob/v4/packages/parser/README.md#parseroptionslib

**Extract:**
> some users may need to configure the new parserOptions.lib option to ensure the global types are correctly defined for rules like no-undef.

**Comment by bradzacher** [comment]
thanks! fixed
