### ISSUE TITLE
Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json'

### ISSUE THREAD

**Issue by tiavina-mika** [typescript-eslint/typescript-eslint#2546]
```
ESLint: 7.8.1

Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json': Cannot find module '@typescript-eslint/parser'
```

I have this error when runing npm run lint in VS Code.

**Comment by bradzacher** [comment]
You have provided literally zero information here.
How am I supposed to help you?

The issue template you ignored contained a lot of sections which would have helped me to help you.
You need to ensure you install everything locally in your repo.
That's the only advice I can give.

**Comment by tiavina-mika** [comment]
I was using two folder /client and /server in the root directory with a
tsconfig.json and .eslintrc within each.
I have to create a tsconfig in the root directory for the VS Code eslint
extension to find it and extend it from each tsconfig inside /client and
/server.

My structure are:
/server
   .eslintrc.json
   .tsconfig
/client
   .eslintrc.json
   .tsconfig
tsconfig


Le sam. 12 sept. 2020 à 19:25, Brad Zacher <notifications@github.com> a
écrit :
