### ISSUE TITLE
Test against multiple TypeScript versions in CI

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#2565]
_(starting from scratch because there isn't a repo build steps focused issue template)_

Splitting out an issue for https://github.com/typescript-eslint/typescript-eslint/pull/2516#discussion_r484678962:

> We don't yet have any test tooling around specifying TS versions (for any package).
> On the to-do list but nobody has ever prioritised it.

The simplest approach might be extending CI's [`unit_tests_on_other_node_versions`](https://github.com/typescript-eslint/typescript-eslint/blob/f785965a12e20e82de1c7f3d039023c225115eb1/.github/workflows/ci.yml#L231) to also switch on different TypeScript package versions ([example syntax](https://github.community/t/create-matrix-with-multiple-os-and-env-for-each-one/16895/2)). 

It'd be great as a next step _(followup issue?)_ to also make use of [CodeCov's report merging](https://docs.codecov.io/docs/merging-reports) to combine unit test coverage from all of them. #2516 is an example PR where code under test changes behavior on the TypeScript version.

**Comment by bradzacher** [comment]
We should probably centralise discussion about this on #1752

**Comment by JoshuaKGoldberg** [comment]
Aha! I searched but didn't find that one. Thanks!
