### ISSUE TITLE
Windows development support

### ISSUE THREAD

**Issue by doumart** [typescript-eslint/typescript-eslint#2580]
I don't know if i am the only who develops on a PC, but i can't run any pipelines.

the visitor-keys tests fails because the regex check for `tests/*.ts` but on PC it would be `tests\*.ts`. 

It is the only exemple i have since i can't run any script.

**Comment by bradzacher** [comment]
There may be some people that do - but I work on a mac.
If you're just working on the plugin, you can ignore all other package tests as the plugin is a leaf node in the dependency graph.

**Comment by doumart** [comment]
Ok ,will do. Anyway i have a mac to, but i was wondering if it would be a good idea to add support for windows.
