### ISSUE TITLE
'U' is defined but never used @typescript-eslint/no-unused-vars

### ISSUE THREAD

**Issue by StanislavNemytov** [typescript-eslint/typescript-eslint#2588]
```export type InferActionsTypes<T> = T extends { [keys: string]: (...args: any[]) => infer U } ? U : never;```
`'U' is defined but never used  @typescript-eslint/no-unused-vars`
How about this. Help!

_Originally posted by @StanislavNemytov in https://github.com/typescript-eslint/typescript-eslint/issues/2459#issuecomment-696283258_

**Comment by bradzacher** [comment]
please open a new issue and follow the template.
