### ISSUE TITLE
no-unused-vars rule being applied to an interface that is being used a an generic param

### ISSUE THREAD

**Issue by LauraBeatris** [typescript-eslint/typescript-eslint#2604]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

Extending https://github.com/jungsoft/eslint-config/blob/master/rules/typescript/index.js and ``plugin:@typescript-eslint/recommended``

```
{
  extends: [
    "plugin:@typescript-eslint/recommended",
    "@jungsoft/eslint-config/react",
    "@jungsoft/eslint-config/typescript",
  ],
  rules: {
    "react/react-in-jsx-scope": "off",
  },
  settings: {
    "import/resolver": {
      typescript: {},
      node: {
        extensions: [
          ".ts",
          ".tsx",
        ],
      },
    },
  },
};
```

```TS
import Document, {
  Html,
  Head,
  Main,
  NextScript,
  // 'DocumentProps' is defined but never used. Allowed unused vars must match /^_/u.
  DocumentProps,
} from "next/document";

class MyDocument extends Document<DocumentProps> {
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "baseUrl": "."
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

Code from https://github.com/DenoBrazil/denobrazil.com/pull/19

**Expected Result**

Since the ``DocumentProps`` type is being passed as a generic param to ``Document``, it shouldn't be considered as an error related to the ``no-unused-vars`` rule 

**Actual Result**

The ``DocumentProps`` is being considered as an unused type but it's being used

**Additional Info**

![image](https://user-images.githubusercontent.com/48022589/94370475-a5cafb80-00c6-11eb-9f60-045ba2a013ed.png)

![image](https://user-images.githubusercontent.com/48022589/94370510-d6ab3080-00c6-11eb-8c9e-83a2805c6a9b.png)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `^4.0.0` |
| `@typescript-eslint/parser`        | `^3.7.0` |
| `TypeScript`                       | `^4.0.2` |
| `ESLint`                           | `^7.10.0` |
| `node`                             | `v12.16.3` |

**Comment by bradzacher** [comment]
> I have updated to the latest version of the packages.

But you listed v3.7.0 of the parser and v4.0.0 of the plugin.

Please update to the latest version.

**Comment by LauraBeatris** [comment]
@bradzacher Yeah... my bad. After updating the parser to 4.2.0, it started to work again. 

Thanks!!
