### ISSUE TITLE
prohibit the default value for empty objects

### ISSUE THREAD

**Issue by TuiMao233** [typescript-eslint/typescript-eslint#2618]
I want a rule that prohibits the default value for an object. 
When the default value is an empty object, the type will be at risk of loss

```javascript
const getUserInfo = (params = {}) => {
  return http.get<UserInfo>('/login', { params });
};
getUserInfo({
  aaa: 123,
  bbb: 123,
});
````

**Comment by bradzacher** [comment]
Could you please explain what you mean by "the type will be at risk of loss"?

**Comment by TuiMao233** [comment]
At work, no matter the result, colleagues always like = {}. When the value is an empty object, no matter whether the placed object is {id: 1} or {di: 1}, it can be compiled normally. This is terrible.

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#how-can-i-ban-specific-language-feature

You can use `no-restricted-syntax` to do this.
A selector like `AssignmentPattern[left.typeAnnotation.type != TSTypeAnnotation] > ObjectExpression[properties.length = 0].right` will match what you want.

**Comment by TuiMao233** [comment]
Thanks, this solved my problem!
