### ISSUE TITLE
ESLint un-used varialbes rule for parameters of function type in TypeScript

### ISSUE THREAD

**Issue by youbek** [typescript-eslint/typescript-eslint#2619]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**
``` type Func = (paramA: number) => void ```

.eslintrc.json
```
{
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/eslint-recommended"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "plugins": [
        "react",
        "@typescript-eslint"
    ],
    "rules": {
    }
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "downlevelIteration": true,
    "lib": ["dom", "dom.iterable", "esnext"],
    "baseUrl": "./src",
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": ["src"]
}
```

**Expected Result**
No any linting error

**Actual Result**
ESLint shows error - 'paramA' is defined but never used. (eslint: no-unused-vars)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `^4.3.0` |
| `@typescript-eslint/parser`        | `^4.3.0` |
| `TypeScript`                       | `^3.9.3` |
| `ESLint`                           | `^6.6.0` |
| `node`                             | `v12.18.3` |

**Comment by yeonjuan** [comment]
@youbek See [FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-am-using-a-rule-from-eslint-core-and-it-doesnt-work-correctly-with-typescript-code), You should `off` the eslint core rule and `on` the typescript-eslint rule.

```
rules: {
  "no-unused-vars": "off",
  "@typescript-eslint/no-unused-vars": "error"
}
```

**Comment by youbek** [comment]
@yeonjuan Thank you, next time I'll first look at FAQ :)
