### ISSUE TITLE
Rule proposal: avoid using deprecated code

### ISSUE THREAD

**Issue by fregante** [typescript-eslint/typescript-eslint#2620]
TypeScript recently added [detection for `@deprecated` JSDoc comments](https://github.com/microsoft/TypeScript/pull/38523) so unless they also start reporting them as type errors (seems unlikely?) I think it makes sense to push the user to stop using deprecated code before the code is actually dropped in a new release and the code breaks without explanation[.](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/17)

```ts
/** @deprecated Use sing() */
function talk() {}
talk();
// Error: `talk` was marked as deprecated: Use sing()
```

**Comment by bradzacher** [comment]
I believe https://github.com/gund/eslint-plugin-deprecation will do what you want here.
See reasoning for this existing separately here: #1223

**Comment by ark120202** [comment]
> they also start reporting them as type errors (seems unlikely?)

There is an open PR that adds a flag that makes these diagnostics warnings - https://github.com/microsoft/TypeScript/pull/40607

> I believe gund/eslint-plugin-deprecation will do what you want here.
> See reasoning for this existing separately here: #1223

Unless this TypeScript PR would be merged, I think it would be nice to keep this issue open. Even though conceptually this issue tracked (and this plugin implemented) the same thing, a rule based on TypeScript API is going to track what is deprecated better ([there is a lot of edge cases](https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+in%3Atitle+label%3ABug+deprecated)), and it's warnings would be guaranteed to match decorations provided by language service.

**Comment by bradzacher** [comment]
It might be better to open a tracking issue against the other plugin for that.

We don't _really_ want to create our own version of the rule to compete with it.

Also I haven't looked into it, but I'd assume the logic is built into the language server. Also accessing that logic is kind of ugly. Its APIs are not designed for use outside the server.

Example #1905 is ugly and took a lot of trial and error to get it into that half working state.

**Comment by ark120202** [comment]
> It might be better to open a tracking issue against the other plugin for that.

I believe API-based rule wouldn't re-use any code from the old one. IMO keeping it in a separate plugin would make it harder to discover and use, especially given that it has less permissive license.

> Also I haven't looked into it, but I'd assume the logic is built into the language server.

It's handled as a part of type checking, and can be easily accessed with `program.getSuggestionDiagnostics(sourceFile)` (though I'm not sure what are performance implications of that)

**Comment by bradzacher** [comment]
> program.getSuggestionDiagnostics(sourceFile) (though I'm not sure what are performance implications of that) 

Probably not too dissimilar to `getSemanticDiagnostics` at ~50ms per file, or `findReferencedSymbols` at ~80ms per file.

That doesn't sound that bad, but that's an unavoidable `O(N)` which costs ~1s per 20 files. So on most codebases you're talking 10s of seconds.

I learnt about this the hard way with  `no-unused-vars-experimental`.

The problem you've got is that our tooling doesn't actually collect any diagnostics as part of the parse, so asking TS to compute something codebase-wide ends up being costly.

I have no idea how it's actually implemented, but hazarding a guess that deprecated checks would likely involve checking every import, member expression or call expression in the file to see if the symbol of the type it's touching is deprecated. This would match a lot of things so there'd be a lot of lazily computed type information to inspect - not cheap.

There's an open question about how to actually use these lint rules. For large codebases it's often too slow to run on the user's machine. But relegating them to only run on the CI only is a poor UX.

**Comment by sindresorhus** [comment]
> There's an open question about how to actually use these lint rules. For large codebases it's often too slow to run on the user's machine. But relegating them to only run on the CI only is a poor UX.

I would think that a note in the rule documentation about its performance implication would be enough. I want this for small projects, so the performance is not a problem.

**Comment by JoshuaKGoldberg** [comment]
The linked https://github.com/gund/eslint-plugin-deprecation has been stable for a few years now, and nobody's interacted with this issue in quite some time. And it only has a half dozen 👍s. While I'd love to have this rule be first-party, we're not going to get to it anytime soon. Closing out to keep our issue queue small.
