### ISSUE TITLE
[@typescript-eslint/semi] Option to not require semicolons at the end of arrow functions in a class

### ISSUE THREAD

**Issue by ukch** [typescript-eslint/typescript-eslint#2633]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

We have code such as the following:

```JSON
{
  "rules": {
    "@typescript-eslint/semi": ["error"]
  }
}
```

```TS
class MYClass {
    public aNormalFunction() {
        /* function content */
    }

    public anArrowFunction = () => {
        /* function content */
    }
}
```

Previously, using `tslint` (and the rule `semicolon: true`), this code would be acceptable. However, after switching to `eslint`, the arrow functions are now expected to end in a semicolon, but the normal functions are not. I can understand the reasoning for this (IIRC an arrow function is technically an attribute), but it would be great if this could be configured as an option.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.2.0` |
| `@typescript-eslint/parser`        | `4.2.0` |
| `TypeScript`                       | `3.9.6` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `13.4.0` |

**Comment by bradzacher** [comment]
> arrow functions are now expected to end in a semicolon, but the normal functions are not.  I can understand the reasoning for this (IIRC an arrow function is technically an attribute) 

The reasoning is exactly as you stated. There is no "technically". They just are.

Arrow functions _are_ class properties.
"Normal functions" are methods.

Like function declarations, methods are not subject to automatic semicolon insertion - and adding a semicolon is actually incorrect syntax.

Arrow functions are class properties, meaning they are subject to automatic semicolon insertion.

The point of the `semi` rule is to explicitly add a semicolon in all places so as to not rely on ASI.

---

Regardless, `semi` is an extension rule. We intentionally do not break too far from the base rule with our extension rules to make maintenance easier and to make it easier for users to understand.

So we will not be adding any options to the rule at this time.
