### ISSUE TITLE
[no-unsafe-return] Replacing JSX namespace works in TypeScript but fails in ESLint as "any"

### ISSUE THREAD

**Issue by heyheyhello** [typescript-eslint/typescript-eslint#2635]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

Hello! I'm trying to ship a library that include two JSX typings, one is the ~900LoC of normal JSX definitions (from Preact), and the other is 25LoC of edits. These edits reference the normal definitions.

This is to enable support for a new datatype in JSX. I'd like to support other developers to add their own datatypes (instead of mine), and it's nice that doing so can possibly be done in around 25LoC (via test case 3, see below).

**Repro**

I've made a minimal testing repo that has 3 test cases and I'll walk through how those work:

https://github.com/heyheyhello/sinueux-typescript-eslint

The relevant files are:
- _/sinueux/index.d.ts_: The library that exports a JSX namespace on its `h()` call. Similar to Preact. This has the 3 test cases.
- _/sinueux/jsx.d.ts_: The normal JSX definitions (library agnostic)
- _/sinueux/jsx-sinueux.d.ts_: Regretfully here to prove that ESLint works when the 25 lines of edits are embedded into the normal JSX namespace. I don't want people to do this or require developers to code/paste and ship their own (900+25) line d.ts file just to support their datatype.
- _/src/index.tsx_: The user code consuming the library.

To cycle through the tests, comment/uncomment the blocks in _/sinueux/index.d.ts_.

**Test 1**: Using the original JSX typings

![image](https://user-images.githubusercontent.com/44614862/95141562-6768b880-0726-11eb-8464-0f4fd05e7b0e.png)

That's OK :) The error on `text` is valid because these are the normal untouched JSX typings so of course they don't support the custom datatype:

![image](https://user-images.githubusercontent.com/44614862/95141622-88c9a480-0726-11eb-9db2-88f5db37c486.png) 

**Test 2**: Writing the 25 lines of edits into the original JSX typings (unfortunate)

![image](https://user-images.githubusercontent.com/44614862/95141680-ab5bbd80-0726-11eb-96d0-e234682cb921.png)

Works great :star2: The 25 lines of edits allow the datatype to work. ESLint is also happy.

**Test 3**: Writing the 25 lines of edits in index.d.ts and leaving the original JSX typings alone (ideal)

Note that you'll have to type some characters and/or save to trigger ESLint to update.

![image](https://user-images.githubusercontent.com/44614862/95141980-6d12ce00-0727-11eb-8d6f-8109110f5e36.png)

Lots of red! All the elements are valid to TypeScript (as in, hovering on them shows the correct type) but to ESLint they're supposedly "any"

---

Note that the edits are pretty much exactly the same in tests 2 and 3. 

I didn't paste my ESLint config since it's a big long but it's the standard one I use in all JSX projects... https://github.com/heyheyhello/sinueux-typescript-eslint/blob/work/.eslintrc.json

tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Node",
    "noEmit": true,
    "strict": true,
    "esModuleInterop": true,
    "pretty": true,
    "jsx": "preserve",
    "jsxFactory": "h"
  }
}
```

**Expected Result**

I expect ESLint's type aware linting to agree with TypeScript (or the TypeScript Language Server, whichever is giving me the valid type popups in VSCode)

**Actual Result**

ESLint returns: `Unsafe return of an any typed value eslint@typescript-eslint/no-unsafe-return`

It's possible that ESLint is right and they are "any" but it doesn't look like it from the tooltips displayed when hovering JSX elements. They seem to have the right type.

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.3.0` |
| `@typescript-eslint/parser`        | `4.3.0` |
| `TypeScript`                       | `4.0.3` |
| `ESLint`                           | `7.10.0` |
| `node`                             | `14.2.0` |

**Comment by bradzacher** [comment]
I'm unable to repro

![image](https://user-images.githubusercontent.com/7462525/95146494-d1875a80-0732-11eb-8f64-93fe6eba3091.png)

**Comment by heyheyhello** [comment]
That's strange. I'll play around with it. It looks like the Test 3 declaration isn't even being applied else `HTMLAttributes` would have `AllowSubject` applied and you wouldn't have that `<input value` error... Could you try removing the JSX lines from `sinueux/h/index.d.ts`? It's possible that for some reason that's taking priority.

![image](https://user-images.githubusercontent.com/44614862/95149809-b40abe80-073b-11eb-907c-d2fb6647a0fa.png)

**Comment by bradzacher** [comment]
same same - no change.
Would you mind putting the exact repro on a branch to make it easier to sync up?

**Comment by heyheyhello** [comment]
I just tossed up exactly what I have but I'll check it out into a new folder / clean clone

**Comment by heyheyhello** [comment]
![image](https://user-images.githubusercontent.com/44614862/95150878-1ebcf980-073e-11eb-8be2-c92056846334.png)

Not sure how to make it more reproducible. Is running ESLint from the CLI also having no errors?

**Comment by heyheyhello** [comment]
Hey I made some pushes. Not exactly happy with it. Maybe it would be easier to just copy/paste the 900 lines and tell other devs to do the same... I feel like I've been fighting the TS compiler for too long and now the code is confusing.

However :rainbow: the issue went away... or happens very intermittently. Still, I think the pushes I just made are a bit less hacky so hopefully less likely to cause this ESLint issue.

:shrug:

**Comment by bradzacher** [comment]
So generally this lint rule will misfire when the instance of TS we run cannot figure out the types.
This can happen for a number of reasons like:
- you've made changes that we can't pick up.
- you've got a misconfiguration
  - vscode is often able "work around" these because it has many, many mechanisms built into it.
- something isn't installed correctly (missing types, missing package, ...)

In this instance looking at your setup, you've essentially manually created a monorepo:
https://github.com/heyheyhello/sinueux-typescript-eslint/blob/work/package.json#L10

This is likely a problem for our tooling because of various limitations that mean we can't detect changes directly outside of the tsconfig.

I would suggest using [project references](https://www.typescriptlang.org/docs/handbook/project-references.html) here to create an explicit relationship between the two "projects" (`/src` and `/sinneux`).
That way TS can inform us of that relationship and we can watch appropriately.

I don't have much more advice for you here as I can't repro / investigate it.

**Comment by heyheyhello** [comment]
That's interesting I didn't even think of that. Thanks for the tip and looking into this. I'll checkout project references and otherwise try to not make a monorepo by accident.

I'm going to go back to the drawing board on the JSX typings but I don't think it's ESLint fault that things are confusing. Namespaces are difficult.

I'll close the issue. Thanks again!
