### ISSUE TITLE
documentation issue: broken "Getting Started" links on npmjs.com

### ISSUE THREAD

**Issue by uchilaka** [typescript-eslint/typescript-eslint#2641]
There's an issue with the library page on npmjs.com. The **Getting Started** links here are broken, returning a text plain 404 when hit: https://www.npmjs.com/package/@typescript-eslint/eslint-plugin

**Comment by bradzacher** [comment]
Duicate of https://github.com/typescript-eslint/typescript-eslint/issues/2310
