### ISSUE TITLE
[@typescript-eslint/no-use-before-define] `import React from 'react';` marked as error in TSX/JSX file

### ISSUE THREAD

**Issue by zaneclaes** [typescript-eslint/typescript-eslint#2646]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

My problem is very similar to [this issue](https://github.com/typescript-eslint/typescript-eslint/issues/2502), but none of the fixes work for me. I will instead paste my actual config files, rather than the minimal.

```node
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint', 'eslint-plugin-react', 'eslint-plugin-react-hooks'],
  extends: [
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
    'prettier',
    'prettier/@typescript-eslint',
  ],
  rules: {
    'no-use-before-define': [0],
    '@typescript-eslint/no-use-before-define': [1],
    'indent': ['error', 2],
    'linebreak-style': ['error', 'unix'],
    'quotes': ['error', 'single'],
    'semi': ['error', 'always'],
  },
  env: {
    amd: true,
  },
  parserOptions: {
    project: './tsconfig.json',
    tsconfigRootDir: __dirname,
  },
};

```

```TS
import React from 'react';
```

```
{
    "compilerOptions": {
        "target": "es6",
        "allowJs": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "noEmit": true,
        "jsx": "preserve",
        "lib": ["es2015", "dom"],
        "skipLibCheck": false,
        "baseUrl": "./src"
    },
    "include": ["src"]
}
```

**Expected Result**

No warning should be emitted.

**Actual Result**

```
 Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define
```

**Additional Info**

As you can see from the rules, I did implement @linonetwo 's solution [here](https://github.com/typescript-eslint/typescript-eslint/issues/2502#issuecomment-689595020), but it did not fix the warnings. The warnings are thrown by `@typescript-eslint/no-use-before-define` (NOT the core package), so I don't think that's the problem.

I started with version(s) `4.0.0`. Then I tried version(s) `4.1.0`. Then I tried installing the latest alpha. However, there is a seems to be a problem with the latest alpha; the package requirements mismatch:

```
npm WARN @typescript-eslint/eslint-plugin@4.4.1-alpha.2 requires a peer of @typescript-eslint/parser@^4.0.0 but none is installed. You must install peer dependencies yourself
```

(even though I have `@typescript-eslint/parser@^4.4.1-alpha.2`, installed to match, per the docs).

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.4.1-alpha.2` |
| `TypeScript`                | `4.0.3` |
| `ESLint`                    | `6.8.0` |
| `node`                      | `12.18.3` |

**Comment by bradzacher** [comment]
Could you please confirm that there is exactly 1 version of of our tooling installed?
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#how-do-i-check-to-see-what-versions-are-installed

**Comment by zaneclaes** [comment]
@bradzacher thanks for the quick response, and good thought. I didn't consider that `react-scripts` would interfere :( It's been a long time since I've dealt with node packages. Is there not a way to force the version resolution with `npm` rather than `yarn`? I'm pretty deep down the rabbit-hole of using the latest versions already, and would hate to have to downgrade.

**Comment by bradzacher** [comment]
not easily with `npm` AFAIK.
you can try using `react-scripts@next` which is a preview of their v4 release and is pinned against v4 of our packages.
