### ISSUE TITLE
Rule proposal: support "named-parameter-patterns", guard against "primitive obsession"

### ISSUE THREAD

**Issue by fkirc** [typescript-eslint/typescript-eslint#2658]
Unlike many other languages, TypeScript does not support "named parameters".
But fortunately, there exist so-called "named-parameter-patterns" that rely on regular JS-objects: https://medium.com/better-programming/named-parameters-in-typescript-e32c763d2b2e
I use those patterns everywhere because of the following advantages:

- Better readability: I can see the meaning of function-parameters without navigating to function-definitions.
- Better maintainability: I can expand or shrink function-parameters without changing every callsite. Likewise, I can pass entire argument-objects throughout multiple wrapper-functions without repeating myself.
- Less bugs: With named parameters, it is less likely to accidentally confuse multiple parameters of the same type (e.g. a wrong order of arguments).
- Thanks to [shorthand property names](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Property_definitions) in ES6, those "named-parameter-patterns" are possible with very little overhead.

Therefore, to promote "named-parameter-patterns", I propose the following rule:

**Forbid functions that satisfy all of the following conditions:**

- **(1.) There exist two or more _adjacent_ parameters of the exact same type.**
- **(2.) There exist three or more parameters in total.**

For example, the following function would be invalid according to this rule:

```TypeScript
function confusingFoo(p1: string, p2: string, p3: string) {}
```

In contrast, the following improved function would be valid:

```TypeScript
function maintainableFoo(args: { p1: string, p2: string, p3: string }) {}
```

**Backwards compat:**

Since this is highly breaking, this is a rule that I would definitely not enforce for huge legacy codebases.
Nevertheless, I believe that such a rule would be great for new TypeScript-code.

**Comment by bradzacher** [comment]
To ensure I understand.

You're saying you want a rule that errors on this code:
```ts
function foo(p1: string, p2: number, p3: string) {}
```
And instead wants you to use:
```ts
interface FooArgs {
  p1: string;
  p2: number;
  p3: string;
}
function foo({ p1, p2, p3 }: FooArgs) {}
```

Am I correct?

**Comment by fkirc** [comment]
To make this more convenient, the rule might provide an optional quickfix that converts `foo(string, string, string)` into `foo({ string, string, string }`.
Although this might seem like a lot of overhead, I observed that this pattern makes it a lot easier to add or change parameters later on.

**Comment by bradzacher** [comment]
cool - was just double checking I understood correctly.

> whereas others work with inline-types

This does not do what you think it does.
```ts
function maintainableFoo({ p1: string, p2: string, p3: string }) {}
```
This code does not define a destructured object with 3 properties of type `string`.
Instead it defines an untyped destructured object and assigns all 3 properties to the variable `string`. I.e. it's equivalent to:
```ts
function maintainableFoo({ p1, p2, p3 }) {
  let string = p1;
  string = p2;
  string = p3;
}
```

This is the valid typescript that you want:
```ts
function maintainableFoo({p1, p2, p3}: { p1: string, p2: string, p3: string }) {}
```
Which is why I hesitate to objectively recommend this pattern. There's a non-trivial effort in duplicating and maintaining the types.

I think the intentions behind this pattern is good, though I don't think that such a lint rule belongs within a general-purpose eslint plugin like this project provides.

**Comment by fkirc** [comment]
This is related to the concept of "primitives obsession", which is a common code smell in many programming languages: https://medium.com/the-sixt-india-blog/primitive-obsession-code-smell-that-hurt-people-the-most-5cbdd70496e9

There will never be an absolute truth for this matter, but I do believe that we should use ESLint to prevent something like `foo(string, string, string, string, string) `.

**Comment by bradzacher** [comment]
> but I do believe that we should use ESLint to prevent something like

Definitely!
For clarity - I'm not suggesting against this rule existing anywhere - it's something easily doable
I'm just saying that I'm not sure if that rule belongs within this eslint plugin.

You could get 99% of the way there with just the core [`max-params`](https://eslint.org/docs/rules/max-params) lint rule.

**Comment by fkirc** [comment]
Thank you for the `max-params` suggestion.
This is helpful, but I still believe that we could improve on that.

Perhaps my proposal is too strict in its current variant, but it could be acceptable in a weaker variant.

For example, let's say that we only produce an error if (1.) two _adjacent_ parameters have the exact same type and (2.) there are _at least three_ parameters in total.
A reason for the "_at least three_" -relaxation is that we might not want to invalidate simple functions like `max(number, number)`. 

If those relaxations are good enough, then we might get something that is acceptable for this ESLint-plugin.

**Comment by fkirc** [comment]
I updated my initial proposal to make it less restrictive.
My fear about external rules is that they will die eventually if there is no maintainer for those packages.
Therefore, if an acceptable rule can be implemented with just a few lines of code, then I would strongly prefer to merge it in this plugin.

**Comment by samuelstroschein** [comment]
@fkirc I am looking for a rule like this. Did you write one for yourself that you can share?

Furthermore, I suspect that this rule can become overly verbose for obvious arguments like `getTranslationForKey(key: string)`.  

Maybe add that the first argument can be positional? 
```typescript
function foo(a: string, args: { b: string, c: number}  ) {}
```
`a` can be positional 
`b` and `c` (the second argument) must adhere to the named parameter pattern

**Comment by safareli** [comment]
I think what we need is a rule that can be used to restrict having N number of subsequent positional arguments of same type. and if this rule has blacklist/whitelist of those types you can configure it to be activated only on primitives or on all types with some exceptions maybe..

**Comment by JoshuaKGoldberg** [comment]
Heyall, I'm going to close this issue as non-actionable **in this repository**. We keep our rules generally to _TypeScript-specific_ best practices _applicable to most projects_. And while at least bradzacher and I agree with the idea of this rule (and would likely turn it on in many of our own projects!), it's looking like more of a stylistic opinion than universal best practice.

Supporting evidence: since this issue was filed over a year and a half ago, only four people have said anything in favor of it.

You the user can always use the APIs documented & referenced in https://typescript-eslint.io/docs/development/custom-rules to make this rule yourself. If you publish your rule on npm and it becomes popular, we'd be very open to re-opening this issue. Cheers! ❤️
