### ISSUE TITLE
Rule proposal: No implicit recursion

### ISSUE THREAD

**Issue by fkirc** [typescript-eslint/typescript-eslint#2664]
For production code, I use recursion only in rare circumstances.
If I do use recursion, then I want to make it as explicit as possible to alert the reader.
On the flip side, in most of the cases, my recursive calls are just bugs that I accidentally produced with auto-completion.
To catch such typing bugs, I propose the rule **no-implicit-recursion**.

This rule flags all recursive calls as invalid, except of those calls that are marked with an `eslint-disable-line`.
This rule should help in both cases of recursion:

- Detect buggy recursions that were caused by auto-completion or similar mistakes.
- Flag legitimate recursions to make complex control-flows easier to read.

**Comment by bradzacher** [comment]
There doesn't seem to be anything typescript specific in this request. Would be better suited for the core eslint repository.

**Comment by fkirc** [comment]
> There doesn't seem to be anything typescript specific in this request. Would be better suited for the core eslint repository.

That's right, but I think that core ESLint is in "maintenance-only-mode". 

According to their issue templates, they have the following requirements:

`<!-- New rules must be related to ECMAScript features added within the last 12 months -->`

This means that they want to stay modern, but they do not really bother about bugs that developers discover in the wild.

Ultimately, I am seeking a place for "easy, but valuable rules" that do not necessarily need to be compatible with legacy code.

**Comment by fkirc** [comment]
According to https://eslint.org/blog/2020/05/changes-to-rules-policies, ESLint is definitely not a place for rule proposals.

Writing a plugin might be doable, but I fear that plugins with only a single trivial rule will just die because the long-term maintenance isn't good enough.

**Comment by bradzacher** [comment]
This plugin isn't the place for this rule.
We are looking for rules related to typescript features, or extensions to the core eslint rules so they understand typescript features (/ improved with type-information).
A rule that's just lints general purpose javascript features isn't the right fit for this project..

There are plenty of other "catch-all" plugins that this could belong in eg - https://github.com/sindresorhus/eslint-plugin-unicorn.
