### ISSUE TITLE
Running into a lint issue when I try to import a ''ts" in a .js file

### ISSUE THREAD

**Issue by lvdang** [typescript-eslint/typescript-eslint#2676]
Running into a lint issue when I try to import a ''ts" in a .js file. Declaring the ending extension works but not declaring will not.

e.g.
![Screen Shot 2020-10-14 at 3 06 29 PM](https://user-images.githubusercontent.com/7051557/96051137-c2d62d00-0e2f-11eb-9e23-5a2d9d1b2567.png)

e.g. Declaring with 'import {getTid} from 'utils/tid.ts' works

**Comment by bradzacher** [comment]
https://github.com/benmosher/eslint-plugin-import/blob/HEAD/docs/rules/extensions.md
