### ISSUE TITLE
new rule `no-unused-declaration` to highlight or remove unused type declarations

### ISSUE THREAD

**Issue by muuvmuuv** [typescript-eslint/typescript-eslint#2689]
I could not find a GH template for asking for new rules, so I hope it is OK asking here. 

In [ESLint someone made the effort](https://cartant.github.io/tslint-etc/#no-unused-declaration) to create a rule that removes or highligts unused type declarations. I think this would fit pretty good in TS-ESLint as well. So it is easier to find obsolete declarations or auto remove them if required.

My current use-case is that I am creating types through `graphql-code-generator` which adds all types (10k lines of code) the API is exposing but I don't need all of those and it makes my interface file a real mess. With this auto-fixing-rule I could reduce the mess there and automated the beautification process after the generation.

**Comment by bradzacher** [comment]
`no-unused-vars` will already do this.

Or are you talking checking exports to see if they're used outside the file?

**Comment by muuvmuuv** [comment]
Oh you are correct, I forgot that I added `/* eslint-disable */` at the beginning of the file. But I cannot see its beeing removed with `--fix`, maybe this can be made an option for the `no-unused-vars` rule. 

Checking if they are used outside file would be pretty awesome but this may require more work I guess.

**Comment by bradzacher** [comment]
`no-unused-vars` does not have a fixer on purpose.

Many people configure their ides with autofix on save. If `no-unused-vars` had a fixer, then it would continually delete your in-progress variables. This has significant chance to irreparably break code (eg if there is a function call with a side-effect that's assigned to an unused variable, deleting it means you lose the side-effect).

There will never be a fixer added for this reason.

For checking usage across files, see https://github.com/typescript-eslint/typescript-eslint/issues/371
