### ISSUE TITLE
[naming-convention] Support distinct convention for react function components

### ISSUE THREAD

**Issue by ethanresnick** [typescript-eslint/typescript-eslint#2692]
[I didn't see an issue template for feature requests, so apologies in advance if I missed that.]

Essentially: React, especially with hooks, strongly encourages users to declare their components as functions rather than classes. However, React also requires component names be PascalCase for them to be rendered in JSX. Often, naming a function PascalCase is a style-guide violation, as PascalCase is reserved for classes, and it's nice to have a visual distinction between things you can `new` and things you can't.

What I'd like is the ability to define a special naming convention rule just for react components, so that they can be PascalCase without other functions only being allowed to be camelCased. Supporting a configuration like this would make it much easier to use the same naming-convention in backend-only and frontend-only projects, and wouldn't require giving a PascalCase carve-out to other functions that aren't react components.

My proposal would be to identify as a react component any single argument function where the argument is called `props`, which is obviously a crude heuristic but would probably get 85% of the way there. Another option might be to allow the user to provide an esquery selector to identify what's a react component.

**Comment by bradzacher** [comment]
See discussion in #2607

**Comment by bradzacher** [comment]
> My proposal would be to identify as a react component any single argument function where the argument is called props

It's a _very_ common practice to destructure the properties parameter, which would break your heuristic as the parameter now has no name.

**Comment by ethanresnick** [comment]
Thanks for pointing me to that; missed it somehow. I'll continue the conversation there.
