### ISSUE TITLE
[method-signature-style] breaks method overloads (duplicate identifiers)

### ISSUE THREAD

**Issue by tao-cumplido** [typescript-eslint/typescript-eslint#2706]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/method-signature-style": ["error", "property]
  }
}
```

```TS
type Foo = {
   x(a: string): number;
   x(): void;
}
```

When using `eslint --fix` the above code will break.

**Expected Result**

Not sure actually, maybe still report but don't fix. Or an option to ignore method overloads?

**Actual Result**

```ts
type Foo = {
   x: (a: string) => number;
   x: () => void;
}
```

`Duplicate identifier 'x'.(2300)`

`Subsequent property declarations must have the same type.  Property 'x' must be of type '(a: string) => number', but here has type '() => void'.(2717)`

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.5.0` |
| `@typescript-eslint/parser`        | `4.5.0` |
| `TypeScript`                       | `3.9.7` |
| `ESLint`                           | `7.12.0` |
| `node`                             | `14.14.0` |

**Comment by bradzacher** [comment]
I'm unable to repro this against master.
In master this autofixes to
```ts
interface Foo {
  x: ((a: string) => number) & (() => void);
}
```

We have passing tests which confirm this:
https://github.com/typescript-eslint/typescript-eslint/blob/343d20db23a1640e3bca8cf52b7db1fa46e092e6/packages/eslint-plugin/tests/rules/method-signature-style.test.ts#L228-L283

Likely you have multiple versions of our tooling installed.
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#how-do-i-check-to-see-what-versions-are-installed

If not, please create a repro repo to help investigate.

**Comment by tao-cumplido** [comment]
Thanks for the reply. I investigated the problem and it seems it only happens with `type` but not with `interface`. Sorry for the mistake in the initial report.

Specifically, I noticed this in a `.d.ts` file, somethings like this:
```ts
declare const Foo: {
   x(a: string): number;
   x(): void;
}
```

**Comment by bradzacher** [comment]
The rule currently only does the correct autofix for interface body.
https://github.com/typescript-eslint/typescript-eslint/blob/e01204931e460f5e6731abc443c88d666ca0b07a/packages/eslint-plugin/src/rules/method-signature-style.ts#L122-L129

should be a simple fix. happy to accept a PR
