### ISSUE TITLE
[return-undefined] rule from TSLint

### ISSUE THREAD

**Issue by PRR24** [typescript-eslint/typescript-eslint#2730]
Please implement [return-undefined] rule from TSLint (or similar) to avoid errors like
```js
function addOnlyPositive(a: number, b: number): number {
    if (b < 0) return; // Typically appears as a part of incorrectly implemented error handling and hides well in black box testing
    a += b;
    return a;
}

function noReturn(a: number, b: number): void {
    if (b < 0) return null;
    a += b;
}
```
Problem can be slightly mitigated with [consistent-return], but if another return line does not exist or does match, it will not trigger.

May be have the unified solution with #2425 (?)

Thank you.

**Comment by bradzacher** [comment]
For the first case - you don't need a lint rule - [TS will error on this](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQwCaoPJgDYE8AKcAzjLAG4CmAFMgFyJggC2ARhQE4A0iL9jrHAJR9mbdogDeAKESzEMYIiotEAHkQAGQYnYUoIdmADciAPSnEAFVwAHCogDk4VBWAwwFVA-lEGcKChEJADmYMgs2PZQcIhQtvYO-GIOAHQycsiIANQAvDxG6bK6+oYoBQC+QA).

An existing rule like [`consistent-return`](https://eslint.org/docs/rules/consistent-return) will get you the majority of the way there.

**Comment by PRR24** [comment]
Found out that I didn't get the error from tsc because of strictNullChecks was off. If turned on, tsc will start outputting errors.
