### ISSUE TITLE
Rule proposal: disallow duplicate union and intersection types

### ISSUE THREAD

**Issue by remcohaszing** [typescript-eslint/typescript-eslint#2738]
I would like to propose a new rule: `no-duplicate-union-intersection`.

This rule reports duplicates in unions and intersections. The autofixer will remove all duplicates, keeping the first one.

The following lines will be reported:

```ts
type A = 1 | 2 | 3 | 1;
type B = 'foo' | 'bar' | 'foo';
type C = A | B | A | B;
```

This will be autofixed to:

```ts
type A = 1 | 2 | 3;
type B = 'foo' | 'bar';
type C = A | B;
```

The rule won’t try to resolve references. This may be an addition for later.

If this is accepted, I’m willing to implement this.

**Comment by bradzacher** [comment]
I've thought about doing this in the past!
Definitely would be a good rule to have

**Comment by kenkozheng** [comment]
Sonarqube has this rule `Union and intersection types should not be defined with duplicated elements`.
And I think it's a good rule to have in eslint.

Hope to get it soon.

**Comment by michaelenglo** [comment]
What is the status of this issue? I'm interested to contribute, perhaps by trying to implement this rule.

**Comment by bradzacher** [comment]
Everything in this project is community maintained! This issue has been open for 2 months and nobody's mentioned they're working on it - so it's safe to assume nobody is.

Happy to accept a PR!

**Comment by remcohaszing** [comment]
I started an implementation, but lost interest at some point. The basics are pretty simple, but I can into more and more corner cases. I.e. type literals need to be compared, call signatures need to be compared, nested unions and intersections should be handled.

I might pick it up at some point, but I won’t complain if someone else wants to fix this issue. :)

**Comment by michaelenglo** [comment]
Cool! I'll see if I can send something EOW. :)

**Comment by remcohaszing** [comment]
I noticed the [sort-type-union-intersection-members](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/sort-type-union-intersection-members.md) rule was added. It might me more worthwile to drop my merge request and reuse some logic of that rule, since basically the difference between the two is that `sort-type-union-intersection-members` should change the order based on the the comparator result, and `no-duplicate-union-intersection` should remove one entry if the comparator returns 0.

**Comment by sajikix** [comment]
What is the status of this issue? (Is anyone working on this issue?)
I would like to implement this rule if no one is working on this issue.

**Comment by bradzacher** [comment]
Currently open for anyone to work on - just needs a champion to implement it!

**Comment by EvgenyOrekhov** [comment]
This is available in [eslint-plugin-sonar](https://github.com/un-ts/eslint-plugin-sonar)  (`no-duplicate-in-composite` rule)
