### ISSUE TITLE
[array-type] --fix doesn't parenthesize ReadonlyArray fixes correctly

### ISSUE THREAD

**Issue by weswigham** [typescript-eslint/typescript-eslint#2741]
**Repro**

```TS
type Q = ReadonlyArray<object>[]
```

**Expected Result**

```TS
type Q = (readonly object[])[];
```

**Actual Result**

```TS
type Q = readonly object[][];
```

**Additional Info**

The lack of parenthesis change which level of array is considered `readonly` (it goes from the inner array to the outer one), causing a meaningful semantic difference in the resulting code.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.5.0` |
| `@typescript-eslint/parser`        | `4.5.0` |
| `TypeScript`                       | `nightly development version - 11/5/2020` |
| `ESLint`                           | `7.12.1` |
| `node`                             | `10.22.0` |

**Comment by bradzacher** [comment]
should be pretty straightforward to check if the parent is a `TSArrayType` and wrap it with parens in that case.

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/array-type.ts#L255-L266
