### ISSUE TITLE
TypeError parsing simple function with argument

### ISSUE THREAD

**Issue by tao-cumplido** [typescript-eslint/typescript-eslint#2742]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```TS
import { parse } from '@typescript-eslint/parser';
parse('function foo(a) { return a; }');
```

**Expected Result**

No error, I guess.

**Actual Result**

```
Uncaught TypeError: Cannot read property '0' of undefined
    at FunctionScope.isValidResolution (node_modules\@typescript-eslint\scope-manager\dist\scope\FunctionScope.js:28:101)
    at resolve (node_modules\@typescript-eslint\scope-manager\dist\scope\ScopeBase.js:186:27)
```

**Additional Info**

This seems to happen whenever the function references the argument in its body. The error doesn't occur when I pass the `range: true` option.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.6.1` |
| `TypeScript`                | `4.0.5` |
| `ESLint`                    | `7.12.1` |
| `node`                      | `14.14.0` |

**Comment by bradzacher** [comment]
What is your use-case? Are you just trying to get the AST?
If so - then you should use `typescript-estree` to do your parsing instead.

**Comment by tao-cumplido** [comment]
I am experimenting with a rule to detect commented code. It uses the parser from the eslint rule context to parse the source file with comments uncommented. So I don't actually need the AST at all, I just need to know whether parsing succeeds or not. I could of course load typescript-estree if the parser is @typescript-eslint/parser but I'd rather not. For now I get by by passing the `range: true` option. I just expected valid code with default options to not throw.

https://github.com/tao-cumplido/eslint-plugin-style/blob/main/src/rules/experimental/no-commented-code.ts

**Comment by bradzacher** [comment]
Yeah it should - we should really change the defaults to match what ESLint passes in to make it easy.
Though as a consumer you should likely do the same:
https://github.com/eslint/eslint/blob/82669fa66670a00988db5b1d10fe8f3bf30be84e/lib/linter/linter.js#L636-L645

For example - this is how `eslint-plugin-import` does the same sort of work to call the user's parser:
https://github.com/benmosher/eslint-plugin-import/blob/adbced7cde1818f23677384868e17380b886683e/utils/parse.js#L13-L48
