### ISSUE TITLE
[ban-types] it is not possible to extendDefaults and remove one of the default type

### ISSUE THREAD

**Issue by paztis** [typescript-eslint/typescript-eslint#2743]
In the ban-types rule, I want to keep all your default values but only remove the case

  '{}': {
    message: [
      '`{}` actually means "any non-nullish value".',
      '- If you want a type meaning "any object", you probably want `Record<string, unknown>` instead.',
      '- If you want a type meaning "any value", you probably want `unknown` instead.',
    ].join('\n'),
  },

For now, I'm force to set **extendDefaults** to false and redefine everything.
I've not found any way to xtends it and remove one of the cases.

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md#options

> The values can be... false to specifically disable this type...

**Comment by paztis** [comment]
Ah cool. Let me test it

Le ven. 6 nov. 2020 à 16:39, Brad Zacher <notifications@github.com> a
écrit :

**Comment by paztis** [comment]
ok well works.
I close the defect
