### ISSUE TITLE
[naming-convention] Cannot disable individual rule options

### ISSUE THREAD

**Issue by ab-pm** [typescript-eslint/typescript-eslint#2755]
I configured the naming-convention rule to my needs in some quite detailed way:
```js
{
  "rules": {
	'@typescript-eslint/naming-convention': [
		'error',
		{ 'selector': 'default', 'format': ['camelCase'] },
		{ 'selector': 'variable', 'format': ['camelCase'] },
		{ 'selector': 'property', 'format': ['camelCase', 'snake_case'] },
		{ 'selector': 'variable', 'modifiers': ['const'], 'format': ['camelCase', 'UPPER_CASE'] },
		{ 'selector': 'parameter', 'format': ['camelCase'], 'leadingUnderscore': 'allow' },
		{ 'selector': 'memberLike', 'modifiers': ['private'], 'format': ['camelCase'], 'leadingUnderscore': 'require' },
		{ 'selector': 'typeLike', 'format': ['PascalCase'] },
	],
  }
}
```
(and there's probably more to come).

However, in some parts of my I will need some exceptions. Let's say in code that deals with the database, I want to allow snake_case property names in object literals. Prior to #1318, I could just disable the camelCase-rule for that section or file, and I would still get checks from e.g. member-naming.

However, with `naming-convention` I see no way to do that. If I turn off the rule, *all* my selector options are disabled at once. Am I missing something that I could do about this?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.7.0` |
| `@typescript-eslint/parser`        | `4.7.0` |
| `TypeScript`                       | `3.9.4` |
| `ESLint`                           | `7.13.0` |
| `node`                             | `14.15.0` |

**Comment by bradzacher** [comment]
There is no way to do that. The downside of making this all one rule is that you can't disable pices of it.

Your options are:
- use eslint overrides to specify different combinations of naming for different paths https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns
- use cascading configs to specify different combinations of naming for different folders https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy

**Comment by ab-pm** [comment]
Yeah, having different rules for different files is an option, but it still requires repeating all the options of the rule even if the change is minor. Or am I missing something about how options get merged (not overwritten) when combining multiple rule configs from multiple places?

What I would love to see is
```js
/* eslint-disable @typescript-eslint/naming-conventions/objectProperty */ 
// eslint-disable-next-line @typescript-eslint/naming-convention/const-variable
```
and have this ignore the `format` for options for the `objectProperty`/`variable` selectors and `const` modifier respectively.

Is this possible or would that require upstream changes in eslint?

**Comment by bradzacher** [comment]
It would take vast changes in both ESLint and the rule.
It's not really possible to do for various reasons.

> but it still requires repeating all the options of the rule even if the change is minor

if you're using `.eslintrc.js`, then it's all javascript. extract config to a module and `require` it around the place to compose you config as appropriate.
