### ISSUE TITLE
[triple-slash-reference] TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by timplateus** [typescript-eslint/typescript-eslint#2762]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

#### .eslintrc.json
```JSON
{
  "root": true,
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": [
          "tsconfig.json"
        ],
        "createDefaultProgram": true
      },
      "extends": ["plugin:@typescript-eslint/recommended"]
    }
  ]
}
```
#### .ts
```TS
/// <reference types="@types/googlemaps" />
import DistanceMatrixResponse = google.maps.DistanceMatrixResponse;
```
#### tsconfig.json
```JSON
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "src",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "es2020",
    "moduleResolution": "node",
    "importHelpers": true,
    "resolveJsonModule": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": false,
    "strictInjectionParameters": true,
    "preserveWhitespaces": true
  }
}
```

### Expected Result

Evaluate the file, and pass/reject the rule

### Actual Result

Unhandled Exception (see below). Note that disabling all rules (//eslint-disable-next-line) for the problematic line did not stop the exception from occurring.
```
TypeError: Cannot read property 'value' of undefined
Occurred while linting corrupted-file.ts:2
    at ...\node_modules\@typescript-eslint\eslint-plugin\dist\rules\triple-slash-reference.js:67:53
    at Array.forEach (<anonymous>)
    at hasMatchingReference (...\node_modules\@typescript-eslint\eslint-plugin\dist\rules\triple-slash-reference.js:66:24)
    at TSImportEqualsDeclaration (...\node_modules\@typescript-eslint\eslint-plugin\dist\rules\triple-slash-reference.js:88:21)
    at ...\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (...\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (...\node_modules\eslint\lib\linter\node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (...\node_modules\eslint\lib\linter\node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (...\node_modules\eslint\lib\linter\node-event-generator.js:297:14)
Process finished with exit code -1
```
### Additional Info

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.7.0` |
| `@typescript-eslint/parser`        | `4.7.0` |
| `TypeScript`                       | `4.0.5` |
| `ESLint`                           | `7.13.0` |
| `node`                             | `14.15.0` |

**Comment by timplateus** [comment]
To resolve this issue, I disabled this rule in .eslintrc.json:
```JSON
{
...
"extends": ["plugin:@typescript-eslint/recommended"],
"rules": {
  "@typescript-eslint/triple-slash-reference": "off"
}
...
}

**Comment by bradzacher** [comment]
Easy bug to fix

https://github.com/typescript-eslint/typescript-eslint/blob/afa7900285ad6d31d2acaff0107fbd19bad4ff06/packages/eslint-plugin/src/rules/triple-slash-reference.ts#L84

This line makes the assumption that `.moduleReference` is always a `TSExternalModuleReference`.
In this instance it's not as it's a `TSQualifiedName`.

Happy to accept a PR

**Comment by deepenpatel3** [comment]
I would like to take it, I have never contributed to **open source** projects. Can you please share some insights on how to solve it?

**Comment by ddubrava** [comment]
> I would like to take it, I have never contributed to **open source** projects. Can you please share some insights on how to solve it?

- How to raise a PR and validate your changes - [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/master/CONTRIBUTING.md#pull-requests)
- Tool which will show you the AST. Select `@typescript-eslint/parser` - [AST explorer](https://astexplorer.net/)
- [ESLint selectors](https://eslint.org/docs/developer-guide/selectors)

**Comment by ddubrava** [comment]
@deepenpatel3 👋 are you working on the issue?
