### ISSUE TITLE
Which set of rules apply to typed linting?

### ISSUE THREAD

**Issue by millsp** [typescript-eslint/typescript-eslint#2777]
Is there a file that describes the rules that apply to typed linting?

https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md

Thanks!

**Comment by bradzacher** [comment]
Have you had a look at the plugin documentation?
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules

**Comment by millsp** [comment]
I thought there would be a `type`-only set of rules, separated from code-related rules. I'll be able to look through the list you gave. Thanks :+1: Cheers

**Comment by bradzacher** [comment]
We don't have a separate table - they're intermingled, but they're marked with a ☁️
