### ISSUE TITLE
[no-loop-func] Global constants are no treated as constant

### ISSUE THREAD

**Issue by ab-pm** [typescript-eslint/typescript-eslint#2780]
**Repro**
```js
{
  "rules": {
    '@typescript-eslint/no-loop-func': 'error',
    'no-loop-func': 'off', // using typescript-eslint/no-loop-func
  }
}
```

```ts
describe('in a jest test', () => {
  it('that uses a loop', () => {
    for (const x of ['values']) {
      function checkX(val: string): void {
        expect(val).toBe(x);
      }
      ['ooh'].forEach(checkX);
    }
  });
})
```

**Expected Result**

The code should lint just fine. `expect` is a constant, declared in `node_modules/@types/jest`:
```ts
declare const expect: jest.Expect;
```
Notice it works if I alias `expect` into a `const` before the loop.

**Actual Result**

EsLint complains about the `checkX` function:

> Function declared in a loop contains unsafe references to variable(s) 'expect'. *(eslint@typescript-eslint/no-loop-func)*

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.7.0` |
| `@typescript-eslint/parser`        | `4.7.0` |
| `TypeScript`                       | `3.9.4` |
| `ESLint`                           | `7.13.0` |
| `node`                             | `14.15.0` |

**Comment by bradzacher** [comment]
This is a bug in the  base rule.
https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tbG9vcC1mdW5jOiBbXCJlcnJvclwiXSAqL1xuXG5kZXNjcmliZSgnaW4gYSBqZXN0IHRlc3QnLCAoKSA9PiB7XG4gIGl0KCd0aGF0IHVzZXMgYSBsb29wJywgKCkgPT4ge1xuICAgIGZvciAoY29uc3QgeCBvZiBbJ3ZhbHVlcyddKSB7XG4gICAgICBmdW5jdGlvbiBjaGVja1godmFsKSB7XG4gICAgICAgIGV4cGVjdCh2YWwpLnRvQmUoeCk7XG4gICAgICB9XG4gICAgICBbJ29vaCddLmZvckVhY2goY2hlY2tYKTtcbiAgICB9XG4gIH0pO1xufSkiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19

Please raise a bug in eslint core.

**Comment by ab-pm** [comment]
Are you saying that [`typescript-eslint/no-loop-func`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/no-loop-func.ts) is a fork of the eslint core rule, and you can only merge this once it's fixed in upstream?

Also I'm not sure I understand how this rule is implemented and where it gets to know about global variables. I would have *expected* the core rule to complain about the `expect()` call since it doesn't know where/how it is declared, and that *only* with typescript support the rule could actually figure out it's a constant from the declaration in `@types/jest.d.ts`.

**Comment by bradzacher** [comment]
Looking into this more - it's not a bug.
It's working as intended.

The lint rule doesn't know about the `expect` variable.
You need to tell eslint about global variables separately.

https://eslint.org/docs/user-guide/configuring#specifying-globals

**Comment by ab-pm** [comment]
Yes, exactly, I wouldn't expect eslint core to know about the global `expect` variable. However, Typescript *does* know about the variable and that it is a `const`ant (even though I don't understand perfectly how it does), so I was suggesting to extend the typescript-eslint rule to utilise this knowledge.

**Comment by bradzacher** [comment]
Sorry. I misunderstood your original post.

No, we aren't going to do that.
Adding that information involves consuming type information, which is a breaking change to a rule.

In its more general form, this change could be applied to the scope analysis ahead of the rule. However changes like this are sweeping and expensive. Type information is calculated lazily, so any time we need to ask TS for more, it takes time and slows down the lint.

As eslint already has a mechanism for declaring globals (and only a few rules that need it), it isn't a good tradeoff.

I would suggest using `eslint-plugin-jest`, which provides a list of globals for you to turn on.

**Comment by ab-pm** [comment]
Thanks, this sounds like a reasonable workaround. I understand the tradeoff, breaking changes are bad. Maybe an idea for a next major release…
