### ISSUE TITLE
[no-unused-vars] "exported" declaration ignored for interface containing a function returning the interface itself

### ISSUE THREAD

**Issue by marekdedic** [typescript-eslint/typescript-eslint#2782]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

See https://gist.github.com/marekdedic/d5f1c0ef082159c9641176d367738b15 and run `npm run lint`

**Expected Result**

In the repro, I would expect to get no errors for the `exported.ts` file and 3 `no-unused-vars` errors for `no-exported.ts`.

**Actual Result**

In the repro, I get 1 error for the `exported.ts` file (specifically for the non-empty interface) and 3 `no-unused-vars` errors for `no-exported.ts`.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.8.1` |
| `@typescript-eslint/parser`        | `4.8.1` |
| `TypeScript`                       | `4.0.5` |
| `ESLint`                           | `7.13.0` |
| `node`                             | `14.15.1` |

Let me know if any additional info is needed ;)

**Comment by bradzacher** [comment]
This happens because currently the rule does out-of-band reporting for interfaces that reference themselves but are otherwise unused.

Will be fixed by #2768
