### ISSUE TITLE
Rule proposal: Collapsible if-statements

### ISSUE THREAD

**Issue by sindresorhus** [typescript-eslint/typescript-eslint#279]
The rule should identify nested if-statements that can be combined into one.

Would be useful if the rule could be auto-fixable.

>
> Instead of:
> 
> ```ts
> if (foo) {
>     if (bar) {
>         // ...
>     }
> }
> ```
> 
> Prefer:
> 
> ```ts
> if (foo && bar) {
>     // ...
> }
> ```

Relevant TSLint issue: https://github.com/palantir/tslint/issues/4427

**Comment by mysticatea** [comment]
I don't think that this fits this plugin because this is not a TypeScript-specific matter.

**Comment by armano2** [comment]
rules like this are implemented for tslint and eslint already by @SonarSource

https://www.npmjs.com/package/tslint-sonarts
https://github.com/SonarSource/eslint-plugin-sonarjs

**Comment by mysticatea** [comment]
Maybe [no-lonely-if](https://eslint.org/docs/rules/no-lonely-if) is a good place for this.

**Comment by JamesHenry** [comment]
I'm going to close this as this is appropriately being developed as a community plugin.

Thanks all 🙏
