### ISSUE TITLE
no-undef: eslint ignores @types

### ISSUE THREAD

**Issue by NikolayMakhonin** [typescript-eslint/typescript-eslint#2799]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

https://github.com/NikolayMakhonin/eslint-bugs

```
npm run build
```
typescript compilation is OK

```
npm run lint
```

```
  1:21  error  'chai' is not defined  no-undef

? 1 problem (1 error, 0 warnings)
```

**tsconfig.json**
```json
{
    "compilerOptions": {
        "target": "ESNext",
        "lib": ["dom", "esnext"],
        "typeRoots": [
            "node_modules/@types"
        ]
    },
    "include": [
        "**/*.ts"
    ]
}
```

eslint ignores `typeRoots`. tslint was work fine with it.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.8.1` |
| `@typescript-eslint/parser`        | `4.8.1` |
| `TypeScript`                       | `4.1.2` |
| `ESLint`                           | `7.14.0` |
| `node`                             | `12.17.0` |

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors

Please read the FAQ before you tick the "I have read the FAQ" box.
