### ISSUE TITLE
error: Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.

### ISSUE THREAD

**Issue by ljwagerfield** [typescript-eslint/typescript-eslint#2811]
**Repro**

Run `eslint . --ext .js,.jsx,.ts,.tsx` on the following codebase:

**/.eslintrc.yaml**
```YAML
root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
env:
  node: true
```

**/tsconfig.json**
```JSON
{
  "compilerOptions": {
    "lib": ["es2019"],
    "module": "commonjs",
    "target": "es2019",
    "strict": true,
    "esModuleInterop": true,
    "allowJs": true,
    "checkJs": true,
    "baseUrl": "./"
  },
  "include": ["./**/*"],
  "exclude": ["./node_modules/**/*"]
}
```

**/package.json**
```JSON
{
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "4.8.2",
    "@typescript-eslint/parser": "4.8.2",
    "eslint": "7.14.0",
    "typescript": "4.1.2"
  }
}
```

**/src/Foo.ts**
```typescript
export default function foo(): string {
  return "";
}
```

**/src/Foo.js**
```typescript
export default function foo() {
  return "";
}
```

**Expected Result**

`eslint` to succeed.

**Actual Result**

`eslint` fails due to `Foo.js` not being included within the project (even though it's covered by my `"include"` settings):

```
/Users/lawrence/Repositories/playground/eslint-js-example/src/Foo.js
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/Foo.js.
The file must be included in at least one of the projects provided

✖ 1 problem (1 error, 0 warnings)
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.8.2` |
| `TypeScript`                | `4.1.2` |
| `ESLint`                    | `7.14.0` |
| `node`                      | `12.19.0` |

**Comment by bradzacher** [comment]
This is a known problem with typescript and files named the same.
Nothing we can do about it unfortunately!

Please checkout the readme - this is explicitly called out!

https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#parseroptionsproject

> TypeScript will ignore files with duplicate filenames in the same folder (for example, src/file.ts and src/file.js). TypeScript purposely ignore all but one of the files, only keeping the one file with the highest priority extension (the extension priority order (from highest to lowest) is .ts, .tsx, .d.ts, .js, .jsx). For more info see #955.

**Comment by ljwagerfield** [comment]
Thank you for the fast response 😄
