### ISSUE TITLE
with the new changes in 4.9.0 - eslint 5.x.x is not supported anymore

### ISSUE THREAD

**Issue by gaurav5430** [typescript-eslint/typescript-eslint#2837]
- [x] I have tried restarting my IDE and the issue persists.
- [ ] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**
The code changes in 
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/no-unused-vars.ts#L7

no longer work with eslint 5.x.x as this folder structure is only available from eslint 6.0.0

This breaks eslint with a not able to read file error when @typescript-eslint/recommended is used.

the package.json still specifies ^eslint 5.0.0 as a valid peer dependency

**Comment by bradzacher** [comment]
how come you're using ESLint v5? The last v5 release was over 18 months ago.
Since then 2 majors have been released.

There's also only one officially supported node version overlap between the two - node v10.
You should really upgrade.

**Comment by gaurav5430** [comment]
Thanks,
I did upgrade. 
Was just trying this out with an older setup and got this issue.
Mentioned it here because the peerDeps are incorrect in package.json and should be fixed?

**Comment by bradzacher** [comment]
Should be and will be with the next major.
Those that are on v5 are less likely to upgrade versions of plugins (because they're on an old version of eslint).
There are very, very, very few users still on v5 - so I've been directing people to upgrade.
