### ISSUE TITLE
Rule proposal: Prefer `.includes()`

### ISSUE THREAD

**Issue by sindresorhus** [typescript-eslint/typescript-eslint#284]
This rule should prefer `.includes()` over `.indexOf()` when checking for existence. This would apply to the following types: `String#includes`, `Array#includes`, `TypedArray#includes`, `Buffer#includes`.

`.includes()` cases:

* `'foobar'.indexOf('foo') !== -1`
* `'foobar'.indexOf('foo') != -1`
* `'foobar'.indexOf('foo') > -1`
* `'foobar'.indexOf('foo') >= 0`

<sub>These would negate `.includes()`:<sub>
* `'foobar'.indexOf('foo') == -1`
* `'foobar'.indexOf('foo') === -1`
* `'foobar'.indexOf('foo') < 0`

It would also be useful to catch cases where `String#includes()` would be better than a regex: `/\r\n/.test(foo);` => `foo.includes('\r\n');`

---

This was originally [proposed](https://github.com/eslint/eslint/issues/4209) for inclusion in ESLint, but declined for lack of type knowledge in JS.

**Comment by mysticatea** [comment]
I will work on this.

I think that I'd like to separate this to two rules:

- `prefer-array-includes` ... for `Array`, `ReadonlyArray`, typed arrays, and child classes of those (`Buffer` extends `Uint8Array`). `Array#includes` has been added in ES2016.
- `prefer-string-includes` ... for strings. This address regular expressions as suggested. `String#includes` has been added in ES2015.

Thoughts?

**Comment by mysticatea** [comment]
After re-tought, I will go with one rule:

- `prefer-includes` ... for all types which have both `indexOf` method and `includes` method, if the parameter types of those methods are same completely, the rule suggests to use `includes` method.
