### ISSUE TITLE
[@typescript-eslint/indent] Rule ignores FunctionDeclaration object

### ISSUE THREAD

**Issue by chaosflaws** [typescript-eslint/typescript-eslint#2843]
- [ not applicable, tested on command line ] I have tried restarting my IDE and the issue persists.
- [ X ] I have updated to the latest version of the packages.
- [ X ] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JS
module.exports = {
    env: {
        browser: true,
        es2021: true
    },
    extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:@typescript-eslint/recommended-requiring-type-checking'
    ],
    parser: '@typescript-eslint/parser',
    parserOptions: {
        project: 'test.tsconfig.json',
        ecmaVersion: 12,
        sourceType: 'module',
        tsconfigRootDir: 'D:/IDEA-Projekte/cplace-eslint/test'
    },
    plugins: [
        '@typescript-eslint'
    ],
    rules: {
        // JavaScript
        'indent': 'off',

        // TypeScript extensions
        '@typescript-eslint/indent': ['error', 4, {FunctionDeclaration: {parameters: 'first'}}],
    }
}
```

```TS
class TestClass {
    constructor(private readonly firstArg,
                private readonly secondArg,
                private readonly thirdArg) {
    }
	
    testMethod(private readonly firstArg,
               private readonly secondArg,
               private readonly thirdArg) {
    }
}
```

TSConfig:
```JS
{
  "compilerOptions": {
    "baseUrl": ".",
    "lib": ["ES2018", "DOM"],
  },
  "include": [
    "./**/*.ts"
  ]
}
```

**Expected Result**

no problems reported by ESLint

**Actual Result**

ESLint reports indent errors for the constructor and the test method:
```
  3:1   error    Expected indentation of 8 spaces but found 16  @typescript-eslint/indent
  4:1   error    Expected indentation of 8 spaces but found 16  @typescript-eslint/indent
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.9.0` |
| `@typescript-eslint/parser`        | `4.9.0` |
| `TypeScript`                       | `4.1.2` |
| `ESLint`                           | `7.14.0` |
| `node`                             | `v12.16.2` |

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/1824

Please use the search next time.

**Comment by chaosflaws** [comment]
I did find that issue, but there was nothing related to this specific bug there, so I decided to create a new one.

Anyway, as the only fix seems to be "we need to rewrite the whole rule", I agree this can be closed.
