### ISSUE TITLE
[no-unused-vars] eslint 5 don't have "eslint/lib/rules/utils/ast-utils"

### ISSUE THREAD

**Issue by kingback** [typescript-eslint/typescript-eslint#2849]
https://github.com/typescript-eslint/typescript-eslint/blob/fed89f24ebe42a6412f0eb19949d5d4771656189/packages/eslint-plugin/src/rules/no-unused-vars.ts#L7

@typescript-eslint/eslint-plugin: 4.9.0
eslint: 5.16.0

eslint 5 don't have "eslint/lib/rules/utils/ast-utils" <https://unpkg.com/browse/eslint@5.16.0/lib/rules/>

![image](https://user-images.githubusercontent.com/471003/101114451-741d6600-361c-11eb-980c-f7f27618a904.png)

**Comment by bradzacher** [comment]
You should upgrade to  ESLint 6+.
ESLint v5 is now well over a year old.
