### ISSUE TITLE
[no-unused-vars] false positive for callback params

### ISSUE THREAD

**Issue by deser** [typescript-eslint/typescript-eslint#2857]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**
![image](https://user-images.githubusercontent.com/3010698/101503617-54bb6b80-3983-11eb-81f4-a93812fdd073.png)
![image](https://user-images.githubusercontent.com/3010698/101503790-8af8eb00-3983-11eb-8faa-aed280e35155.png)

**Expected Result**
Do not blame in these cases. 

**Actual Result**
Blames in the cases.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.9.1` |
| `@typescript-eslint/parser`        | `4.9.1` |
| `TypeScript`                       | `4.1.2` |
| `ESLint`                           | `7.15.0` |
| `node`                             | `2.19.1` |

**Comment by deser** [comment]
Running eslint through npm gives the same errors:
`"eslint": "cross-env NODE_OPTIONS='--max-old-space-size=4096' node_modules/.bin/eslint . --ext .ts,.tsx,.js",`

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-am-using-a-rule-from-eslint-core-and-it-doesnt-work-correctly-with-typescript-code

You're using the wrong rule.
