### ISSUE TITLE
[new rule] await async call

### ISSUE THREAD

**Issue by sbdchd** [typescript-eslint/typescript-eslint#2858]
Somewhat related to:
- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/await-thenable.md
- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/return-await.md
- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/require-await.md
- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/promise-function-async.md

Essentially the following would be invalid:

```ts
function foo(): Promise<number>;
foo();
```

instead a user would have to write:

```ts
function foo(): Promise<number>;
await foo();
```

or 

```ts
function foo(): Promise<number>;
foo().then(...);
```

I think this only really applies to calling the function and not assigning the result, because a user could want to await the `Promise` later in a `Promise.all` or something.

related: https://github.com/Instagram/Fixit/blob/068f87518e164289bd6a2dcfb62c9df5575ab9e6/fixit/rules/await_async_call.py

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md

This rule will do what you want.

**Comment by sbdchd** [comment]
Thanks, works like a charm!
