### ISSUE TITLE
Massive Slowdown

### ISSUE THREAD

**Issue by Goldziher** [typescript-eslint/typescript-eslint#2878]
- [ X ] I have tried restarting my IDE and the issue persists.
- [ X ] I have updated to the latest version of the packages.
- [ ] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

Hi there, so I know this is listed in the FAQs but the level of slowdown I am seeing is really way worse than the build times. I originally reported this in the vscode-eslint repo - https://github.com/microsoft/vscode-eslint/issues/1055, but the issue apparently is not vscode specific.

Please see this repo for a reproducible case: https://github.com/Goldziher/dtsgenerator

**Comment by bradzacher** [comment]
Have you got some more information?

If the expectation is that I will clone your repo and run everything myself - that's fine, but it means that as a _volunteer maintainer_, it is going to stay on the backlog for some time until I have the time to do that.

The more information you can put down in the issue the better.
***Help me to help you.***

What slowdown are you seeing?
How much?
In what usages?
How many files do you have?

More information means I can help you via comments, which means I can help you sooner.

**Comment by ThaJay** [comment]
For me, with eslint typescript and vscode, every time I create or rename a file in this project, "code actions on save, eslint" goes from 0-2 seconds to 2-10 minutes. The project I am working on also has circulair dependencies but I'm refactoring them in phases.

If I reload the workspace or restart vscode and let it sit for a few minutes to fully complete initialization, saving is fast again.

This is our `.eslintrc.js` (without our rules):
```
module.exports = {
  root: true,
  extends: [
    '@react-native-community',
    'plugin:jest/recommended',
    'plugin:jest/style',
    'plugin:import/errors',
    'plugin:import/typescript',
    'prettier',
    'prettier/@typescript-eslint',
  ],
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint', 'jest', 'import'],
  parserOptions: {
    project: './tsconfig.json',
    tsConfigRootDir: '.',
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  plugins: ['@typescript-eslint', 'jest', 'import'],
  env: {
    'jest/globals': true,
    'react-native/react-native': true,
  },
  settings: {
    'import/parsers': {
      '@typescript-eslint/parser': ['.ts', '.tsx'],
    },
    'import/resolver': {
      typescript: {
        alwaysTryTypes: true,
      },
      node: {
        extensions: ['.js', '.ts', '.tsx', '.d.ts'],
        paths: ['node_modules/', 'node_modules/@types/'],
      },
    },
  }
};
```

**Comment by bradzacher** [comment]
@ThaJay if that is your eslint config, then you need to take a look at our FAQ. I can straight away see a number of items in your config that are known to be slow.

https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#my-linting-feels-really-slow

**Comment by Goldziher** [comment]
@bradzacher , i understand please give me any debug steps that you would like me to follow.  The slow down is significantly bigger than the build time. Here are the eslint configs:

```
{
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:import/errors",
        "plugin:import/warnings",
        "plugin:import/typescript",
        "plugin:prettier/recommended",
        "prettier/@typescript-eslint"
    ],
    "plugins": ["sort-imports-es6-autofix"],
    "env": {
        "node": true,
        "es2021": true
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "project": "./tsconfig.json"
    },
    "rules": {
        "@typescript-eslint/no-unused-vars": [
            "error",
            { "argsIgnorePattern": "^_" }
        ],
        "@typescript-eslint/no-use-before-define": 0,
        "@typescript-eslint/no-explicit-any": 0,
        "@typescript-eslint/prefer-optional-chain": 2,
        "@typescript-eslint/prefer-nullish-coalescing": 2,
        "@typescript-eslint/no-floating-promises": [
            "error",
            { "ignoreIIFE": true, "ignoreVoid": true }
        ],
        // recommended configs from the typescript eslint repo - turn off conflicting import rules
        "import/named": 0,
        "import/namespace": 0,
        "import/default": 0,
        "import/no-named-as-default-member": 0
    },
    "overrides": [
        {
            "files": ["**/*_test.ts"],
            "env": {
                "mocha": true
            },
            "rules": {
                "@typescript-eslint/ban-ts-comment": 0,
                "@typescript-eslint/no-empty-interface": 0,
                "@typescript-eslint/no-explicit-any": 0,
                "@typescript-eslint/no-floating-promises": 0,
                "@typescript-eslint/no-implied-eval": 0,
                "@typescript-eslint/no-misused-promises": 0,
                "@typescript-eslint/no-unsafe-assignment": 0,
                "@typescript-eslint/no-unsafe-call": 0,
                "@typescript-eslint/no-unsafe-member-access": 0,
                "@typescript-eslint/no-unsafe-return": 0,
                "@typescript-eslint/no-var-requires": 0,
                "@typescript-eslint/unbound-method": 0
            }
        }
    ]
}
```

Prettier does not seem to be the culprit, neither does the import plugin as far as i can tell. I also followed the FAQ section.

**Comment by bradzacher** [comment]
"significantly bigger" doesn't mean too much as it's relative and subjective.
Eg 3 is significantly bigger than 1, but 103 is not significantly bigger than 101. 

Hard numbers.

What is the total lint time with / without type aware linting?

> What slowdown are you seeing?
> How much?
> In what usages?
> How many files do you have?

**Comment by Goldziher** [comment]
Thanks for the lesson. I am in fact aware of my semantics. I said that the lint time is significantly bigger than the build time. By how much - well saving a single file can take 3-4 minutes, whereas building the entire thing about 15 seconds.

**Comment by ThaJay** [comment]
@bradzacher
- prettier is fast for me.
- The rule import/no-cycle could perhaps affect load times after changing file structure, but I believe this issue was already present before I added this rule.

**Comment by lazyd3v** [comment]
Got this (or very similar) problem recently when doing migration from JS to TS in our monorepo. Solved it by renaming `tsconfig.json` in the root to `tsconfig.base.json` and inside `packages/some-package/.eslintrc.json` specified `parserOptions.project` as `path.resolve(__dirname, './tsconfig.json')`.

Initially I had `parserOptions.project` set to `./tsconfig.json` and I guess in this case eslint tried to run tsc on the entire monorepo instead of one package which affected the performance.

**Comment by rdsedmundo** [comment]
I'm experimenting the same problem lately. In my experience the usability has severely decreased in the last 6 months or so, it used to way better to use the TS + ESLint combo.

In my case, for instance, I keep getting `eslint@typescript-eslint/no-unsafe-call` for functions that are written in TypeScript, if I run `ESLint` in the CLI it returns no errors, or if I use "Go to definition" in the function VSCode finds it perfectly and instant.

**Comment by rdsedmundo** [comment]
@lazyd3v thanks much for sharing that! It was exactly my case (monorepo), changing it to `.base` improved the performance considerably.

**Comment by bradzacher** [comment]
You mean like the getting started guide which includes docs for setting up a monorepo?

https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/MONOREPO.md

**Comment by rdsedmundo** [comment]
I'm still facing performance issues, especially with the type-checking rules.

I noticed a pattern, let's say I have this:

**A.ts** (open in the editor)
```ts
import { callable } from './B';

callable();
```

**B.ts** (not open in the editor)
```ts
export const callable: Callable = () => null;
```

**global.d.ts** (auto-generated, not open in the editor)
```ts
type Callable = any;
```

If I run a script that auto-generates `global.d.ts` which changes `global.d.ts#Callable` to `() => string`, it takes at least 25+ seconds for vscode-eslint to stop throwing `Unsafe call of an any typed value. eslint@typescript-eslint/no-unsafe-call`. However, if I open `global.d.ts` after the auto-generation it realizes way faster (<5s) that the definition has changed. This use case of auto-generation is for using GraphQL codegen.

A similar scenario is for definitions that are changed in subpackages of the workspace that are imported from other packages, it takes way too long for the linter to understand that something has changed, almost as if it was cached.

Is there a better way to improve this other than keeping the files open?

**Comment by bradzacher** [comment]
If the file is open and you switch to it - the ESLint extension will trigger a lint of the file as soon as it changes.
This causes ESLint to immediately pass us the file contents, which we can physically replace in the TS program and trigger an immediate rerun.

If the file is not open, then we will not know about the change until you change another file that has an open editor.
This is why there is a delay. You run the script, you wait for it to finish, you then make changes, then a lint run starts, then we can update the TS program.

We do not attach file system watchers for various reasons, so we cannot react to disk changes in real time.
