### ISSUE TITLE
[no-var-requires] Exceptions for asset `require` via bundler

### ISSUE THREAD

**Issue by thw0rted** [typescript-eslint/typescript-eslint#2896]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended"
    ],
}
```

```TS
const IMG_PATH = require("./images/myImage.png");
```

**Expected Result**

Many TS users pass their code through a bundler like Webpack, which makes related non-code assets available using `require`.  While it's possible to configure Typescript to support syntax like `import IMG_PATH from "./images/myImage.png"`, transpiling down to a `require()` call that is eventually handled by the bundler, this does not work out-of-the-box.  It can also be confusing, since the `import` statement can never be passed through to the browser the way a real ES6 `import` would be.  It's better to keep the delineation between module `import` and resource `require` clear.

**Actual Result**

The current implementation of this rule flags `require` calls like this regardless of what's being `require`'d.  Where possible, the rule should allow this construct to be used when the path specifier ends with a non-code extension.  This could be implemented as a blocklist, where specifiers with (no extension, ".js(x)", ".ts(x)") must use `import`, or an allow-list, where the rule can be configured with extensions that may use `require` without `import`.

I'm not sure how to handle the case where the specifier is not a static string.  Ideally, this would be replaced with a call to `require.context(...)` to explicitly constrain which assets are considered by the bundler, and that would avoid triggering the rule in the first place.  I can't think of a way to tell the difference between a call like `const myModule = require("./modules/" + modName)`, which should be converted to `const myModule = await import("./modules/" + modName);`, and `const myImage = require("./images/" + imgName + ".svg");` which should not, because it looks like TC39 is not planning on supporting `import()` syntax for non-module assets.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.11.0` |
| `@typescript-eslint/parser`        | `4.10.0` |
| `TypeScript`                       | `4.1.3` |
| `ESLint`                           | `7.15.0` |
| `node`                             | `12.7.0` |

**Comment by bradzacher** [comment]
If you believe for your usecase that you want to use var requires, then you should not use the rule.

---

> It can also be confusing, since the import statement can never be passed through to the browser the way a real ES6 import would be

This is an implementation detail. Engineers needn't worry about how imports get executed and by what.

You could also argue that your `import` statements are also confusing as they don't get executed by the browser - they get transpiled to a `require` statement with a specially generated module ID instead of an import.

The two are ultimately the same, and an engineer needn't think any more about it than "if I import this thing, the infrastructure will make it work for me"

> ends with a non-code extension

What is a non-code extension?
Sure there's the standard ones, but what about non standard?
There's a reason that our tooling avoids doing inspection of extensions where possible.

As you've mentioned, dynamic requires also make this an **impossible** problem to solve.

**Comment by thw0rted** [comment]
My `import` statements are passed through to the browser because I'm not down-leveling.  The bright-line difference that I'm trying to establish is that there is a path, today, to emit `import` statements *for code* that the browser understands and executes.  (For `import`, it has to be an ES6 module, for `import()`, it can be an ES6 module or plain JS.)  On the other hand, when the specifier points to anything else, both types of `import` fail, and as far as I've been able to find, there are no plans to change that.

This neatly divides the use cases we used to have for `require` into two groups: code, and assets.  That's what I was trying to explain in the OP.  TC39 has made it clear that they *do* want the engineer to think about what's being loaded, because they make loads for the one class (code) work completely differently from loads for the other class (assets).  There are discussions I've participated in about, for example, supporting `import()` from JSON -- they're against it -- but I'm having trouble finding a reference at the moment.

To be clear, I wasn't proposing a change to the default behavior of the rule, I'd just like to have the option of telling it that certain classes of `require` are allowed to be var-assigned.  Then, I just have to configure the infrastructure so that the linter agrees with the bundler -- if I set up Webpack rules for `\.(png|jpe?g|svg)$`, then I could have my `.eslintrc.json` configured with `"@typescript-eslint/no-var-requires": ["warn", {"assetExtensions": ["png", "jpg", "jpeg", "svg"]}]`, or something like that.  (Perhaps a regex would be better than an array of strings?)

I understand that I could disable the rule completely, but I do want to forbid, for example, `const moment = require("moment")`.  Catching that (mis)use has value to me, but perhaps not so much that I want every asset reference to require an inline `@eslint-disable` annotation.

**Comment by bradzacher** [comment]
Have you tried using import requires?

`import foo = require('./image.png')`

**Comment by thw0rted** [comment]
That syntax gives an error:

> Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.ts(1202)

I'd like to stick with `module: "esnext"`, so that means no import-require.

I was able to make a wildcard module declaration (`declare module "*.png" { const value: string; export=value;`), which makes `import IMG_PATH from "./images/my-image.png"` work, but IMHO this makes it less clear that I'm asking my bundler to process an asset at build time, rather than asking the user-agent to import a script at runtime.

Still, if the team decides that customization for this rule isn't desirable, it's probably the direction I'll wind up going.

**Comment by bradzacher** [comment]
> this makes it less clear that I'm asking my bundler to process an asset at build time, rather than asking the user-agent to import a script at runtime

I don't understand the distinction.

If you're running your code through a bundler (like webpack) then all your code is being bundled together into a single JS file.

Which means that your bundler is translating
`import foo from './foo'` to `const foo = _getModule($ID)` (eg some utility function it controls) within the transpiled output bundle.

That is - unless of course you aren't bundling your JS into a single file, and are literally just letting the browser waterfall load your JS files as it discovers they are needed.

**Comment by thw0rted** [comment]
Sorry, just realized I'd left this open.

You make a good point about how the bundler handles modules.  I like to think of "clean" ES6 modules as special but eventually they're going to wind up in a bundle, as you say.  The config that I happen to be using -- kitted out with the right loaders, the right rules, etc -- will treat assets differently and they won't wind up in a bundle, but with a different config they could.

I guess the distinction I wanted to hold out is that, while asset `import` or `require` eventually *has* to be transformed by the bundler -- into a URL, if the asset is deployed separately, or into a `_getModule`-type memory lookup if the asset is inlined -- the ES6 module `import` *could* be left alone, for "waterfall load" as you say.  Keeping the var-require syntax to denote that difference was something I imposed on myself, I guess.
