### ISSUE TITLE
[scope-manager] should ignore `parserOptions.ecmaVersion`

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#2900]
See discussion in https://github.com/yannickcr/eslint-plugin-react/issues/2882

There are only two cases in this project that we honour `parserOptions.ecmaVersion`, and both are in `scope-manager`:
https://github.com/typescript-eslint/typescript-eslint/blob/498f397ff3898dde631f37311615b555f38a414e/packages/scope-manager/src/ScopeManager.ts#L78-L84

These usages were brought across when I forked `eslint-scope`. 

However in the context of TS scope analysis - the `ecmaVersion` makes zero sense.
TS will never treat your code as if it's ES5 or lower - it is always (syntactically and semantically) "ESNext".

Whilst other parts of the ecosystem respects them - and they should continue to - our parser and scope analyser should (like TS itself) always treat code as if it is ESNext in terms of language features.

**Comment by JoshuaKGoldberg** [comment]
#5889 is merged into #5886; closing this issue now accordingly. It'll be released as a part of the v6 major release.
