### ISSUE TITLE
[sort-type-union-intersection-members] Can null and undefined be sorted separately from other keywords?

### ISSUE THREAD

**Issue by jgeurts** [typescript-eslint/typescript-eslint#2918]
Sometimes null gets lost with other types when it's sorted with the rest of the keyword types. Moving `null` and `undefined` to their own group would allow them to be sorted independently to other types.

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/sort-type-union-intersection-members": "error"
  }
}
```

**Current Behavior**

```TS
function foo(input: number | null | string | undefined) { ... }
```

**Proposed Behavior**

```TS
function foo(input: number | string | null | undefined) { ... }
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.12.0` |
| `@typescript-eslint/parser`        | `4.12.0` |
| `TypeScript`                       | `4.1.3` |
| `ESLint`                           | `7.17.0` |
| `node`                             | `12.20.1` |

**Comment by bradzacher** [comment]
technically this is a breaking change, but because we have *just* released it, and we release every week (and I know adoption is usually slow), I'm okay with it.
