### ISSUE TITLE
Export RuleFixer from the main entry point

### ISSUE THREAD

**Issue by rafaelss95** [typescript-eslint/typescript-eslint#2931]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**
Currently to import `RuleFixer` we should use a deep import:

```ts
import { RuleFixer } from '@typescript-eslint/experimental-utils/dist/ts-eslint';
```

It would be nicer if we could just do:

```ts
import { RuleFixer } from '@typescript-eslint/experimental-utils';
```

cc @JamesHenry (https://github.com/angular-eslint/angular-eslint/pull/260#discussion_r554944759).

I also noticed that there are some other interfaces used [here](https://github.com/angular-eslint/angular-eslint/blob/942fde16f4c204d46fb994df180337a655a87e14/packages/utils/src/test-helpers.ts#L1-L7), for example, that could be exported properly.

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/experimental-utils` | `4.3.0` |
| `TypeScript`                            | `4.0.3` |

**Comment by bradzacher** [comment]
You can just do

```ts
import { TSESLint } from '@typescript-eslint/experimental-utils';

type T = TSESLint.RuleFixer;
```

We won't be exporting it from the root as it makes it unclear what it is used for. The namespace bundles all ESLint types.
