### ISSUE TITLE
[ban-types] Allow use `object` in higher order component 

### ISSUE THREAD

**Issue by retyui** [typescript-eslint/typescript-eslint#2936]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/ban-types": ["error"]
  }
}
```

- [Playground...](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=49&pc=1#code/JYWwDg9gTgLgBAJQKYEMDGMA0BvOBhCcCAOyWJgBUBPMJOAXzgDMpC4AiKVDdgbgCh+MGnQDqwGAAsAMhBQATYMQDmABVZgAznAC8cXME2yFS5QC44AIwgQANqmIMB-APQu4ASTgwoVJPLgAA2x6QMwggHlLACskDDCg5DRoeQAeTR9TTABXYgBrYggAd2IAPkC4cMts+EM4Qvgi6DzmaDgACQi8TVd3duK4FAA3CGAAqTqwVkt7EHCiiUkIGrgkTVslGABaRU0UGaQAfjhBN1X1zZ3Dffst0gAPbY3SOAABYVpNNChgMG2154wFyWFDELYfNb8Ji5DDAEhwBZSYyKFSpdQQLSrR5keTaCAxOIwUoACgIRFI5AsZMgFMoIjRGk0pQAlPp+HBvCI4OitOIkXIUcpdNzGXAAGRwPkyAWmHmaZwc6HEWHwqXI0zEgxGGUqcIAOgNUwx2noFjlap1ylZ2HZHLgXBg2SgjkM6pUcGOxNtdrgqUUQ1KbuUBr1qRc-tK3rgrIsXp9HNS1JIZHg2BDxKNmJQ2jlzMYLkjPuZAg59EEHIdTscFpMKgEZd6cC2zZbrbb7Y7ndbgk2SCgTHQdDlbI52U0fc0HlxFgAglAoCgqOlMipSvXBMliBk4ABZKhJ2nCzVwMcTqcms2M1k6Uoj+1IR3OuBxu1+4ABqMc7CnqCT3F6kAUDAYliR-P9r1vF9419TQwFBOA8iQKgdG-cdfynehSlQs95HoMNYNBQt42ZPMozDCNbWLfh6GcTdtz3A8UxrQVhURaVa2UYkGMIGkUyo-gkHuSBYDgOj4BgNZ4D0VJuPJJjFiDE80L-TQUIAbQAXUYV1LRQnxsiQfM1wEoToHgMTvEkgAmI9bRk-ceOTcgozA891K0qMzneTQtkE2gMF8+c2i2IIdI4ip5AgNZ6ggeBBMMeB4UCOUKghKMwsFPSoAMssOQLfgqKAA)

```TS
import React,{ ComponentType } from "react";

type WithLoadingProps = { isLoading: boolean };

// I tryed `{}`, `Object`, `Record<string,unknown>` , but is not work for HOCs
// How avoid this problem, without eslint-disable? 

// eslint-disable-next-line @typescript-eslint/ban-types
function withLoading<Props extends object>(Component: ComponentType<Props>) {
  type PropsWithLoading = Props & WithLoadingProps;

  function WithLoading({ isLoading, ...props }: PropsWithLoading) {
    return isLoading ? (
      <div>Loading...</div>
    ) : (
      <Component {...(props as Props)} />
    );
  }

  return WithLoading;
}

// ----------------------------------------

interface Props {
  usersIds: Array<string>;
}

const MyComponent = ({ usersIds }: Props) => {
  return (
    <div>
      {usersIds.map((usersId) => (
        <span key={usersId}>{usersId}</span>
      ))}
    </div>
  );
};

const MyComponentWithLoading = withLoading(MyComponent);

export const test = <MyComponentWithLoading usersIds={[]} isLoading={true} />;
export const test2 = (
  <MyComponent
    usersIds={[]}
    // @ts-expect-error - `isLoading` does not exist on `Props` type
    isLoading={true}
  />
);

```

**Expected Result**

For HOCs case this error isn't relevant

**Actual Result**

Annoying error:
```
ESLint: 
Don't use `object` as a type. The `object` type is currently hard to use ([see this issue](https://github.com/microsoft/TypeScript/issues/21732)). Consider using `Record<string, unknown>` instead, as it allows you to more easily inspect and use the keys.
(@typescript-eslint/ban-types)
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.13.0` |
| `@typescript-eslint/parser`        | `4.13.0` |
| `TypeScript`                       | `4.1.3` |
| `ESLint`                           | `7.17.0` |
| `node`                             | `lts` |

**Comment by bradzacher** [comment]
As mentioned in countless other issues (please use the search).
This rule simply bans types - nothing more, nothing less.

It does not and will not have any form of contextual checks added - because it is literally impossible to correctly handle all cases.

The advice is always the same: if you think you have a valid usage of a type - then feel free to use a disable comment.
