### ISSUE TITLE
[ban-ts-comment] @ts-expect-error ignored/has not effect

### ISSUE THREAD

**Issue by LukeOwlclaw** [typescript-eslint/typescript-eslint#2958]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

`.eslintrc.json`:
```JSON
{
    "parser": "@typescript-eslint/parser",
    "plugins": [
        "@typescript-eslint"
    ],
    "rules": {
        "@typescript-eslint/ban-ts-comment": [
          "error",
          {
            "ts-expect-error": false,
            "ts-ignore": false
          }
        ],
        "@typescript-eslint/naming-convention": [
          "error",
          {
            "selector": "interface",
            "format": [ "PascalCase" ],
            "prefix": [ "I" ]
          }
        ],
        "no-unused-vars": 0
    }
}
```

`JQueryExt.json`:
```TS
// @ts-expect-error: Extending existing interface. Cannot change name using I prefix
interface JQueryStatic {}

// @ts-ignore
interface JQueryStatic2 {}

```
`package.json`:
```
{
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.14.0",
    "@typescript-eslint/parser": "^4.14.0",
    "eslint": "^7.18.0",
    "eslint-config-standard": "^16.0.2",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-react": "7.22.0",
    "typescript": "4.1.3"
  },
  "scripts": {
    "lint": "eslint"
  }
} 
```
Run:

    npm install
    npm run lint JQueryExt.ts

**Expected Result**

No errors because one is expected the other is ignored.

**Actual Result**

    npm run lint JQueryExt.ts
    
    > @ lint D:\temp\eslint-test2
    > eslint "JQueryExt.ts"
    
    
    D:\temp\eslint-test2\JQueryExt.ts
      2:11  error  Interface name `JQueryStatic` must have one of the following prefixes: I   @typescript-eslint/naming-convention
      5:11  error  Interface name `JQueryStatic2` must have one of the following prefixes: I  @typescript-eslint/naming-convention
    
    ✖ 2 problems (2 errors, 0 warnings)
    
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! @ lint: `eslint "JQueryExt.ts"`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the @ lint script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\Luke\AppData\Roaming\npm-cache\_logs\2021-01-21T14_03_48_727Z-debug.log

**Versions**

See ``package.json``.

    node --version
    v12.16.3

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-ts-comment.md#ts-expect-error-ts-ignore-ts-nocheck-ts-check-directives

> A value of true for a particular directive means that this rule will report if it finds any usage of said directive. 

You specifically configured

> "​ts-expect-error​"​: ​false​,

**Comment by LukeOwlclaw** [comment]
I disagree. This is not a "user error".

If configured ``true``, the `ban-ts-comment` kicks in reporting

> Do not use "@ts-expect-error" because it alters compilation errors

I do not want that. I want the `@ts-ignore` line to be allowed. That is why I configured to `false`.

How do I get rid of error "Interface name `JQueryStatic` must have one of the following prefixes: I"?

**Comment by bradzacher** [comment]
No.
`ts-ignore` is for typescript errors.
If you want to ignore eslint reports, you must use an eslint disable comment.

**Comment by LukeOwlclaw** [comment]
So the ignore comment I need is: ` /* eslint-disable @typescript-eslint/naming-convention */`
Thank you so much, @bradzacher! It is so obvious now... 🙈
