### ISSUE TITLE
Add ability to mock return value of `context.getFilename()` when using `TSESLint.RuleTester`

### ISSUE THREAD

**Issue by ericbiewener** [typescript-eslint/typescript-eslint#2974]
This is a feature request.

**Repro**

My custom ESLint rule calls `context.getFilename()` and uses some logic based on the resulting path. When using `TSESLint.RuleTester` to test the rule, however, I don't see a way to mock out what `context.getFilename()` should return.

**Expected Result**

API is available to mock the return value of `context.getFilename()` in tests.

**Actual Result**

`context.getFileName()` outputs the string `<input>`.

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/experimental-utils` | `4.9.1` |
| `TypeScript`                            | `4.1.2` |
| `node`                                  | `14.15.4` |

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/957523c3c0bd92201c3607c21f30ac0d80bcd912/packages/experimental-utils/src/ts-eslint/RuleTester.ts#L15-L18

https://github.com/typescript-eslint/typescript-eslint/blob/498f397ff3898dde631f37311615b555f38a414e/packages/eslint-plugin/tests/rules/no-namespace.test.ts#L56-L65
