### ISSUE TITLE
Add "all" configuration that includes all rules

### ISSUE THREAD

**Issue by emlai** [typescript-eslint/typescript-eslint#298]
For example, eslint has [`eslint:all`](https://eslint.org/docs/user-guide/configuring#using-eslintall), eslint-plugin-react has [`plugin:react/all`](https://github.com/yannickcr/eslint-plugin-react#all).

I propose to add a similar option to typescript-eslint.

**Comment by ldrick** [comment]
Hi, I did some work on this and have three questions left, before opening the PR.
1. What would you expect in all.json, `error` or `warn` for rules, which have `meta.docs.recommended === false`?
2. Would you expect for rules known to rival with eslint (like indent)? Disable eslint rules, like recommended.json?
3. Shall this be used as baseConfig for all.json, like in recommended.json?
```ts
const baseConfig = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    sourceType: 'module',
  },
  plugins: ['@typescript-eslint'],
};
```

**Comment by emlai** [comment]
> 1. What would you expect in all.json, `error` or `warn` for rules, which have `meta.docs.recommended === false`?

I would probably prefer `error` because I don't use `warn`.

> 2. Would you expect for rules known to rival with eslint (like indent)? Disable eslint rules, like recommended.json?

Yes I think disabling the eslint rules would be best because I will probably do that anyway when I notice that the eslint rule doesn't work with typescript.

> 3. Shall this be used as baseConfig for all.json, like in recommended.json?

Probably yes, for consistency.

**Comment by ldrick** [comment]
@emlai Thanks for your feedback, I did 2. and 3. like you said and just thought on having 1. defaulting to `warn` just, because if the rule isn't recommended, it might be not an error, which this rule covers.

**Comment by VincentLanglet** [comment]
@ldrick see https://github.com/typescript-eslint/typescript-eslint/pull/313#discussion_r277016336

All rules should be set as error in the `all` config.
