### ISSUE TITLE
[member-delimiter-style] member-delimiter-style autofixer produces invalid code with {delimiter: 'none'}

### ISSUE THREAD

**Issue by pfgithub** [typescript-eslint/typescript-eslint#2982]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

.eslintrc.json
```JSON
{
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"],
  "rules": {
    "@typescript-eslint/member-delimiter-style": ["warn", {"multiline": {"delimiter": "none"}}]
  }
}
```

test.ts:
```TS
type Test = {
    a: {
        one: 1
    }; b: 2
};
```

`eslint --fix test.ts`

**Expected Result**

Autofix would not be enabled for this comma

```
  4:7  warning  Unexpected separator (;)  @typescript-eslint/member-delimiter-style
```

**Actual Result**

Autofixer created invalid code

```TS
type Test = {
    a: {
        one: 1
    } b: 2
//  ^ 4:6  error  Parsing error: ';' expected
};
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.14.1` |
| `@typescript-eslint/parser`        | `4.14.1` |
| `TypeScript`                       | `4.1.3` |
| `ESLint`                           | `7.18.0` |
| `node`                             | `14.15.3` |

**Comment by tanohzana** [comment]
Hello, I could help with that. I'd need 2 weeks I think 🙂
