### ISSUE TITLE
Documentation: the new `require-array-sort-compare` rule is missing in the overview of rules

### ISSUE THREAD

**Issue by doberkofler** [typescript-eslint/typescript-eslint#299]

**Comment by MayhemYDG** [comment]
#467 has been merged so this is fixed now. CC @bradzacher

**Comment by bradzacher** [comment]
@MayhemYDG - thanks for pinging!

As an FYI - If you add "Fixes #xxx" to your PR description, gitub will auto close the related issue when the PR is merged!
