### ISSUE TITLE
Rule proposal: Ensure special verbs match the type (e.g. `hasName` is boolean or boolean function)

### ISSUE THREAD

**Issue by fregante** [typescript-eslint/typescript-eslint#3032]
Would you find this naming confusing?

```ts
const hasName = 'Federico';
const getName = 'Federico';
```

The first is awkward because `has` implies a boolean type, e.g. `boolean | () => boolean | Promise<boolean>`

The second one is awkward because `get` implies a getter, therefore a `function`, not a string.

Possible "special" verbs:

```ts
is -> bool (or anything that returns/resolves into bool)
has -> bool (or anything that returns/resolves into bool)

get -> function
set -> function
unset -> function
delete -> function
add -> function
remove -> function
destroy -> function
```

Maybe not:

```
clear // this is also an adjective
init // this could also be a noun for "initialization of X", a Promise that resolves with X
```

I think many of the verbs above could be booleans in some cases (e.g. `action({delete: true})`)

**Comment by fregante** [comment]
Another common example I've seen:

```js
function hasTitle(id: number): string | false;
```

Where the function doesn't just check for the `title`, but also returns it. This would be a more appropriate name:

```js
function getTitle(id: number): string | false;
```

Where it returns the `title` as a string or `false` when not found (or `undefined`/`null`, but that's irrelevant here)

**Comment by tao-cumplido** [comment]
wouldn't this fit as an enhancement to `naming-convention`? it seems like it is already possible for variables:
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#enforce-that-boolean-variables-are-prefixed-with-an-allowed-verb

the `types` option is currently not allowed for `function` types but maybe could be added to specify the return type?!

**Comment by bradzacher** [comment]
You *could* get most of the way there, except the rule isn't really designed to take on that sort of negative matching.

I'm not even sure that you could configure it to disallow such names whilst also enforcing a different naming convention.
You probably could figure out a way to do it, but it'd be super complicated config.

TBH I'm not sure if this rule should exist. I don't have any argument against why it shouldn't, but I don't know if it's generic enough to belong in this plugin. 🤷 

I figured we can put it on the backlog and figure that bit out exactly later.
As this project is community maintained, I won't be picking this up myself, but if someone from the community is motivated enough to work on it - we can nut out those details then.

**Comment by JoshuaKGoldberg** [comment]
Following up, we're deprioritizing stylistic rules such as this one. The lack of any engagement on this issue in the past couple of years is a good indication that this should be an external plugin.

You can find our docs on building custom rules here: https://typescript-eslint.io/developers/custom-rules

Cheers!
