### ISSUE TITLE
[typescript-eslint/recommended] in nested directory's config disables rules of parent config

### ISSUE THREAD

**Issue by soryy708** [typescript-eslint/typescript-eslint#3061]
- [✅] I have tried restarting my IDE and the issue persists.
- [✅] I have updated to the latest version of the packages.
- [✅] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

Repro repo: https://github.com/soryy708/typescript-eslint-bug

**Expected Result**

I expect the `no-undef` rule to catch the undefined variable 'a' in both `/index.js` and `/inner/index.ts`

**Actual Result**

`no-undef` rule catches the undefined variable 'a' in `/index.js` but not in `/inner/index.ts`

**Additional Info**

If I comment out the `"extends": ["plugin:@typescript-eslint/recommended"]` in `/inner/.eslitrc` and run linting then the result is as expected. It appears like extending `plugin:@typescript-eslint/recommended` disables the `no-undef` rule.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.15.0` |
| `@typescript-eslint/parser`        | `4.15.0` |
| `TypeScript`                       | `4.1.5` |
| `ESLint`                           | `7.20.0` |
| `node`                             | `14.15.0` |

**Comment by bradzacher** [comment]
Our recommended set turns off rules that are covered by the typescript compiler. This is entirely intentional.

**Comment by soryy708** [comment]
> You can browse the list of rules that are disabled in the project code.
I can, but it implies that the documentation is lacking.

Certain rules getting turned off is unexpected, and can allow a situation where someone thinks they're covered by a certain rule but in practice are not. I think that this can be addressed in one of 3 ways:
1. Don't turn off the rules - can be problematic because some rules don't work on TypeScript sources, which can lead to the linter crashing or hanging or falsely positiving/negativing
2. Emphasize the behavior in the documentation s.t. users are aware of the rules getting turned off
3. Instead of turning the rules off, print to eslint's stdout/stderr a warning that the rule should be off and replaced by the one in @typescript-eslint

**Comment by armano2** [comment]
> Instead of turning the rules off, print to eslint's stdout/stderr a warning that the rule should be off and replaced by the one in @typescript-eslint

we can't do that, as we don't have control over external rules
