### ISSUE TITLE
Error when parsing extends clause with type assertion [rule: constructor-super]

### ISSUE THREAD

**Issue by krisztianb** [typescript-eslint/typescript-eslint#3066]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

In a project I'm using the [TypedEmitter](https://github.com/andywer/typed-emitter) type definitions like this:

```typescript
type SomeClassEvents = {
    beforeChange: (oldVersion: string) => void;
    afterChange: (newVersion: string) => void;
};

export class SomeClass extends (EventEmitter as new () => TypedEmitter<SomeClassEvents>) {
    public constructor() {
        super(); // ERROR: Unexpected 'super()' because 'super' is not a constructor. (eslint:constructor-super)
    }
}
```

If I remove the type assertion in the `extends` clause the error is gone.

I would expect this to work as I'm using `@typescript-eslint/parser` to parse TS files. Maybe I'm wrong here and this has something to do with the rule? I'm not sure. If so, my apologizes. Please point me in the right direction so I can report this elsewhere. Thank you.

```JSON
{
   "parser": "@typescript-eslint/parser",
   "parserOptions": {
      "ecmaFeatures": { "jsx": true },
      "ecmaVersion": 2018,
      "sourceType": "module",
      "project": "tsconfig.json"
   }
}
```

**Expected Result**

No error message when calling `super()` in the code above.

**Actual Result**

The following error is reported by ESLint for the marked line in the code above:

> Unexpected 'super()' because 'super' is not a constructor. (eslint:constructor-super)

**Additional Info**

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.15.1` |
| `TypeScript`                | `4.1.3` |
| `ESLint`                    | `7.20.0` |
| `node`                      | `12.13.1` |

**Comment by bradzacher** [comment]
Highly recommend just not using this rule - it's useless in TS code because TS actively checks your `super` calls (error codes 2335 and 2377).

If you use any of our recommended sets, we disable this rule for that reason.

**Comment by krisztianb** [comment]
Unfortunately I haven't been able to activate the recommended sets as our code produces too many linter errors.

Thanks for the suggestion and the explanation. I'm going to disable the rule for our TS files. :+1:
