### ISSUE TITLE
[member-ordering] Feature request: better distinguishing of "methods" from "fields"

### ISSUE THREAD

**Issue by karptonite** [typescript-eslint/typescript-eslint#3067]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

Member ordering tries to enforce placing class fields before the constructor, and class methods after the constructor. It is smart enough to see a field assigned to an arrow function, and call that a class method, but it is currently not smart enough to do the same with more complicated examples. The ordering below is what member-ordering tries to enforce for the example code.

```JSON
{
  "rules": {
    "@typescript-eslint/member-ordering": ["error"]
  }
}
```

```typescript
import { memoize } from 'lodash-es';

class TestClass {
  private aField = 'foo';
  private aMemoizedFunction = memoize(() => 'result');
  private aFunctionReturnsAnArrowMethod = (() => () => 'bar')();
  constructor() {}
  private anArrowMethod = () => 'result';
  private aMethod() {}
}
```

**Expected Result**

```typescript
import { memoize } from 'lodash-es';

class TestClass {
  private aField = 'foo';
  constructor() {}
  private aMemoizedFunction = memoize(() => 'result');
  private aFunctionReturnsAnArrowMethod = (() => () => 'bar')();
  private anArrowMethod = () => 'result';
  private aMethod() {}
}
```
I would prefer it if `aMemoizedFunction` and `aFunctionReturnsAnArrowMethod` were both treated similarly to `anArrowMethod`. 

**Actual Result**
The rule actually requires `aMemoizedFunction` and `aFunctionReturnsAnArrowMethod` to appear before the constructor, because it doesn't recognize them as functions.

**Additional Info**
Obviously, this would require substantial changes to member-ordering. In particular, you'd need to look at the actual type information, I think, to sort these correctly. `aMemoizedFunction`, in particular, is type `(() => string) & MemoizedFunction`, so the type comparison to correctly ascertain that this functions acts as a method is not super simple. But also note that `aFunctionReturnsAnArrowMethod` has the exact same type signature as `anArrowMethod`.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.15.1` |
| `@typescript-eslint/parser`        | `4.15.1` |
| `TypeScript`                       | `4.0.5` |
| `ESLint`                           | `7.20.0` |
| `node`                             | `14.9.0` |

**Comment by bradzacher** [comment]
It is impossible to know that `memoize()` returns a function without type information.

This rule is intentionally designed to not use type information for numerous reasons.

Adding type information is a significant breaking change that restricts many users from being able to use the rule, which is why we only do it if absolutely necessary.

In this case - I don't think the benefits outweigh the costs.
