### ISSUE TITLE
Alignment with ESTree class-features

### ISSUE THREAD

**Issue by tchetwin** [typescript-eslint/typescript-eslint#3068]
Following the addition of `PrivateIdentifier` in https://github.com/typescript-eslint/typescript-eslint/pull/2933#issuecomment-780769499 there remains another (breaking) change to reconcile `@typescript-eslint/estree` with the ESTree specification, namely: `ClassProperty` -> [`PropertyDefinition`](https://github.com/estree/estree/blob/master/stage3/class-features.md#propertydefinition).

Creating this Issue to track.

**Comment by armano2** [comment]
babel pr: https://github.com/babel/babel/pull/12370

**Comment by bradzacher** [comment]
closing in favour of #3430
