### ISSUE TITLE
[member-ordering] Rule crashes on TSAbstractMethodDefinition

### ISSUE THREAD

**Issue by epmatsw** [typescript-eslint/typescript-eslint#307]
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/member-ordering": 2
  }
}
```

```TS
export abstract class ASDF {
    protected abstract blah() {

    }

    public asdf() {

    }
}
```

**Expected Result**

No crash, maybe an error.

**Actual Result**

```
TypeError: Cannot read property 'replace' of undefined
    at getLowestRank (/node_modules/@typescript-eslint/eslint-plugin/dist/rules/member-ordering.js:271:34)
    at members.forEach.member (/node_modules/@typescript-eslint/eslint-plugin/dist/rules/member-ordering.js:293:43)
    at Array.forEach (<anonymous>)
    at validateMembers (/node_modules/@typescript-eslint/eslint-plugin/dist/rules/member-ordering.js:282:25)
    at ClassDeclaration (/node_modules/@typescript-eslint/eslint-plugin/dist/rules/member-ordering.js:306:17)
    at listeners.(anonymous function).forEach.listener (/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/node_modules/eslint/lib/util/node-event-generator.js:280:22)
```

**Additional Info**

It seems like what's happening is that it's hitting the `Number.MAX_SAFE_INTEGER` case in member-ordering's `getRank` (which has the comment `// shouldn't happen but just in case, put it on the end`). That's because `getNodeType` doesn't handle `TSAbstractMethodDefinition` and returns `null` (it also seems to be missing at least `TSIndexSignature`).

Once the rank is set to `Number.MAX_SAFE_INTEGER`, if an error is triggered, that rank gets passed to `getLowestRank`, which ends up looking at `order[Number.MAX_SAFE_INTEGER]`, which is `undefined`, and then calls `undefined.replace` and crashes.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.4.0` |
| `@typescript-eslint/parser`        | `1.4.0` |
| `TypeScript`                       | `3.3.3` |
| `ESLint`                           | `5.14.1` |
| `node`                             | `10.15.0` |
| `npm`                              | `6.7.0` |

**Comment by milesj** [comment]
Same problem here. I threw this console log in,`console.log({ ranks, target, order, lowest });`, and this is the result. Seems like the ranks number is *way off*.

```
{ ranks: [ 9007199254740991 ],
  target: 11,
  order:
   [ 'public-static-field',
     'protected-static-field',
     'private-static-field',
     'public-instance-field',
     'protected-instance-field',
     'private-instance-field',
     'public-field',
     'protected-field',
     'private-field',
     'static-field',
     'instance-field',
     'field',
     'constructor',
     'public-static-method',
     'protected-static-method',
     'private-static-method',
     'public-instance-method',
     'protected-instance-method',
     'private-instance-method',
     'public-method',
     'protected-method',
     'private-method',
     'static-method',
     'instance-method',
     'method' ],
  lowest: 9007199254740991 }
```

**Comment by epmatsw** [comment]
It looks like this would at least not crash after https://github.com/typescript-eslint/typescript-eslint/pull/304.

**Comment by novemberborn** [comment]
I'm still seeing this with 1.4.1. I added `console.error(ranks, target, order, lowest)` before https://github.com/typescript-eslint/typescript-eslint/blob/d362c4a2051ff4128388fc515ba2f07f0ca1a3aa/packages/eslint-plugin/src/rules/member-ordering.ts#L315

```
[ 9007199254740991 ] 11 [ 'public-static-field',
  'protected-static-field',
  'private-static-field',
  'public-instance-field',
  'protected-instance-field',
  'private-instance-field',
  'public-field',
  'protected-field',
  'private-field',
  'static-field',
  'instance-field',
  'field',
  'constructor',
  'public-static-method',
  'protected-static-method',
  'private-static-method',
  'public-instance-method',
  'protected-instance-method',
  'private-instance-method',
  'public-method',
  'protected-method',
  'private-method',
  'static-method',
  'instance-method',
  'method' ] 9007199254740991
```

I'm not sure what particular source file is being linted here, if you let me know how I can log that from the plugin I can share its rough shape.

**Comment by novemberborn** [comment]
Actually looks like 1.4.1 was a bad publish: https://github.com/typescript-eslint/typescript-eslint/issues/317
