### ISSUE TITLE
[react/prop-types] Unable to notice prop-type validation when using `React.FC<PropTypes>`

### ISSUE THREAD

**Issue by ITenthusiasm** [typescript-eslint/typescript-eslint#3075]
The discussion in yannickcr/eslint-plugin-react#2353 seems to suggest that a problem in the typescript eslint parser prevents the `react/prop-types` rule from properly recognizing that the user has validated prop types. @ljharb's comments [here](https://github.com/yannickcr/eslint-plugin-react/issues/2353#issuecomment-513036364) and [here](https://github.com/yannickcr/eslint-plugin-react/issues/2353#issuecomment-650790793) particularly bring light to this concern.

I tried for quite some time to search titles for a similar issue so I'm mildly confident/hopeful this isn't a duplicate.

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

## Repro
I've created an example repo [here](https://github.com/ITenthusiasm/react-prop-types-typescript-issue). Below I've pasted the `.eslintrc.json`, the example code that causes the issue, and the `tsconfig.json`. Of course, you can also view all of these directly in the repo.

**eslintrc.json**
```JSON
{
  "extends": [
    "airbnb-base",
    "plugin:@typescript-eslint/recommended",
    "plugin:react/recommended"
  ],
  "plugins": ["react", "@typescript-eslint"],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "es6": true,
    "browser": true,
    "node": true
  },
  "settings": {
    "react": {
      "version": "detect"
    },
    "import/resolver": {
      "node": { "extensions": [".ts", ".tsx", ".js", ".jsx"] }
    }
  },
  "rules": {
    "no-undef": "off",
    "no-use-before-define": "off",
    "@typescript-eslint/no-use-before-define": "error",

    "import/extensions": [
      "error",
      "ignorePackages",
      { "js": "never", "jsx": "never", "ts": "never", "tsx": "never" }
    ]
  }
}
```

**Sample Code**
```TSX
// MyFailingComponent.tsx

import React from 'react';

/** Fails even though TypeScript *correctly* identifies the type */
const MyFailingComponent: React.FC<MyFailingComponentProps> = (props) => {
  const { text } = props;

  return <div>{text}</div>;
};

interface MyFailingComponentProps {
  text: string;
}

export default MyFailingComponent;
```

**tsconfig.json**
```JSON
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["MyFailingComponent.tsx", "MyPassingComponents.tsx"]
}
```

## Expected Result
When React's built-in type `React.FC<PropsTypes>` is used, eslint should be able to recognize that the props are validated, just as TypeScript recognizes that the types are valid. (It should be able to do this **without** redundant specification of prop types.)

## Actual Result
ESLint is unable to recognize that the prop types are properly validated based on the TypeScript types. (This is specifically when the PropTypes are not redundantly specified.) The error message for my example:

```
'text' is missing in props validation eslint(react/prop-types)
```

## Additional Info

**Command Line Exception**
```
react-prop-types-typescript-issue\MyFailingComponent.tsx
  5:11  error  'text' is missing in props validation  react/prop-types
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.15.1` |
| `TypeScript`                | `4.1.5` |
| `ESLint`                    | `7.20.0` |
| `node`                      | `10.15.1` |

**Comment by bradzacher** [comment]
See comment here which explains how this is correct AST structure and how the rule can be updated to handle this case: https://github.com/yannickcr/eslint-plugin-react/issues/2777#issuecomment-683944481

**Comment by ljharb** [comment]
@bradzacher is there any possibility of this parser attaching this kind of type information to the function in some way, so the work that downstream plugins have to do is less? Otherwise every TS-based plugin will have to reinvent the same helpers that eslint-plugin-import would have to.

**Comment by bradzacher** [comment]
To expand further.

```ts
const Component = (props: Props) => {};
```

produces the AST

```json
{
  "type": "VariableDeclaration",
  "declarations": [
    {
      "type": "VariableDeclarator",
      "id": {
        "type": "Identifier",
        "name": "Component"
      },
      "init": {
        "type": "ArrowFunctionExpression",
        "generator": false,
        "id": null,
        "params": [
          {
            "type": "Identifier",
            "name": "props",
            "typeAnnotation": {
              "type": "TSTypeAnnotation",
              "typeAnnotation": {
                "type": "TSTypeReference",
                "typeName": {
                  "type": "Identifier",
                  "name": "Props"
                }
              }
            }
          }
        ],
        "body": {
          "type": "BlockStatement",
          "body": []
        },
        "async": false,
        "expression": false
      }
    }
  ],
  "kind": "const"
}
```

Note that the `props` argument has a `typeAnnotation`. This is the case the rule currently handles.

```ts
const Component: React.FC<Props> = (props) => {};
```

produces the AST

```json
{
  "type": "VariableDeclaration",
  "declarations": [
    {
      "type": "VariableDeclarator",
      "id": {
        "type": "Identifier",
        "name": "Component",
        "typeAnnotation": {
          "type": "TSTypeAnnotation",
          "typeAnnotation": {
            "type": "TSTypeReference",
            "typeName": {
              "type": "TSQualifiedName",
              "left": {
                "type": "Identifier",
                "name": "React"
              },
              "right": {
                "type": "Identifier",
                "name": "FC"
              }
            },
            "typeParameters": {
              "type": "TSTypeParameterInstantiation",
              "params": [
                {
                  "type": "TSTypeReference",
                  "typeName": {
                    "type": "Identifier",
                    "name": "Props"
                  }
                }
              ]
            }
          }
        }
      },
      "init": {
        "type": "ArrowFunctionExpression",
        "generator": false,
        "id": null,
        "params": [
          {
            "type": "Identifier",
            "name": "props"
          }
        ],
        "body": {
          "type": "BlockStatement",
          "body": []
        },
        "async": false,
        "expression": false
      }
    }
  ],
  "kind": "const"
}
```

Note that in this case, the `props` argument has no type annotation (because it doesn't have one), and this time the variable declaration has a `typeAnnotation`.

This is the case that needs to be handled appropriately.

**Comment by bradzacher** [comment]
> is there any possibility of this parser attaching this kind of type information to the function in some way

Unfortunately not because it's impossible to know what `React.FC<Props>` means, or where the generic argument `Props` specifically applies.
Without type information the only way you can properly apply this is via contextual knowledge of what `React.FC` actually means.

To illustrate - `React.FC` could be defined as `type FC<T> = (props: any) => T`, meaning that `const Component: React.FC<Props> = (props) => {}` actually types a function as returning a type `Props` and not accepting an argument of type `Props`.

In reality, ofc, `React.FC` looks more like `type FC<T> = (props: T) => React.ReactElement`, but we can't know that.
As a generic library, we do not want to apply this sort of contextual knowledge unless it's encoded in the JS specs.
But as `eslint-plugin-react` specifically deals with react - it makes complete sense for it to encode this contextual knowledge!

**Comment by ITenthusiasm** [comment]
@bradzacher Thanks a ton for the helpful insights! Crazy to think the issue I found was actually a dupe of another issue in the other repo that was already commented on. lol. Sorry about that.

The "handling" you mentioned in the comment... is that for the ESLint plugin to do or for the end users to do? (I haven't messed around too much with the details of ESLint. I've only used plugins and updated rules.)

**Comment by bradzacher** [comment]
It's for the plugin to implement.

I'm no expert on the plugin's codebase by any means - but with a quick 5 min look I *think* that this function needs to be updated:
https://github.com/yannickcr/eslint-plugin-react/blob/734dc5384c72a1ae2d5d4ddf0fffd2bb8d2abfd1/lib/util/propTypes.js#L889-L916

**Comment by ITenthusiasm** [comment]
Awesome. Thanks again for the help!
