### ISSUE TITLE
Do we need to set the plugin?

### ISSUE THREAD

**Issue by domoritz** [typescript-eslint/typescript-eslint#3093]
https://github.com/prettier/eslint-plugin-prettier#recommended-configuration says that it's not needed to set the plugin when using `"extends": ["plugin:prettier/recommended"]`. Is this also true for this plugin or could it be made true?

**Comment by bradzacher** [comment]
You can see our configs right here in the repo.
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/src/configs

You don't need to specify it.
