### ISSUE TITLE
[dot-notation] add support for TS4.2's `noPropertyAccessFromIndexSignature` option

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#3104]
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/dot-notation": ["error"]
  }
}
```

```TS
interface GameSettings {
  // Known up-front properties
  speed: "fast" | "medium" | "slow";
  quality: "high" | "low";

  // Assume anything unknown to the interface
  // is a string.
  [key: string]: string;
}

declare const settings: GameSettings;

// good
settings.speed;
settings.quality;

// required to satisfy noPropertyAccessFromIndexSignature, but causes a dot-notation error
settings['username'];
```

We should add detection for the `noPropertyAccessFromIndexSignature`, and add logic so that it allows indexed access in the same cases.

This will allow you to use both this rule and the compiler option simultaneously.

**Comment by noullet** [comment]
Here is a slightly different situation: 

I have the dot-notation rule as "warn" so I thought I could comply with TypeScript and live with the warning until it is properly supported, however `lint --fix` turns the indexed notation into dot notation and breaks the TypeScript rule.
