### ISSUE TITLE
[enum-spacing] Key-spacing for enums

### ISSUE THREAD

**Issue by nuno-mrks** [typescript-eslint/typescript-eslint#3107]
Since enums are not supported by vanilla Javascript, I believe this is the right place for this rule proposal.
Essentially this proposal has a similar behavior of ESLint's own `key-spacing` but with enums, where we can define how to align its members (especially if they have associated values).

**Repro**
```Typescript
enum MyEnum {
  Option1 = 'enumOption1',
  LongerOption2 = 'enumOption2',
  MidOption3 = 'enumOption3',
  MuchLongerOption4 = 'enumOption4'
}
```

If we want to align all values (by the `=` sign), it would look like this:

**Expected Result**
```Typescript
enum MyEnum {
  Option1           = 'enumOption1',
  LongerOption2     = 'enumOption2',
  MidOption3        = 'enumOption3',
  MuchLongerOption4 = 'enumOption4'
}
```

Similar to colons for `key-spacing`, the rule could also support other options for consistent spacing before and/or after the `=` sign, but this could probably be covered already by other existing rules.

**Additional info**
Right now, having `no-multi-spaces` rule active generates an error if I align manually the enum values.
Is it possible that these two rules (`no-multi-spaces` and proposed rule) might conflict when they're both active?

**Comment by bradzacher** [comment]
#940
