### ISSUE TITLE
[consistent-type-import] flags non-type-only imported type as a value import when used in a decorator

### ISSUE THREAD

**Issue by vegerot** [typescript-eslint/typescript-eslint#3108]
As a continuation from https://github.com/typescript-eslint/typescript-eslint/issues/2972#issuecomment-785273015, I was wondering if @bradzacher would be able to comment on whether or not https://github.com/vuejs/vue-cli/issues/3145#issuecomment-785268090 is a bug in vue or in typescript-eslint

**Comment by bradzacher** [comment]
This is something I didn't know about typescript's decorator metadata.
It does use type information to change the emitted code - which is rather surprising.

If I write this code:

```ts
declare function Component(...args: any[]): any;
declare function namespace(...args: any[]): any;

@Component
export default class Comp {
 @namespace('stuff').Action('fetch') private readonly fetchStuff!: ActionMethod;
}
```

Then TS will see the value does not exist in scope, and attempt to [maybe reference the value](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwGEcBbABzxFQwAoA6e2AcwGcAueKVATwG0BdAJTtOXANwAoUJFgIU6bHniooxEM1JQwIOgxgth3fkI7cJ4gAJEyFKuJAAPcjAzxQiKMggvpzZoRKk8ADe4vDmyqrqmtoA5MwYyIiIMQK0AIKYuKjUMYggGGAAFinwpDBYAG5QGAhwUMB4EFxI+UUAyglJAITsGQqoALL5hTjAEgC+QA):

```js
    __metadata("design:type", typeof (_a = typeof ActionMethod !== "undefined" && ActionMethod) === "function" ? _a : Object)
```

If I add an import to a class (eg `import {Component as ActionMethod} from 'react';`), TS will [emit](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMIXBAdgU3fAhgZzgEEBjGYDAWUxgAsIATAXzgDMpU4ByKTXMrgG4AUMIaYSAG1y82AV3RkK6OCjRYcACgB0umQHN8ALji50ATwDaAXQCUJs+ZHipMzPMXkMcdLhCZ8MH5MHT0oQwcLG3tTCxFhAAE1SA0YYUwAD0hYOHFWXDlJeFd8QmTEYTgE339A4M0ufBg5VlYuW21SL3QG1hoSWna4MChgADdcGHdeXAYMSXM2ftoAZWbWgEITLuVqOkYRJiA) the same line

If I declare a class within the file (`class ActionMethod { }`), TS will [emit](https://www.typescriptlang.org/play?#code/MYGwhgzhAECCwBcCWB7AdgWQKYIBYoBNoBvaAXwCgKCtQwAnLaAMwFc1FU1oBhFAWwAO6LGgQAKAHTSGAcwgAuaGDQBPANoBdAJRKVqgNzVa4Ri3ad00NGH5YIgsMCxSZ9eXrVbdytUYoAAnxCImIUWAAewvQI0DTMYKwgsXRQvAKCJBTQATZ2Dk4uAOQQCKzMzEXakvDI6OJFzDjAuFXQgvRIAG5gCEyMYAToIKoszbgAymUVAIRKtVzYeIRGZEA) a slightly different line

```js
    __metadata("design:type", ActionMethod)
```

If I declare a type within the file, TS will emit code depending on what the type is:

- [`type ActionMethod = { }`](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggxsAlgewHYFkLABbICZQC8UA3gL4BQFeEcANgIYBO0AZgK6oIqpQDCyALZg0EVMAAUAOhnMA5gGcAXFAaoQAbQC6AShVqQAbmq1GLKBy5I0UVA0EQFYBnAjTZTRfvXa9q9cYUAAICwqLiFBAAHiJMwFA0rAzsdPH0DAoK-EJgpBRQQXYOTi5uAOQKwOysrGU6UvDWqBJlrFhw2HVQYEyIAG4MwNAsDHhodCAW7dgAylU1AIQqjTyYOPjGZEA)
  - ` __metadata("design:type", Object)`
- [`type ActionMethod = string`](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggxsAlgewHYFkLABbICZQC8UAzsAE6KoDmAULXhHADYCG50AZgK6oIqooAYWQBbMGgipgACgB0C9tRIAuKK1QgA2gF0AlGo0gA3AyZsOUHnyRooqVqIgkwrOBHmLyyw5t0H1TVNaAAERcUlpWggADwlyYChGTlZuZkSWVhISYTEwKABvWigQhycXNw8AcjJuTk4qvTl4W1QZKs4sOGxGqDBKADdWYGgOVjw0ZhArLuwAZWA6zgBCNRaBTBx8UwBfIA)
  - `__metadata("design:type", String)`
- [`type ActionMethod = number`](https://www.typescriptlang.org/play?ssl=1&ssc=27&pln=1&pc=1#code/C4TwDgpgBAggxsAlgewHYFkLABbICZQC8UqArgLYBGEATgFB14RwA2AhjdAGamoIqooAYWTkwaCKmAAKAHTyOAcwDOALihtUIANoBdAJTrNIANyNm7TlB58kaEm3IRlYNnAhyFNFUa17DGlpmdAACImISUnQQAB7iNMBQTFxspCyJrGzKysKiYFAA3nRQIaiOzq7u0gDkysCkXFzV+rLwdqg1XFhw2M1QYDSIAG5swNCcbHhoLCDW3dgAyvWNAITqbQKYOPhmAL5AA)
  - `__metadata("design:type", Number)`

**So far this is all well and good** - TS can and should use the information from within the module to emit code.

If, however, I import a type (`import {ActionMethod} from 'vuex';`), TS will detect that it is a type, evaluate it's type and [emit](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwIIGMbAgOwLIFMYAWEAJgL5wBmUEIcA5AG4CuuAHnQNwBQXxuKAGwCGUXJSaY0GTHADCNSJlyYYACgB0mkQHMAzgC44QzAE8A2gF0AlIeMnufQSLEUJUrHExCQuXWCEouBpaUHq2ppY2RqbcXAAC8uBYyjBcbJCwcHwUQkwC8E66unIKiFxwcV4+fgFBdLowTBQUdFbqqOhYqnQU+CgErXBgUMAMQjBiokLEWAImlH0EAMqNzQCEhh3SeIQk3KRAA) that:

```js
    __metadata("design:type", Function)
```

Which is really surprising - it's the first time I've seen it use type information from an imported thing thing to change the emitted code.

This is obviously not really compatible with non-type-aware tools that work in an isolated model.

**Comment by vegerot** [comment]
Wow that is very interesting.  Thank you for linking the playgrounds and discussion.  I learned a lot about how TypeScript emits decorator metadata.  In this case, what should be the solution in vue class components?

**Comment by bradzacher** [comment]
it seems like a bug in the vue tooling (or whatever tooling it's built on top of).
if you import a type without making it a type-only import then build tool should work as expected.

There is a separate bug in the lint rule because it does not understand that TS understands that the imported type is a type reference only. I don't know if we can fix this, however, because it would require using type information.

**Comment by JoshuaKGoldberg** [comment]
I'm going to go ahead and mark this as non-actionable since it's a bug in other packages:

* It would be a breaking change and inconvenience to the `consistent-type-import` to require type information for this one specific case
* TypeScript relying on types in emit is highly unusual and not a scenario generally recommended for tools
* There is also an issue in Vue tooling

Please post back if you have a proposal for how we could solve this issue in typescript-eslint
