### ISSUE TITLE
cannot read property 'type' of null

### ISSUE THREAD

**Issue by GuoSirius** [typescript-eslint/typescript-eslint#3111]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**
![image](https://user-images.githubusercontent.com/48358523/109085414-936fef00-7744-11eb-9625-2f973127d0d6.png)

```TS
if (options.length === 0) {
  try {
    options = (await this.getOptionsLists(queryString)) || []
  } catch {
    options = []
  }
}
```

**Expected Result**
No Error

**Actual Result**
Error

**Additional Info**

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.15.2` |
| `TypeScript`                | `4.2.0` |
| `ESLint`                    | `7.20.0` |
| `node`                      | `14.16.0` |

**Comment by bradzacher** [comment]
from the looks of that stack trace, the issue has nothing to do with this project.

**Comment by GuoSirius** [comment]
@bradzacher There are no errors in many parts of the project, which could run normally before, but now some files have this problem, not all of them

```TS
if (options.length === 0) {
  try {
    options = (await this.getOptionsLists(queryString)) || []
  } catch (error) { // is OK
  } catch { // cannot read property 'type' of null
    options = []
  }
}
```
