### ISSUE TITLE
[ban-ts-comment] RFC : Prefer jsdoc (`/**`) instead of inline (`//`) comments

### ISSUE THREAD

**Issue by jdeniau** [typescript-eslint/typescript-eslint#3137]
I propose a RFC to avoid using inline comment (`// @ts-expect-error`) and prefer jsdoc comment (`/** @ts-expect-error */`).

The error I see is that the output removes the inline comments in the definition file, and keep only the jsdoc comments.

You can see the exemple [in this typescript playground](https://www.typescriptlang.org/play?ssl=17&ssc=2&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgGIHt0ElzXk5AbwChlkZMAuZACgEpkBeAPmQDd1gATAbmIF9ixBABs4AZ3HIAgsmABbAA4iI8iOCkZsuWIhQkyAegBUx5AAEw4gLQQAHoogIwtqFHRRk168gAqAC2ApIOQQdDBkOBBkaHdPY0NSckwacTAoajSoUABzOmoObiIksgR0EHF0FQA6EXQc1PS6PjJBQWExSWQAITklFTUNNEwcSF0CA2RDQwsrWwcnF1iPLx8AkJCwiKiYtw8kinRGjOQs3Pz2Ti5islLyypq6hqzmpLagA) but I explain it here to make it easier to understand:

Imagine the following library:

```ts
interface FooInterface {
  foo: () => void;
}

class A implements FooInterface {
  /** @ts-expect-error -- This is not an error */
  foo(str: string): void {
    console.log(str);
  }
}

class B implements FooInterface {
  // @ts-expect-error -- This is not an error
  foo(str: string): void {
    console.log(str);
  }
}
```

Both `A` and `B` override the `FooInterface::foo` method and ignore the error, the only change here is that A uses jsdoc and B uses inline doc.

The definition file extract from this code is the following :

```ts
interface FooInterface {
    foo: () => void;
}
declare class A implements FooInterface {
    /** @ts-expect-error -- This is not an error */
    foo(str: string): void;
}
declare class B implements FooInterface {
    foo(str: string): void;
}
```

As you can see the `B` class outputs without the `// @ts-expect-error`.

Then if you use this library in another project, you will have a typescript error in this project reported on the `B` class. That's why I would like to enforce the use of jsdoc.

**Comment by bradzacher** [comment]
You're declaring a contract and then breaking that contract, which is why this errors.

If your classes are breaking the contract then either the implementation is wrong, or the contract is wrong.

Based on your description - this seems like an anti pattern, and a rule does not belong in this plugin.

**Comment by jdeniau** [comment]
You are probably right. Even if Javascript allows this, the purpose of using to use Typescript is to be more stricter.

Thank you for the time you put in this library 👍
