### ISSUE TITLE
[Question] enforce return type if not void

### ISSUE THREAD

**Issue by jvinai** [typescript-eslint/typescript-eslint#3142]
Hi,

I would like to know if it's possible via configuration to enforce requirement of return types if not `void` ?
Basically i dont want to add void everywhere because my team and I know that "no return type = void"

Thanks a lot.

**Comment by bradzacher** [comment]
Nope - we don't have a rule for this.
You can use `explicit-module-return-type`, but it's not possible to make it ignore void.
This is not an option we will be adding to the rule, however.
https://github.com/typescript-eslint/typescript-eslint/issues/50#issuecomment-589751882
