### ISSUE TITLE
Is this a false negative with [require-await]?

### ISSUE THREAD

**Issue by devuxer** [typescript-eslint/typescript-eslint#3153]
Just a question for now but could turn into bug report depending on the answer:

Is `require-await` supposed to trigger an error if a function returns a promise but contains no `await` keyword? I would have thought "yes", but I'm not seeing eslint errors under this circumstance (and I *am* seeing errors if the function doesn't return a promise, so I don't think this is a configuration issue).

If this is not an error, what is the criteria for determining when async is unnecessary? Note that my code works fine whether I include the `async` or not, so to me, it's unnecessary to include it.

**Comment by bradzacher** [comment]
> Is require-await supposed to trigger an error if a function returns a promise but contains no await keyword? I would have thought "yes"

No - that's the entire point of the version of the rule that we offer.
It's mentioned in the readme.

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/require-await.md

If you want the rule to error in this circumstance - then you can use the base rule.
