### ISSUE TITLE
Bad publish of 1.4.1

### ISSUE THREAD

**Issue by novemberborn** [typescript-eslint/typescript-eslint#317]
@JamesHenry `1.4.1` doesn't contain any changes in the `dist` files.

A diff with `1.4.0` yields:

<details>
<pre>
diff foo/node_modules/@typescript-eslint/eslint-plugin/CHANGELOG.md bar/node_modules/@typescript-eslint/eslint-plugin/CHANGELOG.md
5a6,12
> ## [1.4.1](https://github.com/typescript-eslint/typescript-eslint/compare/v1.4.0...v1.4.1) (2019-02-23)
> 
> ### Bug Fixes
> 
> - **eslint-plugin:** out-of-bounds access in member-ordering rule ([#304](https://github.com/typescript-eslint/typescript-eslint/issues/304)) ([4526f27](https://github.com/typescript-eslint/typescript-eslint/commit/4526f27))
> - **eslint-plugin:** support BigInt in restrict-plus-operands rule ([#309](https://github.com/typescript-eslint/typescript-eslint/issues/309)) ([#310](https://github.com/typescript-eslint/typescript-eslint/issues/310)) ([9a88363](https://github.com/typescript-eslint/typescript-eslint/commit/9a88363))
> 
Common subdirectories: foo/node_modules/@typescript-eslint/eslint-plugin/dist and bar/node_modules/@typescript-eslint/eslint-plugin/dist
Common subdirectories: foo/node_modules/@typescript-eslint/eslint-plugin/docs and bar/node_modules/@typescript-eslint/eslint-plugin/docs
diff foo/node_modules/@typescript-eslint/eslint-plugin/package.json bar/node_modules/@typescript-eslint/eslint-plugin/package.json
2,3c2,3
<   "_from": "@typescript-eslint/eslint-plugin@1.4.0",
<   "_id": "@typescript-eslint/eslint-plugin@1.4.0",
---
>   "_from": "@typescript-eslint/eslint-plugin@1.4.1",
>   "_id": "@typescript-eslint/eslint-plugin@1.4.1",
5c5
<   "_integrity": "sha512-LXLxWdq7nwGrJhMB78EKV+PJw4uWLyQLePRbJjbz6klItPaTa+5zxAr3+GGPaKlhTHKdoCsUaIGfCLjopUA65w==",
---
>   "_integrity": "sha512-+7wRNSKK+flJR0pOcGuTP2QwoJYJ91jdZV8Hm0IwVAWTqww8Jt5sN7r/Mlf2oFmDcO8jpM3ajsZCHJ4MmBMRjA==",
11c11
<     "raw": "@typescript-eslint/eslint-plugin@1.4.0",
---
>     "raw": "@typescript-eslint/eslint-plugin@1.4.1",
15c15
<     "rawSpec": "1.4.0",
---
>     "rawSpec": "1.4.1",
17c17
<     "fetchSpec": "1.4.0"
---
>     "fetchSpec": "1.4.1"
23,26c23,26
<   "_resolved": "https://registry.npmjs.org/@typescript-eslint/eslint-plugin/-/eslint-plugin-1.4.0.tgz",
<   "_shasum": "d37e8731a1fddfb2955c1acabac674c533294511",
<   "_spec": "@typescript-eslint/eslint-plugin@1.4.0",
<   "_where": "/private/var/folders/hv/q79j9y7d3znbfxx2s_dcb8fm0000gn/T/tmp.jyU3h1Bc6G/foo",
---
>   "_resolved": "https://registry.npmjs.org/@typescript-eslint/eslint-plugin/-/eslint-plugin-1.4.1.tgz",
>   "_shasum": "f752a6888a957fd411c7bcada11884c4257d374a",
>   "_spec": "@typescript-eslint/eslint-plugin@1.4.1",
>   "_where": "/private/var/folders/hv/q79j9y7d3znbfxx2s_dcb8fm0000gn/T/tmp.jyU3h1Bc6G/bar",
32,33c32,33
<     "@typescript-eslint/parser": "1.4.0",
<     "@typescript-eslint/typescript-estree": "1.4.0",
---
>     "@typescript-eslint/parser": "1.4.1",
>     "@typescript-eslint/typescript-estree": "1.4.1",
40,41c40
<     "eslint-docs": "^0.2.6",
<     "ts-node": "^8.0.1"
---
>     "eslint-docs": "^0.2.6"
53c52
<   "gitHead": "7bf4342d5ebf73fe1d86c13da99fe56ce13f8e8c",
---
>   "gitHead": "d362c4a2051ff4128388fc515ba2f07f0ca1a3aa",
82c81
<   "version": "1.4.0"
---
>   "version": "1.4.1"
</pre>
</details>

**Comment by JamesHenry** [comment]
Sorry about that! Thanks for flagging it up, I have published https://github.com/typescript-eslint/typescript-eslint/releases/tag/v1.4.2
