### ISSUE TITLE
Document whether @typescript-eslint/recommend should be before or after other recommended rules.

### ISSUE THREAD

**Issue by Svish** [typescript-eslint/typescript-eslint#3179]
I'm a bit of a newb still, and trying to set up an `.eslintrc.json` for my project. Currently have the following, based on documentation from here and prettier:

```
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "prettier"
  ],
```
But now I want to add the following, and I find it difficult to understand where these should be added, or whether it even matters. It seems `prettier` should always be last, because it also includes some plugin overrides (including for `@typescript-eslint/plugin`), but for the rest I'm very unsure.

```
    "plugin:react/recommended",
    "plugin:react-hooks/recommended",
    "plugin:jsx-a11y/recommended",
```

Should `@typescript-eslint/*` be first? Middle? Last?  Other than for `prettier` which should be last, does the order matter?

**Comment by armano2** [comment]
only requirement from us is that `plugin:@typescript-eslint/*` is after "eslint:*" as we do disable some of its rules and replace with our implementation

as for `prettier`, it should be placed after any other plugin that applies rules that change style formatting as they disable those

in most cases i will do something like this:

- eslint/*
- typescript-eslint/*
- **
- prettier/*

**Comment by Svish** [comment]
Thank you for quick and simple reply! I'm go for that ordering then, as it seems logical 👍👍

**Comment by bradzacher** [comment]
Check out our getting started guide which shows this order

https://github.com/typescript-eslint/typescript-eslint/tree/master/docs/getting-started/linting

**Comment by Svish** [comment]
> Check out our getting started guide which shows this order
> 
> https://github.com/typescript-eslint/typescript-eslint/tree/master/docs/getting-started/linting

That's where I was and got my initial setup, but it doesn't mention anything about other configurations. Typescript is such a central thing that I want to be really sure it's where it should be in the order.
