### ISSUE TITLE
[naming-convention] Support class type for variable selector

### ISSUE THREAD

**Issue by fedorov-xyz** [typescript-eslint/typescript-eslint#3182]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/naming-convention": [
      "error",
      {
        "selector": "default",
        "format": [
          "camelCase"
        ]
      },
      {
        "selector": "variable",
        "format": [
          "camelCase",
          "UPPER_CASE"
        ],
        "leadingUnderscore": "allow",
        "trailingUnderscore": "forbid"
      },
      {
        "selector": "variable",
        "types": [
          "function"
        ],
        "format": [
          "camelCase",
          "UPPER_CASE",
          "PascalCase"
        ],
        "leadingUnderscore": "allow",
        "trailingUnderscore": "forbid"
      },
      {
        "selector": "class",
        "format": [
          "PascalCase"
        ]
      },
      {
        "selector": "typeLike",
        "format": [
          "PascalCase"
        ]
      }
    ]
  }
}
```

```TS

/**
 * @typescript-eslint/class-name-casing rule
 */

// ❌ Class 'camelCaseClassVar' must be PascalCased.
export const camelCaseClassVar = class { public check = () => true; };

// ✅
export const PascalCaseClassVar = class { public check = () => true; };

// ❌  Class 'snake_case_class_var' must be PascalCased
export const snake_case_class_var = class { public check = () => true; };

// ❌ Class 'UPPER_CASE_CLASS_VAR' must be PascalCased.
export const UPPER_CASE_CLASS_VAR = class { public check = () => true; };

/**
 * @typescript-eslint/naming-convention
 */

// ✅ , but I want to achieve another result
export const camelCaseClassVar = class { public check = () => true; };

// ❌ Variable name `PascalCaseClassVar` must match one of the following formats: camelCase, UPPER_CASE
export const PascalCaseClassVar = class { public check = () => true; };

// ❌ Variable name `snake_case_class_var` must match one of the following formats: camelCase, UPPER_CASE
export const snake_case_class_var = class { public check = () => true; };

// ✅ , but I want to achieve another result
export const UPPER_CASE_CLASS_VAR = class { public check = () => true; };
```

**Expected Result**

I'm trying to implement old `@typescript-eslint/class-name-casing` rule with `@typescript-eslint/naming-convention`.
Before, `class-name-casing` detect `const A = class {}` as class expression and enforce PascalCase convention. Now, `naming-convention` does not allow me to achieve the same result.

I suggest adding a new `class` type to the `variable` selector (in addition to `function` type):

```json
{
  "rules": {
    "@typescript-eslint/naming-convention": [
      "error",
      {
        "selector": "variable",
        "types": ["class"],
        "format": ["PascalCase"]
      }
    ]
  }
}
```

**Actual Result**

There is no ability in `@typescript-eslint/naming-convention` to detect class variables.

**Additional Info**

–

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.17.0` |
| `@typescript-eslint/parser`        | `4.17.0` |
| `TypeScript`                       | `4.2.3` |
| `ESLint`                           | `7.22.0` |
| `node`                             | `14.15.1` |

**Comment by glen-84** [comment]
Is this different to #1485?

[This comment](https://github.com/typescript-eslint/typescript-eslint/issues/1485#issuecomment-725690653) seems to be asking for the same thing.

It's the general need to support `class` in `types`.
