### ISSUE TITLE
[no-undef] I am trying to use enum under the namespace globally

### ISSUE THREAD

**Issue by batmanhit** [typescript-eslint/typescript-eslint#3194]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**
I have defined a `enum` under the `namespace` which is defined in `.d.ts` file and I am having issues using those enum values.
![image](https://user-images.githubusercontent.com/30376020/111401182-643b0680-868e-11eb-8abc-374493fd3b8e.png)
![image](https://user-images.githubusercontent.com/30376020/111401191-68672400-868e-11eb-8af7-37afbe374b2a.png)
![image](https://user-images.githubusercontent.com/30376020/111401232-7cab2100-868e-11eb-8cf9-e25f7ac56ae6.png)

```JSON
module.exports = {
  root: true,
  env: {
    node: true
  },
  extends: [
    'plugin:vue/essential',
    'standard',
    '@vue/standard',
    '@vue/typescript/recommended'
  ],
  parserOptions: {
    ecmaVersion: 2020,
    parser: '@typescript-eslint/parser'
  },
  rules: {
    '@typescript-eslint/ban-ts-ignore': 'off',
    '@typescript-eslint/no-unused-vars': 'error',
    '@typescript-eslint/no-use-before-define': 'off',
    'brace-style': ['error', '1tbs', { 'allowSingleLine': true }],
    'generator-star-spacing': 'off',
    'import/order': ['error'],
    'max-len': ["error", { code: 120, "ignoreTemplateLiterals": true }],
    'no-debugger': 'error',
    'no-undef': 'error',
    quotes: ['error', 'single'],
    semi: ['error', 'never']
  },
  overrides: [
    {
      files: [
        '**/__tests__/*.{j,t}s?(x)',
        '**/tests/unit/**/*.spec.{j,t}s?(x)'
      ],
      env: {
        jest: true
      }
    }
  ]
}
```

Product.d.ts
```TS
declare namespace Batman {
  enum ProductType {
    BASE = 'BASE',
    PART = 'PART'
  }

  type Product = {
    id: string;
    type: ProductType;
  }
}
```

tsconfig.json
```JSON
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "allowJs": true,
    "importHelpers": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env",
      "jest"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.d.ts",
    "src/**/*.vue",
    "src/**/*.js",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Expected Result**

When I use `Batman.ProductType.BASE`, there should be no linting errors.

**Actual Result**

It shows the `Batman.ProductType.BASE` is invalid although it recognizes `Batman.ProductType`.

**Additional Info**

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`      | `2.33.0` |
| `@typescript-eslint/parser`             | `2.33.0` |
| `TypeScript`                            | `3.9.3` |
| `node`                                  | `14.15.4` |
| `npm`                                   | `6.14.10` |

**Comment by bradzacher** [comment]
> - [x]  I have read the FAQ and my problem is not listed.

Did you read the FAQ?

https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
