### ISSUE TITLE
migrate from `huksy` to `simple-git-hooks`

### ISSUE THREAD

**Issue by JounQin** [typescript-eslint/typescript-eslint#3222]
> 1. We can start having all husky 5 benefits (performance, small size) without waiting for MIT license for husky 5.
> 2. simple-git-hooks is smaller than husky 5.
> 3. husky 5 requires extra scripts in package.json.
> 4. husky 5 requires an extra pinst dependency for Yarn 2. simple-git-hooks has out-of-the box Yarn 2 support.

https://github.com/okonet/lint-staged/pull/954#issue-598110918

**Comment by bradzacher** [comment]
what are the actual benefits of the change? TBH I don't care about size (it's installed once per checkout) or yarn 2 support (most people haven't switched to yarn 2 due to the overhead)

**Comment by JounQin** [comment]
Easier to maintain and understand, no more extra `.husky` files.

**Comment by schmod** [comment]
[Husky is once again MIT licensed](https://github.com/typicode/husky/releases)

**Comment by JounQin** [comment]
License is not the key point.

There are a lot of objections on husky's upgrade like https://github.com/typicode/husky/issues/921.

And it is much more 'complex' than before like https://github.com/typicode/husky/issues/929.

**Comment by remcohaszing** [comment]
typicode/husky#929 issue literally starts with:
> I love how the latest husky incorporates `core.hooksPath`. This makes it so much simpler.

**Comment by bradzacher** [comment]
For now - I'm okay with us using husky. I don't think there's any strong arguments for us to migrate across given that we're already on the latest version of husky.
