### ISSUE TITLE
"@typescript-eslint/no-floating-promises" doesn't do the job if operator ! is used

### ISSUE THREAD

**Issue by bonjourjoel** [typescript-eslint/typescript-eslint#3229]
Hi,

I have installed eslint only for the rule "@typescript-eslint/no-floating-promises", because I believe it is a huge whole in typescript compiler to not report unhandled promises, those not using void nor await in async functions.

Eslint helps me a lot, but whenever i try to test a boolean or a boolean function call, i can write something like:
`if (! this.method(args)) {...`  where `method` returns a `Promise<boolean>`
Eslint doesn't detect that I made a programming error. These errors are difficult to find and defeat the purpose of the rule. I understand it's a C-style construction to test a value that's not a boolean. But myself I never do this, even in C, because it's error prone, and it's useless/outdated/cowboy style imho.
Those unhandled promises can cause race situations and make bugs reported by users impossible to reproduce. They are a nightmare. I wish eslint could handle these ones, either in the rule "@typescript-eslint/no-floating-promises", or in another, maybe disabled by default if you believe it's not a good rule for everyone.

Thanks for your time.
Regards.

**Comment by bradzacher** [comment]
`no-floating-promises` doesn't handle this check.
`no-floating-promises` checks for top-level expressions that return a promise and are unhandled.

Instead you want [`no-misused-promises`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-misused-promises.md) will do what you want.

**Comment by bonjourjoel** [comment]
Hi. It's working. It found a few of them actually! I'm glad it did. Very good set of rules. Thanks a lot.
