### ISSUE TITLE
Error: Failed to load parser '**/.eslintrc.prettier.js » .eslintrc.js#overrides[0]': Cannot find module './analyze'

### ISSUE THREAD

**Issue by caohuilin** [typescript-eslint/typescript-eslint#3249]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```TS
Error: Failed to load parser '@typescript-eslint/parser' declared in 'package.json » @jupiter/eslint-config » ./eslintrc.node.js » @jupiter-app/eslint-config » ./eslintrc.prettier.js » ./eslintrc.js#overrides[0]': Cannot find module './analyze'
```

![image](https://user-images.githubusercontent.com/12605189/113085594-bc3b4680-9212-11eb-8f15-be45fa84c9b6.png)

**Expected Result**

**Actual Result**

**Additional Info**

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/scope-manager`      | `4.20.0` |
| `TypeScript`                            | `3.9.9` |
| `node`                                  | `14.16.0` |

**Comment by bradzacher** [comment]
This is due to a mismatch in package versions installed in your node modules folder.
There is likely multiple versions installed and it is causing different versions to be required by different packages.
