### ISSUE TITLE
[docs] "Recommended ✔️" doesn't match recommended.ts

### ISSUE THREAD

**Issue by jtbandes** [typescript-eslint/typescript-eslint#3252]
It seems like [the list of recommended rules](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin) doesn't match the actual [implementation in `recommended.ts`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.ts).

For example, `@typescript-eslint/no-floating-promises` and `@typescript-eslint/no-for-in-array` are marked with a ✔️, but are not enabled in the `recommended` config.

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#usage

> Some highly valuable rules simply require type-checking in order to be implemented correctly, however, so we provide an additional config you can extend from called recommended-requiring-type-checking. You would apply this in addition to the recommended configs previously mentioned
