### ISSUE TITLE
[explicit-module-boundary-types] quick-fix for "Missing return type on function"

### ISSUE THREAD

**Issue by jrr** [typescript-eslint/typescript-eslint#3254]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

I'm not totally sure I'm in the right place. Is this repo reponsible for the quick fixes that appear for ESLint squiggles?

I'm filing this issue to point out some potentially low-hanging fruit:
1) "Missing return type on function" doesn't offer a quick fix.
2) VS Code already has a refactor available for "infer function return type".

It looks like the refactor is implemented in upstream TypeScript:
https://github.com/microsoft/TypeScript/blob/e5294b4d3c86033e350b1221dfa46273b3feacae/src/services/refactors/inferFunctionReturnType.ts

Are ESLint quick fixes able to call TypeScript refactors?

**Repro**

Enable [explicit-module-boundary-types](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md) and export a function with no return type:

```ts
export function foo() {
  return 5;
}
```

Open it in VS Code, right-click, "Refactors", "Infer function return type".

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.19.0` |
| `@typescript-eslint/parser`        | `4.19.0` |
| `TypeScript`                       | `4.2.3` |
| `ESLint`                           | `7.22.0` |
| `node`                             | `14.16.0` |

## Screenshots

![image](https://user-images.githubusercontent.com/164652/113308630-5adbac00-92d4-11eb-9556-67806cc1a0cf.png)

![image](https://user-images.githubusercontent.com/164652/113308701-6d55e580-92d4-11eb-8afb-be0656339949.png)

**Comment by bradzacher** [comment]
The rule does not use type information, so we will not be adding a fixer.

There have been many discussions in the past on this.

**Comment by jrr** [comment]
Ah, thanks, sorry that I missed the previous discussions. (here's one from a few pages deep in the search results: https://github.com/typescript-eslint/typescript-eslint/issues/59#issuecomment-621942695 )

I'm not particularly interested in whether this rule implements a quick fix - what I really want is for the existing refactor to be discoverable in the UI when you're dealing with lint errors. Would that belong to https://github.com/Microsoft/vscode-eslint ?

Are there other rules that pair nicely with existing refactors? There may be a general-purpose pattern to pursue here, something like _"I see you have lint error X. We don't have a fix, but you might be interested in TypeScript refactor Y."_?

**Comment by bradzacher** [comment]
Vscode-eslint does not concern itself with interpreting the lint results. As an extension it simply runs ESLint and reports the results.

Additionally everything is isolated and insulated - meaning it does not have access to TS, so even if it did have logic to interpret lint results, it would not be able to tell what TS refractors are available.

So it would have to be implemented in our rule.

In order for our rule to offer a quick fix from typescript's service (or anything relating to features exposed by typescript), they need to use type information. But as mentioned this rule does not use type information - so is not possible.

**Comment by jrr** [comment]
Could it (use type information)?

What leads to the decision about whether each rule uses type info? (is it an avoid-it-at-all-costs [performance](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md#performance) thing?)

Sorry to keep bothering you. I'm trying to understand the bigger architectural changes that would be needed to make this happen, and it probably comes across as a toddler repeatedly asking "why?".

**Comment by bradzacher** [comment]
Yes, it's a performance thing.

Initialising typescript in of itself incurs a non-trivial cost proportional to the size of your project. This alone causes a large number of users to not use type-aware rules at all.

Types are also computed lazily - i.e. more distinct types accessed by rules = more runtime.

Also introducing type information into an existing lint rule is a breaking change as it requires a config change for users. And as mentioned many users don't use type aware rules; meaning you would restrict many users from being able to use the rule.
