### ISSUE TITLE
[consistent-type-imports] Add coverage for re-exported types

### ISSUE THREAD

**Issue by aaronadamsCA** [typescript-eslint/typescript-eslint#3255]
`consistent-type-imports` can't currently detect or auto-fix this case:

```js
import { SomeType } from "./types";

export { SomeType };
```

It'd be nice if it could!

Current workaround:

1. Enable `isolatedModules` compiler option in `tsconfig.json`.
2. When `tsc` fails, manually update to `export type` (autofix is then able to update to `import type`.
3. Keep going until `tsc` stops failing.

I don't know if you can solve this, or how you would do it; but it's a new enough rule that I don't think anyone's reported the gap yet (sorry if they have, I did search!).

**Comment by bradzacher** [comment]
It's not possible to support this, unfortunately.

The scope analysis does not have access to type information - it solely operates on the AST.

From the perspective of the AST - `export { SomeType }` implies that the variable `SomeType` could be either a type or a value.

**Comment by aaronadamsCA** [comment]
I figured as much! At least now there's an issue for anyone else who searches for this. Thanks for the quick answer.
