### ISSUE TITLE
Rule proposal: prevent uninitialized variables causing runtime errors

### ISSUE THREAD

**Issue by TenPotatoes** [typescript-eslint/typescript-eslint#3274]
Example of uninitialized variable causing an error:

```ts
let firstName: string; // Why is this allowed instead of forcing it to be type string | undefined ?

function greet(){
    return 'Hello ' + firstName.toLowerCase();
}

greet();
```

https://www.typescriptlang.org/play?strict=true#code/DYUwLgBAZglgTgZzAOQIYFsQC4JLjAOwHMBuCAenIgHUALATwhgQjFuYlWGAHsB3EABMmBJCFTCeUaDzgBjQkSaQwPCACMQregActeRRAA+EAK4FBIWASEQA-AFgAUM6jm5YGDwIQicEOAAFACUAN7OEJEQ-mCmcD4A5AASINxqCRAA1NDwSGiYAHSqADL8IHAAwqgIICEkzgC+zs5+AWB1zkA

Request was added for this in Typescript: https://github.com/microsoft/TypeScript/issues/30053 but it was suggested that this could be a lint rule instead.

**Comment by ziloen** [comment]
And this
```ts
function someFn() {
  console.log(someVar) // this will cause runtime errors
} 
someFn()
const someVar = 123
```

**Comment by Josh-Cena** [comment]
This does not seem TypeScript-specific. @typescript-eslint/triage-team does the compiler API enable checking additional cases that the base plugin cannot do?

**Comment by bradzacher** [comment]
this is a really, really, really complicated problem to solve.
there's complex control-flow logic that could apply cross-module or cross-function...
some of the simpler cases, maybe, but I don't know if it's worth-while having a not-even-half-working lint rule.

So we can't really do this TBH

Best case we could create a rule that says "don't create `let` variables without an initialiser unless they have `undefined` in their type". But IDK if there's huge amounts of value in that.
This sort of "use then close over then initialise" pattern is pretty rare. I'm okay with closing this.
