### ISSUE TITLE
Rule proposal: Enforce using `.js` extension in imports

### ISSUE THREAD

**Issue by sindresorhus** [typescript-eslint/typescript-eslint#3288]
When you use `"type": "module"` in package.json, imports must have a `.js` extension. TypeScript, however, will not output `.js` extension and it doesn't allow `.ts` extension in imports. The result is that the only way to compile a TypeScript package to be native ESM, is to use `.js` extension when importing files.

For example, you must use this in a TypeScript file even if the file you're importing `foo.ts`:

```ts
import foo from './foo.js';
```

I would like this rule so I can ensure I write TypeScript code that compiles down to valid ESM that will not crash because of incorrect import statements.

Relevant TypeScript issue: https://github.com/Microsoft/TypeScript/issues/13422#issuecomment-275845062

**Comment by bradzacher** [comment]
This seems like something better suited for `eslint-plugon-import` plus `eslint-import-resolver-typescript`

I.e. this rule https://github.com/benmosher/eslint-plugin-import/blob/HEAD/docs/rules/extensions.md

**Comment by sindresorhus** [comment]
`eslint-plugin-import` is buggy and not very actively maintained. I would prefer to have it here. Most TypeScript users will want this rule in the coming year as everyone moves over to native ESM.

**Comment by bradzacher** [comment]
I believe that this would just be a feature request to `eslint-import-resolver-typescript` to ensure that it supports mapping `.js` files to `.ts` files.

Then the `import/extensions` rule should just work.

[eslint-import-resolver-typescript](https://github.com/alexgorbatchev/eslint-import-resolver-typescript) is well maintained (cc @JounQin as the core maintainer with more knowledge of this space)

**Comment by JounQin** [comment]
It is supported to import `.ts` with `.js` since https://github.com/alexgorbatchev/eslint-import-resolver-typescript/pull/56.

**Comment by bradzacher** [comment]
having a quick look at the source code for the rule - it looks like it will work correctly.

https://github.com/benmosher/eslint-plugin-import/blob/HEAD/src/rules/extensions.js#L177-L184

in particular

https://github.com/benmosher/eslint-plugin-import/blob/HEAD/src/rules/extensions.js#L122-L128

So i'm going to close this as it is already implemented in another plugin
