### ISSUE TITLE
Yarn 2 Plug'n'Play recognition based on location of parser package, rather than file being linted

### ISSUE THREAD

**Issue by WesCossick** [typescript-eslint/typescript-eslint#3293]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

https://github.com/WesCossick/demonstrate-typescript-eslint-bug

**Expected Result**

For the `@typescript-eslint/parser` package to recognize that the `project-to-lint/` directory is using Yarn 2 with Plug'n'Play.

**Actual Result**

The `@typescript-eslint/parser` package is assuming that, since it is located in a directory that's using Yarn 1, that the `project-to-lint/` directory is also using Yarn 1. Therefore, it can't seem to find any imports, because presumably, it's looking for a `node_modules/` directory, which doesn't exist.

**Additional Info**

Using [Node.js API](https://eslint.org/docs/developer-guide/nodejs-api), which doesn't offer `--debug` flag or equivalent option.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.22.0` |
| `TypeScript`                | `4.2.4` |
| `ESLint`                    | `7.24.0` |
| `node`                      | `14.16.1` |

**Comment by bradzacher** [comment]
Our tooling doesn't look for anything. It has no concept of `node_modules` beyond ignoring it in globs.

When we look for typescript all we do is `require('typescript')` so beyond that is up to node how that gets resolved.

**Comment by bradzacher** [comment]
Yarn2 does some stuff to typescript when you install it. It patches the installed TS package so that it understands how to handle yarn2.

We never made any changes in this repo. The changes were made by the yarn team in the patches yarn applies.

https://github.com/typescript-eslint/typescript-eslint/issues/1592

So likely installing it in `node_modules` means yarn2 doesn't apply it's patch, meaning typescript doesn't understand yarns PNP.

**Comment by WesCossick** [comment]
Okay, I see, so Yarn 2 is patching the `typescript` package, and when the parser is being included via the `tool/` directory, which is using Yarn 1, the `typescript` package that gets used is the unpatched one in `tool/node_modules/`. If, instead, the `parser` option is set inside `project-with-workaround/.eslintrc.json`, then it searches up the tree from there and uses the patched `typescript` package in `project-with-workaround/.yarn/`.

Thanks for clarifying.
