### ISSUE TITLE
[Extension Rule Proposal] @typescript-eslint/new-cap

### ISSUE THREAD

**Issue by richpauly13** [typescript-eslint/typescript-eslint#3296]
We use the eslint new-cap rule with the `capIsNew: true` option to prevent developers from using TitleCase without the new keyword.  This is working good.

The issue, however, is that we use Angular which has decorators in most files.  This causes the rule to error on decorators such as `@Component`.

We can add the decorator to the `capIsNewExceptions: ['Component']` options array.  It would be nice if we did not have to.

**Repro**

```JS
{
    rules: {
        'new-cap': [
            'error',
            {
                  capIsNew: true,
                  capIsNewExceptions: [
                        'Directive',
                        'HostBinding',
                        'HostListener',
                        'Injectable',
                        'Input',
                        'NgModule',
                        'Output',
                        'Pipe',
                        'ViewChild',
                        'ViewChildren'
                ],
                newIsCap: true,
                properties: true
            }
        ]
    }
}
```

```TS
@Component({})
```

tsconfig.json

```JSON
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "enableIvy": true,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

**Expected Result**

No eslint errors.

**Actual Result**

ESlint errors because the `@Component` decorator is in TitleCase without the new keyword and not in the `capIsNewExceptions: []` array.

**Additional Info**

Is it possible to make a `@typescript/eslint/new-cap` extension to remedy this problem?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `^4.22.0` |
| `@typescript-eslint/parser`        | `^4.22.0` |
| `TypeScript`                       | `~4.1.5` |
| `ESLint`                           | `^7.24.0` |
| `node`                             | `14.16.1` |

**Comment by bradzacher** [comment]
> to prevent developers from using TitleCase without the new keyword

I'm not sure I understand the point of the rule.

Is it just to stop people from naming variables with an upper case?
If so - our naming-convention rule will do that much better.

Is it to prevent naming errors? If so typescript will ofc just do this so it's not necessary.

Either I don't think bringing this rule in as an extension rule has much merit given that I'm pretty certain naming-convention does everything you'll want and then some.

**Comment by richpauly13** [comment]
Yes I agree the naming-convention rule does do this to a point.  We also use naming convention to make sure Classes are title case.  I guess the point I am making is that new-cap allows the title case if there is a new keyword whereas naming-convention doesnt allow title case at all.  Unless I am missing something.

If naming-convention does handle this situation, then we will turn off the new-cap rule and just use naming-convention.

**Comment by bradzacher** [comment]
> I guess the point I am making is that new-cap allows the title case if there is a new keyword

But I'm asking *why* you need this functionality?

In raw JS - using PascalCase helps signal constructability. And enforcing that `new` is only used with PascalCased names helps prevent bugs in a world without typechecking. It's essentially a weak form of typechecking and program validation.

However TypeScript will only allow you to use `new` with constructable things (error: `'new' expression, whose target lacks a construct signature, implicitly has an 'any' type. (7009)`). Which means that the rule now has little-to-no value as it's duplicating a check TS does.

**Comment by richpauly13** [comment]
Ok we will try turning off the new-cap rule and just use naming-convention.

The 'why' I need this functionality is to prevent amateur developers from invoking the new keyword and also prevent poor coding syntax.  Just trying to keep a consistent style so I do not spend my days refactoring other peoples work.  Just trying to prevent the poor syntax from happening in the first place.

Thanks.  I'll close the issue.
