### ISSUE TITLE
Publish typescript-eslint utilities for 3rd party plugin authors 

### ISSUE THREAD

**Issue by mohsen1** [typescript-eslint/typescript-eslint#330]
A lot of good work has gone into this project to make it possible to write type safe rules. It would be great to publish a package that includes:

* Typed `createRule` function 
* Typed RuleTester class
* General `ts-eslint` types

**Comment by bradzacher** [comment]
Do you think this is a good candidate to barrel up with the `createRule` function?

Could then instead name it `@typescript-eslint/util` or similar.

**Comment by ali-habibzadeh** [comment]
Is there a recipe for writing custom ts rules at the moment using @typescript-eslint/eslint-plugin?

**Comment by bradzacher** [comment]
If you're talking about "internal" rules that you don't intend to submit to this repo, then nope, we don't yet have a recipe for that.

We'll more than likely go down this route and expose our internal tooling to the world. Just need to find the time to do it..
