### ISSUE TITLE
[Question] Is the types util file exposed in the `experimental-utils` package?

### ISSUE THREAD

**Issue by detljh** [typescript-eslint/typescript-eslint#3305]
Is the [types util file](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/util/types.ts) currently exposed in any package? If not will there be any plans to add it to the `experimental-utils` package as I find myself using the helpers here quite a bit when creating my own ESLint rules

**Comment by bradzacher** [comment]
They are not!
If we add any utils to `experimental-utils` then we just use them from there (rather than duplicating them locally).

Happy to accept a PR to move any useful utilities across if you want to use them!

**Comment by RebeccaStevens** [comment]
I believe this fixed now
