### ISSUE TITLE
TypeScript version in tsutils peerDependency is too old

### ISSUE THREAD

**Issue by ghaiklor-wix** [typescript-eslint/typescript-eslint#3309]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

Create a project where TypeScript version is newer than 3.7. Configure the typescript-eslint as you usually do and run install.

```shell
pnpm install --strict-peer-dependencies
```

**Expected Result**

Installation phase is passed.

**Actual Result**

```shell
 ERROR  @typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree: tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none was installed.
```

**Additional Info**

I've opened an issue to `tsutils` repository as well to find out if there are any reasons to not update a peer dependency.
https://github.com/ajafff/tsutils/issues/134

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `<version from @typescript-eslint/eslint-plugin@4.22.0>` |
| `TypeScript`                           | `4.2.4` |
| `node`                                 | `14.16.1` |

**Comment by ghaiklor-wix** [comment]
There is a possibility that it will break on npm v7 as well - https://github.com/ajafff/tsutils/issues/134#issuecomment-825690266

**Comment by bradzacher** [comment]
I think you're misunderstanding the error message:

> tsutils@3.21.0 requires a peer of typescript@​>​=2.8.0 ... but none was installed

To me that's saying that TypeScript isn't installed at all.

Our project does not have an explicit dependency on TypeScript. This is intentional so that we don't install our own duplicate version of TypeScript. You must manually install the version of TypeScript you want to use with your project.

**Comment by ghaiklor-wix** [comment]
@bradzacher I installed it, but with version `4.2.1`. I believe it does not satisfy the semver range specified in `peerDependencies` so the package manager refuses to continue. Any thoughts?

Tagging @zkochan, is it possible that pnpm throws such an error because v4 is not specified in semver range?

**Comment by bradzacher** [comment]
> I believe it does not satisfy the semver range

But the semver range is simply `>​=2.8.0` which any non-rc version will satisfy. I.e. v4.2.4 satisfies this range.

The other versions listed in the range are just RC and beta tags that don't change anything as they're listed as `||`

**Comment by zkochan** [comment]
The error says "but none was installed". If the problem would be with semver, the error would be different. Is it in a monorepo? Maybe add typescript as a dev dependency in the root project of the monorepo.

**Comment by ghaiklor-wix** [comment]
@zkochan it is a shared configuration for eslint. I've added `typescript` both to `peerDependencies` and `devDependencies` and still no luck.

Here is what my `package.json` looks like for shared ESLint configuration:

```json
  "dependencies": {
    "@typescript-eslint/eslint-plugin": "4.22.0",
    "@typescript-eslint/parser": "4.22.0",
    "eslint-config-prettier": "8.2.0",
    "eslint-config-standard-with-typescript": "20.0.0",
    "eslint-plugin-eslint-comments": "3.2.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jest": "24.3.5",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-optimize-regex": "1.2.0",
    "eslint-plugin-prettier": "3.4.0",
    "eslint-plugin-promise": "4.3.1",
    "eslint-plugin-regexp": "0.9.0",
    "eslint-plugin-security": "1.4.0",
    "eslint-plugin-simple-import-sort": "7.0.0",
    "eslint-plugin-tsdoc": "0.2.14"
  },
  "devDependencies": {
    "@wix/nsr-tsc-config": "*",
    "typescript": "4.2.4"
  },
  "peerDependencies": {
    "eslint": "7.24.0",
    "prettier": "2.2.1",
    "typescript": "4.2.4"
  }
```

BTW, I'm using Rush, maybe it gets mixed somehow in the end by Rush 🤔

**Comment by bradzacher** [comment]
I'm going to close this as this isn't an issue with our tooling. Feel free to continue discussing.

**Comment by ghaiklor-wix** [comment]
cc @octogonz 

We are having a strange situation here with Rush + pnpm. Can you take a look?

**Comment by octogonz** [comment]
@ghaiklor-wix This is tracked by https://github.com/microsoft/rushstack/issues/2389.  I'm going to work on it this week.

**Comment by ghaiklor-wix** [comment]
@octogonz I'm not sure I following. The PR you mentioned is about peerDependencies in your configuration, right? If so, the problem we are seeing here is not related, because I'm not using rushstack configuration.
