### ISSUE TITLE
Rule suggestion: generalize @typescript-eslint/no-angle-bracket-type-assertion

### ISSUE THREAD

**Issue by ThomasdenH** [typescript-eslint/typescript-eslint#332]
I would like to have a more general version of `@typescript-eslint/no-angle-bracket-type-assertion`, maybe called `type-assertion`. It would have two options, that can be enabled independently:

`no-angle-bracket`: If this is enabled, angle bracket type assertions are disallowed.
`no-as`: If this is enabled, `as` type assertions are disallowed.

This would allow different use cases. Some people like to use the old assertions instead of the new ones. Personally, I would like to lint all type casting since they introduce unsafety.

The default behaviour would be `['no-angle-bracket']` to match the current situation. If no options are enabled, the lint could warn that the lint can be disabled.

**Comment by j-f1** [comment]
How about `prefer-as`, `prefer-angle-bracket`, and `none` as options?

**Comment by ThomasdenH** [comment]
Also fine!

The `prefer-angle-bracket` option is implemented in the `tslint-microsoft-contrib` ruleset as `
prefer-type-cast`, so adding this option would add another check to the roadmap as well.

**Comment by bradzacher** [comment]
The reason I would lean against doing this is because the angle bracket assertions are kind of deprecated, and `as` is considered best practice because it doesn't clash with jsx syntax (even if you're only writing node code, it's still good to follow best practices).

**Comment by ThomasdenH** [comment]
I personally am mostly interested in the `none` mode, just thought this would be a nice way to reduce duplication. I'd argue that having all options isn't a lot of extra maintenance cost so for completeness it's worth it. Still, `prefer-angle-bracket` wouldn't be an option I'd personally use.

**Comment by uhyo** [comment]
I would really love to use `"type-assertion": "none"` or something like that. It would catch a lot of unsafe code brought into project.

**Comment by bradzacher** [comment]
@uhyo, helping your code be more safe can be accomplished via a combination of these 3 rules:

[`no-unnecessary-type-assertion`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-type-assertion.md)
[`ban-ts-ignore`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-ts-ignore.md)
[`no-explicit-any`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-explicit-any.md)

Type assertions are sometimes necessary to help typescript get it right, so banning them all together would (imo) be a terrible idea, as it would cause developers to lose faith in the linting tools.

**Comment by uhyo** [comment]
@bradzacher Thanks for reply. I understand your argument.

IMO, however, a project which gives much weight to safety should use `"type-assertion": "none"` and require explicit `// eslint-disable-next-line: type-assertion` on every use of `as` as well as plenty of comments which describe the necessity of `as`.

**Comment by bradzacher** [comment]
I'm not against it being built in (if someone wants to do it), but I would fight hard against it being introduced as a lint rule if I were an engineer on the codebase :)
