### ISSUE TITLE
The file does not match your project config

### ISSUE THREAD

**Issue by eng-dibo** [typescript-eslint/typescript-eslint#3334]
- [ x] I have tried restarting my IDE and the issue persists.
- [ x] I have updated to the latest version of the packages.
- [ x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

I set this option in .eslintrc.js file:
```
 parserOptions: {
    project: "tsconfig.json",
    sourceType: "module",
  }
```

tsconfig.json only excludes 'node_modules', which means that the file package.json is included
but when I run `prettier --write .` the following error occurs
```
/home/sh_eldeeb_2010/@eng-dibo/dibo/package.json
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: package.json.
The extension for the file (.json) is non-standard. You should add "parserOptions.extraFileExtensions" to your config
```

I run `prettier` through `lint-staged`

**Comment by bradzacher** [comment]
> The extension for the file (.json) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

I think that the last line of the error message covers it?
If you're planning on our parser to parse json files for linting, then you need to configure it as such.
