### ISSUE TITLE
[prefer-includes] Auto-fix incorrect when optional chaining

### ISSUE THREAD

**Issue by jp7837** [typescript-eslint/typescript-eslint#3341]
- [ x ] I have tried restarting my IDE and the issue persists.
- [ x ] I have updated to the latest version of the packages.
- [ x ] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/prefer-includes": "error"
  }
}
```

```TS
let x: string;
if (x?.indexOf("y") === -1) {
	console.log("y not found in x");
}
```

**Expected Result**
Instance is either not auto-fixed or fixed correctly honoring the optional chaining

**Actual Result**
Auto-fix changes logic.  Result for example below.  The if statement returns false originally and true after the auto-fix.
```TS
let x: string;
if (!x?.includes("y")) {
	console.log("y not found in x");
}
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.22.0` |
| `@typescript-eslint/parser`        | `4.22.0` |
| `TypeScript`                       | `4.2.4` |
| `ESLint`                           | `7.25.0` |
| `node`                             | `12.19.0` |

**Comment by bradzacher** [comment]
Nitpick: your console log doesn't make sense... As your code is checking to see if `"y"` is not contained in the array..

So logging "found" is backwards and just confuses the issue.

---

This is likely a regression from when the optional chain ast changed.

**Comment by jp7837** [comment]
@bradzacher sorry about that, was scoping my scenario down and got it backwards :).  Updated the example for clarity.
