### ISSUE TITLE
[member-ordering] support exclusion list w/ regexp option

### ISSUE THREAD

**Issue by jrista** [typescript-eslint/typescript-eslint#3375]
This is a feature request for the member-ordering rule. I am a heavy user of NgRx with Angular, and TSLint has supported this particular feature for some time. Now that TSLint is going away and ESLint is being used instead, I am hoping we can add some support for this.

When writing NgRx Effects classes, TSLint has ignored the rule that any property created with createEffect be required to be sorted ABOVE the constructor. While effects are properties, they are more like methods than properties, as they are functions. So, TSLint allows them to be sorted BELOW the constructor. I've always found it confusing and odd when the constructor is found at the bottom of an effects class that may potentially have quite a bit of logic and a long scroll to find the constructor. 

In order to support this, while still keeping ESLint general purpose (without having NgRx specific checks), I am wondering if it would be possible to have an exclusions list, with optional regexp pattern support, for property names? 

That would allow us to, say, exclude any property that ends with a $ from the requirement that they be sorted above the constructor.

```ts
type TypeOptions<T> =
  | {
    memberTypes: Array<T> | 'never',
    order?: 'alphabetically' | 'as-written',
    exclusions?: Array<string | Regexp>,
  }
  | {
    order: 'alphabetically',
    exclusions?: Array<string | Regexp>,
  }
  | {
    order: 'alphabetically',
  };
```

With simple strings, exact matching would be applied and exact matches would be excluded from the rule. With a Regexp, the pattern would be applied to each property, and only those that match would be excluded.

**Comment by bradzacher** [comment]
Could you please show an example of the code you're talking about?
a code fragment is worth 1000 words which is why the issue template asks for it.

**Comment by jrista** [comment]
Should be something as simple as:

```json
    {
      "files": ["*.effects.ts"],
      "parserOptions": {
        "project": [
          "tsconfig.json",
          "e2e/tsconfig.json"
        ],
        "createDefaultProgram": true
      },
      "rules": {
        "@typescript-eslint/member-ordering": {
			default: {
				exclusions: [/(.*\$)/g]
			}
		}
      }
    },
```

Perhaps a utility type for the regexp, given this is json:

```ts
type PatternMatch {
  pattern: string;
  options: string; // g, i, m, etc.
  negate: boolean;
}
```

Anyway, anything matching the exclusions would be excluded from being reordered, and would remain where it was.

**Comment by bradzacher** [comment]
Sorry - i meant an example of the code you're talking about.
I completely understand your proposal, and what the config might look like is an irrelevant implementation detail.

What I'm trying to understand the usecase.

> When writing NgRx Effects classes, TSLint has ignored the rule that any property created with createEffect be required to be sorted ABOVE the constructor. While effects are properties, they are more like methods than properties, as they are functions.

What's an NgRx Effects class? What's createEffect look like? I have no idea what you're referencing here.

**Comment by jrista** [comment]
Sorry, was on vacation for a while there, and am finally back into the daily grind again. Sorry about the delay. An NgRx Effect looks like this:

```ts
export class CustomerEffects {
  constructor(private readonly actions$: Actions, private readonly router: Router) {}

  loadCustomers$ = createEffect(
    () => this.actions$.pipe(
      ofType(customersListPageViewed, customerRefreshButtonClicked, ...),
      map(() => loadAllCustomers())
    )
  );

  routeToCustomerDetailView$ = createEffect(
    () => this.actions$.pipe(
      ofType(customerViewed),
      concatLatestFrom(() => this.store.select(selectCurrentRoute)),
      map(([{ customer }, route]) => this.router.navigate([customer.id], { relativeTo: route })),
    )
  );

  selectCustomer$ = createEffect(
    () => this.actions$.pipe(
      ofType(ROUTER_NAVIGATED),
	  routeMatches(\/customers\/\d+),
	  map(({
        root: {
          firstChild: {
            firstChild: { params }
          }
        }
      }) => params['id']),
      map(customerId => selectCustomerByKey({ key: customerId }))
    )
  );
}
```

While technically these are "properties", we still prefer that they be sorted below the constructor, rather than above it.
