### ISSUE TITLE
[no-duplicate-imports] No option to ignore certain imports

### ISSUE THREAD

**Issue by JakeStanger** [typescript-eslint/typescript-eslint#3386]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

eslint (for rule):
```JSON
{
  "rules": {
    "@typescript-eslint/no-duplicate-imports": ["error"]
  }
}
```

erroring code:
```ts
import { IList as List } from '@pnp/sp/lists';
import '@pnp/sp/lists'; // errors
```

tsconfig:
```json
{
  "extends": "../../@microsoft/rush-stack-compiler-3.9/includes/tsconfig-web.json",
  "compilerOptions": {
    "rootDir": "../../../src",
    "target": "es5",
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "outDir": "../../../lib",
    "inlineSources": false,
    "downlevelIteration": true,
    "noImplicitAny": true,
    "noUnusedLocals": false,
    "typeRoots": ["./node_modules/@types", "./node_modules/@microsoft"],
    "types": [
      "es6-promise",
      "webpack-env",
      "cypress",
      "cypress-storybook/cypress"
    ],
    "lib": [
      "es5",
      "dom",
      "es2016"
    ],
    "esModuleInterop": true
  },
}
```

**Expected Result**

There should be an option to ignore certain imports with regex. Perhaps something like:

```json
{
  "rules": {
    "@typescript-eslint/no-duplicate-imports": [
       "error",
       {
         "ignore": ["^@pnp\/sp"]
       }
    ]
}
```

**Actual Result**

Eslint (correctly) detects the import as a duplicate but there is no way to toggle it without adding an ignore to every import

```
'@pnp/sp/lists' import is duplicated  @typescript-eslint/no-duplicate-imports
```

or:
```ts
// eslint-disable-next-line @typescript-eslint/no-duplicate-imports
import '@pnp/sp/lists';
```

**Additional Info**

While it may seem like I could just remove the duplicate import, Webpack is causing errors without the second one due to the nature of the library being used and presumably its tree shaking. 

To have the ability to work around situations like this by ignoring certain packages would be very useful

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.23.0` |
| `@typescript-eslint/parser`        | `4.23.0` |
| `TypeScript`                       | `3.9.9` |
| `ESLint`                           | `7.26` |
| `node`                             | `12.16.0` |

**Comment by bradzacher** [comment]
This is an extension rule, meaning we extend a core ESLint rule to support TypeScript features. We do not build additional features that are unrelated to TypeScript.

If this is important to you. Please submit an issue upstream.

**Comment by JakeStanger** [comment]
Ah my bad, will do
