### ISSUE TITLE
[no-base-to-string] add option to prevent usage of Array .join on non-toString things

### ISSUE THREAD

**Issue by lydell** [typescript-eslint/typescript-eslint#3388]
(Note: I couldn’t find any issue template/info about feature requests, I hope this is ok! 🙏 )

Summary: Disallow `.join()` calls on `Array`s that aren’t `Array<string>`.

Motivation:

I had a function like this:

```ts
function noCommonRoot(paths: Array<string>): string {
  return `
I could not find a common ancestor for these paths:

${paths.join("\n")}

Files on different drives is not supported.
  `.trim();
}
```

I had trouble with using too much `string` types an mixing stuff up, so I introduced an `AbsolutePath` type to help me, and replaced `string` with `AbsolutePath` in many places.

```ts
type AbsolutePath = { tag: "AbsolutePath"; absolutePath: string };

function noCommonRoot(paths: Array<AbsolutePath>): string {
  return `
I could not find a common ancestor for these paths:

${paths.join("\n")}

Files on different drives is not supported.
  `.trim();
}
```

When I had fixed all compile errors, I had accidentally introduced a bug! `noCommonRoot` now outputs:

```
I could not find a common ancestor for these paths:

[object Object]
[object Object]
[object Object]

Files on different drives is not supported.
```

Oops!

I searched for `.join` in the entire project and switched to using this function instead, to avoid this problem in the future:

```ts
function join(array: Array<string>, separator: string): string {
  return array.join(separator);
}
```

That way I could fix the `noCommonRoot` function:

```ts
function noCommonRoot(paths: Array<AbsolutePath>): string {
  return `
I could not find a common ancestor for these paths:

${join(
  paths.map((path) => path.absolutePath),
  "\n"
)}

Files on different drives is not supported.
  `.trim();
}
```

Bonus: my `join` function _requires_ the separator argument. That would be nice to lint too. The default `","` is never what I want.

**Comment by bradzacher** [comment]
THis definitely makes sense as something to lint for, but I don't think it should be a brand new rule.

I think this would work well as an extension / additional option in our [no-base-to-string](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-base-to-string.md) rule, which already does these checks, just not on a `.join` call.

**Comment by lydell** [comment]
That sounds great! Turns out I’m already using that rule, but didn’t remember it when writing this issue.

**Comment by safareli** [comment]
This sounds like a good addition!

**Comment by bradzacher** [comment]
@ronami The latter case would already be covered by [restrict-template-expressions](https://typescript-eslint.io/rules/restrict-template-expressions). It's not as granular as "the elements must be `toString`able" and would just block the array altogether -- but the majority of the time that would be correct.
