### ISSUE TITLE
[no-unsafe-*] All of these rules do not seem to work in Deno

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#3395]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

Related: #2556

**Repro**

- [Install VSCode](https://code.visualstudio.com/) if you don't already have it installed.
- [Install Deno](https://deno.land/#installation) if you don't already have it installed.
- [Install the ESLint VSCode extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) if you don't already have it installed.
- [Install the Deno VSCode extension](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno) if you don't already have it installed.
- `git clone git@github.com:Zamiell/deno-typescript-eslint-bug.git`
- `npm install`
- `code .` (to launch VSCode using this directory as a workspace)
- Open the "eslintrc.js" file using the explorer nav pane on the left side of the screen.
- Observe that this is a minimal config with only two rules enabled.
- Open the "main.ts" file using the explorer nav pane on the left side of the screen.
- Notice that ESLint properly lints the first part of the program, the type alias.
- Notice that ESLint does not properly lint the second part of the program, a simple Deno standard library call.
- Notice that when you mouseover the "Deno" text, you can see that VSCode has full knowledge of this namespace.
- Notice that when you mouseover the "chdir" text, you can see that VSCode has full knowledge of this function.
- Thus, @typescript-eslint should not be complaining that this is an "any" value, and this is a bug in the rule.

This problem also seems to occur for every `no-unsafe-*` rule.

Furthermore, in #2556, @bradzacher said that this kind of thing happens because the TypeScript language server inside of VSCode does not have knowledge about the Deno standard library. However, since everything is appearing properly in the mouseover text, it really does appear that the TypeScript language server does indeed know about all of the Deno stuff correctly. Which means that the fault should lie with the `@typescript-eslint/eslint-plugin` package.

<br />

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.23.0` |
| `@typescript-eslint/parser`        | `4.23.0` |
| `TypeScript`                       | `4.2.4` |
| `ESLint`                           | `7.26.0` |
| `node`                             | `16.1.0` |

**Comment by bradzacher** [comment]
> Install the Deno VSCode extension

I think I explained it all in my comment (https://github.com/typescript-eslint/typescript-eslint/issues/2556#issuecomment-692281184).

> The deno vscode extension would patch the TS language server to teach it about these imports.

Reading the readme of the deno extension:

> Features
> - Type checking for JavaScript and TypeScript, including quick fixes, hover cards, intellisense, and more.
> - Resolution of modules in line with Deno CLI's module resolution strategy allows caching of remote modules in Deno CLI's cache.

We simply use the `typescript` package. That's all. If your deno code can be typechecked by using the `tsc` command with no modifications, then it will work with our project.

If you cannot do this, then it will not work.

**Comment by Zamiell** [comment]
Ok, thanks Brad. Sorry for the duplicate issue, and I greatly appreciate your work on this linter. Cheers.
