### ISSUE TITLE
Which rules require type information?

### ISSUE THREAD

**Issue by NilSet** [typescript-eslint/typescript-eslint#341]
Given the massive slowdown discovered in #243 , I would like to know which rules actually require type info. It would be nice to have that in the chart at https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/README.md

**Comment by NilSet** [comment]
Am I correct in thinking that rules which call getParserServices are the ones that depend on type info? If so I can make a PR adding the column to the readme.

**Comment by bradzacher** [comment]
You are correct. Rules that call `getParserServices` will throw if they do not have a project defined in the config.
