### ISSUE TITLE
Support typescript new syntax `override`

### ISSUE THREAD

**Issue by Innei** [typescript-eslint/typescript-eslint#3447]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

Can't parse `override` syntax. Like this.

![image](https://user-images.githubusercontent.com/41265413/119507405-66fa5c00-bda1-11eb-80cd-2c78552aff97.png)

**Expected Result**

parse `override` syntax.

**Actual Result**

Parsing error: ';' expected. eslint

**Additional Info**

Parsing error: ';' expected. eslint

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.25.0` |
| `TypeScript`                | `4.4-dev` |
| `ESLint`                    | `7.26.0` |
| `node`                      | `14` |

**Comment by bradzacher** [comment]
We do support https://github.com/typescript-eslint/typescript-eslint/pull/3429 as of v4.25.0

If it's not working for you then likely your installed version is wrong.

**Comment by Innei** [comment]
Thank you for your reply. I just remove node_modules and re-install. It worked.

**Comment by akphi** [comment]
@bradleyayers I know this validation has been handled by Typescript, is there a plan to implement a rule in `typescript-eslint` so we can make use of auto-fix?

We have a fairly large codebase and would like to turn on the flag `--noImplicitOverride` but there's currently no programmatic way to add `override` to all places which need it.

**Comment by bradzacher** [comment]
It's a language feature which causes errors in TS. There's no lint rule to implement.

If you want to turn it on in your project - you can script up a codemod for your codebase.
There are examples over the web of using the TS APIs to get the diagnostics, and there are other examples of using tools (like jscodeshift) to make code changes.

**Comment by akphi** [comment]
@bradleyayers 🙏 thank you so much for clarifying!

**Comment by bradzacher** [comment]
@akphi please make sure you check who you're tagging so that you tag the correct user.
or else you're sending spam notifications to someone else.
