### ISSUE TITLE
Get AST, how to turn it into source code? Thank you!

### ISSUE THREAD

**Issue by zhangyuefang** [typescript-eslint/typescript-eslint#346]
Get AST, how to turn it into source code? Thank you!

**Comment by j-f1** [comment]
You could try [Prettier](https://prettier.io).

**Comment by bradzacher** [comment]
Feel free to continue to discuss, but as this is unrelated to this repo, I'm going to close it.

There are also tools like https://www.npmjs.com/package/astring which can generate JS code, and with a bit of modification can also generate typescript.
