### ISSUE TITLE
JSON output `docs.url` includes `[object Object]`

### ISSUE THREAD

**Issue by ybiquitous** [typescript-eslint/typescript-eslint#3473]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "extends": "plugin:@typescript-eslint/recommended"
}
```

```TS
const x = "";
```

Run the following command:

```console
$ ./node_modules/.bin/eslint . -f json-with-metadata | jq .
```

**Expected Result**

(The following are excerpts.)

```JS
{
  // ...
  "docs": {
    // ...
    "url": "https://github.com/typescript-eslint/typescript-eslint/blob/v4.26.0/packages/eslint-plugin/docs/rules/unified-signatures.md"
  },
  // ...
}
```

The JSON output should include `v4.26.0` in the `docs.url` fields.

**Actual Result**

```JS
{
  // ...
  "docs": {
    // ...
    "url": "https://github.com/typescript-eslint/typescript-eslint/blob/v[object Object]/packages/eslint-plugin/docs/rules/unified-signatures.md"
  },
  // ...
}
```

But the actual JSON output includes `v[object Object]` in the `docs.url` fields.

**Additional Info**

Perhaps, the following code seems to have a problem:

https://github.com/typescript-eslint/typescript-eslint/blob/b814e635c1f34139c89e0176727480935dd45cac/packages/eslint-plugin/src/util/createRule.ts#L5

Is this correct? ⬇️ 

```diff
-const version: string = require('../../package.json');
+const version: string = require('../../package.json').version;
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.26.0` |
| `@typescript-eslint/parser`        | `4.26.0` |
| `TypeScript`                       | `4.3.2` |
| `ESLint`                           | `7.27.0` |
| `node`                             | `16.2.0` |

**Comment by bradzacher** [comment]
definitely looks like it's the problem!
