### ISSUE TITLE
proposal: multiline-ternary and operator-linebreak

### ISSUE THREAD

**Issue by privatenumber** [typescript-eslint/typescript-eslint#3474]
## Feature request
Support [multiline-ternary](https://eslint.org/docs/rules/multiline-ternary) and [operator-linebreak](https://eslint.org/docs/rules/operator-linebreak) from ESLint.

## Problem
The above linting rules should help make nested ternaries like this more readable:

```ts
type all = <Promises extends Array<PProgress.PromiseFactory<unknown> | PromiseLike<unknown>>>(
		promises: readonly [...Promises],
		options?: PProgress.Options
	): PProgress<{
		[Promise_ in keyof Promises]: Promises[Promise_] extends PromiseLike<unknown> ? Awaited<Promises[Promise_]> : (Promises[Promise_] extends PProgress.PromiseFactory<unknown> ? Awaited<ReturnType<Promises[Promise_]>> : Promises[Promise_])
	}>;
```

Personally, I find this more readable:
```ts

type all = <Promises extends Array<PProgress.PromiseFactory<unknown> | PromiseLike<unknown>>>(
		promises: readonly [...Promises],
		options?: PProgress.Options
	): PProgress<{
		[Promise_ in keyof Promises]: (
			Promises[Promise_] extends PromiseLike<unknown>
				? Awaited<Promises[Promise_]>
				: (
					Promises[Promise_] extends PProgress.PromiseFactory<unknown>
						? Awaited<ReturnType<Promises[Promise_]>>
						: Promises[Promise_]
				)
		)
	}>;
```

----

Sorry about not following Issue template. There wasn't one for feature requests but I found a few existing proposals to base this after.

**Comment by bradzacher** [comment]
We ***STRONGLY*** recommend you use automatic code formatters like [prettier](https://www.npmjs.com/package/prettier).

Stylistic lint rules take a lot of effort to write, require ongoing maintenance to add more configuration as people want to fit their preferences, and are a large burden to maintain as new syntax is added.
The configurability also leads to huge fanout [making tests huge, and awful to maintain](https://github.com/typescript-eslint/typescript-eslint/blob/b814e635c1f34139c89e0176727480935dd45cac/packages/eslint-plugin/tests/rules/type-annotation-spacing.test.ts).

It's for these reasons that [eslint has frozen all stylistic lint rule options, and will not accept any new ones](https://eslint.org/blog/2020/05/changes-to-rules-policies).

--- 

That being said, we won't explicitly block someone if they want to spend the time to extend a base rule to support TS syntax - as long as it's well written and thoroughly tested.

**Comment by Josh-Cena** [comment]
Because the ESLint core is also working on [deprecating/removing its formatting rules](https://github.com/eslint/eslint/issues/17522), we will close this. A 3rd-party plugin providing formatting, like https://github.com/eslint-stylistic/eslint-stylistic, can surely support TS OOTB.
