### ISSUE TITLE
`@typescript-eslint/prefer-regexp-exec` does not respect flags

### ISSUE THREAD

**Issue by gabrielecirulli** [typescript-eslint/typescript-eslint#3477]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

When used within a function whose arguments are passed to the `new RegExp` constructor, the `@typescript-eslint/prefer-regexp-exec` misfires.

```
function repro(pattern: string) {
  "hello hello".match(new RegExp(pattern, "gi"))?.reduce(() => []);
}
```

Gets replaced to (when the `eslint --fix` option is set):

```
function repro(pattern: string) {
  new RegExp(pattern, "gi").exec("hello hello")?.reduce(() => []);
}
```

This is an incorrect replacement because they are not equivalent due to the presence of the "g" flag.

**Expected Result**

The replacement shouldn't take place, the rule shouldn't error.

**Actual Result**

The rule returns an error and replaces the match if allowed to.

**Additional Info**

**Versions**

```
typescript 4.3.2
@typescript-eslint/eslint-plugin 4.25.0
@typescript-eslint/parser 4.25.0
eslint 7.27.0
```

**Comment by gabrielecirulli** [comment]
> Please ensure you use the issue templates when you file an issue by clicking the new issue template. Don't bypass the issue wizard by entering or changing the URL.
> 
> Bypassing means you get the wrong issue template and your issue won't be automatically tagged.

I used the template but removed some parts that didn't seem applicable. Is there any information you'd like me to add to the issue?

**Comment by bradzacher** [comment]
> I used the template

Sorry, to clarify. If you create a new issue by clicking the "new issue" button on the Github UI it will take you to https://github.com/typescript-eslint/typescript-eslint/issues/new/choose, which is the issue wizard - through which you can choose an issue template workflow.

But if you manually go to https://github.com/typescript-eslint/typescript-eslint/issues/new, then you will not go via the wizard, and you will get a catch-all template. Your issue will also not get automatically tagged.

The lack of tags is why I know you did not go via the wizard.

Always click the new issue button and follow the wizard to ensure you get the correct template and correct tags.

**Comment by DanKaplanSES** [comment]
I'd like to piggyback off of this because it's the closest thing to the issue I'm experiencing, and it may actually be the same issue in disguise:

```typescript
  const matchCount = (str: string, re: RegExp) => {
    return (str.match(re) || []).length;
  };
```

This triggers the error, but I don't think there's any way it could know if the re has a `/g` at the end or not. I happen to be calling it like this `      expect(actual.matchAll(/<\\w+>.*<\\w+>/g), actual).toEqual(0);`, and this fix changes behavior.

**Comment by rafaelss95** [comment]
If #3855 gets in, this will be fixed as well.
