### ISSUE TITLE
Jsx option doesn't work no matter how i set true or false if project option exists

### ISSUE THREAD

**Issue by ldwonday** [typescript-eslint/typescript-eslint#3505]
I find the [issue 566](https://github.com/typescript-eslint/typescript-eslint/issues/566) is seem to me, but it worked for me.

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```js
{
  parserOptions: {
    parser: '@typescript-eslint/parser',
    extraFileExtensions: ['.vue'],
    project: ['./tsconfig.json'],
    ecmaFeatures: {
      jsx: false,
    },
  },
  parser: 'vue-eslint-parser',
  rules: {
    'dot-notation': 'off',
    '@typescript-eslint/dot-notation': 'warn',
  },
}
```

```vue
<script lang="tsx">
export default {
  name: 'MenuItem',
  functional: true,
  props: {
    icon: {
      type: String,
      default: '',
    },
    title: {
      type: String,
      default: '',
    },
  },
  render(h, context) {
    const { icon, title } = context.props;
    const vnodes = [];

    if (icon) {
      if (icon.includes('el-icon')) {
        vnodes.push(<i class={[icon, 'sub-el-icon']} />);
      } else {
        vnodes.push(<svg-icon icon-class={icon} />);
      }
    }

    if (title) {
      vnodes.push(<span slot="title">{title}</span>);
    }
    return vnodes;
  },
};
</script>

<style scoped>
.sub-el-icon {
  color: currentColor;
  width: 1em;
  height: 1em;
}
</style>

```

**Expected Result**
Can be worked well for ".vue" file.

**Actual Result**
no matter how i set the 'jsx' option true or false, there had a error 
```
  21:23  error  Parsing error: '>' expected

✖ 1 problem (1 error, 0 warnings)
```

**Additional Info**

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.26.1` |
| `TypeScript`                | `4.2.4` |
| `ESLint`                    | `6.8.0` |
| `node`                      | `12.18.3` |

**Comment by bradzacher** [comment]
Please read the documentation:
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#parseroptionsecmafeaturesjsx

**Comment by ldwonday** [comment]
@bradzacher I had read the documentation many times and my eslint config is 
```json
{
  parserOptions: {
    parser: '@typescript-eslint/parser',
    extraFileExtensions: ['.vue'],
    project: ['./tsconfig.json'],
    ecmaFeatures: {
      jsx: false,
    },
  },
  parser: 'vue-eslint-parser',
  rules: {
    'dot-notation': 'off',
    '@typescript-eslint/dot-notation': 'warn',
  },
}
```

it doesn't worked.

**Comment by bradzacher** [comment]
> I had read the documentation many times

Have you? The doc section that I linked to ***exactly*** explains the behaviour.

In case you missed it - here is the relevant snippets from the section that I linked

https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#parseroptionsecmafeaturesjsx

> - if parserOptions.project is provided (i.e. you are using rules with type information):
>   - .js, .jsx, .tsx files are parsed as if this is true.
>   - .ts files are parsed as if this is false.
>   - \*\*\*\****"unknown" extensions (.md, .vue) are parsed as if this is false.*******

I added emphasis to highlight the most relevant line.

**Comment by ldwonday** [comment]
@bradzacher Thank for your reply. I am not understand, in my case if i set the project option the file of '.vue' will parsed with errors and has nothing to do with the jsx option?
