### ISSUE TITLE
parser.createProgram is not being exported

### ISSUE THREAD

**Issue by rdsedmundo** [typescript-eslint/typescript-eslint#3514]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

1. `mkdir typescript-eslint-bug-no-createprogram`
2. `yarn init -y`
3. `yarn add eslint @typescript-eslint/parser`
4. Check `node_modules/@typescript-eslint/parser` exports contents.

Attached screenshots at the bottom.

**Expected Result**

Should be exported.

**Actual Result**

I tried to use inside `eslintrc.js` and it threw saying that `parser.createProgram` is not defined.

**Additional Info**

I tried to import from `@typescript-eslint/typescript-estree` as well and got the same result.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.26.1` |
| `TypeScript`                | `4.3.2` |
| `ESLint`                    | `7.28.0` |
| `node`                      | `14.17.0` |

<img width="718" alt="Screen Shot 2021-06-11 at 16 12 22" src="https://user-images.githubusercontent.com/5482378/121737932-ea20ef00-cacf-11eb-9ab6-1742f0fefda4.png">

Notice on this file above how it's missing a third import but still has a trailing comma, [for some reason `createProgram` is getting stripped from there](https://github.com/typescript-eslint/typescript-eslint/blob/79b510c00f25d76daf741936682e1222b0c994b5/packages/parser/src/index.ts#L5).

<img width="1037" alt="Screen Shot 2021-06-11 at 16 12 40" src="https://user-images.githubusercontent.com/5482378/121737938-eab98580-cacf-11eb-900f-998a4fa22e97.png">

**Comment by bradzacher** [comment]
It's not getting stripped. It hasn't been released yet.
We release to the npm `latest` tag on mondays.

If you want to play with this new api - use our `canary` tag on npm

**Comment by bradzacher** [comment]
@rdsedmundo please comment back once you've tested and let us know how it goes!
We'd love to hear what sort of performance improvements you get.

Worth noting that @JamesHenry is working to make this the default for CLI runs in #3512.
Also as an FYI @uniqueiniquity - look a real-world user already getting onto it!

**Comment by rdsedmundo** [comment]
I wasn't focused on performance improvements (although that will be good in the future!), my use case was writing a custom module resolution (#2771) that enables absolute paths within cross-package imports in a monorepo.

Actually, I ended up using `parserOptions.programs` just, created my own `ts.Program` using the [Compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#customizing-module-resolution) and it worked wonders. Thank y'all so much for enabling this feature.

I also had to duplicate the logic into a custom tsc CLI for running the type checking with the awareness of the absolute paths + a language service for VSCode. It's unfortunate that TypeScript doesn't support a global hook for this in the `tsconfig.json` and we have to duplicate this everywhere. https://github.com/microsoft/TypeScript/issues/16607 which asks for this is about to complete 4 years next week.

**Comment by bradzacher** [comment]
> my use case was writing a custom module resolution (#2771) that enables absolute paths within cross-package imports in a monorepo.

oh shit - I didn't even think about that.
this a really awesome possibility that's enabled with this new API.

I know the original usecase Ben was thinking of was for a large project to reuse a project for both linting and typechecking.
So you could probably share your code around and write your own script wrappers for typechecking and linting (and doing both at the same time).

**Comment by rdsedmundo** [comment]
One difficulty that I'm facing is that the eslint server grows fast in memory usage because it creates a new program almost every time I edit the file in the IDE (because it reads the `eslintrc.js` again).

I proceeded to cache the program using the `tsconfig` path, similarly to what you already do with the 'watch programs', it worked, but the problem now is that my program source files are outdated as I don't have access to the dirty file from the IDE before it's saved on the disk, so I can only see the lint problems upon saving the file.

I'd need to do something similar as [this](https://github.com/typescript-eslint/typescript-eslint/blob/8c7d4592ea93a253adf5137d97c61a1f8b2adbba/packages/typescript-estree/src/create-program/createWatchProgram.ts#L278), but the `useProvidedPrograms` [don't get access to the code variable](https://github.com/typescript-eslint/typescript-eslint/blob/8c7d4592ea93a253adf5137d97c61a1f8b2adbba/packages/typescript-estree/src/parser.ts#L85), and even if it did I'm not sure how `@typescript-eslint` could pass that downstream 🤔 , perhaps it could have an overload like this:

```js
module.exports = {
  parserOptions: {
    programs: [
       (code, filePathIn) => {
         const program = getCachedProgram();
         // here I mimic the same logic from the createWatchProgram.ts#L278
       },
    ]
  }
}
```

Do you have any suggestions? Thanks.

**Comment by rdsedmundo** [comment]
I gave up reinventing the wheel and added support for a `parserOptions.moduleResolver` option.

https://github.com/typescript-eslint/typescript-eslint/pull/3516
