### ISSUE TITLE
ban-ts-ignore is not in "plugin:@typescript-eslint/recommended" despite the docs saying so.

### ISSUE THREAD

**Issue by dashmug** [typescript-eslint/typescript-eslint#353]
It should be recommended according to https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules. But simply extending `plugin:@typescript-eslint/recommended` does not enable the rule.

Adding the rule explicitly in `eslintrc.js` works though.

**Repro**

Repro to follow.

**Expected Result**

**Actual Result**

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.4.2` |
| `@typescript-eslint/parser`        | `1.4.2` |
| `TypeScript`                       | [`3.3.3333`](https://github.com/Microsoft/TypeScript/issues/30032) 😄 |
| `ESLint`                           | `5.15.1` |
| `node`                             | `11.11.0` |
| `yarn`                              | `1.13.0` |

**Comment by bradzacher** [comment]
we really need to add a build step to validate the recommended generation.
there's a number

**Comment by ldrick** [comment]
Thats kinda related to my PR #313 
There we agreed on removing the recommended for new rules, until next Major release.
I should also update the docs for the rules I removed recommended?
