### ISSUE TITLE
Plugin doesn't check .ts and .tsx files out of box?

### ISSUE THREAD

**Issue by wszymanski** [typescript-eslint/typescript-eslint#355]
My ESLint configured for project with `@typescript-eslint/eslint-plugin` (installed as `devDependency`), enabled in plugin section doesn't check my `.ts` and `.tsx` project files, but works on `.js` files. 

Maybe I should use `--ext .js,.ts,.tsx` in the lint script? Is not plugin also for this?

**ESLint config file**

```JSON
module.exports = {
  "extends": ["airbnb"],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "project": "./tsconfig.json"
  },
  "plugins": ["@typescript-eslint"],
  "rules": {
    "no-multiple-empty-lines": ["error", {
      "max": 1
    }],
    "quotes": ["error", "double"],
    "eol-last": ["error", "never"],
    "max-len": ["error", 120]
  }
};
```

Part of package.json file.
```JSON
"scripts": 
  "build": "webpack",
  "watch": "webpack-dev-server --mode development",
  "lint": "eslint ./"
},
```

Please take a look at the below screenshot. We can see just error for `test2.js` file, but not for the same `test2.ts` file (event my IDE doesn't "highlight" error, but I suppose it may be their problem). 

<img width="534" alt="Screenshot 2019-03-15 at 13 36 43" src="https://user-images.githubusercontent.com/141330/54431723-71336100-4727-11e9-8f6a-1c3a2e859f6d.png">

**Expected Result**

Listed errors also for `test1.ts` file.

**Actual Result**

No errors for `test1.ts` file.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.4.2` |
| `@typescript-eslint/parser`        | `1.4.2` |
| `TypeScript`                       | `3.3.3333` |
| `ESLint`                           | `5.3.0` |
| `eslint-config-airbnb`                           | `17.1.0` |
| `eslint-plugin-import`                           | `2.16.0` |
| `eslint-plugin-jsx-a11y`                           | `6.2.1` |
| `eslint-plugin-react`                           | `7.12.4` |
| `node`                             | `10.5.0` |
| `npm`                              | `6.8.0` |

**Comment by ldrick** [comment]
Hi, that is currently not possible, see https://github.com/eslint/eslint/issues/10828
But with this great RFC https://github.com/eslint/rfcs/pull/9 it would be possible.

**Comment by wszymanski** [comment]
Thank you!

**Comment by bradzacher** [comment]
As @ldrick said, this is a limitation of eslint.
By default it only checks `.js` and `.jsx` files.
Currently the ***only*** way to enable checking of other extensions is via the `--ext` CLI arg.

Our parser essentially only does one thing - adds support for parsing files which include typescript language features.
However unfortunately it can only parse the files that eslint passes to it.

**Comment by faisalil** [comment]
What about the browser extension, is there a way to have it enabled and show error on ts/tsx files?

**Comment by bradzacher** [comment]
We only parse and lint the files that we are given by eslint.
You have to check with the maintainer of whatever tool you're using.
