### ISSUE TITLE
[brace-style] --fix places the "else" or "catch" indented by one space

### ISSUE THREAD

**Issue by Entroper** [typescript-eslint/typescript-eslint#3552]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

Running eslint with the `--fix` switch produces incorrect indentation for the brace-style rule.

**Repro**

```ts
export class SomeClass {
    someMethod() {
        if (1 < 2) {
            // always
        } else {
            // never
        }
    }
}
```

This becomes:

```ts
export class SomeClass {
    someMethod() {
        if (1 < 2) {
            // always
        }
 else {
            // never
        }
    }
}
```

The `else` should be at the same level of indentation as the previous closing brace.

```JSON
{
  "rules": {
    "@typescript-eslint/brace-style": ["error", "stroustrup", { "allowSingleLine": true }]
  }
}
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.27.0` |
| `@typescript-eslint/parser`        | `4.27.0` |
| `TypeScript`                       | `4.1.5` |
| `ESLint`                           | `7.6.0` |

**Comment by bradzacher** [comment]
This is how the base rule works.
Please file an issue with ESLint core

https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgYnJhY2Utc3R5bGU6IFtcImVycm9yXCIsIFwic3Ryb3VzdHJ1cFwiLCB7IFwiYWxsb3dTaW5nbGVMaW5lXCI6IHRydWUgfV0gKi9cblxuZXhwb3J0IGNsYXNzIFNvbWVDbGFzcyB7XG4gICAgc29tZU1ldGhvZCgpIHtcbiAgICAgICAgaWYgKDEgPCAyKSB7XG4gICAgICAgICAgICAvLyBhbHdheXNcbiAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgIC8vIG5ldmVyXG4gICAgICAgIH1cbiAgICB9XG59Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMSwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==
