### ISSUE TITLE
[promise-function-async] Should ignore simple arrow functions

### ISSUE THREAD

**Issue by fregante** [typescript-eslint/typescript-eslint#3579]
`promise-function-async` is useful to ensure that Promise-returning functions never throw synchronously. However perhaps there could be an exception to allow "simple" functions without `async`.

For example in this case as long as `fetchTitle` itself follows the rule, the arrow function doesn't have to, because it cannot throw on its own (assuming that the types are correct and that `fetchTitle` exists)

```TS
urls.map((url: string): Promise<string> => fetchTitle(url))
```

This however wouldn't be covered because `parse` could throw inside the arrow function:

```TS
urls.map((url: string): Promise<string> => fetchTitle(parse(url)))
```

I suppose that there are probably enough _"as long as"_ conditions to still justify enforcing the rule, but I wanted to open this issue to both remind myself of this and discuss it with you.

---

## Template

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/promise-function-async": "error"
  }
}
```

```TS
urls.map((url: string): Promise<string> => fetchTitle(url))
```

**Expected Result**

The arrow function won't throw synchronously, so adding `async` doesn't change anything.

**Actual Result**

```
1:8  error    Functions that return promises must be async          @typescript-eslint/promise-function-async
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.27.0` |
| `@typescript-eslint/parser`        | `4.27.0` |
| `TypeScript`                       | `4.3.2` |
| `ESLint`                           | `7.28.0` |
| `node`                             | `14` |

**Comment by JoshuaKGoldberg** [comment]
I'll defer to another maintainer here but yeah, my _gut_ is that saving just the `async` keyword is not worth it. 

Reference in case folks come upon this thread from Google: https://jakearchibald.com/2017/await-vs-return-vs-return-await

**Comment by bradzacher** [comment]
As mentioned - I think that this is a grey area with no clearly defined way to lint it without false-positives or worse, false-negatives.

I think this is a case wherein you should use an `eslint-disable` comment to clearly document why there exists an exception to the rule, as opposed to adding some complex magic or options to the rule to handle very specific cases.

For that reason - we will be rejecting this request.
Thanks for raising an issue!
