### ISSUE TITLE
Create a rule overview

### ISSUE THREAD

**Issue by helmbold** [typescript-eslint/typescript-eslint#3591]
Coming from the front page the GitHub project I haven't found an overview of all rules. 

I suggest to create an [overview like ESLint](https://eslint.org/docs/rules/) has for [all rules provided by typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/docs/rules). Ideally this overview would also show whether a rule is "recommended" and auto-fixable.

![grafik](https://user-images.githubusercontent.com/5079980/123667677-a7cf1000-d83a-11eb-97c2-d7957e668639.png)

**Comment by bradzacher** [comment]
Consider having a look at the package's readme...
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin

**Comment by helmbold** [comment]
Thanks, I wasn't aware of that overview. However, it is a bit hard to find from the front page - and what could be more important than the rules themselves? 

What do you think about adding a link to the [overview](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/README.md) on https://github.com/typescript-eslint/typescript-eslint (file: https://github.com/typescript-eslint/typescript-eslint/blob/master/README.md)?
