### ISSUE TITLE
4.3.4 version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree

### ISSUE THREAD

**Issue by LinkedForest** [typescript-eslint/typescript-eslint#3603]
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.2.0
YOUR TYPESCRIPT VERSION: 4.3.4
Please only submit bug reports when using the officially supported version.

**Comment by bradzacher** [comment]
Do not ignore the issue template. It's there for a reason. It's there so you provide us information so that we can help you. Raising an issue with just the copy pasting warning message is one of the least useful issues you could raise.

Your version is out of date. Update it.
