### ISSUE TITLE
[naming-convention] for Vue mixin

### ISSUE THREAD

**Issue by doox911** [typescript-eslint/typescript-eslint#3614]
The problem is that props are written in camelCase and when the class is writing components, they have a class property. And it is customary to write properties in a project in snake_case. For component files, we have overridden these rules, but mixins have the .ts extension, and therefore fall under the rules that are not intended for components (.vue).

Is it possible to somehow solve this problem without adding the use of camelCase in the .ts files, which will further require verbal agreement on the naming of the class properties?

.eslintrc.js:
```
overrides: [
    {
      files: ['*.vue', '*.ts'],
      rules: {
        indent: 'off',
        camelcase: 'off',
        'class-methods-use-this': 'off',
        '@typescript-eslint/naming-convention': [
          'error',
          {
            selector: 'objectLiteralProperty',
            format: ['snake_case', 'UPPER_CASE', 'PascalCase', 'camelCase'],
          },
          {
            selector: 'variable',
            format: ['snake_case', 'UPPER_CASE'],
          },
          {
            selector: 'function',
            format: ['camelCase', 'PascalCase'],
          },
          {
            selector: 'class',
            format: ['PascalCase'],
          },
          {
            selector: 'classProperty',
            format: ['snake_case'],
            leadingUnderscore: 'allowSingleOrDouble',
          },
          {
            selector: 'typeAlias',
            format: ['PascalCase'],
          },
          {
            selector: 'interface',
            format: ['PascalCase'],
            prefix: ['I'],
          },
          {
            selector: 'parameter',
            format: ['snake_case'],
          },
          {
            selector: 'typeParameter',
            format: ['snake_case', 'PascalCase'],
          },
          {
            selector: 'enum',
            format: ['UPPER_CASE'],
          },
        ],
      },
    },
    {
      files: ['*.vue'],
      rules: {
        '@typescript-eslint/naming-convention': [
          'error',
          {
            selector: 'classProperty',
            format: ['snake_case', 'camelCase'],
            leadingUnderscore: 'allowSingleOrDouble',
          },
        ],
      },
    },
  ],
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.27.0` |
| `@typescript-eslint/parser`        | `4.27.0` |
| `TypeScript`                       | `4.3.4` |
| `ESLint`                           | `7.29.0` |
| `node`                             | `16.3.0` |

**Comment by bradzacher** [comment]
Why not just create a naming convention for your Vue component files which allows you to differentiate them?

Eg at FB all files are `.js` files, and we use the convention `.react.js` for react component files.

Same thing could apply here. Just name files like `.vue.ts` or something and now you can uniquely select on them for linting purposes.

You could even create a lint rule to enforce this file naming convention. I'm sure the Vue ESLint plugin could find such a rule valuable for standardisation across the ecosystem.

**Comment by doox911** [comment]
> Why not just create a naming convention for your Vue component files which allows you to differentiate them?
> 
> Eg at FB all files are `.js` files, and we use the convention `.react.js` for react component files.
> 
> Same thing could apply here. Just name files like `.vue.ts` or something and now you can uniquely select on them for linting purposes.
> 
> You could even create a lint rule to enforce this file naming convention. I'm sure the Vue ESLint plugin could find such a rule valuable for standardisation across the ecosystem.

This is a great idea! Thank you!
