### ISSUE TITLE
Parsing error: Cannot read file \e2e\tsconfig.app.json

### ISSUE THREAD

**Issue by turbolego** [typescript-eslint/typescript-eslint#3618]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```
$ npm run lint-and-fix

> frontend@0.0.0 lint-and-fix
> eslint . --ext .ts --fix


C:\DATA\IdeaProjects\test\frontend\e2e\src\app.e2e-spec.ts
  0:0  error  Parsing error: Cannot read file 'c:\data\ideaprojects\test\frontend\e2e\tsconfig.app.json'

C:\DATA\IdeaProjects\test\frontend\e2e\src\app.po.ts
  0:0  error  Parsing error: Cannot read file 'c:\data\ideaprojects\test\frontend\e2e\tsconfig.app.json'

✖ 2 problems (2 errors, 0 warnings)


```
"C:\DATA\IdeaProjects\test\frontend\src\tslint.json"
```JSON
{
    "extends": "../tslint.json",
    "rules": {
        "directive-selector": [
            true,
            "attribute",
            "app",
            "snake_case"
        ],
        "component-selector": [
            true,
            "element",
            "app",
            "kebab-case"
        ]
    }
}

```

**Expected Result**

✖ 0 problems (0 errors, 0 warnings)

**Actual Result**

✖ 2 problems (2 errors, 0 warnings)

**Additional Info**

I upgraded from tslint to eslint

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `^4.28.2` |
| `@typescript-eslint/parser`        | `4.16.1` |
| `TypeScript`                       | `4.0.5` |
| `ESLint`                           | `^7.6.0` |
| `node`                             | `v12.18.0` |

**Comment by bradzacher** [comment]
I'm not sure why you've raised this as an issue? The error message is pretty self-explanatory:

> Parsing error: Cannot read file 'c:\data\ideaprojects\test\frontend\e2e\tsconfig.app.json'

---

Also if you're going to raise an issue - provide as much information as possible.
You're an engineer. You should know that just an error message and unrelated config is not enough information.

**Comment by turbolego** [comment]
> I'm not sure why you've raised this as an issue? The error message is pretty self-explanatory:
> 
> > Parsing error: Cannot read file 'c:\data\ideaprojects\test\frontend\e2e\tsconfig.app.json'
> 
> Also if you're going to raise an issue - provide as much information as possible.
> You're an engineer. You should know that just an error message and unrelated config is not enough information to really help you.. at all

This is my first time working with tslint and eslint.
I was tasked with upgrading from tslint to eslint in an old project, and that worked fine, i was able to solve over 6500 lint errors in the code using eslint.

But i have no idea what the tsconfig.app.json is for, if anything?
Can i just delete the tsconfig.app.json file?

Sorry if it seems like I'm inconsiderate, but I'm not really familiar with either tslint or eslint. 😶

Good job making a linting solution that even n00bs like me can use! ❤️😊

**Comment by bradzacher** [comment]
> But i have no idea what the tsconfig.app.json is for, if anything?
> Can i just delete the tsconfig.app.json file?

I can't answer that question - I don't have the context about your codebase - so I don't know what it is or why it was added. You'd have to talk to another engineer working on your project about the file.

If I had to guess - it's something to do with your project's angular config based on a quick google search. Whether it's required is dependent on your project's setup.

**Comment by turbolego** [comment]
> > But i have no idea what the tsconfig.app.json is for, if anything?
> > Can i just delete the tsconfig.app.json file?
> 
> I can't answer that question - I don't have the context about your codebase - so I don't know what it is or why it was added. You'd have to talk to another engineer working on your project about the file.
> 
> If I had to guess - it's something to do with your project's angular config based on a quick google search. Whether it's required is dependent on your project's setup.

Thanks! I'll ask around if anyone knows. 😁
