### ISSUE TITLE
"parserOptions.project" parsing error for included file

### ISSUE THREAD

**Issue by ahfarmer** [typescript-eslint/typescript-eslint#3619]
Getting this error
```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: app/src/components/LoggedInApp.tsx.
The file must be included in at least one of the projects provided.eslint
```

I've seen other issues like this one: https://github.com/typescript-eslint/typescript-eslint/issues/967

But in those the solution is to add to the `include` property, which I have already done:

```
  "include": ["./src/**/*"],
```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

Creating a repro will be difficult but i can do it if the issue doesn't have an easy fix.

**Versions**

All version are the absolute latest as of this moment.

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.28.2` |
| `@typescript-eslint/parser`        | `4.28.2` |
| `TypeScript`                       | `4.3.5` |
| `ESLint`                           | `7.30.0` |
| `node`                             | `16.14.2` |

<img width="658" alt="Screen Shot 2021-07-08 at 11 44 32 AM" src="https://user-images.githubusercontent.com/597825/124974856-27e73980-dfe2-11eb-96fa-193e0983e471.png">

**Comment by bradzacher** [comment]
Could you provide more information?
What's your folder structure like?
What's your tsconfig?

Have you read the FAQ article?
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-get-errors-telling-me-the-file-must-be-included-in-at-least-one-of-the-projects-provided

**Comment by ahfarmer** [comment]
This was my bad, sorry!

I didn't think I was using parserOptions.project, but it turns out I was extending a`.eslintrc.js` file that was. I just added the missing line there and all is good now.

Appreciate the response ❤️
