### ISSUE TITLE
[rulename] issue title

### ISSUE THREAD

**Issue by Vijay-eZee** [typescript-eslint/typescript-eslint#3628]
**Repro**

1. Install @nuxtjs/eslint-config-typescript: "^6.0.1" and @typescript-eslint/eslint-plugin: "^4.28.1"
2. Extends in eslint configuration file
extends: [
'@nuxtjs/eslint-config-typescript',
'plugin:@typescript-eslint/recommended',
]
**Expected Result**
Should parse .vue file

**Actual Result**

Getting vue parsing error
**Additional Info**
![eslint_vue_parser_error](https://user-images.githubusercontent.com/60382741/125239454-4ca32000-e306-11eb-830b-08a49aa989fa.png)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.28.2` |
| `@nuxtjs/eslint-config-typescript`        | `6.0.1` |
| `node`                             | `12.18.2` |

**Comment by bradzacher** [comment]
You ignored so much of the issue template that I can't help you.
And you also left the title as a useless title.

Where's the config?
Where's the code?
Where's the repro?

If you want help, file something with some information please.
