### ISSUE TITLE
[consistent-type-imports] Using with --fix changes constructor imports to type imports in nest and angular

### ISSUE THREAD

**Issue by yharaskrik** [typescript-eslint/typescript-eslint#3630]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

https://github.com/yharaskrik/eslint-type-import-repro

`yarn nx affected:lint --fix`

**Expected Result**

I would expect that concrete classes that are needed for dependency injection, `ClassType`, would be left as non-type imports and the types that are not needed to be concrete are changed to type only imports, `InterfaceType`. I realize this is probably framework dependant since not everything uses DI and needs concrete classes at runtime.

**Actual Result**

As it stands the imports in `app.service.ts` are not using type imports. when running `yarn nx affected:lint --fix` (which uses eslint and @typescript-eslint under the hood) it changes the import to `import type { ClassType, InterfaceType } from './type';` which then breaks the nest server as the `ClassType` is a concrete class that is needed for dependency injection.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `^4.28.2` |
| `@typescript-eslint/parser`        | `^4.28.2` |
| `TypeScript`                       | `~4.2.4` |
| `ESLint`                           | `7.22.0` |
| `node`                             | `12.22.1` |

**Comment by bradzacher** [comment]
We have support for this, but the issue here is that you don't use type-aware linting (at least in your repro you don't), so we can't detect if you've turned on `emitDecoratorMetadata`, so we default to off.

We don't currently have a mechanism to allow you to turn this on via `parserOptions`.

---

Why do we do detection? Because the meaning is vastly different if you have `emitDecoratorMetadata` on vs if you have it off - as you can see.

**Comment by yharaskrik** [comment]
Thanks for your response @bradzacher! How would I go about turning on type-aware linting? 

I can understand you probably wouldn't want that turned on by default of course! For us our whole stack is Nest+Angular (which both use decorators). I can see if I can work on a PR at some point, is there a work around for now that I can try (I would assume manually use type-aware linting?)?

**Comment by bradzacher** [comment]
> is there a work around for now that I can try

Yup - the only option is to turn on type-aware linting:
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md
