### ISSUE TITLE
Eslint ignores typescript plugins

### ISSUE THREAD

**Issue by brianconnoly** [typescript-eslint/typescript-eslint#3645]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

Hi there!

I think my problem is fundamental and don't need specific code to repro

I use generic eslint configuration

Also I use typescript plugin for css modules
```JSON
    "plugins": [
      {
        "name": "typescript-plugin-css-modules",
        "options": {
          "classnameTransform": "camelCaseOnly",
          "customMatcher": "\\.less$",
          "customRenderer": "node_modules/less-plugin-aliases/lib/customRender.js"
        }
      }
    ]
```

This plugin modifies source code and treats .less files as type declarations

I see result of its work in intellisence, but eslint fail to understand it because it doensn't get modified source

![image](https://user-images.githubusercontent.com/576653/126359171-ed5da2cb-ae10-48fd-9970-4ae954887804.png)

This specific case can be solved by adding separate declaration file
```TS
declare module '*.less' {
    const classes: { [key: string]: string };
    export default classes;
}
```

But the core problem is that eslint ignores augmented output from plugins and deals with raw code

I am writing my own TS-plugin that augments code more complex way
I see results of its work in editor via intellisence, but eslint refuses to understand it and I get error (and no type-aware linting though)

Here we can see that type of `state.logo` is `Logo`, but for eslint it is still `any`
![image](https://user-images.githubusercontent.com/576653/126359685-cefde274-b8ab-4f16-bcc2-5b81ea3967ab.png)

**Expected Result**

I expect that eslint will work with code processed with ts-plugins

**Actual Result**

Eslint ignores typescript plugins and work with raw code

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.28.4` |
| `TypeScript`                | `4.3.5` |
| `ESLint`                    | `7.26.0` |
| `node`                      | `14.17.0` |

**Comment by bradzacher** [comment]
From the TS docs https://www.typescriptlang.org/tsconfig#plugins:

> Plugins - `plugins`
> List of language service plugins to run inside the editor.
> Language service plugins are a way to provide additional information to a user based on existing TypeScript files. They can enhance existing messages between TypeScript and an editor, or to provide their own error messages.

TS plugins ***only*** work with the TS language server used by IDEs.
They do not work with other tools. I.e. they do not work with `tsc`.

We do not run a typescript language server, hence we do not support TS plugins.

**Comment by brianconnoly** [comment]
Maybe I can somehow hack parser?
Replace some methods with my own which will run plugins before creating ast
