### ISSUE TITLE
Using TC39 proposals (Babel) with @typescript-eslint/parser

### ISSUE THREAD

**Issue by hyoretsu** [typescript-eslint/typescript-eslint#3656]
Like #1304 tried to ask 2 years ago, is there any way to use proposals with `@typescript-eslint/parser`? We can get it to work by disabling VSCode's JS/TS validation, adding the necessary Babel (which is used to parse TS by many) modules and then enabling `@babel/eslint-parser`

The problem being, Babel's parser doesn't support TS, and neither does yours support proposals/loading babel modules. Although some `@typescript-eslint/plugin` do work with Babel's parser, others like `@typescript-eslint/naming-convention` don't, and since it doesn't support TS it throws error at anything type-related, starting from imports "being unused".

**Comment by bradzacher** [comment]
We are directly built on top of typescript, so we can only parse what they parse. So if TS doesn't support it, neither do we.
No way around that, sorry.

Babel does support TS though - you only need to configure it to.

**Comment by hyoretsu** [comment]
Babel's eslint parser I mean. They explicitly state in their docs:

"While @babel/eslint-parser can parse TypeScript, we don't currently support linting TypeScript using the rules in @babel/eslint-plugin. This is because the TypeScript community has centered around @typescript-eslint and we want to avoid duplicate work. Additionally, since @typescript-eslint uses TypeScript under the hood, its rules can be made type-aware, which is something Babel doesn't have the ability to do."

I'll try and see if there are some Babel shenanigans to do that ESTree thing @typescript-eslint/parser does. Unfortunately ESLint doesn't allow multiple parsers to be set up for the same kind of file.

**Comment by bradzacher** [comment]
There are some differences between the two. We have loosely worked together on things but we haven't had the time or resources to work on a true standardisation effort.

There's just so little need for one. It's a very rare case where someone is using babel for TS plus features that TS doesn't support. Manily because TS won't support parsing or typechecking those files.
