### ISSUE TITLE
ESLint doesn't report unsupported feature errors when using TS parser

### ISSUE THREAD

**Issue by FunctionDJ** [typescript-eslint/typescript-eslint#3704]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

Here's a repo with the minimum of files to reproduce the issue:
https://github.com/FunctionDJ/ts-eslint-issue

Compare the output of `npm test` with when the parser is specified (no error) and when not (parsing error).

**Expected Result**

When the TS-ESLint parser is used, syntax errors outside the `lib` / `parserOptions` range should still be reported as errors.
E.g. `Parsing error: Unexpected token .` when using conditional chaining without the required ECMA version specified.

**Actual Result**

When using the TS-ESLint parser, no syntax errors of 'unsupported' (by config) language features are reported.

**Additional Info**

No exceptions, tested via CLI.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.28.5` |
| `TypeScript`                | `4.3.5` |
| `ESLint`                    | `7.32.0` |
| `node`                      | `14.17.0` |

**Comment by bradzacher** [comment]
Our parser just parses the code using TS.

TS is a transpiler, meaning it converts syntax to your required target. Thus it doesn't matter what your config is - optional chaining is always supported.

When writing pure JS, it is up to you to write and validate your code. Our parser is not a code validator. If you want to ensure that your JS codebase doesn't use specific features, consider a rule like [no-restricted-syntax](https://eslint.org/docs/rules/no-restricted-syntax) to customise your syntax banning.

Alternately consider using a pure-js parser.

**Comment by FunctionDJ** [comment]
Thank you. For anyone who comes across this, I asked on a Discord and someone found this these ESLint rules, which should work just fine on .js files with the TypeScript parser: https://eslint-plugin-es.mysticatea.dev/
