### ISSUE TITLE
[naming-convention] Extend functionality of naming-convention with new feature

### ISSUE THREAD

**Issue by alexey1966** [typescript-eslint/typescript-eslint#3720]
Sometimes it’s necessary to have prefix “I” for interfaces only in case if at least one method exists in it. According to current functionality I didn’t find a way how it can be accomplished. I suggest to extend functionality with a new feature to add condition of rule, based on text data of the whole method. Or you can suggest another approaches.

I am willing to contribute my code and add functionality of my own.

**Comment by bradzacher** [comment]
Thanks for the request!

Unfortunately this is too specific of a request for us to accept into the codebase. I doubt it'll see much, if any use outside your project.

Feel free to locally fork the rule for your project and add the option there!
