### ISSUE TITLE
[no-unused-vars] problem parsing html file

### ISSUE THREAD

**Issue by HarelM** [typescript-eslint/typescript-eslint#3721]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MapLibre GL JS debug page</title>
    <meta charset='utf-8'>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='stylesheet' href='../dist/maplibre-gl.css' />
    <style>
        body { margin: 0; padding: 0; }
        html, body, #map { height: 100%; }

        #checkboxes {
            position: absolute;
            background: #fff;
            top:0;
            left:0;
            padding:10px;
        }
    </style>
</head>

<body>
<div id='map'></div>
<div id='checkboxes'>
    <select onchange='pickInterpolation(this)'>
        <option value='rgb'>rgb</option>
        <option value='hcl'>hcl</option>
        <option value='lab'>lab</option>
    </select>
</div>

<script src='../dist/maplibre-gl-dev.js'></script>
<script>

var map = window.map = new maplibregl.Map({
    container: 'map',
    zoom: 2.5,
    center: [-77.01866, 38.888],
    style: 'https://demotiles.maplibre.org/style.json',
    hash: true
});

map.addControl(new maplibregl.NavigationControl());
map.addControl(new maplibregl.GeolocateControl());
map.addControl(new maplibregl.ScaleControl());

map.on('load', function() {
    map.addSource('geojson', {
        "type": "geojson",
        "data": "https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_110m_admin_0_countries.geojson"
    });

    map.addLayer({
        "id": "countries",
        "type": "fill",
        "source": "geojson",
        "paint": {
            "fill-color": {
                "property": "pop_est",
                "colorSpace": "lab",
                "stops": [
                    [0, 'blue'],
                    [140041247, 'red']
                ]
            }
        }
    }, 'country-label-lg');
});

function pickInterpolation(input) {
    map.setPaintProperty('countries', 'fill-color', {
        "property": "pop_est",
        "colorSpace": input.value,
        "stops": [
            [0, 'blue'],
            [140041247, 'red']
        ]
    });
}

</script>
</body>
</html>
```
tsconfig:
https://github.com/maplibre/maplibre-gl-js/blob/6d0feff3b8b41fae400898d9c1caf93842f98639/tsconfig.json#L1

**Expected Result**
No warning

**Actual Result**
```
maplibre-gl-js/debug/color_spaces.html
  70:10  warning  'pickInterpolation' is defined but never used  @typescript-eslint/no-unused-vars
```

**Additional Info**
I'm using a mixed project of typescript and javascript but I'm using the same rules for both, it might be related.
The project can be found in github as can be seen above.
Debug run was too long on the project, did you mean run the debug only on the relevant case? I'm not sure I know how to do it.
I have this in my project for additional two html files so this seems like a problem that is not specific to exactly this example...

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.29.1` |
| `@typescript-eslint/parser`        | `4.29.1` |
| `TypeScript`                       | `4.3.5` |
| `ESLint`                           | `7.2.6` |
| `node`                             | `14.17.0` |

**Comment by bradzacher** [comment]
Our scope analysis does not support finding string references to variables within HTML attributes.

**Comment by HarelM** [comment]
Thanks for the quick response!
What can I do besides disabling this rule then?

**Comment by bradzacher** [comment]
use a disable comment?
really your only option.
most tools weren't really designed to work with embedded scripts like that.
