### ISSUE TITLE
[ban-types] recommended way to specify "any object type" on the left side of `extends` clause

### ISSUE THREAD

**Issue by Hypnosphi** [typescript-eslint/typescript-eslint#3758]
ban-types forbids both `{}` and `object` types by default and I agree with the reasoning behind it. Given that, what would be the best way to describe `T extends <any object type>`? `T extends Record<string, unknown>` doesn't accept custom interfaces:

```
function fn<T extends Record<string, unknown>>(param: T) {
  // I should be able to do things like `key in param` and `weakMap.set(param, value)` here
}
interface Foo {
    foo: string
}
declare const foo: Foo
fn(foo)
```
https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMMAeAKogpgDylsAEwGdEAlLCOAJ0NWKmpjAHMAaRcAazDgHcwAPkEAKAA4BDahIC2ALkToAlIgDeAXwBQzfNWASIWRADE4cNZsRXkZhQyatNWwpQA2Uo1TAMbcBabhNFBFgMyVNIA

```
Argument of type 'Foo' is not assignable to parameter of type 'Record<string, unknown>'.
  Index signature is missing in type 'Foo'.
```

**Comment by bradzacher** [comment]
`object` is something I want to relax with the next version - just use that.

Interfaces are tricky to work with generically because of the index signature problem.
