### ISSUE TITLE
Does typescript-estree support for newer typescript version

### ISSUE THREAD

**Issue by umardevid** [typescript-eslint/typescript-eslint#3761]
**Additional Info**
I have installed @typescript-eslint/typescript-estree with typescript 4.3.5 that return info 

```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.1.0

YOUR TYPESCRIPT VERSION: 4.3.5
```

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `latest` |
| `TypeScript`                           | `4.3.5` |
| `node`                                 | `14.17.5` |

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint#supported-typescript-version

Please check out the docs.
