### ISSUE TITLE
No definition and export TSPrivateIdentifier declaration from @typescript-eslint/ast-spec

### ISSUE THREAD

**Issue by gwsbhqt** [typescript-eslint/typescript-eslint#3804]
- [ ] I have tried restarting my IDE and the issue persists.
- [ ] I have updated to the latest version of the packages.
- [ ] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Question**

Recently I am using the @typescript-eslint suite to build custom rules, but I found that some definitions and exports seem to be missing. Is it because I have overlooked something?

For example:

```typescript
class A {
    #A
}
```

I use @typescript-eslint/parser in https://astexplorer.net/ to view the syntax tree, and found a type node of TSPrivateIdentifier.

And after printing the node information, it is found that this type also exists.

But the strange thing is that I did not find any related definitions and exports.

![image](https://user-images.githubusercontent.com/16471930/131210749-291fd47b-0dff-4dc8-8b32-26c42a1bb25e.png)

![image](https://user-images.githubusercontent.com/16471930/131210778-18b0f562-c6a0-4500-bc37-aa9b17a0edad.png)

![image](https://user-images.githubusercontent.com/16471930/131210872-02ca6adc-06b0-4685-877c-0dddce8ebf48.png)

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.29.3` |
| `TypeScript`                | `4.4.2` |
| `ESLint`                    | `7.32.0` |
| `node`                      | `16.7.0` |

**Comment by bradzacher** [comment]
See #3430
