### ISSUE TITLE
[Feature Request] [ESLint-Plugin] [Rules] Include TypeScript typings and Options interfaces/types in published npm package.

### ISSUE THREAD

**Issue by AllySummers** [typescript-eslint/typescript-eslint#3816]
Apologies for not using the issue template, it didn't seem to fit in with a feature request. Also sorry if this is breaking any rules.

I'm trying to make a package (even if it's only me who uses it) for eslint rule configs in TypeScript, and I can see that in your repo you already create TypeScript interfaces/types for the config a rule accepts, however these aren't present (from what I could see at least) when installing from npm in the node_modules.

I can see in all/most of your rules you have an `Options` interface/type (like [here](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/ban-ts-comment.ts)) and it would be very appreciated if it could be somehow changed to include these in what is published to npm, as it would save me a lot of duplication and time of having to copy what's already been done.

[What my project is so far](https://github.com/AllySummers/eslint-typescript-config/tree/master/packages/eslint-typescript-config/src/lib) (it's extremely early, I just spent the last few hours TypeScript-ifying the core ESLint rules)

**Comment by bradzacher** [comment]
There's an old issue for this but I CBF finding it amongst the pile of issues we have.

But the answer to the request is no, sorry.
The option types declared for rules are often not very correct - they are based on some idealistic view of the world or they make some assumptions. In short - they are designed purely for internal development and not intended to 100% match the JSON schema.

I've played with this idea before - #1296 and other users have too - #3227.
It's a great idea and I wish I had the time to build out the tooling and infra to make this a reality.

In terms of getting types for the rules - the better way to do so is to generate the types yourself from the rule's JSON schema. This way you can be sure the types 100% match the schema you're working with.
There are links to some scripts in #1296 which can help you do this - I've already proven the concept!
