### ISSUE TITLE
Accept `readonly RuleFix[]` on `context.report({ fix })`

### ISSUE THREAD

**Issue by rafaelss95** [typescript-eslint/typescript-eslint#3829]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```ts
context.report({
  fix(fixer) {
    const fixes = [...] as const;
    return fixes;
  }
});
```

**Expected Result**
No errors :).

**Actual Result**
<img width="674" alt="readonly not allowed" src="https://user-images.githubusercontent.com/11965907/131602712-711e6a68-1c30-40d3-8ee3-0ee85160ec25.png">

**Additional Info**
A `readonly []` is already accepted for `suggestions`. Probably doing this change would be sufficient (I can take this if accepted):

https://github.com/typescript-eslint/typescript-eslint/blob/0bb878b5306c7a946e856d7a3f6f0ac04646fe20/packages/experimental-utils/src/ts-eslint/Rule.ts#L115-L117

```diff
type ReportFixFunction = (
  fixer: RuleFixer,
- ) => null | RuleFix | RuleFix[] | IterableIterator<RuleFix>;
+ ) => null | RuleFix | readonly RuleFix[] | IterableIterator<RuleFix>;
```

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/experimental-utils` | `4.29.3` |
| `TypeScript`                            | `4.4.2` |
| `node`                                  | `12.22.5` |

**Comment by bradzacher** [comment]
happy to accept a PR!
