### ISSUE TITLE
Cannot use with Node 14?

### ISSUE THREAD

**Issue by AgainPsychoX** [typescript-eslint/typescript-eslint#3832]
- [x] I have tried restarting my IDE and the issue persists. 
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

I just wanted to deploy my Firebase Cloud Functions, it passes eslint and build nicely locally (Typescript compilation). However, I can't deploy the functions project, because it fails to build in the cloud.

**Expected Result**

It build locally, so it should build in cloud too.

**Actual Result**

In Cloud Functions console I can see:
```
Build failed: npm ERR! @types/json-schema not accessible from @typescript-eslint/experimental-utils\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /www-data-home/.npm/_logs/2021-09-02T09_43_57_821Z-debug.log; Error ID: beaf8772
```
This error does not happen when (clean) installing or building the project locally.

_Please note I don't have access to complete log file._

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/parser` | `4.30.0` |
| `@typescript-eslint/experimental-utils` | `4.30.0` |
| `TypeScript`                            | `4.4.2` |
| `node`                                  | `14` (in the Cloud),<br>`16.3.0` (locally) |

It seems Node 14 have some issues.

**Comment by bradzacher** [comment]
We test install against all supported node versions - which includes node 14 and have no issues.
Likely it's an issue with your installation process given that it only happens in your cloud environment.

Without any more information - there's not a lot I can do to help here.
