### ISSUE TITLE
[prefer-return-this-type] Auto-fix does not support generic parameters

### ISSUE THREAD

**Issue by amikheychik** [typescript-eslint/typescript-eslint#3842]
Autofixer for the  `@typescript-eslimt/prefer-return-this-type` replaces only class name, but skips generic parameters.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/prefer-return-this-type": "warn"
  }
}
```

```TS
class Animal<T> {
  eat(): Animal<T> {
    console.log("I'm moving!");
    return this;
  }
}

class Cat<T> extends Animal<T> {
  meow(): Cat<T> {
    console.log('Meow~');
    return this;
  }
}
```

**Expected Result**

```
class Animal<T> {
  eat(): this {
    console.log("I'm moving!");
    return this;
  }
}

class Cat<T> extends Animal<T> {
  meow(): this {
    console.log('Meow~');
    return this;
  }
}
```

**Actual Result**

```
class Animal<T> {
  eat(): this<T> {
    console.log("I'm moving!");
    return this;
  }
}

class Cat<T> extends Animal<T> {
  meow(): this<T> {
    console.log('Meow~');
    return this;
  }
}
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.30.0` |
| `@typescript-eslint/parser`        | `4.30.0` |
| `TypeScript`                       | `4.3.4` |
| `ESLint`                           | `7.32.0` |
| `node`                             | `14.16.0` |

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Comment by bradzacher** [comment]
Happy to accept a PR!
