### ISSUE TITLE
[@typescript-eslint/naming-convention] Request: Allow modifier "destructured" on "objectLiteralProperty"

### ISSUE THREAD

**Issue by Pentadome** [typescript-eslint/typescript-eslint#3850]
```
const { X,  Y }  = getThing();

```
Currently Eslint can be configured to allow X and Y, because they are destructured properties,  to be left PascalCase even though normally camelCase must be used.

```
const thing = { X,  Y }; // <- Error

```
But right now, it can't be configured to allow the above to stay PascalCase.

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#individual-selectors

You can use the `objectLiteralProperty` selector

**Comment by Pentadome** [comment]
`Allowed modifiers: public, requiresQuotes.`
