### ISSUE TITLE
Optimize by sharing AST with typescript

### ISSUE THREAD

**Issue by Brian-Bartels** [typescript-eslint/typescript-eslint#3860]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Question**

Are there configurable optimizations where the typescript compiler and typescript-eslint/parser can share the same AST so that Lint and build both use cached versions of the AST in order to optimize both. 

Thank you for your time

**Comment by bradzacher** [comment]
The two ASTs are physically incompatible - so there's nothing that can be shared.
Which is the entire reason that this project exists.

TypeScript uses its own representation for the AST, and ESLint uses the ESTree representation.

ESLint's engine (and all ESLint rules) explicitly have to deal with the ESTree representation - which is the entire reason this project exists.
Our "parser" isn't actually a parser - it's actually a translator - it translates the TS AST to the ESTree AST (or rather - the ESTree AST with our extensions to support TS syntax).

**Comment by Brian-Bartels** [comment]
@bradzacher I suppose that's my point though. I build my code frequently. And I lint frequently as well. Could the AST generated by the typescript compiler be reused between those two actions. Instead of recompiling for both actions?

**Comment by bradzacher** [comment]
Sorry I may have misunderstood what you are saying originally.

Are you saying you want the parser to reuse the same "program" (TS term) that is used to typecheck your application?

If yes - then the answer is "yes and no".

1) We would have to build our own CLI to wrap both TS and ESLint and the tooling to share the "program" between the two.
    - This is entirely technically feasible to solve
    - However it would require building out that CLI and the required infra (a non-trivial amount of work).
2) In IDEs each extension is 100% isolated from one-another - meaning that the ESLint extension cannot access the "program" used by the TypeScript extension.
    - This is impossible to solve directly, and instead needs to be solved in other ways
    - For example as a custom TS LSP plugin - https://github.com/Quramy/typescript-eslint-language-service.
    - Though it's worth noting that a TS LSP plugin then relies on the TS LSP running on your code - which then precludes you from using ESLint rules on other files (eg markdown, vue).

It's worth noting that the two solutions are incompatible, and would require different tooling etc to support.

**Comment by Brian-Bartels** [comment]
That answered my question. If I end up implementing either of those I'll definitely bring it back here and propose it as a feature! Thanks so much @bradzacher
