### ISSUE TITLE
no-non-null-assertion when in an rxjs pipe

### ISSUE THREAD

**Issue by grosch** [typescript-eslint/typescript-eslint#3866]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "extends": {
    "plugin:@typescript-eslint/recommended"
  }
}
```

```TS
this.supportControl.enabled$
    .pipe(
        combineLatestWith(this.room$),
        map(x => x[1]),
        filter(x => !!x),
        untilDestroyed(this)
    )
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    .subscribe(x => this.supportControl.setEnable(x!.itEditor))
```

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "noImplicitAny": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2017",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

**Expected Result**

It would be awesome if eslint noticed that there's a filter in that chain which ensures that a value will always make it to the subscribe block, so that I don't have to add the comment to disable the force unwrap. 

**Actual Result**

It tells me to not use a non-null-assertion

**Additional Info**

I'm sure what I'm asking is amazingly hard to do, but if I don't ask, it'll never happen :)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.29.3` |
| `@typescript-eslint/parser`        | `4.29.3` |
| `TypeScript`                       | `~4.3.5` |
| `ESLint`                           | `^7.31.0` |
| `node`                             | `v12.19.0` |

**Comment by bradzacher** [comment]
could you please include an isolated example?
it's impossible to investigate this when you've provided a `this` expression with a property that's all untyped.

**Comment by rafaelss95** [comment]
Sorry for chim in, but it has nothing to do with `rxjs` much less with `@typescript-eslint`, this is how Typescript actually infers the expression you wrote. You can check it out this bunch of related issues/questions for deep explanations: 

- https://github.com/microsoft/TypeScript/issues/5101
- https://github.com/microsoft/TypeScript/issues/7657
- https://github.com/microsoft/TypeScript/issues/10734
- https://github.com/microsoft/TypeScript/issues/16069
- https://github.com/microsoft/TypeScript/issues/19640
- https://github.com/ReactiveX/rxjs/issues/3125
- https://github.com/angular/angular/issues/21777
- https://stackoverflow.com/questions/43010737/way-to-tell-typescript-compiler-array-prototype-filter-removes-certain-types-fro
- https://stackoverflow.com/questions/43118692/typescript-filter-out-nulls-from-an-array
- https://stackoverflow.com/questions/62032214/why-cant-typescript-infer-type-from-filtered-arrays

...and so many others.

---

To avoid the non-null assertion operator or maybe a typecast, you must use a typeguard:

```ts
this.supportControl.enabled$
    .pipe(
        combineLatestWith(this.room$),
        map(x => x[1]),
        filter((x): x is NonNullable<SOME_TYPE> => !!x),
        untilDestroyed(this)
    )
    .subscribe(x => this.supportControl.setEnable(x.itEditor))
```

What I usually do to reuse in multiple places is to create an operator:

```ts
export function rejectNil <T>(): OperatorFunction<T, NonNullable<T>> {
  return pipe(filter((value): value is NonNullable<T> => value !== null && value !== undefined));
}
```

and I use it like this:

```ts
this.supportControl.enabled$
    .pipe(
        combineLatestWith(this.room$),
        map(x => x[1]),
        filter(rejectNil),
        untilDestroyed(this)
    )
    .subscribe(x => this.supportControl.setEnable(x.itEditor))
```

**Comment by grosch** [comment]
@bradzacher Thank you so much for your amazing answer! What you showed is definitely the correct thing to do, as opposed to modifying the eslint rules.
