### ISSUE TITLE
Confusing docs for `isParenthesized`

### ISSUE THREAD

**Issue by rafaelss95** [typescript-eslint/typescript-eslint#3885]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**
https://github.com/typescript-eslint/typescript-eslint/blob/1c1b572c3000d72cfe665b7afbada0ec415e7855/packages/experimental-utils/src/ast-utils/eslint-utils/astUtilities.ts#L104-L116

**Expected Result**
I'd expect mentions to the existent parameters only.

**Actual Result**
There is a mention of a non-existent parameter called `times`.

**Additional Info**
-

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/experimental-utils` | `4.31.1` |
| `TypeScript`                            | `4.4.3` |
| `node`                                  | `14.17.6` |

**Comment by bradzacher** [comment]
The docs were copy pasted from the linked docs.
It just looks like we're missing one of the signatures for the function.
