### ISSUE TITLE
[strict-boolean-expressions] cannot figure out how to set allowString to false

### ISSUE THREAD

**Issue by nmattia** [typescript-eslint/typescript-eslint#3888]
- [ ] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**This is not exactly a bug report, I apologize**

I need to set `allowString` to `false` in `strict-boolean-expressions`. The configuration option is mentioned in the [`strict-boolean-expressions` doc](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md#options). However I cannot figure out how to set object-like configuration options.

I have read the [`eslintrc` configuration doc](https://eslint.org/docs/user-guide/configuring/configuration-files) and various [plugin](https://eslint.org/docs/developer-guide/working-with-plugins) [doc](https://eslint.org/docs/developer-guide/shareable-configs) pages. Yet it's unclear to me where I should specify the extra config. Thank you in advance for you help!

**Comment by bradzacher** [comment]
https://eslint.org/docs/user-guide/configuring/rules

Also check out example files like the one in our repo: https://github.com/typescript-eslint/typescript-eslint/blob/master/.eslintrc.js

**Comment by nmattia** [comment]
Thanks, this is great!
