### ISSUE TITLE
How to ban certain methods?

### ISSUE THREAD

**Issue by ugultopu** [typescript-eslint/typescript-eslint#3907]
I would like to ban the usage of [`forEach`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach). ESLint has [`no-restricted-properties`](https://eslint.org/docs/rules/no-restricted-properties) but AFAICT, it is simply a string match. That is, I guess it cannot do something like "prevent all usages of `forEach` on all array instances".

Is this possible with TypeScript-ESLint?

**Comment by bradzacher** [comment]
We don't have a rule for this.
There's only a few `.forEach` methods - so you should be able to get a very high-signal just `no-restricted-properties`.

The only other `.forEach`'s are on `Map`, `Set` and the array-buffer types - so false positives will be few and far between.

---

I don't think there's enough need in the wider community for a type-aware lint rule.
Such a lint rule would be *super* slow as well given how much checking it would need to do (it would need to check **every single** member expression in the codebase).
