### ISSUE TITLE
error 'someVal' is defined but never used no-unused-vars

### ISSUE THREAD

**Issue by UglyHobbitFeet** [typescript-eslint/typescript-eslint#3971]
I have tried with versions 4.18.0 and 4.33.0

I am getting the error mentioned in the title when I have the following:

  type MyType = (someVal: string) => string | true;

**Comment by bradzacher** [comment]
a few things:

First - don't delete and ignore the template. The template exists for a very good reason - to help you provide a baseline of information we need to help you. This prevents frustrating back-and-forth which just wastes ***everyone's*** time and means we can't help you as quickly.

Second - if you had read the template, you'd have been lead to the FAQ where the very first question would have answered your question
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-am-using-a-rule-from-eslint-core-and-it-doesnt-work-correctly-with-typescript-code
