### ISSUE TITLE
Documentation update request

### ISSUE THREAD

**Issue by selfagency** [typescript-eslint/typescript-eslint#3993]
![Capto_Capture 2021-10-12_02-20-03_PM 2021-10-12 14_24_52](https://user-images.githubusercontent.com/2541728/137009515-f4fdcf1c-67c2-4db8-b77b-0e90f961aa64.gif)

Love you guys! Thanks for everything you do! But can you please not bury the recommended installation and configuration three clicks deep?

**Comment by bradzacher** [comment]
closing this as we've released new version of the website with much cleaner layout and navigation.
