### ISSUE TITLE
Why does the parser not generate a cache using Incremental

### ISSUE THREAD

**Issue by Sherry-hue** [typescript-eslint/typescript-eslint#4028]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

Sorry, this is a question about TS compilation cache,I have read [this FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#my-linting-feels-really-slow)

My project is a spa that contains 2000 TS files. It takes 20 seconds to execute lint every time. Now I officially try to use project references to solve it. 

On the other hand, I see that TS already supports [incremental](https://www.typescriptlang.org/tsconfig#incremental),which may also improve the speed of lint, but I find that lint will not generate cache. Is this expected?

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.31.0` |
| `TypeScript`                | `4.3.0` |
| `ESLint`                    | `7.27.0` |
| `node`                      | `14.16.0` |

**Comment by bradzacher** [comment]
We simply do not support project references or incremental builds.

It's not as simple as turning on a flag to make it work, so it would require significant investment of time and effort to investigate and build out.
