### ISSUE TITLE
[adjacent-overload-signatures] Conflicting default rules for Getters and Setters

### ISSUE THREAD

**Issue by ToneyPK** [typescript-eslint/typescript-eslint#4029]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**
The problem is basically that I cannot manage to satisfy both default rules:
 
In the case below I'm getting the **@typescript-eslint/member-ordering**  warning that asks me to move all getters to be next to each other in order to satisfy:

CASE 1:
```
  public get values(): ReadonlyArray<T> {
      return this._values;
    }

  public set values(values: ReadonlyArray<T>) {
    console.log('storage values setter');
    this._values = values;
    this.update();
  }

  public get selected(): T | undefined {
    return this.getValueByKey(this._selectedKey);
  }

  public set selected(selected: T | undefined) {
    if (selected == undefined) {
      this._selectedKey = undefined;
    } else {
      const item = this.convert(selected);
      this._selectedKey = item.key;
    }
  }
```

After moving the getters to be one next to each other and satisfying the previous rule, now there is a **@typescript-eslint/adjacent-overload-signatures** error on the setters that asks for all related fields to be adjacent. 

CASE 2:
```
  public get values(): ReadonlyArray<T> {
      return this._values;
    }

  public get selected(): T | undefined {
    return this.getValueByKey(this._selectedKey);
  }
  
  public set values(values: ReadonlyArray<T>) {
    console.log('storage values setter');
    this._values = values;
    this.update();
  }

  public set selected(selected: T | undefined) {
    if (selected == undefined) {
      this._selectedKey = undefined;
    } else {
      const item = this.convert(selected);
      this._selectedKey = item.key;
    }
  }
```

**.eslintrc** :
```
{
    "root": true,
    "parser": "@typescript-eslint/parser",
    "plugins": [
      "@typescript-eslint",
      "jest"
    ],
    "env" : {
      "browser": true,
      "jest": true
    },
    "extends": [
      "eslint:recommended",
      "plugin:@typescript-eslint/eslint-recommended",
      "plugin:@typescript-eslint/recommended"
    ],
    "rules": {
      "sort-imports" : ["error", {
        "ignoreCase": false,
        "ignoreDeclarationSort": false,
        "ignoreMemberSort": false,
        "memberSyntaxSortOrder": ["none", "all", "multiple", "single"],
        "allowSeparatedGroups": true
      }],
      "quotes":["error", "single"],
      "object-curly-spacing": ["error", "always"],
      "array-bracket-spacing": ["error","always"],
      "key-spacing":["error",{"beforeColon": false, "afterColon": true}],
      "semi": ["error","always"],
      "curly": "error",
      "indent": ["error",2],
      "no-irregular-whitespace": "error",
      "no-multiple-empty-lines": "error",
      "comma-spacing": "error",
      "@typescript-eslint/member-ordering": ["warn"]
    }
  }

```
**tsconfig.json :**
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "jsx": "react",
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "paths": {
      "gefa-controls": [
        "xxx",
        "xxx"
      ]
    },
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2017",
    "module": "es2020",
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

**Expected Result**

No warnings or errors when having either all getters grouped and separatefrom setters or having the getter above setter format. 

**Actual Result**

Error in CASE 2: **@typescript-eslint/adjacent-overload-signatures**
Warning in CASE 1: **@typescript-eslint/member-ordering**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.0.0` |
| `@typescript-eslint/parser`        | `5.0.0` |
| `TypeScript`                       | `4.3.2` |
| `ESLint`                           | `8.0.1` |
| `node`                             | `X.Y.Z` |

**Comment by dsimon-onventis** [comment]
Shortest code for reproduction:

```typescript
class A {
  get a(): unknown { return ''; }
  set a(a: unknown) { console.log(a); }
  get b(): unknown { return 0; }
  set b(b: unknown) { console.log(b); }
}
```
With the following config:
```
rules: {
  "@typescript-eslint/adjacent-overload-signatures": "error",
  "@typescript-eslint/member-ordering": "error"
}
```
When both rules are enabled, there is no way of ordering the getters and setters without a lint error being thrown.

**Comment by ssams** [comment]
> This is expected. You can't group and sort members separately whilst also putting getters and setters next to one another.
> 
> You will need to configure the rules as appropriate for your desired linting.

I don't see how to configure the rules for this without some unintended side effects. 

1. change `member-ordering` to not enforce getter/setter order => in this case you can put getters and setters anywhere (as long as they appear together in pairs), which is not what's desired, I cannot enforce that they appear at a specific position anymore (at least I don't see how this would be done?)
2. disable `adjacent-overload-signatures` => in this case rules regarding overloaded functions which are not getters/setters are also not enforced anymore, so I can now place non-getter/setter overloads in any order without grouping them. this should be unrelated to the getter/setter part in my opinion and enforceable independently.

The second case would work if there'd be an option `ignore-accessors` like in https://palantir.github.io/tslint/rules/adjacent-overload-signatures/, then one could configure it separately. But at the moment I don't see how the desired config could be achieved?

**Comment by ToneyPK** [comment]
> This is expected. You can't group and sort members separately whilst also putting getters and setters next to one another.
> 
> You will need to configure the rules as appropriate for your desired linting.

Can you please provide an example setting where the comment from @ssams  is satisfied?
