### ISSUE TITLE
[not-for-rules] package.json engines setting

### ISSUE THREAD

**Issue by kainstar** [typescript-eslint/typescript-eslint#4037]
- [ ] I have tried restarting my IDE and the issue persists.
- [ ] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

I'm sorry reported issue in '@typescript-eslint/eslint-plugin' package scope, but i didn't found a better choice for my problem.

I'm updating my repo's `@typescript-eslint/eslint-plugin` pakcage, and my local and gitlab ci node version is 14.15.0 which may not be able to upgrade, but all the `@typescript-eslint/*` packages's package.json file declare engines need node version > `14.17.0` which i think is following eslint v8 engines setting, and it lead to install failed.
But `@typescript-eslint/*` packages support both eslint v6, v7 and v8, so is this a unsuitable engines setting? 
Is the engines declaration decided by repo's installed `eslint` version better?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.1.0` |
| `@typescript-eslint/parser`        | `5.1.0` |
| `TypeScript`                       | `4.4.4` |
| `ESLint`                           | `7.32.0` |
| `node`                             | `14.15.0` |

**Comment by bradzacher** [comment]
Newer is better!

We set the engines based off of what ESLint uses and we test against the exact versions we declare.

There's a chance our tooling works on unlisted, older versions of node - but we don't test against them so we provide no guarantees at all. If it works it works, it it breaks it breaks.
