### ISSUE TITLE
Remove `eslint-scope` types from `utils`

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#4041]
In v6, `eslint-scope` (like `eslint` in v8) started using package.json exports. This means that they no longer expose their internals.

As such - we should remove the types from [`utils/src/ts-eslint-scope`](https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/utils/src/ts-eslint-scope).

**Comment by JoshuaKGoldberg** [comment]
#5256 is merged into #5886; closing this issue now accordingly. It'll be released as a part of the v6 major release.
