### ISSUE TITLE
Allow for parserOptions.project to also accept configuration

### ISSUE THREAD

**Issue by kacpak** [typescript-eslint/typescript-eslint#406]
**What code were you trying to parse?**
n/a

**What did you expect to happen?**
I would like to also be able to provide object with configuration (content of tsconfig) to *parserOptions.project* instead of only file path. In my current project we use custom 'sdk' for building frontend packages and we don't provide tsconfig for each of them - rather we use ts-loader to inject configuration from the code.

**What actually happened?**
I can only specify a path to configuration

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `1.6.0` |
| `TypeScript`                | `3.3.3333` |
| `ESLint`                    | `5.16.0` |
| `node`                      | `8.11.2` |
| `npm`                       | `6.8.0` |

**Comment by bradzacher** [comment]
closing in favour of #1613
