### ISSUE TITLE
[prefer-readonly-parameter-types] FR: Add an option to allow `Readonly<>` to satisfy the rule

### ISSUE THREAD

**Issue by marekdedic** [typescript-eslint/typescript-eslint#4061]
**Repro**

See #2699 for an example of when this could be useful.

**Rationale**

I see this as a trade-off - turning such an option on would reduce the strictness of the rule (as far as I understand it, `Readonly<>` only guarantees shallow readonlyness, this rule checks for deep readonlyness), however, it would make it much easier to use in certain cases like #2699 or #2079.

**Comment by bradzacher** [comment]
> Is there any other way to make the rule easier to use in general? You mentioned adding an exception specifically for HTMLElement...

We can create an allowlist of types that are problematic and expand on them as required.
This is actually pretty trivial to implement.

1) get the `Symbol` for the type
2) get the declarations for the type
3) ensure that the declaration is within a TS "default library"
    - This check is to ensure that we don't false-negative if someone declares a `HTMLElement` type locally within their file

For example here is some code we could generalise from an existing rule:
https://github.com/typescript-eslint/typescript-eslint/blob/71c93706e55f5f92a1285102b93c6ab1950c6df4/packages/eslint-plugin/src/rules/no-implied-eval.ts#L83-L91

> however, from my use of the rule it seems the problematic types are much more common. Any way to deal with all of them?

If you've got some examples of the sorts of types that are problematic, we can discuss a solution for them.
If we're just talking about TS lib types like `HTMLElement` - then they can just be allowlisted using the above solution.

If there "custom" types or such - then I'd like to gain an understanding of what these types are so we can figure out the best approach for them.

**Comment by marekdedic** [comment]
Thanks, I opened that as a new issue to keep the record untangled.
