### ISSUE TITLE
Examples of overrides without type information

### ISSUE THREAD

**Issue by mjomble** [typescript-eslint/typescript-eslint#4087]
My apologies for not using an issue template, but none of them seemed to match a proposed documentation change.

There is an existing closed issue for the same problem (#2794), here is a summary:

> In the docs on linting with type information, there's a section that specifically addresses [I get errors telling me "The file must be included in at least one of the projects provided"](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md#i-get-errors-telling-me-the-file-must-be-included-in-at-least-one-of-the-projects-provided).
>
> The solution that is listed there that would apply to my project is:
>
> > Use ESLint's overrides configuration to configure the file to not be parsed with type information.
>
> However, it is not clear what overrides to pass to disable parsing with type information.

The previous issue expired while awaiting response after feedback from @bradzacher:

> It's hard to provide exact docs for this as everyone's setups vary wildly.

I agree with this, but feel that more specific information can still be helpful.

I ran into the same problem today and managed to solve it by reading more docs and issues and experimenting via trial and error. A few extra notes in the documentation would've saved me a lot of time, though.

I've included them in [this commit](https://github.com/mjomble/typescript-eslint/commit/aba936e36b8ba6f00d334abe7e34380c8130d96b) and would like to propose it as a PR if this issue gets marked as 'accepting prs'.

**Comment by bradzacher** [comment]
cc @JoshuaKGoldberg - something we should put in the new website

**Comment by bradzacher** [comment]
also see the comments in #4086

**Comment by JoshuaKGoldberg** [comment]
:wave: @mjomble, aba936e36b8ba6f00d334abe7e34380c8130d96b looks good to me - are you still planning on sending a PR with it?

No worries if you don't have time, I can soon if not!

**Comment by mjomble** [comment]
Thanks for the reminder :) Submitted the PR
