### ISSUE TITLE
[return-await] wrong autofix of `return undefined ?? promise` to `return await undefined ?? promise`

### ISSUE THREAD

**Issue by fregante** [typescript-eslint/typescript-eslint#4090]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/await-thenable": "error"
  }
}
```

```TS
async function bar() {}
async function foo() {
	try {
		return window.foo ?? bar();
	} catch {}
}
```

tsconfig: https://github.com/sindresorhus/tsconfig/blob/67d56ca87d2790081696fe3d745befa7e9ff38b8/tsconfig.json

**Expected Result**

```TS
async function bar() {}
async function foo() {
	try {
		return window.foo ?? await bar();
		                  // ^ correct position of `await`
	} catch {}
}
```

**Actual Result**

```TS
async function bar() {}
async function foo() {
	try {
		return await await await await await await await await await await window.foo ?? bar();
		    // ^ incorrect position of `await`, which is then "autofixed" repeatedly
	} catch {}
}
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.3.0` |
| `@typescript-eslint/parser`        | `5.3.0` |
| `TypeScript`                       | `4.4.4` |
| `ESLint`                           | `8.1.0` |
| `node`                             | `16.4.2` |

**Comment by bradzacher** [comment]
I believe what's happening here is that it's not respecting the operator precedence - it should be wrapped with parentheses when fixed!

**Comment by armano2** [comment]
@fregante i'm a little confused here. this rule doesn't have auto-fixer, and it doesn't report on this? are you sure this is related to `await-thenable`?

**Comment by bradzacher** [comment]
perhaps it's instead `return-await`? That's the only await rule with a fixer?
