### ISSUE TITLE
Standard `no-var` rule breaks on declared vars

### ISSUE THREAD

**Issue by epmatsw** [typescript-eslint/typescript-eslint#410]
I think that this is an issue that might require an `@typescript-eslint/no-var` rule. In `no-var`'s fixer, eslint just replaces the first token in the VariableDeclaration with `let` or `const` (https://github.com/eslint/eslint/blob/c021117915d5d23399233f761a237e138f1854af/lib/rules/no-var.js#L308). This is valid in JS, but in TS that first token can be `declare`, which breaks the fixer.

**What code were you trying to parse?**

```ts
declare var blah: number;
```

**What did you expect to happen?**

When running `eslint --fix` with `no-var` turned on, the code should become `declare let blah: number;`.

**What actually happened?**

The code becomes `let var blah: number;`, which is invalid.

**Versions**

| package                                   | version |
| ----------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin-tslint` | `1.6.0` |
| `@typescript-eslint/parser`               | `1.6.0` |
| `TypeScript`                              | `3.4.1` |
| `ESLint`                                  | `5.16.0` |
| `node`                                    | `11.12.0` |
| `npm`                                     | `6.1.0` |

**Comment by platinumazure** [comment]
I think we could fix this on the ESLint side. In the case of a `declare` declaration, the node info has a `kind` property (which is always var/let/const) and a `declare: true` property. So we could just do this instead:

```js
const varToken = sourceCode.getFirstToken(node, { filter: t => t.value === node.kind });
```

This should work for both TS and JS without needing to create a rule here.

**Comment by epmatsw** [comment]
That seems reasonable. I wasn't sure what the policy on fixing non-JS code in the eslint codebase was, so it seemed like the right approach to start here and head over there if needed.

**Comment by platinumazure** [comment]
@epmatsw Yeah, that's probably the best approach. We don't like making exceptions for non-JS in general, but if we can make a change that works for JS and non-JS and isn't specific to non-JS, I personally am okay with it.

**Comment by bradzacher** [comment]
Awesome! Thanks @platinumazure 
To save us keeping both issues in sync, I'll go ahead and close this issue.
Those that want to track the fix, please subscribe to https://github.com/eslint/eslint/issues/11594
