### ISSUE TITLE
@typescript-eslint/experimental-utils v5.3.1 does not work with Node.js v15

### ISSUE THREAD

**Issue by bennycode** [typescript-eslint/typescript-eslint#4115]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

1. Get Node.js v15 (e.g. 15.14.0)
2. Install @typescript-eslint/experimental-utils v5.3.1 or a package depending on it (e.g. "eslint-plugin-typescript-sort-keys")
3. Try to lint your code

**Expected Result**

Linting works with Node.js v15

**Actual Result**

Linting fails because "@typescript-eslint/experimental-utils" excludes Node.js v15 from the "engines":

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/experimental-utils/package.json#L10-L12

**Additional Info**

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/experimental-utils` | `5.3.1` |
| `TypeScript`                            | `4.4.4` |
| `node`                                  | `15.14.0` |

**Comment by bradzacher** [comment]
This is intentional.
Odd numbered node versions are transitory and only have short term support.
In fact Node 15 is already out of its maintenance window.
https://github.com/nodejs/Release/blob/main/schedule.json#L81-L85

Use a supported node version instead.
