### ISSUE TITLE
[scope analysis] true support for static class blocks

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#4120]
When we added syntax support for this with the TS4.4 support, we did not add proper support for scope analysis of this.

Currently scope analysis will "work" because the analyser will just traverse the block body - but it will create an incorrect scope tree because a new scope will not be created for the block scope created by the static block.

**Repro**

```TS
declare function someCondition(): boolean;

class Foo {
    static count = 0;

    static {
        if (someCondition()) {
            Foo.count++;
        }
    }
}
```

Reference implementation: https://github.com/eslint/eslint-scope/pull/80

**Comment by juank1809** [comment]
Hi! I'd like to help on this issue. Can you assign it to me?
