### ISSUE TITLE
Remove 'experimental-' from @typescript-eslint/experimental-utils

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#4139]
- [x] ~I have tried restarting my IDE and the issue persists.~ N/A
- [x] ~I have updated to the latest version of the packages.~ N/A
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TROUBLESHOOTING.md) and my problem is not listed.

**Repro**

https://www.npmjs.com/package/@typescript-eslint/experimental-utils

**Expected Result**

The package is actually pretty stable across the last few major version bumps. Calling it _experimental_ utils is a little bit of a deterrent to folks feeling comfortable using it. And it's a big name.

Can we call it... say, just `@typescript-eslint/utils`?

**Actual Result**

It's still called _experimental_ today.

**Comment by bradzacher** [comment]
1) v1.8.0: https://github.com/typescript-eslint/typescript-eslint/blob/a7a03ce39f82fac47e9ef1ef052ee1366eeb8c8a/packages/experimental-utils/README.md?plain=1#L13

2) v2.25.0 https://github.com/typescript-eslint/typescript-eslint/blob/3eb5d4525e95c8ab990f55588b8d830a02ce5a9c/packages/experimental-utils/README.md?plain=1#L13

3) v3.4.0 https://github.com/typescript-eslint/typescript-eslint/blob/f5c271f69a2953ca71edc07f66cc0e174e538433/packages/experimental-utils/README.md?plain=1#L19

TODO: change package name

**Comment by bradzacher** [comment]
(4). v5.x #4158 😅
