### ISSUE TITLE
Wrong types for `eslint-utils`' `ReferenceTracker`

### ISSUE THREAD

**Issue by roikoren755** [typescript-eslint/typescript-eslint#4159]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TROUBLESHOOTING.md) and my problem is not listed.

**Information**

First off, I'd like to thank everyone involved in this project, I couldn't imagine myself linting any TS project without this wonderful set of packages.

I recently started writing a personal ESLint plugin in TypeScript, using many of the tools exported by this package.
In one of the rules I am working on, I use `eslint-utils`' `ReferenceTracker`, re-exported under `@typescript-eslint/experimental-utils`' `ASTUtils` export. I kept getting `{ ..., entry: undefined }`, no matter what I tried to track.
Comparing the type given to `ReferenceTracker` in this package with the source code in `eslint-utils`, it looks like a change was made a long time ago to the return value, such that any info saved in the TraceMap was returned on the `info` field, rather than the `entry` one. Could it be that the types are simply out of date? From what I see the type was changed around v1 of `eslint-utils`, in my case, using v3 of `eslint-utils`, the types declared by this package don't match the types of `eslint-utils`.

**Repro**

```TS
import { ASTUtils, ESLintUtils, TSESLint } from '@typescript-eslint/experimental-utils';

const rule = ESLintUtils.RuleCreator((x) => x)({
  name: 'test',
  defaultOptions: [],
  meta: { docs: { description: 'test', recommended: false }, messages: {}, schema: [], type: 'problem' },
  create(context) {
    return {
      'Program:exit'() {
        const referenceTracker = new ASTUtils.ReferenceTracker(context.getScope(), { mode: 'legacy' });
        const results = referenceTracker.iterateGlobalReferences({
          Buffer: { [ASTUtils.ReferenceTracker.READ]: { some: 'information' } },
        });

        for (const result of results) {
          console.log(result);
          console.log(result.entry);
          console.log(result['info']);
        }
      },
    };
  },
});

new TSESLint.RuleTester().run('test', rule, { valid: [{ code: 'Buffer;', env: { node: true } }], invalid: [] });
```

**Expected Result**

Logging `result.entry` to the console should output `{some: 'information'}`, logging `result['info']` should output undefined, as the types suggest.

**Actual Result**

The reverse, `result.entry` is empty, `result['info']` isn't.

**Additional Info**

As can be seen in JSDoc comments [here](https://github.com/mysticatea/eslint-utils/blob/c3b1d38328dc3a5278b208a58186a0735315f58f/src/reference-tracker.js#L79), [here](https://github.com/mysticatea/eslint-utils/blob/c3b1d38328dc3a5278b208a58186a0735315f58f/src/reference-tracker.js#L119) and [here](https://github.com/mysticatea/eslint-utils/blob/c3b1d38328dc3a5278b208a58186a0735315f58f/src/reference-tracker.js#L146), and in tests for the same file, the information stored in the trace map is returned under the `info` field of the object, and not the `entry` field.

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/experimental-utils` | `5.3.1` |
| `TypeScript`                            | `4.4.4` |
| `node`                                  | `14.18.0` |
| `eslint-utils`                                  | `3.0.0` |

**Comment by bradzacher** [comment]
could you please provide some example code?

**Comment by roikoren755** [comment]
@bradzacher I updated the initial issue with code sample, and added links to some of the relevant places in `eslint-utils`' source code. I'd be more than happy to open a PR to update the types, if you want :)

**Comment by bradzacher** [comment]
The types were added in #294 and they were just assumed to be correct back then as they were authored for us by the owner of the package! But they've been wrong since the beginning ha!

Happy to accept a PR to correct them.
