### ISSUE TITLE
[5.4.0] Typescript 4.4.4 (latest) not supported anymore

### ISSUE THREAD

**Issue by jlowcs** [typescript-eslint/typescript-eslint#4164]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TROUBLESHOOTING.md) and my problem is not listed.

**Repro**

Using Typescript 4.4.4 (latest non-rc release)

**Expected Result**

linting should pass

**Actual Result**

```
node_modules/@typescript-eslint/typescript-estree/dist/ts-estree/estree-to-ts-node-types.d.ts:40:42 - error TS2694: Namespace 'ts' has no exported member 'AssertEntry'.
```

![image](https://user-images.githubusercontent.com/3777724/141995056-82218311-93e4-4320-825c-9cdf9dc6d4bd.png)

**Additional Info**

See above

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `5.4.0` |
| `TypeScript`                           | `4.4.4` |
| `node`                                 | `14.17.6` |

**Comment by bradzacher** [comment]
We need to add a manual patch to

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/typescript-estree/src/ts-estree/ts-nodes.ts#L3-L12

**Comment by bradzacher** [comment]
We should really add an integration test which checks the types against an older version of TS to help us guard against this.
