### ISSUE TITLE
website: add links to the rule source to rule pages

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#4166]
### Suggested Changes

Currently there's no way to jump from the rule's docs directly to the rule's source code.
I find this is an invaluable in the ESLint core docs as it allows me to quickly find the implementation.

It'd be great if we could add direct links to the rule source, the docs source and the tests for quick access from the website.

### Affected URL(s)

Any rule page eg https://typescript-eslint.io/rules/no-confusing-void-expression/

**Comment by JoshuaKGoldberg** [comment]
Fixed by #4204 🎉

**Comment by armano2** [comment]
i can't find link that point to rule source in rule docs, am i missing something?

**Comment by JoshuaKGoldberg** [comment]
Oh maybe not 😃
