### ISSUE TITLE
Docs: use a filterable data table for rules

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#4168]
### Suggested Changes

https://typescript-eslint.io/rules is hard to filter & sort through. Perhaps in conjunction with #4156, we could use a more rich table format that can provide column filtering? Or something else that improves searchability within the page?

### Affected URL(s)

https://typescript-eslint.io/rules/

**Comment by Josh-Cena** [comment]
Are we prioritizing the website than GitHub? I'm refraining from implementing JSX-based solutions because that would sacrifice readability with the GitHub interface

**Comment by JoshuaKGoldberg** [comment]
> prioritizing the website over GitHub

Yes.

**Comment by JoshuaKGoldberg** [comment]
> prioritizing the website over GitHub

Yes. 😄
