### ISSUE TITLE
[no-type-alias] suggestion: allowExported option

### ISSUE THREAD

**Issue by burtek** [typescript-eslint/typescript-eslint#4201]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/TROUBLESHOOTING.md) and my problem is not listed.

Quick suggestion: add `allowExported` to `no-type-alias` rule so that

```ts
export type Store = ReturnType<typeof getState>;
```

wouldn't error

**Comment by bradzacher** [comment]
Why? What's the reasoning behind the request?

We don't accept feature requests unless they contain information and justification.

**Comment by burtek** [comment]
Long story short - to allow exporting all types (incl aliases) from a library/module inside an app repo to be used along the module itself in other places in the same app.

I work on multiple applications where we don't allow aliases as general rule, but have multiple places where we ignore this rule for exported aliases, those include:
 - exporting State type for a redux store from the store's module (as 
 - exporting return type and/or argument type (where those are defined via `ReturnType` or `Parameters` )

**Comment by bradzacher** [comment]
Could you give an example?
I'm not sure if it really needs an entire option if you're doing it from certain key files.

It seems like disable comments that can explain the exception would be much better than just allowing any and all files to export type aliases.
