### ISSUE TITLE
[explicit-module-boundary-types] picking up: add option to omit explicit return types on JSX functions

### ISSUE THREAD

**Issue by freeatnet** [typescript-eslint/typescript-eslint#4208]
> closing for repo cleanup due to non-activity.
> feel free to reopen/reraise if you make progress in future!
> _Originally posted by @bradzacher in https://github.com/typescript-eslint/typescript-eslint/issues/2725#issuecomment-874971585_

Hey @bradzacher,

Thank you for your work on this library.

I'd like to revive the PR of adding a JSX exception flag to the `explicit-module-boundary-types` rule. You indicated that you are open to it; however, it looks like the bot locked the original PR from further comments.

Firstly, to address your primary concern raised in the PR: I understand your hesitation to add a flag specific to a given choice of templates; however, TypeScript already ships [with native JSX support](https://www.typescriptlang.org/docs/handbook/jsx.html).

Secondly, I think that the "slippery slope of obvious return types" argument is a bit too broad. It's easy to mix up arbitrary functions, but the JSX and React components are quite distinct: they look different, they are named in a specific way, and their purpose is clear from an external, module boundary, perspective. It's quite hard (for me) to imagine a situation where a component would be mistaken for something else; adding an explicit return type adds lines of code without providing much upside. And again, since this is an option flag, the behavior would remain unchanged for existing users looking to label the component return types manually.

I'm happy to pick up the flag PR from here and fix any issues/linting errors that may be in there.

**Comment by Josh-Cena** [comment]
How would this work exactly? Would this be reported?

```tsx
function Foo({children, showDefault}) {
  return children ? <>{children}</> : showDefault ? 'Default' : null;
}
```

Or do we just stick to functions that return `JSX.Element`?

I'm also annoyed by this rule in Docusaurus's semi-react codebase, but I can't come up with a good heuristic of what would be good to omit

**Comment by bradzacher** [comment]
> they look different, they are named in a specific way

A single upper case character isn't really an obvious naming convention. I deal with react a lot. I do a lot of linting of react code. It's not as obvious as you might think.
And in large enough codebases - it becomes increasingly common for people to use that convention in non component functions.

At the end of the day - a function component is just a function.

----

> where a component would be mistaken for something else

It's not about whether or not a component can be mistaken as a non component or not. Return types are not there for that reason in the slightest.

Return types are there to provide a strict contract for what your component is doing.

As an example - TS does not provide type errors across files in VSCode without having both files open (or jumping through some config hoops).

If you don't annotate the return type and then at some point do `return 'foo';`, then your component definition will be fine, but your usage site will have a type error.
If you're building across package boundaries then this typing bug can easily go unnoticed until after a release when your consumers cannot use your component any more! Oops - if only there had been a return type to enforce a strict contract.

----

@Josh-Cena has really hit the nail on the head here with one issue with this sort of thing - why does one case get ignored and another not?
Without type information we cannot statically determine the type of any function call or variable, which means that quickly you can get into a state where we cannot tell the return type.

Now the rule is inconsistent - sometimes it requires a return type, sometimes it doesn't. But why? How can an average user understand that question? 99.9999% of devs have no idea how linting works - so to them it just seems like the rule is broken.
They could read the rule docs and we could enumerate the cases that are/aren't supported - but that isn't a good experience. If you have to explain it, it isn't good.

Lint rules shouldn't be surprising. They should be predictable.
Hiding behaviour behind an option doesn't negate that. A large portion of users either (a) don't touch ESLint configs directly (eg someone else is responufor it) or (b) use config packages / recommend configs. Either way someone else would be configuring the rule for them - thus they don't know why the rule is inconsistent.

```ts
declare function someFunction(): JSX.Element;

// cannot statically determine the return type
function Foo() {
  return someFunction();
}

// cannot statically determine the return type
function Foo() {
  return useMemo(() => <Component />, []);
}

// cannot statically determine the return type
function Foo() {
  const [content] = useState(<div />);
  return content;
}

// cannot statically determine the return type
function Foo({children}) {
  return React.cloneElement(children);
}

// Really difficult to statically determine the return type
function Foo({cond}) {
  let content = <div />;
  if (cond) {
    content = <a />;
  }
  return content;
}

// Is this exempt? This is a valid "component"
function Foo() {
  return null;
}

// Is this exempt?
function Foo({cond}) {
  if (cond) {
    return null;
  }
  return <div />;
}

// Is this exempt?
function Foo({cond}) {
  if (cond) {
    return someFunction();
  }
  return <div />;
}

// Is this exempt? It's not a "component"
function fooHelper() {
  return <div />;
}
```

----

This is exactly the same discussion I've had time and time again for other return types. Some people say "oh I should have to annotate `: void` - it's obvious when a function returns `void`".
But as with components - that's not the case! *Some* cases are, a lot more aren't.

---

Honestly I don't think this is a good addition to the rule. Ignoring certain cases isn't intuitive.

What would be a much, much better enhancement would be to try to use static analysis to determine the return type and then use that information to do one or both of the following:

- Provide a clear error message stating what the return type likely should be.
- Provide a suggestion fixer to help annotate the return type.

Why is this better?
- The rule remains consistent in all cases.
- The rule can help educate people about what the return type could be.
- With a fixer it's now two quick clicks to annotate the return type automatically.
- This behaviour can work for *any* case, not just react components.
- This behaviour would not require an option.
