### ISSUE TITLE
Rule proposal: no-relative-parent-imports

### ISSUE THREAD

**Issue by rossille** [typescript-eslint/typescript-eslint#4209]
#### Intro

In javascript projects, I love to use the eslint rule
`imports/relative-parent-imports` to force all the code to use dependency injection.

It's works well for JavaScript project.

But in TypeScript we often need interfaces and types introduced by the dependencies to specify 
constructor parameters types for dependency injection.

To illustrate the problem, run `npm install` and `npm run lint` in [this project](https://github.com/rossille/demo-ts-no-relative-parent-imports).

#### Example

Let's say, we have several components, and rely on dependency injection to organize our code.

```
src/
├── dependency                          Low level dependency
│         ├── dependency.ts             Types defining the contract
│         ├── lame-dependency.ts        Implementation
│         └── terrific-dependency.ts    Alternative implementation
├── main
│         └── main.ts                   High level component requiring the dependency
└── entrypoint.ts
```

Here are the types defining the contract.

```typescript
// dependency/dependency.ts

export interface Dependency {
    sayHelloDependency(): void
}
```

Here is the first implementation

```typescript
// dependency/lame-dependency.ts

import { Dependency } from './dependency'

export class LameDependency implements Dependency {
  sayHelloDependency (): void {
    console.log(`Hello, I'm a lame implementation of Dependency`)
  }
}
```

Here is an alternative implementation

```typescript
// dependency/terrific-dependency.ts

import { Dependency } from './dependency'

export class TerrificDependency implements Dependency {
  sayHelloDependency (): void {
    console.log(`Hello, I'm a terrific implementation of Dependency`)
  }
}
```

```typescript
// main/main.ts

import { Dependency } from '../dependency/dependency'

export class Main {
  private readonly dependency: Dependency

  constructor (dependency: Dependency) {
    this.dependency = dependency
  }

  doTheWork () {
    this.dependency.sayHelloDependency()
  }
}
```

```typescript
// entrypoint.ts

import { TerrificDependency } from './dependency/terrific-dependency'
import { Main } from './main/main'

const dependency = new TerrificDependency() // of course

const main = new Main(dependency)

main.doTheWork()
```

#### Current behavior with `imports/relative-parent-imports` 😢

In this project if we use `imports/relative-parent-imports`, we end up with an
error when `main.ts` imports the interface specifying the dependency from `../dependency/dependency.ts`.

#### Proposed rule

I would like to be able to write this :

```json
{
  "rules": {
    "@typescript-eslint/no-relative-parent-imports": [
      "error",
      {
        "allowTypeImports": true
      }
    ]
  }
}
```

This would prevent importing values from parent directories, but allow types.

Also, I would be happy to work on a pull request if there are other who think this rule would be useful

### Fail

```ts
import { TerrificDependency } from '../dependency/terrific-dependency'
//       ^ This is a class, hence a value, we don't want strong coupling
```

### Pass

```ts
import { Dependency } from '../dependency/dependency'
//       ^ This is a an interface, not a value, so it's loose coupling
```

**Comment by bradzacher** [comment]
Thanks for the super detailed issue!

This is a stylistic rule (it's about code organisation) which doesn't have broad applicability (the majority of projects don't use this style).
Your suggested option is very narrow in scope (only a subset of the already small userbase would use it).
Additionally - this is only vaguely related to TS in that you're importing an interface.

For those reasons - it does not belong in this project.

----

My suggestion would be to do one of the following:

1) use type-only imports (`import type {Dependency}...`) and talk to the rule owners about adding an option to ignore type-only imports as they don't introduce runtime dependencies, and it's a common pattern to import types across parent boundaries.

2) fork the rule within your local project and customise it as appropriate to achieve your project's requirements.
