### ISSUE TITLE
Access original TypeScript node for using in typechecker

### ISSUE THREAD

**Issue by goodmind** [typescript-eslint/typescript-eslint#421]
Is this possible to attach original nodes to estree ast? I want to use babel traversal but have access to original TypeScript nodes

**Comment by mohsen1** [comment]
you can get the original node like this:

https://github.com/typescript-eslint/typescript-eslint/blob/063518380215fc0b2df777080d247fe222cf258d/packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts#L83
