### ISSUE TITLE
Docs: rules in `recommended`

### ISSUE THREAD

**Issue by ph-fritsche** [typescript-eslint/typescript-eslint#4224]
### Suggested Changes

The docs should list those rules as `recommended` that are part of `plugin:@typescript-eslint/recommended`.

https://typescript-eslint.io/rules/ does not reflect [configs/recommended](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/recommended.ts):
```diff
@typescript-eslint/adjacent-overload-signatures
- @typescript-eslint/await-thenable
@typescript-eslint/ban-ts-comment
@typescript-eslint/ban-types
+ @typescript-eslint/no-array-constructor
+ @typescript-eslint/no-empty-function
@typescript-eslint/no-empty-interface
@typescript-eslint/no-explicit-any
@typescript-eslint/no-extra-non-null-assertion
+ @typescript-eslint/no-extra-semi
- @typescript-eslint/no-floating-promises
- @typescript-eslint/no-for-in-array
@typescript-eslint/no-inferrable-types
+ @typescript-eslint/no-loss-of-precision
@typescript-eslint/no-misused-new
@typescript-eslint/no-namespace
@typescript-eslint/no-non-null-asserted-optional-chain
@typescript-eslint/no-non-null-assertion
@typescript-eslint/no-this-alias
- @typescript-eslint/no-unnecessary-type-assertion
@typescript-eslint/no-unnecessary-type-constraint
- @typescript-eslint/no-unsafe-argument
- @typescript-eslint/no-unsafe-assignment
- @typescript-eslint/no-unsafe-call
- @typescript-eslint/no-unsafe-member-access
- @typescript-eslint/no-unsafe-return
+ @typescript-eslint/no-unused-vars
@typescript-eslint/no-var-requires
@typescript-eslint/prefer-as-const
@typescript-eslint/prefer-namespace-keyword
- @typescript-eslint/restrict-plus-operands
- @typescript-eslint/restrict-template-expressions
@typescript-eslint/triple-slash-reference
- @typescript-eslint/unbound-method
```

### Affected URL(s)

https://typescript-eslint.io/rules/

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/recommended-requiring-type-checking.ts

We have two recommended configs that are intentionally separated.

This is mentioned at the top of that page.

> 'plugin:@typescript-eslint/recommended-requiring-type-checking' additional recommended rules that require type information. See Linting for more details.

**Comment by ph-fritsche** [comment]
But it doesn't reflect `plugin:@typescript-eslint/recommended` plus `plugin:@typescript-eslint/recommended-requiring-type-checking` either.

**Comment by bradzacher** [comment]
The table is generated - so it contains the same metadata as defined in the rules themselves.
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/tools/generate-rules-lists.ts

So it should all match. What rules are erroneously there / missing?

**Comment by ph-fritsche** [comment]
`recommended` without type information:
```diff
@typescript-eslint/adjacent-overload-signatures
@typescript-eslint/ban-ts-comment
@typescript-eslint/ban-types
+ @typescript-eslint/no-array-constructor
+ @typescript-eslint/no-empty-function
@typescript-eslint/no-empty-interface
@typescript-eslint/no-explicit-any
@typescript-eslint/no-extra-non-null-assertion
+ @typescript-eslint/no-extra-semi
@typescript-eslint/no-inferrable-types
+ @typescript-eslint/no-loss-of-precision
@typescript-eslint/no-misused-new
@typescript-eslint/no-namespace
@typescript-eslint/no-non-null-asserted-optional-chain
@typescript-eslint/no-non-null-assertion
@typescript-eslint/no-this-alias
@typescript-eslint/no-unnecessary-type-constraint
+ @typescript-eslint/no-unused-vars
@typescript-eslint/no-var-requires
@typescript-eslint/prefer-as-const
@typescript-eslint/prefer-namespace-keyword
@typescript-eslint/triple-slash-reference
```

`recommended-requiring-type-checking`:
```diff
@typescript-eslint/await-thenable
@typescript-eslint/no-floating-promises
@typescript-eslint/no-for-in-array
+ @typescript-eslint/no-implied-eval
+ @typescript-eslint/no-misused-promise
@typescript-eslint/no-unnecessary-type-assertion
@typescript-eslint/no-unsafe-argument
@typescript-eslint/no-unsafe-assignment
@typescript-eslint/no-unsafe-call
@typescript-eslint/no-unsafe-member-access
@typescript-eslint/no-unsafe-return
+ @typescript-eslint/require-await
@typescript-eslint/restrict-plus-operands
@typescript-eslint/restrict-template-expressions
+ @typescript-eslint/unbound-method
```

Sidenote: In light mode the `requires-type-information` icon lacks contrast:
![image](https://user-images.githubusercontent.com/39068198/144031568-e030f3cf-b25c-4f55-9d89-a80318136d96.png)

**Comment by bradzacher** [comment]
Scroll down to the third table and you'll find those listed:

https://typescript-eslint.io/rules/#extension-rules

**Comment by ph-fritsche** [comment]
I stand corrected. Sorry about the false report.
I just got confused scrolling up and down that page and when I found the complete list much faster in the code, I somehow got the impression there was something wrong with the docs. :(
