### ISSUE TITLE
Split up linting internally

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#4226]
Following up on https://github.com/typescript-eslint/typescript-eslint/pull/4197: our linting is running out of memory in CI and without that change would likely eventually run out of memory on developer computers too. The short term fix to up the `--max-old-space-size` for Node is a bandaid fix.

Short of the dedicated CLI discussed in #4183, https://github.com/typescript-eslint/typescript-eslint/pull/4197#issuecomment-975015559 / https://github.com/typescript-eslint/typescript-eslint/pull/4197#issuecomment-977288696 would be a better strategy:

```
"lint": "nx run-many --target=lint --all",
```

**Comment by bradzacher** [comment]
The important thing here would be to ensure that the lint output isn't interleaved or anything messy.

That was one big problem we had when running the tests in parallel and it's why we now run them serially.

**Comment by JamesHenry** [comment]
@bradzacher Even if they were interleaved in the raw output we still have the advantage of Nx Cloud:

![image](https://user-images.githubusercontent.com/900523/143936182-af003dab-e760-4410-a4be-b4768dfc5f8e.png)

Each one of those each independently linked and the unique output for that task is isolated and reviewable at any time:

![image](https://user-images.githubusercontent.com/900523/143936270-d66e29e5-acd6-4014-ad38-90fde6204842.png)

We could therefore also potentially switch the tests to run in parallel again with this. It's really with `lerna run` that we had the issue of the interleaved outputs I think

**Comment by bradzacher** [comment]
If it handles it then for sure let's parallelise everything!

Cutting down on waiting time on the GH actions is a huge win.
