### ISSUE TITLE
[restrict-template-expressions] unexpectedly slow

### ISSUE THREAD

**Issue by osdiab** [typescript-eslint/typescript-eslint#4251]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/TROUBLESHOOTING.md) and my problem is not listed.

**Repro**

I don't have a repro case, but happy to provide access to my company's repo to see if there's something pathological about it that would cause major perf degradation; but i do have this in our rules:

```JSON
{
  env: {
    browser: true,
    es2021: true,
    node: true,
  },
  extends: [
    "next",
    "eslint:recommended",
    "plugin:react-hooks/recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:import/typescript",
    "plugin:unicorn/recommended",
    // Excludes ESLint's rules that conflict with prettier
    "prettier",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    project: ["./**/tsconfig.json", "./tsconfig.eslint.json"],
    ecmaVersion: 12,
    sourceType: "module",
  },
  plugins: [
    "@typescript-eslint",
    "unicorn",
    "autofix",
    "unused-imports",
    "spellcheck",
    "@emotion",
  ],
  "rules": {
    "@typescript-eslint/restrict-template-expressions": "error", // likely source of bugs
    "@typescript-eslint/consistent-type-definitions": ["warn", "interface"], // interfaces more performant
    "@typescript-eslint/consistent-type-assertions": [
      "warn",
      { assertionStyle: "never" },
    ], // Typecasts make our code unsafe
    "@typescript-eslint/consistent-type-imports": [
      "warn",
      { prefer: "type-imports" },
    ], // prevents bundler from failing to strip out libs just used as types
    "@typescript-eslint/no-unused-vars": ["warn", { ignoreRestSiblings: true }], // nicer in ESLint for autofixing with standard fix command
    "@typescript-eslint/switch-exhaustiveness-check": "error",
    // ... other plugins' rules
  },
  settings: {
    react: { version: "detect" },
    "import/resolver": "eslint-import-resolver-typescript",
  },
}
```

```
// tsconfig.base.json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "baseUrl": ".",
    "jsxImportSource": "@emotion/react",
    "downlevelIteration": true,
    "jsx": "preserve",
    "incremental": true,
    "outDir": ".build-tsc",
    "rootDir": "."
  },
}
```

```
// tsconfig.eslint.json
{
  "extends": "./tsconfig.base.json",
  "include": ["src", "tests", "scripts", "./*.js"],
}
```

```
// .eslintignore
.next
node_modules
.yarn
out
public
build
.github
src/generated
next-env.d.ts
schema.graphql
hasura/
*.json
.eslintrc.js
.build-tsc
```

and we always run with the `--cache` flag on on ESLint in the hope to speed things up.

**Expected Result**

I expect TypeScript ESLint rules to be as performant as they could be

**Actual Result**

When I run ESLint, it seems the `restrict-template-expressions` takes much longer than other typescript ESLint rules, unless I don't understand how the ESLint timing output works. Seems weird that specifically that one is such an outlier. On my beefed up M1 Macbook Pro Max it's tolerable, but on my coworkers' 2019 Intel Macbook Pro 16, ESLint has become basically unusable for him evidently:

```
Rule                                             | Time (ms) | Relative
:------------------------------------------------|----------:|--------:
@typescript-eslint/restrict-template-expressions |  5916.509 |    57.6%
import/order                                     |  1508.903 |    14.7%
spellcheck/spell-checker                         |   502.295 |     4.9%
@typescript-eslint/switch-exhaustiveness-check   |   350.323 |     3.4%
react/no-deprecated                              |   325.509 |     3.2%
@typescript-eslint/no-unused-vars                |   256.722 |     2.5%
autofix/no-unused-vars                           |   195.751 |     1.9%
react/no-direct-mutation-state                   |   117.295 |     1.1%
react/no-string-refs                             |    82.822 |     0.8%
react/jsx-fragments                              |    68.610 |     0.7%
TIMING=1 yarn eslint .  34.02s user 4.31s system 131% cpu 29.242 total
```

If I turn off the `restrict-template-expressions` rule, and clear out the eslint cache, i get this output:

```

Rule                                           | Time (ms) | Relative
:----------------------------------------------|----------:|--------:
import/order                                   |  1524.161 |    28.7%
@typescript-eslint/switch-exhaustiveness-check |  1302.753 |    24.5%
spellcheck/spell-checker                       |   535.883 |    10.1%
react/no-deprecated                            |   301.702 |     5.7%
@typescript-eslint/no-unused-vars              |   281.330 |     5.3%
autofix/no-unused-vars                         |   192.489 |     3.6%
react/no-direct-mutation-state                 |   108.968 |     2.1%
react/no-string-refs                           |    85.096 |     1.6%
react/jsx-fragments                            |    67.098 |     1.3%
react/require-render-return                    |    56.903 |     1.1%
TIMING=1 yarn eslint .  27.49s user 4.19s system 116% cpu 27.215 total
```

Then if I turn off the switch exhaustiveness check, I get this:

```
Rule                              | Time (ms) | Relative
:---------------------------------|----------:|--------:
import/order                      |  1501.405 |    39.1%
spellcheck/spell-checker          |   459.489 |    12.0%
react/no-deprecated               |   289.459 |     7.5%
@typescript-eslint/no-unused-vars |   244.951 |     6.4%
autofix/no-unused-vars            |   211.008 |     5.5%
react/no-direct-mutation-state    |   100.776 |     2.6%
react/no-string-refs              |    82.763 |     2.2%
react/jsx-fragments               |    69.351 |     1.8%
react/require-render-return       |    53.552 |     1.4%
unicorn/import-style              |    44.508 |     1.2%
TIMING=1 yarn eslint .  24.64s user 4.02s system 129% cpu 22.171 total
```

The above experiment is repeatable, i've tried it like 10 times in the last week. Seems that those two rules are particularly costly to our ESLint runs

**Additional Info**

no exceptions

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.5.0` |
| `@typescript-eslint/parser`        | `5.5.0` |
| `TypeScript`                       | `4.4.3` |
| `ESLint`                           | `7.28.0` |
| `node`                             | `14.16.1` |

**Comment by bradzacher** [comment]
> it seems the restrict-template-expressions takes much longer than other typescript ESLint rules, unless I don't understand how the ESLint timing output works.

Type info is generated "lazily" - meaning it's generated the first time it's needed (for perf reasons). Which means the first rule that needs to access, say, the type of the expression being passed to a template expression will get "hit" with that cost.

You can see this from your test - with `restrict-template-expressions` turned on - `switch-exhaustiveness-check` is attributed to taking just 350ms. With `restrict-template-expressions` turned **off** - `switch-exhaustiveness-check` instead is attribute to take 1302ms.
This is because some of the information used by `switch-exhaustiveness-check` is generated as part of the type information required for `restrict-template-expressions` - so by turning it off, you're forcing the `switch-exhaustiveness-check` to bear the cost of the lazy generation instead.

This is all working as intended. Type information takes time to calculate and there's nothing that can be done about that.

---

- https://typescript-eslint.io/docs/linting/troubleshooting#my-linting-feels-really-slow
- https://typescript-eslint.io/docs/linting/type-linting#how-is-performance
- #2878

**Comment by osdiab** [comment]
Makes sense, thanks for the clarification!
