### ISSUE TITLE
Type-checker not detecting enum symbol during test runtime 

### ISSUE THREAD

**Issue by alexnix** [typescript-eslint/typescript-eslint#4269]
Not exactly following the issue template, but this issue is more of a question rather than a bug. I am not sure I use the test utils correctly because the scenario that is correctly picked by running the rule, is not correctly picked by the `RuleTester`.

I will shorty describe the scenario I am looking for: directly using an enum (accessing the whole enum, rather than just one of its members) imported from certain modules will report. The module where the enum is imported from, is *not* linted (because in the real world scenario it is not a local file but it comes from node_modules).

What appears to be happening is that during test runtime the ts type checker cannot tell the the symbol is an enum. My assumption is that weather (1) i am missing  something, such as a configuration or (2) the type checker does not work the same in test runtime and normal runtime.

**Repro**

I created an isolated repo [here](https://github.com/alexnix/eslint_rules_lab).
It includes the custom rule i developed, located in `rules/no-enum-direct-usage.js`
It also includes two scripts to use in order to replicate:
- `yarn dev:enum` : runs my custom rule `no-enum-direct-usage` over the code in `src/enum-import` code - correctly reports the bad scenario
- `yarn test:enum`: runs the tests in `test/no-enum-direct-usage` (uses the `RuleTester` from `@typescript-eslint/experimental-utils` and has the parser configured with a ts project) - fails to report the bad scenario

**Expected Result**

The test for invalid case passes.

**Actual Result**

The test for invalid cases fails because it does not report any error.

Based on my debugging this is because the it cannot tell the symbol is an `enum`.  Using the debugger it can actually be seen that the variable `declarationType` is an error, and has flag=1.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `^5.4.0` |
| `TypeScript`                | `^4.5.2` |
| `ESLint`                    | `^8.3.0` |
| `node`                      | `16.3.0` |

Therefore, my question is weather I am doing something wrong, or this this actually not working?

**Comment by bradzacher** [comment]
you are doing something wrong.
specifically your type-aware tests are executed relative to the test file.
if you don't provide a `filename` to the test, the default one will be used - which is `tsconfigRootDir/file.ts`.

So by reading the file contents from `__dirname/invalid/1.ts`, you're in essence putting that content into `__dirname/file.ts`.
Considering you're looking for the import `../common/foo` - this will resolve to nothing because you have no file `__dirname/../common/foo`.

If you on-disk paths are important, you should use `filename` to ensure the filename is correct.
