### ISSUE TITLE
Suppress TS peer dependency warning

### ISSUE THREAD

**Issue by NickHeiner** [typescript-eslint/typescript-eslint#427]
I acknowledge the risk of using an unsupported version of TS as a peer dependency of `typescript-eslint/typescript-estree`. I'd like an option to suppress the warning so devs on my project aren't desensitized to warnings.

**Comment by JamesHenry** [comment]
Please read: https://github.com/typescript-eslint/typescript-eslint/blob/master/README.md#supported-typescript-version

It explains everything and links you to instructions

**Comment by JamesHenry** [comment]
> warnOnUnsupportedTypeScriptVersion - default true. This option allows you to toggle the warning that the parser will give you if you use a version of TypeScript which is not explicitly supported

**Comment by JamesHenry** [comment]
I can see the linking is not 100% clear, we can improve that. You just need to override the loggerFn like we do for that option I quoted

**Comment by NickHeiner** [comment]
Wow, reading fail on my part. Thanks for the docs and the lightning-fast response.

**Comment by JamesHenry** [comment]
No worries, if you missed it it means it’s not clear enough, we can definitely keep improving things

**Comment by NickHeiner** [comment]
The thing that would have made it totally clear to me is putting the suppression instructions in the warning itself. :smile: That's what I try to do for the tools I write, because the user's attention is relatively focused on those lines, whereas it can be hard to know where to look in the docs.
