### ISSUE TITLE
[no-unnecessary-boolean-literal-compare] attempts to lint .json files 

### ISSUE THREAD

**Issue by alexnix** [typescript-eslint/typescript-eslint#4279]
**Repro**

I created an isolated repo [here](https://github.com/alexnix/eslint_rules_lab).
It includes a script that can be used to see the problem: `yarn use:schema-validate`. This script behaves differently based on:
- rule `no-unnecessary-boolean-literal-compare` is set to `off` -> everything works as expected
- rule `no-unnecessary-boolean-literal-compare` is set to `warn` -> eslint will complain that `You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.` **but** the project is set

**Expected Result**

I can use both `no-unnecessary-boolean-literal-compare` and `json-schema-validator/no-invalid` at the same time.

**Actual Result**

When I activate `no-unnecessary-boolean-literal-compare` i get an unexpected message saying project is not set. 
I can get message gone by:
1. adding .json to `extraFileExtensions` and by including json files in tsconfig
2. removing the override of the parser for json -> the thing is, by doing this (and keeping the plugin and the rule for json validation), nothing will be reported

Therefore my assumption is that that rule `no-unnecessary-boolean-literal-compare` is attempting to lint json files and is opinionated about which parser to use. 

Now, there is a solution which works just fine for me: override the parser for the the json files **and** in the same override, for the rules section, turn off `no-unnecessary-boolean-literal-compare`. But I am submitting this as am sure there is  something more to this problem: weather me not getting the full picture of how it is supposed to work (IMO i should be able to just have both rules enabled and only override the parser for the  json files), or there is some bug to be fixed.

**Comment by bradzacher** [comment]
Lint rules do not do extension checks on files - they just run on whatever you've configured them to run on. This is the standard across all rules in the ESLint ecosystem.

I'd you want to ensure that json files don't have JS or TS rules run on them, then you have to configure ESLint as such.

You can use ESLint's `--print-config` flag to help determine which rules are turned on for a file.
