### ISSUE TITLE
An error occurs if the `ts` file and `d.ts` file name are the same

### ISSUE THREAD

**Issue by stegano** [typescript-eslint/typescript-eslint#4280]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/TROUBLESHOOTING.md) and my problem is not listed.

**Repro**

**tsconfig.json**
```json
{
  "include": ["**/*"],
  "exclude": ["node_modules"]
}
```

**.eslintrc.js**
```js
module.exports = {
  parserOptions: {
    project: 'tsconfig.json',
  },
  plugins: [],
  extends: ['plugin:@typescript-eslint/recommended'],
  rules: {},
};
```

**/pags/index.ts**
```ts
const test = 1;
export default test;
```

**/pages/index.d.ts**
```ts
/**
 * ERROR!! :( - If a file with a `ts` extension with the same name exists, an error occurs as shown below.
 * Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
 * The file does not match your project config: pages/api/aa/vindex.d.ts.
 * The file must be included in at least one of the projects provided.eslint
 */
export interface Test {}
```

**/pages/index2.d.ts**
```ts
// This is fine
export interface Test {}
```

**command**

```bash
eslint 'pages/**/*.{d.ts,ts,tsx}' --fix
```

**Expected Result**
Lint errors should not occur in the `index.d.ts` file even if the `index.ts` file exists.

**Actual Result**
If the `index.ts` file exists, a lint error occurs in the `index.d.ts` file.

**Additional Info**

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `5.6.0` |
| `TypeScript`                | `4.5.2` |
| `ESLint`                    | `8.4.1` |
| `node`                      | `12.22.4` |

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/parser#parseroptionsproject

Third dot point down.

We cannot ignore files. That's not how ESLint works. We just lint the files ESLint tells us to lint.

If you are shadowing your file names then it's up to you to ignore files you don't want to lint using your config.

**Comment by stegano** [comment]
@bradzacher 

I have set both `index.ts` and `index.d.ts` files to lint, but the `index.d.ts` file lint is not working properly.

The `index.d.ts` file must also be included in the lint target.

The focus of this issue is that a lint error occurs when the same file name(index) is included.

For example, if there are two files, index.ts and `index.d.ts`, a lint error occurs in the `index.d.ts` file, but if you rename the `index.d.ts` file to `index.dd.ts`, the error is It doesn't happen.

**Comment by stegano** [comment]
@bradzacher 
Thanks for your reply 😀
After reading the [#955](https://github.com/typescript-eslint/typescript-eslint/issues/955#issuecomment-529075082) issue, I understood everything.
