### ISSUE TITLE
Exported variable 'X' has or is using name 'ParseAndGenerateServicesOptions' from external module "node_modules/@typescript-eslint/typescript-estree/dist/parser-options" but cannot be named.

### ISSUE THREAD

**Issue by jcbdev** [typescript-eslint/typescript-eslint#4287]
I was trying to write a library which uses @typescript-eslint/typescript-estree as a plugin

When trying to export a wrapped call from one of my modules I received a typescript issue:
```
Exported variable 'typescriptCode' has or is using name 'ParseAndGenerateServicesOptions' from external module "node_modules/@typescript-eslint/typescript-estree/dist/parser-options" but cannot be named.
```

See the repro for some example code.

Investigating I can see this is due to way the `TSESTreeOptions` is exported from the library.
See these issues for more info - https://github.com/microsoft/TypeScript/issues/9944#issuecomment-991961720, https://github.com/microsoft/TypeScript/issues/28754#issuecomment-443820268

The issue occurs because TSESTreeOptions is exported in the following manner and is an external alias of an internal type:
```
export type TSESTreeOptions = ParseAndGenerateServicesOptions;
```

As you can see from this comment this does not establish a usable alias https://github.com/microsoft/TypeScript/issues/28754#issuecomment-443907492.  The way it should be exported is as follows:
```
export { ParseAndGenerateServicesOptions as TSESTreeOptions }
```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/TROUBLESHOOTING.md) and my problem is not listed.

**Repro**

```
import { parse, TSESTreeOptions } from '@typescript-eslint/typescript-estree';

export function doSomething(options: TSESTreeOptions) {
    parse(options); //Type resolution should know types are compatible
}
```

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `4.33.0` |
| `TypeScript`                           | `4.3.5` |
| `node`                                 | `16.2.0` |

**Comment by bradzacher** [comment]
> `parse(options); //Type resolution should know types are compatible`

The first param is a `string`. But I assume this was a typo.

Otherwise - I cannot reproduce this.
For example - here is the TS playground repl which works without error:
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzmAhlAzgUwDRwCoDKAogXlJpgPJgzAQB26cAvnAGZQQhwDkAAjACeYTOgDGUYDQC0ogDbB6MAPRCR4yTNExymHgG4AsACgTmAB6RY7AK70xtBnAAmEAl0wwAFooDmACggaOkYALnxiUl1qR0YASkQTOGTkNCx-Hh5cINj0OP04ZWU8YUw4cnQIORtYuHQvCBs5ZzgAa3oIAHc4NVE4NDKxLlRaACM5TBNmEyA
