### ISSUE TITLE
Eslint v8 migration failed to load plugin

### ISSUE THREAD

**Issue by umbertix** [typescript-eslint/typescript-eslint#4321]
I've been trying to upgrade from eslint v7 to v8 in the last couple days but I haven't been able to fix a problem with some package resolutions. I'm not sure if this is the best place to raise this problem but I was hoping someone can help at least to point in the right direction. I would very much doubt if I'm the first one to run into this problem for this repository.

The error in question is Cannot find module 'eslint/use-at-your-own-risk' from '../../node_modules/@typescript-eslint/eslint-plugin/dist/util/getESLintCoreRule.js'

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/TROUBLESHOOTING.md) and my problem is not listed.

**Repro**
Run `yarn test` on the main branch of [this repo](https://github.com/umbertix/eslintV8/)
 
This should use the eslint engine and parse the rules.

**Expected Result**

Run validation without problems and succeeds the tests:
Example run: https://github.com/umbertix/eslintV8/runs/4560231014?check_suite_focus=true

**Actual Result**
Error raised:
`Failed to load plugin '@typescript-eslint' declared in '.eslintrc.js » plugin:@umbertix/recommended:overrides': Cannot find module 'eslint/use-at-your-own-risk' from '../../node_modules/@typescript-eslint/eslint-plugin/dist/util/getESLintCoreRule.js'`

CI reproduction [here](https://github.com/umbertix/eslintV8/runs/4560189905?check_suite_focus=true)
 
**Additional Info**

Running `yarn eslint .` against the repo seems to be fine, that's why I'm not 100% that this repo is the actual problem. But all my other plugins work without a problem. See example above.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `@canary (5.7.1-alpha.17)` |
| `@typescript-eslint/parser`        | `^5.0.0` |
| `ESLint`                           | `8.4.1` |
| `node`                             | `16.10.0` |

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/4210#issuecomment-981203332
