### ISSUE TITLE
Support 'mts' extensions on "overrides.files"

### ISSUE THREAD

**Issue by CemDemirkartal** [typescript-eslint/typescript-eslint#4327]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

TypeScript 4.5.4 currently builds "mts" to "mjs" files. But typescript-eslint limited the "overrides.files" to not add additional types.

Created side branch to test "mts" extensions, and on "Actions" test is available under "Node.js CI on mts/mjs" name

https://github.com/demirkartal/eaglejs/tree/mts/mjs

**Expected Result**

Lint and fix mts files with typescript-eslint

**Actual Result**

Just eslint works and gives error according to javascript rules

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.7.0` |
| `@typescript-eslint/parser`        | `5.7.0` |
| `TypeScript`                       | `4.5.4` |
| `ESLint`                           | `8.5.0` |
| `node`                             | `16.x` |

**Comment by bradzacher** [comment]
`.mts` is not officially supported by TS. Support was dropped from 4.5

https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#esm-nodejs

When TS officially supports it, we too shall officially support it. Until then - of you want to use it ahead of everyone else's you'll need to define your own config.
