### ISSUE TITLE
Netlify deployments randomly failing

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#4335]
This has been showing up on builds here and there. Example: https://github.com/typescript-eslint/typescript-eslint/pull/4334 -> https://app.netlify.com/sites/typescript-eslint/deploys/61c0fa45d8c444000897bf3a

```
4:50:25 PM: ———————————————————————————————————————————————
4:50:27 PM: > nx run @typescript-eslint/eslint-plugin:build
4:50:27 PM: yarn run v1.22.10
4:50:27 PM: $ tsc -b tsconfig.build.json
4:50:32 PM: ../types/src/ts-estree.ts(1,27): error TS2307: Cannot find module './ast-spec' or its corresponding type declarations.
4:50:32 PM: ../types/src/ts-estree.ts(4,16): error TS2664: Invalid module name in augmentation, module './ast-spec' cannot be found.
4:50:32 PM: ../types/src/ts-estree.ts(21,27): error TS2307: Cannot find module './ast-spec' or its corresponding type declarations.
4:50:32 PM: ../types/src/index.ts(1,32): error TS2307: Cannot find module './ast-spec' or its corresponding type declarations.
4:50:32 PM: ../types/src/index.ts(2,33): error TS2307: Cannot find module './ast-spec' or its corresponding type declarations.
4:50:33 PM: error Command failed with exit code 2.
```

...does anybody know why?

**Comment by Josh-Cena** [comment]
What confuses me is that the production build seems to succeed despite deploy previews constantly failing... Unless someone actually keeps rebuilding until the production build succeeds

**Comment by JoshuaKGoldberg** [comment]
> seems the package dependency graph is incorrect

Yeah, bypassing the historical & practical question of why this is the way it is, I think the `project.json` for `eslint-plugin` needs to note the implicit dependency on the `types` package.

**Comment by JoshuaKGoldberg** [comment]
https://github.com/typescript-eslint/typescript-eslint/pull/4381#issuecomment-1008306617

> Is this actually fixed...? Assuming that the recent PRs are based on the latest `main` HEAD, seems they are still failing for the same error?

😞 yeah @Josh-Cena, it's back / still present. https://github.com/typescript-eslint/typescript-eslint/pull/4445/checks?check_run_id=4833084370 -> https://app.netlify.com/sites/typescript-eslint/deploys/61e4469b19500d000783c5f8

```
11:25:41 AM: $ npx nx build website
11:25:48 AM: >  NX  Running target build for project website and 10 task(s) that it depends on.
11:25:48 AM: ———————————————————————————————————————————————
11:25:50 AM: > nx run @typescript-eslint/scope-manager:build
11:25:51 AM: yarn run v1.22.10
11:25:51 AM: $ tsc -b tsconfig.build.json
11:25:55 AM: ../types/src/ts-estree.ts(1,27): error TS2307: Cannot find module './ast-spec' or its corresponding type declarations.
```

What's interesting is that `scope-manager` seems like it _should_ have a transitive dependency on `ast-spec`:

1. `packages/scope-manager/package.json` has `"@typescript-eslint/types` under `dependencies`
2. `packages/types/project.json` includes `"implicitDependencies": ["@typescript-eslint/ast-spec"]`

It's also a bit odd in https://nx.app/runs/62s679jrbFm that `scope-manager` was a cache miss while everything else was a cache hit...?

...maybe this is some kind of NX caching weirdness?

**Comment by bradzacher** [comment]
What's weird is that it only happens on the netlify builds, not on any other build.

**Comment by Josh-Cena** [comment]
Seems the production builds do succeed though?

**Comment by JoshuaKGoldberg** [comment]
I haven't seen this particular failure in a while. Tentatively closing. 🤞
