### ISSUE TITLE
[member-ordering] Not working as expected

### ISSUE THREAD

**Issue by ArtemFrontendACTUM** [typescript-eslint/typescript-eslint#4339]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

```JSON
{
  "rules": {
                   "@typescript-eslint/member-ordering": [
                    "error",
                    {
                        "default": [
                            // Fields
                            "public-field",
                            "protected-field",
                            "private-field",
                            // Constructors
                            "public-constructor",
                            "protected-constructor",
                            "private-constructor",
                             // Getters
                            "public-get",
                            "public-set",
                            "protected-get",
                            "protected-set",
                            "private-get",
                            "private-set",
                             // Methods
                            "public-method",
                            "protected-method",
                            "private-method"
                        ]
                    }
                ]
  }
}
```

```TS
export class A {
    private readonly a = 1;
    b = 2;

    constructor() {}

    method2(): void {}
    private method1(): void {}
}

```

**Expected Result**
```TS
export class A {
    private readonly a = 1;
    b = 2;  // ESLint: Field should be declared before all private fields

    constructor() {}

    method2(): void {} 
    private method1(): void {}
}
```

**Actual Result**

```TS
export class A {
    private readonly a = 1;
    b = 2;

    constructor() {} // ESLint: Member constructor should be declared before all private method definitions.

    method2(): void {}  // ESLint: Member method2 should be declared before all private method definitions
    private method1(): void {}
}
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.8.0` |
| `@typescript-eslint/parser`        | `5.8.0 |
| `TypeScript`                       | `4.0.2` |
| `ESLint`                           | `8.5.0` |
| `node`                             | `12.22.2` |

**Comment by armano2** [comment]
i'm unable to reproduce it, it seem to correctly report error only at like `b = 2;`

[Playground](https://typescript-eslint.io/play/#ts=4.5.2&sourceType=module&code=KYDwDg9gTgLgBAYwDYEMDOa4EE4G8CwAUHCXGFAJYBuKMwcUwKAJhAHZICecKcAvHACMAbiKk4AI35wATKMJjSCdmhhQArghjQAFAEo8AXyKKSAW2AwAFhGYz9ALjhUIFZkdNlKNOnAvXbQUdnV3dcY0JDIA&rules=N4IgAgLgngDgpgZwMYCcCWMIFpEBs0B2EA9ALZykBGcKWA9igCY2EDmIAXANog0oMgANKGYAzAIYBXXBE48YkyviRZRaOLkZCQMfhDhJ9jVes3bdaAG7j9JjVsE7FyrEjoEEEFJMMDHuun1DOGM3Dy8fCD8ddGtbMM9vXxRzZzQVVjhZfzSVBCzzPQMjLEzsmMDikKx88os4uFKC-1ibRtrUpXSscggACzoHCqCS3oGh+raerPGQAF0AX0WgA&tsConfig=N4XyA)

### Code

```ts
export class A {
    private readonly a = 1;
    b = 2;

    constructor() {}

    method2(): void {}
    private method1(): void {}
}
```

<details>
<summary>Expand</summary>

### Eslint config

```json
{
  "rules": {
    "@typescript-eslint/member-ordering": [
      "error",
      {
        "default": [
          "public-field",
          "protected-field",
          "private-field",
          "public-constructor",
          "protected-constructor",
          "private-constructor",
          "public-get",
          "public-set",
          "protected-get",
          "protected-set",
          "private-get",
          "private-set",
          "public-method",
          "protected-method",
          "private-method"
        ]
      }
    ]
  }
}
```

</details>

**Comment by ArtemFrontendACTUM** [comment]
> i'm unable to reproduce it, it seem to correctly report error only at like `b = 2;`
> 
> [Playground](https://typescript-eslint.io/play/#ts=4.5.2&sourceType=module&code=KYDwDg9gTgLgBAYwDYEMDOa4EE4G8CwAUHCXGFAJYBuKMwcUwKAJhAHZICecKcAvHACMAbiKk4AI35wATKMJjSCdmhhQArghjQAFAEo8AXyKKSAW2AwAFhGYz9ALjhUIFZkdNlKNOnAvXbQUdnV3dcY0JDIA&rules=N4IgAgLgngDgpgZwMYCcCWMIFpEBs0B2EA9ALZykBGcKWA9igCY2EDmIAXANog0oMgANKGYAzAIYBXXBE48YkyviRZRaOLkZCQMfhDhJ9jVes3bdaAG7j9JjVsE7FyrEjoEEEFJMMDHuun1DOGM3Dy8fCD8ddGtbMM9vXxRzZzQVVjhZfzSVBCzzPQMjLEzsmMDikKx88os4uFKC-1ibRtrUpXSscggACzoHCqCS3oGh+raerPGQAF0AX0WgA&tsConfig=N4XyA)
> 
> Expand

Seems like TS version issue.

**Comment by bradzacher** [comment]
I tried reproing this against TS v4.0.5 as well ([playground](https://typescript-eslint.io/play/#ts=4.0.5&sourceType=module&code=PQKgUApgzgNglgOwC4AIBEABJBPADtAYwCc5ckBaaeZYAWwloCMIjyB7IgExcQHM0AXCgDaYFOImTxaFkQ5oANGKkqA3spWb03AGYBDAK4wkgkWA1bLaXAcbwC5HXAgxOii5c3W5SCAV+cjs6u7p6e3nAAbnq+QS5uSmGWHkkS1rb25ARsCFBIRAb+8ompKt5svv4Qgdm5+YVIxSmlEdGxtXkFRUShpVLNqel2cA68ECYlfWk2ww5Q471T0rg+fgHkYxMDSeWV6-NbS9MkbRAbC5NLrTFnB4tL22FDmfRIABZsCY-hKxVr1eRXh8vkdlicboDxsC0N8pABdWEAXwGCJAwHMEAAHrgOKgCDA9FAoCgAIIodSSFZRG4oIgQPScHIwbAoPQoAC8KAAjABuCyMDkoABMfIsHXq3QAFABKcnIixAz5CmVCSJsOCcOUWKmnFCKzhclUoNUarWIoA&rules=N4XyA&tsConfig=N4XyA)) and it works fine as well.

**Comment by ArtemFrontendACTUM** [comment]
> I tried reproing this against TS v4.0.5 as well ([playground](https://typescript-eslint.io/play/#ts=4.0.5&sourceType=module&code=PQKgUApgzgNglgOwC4AIBEABJBPADtAYwCc5ckBaaeZYAWwloCMIjyB7IgExcQHM0AXCgDaYFOImTxaFkQ5oANGKkqA3spWb03AGYBDAK4wkgkWA1bLaXAcbwC5HXAgxOii5c3W5SCAV+cjs6u7p6e3nAAbnq+QS5uSmGWHkkS1rb25ARsCFBIRAb+8ompKt5svv4Qgdm5+YVIxSmlEdGxtXkFRUShpVLNqel2cA68ECYlfWk2ww5Q471T0rg+fgHkYxMDSeWV6-NbS9MkbRAbC5NLrTFnB4tL22FDmfRIABZsCY-hKxVr1eRXh8vkdlicboDxsC0N8pABdWEAXwGCJAwHMEAAHrgOKgCDA9FAoCgAIIodSSFZRG4oIgQPScHIwbAoPQoAC8KAAjABuCyMDkoABMfIsHXq3QAFABKcnIixAz5CmVCSJsOCcOUWKmnFCKzhclUoNUarWIoA&rules=N4XyA&tsConfig=N4XyA)) and it works fine as well.

Well, I checked it and it has nothing to do with the TS version. In playground it works fine, but in playground config is different, no plugins, it's not the issue reproduction.

**Comment by ArtemFrontendACTUM** [comment]
@bradzacher  Sorry, it's definitely a bug of this rule.

With rule enabled:
![image](https://user-images.githubusercontent.com/92377236/147361251-dcecfe7b-c31a-4015-a174-6d20b75eaa2c.png)

With rule disabled: 
![image](https://user-images.githubusercontent.com/92377236/147361264-f379654e-e940-431e-9d2c-4b4ecc369697.png)

Basically, all other rules (around 100+) are working fine.

Sorry, your playground proves nothing.

**Comment by bradzacher** [comment]
My link shows that using the config you provided on the code you provided - it works as expected, using the expectations you provided.

If you can create a repro using the playground (which is a clean ESLint setup that is 100% isolated and reproducible), then I will gladly investigate further.
