### ISSUE TITLE
Docs: Development environment setup guide

### ISSUE THREAD

**Issue by tapanprakasht** [typescript-eslint/typescript-eslint#4363]
### Suggested Changes

I am looking for a development setup guide for typescript-eslint project. Contributing.md doc talks about creating PR, installing dependencies, running test and checks to be done before raising a PR. But I couldn't find proper documentation around setting the project in some IDE, let's say VSCode then able to debug the codebase by putting breakpoints. Looks like the documentation around this is missing and would help people who are interested in contributing to the project.

### Affected URL(s)

https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md

**Comment by JoshuaKGoldberg** [comment]
Agreed, and thanks for filing this @tapanprakasht! Accepting PRs to add a mention for the VS Code debugging setup that's built in.

FWIW you should be able to put a breakpoint in a file and run the appropriate VS Code debug command.

![Screenshot of several VS Code debug options](https://user-images.githubusercontent.com/3335181/147770050-b8e9b316-1257-459c-96d3-adf57e64956a.png)

**Comment by tapanprakasht** [comment]
> docs: mention VS Code debugging tasks in CONTRIBUTING.md #4374

Thanks this helps 👍
