### ISSUE TITLE
Investigate missing "financial contributors" section contents

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#4370]
This was mentioned somewhere, I want to say in Slack?

We should have someone look at the _Financial Contributors_ section on the homepage and make sure it includes _all_ financial contributors.

Edit: it's because the data is sourced from https://github.com/typescript-eslint/typescript-eslint/blob/31d9c8e5f15941a89a770bf32ddb9d2a70601c98/packages/website/data/sponsors.json#L1. We should update that automatically and/or have it be realtime.

**Comment by JoshuaKGoldberg** [comment]
Well, OpenCollective lists more than a dozen recurring supporters:

![Screenshot of multiple recurring sponsor sections on OpenCollective](https://user-images.githubusercontent.com/3335181/147777142-58cc6570-d27c-431b-936b-dba1d4b0c3f9.png)

...but the website right now only lists nine, including one with initials instead of a photo:

![Screenshot of the website with nine sponsors](https://user-images.githubusercontent.com/3335181/147777162-a1a6e0ca-e199-4ab8-aede-854c10a2229d.png)

Something fishy is happening!

**Comment by JoshuaKGoldberg** [comment]
Oh, it's all sourced from https://github.com/typescript-eslint/typescript-eslint/blob/31d9c8e5f15941a89a770bf32ddb9d2a70601c98/packages/website/data/sponsors.json.

**Comment by bradzacher** [comment]
We might want to have a job which periodically updates this file? (Same with the contributors file)

That way our builds don't depend on any web requests. Or we could just query for them from the website live? Depends if we want to add another 3rd party query dependency and risk not showing them if something goes down.

**Comment by JoshuaKGoldberg** [comment]
Yeah my instinct is to MVP it with a cron job on GHA.
