### ISSUE TITLE
Install packages as git dependency

### ISSUE THREAD

**Issue by corbinu** [typescript-eslint/typescript-eslint#44]
Hello all,

I am wondering how I depend on the the various packages from git in this new monorepo as currently I depend on master for both eslint-plugin-typescript and typescript-eslint-parser. 

Thanks,

Corbin

**Comment by j-f1** [comment]
You can install `typescript-eslint/typescript-eslint` then require `typescript-eslint/packages/foo`.

**Comment by corbinu** [comment]
@j-f1 wouldn't that mean I would have to fork and change the requires in each package?

**Comment by armano2** [comment]
better question is why do you need changes from master? it's just for you (not for project), you should consider using links `yarn link` or `npm link`,

something like this:

```bash
cd ../typescript-eslint/
yarn build
cd ./packages/eslint-plugin-typescript
yarn link
cd ../../../your-project
yarn link eslint-plugin-typescript
```

**Comment by corbinu** [comment]
@armano2 It has been to keep pace with all the changes. I publish my own eslint config so that has been depending on master (or even my own fork of the parser that included some of your PRs) ever since TypeScript 3.2 released (so about 6 weeks). 

This was why I proposed a nightly release of the projects. I have seen very little breakage and the fast progress that has been made has been well worth it.

However the monorepo it seems makes it impossible to publish a module that depends on the most recent commits.

I have been maintaining a fork of the parser under my own scope anyway so perhaps the only option is for me to do the same with the other packages also.

**Comment by corbinu** [comment]
@JamesHenry Would you be willing to reopen the idea of a nightly? I am happy to take care of the PR.

Just a bot that would cut off master every night so those that want to be on the edge and tag the release as `nightly`

**Comment by JamesHenry** [comment]
Good news, @corbinu - I have now set things up to publish a canary release on every commit!

E.g.

https://www.npmjs.com/package/@typescript-eslint/eslint-plugin

```
Current Tags
    1.0.0
    latest
    1.0.1-alpha.8
    canary
```

**Comment by corbinu** [comment]
@JamesHenry Your my hero!
