### ISSUE TITLE
[consistent-type-exports] Definition for rule '@typescript-eslint/consistent-type-exports' was not found

### ISSUE THREAD

**Issue by CharlesStover** [typescript-eslint/typescript-eslint#4412]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**

[This minimal repo](https://github.com/CharlesStover/monorepo-template)

[This commit](https://github.com/CharlesStover/monorepo-template/commit/9ca78c68104752a803c8c7f5a2f83eae155cb676) was added as a pull request.

[This `.eslintrc.json` file](https://github.com/CharlesStover/monorepo-template/blob/9ca78c68104752a803c8c7f5a2f83eae155cb676/packages/eslint-config-typescript-fixable/src/.eslintrc.json) was added, which adds `"@typescript-eslint/consistent-type-exports": "error"`.

[This build failure](https://github.com/CharlesStover/monorepo-template/runs/4749563968?check_suite_focus=true#step:6:10) occurred as a result: `Definition for rule '@typescript-eslint/consistent-type-exports' was not found`

**Expected Result**

`eslint` should pass.

**Actual Result**

`eslint` fails with `Definition for rule '@typescript-eslint/consistent-type-exports' was not found`

**Additional Info**

N/A

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.9.0` |
| `@typescript-eslint/parser`        | `5.9.0` |
| `TypeScript`                       | `4.5.4` |
| `ESLint`                           | `8.6.0` |
| `node`                             | `latest` |

**Comment by bradzacher** [comment]
https://typescript-eslint.io/docs/linting/troubleshooting/#how-do-i-check-to-see-what-versions-are-installed

Your issue: https://github.com/CharlesStover/monorepo-template/blob/main/yarn.lock#L4341
