### ISSUE TITLE
Docs: No way to set transpilation options in playground?

### ISSUE THREAD

**Issue by Josh-Cena** [typescript-eslint/typescript-eslint#4414]
### Suggested Changes

I'm trying to reproduce this in the playground:

```ts
const foo = new Map<string, string>();
let bar: string;
for (const [key, value] of foo.entries()) {
  bar = value; // "@typescript-eslint/no-unsafe-argument"
}
```

However, TS tells me that:

```
Type 'IterableIterator<[string, string]>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.(2569)
```

This is probably because the target is set to the default `ES3` in the playground. There's no way for me to either set `target` or enable `downlevelIteration`...

### Affected URL(s)

[Playground link](https://typescript-eslint.io/play#ts=4.5.2&sourceType=module&code=MYewdgzgLgBAZiEMC8MwFMDuMCyBDABwB5oAnASzAHMAaGMyqgPgAoBKAbgCgAbdWAEZ5SALnpQK1bglIwWoSLADaAa3QBPOgDc8PAK7oAujBBx4iAHTowE8ugjs2MAN5cYMIbNQ796DjAB6AJh7HkpYOB48KggYKAALcliwjBg8WLwYLXIQKKgcsBMzACIAASh1AntgCgIoAFpQ8ICwEHq9SDw4dHrhKj0AW2soYq4AXy4gA&rules=N4IgAgLgngDgpgZwMYCcCWMIFpEBs0B2EA9AQPZYCuBCAhgGZxa0oDmlAtnESAFwhwUKMihABfIA&tsConfig=N4IgzgLgTglgxhEAuaBXApgXyA)

**Comment by bradzacher** [comment]
cc @armano2 as an FYI

**Comment by lonyele** [comment]
I investigated the code and found that target is set to `Latest`(ES.NEXT)
https://github.com/typescript-eslint/typescript-eslint/blob/b83f59751956a0acf1ec6747a41c3911ce83a258/packages/website-eslint/src/linter/create-ast-program.js#L27-L33

I tried on the [playground](https://typescript-eslint.io/play/#ts=4.5.2&sourceType=module&code=MYewdgzgLgBAZiEMC8MwFMDuMCyBDABwB5oAnASzAHMAaGMyqgPgAoBKAbgCgAbdWAEZ5SALnpQK1bglIwWoSLADaAa3QBPOgDc8PAK7oAujBBx4iAHTowE8ugjs2MAN5cYMIbNQ796DjAB6AJgAIgABKHUCe2AKAigAWnseSigAsBAEvUg8OHQE4So9AFtrKBCuAF8gA&rules=N4IgAgLgngDgpgZwMYCcCWMIFpEBs0B2EA9AQPZYCuBBcSiCAhilFkmQQCZoRocgAuEHBQoyKEABpw0eMnSYcCfEVIVqtegiYsssuFmYBzSgFs4RBIOGjxIAL5A&tsConfig=N4IgJg9g7gdgNgUwG4LgSQC4IE4EMMCWEMIAXBtgK4IC+QA) and I found that it's working as expected just...
1. all the ts configs are not on the modal. It seems like only something that [uses frequently are on the list.](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/website/src/components/tsConfigOptions.json)
2. I set it manually by click button `Edit Json` and put `downlevelIteration: true` made it working(check above playground)

I was trying to make a PR by putting more ts configs to the json but not sure which should be included or not. Maybe configs that are at [https://www.typescriptlang.org/play](https://www.typescriptlang.org/play)'s configs? or putting all configs?(which seems really bad for UX, but seems possible? by looking at this [schema](https://github.com/microsoft/TypeScript-Website/blob/3f5eb54cf25858d7f6487520c6896853858753e7/packages/tsconfig-reference/scripts/schema/vendor/base.json)

**Comment by Josh-Cena** [comment]
There's certainly something wrong with the target, because [this](https://typescript-eslint.io/play#ts=4.5.2&sourceType=module&code=MYGwhgzhAECC0G8BQ1XQOYFMAu0wAoBKRFNMgJxwFdyA7aARgG5TUBfJNoA&rules=N4XyA&tsConfig=N4XyA) doesn't work either

**Comment by lonyele** [comment]
Yeah, you are right. It is weird that the below code is using some appropriate config input and I get same ouput as input by testing `sandboxInstance.getCompilerOptions()`.   But the playground is saying about `Accessors are only available when targeting ECMAScript 5 and higher.` .... hm... not sure what is wrong
https://github.com/typescript-eslint/typescript-eslint/blob/e7857aa2975412b43c62cd9c55e9f16d09f6a8aa/packages/website/src/components/editor/useSandboxServices.ts#L51-L76

**Comment by armano2** [comment]
hmm, that interesting, i didn't though that this is going to be an issue, but generally yes, we have to let libs to load libs and property propagate supported features, i'm going to take a look at this
