### ISSUE TITLE
Docs: Add more explanation for [no-namespace] rule

### ISSUE THREAD

**Issue by didii** [typescript-eslint/typescript-eslint#4431]
### Suggested Changes

Currently, the reasoning behind the `no-namespace` rule is the following.

> This rule aims to standardize the way modules are declared.

Which is fine, but seems more like a personal preference kind of thing than an actual guideline. Which is still fine.

However, using namespaces has more side-effects than most people would imagine. For example, when using webpack 5 in `'production'` mode, it will change a namespace to just a plain object, which might be a problem for minification. Note that webpack 5 uses Terser as its minification tool by default.

For example:

```ts
export namespace MyNamespace {
  export const myValue = true;
}

if (MyNamespace.myValue) {
  console.log('myValue is true');
}
```

will look something like this after minification:

```js
var De;!function(e){e.myValue=!1}(De||(De={}));const He=De;He.myValue&&console.log('myValue is true');
//Declaration: 59 characters
//Usage: 12 characters + length of statement
```

while using it without a namespace like so

```ts
export const myValue = true;

if (MyNamespace.myValue) {
  console.log('myValue is true');
}
```

will result in the following

```js
const myValue=!0;console.log('myValue is true');
//Delcaration: 17 characters
//Usage: length of statement
```

Note the complete absence of any check on the value of `myValue`, since at compile-time, we already know that the value will always be `true`. Due to how namespaces are translated to JavaScript, this aspect of minification is lost which might (or might not) be important to a user.

---

To conclude: using namespaces has more negative impact that a typical user might expect. Since es-lint is great at teaching little things at a time, I think it would be of good value if this aspect of namespaces could be included into the documentation. We'll probably need to trim some of it down, so it doesn't become a clog to read, but notifying users that using namespaces has more of an impact than just standardizing a way to define your module could be helpful.

### Affected URL(s)

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-namespace.md

**Comment by bradzacher** [comment]
> For example, when using webpack 5 in 'production' mode, it will change a namespace to just a plain object

That's not webpack doing it - it's TS doing it.
A namespace isn't an actual JS construct - so TS converts all namespaces to plain objects.

```ts
namespace Foo {
  // code
  export const x = 1;
}
// merging
namespace Foo {
  // code
  export const y = 2;
}
```
is transformed by TS to:
```ts
var Foo;
(function (Foo) {
    // code
    Foo.x = 1;
})(Foo || (Foo = {}));
// merging
(function (Foo) {
    // code
    Foo.y = 2;
})(Foo || (Foo = {}));
```
[ts playground](https://www.typescriptlang.org/play?#code/HYQwtgpgzgDiDGEAEAxA9mpBvAUEpA9AUvGgCYR5IQAeMaATgC4lrBQs1IC8SAjAG4cAXxxEkkBgHMAlsCk5QkWAmTpMufONIUqtes1bsWATx5IATENFA)

Which your webpack build then minifies and obfuscates as per your config.

---

> Currently, the reasoning behind the no-namespace rule is the following.

There is also the paragraph above that line, which is the actual reason for the rule:

> Custom TypeScript modules (module foo {}) and namespaces (namespace foo {}) are considered outdated ways to organize TypeScript code. ES2015 module syntax is now preferred (import/export).
