### ISSUE TITLE
[no-extra-parens] Definition for rule '@typescript-eslint/no-extra-parens' was not found

### ISSUE THREAD

**Issue by iapYang** [typescript-eslint/typescript-eslint#444]
```JSON
{
  "rules": {
    "@typescript-eslint/no-extra-parens": ["error"],
  }
}
```

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `^1.6.0` |
| `@typescript-eslint/parser`        | `^1.6.0` |
| `TypeScript`                       | `^3.4.3` |
| `ESLint`                           | `^5.16.0` |
| `node`                             | `v8.10.0` |
| `npm`                              | `5.6.0` |

![image](https://user-images.githubusercontent.com/13792624/56415971-fd561c80-62c1-11e9-90a3-1c853a586289.png)

**Comment by bradzacher** [comment]
We haven't released this yet!
If you want to use this rule, please use the `canary` tag on NPM

**Comment by iapYang** [comment]
@bradzacher 
thx!
