### ISSUE TITLE
[naming-convention] camelCase with underscore

### ISSUE THREAD

**Issue by thegreatgreendragon** [typescript-eslint/typescript-eslint#4468]
- [ x] I have tried restarting my IDE and the issue persists.
- [ x] I have updated to the latest version of the packages.
- [ x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**
https://github.com/thegreatgreendragon/eslint-problem

```JSON
{
  "root": true,
  "ignorePatterns": [
    "projects/**/*"
  ],
  "overrides": [
    {
      "files": [
        "*.ts"
      ],
      "parserOptions": {
        "project": [
          "tsconfig.json",
          "e2e/tsconfig.e2e.json"
        ],
        "createDefaultProgram": true
      },
      "extends": [
        "plugin:@angular-eslint/ng-cli-compat",
        "plugin:@angular-eslint/ng-cli-compat--formatting-add-on",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],
      "rules": {
        "import/no-deprecated": 0,
        "jsdoc/check-alignment": 0,
        "no-shadow": "off",
        "@typescript-eslint/no-shadow": ["error"],
        "@typescript-eslint/naming-convention": [
          "error",
          {
              "selector": "default",
              "format": ["camelCase"],
              "filter": {
                "regex": "^(_)$",
                "match": false
              }
          },
          {
            "selector": ["class", "interface"],
            "format": ["PascalCase"]
          },
          {
            "selector": ["property"],
            "format": null,
            "filter": {
              "regex": "\\\\A[a-z_]{1}[a-zA-Z0-9_]*?\\\\b",
              "match": true
            }
          },
          { "selector": ["typeParameter", "typeAlias"], 
            "format": ["PascalCase"]
          },
          { "selector": ["enum", "enumMember"], 
            "format": null            
          },          
          {
            "selector": ["variable", "function"],
            "format": ["camelCase"],
            "leadingUnderscore": "allow",
            "filter": {
              "regex": "^(_)$",
              "match": false
            }
          },
          {
            "selector": "memberLike",
            "modifiers": ["private"],
            "format": ["camelCase"],
            "leadingUnderscore": "allow"
          }
        ],
        "jsdoc/newline-after-description": 0,
        "prefer-arrow/prefer-arrow-functions": 0,
        "@angular-eslint/component-class-suffix": [
          "error",
          {
            "suffixes": [
              "Component",
              "Page",
              "Layout",
              "Modal",
              "Control",
              "Stub"
            ]
          }
        ],
        "@typescript-eslint/consistent-type-definitions": "error",
        "@typescript-eslint/dot-notation": "off",
        "@typescript-eslint/explicit-member-accessibility": [
          "off",
          {
            "accessibility": "explicit"
          }
        ],
        "@typescript-eslint/no-unused-vars": [
          "error",
          {
            "vars": "all",
            "args": "after-used",
            "argsIgnorePattern": "fn|_"
          }
        ],
        "@typescript-eslint/no-use-before-define": 0,
        "brace-style": [
          "error", "1tbs", { "allowSingleLine": true }
        ],
        "id-blacklist": "off",
        "id-match": "off",
        "max-len": [
          "error",
          {
            "code": 240
          }
        ],
        "no-underscore-dangle": "off"
      }
    },
    {
      "files": [
        "*.html"
      ],
      "extends": [
        "plugin:@angular-eslint/template/recommended"
      ],
      "rules": {}
    }
  ],
  "plugins": [
    "jasmine"
  ],
  "extends": [
  ],
  "rules": {
    "jasmine/no-focused-tests": "error"
  },
  "settings": {
    "import/parsers": { "@typescript-eslint/parser": [".ts"] },
    "import/resolver": { "eslint-import-resolver-typescript": true }
  },
  "env": {
      "jasmine": true
  }
}
```

```TS
// your repro code case
export interface LintTestModel {
  id: number;
  processed_OpenAmount: number;
  isPaid: boolean;
  IsSold: boolean;
}
```

**Expected Result**

I except that the linter only throws an error on the property `IsSold`.
`Type Property name `processed_OpenAmount` must match one of the following formats: camelCaseeslint@typescript-eslint/naming-convention
`

**Actual Result**
It throws an error on `IsSold` and `processed_OpenAmount`
`Type Property name `processed_OpenAmount` must match one of the following formats: camelCaseeslint@typescript-eslint/naming-convention
`

Why is this happening? 
I have a rule that should allow the underscores 

```
{
            "selector": ["property"],
            "format": null,
            "filter": {
              "regex": "\\\\A[a-z_]{1}[a-zA-Z0-9_]*?\\\\b",
              "match": true
            }
          },
```
when I chance filter to `custom` every property in `LintTestModel` throws: 
`Type Property name `processed_OpenAmount` must match the RegExp: /\\A[a-z_]{1}[a-zA-Z0-9_]*?\\b/ueslint@typescript-eslint/naming-convention
`
What do I do wrong?

**Versions**
| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.3.0` |
| `@typescript-eslint/parser`        | `5.3.0` |
| `TypeScript`                       | `4.4.3` |
| `ESLint`                           | `8.2.0` |
| `node`                             | `14.18.3` |

**Comment by Josh-Cena** [comment]
[Playground link](https://typescript-eslint.io/play#ts=4.5.4&sourceType=module&code=KYDwDg9gTgLgBASwHY2FAZgQwMbDgGWRgBVgBnGAWQgBNgAbOAbwCg5EaAuOJAVwFsARmgDcbOGCgRcZMsBoB9APJhgSAIL8IvFNz5DR4hGQAKmBFziCIEesExIx7AJJkAyrcvXb9xywC+LEA&rules=N4IgAgLgngDgpgZwMYCcCWMIFpEBs0B2EA9AQIYC2hA5lkgPYEBucRajIAXANohwop6KEABpQCOLjhIIQriAAmcAGZkArrgiiQyoRTJaeIJJUkBhMhJABdETrSb+XUCjjU4AD3kA9ABQB9AEoAEm19CCQACy5VXAkAX3ixEAkpGTkjJFxLBG1CCH5VJDgbO10UcK5eAAVLE1wLK2sk8UlpWWEjGEF4FGhSnT0DLgINXDKHAs6XN095AB1F+YBBbjIsAC9-a2AARni1zeWsAC0ABiwATm2AKgB+JfmAIzCDKK4IFDU4ROTU9oyvGg8FqKFMU20wLgy3wlgG5UqRlqyDIDUsJWafza6U6vFYago2nxFAAsnAKE8nLZBhVhpxRrhcC0UtiOlUQEwyOgyE8pNplGoCDJ2AR4UNDLwTBRzOiBlIyAoaABVAhKFDIIQlTggVG4egAd35kycnBm7i82r8QVCdnC704sQSzP+OPk0op-AAMmgANYlW30RXKND8XJddCcgpi2kS4ymNFNOzyxUEagqtUa1zyXUGkDxZpAA&tsConfig=N4XyA)

**Comment by bradzacher** [comment]
Your regex is your issue.
`"\\\\A[a-z_]{1}[a-zA-Z0-9_]*?\\\\b"` is the same as the regex literal:
```js
  /\\A[a-z_]{1}[a-zA-Z0-9_]*?\\b/
// ^^ \\ === matches a "\" character... which is never going to be valid in an identifier
//   ^ name must start with an "A"
//    ^^^^^^^^^ name must have exactly 1 [a-z_].
//             ^^^^^^^^^^^^^^ name must have 0 or more [a-zA-Z0-9_], reluctant match.
//                           ^^ name must have a "\" character (ditto above - impossible)
//                             ^ name must end in a "b"
```

I don't know what you were trying to match exactly - all I know is that this regex won't match it

**Comment by thegreatgreendragon** [comment]
Thanks for the reply. After a weekend not thinking about the problem I figured it out.
I used regex101.com to check my regex, but I forgot to set it to Javascript. I used the PHP version 😶

So I tried again and got myself a working regex `^[a-z_]{1}([a-zA-Z0-9_]{0,})$`
