### ISSUE TITLE
Playground should warn me about invalid config JSON real-time

### ISSUE THREAD

**Issue by Josh-Cena** [typescript-eslint/typescript-eslint#4469]
### Suggested Changes

Currently, the config editor is just a plain textarea, which seems to have no input validations. If I entered some invalid JSON, the error is silently swallowed and the config is still the last valid object. I think it would be better if there could be a warning if the config is invalid: it doesn't have to be squiggly lines, just some cue that tells me there's an error.

### Affected URL(s)

https://typescript-eslint.io/play

**Comment by bradzacher** [comment]
yeah I was thinking this as well.
we should probably make it a monaco instance and add the eslint JSON schema as a validator so we can have some real-time validation.

or perhaps do something with types? unsure what the best course of action is - but definitely something richer would be great!

**Comment by niko-achilles** [comment]
@bradzacher  you can actually create json-schema and generate types from the json-schema .

**Comment by armano2** [comment]
there was bunch of changes to playground and this suggestion has been applied in #5088 and #5125

@Josh-Cena let me know if we can close this one

**Comment by Josh-Cena** [comment]
Ah yes, I can see it works nicely now
