### ISSUE TITLE
Change ESLint rule creator doc URL base to the website

### ISSUE THREAD

**Issue by Josh-Cena** [typescript-eslint/typescript-eslint#4487]
### Suggested Changes

```ts
export const createRule = ESLintUtils.RuleCreator(
  name =>
    `https://github.com/typescript-eslint/typescript-eslint/blob/v${version}/packages/eslint-plugin/docs/rules/${name}.md`,
);
```

It currently points to the GitHub interface; however, since we have a website already, let's change that to the website instead.

### Affected URL(s)

None...

**Comment by JoshuaKGoldberg** [comment]
Makes sense! I thought we had a todo for this somewhere but can't find it now... yes please!

**Comment by snitin315** [comment]
I will work on it as my first contribution.

**Comment by JoshuaKGoldberg** [comment]
My mistake, duplicate of #4368. Sorry for the noise folks!
