### ISSUE TITLE
Readonly vs Immutable

### ISSUE THREAD

**Issue by RebeccaStevens** [typescript-eslint/typescript-eslint#4536]
I was thinking that we may want to differentiate between a "Readonly" type and an "Immutable" type.

### Overview

Proposed definitions:

 - Immutable: Fully, deeply readonly. Everything is read only and nothing can be modified.
 - Readonly: Only the data is immutable.

So using these definitions, the built-in `ReadonlyArray`, `ReadonlySet` and `ReadonlyMap` are all "Readonly" but not "Immutable".

### Readonly vs Immutable

Consider the mutable type `Array<T>`.

The readonly version (`ReadonlyArray<T>`) is not just `ReadonlyDeep<Array<T>>`, but rather it is `Array<T>` but where all fields are readonly and the methods that cause mutation are removed.

Now consider the immutable version; it would be the readonly version but with everything being readonly, so: `ReadonlyDeep<ReadonlyArray<T>>`.

### Consequences

The rule `prefer-readonly-parameter-types` and the function `isTypeReadonly` would probably need to be reworked.

A readonly type would be defined as an immutable type or a type from a list of known readonly types.
Thus we would need to have a list of readonly types. This list would have to be user configurable so more readonly types can be added.

We would most likely want a mapping of types to readonly types (and possible also to immutable types for the purpose of a fixer).
For example: `Array<> => ReadonlyArray<> => ReadonlyDeep<ReadonlyArray<>>`.

This would also give us a list of non-readonly types. Thus we can then also state that a readonly type is not a known non-readonly type.

### Implementation

As there is currently only a single rule that uses this readonly data (`prefer-readonly-parameter-types`) information, this might be overkill. But as more rules are added this will become an important differentiation.

This might become too much for this core project and it might want to be siphoned off into it's own plugin.

I would like to hear feedback from everyone on your thoughts about this and how we may proceed. @bradzacher

**Comment by qpwo** [comment]
Random outsider here

> - Immutable: Fully, deeply readonly. Everything is read only and nothing can be modified.
> - Readonly: Only the data is immutable.

To me, those definitions sound fairly natural and seem to divide things up fairly well.

**Comment by qpwo** [comment]
You know I'm not sure if this thought belongs here but I wonder what one could do overriding the global types, like the division between node types and browser types (e.g. on setTimeout).

You could override the global `Array` to one without `.push`, then see where you get errors. Maybbbe it could somehow be possible to override how classes work, I suppose involving `Object.prototype` so e.g. all properties are getters by default?

I'm pretty out of my depth here and it may be an over-extension of the basic tooling but it seems like certain tasks that are really hard in other ways could be made relatively doable with global type overrides.

In any case I doubt this plugin would use such a technique.

**Comment by JoshuaKGoldberg** [comment]
> This might become too much for this core project and it might want to be siphoned off into it's own plugin.

Indeed - the lack of discussion on this issue (~5-6 months with only one other participant) makes me think this should be tried in a community plugin first. I'll go ahead and close this issue for now. But if anybody reading this thinks we should seriously reconsider, please do post here with why!

And - thanks so much for the detailed post @RebeccaStevens! 🙌
