### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by niko-achilles** [typescript-eslint/typescript-eslint#4547]
### Suggested Changes

Does a json-schema exist for supporting the configuration of eslint with typescript-eslint  or definitely @types of typescript-eslint ? 

Also in the documentation of the website  typescript-eslint , please mention which configuration attributes of eslint  you override , given 
the preferable workflow to initialize an eslint configuration is via eslint --init
and answering to the questions of the command eslint --init .
It is known that the information can be found if someone want to search on your repo, but why this time consumption?    

e.g i get the following after answering the questions that are applicable to an example project.

Then i can install packages like `eslint-config-prettier` and extend my eslint configuration or 
i  can define rules 
and is worth to mention that for eslint rules i get support on typing but for typescript-eslint not.   
 
````json
{
  "env": {
    "es2021": true,
    "node": true
  },
  "extends": ["eslint:recommended", "plugin:@typescript-eslint/recommended"],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2021,
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint"],
  "rules": {}
}

```

 

### Affected URL(s)

https://typescript-eslint.io/docs/linting/

**Comment by niko-achilles** [comment]
I know that `ESLint`, uses `json-schema` to provide support to the developer for typing a `lint` file in `json` of course. 
Here is actually the handcrafted schema of ESLint: [link](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/eslintrc.json)
Nice and smart.

In the website of [typescript-eslint](https://typescript-eslint.io/docs/linting/) you write : 
`..... This is about the smallest config file we recommend. There's a lot more you can add to this as you further onboard, but this will be enough to get you started.`  

Question: Are small correct functional things usable ? 
If the extension of the `well-characterized`  as `small config` in the `doc link` mentioned above was `json` , and it is functional correct , then we could say that we have a `usable` small thing. 

But that is not the case. We have a small correct functional and `not` usable small config. Not usable because we have `no` support on typing. The truth is that we sacrificed  `config. usability` with `config. power` .
We have for a small config  a `eslintrc.js` file that has the potential to be powerful, but not usable. But we have not yet decided about the balance between usability and config. power.

So this is something that you can improve . Balance the `config usability` with `config power`.  I have seen developers starting directly with  a `.js` config without using any of the `config powers` a `.js` config provides. 
For the `small config` you suggest to start with `typescript-eslint`,  the config file extension respecting usability would be `.json` .

And here we come to a point. The small config is `usable` in context of ESLint but not in context of `typescript-eslint`. No typing support for typescript-eslint .  
So what can we do ? 

Option 1 (better balance between usability and power)
navigate to the playground of typescript-eslint: [link](https://typescript-eslint.io/play) 

Option 2 (desired balance between usability and power)
JSON Schema for typescript-eslint . 
Usage in IDE of developer.  :)
Everything can be extended , either by applying engineering skills or collaboration skills. And because we are defined by time, typescript has proven the ability of collaboration with other tools like `babel collaboration`, etc .

Finally the second improvement would be to add in the small config section in the doc website the information of typescript-eslint, [link](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/base.ts)

Again usability, balance , we should know what we use.
```
 parser: '@typescript-eslint/parser',
 parserOptions: { sourceType: 'module' },
 plugins: ['@typescript-eslint'],
```

**Comment by niko-achilles** [comment]
> ESLint is in the process of pushing people away from json configs because they lack the expressiveness and power most users require.

Do you have  about this ? 
 
If Eslint does that and knowing that they consider developer friendly tools  , then they will also provide something like `types` for typing support when the developer configures rules for eslint in an eslint file.

**Comment by niko-achilles** [comment]
> ESLint doesn't support JSON with comments, so you can't document your config.

And finally , because of JSON 
When i define a rule for ESLint, e.g. `no-console` in .eslint.json , i get the following info
``` 
ESLint rule

"off" - turns the rule off
"warn" - turn the rule on as a warning (doesn't affect exit code)
"error" - turn the rule on as an error (exit code is 1 when triggered)
```

Do you know where it comes from?
Do you like the documentation it provides ? 

It comes form JSON Schema, because Javascript without JSONM is like a `world` without `water`.

**Comment by bradzacher** [comment]
> Do you have a link about this ?

https://github.com/eslint/rfcs/blob/main/designs/2019-config-simplification/README.md#the-eslintconfigjs-file
The accepted RFC for the work they're doing on reworking eslint configs.

> The eslint.config.js file is a JavaScript file (there is no JSON or YAML equivalent) that exports an object

> Do you know where it comes from?

https://github.com/microsoft/vscode-eslint/blob/main/package.json#L476-L489
The `vscode-eslint` extension configures this in your IDE for you when you use a json config file.

> Do you like the documentation it provides ?

Not really TBH - it tells you nothing about the rule's actual config and the text about the strings is the same for *every* rule. For example - `no-console` has an optional object option, which you won't get any information about there.
