### ISSUE TITLE
Rule proposal: Warn when await keyword might be missing

### ISSUE THREAD

**Issue by mindplay-dk** [typescript-eslint/typescript-eslint#4553]
### Description

Add a rule that catches missing `await`, when the return-type of a function is a `Promise`.

This was previously [proposed](https://github.com/eslint/eslint/issues/13567) as an eslint feature, and [rejected](https://github.com/eslint/eslint/issues/13567#issuecomment-674338435) because:

> Without a type system, that’s just not possible in the most common case, which is when the other async function is in another file.

However, as noted in the original issue:

> Some of the meanest kinds of bugs we are running into are race conditions happening at runtime because of accidentally missing await statements.

There is some discussion in the original thread as to why TS itself doesn't type-check and help with this issue - as noted in the thread (before it was closed) the type-system does help when a return-value is assigned somewhere (to a variable or return-type declaration etc.) but I would add that it does not help when the return-type is `Promise<void>`.

(Just to give an example of unavoidable side-effects which may require `Promise<void>`: I am working on a Playwright project, and the Playwright API heavily uses `Promise<void>` to make sure you wait for side-effects you've requested by injecting things into the browser environment - this is just one example, I am sure there are many more, since e.g. DOM relies heavily on global state, side-effects and events.)

### Fail

An [example](https://github.com/eslint/eslint/issues/13567#issuecomment-674160061) was provided with the original eslint issue:

```ts
function sleep(seconds) {
  return new Promise((resolve) => setTimeout(resolve, seconds * 1000.0));
}

async function get1() {
  await sleep(1);
  return 1;
}

async function get2(input) {
  await sleep(1);
  return input;
}

async function main() {
  const result1 = await get1();
  const result2 = get2(result1); // 👈 missing await ❌
  console.log(`done: ${result2}`);
}

main();
```

### Pass

```ts
function sleep(seconds) {
  return new Promise((resolve) => setTimeout(resolve, seconds * 1000.0));
}

async function get1() {
  await sleep(1);
  return 1;
}

async function get2(input) {
  await sleep(1);
  return input;
}

async function main() {
  const result1 = await get1();
  const result2 = await get2(result1); // 👈 correctly awaited ✅
  console.log(`done: ${result2}`);
}

main();
```

**Comment by bradzacher** [comment]
The problem with pure JS is that you don't have a typed function boundary - so you can easily mess up invisibly.
But with TS the cases where you can mess up are much fewer because it checks things for you - making a single, global lint rule mostly unnecessary.

There is no one rule that handles this, there are a number which do handle this.

- `restrict-template-expressions`, as Josh mentioned, will handle this case as it enforces your template expression args are sanely typed.
- `no-floating-promises` will handle promises that aren't awaited at the top level.
- `no-misused-promises` will handle a lot of bad promise uses.
- `require-await` will make sure you're using await or returning a promise from an Async function.
- `promise-function-async` will make sure your functions are marked as async if they return a promise.

Josh is also right that you can't just warn on an unawaited promise anywhere because there's noting logically wrong with it. It's perfectly valid to assign and use later, or to pass to a function which in turn itself awaits.

**Comment by mindplay-dk** [comment]
I've been severely burned on a project using Playwright, where I forgot to `await` certain functions that return `Promise<void>` but have side-effects - this lead to race conditions, such that tests would pass locally, but would randomly fail on the CI server, just because those servers weren't quite as fast.

The problem was very difficult to identify and it's exactly the sort of thing I'd hope a linter would help with.

On this project, I would have rather the linter complained and made me manually ignore false positives - that way, I would be actively making the decision, avoiding the risk of forgetting an await that causes a race condition. The cost of doing that is far less than the time we spent trying to isolate and identify the issue - it's very, very difficult to isolate an error that only occurs 1 out of 5 times, and only a specific system that isn't set up for debugging.

Maybe this is not an inspection for everyone, and not an inspection for every project - projects aren't all the same, and that's why linters are configurable, right? It's definitely something that would help with Playwright projects, and probably others.

I looked through the list of inspections suggested by @bradzacher above - I don't see how these, or any combination of these, would help.

> It's not totally uncommon to generate a promise without immediately awaiting it, because you may want to `Promise.all` several promises later, for example. So I don't think requiring `await` everywhere is ever worthwhile.

I don't think we need to require await *everywhere* to get a useful inspection for this kind of issue.

---

*So ignore for a minute the example I cross-posted from the original eslint request.*

If I had to suggest the simplest possible inspection that would have caught this issue, I guess it would just need to check that you're doing *something* with a Promise. That is, if you create a Promise, or obtain one from a function call, the inspection would check that you're either **assigning** it to variable, **returning** it, **awaiting** it, or **passing it**.

So this would be invalid:

```ts
new Promise(resolve => { .... }); // ❌ no-unused-promise 
```

**Returning** a Promise would be valid:

```ts
function createPromise() {
  return new Promise(resolve => { .... }); // ✔ returned 
}

createPromise(); // ❌ no-unused-promise
```

This would be valid because it's **assigned** - but `no-unused-vars` would have you covered there:

```ts
function stuff() {
  const p = new Promise(resolve => { ... }); // ❌ no-unused-vars
}
```

This would be valid because it's **awaited**:

```ts
async function stuff() {
  await new Promise(resolve => { ... }); // ✔ awaited
}
```

And finally, **passing** the promise somewhere else would be valid:

```ts
usePromise(new Promise(resolve => { ... })); // ✔ passed
```

Again, if the call function doesn't do anything with that promise, `no-unused-vars` has you covered:

```ts
function usePromise(p) {} // ❌ no-unused-vars
```

As far as I can tell, no combination of existing inspections would have caught this issue - and `no-unused-promises` seems to nicely compliment `no-floating-promises` and `no-misused-promises`.

**Comment by bradzacher** [comment]
[Here is a playground that correctly shows both `no-floating-promise`, `no-misused-promises`, and `no-unused-vars` working together to highlight the problems you've been talking about](https://typescript-eslint.io/play/#ts=4.5.2&sourceType=module&code=PQKgUApgzgNglgOwC5gATtQIgAJIJ4AO0AxgE5wFIC008ywCA9lQGYyMCGSiA5lQaUYBbOFGiYAXKgDaAcgilBpWQF0ANGgw58RKGQrVaiJA2YioAVzEATfoPPipchUtUaMWXIRLlKNWMamVBYIVhC2AG4cpFCSMvKKjMoqYCDAYGAIEADuqAAK9qIQABTFAJSoALwAfKgA3qgAvmUA3KjAwKiAMuSoTKzsXLx2wkVQqBkQAB4ESUioLCHE3IwIqGQQXBAFI2Ll9ZqkEEgWpKtZudsOpRU19U2t7Z2AoOSoh8en4eONGeubl0XlNodbq9ZhsTjcBB8AQ7aATaazeaLZarKDHFgsACMezqmmIKzRqAIVV6OXyhV2e1uDWaQM6PT6ITCkWiUDA30gCNIcw4UDwCGISIFKNQaIsGIATDjNBxshw4HNzuTYdcqrUaQ9gS9ZfKkOF2fCZtyhUs4CtUGF-rsCFIrRAADwhADWTGyCGqFTqjUeIMZoRsVCiMQylopJSVdtV1PumueRN5NgynKNPL5ApNIo4MBg0o8+IQhIAJBwSb89ZHY6htVAoHAeFlrJp0PmiwAjUuHP5hwE+6u1+v6ptrAlzaQcNSoVsqEk6hXKhwAOizOekxYnhanlZeBATnyQjHnRSX2fKQ+BDOYTIDQbZHIycBYqGKZa23bKnu959BVHMzOGDjZbIAAs4BgCAnxfCsPx9C8f1EP8YQAsBn07cs31QAB+VAkFICxwKkFgszEStYN-ANENGZDIPQgAfGjsNwiASO-Mjwn-SjigAQmolV3zpX0zHg8iwzZMBrAgYgYGicCFmFM1Vg4YhiAgSgoAANUYOBrAAYQAIWfVspCpWoIk06xWjARTlNUjStL0lCNjQ2FmL6VjbAosRRKTbyfN8vzfOBABiQ4eHk1AeHYVssyJMNsO8MZ91QbIkidaJGBCaxsKA8CCCkvAeEEDLJwsHg2SmFN6kaFoMlAcBUBAVAACUVMOMRkAS7LhyEXKjjCxhHw4BS02IIDBCYKxUEYIhSEGFY0DSMBjAUQjlMPMR7QAFXVM8QDqjwGoAQSQJBFOysZiGXKLiCdMYWCSLLwNaxgYAsTMEGsYB7sOAArCSRX6h61ogBch3q1BsB3GahEmhAFhgFhQLAzKNs6i7syup1sIPKYJNe8DgIgVYkE6u1UFEV5oGeiJwhBjwwYh6IOGhlYfr+z4UfAtGYAxrHUBx4g8aS7KiZJ2LydZpYadBhrsDeE4C1QA6gfme7ic54Qev+x9gLgEa+ep0g1kuxTMfJ-m8esWn9vSDw1YQTbmssGAkExEkNonDbHYsZ2JRJLIDeqYoVjhhHs3CDCjOKKIXogKQNpuWpPegb2XdQei7QAGTgJ0HSTp2XY9NOLXeiAEYbIvQmzCcWYgX7JesCOn2KTsoBWKRBrwBPUDzlPffTsMs5zh3k59wv6Iy0vEE+ejK5gMpbTDYf89d+ie9H6qdr2jBDuO07oFQEsuZ5u7DZWGA8EBiWtcBu0re38HIaZmGr-Z1Hjeu3nzb1IXCZvsWxhfpbaW4M5anDGErUmJ9Ab4m6mBa+asjboxNnfdAC08xcBGkvFOfsIAByDggQBjdSgtzbgfBAnc1Tdy9s7Iumds652oUgMexdxJl2nr0b2c8F6wk2kXNeTDqrfCWqQFa4E7TaRHLhJY91cQeFqsApWhwWAKEJqtRKCCYT7h0MDaWNsMCdmsGfC+mjGDaO4Q4e0HdqgbzkbtYB2lUL7xLBGMMKD6aP2hl-e6Ssj4mwtDYXmiAFRwCzHAAAXuBDRrju4gXOu-U2Ywdw1j3MlA+pAeAWCEITJAUAJDAJLE9GA1NEHcz8cyXmhTilRNhElBUQED6oGjnhSahsEGtWwQDQapjsqGw8hAdw+0yGZQKbXP6JSeblMSlfQGfTanEwaTCCIWlPgkNWPdFwSQ3FoIwEqTagcvGkCMpU2OT4mknI2rQge9C9ld1MlpCcV8jkbFbggRuHdblmQ+VpeeQM9k2IwPIumDUHGOSccrYmXAyYAMpkUz42Q6lkLSTNC+AN2nOzGATBS2ZJqPmqUs8SmU7RsiBRTVusLq6G0AT-BS5Dlbi1GfXLZD9GbQzOeAhSigOAosfESplssjjy3AaSC4rjdFDmXLwqYep3rQo4IYhA59i4ukYG6aQ056JqsDmyuOPy7T2gaFQAxRiZB5DJqsHOeAAYbRUFIA6coFThE2tIPIKhaiNGsRkORnQxAnPgK2Bc0AJQAAZMQAFYFwOpmq2MCC5LY5LPJ0CVW0o5Zjwrk1AABJPUUawK8P7rCQeudqgenMUUJ1rr-noEBYMkFmwxgllJhCuY9KyXU0yl9BlepMqYrIdymZgh8WfCJWkx6MK23AI7XXLtfKPGNNTfvA6HLkU4qBlAPloCFZKxcbCLZej0AzWUpKyY0rrCyvlYq50roEBqqLpqlNMd03x1LetO1upHUbWkKEIQrYFCuo9Qm0UEBfVwH9YGkN4bI0cGjcDONxKAWdAPUW+9aapBZoUFB3NW1dWLwuVKwmp6gaFvtIgZRhsACqtQsJkdQHHf9tit6oNQLWvU9bhUUynZ8WZUC8XLMyqsmdLKKa8nNBzITLz+01LlNCjjQCSX8veJutjVLb5io8FfXhlRSR4NWW88h2GeFbUre0OxJLmNgqVMczKfT10CrAYrUlVNOOiqBXuhzsLyjPodHc6wdGAUmZrY41jFmx1OZqdxzqizeNzpjgJqG0XmlK2s8A+Tgr7OzOAowMQZrs0IGimiTYqAhAYLOhJwdVnnPWyHMcvZyHzmXILdcrDnm-kGnEpJaSw4CxzDtJ5iRXWpH7lIBvIK+GQphQiowKKMAYo1O0VAIAA&rules=N4XyA&tsConfig=N4XyA)

Again - there's no one rule, but there are an assortment of rules you can use to enforce better standards in your codebase.

---

> I would have rather the linter complained and made me manually ignore false positives

That's your perspective, and you're very much in the minority - for good reason.
False positives make people stop trusting lint rules. If every time you write a promise expression the linter warned on it - it won't make you more careful with them and consider whether or not you've properly used it.
Instead you'll frustrate people, and train them to just ignore and disable the rule without considering its errors.

This is me speaking from experience at Meta. We have all manner of bad, custom, internal lint rules - many of which false positive. People just ignore them and add disable-comments. It actually trains people to start to completely ignore *valid*, known good lint rules as well.

The same thing applies to type systems - false positive errors in the type system train people to ignore type system errors!

**Comment by JoshuaKGoldberg** [comment]
Since this issue has gone two months without activity and is asking for something that seems to already exists, closing for housekeeping. Please file a new issue if you have a case not covered by existing rules.

**Comment by mindplay-dk** [comment]
Sorry I didn't follow up - I left my job and didn't work on that project anymore.

From the description and playground example it looks like you have these features, and I just wasn't finding them. I'm pretty thorough about reading documentation before submitting an issue - unfortunately, it's no longer fresh in my memory, so I can't say if there was something that could be improved. Sorry for taking up your time and thanks for looking into this. 🙂
