### ISSUE TITLE
[prefer-const] is not disabled for export let

### ISSUE THREAD

**Issue by Weldify** [typescript-eslint/typescript-eslint#4573]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/prefer-const": "error"
  }
}
```

```TS
class Class {}

namespace Space {
	export let thing: typeof Class = Class;
    // ^ 'thing' is never reassigned. Use 'const' instead. eslint(prefer-const)
}
```

ESLint marks this as an error, even though it doesn't make sense to do that, since the rule cannot detect such usages across boundaries. ( as stated in issue #4572 )

I propose a change that disables the prefer-const rule completely when it is used on `export let`'s

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `vscode ESLint` | `2.2.2` |
| `vsocde`        | `1.64.2` |
| `ESLint`                           | `X8.9.0` |

**Comment by bradzacher** [comment]
Please don't re-file an issue after we close your issue.

The issue is still unlocked and free to discuss there.
