### ISSUE TITLE
Docs: scrolling bug on website

### ISSUE THREAD

**Issue by patcon** [typescript-eslint/typescript-eslint#4574]
### Suggested Changes

Currently, this is what happens when use Chrome (forgot screencap it happening in incognito mode without plugins, but confirmed still happens there):

## Chrome: with bug

[![screenshot of scrolling failing to work](http://g.recordit.co/3QoYSuAV4Z.gif)](https://recordit.co/3QoYSuAV4Z)

## Firefox: without bug

This is a screencast of the issue not manifesting on Firefox:

[![screencast of Firefox working fine](http://g.recordit.co/lntWk2Gh8z.gif)](https://recordit.co/lntWk2Gh8z)

I'm on OSX Big Sur 11.6 (20G165)

This bug goes away on Chrome when the viewport is narrow enough for mobile breakpoint

### Affected URL(s)

https://typescript-eslint.io/docs/linting/monorepo (and other menu item pages)

**Comment by bradzacher** [comment]
Thanks for the report!
It's very difficult to see what's happening from the gifs because they have a low framerate.
If possible - could you attach the raw video? Or failing that - upload it as an unlisted youtube video or similar?

I can't repro any weirdness myself - but I may not be reproing correctly.

**Comment by Josh-Cena** [comment]
Hi, it may be because of https://github.com/facebook/docusaurus/issues/6587. TL;DR: turn off experimental-web-platform-features on your chrome because it's buggy

**Comment by patcon** [comment]
Ah yeah, sorry, i didn't inspect those videos enough..! Here's a loom video of the glitchy, frozen scroll on Chrome :)
https://www.loom.com/share/70b4ec787f9a47898e46ad9b39e7cb77

**Comment by patcon** [comment]
Oh! Confirmed that it works fine with the flag disabled that was mentioned in https://github.com/facebook/docusaurus/issues/6587#issuecomment-1028065115

Thanks @Josh-Cena 🎉 

Will close this :)
