### ISSUE TITLE
Feature: consistent-return, default-case, no-undef: replacement or disable in config

### ISSUE THREAD

**Issue by ilyub** [typescript-eslint/typescript-eslint#4580]
The above ESLint core rules do not work correctly in typescript files.

For example, default-case reports false positive when switch is actually exaustive.

Is it possible to disable them in typescript-eslint/recommended and typescript-eslint/all configs
OR
Write a replacement for these rules?

Let me know if you need further explanation or examples.

**Comment by bradzacher** [comment]
`no-undef` is in the core ESLint recommended set, and is disabled in our recommended config.

https://github.com/typescript-eslint/typescript-eslint/blob/e7857aa2975412b43c62cd9c55e9f16d09f6a8aa/packages/eslint-plugin/src/configs/eslint-recommended.ts#L24

However the rule will work fine for most cases. It just won't know about 3rd party global types and variables you use without extra config.

---

The other two (consistent return and default-case) are NOT in the core ESLint recommended set, so we will not be disabling them in our recommended config.

The latter rule is mostly extended into the type-aware rule [switch-exhaustiveness-check](https://typescript-eslint.io/rules/switch-exhaustiveness-check).
