### ISSUE TITLE
Warning after update to TypeScript@4.6.2

### ISSUE THREAD

**Issue by cojoclaudiu** [typescript-eslint/typescript-eslint#4614]
This warning is after updating TypeScript to version 4.6.2

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.6.0

YOUR TYPESCRIPT VERSION: 4.6.2

Please only submit bug reports when using the officially supported version.

=============

**Comment by Josh-Cena** [comment]
Tracked in #4471
