### ISSUE TITLE
[feature request] ignore return type for anonymous function

### ISSUE THREAD

**Issue by jcyuan** [typescript-eslint/typescript-eslint#466]
is it possible to have option for this rule?

    @typescript-eslint/explicit-function-return-type

for example, only disable for anonymous functions:

    onStart: str => {
                this._chr1.setVisible(true);
                this._chr1.play(str);
            },

**Comment by jcyuan** [comment]
sorry did not read the doc carefully, just found it.

**Comment by markmsmith** [comment]
For anyone else looking for this, you want `allowExpressions: true`.  I kept looking past it because I was looking for words like `arrow function` or `anonymous function`
