### ISSUE TITLE
Use --changedSince for Jest tests in CI

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#4660]
## Overview

Even with SWC replacing Babel (#4583), unit tests on `eslint-plugin` take several minutes to run. [This example](https://github.com/typescript-eslint/typescript-eslint/runs/5485214823?check_suite_focus=true) took 6m 45s.

It'd be nice if we could use something like [Jest's `--changedSince`](https://jestjs.io/docs/cli#--changedsince) against the target branch in a PR to cut down on the number of unnecessary tests run.

Note that this will need to work with Codecov for our test coverage checks.

**Comment by JoshuaKGoldberg** [comment]
Removing my assignment because I couldn't get #4611 to work in a short amount of time 😄. This isn't high on my todo list and I likely won't work on it soon. Someone else is more than welcome to!

Note that our test files can sometimes import from unexpected places. For example, [`docs.test.ts`](https://github.com/typescript-eslint/typescript-eslint/blob/c9500519f25738ce2dc4b8b8b6c43fea5f15433a/packages/eslint-plugin/tests/docs.test.ts) uses `fs.readFileSync` to read in Markdown files.

**Comment by bradzacher** [comment]
One other thing to be careful about here is that I don't believe that jest will detect the inter-package dependencies.

Which means that a change to the parser wouldn't cause all plugin tests to run, even though the change impacts them.

**Comment by JoshuaKGoldberg** [comment]
In the two years since this was filed, we've had a bunch of great Nx caching work done. Also we're interested in moving to Vitest (#7112). Closing out as non-actionable.
