### ISSUE TITLE
explicit type for argument.

### ISSUE THREAD

**Issue by jcyuan** [typescript-eslint/typescript-eslint#468]
`@typescript-eslint/no-explicit-any` seems only works for the variable definitions, but not work on arguments:

![image](https://user-images.githubusercontent.com/850854/56730796-638fe300-678b-11e9-83a5-b657dbfc16de.png)
works for the 's'

but not work for the argument of the next method:
![image](https://user-images.githubusercontent.com/850854/56730871-94701800-678b-11e9-84ad-4bc9a12471f6.png)

**Comment by jcyuan** [comment]
tested again it seems that if a variable does not have a type, the rule won't check for it.

![image](https://user-images.githubusercontent.com/850854/56730937-ca150100-678b-11e9-885d-4f8313c3b387.png)

**Comment by ThomasdenH** [comment]
`no-explicit-any` only checks for explicit declarations with type `any`. tslint has the rule `no-unsafe-any` which checks the safety of `any`, explicit or not.

**Comment by jcyuan** [comment]
@ThomasdenH thanks, but don't know why `no-unsafe-any` still not work for these arguments...

**Comment by bradzacher** [comment]
The linter does not catch missing `any`s, because the compiler has an option to do this:
https://www.typescriptlang.org/docs/handbook/compiler-options.html

> `noImplicitAny` - Raise error on expressions and declarations with an implied any type.

**Comment by jcyuan** [comment]
@bradzacher got it! thanks so much!
