### ISSUE TITLE
[lines-between-class-members] Option to ignore spacing around property getter/setters

### ISSUE THREAD

**Issue by coyoteecd** [typescript-eslint/typescript-eslint#4681]
I would like to be able to configure the `lines-between-class-members` rule to ignore spacing between consecutive get/set accessors, even if their bodies are multi-line. I found a few cases in our codebase that trigger lint errors, formatted as in the repro example.

I've considered putting get/set on a single line. This works when the body is really short (as in the example), but we have setters in our Angular component code that do more than just assignment (this is after all, the reason we've used a setter). And introducing newlines just to keep the rule happy feels like throwing away the logical grouping.

Thoughts?

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/lines-between-class-members": ["error", "always", { "exceptAfterSingleLine": true }]
  }
}
```

```TS
class MyComponent {
  public field: number;
  
  private _otherField: string;
  public get otherField() { 
    return this._otherField;
  }
  public set otherField(value: string) { 
    this._otherField = value;
  }
  
  public method1() {
    // implementation
  }
  
  public method1() {
    // implementation
  }
}
```

**Expected Result**

No lint error.

**Actual Result**

I get "Expected blank line between class members" for the line containing the setter.

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.13.0` |
| `@typescript-eslint/parser`        | `5.13.0` |
| `TypeScript`                       | `4.5.5` |
| `ESLint`                           | `8.10.0` |
| `node`                             | `14.18` |

**Comment by bradzacher** [comment]
With stylistic rules we mirror the config of the core eslint rule so that we are directly compatible. We do not add additional options unless required to support TS syntax.

All stylistic rules are frozen in eslint core and new options will not be accepted. Thus we will be rejecting this proposal.

Thanks for the request.

**Comment by coyoteecd** [comment]
@bradzacher thanks for the reply, I understand. Does this mean that one possible route is to direct this request to the base rule in the ESLint repo instead?
