### ISSUE TITLE
[rulename] issue title

### ISSUE THREAD

**Issue by ftlPhysicsGuy** [typescript-eslint/typescript-eslint#4687]
- [X ] I have tried restarting my IDE and the issue persists.
- [X ] I have updated to the latest version of the packages.
- [X ] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**

```JSON
{
    "env": {
        "browser": true,
        "es6": true
    },
    "parser": "@typescript-eslint/parser",
    "plugins": [
        "@typescript-eslint"
    ],
    "parserOptions": {
        "project": ["./src/tsconfig.json", "./src/common/tsconfig.json", "./src/server/tsconfig.json"],
        "sourceType": "module"
    },
    "overrides": [
        {
            "files": ["*.ts"],
            "extends": [
                "plugin:@typescript-eslint/recommended",
                "plugin:@typescript-eslint/recommended-requiring-type-checking"
            ]
        }
    ]
}
```

```TS
// your repro code case
// NOTE: the problem occurs when code is shared across TypeScript projects
// See attachment below for working example
```

I have created a small project that seems to demonstrate the issue:

[ESLintTest.zip](https://github.com/typescript-eslint/typescript-eslint/files/8249729/ESLintTest.zip)

Please see the detailed readme for step-by-step instructions to recreate the error.  The structure of the project is as follows:

```
src/
    common/
        index.ts
        TestState.ts  --> Defines a simple, self-contained "TestState" class
        tsconfig.json
    server/
        DummyServer.ts. --> Creates an instance of the TestState from the "common" project
        index.ts
        tsconfig.json. --> Includes a proper reference to ../common (the code transpiles and run without issues)
    tsconfig.json
tsconfig.json
```

**Expected Result**

When running ESLint on the DummyServer.ts file (`./node_modules/.bin/eslint src/server/DummyServer.ts`), it should use the reference to `../common` in the tsconfig.json file and recognize the `TestState` class as a valid type.  It should therefore not report any errors. 

**Actual Result**

When running ESLint on the DummyServer.ts file (`./node_modules/.bin/eslint src/server/DummyServer.ts`), it  reports 4 errors:
```
   8:9   error  Unsafe assignment of an `any` value                  @typescript-eslint/no-unsafe-assignment
   8:26  error  Unsafe construction of an any type value             @typescript-eslint/no-unsafe-call
  16:32  error  Invalid type "any" of template literal expression    @typescript-eslint/restrict-template-expressions
  16:32  error  Unsafe member access .stateLength on an `any` value  @typescript-eslint/no-unsafe-member-access
```
Each error is related to a reference to the `TestState` class (or an instance of that class) from the `../common` project.

**Additional Info**

ESLint did not throw any exceptions.  TypeScript recognizes the references from the server to the common project and the code tanspiles and runs without error.  ESLint appears to be ignoring the cross-project references defined in tsconfig.json

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.15.0` |
| `@typescript-eslint/parser`        | `5.15.0` |
| `TypeScript`                       | `4.6.2` |
| `ESLint`                           | `8.11.0` |
| `node`                             | `10.7.0` |

**Comment by bradzacher** [comment]
This is working as expected.
When we resolve the tsconfig for `server/DummyServer.ts`, we use `server/tsconfig.json`.

This tsconfig lists `"include": ["./*.ts"]` - so it only includes the ts files `server/*.ts`. This does not include `common/*.ts`. This means that `common/index.ts` (imported from `server/index.ts`) is not included in the project.

TS will attempt to reference the **compiled output** of the files (their output `.d.ts` files). But without a build - it won't find anything.

You can test this by attempting to build the project `server/tsconfig.json` you will see the errors:
```
% npx tsc --noEmit -p src/server/tsconfig.json
src/server/DummyServer.ts:1:10 - error TS2305: Module '"./index"' has no exported member 'TestState'.

1 import { TestState } from "./index";
           ~~~~~~~~~

src/server/index.ts:1:15 - error TS6305: Output file '/ESLintTest/build/common/index.d.ts' has not been built from source file '/common/index.ts'.

1 export * from "../common/index";
                ~~~~~~~~~~~~~~~~~
```

If you run the lint with debug logging, you'll also see errors which correlate 
```
% DEBUG=typescript-eslint:* npm run lint

...
  typescript-eslint:typescript-estree:createProjectProgram Creating project program for: /ESLintTest/src/server/DummyServer.ts +5ms
  typescript-eslint:typescript-estree:createWatchProgram Creating watch program for /eslinttest/src/server/tsconfig.json. +0ms
  typescript-eslint:typescript-estree:createWatchProgram Found program for file. /eslinttest/src/server/dummyserver.ts +278ms
  typescript-eslint:eslint-plugin:utils:types Found an "error" any type +0ms
  typescript-eslint:eslint-plugin:utils:types Found an "error" any type +0ms
  typescript-eslint:eslint-plugin:utils:types Found an "error" any type +0ms
  typescript-eslint:eslint-plugin:utils:types Found an "error" any type +5ms
...
```

Specifically the "found an "error" any type" logs - which point out that our lint rules found an `any` that was also marked using TS's internal `error` properties.

If you *build* the project `common/tsconfig.json` then TS will be able to reference things correctly and the lint will succeed:
```
% npx tsc -p src/common/tsconfig.json
% npm run lint                        

> eslinttest@1.0.0 lint
> eslint . --ext .ts
```

If you can get the build on `serer/tsconfig.json` passing, then the lint will pass as well.

**Comment by ftlPhysicsGuy** [comment]
@bradzacher Thank you for the response.

I have two followup points/questions, if you will:

First, the server/tsconfig.json file includes a `references` section that defines the path `"../common"`:
```
"references": [
    { "path": "../common" }
],
```
 So, try running tcs with the `-build` option:
```
npx tsc -build src/server
```
Because it uses the `references` section in the tsconfig.json file to find all referenced projects, it successfully compiles both projects as needed and does not complain.

Is there a way to get ESLint to use the `references` in the tsconfig.json file so it will follow the same rules and properly find all referenced code?


Second, I use ESLint via a plugin for VSCode.  In VSCode, my project is setup to use the build option, and so it compiles properly and VSCode does not complain about the types cross-referenced between one project (e.g., common) and another (e.g., server or client).  Apparently VSCode is properly following the defined references.  However, because ESLint does not follow the `references` info, any time I make a change in one project and reference it in another, ESLint complains about the `no-unsafe-[whatever]` errors (until I compile the code AND restart VSCode).  It makes those rules largely unusable for my multi-project setup.  The forum for microsoft/vscode-eslint pointed out that this was a typescript-eslint issue, so here I am...

So, is there a way to prevent these errors (related to cross-referenced projects) from complaining in an IDE like VSCode?


With that said, I still make the following argument:

Because tsc has implemented the `references` section in tsconfig.json, and since tsc WILL properly find the cross-project references when using `tsc -build`, ESLint should also respect the `references` section of tsconfig.json and file all referenced code when run against the `server` project.

**Comment by bradzacher** [comment]
We don't support project references - #2094

**Comment by ftlPhysicsGuy** [comment]
Roger that.  Thanks for the reference (no pun intended -- okay, maybe a little pun was intended)
