### ISSUE TITLE
Rule proposal: explicit-member-accessibility handle decorators.

### ISSUE THREAD

**Issue by infacto** [typescript-eslint/typescript-eslint#4719]
### Description

Is it possible to handle decorators for [explicit-member-accessibility](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/explicit-member-accessibility.md)? 

Example in Angular: 

```ts
@Component({selector: 'app-test'}) 
export class TestComponent {
  // No accessibility modifer required. Handle it as public (default). No error here.
  @Input() value: number;

  // Currently I have also set modifier here. But an Angular Input is alsways "public" (writeable).
  @Input() public value: number;
}
```

Something like an ignore pattern. If member has a decorator with name x, then ignore the rule.

Otherwise this is a suggestion. What do you think? Is it possible to handle decorators with eslint?

**Comment by bradzacher** [comment]
Thanks for the issue!
I don't quite understand - why does a decorator mean you don't need an accessibility modifier?

**Comment by infacto** [comment]
In general a decorator has nothing to do with an accessibility modifier. It's just a subjective case. I see Angular `@Input` as public API. On runtime, an input decorator property is always accessable from outside (indirectly through the decorator). In this case I would always write `public`. It's a bit annoying and ugly. That's really just subjective. Therefore I would add a pattern to ignore the rule when the property has a decorator with name `@Input`, etc. For me `@Input()` == `public`. It's just like `ignoredMethodNames` option. Just a quick web search - I found something about decorators in eslint: [eslint-plugin-decorator-position](https://github.com/NullVoxPopuli/eslint-plugin-decorator-position). So it's seems that it's possible in eslint to handle decorators. It's just an idea. What do you think? Why not? But I'm fine with every decision. Otherwise we could just add an option like `ignoredDecoratorNames` which checks if `@${name}` decorator does exist on method.

**Comment by bradzacher** [comment]
I understand! Your usecase does make sense!
However I think that the applicability is very, very narrow - I don't think many people would use the option. Outside angular decorator usage is reasonably low - so I don't think that it makes sense for us to build this into our general-purpose plugin.

If you're interested you're free to build on top of our rules by forking them to add the option!

**Comment by alex-lighthouse** [comment]
As an added use case, decorators are also often used with NestJS, especially when building a GraphQL API.
