### ISSUE TITLE
Missing visitor keys

### ISSUE THREAD

**Issue by DMartens** [typescript-eslint/typescript-eslint#4724]
I'm sorry for not using any template but none apply.
After filing #4705 I investigated and the reason for the missing parent property is that there missing [visitor keys](https://github.com/typescript-eslint/typescript-eslint/blob/6c3816b3831e6e683c1a7842196b34248803d69b/packages/visitor-keys/src/visitor-keys.ts#L104) (in the issues case `implements` for TSInterfaceDeclaration).
As such ESLint does not traverse the child nodes and therefore does not add the parent property.

I built the ast spec and compared the "enhanced" and TypeScript-only node types and found more missing keys.
The missing keys are:
MethodDefinition: `typeParameters`
TSInterfaceDeclaration: `implements`
TSNamedTupleMember: `label`
TSEnumDeclaration: `modifiers`
TSModuleDeclaration: `modifiers`

**Versions**
| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `5.16.0` |

**Comment by JoshuaKGoldberg** [comment]
> TSInterfaceDeclaration: `implements`

Is this correct? I see in the typescript-eslint/parser AST that `interface A implements B {}` seems to be valid, but that shouldn't be valid in TypeScript code.

**Comment by DMartens** [comment]
The original issue originated from my eslint rule failing for [this TypeScript compiler test case](https://github.com/microsoft/TypeScript/blob/HEAD/tests/cases/compiler/interfaceWithImplements1.ts).
So I thought it is valid TypeScript.
