### ISSUE TITLE
Fix optionals in ParseForESLintResult interface parameters

### ISSUE THREAD

**Issue by gilite** [typescript-eslint/typescript-eslint#4728]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Expected Result**

The [ESLint - Working with Custom Parsers doc](https://eslint.org/docs/developer-guide/working-with-custom-parsers) states:

> The parseForESLint method should return an object that contains the required property ast and *optional properties* services, scopeManager, and visitorKeys.

The `ParseForESLintResult` interface should use optionals on the above 3 properties (i.e. `services`, `scopeManager`, and `visitorKeys`) as they each default to their respective objects.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `5.16.0` |
| `TypeScript`                | `4.6.3` |
| `ESLint`                    | `8.11.0` |
| `node`                      | `14.18.0` |

**Comment by gilite** [comment]
Submitted a PR, but I'm not sure if modifying the `ParseForESLintResult` interface is the right practice. My use case is that I am importing this interface to make a custom parser, but I want the non-`ast` properties to default to their original values as marked in the docs.

**Comment by JoshuaKGoldberg** [comment]
Thanks for filing this @gilite, glad to see usage of the parser APIs!

I don't think modifying the `ParseForESLintResult` interface is the right place, no. ESLint describing the properties as optional refers to their code not needing the parser to return them. But if a particular parser knows its returned object will always include them, it makes sense for the parser to indicate so in its typings. It'd be inconvenient for consumers if the parser added `| undefined` to some object members known to always exist.

If you can post more details, such as a link to your custom parser code, we can probably advise a bit on it. 

Side note: very exciting that this is your first ever OSS PR! ✨

**Comment by JoshuaKGoldberg** [comment]
No worries, thanks for the followup!
