### ISSUE TITLE
[plugin:@typescript-eslint/recommended] Semver violation

### ISSUE THREAD

**Issue by mysticatea** [typescript-eslint/typescript-eslint#473]
As I mentioned in https://github.com/typescript-eslint/typescript-eslint/pull/354#issuecomment-473785205, adding new rules to the recommended config is a breaking change that needs major version up.

But v1.7.0 seemed to add new rules to the recommended config.

Please revert the change of the recommended config and make a patch release.

**Comment by bradzacher** [comment]
It shouldn't have.
https://github.com/typescript-eslint/typescript-eslint/commits/master/packages/eslint-plugin/src/configs/recommended.json

The file hasn't been changed in over 2 months.

I just did a clean install of 1.7.0 and the recommended.json is exactly the same as what is in master right now.

Could you please compare your recommended.json vs master and let me know if you're seeing something different?

**Comment by mysticatea** [comment]
Oh, I apologize.
I had not confirmed code enough after I had seen some tweets.
