### ISSUE TITLE
[consistent-indexed-object-style] fixer produces invalid code and deletes comments

### ISSUE THREAD

**Issue by Josh-Cena** [typescript-eslint/typescript-eslint#4730]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**

[Playground](https://typescript-eslint.io/play#ts=5.3.2&fileType=.tsx&code=C4TwDgpgBAcghgNwEZwE4ElgQLYGcoC8UAShAMYD2qAJgDwBQUUuwqAlgHYDmANI1AHoBUStmwQOwfi3bd6APgDc9eqEixEKDFjyES5KnX4BRAB5kANgFdqEWgCI49qAB8o9pM7f2y9nu6d5PiYZTi5%2BJXogA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6MgeyeUuX0Ra1mAE0QAPRMNocARgCtEZOn0JJ0YANrhsORNGgdokADTadkEeNo8A5kwCG%2BWNESQzYALraAviG9A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

```JSON
{
  "rules": {
    "@typescript-eslint/consistent-indexed-object-style": ["error", "index-signature"]
  }
}
```

```TS
type NavbarItems = Record<
  string,
  // lazy-load the component
  () => (props: any) => JSX.Element
>;

type NavbarItems = Record<
  Exclude<"a" | "b" | "c", "a">,
  string
>;
```

**Expected Result**

I expect the first to be fixed with comment preserved, and the second to be fixed to valid code:

```TS
// lazy-load the component
type NavbarItems = { [key: string]: () => (props: any) => JSX.Element };

type NavbarItems = { [key in Exclude<"a" | "b" | "c", "a">]: string };
```

**Actual Result**

```ts
// This has the comment swallowed
type NavbarItems = { [key: string]: () => (props: any) => JSX.Element };

// This should use mapped type instead of index signature
type NavbarItems = { [key: Exclude<"a" | "b" | "c", "a">]: string };
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.16.0` |
| `@typescript-eslint/parser`        | `5.16.0` |
| `TypeScript`                       | `4.6.3` |
| `ESLint`                           | `8.11.0` |
| `node`                             | `17.5.0` |

**Comment by Josh-Cena** [comment]
It is virtually impossible to determine whether mapped types or index signatures should be used if there are type aliases without making the rule type-aware. Maybe we should just use suggestions instead?

**Comment by bradzacher** [comment]
We can certainly switch to suggestions if we can't reliably determine which should be used!
happy to accept a PR to make this one change

**Comment by Josh-Cena** [comment]
I realized mapped types are more permissive than index access types. Mapped types also allow `{ [key in string]: number }`. Is it possible that we only fix to index signature for `TS{String,Number,Symbol}Keyword`, and fix to mapped types for everything else, without getting rid of the fixer?

**Comment by bradzacher** [comment]
we could definitely do that.
maybe we should do:
1) use an autofixer if the keyword is `string | number | symbol`
2) use a suggestion fixer in other cases
