### ISSUE TITLE
Docs: surface deprecated and replacedBy in docs

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#4736]
### Suggested Changes

Pages like https://typescript-eslint.io/rules/no-implicit-any-catch don't include any indication that the rule is deprecated. I'd like to change the `recommended` property to a string and surface that as a callout on the top of the rules' page.

### Affected URL(s)

https://typescript-eslint.io/rules/camelcase
https://typescript-eslint.io/rules/no-implicit-any-catch

**Comment by bradzacher** [comment]
There should be a `replacedBy` property that can be used.
This will also dump as part of eslint's output

https://eslint.org/docs/developer-guide/working-with-rules#rule-basics

**Comment by JoshuaKGoldberg** [comment]
The site now shows these as deprecated. We're good.
