### ISSUE TITLE
Rule proposal: type-only

### ISSUE THREAD

**Issue by HomyeeKing** [typescript-eslint/typescript-eslint#4775]
### Description

sometimes, we may declare in specific file like `types.ts` or `type.d.ts`, so user can config these _type file_ in rule, the rule  will autofix it into type-import format

basic usage:

```ts
// types.ts

export interface Foo{
  bar: any

}

```

```
// .eslintrc.json

// ...

rules:{
 @typescript-eslint/type-only: ["error", {
  typeImporter: "types$" // using regexp to match the potential type file
}]
}
// ...
```

> there's a rule called [consistent-type-imports](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md), maybe we can extend it 

### Fail

```ts
import {Foo} from './types'
```

### Pass

```ts
import type {Foo} from './types'
```

**Comment by bradzacher** [comment]
Sorry I don't understand.
What do you want the rule to do?
From your description and example it just looks like you want the `consistent-type-imports` rule.

**Comment by HomyeeKing** [comment]
@bradzacher  it's useful when user create type file(only/most contains types) like `types.ts`, 'types.d.ts' ... 
 specify the importer regexp to intercept the import of these type files, report error if not using `import type` and it's fixable

do you think it's too much individual  and not universal enough?

**Comment by bradzacher** [comment]
Definitely too specific of a usecase.

Most people don't use `.d.ts` files for "type only" files because it has a lot of weird rules around it.

You can use `consistent-type-imports` to enforce that all type imports are properly marked as type-only, which should satisfy your usecase fully.
