### ISSUE TITLE
Question about lodash 4.0.1 vulnerability 

### ISSUE THREAD

**Issue by dclaverty** [typescript-eslint/typescript-eslint#480]
Question:
typescript-estree@1.6.0 is using a lodash module with known vulnerabilities. Is it the fact that it is only using the .unescape module from 4.0.1 that there is no concern ? 

└─┬ @typescript-eslint/typescript-estree@1.6.0
└── lodash.unescape@4.0.1

**Comment by bradzacher** [comment]
Looking at the vuln (https://snyk.io/test/npm/lodash/4.0.1)

> The functions merge, mergeWith, and defaultsDeep could be tricked into adding or modifying properties of Object.prototype

We don't use any of those functions, so I don't think it's an issue.

Additionally:
- we aren't even a build tool, so there isn't a runtime vuln for your application.
- the surface for which we use the unescape function is so tiny (unescaping literal strings during parsing), that it isn't an attack vector, even when thinking about eslint's `--fix` mode..
