### ISSUE TITLE
Docs: scroll behavior

### ISSUE THREAD

**Issue by mindplay-dk** [typescript-eslint/typescript-eslint#4840]
### Suggested Changes

I noticed some weird scroll behavior on the documentation site.

On some pages, I can't seem to scroll properly at all - here I'm trying to use the mouse wheel to scroll down, and it just keeps jumping back up. I can't get to the bottom of the page at all:

![weird-scroll](https://user-images.githubusercontent.com/103348/163945123-66807032-7697-4a04-ba63-4e2af6346c73.gif)

The scroll behavior also appears to interfere with the browser's search (CTRL+F) feature - here I'm trying to search for the word "promise", and you can see the search popup indicating some number of results, but the scroll behavior on the page seems to change the offset so you can't actually see the results that are being highlighted on the page:

![weird-search](https://user-images.githubusercontent.com/103348/163945236-8a9a3aa4-5d40-43d5-97ea-c2b9bd9326cb.gif)

I've seen #4574 and I'm not sure if this is related? I don't have any experimental features enabled - I'm running a fairly clean Chrome 100. Could it be the experimental feature mentioned in that issue is now permanently enabled in stable Chrome?

### Affected URL(s)

Probably all documentation pages?

**Comment by Josh-Cena** [comment]
Hi, this is a bug with Docusaurus (https://github.com/typescript-eslint/typescript-eslint/issues/4574) and is supposed to be fixed by https://github.com/typescript-eslint/typescript-eslint/pull/4692. It hasn't been reviewed yet, though
