### ISSUE TITLE
Docs: no-throw-literal should document the requirement for the "parserOptions.project" property

### ISSUE THREAD

**Issue by mozeryansky** [typescript-eslint/typescript-eslint#4847]
### Suggested Changes

Using "@typescript-eslint/no-throw-literal" will cause linting to fail unless additional configuration is done. This requirement should be documented. https://github.com/typescript-eslint/typescript-eslint/issues/4846

### Affected URL(s)

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-throw-literal.md

**Comment by Josh-Cena** [comment]
This rule has already been marked as "Requires type information", which means you are expected to go through the steps to configure type-aware linting properly. There's nothing special about this rule itself.

**Comment by JoshuaKGoldberg** [comment]
For anyone who sees this later: https://typescript-eslint.io/docs/linting/type-linting
