### ISSUE TITLE
[member-ordering] Take in natural and requiredFirst sort options from eslint-plugin-typescript-sort-keys

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#4872]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

There's no way in the built-in `@typescript-eslint/member-ordering` rule...

```JSON
{
  "rules": {
    "@typescript-eslint/member-ordering": "error"
  }
}
```

...to use the `natural` or `requiredFirst` options from https://github.com/infctr/eslint-plugin-typescript-sort-keys.

```TS
/* eslint typescript-sort-keys/interface: ["error", "asc", { natural: true }] */

interface U {
  1: T
  10: T
  2: T
}
```

```ts
/* eslint typescript-sort-keys/interface: ["error", "asc", { requiredFirst: true }] */

interface U {
  a: T
  d: T
  b?: T
  c?: T
}
```

**Expected Result**

https://github.com/infctr/eslint-plugin-typescript-sort-keys has two major sorting options that don't yet exist in typescript-eslint core. From https://github.com/infctr/eslint-plugin-typescript-sort-keys/blob/master/docs/rules/interface.md:

> * `natural` - if `true`, enforce properties to be in natural order. Default is `false`. Natural Order compares strings containing combination of letters and numbers in the way a human being would sort. It basically sorts numerically, instead of sorting alphabetically. So the number 10 comes after the number 3 in Natural Sorting.
> * `requiredFirst` - if `true`, enforce optional properties to come after required ones.

**Actual Result**

Per https://github.com/infctr/eslint-plugin-typescript-sort-keys/issues/50, those features don't exist in typescript-eslint core yet.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.21.0` |
| `@typescript-eslint/parser`        | `5.21.0` |
| `TypeScript`                       | N/A |
| `ESLint`                           | N/A |
| `node`                             | N/A |

**Comment by glen-84** [comment]
@JoshuaKGoldberg Should this be closed now?

**Comment by JoshuaKGoldberg** [comment]
Ah, you're right - thanks for the spot!

* https://github.com/typescript-eslint/typescript-eslint/pull/5965
* https://github.com/typescript-eslint/typescript-eslint/pull/5662
