### ISSUE TITLE
Docs: How to test PR changes to rules

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#4875]
I am doing a PR for a new linter rule.
I would like to test this new linter rule on an existing repository, but it is unclear how to do that.
Normally, I would use `npm link` for this purpose, but that doesn't seem to be working properly, presumably because this is a monorepo.

Please enumerate the steps for testing a PR in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md).

**Comment by JoshuaKGoldberg** [comment]
Great idea!

**Comment by JoshuaKGoldberg** [comment]
We filled out much of how to link locally https://typescript-eslint.io/contributing/local-development/local-linking. Once a project is linked with the steps there, what's next would be enabling the relevant lint rule in the project's ESLint config file and running the project's lint command.

Does that make sense as a starting direction?

**Comment by JoshuaKGoldberg** [comment]
Yeah I think having a section in that same page about testing rules would be great!
