### ISSUE TITLE
[semi] Definition for rule '@typescript-eslint/semi' was not found  @typescript-eslint/semi

### ISSUE THREAD

**Issue by jaybekster** [typescript-eslint/typescript-eslint#489]
Hello!
When I run eslint with command `eslint . --ext .ts` I got an error for each file of linting: `1:1  error  Definition for rule '@typescript-eslint/semi' was not found  @typescript-eslint/semi`
.eslintrc.json config:

```
{
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json",
    "sourceType": "module"
  },
  "plugins": [
    "@typescript-eslint"
  ],
  "rules": {
    "semi": "off",
    "@typescript-eslint/semi": "error",
    "@typescript-eslint/await-thenable": "error",
    "@typescript-eslint/no-extraneous-class": "error",
    "@typescript-eslint/no-misused-new": "error"
  }
}
```

Trying to solve this problem, I figured out that there was no file by path: `node_modules/@typescript-eslint/eslint-plugin/dist/rules/semi.js`

Are there any ways to solve it?

**Comment by bradzacher** [comment]
Please use the canary tag on npm.
The rule hasn't been release to main yet.
