### ISSUE TITLE
Disallow implicit boolean casting of strings and numbers

### ISSUE THREAD

**Issue by novemberborn** [typescript-eslint/typescript-eslint#49]
It'd be great to have a lint rule that disallows (possible) strings and numbers from being implicitly converted to booleans:

```ts
const str: string | null = ''
if (str) {
  // ignores the empty string, the programmer likely attempted to guard against null
}

const num: number | undefined = 0
if (!num) {
  // ignores the 0 value, but the programmer likely attempted to guard against undefined
}
```

Besides `if` statements this would apply to ternary statements as well as `&&`, `||` and `!` operators.

For the above examples passing code could be:

```ts
const str: string | null = ''
if (typeof str === 'string') {
  // …
}
if (str !== null) {
  // …
}

const num: number | undefined = 0
if (typeof num !== 'undefined') {
  // ...
}
```

I can see a stricter version of this rule which enforces explicit conversions even if a value can only be a string or number.

**Comment by SpainTrain** [comment]
As a temporary workaround, one can use `@typescript-eslint/eslint-plugin-tslint` with tslint rule `strict-boolean-expressions` (https://github.com/palantir/tslint/blob/master/src/rules/strictBooleanExpressionsRule.ts).  

I miss this feature from Flow and would love to see this as a rule.  Chatter I saw on the TypeScript tracker indicated it is unlikely to be added to the compiler.

**Comment by novemberborn** [comment]
`strict-boolean-expressions` is now available: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md
