### ISSUE TITLE
[prefer-nullish-coalescing] request for preferring "||" when string value

### ISSUE THREAD

**Issue by NateRadebaugh** [typescript-eslint/typescript-eslint#4906]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**

In cases with strings, we may want to prefer that empty string `""` is equivalent to nullish, and show a fallback in that case. There currently is no option to support customizing string behavior.
* https://typescript-eslint.io/rules/prefer-nullish-coalescing#options

Example:
```ts
let emailAddress: string | null = getEmailAddress();
const link = "<a href='/'>" + (emailAddress || "---") + "</a>";
```

At a minimum, it'd be good to have a `ignoreStrings` option.

**Comment by mrmckeb** [comment]
We've hit this issue today, where we want to default empty strings:
```jsx
<>Hello {name || username || 'friend'}</>
```

**Comment by barroudjo** [comment]
Same thing here. it would be nice to have that `ignoreStrings` option. Can I attempt to open a PR for this, or is it a non-starter ?

**Comment by bradzacher** [comment]
I'd be happy with a separate option for each of the primitives - `string`, `boolean` and `number`.
That way people can configure which cases they want to ignore.

**Comment by mbrowne** [comment]
I'm currently trying to get this rule to work, but for me it's not throwing any error for this example:

```js
let emailAddress: string | null = getEmailAddress();
const link = "<a href='/'>" + (emailAddress || "---") + "</a>";
```

And it doesn't throw an error for this either:

```js
let foo: object | null = null
const link = "<a href='/'>" + (foo || "---") + "</a>";
```

I would think the goal would be to throw an error in the second case but not the first, right?

**Comment by mbrowne** [comment]
Actually I just upgraded to the latest version of `@typescript-eslint/eslint-plugin` and now I get an error for both of these.

IMO it would be great to also have it throw an error even when the type of the left-hand side _doesn't_ include `null`, just for the sake of consistency, but that's a separate issue. My personal preference would be that when dealing with strings, it always lets you do `||` whereas for all other values it would expect `??` whether the value might be null or not.

But anyway, the `ignorePrimitives` option will be a good start.

**Comment by bradzacher** [comment]
@mbrowne see this [playground](https://typescript-eslint.io/play/#ts=5.0.3&jsx=true&sourceType=module&code=CYUwxgNghgTiAEYD2A7AzgF3iAtlAlhAILDBxpoBc8mM+KA5vAD7woCuEEA3AFDLosEegGsAjPAC88AEQAeKPAAWcAGaSA5AHoNAPhnwA1PAAUuAsVLk0LVjIC0jmQEojsuVqj6+vUJFgIApjwqkhI1EgARgBW4FisHFx8QUKiAExS7ooqIOraegbGJqFItrKO9i5u8p7eQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WlqYSNkAC1pkA9gEMkyMswDm6KL2jjokcGAC+ILUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA) for a repro.

The goal of this would be to allow users to tweak what types that they want to allow falsey coercion for. Akin to some of the options available for rules like [`strict-boolean-expressions`](https://typescript-eslint.io/rules/strict-boolean-expressions/#options)
