### ISSUE TITLE
[typescript-eslint] typescript-eslint was conflicted eslint

### ISSUE THREAD

**Issue by Bruno-Goudric** [typescript-eslint/typescript-eslint#4922]
```JSON

{
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": [
        "plugin:react/recommended",
        "airbnb",
        "eslint:recommended",
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "prettier"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": "latest",
        "sourceType": "module"
    },
    "plugins": [
        "react",
        "react-hooks",
        "@typescript-eslint",
        "prettier"
    ],
    "rules": {
        "react-hooks/rules-of-hooks": "error",
        "no-use-before-define": "off",
        "react-hooks/exhaustive-deps": "warn",
        "react/jsx-filename-extension": [
            1,
            {
                "extensions": [
                    ".tsx"
                ]
            }
        ],
        "import/prefer-default-export": "off",
        "import/extensions": [
            "error",
            "ignorePackages",
            {
                "ts": "never",
                "tsx": "never"
            }
        ],
        "prettier/prettier": "error"
    },
    "settings": {
        "import/resolver": {
            "typescript": {}
        }
    }
}

```

```TS
// your repro code case
```

https://gist.github.com/Bruno-Goudric/44102ef3367135230d5c272fdc3836ec

**Expected Result**

**Actual Result**

Failed to compile.

Plugin "@typescript-eslint" was conflicted between ".eslintrc.json" and "..\..\package.json » eslint-config-react-app#overrides[0]".
ERROR in Plugin "@typescript-eslint" was conflicted between ".eslintrc.json" and "..\..\package.json » eslint-config-react-app#overrides[0]".

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.22.0` |
| `@typescript-eslint/parser`        | `5.22.0` |
| `TypeScript`                       | `4.6.4` |
| `ESLint`                           | `^7.32.0 || ^8.2.0` |
| `node`                             | `17.0.0` |

**Comment by bradzacher** [comment]
This occurs if you have multiple versions of our package installed locally. ESLint errors because it cannot tell which version of the package it's supposed to use.

You need to clean up your workspace so that you only have one version installed.
