### ISSUE TITLE
[RFC] Lerna and plans to remove it from depenedencies

### ISSUE THREAD

**Issue by armano2** [typescript-eslint/typescript-eslint#4956]
### Context
Lerna for some time hasn't been updated and is no longer maintained, as a replacements we moved to NX, but currently there are still some command and parts of workflow that relies on it.

currently we are using Lerna for 2 tasks:
1. `"clean": "lerna clean && lerna run clean" ` in main package.json
2. release pipeline

### Possible replacements

1. We can replace clean command with 
    `nx run-many --target=clean --all --parallel` in main package.json

2. release pipeline can be replaced by 
   according to documentation there is no build in functionality to release packages with use of nx, https://nx.dev/guides/lerna-and-nx
  
   from my research we have generaly 2 options https://github.com/jscutlery/semver or https://github.com/bikecoders/ngx-deploy-npm
  
   https://github.com/jscutlery/semver - in my opinion this package better suits our needs as it follows "same" principals as lerna publish

### Note

this threat is meant for discussion and its not meant to be a guideline

**Comment by bradzacher** [comment]
Nx has taken over lerna I believe so ther should be no need to migrate.

Note that `lerna clean` also optionally nukes tge `node_modules` folders in all of the folders as well as running the `clean` script.

**Comment by armano2** [comment]
even if nrwl took over lerna, we are no longer using 99% of its functionalities, all what is left is `lerna clean` and `lerna publish` 

lerna is quiet big dependency wise (~3k lines in yarn.lock),

maybe `nx` is going to receive something like `publish` 🙏

**Comment by bradzacher** [comment]
@JamesHenry is actually working on cleaning up lerna now and is working to trim out a bunch of stuff from the package!

For now - we'll leave lerna as is, and as James gets progresses the work he'll update this repo as appropriate.
