### ISSUE TITLE
[require-this-void-annotation] New rule proposal

### ISSUE THREAD

**Issue by ilyub** [typescript-eslint/typescript-eslint#4964]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Your package has "unbound-method" rule.
This rule suggests using "this: void" annotation to avoid warning when method is not using "this".

I suggest to add a new rule "require-this-void-annotation" that will ensure that ALL methods that do not use "this" have "this: void" annotation.

I suggest this rule to be added to your package because it is complementary to "unbound-method" rule.

### Fail Cases

```typescript
class Sample {
  f() {}
}

const x = {
  f() {}
}
```

### Pass Cases

```typescript
class Sample {
  f(this: void) {}

  g() {
    console.log(this);
  }
}

const x = {
  f(this: void) {}
}
```

**Comment by bradzacher** [comment]
We have thought about this in the past but there was (according to the TS folks) a problem with performance.

I don't remember the specifics, but IIRC adding a `this` annotation does something similar to making your function generic - which means that whenever it's called, TS has to do more work to ensure its safe.
This in turn can greatly impact your typecheck time.

In contrast, a different (and IMO better) way to "work around" method binding is to not use methods, and instead use arrow function properties. I don't believe that these have the same typecheck perf penalty that `this` annotations have.
`unbound-method` is designed to ignore class properties and property signatures. It only reports on methods and method signatures.

---

The perf issue is a big reason why this isn't really a good idea for a lint rule to create a standard across the ecosystem.

**Comment by ilyub** [comment]
Thx for detailed explanation.

I have adjusted existing core eslint rules:
```
"object-shorthand": ["warn", "properties"],
"class-methods-use-this": ["warn", { enforceForClassFields: false }],
```
to encorage the use of arrow functions as you suggest.

It looks like this works perfectly in combination with "unbound-method".
