### ISSUE TITLE
Docs: Add a move notice on the top of every rule .md file

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#4980]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Folks still often go to the .md files for rules instead of their typescript-eslint.io/rules/* page. Google still gives those too.

![Screenshot of searching "typescript-eslint/strict-boolean-expressions" on Google and getting the .md file](https://user-images.githubusercontent.com/3335181/168489054-09595a0f-0aef-4138-8565-015d350f4960.png)

Let's add a big notice to the top of the .md pages like:

> This page has moved to https://typescript-eslint.io/rules/*. Please update your links to point to there!

### Affected URL(s)

https://typescript-eslint.io/rules/*

**Comment by bradzacher** [comment]
we probably need someone to setup a google web admin account and ensure that our website is properly and completely indexed by google?

**Comment by Josh-Cena** [comment]
We cannot add it above the H1 heading, because Docusaurus will only search for the first H1 heading to be used as title, so any content before that will make it believe there's no "global title". Do we want:

```md
# `await-thenable`

Disallows awaiting a value that is not a Thenable.

## We've moved!

This page has moved to https://typescript-eslint.io/rules/adjacent-overload-signatures. The Markdown source may be incomplete or contain syntax not understood by the GitHub Markdown renderer. Please update your links to point to the website instead!

This rule disallows awaiting a value that is not a "Thenable" (an object which has `then` method, such as a Promise).
```

Or:

```md
# `await-thenable`

## We've moved!

This page has moved to https://typescript-eslint.io/rules/adjacent-overload-signatures. The Markdown source may be incomplete or contain syntax not understood by the GitHub Markdown renderer. Please update your links to point to the website instead!

Disallows awaiting a value that is not a Thenable.

This rule disallows awaiting a value that is not a "Thenable" (an object which has `then` method, such as a Promise).
```

If we are to use a Remark plugin to strip this paragraph before building the website, both would be functionally the same.
