### ISSUE TITLE
Docs: searching for a rule name does not return the rules page

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#5008]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

If you search for a rule's name the very first result must be the rule's documentation page.

Currently the first result is a link to the rules table. For a lot of rules the other results aren't even the rules docs. For something like the `no-unsafe-*` rules the search only returns the rules table!

### Affected URL(s)

https://typescript-eslint.io/search?q=no-unsafe
https://typescript-eslint.io/search?q=no-unsafe-argument

**Comment by JoshuaKGoldberg** [comment]
OMG I have been forgetting to file this for _ages_. +1.

**Comment by shortcuts** [comment]
Hey, so here it seems that it's not really related to the `/search` page but the indexing itself.

The website still uses the old infra, which might be outdated (https://docsearch.algolia.com/docs/migrating-from-legacy), here's a screenshot for the results on the new infra:
![Screenshot 2022-05-17 at 18 18 40](https://user-images.githubusercontent.com/20689156/168859956-645c42e4-06e1-4f13-8882-e7270fd86c08.png)
![Screenshot 2022-05-17 at 18 18 54](https://user-images.githubusercontent.com/20689156/168860005-4d2b7217-1962-4410-8880-351241a8ea14.png)

**Comment by Josh-Cena** [comment]
Ah, I wasn't expecting the infra to have this big an impact on the search results🤦‍♂️ Thanks a lot!

We should really take a look at `/search` some time. I'm personally clueless about what's going on, and those issues have kind of stagnated.

**Comment by bradzacher** [comment]
Confirming that the new infra works like a charm and searching for the rule name correctly takes you to the rule page 🎉🎉🎉🥳
