### ISSUE TITLE
Bug: TS2339 doesn't work in Vue SFC Template

### ISSUE THREAD

**Issue by ijcnvv** [typescript-eslint/typescript-eslint#5013]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

it doesnt support vue components

### Repro Code

```typescript
<template>
  <div>{{ item.attr.id }} {{ item.attr.nam }}</div>
</template>

<script lang="ts">
import { ref } from "vue";

type ItemType = {
  attr: {
    id: number;
    name: string;
  }
}

export default {
  setup() {
    const item = ref<ItemType>({ attr: { id: 1, name: "test" } });

    return { item };
  },
};
</script>
```

### ESLint Config

```javascript
module.exports = {
  parser: 'vue-eslint-parser',
  parserOptions: {
        parser: '@typescript-eslint/parser',
        sourceType: 'module',
        ecmaVersion: 'latest',
        ecmaFeatures: {
            globalReturn: false,
            impliedStrict: false,
            jsx: false,
        },
    },
 extends: [
        'eslint:recommended',
        '@vue/typescript',
        'plugin:@typescript-eslint/recommended',
        'plugin:vue/vue3-essential',
    ],
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node",
  }
}
```

### Expected Result

expected that TS2339 error will be showed on the 2rd line

### Actual Result

there was no error on the 2rd line

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.23.0` |
| `@typescript-eslint/parser`            | `5.23.0` |
| `TypeScript`                           | `4.6.4` |
| `ESLint`                               | `8.15.0` |
| `node`                                 | `16.15` |

**Comment by armano2** [comment]
issue is relatively simple to solve, you need different parser,  in your configuration you defined parser as `@typescript-eslint/parser` witch is nto correct for vue files, they have to be processed first by vue-eslint-parser, witch is described at https://eslint.vuejs.org/user-guide/#how-to-use-a-custom-parser

```diff
- "parser": "@typescript-eslint/parser",
+ "parser": "vue-eslint-parser",
  "parserOptions": {
+     "parser": "@typescript-eslint/parser",
      ....
  }
```

**Comment by ijcnvv** [comment]
Have you looked my eslint configuration? Its same

**Comment by bradzacher** [comment]
As mentioned in my comment.
Supporting TS errors in vue is not what our project does.
You'll need to look into the vue project and its tooling for more information on using vue and TS together.
