### ISSUE TITLE
Bug: [member-delimiter-style] autofixer result is not as expected with option `delimiter: 'none'`

### ISSUE THREAD

**Issue by holazz** [typescript-eslint/typescript-eslint#5022]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.6.4&sourceType=module&code=C4TwDgpgBAYg9nKBeKBvAUFKBDAXGzLKAI32ACcBXCAbkIF8aoBjfAM2wBsBnW9e9EA&rules=N4IgAgLgngDgpgZwMYCcCWMIFpEBs0B2EA9ALZykBGcKWAJnPqWhDVgtLnCAFwDaIAO4BDFARAAaUKQCuuCGnwFuPUAyYsavEAQD2ykAF9DAXUNA&tsConfig=N4XyA

### Repro Code

```typescript
type Foo = {
  a: {
    b: true;
  }; c: false;
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/member-delimiter-style": ["warn", {
      "multiline": {
        "delimiter": "none"
      },
    }],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

```ts
type Foo = {
  a: {
    b: true
  }; c: false
}
```

### Actual Result

```ts
type Foo = {
  a: {
    b: true
  }; c: false;
}
```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.25.0` |
| `@typescript-eslint/parser`            | `5.25.0` |
| `TypeScript`                           | `4.6.4` |
| `ESLint`                               | `8.15.0` |
| `node`                                 | `16.15.0` |

**Comment by JoshuaKGoldberg** [comment]
🤔 This works for me on v5.25.0. ESLint has to do a couple of passes of fixing to get it all working, but at least in my runs, `esslint index.ts --fix` removes all the semicolons in the test case.

Can you give more info on how you reproduced this @holazz? How were you able to see that not all the semicolons are removed?

**Comment by armano2** [comment]
@JoshuaKGoldberg this is actually a valid bug report, autofixer is allowing to fix lines that have more than one `;` in them, even if one of them is a last character of the line

simplified use case
```ts
type Foo = {
  a: {}; c: false;
}
```
