### ISSUE TITLE
Docs: More details on Built-In Configurations

### ISSUE THREAD

**Issue by PabloLION** [typescript-eslint/typescript-eslint#5030]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I'm trying to use a more strict rule on linting. But all three rules in the [`strict` chapter](https://typescript-eslint.io/docs/linting/configs#strict) reported error of being unable to find some plugins.

Please add more details on how to use the [built-in configurations](https://typescript-eslint.io/docs/linting/configs#built-in-configurations) (same page as before)

The first missing plugin `@typescript-eslint/eslint-plugin-await-thenable` is [not on NPM](https://www.npmjs.com/search?q=%40typescript-eslint%2Feslint-plugin-await-thenable) (0 packages found) and I don't know where to find it.

<details><summary> The error message </summary>

```
$ yarn lint
yarn run v1.22.18
$ eslint . --ext .ts

Oops! Something went wrong! :(

ESLint: 8.16.0

ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin-await-thenable".

(The package "@typescript-eslint/eslint-plugin-await-thenable" was not found when loaded as a Node module from the directory "SOME_DIR".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install @typescript-eslint/eslint-plugin-await-thenable@latest --save-dev

The plugin "@typescript-eslint/eslint-plugin-await-thenable" was referenced from the config file in "package.json".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

### Affected URL(s)

https://typescript-eslint.io/docs/linting/configs

**Comment by PabloLION** [comment]
OS: Darwin arm64 21.3.0

**Comment by Josh-Cena** [comment]
This is either a bug or a user mistake... What's your ESLint config like?

`@typescript-eslint/await-thenable` is a rule. The fact that ESLint is looking for a plugin means something is in the wrong place.

**Comment by PabloLION** [comment]
> What's your ESLint config like?

I moved it into `"eslintConfig"` in the `package.json`.
ESLint was working because it raised some warnings without `"env": {"node": true},`

**Comment by Josh-Cena** [comment]
I mean, the actual configuration object. This is obviously a bug or a user mistake, not missing documentation.

**Comment by PabloLION** [comment]
Thanks for the reply. It's like this:

```
"eslintConfig": {
    "env": {
      "node": true
    },
    "extends": [
      "eslint:recommended",
      "plugin:@typescript-eslint/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "plugins": [
      "@typescript-eslint"
    ],
    "root": true
  },
 ```

**Comment by JoshuaKGoldberg** [comment]
I can't reproduce with that config, either as an `"eslintConfig"` package setting or in a standalone `.eslintrc.js` file.

@Josh-Cena is right, this is a user bug report and not a documentation request. @PabloLION I'm going to go ahead and close this for housekeeping purposes. Please file an issue using one of the bug report templates on https://github.com/typescript-eslint/typescript-eslint/issues/new/choose. To be able to help you, we need more info than what you're providing in this docs request 🙂 .

**Comment by PabloLION** [comment]
Hi @JoshuaKGoldberg , thanks for testing.
Have you tried with `"plugin:@typescript-eslint/recommended-requiring-type-checking",plugin:@typescript-eslint/strict" `?
The full `eslintConfig` is like
```
  "eslintConfig": {
    "env": {
      "node": true
    },
    "extends": [
      "eslint:recommended",
      "plugin:@typescript-eslint/recommended",
      "plugin:@typescript-eslint/recommended-requiring-type-checking",
      "plugin:@typescript-eslint/strict"
    ],
    "parser": "@typescript-eslint/parser",
    "plugins": [
      "@typescript-eslint"
    ],
    "root": true
  },
```

**Comment by bradzacher** [comment]
@PabloLION

Please create a minimal reproduction and push it to a github repository. You can file a new issue with the problem and the reproduction [using this issue form.](https://github.com/typescript-eslint/typescript-eslint/issues/new?assignees=&labels=bug%2Ctriage&template=8-bug-report-complex.yaml&title=Bug%3A+%3Cshort+description+of+the+issue%3E)

We can't help you by attempting to reproduce your environment via config snippets - we need a full and complete repro!

***Help us to help you***
Thanks!
