### ISSUE TITLE
Docs: [no-extraneous-class] Explain why the rule is useful

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5040]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Right now the rule just quotes TSLint's old docs as evidence:

> Users who come from a Java-style OO language may wrap their utility functions in an extra class, instead of putting them at the top level.

...but it doesn't explain _why_ wrapping utility functions in an extra class is unnecessary or even bad.

In summary:
* Wrapper classes add extra runtime bloat and cognitive complexity to code without adding any structural improvements
    * Whatever would be put on them, such as utility functions, is already organized by virtue of the module it's in.
    * You can always `import * as ...` the module to get all of them in a single object.
* IDEs can't provide as good autocompletions when you start typing the names of the helpers, since they're on a class instead of freely available to import
* It's harder to statically analyze code for unused variables, etc. when they're all on the class (see: [ts-prune](https://github.com/nadeesha/ts-prune)).

IME, this kind of class structure often comes up and is later regretted with teams that are used to adhering to OOP principles but then work in a runtime (e.g. Node) and project type (e.g. Express) that don't need them. They eventually get used to using ECMAScript modules as their form of organization, and find the extra classes to be unnecessary bloat.

### Affected URL(s)

https://typescript-eslint.io/rules/no-extraneous-class

**Comment by armano2** [comment]
examples of correct and incorrect codes shift to much, as its not clear what is ok and what is not, maybe changing only `StaticOnly` could help with that

**Comment by goktugyil** [comment]
> Wrapper classes add extra runtime bloat and cognitive complexity to code without adding any structural improvements

Can you put correct and incorrect examples for this? Also how does this add cognitive complexity?

**Comment by goktugyil** [comment]
> IDEs can't provide as good autocompletions when you start typing the names of the helpers, since they're on a class instead of freely available to import

What situation does IDEs not provide good autocompletions? I don't think I've experienced this

**Comment by goktugyil** [comment]
> Wrapper classes add extra runtime bloat

Do we have any data on the performance difference? Is it 5% difference? 0.01% difference?

**Comment by JoshuaKGoldberg** [comment]
@goktugyil great questions, thanks for pressing on the clarifications! I moved them to individual threads in #5059.
