### ISSUE TITLE
Repo: simplify prettier include lists

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5060]
## Overview

Copying conversation from https://github.com/typescript-eslint/typescript-eslint/pull/5027/files#r878861604: we explicitly list file extensions for Prettier. It's getting a little unweildy.

```
    "format": "prettier --write \"./**/*.{ts,mts,cts,tsx,js,mjs,cjs,jsx,json,md,css}\" --ignore-path ../../.prettierignore",
```

Let's look at using @Josh-Cena's suggestion of `prettier --write \"./**/*\" --ignore-unknown --ignore-path ...`.

It would be nice to format all supported files, including yaml...

**Comment by lydell** [comment]
ℹ️ You shouldn’t need a glob at all, `prettier --write . --whatever` should do the trick. That’s the recommended way of using Prettier: https://prettier.io/docs/en/install.html and https://prettier.io/docs/en/install.html#summary
