### ISSUE TITLE
Chore: consider add a 'repo tooling' issue template

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5062]
## Overview

We don't have a template for this. It's not a high priority for users and should be at the bottom if we do make it. But I think it'd be nice for issues like #5060 and suggesting new issue forms.

**Comment by Josh-Cena** [comment]
Question: how does this relate to https://github.com/typescript-eslint/typescript-eslint/issues/4821?

**Comment by JoshuaKGoldberg** [comment]
LOL. Thank you. 💀
