### ISSUE TITLE
Rule proposal: [prefer-short-falsy | prefer-short-truthy] !a instead of a == false

### ISSUE THREAD

**Issue by jguddas** [typescript-eslint/typescript-eslint#5075]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Please close if this is considered a formatting rule or if this has to much overlap with `no-unnecessary-condition`.

### Fail Cases

```typescript
if (foo == true) {}
if (foo != false) {}
if (!!foo) {}
declare const foo: boolean; if (foo === true) {}
declare const foo: []; if (foo.length !== 0) {}
declare const foo: true | 'bar' | undefined; if (foo !== undefined) {}

/* --- */

if (foo != true) {}
if (foo == false) {}
if (!!!foo) {}
declare const foo: boolean; if (foo === false) {}
declare const foo: []; if (foo.length === 0) {}
declare const foo: true | 'bar' | undefined; if (foo == undefined) {}

/* --- */

const x = foo == true
const x = foo == false
const x = !!!foo
// …
```

### Pass Cases

```typescript
if (foo) {}
if (foo) {}
if (foo) {}
declare const foo: boolean; if (foo) {}
declare const foo: []; if (foo.length) {}
declare const foo: true | 'bar' | undefined; if (foo) {}

/* --- */

if (!foo) {}
if (!foo) {}
if (!foo) {}
declare const foo: boolean; if (!foo) {}
declare const foo: []; if (!foo.length) {}
declare const foo: true | 'bar' | undefined; if (!foo) {}

/* --- */

const x = !!foo
const x = !foo
const x = !foo
```

**Comment by bradzacher** [comment]
https://typescript-eslint.io/rules/no-unnecessary-boolean-literal-compare

this should do what you want
