### ISSUE TITLE
Enhancement: [no-floating-promises] Report when a promise does not have a catch handler added synchronously

### ISSUE THREAD

**Issue by shawnmcknight** [typescript-eslint/typescript-eslint#5084]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-floating-promises

### Description

Currently the `no-floating-promises` rule can miss a scenario where a Promise does not attach a catch handler prior to another asynchronous action.  If the promise rejects it can result in an unhandled promise exception.  A catch handler must be added synchronously or a rejection will cause an unhandled promise rejection.

Effectively the workflow would assign a promise to a variable without any exception handlers or await keyword.  A subsequent line is executed which executes asynchronously.  Subsequently a catch handler is attached to the original promise or it is awaited.  typescript-eslint will not detect this as an unhandled promise because it is awaited or handled, but it is too late in the workflow to prevent an unhandled exception.

Please see https://stackoverflow.com/a/67789482 for a more detailed explainer of the scenario and why this is an issue.

### Fail

```typescript
const resolving = () => {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, 1000);
  });
};

const rejecting = () => {
  return new Promise((resolve, reject) => {
    setTimeout(reject, 1000);
  });
};

(async () => {
  const rejectingPromise = rejecting();

  try {
    await resolving();
    await rejectingPromise;
  } catch (err) {
    console.log(err);
  }
})().catch((err) => {
  console.log(err);
});
```

### Pass

```typescript
const resolving = () => {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, 1000);
  });
};

const rejecting = () => {
  return new Promise((resolve, reject) => {
    setTimeout(reject, 1000);
  });
};

(async () => {
  const rejectingPromise = rejecting();

  try {
    await rejectingPromise;
    await resolving();
  } catch (err) {
    console.log(err);
  }
})().catch((err) => {
  console.log(err);
});
```

**Comment by JoshuaKGoldberg** [comment]
Huh, what an interesting edge case. Thanks for raising!

The proposed kind of _"who has been called and in what way"_ tracking is mostly impossible to do except in very simple cases. Even in the example code snippet, where the only difference is the order of `await resolve();` and `await rejectingPromise();`, just knowing the difference between `rejolving()` and `resolving()` would require creating some kind of tracker that understands the contents of the functions.

Here's a more fun, more impossible scenario:

```ts
// (let's suppose these are imported from some npm package)
declare const rejecting: () => Promise<number>;
declare const resolving: () => Promise<number>;

const [first, second] = Math.random() > 0.5
  ? [rejecting(), resolving()] 
  : [resolving(), rejecting()];

try {
  await first;
  await second;
} catch (error) {
  console.log(error);
}
```

Closing as out of scope, but if you think I'm missing something please do post back!
