### ISSUE TITLE
Bug: [prefer-readonly-parameter-types] Date param requires readonly how?

### ISSUE THREAD

**Issue by imcotton** [typescript-eslint/typescript-eslint#5087]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.6.4&sourceType=module&code=PQgEB4CcFMDNpgOwMbVAGwJYCMC8AiaAZwCYAGARgFZ9RgA+AKGcegA8AHAe0gBdRkXREX6IArgFsA+ry5SRkTIgDmoXKAAUiAFyhxE7AgCUa+noB0sgMq9FKjUebtufAUJGgAJgENe0GXISRGqanroAIr7QJrhmnuYAbt7oYtAA8rAOjEA&rules=N4IgAgLgngDgpgZwMYCcCWMIFpEBs0B2EA9DCnAGZwpbkCGAJgPYG5RYx0p0C2cE1LNHgIQALhDUUTFCAC+QA&tsConfig=N4XyA

### Repro Code

```typescript
/// <reference lib="es2015" />



export const num_to_string = (n: number) => n.toString()

export const date_to_ms = (d: Date) => d.valueOf()
```

### ESLint Config

```javascript
module.exports = {
  "parser": "@typescript-eslint/parser",
  "rules": {
    "@typescript-eslint/prefer-readonly-parameter-types": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {}
}
```

### Expected Result

No complain with builtin `Date` type.

### Actual Result

> Parameter should be a read only type.

### Versions

| package | version |
| -- | -- |
| `@typescript-eslint/eslint-plugin` | `5.26.0` |
| `@typescript-eslint/parser` | `5.26.0` |
| `TypeScript` | `4.6.4` |
| `ESLint` | `8.15.0` |
| `node` | `web` |

**Comment by bradzacher** [comment]
> A type is considered readonly if...
> ... it is an object type whose properties are all marked as readonly, and whose values are all considered readonly. 

https://typescript-eslint.io/rules/prefer-readonly-parameter-types#rule-details

You need to make the date type deeply readonly. There are utilities that may be able to assist you in making it deeply readonly.
Or you can look to defining your own immutable date type.
Or you can use a 3rd pparty date lib that has truly immutable date constructs.

---

Failing that something like #4185 may be desirable.

**Comment by imcotton** [comment]
Thanks for the triage, watching **4185** now, at the meantime found https://www.npmjs.com/package/readonly-date as alternative.
