### ISSUE TITLE
Docs: Auto-generate rules tables for the website

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5096]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Following #4976 and #5085, we're on a roll with the website cleanups! Let's have the giant tables of rules on https://typescript-eslint.io/rules be generated automatically. That way we don't need to keep a giant Markdown table (or two?!) checked into Git.

### Affected URL(s)

https://typescript-eslint.io/rules/

**Comment by armano2** [comment]
related to #4168

**Comment by Josh-Cena** [comment]
Correct—I'm waiting on #5085 and I'll probably work on both
