### ISSUE TITLE
Rule for spacing around punctuation in types

### ISSUE THREAD

**Issue by ddurschlag6river** [typescript-eslint/typescript-eslint#51]
Possibly as part of type-annotation-spacing, possible as a new rule. Right now, the punctuation that I can think of are `|` (union), `&` (intersection), `[]` (array or tuple), and `{}` (anonymous object definition).

The obvious preferences I can see for `|` and `&` are no-spaces (`string|number`) and spaces (`string | number`). Tuples and anonymous types are a bit different -- the two relevant spaces are after `[` and before `]`, but not before `[` or after `]`. A more real-world-y example might be:
```
type keyedEntity = baseEntity & { primaryKey: string|number; records: [ number, string ][]; };
```

This could be formatted a number of different ways.

**Comment by fregante** [comment]
A related rule is https://github.com/typescript-eslint/typescript-eslint/blob/fbf1640c5ab67770a1ace5a9bad2bddfa35bd88d/packages/eslint-plugin/docs/rules/type-annotation-spacing.md

**Comment by DASPRiD** [comment]
It should also be possible to define whether there is a space in object definitions between `?` and `:` – most of the time, you don't want that.

**Comment by elszczepano** [comment]
Hi,
Are you going to develop this feature? Or am I able to achieve the goal described in this issue using other available rules?

**Comment by arrudaje** [comment]
Is someone looking at this at the moment? I am willing to give it a try.

**Comment by JoshuaKGoldberg** [comment]
Per https://typescript-eslint.io/docs/linting/troubleshooting/formatting/#eslint-core-and-formatting:

> With the exception of bug fixes, no new formatting-related pull requests will be accepted into typescript-eslint.

This issue has existed for 4 years without much involvement, and requests a new formatting rule. I'm going to go ahead and close it. Thanks for the participation folks!
