### ISSUE TITLE
Docs: improve testing individual tests flow

### ISSUE THREAD

**Issue by sbdchd** [typescript-eslint/typescript-eslint#5114]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Maybe this isn't a feature, in which case this should be a feature request, but I'm trying to figure out how to run an individual test for a rule.

My current setup is to comment out all the test cases I don't want to run but this isn't ideal.

ESLint has some docs outlining their `only: true` and `RuleTester.only` features, but those didn't work when trying them with typescript eslint

https://eslint.org/docs/developer-guide/unit-tests#running-individual-tests

### Affected URL(s)

https://typescript-eslint.io/docs/development/custom-rules#testing

**Comment by bradzacher** [comment]
> but those didn't work when trying them with typescript eslint

What do you mean, exactly?
Could you provide some more context, maybe a repro repo to help explain?

**Comment by sbdchd** [comment]
I'm trying to figure out how to run a single test out of a group of tests defined via:

https://typescript-eslint.io/docs/development/custom-rules/#testing

```ts
ruleTester.run('my-rule', rule, {
  valid: [
    /* ... */
  ],
  invalid: [
    /* ... */
  ],
});
```


The docs note that the API is similar (not the same), so maybe it's not possible to only run one test, but with ESLint we can pass `only: true` to a given test and that will work.

https://eslint.org/docs/developer-guide/unit-tests#running-individual-tests

**Comment by armano2** [comment]
> I'm trying to figure out how to run a single test out of a group of tests defined via:

it should be working in same way as in eslint, i'm using it often,

eg

```js
ruleTester.run('space-infix-ops', rule, {
  valid: [
    {
      only: true,
      code: `
        enum Test {
          KEY1 = 2,
        }
      `,
    },
  ...
```

as for `RuleTester.only` we are missing type for it, but it should still work

**Comment by sbdchd** [comment]
Oh whoops, I'm on a really old version, time to upgrade. Thank you!

**Comment by JoshuaKGoldberg** [comment]
![Back to the Future Delorean getting to 88 mph and making lightning](https://user-images.githubusercontent.com/3335181/171078472-df6b86b5-9d58-447f-9b64-3d4827fda296.gif)
