### ISSUE TITLE
Cannot extend "plugin:@typescript-eslint/eslint-recommended" configuration

### ISSUE THREAD

**Issue by peterjuras** [typescript-eslint/typescript-eslint#512]
The [README file in the configs directory](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/src/configs#eslint-recommended) suggests, that the eslint-recommended config which disables some eslint:recommended rules and can be used with the following config:

```json
{
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended"
  ]
}
```

However, using this config throws an error stating that this config cannot be found/extended.

**Repro**

You can [clone this repository](https://github.com/peterjuras/typescript-eslint-recommended-issue) to reproduce the error

**Additional Info**

This is the error message when trying to run eslint:
```
Oops! Something went wrong! :(

ESLint: 5.16.0.
ESLint couldn't find the config "plugin:@typescript-eslint/eslint-recommended" to extend from. Please check that the name of the config is correct.
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.8.0` |
| `@typescript-eslint/parser`        | `1.8.0` |
| `TypeScript`                       | `3.4.5` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `12.2.0` (10.X tested as well) |
| `npm`                              | `6.9.0` |

**Comment by ThomasdenH** [comment]
I see. The exported name is `eslintRecommended`, you should be able to use that for now. I have created a PR that fixes the name. (#513)
