### ISSUE TITLE
Docs: Audit and streamline CONTRIBUTING.md

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5120]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

It's been a while since we overhauled the CONTRIBUTING.md file. Lots has changed in the repo and we'll want to check what needs to be updated.

Furthermore, I'm finding the file to be pretty verbose as I read through it. We can probably streamline it a bit. Maybe use some `<summary>` tags to collapse sections. TBD!

### Affected URL(s)

https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md

**Comment by santoshyadavdev** [comment]
Hey @JoshuaKGoldberg can I help with this, I have done some OSS and read through some contributing.md files, maybe I can help here.

**Comment by JoshuaKGoldberg** [comment]
Awesome, thanks! I suspect it'll be helpful for someone who isn't on the maintainer crew to take a look, since you'll know better than us what is useful as an external contributor. Feel free to send a PR at whatever level of suggestion granularity you want. 🎉
