### ISSUE TITLE
Bug: [no-floating-promise] error: Definition for rule '@typescript-eslint/no-floating-promise' was not found

### ISSUE THREAD

**Issue by eng-dibo** [typescript-eslint/typescript-eslint#5139]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=HYUw7gBACgTg9gWwJYGcQAoYQLwD4IzoBEcA1kQJQUDcQA&eslintrc=N4KABGBEAOCGBOBnApvSAuKABALgT2mUQGN4BLaHAWiIBsyA7HAejiVUgBpwo2V4A8pTIB7BogxhQECDHgiAVsmI5JAbR4yoOEmIBmZAOYA6BYjGRNYALrctkcwFd4xZABUCySZAC2IgCaOtF48AL52YCAwtI6GjBLoapC4niTklDSI9EzMdIzU0DFxDJC2UcgAHjjIDP4JSYWxjOgphGkU1Hk58MoiPj41-sj+pdyQ8EFEGNLY+G2kHZnZLAwiVHq0IrA4jIZU0PI+ZCjeqPJoIKEg16FAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
[playground](https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=HYUw7gBACgTg9gWwJYGcQAoYQLwD4IzoBEcA1kQJQUDcQA&eslintrc=N4KABGBEAOCGBOBnApvSAuKABALgT2mUQGN4BLaHAWiIBsyA7HAejiVUgBpwo2V4A8pTIB7BogxhQECDHgiAVsmI5JAbR4yoOEmIBmZAOYA6BYjGRNYALrctkcwFd4xZABUCySZAC2IgCaOtF48AL52YCAwtI6GjBLoapC4niTklDSI9EzMdIzU0DFxDJC2UcgAHjjIDP4JSYWxjOgphGkU1Hk58MoiPj41-sj+pdyQ8EFEGNLY+G2kHZnZLAwiVHq0IrA4jIZU0PI+ZCjeqPJoIKEg16FAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)
```

### ESLint Config

```javascript
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": [
      "tsconfig.json"
    ],
    "sourceType": "module"
  },
  
"plugins":["@typescript-eslint/eslint-plugin"],
"extends":["plugin:@typescript-eslint/recommended"],
"rules":{
  "@typescript-eslint/no-floating-promise": "error"
}


}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

the rule is defined

### Actual Result

```
Definition for rule '@typescript-eslint/no-floating-promise' was not found. 1:1 - 1:2
```

```
Property @typescript-eslint/no-floating-promise is not allowed. 13:3 - 13:43
```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.23.0` |
| `@typescript-eslint/parser`            | `5.23.0` |
| `TypeScript`                           | `4.6.0` |
| `ESLint`                               | 8.16.0` |
| `node`                                 | `16.18.0` |

**Comment by bradzacher** [comment]
The rule is called `no-floating-promises` - note the `s` at the end
https://typescript-eslint.io/rules/no-floating-promises/
