### ISSUE TITLE
Enhancement: [explicit-function-return-type] exclude requirement for primitives

### ISSUE THREAD

**Issue by zargold** [typescript-eslint/typescript-eslint#5163]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/explicit-function-return-type.md

### Description

I propose we add an option `ignore-types` to the rule which would allow users to pick when the rule applies: 

```jsonc
{
  "@typescript-eslint/explicit-function-return-type": [
    "error",
    {
      "ignore-types": {
       // theoretically, if we can imply that this is a JSX.Element then
       // no need to explicitly type that the return is JSX.Element
         "JSX.Element": true, // For now, I'd expect this NOT to work
        // calcSalesTax = price  => price * localTaxes is obviously a number
        // so we don't need to be explicit in this case
         "number": true, // this one I think is plausible true means you can ignore when TS knows that it's this type
        // when running a function with just a side effect/noop
        // and there's no return seems redundant to indicate `: void`
         "void": true, // should be easy
        "undefined": true, // similar
        "string": true ...
      }
     // In other words, I'd love the rule to apply for objects/arrays of objects
     // and especially user defined interfaces
    }
  ]
}
```

This eslint rule makes sense in that in certain times it makes it easier to read and write code especially for complicated situations. I would gladly add it to most enterprise and personal projects. However, at times I find it warns/errors at unnecessary times. I also feel that eslint should as much as possible standardize its options--if some rules have certain options that may make sense for other rules we should extend the philosophy of having the same options. Finally, this is a rule that allows a wide variety of options already so adding an additional one seems like less of a burden on understanding (than adding custom options on a rule with no options). 

In other words, in certain situations it's pretty obvious what the return type is, and being explicit is a bit overkill. So there are advantages and disadvantages of applying it ham-handedly. If I know and everybody knows that the function they're running only has side effects but doesn't return something do they really need to say that it returns `void`? 

### Fail

```json
{
  "@typescript-eslint/explicit-function-return-type": [
   "error",
   { "ignore-types": { "void": true } }
  ]
}
```

The eslint in general will still give errors for all inferred types, except `void` inferred type will be ignored.

```typescript
const calculateSalesTax = (price) => price * 0.08975; // still need to be explicit about `number` since that was not added to `ignore-types`

const mergeUserProfile = (name: string, age: number, description: string) => ({
  name,
  age,
  description
}); // still need to be explicit for all `Record` type
```

### Pass

With:

```json
{
  "@typescript-eslint/explicit-function-return-type": [
   "error",
   { "ignore-types": { "void": true, "number": true } }
  ]
}
```
```typescript
const doSideEffectsForUpdate = (user: IUser) => {
  updateUser(user);
  callAsyncAnalytics(user, actions.CLICKED_UPDATE);
}; // since there's nothing returned here inferred type is void and no need to indicate something

const calculateSalesTax = (price) => price * 0.08975; // no need to be explicit about inferred type `number`
```

### Additional Info

This rule is a great rule but for some types it is overkill--if typescript can infer the type and humans can easily read the type. Do we have to be explicit about it? Do we *really*? Tools should be used when they help improve consistency, readability and ability for people to get things done. If it starts to hinder progress, people might get rid of the rule entirely rather than apply it when you need it most.

**Comment by bradzacher** [comment]
Thanks for the super detailed request!

Unfortunately the rule isn't type-aware. Without types we can't tell what the return type of the function will be to be able to ignore it.
We won't be making the rule type-aware as this is a deeply impactful breaking change which precludes a lot of users from using it.

Technically some types are inferable via static analysis of the AST only (eg `() => x * 1` always returns a number), but beyond the simple cases it's not possible.

---

If you want something less restrictive, consider our rule [`explicit-module-boundary-types`](https://typescript-eslint.io/rules/explicit-module-boundary-types/) which just enforces at the module boundary as opposed to every function.
