### ISSUE TITLE
Bug: [ban-types] can't ban stuff like '"string"' and '"number"' for a type

### ISSUE THREAD

**Issue by yay** [typescript-eslint/typescript-eslint#5167]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=G4QwTgBAzgLmBcEDkswEsB2BzJBuAUKJBgK4C2iSpZARgKZh5A&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AIwEMnajTUMAbXDYciaNAD20SABoRorKOyQ+KdJgXKcAcmT4qTAOY6NS7aMgBbFMk5HEGyAClY+sABNJTHfjlaLKAAzSgAPAHVKfAALJ31DI0gA5QBfeUDdJlgrdnFTDHMM61t7RwwXN3xPb19-DJUQiKjY8qyc8ST6lOSINJ6oRFD8RCYPABFEIM4EfAEwA1hEZO7RAF0RbpSgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
var str: 'string';
var num: 'number';
```
```


### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    {
  "rules": {
    "@typescript-eslint/ban-types": [
      "error",
      {
        "types": {
          "'string'": {
            "message": "Just don't",
            "fixWith": "string"
          },
          "'number'": {
            "message": "Just don't",
            "fixWith": "number"
          }
        },
        "extendDefaults": true
      }
    ]
  }
}
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

The code to be replaced with:

```
var str: string;
var num: number;
```

### Actual Result

Repro code stays the same:

```
var str: 'string';
var num: 'number';
```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.27.1` |
| `@typescript-eslint/parser`            | `5.27.1` |
| `TypeScript`                           | `4.4.0` |
| `ESLint`                               | `7.7.0` |
| `node`                                 | `14.19.1` |

**Comment by bradzacher** [comment]
ban-types intentionally does not handle any literal types - it only matches named types.

This FAQ article can help direct you towards how you might ban specific literal types if you want:
https://typescript-eslint.io/docs/linting/troubleshooting/#how-can-i-ban-specific-language-feature

**Comment by yay** [comment]
@bradzacher  Thank you. It's still not clear to me how the `selector` should looks like in this case?
<img width="330" alt="Screen Shot 2022-06-09 at 10 27 33 PM" src="https://user-images.githubusercontent.com/1799756/172948451-9c0dc6ce-9020-439b-be19-bf6b67020b29.png">

**Comment by armano2** [comment]
you can read more about query at: https://github.com/estools/esquery

depends on what exactly you want to "report" you can do either 

```
'Literal[value="number"]'
```
or
```
'TSLiteralType[literal.value="number"]'
```

**Comment by yay** [comment]
Thank you. Much appreciated.
