### ISSUE TITLE
[class-methods-use-this] Prevent false positives with classes

### ISSUE THREAD

**Issue by luxaritas** [typescript-eslint/typescript-eslint#52]
I think it would be benefit to have a rule similar to `typescript/no-unused-vars` to prevent `class-methods-use-this` from triggering on class methods where the method in base class (or additionally one of its descendants) doesn't use `this`, but one of the (other) subclasses does. For example, an abstract class may implement a method as just returning a default value, but the intention of the method is that some/most subclasses will have a concrete implementation that does use `this`.

**Comment by bradzacher** [comment]
I'll close this in favour of #1103 as that has more discussion
