### ISSUE TITLE
Docs: first homepage "Get Started" button background has low color contrast

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5211]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

![Screenshot of the Get Started button with blue fill on a dark blue background](https://user-images.githubusercontent.com/3335181/174568059-a5761a89-3489-4c16-acea-6719cbaee72b.png)

Although the button's white text has enough color contrast against the blue button fill, the fill itself isn't very contrasted against the medium/dark blue background. That means users might not know what is or isn't safe to click on (interactive button or non-interactive background).

Suggested remediation: add some kind of outline/shadow to the button. Which is a nice design idea in general, to make it stand out more.

Discussed on stream with @BenDMyers on Twitch: https://www.twitch.tv/videos/1498962341. See https://benmyers.dev/blog/fix-low-contrast-text for a description of low contrast issues.

### Affected URL(s)

https://typescript-eslint.io

**Comment by BenDMyers** [comment]
Adding a bit more context as to which thresholds the new colors will need to meet:

* Given this button text is both bold and `1.4rem` (resolving to `25.2px`), it definitely constitutes [large text](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html#dfn-large-scale). This means it only needs to meet a ratio of **3**:1, per [WCAG Success Criterion 1.4.3: Contrast (Minimum)](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html)
* The button background should stand out from the page background with a ratio of **3**:1. This requirement for buttons and other UI controls comes from [WCAG Success Criterion 1.4.11: Non-text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html).

From a general usability and UI design standpoint, the _Get Started_ link is the core call to action on the page, and could benefit from a much higher contrast than **3**:1. On the stream, we discussed making the button background yellow as a possibility.

**Comment by andrmaz** [comment]
@JoshuaKGoldberg Is this issue open in order to contribute ?

**Comment by bradzacher** [comment]
@andrmaz any issue with the "accepting PRs" tag is free to anyone! Doubly so if it's got the "good first issue" tag!

If there's no open PR and there's noone saying there doing it, you're good to put up a PR!

**Comment by andrmaz** [comment]
@bradzacher Thanks for your quick reply.

I am fairly new to open source. I'll start working on it as soon as I can.
