### ISSUE TITLE
Repo: filter private packages from the release log

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#5218]
### Suggestion

This week we didn't merge any publicly-facing PRs. However https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.29.0 was released as a minor bump instead of a patch bump. This was because #5190 was marked as a `feat` instead of a `chore`.

These private packages definitely should not contribute to our weekly release version calculation.

We need to look into if lerna can filter these out automatically so we don't need to be strict about the semantic commit labelling. I've been manually updating PR titles as I saw them - but we really shouldn't be relying on a manual process to ensure our automated process is correct.

**Comment by JamesHenry** [comment]
Looking into this via the custom changelog renderer option in `nx release`

**Comment by JamesHenry** [comment]
We addressed this via excluding the relevant projects from publishing
