### ISSUE TITLE
Rule proposal: prefer-private-class-members 

### ISSUE THREAD

**Issue by nicojs** [typescript-eslint/typescript-eslint#5228]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I would love a rule that forces users to use [private class members](https://devblogs.microsoft.com/typescript/announcing-typescript-4-3/#private-elements) over using the `private` keyword.

Private class members have been added in ES 2022 and are supported in most major browsers as well as Node 14 and up. Time for libraries to migrate.

### Fail Cases

```typescript
class Foo {
   // Error
   private bar = 0;
  
  // Error
  constructor(private baz: number){} 
 
  // Error
  private toString(): string {
    return '';
  }
}
```

### Pass Cases

```typescript
class Foo {
   #bar = 0;
  
  #baz: number;
  constructor(baz: number) {
    this.#baz = baz;
  } 
 
  // Error
  #toString(): string {
    return '';
  }
}
```

### Additional Info

This might be auto-fixable, that would be sweet! But it might make it very difficult.

**Comment by Josh-Cena** [comment]
That's true; I feel TS-ESLint is being a bit over-optimistic about auto-fixes in general. I can't speak for existing rules.

**Comment by bradzacher** [comment]
Yeah so there is a problem in that historically we have been bad about truly evaluating the scope of an autofixer and determining if it's truly safe.

Then generally we don't go back and remove a fixer unless it's really a problem or has some glaring issues.

So we have some bad fixers in our codebase that we should get rid of, but haven't gotten around to it yet. What's important is enforcing the standards going forward. 

---

The golden rule of autofixers is "don't break the build".

I eluded to it on the other issue - but a fixer for this is unsafe at typecheck time and at runtime.

Few actually know this but you can legally (no type error) access a TS private member anywhere at anytime using the index access syntax: `instance['privMember']`. I believe the reason this was added was for testing purposes so you could poke at the internals.

This fun quirk means that renaming a member to a true private member would break your build! As Josh said not only your TS build, but also your runtime code! Doubly bad.

There's another side-effect to consider here - the public API. If you're a module owner then TS private members are part of your public API surface. To a pure JS consumer they just see normal members that are undocumented. By changing them to true private you will make a breaking change to your API surface - which can inadvertently break consumer code!

A suggestion fixer would be more acceptable here, but I don't know if it's worth it given that TS IDE features can be use to do this just as fast IIRC (select prop name, f2 to rename, enter new name - TS renames usages, delete private keyword).

I just don't see enough value to warrant a standalone rule in our codebase, personally.

**Comment by bradzacher** [comment]
yeah migration is something that ESLint *can* be used for - but it isn't the intention for it to be used that way.
the issue with building rules for migration purposes is that rules live forever but migrations are temporary.

So you might allow some unsafe transforms for a migration (and fix the few edge-cases by hand), but outside of migration you need to be strict.

This is where I wish there was a canonical TS codemod framework where someone could contribute these sorts of one-off migrations.

---

In regards to 3rd-party, there is this plugin which might work (and they already have an issue) - https://github.com/sindresorhus/eslint-plugin-unicorn/issues/979
