### ISSUE TITLE
parser typescript declarations are unusable

### ISSUE THREAD

**Issue by 43081j** [typescript-eslint/typescript-eslint#523]
I know you've mentioned the types before as being in progress still (and likely to change), but figured this is its own issue.

Currently the parser types are unusable as `eslint-visitor-keys` has no declaration file in the shipped package.

The same seems to apply for `eslint-scope` types.

This means nobody using typescript can successfully import the parser package without installing the dependencies themselves (and copying your custom types across).

**Comment by bradzacher** [comment]
It's hard for us to know exactly how people are consuming our packages; i.e. I didn't realise people were consuming the parser package directly from within typescript code.

More than happy to accept PRs if there's something that's hard to use for your use case.
Esp for something like `eslint-scope`, the idea would just be to move it to the utils package.

**Comment by 43081j** [comment]
In my case i'm trying to consume the parser module for test purposes (i need to parse a block of code in order to do some assertions on the resulting AST and what not).

It seems to be because the dependant types are devDependencies but im not too sure as I haven't run into this problem before.
