### ISSUE TITLE
Docs: Make it more clear on README.mds to go to the website for docs

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5242]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Some users are still navigating directly to README.md files and getting lost in all the nomenclature. Example: https://twitter.com/amatchneer/status/1540410203165937665

> how does anyone make sense of all these little ts eslint word salad packages

Agreed. Too much word salad. Most .md source files are generally for developers only, and the website docs are for most end users. Any important end-user info that exists only in README.md files should be added to the website, I would think.

### Affected URL(s)

n/a

**Comment by bradzacher** [comment]
For our proper plugin the very first block of text after the heading are two links to our website.

Also when you open our repo the very first thing in the readme is two emoji fingers pointing at the website url.

Can we get any more direct than that?

The only other option would be to delete all the text from the readme and only have the links?

**Comment by JoshuaKGoldberg** [comment]
>  delete all the text from the readme and only have the links?

... that!

If the text is just dup, is there any reason to keep it around?

**Comment by Josh-Cena** [comment]
Should be fixed by #5116 (mostly). I think it's still useful to keep _some_ text around, just get rid of the rules table.

**Comment by bradzacher** [comment]
The thing to be weary of is that it's easy to get lost jumping from a package readme to the website.

We need to ensure there are deep links to help people get to the info they need instead of figuring out our website to get it

**Comment by JoshuaKGoldberg** [comment]
#5247 and #5248 are roughly blocking this work, in that I think this will be easier to do once they're merged.
