### ISSUE TITLE
Bug: [no-invalid-void-type] better report message for void used as a constituent inside a function return type

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#5255]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwAoBKALnlWQFsAjEGeAH3gDcctgBuAWACggA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1uYDcBDRgBNaPDpWFFS6KAHc+0JpHBgAviDVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

**Comment by bradzacher** [comment]
That is working as expected.
You should use `type | undefined`, not `| void`.
This is the exact thing the rule is seeking to prevent.

Please see the rule docs
https://typescript-eslint.io/rules/no-invalid-void-type/

**Comment by Zamiell** [comment]
Oh, I see. The error message is a little misleading then, maybe we should update it?

**Comment by JoshuaKGoldberg** [comment]
Good point - yes, we can special case the error message in the case of a union or intersection type directly used as a function's return type.

**Comment by kmin-jeong** [comment]
@Zamiell I push pr about this issue! Please check it if what you intended!

**Comment by kmin-jeong** [comment]
@JoshuaKGoldberg @Zamiell 
When I contributed to this issue, I only added the message type part, and the rest of the part was the type boolean, so I didn't touch it. Is it correct that I understood?

**Comment by JoshuaKGoldberg** [comment]
Sorry, I don't follow?

**Comment by kmin-jeong** [comment]
@JoshuaKGoldberg I don't have enough time to solve this , so can I hand it over to someone else?
