### ISSUE TITLE
Docs: Add rationale to rules

### ISSUE THREAD

**Issue by hoffa** [typescript-eslint/typescript-eslint#5265]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Would be great if the rules consistently explained _why_ something is a rule.

See e.g. `shellcheck` rules, which always include a "Rationale" section:

- https://github.com/koalaman/shellcheck/wiki/SC1000
- https://github.com/koalaman/shellcheck/wiki/SC2236
- https://github.com/koalaman/shellcheck/wiki/SC2235

For `typescript-eslint`, the rationales are either unclear (mixed in the _what_ section) or missing (e.g. https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/restrict-template-expressions.md).

A rationale would help developers improve their understanding as they stumble upon violations, and would help rule writers clarify their reasoning.

### Affected URL(s)

Some examples:

- https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/restrict-template-expressions.md
- https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/dot-notation.md

**Comment by JoshuaKGoldberg** [comment]
Strong agree! We can treat this as a spin-off / subset of #4861, in that this is a big part of why a lot of rule docs are unclear.

It'd be great to have testing set up to make sure each rule has a _Rule Details_ section and at least one sentence explaining the rule. Right now that's in Jest tests but will likely eventually be linting. #4366.

**Comment by JoshuaKGoldberg** [comment]
Following up on this old issue, we've had a lot of docs overhauls land: 

* #4367: added options descriptions & started to standardize headings
* #5696: we added a lot of details to many rules and continued standardizing headings
* #7951: made sure fleshed-out _"When Not To Use It"_ exist in almost all rules

At this point, roughly all rules have a 1-2 paragraph rationale as their opening descriptions. So I think we can close this general issue out as resolved.

But! Docs are never done, and it's a certainty some rules don't have informative rationales. Request to anybody reading this: if you see a rule whose docs are lacking, please file a new issue. That'd be lovely. ❤️
