### ISSUE TITLE
Bug: [no-empty-interface]  autofix break typescript

### ISSUE THREAD

**Issue by rluvaton** [typescript-eslint/typescript-eslint#5273]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

[Link](https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=JYOwLgpgTgZghgYwgAgILIN4ChnIA4CMAXMiAK4C2ARtANw74BMJ51dWAvllqJLIigBCyCAA9IIACYBnNJm5csCADZxps4dg5A&eslintrc=N4KABGBEBOCuA2BTAzpAXGUFvcgAQBcBPABxQGNoBLEggWhXioDsCB6ZgewYFtai6LAomgAzAIblE6KAHdx0ZpHBgAviFVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)

### Repro Code

```typescript
interface A {
  p1: number;
  p2: number;
}

interface B extends A {

}

class B {
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
        "@typescript-eslint/no-empty-interface": "warn"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

I expect that it will not try to auto-fix this

```ts
interface A {
  p1: number;
  p2: number;
}

interface B extends A {

}

class B {
}
```

### Actual Result

After auto-fix this how it will look:

```ts
interface A {
  p1: number;
  p2: number;
}

type B = A

class B {
}
```

This breaks typescript

### Additional Info

[TypeScript Eslint Demo](https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=JYOwLgpgTgZghgYwgAgILIN4ChnIA4CMAXMiAK4C2ARtANw74BMJ51dWAvllqJLIigBCyCAA9IIACYBnNJm5csCADZxps4dg5A&eslintrc=N4KABGBEBOCuA2BTAzpAXGUFvcgAQBcBPABxQGNoBLEggWhXioDsCB6ZgewYFtai6LAomgAzAIblE6KAHdx0ZpHBgAviFVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)

### Versions

| package | version |
| -- | -- |
| `@typescript-eslint/eslint-plugin` | `5.30.0` |
| `@typescript-eslint/parser` | `5.30.0` |
| `TypeScript` | `4.7.2` |
| `ESLint` | `8.15.0` |
| `node` | `web` |

**Comment by bradzacher** [comment]
You should really avoid using declaration merging between interfaces and classes. It's really, really unsafe because you can define properties that aren't initialised and there are no tools to catch the bug (not even TS will catch it).
