### ISSUE TITLE
Docs: `ban-ts-comment` is missing description of a new `descriptionFormat` option

### ISSUE THREAD

**Issue by dzek69** [typescript-eslint/typescript-eslint#5282]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

This PR https://github.com/typescript-eslint/typescript-eslint/pull/5026 adds a support for new  `descriptionFormat` option for `ban-ts-comment`.

@[Josh-Cena](https://github.com/Josh-Cena) had written:
> I personally don't like this API design a lot, so I'd like to get settled on the API before writing docs.

But finally the PR got merged without any docs and a month has passed without docs update, so I guess it just a forgotten thing now. So I'm leaving this issue as an reminder.

### Affected URL(s)

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/ban-ts-comment.md

**Comment by Josh-Cena** [comment]
Ha, would fix that when I get to my computer.
