### ISSUE TITLE
Bug: [type-annotation-spacing] New line throw an error

### ISSUE THREAD

**Issue by PierBJX** [typescript-eslint/typescript-eslint#5305]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.4.4&sourceType=module&code=MYewdgzgLgBADgJxHApgqBPA6gSygCwBlwBzAOQEMBbFLfHYfAUQA9gUUATAWQpcJRgAsACgYMAFwxoCHGBIwAvDADkUFNBUBuIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6I02gQyaYHt8XfJT5NayYlzLMA5uiiJo0PtEgAacNjwdyVGvWSMWrZgBNELeQG1N2BUpXrb2AEwa7ELB5wBlAO6U+GQAFgDCXMiI8gCM7t5QAGpcVFwARkgAIohk8MlCjhiQAGaU0Mj4TvFQfLD4igCS9QBiAKIAQnymhDFx3pAAsogAtqmKLQAexNAoyCJMPc52kE2wTGTColk5eRvzGF5VkKmd3Rixix6QktBcQ4h1ZfLFpeWQFxAAvr2XK2u7E1MZnN5Ad4kcTgsqjhrrd7opUIUSmUKu8wF9UZAfIJhGQ2vA+GQANYg1E4Y5dGKo9GHcLweAA6bIWaiElQqDJGSwO4sBFgaJU75LACCSi4hAZQJZiJeFUFWgA8qkAFbZfASpnA6XIypg+pDYgqfBbXI3XZPJGvOU4Iq5fAAFUUTGS4smjOZTF5RS48EiVuqRSKkXtjud6vdnu9kQuH2cAF1vpAhlxxrQkHswFZIIplKo1GAAKwABljmhjHyAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
const propertyWithLongNameWhichExceedMaxLen
  : string = 'test';
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/type-annotation-spacing": "error",
    "@typescript-eslint/indent": [
      "error",
      2,
      {
        "SwitchCase": 1,
        "VariableDeclarator": "first",
        "outerIIFEBody": 1,
        "MemberExpression": 1,
        "FunctionDeclaration": {
          "body": 1,
          "parameters": "first"
        },
        "FunctionExpression": {
          "body": 1,
          "parameters": "first"
        },
        "StaticBlock": {
          "body": 1
        },
        "CallExpression": {
          "arguments": 1
        },
        "ArrayExpression": "first",
        "ObjectExpression": "first",
        "ImportDeclaration": "first",
        "flatTernaryExpressions": false,
        "offsetTernaryExpressions": false
      }
    ],
    "max-len": ["error", 50]
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "declaration": true,
    "declarationDir": "dist/typings",
    "baseUrl": "./",
    "module": "CommonJS",
    "moduleResolution": "node",
    "importHelpers": true,
    "strict": true,
    "noEmitHelpers": true,
    "sourceMap": true,
    "noImplicitAny": false,
    "experimentalDecorators": true,
    "downlevelIteration": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "target": "es6",
    "lib": [
      "dom",
      "esnext"
    ]
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}
```

### Expected Result

I expect the rule to not throw an error when there is a new line and take in account indent rules if defined.

### Actual Result

It does not take in account the new line.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.30.0` |
| `@typescript-eslint/parser`            | `5.30.0` |
| `TypeScript`                           | `4.4.4` |
| `ESLint`                               | `8.18.0` |
| `node`                                 | `16.15.1` |

**Comment by bradzacher** [comment]
This is by design.

The rule by default is configured to disallow spacing before the colon.
A new line and indentation is spacing before the colon, thus it violates the rule.

If you want to use this coding style and insert a newline, then insert the new line afterward.

> and take in account indent rules if defined

Rules are completely isolated. No two rules have any knowledge of one another. They cannot take one another into account.
