### ISSUE TITLE
Enhancement: [naming-convention] Extend Individual Selector typeAlias with rules for InstanceType, ReturnType or simple declaration

### ISSUE THREAD

**Issue by MaksymRadchenko** [typescript-eslint/typescript-eslint#5316]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/naming-convention.md

### Description

There are a few kinds of "type" aliases

type TButtonWithIconInstance = InstanceType<ReturnType<typeof import('widgets/global/ButtonWithIcon').default>>;
type TProductDetail = ReturnType<typeof import('widgets/product/ProductDetail').default>;
type TCustomerData = { customerId: string; isAnonymous: boolean };

would we awesome to be able provide unique setup for each kind
ex.
InstanceType -> [T + name + Instance]
ReturnType --> [T + name]
simple declaration --> [T + PascalCase Name]

and so on

### Fail

```typescript
Current 
{
"selector": "typeAlias",
"format": ["PascalCase"],
"prefix": ["T"]
}
```

### Pass

```typescript
Extended
{
"selector": "typeAlias",
"format": ["PascalCase"],
"prefix": ["T"],
"customTypes" : [
    "instanceType" : {
        "format": ["PascalCase"],
        "prefix": ["T"],
        "suffix" ["Instance"]
    },
    "returnType" : {
        "format": ["PascalCase"],
        "prefix": ["RT"]
    }
]
}
```

### Additional Info

Thank you

**Comment by bradzacher** [comment]
Thanks for the issue!

I don't think this has broad enough applicability for it to be accepted into this project.

Whilst your project might treat specific generic types as "different kinds of types", most do not as things like `ReturnType` ultimately just resolve to a normal type.

**Comment by MaksymRadchenko** [comment]
Thanks! Maybe there will be extension for InstanceType
