### ISSUE TITLE
Enhancement: [no-unnecessary-condition] option to ignore consts

### ISSUE THREAD

**Issue by mycroftjr** [typescript-eslint/typescript-eslint#5319]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-unnecessary-condition

### Description

I would like to see an option for this rule that ignores "unnecessary conditions" that are const values (see below example).
This is useful for top-of-script script configuration for end users, or as a sort of C-style `#if blah` preprocessor directive/switch for functionality. The const values not counted could have to be named in a specific format, such as ALL_UPPER_CASE, if you're worried about auto-fixed https://eslint.org/docs/latest/rules/prefer-const variables not being detected (i.e. vars that were previously not const, but their last other assignment was removed, so the auto-fixer made the var const).

### Fail

```typescript
if (true)
```

### Pass

```typescript
// Do the thing?
const DO_IT = true;

if (DO_IT)
```

**Comment by bradzacher** [comment]
Thanks for the request. Based on your description - I don't see this as having broad applicability to the wider TS community.

Dead code is dead code, and unnecessary conditions that come from constant, unchanging variables is dead code that the vast majority of users will want to flag and clean up.

**Comment by mycroftjr** [comment]
> Thanks for the request. Based on your description - I don't see this as having broad applicability to the wider TS community.
> 
> Dead code is dead code, and unnecessary conditions that come from constant, unchanging variables is dead code that the vast majority of users will want to flag and clean up.

As I said, the code is not dead because there's literally a section of const variables at the top of the script for behavior configuration purposes to be edited by the user. But I guess I should probably just move that section to an external JSON file...
