### ISSUE TITLE
Enhancement: [restrict-template-expressions] `allowURLSearchParams` option

### ISSUE THREAD

**Issue by mmkal** [typescript-eslint/typescript-eslint#5323]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://github.com/typescript-eslint/typescript-eslint/blob/v4.28.2/packages/eslint-plugin/docs/rules/restrict-template-expressions.md

### Description

Having to do this is a little annoying:

```ts
const href = `https://example.com/foo/bar/baz?${new URLSearchParams({ abc: 'xyz' }).toString()}`
```

When the version of the above without `.toString()` is _always_ safe and less verbose. [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) is supported in pretty much every browser, nodejs, and deno.

I read the rationale for closing the broader issue #3538: https://github.com/typescript-eslint/typescript-eslint/issues/3538#issuecomment-862697743 and I don't think it applies here. This is specific to `URLSearchParams` not any-class-which-implements-`toString` which is less safe and harder to implement.

### Fail

```typescript
const href = 'https://example.com/foo/bar/baz?${{ abc: 'xyz' }}`
```

### Pass

```typescript
const href = 'https://example.com/foo/bar/baz?${new URLSearchParams({ abc: 'xyz' })}`
```

### Additional Info

The option should work just like `allowNumber`, `allowBoolean`, etc.

I'd be happy to contribute a PR if it'd be accepted.

**Comment by bradzacher** [comment]
The reasoning in the comment still applies here - just because this type has a `toString` method doesn't mean it's what you want to be using in all cases.

I'm not sure I understand why there should be a specific exception made for this type over any other type. Why should we add an option for `URLSearchParams` and not `Array`, or `<insert type name here>`?

**Comment by mmkal** [comment]
Because URLSearchParams has a `toString` method which is particularly useful for an extremely ubiquitous, standardised format (URLs), unlike `Array`. If `<insert type name here>` is supported in all engines and outputs a similarly ubiquitous and well spec'd format, maybe it should be considered too. I can't think of any examples right now.
