### ISSUE TITLE
Bug: no-inferrable-types fixer does not remove `?` when removing the type

### ISSUE THREAD

**Issue by davecaruso** [typescript-eslint/typescript-eslint#5340]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=GYVwdgxgLglg9mABFApgZygCgIYH4BciYIAtgEYoBOiAvIgIwCUiA3ogL4CwAUEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1uYDNFpoAQwBGSWkVKoMkftA7RI4MAF8QyoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

There is a lint error, use the fix command on it.

### Repro Code

```typescript
function test(a?: number = 1) {}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-inferable-types": ["error"],
  },
};
```

### Expected Result

Valid TS Code
```
function test(a = 1) {}
```

### Actual Result

Code that throws ts error

> Parameter cannot have question mark and initializer

```
function test(a? = 1) {}
```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.30.6` |
| `@typescript-eslint/parser`            | `5.30.6` |
| `TypeScript`                           | `4.7.4` |
| `ESLint`                               | `8.19.0` |
| `node`                                 | `16.16.0` |

**Comment by davecaruso** [comment]
sorry, i pressed submit too early without adding an issue title or clarifying that it's a bug with the fixer. if i used the wrong template let me know.

**Comment by bradzacher** [comment]
In this instance the code as written is actually invalid - it's a TS error to have an optional property with a default value. Which is where you enter the territory of "undefined" behaviour.

I think we can probably handle this though.

**Comment by davecaruso** [comment]
oh wait, you're right, the ts error is there before and after. i didn't catch that. the only reason i ended up there was either by another rule or realizing i should set the default value to avoid an undefined; it was a manual change not another bug.

though before i could even say anything, theres already a pr fixing it. wow, you guys are cool.

**Comment by Josh-Cena** [comment]
Yeah, I agree we shouldn't fix semantic errors to syntax errors.
