### ISSUE TITLE
yarn audit error

### ISSUE THREAD

**Issue by Aayush1820** [typescript-eslint/typescript-eslint#5353]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://www.npmjs.com/advisories/1081522

### Repro Code

```typescript
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ glob-parent before 6.0.1 vulnerable to Regular Expression    │
│               │ Denial of Service (ReDoS)                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ glob-parent                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=6.0.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @typescript-eslint/parser                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @typescript-eslint/parser >                                  │
│               │ @typescript-eslint/typescript-estree > globby > fast-glob >  │
│               │ glob-parent                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1081522                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/<rule-name>": ["error", ...<options>],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

No vulnerabilities

### Actual Result

1 moderate vulnerabilities

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `^5.30.0` |
| `@typescript-eslint/parser`            | `^5.30.0` |
| `TypeScript`                           | `~4.5.5` |
| `ESLint`                               | `^8.18.0` |
| `node`                                 | `>= 14.17.0` |

**Comment by bradzacher** [comment]
Thus is a non issue because you don't use our tooling to power disk reads in production using user generated globs.
There is exactly zero risk here.

Regardless - we are stuck on v11 of gkobby due to their breaking change switch to ESM, and thus cannot fix this.

**Comment by paulmillr** [comment]
this is also bogus

https://github.com/github/advisory-database/pull/531

**Comment by ThisIsMissEm** [comment]
@paulmillr thanks for figuring this out, and closing the loop here. Hopefully GitHub will take note of the incident and it'll lead to better review on advisories before they're published: https://github.com/orgs/github-community/discussions/20895
