### ISSUE TITLE
Enhancement: [no-magic-numbers] add support for switch case

### ISSUE THREAD

**Issue by btd1337** [typescript-eslint/typescript-eslint#5356]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-magic-numbers/

### Description

Today it is not possible to use a switch case with numbers without the `no-magic-number` rule showing an error in the linter.

Is it possible to add an option to ignore errors in switch case statement?

### Fail

```typescript
switch (path.length) {
  case 0: {
    execute_action_a();
    break;
  }
  case 1: {
    execute_action_b();
    break;
  }
  case 2: {
    execute_action_c();
    break;
  }
  case 3: {
    execute_action_d();
    break;
  }
  case 4: {
    execute_action_d();
    break;
  }
  default: {
    execute_action_default();
  }
}
```

### Pass

```typescript
const lenght0 = 0;
const lenght1 = 1;
const lenght2 = 2;
const lenght3 = 3;

switch (path.length) {
  case lenght0: {
    execute_action_a();
    break;
  }
  case 1: {
    execute_action_b();
    break;
  }
  case lenght2: {
    execute_action_c();
    break;
  }
  case lenght3: {
    execute_action_d();
    break;
  }
  case lenght4: {
    execute_action_d();
    break;
  }
  default: {
    execute_action_default();
  }
}
```

### Additional Info

Regardless of having other ways to implement this code, the goal is for the rule to work for those who actually want to use the switch case.

**Comment by bradzacher** [comment]
Thanks for the issue!

This is an extension rule. That means we take the base rule and extend it to support TS syntax or features.

We don't break from the base rule to add new features unless they are specifically related to TS.

In this instance - this request is not related to TS, thus we shall not implement it. If you'd like to see it, feel free to raise a request with the ESLint team.
