### ISSUE TITLE
Bug: [Unnecessary optional chain on a non-nullish value] Using Pick with optional paramater recognize it as non-nullish

### ISSUE THREAD

**Issue by eliezra236** [typescript-eslint/typescript-eslint#5378]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=JYOwLgpgTgZghgYwgAgIICEDCyDeBYAKGWTgC5kAjAeyoBsI4QBuQ4i86uh515BAfg416jFgQC+hQmACeABxRZkAXmQAFYAgDWAHgyYANMgDkFY8gA+JhMYB8YwgiogAzmGQBbGVnJLV+IkpyMCgAVwgDQnEHAidXLgA6WioAcwAKLyx+BIQASjEgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
interface ABC {
  a: boolean;
  b: boolean;
  c?: boolean;
}

type BC = Pick<ABC, 'b' | 'c'>;

const myBC: BC = {
  b: true,
};

console.log(myBC?.c);
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/<rule-name>": ["error", ...<options>],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

`console.log(myBC?.c);`

Shouldn't produce error, since c is optional.

### Actual Result

Unnecessary optional chain on a non-nullish value.eslint[@typescript-eslint/no-unnecessary-condition](https://typescript-eslint.io/rules/no-unnecessary-condition)

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `X.Y.Z` |
| `@typescript-eslint/parser`            | `X.Y.Z` |
| `TypeScript`                           | `X.Y.Z` |
| `ESLint`                               | `X.Y.Z` |
| `node`                                 | `X.Y.Z` |

**Comment by bradzacher** [comment]
It looks like you're misunderstanding how optional chaining works!
Your optional chain is equivalent to this code:
```ts
let result;
if (myBC === undefined || myBC === null) {
  result = undefined;
} else {
  result = myBC.c;
}
console.log(result);
```

Optional chaining operates on the left value, not the right. The value of `.c` does not matter at all!
Thus because your type for `myBC` is never nullish, the optional chain is unnecessary
