### ISSUE TITLE
Docs: Add a left sidebar category for formatting rules

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5400]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Right now, all non-deprecated rules are placed in the same list in the sidebar. That includes formatting rules mixed with other, more useful rules.

![Screenshot of typescript-eslint.io left sidebar with rules](https://user-images.githubusercontent.com/3335181/181855710-52b8073d-b863-4e08-ab9b-de38c9d8dedf.png)

Proposal: similar to how deprecated rules have their own section at the bottom, let's put all formatting rules (ones that should be replaced with a formatter such as Prettier) down in their own section? That way they don't clutter the space and take focus away from the more useful rules.

### Affected URL(s)

https://typescript-eslint.io/rules/*

**Comment by bradzacher** [comment]
ESLint core does this - https://eslint.org/docs/latest/rules/

It would be a win for us because we can "demote" the formatting rules and promote the actual error catching rules.
