### ISSUE TITLE
Enhancement: [naming-convention] Negative modifiers/types

### ISSUE THREAD

**Issue by danikaze** [typescript-eslint/typescript-eslint#5403]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

// https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/naming-convention.md

### Description

**What**
Modifiers or types could accept a prefix like `no-` or `!` (so it becomes like `modifiers: ['no-destructured']`, etc.) to allow more granular rules.

Same could be applied to types as `'no-function'` etc.

**Why**
Things like this are not possible:
```js
// .eslintrc.js
'@typescript-eslint/naming-convention': [
  'error',
  // destructured variables come from other places so no format is enforced
  {
    selector: 'variable',
    modifiers: ['destructured'],
    format: null,
  },
  // constants must be UPPER_CASE
  {
    selector: 'variable',
    modifiers: ['const'],
    format: ['UPPER_CASE'],
  },
];
```
```ts
// code
import webpackPaths from '../configs/webpack.paths';
const { appNodeModulesPath } = webpackPaths;

// Variable name `appNodeModulesPath` must match one of the following formats: UPPER_CASE
```

It would be possible by changing the modifier like this:
```js
  {
    selector: 'variable',
    modifiers: ['const', 'no-destructured'],
    format: ['UPPER_CASE'],
  },
```

### Fail

```typescript
const globalConstant = 123;
```

### Pass

```typescript
const GLOBAL_CONSTANT = 123;
const { srcNodeModulesPath, appNodeModulesPath } = webpackPaths;
```

**Comment by bradzacher** [comment]
[Using the exact config you provided, all examples you provided are correctly checked as you have described them to be](https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=CYUwxgNghgTiAEA3W8DOB7AtiAarAXPFAHYCeA3AFCUDel88A9I-MegC7xgAW4A1iGDwARqXjteXdMQBmASwDm9KcVScaRAA6aAculABZfQFcIIVAAUoE+AF94AXjRZcsKgzDS18DQEF-AYF2js7YeDDuKt5+APq+cQnxSYnBThhhbpS21HQMzFy8YAJCouKSnrKKyhXeUNp6hiZmltbcIemuEdVenIF9vu0u4ZE1vYnjyUmDGV3Z1PkAYr4AkgAylKPwChDowlAQAMI9JJxOAIwATADMVJT5Fr4Ayo-wGz3wAOKrAPIAQr6rGIHb46R4AFV8OjBIUuNzeqnUaBgYAaICMwFM5isEgANFpdPo0U0sa1UqFOrcgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6JgQwFtmBzWsgHsmAN0QtKw9GADa4bDkTRog6JAA08hVgXZIyREjL5V0yCI5UOAIyQatuyF0EATSgDNKS1BhmQXKPhwxrDQiC6QALqaunruqlwc+NJMCPAOEAC+Mbo6sfqGiMamGOaWlDZ2OfnObp7e0n5CTMjJ0RlxCUmNkACqAAr9AKIASgD6AMIAggDKQ1EdmQ6R8kuZQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA).

**Comment by danikaze** [comment]
Uhm, I see.
I wonder why I'm getting the errors...
Basically added the rules to a project generated using the [erb](https://github.com/electron-react-boilerplate/electron-react-boilerplate) template...

**Comment by danikaze** [comment]
I've been trying other things like this:
```ts
import { basename } from 'path'; // this destructuration is ok
import webpackPaths from '../configs/webpack.paths';

const { srcNodeModulesPath, appNodeModulesPath } = webpackPaths; // I still get the error here
```

I think it might be related to the fact that the `webpack.paths.ts` file exports everything in an object as default:
If I change the export to multiple constants like this:
```ts
// from this
const srcNodeModulesPath = '123';
const appNodeModulesPath = '456;

export default {
  srcNodeModulesPath,
  appNodeModulesPath,
};

// to this
export const srcNodeModulesPath = '123';
export const appNodeModulesPath = '456;
```
the error disappears...

Is there any known limitation with default exports?

**Comment by bradzacher** [comment]
A default export isn't exporting the names - it's exporting an object.

I.e. your default export is the same as:
```ts
export default { a, b };

// same as
const defaultExp = { a, b };
export default defaultExp;
```

I.e. the names are separately covered by any properties conventions you enforce.

Note that named exports are not equivalent to an object.
```ts
export { a, b };

// NOT the same as
const namedExp = { a, b };
export namedExp; // not even valid syntax
```

---

[Also worth noting again that the examples you mentioned work correctly using the config provided.](https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=JYWwDg9gTgLgBAbzgIwIYGcCmA7VJNwC+cAZlBCHAORiowAWVA3HAPStwPDpwAmm6GFACuAYxjCodYBGxxucCAGsAUKEiw4Ad0zJaopQAU69HmQrUAdJdajZJYAHN0rHXtQHLtBumYqVdtiCiHDoUKIAchD8ALLRwgA2AsYMAIwANHCoYGBRsfFJ6Cn0qURwALzauvpGJugs7HAAkqEwwAkJcI6Y8AwEmFDkUHD0A5j+gcFhkdGYcbyJySYATBXUqcsAzH6T8Nm5s-OLRStrVAAsAKwAbH4qmAAeGvD8JKiJ8AgqcKHheXMFJYMZbpb5ZHL-I6FYoglSEJj+RowCCcejce5PaDwXa-Gb5BbQkybM4bbYIx7POA4-aQwEnBjEyoXG7MIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6JgQwFtmBzWsgHsmAN0QtKw9GADa4bDkTRog6JAA08hVgXZIyREjL5V0yCI5UOAIyQatuyF0EATSgDNKS1BhmQXKPhwxrDQiC6QALqaunruqlwc+NJMCPAOEAC+Mbo6sfqGiMamGOaWlDZ2OfnObp7e0n5CTMjJ0RlxCUmNkACqAAr9AKIASgD6AMIAggDKQ1EdmQ6R8kuZQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)

There's more to this story than you've let on in your OP - your minimal config isn't actually reproducing anything. It's hard to provide much guidance without more information.

---

Regardless, I don't think that negative modifiers add enough to be worth the complexity they bring in. Most, if not all negative modifiers can be expressed with the current schema, albeit verbosely with multiple selectors for different cases.

They also invite issues with conflicting configs. For example, if I configure that "variables except `const` variables should be UPPER_CASE" and "variables except destructured variables should be snake_case", now I have an issue where `let foo` matches BOTH selectors at once. Which format should the identifier be in? How can the user control which one gets matched?

With positive selectors it's not possible to create the same "overlapping sets" (I believe), which significantly reduces the complexity in understanding how the rule works when configuring and debugging.

**Comment by danikaze** [comment]
Yes, I agree that this being the case the negative modifiers are not needed anymore.

But still, it's failing to check on names for default exports.

As I understand a default export is just an object with the `default` property, but if that default property is an object, every field inside the object should have their names, which should be detected by eslint and is not based on the examples.

Is there any way to simulate or test imports in the TS ESLint playground?
In any case it's ok to close this ticket, and if I can provide maybe a basic repo to test this I might open a new ticket as bug maybe. Would that be ok?

**Comment by bradzacher** [comment]
> Is there any way to simulate or test imports in the TS ESLint playground?

No you can't do multi-file setups in the playground.
But you don't need to because imports are NOT linted by the rule.

> every field inside the object should have their names, which should be detected by eslint

It will be detected if you use the selector for object properties (`objectLiteralProperty` or `property`).

> if I can provide maybe a basic repo to test this I might open a new ticket as bug maybe. Would that be ok?

Sure, if you can create an isolated repro in the playground for the issue you're seeing, feel free to raise a new issue and we can help you out.
