### ISSUE TITLE
Bug: [member ordering] Static initialization blocks are regarded as public instance methods.

### ISSUE THREAD

**Issue by LvChengbin** [typescript-eslint/typescript-eslint#5404]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play#ts=4.7.2&sourceType=module&code=MYGwhgzhAEAqCmEAu0DeAoa1liQS2GiQE8AHeLAXmgHIAZGgbk2mAHsA7ZAJwFdgkbbgAoAlGmgBfdNPShIMBMgBMaFjnyFUUluy5I+AoWLTTJQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AW0XYCNFpaA9tAAmfZgHNIYDAG0ofaEMgAacNghZ12SKIBmAQwT4psqLsqJ4wlVGSVxTffljRENyGQFNk+OGXxKylCc+AAWAtZgALqqWtpk8PrIyCgmYDJqcTjEVABuToi0Pk6UZLTmltaxWdmw3Ixlxfil5RZWKplZkDmU+fiFTS0h4VWdcd11DUX4JWXDER012XkFtMzFTGSFFe3VNRP1Leszm9tto0tQnt6+sP6BY1rdK-1rN-qntPMXSwdTxx8tl9EGEFo8IFFHgBfTqQiAwqFAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
class Test {
  static type  = 'L';
  constructor() { }
}

class Test2 {
  static { }
  constructor() {}
}
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/member-ordering" : [ "error",
      {
        "default" : [ "field", "signature", "constructor", "method" ],
        "classes" : [
          "private-static-field",
          "public-static-field",
          "private-static-method",
          "public-static-method",
          "private-instance-field",
          "public-instance-field",
          "constructor",
          "private-instance-method",
          "public-instance-method"
        ]
      }
    ]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

No error.

### Actual Result

```
Member constructor should be declared before all public instance method definitions. 8:3 - 8:19

```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.31.0` |
| `@typescript-eslint/parser`            | `5.31.0` |
| `TypeScript`                           | `4.7.4` |
| `ESLint`                               | `8.20.0` |
| `node`                                 | `18.7.0` |

**Comment by JoshuaKGoldberg** [comment]
Amusing. The rule's logic just hasn't been updated to support static initialization blocks since [TypeScript 4.4](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4) added support in August 2021.

Static initialization blocks don't fit nicely into the existing `MemberType` type's concept of:
* `"instance"` vs. `"static"`
* `"field"` vs. `"get"` vs. `"method"` vs. `"set"`

Tentatively: let's say there should be a new description for them? `"static-initialization"`?
