### ISSUE TITLE
Bug: [typescript-compatibility] <TypeScript(4.7.4) which is not officially supported by @typescript-eslint/typescript-estree.>

### ISSUE THREAD

**Issue by Ramya-bs10** [typescript-eslint/typescript-eslint#5418]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=N4WAUABBBEBOD28Au0BcEmwK4FMA04UU0AlgOYB28sOACgIZJI6wUDOaEA2tAA4IArHAGMkbAPQAqSVOgBdApCLF4ANxawSAExwd0XQsqKglRotABmJADa7OPSQDox8xWeV96sNiwDyvJBJ4dk4TdyM+QREUfWgxYWCrMkcBNmDoPBgcACYccXjE8hS0ildDcOJhGkYcABEcC3osayRaBDJYegBbTkxccvcAXzcK6BwAD2YKLT1uAfC+aywyEgpUAAF6CjJmrwBaXWtVpHFtveEj8-gu3kYM+fdF5dWNrZ3rfcPj07Jzy4Sbow9nsLNQuoxAmd6FotHt0iMKjBeEsVmtNttdrADmwjhQTswbh9mOJ+PBhLo2HtVricHsCciahwHsoFMzzNhbLMwoiYFQrux4LZOGNYAhYPdTKN0e9PjjvgDeMEcHi-vQ2JS2FgLFZxvY2WYRWKJTzjPrHprtSRxnZYgwyDgMjAAMLXRUUZUoORm5SDb0QVmShbSzHY3EnBVKlU+Wyiah6wOjDRxhE87km4hIACevAd6DGti6HuN6eI-AaVuF9F4vGLJegbCzQrzAGscAAjeht85qh1+qC+hNmAMm6DBj5Yr548RaEg0UQkdR7aPROP6PtZUXJ9dp9NxbO5mAQzRtrDMWu7ss6yvV88jhuZpswYTdHDWJ096Drgcmr2DojfoYU2UHcDSsTl7GgJwAAskC6awyj-YgJimGYIORZ40TeENJ3xHBCRqcQ52uQtphwLQEMROBmhtCBgAAsx6KIX8ByAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
{
  "name": "first_project",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^14.0.0",
    "@angular/core": "^14.0.0",
    "@angular/forms": "^14.0.0",
    "@angular/platform-browser": "^14.0.0",
    "@angular/platform-browser-dynamic": "^14.0.0",
    "@angular/router": "^14.0.0",
    "@capacitor/android": "4.0.0",
    "@capacitor/app": "4.0.0",
    "@capacitor/core": "4.0.0",
    "@capacitor/haptics": "4.0.0",
    "@capacitor/ios": "4.0.0",
    "@capacitor/keyboard": "4.0.0",
    "@capacitor/status-bar": "4.0.0",
    "@ionic/angular": "^6.1.9",
    "@typescript-eslint/typescript-estree": "^5.32.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.0.0",
    "@angular-eslint/builder": "14.0.2",
    "@angular-eslint/eslint-plugin": "14.0.2",
    "@angular-eslint/eslint-plugin-template": "14.0.2",
    "@angular-eslint/schematics": "14.0.2",
    "@angular-eslint/template-parser": "14.0.2",
    "@angular/cli": "^14.0.0",
    "@angular/compiler": "^14.0.0",
    "@angular/compiler-cli": "^14.0.0",
    "@angular/language-service": "^14.0.0",
    "@capacitor/cli": "4.0.0",
    "@ionic/angular-toolkit": "^6.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "5.29.0",
    "@typescript-eslint/parser": "5.29.0",
    "eslint": "^8.18.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~3.8.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.7.3"
  },
  "description": "An Ionic project"
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/<rule-name>": ["error", ...<options>],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

Angular 14  typescript version is 4.7.2.It should compatible with typescript-eslint/typescript-estree.

### Actual Result

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.7.4

Please only submit bug reports when using the officially supported version.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.29.0` |
| `@typescript-eslint/parser`            | `5.29.0` |
| `TypeScript`                           | `4.7.2` |
| `ESLint`                               | `v8.21.0` |
| `node`                                 | `v16.15.1` |

**Comment by bradzacher** [comment]
We fully support TS 4.7 and there will be no warnings logged when using the latest versions of our tooling.

This problem usually occurs because you have an old version of our tooling installed indirectly. Considering you're using angular's tooling - youul probably find you need to wait for them to upgrade the versions.

https://typescript-eslint.io/docs/linting/troubleshooting/#how-do-i-check-to-see-what-versions-are-installed
