### ISSUE TITLE
Bug: bun-ts-comments: Deprecation notice

### ISSUE THREAD

**Issue by coderaiser** [typescript-eslint/typescript-eslint#5420]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

d

### Repro Code

```typescript
(node:39140) DeprecationWarning: "typescript-eslint: comments" rule has options but is missing the "meta.schema" property and will stop working in ESLint v9. Please add a schema: https://eslint.org/docs/developer-guide/working-with-rules#options-schemas
(node:39140) DeprecationWarning: "typescript-eslint-parser-error" rule has options but is missing the "meta.schema" property and will stop working in ESLint v9. Please add a schema: https://eslint.org/docs/developer-guide/working-with-rules#options-schemas
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/<rule-name>": ["error", ...<options>],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

No deprecation

### Actual Result

Deprecation

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `X.Y.Z` |
| `@typescript-eslint/parser`            | `X.Y.Z` |
| `TypeScript`                           | `X.Y.Z` |
| `ESLint`                               | `X.Y.Z` |
| `node`                                 | `X.Y.Z` |

**Comment by JoshuaKGoldberg** [comment]
wat

**Comment by coderaiser** [comment]
> Starting from `v8.21.0` [ESLint will print deprecation warnings for two changes that are coming in ESLint v9: First, rules with options must specify schemas].(https://eslint.org/blog/2022/08/eslint-v8.21.0-released/#:~:text=ESLint%20will%20now%20print%20deprecation%20warnings%20for%20two%20changes%20that%20are%20coming%20in%20ESLint%20v9%3A%20First%2C%20rules%20with%20options%20must%20specify%20schemas)

I thought that deprecation warnings was related to `typescript-eslint`, but It was related to rules of **[eslint-plugin-putout](https://github.com/coderaiser/putout/tree/master/packages/eslint-plugin-putout#eslint-plugin-putout--)** and has successfully been fixed by adding the schema.

Sorry for inconvenience!
