### ISSUE TITLE
Bug: NewExpression doesn't allow SpreadElement as argument

### ISSUE THREAD

**Issue by burtek** [typescript-eslint/typescript-eslint#5421]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Relevant Package

ast-spec

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

`NewExpression` and `CallExpression` are basically identical in terms of arguments list. Among others, you're perfectly fine with spreading arguments in both of them:

```ts
class A { constructor(...args: unknown[]) {} }
const a = new A(...someArray);

const F = (...args: unknown[]) => {}
const f = F(...someArray);
```

That is reflected in `CallExpression` type:
https://github.com/typescript-eslint/typescript-eslint/blob/d2394f810960fda07b9c8affd47b769d16f4b8cb/packages/ast-spec/src/expression/CallExpression/spec.ts#L7-L10
With `CallExpressionArgument` being:
https://github.com/typescript-eslint/typescript-eslint/blob/d2394f810960fda07b9c8affd47b769d16f4b8cb/packages/ast-spec/src/unions/CallExpressionArgument.ts#L4

At the same time, `NewExpression` typing allows only `Expression` arguments:
https://github.com/typescript-eslint/typescript-eslint/blob/d2394f810960fda07b9c8affd47b769d16f4b8cb/packages/ast-spec/src/expression/NewExpression/spec.ts#L7-L10
`SpreadElement` is not there, even though it is legal to spread arguments in constructor call ([playground](https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&showAST=ts&code=MYGwhgzhAECC0G8CwAoa1gHsB2EAuATgK7B6YEAUAdDWAQOYQBc0R2A1tpgO7YDaAXQCUiaAF9UElKiy480OgWgBeaHwCMAGmgAmbQGYBqGTnwKV0bAFNucarQIEhqIA))

### Fail

```typescript
n/a
```

### Pass

```typescript
n/a
```

**Comment by burtek** [comment]
Ofc happy to preapre a PR for this, but as this is my first contribution to typescript-eslint, I wanted to make sure this is discussed and that my thinking is correct

**Comment by bradzacher** [comment]
This is definitely a bug in the types `NewExpression` should accept the same argument type as `CallExpression`!

**Comment by burtek** [comment]
Working on it :)
