### ISSUE TITLE
Docs: Rule page links previews show the 🛑 warning

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5425]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Here is @JamesHenry posting https://typescript-eslint.io/rules/explicit-member-accessibility in Slack:

<img width="611" alt="@JamesHenry on Slack posting a link preview of https://typescript-eslint.io/rules/explicit-member-accessibility/, showing that it still shows the _This file is source code, not the primary documentation location!_ warning" src="https://user-images.githubusercontent.com/3335181/183143379-4325831a-047a-4163-b1c6-51acbebf8c32.png">

The notice was added to all rule docs file in #5249:

https://github.com/typescript-eslint/typescript-eslint/blob/d2394f810960fda07b9c8affd47b769d16f4b8cb/packages/eslint-plugin/docs/rules/explicit-member-accessibility.md?plain=1#L1

https://github.com/typescript-eslint/typescript-eslint/blob/d2394f810960fda07b9c8affd47b769d16f4b8cb/packages/website/docusaurusConfig.ts#L27

https://github.com/typescript-eslint/typescript-eslint/blob/ad412cdd74dc5619fbe4bf27c0a5eb5c5a4b65ca/packages/website/plugins/generated-rule-docs.ts#L20

Will moving this to `beforeDefaultRemarkPlugins` fix the preview? If not, is there anything we can do?

### Affected URL(s)

https://typescript-eslint.io/rules/*

**Comment by JoshuaKGoldberg** [comment]
https://github.com/typescript-eslint/typescript-eslint/pull/5426#issuecomment-1206778457: `beforeDefaultRemarkPlugins` isn't enough.

<img width="619" alt="Screenshot of https://deploy-preview-5426--typescript-eslint.netlify.app/rules/array-type as a link preview with the same notice" src="https://user-images.githubusercontent.com/3335181/183145058-8c3eb445-27c5-473c-a0c5-b25469f60c65.png">

cc @Josh-Cena, our favorite Docusaurus expert 😄 

(I haven't dug too deep yet)

**Comment by JoshuaKGoldberg** [comment]
Or, actually, maybe we don't know whether that's a fix? Please hold... https://github.com/typescript-eslint/typescript-eslint/pull/5427/files#r939236421

**Comment by Josh-Cena** [comment]
Are you okay with using an explicit [`description`](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#description) in front matter? You kind of have to do that anyway, since the rule description is now not in the Markdown source at all.

**Comment by JoshuaKGoldberg** [comment]
That does fix it, thanks! 🙌
