### ISSUE TITLE
Bug: [no-undef] 'WindowEventMap' is not defined

### ISSUE THREAD

**Issue by axelthat** [typescript-eslint/typescript-eslint#5430]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=C4TwDgpgBAogbhAdsAKuaBeKB1AlogEwHsB3eJYAWQEMwg&eslintrc=N4KABGBECmB2BukBcZQQpARgJwPYHcBnabZMAF2wFdoAacdGQgJgAZmBGMymhgX3oYADgENsxUikgABcgE8h0QgGNsASyHkAtEoA2a2OQD0o8SUiCo0AB7k4AE0JkA2gwx6D5JNmjLcAW38HaHsLNyghXSoAcwMkWQUlVQ1tD0MjHz9A4NCGAF1LSFMJAHlNNVxYJxQ0Rl9-EQA1EkIK2DJIXRE7QnIw9AixCQ6ExRV1TR1CfXTi80sMQlwqbGVoABVEjv9ceypdaEh+QsiYg2qwVwGZeTHkybS+-JA+IA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
type EventType = WindowEventMap
```

### ESLint Config

```javascript
module.exports = {
  env: {
    browser: true,
    es2021: true
  },
  globals: {
    defineProps: 'readonly',
    defineEmits: 'readonly',
    defineExpose: 'readonly',
    withDefaults: 'readonly'
  },
  extends: ['plugin:vue/vue3-essential', 'standard', 'eslint-config-prettier'],
  parser: 'vue-eslint-parser',
  parserOptions: {
    ecmaVersion: 'latest',
    parser: '@typescript-eslint/parser',
    sourceType: 'module'
  },
  plugins: ['vue', '@typescript-eslint'],
  rules: {
    'space-before-function-paren': 'off'
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "lib": ["ESNext", "DOM"],
    "skipLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"],
  "references": [
    {
      "path": "./tsconfig.node.json"
    }
  ]
}
```

### Expected Result

I expected eslint to recognize `WindowEventMap`.

### Actual Result

'WindowEventMap' is not defined

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.31.0` |
| `@typescript-eslint/parser`            | `5.31.0` |
| `TypeScript`                           | `4.6.4` |
| `ESLint`                               | `8.20.0` |
| `node`                                 | `16.16.0` |

**Comment by bradzacher** [comment]
You ticked that you read the FAQ, but there's an FAQ that addresses this problem.

https://typescript-eslint.io/docs/linting/troubleshooting/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
