### ISSUE TITLE
Repo: Stop testing on Node 12

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5438]
### Suggestion

https://github.com/typescript-eslint/typescript-eslint/blob/b9329980a67ed3b0acc96a4858e2fa8cae159f58/.github/workflows/ci.yml#L124 still tests on Node 12. Following #4465, I think we can remove those, no?

**Comment by bradzacher** [comment]
Yeah - it should be 14, not 12!

**Comment by m4thieulavoie** [comment]
As this issue is marked as `accepting prs`, I went ahead and [created a PR](https://github.com/typescript-eslint/typescript-eslint/pull/5512) for it 👍
