### ISSUE TITLE
Docs: Add guidance for third party ESLint plugins and type checking

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5444]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Forking from https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/812#issuecomment-1207694721: ESLint plugins want to be able to use type checking in their rules. For example, `eslint-plugin-jsx-a11y`'s `jsx-a11y/alt-text` wants to be able to determine whether a spread provides a prop such as `alt` to an image that would make it obviously inaccessible.

```tsx
// Is this statically known to be inaccessible?
// We need type information to know!
<img src="something.jpg" {...myProps} />
```

Copying https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/812#issuecomment-1207694217:

> A couple of implementation detail points that make being type-aware tricky:
>
> * If the rule uses the typescript-eslint tooling to be type-aware, it'll be locked into TypeScript (i.e. Flow and any future competitors won't work for its type checking)
> * In my (and other typescript-eslint maintainers') experience, it's generally confusing for users when rules provide different -even better!- results when the config changes to allow type checking
>
> Those concerns might be small and not more important than getting better info. Either way, this scenario is something we probably need to make explicit docs for on typescript-eslint.io.
>
> Out of curiosity @ljharb, have you seen other plugins add type-aware linting the way this issue is suggesting before?

Copying https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/812#issuecomment-1207694721:

> eslint-plugin-react and eslint-plugin-import have lots of examples to look at.
>
> The one trick tho will be that we'll probably need to add the infrastructure for testing with the TS parser.

---

We'll want to document, at the very least:

* Guidance for how to turn on typed linting for rules (explicit opt-in? implicit-if-parser-services-are-available?)
* How to set up tests, if not already covered in https://typescript-eslint.io/docs/development/custom-rules
* ...anything else useful?

I would mention other maintainers on those repos to ask for input too, but... @ljharb are you the only one? Are there other people we should loop in? 😂 

### Affected URL(s)

https://typescript-eslint.io/docs/development/custom-rules should probably link to this new page

Maybe https://typescript-eslint.io/docs/development/custom-plugins or some similar URL?

**Comment by joshwilsonvu** [comment]
I don’t use type-aware linting, but in maintaining [eslint-plugin-solid](https://github.com/joshwilsonvu/eslint-plugin-solid) I definitely appreciate being able to write fully-typed rules, especially for JSX in the AST. It’s surfaced a _lot_ of possible situations to handle and provided confidence that the finished rules can handle anything.

**Comment by bradzacher** [comment]
This way they can consume it if it's available without locking themselves into it.
If they use our [`getParserServices`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/utils/src/eslint-utils/getParserServices.ts) util then it'll throw if the code isn't parsed by our parser (which would lock them in).

The secret sauce for 3rd party plugins to consume type-info if it's available is to do a check like
```ts
if (context.parserServices?.hasFullTypeInformation === true) {
  // has type info
  const services = getParserServices(context);
}
```

**Comment by JoshuaKGoldberg** [comment]
We should also note to answer the question from this `#help` post in Discord: https://discord.com/channels/1026804805894672454/1112089535967412416

> one more thing: if I have an eslint config with overrides for *.ts files, and use a seperate parser there, is that parser considered a peer or normal dependency? what about typescript itself when you're using the type checking features?

...

> I ended up putting my config in a separate npm package and didn't put typescript as a dependency, and put the typescript-eslint parser as a peerdependency
> Is this a correct way of doing this?

Thanks @NanderTGA for asking!

**Comment by JoshuaKGoldberg** [comment]
> The secret sauce for them to consume type-info if it's available is to do a check like this:
>
> ```ts
> if (context.parserServices?.hasFullTypeInformation === true) {
> ```

Note that that's no longer the case in v6: https://github.com/typescript-eslint/typescript-eslint/issues/7124. Just checking whether `context?.parserServices.program` exists will check whether (a) you're using typescript-eslint and (b) it's got type information. We also recommend against "progressive enhancement" with rule type information: https://github.com/typescript-eslint/typescript-eslint/issues/7158.

**Comment by JoshuaKGoldberg** [comment]
Surfacing dicussion from a [Discord discussion on plugin dependencies](https://discord.com/channels/1026804805894672454/1133488751507669027), plugin packages should:

* have an explicit dependency on `@typescript-eslint/utils`:
	* it's runtime code
	* you'll ensure what version you run & test against
* have a peer dependency of `@typescript-eslint/parser`, `eslint`, and `typescript`
	* those are all packages consumers are expected to be using already
	* you still want to enforce the version range allowed without making the package manager install them
