### ISSUE TITLE
Rule proposal: type validation features like dtslint and tsd

### ISSUE THREAD

**Issue by xenoterracide** [typescript-eslint/typescript-eslint#5448]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I would like to have extensive type validation. To be honest reading dtslint and tsd documentation I don't believe even they could solve my issues, as they seem to be exclusively checking things like returns. I've added eslint-plugin-dtslint for some coverage. One problem I can see is that it probably has to use comments like dtslint to define how to validate which would be unusual.

### Fail Cases

```typescript
export function validateRequired<ERRORCODE extends string // @typescript-eslint valid no-implicit-generic true
, IN extends Input // @typescript-eslint valid no-implicit-generic false
, OUT extends IN & Input = IN>( // @typescript-eslint valid no-implicit-generic false
  v: IN | null | undefined,
  schema: Joi.AnySchema<OUT>,
  code: ERRORCODE,
  options?: Joi.ValidationOptions,
): OUT { // @typescript-eslint-type-check valid no-return any
  return v as OUT // just for example
}

validateRequired(1, Joi.any(), 'npe')
```

### Pass Cases

```typescript
export function validateRequired<ERRORCODE extends string // @typescript-eslint valid no-implicit-generic true *** I haven't actually figured out how to fix this atm
, IN extends Input // @typescript-eslint valid no-implicit-generic false
, OUT extends IN & Input = IN>( // @typescript-eslint valid no-implicit-generic false
  v: IN | null | undefined,
  schema: Joi.AnySchema<unknown>,
  code: ERRORCODE,
  options?: Joi.ValidationOptions,
): OUT { ): // @typescript-eslint-type-check valid no-return any

  return v as OUT // just for example
}

validateRequired<ErrorCode>(1, Joi.any(), 'npe')
```

### Additional Info

I think typescript eslint has the tools to do this, just needs implementing. I'm not qualified.

**Comment by xenoterracide** [comment]
I'm not sure I'm asking for a feature. I'm just trying to figure out how to achieve what I'm trying to do. Was hoping you might know.

I figured out the `any` problem, has something to do with The Joi schema, not giving that an argument makes it work correctly...

No luck so far though on finding a way to make the ErrorCodeKey some kind of partially validated generic. I've tried using some conditionals but so far no luck. I'm not very good with those yet. The other problem seeming to be that as soon as I pass a generic for ERRORCODE The IN generic is also required. Also that the error ERRORCODE generic is not required. Basically I'm trying to idiot proof this so the idiots can't type out and they can't bypass a real error code, and ideally they get code completion in their IDE.

**Comment by JoshuaKGoldberg** [comment]
One more project to add to your list: https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type 😄 

Agreed with bradzacher, this area is too new and unsettled for us to take it into typescript-eslint core. There are multiple projects out there that do things very differently. It's not yet clear what best way(s) will emerge.
