### ISSUE TITLE
Bug: [@typescript-eslint/quotes] Angular doesn't parse plain backticks in decorators

### ISSUE THREAD

**Issue by splincode** [typescript-eslint/typescript-eslint#5456]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=JYWwDg9gTgLgBAbzgYQBYEMB2BzApgEVxlwGMZgJMBlGKdY7ATwBoUJxLdMZWBJTMAFd4AXzgAzKOzgByAAJZsggDbooAehLRcMgNwAofXOTtImLjAAUCfXDgBnXMtIxoALlnowYALRSIMDLMtnDE4KrEHgAGADyoAIwAfAASTsoQcADq0MoAJjHqCYlRwXYkGDgERC4UmB5oilXEZLU0dAyMAHQA8pgACoL2qPoiAJT6uAAekLBwJKr29nBU7LgmHObciCFy-EJWMvYQglAkOqNwufToHva0wDgA2gC6cAC8cC8GIvpAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQI6wHsAXFdKAgMwsgBpxtIABIgTwAcUBjaASzaIC0KeDwB2RAPT5ipDAG1IiaNALRaUAEYBDTgGsiPPZAC69AL4gzQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUjoAHoizJ46IngCGqACL9YmNXl3Cwo9FIC+IM0A

### Repro Code

```typescript
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `<h1>Hello World</h1>`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SomeComponent {
  @Input('source') data: string[] = [];
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "quotes": "off",
    "@typescript-eslint/quotes": ["error", "backtick"]
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true,
    "experimentalDecorators": true
  }
}
```

### Expected Result

should not replace with backtick in decorators

```ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `<h1>Hello World</h1>`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SomeComponent {
  @Input('source') data: string[] = [];
}
```

### Actual Result

<img width="698" alt="image" src="https://user-images.githubusercontent.com/12021443/183879166-36bb2ca9-8a28-42cb-a1fd-0f89ab329111.png">

### Additional Info

https://youtrack.jetbrains.com/issue/WEB-56900/Angular-doesnt-parse-plain-backticks-in-decorators

Angular doesn't parse plain backticks in decorators

What steps will reproduce the issue?
1. Create a component or a directive and use backticks in selector/templateUrl
2. Write template or use that directive anywhere
What is the expected result?

It should work correctly

What happens instead?

Template does not recognize class properties, directive is not recognized by selector.

Note

Doing any change to class code makes it work but it randomly breaks again when you relaunch WebStorm. We try to use backticks everywhere for uniformity, here's our rather big repository where you can reproduce it:

https://github.com/Tinkoff/taiga-ui

Looks similar to this, which is marked fixed :

https://youtrack.jetbrains.com/issue/WEB-25943/Angular2-cant-navigate-to-declaration-from-attribute-if-its-name-doesnt-immediately-follow-opening-quote-in-selector-value

I'm using latest WebStorm 2022.2 Build #WS-222.3345.108

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.33.0` |
| `@typescript-eslint/parser`            | `5.33.0` |
| `TypeScript`                           | `4.3` |
| `ESLint`                               | `8.0` |
| `node`                                 | `16.6` |

**Comment by bradzacher** [comment]
We don't encode framework specific semantics into our tooling.

If angular requires nornal strings there then that's a lapse in their tooling.
Feel free to follow up with them on that to improve the entire angular ecosystem.

Otherwise - perhaps the @angular-eslint project can encode framework semantics in an extension rule there.
