### ISSUE TITLE
error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.

### ISSUE THREAD

**Issue by wqcstrong** [typescript-eslint/typescript-eslint#5457]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.

### Playground Link

/

### Repro Code

https://github.com/wqcstrong/eslint-config-typescript/tree/eslint%408

### ESLint Config

```javascript
const defaultRules = require('./default-rules');
const tsLintRules = require('./tslint');

module.exports = {
  env: {
    browser: true,
    node: true,
    es6: true,
    commonjs: true,
    mocha: true,
    jest: true
  },
  extends: ['airbnb-base', 'prettier', 'plugin:@typescript-eslint/recommended'],
  parser: '@typescript-eslint/parser',
  ignorePatterns: ['.eslintrc.js', '*.config.[jt]s'],
  parserOptions: {
    ecmaFeatures: {
      jsx: true
    },
    ecmaVersion: 'latest',
    sourceType: 'module',
    project: ['tsconfig.json']
  },
  plugins: ['eslint-comments', 'jest', 'import'],
  rules: {
    ...defaultRules,
    ...tsLintRules
  }
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "baseUrl": ".",
    "allowJs": true,
    "module": "ESNext",
    "moduleResolution": "node",
    "lib": [
      "esnext",
      "dom"
    ],
    "noEmit": true
  },
  "include": [
    "example"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

### Expected Result

All files will be parsed and lint if matched~

In my repo case, the lint target director is `example` and I include it in `include` field which is in `tsconfig.json`.

```
// target directory structure
example
├── test.js
└── test.ts
```

But there would occur error info about `test.js`. The error information:

```
0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: example/test.js.
The file must be included in at least one of the projects provided
```

I have tried to change the `include` config as following, the error still be there.

```js
// 1. Error about js file
{
  ...,
  "include": ["example"]
}


// 2. Error about js file
{
  ...,
  "include": [
    "example/test.ts",
    "example/test.js"
  ]
}


// 3. Error about js file
{
  ...,
  "include": ["example/*"]
}
```

### Actual Result

`.js` file cannot be matched and lint.

### Additional Info

Reproduction steps:

```bash
$ git clone git@github.com:wqcstrong/eslint-config-typescript.git

$ git checkout eslint@8

$ yarn install && yarn test
```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.32.0` |
| `@typescript-eslint/parser`            | `5.32.0` |
| `TypeScript`                           | `4.7.4` |
| `ESLint`                               | `8.21.0` |
| `node`                                 | `16.13.0` |

**Comment by JoshuaKGoldberg** [comment]
Hi @wqcstrong, thanks for filing a detailed issue! That repo has both [`example/test.js`]() and [`example/test.ts`](). Two files with the same name but one is `.ts` and the other `.js`. If you rename `example/test.ts` to some other name then there are no more issues.

```plaintext
% mv example/test.ts example/test2.ts
% yarn test
yarn run v1.22.15
$ eslint --ext .js,.ts ./example

/Users/josh/repos/eslint-config-typescript/example/test.js
  ...

/Users/josh/repos/eslint-config-typescript/example/test2.ts
   ...

✖ 13 problems (0 errors, 13 warnings)
```

The root of the issue is that TypeScript just sees `example/test.ts`, and intentionally won't see a `.js` file alongside it. A `.js` file with the same name as a sibling `.ts` file is intentionally ignored. https://stackoverflow.com/questions/58160910/same-file-name-in-typescript-files-and-javascript-files

**Comment by bradzacher** [comment]
This is also mentioned in our docs

https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/parser#parseroptionsproject

> TypeScript will ignore files with duplicate filenames in the same folder (for example, src/file.ts and src/file.js). TypeScript purposely ignore all but one of the files, only keeping the one file with the highest priority extension

#955

**Comment by wqcstrong** [comment]
Thanks for your answers @JoshuaKGoldberg @bradzacher

**Comment by 2531800823** [comment]
> This is also mentioned in our docs
> 
> 我们的文件中也提到了这一点
> 
> https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/parser#parseroptionsproject
> 
> > TypeScript will ignore files with duplicate filenames in the same folder (for example, src/file.ts and src/file.js). TypeScript purposely ignore all but one of the files, only keeping the one file with the highest priority extensionTypeScript 将忽略同一文件夹中具有重复文件名的文件(例如，src/file.ts 和 src/file.js)。TypeScript 故意忽略除一个文件以外的所有文件，只保留具有最高优先级扩展名的一个文件
> 
> [#955 955英镑](https://github.com/typescript-eslint/typescript-eslint/issues/955)

Parsing error: Circularity detected while resolving configuration
JSON schema for the TypeScript compiler's configuration file

JSON schema for the TypeScript compiler's configuration file
