### ISSUE TITLE
Docs: add redirects for removed pages

### ISSUE THREAD

**Issue by Josh-Cena** [typescript-eslint/typescript-eslint#5465]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

When you search for "tslint", the first result takes you to https://typescript-eslint.io/docs/linting/tslint/:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/55398995/184279097-d134937d-99e5-4e8a-a791-477387c2166e.png">

That is unfortunately 404. We need to add a redirect.

### Affected URL(s)

https://typescript-eslint.io/docs/linting/tslint/
https://typescript-eslint.io/docs/linting/troubleshooting/tslint

**Comment by bradzacher** [comment]
Is this just an indexing thing with algolia?
We are still on the old infra (https://github.com/typescript-eslint/typescript-eslint/issues/5008)

**Comment by Josh-Cena** [comment]
Possibly, but we _should_ add redirects for all removed pages anyway.

**Comment by JoshuaKGoldberg** [comment]
Accepting PR to add redirects for removed pages. +1!
