### ISSUE TITLE
Enhancement: explicit-function-return-type - Add fixer to populate missing return types on functions

### ISSUE THREAD

**Issue by KristofferHenriksson** [typescript-eslint/typescript-eslint#5470]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/explicit-function-return-type

### Description

There is currently no fixer for the rule explicit-function-return-type. It would be great to have this functionality to give a head start on fixing missing return values.

### Fail

```typescript
function foo() {
}
```

### Pass

```typescript
function foo(): void {
}
```

**Comment by bradzacher** [comment]
Thanks for the request.

This has been asked before - we won't be adding a fixer.

- A fixer would require type information (which is a breaking change).
- The rule is about enforcing you declare strict contracts on your functions - automatically adding return types means you just get whatever return type is inferred - which is no better than having no return type in many cases.
- Our tooling cannot detect which named types should be used - meaning object types will be the raw object type or union types will be the raw unions.

If someone wants to build a codemod that people can run once to add return types to their codebase - they're free to, but we won't be adding a fixer.
