### ISSUE TITLE
[indent] Multiline class members with linebreak right after `=`

### ISSUE THREAD

**Issue by Philipp91** [typescript-eslint/typescript-eslint#549]
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/indent": "error",
  }
}
```

```TS
class Test {
    public test =
        'test';
}
```

**Expected Result**

No warning. This is what the auto-formatter does, this is also what I consider to look reasonable.

**Actual Result**

`error  Expected indentation of 4 spaces but found 8` on the `'test'` line, and auto-fix to:

```TS
class Test {
    public test =
    'test';
}
```

**Additional Info**

```
  eslint:linter Linting code for ......ts (pass 1) +0ms
  eslint:traverser Unknown node type "ClassProperty": Estimated visitor keys ["type","key","value","computed","static","readonly","range","loc","accessibility"] +0ms
  eslint:linter Generating fixed text for ......ts (pass 1) +29s
  eslint:source-code-fixer Applying fixes +0ms
  eslint:source-code-fixer shouldFix parameter was false, not attempting fixes +0ms
```

The problem does **not** occur if there is no line-break after the `=` operator, or outside of class properties:

```TS
class Test {
    public test = 'test' +
        'test';
}
const test =
    'test';
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.9.0` |
| `@typescript-eslint/parser`        | `1.9.0` |
| `TypeScript`                       | `3.4.5` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `8.11.3` |
| `npm`                              | `6.9.0` |

**Comment by Philipp91** [comment]
The error message says that the `ClassProperty` node type is not known. In the [code ](https://github.com/typescript-eslint/typescript-eslint/blame/master/packages/eslint-plugin/src/rules/indent.ts#L18-L19) it's listed as `KNOWN_NODES` with the remark that `eslint` doesn't support it.

I couldn't find an upstream tracking bug at `eslint` or `babel-eslint` (I'm using version `10.0.1`).

When I remove the `public` keyword, my repro example becomes valid JavaScript, and the non-TS `eslint`  does not complain on the code, though it seems to allow any arbitrary indentation in that position, which seems to be tracked in https://github.com/babel/babel-eslint/issues/598.

**Comment by bradzacher** [comment]
Merging into #1824
