### ISSUE TITLE
Bug: [strict-boolean-expressions] Only the first operand in a chain of `&&` is checked

### ISSUE THREAD

**Issue by phaux** [typescript-eslint/typescript-eslint#5518]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.4&sourceType=module&code=PQKgBApgzgNglgOwC5gAJIJ4AdoGMBOcWSAtNPMsFEobqQEYD2jMEAhgmQB5b7RRxGCKAC4wAbQj58jfABowAbzBsYMRgHcAcgFcAtvSliAZqqgQwAXwC6YEMABQD4MDABGSNNkLGAawVwxmA65gAmYIhgAFIAygAaYLiMOjDhfAihUmAADA7ZYABkBUqWANxOLu6eMvhg9DooUAAWyal1FgBMCoa4bCEWxnD41GAdYIw4+ByhUCp8YABESRlwSILCCw4eRaOFxYplFa4eUjV1DWDNreGGYADMW3u7O3dPB+XOrmOnsrP1jS0UjcLAAWBwACg8AB8oaMAJRPcGvGFgEEInbvI5VH7yca+AD8ESQswgAEcdHAAG6qCDIMBIRgqelSBBsfAYR4YyxgFEIFIwD6Vf70ppwWZihAAchQ03GCBgGGxXlqwquQPao05xXyvP5gq+1V+PgJkHJVJpdIZESCEBg5mtkDtEAh232lgRKPBYx24msHthfLU+suazUuxxfwuaratzBkKe2X9YC9CaTgYFTiAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
/* eslint @typescript-eslint/strict-boolean-expressions: [error, { allowNumber: false }] */

// 1 error, ok, if used in JSX could render 0
0 && {};

// 1 error but should be 2, because first 2 operands are "conditions"
1 && 2 && {};

// 1 error but should be 3
1 && 2 && 3 && {};

// 2 errors but should be 4
(1 || 2) && (3 || 4) && {};

// 1 error, ok? its equivalent to a ternary
1 && {} || null;

// but this isn't and only 1 error but should be 2
1 && 0 || null;

// 2 errors, ok? equivalent to if else if else
(1 && {}) || (2 && []) || null;

// still 2 errors but should be 4
(1 && 0) || (2 && 0) || null;
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/strict-boolean-expressions": ["error", { "allowNumber" : false }],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strict": true
  }
}
```

### Expected Result

I'm not even sure what the correct behavior should be here.
I think when given a chain of `&&` or `||`, all the operands should be checked except the last one.
If somebody used `cond && valIfTrue || valIfFalse` instead of ternary it would be a breaking change for them.

### Actual Result

It checks only the first operand in a chain.
It was implemented that way to allow `cond && doIfTrue() || doIfFalse()` but its flawed and shouldn't be used after all.

### Additional Info

I can send a PR

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.20.0` |
| `@typescript-eslint/parser`            | `5.20.0` |
| `TypeScript`                           | `4.6.3` |
| `ESLint`                               | `8.11.0` |
| `node`                                 | `16.14.0` |

**Comment by JoshuaKGoldberg** [comment]
@phaux I'm not sure I follow exactly what the issue is. There's a lot going on there - is the crux that there might be violations of the rule _at each point_ in the chain, but none after the first are checked?

```ts
/* eslint @typescript-eslint/strict-boolean-expressions: [error, { allowNumber: false }] */

declare const maybeDefined: string[] | undefined;
maybeDefined && 0 && {};
//              ~
// Should error here, but doesn't
```

**Comment by phaux** [comment]
Here's a more realistic example:

```tsx
interface UserProfileProps {
  name?: string
  age?: number
  favFood?: string[]
}

function UserProfile(props: UserProfileProps) {
  const { name, age, favFood } = props

  return ( 
    <div>
      {
        name // error: unexpected nullable string in a conditional
        && age // no error 
        && favFood // no error
        && favFood.length // no error
        && (
          <div>
            <p>Name: {name}</p>
            <p>Age: {age}</p>
            <p>Fav foods: {favFood.join(", ")}</p>
          </div>
        )
      }
    </div>
  )
}
```

but with a ternary:

```tsx
function UserProfile(props: UserProfileProps) {
  const { name, age, favFood } = props

  return ( 
    <div>
      {
        name // error: unexpected nullable string in a conditional
        && age // error: unexpected nullable number in a conditional
        && favFood // error: unexpected nullable object in a conditional
        && favFood.length // error: unexpected number in a conditional
        ? (
          <div>
            <p>Name: {name}</p>
            <p>Age: {age}</p>
            <p>Fav foods: {favFood.join(", ")}</p>
          </div>
        )
        : null
      }
    </div>
  )
}
```
```

**Comment by JoshuaKGoldberg** [comment]
Got it, thanks for the context! Accepting PRs to make the rule check all operands in a chain of `&&`s.

Note that this shouldn't change the rule's core logic around what conditionals it considers ok or not. We're just filling in coverage for which conditionals it looks at.
