### ISSUE TITLE
Please update your documentation of typescript-eslint so I know how to install it.

### ISSUE THREAD

**Issue by FranzWegener** [typescript-eslint/typescript-eslint#552]
**What did you expect to happen?**
I expected to find instructions on how to install your typescript-eslint in the readme.md,
I've tried `npm i typescript-eslint`, but to no avail.
I've also done `npm install @typescript-eslint/parser --save-dev` which didn't install a linter either. I really do not understand how to install your project.

**What actually happened?**
nothing

**Versions**
the current latest 2019-05-24

**Comment by bradzacher** [comment]
What project are you looking to install?
There are three that you might be interested in. Each of them has their own documentation on how to install it.

- the parser (https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#installation)
- the eslint plugin with typescript rules (https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#installation)
- the eslint plugin which runs tslint (https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin-tslint#installation)

If anything is unclear to you, please feel free to comment back.

**Comment by tieTYT** [comment]
I would suggest the section in the main readme that explains which one of these tools I should be installing depending on the situation. I'm looking at these 3 links and I can't tell if I should be installing all 3, 2 of them, or one of them. I think there should be a section in the readme that says, "If you're doing X, install Y, if you're doing..."

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/tree/master/docs/getting-started

**Comment by tieTYT** [comment]
That's helpful. I think my eyes glossed right over that. Can I suggest that the title of that section is called "Getting started/Installation"? I was skimming every part of the readme looking for the word "Installation" or some npm commands.

**Comment by bradzacher** [comment]
happy to accept a PR
