### ISSUE TITLE
Website: Allow resizing/collapsing panes

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5536]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Sometimes it'd be useful to expand or collapse different sections of the playground, such as needing to expand the code section a bit horizontally to read a long comment in full. I wish you could drag-and-drop the three vertical sections (panes) to resize them.

### Affected URL(s)

https://typescript-eslint.io/play/

**Comment by santoshyadavdev** [comment]
I will take this.

**Comment by jimsu2012** [comment]
@santoshyadavdev Are you still working on this? If not, I'm happy to take.

**Comment by jimsu2012** [comment]
Thanks!
