### ISSUE TITLE
Repo: drop dependency on tsutils

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#5552]
### Suggestion

[tsutils](https://github.com/ajafff/tsutils) hasn't had a release (or even a commit) in well over a year (march 2021).

It seems like it's a dead package at this point, sadly - there are a number of issues going unanswered and PRs unreviewed. I guess that the owner has moved on to other things, and unfortunately they were the single point of failure.

This hasn't been a problem thus far, but with TS4.8 one of the types is now wrong and required a local patch to work around (#5551).
There are also some known issues caused by the package, which we cannot address without upstream patches (#5458, #3405).

I see three paths forward:
1) fork the package and release it under our namespace.
1) attempt to take ownership of the package and updated it.
1) bring the relevant utils internal into our `type-utils` package and drop the dependency.

(1) really conflicts with our `type-utils` package, so it seems immediately dead in the water.
(2) could work, but I personally don't have time to maintain it as a separate project - so we'd be relying on someone else for it (which doesn't really change our predicament - just shifts it). Also it would rely on the current owner being responsive or would rely on npm support passing ownership (which takes time).

IMO just dropping the dependency entirely and bringing the relevant utils into our `type-utils` package is the best course of action as it allows us to control the code that we so heavily rely on, which makes it easier for us to maintain everything. Given that we publish them as a package, the open-source community still benefits from our maintained versions.

**Comment by JoshuaKGoldberg** [comment]
I'd actually be interested in taking on tsutils - it's a pretty useful package and I use it in TypeStat. I've tried emailing the maintainer before but haven't heard from them in a bit. Regardless of what we decide here, I'll try to get that conversation started...

**Comment by bradzacher** [comment]
If you can get yourself added as a maintainer with full privileges so you needn't depend on the current owner, then that would work great! I'm confident you'll be sticking around for the forseeable future.

---

In case we do want to drop it as a dep, these are the functions that we use from the package:

- getWellKnownSymbolPropertyOfType
- hasModifier
- isAssignmentKind
- isBinaryExpression
- isBooleanLiteralType
- isCallExpression
- isCompilerOptionEnabled
- isConditionalType
- isIdentifier
- isIntersectionType
- isJsxExpression
- isModifierFlagSet
- isNewExpression
- isObjectFlagSet
- isObjectType
- isParameterDeclaration
- isPropertyAssignment
- isPropertyDeclaration
- isPropertyReadonlyInType
- isStrictCompilerOptionEnabled
- isSymbolFlagSet
- isThenableType
- isTypeFlagSet
- isTypeReference
- isUnionOrIntersectionType
- isUnionType
- isValidPropertyAccess
- isVariableDeclaration
- unionTypeParts

A lot of these are pretty light-weight, small functions so there's nothing major or complicated that we depend on.

**Comment by aaditmshah** [comment]
Hey folks, I'm also facing the #3405 issue in my project. I'm glad to see that you're working towards resolving the tsutils issue. Thank you so much. I know it's not much but if you need any help then I'll be glad to do so. I have the bandwidth to work on other projects right now. However, it'll take me a while to get up to speed.

**Comment by varwasabi** [comment]
> If you can get yourself added as a maintainer with full privileges so you needn't depend on the current owner, then that would work great! I'm confident you'll be sticking around for the forseeable future.
> 
> In case we do want to drop it as a dep, these are the functions that we use from the package:
> 
> * getWellKnownSymbolPropertyOfType
> * hasModifier
> * isAssignmentKind
> * isBinaryExpression
> * isBooleanLiteralType
> * isCallExpression
> * isCompilerOptionEnabled
> * isConditionalType
> * isIdentifier
> * isIntersectionType
> * isJsxExpression
> * isModifierFlagSet
> * isNewExpression
> * isObjectFlagSet
> * isObjectType
> * isParameterDeclaration
> * isPropertyAssignment
> * isPropertyDeclaration
> * isPropertyReadonlyInType
> * isStrictCompilerOptionEnabled
> * isSymbolFlagSet
> * isThenableType
> * isTypeFlagSet
> * isTypeReference
> * isUnionOrIntersectionType
> * isUnionType
> * isValidPropertyAccess
> * isVariableDeclaration
> * unionTypeParts
> 
> A lot of these are pretty light-weight, small functions so there's nothing major or complicated that we depend on.

I'll open a PR that has the `tsutils` functions listed added to `eslint-plugin/src/util` and remove the `tsutils` as a project dependency.

**Comment by JoshuaKGoldberg** [comment]
Bringin in my comment in https://github.com/typescript-eslint/typescript-eslint/pull/5689#issuecomment-1418430437 here: I ended up forking `tsutils` into [`ts-api-tools`](https://github.com/JoshuaKGoldberg/ts-api-tools). Hence #6428.

**Comment by JoshuaKGoldberg** [comment]
#6428 was merged into the `v6` branch (PR: #5886) and so will be released as part of our v6 major version. Cheers!
