### ISSUE TITLE
Website: Consider always expanding collapsible sidebar menus under docs/

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5554]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Right now, _Type Information_, _Troubleshooting and FAQs_, and _Architecture_ default to collapsed state on typescript-eslint.io/docs. That means their children are hidden.

<img width="306" alt="Screenshot of typescript-eslint.io sidebar menu with collapsed Linting with Type Information, Troubleshooting and FAQs, and Architecture" src="https://user-images.githubusercontent.com/3335181/186995450-f736b9d7-65dd-4698-a7ca-9f231a820e5a.png">

Hiding the children means people have to click through pages to discover that the exist. In retrospect I think hiding them might have been a negative for discoverability...?

### Affected URL(s)

https://typescript-eslint.io/docs/*

**Comment by santoshyadavdev** [comment]
I will take this
