### ISSUE TITLE
Enhancement: CLI to fix typescript dependencies to match compatibilities with @typescript-eslint/* packages 

### ISSUE THREAD

**Issue by martin-braun** [typescript-eslint/typescript-eslint#5555]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-estree

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I maintain a template that uses typescript and @typescript-eslint/\* packages. Every now and then, I decide to rise all package versions using `npx npm-check-updates -u && npx shx rm -r node_modules package-lock.json && npm i`.

This causes me to do a lot of testing, as things can change. This is fine. Obviously, I now get a warning when I build: 

> WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
> 
> You may find that it works just fine, or you may not.
> 
> SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.8.0
> 
> YOUR TYPESCRIPT VERSION: 4.8.2
> 
> Please only submit bug reports when using the officially supported version.

Sure, I can downgrade typescript manually now, but I wonder if there is a way to fix those dependencies using a command to further automate the process.

I think it would be nice if there was a CLI util that could be installed to automatically fix those dependencies, so they stay in line when upgrading everything.

**Comment by bradzacher** [comment]
Thanks for the request.

Ultimately I'm not sure that it makes sense for us to build and maintain a CLI for this.

- In general we only lag behind the TS release by a few days to a week - so the problem is short-lived.
- TS releases once per quarter - so this problem really only arises at most 4 times a year.
- When it does arise, downgrading only takes a single command:
    ```
    npm i typescript@"<4.8.0"
    ```

Given that this is a community maintained project, and the core maintainers are volunteers - to me it seems like the small and short-lived benefits don't outweigh the cost of building, maintaining and releasing a CLI.

**Comment by martin-braun** [comment]
@bradzacher Thanks for looking into the issue. I do understand that this issue is minimal and that it is not cost-effective to maintain a CLI for that. Is there an exported function from any of the packages that would help me to retrieve the supported TS version, so that I can at least write a script on my own?
