### ISSUE TITLE
Rule proposal: keep typeversion in sync

### ISSUE THREAD

**Issue by jantimon** [typescript-eslint/typescript-eslint#5570]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

`Node.Js` 12 introduced [`exports` for `package.json`](https://nodejs.org/api/packages.html#packages_package_entry_points).

For example your ui module might export several ui patterns:

```json
{
  "name": "@foo/ui"
  "exports": {
      "./button": "./dist/src/components/button.js",
      "./input": "./dist/src/components/input.js"
   }
}
```

Which would allow to write the following imports:

```js
import Button from "@foo/ui/button"
import Input from "@foo/ui/input"
```

Typescript introduced `typesVersions` which can be used to tell typescript how to resolve these imports:

```json
{
  "name": "@foo/ui"
  "exports": {
      "./button": "./dist/src/components/button.js",
      "./input": "./dist/src/components/input.js"
   },
  "typesVersions": {
      "*": {
        "button": ["/dist/src/components/button.d.ts"],
        "input": ["/dist/src/components/input.d.js"],
      }
   }
}
```

Dr. Axel Rauschmayer wrote a great summary about that topic:   
https://2ality.com/2021/06/typescript-esm-nodejs.html#package-exports%3A-hiding-package-internals-and-providing-nicer-module-specifiers

It would be great to introduce linting rules to keep `exports` and `typesVersion` in sync.

### Fail Cases

```typescript
"exports": {
      "./button": "./dist/src/components/button.js",
      "./input": "./dist/src/components/input.js"
   },
  "typesVersions": {
      "*": {
        "button": ["/dist/src/components/button.d.ts"]
      }
   }
```

### Pass Cases

```typescript
"exports": {
      "./button": "./dist/src/components/button.js",
      "./input": "./dist/src/components/input.js"
   },
  "typesVersions": {
      "*": {
        "button": ["/dist/src/components/button.d.ts"],
        "input": ["/dist/src/components/input.d.js"],
      }
   }
```

**Comment by bradzacher** [comment]
I'm not too familiar with the ins-and-outs of it yet - but do you need an *explicit* `typesVersions` if the `.d.ts` file is alongside the `.js` file?

Also it seems to me like this would be a pretty constant thing for most projects - that they wouldn't really change too often, right?

---

I don't think this is a good idea for us to attempt within this project because parsing and linting JSON is its own beast, to say the least.
Because JSON is valid TS, we could not use our parser - we would need special infrastructure to make it work.

Which is why right now I'd say that if the package.json is pretty static, the value is probably far outweighed by the cost to build and maintain it.

**Comment by JoshuaKGoldberg** [comment]
Ping @jantimon - I'm going to close this issue now as it's been >1.5 months without comment. But please do post back if you have more info & think we should reopen. Cheers!
