### ISSUE TITLE
Bug: [no-unused-vars] 'Component' is defined but never used

### ISSUE THREAD

**Issue by muuvmuuv** [typescript-eslint/typescript-eslint#5571]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

does not work

### Repro Code

```typescript
import { Component } from '@angular/core'

@Component({
  selector: 'app-root',
  template: '',
})
export class AppComponent {}
```

### ESLint Config

```javascript
{
  "root": true,
  "overrides": [
    // ....
    {
      "files": ["*.ts"],
      "parser": "@typescript-eslint/parser",
      "plugins": ["tsdoc", "@typescript-eslint"],
      "extends": [
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:@typescript-eslint/strict"
      ],
      "parserOptions": {
        "project": ["tsconfig.lint.json"]
      },
      "rules": {
        "tsdoc/syntax": "error"
      }
    },
    {
      "files": ["src/**/*.ts"],
      "env": {
        "node": false,
        "browser": true
      },
      "extends": [
        "plugin:compat/recommended",
        "plugin:@angular-eslint/recommended",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],
      "parserOptions": {
        "project": ["tsconfig.lint.json"]
      },
      "rules": {
        "no-alert": "error",
        "no-debugger": "error",
        "no-console": "error",
        "@angular-eslint/component-class-suffix": [
          "error",
          {
            "suffixes": ["Page", "Component"]
          }
        ],
        "@typescript-eslint/explicit-module-boundary-types": [
          "off",
          {
            "allowHigherOrderFunctions": true
          }
        ]
      }
    },
    {
      "files": ["*.js", "*.mjs", "*.ts", "*.mts", "*.html"],
      "extends": ["prettier"]
    }
  ]
}
```

### tsconfig

```jsonc
{
  "$schema": "http://json.schemastore.org/tsconfig",
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "./dist/out-tsc",
    "strict": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitOverride": true,
    // "noPropertyAccessFromIndexSignature": true,
    "noFallthroughCasesInSwitch": true,
    "forceConsistentCasingInFileNames": true,
    "strictPropertyInitialization": true,
    "strictNullChecks": true,
    "esModuleInterop": true,
    "downlevelIteration": true,
    "sourceMap": true,
    "declaration": false,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2020",
    "module": "ESNext",
    "lib": ["ESNext", "DOM"]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

### Expected Result

Recognise imported "Component" as "experimentalDecorators".

### Actual Result

'Component' is defined but never used.eslint[@typescript-eslint/no-unused-vars](https://typescript-eslint.io/rules/no-unused-vars)

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `^5.36.0` |
| `@typescript-eslint/parser`            | `^5.36.0` |
| `TypeScript`                           | `<4.8.0` |
| `ESLint`                               | `^8.23.0` |
| `node`                                 | `17` |

**Comment by stefnedelchev** [comment]
I also confirm the issue. After updating to `5.36.1` I started experiencing it so I had to revert back to `5.35`

**Comment by rbargholz** [comment]
Also have this problem, pinning our dependency at 5.35.1 worked for our team for now.

**Comment by bradzacher** [comment]
As per our [contributing guide](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md#commenting) - please don't comment in the form of "+1" or "I also have this issue".

**Comment by bradzacher** [comment]
It looks like we introduced a regression with exported decorators and <4.8

**Comment by pgrivachev** [comment]
I have the similar issue. Here is my example:
A.ts:
```
export interface A {
  name: string;
}
```
B.ts:
```
import { A } from './A';

export class B {
  a?: A;
  static {}
}
```
@typescript-eslint/eslint-plugin: ^5.36.0
@typescript-eslint/parser: ^5.36.0
The error is:
```
  1:10  error  'A' is defined but never used  @typescript-eslint/no-unused-vars
```
If I remove the static block, then everything works correctly.

**Comment by BryanHunt** [comment]
I'm having this problem with `5.36.0` and typescript `4.8.2`

**Comment by bradzacher** [comment]
locking because we have a fix and no additional info is needed

**Comment by bradzacher** [comment]
Fix has been released as https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.36.1
