### ISSUE TITLE
Repo: add e2e test(s) for the website playground

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#5579]
### Suggestion

Reference: #5572

#5551 introduced a breakage into the website playground.
We don't have checks for this, so we didn't discover this until a few days after it had been merged and released.

The playground is the only part of the website that can easily and silently break due to dependency changes or changes in our packages because all the code is lazy-loaded.
It's too cumbersome to expect every relevant change to be manually tested against the website - so we should have automated testing to ensure that the page works correctly.

The MVP for this would be a test that ensures the playground can load without issue. Given the architecture this will likely need to be some form of webdriver (or whatever the best framework is) based e2e browser test, but we'd be more than open to some other solution if there's a better way to do it (even if it means some re-architecting of the tooling).

Full coverage would include a test that is an e2e browser test that enters code and config into the playground and asserts that the errors are shown.

**Comment by santoshyadavdev** [comment]
As we are using NX, are you open to try cypress? I can do the initial PR to setup the cypress and run the tests on CI and local,

**Comment by JoshuaKGoldberg** [comment]
#4362 - we already have Cypress set up 🙂

**Comment by bradzacher** [comment]
Though, it is super flaky in the CI.
We're not sure why.

Right now we don't really pay attention to that signal cos it's often wrong.

**Comment by JoshuaKGoldberg** [comment]
Aside: we've since switched to Playwright, because we couldn't get Cypress to stop being flaky in CI. #5814

**Comment by JoshuaKGoldberg** [comment]
My current plan is to do them on my [10:30am EST Twitch stream on November 24th](https://www.twitch.tv/joshuakgoldberg/schedule?seriesID=c53bbfdd-92bd-487b-bb14-1ffc5965c191). 🙌

**Comment by JoshuaKGoldberg** [comment]
> Enabling the AST viewer to inspect its ESTree and TypeScript ASTs

oh oop I never added this... next!
