### ISSUE TITLE
[typedef] What is ETA of the typedef rule?

### ISSUE THREAD

**Issue by takuma7** [typescript-eslint/typescript-eslint#558]
I'm thinking of migrating from TSLint to ESLint. Reading the [roadmap](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md), I realized the [`typedef`](https://palantir.github.io/tslint/rules/typedef/
) rule is still "unimplemented".

Is there any plan to implement this rule? If yes, do we have any ETA?

Thank you!

**Comment by bradzacher** [comment]
If I'm understanding that rule, then it looks like it can be "implemented" as follows:

- turn on `noImplicitAny` in your tsconfig.
- turn on our rule `@typescript-eslint/explicit-function-return-type`.

**Comment by gruckion** [comment]
@bradzacher a follow up to the above reference, we are using the suggested and it appears to cover our use case.

**Comment by bradzacher** [comment]
As an FYI there is an open PR to add the typedef rule (#581).
It is under discussion though.
