### ISSUE TITLE
Bug: decorators get duplicated in AST for parameter properties

### ISSUE THREAD

**Issue by fisker** [typescript-eslint/typescript-eslint#5581]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Relevant Package

parser

### Playground Link

https://typescript-eslint.io/play/#ts=4.8.2&sourceType=module&showAST=es&code=MYGwhgzhAECC0G9pgBQAEAm0AOAnAlgG5gAuAptAB4Bc0AdgK4C2ARmbgJSLQC+vQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
> parse = require("@typescript-eslint/typescript-estree").parse
[Function: parse]
> ast = parse('class A {a (@d private x: number) {}}')
{
  type: 'Program',
  body: [
    {
      type: 'ClassDeclaration',
      id: [Object],
      body: [Object],
      superClass: null
    }
  ],
  sourceType: 'script'
}
> ast.body[0].body.body[0].value.params[0].decorators[0]
{ type: 'Decorator', expression: { type: 'Identifier', name: 'd' } }
> ast.body[0].body.body[0].value.params[0].parameter.decorators[0]
{ type: 'Decorator', expression: { type: 'Identifier', name: 'd' } }
```

### ESLint Config

```javascript
N/A
```

### tsconfig

```jsonc
N/A
```

### Expected Result

Not duplicate the decorator

### Actual Result

the decorator get duplicate 

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/parser`            | `5.36.1` |
| `node`                                 | `18.8.0` |

**Comment by bradzacher** [comment]
I believe that this specific code isn't required.

https://github.com/typescript-eslint/typescript-eslint/blob/f7c5deb2328279b4b988d072aca9110bacf56514/packages/typescript-estree/src/convert.ts#L1672-L1675

This block was added in #5551 (https://github.com/typescript-eslint/typescript-eslint/pull/5551/files#diff-341d9ffb40c62139c7da69b49d5081cbce7eabce79b58fe569de987a91e63c14R1676-R1679)
