### ISSUE TITLE
Docs: [strict-boolean-expressions] nullable number as wrong 'undefined' type

### ISSUE THREAD

**Issue by Luk-z** [typescript-eslint/typescript-eslint#5587]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

`let num: number | undefined = 0;` should be `let num: number | null = 0;`

### Affected URL(s)

-

**Comment by JoshuaKGoldberg** [comment]
@Luk-z could you please explain _why_ you think this is a bug? The rule handles both `null` and `undefined` pretty similarly.

**Comment by Luk-z** [comment]
@JoshuaKGoldberg
If you define a value `undefined` you would check it against undefined, not null. Of course `undefined == null` is true and the snippet works.

**Comment by Luk-z** [comment]
Additionally `null` value is not assignable to a variable of type `number | undefined`, I think this creates confusion

**Comment by JoshuaKGoldberg** [comment]
🤔 I still don't follow. This is the snippet in the docs right now:

```ts
let num: number | undefined = 0;
if (num) {
  console.log('num is defined');
}
```

It doesn't matter whether we declare it as `number | null` or `number | undefined`. Both are technically valid TypeScript code and are handled similarly by `strict-boolean-expressions`.

Expanding the docs example a bit, this is the type of situation the rule is meant to detect -- a logical check that is tricked by a falsy value like `0`:

```ts
// let num: number | null = Math.random() ? 0 : undefined;
let num: number | undefined = Math.random() ? 0 : undefined;
if (num) {
  console.log('num is defined');
}
```

Closing as non-actionable, but please do post back if you feel I'm missing something!

**Comment by Luk-z** [comment]
@JoshuaKGoldberg 
the confusing part is the second change of the PR https://github.com/typescript-eslint/typescript-eslint/pull/5588/files#diff-ae8706b9da06d32dab19a7fd207086b7fe8ed718bf4a3bc1d5b9a0af1284c710L70 (the first change can be rollbacked):
```
let num: number | undefined = 0;
if (num != null) {
  console.log('num is defined');
}
```

If you type a variable `number | undefined` why check if this variable is `null`? It's a non-sense, also if `null==undefined`.
With that philosophy you can also use `if(num=="1"){...}` to check if `num` is 1, but this is non-sense too.

**Comment by bradzacher** [comment]
Using `== null` to check for both null and undefined at the same tine is not nonsense - it us a well documented, common, and very widely used practice.

As an example for how common it is - the ESLint rule `eqeqeq` [has an option to specifically allow you to use double equals comparisons just for null](https://eslint.org/docs/latest/rules/eqeqeq#allow-null).

Further to this point - TS not only allows, but it fully understands the code and correctly refines the type.

The same [cannot be said about your other example of `1=='1'`, which TS not only disallows with an error, but also does not refine](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gDwFzwEYBuAKBIEsAzeACm3gF4H4AiAlgSngG8T5-4AekHwMaeMCQhxKJFigQISAO6iAFuRmo0IdCD4DsfYfAB6AfhIBfIA)

**Comment by Luk-z** [comment]
It's well know you can use `== null` to check  both `null` and `undefined`. 

But they are not semantically equal: `undefined` means "not defined" and `null` means "empty" and they must not be used indiscriminately. Like I sad before this could crete confusion on newby reading this (`typeof null != typeof undefined`). 
It's always a best practice to compare a value according with its declaration. 

Like Kyle Simpson (@getify) wrote in [You-Dont-Know-JS](https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/get-started/ch2.md) `it's safest and best to use only undefined as the single empty value, even though null seems attractive in that it's shorter to type`.

Also, Typescript allows to check `undefined` value against `== null`, but doesn't allows `null` assignment `const x: number | undefined = null;`

Btw This rule is not about the correlation between `null` and `undefined` with the loose equality operator, and I confirm it's more clear to check against `undefined`. The fact it's a "widely used practice" it's not a good reason to keep making mistakes. 

I could compromise on change only variable definition from `let num: number | undefined = 0;` to `const num: number | undefined | null = 0;`

**Comment by bradzacher** [comment]
> But they are not semantically equal: undefined means "not defined" and null means "empty" and they must not be used indiscriminately

They can either mean the same thing, or different things - depending on how you use them within your codebase.

Some people are of the opinion that you should use one over the other always, some people are of the opinion that you should use both but only in certain situations, and others are of the opinion that you should treat them exactly the same.

As an example at meta the enitre codebase treats the two values as exactly the same thing. In fact in flow there is a type operator that allows you to easily define a type as `T | null | undefined` - it looks like this `?T`.

This is a purely stylistic choice based on your codebases opinionated choices. There is no right or wrong answer. It is not a mistake to use it contravene to your opinion.

**Comment by Luk-z** [comment]
Are you comfortable with that change https://github.com/typescript-eslint/typescript-eslint/compare/main...Luk-z:typescript-eslint:Luk-z-patch-strict-boolean-expressions-nullable-numbers

I can create new PR or you can re-open https://github.com/typescript-eslint/typescript-eslint/pull/5588 and i push last commit.
