### ISSUE TITLE
Enhancement: [member-ordering] 'natural' sorting order from from eslint-plugin-typescript-sort-keys

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5597]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/member-ordering

### Description

[eslint-plugin-typescript-sort-keys](https://github.com/infctr/eslint-plugin-typescript-sort-keys) supports a `natural` option for sorting. Can we add that to `@typescript-eslint/member-ordering`, to bring it up to parity?

> Natural Order compares strings containing combination of letters and numbers in the way a human being would sort. It basically sorts numerically, instead of sorting alphabetically. So the number 10 comes after the number 3 in Natural Sorting.

Porting discussion from https://github.com/infctr/eslint-plugin-typescript-sort-keys/issues/50#issuecomment-1108934841

### Fail

```typescript
interface Example {
  1: number;
  10: number;
  3: number;
  6: number;
  8: number;
}
```

### Pass

```typescript
interface Example {
  1: number;
  3: number;
  6: number;
  8: number;
  10: number;
}
```

### Additional Info

Examples taken from https://github.com/infctr/eslint-plugin-typescript-sort-keys/blob/master/docs/rules/interface.md.

**Comment by asdf93074** [comment]
Is it okay to use a lib for the comparison or would you prefer we just code in the function too?

**Comment by JoshuaKGoldberg** [comment]
@asdf93074 please pardon my poor timing, I sent in a draft PR a couple of days ago that starts tackling this issue 😬 -- and neglected to link it to this issue. bradzacher did that just now. 

#5662 uses `natural-compare-lite`, the same library as eslint-plugin-typescript-sort-keys.
