### ISSUE TITLE
Use snapshots for testing rules

### ISSUE THREAD

**Issue by j-f1** [typescript-eslint/typescript-eslint#56]
We should use a snapshot system to test rules with each rule having a `rule-name.ts` fixture that is run through ESLint. Config can be provided by inline `/* eslint */` comments, and any reported errors would be dumped to either a Jest snapshot or an `errors.json` file. We could either switch the test framework from Mocha to Jest or just import Jest’s [`expect`](https://yarnpkg.com/en/package/expect) function to get access to the `toMatchSnapshot` matcher.

**Comment by JamesHenry** [comment]
I don't believe this is currently in our plans, and I would class this as pretty stale at this point, so going to close for now
