### ISSUE TITLE
Rule proposal: Prevent / Warns if the code attempts to interpolate functions directly into string template

### ISSUE THREAD

**Issue by chenxinyanc** [typescript-eslint/typescript-eslint#5600]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

This rule prevents potential erroneous implicit `Function` to `string` conversion in string interpolation expressions. Converting a function (or class itself) into string will cause function body being inserted into the string template, which could be undesirable in most of the cases.

I think we can leverage TypeScript typing information for the "Function" type checking. We don't need to cover the case where the interpolated value does not have `Function` type at compile-time.

### Fail Cases

```typescript
const formatErrorMessage = (error: unknown) => String(error);
// `formatErrorMessage` is of function type. Converting it into string results in function body being printed.
const message = "Error is {formatErrorMessage}";
```

### Pass Cases

```typescript
const formatErrorMessage = (error: unknown) => String(Error);
// Call the function to return the string result.
const message1 = "Error is {formatErrorMessage(err)}.";
// Or if you are converting function into string by design.
const message2 = "Error is {String(formatErrorMessage)}.";
```

**Comment by bradzacher** [comment]
Try our rule `restrict-template-expressions`
https://typescript-eslint.io/rules/restrict-template-expressions

it does exactly this - and more!

[playground](https://typescript-eslint.io/play/#ts=4.8.2&sourceType=module&code=PQKgUApgzgNglgOwC4AIBEABJBPADtAYwCc5ckBaaeZYI6JEgipCAW1xgEMXKAPXOlChwA9gihoAXOghEiIomjAhgYMABMIBLnRQExUVADMFrbgFE5CgLLQonAOYRpAClnyi0gK4IA1ghEAdwQAShQAXgA+FEMSBAcAbjVgYBQAMU44GBQAYU4oaGTUgAMTIjMkSw9bIUcIYpQ4KBQRIxQjHyZRBBQcfAA6XLEAN1kkRAdG1EQkERiGCZRBLxgkZsR2zvGxFAAjEXVsPYhFgRmIdX6wfXFUVjs6iJRiqoVG5oASAG8yiteiGr2JwAX2KSSKKAACvlmnkClAIXkYNkkAALCCbBBdHazJYQJBeIg9NEY2KLZarK43Qwoe61JwARieLysRHeKG+vwsrMBdRcX2BIWB-TBYBSKAA8my4G1sCIvChOLobqMiON4pjsT0ZnMyRrdkdNMIHAgqQY7g8nAAmZn-dnfADKC3iLi5lR5logQpFSSAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUELjAXxDyA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)
