### ISSUE TITLE
Docs: fix link to parameter-properties from no-parameter-properties

### ISSUE THREAD

**Issue by rafaeldolfe** [typescript-eslint/typescript-eslint#5603]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Change the link leading to 
https://typescript-eslint.io/rules/no-parameter-properties/parameter-properties
to instead lead to
https://typescript-eslint.io/rules/parameter-properties

### Affected URL(s)

https://typescript-eslint.io/rules/parameter-properties

**Comment by bradzacher** [comment]
@rafaeldolfe - could you please indicate where this link is?
Is it on the `parameter-properties` page? Or is it on some other page?

**Comment by armano2** [comment]
![image](https://user-images.githubusercontent.com/625469/189540050-d26756d5-bfa4-410a-9859-d99013ba07ac.png)

**Comment by Josh-Cena** [comment]
@armano2 That link on https://typescript-eslint.io/rules/no-parameter-properties is already working. See #5611

**Comment by armano2** [comment]
it looks like this fix is still needed 
![image](https://user-images.githubusercontent.com/625469/189540357-314e02fd-16c4-4fba-b6b3-28febdacba2b.png)

**Comment by Josh-Cena** [comment]
Wait, are you on the https://typescript-eslint.io/rules/no-parameter-properties/ page? I see the correct href on my side.

**Comment by armano2** [comment]
something seems to be broken, maybe we have some phantom redirect? 
![chrome-capture-2022-8-11](https://user-images.githubusercontent.com/625469/189540780-d34f952c-27af-4857-a5d1-a19317ca79a8.gif)

**Comment by Josh-Cena** [comment]
It works as expected even with JS off, which means the initial HTML also contains the right link. Maybe we should resurrect #5611, considering that's just generally a better thing to do? See https://docusaurus.io/docs/markdown-features/links:

> Using relative file paths (with .md extensions) instead of relative URL links provides the following benefits:

**Comment by armano2** [comment]
i just noticed something, link sometimes shows correct value, but js link always points to incorrect page

![image](https://user-images.githubusercontent.com/625469/189540946-f6183e8b-2799-4614-a23a-20bf4bf60349.png)

![image](https://user-images.githubusercontent.com/625469/189540954-35f2da80-f9ee-4386-b9cc-331df2627a0a.png)
