### ISSUE TITLE
Docs: `parserOptions.project` may have performance implications when using `**` glob patterns

### ISSUE THREAD

**Issue by chenxinyanc** [typescript-eslint/typescript-eslint#5613]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Same as #2611, but probably explicitly stating "using `**` glob patterns may cause performance implications" or "do not use `**` in `parserOptions.project` unless you are sure what you are doing".

Currently there is nowhere stating this caveat except somewhere [at the bottom of "Troubleshoot" page](https://typescript-eslint.io/docs/linting/troubleshooting#my-linting-feels-really-slow).

Is it possible for us to also have such kindly notice
* in [Monorepo Configuration#One tsconfig.json per package (and an optional one in the root)](https://typescript-eslint.io/docs/linting/typed-linting/monorepos#one-tsconfigjson-per-package-and-an-optional-one-in-the-root),
* and in [typescript-eslint/packages/parser/README.md#Configuration >> parserOptions.project](https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/parser#parseroptionsproject)?
    * Noting that this README file contains the following code sample without any caution:
    ````js
    // glob pattern
    project: './packages/**/tsconfig.json';
    ````

### Affected URL(s)

* https://typescript-eslint.io/docs/linting/typed-linting
* https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/parser#parseroptionsproject

**Comment by adnanhashmi09** [comment]
I would like to work on this. I will submit a PR shortly.
