### ISSUE TITLE
Docs: add a tool section for tools that use eslint

### ISSUE THREAD

**Issue by juli1** [typescript-eslint/typescript-eslint#5619]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I propose to have a tool section for all tools that use `typescript-eslint`.

I am working on [Codiga](https://www.codiga.io) and we provide services to analyze code and automate code reviews. We do analyze typescript code and use typescript-eslint. Having a section about tools that use `typescript-eslint` would help user that want to check their typescript code.

### Affected URL(s)

The URL would be the [in the doc](https://typescript-eslint.io/docs/), have a section tools with the list of all tools related to typescript-eslint. Maybe the tools can be divided into different subsections.

**Comment by JoshuaKGoldberg** [comment]
Agreed, I think this would be good to have. Codeclimate, SonarQube, etc. Perhaps under some kind of "integrations" section?

Alternately, I also wonder if it makes sense to have the main ESLint website itself have these integrations, as most or all of them are general to all ESLint setups?

**Comment by bradzacher** [comment]
I think the eslint team generally avoided doing this because it means you need to create policies around what constitutes a tool that should or shouldn't be on the list and you also would need to field all the PRs that would come in from companies / tools looking to get themselves on the list.

I believe they just leave this sort of thing in the community's hands with lists like this one:
https://github.com/dustinspecker/awesome-eslint

**Comment by juli1** [comment]
@bradzacher I understand your point of view. eslint is more the exception than the norm in terms of sponsorship and many popular linters have an integration page. Few examples:

 - PMD (most popular linter for Java) has a dedicated in [their doc](https://pmd.github.io/latest/pmd_userdocs_tools.html).
 - Shellcheck (best shellscript linter) puts popular integration and sponsors as reference integrations on [their homepage](https://www.shellcheck.net/)

A page that lists the integrations helps people find tools to check their code using typescript. Some folks do not use `typescript-eslint` in VSCode (some developers disable it all together to avoid what they consider noise). In such cases, integration in the CI/CD pipeline is the best way to ensure rules are checked.

As for the rule to accept an integration, it should be simple: the PR should show proof of correct integration with the project. In other words, the tool surfaces the `typescript-eslint` warnings/errors in their product.

Finally, promoting integrators not only helps your project get more traction and improves typescript code quality at multiple points of the software development process (here, in the CI/CD pipeline). It also incentivizes organizations to contribute financially to your organization. I understand that may not be important for the project, but if that is the case, it can help to get resources and promote the product.

Just me $0.02 coming from the integrator side; please close if not interested and there is no chance to be implemented.

Thanks,

**Comment by bradzacher** [comment]
> As for the rule to accept an integration, it should be simple: the PR should show proof of correct integration with the project. In other words, the tool surfaces the typescript-eslint warnings/errors in their product.

I wish it were this simple. But we're talking about linking from our website to an external one. This does imply some form of a relationship between the two pages - it suggests we endorse the content on the linked website.

As a project we have a "brand" we want to maintain and as such there are certain standards and principles which we want to ensure the links uphold. Which means we do need some form of policies around what can be linked to.

As a strawman argument - imagine that someone builds a tool that uses our tooling (I.e. Satisfies your definition), but their docs are covered with porn. Obviously that's not something we would want to promote or associate ourselves with. However if our policy was just as you suggest - we'd have no specific recourse to remove the link aside from "we're the maintainers, too bad".

More serious examples of things we don't want to associate ourselves with: illegal activities, terrorism, human rights violations, political issues, etc. 

Another less egregious example - imagine someone builds a tool that simply wraps the eslint cli and does nothing interesting or helpful. Technically such a tool satisfies your policy - but it's really low quality, so linking it would "spam" the page, lowering the value of the integrations page. This in turn lowers the value proposition for tool owners.

We need to have a bit more detail in our policies to help guide our distributed decision making as maintainers so we can be consistent and no one person owns it. Also such a policy helps the community understand what's allowed or not - tool owners can self-select and understand if they would qualify (which reduces our maintenance burden) and there's less need to have any discussion(/argument) about a link when it's proposed to be added.
This policy would likely mirror the one we design for our "sponsor" links (#5504).

---

To clarify - I'm not at all against adding such a section to the website! I think promoting other tools is going to be important for the community to discover things and grow.

We just need ensure we have the policies in place to promote a high quality, safe, inclusive community.

**Comment by juli1** [comment]
Sounds good, thank you.

**Comment by JoshuaKGoldberg** [comment]
Making sure this doesn't get lost: typescript-eslint.io is generally just for TypeScript-specific information. For tools that that work roughly the same on JS or TS code, the right place to put them would be on eslint.org. Now, many tools -such as Codiga, it seems?- work much better on TypeScript code, but most are still at their core ESLint tools. They just happen to use the plugins & rules from typescript-eslint.io.

I'm going to close this issue because I don't know that there are any tools that _specifically_ use typescript-eslint. But please do post back if you think I'm misunderstanding anything @juli1. Thanks!
