### ISSUE TITLE
Bug: Base urls in a monorepo

### ISSUE THREAD

**Issue by MariaSolOs** [typescript-eslint/typescript-eslint#5623]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Issue Description

I keep getting linting errors related to variables being of type `any`. After several hours of debugging, I narrowed it down to being caused by using absolute paths in my imports. I followed the documentation for setting typed linting in a monorepo, and so I'm unsure of why the setting of `"baseUrl: ."` in the `inner` TS project (refer to the repo) isn't being picked up by the plugin... 

In particular, if I change the contents of `inner/page.ts` to:
```
import routes from "./routes";

const navigationLinks = [
    { ...routes.home, title: 'Home' }
];
```

Then `routes` isn't resolved to `any`, despite the `tsconfig.json` file inside `inner` setting the right base url and my `.eslintrc.js` including `./inner/tsconfig.json` in `projects`.

### Reproduction Repository Link

https://github.com/MariaSolOs/ts-eslint-repro

### Repro Steps

1) Clone the repo
2) Run `npm install`
3) Lint `inner/page.ts`. Line 4 will complain about `Unsafe member access .home on an any value.`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `^5.36.2` |
| `@typescript-eslint/parser`            | `^5.36.2` |
| `ESLint`                               | `^8.23.0` |
| `node`                                 | `^4.8.3` |

**Comment by bradzacher** [comment]
If I had to guess from a quick glance

Your "outer" tsconfig includes the "inner" folder.
https://github.com/MariaSolOs/ts-eslint-repro/blob/main/tsconfig.eslint.json#L6

In your eslintrc the "outer" tsconfig is first in `parserOptions.project`, so it's the first one that we will check when trying to resolve types for a file
https://github.com/MariaSolOs/ts-eslint-repro/blob/main/.eslintrc.js#L9-L12
This means that we'll never actually look at your "inner" tsconfig.

**Comment by MariaSolOs** [comment]
OHHHHH.
Well that fixed it. Thanks a lot!
