### ISSUE TITLE
Bug: [dot-notation] Doesn't respect `noPropertyAccessFromIndexSignature`

### ISSUE THREAD

**Issue by simonhaenisch** [typescript-eslint/typescript-eslint#5649]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.8.2&sourceType=script&code=JYOwLgpgTgZghgYwgAgApQPZIM7YKIgBuyA3gFDLIDaA1hAJ4Bcy2YUoA5gLrOvsgdkAH2QBXEABMIMUBAkBuMgF8yZKQgA2cKCgQYQrZAAdMObMxLIIRZuiwRcBYirJ6DGDRAB0GjBwAUJva4XtaEXgByAPIAIngA+ngRAGoAlGRAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQCYHsAXAWgDsiBDQgS31PSkWmn2knDAF8ROg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUhFYABUyxEWPAE8AgtGjoSJAGKL4ASSIATdAA8AysgDmRAIZ42mdBTCj0UgL4hvQA

### Repro Code

```typescript
interface ProcessEnv {
  [key: string]: string | undefined;
}

declare const process: { env: ProcessEnv }

console.log(process.env.NODE_ENV)
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "dot-notation": "error",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "noPropertyAccessFromIndexSignature": true
  }
}
```

### Expected Result

According to https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/dot-notation.md, it should be compatible with `noPropertyAccessFromIndexSignature`.

### Actual Result

ESLint shows an error

```
["NODE_ENV"] is better written in dot notation.
```

and if you auto-fix it, TypeScript shows an error

```
4111: Property 'NODE_ENV' comes from an index signature, so it must be accessed with ['NODE_ENV'].
```

### Versions

| package | version |
| -- | -- |
| `@typescript-eslint/eslint-plugin` | `5.37.0` |
| `@typescript-eslint/parser` | `5.37.0` |
| `TypeScript` | `4.8.2` |
| `ESLint` | `8.15.0` |
| `node` | `web` |

**Comment by bradzacher** [comment]
> [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

The very first FAQ answers this for you
https://typescript-eslint.io/docs/linting/troubleshooting/#i-am-using-a-rule-from-eslint-core-and-it-doesnt-work-correctly-with-typescript-code

https://typescript-eslint.io/rules/dot-notation/

**Comment by simonhaenisch** [comment]
OK sorry, however is it also expected that this happens when using

```
{
  "extends": ["plugin:@typescript-eslint/recommended"]
}
```

?

https://typescript-eslint.io/play/#ts=4.8.2&sourceType=script&code=JYOwLgpgTgZghgYwgAgApQPZIM7YKIgBuyA3gFDLIDaA1hAJ4Bcy2YUoA5gLrOvsgdkAH2QBXEABMIMUBAkBuMgF8yZKQgA2cKCgQYQrZAAdMObMxLIIRZuiwRcBYirJ6DGDRAB0GjBwAUJva4XtaEXgByAPIAIngA+ngRAGoAlGRAA&eslintrc=N4KABGBECmAeAu0B2ATAzpAXGA2pADgDYCuA5gJZKYAC8AnvtGgMYBO5+8AtE4ZfAHpW0ZgHsAtuOQpoKSAF0QAXyA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUhFYABUyxEWPAE8AgtGjoSJAGKL4ASSIATdAA8AysgDmRAIZ42mdBTCj0UgL4hvQA

**Comment by simonhaenisch** [comment]
I think it's missing `dot-notation` here: https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts?

**Comment by bradzacher** [comment]
nope - `dot-notation` is not a recommended rule in ESLint core so our recommended sets do not turn it on either.

**Comment by simonhaenisch** [comment]
Right, I did not realize that there was a different config inside our shareable config that turned this rule on (`eslint-config-standard`). Thanks for the quick help!
