### ISSUE TITLE
[eslint-plugin-readme] document rules need disable base rule from eslint

### ISSUE THREAD

**Issue by bluelovers** [typescript-eslint/typescript-eslint#569]
document notice rules need disable base rule from eslint

some of rule, need to disable base rule
https://github.com/typescript-eslint/typescript-eslint/search?utf8=%E2%9C%93&q=disable+the+base+rule&type=

maybe should notice it in Supported Rules table
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules

and also notice the rule has extra options or not

**Comment by bradzacher** [comment]
We now separate the extension rules in the readme: https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#extension-rules
