### ISSUE TITLE
Repo: Readonly vs Immutable Update

### ISSUE THREAD

**Issue by RebeccaStevens** [typescript-eslint/typescript-eslint#5699]
### Suggestion

Hey @JoshuaKGoldberg @bradzacher @marekdedic @qpwo @rodrigofariow

I thought I'd update you with regards to previous discussions around the `prefer-readonly-parameter-types` rule and the updates I've made to [`eslint-plugin-functional`](https://github.com/eslint-functional/eslint-plugin-functional).

A while ago I created issue #4536 talking about Readonly vs Immutable definitions and how these definitions should be applied. I've recently released a new library called [is-immutable-type](https://github.com/RebeccaStevens/is-immutable-type) (based of `isTypeReadonly` utility function) which uses the definitions discussed in that issue and also addresses some of the issue that have been opened here (such as #4185).

I've created a new rule ~[`prefer-immutable-parameter-types`](https://github.com/eslint-functional/eslint-plugin-functional/blob/next/docs/rules/prefer-immutable-parameter-types.md)~ (edit: now [prefer-immutable-types](https://github.com/eslint-functional/eslint-plugin-functional/blob/next/docs/rules/prefer-immutable-types.md)) to replace the original `prefer-readonly-parameter-types` rule as part of [`eslint-plugin-functional@5.0.0`](https://github.com/eslint-functional/eslint-plugin-functional/releases) (which is currently in beta). And in case you're curious, there's also a second rule that also uses that new library [`type-declaration-immutability`](https://github.com/eslint-functional/eslint-plugin-functional/blob/next/docs/rules/type-declaration-immutability.md). `eslint-plugin-functional` v5 should be released in the ~next few days 😄~ (edit: hopefully soon 😞).

I've also just proposed to [`type-fest`](https://github.com/sindresorhus/type-fest) about renaming the `ReadonlyDeep` type to `Immutable` ([issue](https://github.com/sindresorhus/type-fest/issues/480)) as it follows the "immutable" definition. (Waiting on [this PR](https://github.com/sindresorhus/type-fest/pull/479) to properly support Immutable Arrays.)

Let me know if you have any feedback 😄.

**Comment by qpwo** [comment]
Awesome I'll try it soon as I can

**Comment by marekdedic** [comment]
Hi, thanks for the proposal. Are you aware of sindresorhus/type-fest#467 ? That will probably impact your work as well and I am not sure it's actually solvable without changes to TS itself...

**Comment by marekdedic** [comment]
Also, incorporating #4436 would be great, if you didn't do so already - in typescript-eslint it is waiting for the next major as some breaking changes are needed :(

**Comment by RebeccaStevens** [comment]
@JoshuaKGoldberg I don't think there's really anything that needs to be changed here. Maybe is-immutable-type could be used by some rules in the future?

Note: The release of eslint-plugin-functional v5 has been delayed [due to what seems to be a bug in tsutils](https://github.com/ajafff/tsutils/issues/147) - hopefully it will be patched soon. And @jonaskello wants to do a bit more testing first too.

**Comment by RebeccaStevens** [comment]
@marekdedic 

#4436 is indeed included. Instead of an allow list though, it's a set of overrides. See [overrides](https://github.com/RebeccaStevens/is-immutable-type#overrides) and [immutability settings](https://github.com/eslint-functional/eslint-plugin-functional/blob/next/docs/rules/settings/immutability.md) for details on how to use them.

I don't think any type-fest issues will affect things too much as `ReadonlyDeep` is by no means required to achieve immutability, it's just a convenient helper.

**Comment by JoshuaKGoldberg** [comment]
> tsutils ... hopefully it will be patched soon

https://github.com/typescript-eslint/typescript-eslint/issues/5552 😬 

In this case, I'm going to close this issue as non-actionable to keep it out of our queue. But feel free to keep commenting here a bit, it's useful info. Cheers!

**Comment by marekdedic** [comment]
@RebeccaStevens 
> #4436 is indeed included. Instead of an allow list though, it's a set of overrides. See [overrides](https://github.com/RebeccaStevens/is-immutable-type#overrides) and [immutability settings](https://github.com/eslint-functional/eslint-plugin-functional/blob/next/docs/rules/settings/immutability.md) for details on how to use them.

Hi, thanks for the pointer - it's a bit of a missed opportunity that the overrides style will be different in the 2 plugins, but that's probably too late to change...
