### ISSUE TITLE
Bug: [promise-function-async] Invalid fixer for method named `catch`

### ISSUE THREAD

**Issue by SimenB** [typescript-eslint/typescript-eslint#5729]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.8.3&sourceType=module&code=KYDwDg9gTgLgBAE2AMwIYFcA28DGnUDOBcACgMKoB2Ow+ARpsADwAqAfHAJYC2Yj3wSjGIkoEbpwLAAMpwDWzdnADeAKDhwwUTgDdUMYHCjBUCCJUwBPOAH0t4ycABcpMRKms2AblXq4OcwIYKHQcGGgACgBKFT8NGAALSQA6OzdHOABeOEpgAHdXBykI6KyOZTgAXyifDUrfeITBVgAlYAIsGABGLLgWABo+to7sACZe3J1gKDYIuLhzADEsZE5MRgQAfid5jQAfOBK9THRnPpjMjhZhzp6D0SKZeUUb7C62KN24A-RKJFXcggvgdKFhMP15uY2gArYBhYBbHYaZHfQ4RYyEcwuX5ySgQPKUC5XV4wcb3dJSWQKVrtTqjD7AuC-f6cQGM0HrCEaKIuB7uF60t6o66C0nlebGGDoKCUOCJFJpR7JRKCCJLFZrDaDKHAWHwhA1Pz1Pw4fQ4BI0kYwWaQygwuEGRGMkoYghYpmUXH4wllIai1F8xxUgVWhko-Yells8Oojngvw8wr81jCknilGS6Wy+UEVL2fnJU0wc1qu26h0Iw11VSVIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6AewFtLlFaAM1hMy+Spya0AhskKj0URNC7RI4MAF8QmoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
export default class PCancelable<T> implements PromiseLike<T> {
  private readonly _promise: Promise<T>;

  constructor() {
    this._promise = new Promise(() => { });
  }

  then<TResult1 = T, TResult2 = never>(
    onFulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onRejected?:
      | ((reason: unknown) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): Promise<TResult1 | TResult2> {
    return this._promise.then(onFulfilled, onRejected);
  }

  catch<TResult>(
    onRejected?:
      | ((reason: unknown) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): Promise<T | TResult> {
    return this._promise.catch(onRejected);
  }
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/promise-function-async": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

```ts
export default class PCancelable<T> implements PromiseLike<T> {
  private readonly _promise: Promise<T>;

  constructor() {
    this._promise = new Promise(() => {});
  }

  async then<TResult1 = T, TResult2 = never>(
    onFulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onRejected?:
      | ((reason: unknown) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): Promise<TResult1 | TResult2> {
    return this._promise.then(onFulfilled, onRejected);
  }

  async catch<TResult>(
    onRejected?:
      | ((reason: unknown) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): Promise<T | TResult> {
    return this._promise.catch(onRejected);
  }
}
```

### Actual Result

Instead of `async catch<TResult>(`, the fixer produces `catch async <TResult>(` which is invalid syntax.

### Versions

| package | version |
| -- | -- |
| `@typescript-eslint/eslint-plugin` | `5.38.1` |
| `@typescript-eslint/parser` | `5.38.1` |
| `TypeScript` | `4.8.3` |
| `ESLint` | `8.15.0` |
| `node` | `web` |

**Comment by bradzacher** [comment]
The bug here is caused because our parser parses the `catch` identifier as a `Keyword` token.
This behaviour is *technically* wrong, but is consistent with ESLint's core parser (espree), so we shouldn't change it there.

Instead we need to make the rule more resilient so that it looks for both an `Identifier` token, OR a `Keyword` token.

Note that you can repro this bug with any keyword that's a valid method name like `default`, `case`, `for`...
