### ISSUE TITLE
Repo: Switch from dependabot to renovate

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5732]
### Suggestion

Context: https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/26 -> https://twitter.com/bradzacher/status/1577071598682935296

Renovate has a lot more features than dependabot, including around [`stabilityDays`](https://docs.renovatebot.com/configuration-options/#stabilitydays) and [Noise Reduction](https://docs.renovatebot.com/noise-reduction/#the-future-of-noise-reduction). Let's use them!

**Comment by RahulGautamSingh** [comment]
Hey @JoshuaKGoldberg, Can I help with this one?
