### ISSUE TITLE
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.

### ISSUE THREAD

**Issue by jez9999** [typescript-eslint/typescript-eslint#5765]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Issue Description

I recently added a couple of ESLint rules that required me to add this to my `.eslintrc.cjs` config:

```
	"parserOptions": {
		"ecmaVersion": "latest",
		"project": "./tsconfig.json",
		"parser": "@typescript-eslint/parser"
	},
```

This is causing the following error in VS Code in *some* of my TS and JS files:

> Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
> The file does not match your project config: src\router.js.
> The file must be included in at least one of the projects provided.

The weird thing is I will get this error in a TS file in a dir, but not in another TS file in the same dir.  If I rename the file with the error (something like `file.ts` -> `file2.ts`), the error will disappear, and it appears when I rename it back, so I assume it's some weird caching issue.

In my example repo, I'm getting the error for `src/router.js` but not for `src/main.js`.

### Reproduction Repository Link

https://gitlab.com/jez9999/eslint-bug

### Repro Steps

1) clone the repo
2) `npm install`
3) `npm run lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `TypeScript`                           | `4.8.4` |
| `ESLint`                               | `8.23.1` |
| `node`                                 | `16.17.0` |

**Comment by JoshuaKGoldberg** [comment]
Interesting. #5762 should improve the error message a bit. Two things fix this locally for me:

* Removing the `references` from `tsconfig.json`
    * We don't yet support project references: #2094
* Enabling `parserOptions.EXPERIMENTAL_useSourceOfProjectReferenceRedirect` per #2669

My recommendation here would be to do either of those two things, or if you can't, set up a `tsconfig.eslint.json` as described in https://typescript-eslint.io/docs/linting/typed-linting/monorepos.

As to why those _specific_ files do or don't get the parsing error... great question. Marking as this needing an investigation.

**Comment by bradzacher** [comment]
Something weird is happening with the project references yeah.
How come you have both a `tsconfig.json` AND a `tsconfig.app.json` **that are exactly the same?

Similarly your `tsconfig.vitest.json` has no `includes` - which means it **includes every single file in your project**.

For some reason the combination of the duplicated tsconfig and the unrestricted includes in project references causes TS to exclude `src/router.js` from the program.

What makes it weirder is that TS gives us inconsistent information:
- `program.getRootFileNames()` returns
  ```
  Set(3) {
    'env.d.ts',
    'src/main.js',
    'src/router.js'
  }
  ```
- `program.getSourceFiles()` returns
  ```
  Set(34) {
    // ... snip node modules ...
    'env.d.ts',
    'src/main.js'
  }
  ```

So TS knows that `src/router.js` is a root file, but it doesn't create a source file for it.
I don't know why *exactly*. I was under the impression that TS should completely ignore the project references for our call.

Regardless - cleaning up your project references so there's less duplication in the `includes` would be best.

I would suggest [creating a single tsconfig for your entire project](https://typescript-eslint.io/docs/linting/typed-linting/monorepos#one-root-tsconfigjson).

**Comment by bradzacher** [comment]
I'm going to close this for now because there are workarounds provided.
We'll investigate following up with TS separately.

**Comment by jez9999** [comment]
The trouble is, the default vue project created with `npm init vue@3` wants to do this whole "multiple .tsconfig" thing, where different .tsconfig files have different values for "extends".  I'm not sure exactly what that's doing so I'm not sure how to translate it all into one .tsconfig.

**Comment by bradzacher** [comment]
@jez9999 check the guide I linked. It should help you setup a tsconfig.eslint.json to lint with.

**Comment by jez9999** [comment]
> Interesting. #5762 should improve the error message a bit. Two things fix this locally for me:
> 
> * Removing the `references` from `tsconfig.json`
>   
>   * We don't yet support project references: [Support for Project References #2094](https://github.com/typescript-eslint/typescript-eslint/issues/2094)
> * Enabling `parserOptions.EXPERIMENTAL_useSourceOfProjectReferenceRedirect` per [feat(typescript-estree): add flag EXPERIMENTAL_useSourceOfProjectReferenceRedirect #2669](https://github.com/typescript-eslint/typescript-eslint/pull/2669)
> 
> My recommendation here would be to do either of those two things, or if you can't, set up a `tsconfig.eslint.json` as described in https://typescript-eslint.io/docs/linting/typed-linting/monorepos.
> 
> As to why those _specific_ files do or don't get the parsing error... great question. Marking as this needing an investigation.

If you ask me, @JoshuaKGoldberg, supporting project references should be a very high priority for this project.  They seem to have been around now for 4 years and are presumably widely used.  It's somewhat ridiculous they're not supported.  Also, I tried adding that that experimental flag, and it didn't fix the errors here at all:

```
	"parserOptions": {
		"ecmaVersion": "latest",
		"project": "./tsconfig.json",
		"parser": "@typescript-eslint/parser",
		"EXPERIMENTAL_useSourceOfProjectReferenceRedirect": true
	},
```

**Comment by bradzacher** [comment]
> It's somewhat ridiculous they're not supported

That sort of statement is a really harmful, inflammatory statement. It is based on a lack of understanding of the **_volunteer_** maintainers' circumstances as well as the scope of the problem.

I would thank you to not use such a tone, especially when you're asking people to volunteer their free time to help you out.

> If you ask me supporting project references should be a very high priority for this project

Project references aren't something you can simply support because we don't support them - TS APIs support them.
We need involvement from the TS team to properly support them, but we as **_volunteer_** maintainers haven't have the bandwidth to get involved in such a collaboration because it will take a lot of time to properly spec it, build it and test it.

Right now the APIs TS provides to work with project references are not good for us - there are a number of cases for which they break the type-aware linting; which is why the flag is `EXPERIMENTAL`.
