### ISSUE TITLE
Enhancement: [no-unused-vars] ignoreImport

### ISSUE THREAD

**Issue by mathieulb** [typescript-eslint/typescript-eslint#5813]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-unused-vars/

### Description

ignoreImport=true would ignore any variables that occur in a import...from.

There may be incentive to further distinguish between `import * as stuff from 'stuff'` and `import {foo,bar,baz} from 'stuff'` because the latter is a lot more likely to introduce unused variables and take lots of lines in the reports. Those could be either handled by two extra values of ignoreImport, or by splitting ignoreImport into two bools, though of the two extra cases I only expect to use the one that only ignores import {...} and not the one that only ignores import *.

### Fail

```typescript
import * as stuff from 'stuff'     // "stuff is unused" only if ignoreImport=false
import {foo,bar,baz} from 'stuff'  // "bar is unused"   only if ignoreImport=false

console.log(foo(baz+42))
```

### Pass

```typescript
import * as stuff from 'stuff'
import {foo,bar,baz} from 'stuff'

console.log(foo(baz+42))
console.log(stuff.thing(bar))
```

**Comment by bradzacher** [comment]
Why would you want to ignore imports?
I don't think there's any good reason to ignore an unused import.

If you want to keep the import as it has a side-effect, you can do so without a variable - `import 'module'`

Please help me understand **why** you would want to ignore imports.

**Comment by mathieulb** [comment]
E.g. every time I import `logger` in a file for a temporary `logger.debug(...)` and then remove the latter, I have to comment out the import as well, or have one useless no-unused-variable warning, until next time I need `logger`.

**Comment by bradzacher** [comment]
This is working as intended then.
The logger is unused, so it gets reported.
You don't want to leave the logger in your production code as module imports aren't zero cost.

If for some reason you want to ignore the logger import, then use the `varsIgnorePattern` option to declare `logger` as an ignored name.

**Comment by mathieulb** [comment]
BTW, `require` of a module that has already been required somewhere else is nearly zero-cost in Node, as the modules get memoised (and actually they have to, because they have to present the same exported globals to every other module). I believe `import` in TSC works pretty much the same (though "only" for speed, as the actual exported vars are runtime-only). It would be quite impractical if the files were reread each time due to the combinatorics of recursive descent of deps of every module, and can't think of any other cost than that of doing `const {logger} = someObj`.
