### ISSUE TITLE
Rule proposal: ban importing `.ts` files from packages in `node_modules` when compiled `d.ts` & `.js` files are available

### ISSUE THREAD

**Issue by DetachHead** [typescript-eslint/typescript-eslint#5815]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

contrary to popular belief, when publishing npm packages it's actually a good idea to include the source code in the published package. this is because you can use the [`declarationMap`](https://www.typescriptlang.org/tsconfig#declarationMap) compiler option to make `ctrl+click` navigate to the source code instead of the declarations.

unfortunately IDEs sometimes incorrectly suggest importing from the source code instead of the compiled code. i think there should be an eslint rule to warn against this

#### folder structure
```
my-project/
├── node_modules/
│   └── some-package/
│       ├── dist/
│       │   ├── index.js
│       │   ├── index.d.ts
│       │   ├── foo.js
│       │   └── foo.d.ts
│       ├── src/
│       │   ├── index.ts
│       │   └── foo.ts
│       ├── tsconfig.json
│       └── package.json
└── src/
    └── index.ts
```

### Fail Cases

```typescript
// my-project/src/index.ts
import {foo} from 'some-package/src/foo'
```

### Pass Cases

```typescript
// my-project/src/index.ts
import {foo} from 'some-package/dist/foo'
```

### Additional Info

while this won't cause any runtime errors, i believe it's bad for performance as it causes typescript to unnecessarily re-compile the package, when it's already been compiled

**Comment by bradzacher** [comment]
We don't want to build rules that inspect imports like this.
There are a lot of complexities around resolving a module specifier to a path on disk.
There are other projects better suited to analysing imports like this!
Consider raising an issue in `eslint-plugin-import` https://github.com/import-js/eslint-plugin-import/
