### ISSUE TITLE
Docs: Consider surfacing remaining docs from repo Markdown files on the website

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5824]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Spiritual successor to #5242, and following up on https://github.com/typescript-eslint/typescript-eslint/pull/5762/files#r994711306: there's still a lot of information stored in `.md` files checked into the repo. But we've been directing users to the website -- which makes a divide between two areas of docs.

I propose we make the website the primary and _mostly_ only place to view documentation, including type descriptions such as `parserOptions`. That would include guides for contributing and release strategies.

For that many users would expect to be in the repo, I propose we leave them where they are and configure Docusaurus to surface them -- as we've done for rule docs in #5249. The files to leave in-place are:

* `./.github/*.md`
* `./*.md`
* `./packages/*/README.md`

Thoughts?

### Affected URL(s)

Potentially many!

**Comment by bradzacher** [comment]
Relayed yo https://github.com/typescript-eslint/typescript-eslint/issues/5090?
