### ISSUE TITLE
Website: Add ESQuery visualizer to the playground

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5846]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

https://estools.github.io/esquery exists and is useful for previewing ESQuery query results. But it'd be really nice to have a playground that's integrated natively with typescript-eslint. And having it on typescript-eslint.io/play seems like a natural fit to me.

I don't know what it would look like - suggestions very welcome. We can certainly play around with it and get creative!!

### Affected URL(s)

https://typescript-eslint.io/play

**Comment by bradzacher** [comment]
Quick design thought.
Add a tickbox which shows a single-line text-box above the editor window and the right panel
![image](https://user-images.githubusercontent.com/7462525/196686210-3a797b10-5f67-41b5-9950-cb39e1206539.png)

When you type your selector we highlight the matches in the editor, just like VSCode's find+replace:
![image](https://user-images.githubusercontent.com/7462525/196686444-3e8856a4-65ab-4ec0-9ae6-b88cefdc3f9b.png)

Thought:
We can make use of the "errors" panel (i.e. "AST Viewer = disabled") to dump out query parse/validation errors.

**Comment by jtbandes** [comment]
This would be great! Any updates on it?
