### ISSUE TITLE
Bug: [@typescript-eslint/no-unused-vars] Error "is defined but never used" for decorator imports on Typescript 4.8

### ISSUE THREAD

**Issue by bogdanb** [typescript-eslint/typescript-eslint#5866]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Issue Description

When using Typescript 4.8.x, the `@typescript-eslint/no-unused-vars` reports an “is defined but never used” when importing a decorator. I can reproduce it with Typescript 4.8.4 (the newest as I’m writing this) but also with 4.8.1-rc. If I use 4.7.3 instead (the last 4.7 version I know of) it doesn’t happen anymore.

For the record, when reproducing I get this output:

```
$ npm run lint

> test-eslint@0.0.1-SNAPSHOT lint
> eslint --ext .ts ./src


C:\workspace\test-eslint\src\user.ts
  1:9  error  'Decorator' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

(PS: Note that there are a lot of issues about similar messages from this rule, but they are old and all seem to have different causes. #5745 was closed as not reproducible, but given the comment at the end I wonder if it might not have been caused by accidentally/temporarily upgrading Typescript or something.)

### Reproduction Repository Link

https://github.com/bogdanb/eslint-unused-decorator-import-bug

### Repro Steps

1) clone the repo
2) `npm ci`
3) `npm run lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `TypeScript`                           | `4.8.4` |
| `ESLint`                               | `8.26.0` |

(I removed all lines for things that are not explicitly mentioned in my `package.json`. Not sure if whatever npm does to pick a version is relevant, but I included a `package-lock.json` file which should be enough.)

**Comment by bradzacher** [comment]
[This does not reproduce in the playground.](https://typescript-eslint.io/play/#ts=4.8.4&sourceType=module&code=FAehAIAEBcGcFoCWBzAdgewE4FNiILYAOW04AItgGYCGArgDbQA04A3uAHLX7YAm4AX3CVM6fOABEAOhC9sAYyzVoWCQG5gwSBRoNoACgkAVbLFJceEgJTBsAD2KZS8+tVixwJswGFX7gIxswODgAG7U9LTY4AC84P4aApqQFnyGXubc2Na2DiTgLm4eGb5FAExBIeGR0XEJwElAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUjoAHoizJ46IngCGqACL9YmNXl3Cwo9FIC+IM0A)

It reproduces in your repro because of the big warning that's logged:
```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.8.0

YOUR TYPESCRIPT VERSION: 4.8.4

Please only submit bug reports when using the officially supported version.

=============
```

you can't use mismatched version of our tooling and TS. Things must be supported.
TS 4.8 is not supported by v5.30.5 of our tooling

**Comment by bogdanb** [comment]
Wait, I think I’m missing something. Where did you find that warning? I don’t see it anywhere when I reproduce it on my machine:

```
bogdanb@DELL2-BB MINGW64 /c/workspace/test-eslint (master)
$ npm ci

added 261 packages, and audited 262 packages in 3s

80 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

bogdanb@DELL2-BB MINGW64 /c/workspace/test-eslint (master)
$ npm run lint

> test-eslint@0.0.1-SNAPSHOT lint
> eslint --ext .ts ./src


C:\workspace\test-eslint\src\user.ts
  1:9  error  'Decorator' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

**Comment by bogdanb** [comment]
I tried to do exactly the steps you mentioned, and in my case it does not show any warning:

```
bogdanb@DELL2-BB MINGW64 /c/workspace
$ git clone git@github.com:bogdanb/eslint-unused-decorator-import-bug.git
Cloning into 'eslint-unused-decorator-import-bug'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 9 (delta 0), reused 9 (delta 0), pack-reused 0
Receiving objects: 100% (9/9), 55.57 KiB | 598.00 KiB/s, done.

bogdanb@DELL2-BB MINGW64 /c/workspace
$ cd eslint-unused-decorator-import-bug/

bogdanb@DELL2-BB MINGW64 /c/workspace/eslint-unused-decorator-import-bug (master)
$ npm i

added 261 packages, and audited 262 packages in 2s

80 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

bogdanb@DELL2-BB MINGW64 /c/workspace/eslint-unused-decorator-import-bug (master)
$ npm run lint

> test-eslint@0.0.1-SNAPSHOT lint
> eslint --ext .ts ./src


C:\workspace\eslint-unused-decorator-import-bug\src\user.ts
  1:9  error  'Decorator' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

I’ll even provide a screenshot in case the copy-paste omits something:

![image](https://user-images.githubusercontent.com/225448/198251215-420eeffa-1ef2-47f6-9a47-2e1698325253.png)

The `package-lock.json` was generated by just running `npm i` as well, so it should have been up to date. Do you have any idea why I would get different results?

**Comment by bogdanb** [comment]
Huh, I found part of the issue. I’m running on Windows usually, and it does not show that warning for some reason. I just tried the same steps above on a Linux machine and there I _do_ get the warning.

Do you have any idea why the warning is not shown on Windows? Could this be a problem in `eslint` itself, or something from `npm` in general?

Turns out I completely misunderstood how `npm i` works. I thought it would update all dependencies when called without a `package-lock.json` file (because I usually run it only after updating `package.json`, so it updates _some_ things), and thus I was convinced my `package-lock.json` file had everything up-to-date. So it never occurred to me I actually need to run `npm update` as well. Thanks a lot, and sorry for the confusion!
