### ISSUE TITLE
Bug: [no-empty-interface] Resolving creates circular reference with `typeof`

### ISSUE THREAD

**Issue by 4LT** [typescript-eslint/typescript-eslint#5867]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.8.4&sourceType=module&code=JYOwLgpgTgZghgYwgAgLIE8CS5rycgb2QGcB7AWwjAAtQBzALmRAFdyAjaZAXwFgAoAQlIhiYZABMIwqHDDARyALyEBySaQAqtEI2QwWIBPMUAKGsGJMMqUlIA2ASlX916gPTuNJClR11kAHdgGmQAAwtiMLUeAW4AbgEBTxIIFGowMAAHK086EOoWdgA6YXJ3VGAEKFIyGDB3TXQsiABlauAshstiFghidwBGABYAdgBWUYEwZpQAfQxsSFhECAARaVJZExBlZBmW0hhJTe2FEET+FOI05Azs3Pd8miLSindyKpq6hqaW9qgnW6xF6-XcwwADOMAGxTfigZZ4FCLHArJAbGRyc7ICAAD0gIAkxGQCywqKRGK2WMUBD4gn4B2R6FsDj2KMRq2QADI0GSOejTtSLgIgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge3oFsbDbm+RNABmAQzKJ0UYdA7RI4MAF8QyoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
interface MyInterface { something: number }

const decoration = {
    doThing: function(this: MyModel) {
        // do something with `this`
    }
};

// see https://github.com/Microsoft/TypeScript/issues/14757
type _MyInterfaceDecoration = typeof decoration;
// see https://github.com/microsoft/TypeScript/issues/40567
interface MyInterfaceDecoration extends _MyInterfaceDecoration {}

type MyModel = MyInterface & MyInterfaceDecoration;
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-empty-interface": "error"
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

No errors/suggestions

### Actual Result

Line 12

>An interface declaring no members is equivalent to its supertype. 12:11 - 12:32

### Additional Info

Converting MyInterfaceDecoration to a `type` declaration creates a circular reference.  Arguably a TypeScript issue not being able to handle circular references "broken" by `typeof`

Disclaimer: Wasn't able to update packages to the latest versions, but I was able to re-create the issue with playground.  Versions listed reflect the playground

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.40.1` |
| `TypeScript`                           | `4.8.4` |
| `ESLint`                               | `8.15.0` |

**Comment by 4LT** [comment]
Turns out there's a much simpler solution to my problem:
```typescript
interface MyInterface { something: number }

class MyInterfaceDecoration {
  doThing(this: MyModel) {
    // do something with `this`
  }
}

const decoration = new MyInterfacceDecoration();

type MyModel = MyInterface & MyInterfaceDecoration;
```

in practice, I'd want to export `MyModel` and `MyInterface`, and leave `MyInterfaceDecoration` and `decoration` private to the module.

**Comment by JoshuaKGoldberg** [comment]
Fun use case - I hadn't seen https://github.com/microsoft/TypeScript/issues/40567 before, and just upvoted it.

In theory this issue makes sense & would be nice to fix. Unfortunately, doing so would require adding [type information](https://typescript-eslint.io/docs/linting/typed-linting "Linting with Type Information") to `@typescript-eslint/no-empty-interface`, which would make the rule much slower & block many ranges of users from using it.

Since this is a relatively uncommon edge case, I'd say your best bet is to use the `allowSingleExtends` option from https://typescript-eslint.io/rules/no-empty-interface/#options.

Thanks for filing though!

**Comment by JoshuaKGoldberg** [comment]
https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.41.0

![Indiana Jones reaching back under a closing stone door for his hat and barely making it](https://user-images.githubusercontent.com/3335181/197590739-61c0bc21-f4ea-4376-99b6-de2439d86391.gif)
