### ISSUE TITLE
Website: Add a happy message to playground output pane when no errors or AST

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5868]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

This is what the playground looks like when there are no code errors and _AST Viewer_ is disabled:

![Screenshot of the playground with no code or output](https://user-images.githubusercontent.com/3335181/197588046-c601bf9d-71d3-4b80-a9dd-1c2ae13f8dc2.png)

There's nothing to indicate that ESLint & TypeScript ran successfully and produced no complaints. Let's add a default message there when there isn't.

Maybe: `No ESLint or TypeScript messages created`? Or some more friendly version of that phrase?

### Affected URL(s)

https://typescript-eslint.io/play

**Comment by sviat9440** [comment]
![image](https://user-images.githubusercontent.com/13107421/197628117-0160c8aa-28b8-48f0-86bc-85258e757c5f.png)

**Comment by sviat9440** [comment]
Suggested messages: 
'All is ok!'
'No errors found'
'There are no errors'
