### ISSUE TITLE
Rule proposal: Don't return unions with `void` 

### ISSUE THREAD

**Issue by fregante** [typescript-eslint/typescript-eslint#5877]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

This is more of a question rather than necessarily a proposal:

- Do you think it ever makes sense for a function to return `string | void` rather than `string | undefined`?

The latter requires an explicit `return undefined` statement so I generally prefer the former. The drawback is that now I have `a = fn()` with type `string | void` and I can’t use `a!` to cancel out the type. 

### Fail Cases

```typescript
function getLuck(sky): string | void {
   if (sky === 'blue') {
      return 'good'
   }
}
```

### Pass Cases

```typescript
function getLuck(sky): string | undefined {
   if (sky === 'blue') {
      return 'good'
   }

   return undefined; // But unicorn/no-useless-undefined: Error
}
```

**Comment by sviat9440** [comment]
Void functions cannot return anything, so `string | void` return type is invalid. The rule `@typescript-eslint/no-invalid-void-type` prohibits this.

**Comment by fregante** [comment]
Good to see it exists! My config had it disabled so I'll try enabling it.

https://github.com/xojs/eslint-config-xo-typescript/blob/2a7e3b0b3c28b0c25866721298e67947a95767ab/index.js#L441-L442
