### ISSUE TITLE
Repo: Enable react/jsx-curly-brace-presence lint rule in website package

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5878]
### Suggestion

https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md

We don't yet have this lint rule enabled in the `packages/website` directory/package. But it'd be nice to have turned on!

**Comment by shogohida** [comment]
Hi @JoshuaKGoldberg, can I work on this? I'm new to typescript-eslint and found this issue with good first issue label so I want to solve it!

**Comment by JoshuaKGoldberg** [comment]
Absolutely, welcome aboard @shogohida! 🙌 

A little more detail on the issue:
* This issue is only about enabling a lint rule in our codebase. It's not about adding any new user-facing features
* JSX/React lint rules are only applicable in our `packages/website` package. Its eslint config is: https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/website/.eslintrc.js
* After enabling the rule in that file's `rules` object, there may be some new lint complaints in existing `.tsx` files. You'll need to fix those up to appease the rule.

Feel free to comment back here if any of that's unclear!

**Comment by shogohida** [comment]
@JoshuaKGoldberg 
Hi Josh! Thanks for giving me clear explanation!

I will try to implement all the necessary changes as soon as possible. I'll let you know when I need your help!

**Comment by shogohida** [comment]
@JoshuaKGoldberg 
I made a draft pull request but 2 tests (Header rules and Page changed) are still running after 12 hours.... How can I solve this problem?

https://github.com/typescript-eslint/typescript-eslint/pull/5894

**Comment by JoshuaKGoldberg** [comment]
Huh, must have been a transient issue with GitHub Actions. I see them as having passed now. 🤷
