### ISSUE TITLE
Mention eslint:recommended in eslint-plugin's README?

### ISSUE THREAD

**Issue by borekb** [typescript-eslint/typescript-eslint#588]
We were following [the README](https://github.com/typescript-eslint/typescript-eslint/blob/b5e95edbb811ba239d2856e9caee21e802fbd8fb/packages/eslint-plugin/README.md#usage) a bit too blindly and just copied this to our `.eslintrc.js`:

```js
extends: [
  'plugin:@typescript-eslint/recommended'
]
```

Only later we realized that this doesn't include any of the `eslint:recommended` rules :) Rookie mistake but we previously used TSLint which, if I remember correctly, set up everything.

I now realize that in the ESLint world, typescript-eslint is just piece of the puzzle but it was not immediately obvious to us. I'm not sure if we're an exception or not but maybe this could be mentioned in the README?

**Comment by bradzacher** [comment]
Be the change you want to see!
We love new contributors, and accept PRs from any and everyone, esp for small things like this.

**Comment by borekb** [comment]
Thanks :) Here: https://github.com/typescript-eslint/typescript-eslint/pull/591
