### ISSUE TITLE
Bug: [ban-types] <rule don't work>

### ISSUE THREAD

**Issue by koyoter** [typescript-eslint/typescript-eslint#5898]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.8.4&sourceType=script&code=MYGwhgzhAEBiD29oG8CwAoa0B2YC2ApgFzQQAuATgJbYDmA3BgL4YbDzbnQBm0AvDgIB3OIgAUASkbp2neCAIA6EPFpjui3ISmsZHLmX4om02RHlKVaslKA&eslintrc=N4KABGBEACAuCeAHApgZwMYCcCWjYFo0AbbAO1gHoAjAQ1PwRVUgC4wBtcCKZTTAe0yQANFwihu3SIzSswEyVIBi-fnMgARfqQDksMAFdUyMCv5gqydDSMns+7KkOlUNAGbIRYxZADyRABMAQQAFAEk5BUUpAFs0VwBzTzZIAFVjMAA5ZAB3ULCwMlRYZBoAr2jJSDdsAA8AdXsAC3VsvPDIb0kAX1FKqGBuuTcaImMusF6JyGRaktIAjWQRgyJYZjZYTANkb26uAF0QbqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
class Foo {
  name: string;
}

const f = new Foo();
console.log(f.name);

const t = {};
console.log(t);
```

### ESLint Config

```javascript
module.exports = {
  "@typescript-eslint/ban-types": [
    "error",
    {
      "types": {
        "Foo": "Don't use Foo because it is unsafe",
        "OldAPI": {
          "message": "Use NewAPI instead",
          "fixWith": "NewAPI"
        },
        "{}": false
      },
      "extendDefaults": true
    }
  ]
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

expected that the should report the error "Don't use Foo because it is unsafe".

### Actual Result

no error.

### Versions

| package | version |
| -- | -- |
| `@typescript-eslint/eslint-plugin` | `5.41.0` |
| `@typescript-eslint/parser` | `5.41.0` |
| `TypeScript` | `4.8.4` |
| `ESLint` | `8.15.0` |
| `node` | `web` |

**Comment by bradzacher** [comment]
The rule is called ban-***TYPES***. In your example your usages of `Foo` is as a ***VALUE***.

The rule does not match value usages. Please checkout the rule's documentation https://typescript-eslint.io/rules/ban-types/

Here are two other rules that may be of interest to you:
https://eslint.org/docs/latest/rules/no-restricted-globals
https://eslint.org/docs/latest/rules/no-restricted-imports

**Comment by koyoter** [comment]
Thank you. Much appreciated.
