### ISSUE TITLE
provide FlatESLint compatible configs

### ISSUE THREAD

**Issue by adrian-gierakowski** [typescript-eslint/typescript-eslint#5908]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Description

provide FlatESLint compatible configs

see:
https://eslint.org/blog/2022/08/new-config-system-part-1
https://eslint.org/blog/2022/08/new-config-system-part-2
https://eslint.org/blog/2022/08/new-config-system-part-3
https://github.com/eslint/eslint/issues/13481

### Impacted Configurations

alll

**Comment by bradzacher** [comment]
Based on https://github.com/eslint/eslint/issues/13481 - it looks like it's still *relatively* early days for this work and it's not truly "production ready" yet.
I don't think it's time to really move on this until they hit "Phase 3" of the plan.

They have a compatability system designed (and implemented) that will support our tooling for now.
https://eslint.org/blog/2022/08/new-config-system-part-2/#backwards-compatibility-utility

**Comment by bradzacher** [comment]
I'm going to close this for now as there's nothing we will be actioning at this time.
We'll chat with the ESLint folks and figure out a plan.
