### ISSUE TITLE
Bump minimum supported TS version to 4.2 to match DefinitelyTyped's 2y version support window

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#5914]
### Suggestion

Reference: https://github.com/typescript-eslint/typescript-eslint/issues/1752#issuecomment-1193377596

DefinitelyTyped only tests against and guarantees support for versions up to 2 years old - https://github.com/DefinitelyTyped/DefinitelyTyped#support-window

We talked about this a while ago but never got around to it - let's bump the minimum version in the next major.

This will allow us to delete a bunch of branches from our codebase reducing complexity and maintenance burden.

**Comment by JoshuaKGoldberg** [comment]
Would be good to add this to the upcoming maintenance guide too! #5238

**Comment by JoshuaKGoldberg** [comment]
#5915 is merged into #5886; closing this issue now accordingly. It'll be released as a part of the v6 major release.
