### ISSUE TITLE
Drop support for NodeJS v12

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#5917]
### Suggestion

https://github.com/nodejs/Release/blob/main/schedule.json#L66

NodeJS v12 was EOL 2022-04-30.
We also stopped testing on Node v12 in #5512 last month - so we don't even have signal if we have support!

**Comment by bradzacher** [comment]
As per https://github.com/typescript-eslint/typescript-eslint/pull/5886#discussion_r1019717517 by @bmish 

Let's make the dependency range `"^14.18.0 || ^16.0.0 || >=18.0.0"`
- `14.18` means we can switch our node lib imports to `'node:fs'`
- v17 is EOL, so no reason we should include it in our ranges still.

**Comment by bmish** [comment]
This issue should be closed. Not sure why GitHub didn't automatically close it.

**Comment by JoshuaKGoldberg** [comment]
Oh yeah, it's been not closing them when they're merged into `v6`. 🤷
