### ISSUE TITLE
Docs: new eslint.config.js - adapt all existing content to new flat config

### ISSUE THREAD

**Issue by revelt** [typescript-eslint/typescript-eslint#5938]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

The `eslint` [flat config](https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new) is generally available — no more `extends`. Let's adapt all our content for both the old and the new flat config. We'll need to add the alternative counterpart snippets and solve how to toggle between them.

Also, if there was a global toggle (in the nav let's say), user would not have to toggle each snippet.

On this occasion, it would be nice to supplement the _Custom rules > Testing_ section because there's no more `defineParser()`, and people might want few examples how to set up `let linter = new Linter({ configType: "flat" }); linter.verifyAndFix(str, [ ...` and how to test the plugin works on `esprima` and `@typescript-eslint/parser`. Ideally, we should link to more real-life plugin examples — simplistic `ruleTester ` ones, then more complex ones which use test file fixtures and double-check multiple parsers, `esprima` and `@typescript-eslint/parser`.

### Affected URL(s)

- [ ] https://typescript-eslint.io/docs/
- [ ] https://typescript-eslint.io/docs/linting/typed-linting
- [ ] https://typescript-eslint.io/docs/linting/typed-linting/monorepos
- [ ] https://typescript-eslint.io/docs/linting/configs
- [ ] https://typescript-eslint.io/docs/linting/troubleshooting — add a new entry to explain the situation and common errors; adapt [this comment's](https://github.com/eslint/eslint/issues/15453#issuecomment-1001200953) examples for async `require` for CJS users

**Comment by bradzacher** [comment]
See #5908
Whilst the flat config is "generally available" it's not actually finished yet. People adopting it now are really "early adopters" and are testing what is still an experimental API.

There's a lot we as a project want to do to truly support flat configs and provide the best possible devx we can.

As a project we're not going to move on any of the flat config related work (including documentation) until we've partnered with ESLint core in "phase 3" of their plan (https://github.com/eslint/eslint/issues/13481) and solidified support from both sides.
