### ISSUE TITLE
Rule docs on website should show the latest version, not what's in the main branch

### ISSUE THREAD

**Issue by sindresorhus** [typescript-eslint/typescript-eslint#5939]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I wasted a lot of time now because I thought the `fixStyles` option for the `consistent-type-imports` rule here was available in the latest release since it's shown on the website: https://typescript-eslint.io/rules/consistent-type-imports/#fixstyle

It's expected that a website shows docs for the latest available release, not what's in the main branch.

### Affected URL(s)

https://typescript-eslint.io/rules/

**Comment by lsagetlethias** [comment]
Same as the playground that should not used the main branch but the last release. ([eslint playground](https://typescript-eslint.io/play/#ts=4.8.4&sourceType=module&code=JYWwDg9gTgLgBAbzgVwM4FMDCBDANrgI2wGMBrOAXzgDMoIQ4AiKdEmRgbgChRJY4ASq2Lxa9JizacuXACbpiubCzjEIAO1TxsALwBcKDDnxEyHIA&eslintrc=N4KABGBEBOD2sBdIC4wOgVwKYBpxSwA8EsA7AEwGcUwBtfCSLSgGwEtSFlosBjWALYCy5LOUj4AunkaYWzGqAiMAAggCeAB2a9obTQgC0zdpwD0-UpTaUSnQxu2G2AzbGgJqqesuVNocNCQMr5gSqERkABmbIQAyhryNJAcplgOWukubh7UDMoAvvmS+EUFQA&tsconfig=N4KABGBEAmCWDOAHANgQwJ6QFxQHIFMAPAFwDoAreSAGnCgGMB7AW0VmXwCcB5RY2RgDsqOUBAiRiqTgHN8xbFHzwArDToTksAEaKA2hvEwW68UegtSsYl1TaOps0viCiCwwF1aZyKmTJGAHcAKREwYk4AV3xvI3gAa1hEABkdAGEAC3x6eMUI6NiJeAjYegUcfJjDSAAzRk56fDSheAQbQWI01FbBGQBJQQAxdnxcVGZlPKiqn0FGAFFmaymC6uUAWUZoSI4Bm05GRBWZo2YtnfxFSGVXEkcJM+2OACVlRmRI-iEruehLwqgnDeyAAbvhQkJNk9LhVpgDIAh3qgbNAoRcwpV4ZRCFdEED4FwwfcoLBBPQgRMOn5jvCUJEZKSwgYnGAxCyoIJxjCOW5IIYIABfTx0IUCoA))
Really confusing.

**Comment by Josh-Cena** [comment]
The release script is not public, so I'm going to let @JoshuaKGoldberg do it. Basically we just need to run `yarn docs:version` during release.

**Comment by JoshuaKGoldberg** [comment]
I'm working on this now. Plan is to:
1. Short term: have Netlify pull from a `docs` branch that's only updated on releases
2. Long term: look into [Docusaurus versioning](https://docusaurus.io/docs/versioning) or a similar system

**Comment by JoshuaKGoldberg** [comment]
Ok, the website should be pinned to the latest _stable_ released version now. #6055 will add an explicit version number to it too, but this issue is technically resolved. So I'll close it now.

Thanks for posting @sindresorhus, @lsagetlethias, and everyone who 👍d! Please let us know in new issues if there are any other website bugs or features you'd like to see. ❤️
