### ISSUE TITLE
Website: Add IDs to the homepage's <h2>s

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5949]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

The homepage of the website has a few sub-headings on it:

* _What are ESLint and TypeScript, and how do they compare?_
* _Why does this project exist?_
* _Financial Contributors_

...but because we've styled these as custom React components instead of using typical Docusaurus pages, they aren't assigned `id`s automatically. That means you can't provide a `#` hash link to them natively, like `https://typescript-eslint.io#financial-contributors`.

Proposal: let's add an explicit `id` attribute to each heading?

```diff
- <h2>Financial Contributors</h2>
+ <h2 id="financial-contributors">Financial Contributors</h2>
```

Example source in code: https://github.com/typescript-eslint/typescript-eslint/blob/1cc35d3af0b001667e01d6a6c453bc7a8e627416/packages/website/src/pages/index.tsx#L164

### Affected URL(s)

https://typescript-eslint.io

**Comment by armano2** [comment]
fixed by #5951
