### ISSUE TITLE
Docs: Add info on website development to DEVELOPMENT.md

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5956]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

https://github.com/typescript-eslint/typescript-eslint/pull/5951 shows that our DEVELOPMENT.md docs don't explicitly state:

* How to `yarn start`
* Where it's ok to `yarn` / `yarn install` from
    * In theory `yarn install` isn't location-dependent, but the resultant `yarn build` from running it in the root of the repo is important because 👇 
* That you have to `yarn build` dependent packages

### Affected URL(s)

Just https://github.com/typescript-eslint/typescript-eslint/blob/75dcdf164d206c5530ba7cc095c4599ec90abe35/DEVELOPMENT.md for now, until #5824 lands and it's surfaced on the website.

**Comment by Josh-Cena** [comment]
I assume it's fixed, given https://typescript-eslint.io/contributing/local-development#website-development. It's brief but should get things working.
