### ISSUE TITLE
Bug: [class-literal-property-style] A literal getter with a setter does not pass lint, and incorrectly auto-fix

### ISSUE THREAD

**Issue by sviat9440** [typescript-eslint/typescript-eslint#5961]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.8.4&sourceType=module&code=MYGwhgzhAEAqCmEAu0DeBYAUNaF4oDcwQBXeACiJAC5ckAnASwDsBzASjSxxwHpfoAOmHdoAXyyjW+aFTLl2tZEzZdsPevhL1m0AORJESPQG5REzGKA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6M+AQ2WVsf0TRO8WsWgB7UtCK1kRJOiiCJ0SODABfEBqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUjoAHoizJ46IngCGqACL9YmNXl3Cwo9FIC+IM0A

### Repro Code

```typescript
class Test {
  set value(val: string) {
    // ...
  }

  get value(): string {
    return 'test';
  }
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/class-literal-property-style": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true,
    "experimentalDecorators": true
  }
}
```

### Expected Result

Should be no errors because the setter exists

### Actual Result

Error: `Literals should be exposed using readonly fields.`

Auto-fix: 

```
class Test {
  set value(val: string) {
    // ...
  }

  readonly value = 'test';
}
```

Then TypeScript error:
``` Duplicate identifier 'value'```

### Versions

| package | version |
| -- | -- |
| `@typescript-eslint/eslint-plugin` | `5.42.1` |
| `@typescript-eslint/parser` | `5.42.1` |
| `TypeScript` | `4.8.4` |
| `ESLint` | `8.15.0` |
| `node` | `web` |

**Comment by bradzacher** [comment]
why do you have a getter with a constant value and a setter?
that really looks like a code smell, TBH.

**Comment by bradzacher** [comment]
I'm happy for this rule to be upgraded to be smarter such that it doesn't error if there is a setter of the same name defined on the class.
