### ISSUE TITLE
Docs: `sort-type-union-intersection-members` deprecation message is circular

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [typescript-eslint/typescript-eslint#5963]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

`sort-type-union-intersection-members` was renamed to `sort-type-constituents`. Currently the page links to itself.

### Affected URL(s)

https://typescript-eslint.io/rules/sort-type-union-intersection-members

**Comment by JoshuaKGoldberg** [comment]
🤔 I don't know why merging #5970 didn't close this. I think there was a GitHub bug at the time.
