### ISSUE TITLE
Drop support for ESLint v6

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#5968]
### Suggestion

Just like we did in our v5 release (https://github.com/typescript-eslint/typescript-eslint/issues/2465).

Most users should have have migrated off of v6 by this point, and I think a year back is far enough for us to support.
Supporting old versions restricts which APIs we can use, and makes it harder to build extension rules as we have to take care to fill in missing messageIds ourselves.

ESLint v8.0.0 was released 10 October 2021 - over 1 year ago.
ESLint v7.0.0 was released 09 May 2020 - over 2 years ago.
ESLint v6.0.0 was released 21 June 2019 - over 3 years ago.

**Comment by JoshuaKGoldberg** [comment]
#5972 was merged, so this will be resolved in the next major version.
