### ISSUE TITLE
Repo: Raise tsconfig target

### ISSUE THREAD

**Issue by bmish** [typescript-eslint/typescript-eslint#5980]
### Suggestion

Consider whether we should raise tsconfig [target](https://www.typescriptlang.org/tsconfig#target) / [lib](https://www.typescriptlang.org/tsconfig#lib) from ES2017 to something higher. 

https://github.com/typescript-eslint/typescript-eslint/blob/91d71bcf6b2f822116d25b281e289fe1d5005401/tsconfig.base.json#L16-L17

We're already planning to increase requirements for v6 including:

* https://github.com/typescript-eslint/typescript-eslint/pull/5972 (released 2019)
* https://github.com/typescript-eslint/typescript-eslint/issues/5917 (released 2019, EOL 2022)
* https://github.com/typescript-eslint/typescript-eslint/pull/5915 (released Feb 2021)

This all seems to indicate people would have a relatively modern environment to run TypeScript linting in.

The newest possible we could use is `ES2021`, is that too new or is there any reason we couldn't use that?

This may be a breaking change that could be included with v6 (https://github.com/typescript-eslint/typescript-eslint/pull/5886).

**Comment by JoshuaKGoldberg** [comment]
Seems reasonable to me! Agreed on including it in v6 just to be safe.
