### ISSUE TITLE
[no-dupe-class-members] Cannot turn off rule

### ISSUE THREAD

**Issue by twhitbeck** [typescript-eslint/typescript-eslint#599]
**Repro**

https://gist.github.com/twhitbeck/0235fc09ee7076a4f60a5c42107e73d2

**Expected Result**
Running `yarn lint` should succeed

**Actual Result**
Running `yarn lint` fails with errors because of rule `no-dupe-class-members` even though that rule is turned off.

**Additional info**
I did verify that this is not an issue with a vanilla js project with same version of eslint and using `{ "extends": ["eslint:recommended"], "rules": { "no-dupe-class-members": "off" } }`.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.9.0` |
| `@typescript-eslint/parser`        | `1.9.0` |
| `TypeScript`                       | `3.5.1` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `12.3.1` |
| `npm`                              | `6.9.0` |

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/pull/520

This has been fixed in master, but hasn't been released yet.
You can manually patch your repo with the above PR fix, or use the `canary` tag on NPM
