### ISSUE TITLE
Rule proposal: consistent readonly `TSTypeLiteral` (`readonly` keyword vs `Readonly<T>`)

### ISSUE THREAD

**Issue by RebeccaStevens** [typescript-eslint/typescript-eslint#6004]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Require consistently using either `readonly` keywords or `Readonly<T>` for `TSTypeLiteral`.

### Fail Cases

```typescript
// When enforcing `Readonly<T>`
type Foo = {
  readonly bar: string;
  readonly baz: number;
};

// When enforcing `readonly` keyword
type Foo = Readonly<{
  bar: string;
  baz: number;
}>;
```

### Pass Cases

```typescript
// When enforcing `Readonly<T>`
type Foo = Readonly<{
  bar: string;
  baz: number;
}>;

// When enforcing `readonly` keyword
type Foo = {
  readonly bar: string;
  readonly baz: number;
};

// Should never be flagged
type Foo = {
  bar: string;
  readonly baz: number;
};
```

### Additional Info

- The rule should apply to all `TSTypeLiteral` nodes.
- The rule should have a fixer.

Note: This proposed rule is similar to the [`array-type`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/array-type.md) rule.

### Additional Question

When working with deeply readonly records, should there be an option to allow for use of `ReadonlyDeep` (or another wrapping type) instead of wrapping each level with `Readonly`?

**Comment by RebeccaStevens** [comment]
This library already has the rule `prefer-readonly-parameter-types`. As that rule can be satisfied with either of these approaches, wouldn't it be best to have a way to enforce which approach is used?

> For TS it's so common to use interfaces, not type aliases

I've noticed that those that enforce a more functional (fp) codebase, interfaces are used a lot less than type aliases.

Personally, I never use interfaces unless I need to use declaration merging.

> it's really quite uncommon for TS users to bother marking anything readonly from what I've seen - so it's reasonably rare that people even reach for Readonly<T> or readonly.

Although this is pretty true, I believe we should really be encouraging users to use readonly types where it makes sense. Providing a rule to help keep things stylishly consistent (like with `array-type`) should help lessen friction.

On a side note: Any library providing a TS API for users should always use readonly types with that API (unless they are actually mutating the data).

I was originally thinking of just adding this rule to [`eslint-plugin-functional`](https://github.com/eslint-functional/eslint-plugin-functional) but I thought it was broad enough to be here, thus why I opened the issue.

**Comment by JoshuaKGoldberg** [comment]
Thinking more: I'm personally in favor of having a rule _in general_* just to be able to enforce consistency. For rules like the aforementioned `array-type`, it's nice to be able to keep it the same across your codebase. And, also like `array-type`, when there's a clearly community-preferred syntax, it's nice to be able to include that preference in a recommended config.

*But, strongly functional/immutable/readonly patterns are so rare to see in most TypeScript codebases (😢), it's not something I think we can justify spending time on in this repo. +1 to:

> I'm not sure if this meets the bar of "useful to the broader TypeScript community" for these reasons.

Thanks for bringing this up though @RebeccaStevens! If you ever want more folks working on adding rules like this one -heck, especially this one!- to [eslint-plugin-functional](https://github.com/eslint-functional/eslint-plugin-functional), please tag me and I'll try to find time to help out 😄.
