### ISSUE TITLE
Outdated peer dependency in @typescript-eslint/eslint-plugin

### ISSUE THREAD

**Issue by billyjanitsch** [typescript-eslint/typescript-eslint#601]
The recently-published @typescript-eslint/eslint-plugin@1.10.1 still peer-depends on @typescript-eslint/eslint-parser@1.9.0:

https://github.com/typescript-eslint/typescript-eslint/blob/729c7602233f3f9d05323143fc0da2234730d43f/packages/eslint-plugin/package.json#L55-L56

I assume this is a mistake since @typescript-eslint/eslint-parser@1.10.1 was also just published:

https://github.com/typescript-eslint/typescript-eslint/blob/729c7602233f3f9d05323143fc0da2234730d43f/packages/parser/package.json#L3

This means that `npm install -D @typescript-eslint/eslint-plugin @typescript-eslint/eslint-parser` yields a missing peer dependency warning.

This could be fixed either by updating the peer dependency to 1.10.1 (and generally keeping these in sync) or by specifying the peer dependency as a caret version range (e.g. ^1.9.0).

Thanks!

**Comment by JamesHenry** [comment]
Thanks for catching this @billyjanitsch
