### ISSUE TITLE
Bug: [prefer-optional-chain] Unexpected member property type: ThisExpression

### ISSUE THREAD

**Issue by sviat9440** [typescript-eslint/typescript-eslint#6024]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.8.4&sourceType=module&code=MYGwhgzhAECC0G8CwAoa0DEYDcr0YCNcU9oBbAUwBcALAewBMAKASkVPQEsAzaJgQlqcIAOizQAPhOiCawsQTbI06VQCdqAVzUA7YqugBfUsZSmgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WloHsalfkwCG8WmQAWo5uii9o-aJHBgAviHVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUjoAHoizJ46IngCGqACL9YmNXl3Cwo9FIC+IM0A

### Repro Code

```typescript
class A {
  #a;
  #b;

  method() {
    if (!this.#a || !this.#b) {
      return;
    }
  }
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/prefer-optional-chain": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true,
    "experimentalDecorators": true
  }
}
```

### Expected Result

No errors

### Actual Result

Unexpected member property type: ThisExpression

### Additional Info

This is a regression of 5.43.0. In version 5.42.1 all works correctly.
I suppose it was a consequence of these changes: #5594 @omril1

### Versions

| package | version |
| -- | -- |
| `@typescript-eslint/eslint-plugin` | `5.43.0` |
| `@typescript-eslint/parser` | `5.43.0` |
| `TypeScript` | `4.8.4` |
| `ESLint` | `8.15.0` |
| `node` | `web` |

**Comment by omril1** [comment]
@JoshuaKGoldberg I'm on it

**Comment by yovanoc** [comment]
Any news on this?

**Comment by JoshuaKGoldberg** [comment]
@yovanoc per https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md -> https://typescript-eslint.io/contributing/issues#commenting, please don't comment on issues asking for updates. We're a small maintenance team and we make progress when we can. Bumping issues like this just spams the thread and doesn't make them get done faster.

That being said, this issue has a pending PR at #6028. So you can follow along with that PR for progress if you want. 🙂

**Comment by yovanoc** [comment]
@JoshuaKGoldberg Thanks for the pending PR to follow. Meanwhile it was not to urge the team. Sorry for not being clear.

**Comment by JoshuaKGoldberg** [comment]
No worries!
