### ISSUE TITLE
Docs: Maintenance > Bumping the Babel version

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6027]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Right now the `@babel/*` versions in our `package.json` are out of date, behind e.g. `@babel/code-frame@7.18.6`:

https://github.com/typescript-eslint/typescript-eslint/blob/97d3e56709ee19fdec39fd8b99d080db90b306e9/package.json#L52-L55

I'm also seeing in [`fixtures-to-test.ts`](https://github.com/typescript-eslint/typescript-eslint/blob/97d3e56709ee19fdec39fd8b99d080db90b306e9/packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts) that there are some ignored fixture files due to previously filed Babel issues that have since been resolved:

https://github.com/typescript-eslint/typescript-eslint/blob/97d3e56709ee19fdec39fd8b99d080db90b306e9/packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts#L477

https://github.com/typescript-eslint/typescript-eslint/blob/97d3e56709ee19fdec39fd8b99d080db90b306e9/packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts#L514

When I update the `@babel/*` packages to latest, remove those `ignore`s, and run `typescript-estree` tests, there are snapshot failures in `typescript/expressions/instantiation-expression.src.ts`. https://github.com/typescript-eslint/typescript-eslint/actions/runs/3490803456/jobs/5842786077

```plaintext
             91 |     // Received = Babel, Expected = TSESTree
           > 92 |     expect(babelAst).toEqual(tsestreeAst);
```

It'd be helpful to have the system of fixtures and snapshots documented. In particular I'd like to document what to do when these discrepencies show up in a package bump or AST fix.

#5885 is another example of where the docs would be helpful.

Edit: some context here too: https://github.com/typescript-eslint/typescript-eslint/pull/5717#pullrequestreview-1185296800, https://github.com/typescript-eslint/typescript-eslint/pull/5926#issuecomment-1319540963

### Affected URL(s)

https://typescript-eslint.io/docs/maintenance/package-updates, maybe?

**Comment by bradzacher** [comment]
ideally we should be moving all of our fixture tests to `ast-spec` where all of this stuff is handled and reported automatically.

In a future state we would have all of the fixtures moved and then an upgrade should just be like:
```bash
$ yarn add -DW @babel/core @babel/parser @babel/eslint-parser
$ (cd packages/ast-spec && yarn test -u)
$ git commit -a -m "chore: bump babel dependency"
```

**Comment by JoshuaKGoldberg** [comment]
Marking as blocked on #6065 so we don't spend time documenting the old flow.
