### ISSUE TITLE
not use non-public api: "eslint/lib/util/traverser"

### ISSUE THREAD

**Issue by aladdin-add** [typescript-eslint/typescript-eslint#603]
```bash
Failed to load parser '@typescript-eslint/parser' declared in '--config » ../../../index.js » plugin:@typescript-eslint/recommended » ./configs/base.json': Cannot find module 'eslint/lib/util/traverser'
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.10.2` |
| `@typescript-eslint/parser`        | `1.10.2` |
| `ESLint`                           | `6.0.0-rc.0` |

**Comment by mysticatea** [comment]
This is a duplicate of #563 :)

**Comment by JamesHenry** [comment]
Thanks @aladdin-add, as @mysticatea indicates, please subscribe to the other issue for updates
