### ISSUE TITLE
Rule rename: no-array-constructor -> array-constructor

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6034]
## Overview

Porting context from #6022 > https://github.com/typescript-eslint/typescript-eslint/discussions/6022#discussioncomment-4168862:

> A number of the `no-` rules make sense as things that won't be turned on and have no inverse, so a blanket rule against `no-` prefixes is a bad idea.
> I agree though that it makes sense for us to advise against that naming if it's feasible that we will add inverse functionality to a rule.

[`@typescript-eslint/no-array-constructor`](https://typescript-eslint.io/rules/no-array-constructor) is mentioned as a potential rule to rename:

> * has no inverse
> * maybe should be renamed though because it sounds like you shouldn't use any array constructors, when it's only enforcing correct usage.

Personally, I'm on the fence of whether a different name would be better, and don't mind either way. Which makes me lean slightly towards keeping it the same, just to reduce changes.

@bradzacher, did you have a different name in mind?

**Comment by bradzacher** [comment]
Yeah it's probably a rename that would need to be upstreamed
In terms of naming - probably should be something like `prefer-array-literal`

**Comment by JoshuaKGoldberg** [comment]
Copying from @nickmccurdy's https://github.com/typescript-eslint/typescript-eslint/discussions/6022#discussioncomment-4168868: 

> Can we at least keep the `no-` prefix for extension rules? I don't think the benefits of simplifying the APIs apply to rules that are already in ESLint, and this makes migrating from ESLint rules more confusing.

I agree that it's confusing for users. Since unlike `(no-)return-await` we don't have options to invert it, I'm going to close this out. Thanks all!
