### ISSUE TITLE
Rule rename: no-extraneous-class -> no-class-as-namespace

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6035]
## Overview

Porting context from #6022 > https://github.com/typescript-eslint/typescript-eslint/discussions/6022#discussioncomment-4168862:

> A number of the `no-` rules make sense as things that won't be turned on and have no inverse, so a blanket rule against `no-` prefixes is a bad idea.
> I agree though that it makes sense for us to advise against that naming if it's feasible that we will add inverse functionality to a rule.

[`@typescript-eslint/no-extraneous-class`](https://typescript-eslint.io/rules/no-extraneous-class) is mentioned as a potential rule to rename:

> * I doubt anyone would ever want the inverse of this unless they absolutely love java.
> * would be good to rename this so it's clearer though (no-class-as-namespace?)

Personally, I slightly prefer `no-extraneous-class` because it directly implies that the practice is bad. `no-class-as-namespace` just says what the practice is, without that explicit negative connotation. But maybe that's just me - posting this issue to hear other folks' thoughts!

**Comment by bradzacher** [comment]
Personally I'm also happy to keep it as is - i don't think there's enough value to be gained by renaming it given the churn it would introduce!
