### ISSUE TITLE
Website: [Playground] Add "copy as JSON" option to AST Viewer

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6037]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

The AST Viewer part of the playground can have a lot of objects in it:

<img width="581" alt="Screenshot of a console.log('Hello, world!') ESTree AST on the playground in the viewer" src="https://user-images.githubusercontent.com/3335181/202834404-8d2f7a24-59c7-4551-849e-3cd1998f1785.png">

It'd be nice to add a little _Copy as JSON_ button to the bottom of the AST viewer that copies its contents as a string to the user's clipboard.

### Affected URL(s)

https://typescript-eslint.io/play

**Comment by Josh-Cena** [comment]
Curious what the use case is?

**Comment by JoshuaKGoldberg** [comment]
I've personally wanted this a few times when writing docs for a page. Also @armano2 had left this as a todo in https://github.com/orgs/typescript-eslint/projects/3. 🤷
