### ISSUE TITLE
Bug: [no-base-to-string] improve error message for unknown types

### ISSUE THREAD

**Issue by matthew-dean** [typescript-eslint/typescript-eslint#6047]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=DYUwLgBCBO0PbQLIgM4oIYHMQC4IrGgEsA7TAKAGM4SCpYEB5AIwCsIBeCAKQGVGAcgDoADumgoQACgDkAbwgAiALaoM2RXkUBRBtAiq0WEIoC+MgJRUadGPGgA1dMACuqThBasQlMEIBuzm4oUnZMbFbkRABmEKF6Tq6oANoADAC6FhBy5BD09shG2B4ABgAkcmGOQSkZpiXkpkA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oCMBDZRLXxdk+KkwDm6MACZwYAL4gFQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
let errorMessage: string
const errorObj = JSON.parse('{ "message": "Error message"}')
const errorValues = Object.values(errorObj)

if (errorValues[0]) {
  errorMessage = `${errorValues[0]}`
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-base-to-string": 2
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
  }
}
```

### Expected Result

'errorValues[0]' may evaluate to '[object Object]' when stringified

### Actual Result

'errorValues[0]' will evaluate to '[object Object]' when stringified

### Additional Info

After upgrading to 4.9.3 and latest typescript-eslint, there were a lot of confusing errors of this nature for anything being returned as an unknown type. The rule is asserting that it **_will_** evaluate to '[object Object]', when the truth is it **_may_** evaluate to '[object Object]'. ESLint doesn't actually know because it is unknown. This is confusing because this rule leads the dev to believe that `unknown` is synonymous with `object` at runtime.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.43.0` |
| `@typescript-eslint/parser`            | `5.43.0` |
| `TypeScript`                           | `4.9.3` |
| `ESLint`                               | `8.20.0` |
| `node`                                 | `16.17.1` |

**Comment by Josh-Cena** [comment]
Technically, everything is a "may", because TS doesn't forbid excess keys, so even if a type doesn't declare it has a `toString` method, it may actually have one at runtime. We only issue the "may" message in case it's a union where some constituents are known to be good—that's a more certain case.

**Comment by matthew-dean** [comment]
@Josh-Cena Okay. Is there a different way you would improve this error message so it doesn't assert that `unknown` will result in that output?

**Comment by Josh-Cena** [comment]
Hmm, what about changing the "more certain" message to "is likely to evaluate to '[object Object]' when stringified"? The idea is that there's no case where it _provably doesn't_ stringify to `[object Object]`, but I'm not sure either, because we either change it for all types, or we don't change it at all—`unknown` is not any different from `{}` or `{ a: number }`.

**Comment by bradzacher** [comment]
Josh is correct, TS's structural typing object model only deals in inexact objects.

This means it's entirely possible to under-specify an object:

```ts
declare const foo: {a: string, toString(): string};

function acceptsA(obj: {a: string}) {
  return `${obj}`;
}

acceptsA(foo);
```
[playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPAN5SGYwCWKA5gDTwZIDKGlNAFAJRmtXUC+AbgBQw7AFcUYDBVTwoYMCAAOGNAEF2SAEYArQiR5sBnYsPgX4cDOJgp4AAwAkRHbv4OR-UQqWqN7LhInIJAA)

So even cases where the types look like they'll prong a bad thing can be fine.

Similarly cases that look like they should be fine won't always be fine:

```ts
declare const foo: {a: string};

function acceptsA(obj: {a: string, toString(): string}) {
  return `${obj}`;
}

acceptsA(foo);
```
[playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPAN5SGYwCWKA5gL4DcAUI9gK4pgYWrxRhggADhjQBBABRIARgCtCJMhko0ANPAxIAykqrVxASkXK6+4o3gX4cDKxgp4AAwAkRaTNoOmtZnwHCx4rhI+kxAA)

The rule is really best effort and is sadly not always going to be correct in either direction. I think that being strict in the error message for cases like `any` or `unknown` is best for consistency.
If you think we should be loose for those types, then IMO we should just remove "will" from the rule entirely as I've shown above - but I don't think I've seen a strong enough argument that that would be a good idea that nets any real clarity benefits.

**Comment by Josh-Cena** [comment]
What about "this object may stringify to '[object Object]'" plus "this type union has some constituents may stringify to '[object Object]'"? Or do you feel like that's a leak of abstraction?

**Comment by bradzacher** [comment]
A minor change like that doesn't seem that much clearer, IMO. I would say that if we're going to make any change - specifying error messages for each case (any/unknown/never, union, object without toString) would be the best course of action if we wanted to improve things and make everything clear as possible.

But again - I ***personally*** only see very, minor clarity improvements from that. On the other hand it would require quite a bit of extra logic to emit. Not sure if it's worth the effort and complexity / maintenance overhead? I'm not going to block if someone feels strongly, just voicing my concern.

**Comment by Josh-Cena** [comment]
I don't have great ideas either, and I'd prefer someone to suggest in this thread before opening a PR, if they want to improve.

**Comment by JoshuaKGoldberg** [comment]
Looks like this issue aged away. If anybody has a suggestion for an error message that satisfies the discussion without adding lots of extra logic, please do post back or file a new issue. Thanks everyone!

**Comment by matthew-dean** [comment]
> Not sure if it's worth the effort and complexity / maintenance overhead?

It was literally proposing just changing one word to improve semantics? 🤔

**Comment by Josh-Cena** [comment]
Yeah, @JoshuaKGoldberg I see https://github.com/typescript-eslint/typescript-eslint/labels/awaiting%20response as "awaiting suggestions from the community", not "we are not willing to do anything about it". Might want to keep this open instead of getting two duplicated issues.

**Comment by JoshuaKGoldberg** [comment]
Oh funny I'd interpreted it differently - as awaiting response from one specific author. Makes sense to reopen then if that's the intent.

**Comment by bradzacher** [comment]
> instead of getting two duplicated issues

To be fair - this issue has been open for 5 months with no reactions and no other community commenters, and the rule itself has existed for over 3 years and this is the first time someone has mentioned it.

Altogether theres little signal to suggest the community shares the sentiment or that we'll get another issue about this.

**Comment by matthew-dean** [comment]
Probably no reaction because such a small change? What's the downside? It's just clearer language. 🤷‍♂️

**Comment by bradzacher** [comment]
This issue has been open for 3 months and has not received any community engagement.
As such - we're taking this as signal that this is not important to the broader community, and so we are rejecting this proposal. Thanks for filing!
