### ISSUE TITLE
Rule proposal: Prefer `unknown` instead of `any` whenever possible

### ISSUE THREAD

**Issue by sindresorhus** [typescript-eslint/typescript-eslint#605]
I would like to enforce using `unknown` instead of `any` whenever possible for stricter typing.

## Fail

```ts
function foo(x: any) {}

function foo(): any {}
```

## Pass

```ts
function foo(x: unknown) {}

function foo(): unknown {}
```

## Exceptions

There are a couple of exceptions:

- For function arguments and assignment, `{[key: string]: any}` cannot be enforced into `{[key: string]: unknown}`, because it has special behavior:
	> The index signature `{[key: string]: any}` in TypeScript behaves specially: it’s a valid assignment target for any object type. This is a special rule, since types with index signatures don’t normally produce this behavior.
- For `new(...args: any[])`, I remember it not working when I tried to use `unknown` there.

There might be more exceptions I haven't thought of.

---

Because of the above exceptions, I cannot use the `@typescript-eslint/ban-types` rule for this.

**Comment by bradzacher** [comment]
There's `no-explicit-any` which will ban `any`, could add an option to that to suggest fixing to `unknown` where possible?

**Comment by sindresorhus** [comment]
@bradzacher That could work, but what about the mentioned exceptions?

**Comment by bradzacher** [comment]
Have you got an example for the special case second one?
I was looking and it seems like it works? [an example](https://www.typescriptlang.org/play/#src=interface%20TConstructor%20%7B%0A%20%20new%20(...args%3A%20unknown%5B%5D)%0A%7D%0A%0Afunction%20foo%3CT%20extends%20TConstructor%3E(x%3A%20T%2C%20...args%3A%20T%20extends%20%7Bnew%20(...args%3A%20infer%20TArg)%7D%20%3F%20TArg%20%3A%20never)%20%7B%0A%20%20const%20foo%20%3D%20new%20x()%3B%0A%7D%0A%0Aclass%20Foo%20%7B%0A%20%20constructor(a%3F%3A%20string)%20%7B%0A%0A%20%20%7D%0A%7D%0A%0Aconst%20x%20%3D%20foo(Foo%2C%20'a')%3B%0A)

----

We can code them into the rule either as explicit, always-on handling, or via an option.

I.e. could add option like `allowSpecialIndexSignature` or something which specifically allows the `{[k:string]:any}` case.

We could also add an option like `fixWithUnknown` which turns on a fixer to convert `any` to `unknown` in all matching cases.

**Comment by JamesHenry** [comment]
The related PR for this was merged so I'm going to close this one
