### ISSUE TITLE
Bug: [@typescript-eslint/no-unused-vars] not collect used types on satisfies operator

### ISSUE THREAD

**Issue by YuseiUeno** [typescript-eslint/typescript-eslint#6057]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&jsx=true&sourceType=module&showAST=es&code=C4TwDgpgBAwg9gGzgJwM5QLxQETIgE2ygB8cBzPCAOyNOwCMEBXCbAbgCgPRIoAlAOIAhTFADaefAC4oVJgFt6EZABooFCNRlzFytYxbaFS5AF1OHAMZwqqYFDABDBBGDBoWAN4coUSTLEAJgBWYLUABgjTFR91SioZbABicPCAMzTU7BjfAwgAyKhCkODTDgBfKFRHYABLVDTaiHQ+CGtkfAAeeCQ0NTtkWqoyEn5hAD42IA&eslintrc=N4KABBYEQE4K4BsCmBnKAuMpI8lAdgPYC0c+cKSAJsQG4CGMamUhAZm1ADTi45QABAC4BPAA6oAxjACWYocVQIZ+IQHoipcpRoMmGaAHdG+KLwgBfEBaA

### Repro Code

```typescript
type Colors = "red" | "green" | "blue";
type RGB = [red: number, green: number, blue: number];
// Above types error by @typescript-eslint/no-unused-vars

const palette = {
  red: [255, 0, 0],
  green: "#00ff00",
  blue: [0, 0, 255]
} satisfies Record<Colors, string | RGB>;
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
          "no-unused-vars": "off",
          "@typescript-eslint/no-unused-vars": "warn"
  },
};
```

### Expected Result

To collect use type if use on satisfies operator

### Actual Result

error  'Colors' is defined but never used  @typescript-eslint/no-unused-vars
error  'RGB' is defined but never used     @typescript-eslint/no-unused-vars

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.44.0` |
| `@typescript-eslint/parser`            | `5.44.0` |
| `TypeScript`                           | `4.9.3` |
| `ESLint`                               | `8.28.0` |
| `node`                                 | `18.12.1` |

**Comment by Josh-Cena** [comment]
As always—new syntax needs updates to the scope manager. I really wish this can be done as part of the parser update.

**Comment by bradzacher** [comment]
Forgot this when I merged support for satisfies.
It's too easy to forget this when we're adding new syntax!
Unfortunately I don't know if there's a good way to catch this ahead of time..

**Comment by Josh-Cena** [comment]
Add it to the TS release tracking issue template? ^^
