### ISSUE TITLE
Parser mishandling comments in jsx including //.

### ISSUE THREAD

**Issue by Thiry1** [typescript-eslint/typescript-eslint#606]
```ts
const parser = require('@typescript-eslint/typescript-estree');
const code = `
  <div>
    <div>hello</div>
    // This is not a comment.
  </div>
`;
const ast = parser.parse(code, {
    jsx: true,
    comment: true,
});
return ast.comments;
```

**What did you expect to happen?**
`[]` is returned.

**What actually happened?**
`[ { type: 'Line',
    value: ' This is not a comment.',
    range: [ 34, 59 ],
    loc: { start: [Object], end: [Object] } } ]` is returned.
**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `1.10.2` |
| `TypeScript`                           | `3.5.1` |
| `node`                                 | `11.9.0` |
| `npm`                                  | `6.9.0` |

**Comment by bradzacher** [comment]
Probably a regression caused by #596.

Just curious - why is there double slash non-comments in your JSX?

**Comment by Thiry1** [comment]
>Just curious - why is there double slash non-comments in your JSX?
In my case, I wrote URL in JSX. URL has double slash :D
