### ISSUE TITLE
Bug: @typescript-eslint/keyword-spacing crashes

### ISSUE THREAD

**Issue by andreashuber69** [typescript-eslint/typescript-eslint#6060]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Issue Description

When running eslint on the repo as is, everything works as expected. However, **when upgrading to v5.44 first**, the lint crashes with the message below. **See Repro Steps for more info.**

```
Oops! Something went wrong! :(

ESLint: 8.28.0

TypeError: Cannot read properties of undefined (reading 'after')
Occurred while linting /home/a/git/async-css-plugin/src/AsyncCssPlugin.ts:2
Rule: "@typescript-eslint/keyword-spacing"
    at ImportDeclaration[importKind=type] (/home/a/git/async-css-plugin/node_modules/@typescript-eslint/eslint-plugin/dist/rules/keyword-spacing.js:65:40)
    at ruleErrorHandler (/home/a/git/async-css-plugin/node_modules/eslint/lib/linter/linter.js:1115:28)
    at /home/a/git/async-css-plugin/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/a/git/async-css-plugin/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/a/git/async-css-plugin/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/a/git/async-css-plugin/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/a/git/async-css-plugin/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/home/a/git/async-css-plugin/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /home/a/git/async-css-plugin/node_modules/eslint/lib/linter/linter.js:1150:32
```

### Reproduction Repository Link

https://github.com/andreashuber69/async-css-plugin

### Repro Steps

```
git clone https://github.com/andreashuber69/async-css-plugin
cd async-css-plugin
npm install
npx eslint src --ext .js,.ts
```

The lint should complete without error. If you then continue with:

```
npm install @typescript-eslint/eslint-plugin @typescript-eslint/parser
npx eslint src --ext .js,.ts
```

(the above installs v5.44 of both packages, v5.43 was installed before)
The lint crashes, see output above.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.44.0` |
| `@typescript-eslint/parser`            | `5.44.0` |
| `TypeScript`                           | `4.9.3` |
| `ESLint`                               | `8.28.0` |
| `node`                                 | `18.12.1` |

**Comment by bradzacher** [comment]
This is a bit weird because our tooling should enforce that the default is an empty object, preventing this error state:

https://github.com/typescript-eslint/typescript-eslint/blob/b1f4dad16fa00ff4c3e1528c48f0216c452ba6d1/packages/eslint-plugin/src/rules/keyword-spacing.ts#L26

**Comment by rgant** [comment]
I reverted back to version 5.43 and this error went away: `npm install @typescript-eslint/eslint-plugin@5.43`

**Comment by josundt** [comment]
Same problem here

**Comment by sap-dshapovalov** [comment]
Same problem in 5.44.0

**Comment by JoshuaKGoldberg** [comment]
@bradzacher TIL `context.options` is the user-provided options _before_ `defaultOptions` are provided. I'll set up some linting for it.

**Comment by josundt** [comment]
@bradzacher This issue is only partly fixed, and should potentially be reopened.

After upgrading to 5.45.0, I no longer experience crashes with type only imports like...

`import type { foo } from "./foo.js";`

..but the keyword-spacing rule complains about unexpected white-space, and claims this would be correct:

`import type{ foo } from "./foo.js";`

This is not correct according to the rules.
Maybe this issue should be reopened, unless someone feels like creating a new one.

What I have done as a workaround was to move the `type` keyword _inline_; then there's no problems.

`import { type foo } from "./foo.js";`

Both syntaxes are anyway supported by TypeScript, so the keyword-spacing rule should have a valid check for both.
