### ISSUE TITLE
Bug: [@typescript-eslint/keyword-spacing] Unexpected space(s) before "{" in import type

### ISSUE THREAD

**Issue by crystalfp** [typescript-eslint/typescript-eslint#6063]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

none

### Repro Code

```typescript
import type {SavedQueries} from "./SavedQueries.js";
import type http2 from "node:http2";
import type http from "node:http";

where SavedQueries.js contains only: export const SavedQueries;
```

### ESLint Config

```javascript
parser: '@typescript-eslint/parser'

plugins:
    - '@typescript-eslint'

extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:@typescript-eslint/recommended-requiring-type-checking'

parserOptions:
    ecmaVersion: 2021
    ecmaFeatures:
        impliedStrict: true
    project:
        - ./server/tsconfig.json

settings:
    import/parsers: {'@typescript-eslint/parser': [.ts, .tsx]}
    import/resolver: {typescript: {}}
    import/extensions: [.js, .ts]
    import/ignore: [node_modules]

env:
    es2021: true
    node: true

rules:
    keyword-spacing: off
    '@typescript-eslint/keyword-spacing':
        - warn
        - before: true
          after: false
          overrides:
            else: {after: true}
            return: {after: true}
            try: {after: true}
            catch: {after: false}
            case: {after: true}
            const: {after: true}
            throw: {after: true}
            let: {after: true}
            do: {after: true}
            of: {after: true}
            as: {after: true}
            finally: {after: true}
            from: {after: true}
            import: {after: true}
            export: {after: true}
            default: {after: true}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "lib": [
        "esnext",
    ],
    "removeComments": true,
    "strict": true,
    "alwaysStrict": true,
    "useDefineForClassFields": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "moduleResolution": "node",
    "types": [
        "node",
    ],
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true,
    "importsNotUsedAsValues": "remove",
    "strictNullChecks": true
  },
  "include": [
      "*"
  ],
  "exclude": [
      "./node_modules",
      "./tests"
  ]
}
```

### Expected Result

The rule always worked on my codebase with version 5.43.0. The error message appeared as soon as I moved to version 5.44.0

### Actual Result

```
warning: Unexpected space(s) before "{" (@typescript-eslint/keyword-spacing) at server\ServerResources.ts:13:13:
> 13 | import type {SavedQueries} from "./SavedQueries.js";
     |             ^
  14 | import type http2 from "node:http2";
  15 | import type http from "node:http";
  16 |

warning: Unexpected space(s) before "http2" (@typescript-eslint/keyword-spacing) at server\ServerResources.ts:14:13:
  13 | import type {SavedQueries} from "./SavedQueries.js";
> 14 | import type http2 from "node:http2";
     |             ^
  15 | import type http from "node:http";
  16 |

warning: Unexpected space(s) before "http" (@typescript-eslint/keyword-spacing) at server\ServerResources.ts:15:13:
  13 | import type {SavedQueries} from "./SavedQueries.js";
  14 | import type http2 from "node:http2";
> 15 | import type http from "node:http";
     |             ^
  16 |
 ```

### Additional Info

Also it is not possible to add as `overrides` the line `type: {after: true}` that elicits the following error running eslint:
```
Oops! Something went wrong! :(

ESLint: 8.28.0

Error: --config:
        Configuration for rule "@typescript-eslint/keyword-spacing" is invalid:
        Value {"else":{"after":true},"return":{"after":true},"try":{"after":true},
"catch":{"after":false},"case":{"after":true},"const":{"after":true},"throw":{"after":true},
"let":{"after":true},"do":{"after":true},"of":{"after":true},"as":{"after":true},"finally":{"after":true},
"from":{"after":true},"import":{"after":true},"export":{"after":true},"default":{"after":true},
"type":{"after":true}} should NOT have additional properties.
```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.44.0` |
| `@typescript-eslint/parser`            | `5.44.0` |
| `TypeScript`                           | `4.9.3` |
| `ESLint`                               | `8.28.0` |
| `node`                                 | `18.12.1` |

**Comment by bradzacher** [comment]
> Playground Link
> none

A playground link makes it quick and easy for us to reproduce your issue.

As it stands right now using your config and code I cannot reproduce your issue.
[playground](https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=FASwtgDg9gTgLgAjgTwgUwQbwQZQIYBuaAJgIoCuaMIaAzggL4IBmMUYCARAHQD0+RMpWp1uAK1qcA3KEixEKdAgAWcOBABMLNh04A7KMTQAuVeo3TZ0eElQYzEbey4GjptREtA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Aa0UIHcB7aACa1kxAIZlmAc3RgA2uGw5uo6E0gAaBYqyLskAEaIAZv0Qz8cRJt17RR-Imgyjo+MitbdkXgDdHVARQZHRscRDczDBDQnDsHJwwLWERPGwBfaxioaER8WFVg1NDIOMdzSyLFDMq9C0JCrNt7MsSKxurGyDJRfDIACwbGqFKEsBcImogOrK7Rd0HOkfLkybBpmK7eJmR8BZml1pX2zI38Puhebj2Ng7AklOPVyCRdqNXY5tH71fXigV5rsVbt9Hp1eEZATYSp9lg8sr8oXNIV5gW14SdikZmK54PU3kNhjDDnCYgivEYLgBbZGKaHxWE-DFQyiU4j8V6Yd6E+nExlPRAADzZ0A50RuRLuaNJTK8gRcCFFXLpLUlR3hNTSRU1igAuiA0kA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)

**Comment by nmss** [comment]
@bradzacher here you find a playground that shows the issue [playground](https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=LAKAlgtgDg9gTgFwAQIJ5QKZIN5IMoCGAbhgCYCKArhnGBgM5IC+SAZnDBEgEQB0A9IRIVqtBrwBW9bgG5QkWIhTosACwQIoAJjYcu3AHYxSGAFzrNW2fOjxkaTEgtRdnHkZPmNUayCA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Aa0UIHcB7aACa1kxAIZlmAc3RgA2uGw5uo6E0gAaBYqyLskAEaIAZv0Qz8cRJt17RR-Imgyjo+MitbdkXgDdHVARQZHRscRDczDBDQnDsHJwwLWERPGwBfaxioaER8WFVg1NDIOMdzSyLFDMq9C0JCrNt7MsSKxurGyDJRfDIACwbGqFKEsBcImogOrK7Rd0HOkfLkybBpmK7eJmR8BZml1pX2zI38Puhebj2Ng7AklOPVyCRdqNXY5tH71fXigV5rsVbt9Hp1eEZATYSp9lg8sr8oXNIV5gW14SdikZmK54PU3kNhjDDnCYgivEYLgBbZGKaHxWE-DFQyiU4j8V6Yd6E+nExlPRAADzZ0A50RuRLuaNJTK8gRcCFFXLpLUlR3hNTSRU1igAugpNWkgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)

**Comment by blephy** [comment]
Same issue here

**Comment by jdforsythe** [comment]
We have what I believe to be the same issue. The addition of `type` in https://github.com/typescript-eslint/typescript-eslint/pull/5977 broke the default behavior. Our rule was simply:

`"@typescript-eslint/keyword-spacing": ["error"]` so it would use the default `{ "before": true, "after": true }`. After this PR, the following code errors:

```ts
import type * as Bull from 'bull';
```

or

```ts
import type { Job } from 'bull';
```

however this does not error:

```ts
import { type Job } from 'bull';
```

We would expect all of these to pass, as the default is to require spaces before and after, but typescript-eslint wants to remove the space before the `*` and before the `{` when `type` is outside the curlies.

This is a bug because it broke the default behavior.

There should probably also be an override for `type` to allow configuring it as one would desire, which would only apply when the `type` keyword is outside the curlies or is followed by a `*`.
