### ISSUE TITLE
Bug: prefer-optional-chain throws error: "Unexpected member object type: TSAsExpression"

### ISSUE THREAD

**Issue by revelt** [typescript-eslint/typescript-eslint#6068]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=JYOwLgpgTgZghgYwgAgCoHsDWETIN4BQyymoAJgPwBcyAzmFKAOYDcBAvgTAK4gJjB0uenChhaqOEwAUYLDhoZsIAJQ0ARunQAbCHFyFiUCGG5RcAQgvSixZNbnLkcWs5ABPFQDpSIMsgAfAPsAbQAiMnR+dwAHCDCAGmQwgA8AW20wgF0vUARtbjIIWmlZeVwXN08fchVbFTZOAggUmPQxZCL4bm0wOjBRcUlWAiA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WloHsalfkwCG8WmQAWo5uii9o-aJHBgAviHVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
interface Token {
  kind?: string;
}
function startsTag(token: Token): boolean {
  return !!(
    !(token as any).kind || !["doctype", "xml"].includes((token as any).kind)
  );
}

export default startsTag;
```

for reference, the full source is [here](https://github.com/codsen/codsen/blob/main/packages/codsen-tokenizer/src/util/startsTag.ts)
```


### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/prefer-optional-chain": "error"
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

Expected ESLint not to throw

### Actual Result

In VSCode ESLint throws with a message "Unexpected member object type: TSAsExpression":

![Screenshot 2022-11-23 at 08 56 27](https://user-images.githubusercontent.com/8344688/203506063-3318b3b9-d6b2-4012-b5bb-bbf738ab4e42.png)

The playground error is more cryptic:

![Screenshot 2022-11-23 at 08 58 16](https://user-images.githubusercontent.com/8344688/203506193-e39345c7-08f8-4bba-b16f-c403e46951f6.png)

### Additional Info

I suspect it's from v5.44 release, and it might be a similar-class bug to #5553 

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `^5.44.0` |
| `@typescript-eslint/parser`            | `^5.44.0` |
| `TypeScript`                           | `^4.8.4` |
| `ESLint`                               | `^8.28.0` |
| `node`                                 | `16.14.2` |

**Comment by omril1** [comment]
Seems related to #6024 as well.
The enhancement to the rule caused a lot of possible node types to break it 😞

**Comment by revelt** [comment]
The new v5.45 is still affected. The last working version is v5.42.

**Comment by bradzacher** [comment]
This should now be fixed (the above playground is not crashing)
