### ISSUE TITLE
Website: "Get Started" homepage buttons not centered on production

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6081]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

This only happens on production, not `yarn start` locally:

<img width="875" alt="Screenshot of a small left-aligned 'get started' button on the typescript-eslint.io homepage, which is otherwise center-aligned" src="https://user-images.githubusercontent.com/3335181/203842297-982a517e-51b1-45d9-a58f-49d75e6c459f.png">

wat

### Affected URL(s)

https://typescript-eslint.io/

**Comment by JoshuaKGoldberg** [comment]
Something spooky is happening. When I reload the page, the buttons start centered & correctly sized until the load is done.

This recording shows a Slow 3G throttled page load:

https://user-images.githubusercontent.com/3335181/204148714-014eafc1-74d8-4853-b277-d0949a54efef.mov

**Comment by JoshuaKGoldberg** [comment]
😞 I haven't been able to figure this one out. Not sure if it's Netlify and/or Nx caching (@JamesHenry?), and/or Docusaurus (@Josh-Cena?). Help please? 🙏

**Comment by JoshuaKGoldberg** [comment]
Ok 😮‍💨 sorry for the ping - I again cleared the site cached and it went away now. I suppose just raising this to your attention - that if we see this again, we should clear the cache & redeploy in Netlify.

**Comment by JoshuaKGoldberg** [comment]
Or - no, it's still happening!

**Comment by JamesHenry** [comment]
Just to check - do you think it could be the Nx cache because this was an actual bug that was theoretically already fixed? And you think a version of the cache from before the bug fix is erroneously being applied?

**Comment by JoshuaKGoldberg** [comment]
I think those are both possibilities, yes. This bug doesn't happen locally.

**Comment by JoshuaKGoldberg** [comment]
I paired with @AgentEnder on this and narrowed it down to not be a Netlify or Nx thing, we think. Just running `npx docusaurus build` and then `npx docusaurus serve` from `packages/website` displays the behavior. I'll file a bug soon.
