### ISSUE TITLE
[typescript/no-unused-vars] errors inside declare namespace

### ISSUE THREAD

**Issue by ficristo** [typescript-eslint/typescript-eslint#61]
**Repro**
See below

```JSON
{
  "rules": {
    "no-unused-vars": "off",
    "typescript/no-unused-vars": ["error", { "vars": "all", "args": "none" }]
  }
}
```

```TS
export = CodeMirror;
export as namespace CodeMirror;

declare function CodeMirror(host: HTMLElement, options?: CodeMirror.EditorConfiguration): CodeMirror.Editor;

declare namespace CodeMirror {
    function countColumn(line: string, index: number | null, tabSize: number): number;
    var version: string;
}

```

**Expected Result**
No errors.

**Actual Result**
`typescript/no-unused-vars` errors for `function countColumn` and `version`.

**Additional Info**

**Versions**

| package                    | version |
| -------------------------- | ------- |
| `eslint-plugin-typescript` | `1.0.0-rc.0` |
| `typescript-eslint-parser` | `eslint-plugin-typescript/parser` |
| `typescript`               | `3.1.6` |

**Comment by bradzacher** [comment]
this will require tests if it has been fixed in the parser
