### ISSUE TITLE
Repo: Semantic PR Titles check fails on two rule names

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6103]
### Suggestion

See #6091 > https://github.com/typescript-eslint/typescript-eslint/actions/runs/3556218470/jobs/5973681087:

```plaintext
feat(eslint-plugin): [no-unsafe-enum-assignment] [no-unsafe-enum-comparison] new rules
```

```plaintext
subjectPattern: ^(\[[a-z\-]+\] )?[a-z].+[^\.]$
subjectPatternError: The "subject" must start with a lower-case letter and must not end with a full-stop.
```

cc @bradzacher - not sure if bug or something we should improve the error message for...

**Comment by bradzacher** [comment]
Ideally we'd do one rule per PR just to make it easier to review and nicer in the release notes.

But given that stacking PRs is a pain I can see why you'd wanna do related rules together..!

**Comment by JoshuaKGoldberg** [comment]
Hmm, yeah. I guess I can split this one out and stack it - it's not a common thing. If it keeps happening we can always come back to this...
