### ISSUE TITLE
Bug: prettier/eslint typescript adds new lines, while JS without types does not.

### ISSUE THREAD

**Issue by lifeiscontent** [typescript-eslint/typescript-eslint#6131]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Issue Description

given the following reproduction it adds 2 new lines, while the JS variant doesn't which causes issues with disabling eslint rules.

https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEA3AhgGwEsATXeAYWngA8sBeAHSk0wHpXM40jYBaYwmlwAjfHF5Q4tXjziYAAjACeABy5gAToRUxeXHjFZQIe6iqJhCu3FCVMWLADwBlTrQTE0mAJoBXFQB0APLCAFZwYDDOYAAWcAC2uI42SgB8ADSY5KkAFGixCbhImM6ZkLBSMMXkAJSYdKn2Do4Aam7wUJ6YEGERMLl4+L5cxS11DZjATQ6YGnAwvhrM+XGJ0zOYAYMkZHA5g8NomcCYIhAaMACiuBr4SsUwGsNlVJWYAL416zMBMHFQORy41SmF8nTgADNCJJiF9mBsWAEwGRYjklP4ACoQABi53ilw0GnOaBqAG51u9yVAQOkQBAdIR0MhQDciQB3AAKNwQaGQIFw2AgJBpIGEGlwYAA1vNnLh4nAADLQuDICEENBwWliiXSqIqCXQgDmyEezxACWEcGIxCtCpsht8uENcFxGkSMBgRr5uF8MAgIpiMHi+AA6jErFx9WA4M4eVZCNgrEo+YRDcY5iLoRqLhzxYbEqr1ZqQKE0NRnEaxABFXwQeCF-Aa2n6jTZvnKNT5LQ6EUqLSwEMkP7IAAcAAZm0SNSHxSpvfg2bglLzaQBHWvwXP03koPtcOAabAq2lzdeEOa5p0FpBqxvFjXxQgmp73ytwACCHq0wl9cA5B6VSQGybEA0DfGs6xVG8i1pGAREHYhhyQAAmWDxUIHhDUoeJr35fB8BFXwNQxEQd1vEDsGGABJcFYGibsYHfTpnGUMRgLgd53iAA

https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEA3AhgGwEsATXeAYWngA8sBeAHSk0wHpXM40jYBaYwmlwAjfHF5Q4tXjziYAAjACeABy5gAToRUxeXHjFZQIe6iqJhCu3FCVMWLABRowACzgBbXABpMkWFIwAJSYdAB89g6OePgArlwh4ZjAkQ6YGnAwsRrMLu5eqWmYAHQxJGRw0QTxaL7AmCIQGjAAorga+EpImDAa8b7+NFgAvkGFacUw7lCOjolhmLFQxHAAZoSSxGPMRSzFYGRujkqxKgAqEABiTR4tGhpNaEEA3IXDr1Ag3iAQOoToyFA7QeAHcAArtBBoZAgXDYCAkL4gYQaXBgADWmQAyrgPHAADIbODIVYENBwb4otGYmBYlRojYAc2QvX6IE8wjgxBWxHxNkZsVwjLg1w0XhgMCZMNwsRgECRrhgHnwAHVXFYuPSwHAsVCrIRsFYlDDCIzjBkkRtyc0wajGV4SWSKSAAFZoahYpliACKsQg8Ed+HJ33pGmtMOUahcWh0SJUWlgKpIU2QAA4AAwhh7klWolTS-Ag3BKaHfACOfvgtt+0JQ8a4cA02GJ3wyFcIGVtQodSFJQed5I8hBZfQHXrgAEEJVphLK4GDG4TJIHgyA0OPff7ib2nd8YCIk8QU0gAEx71GEHiMygeHuw-D4JGxclnES1vur7DxACSywQtM0bQYAnZYsWUMQVzgYZhiAA

### Reproduction Repository Link

N/A

### Repro Steps

already provided above

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `X.Y.Z` |
| `@typescript-eslint/parser`            | `X.Y.Z` |
| `@typescript-eslint/scope-manager`     | `X.Y.Z` |
| `@typescript-eslint/typescript-estree` | `X.Y.Z` |
| `@typescript-eslint/type-utils`        | `X.Y.Z` |
| `@typescript-eslint/utils`             | `X.Y.Z` |
| `TypeScript`                           | `X.Y.Z` |
| `ESLint`                               | `X.Y.Z` |
| `node`                                 | `X.Y.Z` |

**Comment by JoshuaKGoldberg** [comment]
This is the repository for TypeScript-ESLint. The playground you posted is for the Prettier project and has a link to Prettier's GitHub: https://github.com/prettier/prettier. Please post an issue there. This isn't our issue! 😄

**Comment by Josh-Cena** [comment]
Please see https://prettier.io/docs/en/rationale.html#comments. This is not a TS-ESLint defect. If the code to be formatted contains comments, you need to manually position the comment.

**Comment by JoshuaKGoldberg** [comment]
haha, jinx 😄

**Comment by Josh-Cena** [comment]
The point is not about the parser. The point is that the formatter does not care what's inside the comment, and doesn't try to put it where the error would occur (indeed, because the previous line is now split into two lines, and there's no way for Prettier to guess which line to put the comment on). This is neither an issue with Prettier nor TS-ESLint—this is fully working as intended, and you just need to manually position the comment yourself.

**Comment by bradzacher** [comment]
Josh and Josh are correct - this is not an issue with our project.
We simply provide a parser that prettier uses to convert the source code to an AST.
After that all logic with formatting, including comment positioning, is firmly within prettier's domain.

To further show that this isn't a problem with our parser [you can test the `babel-ts` parser](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEA3AhgGwEsATXeAYWngA8sBeAHSk0wHpXM40jYBaYwmlwAjfHF5Q4tXjziYAAjACeABy5gAToRUxeXHjFZQIe6iqJhCu3FCVMWLADwBlTrQTE0mAJoBXFQB0APLCAFZwYDDOYAAWcAC2uI42SgB8ADSY5KkAFGixCbhImM6ZkLBSMMXkAJSYdKn2Do4Aam7wUJ6YEGERMLl4+L5cxS11DZjATQ6YGnAwvhrM+XGJ0zOYAYMkZHA5g8NomcCYIhAaMACiuBr4SsUwGsNlVJWYAL416zMBMHFQORy41SmF8nTgADNCJJiF9mBsWAEwGRYjklP4ACoQABi53ilw0GnOaBqAG51u9yVAQOkQBAdIR0MhQDciQB3AAKNwQaGQIFw2AgJBpIGEGlwYAA1vNnLh4nAADLQuDICEENBwWliiXSqIqCXQgDmyEezxACWEcGIxCtCpsht8uENcFxGkSMBgRr5uF8MAgIpiMHi+AA6jErFx9WA4M4eVZCNgrEo+YRDcY5iLoRqLhzxYbEqr1ZqQKE0NRnEaxABFXwQeCF-Aa2n6jTZvnCERwfC8GC85taWAhkh-ZAADgADP2IBqQ+KVN78GzcEo+yAAI61+C5+m8lAqObZ7Aq2lzDeEOa5p0FpBqxvFjXxQgmp73ytwACCHq0wl9cA5cA0JVJAbJsQDQN8azrFUbyLWkYBEIdiBHJAACY4PFQgeENSh4mvfl8HwEVfA1DERF3W9QOwYYAElwVgaItB0d9OmcZQxBAuB3neIA) which has exactly the same result. You can even go one step further and [test the `flow` parser using equivalent flow code](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEA3AhgGwEsATXeAYWngA8sBeAHSk0wHpXM40jYBaYwmlwAjfHF5Q4tXjziYAAjACeABy5gAToRUxeXHjFZQIe6iqJhCu3FCVMWLADwBlJJgCaAVxUA6APLCAFZwYDDOYAAWcAC2uI42SgB8ADSY5IkAFGiRMbhuzqmQsFIwbuQAlJh0ifYOjgBqbhBBITCZePieXG71ldWYwLUOmBpwMJ4azNlRsUPDmD4dJGRwGR1daKnAmCIQGjAAorga+EpuMBpdhVQlmAC+5XPDPjBRUBkZfYmYnlDEcAAzQiSYiPZjzFg+MBkSIZJTeAAqEAAYntogcNBo9mhygBuOZ3fFQEDJEAQHSEdDIUDHLEAdwACscEGhkCBcNgICQSSBhBpcGAANZjZy4aJwAAywLgyABBDQcFJfIFwrCKgFwIA5sgLlcQDFhHBiP9iBKbJrPLhNXBURpYjAYFq2bhPDAIDyIjBovgAOoRKxcdVgODOFlWQjYKxKNmETXGUY84EK-YM-ma2Ky+WKkCBNDUZxasQARU8EHgmfwCtJ6o0ybZAPwEDpPJUWlgPpIr2QAA4AAzVrEKn38lTO-B03BKVmkgCOpfgqfJrJQra4cA02BlpNGc8Io1TVozSDllezCuihB1lzPhbgAEEHVphK64Az11LJBWqyA0LeS2WZWPLNSRgEQO2ILskAAJhA-lCB4TVKGiI92XwfAeU8BUEREZcT2-bAugAST+BAwk0bQYDvP5nGUMQvzgO47iAA).

Consider filing a bug with prettier if you think this is something they should look into.
