### ISSUE TITLE
Enhancement: [member-ordering] treat instance properties assigned to lambdas as property, not as methods

### ISSUE THREAD

**Issue by dko-slapdash** [typescript-eslint/typescript-eslint#6133]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/member-ordering.md

### Description

I noticed that
```
protected readonly SOME_CONST = 123;
```
is treated as "protected instance field", whilst
```
protected readonly SOME_LAMBDA = () => console.log("hello");
```
is treated as "protected instance method", although they're semantically the same.

My proposal is to add an option which forces field assigned to lambdas be treated as field, not as methods. (Can be off by default.)

What's interesting is that in AST viewer, SOME_LAMBDA is shown as PropertyDefinition (which is correct), not as MethodDefinition. But the rule still treats it as a method.

![CleanShot 2022-11-30 at 01 11 35@2x](https://user-images.githubusercontent.com/46383452/204754975-bc5144d0-ad65-44bf-98ec-60fd3daef678.png)

Example eslint config:

```
{
  "rules": {
    "@typescript-eslint/member-ordering": [
      "error", 
      {
        "default": [
          "field",
          "public-instance-method",
          "protected-instance-method"
        ]
      }
    ]
  }
}
```

What I want to achieve here is to force all of the fields be above all of the methods. A field can be a of a primitive type or of a complex type, including lambdas.

### Fail

```typescript
class Test {
  public myPublicMethod() {
    console.log("world");
  }

  protected readonly SOME_LAMBDA = () => console.log("hello");
}
```

### Pass

```typescript
// The code below should pass with the new proposed option turned on.
// Currently, it fails.

class Test {
  // First, all fields.
  protected readonly SOME_CONST = 123;
  protected readonly SOME_LAMBDA = () => console.log("hello");

  // Then, all methods: first public, then protected.

  public myPublicMethod() {
    console.log("world");
  }

  protected myProtectedMethod() {
    console.log("hello");
  }
}
```

### Additional Info

https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&showAST=es&code=MYGwhgzhAEAqCmEAu0DeAoa0AOAnA9kvMEQCbS7xin4B2IAntAMoDyAsgKID6AwqwDlmsaAF5oARgBMAZgDc6TDgJES8cpWp1GLDjwAyAQXYAhACKGx0ABQBKMQD5owOhHwh4AOhD4A5tYAiAAt4EB8A2wUlbABXACMQAEtgaABbBgAFeKTgdngkIPxSOzQlLBdaNw9vP0CAd3xcEFIIhSwAX0UsPEJiMjTMlT71PIKikowsctd3Lx9-YNDwyKVO9qA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AW0XYCNFpaA9tAAmfZgHN0YANrhsOPtCGQANGDnys87JFEAzAIYJ8U2du2Q9lRPGGqN5qMVjdGZWs2T4DTMolqc+AAWAnYqDuaQxEr4iGSxwh5MXj5+AYjBoZAR2AC6OQC+DvkQRQVAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

**Comment by bradzacher** [comment]
This behaviour is completely intentional!
Why? Because for the vast, vast majority of devs - when they define a class property with an arrow function what they're really doing is defining an method that has an automatically bound `this` context (aka an auto-bound method).

Why do people do this? Because it's a convenient short-hand that saves having to define a constructor and include a bind statement for each and every relevant method - which is just extra lines to maintain and remember to add, and if you forget to add them it can cause crashes.

Clarifying with an example:
```ts
class Foo {
  prop = 1;
  method() { return this.prop }
  
  constructor() {
    // forcefully bind the this context for the method
    this.method = this.method.bind(this);
  }
}

const fooInstance = new Foo();
const fooMethod = fooInstance.method;
fooMethod(); // doesn't break as the this context was pre-bound

// the above class declaration can be simplified for almost all cases to just
class Bar {
  prop = 1;
  method = () => { return this.prop };
}
```

I'm yet to encounter a codebase that doesn't conceptually think of arrow function properties as methods, and most users agree this is correct. Since it was implemented this way back in 2016 you're the first user to ask for an option!

For this reason, I do not believe this request satisfies the requirement of "would be useful to the broader TypeScript community", thus I am going to reject the proposal.
Thanks for filing!

**Comment by dko-slapdash** [comment]
@bradzacher I see what you mean, but still, the problem exists. Arrow function (as a value) is not much different from any other complex type like an array, an object etc.

Also, an opposite problem exists:

```
class Test {
  myDebouncedMethod = lodash.debounce(() => console.log(...), 1000);
  myRegularMethod = () => console.log(...);
}
```

Here, myDebouncedMethod is also a method (logically speaking), but eslint obviously thinks it's a property. Thus, despite myDebouncedMethod and myRegularMethod are basically of the same kind, eslint reacts on them differently. What I want to say is that implicit treatment of an arrow function as a "method" doesn't cover all of the cases, and thus, it deserves being configurable at least (the current behavior is a good default).

But, if it's a "won't fix", then the similar effect could've been achieved by adding a rule which matches CAPITAL_CASE fields from other fields. If done so, then I'd be able to tell eslint to put all CAPITAL_CASE fields on top of the class (it's like a convention that CAPITAL_CASE is a constant; what I'm trying to achieve is to just be able to expose some static- and instance-fields as constants, irregardless on whether they're of a primitive type, of a complex type or of an arrow-function type.

I saw this as a feature request somewhere though.

**Comment by dko-slapdash** [comment]
@bradzacher BTW, another way (besides an option) could've been changing `*-method` from MemberType to GroupType, and make these new GroupTypes compound, e.g. `public-instance-method-bound` + `public-instance-method-unbound`. This would've been fully consistent with the approach of the rule and backward compatible.

(All those names actually look more like "property tags", like saying "public:instance:method:bound" is the same as saying "instance:method:bound:public" (the order doesn't matter), and other tags could've been e.g. "abstract", "overridden", "capital", "#", "underscored" etc. If done this way, the rule would've been infinitely expressive.)
