### ISSUE TITLE
Repo: investigate switching core TS->ESTree conversion logic from a "switch/case" to a "jump table" for performance improvements

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#6149]
### Suggestion

https://artemis.sh/2022/08/07/emulating-calculators-fast-in-js.html

I read this a while ago but didn't think about it's possible performance application in our parser.

Our [core conversion logic](https://github.com/typescript-eslint/typescript-eslint/blob/ce2e5dad036087baa9098ad8818a752dec3f6163/packages/typescript-estree/src/convert.ts#L806-L2986) is one massive switch/case (currently 159 cases).

According to [the stackoverflow comment](https://stackoverflow.com/questions/18830626/should-i-use-big-switch-statements-in-javascript-without-performance-problems#comment27798374_18830724) (which has references to the v8 source code) - if you've got more than 128 cases then the switch might not get properly optimised and thus acts slower than hand-written if/else.

One workaround is to use a "jump table" instead of a switch. Jump tables rely on the case value instead being the key of an object - meaning the lookup is instead always as performant as a property lookup (which is usually O(1)).

We should investigate if switching to a "jump table" improves the perf of our parser.

For reference the conversion would be something like this:
```ts
switch (node.kind) {
  case SyntaxKind.SourceFile: // ...
  case SyntaxKind.Block: // ...
  // ...
}

// to

const JUMP_TABLE = {
  [SyntaxKind.SourceFile]: (node: ts.SourceFile) => { /* ... */ },
  [SyntaxKind.Block]: (node: ts.Block) => { /* ... */ },
  // ...
};

JUMP_TABLE[node.kind](node);
```

For this task we'll want to:
1) instrument `typescript-estree` to measure the performance baseline with the current code.
2) make the conversion to a jump table.
3) measure the performance after the change.
4) if (3) < (1), then merge the change.

**Comment by liuxingbaoyu** [comment]
FYI: https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#performance-improvements

**Comment by bradzacher** [comment]
Yeah that's where I saw the blog post (in the 4.9RC release notes!)
I completely forgot about it until now when I was thinking about the perf of our parser.

Hopefully we can net some decent wins with this!

**Comment by bradzacher** [comment]
As per investigation on #6371 - time savings are going to amount to less than a tenth of a percent in most cases. Not worth making this change.
