### ISSUE TITLE
Enhancement: [strict-boolean-expressions] Change == to ===?

### ISSUE THREAD

**Issue by justinhelmer** [typescript-eslint/typescript-eslint#6173]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/strict-boolean-expressions/

### Description

Hello! We believe strongly that strict boolean expressions are a good thing, because truthy evaluation opens the door for developer error and bugs to slip into the wild.

For this reason, we very much like the power of the [strict-boolean-expressions](https://typescript-eslint.io/rules/strict-boolean-expressions/) rule.

The challenge we are facing, is how auto-fix conflicts with some other rules that we believe are very valuable:

1. [eqeqeq](https://eslint.org/docs/latest/rules/eqeqeq) - We agree with the philosophy of the rule: It is considered good practice to use the type-safe equality operators === and !== instead of their regular counterparts == and !=. The reason for this is that == and != do type coercion.
2. [no-eq-null](https://eslint.org/docs/latest/rules/no-eq-null) - Comparing to null without a type-checking operator (== or !=), can have unintended results as the comparison will evaluate to true when comparing to not just a null, but also an undefined value.

[The fixes and suggestions](https://typescript-eslint.io/rules/strict-boolean-expressions/#fixes-and-suggestions) (specifically the auto-fix for objects when `allowNullableObject` is `false`) conflict with the above rules.

I am sure that there is good reason and a lot of discussion behind why there was a decision to use `== null` as opposed to `=== undefined`, but I thought it would be worth opening a discussion to see if we can get a consensus that it would be preferable to change the behavior to align more with the core eslint rules and the philosophy behind why it is a good idea to enable them.

### Fail

```typescript
let obj;
if (Math.random() > 0.5) {
  obj = {};
}

if (obj) {
  console.log('I am set!');
}
```

### Pass

```typescript
// Current behavior
let obj;
if (Math.random() > 0.5) {
  obj = {};
}

if (obj != null) {
  console.log('I am set!');
}

// Preferred behavior
let obj;
if (Math.random() > 0.5) {
  obj = {};
}

if (obj !== undefined) {
  console.log('I am set!');
}
```

### Additional Info

- There are a couple issues I found with some information on the topic, but it is not explicit about this particular choice so I thought it was worth opening a new thread:

  - https://github.com/typescript-eslint/typescript-eslint/issues/2894
  - https://github.com/typescript-eslint/typescript-eslint/issues/5587

**Comment by sindresorhus** [comment]
> the fixers were added 18m ago (https://github.com/typescript-eslint/typescript-eslint/pull/2847) and there's been very little complaint - suggesting users either (a) don't care about choosing one style over the other, (b) prefer the double equals style, or (c) are okay with manually fixing to triple equals style

In my case, I didn't use the rule because it used to be buggy and too limited. And now, I cannot enable the rule as the auto-fix fixes to the wrong thing (not `===`).

---

https://github.com/xojs/eslint-config-xo-typescript/issues/71

**Comment by bradzacher** [comment]
I'm okay if we add an option to control the null/undefined fixer style.
```ts
interface Options {
  nullishFixStyle?: 'double-equals' | 'triple-equals';
}

const defaults: Options = {
  nullishFixStyle: 'double-equals',
};
```

Where `double-equals` is the current behaviour which fixes to `== null`, and `triple-equals` will pick the best fix between `=== null`, `=== undefined` or `=== null && === undefined` depending on the types.

**Comment by kirkwaiblinger** [comment]
Since https://github.com/typescript-eslint/typescript-eslint/pull/7394, the autofix has been changed to a suggestion.

We _could_ offer multiple suggestions, but I'm not sure it's worth the effort at that point. Since the suggestion requires human intervention anyway, it seems like this is just as well handled as a manual adjustment when accepting the suggestion. 
*** 

See [Playground](https://typescript-eslint.io/play/#ts=5.5.2&fileType=.tsx&code=DYUwLgBA9gRgVgbgFAEsBmEAUBZAhmACwDoAnXAOwBMoBbTASggD4IAGIgVkYG8kJp4EALwRuAX2RikqDJlhwefCAGMo5AM5RQRYFADmmAOQBJCLhoR14AISH6koA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6ZfKsugIwHs%2BSAIZN6AD2LQUySnyaoMAbUgB3IdCaQANJkhD48PioByCeEJ5IA8jwBWibujAAzfckQBfALrgwHkB5AA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDAruuGAL4g9A&tokens=false)

### Code

```ts
let obj;
if (Math.random() > 0.5) {
  obj = {};
}

if (obj) {
  console.log('I am set!');
}
```

### Eslint config

```json
{
  "rules": {
    "@typescript-eslint/strict-boolean-expressions": ["warn", {"allowNullableObject": false}]
  }
}
```

### TypeScript config

```json
{
  "compilerOptions": {
    "strict": true
  }
}
```

**Comment by JoshuaKGoldberg** [comment]
Agreed. This was never a highly requested feature, and the rule is much more stable now than it used to be. Closing as non-actionable. Cheers!
