### ISSUE TITLE
 Parsing error when using @typescript-eslint/parser with eslint-plugin-pug

### ISSUE THREAD

**Issue by arisslin** [typescript-eslint/typescript-eslint#6177]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

I added **eslint-plugin-pug** to my project and configured my npm lint script to lint _*.pug_ files as well. After running the linter with the script i get following error message in the console:

```
/Volumes/projects/eslint-pug-bug/src/404.pug
  0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/src/404.pug/0_0.js` using `parserOptions.project`: <tsconfigRootDir>/../../../volumes/projects/eslint-pug-bug/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the TypeScript ESLint docs for more info: https://typescript-eslint.io/linting/troubleshooting##i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file
```

I rebuild the configuration of another project with the help of an rejected create-react-app.

May lint script looks like this:

`"lint": "eslint -c .eslintrc.js \"src/**/*.{ts,tsx,pug}\""`

My _.eslintrc.js_ looks like this:

```
module.exports = {
  root: true,
  extends: [
    "react-app",
    "react-app/jest",
    "plugin:@typescript-eslint/recommended"
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: ["tsconfig.json"],
    ecmaFeatures: {
      jsx: true
    },
    ecmaVersion: 12,
    sourceType: "module"
  },
  plugins: [
    "@typescript-eslint",
    "pug"
  ],
  rules: {
    "@typescript-eslint/await-thenable": "error"
  }
}
```

my _tsconfig.json_ looks like this:

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}
```
However, if i delete the **parserOptions** and the **rule** from _.eslintrc_ everything works fine. But i need that rule in my configuration.

I tried to troubleshoot it with this article: https://typescript-eslint.io/linting/troubleshooting/#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file

But it doesn't work.
- using an .eslintignore or excluding the file is no option because i want to lint the file
- include _src/404.pug_ or _src/404.pug/0_0.js_ into does not work and i get the same parsing error

What am i doing wrong?

### Reproduction Repository Link

https://github.com/arisslin/eslint-pug-bug

### Repro Steps

1) clone the repo
2) `npm install`
3) `npm run lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.45.1` |
| `@typescript-eslint/parser`            | `5.45.1` |
| `TypeScript`                           | `4.9.3` |
| `ESLint`                               | `8.29.0` |
| `node`                                 | `14.19.3` |
| `eslint-plugin-pug`                                 | `1.2.5` |

**Comment by bradzacher** [comment]
So what's happening here is that `eslint-plugin-pug` is running a ["preprocessor"](https://eslint.org/docs/latest/user-guide/configuring/plugins#specify-a-processor) on your pug file which extracts the JS content so that ESLint can lint it.

The problem with this is that the extracted JS is given this "virtual" filename which doesn't work with TS because it doesn't exist on disk. This means that type-aware linting can never work on it.

What I would be doing here is explicitly turning off any type-aware lint rules on pug files using [overrides config](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#configuration-based-on-glob-patterns).

**Comment by arisslin** [comment]
@bradzacher thanks for the tip. I will check it out and give a feedback here.
