### ISSUE TITLE
Rule parity with TSLint core

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#62]
Spinning off of https://github.com/bradzacher/eslint-plugin-typescript/issues/276: I'm a TSLint maintainer and would _love_ to help get all the TSLint-exclusive rules available in ESLint. For each of these, would you accept a PR adding them in?

 - [ ] [await-promise](https://palantir.github.io/tslint/rules/await-promise)
 - [ ] [completed-docs](https://palantir.github.io/tslint/rules/completed-docs)
 - [ ] [deprecation](https://palantir.github.io/tslint/rules/deprecation)
 - [ ] [match-default-export-name](https://palantir.github.io/tslint/rules/match-default-export-name)
 - [ ] [no-boolean-literal-compare](https://palantir.github.io/tslint/rules/no-boolean-literal-compare)
 - [ ] [no-floating-promises](https://palantir.github.io/tslint/rules/no-floating-promises)
 - [x] [no-for-in-array](https://palantir.github.io/tslint/rules/no-for-in-array): #250
 - [ ] [no-inferred-empty-object-type](https://palantir.github.io/tslint/rules/no-inferred-empty-object-type)
 - [ ] [no-unbound-method](https://palantir.github.io/tslint/rules/no-unbound-method)
 - [ ] [no-unnecessary-qualifier](https://palantir.github.io/tslint/rules/no-unnecessary-qualifier)
 - [ ] [no-unnecessary-type-assertion](https://palantir.github.io/tslint/rules/no-unnecessary-type-assertion)
 - [ ] [no-unsafe-any](https://palantir.github.io/tslint/rules/no-unsafe-any)
 - [ ] [no-unused-variable](https://palantir.github.io/tslint/rules/no-unused-variable)
 - [ ] [no-use-before-declare](https://palantir.github.io/tslint/rules/no-use-before-declare)
 - [ ] [no-void-expression](https://palantir.github.io/tslint/rules/no-void-expression)
 - [ ] [prefer-readonly](https://palantir.github.io/tslint/rules/prefer-readonly)
 - [ ] [promise-function-async](https://palantir.github.io/tslint/rules/promise-function-async)
 - [x] [restrict-plus-operands](https://palantir.github.io/tslint/rules/restrict-plus-operands): #230
 - [ ] [return-undefined](https://palantir.github.io/tslint/rules/return-undefined)
 - [ ] [strict-boolean-expressions](https://palantir.github.io/tslint/rules/strict-boolean-expressions)
 - [ ] [strict-type-predicates](https://palantir.github.io/tslint/rules/strict-type-predicates)
 - [ ] [unnecessary-bind](https://palantir.github.io/tslint/rules/unnecessary-bind)
 - [ ] [use-default-type-parameter](https://palantir.github.io/tslint/rules/use-default-type-parameter)

**Comment by not-an-aardvark** [comment]
I'm not at all familiar with the TSLint rule API, but would it be feasible to have a compatibility wrapper that generically converts TSLint rules to ESLint rules at runtime? That would avoid the effort of manually reimplementing TSLint rules as ESLint rules, both for this project and for custom rules.

In other words, it would be similar to `eslint-plugin-tslint` except that it would just invoke a single TSLint rule rather than invoking TSLint itself. This might have some performance benefits because it wouldn't be necessary to re-parse each file.

**Comment by JamesHenry** [comment]
@not-an-aardvark We now reuse the ts SourceFile and Program via `parserServices`, so it shouldn't need to re-parse the file already

**Comment by JamesHenry** [comment]
Definitely excited to explore more ideas around briding/conversion though! Just wanted to point that out :)

**Comment by not-an-aardvark** [comment]
> We now reuse the ts SourceFile and Program via `parserServices`, so it shouldn't need to re-parse the file already

I see, I was confused because it's [passing in the source text too](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin-tslint/src/index.ts#L135), but I hadn't realized it was also passing in the parsed version.

**Comment by JamesHenry** [comment]
You might well be right, I need to look into - thanks for following up!

**Comment by JamesHenry** [comment]
@JoshuaKGoldberg Just to confirm, PRs definitely welcome! I think it would be good to use the existing ROADMAP.md as the source of truth for the progress of this, rather than the items in this issue, as it is more discoverable and under version control.

Thanks!

**Comment by fabb** [comment]
Will/can rules that depend on compiler information be implemented in this bridge as well (e.g. the helpful `no-unsafe-any`)

**Comment by bradzacher** [comment]
@fabb here's a list of currently implemented rules that already use the parser services to do get type information.

https://github.com/search?utf8=%E2%9C%93&q=getParserServices+user%3Atypescript-eslint+repo%3Atypescript-eslint+path%3Apackages%2Feslint-plugin%2Flib%2Frules&type=Code&ref=advsearch&l=&l=
