### ISSUE TITLE
Enhancement: [naming-convention] Remove requiresTypeChecking

### ISSUE THREAD

**Issue by graup** [typescript-eslint/typescript-eslint#6204]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/naming-convention/

### Description

The [source code](https://github.com/typescript-eslint/typescript-eslint/blob/0af822abb44c566fc05f52d78c0783282fe5556d/packages/eslint-plugin/src/rules/naming-convention.ts#L57-L58) says "technically only requires type checking if the user uses "type" modifiers".

Can we remove `requiresTypeChecking`? If naming convention is the only typed linting I need, needing the whole `parseOptions.project` setup (and the performance impact that comes with it) just for that seems unnecessary.

The docs actually say "This rule only needs type information in specific cases", but including the rule with its default settings throws an error if you do not specify `parserOptions.project`. That's confusing.

### Fail

```typescript
type foo = boolean;
```

### Pass

```typescript
type Foo = boolean;
```

**Comment by bradzacher** [comment]
The metadata config `requiresTypeChecking` doesn't do anything - that's solely used by our tooling to generate our documentation. The type-information error is not thrown unless type information is actually requested by the rule (the `util.getParserServices(context, false)` call).

Additionally the default config doesn't include any type-aware configuration

https://github.com/typescript-eslint/typescript-eslint/blob/89130772b255071003d866ceb6e357edaeb26ca5/packages/eslint-plugin/src/rules/naming-convention.ts#L29-L48

---

I just tested with a fresh install of our tooling and the config `'@typescript-eslint/naming-convention': 'error'`, and without type-aware linting enabled, and everything worked fine.

If you're encountering errors about the rule needing type information then it's likely something else in your config has changed the config.

An isolated repro, a config, or any additional information would be good.
**Help me to help you.**

**Comment by Josh-Cena** [comment]
Closing assuming it's fixed
