### ISSUE TITLE
Docs: ban-types.md should pull in defaultTypes automatically

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6210]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

https://github.com/typescript-eslint/typescript-eslint/pull/6209: `ban-types.md` has a copy & pasted description of the default rule options. We should instead pull from the source file automatically.

@orta suggested https://github.com/orta/markdown-magic-inline-types & co. as a potential option. I also would love to see if there's anything in Docusaurus for this kind of feature request.

### Affected URL(s)

https://typescript-eslint.io/rules/ban-types/

**Comment by Josh-Cena** [comment]
> I also would love to see if there's anything in Docusaurus for this kind of feature request.

Docusaurus tries to be decoupled from any specific setup, and so far we haven't seen great demand for it (FWIW, we have much greater demand for OpenAPI, etc.)

If you run into any issue while working on it, or if I should investigate myself, I can take a look since winter break is coming :)
