### ISSUE TITLE
Enhancement: [no-explicit-any] Adding the ability to ignore any in extends in generic

### ISSUE THREAD

**Issue by oriSomething** [typescript-eslint/typescript-eslint#6252]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-explicit-any.md

### Description

I propose to adding an option to ignore `any` in generics when there is extend. The reason is that `unknown` doesn't give the same result. and sometimes can actually create less typesafe types. Example:
```ts
declare function tester_unknown<F extends (..._: unknown[]) => unknown>(fn: F): F;

declare function tester_any<F extends (..._: any[]) => any>(fn: F): F;

const withUnkwown = tester_unknown((x: number) => x);
                                // ^^^^^^^^^^^^^^^^ => Error
const withAny = tester_any((x: number) => x); // Will result to `(x: number) => number` as expected
```

### Fail

```typescript
declare function tester_unknown(fn: any): number;
declare function tester_unknown(fn: number): any;
```

### Pass

```typescript
declare function tester_any<F extends (..._: any[]) => any>(fn: F): F;
```

**Comment by bradzacher** [comment]
IMO `Function` would be a better type to use in this situation.
Even better would be a specific type if you could constrain it.

---

This rule is over 4 years old (it's really one of the first rules implemented!) and you're the first person to want an option for this case.
From that I would infer that this is not something that would benefit even a minority of the TS community.

Thanks for filing!

**Comment by Josh-Cena** [comment]
@oriSomething The reason why your code without `any` doesn't work is because function parameters are contravariant, so the top type for a function is `(...args: never[]) => unknown`, not `(...args: unknown[]) => unknown`.

`any` is simply not a thing in the type system. If you trace your program's variance carefully, there should not be a single reason for you to write `any`.
