### ISSUE TITLE
Base rule extension: [prefer-arrow-callback] with correct autofix

### ISSUE THREAD

**Issue by fasttime** [typescript-eslint/typescript-eslint#6301]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+base+rule+extension%22) and found none that match my proposal.
- [X] I have searched the [current extension rule list](https://typescript-eslint.io/rules/#extension-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the base rule

https://eslint.org/docs/latest/rules/prefer-arrow-callback

### Description

In some cases, the `prefer-arrow-callback` base rule generates autofix code that is illegal syntax in TypeScript. This could be addressed with a rule extension.

### Fail

```typescript
/* Example 1 */

// Original code:
[].filter(
  function (value): (unknown) { return value; }
);

// Autofixed code with syntax error:
[].filter(
  (value): (unknown) => { return value; }
);

/* Example 2 */

// Original code:
setTimeout(
  function (): ([number, string]) { return [42, 'foobar'] }
);

// Autofixed code with syntax error:
setTimeout(
  (): ([number, string]) => { return [42, 'foobar'] }
);

/* Example 3 */

// Original code:
Reflect.construct(
  function (): ({ constructor: Function }) { return Object },
[]);

// Autofixed code with syntax error:
Reflect.construct(
  (): ({ constructor: Function }) => { return Object },
[]);
```

### Pass

```typescript
// not relevant
```

### Additional Info

When the callback has a return type annotation in (unnecessary) parentheses, it is not always safe to insert an arrow (`=>`) after the annotation, because sometimes the parser interprets it as the parameter list of an arrow function and complains about the bad syntax.

I can think of three possible solutions here (there are maybe more):
* Leave the callback as it is.
* Remove the unnecessary parentheses in the autofix (e.g. `(value): unknown => { return value; }`).
* Add a new pair of parentheses (e.g. `(value): ((unknown)) => { return value; }`).

**Comment by bradzacher** [comment]
This would probably be worth reporting upstream to eslint core.
I don't think it's great for anyone if we completely fork the lint rule to fix a (frankly rare) bug in the autofixer.
Fkxing it upstream would benefit the entire community without creating any friction with a duplicate rule.

**Comment by fasttime** [comment]
> Fkxing it upstream would benefit the entire community without creating any friction with a duplicate rule.

The autofix works well in JavaScript. Not sure how *fixing* this rule would benefit the whole community.

**Comment by bradzacher** [comment]
Somewhere in the order of 60% of eslint users use TS, so fixing things in core is hugely beneficial to the majority of the community.
