### ISSUE TITLE
Bug: [(2312)] An interface can only extend an object type or intersection of object types with statically known members.ts(2312)

### ISSUE THREAD

**Issue by Nut41tank** [typescript-eslint/typescript-eslint#6303]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&jsx=true&sourceType=module&code=JYWwDg9gTgLgBAZQKYBskGMYBo4G9GoYwDCAFgIYB2A5kgKIBuSl2BamAClBGAM5wBfOADNuIOAHIAAiACuwAPQhyMJFGDkUC5OxgSA3AFgAUCeAs1w8uiRwAgukoARbmAAmEAO6UuPXgB4AFQA+OCQAD1VKN34dIl8+PBM4OBRyACNUAH4ALjheGHUaI2MU4FUQXjzAgG0AXRKUsDSbUggUNzVc-MLzaka4N2BeDLQ3bvSIdqQqAYZNWSRuwIHSVDA1QIiYboKi6jgAHzhKWRQUAbTMlAAlLwmptFnkuApotDIqWjyACiQmFh5OKYT40egAmD+WSUADWlC8lCOPX2wQAlHAALyhBgQYBuEoCIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
@mui
export type SelectProps<T = unknown> = CommonProps<T> & ConditionalRenderValueType<T>;

import Select, { SelectChangeEvent, SelectProps } from '@mui/material/Select';
interface DropdownProps<T> extends SelectProps {
  ...
  handleChange: (event: SelectChangeEvent<unknown | string>) => void;
}
```

### ESLint Config

```javascript
{
  "root": true,
  "extends": ["airbnb", "react-app", "prettier", "plugin:prettier/recommended"],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "settings": {
    "import/resolver": {
      "typescript": {}
    }
  },
  "plugins": ["import", "react", "@typescript-eslint"],
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "endOfLine": "auto"
      }
    ],
    "quotes": [
      "error",
      "single",
      {
        "avoidEscape": true,
        "allowTemplateLiterals": false
      }
    ],
    "import/extensions": [
      "error",
      "always",
      {
        "js": "never",
        "jsx": "never",
        "ts": "never",
        "tsx": "never"
      }
    ],
    "react/jsx-filename-extension": [
      "error",
      {
        "extensions": [".tsx"]
      }
    ],
    "no-nested-ternary": "off",
    "import/prefer-default-export": "off",
    "react/require-default-props": "off",
    "react/prop-types": "off",
    "react/function-component-definition": "off",
    "react/jsx-props-no-spreading": "off",
    "default-param-last": "off",
    "no-shadow": "off",
    "@typescript-eslint/no-shadow": ["error"]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

What did you expect to happen?
should not face
An interface can only extend an object type or intersection of object types with statically known members.ts(2312)

### Actual Result

What actually happened?
face this error
An interface can only extend an object type or intersection of object types with statically known members.ts(2312)

**Comment by bradzacher** [comment]
I'm not quite sure what your issue is about.
You've only mentioned a TS error, but we don't do anything with TS errors.

Was there a bug you'd like to report about an ESLint rule?

**Comment by Nut41tank** [comment]
Thank you for your quick response 
To clarify I'm trying to extend SelectProps from Mui to my interface but 

Lint check told that "An interface can only extend an object type or intersection of object types with statically known members.ts(2312)" 

so, I check the Mui type that I try to extend 
It already exports as a Type like this 
`export type SelectProps<T = unknown> = CommonProps<T> & ConditionalRenderValueType<T>;`
I am not sure whether I am missing something or Eslint problem?

**Comment by bradzacher** [comment]
> Lint check

Again, the error you've mentioned is not an ESLint error - it is a TS error. You can tell because (a) the error code is a number and (b) the error code is prefixed with `ts`.

If you ran `eslint` from your cli you wouldn't see the error, but running `tsc` would reveal it.

This it is not an error reported by our tooling.
Try asking on stackoverflow for TS support!
