### ISSUE TITLE
Rule proposal: Implement typescript version of eslint/no-extra-boolean-cast

### ISSUE THREAD

**Issue by yf-yang** [typescript-eslint/typescript-eslint#6308]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

[eslint/no-extra-boolean-cast](https://eslint.org/docs/latest/rules/no-extra-boolean-cast) conflicts with [@typescript-eslint/strict-boolean-expressions](https://typescript-eslint.io/rules/strict-boolean-expressions) when a variable is `unknown` type.

For example:
``` typescript
const foo: unknown = 'bar';
if (foo) {
  console.log('baz');
}
```
First, @typescript-eslint/strict-boolean-expressions would complain that `An explicit comparison or type cast is required`, and change `foo` with `Boolean(foo)`.
Then, eslint/no-extra-boolean-cast would complain that `Redundant Boolean call`, because the rule has no idea about `unknown` type, so it would consider `Boolean(foo)` as a redundant case.
In such scenario an explicit type cast is necessary, but eslint/no-extra-boolean-cast lacks type info, so I suggest implement this rule in typescript-eslint. Also, eslint/no-extra-boolean-cast is a recommended rule provided by eslint.

### Fail Cases

```typescript
/** @link https://eslint.org/docs/latest/rules/no-extra-boolean-cast#rule-details */
```

### Pass Cases

```typescript
/** @link https://eslint.org/docs/latest/rules/no-extra-boolean-cast#rule-details */
let foo: unknown = 'bar';
if (foo) {
  console.log('baz');
}
```

**Comment by yf-yang** [comment]
After checking https://github.com/typescript-eslint/typescript-eslint/issues/1954, I'm hesitant whether it should be a change of rule eslint/no-extra-boolean-cast. 
Another approach to resolve this is to change the fix behavior of @typescript-eslint/strict-boolean-expressions. For example:
``` typescript
const foo: unknown = 'bar';
if (foo as boolean) {
  console.log('baz');
}
```
Maybe add `as` as a fix for unknown type is better.

**Comment by bradzacher** [comment]
The point of `strict-boolean-expressions` is that you do explicit logical checks, not that you work around it by using the boolean constructor.

Both rules are correctly reporting here.

The correct code would be something like this so you're explicitly habing just one logical case at a time.
```ts
if (value != null) {
  //
}
```

If you really really wanted to intentionally treat all possible falsey cases the same way, then use a disable comment that denotes why you're using a broad approach instead of something fine-grained.

```ts
// eslint-disable-next-line @typescript-eslint/strict-boolean-expressions -- my reasoning for bypassing the rule
if (value) {
  //
}
```
