### ISSUE TITLE
Repo: no-jest-import rule was removed

### ISSUE THREAD

**Issue by MageJohn** [typescript-eslint/typescript-eslint#6322]
### Suggestion

Currently running `yarn lint` in the repo throws the error `Definition for rule 'jest/no-jest-import' was not found` for every package. It looks like the package `eslint-plugin-jest` was recently (in #6233) bumped to version 27.0.0, which removed that rule (see their [changelog](https://github.com/jest-community/eslint-plugin-jest/blob/6f4f84cc28f08f00d8399904d23bd0bca42dde42/CHANGELOG.md#2700-2022-08-28)).

The fix should be simple, just removing the line activating it from the `.eslintrc.js`.

**Comment by JoshuaKGoldberg** [comment]
Indeed. This should have been fixed by #6310. Thanks for reporting!
