### ISSUE TITLE
Enhancement: [dot-notation] allowUnknownPropertyAccess

### ISSUE THREAD

**Issue by KurtPreston** [typescript-eslint/typescript-eslint#6328]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/dot-notation

### Description

We occasionally use square bracket notation to access or edit properties not listed on the type. This can be useful for when the type has limited information.

```
// If we have an object with limited type info
const myObject: object = {};

// I would like to be able to read/write from certain attributes without needing to `(myObject as any)`
// However, the following line errors if `@typescript-eslint/dot-notation` is turned on:
obj["someProperty"] = 5;

// Changing the line to use dot notation results in TypeScript compile errors:
obj.someProperty = 5; // throws error
```

I am proposing a new `allowUnknownPropertyAccess` option to disable the dot-notation check when accessing an unknown property.

### Fail

```typescript
// If allowUnknownPropertyAccess is false, dot-notation will maintain current behavior of throwing an error when accessing an unknown property using square brackets

const myObject: object = {};
obj["someProperty"] = 5;
```

### Pass

```typescript
// If allowUnknownPropertyAccess is true, dot-notation will ignore any properties not listed in the type definition

const myObject: object = {};
obj["someProperty"] = 5; // no error!
```

**Comment by bradzacher** [comment]
As mentioned in the rule docs, use the `noPropertyAccessFromIndexSignature` option

https://www.typescriptlang.org/tsconfig#noPropertyAccessFromIndexSignature
