### ISSUE TITLE
Rule proposal: enforce as-const

### ISSUE THREAD

**Issue by jguddas** [typescript-eslint/typescript-eslint#6331]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

You might want to do `enforce-as-const: [ 'error', { 'UPPER_CASE': ['ObjectExpression'] } ]` which will autofix `const EXAMPLE = { x: 5 }` to `const EXAMPLE = { x: 5 } as const`

Options are the key as [format](https://typescript-eslint.io/rules/naming-convention/#format) and the value is either `true` for all or an array of ast types.

One thing to consider is that there are not just `VariableDeclaration[kind=const]` that could benefit from this,
for example, both `(() => ({x:5})).x` and `({x:5}).x` are of type number when ideally they would be `5`.

That the return type of arrow functions is not supper narrow is generally more of a Typescript issue.
`() => 5` is type `() => number` for example.

I would love your feedback, if this is a good idea in general and could find a place in the strict rule set.

---

We could also not just make it depend on the casing, but on if the variable is reassigned or exported.
```ts
// This would not be autofixed because it is reasigned.
const x = { x: 5 }
x.x = 7
```

I would just love if typescript were smart enough to understand that `x.x` is `5 | 7` in that case :man_shrugging:.

### Fail Cases

```typescript
const EXAMPLE = { x: 5 };
const x = () => 5;
({ x: 5 }).x
```

### Pass Cases

```typescript
const replace = 'me';
const x = { x: 5 }; x.x = 7;
```

**Comment by bradzacher** [comment]
You can't just insert `as const` around the place freely because it makes object and array types readonly, which will then cause errors when you pass things around as most locations won't expect readonly types.

Which means that the only case that can truly benefit from this is if you define a constant "grab bag" object value that solely exists to group some values together in a single declaration.

Which in the general case is a really rare thing and TBH even in that case you may not need to `as const` the entire object unless you really need the true literal types for some usecase.

All round the benefits of this proposal are very niche and the invalid cases it matches are rare. I don't think this is something that should exist in this plugin. Thanks for raising!

**Comment by jguddas** [comment]
> which will then cause errors when you pass things around as most locations won't expect readonly types.

Do you have an example where this is an issue?

**Comment by bradzacher** [comment]
It depends. In some cases, yes, TS correctly disallows you from assigning readonly types to mutable locations. Other times TS incorrectly allows you to readonly types to writeable locations.

There's also the chance that TS tightens this more in future to behave correctly with respect to readonly types.

**Comment by jguddas** [comment]
> All round the benefits of this proposal are very niche and the invalid cases it matches are rare.

Having a convention that makes `UPPER_CASE` variable names read only is super common.
I do think using `as const` is probably not the right solution but the problem is quite common that this convention is not followed.

#### Here is an example

https://github.com/typescript-eslint/typescript-eslint/blob/eefc5781b0f455264e4e58e33c27f8a91b3ab5e3/packages/scope-manager/tests/util/serializers/TSESTreeNode.ts#L48

The solution here would be not `as const` but rather something like this:

```diff
- const SEEN_NODES = new Map<Node, number>();
+ const SEEN_NODES: ReadonlyMap<Node, number> = new Map();
```

#### In the same file, we also have another case
https://github.com/typescript-eslint/typescript-eslint/blob/eefc5781b0f455264e4e58e33c27f8a91b3ab5e3/packages/scope-manager/tests/util/serializers/TSESTreeNode.ts#L7-L15

This would be a good start
```diff
- const EXCLUDED_KEYS = new Set([ 
+ const EXCLUDED_KEYS: ReadonlySet<string> = new Set([ 
```

This would be even better
```diff
- const EXCLUDED_KEYS = new Set([ 
+ const EXCLUDED_KEYS: ReadonlySet<'parent' | 'type' | 'range' | 'loc'> = new Set([ 
```
but doesn't really work due to [`new Set(['a'] as const).has('b' as string)`](https://www.typescriptlang.org/play?#code/HYUw7gBAyiAuAUBtA5AQ2QXQqgzhAxgPbA6wCUAdABa7zIBGy2epATgJbADmZQA) throwing a type error.

> Argument of type 'string' is not assignable to parameter of type '"a"'.

That is a bit weird and IMO a typescript issue, I will see if there already is an issue for having `has` be a type guard.
```ts
- has(value: T): boolean;
+ has(value: unknown): value is T;
```
would make a lot more sense, IMO.

**Comment by jguddas** [comment]
Typescript does provide a `ReadonlyMap` but it is quite limited, there is an open issue for improving the `ReadonlyMap` type. https://github.com/microsoft/TypeScript/issues/36029

Here is a [playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEoTgEwPYgDYCeA8gEYBWECYAMsANYQCycADgDwAqyEAHpCJgDOybOUpgAfMgDeAKGQLkMbFACiiABYAKBHDx4SiOjBAAuZGwDS3PhAHCGBbDGQcJW+Yq8A3PQFcIcw4AbUsAXQAaZEdzSyiAW1ZzMA1gQQBKZABeKW9sYEwolLSAQSgAcwB+czgQAk8FdPM8goBuBuRyiDArG34haIgnFzctGORLJtdQsPavDThBMaHzR2dXKbAoALnFBaXxvxA6EGwAdxApx2Q0weHXXYUoDBx8AmRBYAAvQOQQP3iJGgj2QwQAygRAdg8AA6YCQKBwMAqMJaKYASQRcBIeAgmOgSJUbGkoOsoDu6w4YQAtNVSVEQuEwsgAL7BNYjMISEF2LbACBLDFYnF4rHIqDE0k3EAUzm08yhBkzZlsjmuLkgxyC8z4xEi3WEiVqtwg3x4ALa5AG-ViokhY0ajrPLC4QigiFQ2HIsF8kDlDhwcphcyCX3ldos2SyUAI+BINAvV3EMRUWgMZgsADCuFD2yoKhkTsTb2QLCg2GRYAILF+6Bdb1IFFT9CYrDYtQI3I6IAgZzR5jrr0IjfEadb7GkLK7Xh7Zws1l4-WEAAVyzWoFXLEMIh0vAA1Pp2Aa50DlZAAHz+AKBUAvyBI2GhGBll8EkIfeDvk7v-30d6OmAQDAoAQIUu6KFwi5HsIzpDu8irIHuXIeF4XjwgSIo6sKuKcBIHRTIOSYjs26ZtiSoTStMAAMYTBsgqh8IiVCcFEsFJvSyAdlywQAIwqnhkayAgOZgMgAAiJQcKoAD6ABiRCoIwklgtkfy9sgWgZpxwhHCc5wyosCb1sOKY0C2GbZiAuZ+PmUDpFowQdMEABEmBIhAzlRM5ACavnedSjCMNSYlic5kROa57lgMA8QeV5fn+YFwVicEVIABJpaY8TxGFO5eC5bmQNFsXUng2C6HgnnID5fkBUFIWpWEGVZTl4X5c58S4CkVU1b5dW5RFxVxdVzXZQN7VnBAEB0D1CXUsEADqYQLQtYWyGE6TtEJInIDwqkSVJckKUpHBgjCXRgFoADkhUQFd6SyAA9I9XgAHqVEAA) that also includes some improvements.

If Typescript had a type like `ReadonlyMapConstructor` we could simply autofix `const EXAMPLE = new Map(…)` to `const EXAMPLE = new (Map as unknown as ReadonlyMapConstructor)(…)`.
