### ISSUE TITLE
Bug: Playground crashes when switching between light and dark mode

### ISSUE THREAD

**Issue by lostfictions** [typescript-eslint/typescript-eslint#6335]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

website

### Playground Link

https://typescript-eslint.io/play#ts=4.9.3&sourceType=module&code=C4TwDgpgBAglC8UDeUC+BYAUFgJhAxgDYCGATtAG5lQAeAXFEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
Visit provided playground link to see the issue.
```

### ESLint Config

```javascript
N/A (see playground link)
```

### tsconfig

```jsonc
N/A (see playground link)
```

### Expected Result

The playground should not crash when switching from light to dark mode, or vice-versa. Playground state should be preserved when switching.

### Actual Result

The playground state may disappear and reappear after around 5 seconds of waiting. Then the page crashes.

### Additional Info

Here's a video showing the issue:

https://user-images.githubusercontent.com/567041/212404261-c2f11517-4502-4311-833d-a1b063742c96.mp4

Note that in this video I don't paste in any code -- the page loads up blank, then when I hit the dark mode button, after several seconds the code appears. Then it crashes.

The video shows the page crashing after I refresh it following a previous crash, but this also occurs for me in a fresh incognito session, ie. without any service workers, cookies, localstorage or other persistent state set.

### Versions

- Firefox 108
- Chrome 108

**Comment by armano2** [comment]
side effect of #5663

**Comment by JoshuaKGoldberg** [comment]
I want to investigate this more but am unable to locally for #6368 😞

**Comment by bradzacher** [comment]
@armano2 why would extra hooks deps cause a crash? The only time that there should be truly differing behaviour is if it's an effect with side-effects - otherwise worst case it should just cause more invalidation and thus more renders.

Following from that it likely means that we have a side-effectful `useEffect` which can't be run an extra time. Generally in react such a thing is a dangerous anti-pattern.
IIRC in React 18 strict mode it'll run effects twice in dev to help catch such bugs.

**Comment by armano2** [comment]
not all changes from PR that are linked are causing this, biggest issue is in adding dependencies to `useEffect` when there was none

![image](https://user-images.githubusercontent.com/625469/214305939-1bbab3dd-3cc1-46f9-80d3-4a0ab51aa1a9.png)

**Comment by armano2** [comment]
@bradzacher generally if we pass empty array to `useEffect` it works simmilarry to  `componentDidMount` and `componentWillUnmount`
https://reactjs.org/docs/hooks-effect.html
