### ISSUE TITLE
Bug: [no-floating-promises] Not marking as error when combined with a logical operator variable

### ISSUE THREAD

**Issue by aurislt7** [typescript-eslint/typescript-eslint#6343]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=IYZwngdgxgBAZgV2gFwJYHsL3egFAShgG8BYAKBhikxGRgFswAFAJ3XtRAFMYBeGVu05cAdCy4h0AGwBuXXMhYIu+ANzlK1CLSqYAJqjSY+MRcvVkNuiAaNYAZPYbM2HbhYC+QA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oDN4OBDfMwDmtYtA4BbSshTooiaBOiQANOGx4ipZBWp0GzNp1rTksWQBMxEs3IyRFyyBoC+IV0A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
async function foo() {
  const myPromise = Promise.resolve(true);
  const condition = true;

  condition && myPromise;
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-floating-promises": "error",
    "@typescript-eslint/no-misused-promises": "error",
  },
};
```

### Expected Result

This promise should be marked as `floating-promises` or `misused-promise`.

```
// Wrong usage
 condition && myPromise;

// Correct usage
 condition && await myPromise;
```

### Actual Result

This promise is not marked as floating/misused.

### Additional Info

Similar issue was closed: https://github.com/typescript-eslint/typescript-eslint/issues/2544

**Comment by bradzacher** [comment]
Separately - note that you can catch this particular case using [`@typescript-eslint/no-unused-expressions`](https://typescript-eslint.io/rules/no-unused-expressions), which will warn you that your code doesn't do anything.

[playground](https://typescript-eslint.io/play#ts=4.8.4&sourceType=module&code=IYZwngdgxgBAZgV2gFwJYHsL3egFAShgG8AoGGKTEZGAWzAAUAndW1EAUxgF4ZnX2HAHRMOIdABsAbh1zImCDvgDcZClRqUIAE1RpMPGPMWq1W3fqwAyK3UYs2nVQF8gA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tidmUQAm9AB7FoKZJQ5NUaSImjQO0SODABfEOqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA).

But this wouldn't catch a case like `condition && returnsPromise()`

---

We interrogate [conditional expressions](https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=IYZwngdgxgBAZgV2gFwJYHsL3egFAShgG8AoGGKTEZGAWzAAUAndW1EAUxgF4ZnX2HAHRMOIdABsAbh1zImCDvgDcZClRqUIAE1RpMPGPMWq1W3fqwB+OoxZtOMAFxGFHVQF8gA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oDN4OBDfMwDmtYtA4BbSshTooiaBOiQANOGx4ipZBWp0GzNp1rTksWQBMxEs3IyRFyyBoC+IV0A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA), so I don't see why we shouldn't also interrogate short-circuit logicals.

Happy to accept a PR!
