### ISSUE TITLE
Docs: Add a "how to change rule options" on the docs

### ISSUE THREAD

**Issue by GustavoMelloGit** [typescript-eslint/typescript-eslint#6345]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I have searched a lot and i still did not find any solution on how to change the default option to "type" instead of the default "interface" option. It would be nice if it had a link inside this page in order to change this option

### Affected URL(s)

https://typescript-eslint.io/rules/consistent-type-definitions/

**Comment by GustavoMelloGit** [comment]
I asked chatGPT and he taught me how to do it, if someone has the same question: 
`
**./.eslintrc.json**
"rules": {
    ...
    "@typescript-eslint/consistent-type-definitions": ["error", "type"]
 },
`

**Comment by bradzacher** [comment]
The docs examples include the config you can put into your eslintrc. EG 
```ts
/* eslint @typescript-eslint/consistent-type-definitions: ["error", "interface"] */

type T = { x: number };
```

ESLint's docs also include the information you're looking for:
https://eslint.org/docs/latest/use/configure/configuration-files

We link to this doc from our getting started guide:
https://typescript-eslint.io/getting-started/#details
