### ISSUE TITLE
[array-type] add `ReadonlyArray` option

### ISSUE THREAD

**Issue by a-tarasyuk** [typescript-eslint/typescript-eslint#635]
**Repro**

```TS
// "typescript/array-type": ["error", "array"]
const x: Array<number> = [1];
// fixes to
const x: number[] = [1];
```

```TS
// "typescript/array-type": ["error", "ReadonlyArray"]
const x: ReadonlyArray<number> = [1];
// fixes to
const x: readonly number[] = [1];
```

```TS
// "typescript/array-type": ["error", "array", "ReadonlyArray"]
const x: ReadonlyArray<number> = [1];
const y: Array<number> = [1];
// fixes to
const x: readonly number[] = [1];
const y: number[] = [1];
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.10.2` |
| `@typescript-eslint/parser`        | `1.10.2` |
| `TypeScript`                       | `3.5.2` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `8.15.0` |
| `npm`                              | `6.4.1` |

**Comment by sindresorhus** [comment]
Related to https://github.com/typescript-eslint/typescript-eslint/issues/514

**Comment by a-tarasyuk** [comment]
@sindresorhus @bradzacher maybe need to close this issue in favor to #514?

**Comment by bradzacher** [comment]
No - the two are distinct rules.
This is an _option_ for `array-type` which enforces you use `ReadonlyArray` instead of `readonly array[]`.

#514 is a new rule which enforces that function arguments are readonly where appropriate, and return values are (optionally) not.
