### ISSUE TITLE
Repo: Automate version ranges in website's Versioning.md

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6389]
### Suggestion

From https://github.com/typescript-eslint/typescript-eslint/pull/6251#discussion_r1090119075: we have hardcoded version ranges in _Versioning.md_:

https://github.com/typescript-eslint/typescript-eslint/blob/66708d737855174ef7fe53c0023c4d78497d2e4f/docs/maintenance/Versioning.md#L45

Let's use some kind of Docusaurus<>React component shenanigan(s) to automate this. Supported version ranges should be sourced from our `package.json`s.

**Comment by armano2** [comment]
when we expose those as variables we should update playground to allow only those versions

![image](https://user-images.githubusercontent.com/625469/221313308-8d88b112-e153-4d37-85a3-23358249548b.png)
