### ISSUE TITLE
Enhancement: [ban-types] Specify severity for individual types.

### ISSUE THREAD

**Issue by jordanjlatimer** [typescript-eslint/typescript-eslint#6390]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/ban-types

### Description

I'm currently working on a codebase that has this custom type:
```
interface GenericObject {
    [prop: string]: any;
}
```
We're trying to clean up the codebase and remove the usage of `any`. This object introduces `any` implicitly and so has caused the `any` type to creep into our functions.

I would like to ban this type, but with only a severity of "warn" while we work on removing its usage. However, I **also** want to ban the default types as well with a severity of "error". Looking at the documentation for the rule "ban-types", there doesn't appear to be a way for me to do what I want. The severity of all banned types has to be the same.

### Fail

```typescript
const str: String = 'foo';
const bool: Boolean = true;
// ... all other default banned types with a severity of "error"

const genericObject: GenericObject = {};
// with a severity of "warn"
```

### Pass

```typescript
const str: string = 'foo';
const bool: boolean = true;
// ...

const genericObject: Record<string, unknown> = {}
```

**Comment by bradzacher** [comment]
Unfortunately ESLint does not support different severities for the same rule.

Rules can report problems only. It is your config which specifies the level for the entire rule.

**Comment by Josh-Cena** [comment]
FWIW, I've always wanted this ability as well—mainly for `no-restricted-syntax`, because I have to implement so many things with it. Sometimes I wonder if we can register two rules that do the same thing, just to allow users to config them with different severities.

**Comment by bradzacher** [comment]
> Sometimes I wonder if we can register two rules that do the same thing, just to allow users to config them with different severities

I think that you could make this work with the new config system like:
```ts
import ts from '@typescript-eslint/core'; // doesn't exist yet TODO 

export [
  {
    files: ['**/*.{ts,tsx}'],
    plugins: {
      '@typescript-eslint': ts,
      'ban-types1': ts,
      'ban-types2': ts,
    },
    rules: {
      '@typescript-eslint/ban-types': ['error', { ... }],
      'ban-types1/ban-types': ['warn', { ... }],
      'ban-types2/ban-types': ['error', { ... }],
    },
    // ...
  },
];
```

Haven't tried it but I assume ESLint doesn't care if you use the same plugin under different aliases?
