### ISSUE TITLE
Repo: Simplify typeof === 'undefined' checks

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6398]
### Suggestion

Forking from https://github.com/typescript-eslint/typescript-eslint/pull/6228#pullrequestreview-1274605754: this is a small internal change that shouldn't impact any users. 

> if you wanted to go one step further and clean up our now out-of-style `typeof x === 'undefined'` checks as part of this - that'd be gr8

https://cs.github.com/typescript-eslint/typescript-eslint?q=%2Ftypeof+.%2B%3F+%5B%21%3D%5D%3D%3D+%27undefined%27%2F

**Comment by theVJagrawal** [comment]
Can I work on this issue? I am pretty new to open source stuff

**Comment by JoshuaKGoldberg** [comment]
Please do @theVJagrawal, that'd be great!

In general, what we're looking for simplifying code like:

```diff
- if (typeof abc.def === 'undefined') {
+ if (abc.def) {
```

The only exception would be around checking for the existence of some globals (e.g. `process`).

**Comment by fisker** [comment]
Maybe [`unicorn/no-typeof-undefined`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-typeof-undefined.md) can help?
