### ISSUE TITLE
@typescript-eslint/parser seems to be incompatible with ESLint v6

### ISSUE THREAD

**Issue by joealden** [typescript-eslint/typescript-eslint#641]
The breaking changes introduced in v6 of ESLint seem to have made it incompatible with `@typescript-eslint/parser` v1.10.2 (the latest version as of writing).

The following is logged when running our linting script (`eslint . --ext .js,.ts,.tsx`):

```
$ eslint . --ext .js,.ts,.tsx
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js': Cannot find module 'eslint/lib/util/traverser'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (project/node_modules/@typescript-eslint/parser/dist/parser.js:7:37)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 2.
```

From the error message, it looks like `@typescript-eslint/parser` depends on ESLint utilities that are no longer available in v6 (this is just an educated guess though).

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `1.10.2` |
| `TypeScript`                | `3.5.2` |
| `ESLint`                    | `6.0.0` |
| `node`                      | `10.16.0` |
| `yarn`                       | `1.16.0` |

**Comment by platinumazure** [comment]
Hi @joealden, this is fixed in master- try installing the canary version.

**Comment by marcobiedermann** [comment]
@platinumazure

Sorry to ask but could you show me how to install the canary version?

I've tries `@next` and `@latest` but it still points to the same version.

**Comment by joealden** [comment]
@marcobiedermann `@canary`.

**Comment by JamesHenry** [comment]
1.11.0 has now also been released which contains the necessary update

**Comment by bradzacher** [comment]
@marcobiedermann - for future reference, @joealden is correct.

as per our readme:
https://github.com/typescript-eslint/typescript-eslint#package-versions

**Comment by ironsoul0** [comment]
> 1.11.0 has now also been released which contains the necessary update

It seems problem still exists even in 1.11.0 release :(

<img width="1440" alt="git pro" src="https://user-images.githubusercontent.com/31582693/60044190-83c81980-96ca-11e9-89cf-c42ad8f2a86e.png">

**Comment by bradzacher** [comment]
@ironsoul0 - that is a different error.

This issue was about an internal dependency of the parser being missing.

Your issue is that eslint cannot find the parser at all.

Please open a separate issue to discuss it.
