### ISSUE TITLE
Bug: [@typescript-eslint/no-unsafe-argument] import package.json

### ISSUE THREAD

**Issue by loynoir** [typescript-eslint/typescript-eslint#6419]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/

### Repro Code

```typescript
import { name } from './package.json'

function foobar(s: string) {
  console.log(s)
}

// Unsafe argument of type `any` assigned to a parameter of type `string`
// eslint-disable-next-line @typescript-eslint/no-unsafe-argument
foobar(name)
```

### ESLint Config

```javascript
{
      extends: [
        'plugin:prettier/recommended',
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:@typescript-eslint/recommended-requiring-type-checking',
      ],
      files: ['*.mts'],
      plugins: ['@typescript-eslint'],
      parser: '@typescript-eslint/parser',
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: 'module',
        project: ['./tsconfig.json'],
        tsconfigRootDir: '.'
      }
    }
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
    "resolveJsonModule": true
  }
}
```

### Expected Result

```ts
import { name } from './package.json'

function foobar(s: string) {
  console.log(s)
}

foobar(name)
```

### Actual Result

Unsafe argument of type `any` assigned to a parameter of type `string`

**Comment by sudhakar3697** [comment]
@loynoir I am still seeing this error when I tried to import package.json and get the version. Kindly let us know if you have solved it. TIA.

**Comment by loynoir** [comment]
@sudhakar3697 I touched something, complain was gone, I guess somehow it can be solved.
