### ISSUE TITLE
Docs: eslint new-config-system

### ISSUE THREAD

**Issue by loynoir** [typescript-eslint/typescript-eslint#6420]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

https://eslint.org/blog/2022/08/new-config-system-part-2/#goodbye-extends%2C-hello-flat-cascade
> Goodbye extends, hello flat cascade

seems new eslint config deprecated `extends`

https://typescript-eslint.io/getting-started
```js
module.exports = {
  extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended'],
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint'],
  root: true,
};
```

### Affected URL(s)

- https://eslint.org/blog/2022/08/new-config-system-part-2/#goodbye-extends%2C-hello-flat-cascade
- https://typescript-eslint.io/getting-started

**Comment by bradzacher** [comment]
The new tooling is still very early on in its release - call it a beta currently.

We'll be looking to build out integration as part of "stage 3" of eslint's plan
https://github.com/eslint/eslint/issues/13481

Its not as simple as just documenting things, sadly, we need to change our code to make it work.

**Comment by CallMeLaNN** [comment]
@bradzacher I was going deep into the flat config and this plugin config too until it's working. The stage 3 almost there and the last PR waiting for approval. I've seen a few docs request has been closed, do you mind if I open an improvement?

At least we have something from what I got to initiate the compatibility. I believe the changes is not much and possible for me to try it.
