### ISSUE TITLE
Enhancement: [no-explicit-any] add option to allow 'any' when used in extends clause

### ISSUE THREAD

**Issue by bbrzoska** [typescript-eslint/typescript-eslint#6437]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-explicit-any/

### Description

It's useful to use `any` in an `extends` clause. 

For example, it is 100% type safe to use `any` to limit what template types can be used in a given type, without having to restrict their output type. `T extends any ? ... : ...` can also be used to distribute a union type. See [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types) for explanation and examples using `any`.

Note that `unknown` cannot be used in place of `any` in such cases, because that prevents `undefined` from being assigned to it.

### Fail

```typescript
const value: any = 'value';
```

### Pass

```typescript
interface SomeInterface<T extends {type: any}> {
  value: T
}
```

```typescript
export type UnionToIntersection<U> = 
  (U extends any ? (k: U) => void : never) extends ((k: infer I) => void) ? I : never
```

### Additional Info

There was https://github.com/typescript-eslint/typescript-eslint/issues/6252 but it gave an example with a function that could be typed differently. This is a different use case.

**Comment by bradzacher** [comment]
> T extends any ? ... : ... can also be used to distribute a union type. See [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types) for explanation and examples using any.

You're misunderstanding the handbook there. It's not saying that `any` specifically makes TS distribute a union type into a conditional - the handbook is saying that union types are distributed into a conditional, full stop - the constraint type doesn't matter at all

For example:
```ts
type ToArray1<Type> = Type extends string | number ? Type[] : never;
type Test1 = ToArray1<string | number>;
//   ^? string[] | number[]

type ToArray2<Type> = Type extends unknown ? Type[] : never;
type Test2 = ToArray1<string | number>;
//   ^? string[] | number[]
```
[playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKg9gQQE5IIYgIwB4bggPigF5Y8oIAPYCAOwBMBnKB4JASxoHMoAfKGgK4BbAEYQkUAPylIAbQC6UAFz8IAN3EBuAFChIsCCwzFYiFOmwt2XXv2Fik+HQHpnUdwD1J23WXjI0EAAmHDxCElx9Smp6JgEaAGsaOAB3GikZCAVlVQ0kHT1oGENgIJN-c0wsKw5uPkFRcSdtV3coL20gA)

> Note that unknown cannot be used in place of any in such cases, because that prevents undefined from being assigned to it.

Does it? To me it looks like `undefined` is perfectly acceptable in all cases:
```ts
type ToArray1<Type> = Type extends any ? Type[] : never;
type Test1 = ToArray1<string | undefined>;
//   ^? undefined[] | string[]

type ToArray2<Type> = Type extends unknown ? Type[] : never;
type Test2 = ToArray1<string | undefined>;
//   ^? undefined[] | string[]

type ToArray3<Type> = Type extends never ? Type[] : never;
type Test3 = ToArray1<string | undefined>;
//   ^? undefined[] | string[]
```
[playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKg9gQQE5IIYgIwB4bggPigF5Y8oIAPYCAOwBMBnKVGkKAflMgG0BdKAFxQaEAG4QkAbgBQoSLAgNgGYrEQp02JUgCWNAOZQAPlACu9CADM9EOvhkB6B1BcA9dtNll4yNCABMOHiEJLjylNT0TOYA1jRwAO40HFwQfILCYhIyctAwisD+qj4amFjaeoYm5nRWNnaOzm4eXvIlfgDMQZAhqeRUtIyZ4kgpYWn8QiIjOd4FHcXqflrAugbGZhbWIg3STi5Q7tJAA)

```ts
interface SomeInterface1<T extends {type: any}> {
  value: T
}
// no errors, as expected
const test1: SomeInterface1<{ type: undefined }> = {
    value: {
        type: undefined,
    },
};

// no errors either!
interface SomeInterface2<T extends {type: unknown}> {
  value: T
}
const test2: SomeInterface2<{ type: undefined }> = {
    value: {
        type: undefined,
    },
};
```
[playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoHsC2ECS5rxICMAPACrIQAekIAJgM7IDeYAngA4QBcycIbAL4A+FgChkyAG5wANgFceyMmMFiA9OuQh0lKFHRQGAGj5NqXBJDpiE6EAzDJIjorwzY8kWIgilmzpxK8vQQMKAQdMgiyAC84pKSMgpKzBKJGexcvCF0YRF0xumSgkWCANxiGlo6egZGlMBgABbQAIRioN6EKB64+D5IAEzklDQQ9EysQTkgANY6AO4gMWlJcoq8Kmp2Dk4uYEPuWP3dviMBWcGh4SCR0aLxa4nJmwkZiVezebeRRRmlVSVIA)

> For example, it is 100% type safe to use any to limit what template types can be used in a given type, without having to restrict their output type.

This is factually incorrect. TS uses the constraint to determine how you may interact with the type down-the-line.

An example of where this might be unsafe:
```ts
function test1<T extends {type: any}>(arg: T) {
    // fine, as expected
    arg.type = 1;
    // no error
    arg.type.this.will.crash.and.ts.wont.catch.it();
}

function test2<T extends {type: unknown}>(arg: T) {
    // fine, as expected
    arg.type = 1;
    // TS will error and prevent you doing dumb things
    arg.type.this.will.crash.and.ts.wont.catch.it();
}
```
[playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygRgDwBVEoAeqYAJmogN5QCeADigFyICGYNAvgHwAULATgHNmuAJRUAUImmIA9LMTAYYFABpWFIg2gpSUmQMEA6Wg0QBeRJgDc+6fMRg4Bfvzj87rISfooTACxg0IwB3GAAbcKMIfhY0fyM2UhNgkIQoaJYoCASYKB5RWw4JCVBIWARkdCgAJjwCYhQyCmpfZnAAaycQsG4+IRFxSk8HJRV1OIbtVD0ZL2NTFAsrWzmHXABlRDDIlzd+VjJEOn4UADcmqEQaOBBEUjhlQXuQAFsAI2RAsEE0T0MfAwAkFQhEojE4gkkilQulMtlcvlChIOEA)

You should not be using `any` unless you really, really, really, really need to - and most of the time even then there's probably a better alternative.

**Comment by Josh-Cena** [comment]
I would also suggest `T extends T` since it's shorter to type.
