### ISSUE TITLE
Rule proposal: no-type-annotations-with-as-const

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#6446]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

# `no-type-annotations-with-as-const`

In the JavaScript/TypeScript ecosystem, constants are conventionally denoted by SCREAMING_SNAKE_CASE. Prior to TypeScript version 3.4, they would look something like this:

```ts
const MY_ARRAY: readonly number[] = [1, 2, 3];
```

TypeScript version 3.4 introduced `as const`, which means it is both more-succinct and more-safe to write it like this:

```ts
const MY_ARRAY = [1, 2, 3] as const;
```

As a TypeScript programmer, once you learn about `as const`, you will begin to sprinkle it throughout your codebase, in order to make everything safer. However, when doing so, it is easy to make this mistake:

```ts
const MY_ARRAY: readonly number[] = [1, 2, 3] as const;
```

Here, we have added `as const` to the end of an existing read-only array, with the intent to make the code slightly more safe. However, we have also forgotten to remove the explicit type annotation. Uh oh! This essentially means that the `as const` part is doing nothing at all, because the type immediately gets widened by the explicit type annotation.

This kind of thing is almost always a bug, so we need a lint rule to warn us when both `as const` & an explicit type annotation are present at the same time.

### Test Cases with Arrays

```ts
const MY_ARRAY: readonly number[] = [1, 2, 3] as const; // Fail
const MY_ARRAY = [1, 2, 3] as const; // Pass
```

### Part 2 - Objects

Consider the following object:

```ts
interface Thing {
  foo: string;
  bar: number;
}

const MY_THING: Thing = { foo: "lol", bar: 123 } as const; // Fail
```

In this case, if the hypothetical lint rule told us to drop the `Thing` explicit type annotation, this would actually remove type safety, because the compiler would no longer guarantee that all of the `Thing` fields are present.

Crap. So now things get slightly more complicated.

Instead, I envision that the lint rule would recommend the following:

```ts
const MY_THING = { foo: "lol", bar: 123 } as const satisfies Thing; // Pass
```

### Arrays of Objects

The same logic would apply to arrays of objects. For example, using the `Thing` from the previous section:

```ts
const MY_THINGS: Thing[] = [
  { foo: "lol", bar: 123 },
  { foo: "haha", bar: 456 },
] as const;
```

Here, if we simply removed the explicit type annotation, we would actually lose some type safety in the same way as the previous section. So this is another case where the rule should recommend to use `satisfies`:

```ts
const MY_THINGS = [
  { foo: "lol", bar: 123 },
  { foo: "haha", bar: 456 },
] as const satisfies Thing[];
```

Thus, in order to give the end-user the correct recommendation / error message, I believe that the rule would need to distinguish between the cases of trivial primitives (e.g. `string` / `number` / `boolean`) and objects.

**Comment by bradzacher** [comment]
You can achieve this banning behaviour in the general case without a rule - just using `no-restricted-syntax` would be good enough for this.

https://typescript-eslint.io/linting/troubleshooting/#how-can-i-ban-specific-language-feature

```js
{
  'no-restricted-syntax': ['error', {
    selector: 'VariableDeclarator[id.typeAnnotation] > :matches(TSTypeAssertion, TSAsExpression) > TSTypeReference.typeAnnotation > Identifier[name="const"]',
    message: "Don't use `as const` with an annotated variable",
  }]
}
```
[playground example](https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&showAST=es&code=PQKgUApgzgNglgOwC4AIEHsC0AnaTtwDGSEAJplAJ7ICGAHgFwoDaA5BNtutqwDQoBvMChRQIMCMW5NWANRoEaAIwkARSTAU0k3ZnFIA6JJQAOEAIIIMSbXHQIAuigB8KBgFtthABbQAFAAqAMoBphZQYthIdgj8weZQAKJ0JrgRMQCULijBoWYAShAAZhwQCIQQRmGW1rb22QCSpGXRRXAczAg07hAAvABEhPZQSP0OfMIoPRE0AOYQTP2q9qyoAK5iKAAGNFAoQwgjWygA7nBI3ig0CFdW6DYkpCgAbgpwyhL9vGAAvg5gIGAYDABxGKAAsgBNAD65ny+XMkIAjExcDRSPYYJQ0Gt3EoOk5eiwkfwAEz8ADMTl2+2GSAA3ChgMAUAAxGhwGAgukQmFwhGQ0koInMEkockoKlXPaghlMlkABV2UGBwMQJGwRRoFRy3kQs0EkyK6HQTBGBAQs3pkyUCiYCFx+Ow1p+wNlvOhAQAEg0AHIAcRRuv1wsEKGNppQ-Rg6BgXxQtuwTCRpIpKB+0tphzlzLZHK57qhnp9AaFRIE4ZNixjcf4ieTqfTmfdUFsUDa0GDlsZuaVETdPKL3r9-qCQbRGIQWK7s2YhJYkwrEersfj9ZQKbTP2+IiXVaj3hoh7XdpQABYAKwANnT32pMrp1sLMOHAaCZYXu8rkejq7rp83W9F2-RZD2Pf8k3Pa8gPvLMwVbaJ23aPYJ0xbEAj1S052tIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)

It wouldn't let you differentiate between objects, arrays and primitives though.

---

As for the style as a whole - I don't know if there's really too much of a win in going further than that for a rule in this project.

You mentioned a few times that you're losing safety, but you're actually not - widening the type from a tuple to a readonly array isn't a loss of safety - it's just a wider type. TBH in a lot of cases the wider type might be "more correct" as a representation of the value.

I definitely hear you in regards to not having the object keys explicitly typed - there's a separate proposal which is intended to help ensure you avoid anonymous object types - #1467 which would be of more general-purpose use I think.

**Comment by Zamiell** [comment]
Thanks a lot Brad! I will give that "no-restricted-syntax" rule a whirl.

**Comment by bradzacher** [comment]
It's been a month and this issue has garnered no additional reactions or comments from the community. As such I'm going to close and reject this from the plugin, as it does not appear to represent a problem the wider community is interested in.
