### ISSUE TITLE
Bug: Link is broken on "recommended"

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#6447]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

website

![image](https://user-images.githubusercontent.com/5511220/218052092-ae264e46-165d-4daa-b7df-77679ffe1940.png)

Link is broken when clicking on "recommended". I believe it happens on every page.

**Comment by bradzacher** [comment]
It looks like it links to

https://typescript-eslint.io/docs/linting/configs#recommended

Instead of

https://typescript-eslint.io/linting/configs#recommended

I guess it's not covered by the docusaurus checks because the link is inserted via our custom react components.
