### ISSUE TITLE
Docs: [no-explicit-any] missing examples for `ignoreRestArgs`

### ISSUE THREAD

**Issue by thw0rted** [typescript-eslint/typescript-eslint#6461]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

The current docs for no-explicit-any include sections for

> Examples of incorrect code for the { "ignoreRestArgs": false } option

and

> Examples of correct code for the { "ignoreRestArgs": true } option

but the other two cases, correct code for `ignoreRestArgs: true` and incorrect code for `ignoreRestArgs: false` are not covered.  The docs should provide correct and incorrect examples for all options.

### Affected URL(s)

https://typescript-eslint.io/rules/no-explicit-any/

**Comment by JoshuaKGoldberg** [comment]
It'd be nice to see the `ignoreRestArgs` part of that page converted to having proper `❌ Incorrect` / `✅ Correct` tabs for its code snippets. Accepting PRs!
