### ISSUE TITLE
Bug: [require-await] Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by roydukkey** [typescript-eslint/typescript-eslint#6477]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

I expect the configuring `require-await` to not crash.

```sh
TypeError: Cannot read properties of undefined (reading 'type')
Occurred while linting /xxx/moist/src/main.ts:1
    at Array.<anonymous> (/xxx/moist/node_modules/esquery/dist/esquery.min.js:1:29469)
    at /xxx/moist/node_modules/esquery/dist/esquery.min.js:1:29985
    at /xxx/moist/node_modules/esquery/dist/esquery.min.js:1:30512
    at Function.b.matches (/xxx/moist/node_modules/esquery/dist/esquery.min.js:1:34848)
    at NodeEventGenerator.applySelector (/xxx/moist/node_modules/eslint/lib/linter/node-event-generator.js:296:21)
    at NodeEventGenerator.applySelectors (/xxx/moist/node_modules/eslint/lib/linter/node-event-generator.js:324:22)
    at NodeEventGenerator.enterNode (/xxx/moist/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/xxx/moist/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /xxx/moist/node_modules/eslint/lib/linter/linter.js:1153:32
    at Array.forEach (<anonymous>)
```

### Reproduction Repository Link

https://github.com/roydukkey/moist/tree/typescript-eslint/require-await

### Repro Steps

1) clone the repo
2) `npm install`
3) `npm run lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.52.0` |
| `@typescript-eslint/parser`            | `5.52.0` |
| `TypeScript`                           | `4.9.3` |
| `ESLint`                               | `8.34.0` |
| `node`                                 | `16.19.0` |

**Comment by riiji** [comment]
Same issue

<!DOCTYPE html>

package | version
-- | --
@typescript-eslint/eslint-plugin | 5.52.0
@typescript-eslint/parser | 5.52.0
TypeScript | 4.9.4
ESLint | 8.34.0
node | 18.13.0

**Comment by bradzacher** [comment]
https://github.com/estools/esquery/issues/135

This is a bug in esquery, not in our tooling. Please subscribe to the above issue (please don't comment) and wait patiently for a fix.

**Comment by Silvea12** [comment]
As mentioned in the referenced issue https://github.com/estools/esquery/issues/135, this is not a typescript-eslint bug, it's an esquery bug in 1.4.1.  An easy solution for now is to explicitly include esquery version 1.4.0 (no ^) via ` npm i -D esquery@1.4.0 --save-exact`
