### ISSUE TITLE
JSX comment value is from previous line, not comment

### ISSUE THREAD

**Issue by k2snowman69** [typescript-eslint/typescript-eslint#648]
**What code were you trying to parse?**

```ts
return <input 
  // Onclick
  onClick={() =>{}}
  // OnBlur
  onBlur={() =>{}} />;
```

**What did you expect to happen?**
When parsing with 
```
  return parser.parse(text, {
    comment: true,
    errorOnUnknownASTType: false,
    jsx: true,
    loc: true,
    range: true,
    tokens: true,
    useJSXTextNode: false,
    // Override logger function with noop,
    // to avoid unsupported version errors being logged
    loggerFn: () => {}
  });
```
That the comments returned to contain
```
[
              {
                type: "Line",
                value: " Onclick",
                range: [18, 28],
                loc: {
                  start: { line: 2, column: 2 },
                  end: { line: 2, column: 12 }
                }
              },
              {
                type: "Line",
                value: " OnBlur",
                range: [50, 59],
                loc: {
                  start: { line: 4, column: 2 },
                  end: { line: 4, column: 11 }
                }
              }
            ];
```
**What actually happened?**

comments contain:
```
[
              {
                loc: {
                  end: { column: 15, line: 1 },
                  source: null,
                  start: { column: 0, line: 1 }
                },
                range: [0, 15],
                type: "Line",
                value: "turn <input \r"
              },
              {
                type: "Line",
                value: " Onclick",
                range: [18, 28],
                loc: {
                  start: { line: 2, column: 2 },
                  end: { line: 2, column: 12 }
                }
              }
            ];
```

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `1.11.0` |
| `TypeScript`                           | `3.5.2` |
| `node`                                 | `10.15.3` |
| `npm`                                  | `6.5.0` |

**Comment by NickHeiner** [comment]
I believe I've observed this same problem. I see it with @typescript-eslint/parser@1.11.0, but not with @typescript-eslint/parser@1.7.0.

Here's a repo that provides a self-contained example: https://github.com/NickHeiner/eslint-test-no-fallthrough/blob/master/index.js. Check out branch https://github.com/NickHeiner/eslint-test-no-fallthrough/blob/tslint-estree-1.7.0/index.js to see it passing with the old version.

**Comment by k2snowman69** [comment]
@NickHeiner You should be able to go all the way up to `@typescript-eslint/parser@1.10.2` without hitting this issue.
