### ISSUE TITLE
Bug: [@typescript-eslint/dot-notation] dot-notation conflict with typescript in case of type union with uncommon fields

### ISSUE THREAD

**Issue by KuSh** [typescript-eslint/typescript-eslint#6483]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=C4TwDgpgBAKuEEYoF4oG8oEMBcUDOwATgJYB2A5gNxQC+lAUKJLPAEwrpQBGuBJF1Oo3hQAqqWIB7UhziQkAHxaRWDegGNpBKMTxzEHABQA3TABsArhFzippAJS5Tl6LuUHkAPnpQoAQj9nKwBtAHJMUIBdagB6GKgAASYIPHUSMGAAWhSzMmAYgBNJLNJizGA7KAB3TEIJCnoNLWAdPTYjIOsxCWlHKE7W93YvH39A8ysAOi5Y+OA8Q1YAZiWATnsoCEJCSUIdADMoAEkoCzxoIpbS4HK7IA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUFtQCYHsAXAWgDsiBDQgS31PSnwDMnIAacHKAAUIE8ADigDG0agJIp41UoQD0BEuUJVa9DJADuFaPU4BfEPqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUhFYABUyxEWPAE8AgtGjoSJAGKL4ASSIATdAA8AysgDmRAIZ42mdBTCj0UgL4hvQA

### Repro Code

```typescript
type Type1 = { a: string; };
type Type2 = { b: string; };
type Union = Type1 | Type2;

const isType1 = (value: Union): value is Type1 =>
  !!value['a']; // @typescript-eslint/dot-notation warning
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
      "dot-notation": "off",
      "@typescript-eslint/dot-notation": "warn"
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true,
    "noPropertyAccessFromIndexSignature": true
  }
}
```

### Expected Result

I expect no warning as resolving it generate a typescript error

### Actual Result

@typescript-eslint/dot-notation warning on 6th line

**Comment by Josh-Cena** [comment]
Hey, the reason why `value['a']` doesn't give an error is because you don't have `noImplicitAny` on, which I don't think any reasonable TS codebase would leave off. I don't feel like we want to take care of this at the cost of outright unsoundness. You should be using a proper discriminated union:

```ts
type Type1 = { type: "a", a: string; };
type Type2 = { type: "b", b: string; };
type Union = Type1 | Type2;

const isType1 = (value: Union): value is Type1 => value.type === "a";
```

**Comment by Josh-Cena** [comment]
You should still use an `in` check. `const isType1 = (value: Union): value is Type1 => "a" in value;` Your code wouldn't typecheck under `noImplicitAny` anyway.

**Comment by bradzacher** [comment]
Yup - Josh is correct here
The types are not indexable with the string indexer. In any codebase using `noImplicitAny` this code will cause an error:

```
Element implicitly has an 'any' type because expression of type '"a"' can't be used to index type 'Union'.
  Property 'a' does not exist on type 'Union'.
```

With the option off, this index access will return `any`,which you're hiding from your types with an explicit return type annotation.

Josh is correct - this is an edge-case intersection of a bad config mixed with bad code.
We could fix it, but I don't think it's a good idea or worth the effort to support this sort of bad case that is going to be so, so, so rare.

This is the first time in 3 years that this has been reported - very rare and it probably won't happen again!

Suggested alternatives:
- turn on `noImplicitAny`
- use an `in` check instead of direct property access
