### ISSUE TITLE
Enhancement: [ban-types] Suggest `NonNullable<unknown>` as an alternative for `{}` and `Object`

### ISSUE THREAD

**Issue by grumpygreenguy** [typescript-eslint/typescript-eslint#6486]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/ban-types/

### Description

The rule forbids the use of the type `{}` (and its synonym `Object`), which means "any non-nullish value", and gives some helpful suggestions on what to use instead, depending on what the developer actually might have meant.

However, there seems to be no suggestion (outside [disabling the rule](https://github.com/typescript-eslint/typescript-eslint/issues/5542#issuecomment-1227114340)) for what to use when the intended meaning _really_ is "any non-nullish value". The suggested alternative for "any object", namely `object`, doesn't include primitive types such as `number`, so it's not an equivalent replacement in this case.

Rather than bypassing or disabling the rule, and leaving the easily misunderstood `{}` in place, I think it would be useful to suggest an explicit alternative for this case as well; something along the lines of
```
- If you really want a type meaning "any non-nullish value", you probably want `NonNullable<unknown>` instead.
```
(placed _after_ all the other suggestions).

TypeScript includes the [`NonNullable` utility type](https://www.typescriptlang.org/docs/handbook/utility-types.html#nonnullabletype) since 2.8, so I don't think there shouldn't be any compatibility issues.

PS: I wasn't sure if this issue should go under Documentation or Enhancement; since it changes the output of the rule I opted for the latter. My apologies if I got it wrong :)

### Fail

```typescript
/**
 * This is a generic combinator to add a fallback value to a function, to handle a null input.
 * However, we don't want to accidentally use it when the function _already_ handles null,
 * otherwise our fallback will clobber the original value.
 */
const withFallback: <Input extends {}, Output>( // This fails the rule and that's OK :)
  mapping: (input: Input) => Output,
  fallback: Output
) => (input: Input | null) => Output = (mapping, fallback) => (input) =>
  input === null ? fallback : mapping(input);

const plusOne: (input: number) => number
const plusOneWithFallback = withFallback(plusOne, 0); // This won't compile if we replace {} with object
```

### Pass

```typescript
const withFallback: <Input extends NonNullable<unknown>, Output>( // Same meaning, explicit, passes :)
  mapping: (input: Input) => Output,
  fallback: Output
) => (input: Input | null) => Output = (mapping, fallback) => (input) =>
  input === null ? fallback : mapping(input);

const plusOne: (input: number) => number
const plusOneWithFallback = withFallback(plusOne, 0); // This compiles
```

**Comment by JoshuaKGoldberg** [comment]
👋 @grumpygreenguy, sorry for the delay here! This seems reasonable to me (and @Josh-Cena also 👍d). Accepting PRs to add the new line to the end of the existing output for the rule.

**Comment by grumpygreenguy** [comment]
@JoshuaKGoldberg No worries; thanks to you and @NotWoods for picking this up! :raised_hands:
