### ISSUE TITLE
Repo: Add Windows testing to CI

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6490]
### Suggestion

Windows development support (#2580) sometimes gets broken: e.g. #6488. GitHub Actions now has good prebuilt Windows images for Node testing. I think it'd be a good idea to add a Windows machine to the unit tests matrix.

**Comment by liuxingbaoyu** [comment]
I can try to get this done once https://github.com/typescript-eslint/typescript-eslint/pull/6162 gets merged!
