### ISSUE TITLE
Docs: Reword rule formatting docs to allow for partially overlapping rules

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6494]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

We **strongly** recommend users do not use a linter (e.g. ESLint) to do the job of a formatter (e.g. Prettier). Right now, this notice is injected on top of every rule's docs page (example: [`@typescript-eslint/padding-line-between-statements`](https://typescript-eslint.io/rules/padding-line-between-statements/)):

> We strongly recommend you do not use this rule or any other formatting linter rules. Use a separate dedicated formatter instead. See [What About Formatting?](https://typescript-eslint.io/linting/troubleshooting/formatting) for more information.

However! Not all ESLint formatting rules are _completely_ in conflict with formatters. For example, `@typescript-eslint/padding-line-between-statements` can be used to enforce blank lines after `}`s, which Prettier doesn't cover (https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/231 -> https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/247).

I propose we change the wording slightly to account for this nuance. Maybe...

> We strongly recommend you use a separate dedicated formatter for formatting files. Lint rules are buggier, less comprehensive, and slower for formatting concerns. See [What About Formatting?](https://typescript-eslint.io/linting/troubleshooting/formatting) for more information.

### Affected URL(s)

https://typescript-eslint.io/rules/padding-line-between-statements & co.

**Comment by JoshuaKGoldberg** [comment]
ping @typescript-eslint/triage-team, any thoughts on this?

**Comment by bradzacher** [comment]
I personally think that any rule that enforces spacing, even padding-line-between-statements, is bad and shouldn't be used.

When people turn on such a rule they always end up with a hugely complex config of cases where it's okay to not have a break.

It further goes to show that a linter isn't the right tool for the job of laying code out.
