### ISSUE TITLE
Docs: Be more clear in differentiating "formatting" vs "style"

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6495]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I had a conversation with @mattpocock a bit back about how we describe the difference between formatters and linters. This topic has been coming up quite a lot in my dev evangelism in general. Matt had some good feedback from the perspective of a hypothetical new reader:

> I think I get it. Basically, 'let Prettier do your formatting, let ESLint correct your code's logic'?
> I.e. Prettier cares about the actual formatting of the text, ESLint basically only cares about AST structure.
>
> That doc is a little confusing, because of this line:
>
> > We support the ESLint team's decision and backing logic to move away from stylistic rules.
> > With the exception of bug fixes, no new formatting-related pull requests will be accepted into typescript-eslint.
>
> ...which makes formatting and style feel interchangeable.

Agreed. I'm thinking at the very least that page should be cleaned up to use terminology consistently, and probably also have a more clear glossary of terms to start. The difference between _formatting_, _logical_, and _stylistic_ concerns is not a shared vocabulary even amongst linter maintenance teams!

### Affected URL(s)

https://typescript-eslint.io/linting/troubleshooting/formatting/

**Comment by bradzacher** [comment]
I think examples are important in demonstrating the difference.

Formatting = indent, brace placement, etc.
Stylistic = interface vs types, destructure vs assign, const enum vs non-const enum, etc.
Logical = missing await, missing `case`s, unnecessary conditions, etc.
