### ISSUE TITLE
Bug: [require-await] autofix by removing async?

### ISSUE THREAD

**Issue by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [typescript-eslint/typescript-eslint#6509]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

Playground is currently broken or something

### Repro Code

```typescript
const f = async () => {};
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/require-await": ["error"],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

autofix

### Actual Result

no fix

**Comment by bradzacher** [comment]
The golden rule of fixers is that they must not break the build.

Removing the `async` keyword changes the return type of the function from `Promise<T>` to just `T`.
If you have downstream callsites doing `f().then()`, then they will now have a type error (i.e. break the build).

Hence the rule does not have a fixer on purpose.
