### ISSUE TITLE
Repo: Playground does not seem to work

### ISSUE THREAD

**Issue by AbdealiLoKo** [typescript-eslint/typescript-eslint#6521]
### Suggestion

The playground on the website does not seem to be working for me today

The 3 dots don't go away (the just keep jumping there)
Last time I was able to use it was sometime last week

![image](https://user-images.githubusercontent.com/2200743/220880172-cd0e5668-dd37-4e3e-9dd0-c8063bd5869e.png)

PS: I was not sure about the category to choose for this issue ...

Windows: 10.0.19045 Build 19045
Chrome: Version 110.0.5481.104 (Official Build) (64-bit)
Firefox: 105.0.3 also gives the same error

**Comment by bradzacher** [comment]
@JamesHenry - it looks like the old build got re-deployed?

**Comment by JamesHenry** [comment]
Sorry about this @AbdealiLoKo we're not 100% clear why this redeployment happened but it's fixed now!

**Comment by AbdealiLoKo** [comment]
Thanks for the super quick response !
