### ISSUE TITLE
Bug: parserOptions.project is slow when set as an array

### ISSUE THREAD

**Issue by AnielloFalcone** [typescript-eslint/typescript-eslint#6523]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

parser

### Repro Code

```typescript
{
      files: [`${SRC_DIRS}/*.{ts,tsx}`, '**/tsconfig.d.ts'],
      extends: ['./.eslint/.eslintrc.typescript.js'],
      parser: '@typescript-eslint/parser',
      parserOptions: {
          sourceType: 'module',
          ecmaVersion: 'latest',
          tsconfigRootDir: __dirname,
          project: [
              './packages/*/tsconfig.json',
              './cypress/tsconfig.json'
          ]
      },
      settings: {
          'import/resolver': {
              typescript: {
                  alwaysTryTypes: true,
                  project: [
                      './packages/*/tsconfig.json',
                      './cypress/tsconfig.json'
                  ]
              }
          }
      }
  }
```

### ESLint Config

```javascript
module.exports = {
    root: true,
    extends: ['./.eslint/.eslintrc.base.js', './.eslint/.eslintrc.import.js'],
    overrides: [
        // ...other overrides
    {
      files: [`${SRC_DIRS}/*.{ts,tsx}`, '**/tsconfig.d.ts'],
      extends: ['./.eslint/.eslintrc.typescript.js'],
      parser: '@typescript-eslint/parser',
      parserOptions: {
          sourceType: 'module',
          ecmaVersion: 'latest',
          tsconfigRootDir: __dirname,
          project: [
              './packages/*/tsconfig.json',
              './cypress/tsconfig.json'
          ]
      },
      settings: {
          'import/resolver': {
              typescript: {
                  alwaysTryTypes: true,
                  project: [
                      './packages/*/tsconfig.json',
                      './cypress/tsconfig.json'
                  ]
              }
          }
      }
  }
  ]
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
        "target": "ESNext",
        "module": "ESNext",
        "moduleResolution": "NodeNext",
        "resolveJsonModule": true,
        "allowUnreachableCode": false,
        "lib": ["ESNext"],
        "allowJs": false,
        "checkJs": false,
        "noEmit": false,
        "noEmitOnError": true,
        "declaration": true,
        "emitDeclarationOnly": true,
        "declarationMap": true,
        "strict": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "esModuleInterop": false,
        "forceConsistentCasingInFileNames": true,
        "useDefineForClassFields": true,
        "removeComments": false,
        "allowSyntheticDefaultImports": true
    }
}
```

### Expected Result

Linting should require a couple of minutes in large codebases

### Actual Result

Linting takes about 13 minutes, but if instead of this:
```
          project: [
              './packages/*/tsconfig.json',
              './cypress/tsconfig.json'
          ]
```

I do:
```
          project: './packages/*/tsconfig.json',
```

it actually takes the expected amount of time still performing the type checking.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.49.0` |
| `@typescript-eslint/parser`            | `5.49.0` |
| `eslint-import-resolver-typescript` | `3.5.1`|
| `TypeScript`                           | `4.8.3` |
| `ESLint`                               | `8.23.1` |
| `node`                                 | `16.17.0` |

**Comment by bradzacher** [comment]
It's hard to tell much of anything without knowing your codebase.

Setting it as an array doesn't actually make anything work differently internally - we normalise the string to an array.
In a nutshell we do
1) normalise `string` to `string[]`
2) for each string, resolve the glob
3) for each resolved tsconfig, check to see if it contains the file being linted.

What I would guess is happening is that your cypress config covers a large amount of code which, for whatever reason, takes us a lot of time to check and compute types for.

Again - hard to provide any guidance at all for you though with just some config files. We would need a reproduction repo which demonstrates the bug.

Without a repro I'm going to have to close this. If you can create one, happy to investigate fully!
