### ISSUE TITLE
[explicit-function-return-type] Allow bodyless arrow functions which return `as const`

### ISSUE THREAD

**Issue by CzBuCHi** [typescript-eslint/typescript-eslint#653]
### TL;DR: 
Add config option for inferred const return type. eg:
```ts
const func = (value: number) => ({ type: "X", value } as const); 
// func return type inferred as { type: "X", value: number };
```

### Long story:

When im creating redux actions i like wrote them this way:
```ts
export const action = (value: ValueType) => ({ type: "ACTION", payload: { value }} as const);
```
which correcly infer action return type as:
```ts
ReturnType<typeof action> === { type: "ACTION", payload: { value: ValueType } };
```

but **explicit-function-return-type** rule forces me to write action creator like this (basically write almost same thing twice):
```ts
export const action = (value: ValueType): { type: "ACTION", payload: { value: ValueType } } 
                                      => ({ type: "ACTION", payload: { value }} as const);
```
i already tryied to mess with config but none of **allowExpressions**, **allowTypedFunctionExpressions** or **allowHigherOrderFunctions** (true nor false)  will remove "Missing return type on function" error.

**Comment by bradzacher** [comment]
Please make sure you pick an issue template next time.
This is obv related to `eslint-plugin`, so you can select that, even if it's a feature request.
We have an issue template which includes a bunch of information that's good for us to collect from you.
Also it auto tags the issue with relevant labels so it's organised.

-----

no, none of the options will help you because you're creating a function with no type annotation.

Don't you have any function types for your reducers and actions?
I.e. unless I'm mistaken, don't you write code somewhat like this:
```ts
type SomeActionType =
    | { type: "ACTION1", payload: Action1Payload }
    | { type: "ACTION2", payload: Action2Payload }
 /* | .... */;
function reduce(action: SomeActionType): StateType { /* ... */ }

function action(value: ValueType) {
  return { type: "ACTION1", payload: { value } };
}
```

In that case the return type for your `action` function is `SomeActionType`.

**Comment by CzBuCHi** [comment]
> This is obv related to eslint-plugin

i had no idea where this belongs so i belive u ... 

>Don't you have any function types for your reducers and actions?

my actions looks like this:
```ts
export const foo = (foo: string) => ({ type: "FOO", foo } as const);
export const bar = (bar: number) => ({ type: "BAR", bar } as const);
export const baz = (baz: SomeType) => ({ type: "BAZ", baz } as const);

// Discriminated Union
export type Actions = 
    | ReturnType<typeof foo>
    | ReturnType<typeof bar>
    | ReturnType<typeof baz>;

// ActionType infered as:
type ActionsInferred =
    | { type: "FOO", foo: string } 
    | { type: "BAR", bar: number } 
    | { type: "BAZ", baz: SomeType };
```

and reducer:
```ts
import { Actions } from "./actions";

export function reducer(state: State, action: Actions): State {
    switch(action.type){
        case "FOO": // vscode intelisense shows me "FOO" | "BAR" | "BAZ" here
            return handleFoo(state, action.foo); // action is inferred as { type: "FOO", foo: string }
        case "BAR":
            return handleBar(state, action.bar);  // action is inferred as { type: "BAR", bar: number }
        case "BAZ":
            return handleBaz(state, action.baz);  // action is inferred as { type: "BAZ", baz: SomeType}
         case "BOO": // typescript error: Type '"BOO"' is not comparable to type '"FOO" | "BAR" | "BAZ"'.
             return state;
    }
}
```

as u can see i dont have explicitly defined action types anywhere because typescript is smart enough to infer them all ...

PS: cannot use `Actions` as return type because that will cause circular reference.

**Comment by bradzacher** [comment]
Ah I'm with you - you've inverted the approach to typing.

I don't think it's unreasonable for there to be an option to specifically allow arrow expressions without bodies if they return `as const` i.e. `() => value as const`
