### ISSUE TITLE
Rule proposal: Check that the argument to Object.fromEntries is an array

### ISSUE THREAD

**Issue by cmdcolin** [typescript-eslint/typescript-eslint#6537]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

My rule would check that the argument to Object.fromEntries is a array. A common reason to this would be useful would be accidentally calling fromEntries instead of entries. It is pretty niche but if you are writing a lot of code, you might miss it :)

### Fail Cases

```typescript
Object.fromEntries({a:1,b:2})
const val={a:1,b:2}; Object.fromEntries(val)
```

### Pass Cases

```typescript
Object.fromEntries([['a',1],['b',2]]);
const val=[['a',1],['b',2]]; Object.fromEntries(val);
```

### Additional Info

a similar issue could be made for Object.entries expecting an object-like thing, or not an array, as that would be an uncommon usage of Object.entries (IMO). Could also expect array for new Map also

I started a branch for this here  (not complete, doesn't check that the function being accessed is object.fromentries) but noticed the contributing guidelines suggest proposing a rule first https://github.com/typescript-eslint/typescript-eslint/compare/main...cmdcolin:typescript-eslint:object-fromentries-lint?expand=1

**Comment by bradzacher** [comment]
https://github.com/microsoft/TypeScript/blob/835fff8106e0cdf2e53028cd0e2c9759b426ebb4/lib/lib.es2019.object.d.ts#L23-L35

`Object.fromEntries` is typed to accept an `Iterable`, as per the spec.

Your [example fail cases cause TS errors](https://www.typescriptlang.org/play?target=99#code/PTAEDEEEEkBkCgDyAjAVgUwMYBcB0AzAJwHsBbAUQDttCBLdAZwAoBvAQwC4BGAGmQ4BMAXwCU8TMUoNsoAG5sANlwC87bn0FCA3KBQYcBEhWp1GTeUrHwQoAAqQAyg6RoseImSo16zANq+AcjYAni4AXR5A5BCBMLCRLXFJaTlFAWV-IJDwyIDonliwnT03Q08TH3M0hKA).

We don't look to create rules that duplicate existing TS errors unless there's a very good reason. I don't see this as having a good reason to duplicate.
Thanks for the submission!

**Comment by cmdcolin** [comment]
I suppose that is true and I was misremembering my original toe-stub which was this one..it is not caught by tsc https://www.typescriptlang.org/play?#code/FAYw9gdgzgLgBLArgM2QXgNoEYA0AmHAZgF1gB5AIwCsBTEGAOhohgCcBLGqACiVQYC2AQwAO3ZmwCeaAHwYJrSTjgBvdgBMAXAskBfYgEoDQA

**Comment by bradzacher** [comment]
But again - I'm not sure how that call causes issues.

The return type of your call would be `[string, [number, {id: number}]][]` which means if you tried to do anything with it beyond assignments to `object`, `any` or `unknown`, you'd hit TS errors, highlighting the issue quickly.
