### ISSUE TITLE
Bug: Performance issue: call createProgram everytime

### ISSUE THREAD

**Issue by Jack-Works** [typescript-eslint/typescript-eslint#6544]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

I'm using a single tsconfig.json for typescript-eslint (otherwise it will OOM), but it is still very slow (about 3~6 files checked per second which is endless).

This is the flame chart:

![image](https://user-images.githubusercontent.com/5390719/221787961-00c768c1-7478-4dc3-b722-bd209f15c585.png)

As you can see, it requires 0.3s to check any single `.ts` file. It calls createNewProgram for every file.

I patched `@typescript-eslint/typescript-estree` to remove the updateProgram call (though I don't know if it is correct) and it becomes fast.

```diff
diff --git a/dist/create-program/getWatchProgramsForProjects.js b/dist/create-program/getWatchProgramsForProjects.js
index 09e5ebeaab8b38f9eb7dabd8f1c2795a552a26a1..2c51a9470e2af6ebce0533314ce977e90e5f3b2c 100644
--- a/dist/create-program/getWatchProgramsForProjects.js
+++ b/dist/create-program/getWatchProgramsForProjects.js
@@ -105,6 +105,7 @@ function updateCachedFileList(tsconfigPath, program, parseSettings) {
     programFileListCache.set(tsconfigPath, fileList);
     return fileList;
 }
+let updatedProgram
 /**
  * Calculate project environments using options provided by consumer and paths from config
  * @param parseSettings Internal settings for parsing the file
@@ -139,7 +140,6 @@ function getWatchProgramsForProjects(parseSettings) {
             continue;
         }
         let fileList = programFileListCache.get(tsconfigPath);
-        let updatedProgram = null;
         if (!fileList) {
             updatedProgram = existingWatch.getProgram().getProgram();
             fileList = updateCachedFileList(tsconfigPath, updatedProgram, parseSettings);
@@ -201,7 +201,7 @@ const isRunningNoTimeoutFix = semver_1.default.satisfies(ts.version, '>=3.9.0-be
 function createWatchProgram(tsconfigPath, parseSettings) {
     log('Creating watch program for %s.', tsconfigPath);
     // create compiler host
-    const watchCompilerHost = ts.createWatchCompilerHost(tsconfigPath, (0, shared_1.createDefaultCompilerOptionsFromExtra)(parseSettings), ts.sys, ts.createAbstractBuilder, diagnosticReporter, 
+    const watchCompilerHost = ts.createWatchCompilerHost(tsconfigPath, (0, shared_1.createDefaultCompilerOptionsFromExtra)(parseSettings), ts.sys, ts.createAbstractBuilder, diagnosticReporter,
     /*reportWatchStatus*/ () => { });
     if (parseSettings.moduleResolver) {
         watchCompilerHost.resolveModuleNames = (0, shared_1.getModuleResolver)(parseSettings.moduleResolver).resolveModuleNames;
```

### Reproduction Repository Link

https://github.com/DimensionDev/Maskbook/pull/8804/commits/61b0ec829207c7aff16438267b39be9103092551

### Repro Steps

1) clone the repo, checkout commit [DimensionDev/Maskbook@`61b0ec8` (#8804)](https://github.com/DimensionDev/Maskbook/pull/8804/commits/61b0ec829207c7aff16438267b39be9103092551)
2) `pnpm install`
3) `npx gulp codegen`
4) `npx eslint packages --debug`

And if you checkout to commit [DimensionDev/Maskbook@`bd34e0c` (#8804)](https://github.com/DimensionDev/Maskbook/pull/8804/commits/bd34e0c97ad5f4693fe16c69a55f467678a88f1e), that I have typescript-estree patched, you will find it becomes faster.

Please be aware, if you switch between these two commits, please make sure the patch is correctly applied / unapplied, otherwise, you may see the incorrect result.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.53.0` |
| `@typescript-eslint/parser`            | `5.53.0` |
| `@typescript-eslint/scope-manager`     | `5.53.0` |
| `@typescript-eslint/typescript-estree` | `5.53.0` |
| `@typescript-eslint/type-utils`        | `5.53.0` |
| `@typescript-eslint/utils`             | `5.53.0` |
| `TypeScript`                           | `5.0.0-dev.20221202` |
| `ESLint`                               | `8.32.0` |
| `node`                                 | `19.7.0` |

**Comment by bradzacher** [comment]
Long story short - we need to support both the IDE usecase and the CLI usecase from the same parser without any flags. The IDE case needs to handle incremental updates, so that's the code path we use by default.

We have an experimental code path for cli runs which disables the incremental updates that you can enable with `parserOptions.allowAutomaticSingleRunInference = true`.

We are considering turning it on by default in the next major.

**Comment by Jack-Works** [comment]
it's expected to call createProgram for each file?
