### ISSUE TITLE
Bug: v6 can't be `import()`ed

### ISSUE THREAD

**Issue by fisker** [typescript-eslint/typescript-eslint#6549]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

@typescript-eslint/typescript-estree@6.0.0-alpha.66
@typescript-eslint/visitor-keys@6.0.0-alpha.66

Can't use 

`import ... from "@typescript-eslint/typescript-estree"`  

or

```console
await import('@typescript-eslint/typescript-estree')
Uncaught:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in <CWD>\node_modules\@typescript-eslint\typescript-estree\package.json
```

Missing `import` or `default`

https://github.com/typescript-eslint/typescript-eslint/blob/35be101c0fc996be04b8017c7ae7692f6c1bdafe/packages/visitor-keys/package.json#L14-L17

---

Can you also add a `./use-at-your-own-risk/parser` entry to `@typescript-eslint/typescript-estree`? [Prettier use it instead of `index.js`](https://github.com/prettier/prettier/blob/b9f02a9eb5e2d70f4d0e5909831dbffb2e3a097d/src/language-js/parse/typescript.js#L1).

**Comment by bradzacher** [comment]
So the reason that I didn't define `import` was because we only build as CJS.
I was just playing locally and it looks like it doesn't matter - if I add `import: './dist/index.js'` node just "makes it work":

```js
await import('@typescript-eslint/typescript-estree')
> {
  AST_NODE_TYPES: { ... },
  AST_TOKEN_TYPES: { ... },
  TSESTree: { ... },
  TSError: [class TSError extends Error],
  __esModule: true,
  clearCaches: [Function: clearCaches],
  clearProgramCache: undefined,
  createProgram: [Function: createProgramFromConfigFile],
  default: {
    parse: [Getter],
    parseAndGenerateServices: [Getter],
    parseWithNodeMaps: [Getter],
    simpleTraverse: [Getter],
    createProgram: [Getter],
    typescriptVersionIsAtLeast: [Getter],
    TSError: [Getter],
    version: '6.0.0-alpha.66+35be101c',
    AST_NODE_TYPES: [Getter],
    AST_TOKEN_TYPES: [Getter],
    TSESTree: [Getter],
    getScriptKind: [Getter],
    getLanguageVariant: [Getter],
    getModifiers: [Getter],
    getDecorators: [Getter],
    clearCaches: [Getter],
    clearProgramCache: [Getter]
  },
  getDecorators: [Function: getDecorators],
  getLanguageVariant: [Function: getLanguageVariant],
  getModifiers: [Function: getModifiers],
  getScriptKind: [Function: getScriptKind],
  parse: [Function: parse],
  parseAndGenerateServices: [Function: parseAndGenerateServices],
  parseWithNodeMaps: [Function: parseWithNodeMaps],
  simpleTraverse: [Function: simpleTraverse],
  typescriptVersionIsAtLeast: { ... },
  version: '6.0.0-alpha.66+35be101c'
}
```

So we should definitely define `import` for all of the packages as well

**Comment by bradzacher** [comment]
> Can you also add a ./use-at-your-own-risk/parser entry to @typescript-eslint/typescript-estree? Prettier use it instead of index.js.

For the most part the `use-at-your-own-risk` entrypoints we added for the internal usages we needed to make it easier for us to do our website bundle because we're too lazy to mock or setup tree shaking.

Why do you guys deep import for?

**Comment by fisker** [comment]
> Why do you guys deep import for?

To reduce bundle size, we don't need things like `simpleTraverse`.

> For the most part the use-at-your-own-risk entrypoints we added for the internal usages

It's fine, we can "tree-shake" in build script 
https://github.com/prettier/prettier/pull/14429/files#diff-b345b1ff41c7f7ece49f201bc8d45c6c56eb581b664618b7cf09c38322dfeed3R160
