### ISSUE TITLE
Bug: [no-restricted-imports] Config entries get ignored when they have the same name attribute

### ISSUE THREAD

**Issue by DerZyklop** [typescript-eslint/typescript-eslint#6552]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.8.4&sourceType=module&code=PTAEAEBcGcFoDsD2BjAFgU2QawFAEsBbAB0QCdJQBvUAUXgFcCBBUAX1ADNTEDQBycNB7pIqPPADmwAgE9Y6BgWh8A3PmJkK1OowBCbTt14ChBEWMnS5CxsrVA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEoAEAuAngA4oDG0AlkXgLQrwUB2eA9IwPY3Qp6Wl6IAJjQoBbIu2h5UGANrhsESImjRJkADQLFWRdkiMAhqMTpcydibwALJgHMWognUaxRqLXv1iJUgHLGKGbyXoqQAKKuogCCkNp6ALrxEAC+nnq6XgaBZpA4Fla2jA5OLm4eyd7ikngBJjJgIaFKkW4AQnHNSV4p8d1gvSlAA&tsconfig=N4XyA

### Repro Code

```typescript
Same as in the playground link:


// @ts-nocheck
import { EnumA } from '@something/my-enums';
import { EnumB } from '@something/my-enums';
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
   "@typescript-eslint/no-restricted-imports": [
      "error",
      {
        "name": "@something/my-enums",
        "importNames": [
          "EnumA"
        ]
      },
      {
        "name": "@something/my-enums",
        "importNames": [
          "EnumB"
        ]
      }
    ]
  },
};
```

### tsconfig

```jsonc
{}
```

### Expected Result

Expected to have two errors. One for each import.

### Actual Result

The import for `EnumA` was accepted by `no-restricted-imports`.

### Additional Info

I guess it’s obvious that the second entry (for`EnumB`) in the rule options overwrites the first entry (for`EnumA`), because they have the same name.

This is a possible solution/workaround for me:

```json
   "@typescript-eslint/no-restricted-imports": [
      "error",
      {
        "name": "@something/my-enums",
        "importNames": [
          "EnumA", "EnumB"
        ]
      }
    ]
```

But for me, this behavior was unexpected and seems to me like a pitfall. It took a while till we noticed that eslint should complain about something where it did not.

**Comment by bradzacher** [comment]
This is working the same way as in the base rule that we extend.

The rule assumes that each `name` is unique:
https://github.com/eslint/eslint/blob/b09a512107249a4eb19ef5a37b0bd672266eafdb/lib/rules/no-restricted-imports.js#L157-L167

Please file an issue in the ESLint repo for a fix.

**Comment by DerZyklop** [comment]
➡ [Related issue at ESLint](https://github.com/eslint/eslint/issues/15261)
