### ISSUE TITLE
Bug: Parsing error: Unexpected token... in every typescript file on namespace line

### ISSUE THREAD

**Issue by Mek7** [typescript-eslint/typescript-eslint#6563]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

parser

### Repro Code

```typescript
/// <reference path="../../../common/ArrayUtility.ts" />

namespace JasmineTests { // ESLINT parser error reported on this line
    import ArrayUtility = Common.ArrayUtility;

    describe("ArrayUtility.indexOf", () => {
        it("returns -1 for empty arguments", () => {
            Common.Constants.arrayEmptyValues.forEach((array: any[]) => {
                Common.TestUtility.toBeEqualExtended(expect(ArrayUtility.indexOf(array, null)), -1);
            });
        });
    });
}
```

### ESLint Config

```javascript
const prettierEnabled = false;

const config = {
    "root": true,
    "ignorePatterns": [".eslintrc.js", "**/*.d.ts"],

    // We can lint almost any file extension with an appropriate plugin, so having rules that apply to them all makes little sense
    // Instead all rules are defined in overrides sections by file extension, even though we're not actually overriding anything
    "overrides": [
        {
            // This object has rules etc. that apply to BOTH JavaScript and TypeScript.
            // Rules that only apply to JavaScript are in a JavaScript object further below, and similarly for TypeScript.
            "files": ["*.js", "*.jsx", "*.mjs", "*.cjs", "*.ts", "*.tsx"],
            "parserOptions": {
                "ecmaVersion": 5,
                "sourceType": "script",
                "ecmaFeatures": {
                    "jsx": false, // Allows support of JSX, but use of React plugin is required to support React semantics
                },
            },
            // To disable a plugin commment it out here and also comment out its rules in the appropriate section below
            // Reverse that to enable one
            "plugins": [
                "@typescript-eslint",
                "prettier",
            ],
            "env": {
                "amd": false,
                "browser": true,
                "jquery": false,
                "node": false,
                "es6": false, // This enables ES6 global variables AND ES6 syntax
                "worker": false,
            },
            "rules": {
...
```

### tsconfig
There is no tsconfig. Related properties are configured using project properties in Visual Studio 2022.
![image](https://user-images.githubusercontent.com/12199478/222693315-8986c740-3fc8-42a2-ab0c-a1c55d2f41de.png)

### Expected Result

No errors.

### Actual Result

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	(ESLint) 	Parsing error: Unexpected token JasmineTests		D:\(path to file)\JasmineTests\ArrayUtilityTests.ts	3	
(copied from Error List in Visual Studio 2022)

### Additional Info

Everything compiles fine and code works, but the ESLINT error appears when a .ts file is opened. For every opened .ts file there is one error. Linting works, however, checks are performed and rule breaks in code correctly reported by ESLINT. I just don't know how to get rid of this error - Unexpected token (namespace name). Our project compiles against ecmascript 5, I tried changing eslint configuration to various ecmaVersions to no avail.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.54.0` |
| `@typescript-eslint/parser`            | `5.54.0` |
| `@typescript-eslint/scope-manager`     | `5.54.0` |
| `@typescript-eslint/typescript-estree` | `5.54.0` |
| `@typescript-eslint/type-utils`        | `5.54.0` |
| `@typescript-eslint/utils`             | `5.54.0` |
| `TypeScript`                           | `4.9.5 (under node_modules) but 2.5.3 as installed from Microsoft.TypeScript.MSBuild nuget package. Upgrade is not possible because of too many breaking changes.` |
| `ESLint`                               | `8.35.0 (under node_modules)` |
| `node`                                 | `16.17.0` |
| `TypeScript Analyzer (ESLint, Prettier) - VS extension` | `2.6` |
| `MS Visual Studio` | `2022` |

**Comment by bradzacher** [comment]
Based on the config you provided, it looks like you haven't configured our parser at all - so the errors would be because the base eslint parser is trying to parse language features it doesn't understand.

https://typescript-eslint.io/getting-started/#step-2-configuration

If this is wrong, please provide an isolated repro case and we can reopen and help you look into it.

**Comment by Mek7** [comment]
OK, sorry for the confusion. Now I see that I only added it as a plugin but didn't actually "use" it. If anyone gets stuck on this in the future, the "parser" line fixed it in .eslintrc.js:
```
...
            "files": ["*.js", "*.jsx", "*.mjs", "*.cjs", "*.ts", "*.tsx"],
            "parser": "@typescript-eslint/parser",
            "parserOptions": {
                "ecmaVersion": 5,
                "sourceType": "script",
                "ecmaFeatures": {
                    "jsx": false, // Allows support of JSX, but use of React plugin is required to support React semantics
                },
            },
...
```
