### ISSUE TITLE
Bug: [no-unused-vars] Not detecting unused function arguments

### ISSUE THREAD

**Issue by arpl** [typescript-eslint/typescript-eslint#6564]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=KYDwDg9gTgLgBAYwgOwM7wEYEMpwLxwAUwUUAXHFsgJ4A0cUwAjhRhBADbBX2OqvsuPOMlAwBnbsgCU+AHxwA3gCg4DYDACuUZCLEBuZQF9Dy0JFiIU6OADN2+IiXKUavZhKHJ3-OG0nCoiDifoJSsngKKmqMWjrqqIYmymbg0PBIaPAcnI7EpBRUdOosoQHeCZ5S9EEh-l4RUarqcbqMTEmm5ulWWX5YAF55zoVuJVXCfBMVtdONSs2x2rrOnUA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUFvcgOwHsBaWPWZRAEyIDcBDaVDSAgM1cgBpwdcABAC4BPAA4oAxtACWIgURTwpeAQHpCJMhWr1G6MAG0evXImjQC0LkeOZrNqAwDmyAJKPC0RAAU6Agabw9SAA9AH1IO14AX0iIAF0eGKigA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
export const bar = (err: boolean, req: boolean, res: boolean, next: boolean) => {
  return next;
};
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unused-vars": "error",
    "no-unused-vars": "off"
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

Match the typescript server error message and  report `err, req, and res` as unused.

### Actual Result

Does not report `err, req, and res` as unused.

**Comment by bradzacher** [comment]
https://eslint.org/docs/latest/rules/no-unused-vars#args

The default check for args is to only flag unused arguments *after* the last used argument.
