### ISSUE TITLE
Rule proposal: Add `no-useless-rest-spread` in a better way than `mysticatea`

### ISSUE THREAD

**Issue by gauthieramano** [typescript-eslint/typescript-eslint#6565]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

`@mysticatea/eslint-plugin` has a rule called `no-useless-rest-spread`
See: https://github.com/mysticatea/eslint-plugin/blob/master/docs/rules/no-useless-rest-spread.md

The aim is to do the same thing but handling cases this plugin doesn't.

The tricky case is when the spread operator is used for arguments in function declarations. This plugin automatically transforms this:

```ts
// Let's consider that this type is used many times in a codebase
type Tuple1 = [a: string, b: number];

const foo = (...[a, b]: Tuple1) => {
  // someting
};
```

to:

```ts
// both arguments are now typed as `any`
const foo = (a, b) => {
  // something
};
```

and it's not possible to disable it just for arguments in function declarations.

### Note:

I liked how `@typescript-eslint/no-shadow` considered the issues related to the initial ESLint `no-shadow` rule. I would like the same treat for `@mysticatea/eslint-plugin`.

### Fail Cases

```typescript
const list = [a, ...[b, c], d];
const obj = { a, ...{ b, c }, d };

foo(...[a, b, c]);

const [a, b, ...[c, d]] = list;
const { a, b, ...{ c, d } } = obj;
```

### Pass Cases

```typescript
const list = [a, b, c, d];
const obj = { a, b, c, d };

foo(a, b, c);

const [a, b, c, d] = list;
const { a, b, c, d } = obj;

// In JavaScript, this bellow example should be fixed, but not in TypeScript:
function bar(...[a, b]: [a: string, b: number]) {
}
```

### Additional Info

I opened an issue in `@mysticatea/eslint-plugin` repository:
- https://github.com/mysticatea/eslint-plugin/issues/48

But as it's related to a TypeScript issue, it's maybe more relevant this rule belongs to the `@typescript-eslint` plugin.

**Comment by bradzacher** [comment]
We fork core eslint rules because they have purposely restricted their rules to solely deal with plain JS - they intentionally do not support any other languages in their lint rules.

OTOH we don't look to fork rules from other plugins because plugins (generally) do not have the same restriction in place - they are free to support whatever languages that they desire, and thus can be updated to handle TS-specific syntax.

You've already filed an issue against the plugin - so I would recommend pursuing that path.

**Comment by gauthieramano** [comment]
@bradzacher, I understand. Thanks for your comment.
