### ISSUE TITLE
Enhancement: add `experimentalDecorators` option to `typescript-estree`

### ISSUE THREAD

**Issue by sosukesuzuki** [typescript-eslint/typescript-eslint#6571]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-estree

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

**What:**
Adds `experimentalDecorators` option to `@typescript-eslint/typescript-estree`.
It just corresponds to [`experimentalDecorators` in TS compiler options](https://www.typescriptlang.org/tsconfig#experimentalDecorators).

**Why:**
Since TypeScript 5.0, ECMAScript decorators are implemented; we can switch between them using `experimantalDecortors` in the compiler options.

There is no way to switch it on in `typescript-estree` except by specifying `tsconfig.json` by `project`.

It would be helpful to have `experimentalDecorators` as a parsing option, like the already existing `jsx` option.

### Fail

```typescript
// N/A
```

### Pass

```typescript
// N/A
```

### Additional Info

I think we can avoid breaking changes by setting the default value of this option to `true`. (And, we can change it to `false` at next major version)

**Comment by bradzacher** [comment]
Is there a syntax difference between the two of them, or just a semantic difference?
If it's just the latter - then there's no need for an option because the only time the difference would impact things is type-aware parsing, which needs a tsconfig.

If it's the former, then we can look into it.

**Comment by sosukesuzuki** [comment]
There is syntax difference between the two of them.

For example, the following decorator is valid as experimental decorators, but is invalid as ES decorators.

```ts
declare const special: any;

class Foo {
  bar(@special(true) { bar }: any) {}
}
```

[Experimental decorators playground](https://www.typescriptlang.org/play?emitDecoratorMetadata=false&ts=4.9.5#code/CYUwxgNghgTiAEYD2A7AzgF3mgDuAllBAFzxQoCeA3AFA2RRprwBiSS8A3jfPAEawAFAAFcBIoIwwAriACUXfrHgBfUuQoLOKmjqA)
[ES decorators playground](https://www.typescriptlang.org/play?experimentalDecorators=false&emitDecoratorMetadata=false&ts=5.1.0-dev.20230305#code/CYUwxgNghgTiAEYD2A7AzgF3mgDuAllBAFzxQoCeA3AFA2RRprwBiSS8A3jfPAEawAFAAFcBIoIwwAriACUXfrHgBfUuQoLOKmjqA)

**Comment by bradzacher** [comment]
Sorry - to clarify I meant semantic/syntactic in the TS sense, i.e. for a syntactic error the TS parser would hard-error, but for a semantic error the parser does not error (but TS itself will emit an error).

Looking at your example - the decorator positioning is (currently at least) a semantic error, not a syntactic one.
I don't think it's necessary for us to add a parser option to cause us to error on the old, invalid position. I don't think we gain anything from that because we still need to support it from an AST perspective, and rules still need to support linting them.

I think us just supporting everything and having TS semantically error on the user's code is the best course of action for now - over time TS will remove the experimental flag and we'll stop parsing it naturally.

**Comment by sosukesuzuki** [comment]
@bradzacher Ah I got it, thank you. So what do you think about https://github.com/typescript-eslint/typescript-eslint/pull/6570#discussion_r1125603464? Should we default this option to `trure`? Or should it be `false`?

**Comment by sosukesuzuki** [comment]
https://github.com/typescript-eslint/typescript-eslint/pull/6570#discussion_r1125722443
