### ISSUE TITLE
enum error eslint 查不到 enum 的类型不存在

### ISSUE THREAD

**Issue by 2531800823** [typescript-eslint/typescript-eslint#6574]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

null

### Repro Code

```typescript
enum A {
    //#region app
    Bond_InvestmentAdviser_ResetState = "Bond_InvestmentAdviser_ResetState",
    Bond_InvestmentAdviser_UpdateState = "Bond_InvestmentAdviser_UpdateState",
}


// error
const a = A.a1;
```

### ESLint Config

```javascript
module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
  ],
  plugins: ['@typescript-eslint'],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    tsconfigRootDir: __dirname,
    project: './tsconfig.json',
  },
  root: true,
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "outDir": "build",
    "module": "esnext",
    "target": "es5",
    "lib": ["es2015", "es2016", "es2017", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "baseUrl": "./",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "build", "dist"]
}
```

### Expected Result

$ tsc  --project tsconfig.json --pretty --noEmit

 Property 'a1' does not exist on type 'typeof A'.

### Actual Result

eslint --ext js,jsx,ts,tsx

succeed !!

**Comment by Josh-Cena** [comment]
ESLint does not report type-checking errors. You always need to run both commands if you want full diagnostics. However, your case would be caught if you enable the `@typescript-eslint/no-unsafe-assignment` rule: [playground](https://typescript-eslint.io/play#ts=4.9.3&sourceType=module&code=KYOwrgtgBAglDeAoKUD0qDEAnYBzAlgPYhQCGADuclAELEAmA+gJIgBuwAzgC4Sjcx6bfJ2BZGAJS7BuAZW6luwKAF4oAIjogmrDjz4gBQkWMnS5CpeoA01LTvZde-QcNHiAquXqLg836oa9iyO+i7G7oxePkr+VrYAvojJ6FBiWIRYiADGxDxkgTAAdKQAjADciEA&eslintrc=N4KABGBECmAeAu0B2ATAzpAXGA2uCU0aANgJZLyYBO0AxgPYC2jyK0KkANPhJAA7EArgHNymAALwAnnyK0qpPvAC0RMhQD0NBs1bsuPKAJFjJMuQqWqS5eFrpMWqdspoBHQaQVJhy6bOVaAAs6AGtyYUh8AF1uXipBYiIsMFACKDNZNHlFFTVbDSR6ZUEkNABDADNoZXK0NFJhJCd4FJgqKnoqKIgAXxB+oA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEksArngCLKYVQBG9aAJpADTgakeLB70M7SOhJF0ADzwChtPAENMAc3RLK0kgFZlNKKmQd2AbRXCZAJgAMARiOCTte84Bsx9-sdOAOy+JpA8CJA2ALpuwiQMmNDoALJqiOx4mPTosbRqqKiwAO4AUmSUmdm5UABWJPJSmOhq0ErVImIS6ABKMrCojIREUkRi6CFQmLCwzKxSJIkTkABmsInoAMLEJMgkeOhEeBtqO0SaAJJEAGJo6AByavAyGVk5NpCj50hm0Mh4vXh6JhSC8qu9Pt9kL88AAVAAWu1Bb1CEMQPz+AEEiABPJHtPaYKF4O4SVAbOHoaAAa3KYEqyLi9EQiCaJBIXzRUMxOMuPAUAFFMFNMLT6e1RgBVIj0EjoHgAGVg0Hyote7QUiCwyCeh3yTEpazUeDWqrBoXQ8D++rgmCNa2SOjUPCNajx7xIVOQiHl5nJlKpbtC+UKRQAytjDhSCNB9cs1BI8By1nhTQzaKz+gA3dBlYjJTqSCpq94cE7oCWYVBSAB0AHologjXDadQ-AABWsAKisNlCC2gXci7jAURsAF8hGPYpBkERoAM+T2+4ku53B0IYkJpPJ5-RF5RrCixgB9UTiDBkdpcXhLHi7JQbkBjoA)

**Comment by bradzacher** [comment]
FAQ: https://typescript-eslint.io/linting/troubleshooting/#why-dont-i-see-typescript-errors-in-my-eslint-output

Please make sure you read the FAQ before posting.

**Comment by bradzacher** [comment]
Please also avoid filing issues in languages other than english.
We want to ensure all issues are accessible for the maintainers and the community.

**Comment by 2531800823** [comment]
Do not enable any, it will affect other code, can I look for enum separately from tsc?
