### ISSUE TITLE
Enhancement: @typescript-eslint/naming-convention enum values in PascalCase

### ISSUE THREAD

**Issue by Conaclos** [typescript-eslint/typescript-eslint#6592]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/naming-convention/

### Description

As notes in a [stackoverflow thread](https://stackoverflow.com/questions/68583644/why-does-typescript-eslint-enforce-camelcase-for-enummember), by default ESLint [naming-convention](https://typescript-eslint.io/rules/naming-convention/) rule enforces _camelCase_ for enum values.

This is really strange because I am not aware of any style guide that encourages this convention. Generally style guide encourages the use of _PascalCase_ or _CONSTANT_CASE_.

I propose to change the default behavior to _PascalCase_ for enum values.

Note that enum value are also types, this should thus be consistent with the existing defaults.

### Fail

```typescript
enum Direction {
  prev,
  next,
}
```

### Pass

```typescript
enum Direction {
  Prev,
  Next,
}
```

**Comment by bradzacher** [comment]
The default isn't there as a "this is the way to do things for everyone". Instead it's there as a quick proxy for the old `camelcase` lint rule. It's there as an example to show what you could do with the rule.
Its rare that the default will truly match a codebase's naming convention - in which case they will have to design their own config.

This exact default has been in place for 2 years and this is the first time someone has asked for a change. Either that means that (a) few people use the rule so nobody has noticed, (b) the people that use the rule don't use the default or (c) people are happy with the default.

In either case, I don't see a compelling argument for us to change the default here, given that it is a breaking change for us to change defaults and could potentially be disruptive to users that rely on them.
