### ISSUE TITLE
Docs: options heading and content reversed

### ISSUE THREAD

**Issue by Josh-Cena** [typescript-eslint/typescript-eslint#6595]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

<img width="242" alt="image" src="https://user-images.githubusercontent.com/55398995/224220473-bab9fa55-6da1-4ac3-a92c-173d3b8a68a5.png">

### Affected URL(s)

https://typescript-eslint.io/rules/prefer-string-starts-ends-with
https://typescript-eslint.io/rules/prefer-ts-expect-error
etc.

**Comment by bradzacher** [comment]
I noticed this but it never clicked that they weren't supposed to be that way around heh
