### ISSUE TITLE
[no-object-literal-type-assertion] False positive when asserting function argument

### ISSUE THREAD

**Issue by IlyaSemenov** [typescript-eslint/typescript-eslint#66]
**Repro**

```js
module.exports = {
    root: true,
    plugins: ["typescript"],
    parser: "typescript-eslint-parser",
    extends: ["plugin:typescript/recommended"],
}
```

```TS
interface Foo {
    foo?: number;
}

function print(x: Foo): void {
    console.log(x.foo)
}

print({ bar: 5 } as Foo)
```

**Expected Result**

No errors.

**Actual Result**

```
/Users/semenov/tmp/ts-rule/test.ts
  9:7  error  Type assertion on object literals is forbidden, use a type annotation instead  typescript/no-object-literal-type-assertion

✖ 1 problem (1 error, 0 warnings)
```

**Additional Info**

The primary purpose of the rule (as I see it) is to prevent object assignment such as `const x = { ... } as T;` which is better rewritten as `const x: T = { ...};`, but the rule disallows all other legitimate uses.

**Versions**

| package                    | version |
| -------------------------- | ------- |
| `eslint-plugin-typescript` | `1.0.0-rc.2` |
| `typescript-eslint-parser` | `21.0.2` |
| `typescript`               | `3.2.2` |

**Comment by armano2** [comment]
@IlyaSemenov you can override definition file
```ts
// module-name.d.ts
declare 'module-name/path/test' {
  export class query {
    patch<T extends PartialUpdate>( model: T) {}
  }
}
```

**Comment by IlyaSemenov** [comment]
@armano2 I am well aware of augmenting external modules, thank you. In this particular case [the typings](https://github.com/Vincit/objection.js/blob/d799b555f51504319f6843d0fc9b610d0fe5e0f0/typings/objection/index.d.ts) already make sense:

```ts
type PartialUpdate<QM extends Model> = {
  [P in keyof QM]?: QM[P] | Raw | Reference | QueryBuilder<any, any[]>
};

interface QueryBuilderBase<QM extends Model, RM, RV> extends QueryInterface<QM, RM, RV> {
  patch(modelOrObject: PartialUpdate<QM>): QueryBuilderYieldingCount<QM, RM>;
}
```

Extending the interface for `modelOrObject` to `T extends PartialUpdate` will break the guards for 'normal' field updates (not using JSON subfields).

In either case, let's not do Typescript learning sessions here, this issue is about something completely different and is irrelevant to my comprehension of TS and/or possibility of other workarounds.

**Comment by armano2** [comment]
now i see full context 👍 

do we have any other scenarios when we want to not chekc this rule except in call/new expression?

**Comment by aboyton** [comment]
TypeScript have added support for `as const` in master. I've created a new ticket for adding support in #166 which might be of interest to people.
