### ISSUE TITLE
Enhancement: use @eslint-community dependencies

### ISSUE THREAD

**Issue by oceandrama** [typescript-eslint/typescript-eslint#6601]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

eslint-plugin, utils

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Since [v8.36.0](https://github.com/eslint/eslint/releases/tag/v8.36.0) `eslint` [using](https://github.com/eslint/eslint/pull/16784) `@eslint-community/eslint-utils` and `@eslint-community/regexpp` instead of `eslint-utils` and `regexpp`

It would be great to switch to it too for dependency deduplication

I wiil be glad to help with PR

**Comment by bradzacher** [comment]
Happy to accept a PR!

**Comment by oceandrama** [comment]
@bradzacher It's done!
