### ISSUE TITLE
Enhancement: [consistent-type-assertions] Option to turn off consistent type assertions but keep object literal assertion check

### ISSUE THREAD

**Issue by NotWoods** [typescript-eslint/typescript-eslint#6605]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/consistent-type-assertions/

### Description

In our codebase at Microsoft, we don't care about enforcing assertion code style (both `<T>` and `as T` are fine). 

However, we do want to avoid casting with object literals. `const x = { ... } as T` is usually a bug where a developer doesn't realize that assertions act different to `const x: T = { ... };`.

It would be great to have an option to turn off this rule's main functionality while keeping it's secondary functionality. Alternatively, this might be better off split into two separate rules since they don't overlap very much. While both rules deal with assertions, one part deals with code style and another deals with potential errors.

### Fail

```typescript
const x = { ... } as T;
```

### Pass

```typescript
const x: T = { ... };
const y = x as A
const z = <B>x;
```

### Additional Info

Happy to open a PR once an option name is decided on

**Comment by bradzacher** [comment]
It's very, very uncommon for codebases to allow inconsistency like this, so I don't think an option provides value to the broader community.

If you're just looking to ban assertions on object literals you can:
https://typescript-eslint.io/linting/troubleshooting#how-can-i-ban-specific-language-feature
