### ISSUE TITLE
Enhancement: [consistent-type-assertions] Autofix to change assertion style

### ISSUE THREAD

**Issue by NotWoods** [typescript-eslint/typescript-eslint#6606]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/consistent-type-assertions/

### Description

consistent-type-assertions feels like a good candidate for an autofix. Swapping between the assertion styles is doable with ESLint's fixer API.

### Fail

```typescript
const x = <T>{ ... }; // with assertionStyle: 'as'
```

### Pass

```typescript
const x = { ... } as T; // autofixed with assertionStyle: 'as'
```

### Additional Info

Happy to open a PR

**Comment by bradzacher** [comment]
I'm more than happy for an autofixer from angle bracket to `as`. The most complicated bit will be ensuring the correct parenthesisation based on expression precedence.

However the other direction I don't think we should bother with for two reasons (1) it's really rare in modern TS to use angle bracket and (2) a safe fixer would require us to be aware of whether the file is considered a "tsx" file.
