### ISSUE TITLE
vscode alerts on typescript error and eslint misses.

### ISSUE THREAD

**Issue by iliran11** [typescript-eslint/typescript-eslint#661]
**What code were you trying to parse?**

I have the following `Test` component.

```ts
import React, { ReactElement } from 'react';
import BlogDate from './BlogDate';

export default function Test() {
const liran = 1
  return <BlogDate date={props.date} writer={props.writer} />
}
```
`BlogDate` component:

```ts
interface BlogDateProps {
  children?: string;
  date: Date;
  writer: string;
}

const BlogDate: (props: BlogDateProps) => React.ReactNode = (
  props: BlogDateProps,
): ReactNode => {
  return (
      <div>
      {props.children}
      </div>
  );
};

```

I am using vscode. the editor highlights this error about the rendering of `BlogDate`:

> JSX element type 'ReactNode' is not a constructor function for JSX elements.
>   Type 'undefined' is not assignable to type 'Element | null'.

When running Eslint from CLI it gives me the following errors, but not the one the VScode outputs.

> /Users/lirancohen/Projects/bookaway-platform/landing-page/components/comps/Blog/BlogCard.tsx
>   5:16  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
>   6:26  error    'props' is not defined           no-undef
>   6:46  error    'props' is not defined           no-undef
>   6:62  error    Insert `;`                       prettier/prettier
>   7:2   error    Insert `⏎`                       prettier/prettier
> 

Why and should `@typescript-eslint/parser` catch the "not assignable to type" error? 

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `1.11.0` |
| `TypeScript`                | `3.2.4` |
| `ESLint`                    | `6.0.1` |
| `node`                      | `8.16.0` |
| `npm`                       | `6.4.1` |

**Comment by bradzacher** [comment]
Typescript errors are outside of the scope of the parser. The parser simply parses the code, it doesn't look for typescript errors.
If you want to detect and handle typescript errors, use the typescript compiler.
