### ISSUE TITLE
Website: missing Twitter metadata on blog posts

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6622]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

When we post a link to the site blog on Twitter, nothing gets expanded/previewed:

[Example tweet](https://twitter.com/tseslint/status/1635393594101039105]:

![Screenshot of the example tweet with no media preview](https://user-images.githubusercontent.com/3335181/224838641-539bb0a3-3979-4c1a-a3cb-5155600fe82c.png)

This is like #5240, but there's nothing expanded on Twitter at all. 😞 

### Affected URL(s)

https://typescript-eslint.io/blog/*

Example: https://typescript-eslint.io/blog/announcing-typescript-eslint-v6-beta

**Comment by Josh-Cena** [comment]
Weird, https://typescript-eslint.io/blog/announcing-typescript-eslint-v6-beta doesn't seem to miss any metadata that https://docusaurus.io/blog/releases/2.3 has, but the latter works: https://twitter.com/docusaurus/status/1619019393756794900

**Comment by Josh-Cena** [comment]
There is link previews for all new tweets, such as the [pinned one](https://twitter.com/tseslint/status/1703851687142727880). I still don't see a preview for https://twitter.com/tseslint/status/1635393594101039105 but I suspect there's just some glitch. Closing this as resolved.
