### ISSUE TITLE
Docs: Mention the Discord server

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6628]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

We're trying out having a Discord server. Previously we haven't had the funding & time to run one, but now that I'm on full time I'd like to try it out. https://typescript-eslint.io/blog/announcing-typescript-eslint-v6-beta#trying-out-v6 links to it.

### Affected URL(s)

At least...

* https://typescript-eslint.io/contributing/discussions
* https://typescript-eslint.io/contributing/issues#questions-and-support-requests

**Comment by armano2** [comment]
Maybe we could add the link in footer, as we have all other social links there
