### ISSUE TITLE
Spelling mistake in "A "Thenable" value is an object with has a then method" - Replace "with" with "which"

### ISSUE THREAD

**Issue by danielbudasca** [typescript-eslint/typescript-eslint#6629]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Fix spelling mistake.

### Affected URL(s)

https://typescript-eslint.io/rules/await-thenable/

**Comment by Josh-Cena** [comment]
Fixed by #6639
