### ISSUE TITLE
[tslint: whitespace] Should I add the replacement of this tslint rule in this Repo?

### ISSUE THREAD

**Issue by fa93hws** [typescript-eslint/typescript-eslint#664]
Hi
I am currently working on migrating the existing tslint rule to eslint rule because running the tslint as eslint plugin extremely slow due to the fact it need the type information.
There are quite a few rules missing now and one of them is `whitespace` in tslint https://palantir.github.io/tslint/rules/whitespace/

The missing parts so far are:
check-type
check-typecast
check-type-operator

And my question is, 
1. Do you think the eslint equivalent rule should be included in this repo? Or it's better to modify the existing eslint rule to handle the ts keyword?
2. If it should be in this repo, do you prefer them to be 3 rules or 1 rule?

**Comment by bradzacher** [comment]
there are various rules in eslint core which can (and should) be extended to handle this.

I don't know what the TSLint rule actually enforces, because it has no examples.

- `check-type` = checks for whitespace before a variable type specification.
    - does this mean it wants a space around the equals signs for `type Foo = X`?
    - If yes, then could be handled by a modified [`space-infix-ops`](https://eslint.org/docs/rules/space-infix-ops)
- `check-typecast` = checks for whitespace between a typecast and its target.
    - does this mean it is for whitespace when using angle bracket assertions?
    - If yes, I wouldn't even bother with this - angle bracket assertions are essentially deprecated in favour of `as` casts.
- `check-type-operator` = checks for whitespace between type operators | and &.
    - could be handled by a modified [`space-infix-ops`](https://eslint.org/docs/rules/space-infix-ops)

By "could be handled" I mean we could extend the rule in this plugin to add handling for typescript AST nodes.

**Comment by fa93hws** [comment]
Hi, many thanks for the quick reply.
Sorry I am not quite sure what do you mean by "extend the rule in this plugin to add handling for typescript AST nodes"

Do you suggest that I could write a new rule in this repo by importing or copy&paste the rule in eslint and then make some modification?
Or make a PR to eslint repo to add the typescript AST nodes?

**Comment by bradzacher** [comment]
Examples:
- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/camelcase.ts
- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/func-call-spacing.ts
- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/semi.ts

The base rule `space-infix-ops` does what we want to, except it doesn't handle typescript nodes.
So what we do in this case is create what we call an extension rule.

1) create a new rule in this repo called `space-infix-ops`
2) import the rule `space-infix-ops` from the base eslint package.
3) make sure the `create` function of your rule returns the create function output of the base rule `create(context) { return {...baseRule.create(context)} }`
4) add new selectors for typescript nodes.
    - review the base rule code to see if you can reuse the internal logic by calling the base rule's selectors.
5) add tests.

**Comment by fa93hws** [comment]
Many thanks!
