### ISSUE TITLE
Default rules from typescript-eslint plugin not active in my project

### ISSUE THREAD

**Issue by gidgudgod** [typescript-eslint/typescript-eslint#6660]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.0.1-rc&sourceType=module&eslintrc=LYewJgrgNgpgdDAHgBxAJwC4GcAEBeHAbwCgcc0QQMAuHDNCGAGlJyQxgDswtaBtVmQBEyKBADmAS07UAAhgCeyGFgDGaScgwBaFVGkYA9GhiqQwYFzAwwQlmWGd2hsye0B3GACNtAN0kYAIZQWHaCOCImGBiSMGhhZAC69jjIgWhYcbQA5PJKKuqaOnoGhmkZcdkp5ZloAPJakiCcvEThyBQAVqY0ONlwhthmnABmkuJwnVjNVeGmwIEAanFYTTI4AEwADBsbrAC+1WJSLfy5ispqGlq6WPqcGNmsyawMsK2EOOHn+VdFt-cjMNVlgOA9tBcYNpJMBUJgsNl+OEyNl3OlOLMHA4SFisR0YCMsn1IdDYehsJjcYdwi8yNSyCBfHENNZWgIsTjcWN3mcAFRwClMPr87CIJ64nC03FvFS0TkSn6XQo3EoPQycEDaCCcCCZMB+dIIs5otAYlISsifdLiLAASXEGpMAAVAtE4utsgA9AD64otdORDilCrySuuxTupQ1uhQ+lUAW0gU4CkRfRNZsD9IcWZe+wA3MRiEA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkeAhpgObp4VTokCskANODUipkAI3YBtATSgATBHymC58AHTI8WeiIwLptTkXQAPNooC6-aZHqpUsAO4ApMpTyYArukuCSAa2SIADKiAMIAFujQvuxunt60JG7I0GyuHl6KkABmsJjQ6CHEJMiJ6ER4IfTFREwAkkQAYmjoAHL08Jwx6fFQRLAAovDqXXGZnACysDLuGPUamLCIIxlW8FMz6OyQBsZsPZBr0xgASpywqO4ExFt9Mpv7mGeoAG7ozsSTR5tpo1Yl5-QNDJPhsXGBYitBAArEhGLaIR4kLCvXSCERVdAAVUwqC2KlRtEQgLCYOoekgAAE4EhiGU8CQAPQAKgkiisJDyDOpiFp5UZLLZYAsgsp3N59NZeh8nLFhj5kEFwqlouIGhM-MlUqgHOgXNVuw1ip6tCp+vVmuVOr15QNCqlSvJFMSAE8MBrKJItdrOS63cy7XoHVYnXhXZ0PYKEj7Q26A9Ig4IKYh3Npkv6I17IMnU7qBfbjVAkynhNALeTsyW4zQzIoAL77ZBEaCPDrlGzLfZ9WpIEvqACCRGd7CyNiRAnrAkgjegFzuZcgKk4wnKeRUMIJvV2AFoys8VDIVBL9kymczD2Rj6emee4Zez9B13fr-B1wIHdsjDP3HOM4JbugAH1DlBAMa1rIA

### Repro Code

```typescript
if (true)      
    {
      console.log('Yes its true') }
```

### ESLint Config

```javascript
module.exports = {
  root: true,
  extends: ["plugin:@typescript-eslint/recommended",
  "next/core-web-vitals",
  "prettier", ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: './tsconfig.json',
    ecmaVersion: 2022
  },
  plugins: ['@typescript-eslint'],
  rules: { 
    '@typescript-eslint/consistent-type-imports': [
      'warn',
      {
        prefer: 'type-imports',
      },
    ],
  },
  overrides: [
    {
      files: ['*.ts', '*.tsx'],
      rules: {
        '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
        '@typescript-eslint/no-explicit-any': 'warn',
      }, 
    },
  ],
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "baseUrl": ".",
    "paths": {
      "@components/*": ["src/components/*"],
      "@components": ["src/components"],
      "@contexts/*": ["src/contexts/*"],
      "@contexts": ["src/contexts"],
      "@styles/*": ["src/styles/*"],
      "@styles": ["src/styles"],
      "@public/*": ["public/*"],
      "@public": ["public"]
    },
    "incremental": true,
    "noImplicitAny": false
  },
  "include": [
    ".eslintrc.js",
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "**/*.cjs",
    "**/*.mjs"
  ],
  "exclude": ["node_modules"]
}
```

### package.json devDependencies
```jsonc
  "devDependencies": {
    "@types/eslint": "^8.21.2",
    "@types/node": "^14.14.13",
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "@typescript-eslint/eslint-plugin": "^5.55.0",
    "@typescript-eslint/parser": "^5.55.0",
    "cross-env": "^7.0.3",
    "eslint": "^8.36.0",
    "eslint-config-next": "^13.2.4",
    "eslint-config-prettier": "^8.7.0",
    "eslint-import-resolver-typescript": "^3.5.3",
    "prettier": "^2.8.4",
    "typescript": "^4.7.4"
  }
```

### Expected Result

From the "Repro Code", I expect error from the brace-style rules, also from multiple spacing. Also expect the ESlint extension automatically format it on save. 
I've test tried to add rules manually and the rules are working. But I dont want to add all the default rules one-by-one manually, that's why I installed this package.

### Actual Result

I dont get any error/warn, I already use eslint extension in my VSCode, I already run the eslint command in my terminal and the error or warn still not comes up.

**Comment by bradzacher** [comment]
You can use the `--print-config` cli flag to display the config for any file in your codebase.
https://eslint.org/docs/latest/use/command-line-interface#--print-config

This can help you debug your config.

Otherwise you're going to need to create an isolated reproduction repo for the issue so that we can help. Dumping some config into an issue isn't enough for us to help.

https://typescript-eslint.io/maintenance/issues#-complex-bugs

**Comment by gidgudgod** [comment]
This is the result of the debug from my project using ` --print-config`
```
{
  "env": {
    "browser": true,
    "node": true
  },
  "globals": {},
  "parser": "D:\\myProject\\node_modules\\@typescript-eslint\\parser\\dist\\index.js",
  "parserOptions": {
    "project": "./tsconfig.json",
    "ecmaVersion": 2022,
    "requireConfigFile": false,
    "sourceType": "module",
    "allowImportExportEverywhere": true,
    "babelOptions": {
      "presets": [
        "next/babel"
      ],
      "caller": {
        "supportsTopLevelAwait": true
      }
    },
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "plugins": [
    "react-hooks",
    "jsx-a11y",
    "react",
    "import",
    "@next/next",
    "@typescript-eslint"
  ],
  "rules": {
    "@typescript-eslint/consistent-type-imports": [
      "warn",
      {
        "prefer": "type-imports"
      }
    ],
    "curly": [
      0
    ],
    "lines-around-comment": [
      0
    ],
    "max-len": [
      0
    ],
    "no-confusing-arrow": [
      0
    ],
    "no-mixed-operators": [
      0
    ],
    "no-tabs": [
      0
    ],
    "no-unexpected-multiline": [
      0
    ],
    "quotes": [
      0
    ],
  ....others unactive rules
}
```

**Comment by gidgudgod** [comment]
I see... so these rules aren't active by defaults and these rules showed in my terminal when I use `--print-config` because of prettier package that I supplied
```
    "@typescript-eslint/block-spacing": [
      "off"
    ],
    "@typescript-eslint/brace-style": [
      "off"
    ],
    "@typescript-eslint/comma-dangle": [
      "off"
    ],
    "@typescript-eslint/comma-spacing": [
      "off"
    ],
    "@typescript-eslint/func-call-spacing": [
      "off"
    ],
    "@typescript-eslint/indent": [
      "off"
    ],
```

so I need to add them manually or find package that has style format rules that won't conflict with @typescript-eslint package.
Thanks for the help and answer Sir @bradzacher . ^_^

**Comment by bradzacher** [comment]
It's not a set of rules that conflict with our package - its rules that co flict with the tool prettier.

Prettier is a formatter and is a separate project - https://prettier.io/
You've turned on their config I assume because you use their tool, which is a formatter. If you don't use their tool then you shouldn't use their config.
