### ISSUE TITLE
[no-object-literal-type-assertion] make allowAsParameter work with "throw" keyword?

### ISSUE THREAD

**Issue by ZYinMD** [typescript-eslint/typescript-eslint#668]
```JSON
{
  "rules": {
    "@typescript-eslint/no-object-literal-type-assertion": ["error", {
      "allowAsParameter": true 
    }]
  }
}
```
My code:
```TS
else throw { code: 'E42', message: 'foo failed' } as CustomError;
```

**Expected Result**
I hope eslint would allow it, since I've set `"allowAsParameter": true`

**Actual Result**
It's not allowed, because `throw` is not a function, it's a function-like keyword, just like `typeof` or `delete`.

Could we make it treat `throw` as a function in regards to `"allowAsParameter": true` ?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.9.0` |
| `@typescript-eslint/parser`        | `1.9.0` |
| `TypeScript`                       | `3.4.5` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `10.15.3` |
| `npm`                              | `6.9.0` |

**Comment by bradzacher** [comment]
I don't understand - what does casting a `throw` do?
Are you doing it solely to make sure you adhere to a certain structure for your thrown objects?

Why not create a class, or a utility function?

**Comment by ZYinMD** [comment]
In my case, which is front-end code, I want to adhere to a certain structure for the thrown objects, because all these objects with different error code will propagate to a central `catch`, and stored, and be displayed with an UI for the user to see.

Yes there're many ways to do it. I could also just create a typed variable and throw that variable. Maybe I fell into that mentality of "I got a cool idea so let's file an issue because why not"... Feel free to close it. :)

**Comment by bradzacher** [comment]
It wouldn't fall under the `allowAsParameter` option, because `throw` is an operator, not a function - so it's not technically a parameter.

We could always add a new option for operators.

**Comment by ZYinMD** [comment]
One thing I've always been confused about is that `return` and `throw` are not listed on the [JS Operator Precedence](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence) . Don't know if they are operators.

**Comment by bradzacher** [comment]
Sorry, I wasn't intending to use the strict definition of the word `operator`.
It's technically not an operator, no, as operators are generally expressions.

It's a statement. Same as things like `if`/`for`/`while`/`do...while`.

Similar to those, they don't have "parameters" and are not covered by the ruke
Though the reason I say operator is because syntactically it's not much different to other operators, because it requires no parentheses and takes a single expression.
