### ISSUE TITLE
Bug?: type-utils > TypeOrValueSpecifier's file detection is case insensitive

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6697]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

type-utils

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Following up from https://github.com/typescript-eslint/typescript-eslint/pull/4436/files#r1134626465: in order to get the PR merged, the _"is this type declared in one of these files?"_ logic (`typeDeclaredInFile`) logic was changed to be case _insensitive_. It `.toLowerCase()`s all strings.

That means this config:

```js
{ from: 'file', name: 'MyType', path: './filename' }
```

...will match `./filename`, `./Filename`, `./FILENAME`, and so on.

This case insensitivity _probably_ won't matter in any projects. But most file systems are in fact case sensitive. So we really should get it to work at some point.

### Additional Info

To start on this issue, remove the `.toLowerCase()` calls in `typeDeclaredInFile`. https://github.com/typescript-eslint/typescript-eslint/blob/346fdbc1c2cfe63a6cd006c22b652d536332cefc/packages/type-utils/src/TypeOrValueSpecifier.ts#L130

Re-run unit tests for `type-utils` and `eslint-plugin`. You'll also want to add unit tests to `TypeOrValueSpecifier.test.ts` to make sure that case sensitivity is respected.

**Comment by Josh-Cena** [comment]
Is https://github.com/typescript-eslint/typescript-eslint/issues/4680 related?

> But most file systems are in fact case sensitive.

APFS is case-insensitive, and AFAIK NTFS is somehow case-insensitive? That leaves only Unix-like systems (a.k.a. CI environments)

**Comment by marekdedic** [comment]
From the linked review, on the machine of @JoshuaKGoldberg:

* `relativePath` is `'tests/fixtures/file.ts'`
* `absolutePath` is `'/Users/josh/repos/typescript-eslint/packages/type-utils/tests/fixtures/file.ts`
* `declarationFiles[0].fileName` is `'/users/josh/repos/typescript-eslint/packages/type-utils/tests/fixtures/file.ts'`

**Comment by marekdedic** [comment]
On my machine:
- `realtivePath` is `tests/fixtures/file.ts`
- `absolutePath` is `/home/marekdedic/Documents/git/typescript-eslint/packages/type-utils/tests/fixtures/file.ts`
- `declarationFiles[0].fileName` is `/home/marekdedic/Documents/git/typescript-eslint/packages/type-utils/tests/fixtures/file.ts`

I'm on Linux and I presume @JoshuaKGoldberg is on a Mac. It seems like `declarationFiles[0].fileName` is getting lower-cased on Mac and not on Linux...

**Comment by JoshuaKGoldberg** [comment]
Btw, yes, I'm on a Mac. 👍

**Comment by JoshuaKGoldberg** [comment]
Fixed in #6781, will be released in v6 🚀

**Comment by JoshuaKGoldberg** [comment]
Fixed in #6781, will be released in v6 🚀. Thanks @marekdedic as always!
