### ISSUE TITLE
Bug: type-utils > TypeOrValueSpecifier doesn't account for org-scoped packages

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6698]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

ast-spec

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

From https://github.com/typescript-eslint/typescript-eslint/pull/4436#discussion_r1134628059: when checking whether a `'package'` matches in `TypeOrValueSpecifier.ts`, we check whether the declaration file name includes `specifier.package` directly:

https://github.com/typescript-eslint/typescript-eslint/blob/346fdbc1c2cfe63a6cd006c22b652d536332cefc/packages/type-utils/src/TypeOrValueSpecifier.ts#L170-L176

This is a potential issue because package names with `@` in them have a `__` replacing the `@`. And there might be other replacements I'm not remembering - haven't looked deeply into it. 

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/cc222f340546ff85b7c9271f4ecbd07b9d661c94/types/11ty__eleventy-img

We should handle any name substitutions in npm packages well, and add unit tests for it in `TypeOrValueSpecifier.test.ts`.

### Fail

```typescript
n/a
```

### Pass

```typescript
n/a
```

**Comment by marekdedic** [comment]
I think the elephant in the room here is that TypeOrValueSpecifier has not tests for package types - I don't know how to do that as it seems the test environment is essentially "sandboxed". Any ideas on that? If somebody can help with that I'd like to finish what I started in the original PR :)

**Comment by JoshuaKGoldberg** [comment]
Heh, a good question. You can try basing it on the packages this repository depends on, like `typescript` and `@types/react`.

**Comment by JoshuaKGoldberg** [comment]
Heh yeah merging into `v6` doesn't get the auto-close. Only merging into our default branch (`main`). 🤷
