### ISSUE TITLE
Bug: [non-nullable-type-assertion-style] autofix removes necessary cast of generic function return value, changing type of variable from child type to parent type

### ISSUE THREAD

**Issue by idrisa-bsquare** [typescript-eslint/typescript-eslint#6706]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.0.1-rc&sourceType=module&code=JYOwLgpgTgZghgYwgAgApyhcyDeyC+AUKJLIigMIAWwANgCbIQAekI9AzmhlmLocmQcA9gFsIqKMIAO0MAE8A-AC5kAI2HDaEOCADchIoRgBXEAjDBhIZAHMIYAGpxaJiAB4AKk1ZZO3THAAPgAKAEpVbwAfZDN6CBhQCEYcAWRMMBMoGxx8ZDguaNj2BKT6AyMEaw4+BBoGZABeOwdnVwhw-K5qOnLCQjregDoRcUkZOXkm5HhaDgg9IA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6JgeydqYXgEMARklpFStfsmSJo+Sl1rIiSdFADu-aE0hhwYAL4h9QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
interface Parent { }
interface Child extends Parent {
  someProperty?: boolean;
}

function getValue<T extends Parent>(): T | undefined {
  return {} as T | undefined;
}

const child = getValue() as Child; // autofix converts this to getValue()!; changing the type of child from Child to Parent

child.someProperty = false; // following autofix this this is an error
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/non-nullable-type-assertion-style": "warn" 
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

Autofix should not have replaced the typecast with a non-null assertion operator as the typecast changes the type inferred by typescript from Parent to Child

### Actual Result

Autofix replaces the typecast with a non-null assertion operator

### Additional Info

Seems similar to https://github.com/typescript-eslint/typescript-eslint/issues/3938

Simple work around is declaring the type of child, e.g.
```typescript
const child: Child = getValue() as Child;
```

**Comment by bradzacher** [comment]
This is the same behaviour as in #528

In a nutshell - TS uses the `as` assertion to back-fill the generic. So when you look at the types you'll see `getValue<Child>() as Child`.
![image](https://user-images.githubusercontent.com/7462525/226486660-beea43e9-f706-4b47-90a0-b06e9a813fb3.png)

Using a generic parameter only in a return value location is an anti-pattern and behaves rather strangely in TS. You should use the parameter and a non-null assertion instead if this is the type you want `const child = getValue<Child>()!;`
