### ISSUE TITLE
Bug: [no-misused-promises] Nullish coalescing is not handled

### ISSUE THREAD

**Issue by varsis** [typescript-eslint/typescript-eslint#6739]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.4&sourceType=module&showAST=scope&code=JYOwLgpgTgZghgYwgAgBrIN7IFDOQCgEoAuZANwHtgATbAX2wQpAGcxko4RrT8jkAvAD5yVasgA+yEAFcANnMKDkAETiQAdCAoB3fgFJkABmQB+Av2GZkdJaVkKA3NkbM2yYJAC2yoqQAKUBRewCwQADxsUKAA5iJWIBA6yIHBoRD4UBAsgiJZLPgARIWEhC5MrOwAHqToAh7e5W7sAJ61yhxc4qbmnhBeTawUchAachQx+FUANMgtZUA&eslintrc=N4KABGBEAOA2CuBzAlgOwM6QFxgNrgigAEAXAT2gFN0BjAJ2WhIFprY0TICBdAGgJgBDOukp1sxclVoMmrdO1QkA9NGGjx-CJEoAPEpVQATTDnyEocJGiykK1eoxZsOyupRoB7ALbfDRyiMuCD4BOnhYaglQC0g7aUc5FyVlVE9mADNYT0ESNERmaDofZFFTKDFizQJteIdZZwVXNOZvUvhRI0LitrKJHToq4LAAXxARoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
interface X { 
  (): void
}
const void_or_null: (null | X) = Date.now() % 0 ? (() => { }) : null;

const fn_promise = (): Promise<string> => new Promise(res => res(""))

const x: X = fn_promise

const y: X = void_or_null ?? fn_promise

console.log(x, y)
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
     "@typescript-eslint/no-misused-promises": "error"
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

I expect that the 10th line (`const y: X = void_or_null ?? fn_promise`) should highlight `no-misused-promises` lint error

### Actual Result

No error

**Comment by bradzacher** [comment]
[The return type of your nullish coalescing is not `(() => Promise<void>) | (() => void)`, it is just `() => void`](https://www.typescriptlang.org/play?ts=5.0.2#code/CYUwxgNghgTiAEYD2A7AzgF3gDwFzwAoBKeAXgD54AFGJAWwEs0QAeANyQeHIG4AoUJFgJk6LAE98KAK4QI8AD6FiZShy5F+fUZngAvMvHHwA-CZz8A9Jfi34APRN8gA).

This is why the rule doesn't report on your example - because according to the types there isn't anything wrong here.

I'd need to dig in more but we might be able to detect this with some effort. Unsure though.

**Comment by varsis** [comment]
@bradzacher Should I raise this as a bug on the typescript project instead? Seems to be more fitting

**Comment by bradzacher** [comment]
Yeah it might be a bug in TS? Or at least some weird behaviour.

For some reason TS is collapsing the union here even though I don't think it should. If I define a type like `(() => void) | (() => Promise<void>)` then TS won't collapse it, and if the left function returns something other than `void` then TS won't collapse it.

I'm not sure - but might be worth asking?

**Comment by JoshuaKGoldberg** [comment]
Yeah, I don't think there's anything we can do here 😞. If TypeScript tells us a value's type is `() => void`, there's nothing we can do.

Thanks for filing though!
