### ISSUE TITLE
typescript-eslint/no-unsafe-assignment error with dependencies of depencies

### ISSUE THREAD

**Issue by Baptiste-Garcin** [typescript-eslint/typescript-eslint#6746]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

In the `index.ts` there is an error caused by the rule `typescript-eslint/no-unsafe-assignment`

This error is caused by the fact that eslint considers that the return of the `getExpress()` function is `any` even with the type definition. Typescript in the other hand seems to get the proper type for the `foo` variable.

This example is a simplification of the case I face in my project. I am actually writing a type definition for a npm package written in javascript and this package give access to function that return Express element (Application, Router…). I might be a difference between this example and the real world. And also, maybe, it's not a bug and I am doing something wrong.

### Reproduction Repository Link

https://github.com/Baptiste-Garcin/issue-ts-eslint

### Repro Steps

1) clone the repo
2) `npm install`
3) `npm run eslint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.56.0` |
| `@typescript-eslint/parser`            | `5.56.0` |
| `TypeScript`                           | `5.0.2` |
| `ESLint`                               | `8.36.0` |
| `node`                                 | `18.12.1` |

**Comment by JoshuaKGoldberg** [comment]
> Typescript in the other hand seems to get the proper type for the foo variable.

No, it doesn't, because the `'express'` isn't typed in this package. `express` isn't listed as a dependency/devDependency/peerDependency and nothing provides its types. The `foo` variable might not be giving any type errors (and I find it odd that enabling `noImplicitAny` doesn't cause any of those to be reported), but it doesn't have any known properties in TypeScript-land.

Thanks for filing - but the `@typescript-eslint/no-unsafe-assignment` is acting correctly based on the information it's given.
