### ISSUE TITLE
Docs: Figure out a way to link to our Discord's v6 channel

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6757]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Thanks @reintroducing for mentioning this in https://github.com/typescript-eslint/typescript-eslint/discussions/6014#discussioncomment-5411631!

https://typescript-eslint.io/blog/announcing-typescript-eslint-v6-beta includes a link to the `#v6` channel in our Discord server. 

* `#v6` channel direct link (in that post): https://discord.com/channels/1026804805894672454/1084245444676292688
* Invite to join our Discord server (in the site footer): https://discord.gg/FSxKq8Tdyg

For folks who've already joined the Discord server, the direct channel link works. But for folks who haven't, they see ... well, I can't get Discord to verify my new test account, so I'll leave this for someone else to fill in 😄 what happens if you try to visit the v6 channel link without having previously joined the server?

Admittedly, I'm not a Discord poweruser and am not sure the best strategy here.

### Affected URL(s)

https://typescript-eslint.io/blog/announcing-typescript-eslint-v6-beta/

**Comment by reintroducing** [comment]
@JoshuaKGoldberg Thank you for opening this and the other issue about the v6 docs, I was going to open them this morning and woke up to see you already have, much appreciated.  

This is what you see when you try to go to the Discord link in the post:
![Screenshot 2023-03-24 at 7 21 31 AM](https://user-images.githubusercontent.com/259901/227552446-eec5249a-9aca-4327-9ce8-771017d42af1.png)
I also tried searching for the typescript-eslint server which returned no public results. I am also far from a Discord power user so I didn't realize that it was private nor that I needed an invitation. I clicked on your link above, accepted the invite, and now I am in (thank you). Maybe just a note in the blog post in parentheses after the channel link to notify people who are also unfamiliar with how Discord works that you need an invite with that link would suffice?

**Comment by sfavello** [comment]
Hi, I wasn't sure how to make a PR for this so I just wanted to drop a suggestion. After linking the discord where the user is already a member, you can add a sentence afterwards that says something like:

_"If you are not a member of our discord group, [click here to join!](https://discord.gg/FSxKq8Tdyg)"_  and I'd just add the launch icon to indicate to the users that the link will take them away from the website.
