### ISSUE TITLE
Try out v6 beta on various important community repos

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6760]
V6 is ready for public testing (hooray! https://typescript-eslint.io/blog/announcing-typescript-eslint-v6-beta 🎉) and we want to make sure we try it out on lots of projects. It'd be particularly valuable to try out projects that are:

* Large enough to exercise test cases _(think >100 source files)_
* Popular enough to get visibility for the v6 beta in front of many people _(think >1000 GH stars)_

I'm thinking to start, at least:

* ~Angular~ _(still on TSLint)_
* Astro: https://github.com/withastro/astro/pull/7425
* Babel: https://github.com/babel/babel/pull/15716
* create-t3-app: https://github.com/t3-oss/create-t3-app/pull/1476
* ~Prettier~ _(doesn't use our recommended configs)_
* Redux: https://github.com/reduxjs/redux/pull/4566
* Redux Toolkit: https://github.com/reduxjs/redux-toolkit/pull/3541
* ~Solid~ _(doesn't lint itself)_
* Tanstack _(was on my home computer and I had a hard time setting up before traveling - next time maybe!)_
* trpc: https://github.com/trpc/trpc/pull/4541
* TypeScript: https://github.com/microsoft/TypeScript/pull/54693

For each of these projects, we should see:

* Is someone on their end willing to try things out?
* In addition to version bumps, are they up for recreating their linter configs with the new configs (https://github.com/typescript-eslint/typescript-eslint/discussions/6014)?

Filing this tracking issue to make sure we do this before releasing v6 as stable.

> If you've got a project that matches those criteria & want to get it added to the list, let us know! We'd be happy to work with you.

**Comment by RebeccaStevens** [comment]
v6 seems to strip out the `"main"` field from the `package.json`. Although I'm all in favor using `"exports"` instead, rollup doesn't currently support resolving exports. Would we be able to keep the `"main"` field for now?

**Comment by JoshuaKGoldberg** [comment]
👍 ok will do! Btw @RebeccaStevens I appreciate the info but for unrelated-to-the-OP issues like this one, please file a new issue. Info in these comments tends to get lost over time. No worries on this one!

**Comment by fisker** [comment]
# Prettier

https://github.com/prettier/prettier/pull/14429

Still waiting for #6723

**Comment by JoshuaKGoldberg** [comment]
Aside: chatted with @jakebailey today who gave a tentative 👍 to at least trying v6 out on the TypeScript codebase. If I have time I'll try to look into overhauling their config to use type-aware rules only in smaller, not-so-performance-killing files (e.g. not `src/checker.ts`).

**Comment by JoshuaKGoldberg** [comment]
#7110 is merged into the `v6` branch, #7111 is fixed, and https://www.npmjs.com/package/@typescript-eslint/eslint-plugin/v/6.0.0-alpha.158 is published. I'll start on this now! 🚀

**Comment by fisker** [comment]
I want give an update here, we (Prettier) can remove all the invalid node checks after upgrade to latest v6, so we can now use `parse` dirctly instead of `parseWithNodeMaps`. I think this method was added because Prettier need it at that moment, free feel to remove it if you think it's unnecessary to keep.

**Comment by nicolo-ribaudo** [comment]
I don't know exactly what what we need to update in our configs to try this, but I would happily review a PR trying it out in Babel.

**Comment by JoshuaKGoldberg** [comment]
Ah amazing thanks @nicolo-ribaudo! I'll send a PR :)

**Comment by nickmccurdy** [comment]
How about Vite and Vitest (using [`@antfu/eslint-config`](npm.im/@antfu/eslint-config))?

**Comment by JoshuaKGoldberg** [comment]
@nickmccurdy a great idea for next time, thanks!

**Comment by JoshuaKGoldberg** [comment]
Per https://github.com/sveltejs/kit/pull/10371, looks like Sveltekit would be a good one to add too. :)
