### ISSUE TITLE
Docs: Add comments to all rules for auto-complete and description.

### ISSUE THREAD

**Issue by hindicator** [typescript-eslint/typescript-eslint#6764]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Hi,
I'd like to suggest that you add to all rules `@fileoverview` comment with description for the specific rule.
This would achieve VSCode auto-complete inside eslintrc file, so that rules will be easier to define.

[See this](https://github.com/eslint/eslint/blob/main/lib/rules/no-multi-spaces.js#L2)

[example file](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/rules/semi.ts#L1) that could use that.
Could be nice :)

**Comment by bradzacher** [comment]
> This would achieve VSCode auto-complete inside eslintrc file, so that rules will be easier to define.

What do you mean by that?
What does `@fileoverview` do for vscode?

---

This is a coding style that we don't necessarily agree with - top level comments like that are another thing to maintain and keep in sync. I don't see any tangible benefit compared to the maintenance cost, personally.

**Comment by bradzacher** [comment]
Additionally - please fill in the issue title when filing an issue.

**Comment by hindicator** [comment]
![image](https://user-images.githubusercontent.com/73799532/227752947-83f4ae5b-c92f-4b5f-9f50-47e2ee4f72dd.png)

IntelliSense has suggestions for ESLint rules but not for the plugin(or any other I assume).
Trying now to figure out how it's implemented, 
if it's related only for VSCode - ESLint package or we can do something in here that would achieve this.
Maybe I'll create a PR for this when I'll know more.

**Comment by bradzacher** [comment]
This is implemented via a json schema, not via the JSDoc.

Specifically for `.eslintrc.json` files the vscode eslint extension provides a json schema which has descriptions for the core eslint rule.

This schema does not include definitions for any 3rd party rules, however, like ours.
