### ISSUE TITLE
Website: [Playground] ast viewer should display comments and tokens

### ISSUE THREAD

**Issue by armano2** [typescript-eslint/typescript-eslint#6769]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

while debugging [issue #6768](https://github.com/typescript-eslint/typescript-eslint/pull/6768) and trying to reproduce it in playground i stumbled upon issue with playground not displaying comments correctly

note:
- tokens and comments are currently hidden
  https://github.com/typescript-eslint/typescript-eslint/blob/bc31078cf86d69eee881e4a7daeffa347c1d82a7/packages/website/src/components/ast/serializer/serializerESTree.ts#L6
- auto-selecting nodes from editor should not trigger for tokens and comments

### Affected URL(s)

https://typescript-eslint.io/play/

**Comment by bradzacher** [comment]
Tokens might be nice behind a flag, comments probably always.

I was actually just thinking about this the other day as I was looking into the hashbang comments!
