### ISSUE TITLE
Repo: Add a GitHub Action that runs stylelint

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6784]
### Suggestion

#6688 -> #6779 added [Stylelint](https://stylelint.io) to our CSS files. But nothing runs in CI to make sure no violations have popped up.

Similar to how [`.github/workflows/ci.yml`](https://github.com/typescript-eslint/typescript-eslint/blob/2b2a075b4b82a273d97009cc30be4ba0a98fc635/.github/workflows/ci.yml) has `build` and `lint*` jobs, let's add a new one for running `stylelint`.

**Comment by juank1809** [comment]
I'd like to work on this issue!

**Comment by JoshuaKGoldberg** [comment]
Fixed by #6800. 👍
