### ISSUE TITLE
Docs: Document website-eslint 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6799]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I'm on @jutanium's Twitch stream. Dan is working on a browser app that includes a CodeMirror editor that we'd sure love to have ESLint run on... except, getting ESLint to run in the browser is a nontrivial task (https://github.com/eslint/eslint/issues/8348). We've managed to do it though!

It'd be good to document how the `website-eslint` package works architecturally, similar to how we document typescript-estree on https://typescript-eslint.io/architecture/typescript-estree.

At the very least, adding a README.md to the package would be nice.

### Affected URL(s)

https://typescript-eslint.io/architecture/website-eslint, maybe?

**Comment by bradzacher** [comment]
@armano2 knows the most - but the TLDR is that you only need/want the `Linter`class - which is designed to solely operate on strings and takes object definitions for rules and parsers.

You can tree shake everything else from the package after that.

**Comment by armano2** [comment]
making eslint work in browser is actually not that hard, har part is making ts-eslint work, this package is intentionally private as this is "hack" and build to work monaco,

I will try to prepare some documentation for it after I finish "splitting" #6656, but this is low prio  for me (at least for now)

this package on main is kinda a mess and i simplified it in v6
https://github.com/typescript-eslint/typescript-eslint/blob/v6/packages/website-eslint/build.ts

----------------------------

if you want to just load eslint for web without typescript you an look at what @mysticatea and @ota-meshi did in 
- https://github.com/mysticatea/vue-eslint-demo
- https://github.com/mysticatea/eslint4b (no longer maintained)
- https://github.com/ota-meshi/eslint-plugin-vue-demo
- https://github.com/ota-meshi/site-kit
