### ISSUE TITLE
Enhancement: [no-for-in-array] Write a more informative report message

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6824]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-for-in-array

### Description

The standard report message from `@typescript-eslint/no-for-in-array` hasn't been updated in quite a while:

> ```plaintext
> For-in loops over arrays are forbidden. Use for-of or array.forEach instead.
> ```

I'm under the impression we generally try to [edit: _not_] use authoritarian phrases like _"are forbidden"_. Users don't like being told what to do without a backing reason. ESLint can sometimes have a reputation of yelling about things it doesn't need to. These phrases don't help.

Instead, how about something like...

```plaintext
For-in loops over arrays loop over array keys as strings, which is often confusing and not desirable.
```

...except, not so wordy. Can someone help find a better phrase? 😄 

### Fail

```typescript
for (const letter in ['a', 'b']) { }
```

### Pass

```typescript
n/a
```

### Additional Info

This issue came out of a Twitch stream with @jutanium. 👋

**Comment by bradzacher** [comment]
> I'm under the impression we generally try to use authoritarian phrases like "are forbidden". Users don't like being told what to do without a backing reason.

Eh. I think it's much of a muchness.
Users will choose to ignore or not ignore regardless of what the error says because all engineers are the worst because they think they know better and a more descriptive error won't necessarily sway someone.

But I'd agree that including a concise reason is better. The rule docs are pretty clear as to why it's a bad idea to at least inform the uninformed.

> A for-in loop (`for (var i in o)`) iterates over the properties of an Object. While it is legal to use for-in loops with array types, it is not common. for-in will iterate over the indices of the array as strings, omitting any "holes" in the array.

The big problems:
- skips holes
- string keys
- can include prototype keys

We should probably also update the docs.
