### ISSUE TITLE
Docs: There's a typo in "Monorepo Configuration" section

### ISSUE THREAD

**Issue by frencojobs** [typescript-eslint/typescript-eslint#6833]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Here, it says `(see below)` while the content it references is actually above it. https://github.com/typescript-eslint/typescript-eslint/blob/74016c2de9f4e83a06e2c2be5a57bf0f4adfba63/docs/linting/typed-linting/Monorepos.mdx?plain=1#L102

### Affected URL(s)

https://typescript-eslint.io/linting/typed-linting/monorepos

**Comment by JoshuaKGoldberg** [comment]
Oh no! 😄 agreed, this is a typo.

I'd also go one step further and say we should avoid directional terms like _"above"_ and _"below"_. Readers who aren't visually looking through the code might not identify with that.

Let's have the code link to the specific section in the page with the info by name.
