### ISSUE TITLE
Website: Add 'pnpm' tab alongside 'npm' and 'yarn'

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6835]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

[pnpm](https://pnpm.io) is nice. I use it in all my new packages, and many users are switching to it. But, our guides just have npm and yarn tabs:

![Screenshot of npm and yarn instructions in our getting started docs page](https://user-images.githubusercontent.com/3335181/229581897-8c7b5820-7133-425c-9009-fcac05b05f56.png)

Let's add pnpm as a tab! 🚀 

I don't know the best way to do this. Perhaps there's a dedicated package somewhere, or an option in an existing package we use?

This issue came out of a Twitch stream with @Jutanium. 👋

### Affected URL(s)

* https://typescript-eslint.io/getting-started
* Quite a few others

**Comment by armano2** [comment]
this will be done upstream, https://github.com/facebook/docusaurus/pull/8690

**Comment by JoshuaKGoldberg** [comment]
@armano2 my hero!!

**Comment by JoshuaKGoldberg** [comment]
👍 can confirm, thanks! cc @jutanium: https://v6--typescript-eslint.netlify.app/ -> https://v6--typescript-eslint.netlify.app/getting-started#step-1-installation
