### ISSUE TITLE
Bug: [naming-convention] "modifiers": ['public'] matches public static

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [typescript-eslint/typescript-eslint#6838]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.0.2&sourceType=module&code=KYDwDg9gTgLgBAYwDYEMDOa4GEIDs3C4wDyYMAlnmgOrkAmA5sPAN4BQccYArgEZLkEcNDBQUhAOQCqAGRkB9LAEEAKgFEA4sQBKATXkAFGUqxqAEsRkARNdrgBeOAHJS8crjgwIiABYpcuMBITgDcHFx8AkIiYoJwagCySgCSClhmShISajIOzmoAtijkwWGcPPxxPsAodMBQ8rgoBcAAhABcwjBQ7gxlEZVCCFSEMADKojDALUQdXT24fWwAvkA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6JgQwFtmBzWsgHsmAN0QtKw9GADa4bDkTRog6JAA08hVgXZIAM1VcO+aXN27IyTgGtEAfTIdkiSFt0BdTRZxdBAE0p9SiVUDBlIYlgAI0YySC93BStEJDJ8VWlIMnhnZAAFFVJoIjcLAF93D0ryoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
export class ConsentOptionsWidget {
  public static NULL_CATEGORY_PLACEHOLDER = 'Opt in to channel';
  public static EMAIL_CHANNEL = 'Email';
  public header_name!: string;
  public consentStatement!: string;
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/naming-convention": [
      "error",
      {
        "format": [
          "snake_case"
        ],
        "modifiers": ["public"],
        "selector": "classProperty"
      }
    ]
  }
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

Only `consentStatement` generates an error.

### Actual Result

I expected `consentStatement` to generate an error because it's a class property and `public` but I did not expect `NULL_CATEGORY_PLACEHOLDER` or `EMAIL_CHANNEL` to generate an error since they are `public static` and the docs say:

> The name must match all of the modifiers.
For example, if you provide { modifiers: ['private','readonly','static'] }, then it will only match something that is private static readonly, and something that is just private will not match.

**Comment by bradzacher** [comment]
You've misinterpreted the docs.

You're interpreting it as "a name's modifiers must be the exact set specified in the selector"

The correct meaning of the docs is "a name's modifiers must be a strict superset of the set specified in the selector"

So for example if a name's modifiers are `[private, static, readonly]` then the following selector sets match:
- `[private]`
- `[static]`
- `[readonly]`
- `[private, static]`
- `[private, readonly]`
- `[static, readonly]`
- `[private, static, readonly]`

But the following selector sets won't match:
- `[public]`
- `[public, readonly]`
- `[private, async]`
- `[private, async, readonly]`
- `[private, async, static]`
- `[private, async, static, readonly]`

Similarly if a name's modifiers are `[private]` then it will only match `[private]`, and not any others (like `[private, readonly]`, etc)

**Comment by Blackbaud-JasonBodnar** [comment]
I think the docs should be improved then because "The name must match all of the modifiers." does not mean superset.
