### ISSUE TITLE
Enhancement: consistent-type-imports add option to behave like typescript's importsNotUsedAsValues

### ISSUE THREAD

**Issue by everett1992** [typescript-eslint/typescript-eslint#6844]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/consistent-type-imports

### Description

There is some overlap between consistent-type-imports and TypeScript's importsNotUsedAsValues option. This has already been discussed in #6393. With the release of TypeScript 5 importsNotUsedAsValues is now deprecated and will cause tsc to error so I have to migrate from importsNotUsedAsValues to consistent-type-imports

I would like an option for consistent-type-imports to behave like `importsNotUsedAsValues: error` because
 * I like importsNotUsedAsValues's behavior more
 * I won't have to update code to fix lint warnings (even if they are auto fixable it adds noise)
 
importsNotUsedAsValues allows a type-less import as long as one import is used as a value, while consistent-type-imports requires separating all value and type imports.

### Fail

```typescript
// All imports are used as types 
import { Foo, Bar } from 'foo'

let x: Foo
let y: Bar
```

### Pass

```typescript
// This should be allowed because `Bar` is used as a value
import { Foo, Bar } from 'foo'

let x: Foo
let y = new Bar()
```

### Additional Info

The current rule  requires 

```typescript
import type { Foo } from 'foo'
import { Bar } from 'foo'
```

or 

```typescript
import { type Foo, Bar } from 'foo'
```

**Comment by bradzacher** [comment]
Thanks for the request.
I don't believe such a request broadly reflects the style in the ecosystem.

Lint rules are about enforcing consistency in the codebase, and this rule in particular is about helping flag specifiers that are not used as values. By ignoring certain specifiers it introduces inconsistency into the codebase. Additionally it means that deleting one specifier that's used as a value would cause a lint error - which is a frustrating and confusing thing for users.

For these reasons I am going to reject this request from this project.

**Comment by everett1992** [comment]
> By ignoring certain specifiers it introduces inconsistency into the codebase.

I disagree, importsNotUsedAsValues is consistent. When a module is only imported for it's types you must use `import type`. If a module is ever imported as a value it must use `import`.

>  Additionally it means that deleting one specifier that's used as a value would cause a lint error - which is a frustrating and confusing thing for users.

I feel the current behavior is also frustrating. If I reference an imported type as a value I have to move it from  `import type` to `import`, or vice versa if I remove the last value import I  have to move it into `import type`.

Atleast with the importsNotUsedAsValues behavior I only have to change the imports when _all_ imports are only used as types.

**Comment by bradzacher** [comment]
You don't need to use a top-level type-only import - you can use an inline type specifier. The rule has a configurable auto fixer for this.
Which preserves your desired effect of having value-only imports and limiting the scope of changes.

**Comment by everett1992** [comment]
Don't inline types run into no-import-type-side-effects when all imports
are used as types?

```
import { type A, b } from 'mod'
// Without b
import type { A } from 'mod'
```
