### ISSUE TITLE
Website: Allow filtering to both recommended & strict rules

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6848]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I want to share our _Rules_ page with a filter set to include both _recommended_ and _strict_ rules. The URL for that would be something like https://typescript-eslint.io/rules/?supported-rules=recommended-strict... but:

* There's no way in the page's UI to create that URL. Clicking one of those two buttons causes the other to become a :x: filter
* Visiting that URL results in _no_ rules being shown

https://user-images.githubusercontent.com/3335181/230128671-e25f041b-7969-447b-aa7a-04214d9a2b6a.mov

Suggestion: maybe we should change the UI so that clicking one of the buttons doesn't :x: out the other?

### Affected URL(s)

https://typescript-eslint.io/rules

**Comment by Josh-Cena** [comment]
The reason is because we treat all filters as AND. There's no OR filter, with the assumption that you would just do filtering multiple times instead. The UX of supporting both AND and OR is quite complex, because what if you want a mix of both...

**Comment by JoshuaKGoldberg** [comment]
...yeah, this is very unintuitive to try to grasp 😄. It's been over a year and nobody's reacted to this or stepped up. Closing as out of scope.
