### ISSUE TITLE
Docs: Document how a maintainer might refresh the Algolia search index

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6856]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Forking from https://github.com/typescript-eslint/typescript-eslint/discussions/6855#discussioncomment-5548324: how do we refresh the Algolia index? This has come up at least one time before IIRC.

I see in the Algolia admin page that we have the option to clear the index... but that's very scary. Can someone confirm what the right thing to do is please? 😄 

### Affected URL(s)

https://typescript-eslint.io/architecture/website, maybe?

**Comment by Jolg42** [comment]
@JoshuaKGoldberg Random note, Redwood does it like this
`- Once the docs are done deploying (check here https://app.netlify.com/sites/redwoodjs-docs/overview), start the algolia crawler at https://crawler.algolia.com/admin',` ([link](https://github.com/redwoodjs/redwood/blob/6db7133604de04e1f76805c41270a1ae95a15b56/tasks/release/releaseCommand.mjs#L451))

**Comment by JoshuaKGoldberg** [comment]
Ooh thanks, that is helpful!

And oof:

![Algolia dashboard screenshot showing status blocked for 6 months](https://user-images.githubusercontent.com/3335181/230681368-987360f7-0b43-46e8-b34f-5122081131c7.png)

**Comment by JoshuaKGoldberg** [comment]
I:

1. Cleared the crawler & restarted a new crawl manually (crawler.algolia.com)
2. Cleared the production index (algolia.com/apps/...)
3. Created a new production index
4. Waited 1 minute
5. Saw the new index is live and working on the site 👍 

Would be nice to know if that was the right set of steps.

**Comment by bradzacher** [comment]
Is there a CLI so that we can automatically do these things after a release?

**Comment by Jolg42** [comment]
I didn't find anything in the CLI but they have an endpoint in the REST API: 
https://www.algolia.com/doc/tools/crawler/apis/crawler-rest-api/#control-your-crawlers
https://www.algolia.com/doc/rest-api/crawler/

Random find 🤔 (sounds like they just don't want to guarantee SLA here but it should be fine for this project):
>While there are [use cases for the Crawler REST API](https://www.algolia.com/doc/tools/crawler/apis/crawler-rest-api/), Algolia recommends using the Admin Console. Usage of the REST API isn’t covered by any service-level agreement (SLA). 
https://www.algolia.com/doc/tools/crawler/getting-started/overview/#crawler-rest-api

Maybe this is interesting to try? It's an official action and looks maintained.
https://github.com/algolia/algoliasearch-crawler-github-actions

**Comment by armano2** [comment]
instead of adding it as a task in github, we could use netlify integration for this?

https://www.netlify.com/integrations/algolia/
