### ISSUE TITLE
Enhancement: Detect declared modules for TypeOrValueSpecifier

### ISSUE THREAD

**Issue by marekdedic** [typescript-eslint/typescript-eslint#6861]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

type-utils

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

The `PackageSpecifier` check currently checks the declaration file path for the string `node_modules` and the name of the package: 

https://github.com/typescript-eslint/typescript-eslint/blob/v6/packages/type-utils/src/TypeOrValueSpecifier.ts#L173-L179

I propose to use TypeScript's `sourceFileToPackageName` map defined [here](https://github.com/microsoft/TypeScript/blob/85f20246a4a2b424f7d92b463c20886ddf7488f9/src/compiler/types.ts#L4796).

Only problem is that it is currently marked as internal - but maybe we could get TS maintainers to open it up?

### Fail

```typescript
-
```

### Pass

```typescript
-
```

**Comment by JoshuaKGoldberg** [comment]
> maybe we could get TS maintainers to open it up?

That would certainly be nice. Could you file an issue on them? Until they provide guidance, I'm very nervous taking on _even more_ dependencies on internal TypeScript APIs.

**Comment by marekdedic** [comment]
Great, I was waiting for some kind of go-ahead, opened the issue now :)

**Comment by JoshuaKGoldberg** [comment]
This is actually important to us now, as it blocks `node:test` from being matched to `node_modules/@types/node/test.d.ts`.

**Comment by JoshuaKGoldberg** [comment]
As of #6870, we actually do use `sourceFileToPackageName` now. So renaming & retargeting this issue to support separately declared modules like `node:test` properly.
