### ISSUE TITLE
Docs: Suggest gif reactions on PR maintenance practices

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6889]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

@bradzacher I really like how you post gifs on PR reviews - it feels fun and welcoming. Maybe we should standardize this as a suggestion in our PR maintenance docs? I'm imagining it's something we can encourage ourselves to do especially on PR approvals and also on other comments. 

Thanks to @bdougie I now know of [GIFs for GitHub](https://chrome.google.com/webstore/detail/gifs-for-github/dkgjnpbipbdaoaadbdhpiokaemhlphep) (and [Firefox support too!](https://addons.mozilla.org/en-US/firefox/addon/gifs-for-github)). Which makes the task of finding a gif much easier.

### Affected URL(s)

https://typescript-eslint.io/maintenance/pull-requests

**Comment by bradzacher** [comment]
<img src="https://media2.giphy.com/media/p3TJVtdmIjp8tQFU7F/giphy.gif"/>
