### ISSUE TITLE
Rule proposal: order object properties by type definition

### ISSUE THREAD

**Issue by domdomegg** [typescript-eslint/typescript-eslint#6893]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

The proposed rule would enforce that objects based on type definitions ordered their keys in the same way as the type definition.

This would encourage consistency across the codebase in terms of argument ordering, in particular where there is use of object arguments. This in turn would help readability.

## Why not alphabetical ordering?

The benefit of matching the type definition is that you can still manually group related properties so the ordering would make sense semantically. For example:

```ts
type MyType = {
  one: string;
  two: string;
  three: string;

  ayy: number;
  bee: number;
  see: number;
}
```

doesn't get mangled to:

```
type MyType = {
  ayy: number;
  bee: number;
  one: string;
  see: number;
  three: string;
  two: string;
}
```

or a more practical example

```
type HttpStatuses = {
  "Bad Request": 400,
  "Unauthorized": 401,
  "Payment Required": 402,
}
```

### Fail Cases

```typescript
type MyType = {
  one: string;
  two: string;
  three: string;
  four?: string
}

// error: expected properties in order [one, two, three] but got [two, one, three]
const myObj: MyType = {
  two: 'a',
  one: 'b',
  three: 'c',
}

// error: expected properties in order [one, two, three, four] but got [four, one, two, three]
const otherObj: MyType = {
  four: 'd',
  one: 'b',
  two: 'a',
  three: 'c',
}
```

### Pass Cases

```typescript
type MyType = {
  one: string;
  two: string;
  three: string;
}

const myObj: MyType = {
  one: 'b',
  two: 'a',
  three: 'c',
}

const otherObj: MyType = {
  one: 'b',
  two: 'a',
  three: 'c',
  four: 'd',
}
```

### Additional Info

I think the closest thing in the project so far is https://typescript-eslint.io/rules/member-ordering/

However, this is not suitable for this case as often we want the type definition to be 'as-written' and then everything else to be like 'as-type'. However, if this rule could be extended for this behaviour that would also work.

**Comment by bradzacher** [comment]
This seems like a good idea on the surface - however there are a few quick things I can see that are wrong with it.

First it can easily be really difficult to manage in a codebase because changes to a type definition could easily cause hundreds of objects across files to need to be reordered. Such a small and literally harmless change as reordering a type's properties should not be able to cause such a huge impact.

Second two types with the same properties can be sorted differently for no reason other than "the author wrote it differently".
```ts
type T1 = { a: string, b: string, c: string };
type T2 = { c: string, b: string, a: string };

const x: T1 = { a: '', b: '', c: '' }; // okay
const y: T2 = { a: '', b: '', c: '' }; // error!?!?!?
```
This is confusing for users and leads to an inconsistent codebase, not a consistent one.
A code reviewer on github would have no real knowledge of what's correct or why the properties are in a seemingly weird order unless they manually resolved the type or pulled the PR locally.

Additionally you have this problem of anonymous objects that won't have any enforcement on them at all, which can lead to even more inconsistent ordering:
```ts
const z = { a: '', c: '', b: '' }; // okay
const x: T1 = { a: '', c: '', b: '' }; // error!?!?!?
const y: T2 = { a: '', c: '', b: '' }; // error!?!?!?

// even worse - declaring an object inline vs "anonymously" can change the sorting requirements
declare function foo(arg: T1): void;

const a = { a: '', c: '', b: '' }; // okay
foo(a);

foo({ a: '', c: '', b: '' }); // error!?!?!?
```

Really any orderings applied to anything in the codebase should be solely limited in scope to a syntactic check on the thing to ensure a consistent and fast lint rule.

For these reasons, I think we should reject this proposal.

**Comment by JoshuaKGoldberg** [comment]
Haha, jinx - I agree with @bradzacher. Here's what I was going to post:

> Whooo that's a very specific need. If we were to implement it we'd definitely want to keep it in `member-ordering`. Having two rules that target the same user need (ordering members) would be confusing.
> 
> But:
> * This is a really specific ask and the first instance of it I can find
>     * Most users would not want such a thing - and would likely be confused by it
> * Adding type definition to a rule categorically slows the rule down (when the type info is requested)
> 
> Slapping on the `evaluating community engagement` label for a while to see if anybody else has this need. But my instinct is that no, it won't be something we can take in. I'd suggest making your own version of it using the guide at https://typescript-eslint.io/custom-rules. You could even publish your own plugin! 

Let's close.

**Comment by domdomegg** [comment]
Thanks both for the detailed responses! Understood and I think those are reasonable explanations to not have it in this package :)

Will take a look at implementing it as a custom rule for us.
