### ISSUE TITLE
Docs: wrong information for rule in `no-unnecessary-boolean-literal-compare`

### ISSUE THREAD

**Issue by thariq-nugrohotomo** [typescript-eslint/typescript-eslint#6897]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I'm reading through the documentation in https://typescript-eslint.io/rules/no-unnecessary-boolean-literal-compare/#fixer and seeing the following part:

|           Comparison           | Fixer Output                    |
| :----------------------------: | ------------------------------- | 
| `nullableBooleanVar === false` | `nullableBooleanVar ?? true`    | 
| `nullableBooleanVar !== false` | `!(nullableBooleanVar ?? true)` |

I believe both of them are wrong, i.e. the statement in `comparison` and `fixer output` are not equal.

To show how those are wrong, we can simply compare final evaluation result for each possible value of `nullableBooleanVar` = `true`, `false`, and `undefined`. (`null` will be treated as same as `undefined`).

| Variable `nullableBooleanVar` | Comparison `nullableBooleanVar === false` | Fixer Output `nullableBooleanVar ?? true` |
|-----------------------|-----------------------------------|---------------------------------|
| **_`true`_**                        | `false`                                          | `true`                                      |
| _**`false`**_                       | `true`                                           | `false`                                     |
| _**`undefined`**_              | `false`                                          | `true`                                      |

As shown above, we can see that the reported `Fixer Output` on the right-side will use expression that evaluate to different value from the original code on the middle.

| Variable `nullableBooleanVar` | Comparison `nullableBooleanVar !== false`| Fixer Output `!(nullableBooleanVar ?? true)` |
|-----------------------|-----------------------------------|---------------------------------|
| _**`true`**_                        | `true`                                          | `false`                                       |
| _**`false`**_                       | `false`                                         | `true`                                        |
| **_`undefined`_**              | `true`                                          | `false`                                       |

Again, as shown above, we can see that the reported `Fixer Output` on the right-side will use expression that evaluate to different value from the original code on the middle.

I can't advise about what the correct (expected) `Fixer Output` should be. The reason why I read this documentation in the first place is because I'm not sure how to fix my code. Yet the documentation gives incorrect information.

Also, I'm not sure whether this issue is also happen to your Fixer utility, since I'm not using it. I always fix lint error by hand ;-) or IDE.

Thanks.

### Affected URL(s)

https://typescript-eslint.io/rules/no-unnecessary-boolean-literal-compare/#fixer

**Comment by JoshuaKGoldberg** [comment]
Heh, yes, nice spot! I think it's a docs issue that's been there for a while, unnoticed. The _Comparison_ column is missing an `!( ... )` negation around the cases. See the tests for the rule:

https://github.com/typescript-eslint/typescript-eslint/blob/81c85193d27d2e7f6d12bc259088b9b73dbe1e8b/packages/eslint-plugin/tests/rules/no-unnecessary-boolean-literal-compare.test.ts#L187-L206

[If we add `!` to the _Comparison_ ("before") cases, they're equivalent to the fixer output](https://www.typescriptlang.org/play?#code/PTAEBMFMGMBsEMBOlTQPYDsDOAXUGBXWBAI1kgCE01z4MA1JALlBOto1AB98jYBuALAAoESFSZcoZFiI4KkAGZpkoALy9i8MpXaQ6jROrUbF8WFkhDh48aHsA9APwixYdNjwy5AMQCWAB6Q4OqgAISEWjpUNPoMSNa2YPagzq7CHlixAHRw+ogAFACU1iLKRgWZeABu5gQoaIqgANo4iPUANKBmFpBdBBhQin4YwQC6RaAA3iIpEp6sSiqQ-gGhYQW1sPXGpuaWJbMpVaDwijiQiKuhWztOTqBt9aXCc5k5sGgA5gXNtyj3UAAIgGQxGwSBXSB3lgOCwoBGkNA2RRBSOc3sJCWyGuJg0ZwuV0C6IxcwezSBWHgAFtIEwkVjyitAmMSaT7CwKeA-IpFJdIBgcPSuozlqsoQBaAB8SIJl1WrNeKSKY2yACs0CMCkDgUVDsIAL5AA):

```plaintext
[LOG]: "true results in same: true" 
[LOG]: "false results in same: false" 
[LOG]: "undefined results in same: true" 
```

Accepting a PR to fix the docs.
