### ISSUE TITLE
@typescript-eslint/parser does not exist in the npm registry

### ISSUE THREAD

**Issue by brieb** [typescript-eslint/typescript-eslint#69]
According to https://www.npmjs.com/package/typescript-eslint-parser and https://eslint.org/blog/2019/01/future-typescript-eslint `typescript-eslint-parser` is deprecated in favor of `@typescript-eslint/parser`. But, `@typescript-eslint/parser` is not published in the npm registry. Can you please publish `@typescript-eslint/parser`?

![image](https://user-images.githubusercontent.com/723547/51416746-b1170700-1b2f-11e9-82a2-56c8c2da15cd.png)

![image](https://user-images.githubusercontent.com/723547/51416858-313d6c80-1b30-11e9-8372-f6981f74aaa0.png)

Thank you for all of your work on this project! ❤️

**Comment by JamesHenry** [comment]
Yep, we were actually not expecting the announcement to drop exactly when it did 😄 

The first release from the monorepo will be live as soon as we update the docs, stay tuned!

**Comment by JamesHenry** [comment]
I have added https://github.com/typescript-eslint/typescript-eslint/issues/73

To make it clearer we are about to release the first version under the new scope

**Comment by JamesHenry** [comment]
v1.0.0 has been published, https://github.com/typescript-eslint/typescript-eslint/releases/tag/v1.0.0
