### ISSUE TITLE
Docs: Add unknown object suggestion for ban types 

### ISSUE THREAD

**Issue by isaacbatst** [typescript-eslint/typescript-eslint#6914]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Add to banned type `{}` a suggestion for a type meaning unknown object: `Record<string, unknown>`. Useful for when we know we are receiving an object, but validation of its properties is still needed.

### Affected URL(s)

https://typescript-eslint.io/rules/ban-types#options

**Comment by isaacbatst** [comment]
I have created a PR adding the text [here](https://github.com/typescript-eslint/typescript-eslint/pull/6913)

**Comment by bradzacher** [comment]
On modern versions of TS you can just use `object` instead of `Record<string, unknown>` - which is what we cover with the "unknown object" line.
