### ISSUE TITLE
Repo: ESLint warnings in useSandboxServices (react-hooks/exhaustive-deps)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6917]
### Suggestion

```plaintext
/home/runner/work/typescript-eslint/typescript-eslint/packages/website/src/components/editor/useSandboxServices.ts
Warning:   128:6  warning  React Hook useEffect has missing dependencies: 'colorMode', 'onLoaded', and 'props'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
```

Example: #6907 -> https://github.com/typescript-eslint/typescript-eslint/actions/runs/4703925812/jobs/8343076171?pr=6907

This is showing up in PRs. Can we fix for the rule's complaint without causing bugs in the playground?

**Comment by armano2** [comment]
sadly we have to eslint-disable it

**Comment by armano2** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/f1a0d78ddae418e13ae82f258d951690bb594eaf/packages/website/src/components/editor/useSandboxServices.ts#L150-L153
