### ISSUE TITLE
Rule proposal: Require tuple types to be readonly

### ISSUE THREAD

**Issue by JulesBlm** [typescript-eslint/typescript-eslint#6927]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

This rule would require all tuple types to be declared with the `readonly` type operator.

This proposal is inspired by [this tweet](https://twitter.com/mattpocockuk/status/1645710705532846082?s=20). Tuples can be mutated such that the type and value diverge. For example, tuples can receive array-mutating methods like `.push()` or `.pop()`  and their length can be modified by assigning to an arbitrary index like this.

```ts
type LatLon = [number, number]

const coords: LatLon = [52, 4];

let index = 2;

coords[index] = 400; 
// coords = [52, 4, 400];
```

Requiring `readonly` would prevent the length of the tuple being incorrectly modified.

### Fail Cases

```typescript
type XYZ = [number, number, number];

const numbers: readonly [number, number] = [50.85, 5.68];
```

### Pass Cases

```typescript
type XYZ = readonly [number, number, number];

const coords: readonly [number, number] = [50.85, 5.68];
```

### Additional Info

Adding `readonly` forbids all mutation, so there's some 'collateral damage' to this rule. It would also forbid mutating the elements of a tuple in place, like this:

```ts
const coords: LatLon = [52, 4];

coords[1] = 5;
```

Of course it's possible to work around this by creating a new tuple instead:

```ts
const coords: LatLon = [52, 4];

const newCoords: LatLon = [coords[0], 5]
```

Personally, I don't mind this given the benefits it bring but not everyone may agree.

**Comment by bradzacher** [comment]
https://typescript-eslint.io/linting/troubleshooting#how-can-i-ban-specific-language-feature

No need for a custom rule here - this can be achieved using the built-in rule as described in the FAQ.

Example https://typescript-eslint.io/play#ts=5.0.2&sourceType=module&showAST=es&code=PQKgUApgzgNglgOwC4AIEHsC0AnaTtwDGSEAJplAJ7ICGAHgFwoDaYKKARBNtuthwBo2KAN7D2HKBBgRifDkwUYkACgAqAZTWUADhADye7DSR9m6Iyb4oAvCgDkuGqXQIYlewF0AlCgB8KJpqAK46Mtp6guKcALbQUDQA5hAKnEihMlAoMcFQqABGEChOLm6UHMIAvmCeYCDAYGBIukVqtix5BAiJngDcTS0oAKrtJa7uHfiIPf1AA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA
