### ISSUE TITLE
Rule proposal: @typescript-eslint/typedef with arrowParameter or parameter but for const arrow functions

### ISSUE THREAD

**Issue by eau-de-la-seine** [typescript-eslint/typescript-eslint#6944]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Hello, `@typescript-eslint/typedef#parameter` only works for functions declared with the `function` keyword, but in our projects with use the following _elegant_ syntax:
```ts
const myFunction = (foo: FooType): BarType => myService.myMethod(foo);
```
instead of:
```ts
const myFunction = function (foo: FooType): BarType {
   return myService.myMethod(foo);
};
```

The problem is that `@typescript-eslint/typedef#arrowParameter` is painful because if forces every arrow functions to be typed, so:
```ts
myArray.filter(e => e).map(e => myService.myMethod(e, MY_CONST));
```
has to become:
```ts
myArray.filter((e: FooType): FooType => e).map((e: FooType): BarType => myService.myMethod(e, MY_CONST));
```
but this is totally unnecessary because `myArray` is already typed, we already know all the types at this point!

My proposal would be to have a mix between  `@typescript-eslint/typedef#parameter` and `@typescript-eslint/typedef#arrowParameter` so only const arrow functions requires parameter typing, maybe something like `@typescript-eslint/typedef#constArrowFunctionParameter`

Thanks

### Fail Cases

```typescript
empty
```

### Pass Cases

```typescript
empty
```

**Comment by bradzacher** [comment]
`typedef` is intended to be a transitional rule that is not enabled permanently. It's intended to help you migrate onto the `noImplicitAny` compiler option and then turned off.

We do not intend to make it more granular or more configurable.

**Comment by eau-de-la-seine** [comment]
hi @bradzacher , `noImplicitAny` seems to be the _ultimate solution_, but the problem is the project's dependencies, developers come from JavaScript and don't think about implementing generics in their libs, `noImplicitAny` is utopic.

Today with [eslint' func-style](https://eslint.org/docs/latest/rules/func-style) it's not even possible to force `func-style:expression` with the `function` keyword in order to make `@typescript-eslint/typedef#parameter` properly. `func-style:declaration` is already a problem since JavaScript functions can be overriden.

`eslint/typedef#constArrowFunctionParameter` was proposal to fill these lacks, to make `noImplicitAny` more real

**Comment by Josh-Cena** [comment]
> but the problem is the project's dependencies

Not sure why that would be relevant—are you linting your dependencies' declaration? You should be writing strict signatures yourself, and do what you can when calling external dependencies.

Could you give an example where you cannot turn on `noImplicitAny` and have to rely on `typedef`?
