### ISSUE TITLE
Enhancement: [rule-name] <a short description of my proposal>

### ISSUE THREAD

**Issue by tylerlaprade** [typescript-eslint/typescript-eslint#6952]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/array-type/

### Description

A 4th option for the two property objects that would enforce `array` for simple types and not enforce either syntax for other types. I like always using the clean `[]` syntax for simple types, but it's situational whether `Array<>` is merited for more complex types - am I nesting multiple levels of array? Is it being used as a generic that already has lots of nested `<>`?

### Fail

```typescript
const x: Array<string> = ['a', 'b'];
const y: ReadonlyArray<string> = ['a', 'b'];
const z: Array<MyType> = ['a', 'b'];
```

### Pass

```typescript
const x: string[] = ['a', 'b'];
const y: readonly string[] = ['a', 'b'];
const z: MyType[] = ['a', 'b'];
const a: (string | number)[] = ['a', 'b'];
const b: { prop: string }[] = [{ prop: 'a' }];
const c: (() => void)[] = [() => {}];
const d: Array<string | number> = ['a', 'b'];
const e: Array<{ prop: string }> = [{ prop: 'a' }];
const f: Array<() => void> = [() => {}];
```

### Additional Info

I suggest the name `array-simple-flex`, but any name is fine!

**Comment by bradzacher** [comment]
For stylistic rules we don't like to add options that make rules less consistent. Inconsistent style patterns are hard for people to understand and write code for, and it confuses people when lint rules should fire but don't.

This rule is also old (2016) and is very well established. This is the first request I know of to lessen the strictness of the rule, which implies that it's not something that the broader community agrees with.

For these reasons I'm going to reject this request for this project.
Thanks for filing!
