### ISSUE TITLE
[naming-convention] set filter.match to false not working with enum selector

### ISSUE THREAD

**Issue by liuliangsir** [typescript-eslint/typescript-eslint#6969]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.0.4&sourceType=module&code=MYewdgzgLgBApmArgWxgIQIYTgVQEoAyAokqgN4BQMMAggG4DmA4snBDALwwDkAFlFAAOEAFwB6MRkYA6BhlYRuAGgoBfIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6JgQwFtmBzWsgHsmAN0QtKw9GADa4bDkTRog6JAA08hVgXZIyREjL5V0yONhcNW3ftgAze5QAe0ubtsBRJpcg2FALqaHjhO8PhK0johUFwc+GQAFtL2HPAGwTFQ0Ii8iK4YkKwAqgBKADKsfjEAvpkekPaqcfhu-rYAyvhUxgAKHMhkaQDCA4jVIQHtNTZTEDM1QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
const enum BaseURLEnum {
  A = 'https://www.foobar.com',
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/naming-convention": [
      "error",
      {
        "selector": "enum",
        "suffix": [
          "Enum"
        ],
        "filter": {
          "match": false,
          "regex": "/URL/"
        },
        "format": [
          "StrictPascalCase"
        ]
      }
    ]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

No error reported

### Actual Result

Error reported

**Comment by Josh-Cena** [comment]
Not sure what your desired effect is. Per the docs: https://typescript-eslint.io/rules/naming-convention/#filter

> `match` - true if the identifier must match the regex, false if the identifier must not match the regex.

You are using `match: false` here, which means you expect enum names to NOT match the regex `/URL/`. The name here matches, so the rule reports.
