### ISSUE TITLE
[no-default-export] new rule

### ISSUE THREAD

**Issue by adrianhopebailie** [typescript-eslint/typescript-eslint#697]
Can we get a new rule that does the same as:
https://palantir.github.io/tslint/rules/no-default-export/

Related to #62 

Happy to try and put it together if it's not already on the roadmap. Anyone keen to assist please say so in this issue.

**Comment by bradzacher** [comment]
Hey thanks for the suggestion.
Please take a look at https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md

You'll see alternatives to tslint rules listed there. In this case there's a 1:1 replacement in another eslint plugin (eslint-plugin-import), so we won't be implementing this in this plugin.
