### ISSUE TITLE
Bug: TS1196 vs @typescript-eslint/no-explicit-any

### ISSUE THREAD

**Issue by eighty4** [typescript-eslint/typescript-eslint#6972]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

eslint-plugin-tslint

### Repro Code

```typescript
try {
  throw new Error('cannot divide by 0')
catch (e: any) {
  console.log(e.message)
}
```

### ESLint Config

```javascript
module.exports = {
    'env': {
        'browser': true,
        'es2021': true,
    },
    'extends': [
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
    ],
    'overrides': [],
    'parser': '@typescript-eslint/parser',
    'parserOptions': {
        'ecmaVersion': 'latest',
        'sourceType': 'module',
    },
    'plugins': [
        '@typescript-eslint',
    ],
    'rules': {
        'indent': [
            'error',
            4,
        ],
        'linebreak-style': [
            'error',
            'unix',
        ],
        'quotes': [
            'error',
            'single',
            {avoidEscape: true},
        ],
        'semi': [
            'error',
            'never',
        ],
    },
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "declaration": true,
    "esModuleInterop": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es2022",
    "strict": true
  },
  "include": [
    "lib/*.ts"
  ]
}
```

### Expected Result

Typescript eslint should not warn for use of `any` mandated by typescript for caught errors.

### Actual Result

TS1196 error occurs if you declare a caught exception as any thing other than `any` or `unknown`.

### Additional Info

TS1196 error occurs if you declare a caught exception as any thing other than `any` or `unknown`.  `e.message` can't be accessed unless it is declared as `any` like so:

```
try {
 ...
catch (e:any) {
  console.log(e.message)
}

```

This causes the ts plugin's default for `@typescript-eslint/no-explicit-any` to throw a warning. Seems like a Catch-22. Am I overlooking a configuration for `@typescript-eslint/no-explicit-any` that would break out of these conflicting rules?

### Versions

  "devDependencies": {
    "@types/node": "^18.16.1",
    "@typescript-eslint/eslint-plugin": "^5.59.1",
    "@typescript-eslint/parser": "^5.59.1",
    "eslint": "^8.39.0",
    "typescript": "^5.0.4"
  },

**Comment by Josh-Cena** [comment]
You should be doing this:

```ts
try {
 // ...
} catch (e: unknown) {
  if (e instanceof Error)
    console.log(e.message)
}
```

Using `any` is never sound.

**Comment by bradzacher** [comment]
> TS1196 error occurs if you declare a caught exception as any thing other than any or unknown.

This describes why the rule is valid here.

You have two choices - the safe option, `unknown`, or the unsafe option, `any`.

The rule is there to warn against making the unsafe choice.
If you are intentionally making the unsafe choice rather than being safe - then use a disable comment.
Otherwise make the safe choice and use `unknown`.

The same goes for any annotation anywhere - you can choose any type at all for an annotation and the rule will warn if you make the unsafe choice.

**Comment by eighty4** [comment]
Using `unknown` prevents accessing e.message which is something I've never not done on an exception. Littering every exception catch with a disable comment seems excessive. Would `@typescript-eslint/no-explicit-any` be able to support a configuration to suppress warnings on `catch(e: any)`?

**Comment by Josh-Cena** [comment]
@eighty4 No—this is unsafe. You should simply be adding an `if (e instanceof Error)` guard.

**Comment by eighty4** [comment]
I didn't think of that. Thought it was a game of cat and mouse between no-implicit-any and no-explicit-any, but it works with unknown and a type check. Thanks.

**Comment by Josh-Cena** [comment]
You can turn on `useUnknownInCatchVariables` and then avoid adding type annotations as well.

**Comment by bradzacher** [comment]
The danger of just doing `e.message` is that you're making the assumption that `e` is a non-nullish value.

However in JS it's legal to do `throw null`! There's also no guarantee that the caught value is an `Error`.

So Josh's advice is right - you want to use `unknown` and refine the value appropriately.
