### ISSUE TITLE
Docs: no-unnecessary-type-constraint should mention extending unknown

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6973]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

@MichaelDeBoey raises an excellent point in https://github.com/remix-run/remix/pull/6248#discussion_r1181130274:

> The docs are talking about `any` only, but this had `unknown` Does the same apply? If so, I guess it would be a good idea to update the docs?

Agreed - we should update the docs. They should mention when `extends unknown` is unnecessary, and include at least one or two examples in the code blocks. Accepting PRs!

### Affected URL(s)

https://typescript-eslint.io/rules/no-unnecessary-type-constraint/

**Comment by takanome-dev** [comment]
Time to learn more about eslint/ts-eslint rules :fire:, let me give it a a shot :gun:
