### ISSUE TITLE
Docs: Potentially confusing flow for enabling typed linting

### ISSUE THREAD

**Issue by zacharysyoung** [typescript-eslint/typescript-eslint#6982]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Related to #6826 and its PR #6919, I'm still getting the error, and still don't know what approach to take.

I tried the suggested "popular setup..." and ended up with the following:

**.eslintrc.cjs**

```javascript
/* eslint-env node */
module.exports = {
    extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
    ],
    parser: '@typescript-eslint/parser',
    parserOptions: {
        project: true,
        tsconfigRootDir: '.',
    },
    plugins: ['@typescript-eslint'],
    root: true,
    rules: {
        "semi": ["error", "always"]
    },
    overrides: [
        {
            extends: [
                'plugin:@typescript-eslint/recommended-requiring-type-checking',
            ],
            files: ['./**/*.{ts,tsx}'],
        },
    ],
};
```

**tsconfig.json**

```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "outDir": "out",
        "strictNullChecks": true
    },
}
```

**package.json**

```json
{
  "type": "commonjs",
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.59.2",
    "@typescript-eslint/parser": "^5.59.2",
    "eslint": "^8.39.0",
    "typescript": "^5.0.4"
  }
}
```

Did I misunderstand something in the `// ... the rest of your config ...` part of the CJS file?

You can see in the screenshot my .eslintr.cjs, and a foo.js in the out dir, are affected:

<img width="959" alt="Screenshot 2023-05-02 at 21 18 55" src="https://user-images.githubusercontent.com/945134/235832215-f6387827-6734-4c4e-8645-b51e12244243.png">

Maybe I'm not the right audience for this "Getting Started": I've had some success getting ESLint configured for some JavaScript development I've done (and will continue to do), and I just decide to take the plunge and try and port a small codebase to TypeScript and I wanted the comfort and security I've gotten with ESLint over in JS-Land, which lead me to this Getting Started.

Sincerely, and thank you.

### Affected URL(s)

- <https://typescript-eslint.io/getting-started>
- <https://typescript-eslint.io/linting/troubleshooting/#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file>

**Comment by JoshuaKGoldberg** [comment]
> Maybe I'm not the right audience for this "Getting Started"

No you're definitely the right audience 😄 and this is very good docs feedback, thank you for raising it!

> ended up with the following

ESLint was configured to run on your `.js` file, but is not included in any of your TSConfig file(s) _(just the one in this case)_. It's not included because TypeScript doesn't by default include `.js` files unless the [`allowJs`](https://www.typescriptlang.org/tsconfig#allowJs) or [`checkJs`](https://www.typescriptlang.org/tsconfig#checkJs) options are enabled. Does that make sense?

---

Aside: normally for these kinds of questions I'd request posting in our Discord. But this one smells of a gap and/or flaw in the docs - hence the visibility here.

**Comment by bradzacher** [comment]
This is fixed in v6 because in v6 the guide tells you to use the new disable type check config on js files IIRC

**Comment by JoshuaKGoldberg** [comment]
cc @zacharysyoung - is there anything more you'd want here now that v6 is out?

**Comment by JoshuaKGoldberg** [comment]
Closing as aged away. Thanks everyone!
