### ISSUE TITLE
Docs: what parserOptions.project relative to?

### ISSUE THREAD

**Issue by majiang** [typescript-eslint/typescript-eslint#6992]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/Typed_Linting.mdx

```
## Specifying TSConfigs

The `parserOptions.project` option can be turned on with either:

- `true`: to always use `tsconfig.json`s nearest to source files
- `string | string[]`: any number of glob paths to match TSConfig files relative to the

For example, if you use a specific `tsconfig.eslint.json` for linting, you'd specify:
```

Second item ends with "relative to the" without noun.  It seems to be "config file" but I'm not sure.

### Affected URL(s)

https://typescript-eslint.io/linting/typed-linting#specifying-tsconfigs

**Comment by bradzacher** [comment]
It should read "relative to `parserOptions.tsconfigRootDir`, or the CWD if that is not provided".
