### ISSUE TITLE
Docs: will type information also lead to new reports by default eslint rules?

### ISSUE THREAD

**Issue by kkmuffme** [typescript-eslint/typescript-eslint#7004]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

When using eslint-typescript with type information enabled and `eslint:recommended`

Will supplying type information also (possibly) report new errors with the eslint default (and/or @typescript-eslint/recommended) rulesets or is type information only relevant for @typescript-eslint rules that specifically require it (e.g. the rules in `@typescript-eslint/recommended-requiring-type-checking`)

### Affected URL(s)

https://typescript-eslint.io/linting/typed-linting/

**Comment by bradzacher** [comment]
No, type information is something that has to be explicitly built into the rule.

Thus it is only needed for rules that are marked as consuming type information.

We also don't conditionally consume type information - rules either don't use it at all or they require it and will be broken without it.

**Comment by JoshuaKGoldberg** [comment]
Technically, the page already does that in the first sentence:

> Some typescript-eslint rules

I'm not sure it makes sense to add this explicit notice. The question sometimes comes up, but strikes me as rooted in a misunderstanding of how ESLint rules actually work. 🤔

**Comment by JoshuaKGoldberg** [comment]
Yeah it's been a few months and this issue hasn't come up. Filing aways as non-actionable. Thanks for asking though!
