### ISSUE TITLE
Bug: [no-unsafe-member-access] does not respect `in` operator / check

### ISSUE THREAD

**Issue by JoshMcCullough** [typescript-eslint/typescript-eslint#7037]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

[Playground Example](https://typescript-eslint.io/play/#ts=5.0.4&sourceType=module&code=JYWwDg9gTgLgBAMwM6KhEcDkzMG4BQ+AhkgJ4B2AxogK5UzATlyUAWAppQNYCSCAYsAA27HkgDCQiEnYATABRgiMVgC44SGFGDkA5gEo4Ab3xw4I+AlnrBIgCLsklbWBjQ4AXjh1Z7BDrkCUzgtUmNgsytPOCIAdyJgSyQAOggwdnJFZVYAGiwiTH0CMwBfYMplNjh5digodSJyUkMTMzMAena4AFEAJV6AeV64Dih2OGTJiLhgBGrMSghfTBnmWqg4ADJNuHXkxd9PDy9MboAhAFUAZQBNQvC2trGYGihmBCIhGWK2ssf2L7jVqPEKsNCxXZ1H6lYJ-RA6T5CMLAsxxBKWWQAfn2Uhk8iKsMIZmer2YWho7AIZVMaMSLA43D4tlEElxcnkmHaShU7Tc7SQ6HY7X8IkKuCAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZoloBbRCIBGiaLT5kyKVBkjToHaJHBgAviG1A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkeAhpgObp4VTolHoAebANOBqR4sACYBXDO0idufSIJocSAWXFT0ASSJ4ssROzyYJ6JcIBmsTNHQBhYiWQk9uu-SdEmOgGJp0AHL08JxGJmZCtC6YyNBslMam5lEA1siIADLIAEZ2ABbo0ClhSZFQRLAAovDI8WCJ6EIAviBNQA)

### Repro Code

```typescript
import fs from 'fs';

async function checkIfFileIsClosed(path: string) {
  let fd: FileDescriptor = undefined;

  try {
    fd = await fs.open(path, 'a');
  }
  catch (err: any) {
    // ERROR HERE ...
    if ('code' in err && err.code === 'EBUSY') {
      return false;
    }
    else {
      throw err;
    }
  }
  finally {
    await fd?.close();
  }

  return true;
}

 await checkIfFileIsClosed('/path/to/some/file');
```

### ESLint Config

```javascript
module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
  ],
  parser: '@typescript-eslint/parser',
  plugins: [
    '@typescript-eslint',
  ],
  root: true,
  overrides: [
    {
      files: ['*.ts'],
      parserOptions: {
        project: 'tsconfig.json',
      },
      rules: {
        '@typescript-eslint/prefer-nullish-coalescing': 'error',
      },
    },
  ],
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "es2016",
    "module": "CommonJS",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "noEmit": true,
    "types": [
      "node"
    ]
  },
  "include": [
    "test"
  ]
}
```

### Expected Result

Using the `in` operator should make the this rule not apply:

```js
if ('x' in test && test.x === true) {
  // ...
}
```

### Actual Result

```
error    Unsafe member access .code on an `any` value    @typescript-eslint/no-unsafe-member-access
```

**Comment by Josh-Cena** [comment]
Just curious: why don't you use `err: unknown` here? It's much safer and can be properly narrowed.

**Comment by bradzacher** [comment]
The rule is driven by your types.
A variable typed as `any` does not refine to another type when you use `in` - it's still typed as `any`.
Which makes sense because the way that `in` refines the type is with an intersection - `T & {code: unknown}`. However any type intersected with `any` is still `any` - thus it does nothing.

Also note that your code is unsafe because in JS it is valid to throw a non object value. Using `in` on a non-object or null value will throw.

The correct and safe method for doing this is to use `unknown`, as Josh mentioned, and by first narrowing the type to an object eg `typeof err === 'object' && err != null && 'code' in err`.
