### ISSUE TITLE
Website: Playground doesn't capture undo state for auto-fixes

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7044]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Forking from #7041 (thanks @6XGate for filing!): if the playground auto-fixes code, such as from pressing <kbd>Cmd/Ctrl+S</kbd>, then you undo (<kbd>Cmd/Ctrl+Z</kbd>), your original code is lost. Only the fixed code remains. This must be particularly irksome for people who've been trained to keyboard-shortcut-save often!

1. Enter code into the playground that could be fixed
2. Trigger an auto-fix
3. Undo

Example playground: https://typescript-eslint.io/play#ts=5.0.1-rc&sourceType=module&code=DYUwLgBAbghsCuIBcECCAndMCeAeAzmOgJYB2A5gHwDcQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AQ2mncNqNPRREXAPbRI4MAF8QUoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Affected URL(s)

https://typescript-eslint.io/play

**Comment by armano2** [comment]
hmm, we can remove shortcut that i added with "fix all" command in #6529

https://github.com/typescript-eslint/typescript-eslint/blob/5166a00e1a903901c5bedbd7d57198fc0962061e/packages/website/src/components/editor/LoadedEditor.tsx#L233-L236

as for `ctrl/cmd + z` should work fine and undo stack is only cleared if you change extension (enable jsx)

**Comment by armano2** [comment]
@JoshuaKGoldberg sine v6 has been merged, if you find some time can you chheck if you can still reproduce this issue?

**Comment by JoshuaKGoldberg** [comment]
Confirmed, it's fixed - thanks!
