### ISSUE TITLE
Docs: v6 configs file for `strict-type-checked` is missing

### ISSUE THREAD

**Issue by takanome-dev** [typescript-eslint/typescript-eslint#7081]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

When setting up the configs to try out v6, I clicked [this](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/strict-type-checked.ts) link to see the configs for `strict-type-checked` but got a `404`

### Affected URL(s)

THIS URL LEADS TO A 404 PAGE -> https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/strict-type-checked.ts

**Comment by takanome-dev** [comment]
Encountered the same with `stylistic` configs -> https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/stylistic.ts

**Comment by bradzacher** [comment]
That would be because the configs aren't merged to main yet!

Though the v6 blog should probably link to the v6 branch.

https://github.com/typescript-eslint/typescript-eslint/blob/v6/packages/eslint-plugin/src/configs/strict-type-checked.ts

**Comment by takanome-dev** [comment]
Ah got it, sending a pr shortly for that :+1:
