### ISSUE TITLE
Bug: [no-inferrable-types, typedef] Rules can't works together 

### ISSUE THREAD

**Issue by kerambitls** [typescript-eslint/typescript-eslint#7085]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.0.4&sourceType=module&code=KYDwDg9gTgLgBAQwM4E8B2BjOAzArpmASwjTgHNgYAKAKDjgFsUAxQ4AGwBM4BeOAcn40AlAC44ABSgQGhJMAA8ANwiFOAPjgBvOnAwkkEdsAB07CGSpNWHTsJoBfIA&eslintrc=N4KABGBECmB2BukBcZQQpARgJwPYHcBnabZMAF2wFdoAacdSWXAE2jMpvvSmkICYADPwCMHatAYBfblAAOAQ2zFSKSAAFyATzl8AxtgCWc8gFo+AG0OxyAekXKSkWTAAe5OC0JkA2gwyW1uRI2NB6uAC2EZ7QLM7+8hZUAObWSJo6+kYm5oRWNrah4VExcQwAui5ySamw3ih+PBrauoQGxmaBNpAVLobJzKEACgrkHth1vgmQAHRdlHozAFbevQyQDioA8iaGuJMoaIxyeEth5GSztuRt+wBm-cuE+-FNYREKAGokhHuwlxZRnwLrIMM8qNg9NAACqZS4RVhUCzsaQuajI+qoaYZVrtHLzWzRCKYEimNhWCKGcamQjaZFTHgBbB4Uig9BHRlQCJI8iGfLsQ4JTmQcmGSnjS7ESmvTmMUIARyohlCABkFLTxDQhegZNqwdZksj+WQObKRdAKVSnGopYYZbKoAqlar1RcUJxJA6pNrvTxKtiWlkOrl8nYlNgFFpTIGGYyYMzcKztaammw7goeZdknASIY9Pa46EFCx9hYtFmc0Z8z6Ev6mjig-i8kFbNBXNU81TTHcqLA9Lz9qZQuQIbBo3C1CQWQXmpk2tlOs2Cm2O3ou0SSdhTAo9FDCL9MHyqeWGtr49O2RAU4x+oNYgBZaDkAAWrAAcgpopjGg6oOE6pw-aJgWwoAPpFmUDrlDWfpsrOuILiGLawJ+BqmP+8BwAO-ynsKU7AZeWIOpAxDIkBqhgD+xGBiqhgANYolBhEYHciYfG6lF6owIxtAoFgAMLqoxsrQZyuqcteYIWucwG4b+kDRC+rAgXGeiAvuQx4Lo2DaCpbywFQESPsSTjMYw8BKIYCiYMitEMT0TFcZArHYOxsbEXon4WoJxB6dx6qeQJQkOSJMHoHWjANvOwYEswpiUq4sTmAZESYueBEBnOeKLqGthxb2hAKHc0DxdAJlbjue5pfhSb1oG0VNrlJzQMVW7WGpVBsNVCa1ZF9XZUhBSBmm7mMDVKmSfIWkkNoAAiYSAhG2GanQTkOF5EruhIZmQOGBAjBGinWhQEhhRAEUYDgO4lbSWj0nJbw9SpkAiOQmDeIRk27RYFgEAAygatnWAKJ1amJtZwXF3IWLy1QlWVJhRvy35nuNn1OR8rhkCIO2YwAolsABiZCCGdYAXVAcUI9o3a9v2fyjUyF7Jk5fG-fgjNxnt+CE3T2GrFBZOiWA3pSEAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkeAhpgObp4VTokBMADF15AA04GpBJ5MyaHgByAV1SoAwgAt00ANZlKEuemE0o8WABMF6djATGiAKzIHRmWLDwARZJksA6APQlMaCERWjwAT0ROdgBtENEiUws4gF1HWhN1VEZ6AmJ2XX04yFg5d08fXwAjOTQTYMNITgBZU3MASSI8LFhEfMw9NKgAM1hA9CViEmRxdE6leimiJg6AMTR0GXp4KJ1+wobxSWk+gaKSDWREABlkStV1DRP0EQBfEBegA

### Repro Code

```typescript
export async function get(
    myField = ''
): Promise<void> {
    console.log(myField)
}
```

### ESLint Config

```javascript
module.exports = {
    env: {
        "browser": true,
        "node": true,
        "es2021": true
    },
    parser: '@typescript-eslint/parser',
    extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended'],
    plugins: ['@typescript-eslint'],
    ignorePatterns: [".eslintrc.js"],
    parserOptions: {
        project: './tsconfig.json',
        "ecmaVersion": "latest",
        "sourceType": "module"
    },
    rules: {
        '@typescript-eslint/member-delimiter-style': [
            'error',
            {
                multiline: {
                    delimiter: 'semi',
                    requireLast: true,
                },
                singleline: {
                    delimiter: 'semi',
                    requireLast: true,
                },
            },
        ],
        "@typescript-eslint/array-type": [
            "error",
            {
                default: 'generic',
                readonly: 'generic',
            }
        ],
        "@typescript-eslint/explicit-function-return-type": "error",
        "@typescript-eslint/explicit-member-accessibility": [
            "error",
            {
                ignoredMethodNames: ['constructor', '_read']
            }
        ],
        "@typescript-eslint/naming-convention": [
            "error",
            {
                selector: ['typeLike'],
                format: ['PascalCase'],
            },
            {
                selector: ['method', 'classProperty', 'enumMember', 'variableLike'],
                format: ['camelCase', 'PascalCase'],
            }
        ],
        "@typescript-eslint/no-mixed-enums": "error",
        "@typescript-eslint/no-unsafe-member-access": "error",
        "@typescript-eslint/prefer-includes": "error",
        "@typescript-eslint/typedef": [
            "error",
            {
                "propertyDeclaration": true,
                "parameter": true,
                "arrowParameter": true,
            }
        ],
        "brace-style": ["error", "1tbs", { "allowSingleLine": true }],
        "no-multiple-empty-lines": ["error", { "max": 1, "maxEOF": 0 }],
        "no-empty-function": ["error", { "allow": ["arrowFunctions"] }],
    },
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "es2022",
    "strictNullChecks": true,
    "module": "commonjs",
    "rootDir": "./src",
    "types": [
      "node"
    ],
    "declaration": true,
    "outDir": "./build",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

### Expected Result

Rules works together and doesn't shows any errors

### Actual Result

When I have code such this 

```typescript
export async function get(
    myField = ''
): Promise<void> {
    console.log(myField)
}
```

IDE shows me the error "ESLint: Expected a type annotation.(@typescript-eslint/typedef)"

When I change it and make type annotation such this

```typescript
export async function get(
    myField: string = ''
): Promise<void> {
    console.log(myField)
}
```

I receive the next error from IDE "ESLint: Type string trivially inferred from a string literal, remove type annotation.(@typescript-eslint/no-inferrable-types)" 

Reproduces in PhpStorm/GoLand

### Additional Info

IDEs info: 

- PhpStorm 2023.1.2 
- GoLand 2023.1.2

**Comment by bradzacher** [comment]
This is expected - not all rules are intended to be able to work together.
Each rule is entirely isolated and it's up to you to configure them such that they do not clash.

In particular these two rules are entirely at odds and can never work together. One enforces always annotating certain locations, no exceptions, and the other enforces removing obviously superfluous annotations.

`typedef` is a rule we ***strongly*** discourage people from using because it's like using a sledgehammer to crack a nut. It has no nuance and no contextual understanding builtin and it never will because its intended usecase it to help people migrate to stricter typings (eg to work towards turning on `noImplicitAny`) and then the rule disabled (eg once `noImplicitAny` is turned on).
