### ISSUE TITLE
Bug: no-unused-vars | 'variable is defined but never used' on defined variables too in NestJS when initialized with pnpm

### ISSUE THREAD

**Issue by slyofzero** [typescript-eslint/typescript-eslint#7095]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://github.com/slyofzero/nestjs-pnpm-issue

### Repro Code

```typescript
1. git clone https://github.com/slyofzero/nestjs-pnpm-
2. pnpm 
3. Open the project using 
4. Open any of the default module, controller, or service files
```

### ESLint Config

```javascript
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "tsconfig.json",
    "tsconfigRootDir": "./",
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint/eslint-plugin"],
  "extends": [
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended"
  ],
  "root": true,
  "env": {
    "node": true,
    "jest": true
  },
  "ignorePatterns": [".eslintrc.json"],
  "rules": {
    "@typescript-eslint/interface-name-prefix": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/no-explicit-any": "off"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": false,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
```

### Expected Result

The expected result would be to not get any of these errors on the defined variables, function, classes, and decorators. This is something that isn't happening when the project is generated using `yarn` as the package manager in the cli.

![image](https://github.com/typescript-eslint/typescript-eslint/assets/71858966/b61d1e15-a539-4186-a727-4844070f0142)

### Actual Result

When initializing a project using the nest-cli and choosing pnpm as the package manager, I get ESLint warnings because of the no-unused-vars rule in all of the app module, controller, and service files generated. This warning should only appeared for unused variables, functions, or classes that were defined but never called back again in the file and should not appear on exported items but in this case they are appearing for decorators and exported items.

![image](https://github.com/typescript-eslint/typescript-eslint/assets/71858966/63e348f7-1be0-4dea-9d13-d382e6988799)

**Comment by bradzacher** [comment]
Generally we look for isolated reproductions when reporting issues with the intent being that you remove the unrelated cruft to help expedite investigation.

By just taking the code from your repo and turning on our `no-unused-vars` lint rule in our playground - [I am unable to reproduce this](https://typescript-eslint.io/play/#ts=5.0.4&sourceType=module&code=JYWwDg9gTgLgBAbzgYQgOxlCAbbBTKAGjgHE94BfOAMyxDgHIABNPAZxgCs2B6AYwggQ6BgG44AKDihIsRHACCYMAGUCAN2B88cKrUGMAdDwCGyw2w1a8YyXHsSmqDFlwEAFAEoJeAB6z4PmwTNjZFZWdMHHwoRCk4ATQOKABXPhhodzAoYHUTGB0oPBMAE3RsAE84M1UrbQAucNqoTW1PeQoJeKYyGC94gHNyAAk8XAgvRuTgNAG4+3simBSoNDgYAAtgNkMatRbrQyGYUfGvUXjOzqA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tidmUQAmtAG4BDaKgyRE0aB2iRwYAL4hlQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA).

Are you able to create an isolated reproduction in our playground?

If not then it's likely not an issue with our tooling and is something else.

---

> I have updated to the latest version of the packages. 

You ticked this, and yet looking at your lock file you're pinned to v5.0.0 of our packages and v8 of eslint - all of which are over 2 years old.

https://github.com/slyofzero/nestjs-pnpm-issue/blob/main/pnpm-lock.yaml#L46-L54

Perhaps try updating your dependencies?
