### ISSUE TITLE
Bug: [naming-convention] Rule triggers when following external typing (such as object key when inlined in a function call)

### ISSUE THREAD

**Issue by sharky98** [typescript-eslint/typescript-eslint#7109]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.0.4&sourceType=module&code=MYewdgzgLgBAtgTwLIFMoAsQBMYF4YAUADgE4hEQBcMA3jEggEIggA2KAhmNQEYvtcA3DACWEBszaduMPlKEwAvgEo8APloBYAFAwYAen17jJ02ZMA9GAAEoCIigjASIolAC0j1iLBR9YDjgfAHN3UDAANxRfEXAYKBdg4JQSCBgONJQADwdgKBQsADodPXCIKULWEGDiMgplQR1FRu0dOwd6BAAVexQ8LV1OyQEZORGWvUMYK1tepxc3TwhvX39AkLDwKJi4hJEklLSMmGzc-KKS0XEmfmleW6Emlp0y2EQAeQB3MHeeACsUHlqAweh18DRLhIHjIEgBXFAAGkuUxm7UczlcHi8Pj8ASCYFC4W2UFiYHiiWSqQRslhsAAkuk4DAAGZsKqfELxdB9ABErJIwAKPPi9hCxUGYih8hkzI4rAgKCeOh0iFQGGwBDoUpG1Fl8sRV21d3J8KUDR0U3M0xsaPmmKWK1x6wJm0i0RJuwph2pPFpMAZgRZbJAHIJXN5-MFWGF7TFQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6JgQwFtmBzWsgHsmAN0QtKw9GADa4bDgDuHaE0gAaeQqwLskZIiRl8g6NMjFog0tCIatuyEVKoMc3Y4BGgwUg5qHBQBdTQ8cADNTLg58aXcwnAAFDmQyDngAYRTESEDsELycS0RwygAPOMK9SlRQhKhkAAtBBAATe3qoRpSO+sg0tTqEyFbKdqGwyEVKeHhchKC8gF8HRYgVpaA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
const myMethod = (props: { MyBoolean: boolean; isMyBoolean: boolean; }) => {
  //                        ^ @typescript-eslint/naming-convention triggers as expected.
  console.log(props);
};

type MyType = {
  MyBoolean: boolean;
  // ^ @typescript-eslint/naming-convention triggers as expected.
  isMyBoolean: boolean;
};

const myOwnObject: MyType = {
  MyBoolean: true,
  // ^ @typescript-eslint/naming-convention triggers, but I am following the "forced" typing.
  isMyBoolean: false
};

myMethod({ MyBoolean: false, isMyBoolean: true });
//         ^ @typescript-eslint/naming-convention triggers, but I am following the "forced" typing.
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/naming-convention": [
      "warn",
      { "selector": "property",
        "types": [ "boolean" ],
        "format": [ "PascalCase" ],
        "prefix": [ "is", "should", "has", "can", "did", "will" ]
      }
    ]
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

I expected line 13 and 18 to not trigger the naming convention rules, as they are following a previously (could be external) configured type.

### Actual Result

Line 13 and 18 trigger the naming convention rule.

### Additional Info

The playground do reproduce the situation, but we are in full control of both the typing and the object. I used the boolean rule from the [example](https://typescript-eslint.io/rules/naming-convention/#enforce-that-boolean-variables-are-prefixed-with-an-allowed-verb).

However, in my real use case I am providing an object as argument to a constructor of an external package. Obviously, I can't change the name of the object key since I don't control that package!

```ts
const forkTypeCheckingPlugin = new ForkTsCheckerWebpackPlugin({
    typescript: {
      mode: "write-references",
      build: true,
//    ^ trigger the naming-convention rule.
      diagnosticOptions: { semantic: true, syntactic: true },
//                         ^               ^ trigger the naming-convention rule.
    },
  });
```

I would think that any naming rules that target an element we cannot control (such as key of a typed object) should not be checked by this rule. Another option could be to reduce the severity by one if this case is seen (if the rule is set as "error", shown those cases as "warn").

**Comment by sharky98** [comment]
I am looking at the ESTree of my playground link if this could be something that is done. Here some idea (it is my first time looking at ESTree, so feel free to tell me I am missing the big picture here!).

* Do not run `naming-convention` rule on properties of a `init: ObjectExpression` inside a `VariableDeclator` if the `Identifier` has a `TSTypeAnnotation` assigned.
  * That way, object created without type annotation will still be validated against the rule.
* Do not run `naming-convention` rule on a `ObjectExpression` argument inside a `CallExpression` expression.
  * I don't think there could be an exception here, since no matter what CallExpression it is, the argument have no control on how the key are named.

**Comment by Josh-Cena** [comment]
Duplicate of https://github.com/typescript-eslint/typescript-eslint/issues/6120?

**Comment by sharky98** [comment]
I clearly didn't use the right keywords to find existing issues (but I was looking at bug, not enhancement)! Closing myself as duplicate.
