### ISSUE TITLE
Bug: [consistent-type-assertions] What to do when initializing a mapping object (empty)

### ISSUE THREAD

**Issue by xsjcTony** [typescript-eslint/typescript-eslint#7115]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.0.4&sourceType=module&code=KYDwDg9gTgLgBAYwgOwM7wIZShgngFQgFFkBXAWzgF44AefOUGYZAE1TnSgEtkBzAHwAKbs3KoAXHHwBtALoBKKQG84MgNJxe0uVM0BfagLjKAsACg4iFOjhRgHGssMYOqjVuQ69cfRYtWAGbQcEJIaPCiwJQQgVpiqAomAVZ2DjJR5HLU8dEpfuYp9jCkUF72qBb6QA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6MgeyeUuX0Ra0ipWgENkyRNHyUuqDAG1w2HFOgdokADTKVWFdkjjJ02UwDKRJOijjtug5A4AjAFaIy+ADKV+0UfAAKiSIAIISUjJyNkbw8BwA7mLItMSi-gC2iH6QDhAAvg4AusqF+UA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDAruuGAL4g9A

### Repro Code

```typescript
export const arrayToEnum = <T extends string>(items: T[]): { [K in T]: K } => {
  const res = {} as { [K in T]: K }

  for (const item of items) {
    res[item] = item
  }

  return res
}
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/consistent-type-assertions": [
      "error",
      {
        "assertionStyle": "as",
        "objectLiteralTypeAssertions": "allow-as-parameter"
      }
    ]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strict": true
  }
}
```

### Expected Result

I prefer this is not reported, however I don't want to set `objectLiteralTypeAssertions` to `allow`, since most of the time I don't want to use `as`.

Is there any other way I can workaround this? Without using `eslint-disable` comment of course... Is their any better way to write this simple util function's typing?

It's the same even if I use `arr.reduce`, I still needs to assert it, but at least it's not reporting because of `allow-as-parameter`, but what if I just want to use normal for of loop here?

```ts
export const arrayToEnum2 = <T extends string>(items: T[]): { [K in T]: K } => {
  return items.reduce(
    (obj, item) => {
      obj[item] = item
      return obj
    },
    {} as { [K in T]: K }
  )
}
```

### Actual Result

It's reporting error, but is expected. Looking for workaround other than `eslint-disable`

**Comment by Josh-Cena** [comment]
This is a perfect case for a disable comment. ESLint is preventing you from doing unsafe operations. Namely, `{}` is NOT a valid `{ [K in T]: K }` because it is missing the keys of `T`. You are only doing this assertion because you know that you are initializing those keys without doing any read operation. You could easily do something unsafe:

```ts
const arrayToEnum = <T extends string>(items: T[], key: T): { [K in T]: K } => {
  const res = {} as { [K in T]: K }
  const value = res[key].toUpperCase();
  //    ^?

  for (const item of items) {
    res[item] = item
  }

  return res
}
```

TypeScript thinks the `res[key]` is a string, while in effect it is `undefined`.

**Comment by xsjcTony** [comment]
@Josh-Cena Yeah I can see it's a good idea to use disable comment in this special case, but I'm wondering whether `Object.fromEntries` is more performant?
From the benchmark, my way seems more performant but I'm not quite sure...
https://www.measurethat.net/Benchmarks/Show/9268/0/objectfromentries-vs-reduce

**Comment by bradzacher** [comment]
Sure it's 10x faster... but even with an array of 10k entries that's still worst case 3ms for `Object.entries`.

If you're doing that every frame then sure - use `reduce`, otherwise don't bother thinking about it.
Write the cleaner/clearer code and don't get hung up on speed unless your app has perf hitches.
