### ISSUE TITLE
Remove parseWithNodeMaps

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7119]
## Overview

Copying @fisker's https://github.com/typescript-eslint/typescript-eslint/issues/6760#issuecomment-1596451396:

> I want give an update here, we (Prettier) can remove all the invalid node checks after upgrade to latest v6, so we can now use `parse` dirctly instead of `parseWithNodeMaps`. I think this method was added because Prettier need it at that moment, feel free to remove it if you think it's unnecessary to keep.

We always like deleting unused code! Just checking on Sourcegraph, https://sourcegraph.com/search?q=context:global+parseWithNodeMaps+-repo:.*typescript-eslint.*+-file:.*node_modules.*&patternType=standard&sm=1&groupBy=repo shows exactly one other runtime use:  [brodybits/prettierx](https://sourcegraph.com/github.com/brodybits/prettierx) › [src/language-js/parser-typescript.js](https://sourcegraph.com/github.com/brodybits/prettierx/-/blob/src/language-js/parser-typescript.js): a fork of prettier not updated since 2021. cc @brodybits 

I think it's safe to remove `parseWithNodeMaps`. Filing this issue under triage to check with @typescript-eslint/triage-team.

**Comment by bradzacher** [comment]
This API was added solely for prettier because they had some usecases for checking the source code tokens that we didn't explicitly encode in our AST (but was available via the TS AST). So we can remove this.
