### ISSUE TITLE
Enhancement: [prefer-string-starts-ends-with] Option to ignore [0] === cases?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7140]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/play/#ts=5.0.4&sourceType=module&code=CYUwxgNghgTiAEYD2A7AzgF3gNyhAriAFzyYwCWKA5gNwBQd5AZvABS4EgDaADALrwAvMJx5CvPgDoMSAKoAHeSBgBhKGhCsAlFvgBvOvHgB6Y-EkW6AXwbM2HQpMywMaAOrkMAC3Zju-aTlFZTUNbR19QxMzC0lrOiA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WluXxUmAc374AhtHzJ6TACYyA7pXwALdFF7QA9tEjgwAXxCGgA

### Description

Coming over from https://github.com/typescript-eslint/typescript-eslint/pull/7138#discussion_r1241171363: when checking whether a string's `[0]` member equals a modification of `[0]`, the rule's preference ends up being even more code:

```ts
declare const value: string;

if (value[0] === value[0].toUpperCase()) { /* ... */ } // before

if (value.startsWith(value[0].toUpperCase())) { /* ... */ } // after
```

Agreeing with @bradzacher:

> I actually think that the previous form is clearer for this specific case.
> [It's also substantially faster (not that it matters at the this speed... but it is twice as fast - ~1.2B ops/s vs ~2.4B ops/s)](https://jsbench.me/buljbfvcn4/1). 
>
> I wonder if we should add an option to skip this case from the rule?

It's not yet clear to me how we would categorize and describe "this case". Maybe it's that we don't want to flag cases that are just checking whether `value[0] ===` something? In that case, maybe the option would be named something like `checkFirstElementEquality`?

### Fail

```typescript
n/a
```

### Pass

```typescript
n/a
```

**Comment by Josh-Cena** [comment]
I would avoid against `[0]` because it doesn't deal with astral characters. `.toUpperCase()` also feels "icky" but I think it's generally fine. I would recommend using regex though. Consider the following case:

```js
const adlam = "𞤢𞤣𞤤𞤢𞤥";‎ // All lowercase: "adlam"
console.log(adlam[0]); // '\uD83A'; only a surrogate pair, not a character
console.log(adlam[0] === adlam[0].toUpperCase()); // true??
console.log(/^\P{Lowercase_Letter}/u.test(adlam)); // false; looks better
```

**Comment by bradzacher** [comment]
TIL `𞤢𞤣𞤤𞤢𞤥` is actually a valid JS Identifier - but tools really go wonky with it cos it's RTL.
TBH in our rules I think KISS is fine.

Also worth noting that the regex approach is much, much, much slower.
Testing on my m1 on chrome:
- index -> 705M ops/s
- `.startsWith` -> 544M ops/s -> 23% slower
- regex -> 65M ops/s -> 90% slower

I think that in some codebases you're going to want to be i18n friendly and use the regex approach - but in a lot of cases the index approach is going to be just fine.

**Comment by Josh-Cena** [comment]
So what's the scope here? Here's my attempt:

`checkFirstElementEquality`: ignore the case where an equality expression is used and both sides reference `string[0]`.

Because I assume we still want to report `string[0] === "f"`. Do we want to report `string[0] === string[1]`?

**Comment by bradzacher** [comment]
Breaking it down - we really have a two cases here.
1) `string[0] === character`
    - maybe a separate option for codebases that only cares for single-code characters?
    - probably want to refine the error message to highlight that it's not safe for i18n contexts.
2) `string[0] === string[0].(toUpperCase|toLowerCase)()`
    - maybe a separate option for codebases that only cares for single-code characters?
    - probably want to refine the error message to highlight that it's not safe for i18n contexts and provide the regex as an alternative.
