### ISSUE TITLE
Bug: [no-unsafe-assignment] unknown ignored from JSDoc

### ISSUE THREAD

**Issue by kkmuffme** [typescript-eslint/typescript-eslint#7144]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.1.3&sourceType=module&code=LAKAxg9gdgzgLgAgB4C4EFcoGsoQO5QIC8CAUgMoDyAcgHQAOAhgE4wCmAFAOQBmEEXAJQBuUEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolp9kySgHMmAW0Qt0URNGgdokcGAC+ITUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
const x: unknown = JSON.parse('foo');
```

When doing the same in a JS file with JSDoc, you'll get an error: "Unsafe assignment of an `any` value"
(however it works fine for tsc itself, as it will report x as unknown instead of any)

```js
const x = /** @type {unknown} */ (JSON.parse('foo'));
```

In JS only this works without error

```js
const /** @type {unknown} */ x = JSON.parse('foo');
```

Which is a problem if it's not a const but a let or an object property assignment (e.g. foo.bar = JSON.parse() ). There is no way to fix this error/change the type to unknown.

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unsafe-assignment": "error",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
  }
}
```

### Expected Result

No error in JS when using @type unknown

### Actual Result

Error

**Comment by bradzacher** [comment]
I ma unable to repro this in the playground
[v6 playground with extension support](https://v6--typescript-eslint.netlify.app/play/#ts=5.0.4&fileType=.js&code=FAYw9gdgzgLgBADzgXjgegFQbgARgTwAcBTOAbwFcIBrCMAdwgF84M04AKAKQGUB5AHIA6QgEMATlGIcA5ADMwYGQEplAbmBA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolp9kySgHMmAW0Qt0URNGgdokcGAC%2BITUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)
