### ISSUE TITLE
Repo: CI / Website tests (pull_request) fails on PRs from forks

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7168]
### Suggestion

Example: https://github.com/typescript-eslint/typescript-eslint/pull/7167 -> https://github.com/typescript-eslint/typescript-eslint/actions/runs/5480558418/jobs/9983914931?pr=7167

```plaintext
/home/runner/work/typescript-eslint/typescript-eslint/node_modules/@actions/core/lib/core.js:106
        throw new Error(`Input required and not supplied: ${name}`);
        ^
```

@JamesHenry I'm up-to-date from `main` and still getting this. Are we blocked on anything?

**Comment by JamesHenry** [comment]
We discussed this on discord and none of us could figure out why the `if` wasn't causing it to skip the task on forks as intended...

We can't hit the Netlify API without an auth token, and we can't use the auth token without it being a secret naturally, so we are kind of stuck with the tests only running on netlify on main and other origin branches

**Comment by JoshuaKGoldberg** [comment]
A few thoughts on approaches:

* Less work, not as good result: at this point I'd be satisfied just disabling that on branches other than main, and filing a followup to get it working on others & on fork PRs...
* More work, better result: maybe we can use a different strategy than Netlify if from a community PR?
* Experimental: maybe [`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) (https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) would help?
