### ISSUE TITLE
Docs: [prefer-readonly-parameter-types] mention problem with 3rd party interfaces

### ISSUE THREAD

**Issue by ddubrava** [typescript-eslint/typescript-eslint#7179]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Hi! It's not clear at all that this rule requires deep readonly. Since you can't change 3rd party libraries, while `DeepReadonly` is not a silver bullet, you waste time figuring out why this rule emits errors. So I would suggest improving documentation and mentioning the limited usage (actually it doesn't work) with external libraries.

<img width="889" alt="Screenshot 2023-07-10 at 16 26 50" src="https://github.com/typescript-eslint/typescript-eslint/assets/22116465/a3baa152-c897-46e1-9c8a-45175a80b120">

<img width="877" alt="Screenshot 2023-07-10 at 16 26 42" src="https://github.com/typescript-eslint/typescript-eslint/assets/22116465/12b9c1e7-eb56-46c5-ab5e-c32cedeeaf6d">

### Affected URL(s)

https://typescript-eslint.io/rules/prefer-readonly-parameter-types/

**Comment by bradzacher** [comment]
It works for most things - the cases it doesn't support are rarer. Do you have an example of a type that isn't possible to make readonly?

Whilst we don't explicitly mention it - it is definitely strongly implied by the `allow` option which allows you to ignore specific types from libraries.
https://typescript-eslint.io/rules/prefer-readonly-parameter-types/#allow

**Comment by ddubrava** [comment]
> It works for most things - the cases it doesn't support are rarer. Do you have an example of a type that isn't possible to make readonly?
> 
> Whilst we don't explicitly mention it - it is definitely strongly implied by the `allow` option which allows you to ignore specific types from libraries. https://typescript-eslint.io/rules/prefer-readonly-parameter-types/#allow

Well, I don't understand how I can make all properties in an external interface readonly. Won't it break anything? I believe that `allow` solves the issue, but it's very painful to add all external libraries to this option.

And I don't understand why it doesn't work in these cases

<img width="774" alt="Screenshot 2023-07-11 at 11 51 32" src="https://github.com/typescript-eslint/typescript-eslint/assets/22116465/2c8af667-619d-4b82-bf1b-e46cded33d7c">

<img width="812" alt="Screenshot 2023-07-11 at 12 18 54" src="https://github.com/typescript-eslint/typescript-eslint/assets/22116465/2729db43-01e6-4e40-9df7-793168a6369e">

<img width="1180" alt="Screenshot 2023-07-11 at 12 26 20" src="https://github.com/typescript-eslint/typescript-eslint/assets/22116465/db194169-4207-484b-b4e9-cecbce69a91e">

**Comment by bradzacher** [comment]
@ddubrava please don't send screenshots of code - first of all other users cannot find their content in search and second of all nobody can reproduce your issue from a screenshot without hand-typing all of the code.

Instead - use our playground - https://typescript-eslint.io/play/

**Comment by bradzacher** [comment]
Unfortunately your `DeepReadonly` utility is not infallible - there are some cases that it cannot truly mark as readonly. As you saw - tuples and arrays it isn't good at.

There are 3rd party options out there - like [`type-fest`](https://www.npmjs.com/package/type-fest) which supply the [`ReadonlyDeep` type](https://github.com/sindresorhus/type-fest/blob/main/source/readonly-deep.d.ts) - which should cover more cases and do a much better job.

However even then there are still cases it won't necessarily get right.

This is the point of the [`allow` option](https://typescript-eslint.io/rules/prefer-readonly-parameter-types/#allow) I mentioned earlier - it allows you to configure the rule to ignore certain types that you know are impossible to make truly readonly.

**Comment by ddubrava** [comment]
> Unfortunately your `DeepReadonly` utility is not infallible - there are some cases that it cannot truly mark as readonly. As you saw - tuples and arrays it isn't good at.
> 
> There are 3rd party options out there - like [`type-fest`](https://www.npmjs.com/package/type-fest) which supply the [`ReadonlyDeep` type](https://github.com/sindresorhus/type-fest/blob/main/source/readonly-deep.d.ts) - which should cover more cases and do a much better job.
> 
> However even then there are still cases it won't necessarily get right.
> 
> This is the point of the [`allow` option](https://typescript-eslint.io/rules/prefer-readonly-parameter-types/#allow) I mentioned earlier - it allows you to configure the rule to ignore certain types that you know are impossible to make truly readonly.

Ok, many thanks for explaining all of this to me. So, don't you think it's worth summarizing this and adding key points to the documentation?

**Comment by JoshuaKGoldberg** [comment]
I think it'd make sense to note in the docs:

* Third party types are often not readonly
* Utils such as `type-fest` can be useful
* The tradeoffs in this thread

**Comment by ddubrava** [comment]
> I think it'd make sense to note in the docs:
> 
> * Third party types are often not readonly
> * Utils such as `type-fest` can be useful
> * The tradeoffs in this thread

I can work on this
