### ISSUE TITLE
@typescript-eslint/utils imports no longer detect types in moduleResolution: node(10) in 6.0.0

### ISSUE THREAD

**Issue by andreashuber69** [typescript-eslint/typescript-eslint#7185]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

After upgrading `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` to 6.0.0 (from 5.61.0) it appears that `@typescript-eslint/utils` can no longer be found, see Repro for details.

### Reproduction Repository Link

https://github.com/andreashuber69/eslint-config

### Repro Steps

```
git clone https://github.com/andreashuber69/eslint-config.git
cd eslint-config
npm i
npm run lint
```

The above steps produce no error (5.61.0 packages are installed). Now upgrade to 6.0.0 and lint again, as follows:

```
npm i @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest
npm run lint
```

I get the following errors:
```
/home/a/git/eslint-config/test/getSeverities.ts
   6:18  error  'any' overrides all other types in this union type  @typescript-eslint/no-redundant-type-constituents
   6:31  error  'any' overrides all other types in this union type  @typescript-eslint/no-redundant-type-constituents
  14:13  error  Unsafe return of an `any` typed value               @typescript-eslint/no-unsafe-return
  19:11  error  Unsafe assignment of an `any` value                 @typescript-eslint/no-unsafe-assignment
  29:13  error  Unsafe return of an `any` typed value               @typescript-eslint/no-unsafe-return

/home/a/git/eslint-config/test/typescriptEslintRules.ts
   5:69  error  Unsafe return of an `any` typed value       @typescript-eslint/no-unsafe-return
   5:81  error  Unsafe member access [0] on an `any` value  @typescript-eslint/no-unsafe-member-access
   8:11  error  Unsafe assignment of an `any` value         @typescript-eslint/no-unsafe-assignment
  14:5   error  Unsafe return of an `any` typed value       @typescript-eslint/no-unsafe-return
```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `6.0.0` |
| `@typescript-eslint/parser`            | `6.0.0` |
| `@typescript-eslint/scope-manager`     | `6.0.0` |
| `@typescript-eslint/typescript-estree` | `6.0.0` |
| `@typescript-eslint/type-utils`        | `6.0.0` |
| `@typescript-eslint/utils`             | `6.0.0` |
| `TypeScript`                           | `5.1.6` |
| `ESLint`                               | `8.44.0` |
| `node`                                 | `18.16.1` |

**Comment by andreashuber69** [comment]
> Well that was fast

You were even faster. Kudos to you for the fastest response I ever got!

**Comment by JoshuaKGoldberg** [comment]
Pulling a suggestion from #7186's body: since you're stuck on the old deprecated TSConfig, I'd recommend setting `"moduleResolution": "node16"` (or similar) in your TSConfig. `"moduleResolution": "node"`, which is set in `"@tsconfig/node-lts-strictest/tsconfig.json"`, is actually an alias for `"node10"` which is very old and crusty.

```diff
{
  // node-lts-strictest is deprecated in favor of using an array to combine node-lts and strictest but doing so
  // currently leads to problems with the eslint-plugin-import package, see
  // https://github.com/import-js/eslint-plugin-import/issues/2751
  "extends": "@tsconfig/node-lts-strictest/tsconfig.json",
  "compilerOptions": {
+    "moduleResolution": "Node16",
  },
}
```

Oh the joys of Node package resolutions!

**Comment by andreashuber69** [comment]
Thanks, that would have taken me much longer to figure out. I'll report that as a bug in @tsconfig/node-lts-strictest. Even though it's deprecated, `"moduleResolution": "node"` did not ever make sense for an lts config.

**Comment by JoshuaKGoldberg** [comment]
Sorry, just reopening this for anybody else who has the same issue. +1 to filing the issue on the preset!

**Comment by JoshuaKGoldberg** [comment]
Copying from https://github.com/typescript-eslint/typescript-eslint/pull/7186#issuecomment-1631373279 - I forgot about this convoluted chain of versioning shenanigans:

* We dropped support for Node <=14
* As a part of ☝️ we removed the entries in our `package.json`s that helped old Node versions resolve package entries ("module resolution")
* TypeScript respects Node module resolution algorithms, which means we essentially dropped _types_ module resolution support for older versions of Node
* TSConfig `"moduleResolution": "node"` is actually an alias of `"node10"`, which is EOL - you should switch to `"node16"` or `"nodeNext"` or whatever is most accurate for your project per https://www.typescriptlang.org/tsconfig#moduleResolution

This is actually working as intended. The workaround in that last list item is our recommended user-land fix. 👍

**Comment by christianvuerings** [comment]
@JoshuaKGoldberg Thanks for the context and potential workaround.

In our repo we can't yet use `"modeResolution": "node16"` or `"modeResolution": "nodenext"` since it breaks Next.js: https://github.com/vercel/next.js/issues/46078

Is there any other way we can upgrade to `@typescript-eslint` v6? It looks like some folks are using the `tsconfig.json` `paths` setting: 
https://github.com/sindresorhus/got/issues/2267#issuecomment-1582075262
