### ISSUE TITLE
Enhancement: [no-unsafe-enum-comparison] Add option to allow comparing left-side primitive values with right-side enum values

### ISSUE THREAD

**Issue by DanielRose** [typescript-eslint/typescript-eslint#7219]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-unsafe-enum-comparison/

### Description

In our codebase, in various places we have values which are typed as string. This can be due to control/component limitations, or because they are coming from the database, or because they are partially user-defined (ie. there are standard values and custom values).

We place the "known values" or "standard values" in a string enum, and do comparisons with these known values to handle them, with the user-provided value on the left side and the known enum value on the right side.

This is now an error due to `no-unsafe-enum-comparison`. At the same time, this rule has found places where we did incorrect comparisons, so we don't want to disable the rule.

The proposal would be to add an option to allow a comparison between a primitive value (string/number) on the left side, and an enum value of the same type on the right side. Any other comparisons would still be an error.

### Fail

```typescript
enum KnownVegetable {
  Asparagus = 'asparagus',
}

declare let vegetable: KnownVegetable;
declare let apiVegetable: string;

vegetable === 'asparagus';
KnownVegetable.Asparagus === apiVegetable; // still not allowed: primitive value must be on left side
```

### Pass

```typescript
enum KnownVegetable {
  Asparagus = 'asparagus',
}

declare let vegetable: KnownVegetable;
declare let apiVegetable: string;

vegetable === KnownVegetable.Asparagus;
apiVegetable === KnownVegetable.Asparagus; // now allowed: primitive value on left side compared with enum value on right side
```

**Comment by bradzacher** [comment]
I think this is a very niche usecase - wanting it to only pass if and only if it's on the LHS is very specific.
I understand the request - but I don't think it makes sense for us to implement it here as there likely aren't many users that use this specific style (i.e. fails the broad applicability test).

---

I wonder if you can do "better" here type-wise by converting a string to the enum with a safe type conversion on the value before the check?
EG
```ts
enum KnownVegetable {
  Asparagus = 'asparagus',
}

function asKnownVegetable(str: string): KnownVegetable | null {
  switch (str) {
    case KnownVegetable.Asparagus:
        return str as KnownVegetable;

    default:
        return null;
  }
}
```

This way you can sanitise your data to coerce it to a valid value before it progresses through your code.

Depends on what your DB layer looks like and how easy it is to move this upstream to the fetching layer, I guess. With most ORMs you should be able to add conversion functions on individual fields to correct their type.

---

Or perhaps this is a good candidate for an `as` to explicitly document the assumption that the string is supposed to be of the enum type whilst also satisfying the lint rule:

```ts
(vegetable as KnownVegetable) === KnownVegetable.Asparagus;
```

Alternately a disable comment would serve the same purpose albeit more verbosely

```ts
// eslint-disable-next-line @typescript-eslint/no-unsafe-enum-comparison -- vegetable should be a KnownVegetable
vegetable === KnownVegetable.Asparagus;
```

**Comment by DanielRose** [comment]
Those are good points. Broadly speaking we have two cases:

1. The value is actually an enum value, but due to various reasons, it is not typed as such
    * In that case, we could do a conversion, such as the `asKnownVegetable` function
2. The value is (partially) user-defined, with some known standard values (grouped in an enum), but also could have custom values
    * In that case, we could use an `as` assertion when comparing with a standard enum value

If you think this option is too niche, feel free to close this ticket.
