### ISSUE TITLE
Repo: Readme should be updated now that v6 has been released

### ISSUE THREAD

**Issue by rubiesonthesky** [typescript-eslint/typescript-eslint#7233]
### Suggestion

Readme is little bit outdated now that v6 has been released. The mention about v6 documentation site could be removed. 

I also noticed that link [canary release](https://main--typescript-eslint.netlify.app/maintenance/versioning) does not work. I guess it should be pointing to `https://main--typescript-eslint.netlify.app/users/versioning` ?

**Comment by JoshuaKGoldberg** [comment]
Ha, good callout - something to note for #6761.
