### ISSUE TITLE
Configs: no-return-await

### ISSUE THREAD

**Issue by kkmuffme** [typescript-eslint/typescript-eslint#7235]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

None of the issue suggestion really fit this, so I went with Configs. Anyway:

Given https://github.com/eslint/eslint/issues/17345 (with fix https://github.com/clshortfuse/eslint/commit/3ecf6b9546d9a50abf2940b5616e98e10f43b2ac) this should be updated here https://eslint.org/docs/latest/rules/no-return-await too

In fact, I think changing https://typescript-eslint.io/rules/no-floating-promises/ should be changed to not allow "return"; this would be a simple(r) way than adding a new rule "return-await" or similar, to enforce the use of await when returning. Possibly adding this as a configuration option to that rule, that should be enabled by default?

**Comment by bradzacher** [comment]
https://typescript-eslint.io/rules/return-await/

We already have a type-aware extension rule for `no-return-await` that can enforce for or against returning an `await`

**Comment by bradzacher** [comment]
Ultimately it is a stylistic preference as to whether or not you do it - so best case it goes into `stylistic-type-checked`.
We'll assess this when we do the next major - thanks!

**Comment by bradzacher** [comment]
> but the performance is slightly better

it's like saying "if you unroll your loops it's faster" - the impact would be unnoticeable in all but the most perf critical situations (but for those you wouldn't be using JS...)

It's near enough that it is ultimately a stylistic choice.

> stacktrace is better too

Some prefer it, some prefer it next to the original call.
Both have merits depending on who you talk to.
