### ISSUE TITLE
Bug: [non-nullable-type-assertion-style] autofix does not account for `await`

### ISSUE THREAD

**Issue by G-Rath** [typescript-eslint/typescript-eslint#7243]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=CYUwxgNghgTiAEAzArgOzAFwJYHtVK1WABEoMoAKASgC54AFGHAWywGcQAeNjGQgc3gAfeKmQQIAPgDcAWABQCsHh7xmAD3gBeeFDYBPdPGp1GLdlx59U-SdrsBvBfHhwMyGPgpQA7lCwYBESk5NRUumzwVgJy8gC%2BQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6JgeydqYXgEMARklpFStfsmSJo%2BSl1rIiSdFBnQO0SODABfELqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```typescript
declare function findData(): Promise<string | null>;

const mx = async () => {
  (await findData()) as string;
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/non-nullable-type-assertion-style": "error"
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

```
declare function findData(): Promise<string | null>;

const mx = async (): Promise<string> => {
  return (await findData())!;
}
```

### Actual Result

```
declare function findData(): Promise<string | null>;

const mx = async (): Promise<string> => {
  return await findData()!;
}
```

**Comment by JoshuaKGoldberg** [comment]
👍 Looks like another case where precedences aren't being respected. This should probably be fixed using `util.getOperatorPrecedence`.
