### ISSUE TITLE
Status of ported TSLint rules

### ISSUE THREAD

**Issue by ulrichb** [typescript-eslint/typescript-eslint#726]
First, sorry for using an issue for my question.

I didn't find anywhere a documentation of the status of the ported TSLint rules.

Is there any? If no, then this issue is a feature request for extending the table on the [README page](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin) with an "equivalent TSLint rule" column + list all missing TSLint rules.

**Comment by JamesHenry** [comment]
They are covered here: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md

**Comment by ulrichb** [comment]
![facepalm](https://i.kym-cdn.com/entries/icons/original/000/000/554/picard-facepalm.jpg)

Thx!!
