### ISSUE TITLE
Docs: Add explanation of common narrowing woes to no-unnecessary-condition

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7264]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Following #7210 and its trail of duplicate issues, @marekdedic is right that many users get tripped up by the rule's exposing TypeScript's potentially confusing nuances around type narrowing. +1 to https://github.com/typescript-eslint/typescript-eslint/issues/7210#issuecomment-1640647549 for mentioning this in the rule's docs.

A couple of notes:
* I wrote an article explaining it here: https://www.learningtypescript.com/articles/objects-functions-and-type-narrowing. No worries if you don't like that explanation 😄 
* This makes sense to me as maybe a `:::tip`/`:::note`/etc. somewhere in the rule's docs page? 🤷 not too opionionated

### Affected URL(s)

https://typescript-eslint.io/rules/no-unnecessary-condition/

**Comment by marekdedic** [comment]
Thanks, @matwiem !
