### ISSUE TITLE
Base rule extension: no-implicit-coercion errors on string + nonString and similar expressions

### ISSUE THREAD

**Issue by rhiz0-eth** [typescript-eslint/typescript-eslint#7265]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+base+rule+extension%22) and found none that match my proposal.
- [X] I have searched the [current extension rule list](https://typescript-eslint.io/rules/#extension-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the base rule

https://eslint.org/docs/latest/rules/no-implicit-coercion

### Description

I propose that we extend the no-implicit-coercion rule to error not only in cases with code written specifically to do implicit type coercion, but also to cases which perform implicit type coercion by accident.

### Fail

```typescript
const foo = !!7; // From the original eslint rule
const bar = 17 + ""; // From the original eslint rule

const myArray = ["3", "3", "7"];
const myJoinedArray = "1" + myArray; // Implicitly calls toString() on array, returning "13,3,7"

const myObject = {a: 1};
const myLiteral = `Contents of myObject: ${myObject}`; // Implicitly calls toString() on object returning `Contents of myObject: [object Object]`
```

### Pass

```typescript
const foo = Boolean(7); // From the original eslint rule
const bar = String(17); // From the original eslint rule

const myArray = ["3", "3", "7"];
const myJoinedArray1 = "1" + myArray.toString();
const myJoinedArray2 = "1" + myArray.join("");

const myObject = {a: 1};
const myLiteral1 = `Contents of myObject: ${String(myObject)}`;
const myLiteral2 = `Contents of myObject: ${JSON.stringify(myObject)}`;
```

**Comment by bradzacher** [comment]
We already have lint rules that cover these cases! See the config in this [playground](https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=PTAEDEEMEsBsCgDGB7AdgZwC6gGbOQIygC8oAhGQOwDcoIEATsgLaiYAWApqMg9AObRUkWKE7pYQ7AwCusTkjRZQAI0gMipApVABqUACIDteuCasO3XgKEixEqaFnz4ijNmYBPAIIMGkT01QAG0DAGYDABpDCOiDSgMAXWo3ZS8AKWQhTgATX39AkkMCAz1QL3yAghMwAElmAAdJRGhMWE9QRBFYdDZkAGVMPlR%2BAAoASh5UUHUC6IZOTBkGVCF%2BYrDIzYTXFHdyzwB5FQArTkRMIIBvSAAuUAIAXxS9tM8AGVbOf1gggAMAMJoTCcVCYXrIHAHY5nC73AAkVy8MPOl0efxqoHqTWgLTaHS6sB6fUGwzGkzQPFOqKci2WqxGoEBwNB4J4UOR1LhIWQXOwKIuiT%2Brng9AACpB0OhUtg8MgAExFABC%2BHkkFQo0o40xZhYbC4PD4gmEonEkjBTjkCle2DUDEVpFJa1G2m1dDAuosBusxrsZsczgUMoOlU8DpC4SiMSj8SSLyUHk8mWyeT8AXDBhKZQqabDADpMAMhs7tcGMllULlQ-KM1n9DmCvK8ycK6MjKWy0c%2BeGbvcnvH9l5PiCfuHmWDWRCOV3YZgEVcnSNRpzZ-LxuiB29h98RDWiuOQWCp9C%2BfP0v1DgA5PNYMnQHCeZcz1FrjfwIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oCMBDZRLXxdk%2BKkwDm6KImjQO0SABpw2PEVLIK1Og2ZtoKMZTJ1i8WMlodS0XkwAmqDJFnzFK7FE61KAW3MTSjoyDlkySg4maVc5BUhVAF8QRKA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)
