### ISSUE TITLE
Bug: Peer Deps Issue with @typescript-eslint/parser on @typescript-eslint/eslint-plugin

### ISSUE THREAD

**Issue by kentond18** [typescript-eslint/typescript-eslint#7268]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

eslint-plugin-tslint

### Repro Code

```typescript
npm i @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest --save-dev
```

### Expected Result

I expected no issues on install of the latest of each package.

### Actual Result

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: undefined@1.0.0
npm ERR! Found: @typescript-eslint/eslint-plugin@5.62.0
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   dev @typescript-eslint/eslint-plugin@"6.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @typescript-eslint/eslint-plugin@"6.1.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @typescript-eslint/parser@6.1.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   peer @typescript-eslint/parser@"^6.0.0 || ^6.0.0-alpha" from @typescript-eslint/eslint-plugin@6.1.0
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     dev @typescript-eslint/eslint-plugin@"6.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `6.1.0` |
| `@typescript-eslint/parser`            | `6.1.0` |

**Comment by bradzacher** [comment]
Works fine for me - likely something else in your npm install that's causing it.

```
~ $ cd temp
~/temp $ mkdir 7268
~/temp $ npm i @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest --save-dev

added 126 packages in 14s

33 packages are looking for funding
  run `npm fund` for details
```

Maybe try nuking `node_modules` and trying again?
