### ISSUE TITLE
Docs: document how to setup RuleTester.afterAll

### ISSUE THREAD

**Issue by gajus** [typescript-eslint/typescript-eslint#7275]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

```
Error: Missing definition for `afterAll` - you must set one using `RuleTester.afterAll` or there must be one defined globally as `afterAll`.
    at Function.get afterAll [as afterAll] (/Users/gajus/Developer/gajus/eslint-plugin-canonical/node_modules/.pnpm/@typescript-eslint+rule-tester@6.1.0_@eslint+eslintrc@2.1.0_eslint@8.45.0_typescript@5.1.6/node_modules/@typescript-eslint/rule-tester/src/TestFramework.ts:65:11)
    at new RuleTester (/Users/gajus/Developer/gajus/eslint-plugin-canonical/node_modules/.pnpm/@typescript-eslint+rule-tester@6.1.0_@eslint+eslintrc@2.1.0_eslint@8.45.0_typescript@5.1.6/node_modules/@typescript-eslint/rule-tester/src/RuleTester.ts:100:17)
```

Just got the above error and I have no clue what is the correct action. Using mocha for what it is worth.

### Affected URL(s)

https://typescript-eslint.io/packages/rule-tester

**Comment by gajus** [comment]
I think it is just this, but since it is not documented, I am not confident.

```diff
import { RuleTester } from '@typescript-eslint/rule-tester';
import { AST_NODE_TYPES } from '@typescript-eslint/utils';
+import * as test from 'mocha';
import rule from '../../src/rules/exportSpecifierNewline';

+RuleTester.afterAll = test.after;
```

**Comment by bradzacher** [comment]
[Based on the mocha docs](https://mochajs.org/#hooks) - yup, that should be the hook you're looking for.

This is just a static that needs to be set based on your test environment if it doesn't already provide a global hook for this. This falls into the same bucket as [`it`, `it.only` and `describe`](https://eslint.org/docs/latest/integrate/nodejs-api#customizing-ruletester)

People had the same questions about how to integrate `vitest` - so we'll add a section to the [documentation](https://typescript-eslint.io/packages/rule-tester) to explain how to do this.

EG:

```ts
// mocha
// best done once in the global setup - https://mochajs.org/#global-setup-fixtures
import * as mocha from 'mocha';
import { RuleTester } from '@typescript-eslint/rule-tester';

RuleTester.afterAll = mocha.after;
```

```ts
// vitest
// best done once in the global setup - https://vitest.dev/config/#globalsetup
import * as vitest from 'vitest';
import { RuleTester } from '@typescript-eslint/rule-tester';

RuleTester.afterAll = vitest.afterAll;
// if you are not using vitest with globals: true
RuleTester.it = vitest.it;
RuleTester.itOnly = vitest.it.only;
RuleTester.describe = vitest.describe;
```

**Comment by gajus** [comment]
Thanks. I figured it out. Just wanted to seed the conversation for others that may encounter the error and Google it.
