### ISSUE TITLE
Bug: [no-misused-promises] async finally error

### ISSUE THREAD

**Issue by ZiiMakc** [typescript-eslint/typescript-eslint#7276]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=IYZwngdgxgBAZgV2gFwJYHsLwgCgJQwDeAsAFAwzADuwqyMACgE7oC2qIApgHROcBWnKMhwBmPNzioIwADaywOUJFj4YAXgB8RAL54A3GR1A&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oFtLlZkiACa1i0Dr0GoMkRNHHRI4MAF8QKoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```typescript
async function fn() {
  await Promise.reject(3).finally(async () => {});
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-misused-promises": "error"
  },
};
```

### tsconfig

```jsonc
{
	"exclude": ["**/node_modules"],
	"compilerOptions": {
		"target": "ES2022",
		"useDefineForClassFields": true,
		"module": "ES2022",
		"moduleResolution": "node",
		"resolveJsonModule": true,
		"allowJs": true,
		"checkJs": true,
		"declaration": true,
		"declarationMap": true,
		"sourceMap": true,
		"removeComments": true,
		"importHelpers": true,
		"downlevelIteration": true,
		"newLine": "LF",
		"isolatedModules": true,
		"verbatimModuleSyntax": true,
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"strict": true,
		"noUnusedLocals": false,
		"noUnusedParameters": false,
		"exactOptionalPropertyTypes": true,
		"noImplicitReturns": true,
		"noFallthroughCasesInSwitch": true,
		"noUncheckedIndexedAccess": true,
		"noImplicitOverride": true,
		"noPropertyAccessFromIndexSignature": true,
		"allowUnusedLabels": false,
		"allowUnreachableCode": false,
		"skipLibCheck": true
	}
}
```

### Expected Result

No error

### Actual Result

Error:

> Promise returned in function argument where a void return was expected

**Comment by bradzacher** [comment]
This is working as expected - the `.finally` method is not intended to accept a promise.

It's definition is:
```ts
interface Promise<T> {
  finally(onfinally?: (() => void) | undefined | null): Promise<T>
}
```

I.e. Whatever you return from the callback is ignored. So if you return a promise - that promise is not waited on and if it throws then it is an unhandled promise rejection.

**Comment by ZiiMakc** [comment]
@bradzacher I don't intend to return there, just do some cleanup and it does awaited [typescript playground](https://www.typescriptlang.org/play?target=99#code/GYVwdgxgLglg9mABAdwIYygCgLYGcCUiA3gFCLmIBOAplCJUmNcogAqVzYy7WY25wANgDdqiALwA+YmQpyeUACoxs1OCCz8hogDSI8+ANyzyAX3wlTJEqlwBPSIlCRYCRFGq4shUnNRoMFHQsAEYABgj8ADpgGDBUQUE7TFsHCERMQikZOT8AqCCMTHDIk1yIBAFBaijBOABzTAByWPjEu0QAIzqIAGtECuwAB2qPJqMy82s5CrAqmrrGpoAxOISkoNxEf2DqABNxy2sPL0zDIA)

**Comment by Josh-Cena** [comment]
The point of this rule is to prevent you from passing promises where the caller doesn't intend to handle rejections. If your `finally` callback rejects, it creates an unhandled rejection.

**Comment by Josh-Cena** [comment]
> So if you return a promise - that promise is not waited on and if it throws then it is an unhandled promise rejection.

That's not entirely true—rejected promises and synchronous errors from the `finally` callback causes the promise to be rejected: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

> A `throw` (or returning a rejected promise) in the `finally` callback still rejects the returned promise. For example, both `Promise.reject(3).finally(() => { throw 99; })` and `Promise.reject(3).finally(() => Promise.reject(99))` reject the returned promise with the reason `99`.

**Comment by ZiiMakc** [comment]
@Josh-Cena but rejection will be [handled by parent](https://www.typescriptlang.org/play?target=99#code/GYVwdgxgLglg9mABAdwIYygCgLYGcCUiA3gFCLmIBOAplCJUmNcogAqVzYy7WY25wANgDdqiALwA+YmQpyeUACoxs1OCCz8hogDSI8+ANyzyAX3wlTJEqlwBPSIlCRYCRFGq4shUnNRoMFHQsAEYABgj8ADpgGDBUQUE7TFsHCERMQikZOT8AqCCMTHDIk1yIBAFBaijBOABzTAByWPjEu0QAIzqIAGtECuwAB2qPJqMyuSgACw4WJhYAUUoOSkwAIhCAJgBmdYs5c2s5CrAqmrrGpoAxOISkoNxEf2DqABNxy2sPL0yoiFQUAg00w1Ckvgop3OtQaoIs5kMQA), so it's fine by me

**Comment by Josh-Cena** [comment]
@ZiiMakc Sorry for the confusion—I deleted my previous comment right after I sent it.

**Comment by bradzacher** [comment]
The rule is simply warning you that you're passing an async function into a place that won't handle the promise.

If you're doing this on purpose and know the risks then feel free to use a disable comment with an explanation to signify this is intentional.
