### ISSUE TITLE
🔪 Deprecate no-loss-of-precision rule extension

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7277]
## Overview

https://typescript-eslint.io/rules/no-loss-of-precision states that it exists to add support for [numeric separators](https://github.com/tc39/proposal-numeric-separator) to the base [eslint/no-loss-of-precision](https://eslint.org/docs/rules/no-loss-of-precision) rule. But, numeric separators have passed stage 3 and are natively supported in ESLint I believe. [[Example ESLint playground with the rule working on a number with a numeric separator](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tbG9zcy1vZi1wcmVjaXNpb246IFwiZXJyb3JcIiovXG5cbmNvbnN0IHggPSA5MDA3MTk5XzI1NDc0XzA5OTMiLCJvcHRpb25zIjp7ImVudiI6e30sInJ1bGVzIjp7fSwicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9LCJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQifX19)]

tl;dr: I propose we remove the rule _extension_ because the base rule contains all its features. 

👉 I'm not proposing we remove the base rule (or ask ESLint to)

> Whether it exists in popular configs such as eslint-config-airbnb-typescript and eslint-config-standard-with-typescript

* `eslint-config-airbnb-typescript`: yes, https://github.com/iamturns/eslint-config-airbnb-typescript/blob/8ef77c928c97d977f053c9c638831363a715d4a9/lib/shared.js#L143
* `eslint-config-standard-with-typescript`: yes, https://github.com/standard/eslint-config-standard-with-typescript/blob/b7b298d13ec737684e4368c726a3a9a66cd2f465/src/index.ts#L16

> Sourcegraph queries showing how often it appears in user configs

[Sourcegraph query showing it used in <200 repos](https://sourcegraph.com/search?q=context:global+file:.*eslint%7Cjs%7Cjson%7Cyaml%7Cyml%7Cyaml.*+%22%40typescript-eslint/no-loss-of-precision%22+-file:.*node_modules.*+-file:dist%5C/.*+count:200000&patternType=standard&sm=0&groupBy=repo): this doesn't seem like a particularly common rule for users to explicitly specify. That makes sense to me given that it's in the base recommended config (and has been for a while).

**Comment by Josh-Cena** [comment]
Interesting—I would have expected this rule to handle numeric type literals!

```ts
const a: 9007199254740993 = 9007199254740992; // No error?
```

**Comment by That-Guy977** [comment]
[@typescript-eslint/no-extra-semi](https://typescript-eslint.io/rules/no-extra-semi/) states that it adds support for [proposal-class-fields](https://github.com/tc39/proposal-class-fields) which is also stage 4 and seems to be supported by the [base rule](https://eslint.org/docs/latest/rules/no-extra-semi) as one of its examples.

I'm not familiar enough with the ecosystem here so I haven't made an issue for it, I wouldn't know what details to find and check 😅

**Comment by JoshuaKGoldberg** [comment]
Ah, the nice thing about `no-extra-semi` is that it's going to be a part of eslint.style now. So that's less for us to worry about. Good spot!

**Comment by JoshuaKGoldberg** [comment]
#8832 was merged into the `v8` branch. ✅
