### ISSUE TITLE
Docs: remove redundant `parser` property passed to `RuleTester` in usage example

### ISSUE THREAD

**Issue by dasa** [typescript-eslint/typescript-eslint#7304]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

This is the default:

https://github.com/typescript-eslint/typescript-eslint/blob/9105011681514372a7e851768d83a603fa19e8f2/packages/rule-tester/src/RuleTester.ts#L57

### Affected URL(s)

https://typescript-eslint.io/packages/rule-tester/#usage

**Comment by JoshuaKGoldberg** [comment]
Nice catch!
