### ISSUE TITLE
Bug: @typescript-eslint/strict-boolean-expressions breaks code on --fix

### ISSUE THREAD

**Issue by fasenderos** [typescript-eslint/typescript-eslint#7312]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

Running `eslint --fix` breaks code when the rule `@typescript-eslint/strict-boolean-expressions` has the option `allowNullableObject` set to false

Code before fix
```
type Items = {
    foo: string
}
const items: Items[] = [
    {foo: 'bar'},
    {foo: 'bar'},
]
function someFn (items?: Items[]) {
    return JSON.parse(
        JSON.stringify(items || []),
    );
}
const test = someFn(items)
console.log(test); // [ { foo: 'bar' }, { foo: 'bar' } ]
```
code after fix
```
...
function someFn (items?: Items[]) {
    return JSON.parse(
        JSON.stringify((items != null) || []),
    );
}
const test = someFn(items)
console.log(test); // true
```

**What did you expect to happen?**
Code gets changed with the `??` operator or not changed at all

### Reproduction Repository Link

https://github.com/fasenderos/typescript-eslint-strict-boolean

### Repro Steps

Clone the repo and run `npm install`, then try the code before fix

- `npm run build`
- `npm start`

The output will be `[ { foo: 'bar' }, { foo: 'bar' } ]`

Now run the fix and try again

- `npm run lint:fix`
- `npm run build`
- `npm start`

The output will be `true`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `^6.2.0` |
| `@typescript-eslint/parser`            | `^6.2.0` |
| `TypeScript`                           | `^5.1.6` |
| `ESLint`                               | `^8.45.0` |
| `node`                                 | `18.16.1` |

**Comment by bradzacher** [comment]
Isolated playground repro

https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=C4TwDgpgBAksEFsDOUC8UDeAoKUBmA9gQFxRLABOAlgHYDmWAvlgMYE3lRXzKlyJIA2gF00UQTkz4ipAOQAjAIYVZURgBpJGaSSgLlqjVmFY8AVxotgVdmQIIIAMRoAKbgID8fHkOEBKTEkKCGAzChooACkAZQB5ADkAOjBlJAgXSVwYhMTyanoqPBA3HygAHzLxf01cPwBuJlZ2TnhOdCR7J1d3ZD8mjgIAGwhEwYI6F1bgeqwgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6ZfKsugIwHs%2BSAIZN6AD2LQUySnyaoMAbUiJo0PtEgAaTOGw4h8eHwDuAOQTwhPJAHkeAK0Td0YAGaHkiPRAC%2BAXT1fEF8gA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

**Comment by bradzacher** [comment]
Side note that the code you want is `items ?? []`

**Comment by kemilbeltre** [comment]
The change we're expecting here is:

```js
function someFn (items?: Items[]) {
    return JSON.parse(
        JSON.stringify((items ?? []) || []),
    );
}
const test = someFn(items)
console.log(test); // true
```

I think should be better idea just to leave the value as it's since we have the same value in the other side (?).

**Comment by kemilbeltre** [comment]
I meant, we cannot change the whole line because the only thing that is producing an error is:

```js
item != null
```

Probably I'm wrong, so let me know what we can do instead. Thanks

**Comment by bradzacher** [comment]
There should not be an autofixer for this case.
Reporting on it is fine and correct as per the user's options - it's just the fix should not have been offered.
