### ISSUE TITLE
Rule proposal: no-optional-chaining-on-defined-object

### ISSUE THREAD

**Issue by Lesik** [typescript-eslint/typescript-eslint#7313]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Imagine you're writing some code that tries to access a property on an object that might be undefined. You'll likely use the [Optional Chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining):

```ts
function getObjectFromSomewhere(): { hello: string } | undefined;

const foo = getObjectFromSomewhere();

const bar = foo?.hello;
```

At a later point in time, you refactor `getObjectFromSomewhere` to actually always return the object, but not all the places where that function is used will be checked, and some of them retain the optional chaining operator. While it's not technically a problem (code behaves exactly the same), it is unnecessary and introduces a second way to write the same code. Additionally, it signals to any developer reading the code that the property might be undefined, while it actually can't, and you can only find out by hovering or going to the definition.

### Fail Cases

```typescript
const foo = {
  hello: "world",
};

const bar = foo?.hello;
```

### Pass Cases

```typescript
const foo = {
  hello: "world",
};

const bar = foo.hello;

const foofoo: {
  hello: "world",
} | undefined = {
  hello: "world",
};

const barbar = foofoo.hello;
```

**Comment by Josh-Cena** [comment]
This is covered by https://typescript-eslint.io/rules/no-unnecessary-condition/ already!

**Comment by Lesik** [comment]
Thanks @Josh-Cena!

I was searching for something with "chaining" so I overlooked this one. Hopefully the next person who searches for "chaining" stumbles upon this ticket and also finds it.

**Comment by bradzacher** [comment]
This is already covered by `no-unnecessary-condition`

https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=MYewdgzgLgBAZiEMC8MDeAoGMAWBTAGwJAC4YAiAdxACcCATcgGgwF8BuDDUSWAIwCGNFPEQB%2BAHT4iITkA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRRE0aB2iRwYAL4gtQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false
