### ISSUE TITLE
Website: Consider aligning to eslint.org 'Open in Website' 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7315]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

https://github.com/eslint/eslint/issues/17018 -> https://github.com/eslint/eslint/pull/17306 added playground links to correct and incorrect code blocks in the ESLint playground. The design the ESLint team asked for is different from ours:

* We (typescript-eslint.io) have a single _Try this rule in the playground ↗_ link on a rules page, floating underneath the config example
* eslint.org instead has an _Open in Playground_ link in the bottom-right of each rule (in)correct code snippet

I very much like how the eslint.org approach lets users directly try out code snippets (thanks @nzakas! ref: https://github.com/eslint/eslint/issues/17018#issuecomment-1490970585). How about we add the same type to our website?

I'm actually leaning towards keeping the existing _Try this rule in the playground ↗_ link -perhaps de-emphasizing it visually- so that folks still get the link above the fold & in a consistent location.

### Affected URL(s)

https://typescript-eslint.io/rules/*

**Comment by bradzacher** [comment]
> I very much like how the eslint.org approach lets users directly try out code snippets 

That was actually my original thought with the feature - but as a v0 opening the playground with the rule configured was "good enough".

**Comment by bradzacher** [comment]
Slightly off-topic but one other feature I'd love: interactive examples.

For example the Vue plugin embeds Monaco for each example!
https://eslint.vuejs.org/rules/multi-word-component-names.html

A lighter thought was maybe we do something like [twoslash](https://shikijs.github.io/twoslash/) and pre-calculate the errors to render statically for each example.

**Comment by nzakas** [comment]
> Slightly off-topic but one other feature I'd love: interactive examples.

This was actually how we envisioned the rules documentation working but we ran out of time so designed a fallback with "Open in Playground".
