### ISSUE TITLE
Configs: Allow strict configs to have more strict options than recommended?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7318]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

Coming over from comment thread https://github.com/typescript-eslint/typescript-eslint/pull/7110#discussion_r1271360631: rules are occasionally in a situation where:

* Many users in the _recommended_ configs don't want to use their full options, as they're more "strict" than common use cases
* We still want to enable the strict options for users, especially those on the _strict_ configs

What if we added to the `defaultOptions` and/or `meta.docs` sections of rules so that different configs can have different default options?

### Impacted Configurations

* `strict`
* `strict-type-checked`

### Additional Info

The example from the thread is https://typescript-eslint.io/rules/restrict-plus-operands/#options.

**Comment by Zamiell** [comment]
This sounds like a must-do!

As a user who wants the maximally strict linting config, I'd be super interested to know which rules that I'm using that are inherited from `strict` that aren't maximally strictly configured. To start with, can we just document the specific rules that are included in `recommended` and could be stricter so that people can fix it themselves?

**Comment by JoshuaKGoldberg** [comment]
> document the specific rules that have dumbed-down options? 

Hmm, very interesting. I like the root ask of knowing which rules have opt-in "more strict" options...

**Comment by bradzacher** [comment]
I'm of two minds - I like the idea but I also dislike it because it does make things quite a bit more complicated to define and strictly type. The options type we use is not for the config inputs - it's for the "after defaults" merging - which is one reason we haven't added strict types for user configs with our options types.

The last thing I'd want is for us to define a stricter config, roll it out, then find we misconfigured it and it's broken!

**Comment by JoshuaKGoldberg** [comment]
Here's a list of rules I'd propose:

* [`ban-ts-comment`](https://typescript-eslint.io/rules/ban-ts-comment): `minimumDescriptionLength` could be raised from 3
* [`no-floating-promises`](https://typescript-eslint.io/rules/no-floating-promises): `ignoreVoid` could switch from `true` to `false`
* [`restrict-plus-operands`](https://typescript-eslint.io/rules/restrict-plus-operands): turning off many of the `allow*` options
* [`restrict-template-expressions`](https://typescript-eslint.io/rules/restrict-template-expressions): turning off many of the `allow*` options
* https://github.com/typescript-eslint/typescript-eslint/pull/8094#issuecomment-1874637568

> it does make things quite a bit more complicated to define and strictly type

Maybe we could make `meta.docs.recommended` a union type? Perhaps rename it to something like `config(s)` or `recommendation(s)`?

Sent #8364 as reference.

**Comment by Zamiell** [comment]
strict-boolean-expressions also has some weird defaults that could be stricter:

```
  "@typescript-eslint/strict-boolean-expressions": [
    "error",
    {
      allowString: false,
      allowNumber: false,
      allowNullableObject: false,
      allowNullableBoolean: false,
      allowNullableString: false,
      allowNullableNumber: false,
      allowNullableEnum: false,
      allowAny: false,
      allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing: false,
    },
  ],
 ```

**Comment by Zamiell** [comment]
Also here:

```ts
  /**
   * The `allowDefaultCaseForExhaustiveSwitch` option is disabled and the
   * `requireDefaultForNonUnion` option is enabled to make the rule stricter.
   */
  "@typescript-eslint/switch-exhaustiveness-check": [
    "error",
    {
      allowDefaultCaseForExhaustiveSwitch: false,
      requireDefaultForNonUnion: true,
    },
  ],
```

**Comment by Zamiell** [comment]
And this:

```ts
  /** The `capIsConstructor` option is disabled to make the rule stricter. */
  "@typescript-eslint/no-invalid-this": [
    "error",
    {
      capIsConstructor: false,
    },
  ],
```

And this:

```ts
  /**
   * The `args` option is set to `all` make the rule stricter. Additionally, we ignore things that
   * begin with an underscore, since this matches the behavior of the `--noUnusedLocals` TypeScript
   * compiler flag.
   */
  "@typescript-eslint/no-unused-vars": [
    "error",
    {
      args: "all", // "after-used" is the default.
      argsIgnorePattern: "^_", // Optional, this line makes the rule less strict, but is idiomatic
      varsIgnorePattern: "^_", // Optional, this line makes the rule less strict, but is idiomatic
    },
  ],
 ```

**Comment by JoshuaKGoldberg** [comment]
Oh @Zamiell just looking at those now: none of those are in the `recommended`, `strict`, or `stylistic` presets. If you think we should enable stricter options for them by default and/or add them to a preset that'd be a separate issue.
