### ISSUE TITLE
Docs: Update info about the supported TypeScript version range

### ISSUE THREAD

**Issue by auvred** [typescript-eslint/typescript-eslint#7320]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

This line looks outdated, because the TypeScript `~5.1.0` is already supported:

https://github.com/typescript-eslint/typescript-eslint/blob/a56af12b83fab9def8989a83d5b9d2a660b099fd/docs/users/Versioning.mdx#L51

Also in this PR https://github.com/typescript-eslint/typescript-eslint/pull/7033, `Versioning.mdx` was moved from `/docs/maintenance` to `/docs/users`. I guess we should update this comment too, to match the new folder structure

https://github.com/typescript-eslint/typescript-eslint/blob/a56af12b83fab9def8989a83d5b9d2a660b099fd/packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts#L5-L8

### Affected URL(s)

https://typescript-eslint.io/users/versioning

**Comment by JoshuaKGoldberg** [comment]
Good catch, thanks @auvred!

**Comment by JoshuaKGoldberg** [comment]
Good catch, thanks @auvred! 

I'll note that #6389 tracks making this automatic. It'd be nice.

**Comment by auvred** [comment]
Oh, nice! I'll try to look into this

**Comment by JoshuaKGoldberg** [comment]
Awesome! My advice would be to fix this docs issue first -that way we can get the PR merged ASAP-, then look into #6389 if you still have time after.
