### ISSUE TITLE
Docs: Tip shown for parser points to non-existent playground option

### ISSUE THREAD

**Issue by dehoward** [typescript-eslint/typescript-eslint#7322]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I do not see the sidebar option mentioned in the tip for `@typescript-eslint/parser`.
looks like the option has been moved a tab on the right side?

Docs:
<img width="735" alt="image" src="https://github.com/typescript-eslint/typescript-eslint/assets/52973358/6dec305e-4ef7-4de8-85c7-0e7bf60de9c5">

Playground:
<img width="1308" alt="image" src="https://github.com/typescript-eslint/typescript-eslint/assets/52973358/2c2e17a3-be08-4c8d-9865-f30c209d21fd">

### Affected URL(s)

https://typescript-eslint.io/packages/parser/

**Comment by Josh-Cena** [comment]
Yes, there was a layout change.
