### ISSUE TITLE
When can body be undefined or null in vanilla espree?

### ISSUE THREAD

**Issue by G-Rath** [typescript-eslint/typescript-eslint#734]
I'm working on converting `eslint-plugin-jest` to typescript, and have come across a type definition that I can't reproduce at runtime.

While converting [`no-test-callbacks`](https://github.com/jest-community/eslint-plugin-jest/pull/321), I found out that it's apparently possible for the `body` of a [`FunctionDeclaration` to be `null`](https://github.com/typescript-eslint/typescript-eslint/blob/807bc2d4f5dbd62aebfcbd01012d41c37066480f/packages/typescript-estree/src/ts-estree/ts-estree.ts#L485).

This has required me to [add a null check](https://github.com/jest-community/eslint-plugin-jest/pull/321/files#diff-4ef22a3863ce94155654b7576ef9793fR40) in order to please typescript.

This in turn upsets our coverage b/c that branch is never tested, leading me here as I've not been able to write any code that reproduces the defined type.

Hence: how can I have a `FunctionDeclaration` w/ a `body` of `null` at runtime?

I suspect this heavily relates to #420, but theres too many moving parts for me to properly track :)

**Comment by bradzacher** [comment]
in vanilla espree?
I have no idea. I don't think it's possible there.

In typescript there are a number of places, such as:

```ts
// declarations
declare function foo(): void;

// overloads
function bar(): void;
function bar(arg?:string) {}

// abstract
abstract class Foo {
  abstract meth(): string;
}
```

**Comment by G-Rath** [comment]
That's what my investigation reveals as well, except that at those points the node type stops being `FunctionDeclaration`, instead becoming a `TS` node type (`TSDeclareFunction` & `TSAbstractMethodDefinition`).

It's all sounding to me like the `FunctionDeclaration` & `FunctionExpression` interfaces should redefine `body` as being just `BlockStatement`.

**Comment by bradzacher** [comment]
I'm not actually sure tbh.
I can't remember the cases.

The type of `body` is optional in the core typescript types:
https://github.com/microsoft/TypeScript/blob/97b5671f998bdc46db6e9b5cdc2f61a66efcbe7d/src/compiler/types.ts#L1051-L1084

I didn't realise it, but in #156, it added handling to convert function declarations with no body into `TSFunctionDeclaration` (https://github.com/typescript-eslint/typescript-eslint/pull/156/files#diff-68b2b0b0d2d0ff1846b1114472008332R674)

So it looks like there's no case now that a `FunctionDeclaration` can have no body?

`FunctionExpression` has no such handling, so the body will have to remain nullable.
Technically via the parser, we transform empty bodied function expressions into a new type `TSEmptyBodyFunctionExpression`, however the types come from `typescript-estree`, which does not have this conversion.

https://github.com/typescript-eslint/typescript-eslint/blob/93f72e3e8047656cb489f43f82af2babd2af8866/packages/parser/src/parser.ts#L94-L98

Maybe we should move that conversion into `typescript-estree` so we can simplify the types?

**Comment by G-Rath** [comment]
Any progress on this?

I'm happy to help if there's anything I can do 🙂

**Comment by bradzacher** [comment]
Happy to accept a PR, I hadn't looked into it any further.

**Comment by armano2** [comment]
note. _why it stayed in this way_

Initially there was a lot of additional conversions from AST produced by ts-estree in parser, most of them was cleared out, and looks like i forgot about this one.

this is part of legacy code from: https://github.com/eslint/typescript-eslint-parser/blob/master/parser.js#L46-L58 

and last change to this was done in PR https://github.com/eslint/typescript-eslint-parser/pull/596/files#diff-09461573a85e2d94f056dd6814769042

those changes was done before mono-repo, and at that time there was a lot of misalignment's between projects, and pushing any breaking changes was way way harder than now.

-----------

@G-Rath i'm glad that you picked it up 👍
