### ISSUE TITLE
Repo: Our EXPERIMENTAL_useProjectService unit tests are much slower in CI

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7348]
### Suggestion

Taking 18ea3b1f8938e25053f89b7e4ec8dcc6c453118a's https://github.com/typescript-eslint/typescript-eslint/actions/runs/5588135268/ as an example:

* [`eslint-plugin` run without the flag](https://github.com/typescript-eslint/typescript-eslint/actions/runs/5588135268/job/15134401904): 8m 6s
* [`eslint-plugin` run with the flag](https://github.com/typescript-eslint/typescript-eslint/actions/runs/5588135268/job/15134396350): 34m 9s

The Node version is 18 with the flag and 16 or 20 without, but that's just a quirk of the CI file. I've found it to be slower locally as well. This should be investigated.

@bradzacher and I noticed this when we first merged. cc @jakebailey - if you have the time, we'd appreciate any tips you have on it. We haven't investigated deeply yet.

**Comment by jakebailey** [comment]
Does each test fully spin up a new ProjectService? It's not a cheap operation; starting tsserver takes a bit to get going so if it's fresh each time I suspect that it won't be cheap.

But, if it's all in one process, I should be able to profile it pretty easily too.

**Comment by JoshuaKGoldberg** [comment]
> each test fully spin up a new ProjectService

Yeah, I believe so. We've previously tried to keep tests pretty isolated from each other. Would it be reasonable to look into speeding up tsserver creation?
