### ISSUE TITLE
Enhancement: [array-type] Consider types with template arguments to be simple types

### ISSUE THREAD

**Issue by JannikGM** [typescript-eslint/typescript-eslint#7393]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/array-type/

### Description

For `'@typescript-eslint/array-type': ['error', { default: 'array-simple' }]`:

```ts
type Foo = string | number
type Ref<T> = {
  foo: T
}
const bar: Ref<Foo>[] = [] // Problem!
```

This claims that `Ref<Foo>` is a non-simple type, so it should be `Array<Ref<Foo>>` instead.
We consider it to be debatable wether `Ref<Foo>` is a non-simple type.

The idea behind using this rule (for us) is that you increase readability by structuring the code more clearly.
This means avoiding parentheses (such as required for `(number | string)[]`) or using differently looking / more obvious / more explicit code like `Array<number | string>`.

However, the above `Array<Ref<Foo>>` is a counter-example, because the rule makes the resulting code less readable, by forcing us to reuse `<>` and `Array` disappearing in a sea of brackets and parentheses.

### Fail

```typescript
type Foo = string | number
type Ref<T> = {
  foo: T
}
const bar: Array<Ref<Foo>> = []
const bar2: (Ref<Foo> | undefined>)[] = []
```

### Pass

```typescript
type Foo = string | number
type Ref<T> = {
  foo: T
}
const bar: Ref<Foo>[] = []
const bar2: Array<Ref<Foo> | undefined> = []
```

### Additional Info

I can see how this might be debatable, so this should probably be an option.

**Comment by bradzacher** [comment]
Thanks for filing!

Given that this rule has worked this way since it was first implemented over 5 years ago - I don't think this is something the rest of the community agrees with.
For that reason I am going to reject this suggestion for this project.
