### ISSUE TITLE
Rule proposal: Prevent accidental stringification of data types that don't implicitly stringify well

### ISSUE THREAD

**Issue by SuttonKyle** [typescript-eslint/typescript-eslint#7400]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

This rule, which we propose to be called `no-implicit-to-string`, would effectively be a more restrictive version of the existing rule [no-base-to-string](https://typescript-eslint.io/rules/no-base-to-string/). The rule would flag implicit stringification of functions and other non-primitives, even if they implement their own `toString` method, including arrays (however, it would not flag explicit calls to `toString` directly). It would have a configurable option to flag non-string primitives  (number, boolean, bigint) as well, but primitives would not be flagged by default. This rule is an alternative proposal to the one I made in #7337, based on @jleider's comment on that issue.

### Fail Cases

```typescript
const fn = () => "hello world!";

`${fn}`;

const arr = ["hello", "world", "!"];

`${arr}`;
```

### Pass Cases

```typescript
const fn = () => "hello world!";

fn.toString();

const arr = ["hello", "world", "!"];

arr.toString();
```

**Comment by SuttonKyle** [comment]
> There are already `restrict-plus-operands` and `restrict-template-expressions` that work in the same domain; I doubt we want a _fourth_ rule that deals with stringification.

You're correct, it seems like `restrict-template-expressions` mainly does what we want from this rule. It looks like the documentation on `restrict-template-expressions` was altered in the last month -- prior to that, it suggested that values which define a `toString()` method would not be flagged by the rule, which was not what we wanted. The new documentation is more accurate and it seems that the rule is what we've been looking for.

**Comment by Josh-Cena** [comment]
Indeed, it was updated in https://github.com/typescript-eslint/typescript-eslint/pull/7009 ^^
