### ISSUE TITLE
Docs: is eslint-plugin-prettier considered a bad practice?

### ISSUE THREAD

**Issue by romeerez** [typescript-eslint/typescript-eslint#7403]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I'm using [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) on my projects, someone said that's a bad practice and linked your document: [What About Formatting](https://typescript-eslint.io/linting/troubleshooting/formatting/).

> We strongly recommend against using ESLint for formatting. We strongly recommend using [Prettier](https://prettier.io/)

The first sentence means that "eslint-plugin-prettier" is discouraged. But maybe it's an exception?
So I suggest stating directly in the doc that "eslint-plugin-prettier is a bad practice as well", and let's ask its maintainers to deprecate it. Or, if it's an exception, clarify this in the doc.

I'm using a pair of `eslint-plugin-prettier` and `eslint-config-prettier` for years and never experienced problems. I actually think it's even better because it's more efficient: instead of processing files twice by two different processes, lint & prettify in a single run. And always wondered why people use two tools separately when this can be simplified.

### Affected URL(s)

https://typescript-eslint.io/linting/troubleshooting/formatting

**Comment by Josh-Cena** [comment]
I think the docs can be rephrased on this point because there's nothing wrong _philosophically_ with eslint-plugin-prettier. But RE: performance, see https://typescript-eslint.io/linting/troubleshooting/performance-troubleshooting#eslint-plugin-prettier. In fact, all this plugin does is to run each file through Prettier, compute a diff, and report an error for each diff. It does not rely on the AST ESLint generates.

**Comment by romeerez** [comment]
Thanks for the info, I didn't know about it.

**Comment by bradzacher** [comment]
You're misunderstanding what we're saying here.

To better clarify - we're saying that you should avoid rules like `semi`, `arrow-parens`, `block-spacing`, `comma-dangle`, etc. I.e. avoid lint rules that format your code.

`eslint-plugin-prettier` could *technically* be thought of as "a lint rule that formats your code" - but it's not actually one.
A better way to think of it is "a tool that turns ESLint into a task runner that runs prettier".

As josh does mention though - running prettier this way is often slower overall - so generally we recommend running the two tools separately.

**Comment by Josh-Cena** [comment]
The way the sentence is phrased sounds confusing (and somewhat oxymoronic). People unfamiliar with the internals of eslint-plugin-prettier may not recognize what it does and just think it's a linter with all of Prettier's formatting rules incorporated.

**Comment by JoshuaKGoldberg** [comment]
> People unfamiliar with the internals of eslint-plugin-prettier may not recognize what it does and just think it's a linter with all of Prettier's formatting rules incorporated.

Yeah agreed. I ended up having to add a couple FAQs in https://www.joshuakgoldberg.com/blog/configuring-eslint-prettier-and-typescript-together-faqs because a lot of users don't know the difference between the two.

> We can make it explicit that it's only the formatting rules we are advising against, and mention eslint-plugin-prettier as a special case.

Err, I think we should be recommending against both the config and the plugin. Copy & pasting from my blog post:

> I strongly advise not using eslint-plugin-prettier for two reasons:
> 
> * It slows formatting down to the speed of your linter. Which, if you’re using [type-aware lint rules](https://typescript-eslint.io/linting/typed-linting) (as you generally should in TypeScript projects), should be much slower than running the formatter on its own.
Combining formatting complaints and lint complaints into one report is clunky and confusing.
> * You’ll often see large swathes of editor squigglies that may or may not be real logical complaints. New users have enough trouble understanding the differences between formatters and linters!

**Comment by JoshuaKGoldberg** [comment]
Oh, and:

> instead of processing files twice by two different processes

Nope, the prettier plugin actually passes a string directly to Prettier:

https://github.com/prettier/eslint-plugin-prettier/blob/b2b93c30c5679d38a094589eb608d0f5d7615aaf/eslint-plugin-prettier.js#L147-L149

https://github.com/prettier/eslint-plugin-prettier/blob/b2b93c30c5679d38a094589eb608d0f5d7615aaf/eslint-plugin-prettier.js#L141

https://github.com/prettier/eslint-plugin-prettier/blob/b2b93c30c5679d38a094589eb608d0f5d7615aaf/eslint-plugin-prettier.js#L170-L171

---

I'd meant to mark this as `accepting prs` earlier I think. Will send a PR now. Thanks y'all!
