### ISSUE TITLE
Docs: Mention closing issues as not planned in the maintenance guide

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7433]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Thanks to @Josh-Cena, TIL that closing an issue as _"completed"_ shows up differently from _"not planned"_. I've been doing the former but in many cases -aged-aways, invalid questions, wontfixes, etc.- should have been doing the latter.

https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue -> the last step...

Perhaps we should mention this in the maintenance docs?

### Affected URL(s)

https://typescript-eslint.io/maintenance/issues

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/typescript-eslint/typescript-eslint/pull/8489
