### ISSUE TITLE
`context.sourceCode` does not exist in type definition

### ISSUE THREAD

**Issue by so1ve** [typescript-eslint/typescript-eslint#7453]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

First of all, thanks for this awesome project!

(Not sure if I'm using the correct template)

Since eslint 8.40.0, a new property called `sourceCode` was added to `context`, and the old `context.getSourceCode` has been deprecated. However, typescript-eslint doesn't include these types.

### Reproduction Repository Link

N/A

### Repro Steps

1) Just check `context` in any rule

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `latest(6.x.x)` |
| `@typescript-eslint/parser`            | `latest(6.x.x)` |
| `@typescript-eslint/scope-manager`     | `latest(6.x.x)` |
| `@typescript-eslint/typescript-estree` | `latest(6.x.x)` |
| `@typescript-eslint/type-utils`        | `latest(6.x.x)` |
| `@typescript-eslint/utils`             | `latest(6.x.x)` |
| `TypeScript`                           | `5.1.6` |
| `ESLint`                               | `8.45.0` |
| `node`                                 | `16.18.0` |

**Comment by JoshuaKGoldberg** [comment]
This template works 🙂 thanks for filing! From https://eslint.org/blog/2023/05/eslint-v8.40.0-released/#highlights:

> Rules can now use properties `context.sourceCode`, `context.cwd`, `context.filename`, and `context.physicalFilename` instead of methods `context.getSourceCode()`, `context.getCwd()`, `context.getFilename()`, and `context.getPhysicalFilename()` respectively. The methods are now considered deprecated.

https://github.com/JoshuaKGoldberg/typescript-eslint/blob/4087f48b98e08778cf975b3be8964dd4616a0641/packages/utils/src/ts-eslint/Rule.ts will need to be updated to:

* Add the new properties
* Mark the old methods with `@deprecated` in their JSDocs
