### ISSUE TITLE
Bug: [@typescript-eslint/no-unsafe-assignment] Array destructuring of narrowed value (false postive)

### ISSUE THREAD

**Issue by andreashuber69** [typescript-eslint/typescript-eslint#7464]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.1.6&fileType=.ts&code=MYewdgzgLgBA7gCwIZQKYDdUCcBcMCuYA1mCHGDALwwDaARAqgJ50C6A3AFCcCWAZjAAUAQSxYkTAHQ8Io8U0GIUGbAEoYAMg3xkaTFkkAbVGADmUBDAB8MAAybtUJgAdUIAUr3Yat1lUrUdNBYPGZ06gDenDAwoJCwNIxMftSeKljsMAD0WTAAqpBIfKgwSGISMAAmqMH4wFD4IWYw7qUUAAZIYEztpeVMMOhIhvioktGDIDyVMElcAL6cQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolp9kySgHMmAW0Qt0YANrhsORNGgdokFRAC6KgL4hDQA&tsconfig=&tokens=false

### Repro Code

```typescript
const whatever: unknown = ["hey"];

if (Array.isArray(whatever) && whatever.length > 0 && typeof whatever[0] === "string") {
  const [hey] = whatever; // Unsafe array destructuring of an `any` array value.
  void hey; 
}
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/no-unsafe-assignment": [
      "error"
    ]
  }
}
```

### Expected Result

Given type narrowing in typescript, the compiler knows that `hey` must be a string. I therefore expected typescript-eslint to not flag this as an unsafe assignment.

### Actual Result

Unsafe array destructuring of an `any` array value. eslint([@typescript-eslint/no-unsafe-assignment](https://typescript-eslint.io/rules/no-unsafe-assignment))

**Comment by bradzacher** [comment]
`Array.isArray` refines `whatever` to `any[]`. [playground](MYewdgzgLgBA7gCwIZQKYDdUCcBcMCuYA1mCHGDALwwDaARAqgJ50C6A3AFCcCWAZjAAUAQSxYkTAHQ8Io8U0GIUGbAEoYAMg3xkaTFkkAbVGADmUBDAB8MAAybtUJgAdUIAUr3Yat1lUrUdNBYPGZ06gDenDAxOsr6XLEwAPTJMAB6APycAL5AA)

Your subsequent type-guards are not considered by TS because they operate on an array element - and TS does not track the type of individual array elements - i.e. TS will never refine `T[]` to `[U, ...T[]` - no matter the types for `T` or `U`.

I.e. according to the types you are destructuring from `any[]` - which is an error.

You must assign the element before the type cast to remove the `any`
```ts
const whatever: unknown = ["hey"];

if (!Array.isArray(whatever)) {
    return;
}
const value = whatever[0];
if (value && typeof value === "string") {
    value;
    // ^? string
}
```
[playground](https://www.typescriptlang.org/play?ssl=11&ssc=6&pln=2&pc=1#code/GYVwdgxgLglg9mABAWwIYzACgJSIN4BQixiECAzlIgO4AWqUApgG6MBOAXIuANZhzUkAXkQBtAES1GAT3EBdANwEiJGMESYAhAEE2bVNIB0Mcrv3TMdBi3bZchEo8RtGUEGzBLHAXxXEyYJSIzKgANiCMiCJWTKxsogAMin6Iahoh4ZEAZFmIUNIADoxw6hkRUUIi4pRsGADm4vYpjmWMXk7EAPSdiAB6APwpvt5AA)

**Comment by andreashuber69** [comment]
> `Array.isArray` refines `whatever` to `any[]`. [playground](MYewdgzgLgBA7gCwIZQKYDdUCcBcMCuYA1mCHGDALwwDaARAqgJ50C6A3AFCcCWAZjAAUAQSxYkTAHQ8Io8U0GIUGbAEoYAMg3xkaTFkkAbVGADmUBDAB8MAAybtUJgAdUIAUr3Yat1lUrUdNBYPGZ06gDenDAxOsr6XLEwAPTJMAB6APycAL5AA)
> 
> Your subsequent type-guards are not considered by TS because they operate on an array element - and TS does not track the type of individual array elements - i.e. TS will never refine `T[]` to `[U, ...T[]` - no matter the types for `T` or `U`.
> 
> I.e. according to the types you are destructuring from `any[]` - which is an error.
> 
> You must assign the element before the type cast to remove the `any`
> 
> ```ts
> const whatever: unknown = ["hey"];
> 
> if (!Array.isArray(whatever)) {
>     return;
> }
> const value = whatever[0];
> if (value && typeof value === "string") {
>     value;
>     // ^? string
> }
> ```
> 
> [playground](https://www.typescriptlang.org/play?ssl=11&ssc=6&pln=2&pc=1#code/GYVwdgxgLglg9mABAWwIYzACgJSIN4BQixiECAzlIgO4AWqUApgG6MBOAXIuANZhzUkAXkQBtAES1GAT3EBdANwEiJGMESYAhAEE2bVNIB0Mcrv3TMdBi3bZchEo8RtGUEGzBLHAXxXEyYJSIzKgANiCMiCJWTKxsogAMin6Iahoh4ZEAZFmIUNIADoxw6hkRUUIi4pRsGADm4vYpjmWMXk7EAPSdiAB6APwpvt5AA)

Hmmm, I'm not sure I understand. typescript does know that `hey` is a `string`, see [new playground](https://typescript-eslint.io/play/#ts=5.1.6&fileType=.ts&code=MYewdgzgLgBA7gCwIZQKYDdUCcBcMCuYA1mCHGDALwwDaARAqgJ50C6A3AFCeiSwAmIAMogAtqigIAlmADmVGAAp0SADb5UeaFhmyAlFQB8MdCCn8TajV05SAZkoCCWLEiYA6KRGeumixCgY2AYAZCHwyGiYWO6qqHKSMMYADDBhMFBMAA6oIA4BUdg0yaxUlNR02rp0BgDenDAwAPRNMKgQqjJQALT8XkgARnHdYKgAHj2dozAAApk5EMA6WT3tU1BNpN2EEEh2qN1IEBBSsmDiYFANMLzQtIxMpdQFQVhcjYIi4pK6ig96XAAvpwgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolp9kySgHMmAW0Qt0YANrhsORNGgdokFRAC6KgL4hDQA&tsconfig=&tokens=false), right? The typescript playground seems to agree. If you hover over the `hey` constant, both show that the type is `string` and neither has a problem calling `doSomething` with `hey` as an argument. Why doesn't tseslint use that info?

**Comment by bradzacher** [comment]
sorry - TS does track the type of the first element, but it doesn't narrow the type of `whatever`.

> TS will never refine `T[]` to `[U, ...T[]` - no matter the types for `T` or `U`.

So as far as the rule is concerned it sees `const [string] = any[]` - hence the rule errors.
There is no way for us to query TS here - this information is hidden to the APIs AFAICT.

**Comment by andreashuber69** [comment]
> So as far as the rule is concerned it sees `const [string] = any[]` - hence the rule errors.

Ok, but shouldn't the rule then consider the `const [string]` part and conclude that there is no problem? After all, there is nothing unsafe going on here, right?

(Sorry for being pedantic, if there's no way for the rule to consider that, I'm happy with your workaround.)
