### ISSUE TITLE
Website: playground keeps loading forever

### ISSUE THREAD

**Issue by haocheng6** [typescript-eslint/typescript-eslint#7476]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

#### How to reproduce

Open https://typescript-eslint.io/play/ in an incognito window.

![typescript-eslint io_play](https://github.com/typescript-eslint/typescript-eslint/assets/7645930/ecc59f3d-5d1e-4563-9f55-9a8b923bbdf6)

### Affected URL(s)

https://typescript-eslint.io/play/

**Comment by JoshuaKGoldberg** [comment]
🤔 works on my end. Have you tried a [hard refresh](https://superuser.com/questions/89809/how-to-force-refresh-without-cache-in-google-chrome)?

**Comment by haocheng6** [comment]
@JoshuaKGoldberg I tried hard refreshing the page, and it is still the same. Looks like it is a problem of TypeScript 5.2.1-rc.

If I add the following `config` to the localStorage, the playground will work again.

```jsonc
{"ts":"5.1.6","fileType":".tsx","sourceType":"module","showAST":false,"scroll":false}
```

**Comment by JoshuaKGoldberg** [comment]
Aha! _I_ did a hard refresh (and also tried incognito) and now I repo. Lovely! Thanks for reporting 😄

**Comment by NWYLZW** [comment]
Probably Microsoft deleted their monaco cdn resources of this version, and a similar problem appeared on my playground today.
Since that person left, I feel that there is no one to maintain it.

**Comment by JoshuaKGoldberg** [comment]
Ref for TypeScript's website's direction: https://github.com/microsoft/TypeScript-Website/issues/2804. Though, my bet this particular issue is just a transient issue. They still have folks maintaining the website.

I'm not sure where to file this given the website issue tracker only has a field for "CRITICAL" issues. [Asked in the TypeScript discord for now](https://discord.com/channels/508357248330760243/640177465490407425/1141012694057635840): 

> The typescript-eslint.io/play playground is getting a 404 for https://typescript.azureedge.net/cdn/5.2.1-rc/monaco/min/vs/editor/editor.main.js. Older / non-rc versions such as 5.1.1-rc still work. Where should I file an issue / ask for the new version to be uploaded, or whether it's no longer safe to rely on those URLs?

I'll keep this issue updated if any new information is posted there or otherwise outside of GitHub.

**Comment by haocheng6** [comment]
I found the following [comments](https://github.com/typescript-eslint/typescript-eslint/blob/a4e1ed7304440c8cfc059e1e427ab9135c24e2de/packages/website/src/components/editor/loadSandbox.ts#L21-L23) in the typescript-eslint codebase:

```
      // For the monaco version you can use unpkg or the TypeScript web infra CDN
      // You can see the available releases for TypeScript here:
      // https://typescript.azureedge.net/indexes/releases.json
```

According to https://typescript.azureedge.net/indexes/releases.json, not every version of TypeScript is available on the CDN.

I think a quick fix is to set `process.env.TS_VERSION` in our [webpack config](https://github.com/typescript-eslint/typescript-eslint/blob/a4e1ed7304440c8cfc059e1e427ab9135c24e2de/packages/website/webpack.plugin.js#L15-L17) to the latest available TypeScript version instead of `require('typescript/package.json').version`.

**Comment by NWYLZW** [comment]
> I found the following [comments](https://github.com/typescript-eslint/typescript-eslint/blob/a4e1ed7304440c8cfc059e1e427ab9135c24e2de/packages/website/src/components/editor/loadSandbox.ts#L21-L23) in the typescript-eslint codebase:
> 
> ```
>       // For the monaco version you can use unpkg or the TypeScript web infra CDN
>       // You can see the available releases for TypeScript here:
>       // https://typescript.azureedge.net/indexes/releases.json
> ```
> 
> According to https://typescript.azureedge.net/indexes/releases.json, not every version of TypeScript is available on the CDN.
> 
> I think a quick fix is to set `process.env.TS_VERSION` in our [webpack config](https://github.com/typescript-eslint/typescript-eslint/blob/a4e1ed7304440c8cfc059e1e427ab9135c24e2de/packages/website/webpack.plugin.js#L15-L17) to the latest available TypeScript version instead of `require('typescript/package.json').version`.

Indeed, according to my recent research on them, they basically follow this rule, and I think it can be sent to you for some reference.

https://github.com/Power-Playground/app/blob/main/core/src/utils/typescriptVersionMeta.ts#L12-L26

**Comment by JoshuaKGoldberg** [comment]
Saved by @JakeBailey - thanks Jake! I can confirm the playground loads again in an incognito window.

This shouldn't happen again on the TypeScript side. So we can consider this a transient bug, not an indication of something that needs to changed.
