### ISSUE TITLE
Bug: Cannot find module `@typescript-eslint/parser` or its corresponding type declarations in TS file

### ISSUE THREAD

**Issue by ifshizuku** [typescript-eslint/typescript-eslint#7486]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

parser

### Repro Code

```typescript
import tsParser from "@typescript-eslint/parser"
```

### tsconfig

```jsonc
{
    "compilerOptions": {
        "target": "ESNext",
        "module": "ESNext",
        "moduleResolution": "Node",
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "strict": true,
        "noEmit": true,
    },
    "exclude": [
        "**/node_modules",
        "**/dist",
    ],
}
```

### Expected Result

In typescript `.ts` file

<img width="583" alt="CleanShot 2023-08-16 at 18 32 39@2x" src="https://github.com/typescript-eslint/typescript-eslint/assets/73536163/34b998f1-54ef-41d6-9e90-f2699c31e17e">

it should happen like this with no typescript error

### Actual Result

I've try to import this parser in ESLint Flat config which I used `.ts` file, the typescript report an error on the parser packages' types declaration.

<img width="1168" alt="CleanShot 2023-08-16 at 18 31 06@2x" src="https://github.com/typescript-eslint/typescript-eslint/assets/73536163/f8eab9c3-1bca-4e40-85da-672d74629b78">

### Additional Info

We can bring a fix by simply add the `"types": "./dist/index.d.ts"` to `packages.json` so that the TypesScript could find the declaration file in `dist` instead of trying to find it at `./index.d.ts` leading to a error while there is not a `./index.d.ts` but `./dist/index.d.ts`.

<img width="341" alt="CleanShot 2023-08-16 at 18 32 08@2x" src="https://github.com/typescript-eslint/typescript-eslint/assets/73536163/4b6fced3-cd1f-49b1-b696-a81d17eadb6c">

**I can bring up a PR if that's OK.**

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/parser`            | `6.4.0` |
| `TypeScript`                           | `5.1.6` |
| `node`                                 | `20.5.0` |

**Comment by bradzacher** [comment]
Please use the search and see the pinned issues.
https://github.com/typescript-eslint/typescript-eslint/issues/7284
