### ISSUE TITLE
Enhancement: [no-unsafe-enum-comparison] Add an option to allow comparation between enum values and literals.

### ISSUE THREAD

**Issue by OpportunityLiu** [typescript-eslint/typescript-eslint#7492]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-unsafe-enum-comparison/

### Description

I am suggesting an enhancement for the `no-unsafe-enum-comparison` rule that would introduce an option to permit comparisons between enum values and string and/or number literals.

I believe this modification is warranted as it aligns with common usage patterns, as numerous library authors utilize enum types similarly to literal unions. In some cases, these authors may not even directly export the enum types, thereby making it challenging to compare using `ENUM_TYPE.ENUM_VALUE`.

For example, in `@apollo/gateway`, type `GraphQLDataSourceRequestKind` is not exported directly, but widely used in `GraphQLDataSource` hooks.
```ts
 new RemoteGraphQLDataSource<ApolloContext>({
            willSendRequest(options) {
                // options.kind has type `GraphQLDataSourceRequestKind`
                // The two values in this comparison do not have a shared enum type. eslint[@typescript-eslint/no-unsafe-enum-comparison](https://typescript-eslint.io/rules/no-unsafe-enum-comparison)
                if (options.kind !== 'incoming operation') return;
                // ...
            }
        });
    }
```

Since TypeScript (tsc) checks for overlaps between two types when comparing literals and enum values, I believe that introducing this option will not lead to potential bugs.

### Fail

```typescript
enum Foo {
  A = 'a',
}
 

declare const bar: Foo;
declare const baz: string;

if (bar === baz) { // this is still reported
  //
}
```

### Pass

```typescript
enum Foo {
  A = 'a',
}
 

declare const bar: Foo;

if (bar === 'a') { // this is allowed when the new option is set to allow string literal
  //
}

if (bar === 'b') { // it is ok to make this also allowed, since tsc will complain that `This comparison appears to be unintentional because the types 'Foo' and '"b"' have no overlap.`
  //
}

if (bar === 1) { // even this could be ok when the new option is set to allow number literal, tsc will perform check
  //
}
```

**Comment by NextThread** [comment]
Hey, can I work on this?

**Comment by bradzacher** [comment]
@OpportunityLiu the entire reason that the lint rule was built was to explicitly catch the case of using literals instead of the enum values!

Whilst modern TS does enforce there must be overlap between the literal and the possible enum values - it's still undesirable to use literals in this comparison because enums should be thought of as opaque values with their member values a private implementation detail, rather than public information.
