### ISSUE TITLE
Bug: [no-unused-vars] Mapped type keys marked as unused in type declaration

### ISSUE THREAD

**Issue by KrofDrakula** [typescript-eslint/typescript-eslint#7503]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.1.6&showAST=es&fileType=.ts&code=C4TwDgpgBAglC8UDeUDaBrCIoEsB2UAzsAE74DmAugFxR4CuAtgEYQlQC%2BAsAFC8QAPMAHsSwKABsI4gIa0YAbl5A&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQHYHsBaWXWZRAE0IDcBDaVDAbXGx0Wmn2kgBpW2WNtkh0G6KLXjw%2BA4ZHoBzRlAK5EkORAC%2BcgLr82kAAIAXAJ4AHFAGNoAS0unCKePdymA9AWKlyVMRUWYSgOLh5DYSEQ0XoVBWlZEJwleLUNLTBdNj1WXW0gA&tsconfig=&tokens=false

### Repro Code

```typescript
type A = { [key in string]: number }

export let a: A;
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "no-unused-vars": [
      "error",
      {
        "vars": "all",
        "args": "none"
      }
    ],
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        "vars": "all",
        "args": "none"
      }
    ]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

`key` in the mapped type should not be marked as an unused type parameter since you cannot create a mapped type without naming the parameter.

### Actual Result

`key` is considered an unused type argument.

**Comment by bradzacher** [comment]
Please see the rule docs which explain how to correctly configure the rule.

https://typescript-eslint.io/rules/no-unused-vars/#how-to-use

**Comment by KrofDrakula** [comment]
@bradzacher Ah, my bad. Thanks!
