### ISSUE TITLE
Bug: [ban-types][member-ordering][naming-convention] <not found>

### ISSUE THREAD

**Issue by devildant** [typescript-eslint/typescript-eslint#7504]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.5&showAST=scope&fileType=.ts&code=FBA&eslintrc=N4KABGBEBOD2sBdIC4wOgVwKYBpxQEsBzAO1miwAUBDBBLaEgZxTAG0BdPCSWANwbQCAEywtUbfBFARZUAGYEANmNaS5cyACoAdAhZTZXQzwAO1aEwYB5UwgKxmrGRrNwAVlgDGSCSY2Q%2Bl6OikQ67kyOkNyuspBYAExYAPRBIcThkSSQ-hDGsVBeFLRYACJY8tQYSgiUcETQ1AC2rOjY-gC%2BMZpYAB70JMLi7LlQpkoYRAQkyAAC1CRE1RYAtGJK0wjJFMFNTViDWMLRo5Djk9NzC0tKq%2BubqVhN4yXJpnBeYkwr0xskWCt6M9bvQDK58gFMCphi5XJB5otltA1kw-ltdqZHAcECsrCofOQ1KMeLB5PITgVpMS4ggAJ6mLCseIqfYkJDdSlnCiKXpM6imUwUyk8Jh0lRMgDWWAARtRpSsvNQrDlhR1RhC4QibndUQ9hAQdvYBLisPiEIS-ML4tA4NAhQVYZy6Qy%2BXQhNKMPR7Zz3hUCLzUJBvQVIKLaeLA4r9koAMJKxnUtUFDUBWbOsRFAh2FFo5IkZrTIgKxwCNkObKWzmCQkc1yOkN47zmu2BvgWAhy8W12KQeTkJq0InCzRR01x5XdkMAVUolAAogAlAD6MYAggBlOcq4ccRPqydQaWNT64sWMysh6t2g88ACMCGlYNiKc0sGlnh8Cow0CUtNx5i8QshyrG0a2pSBqCUAB3ahaRYG8wGAJNnwPeIAEcsAwtDgMvUDr3ApgB2gJB91OMhAUaZRC3-ahPmGdQQNtYMNHrHtiDICgY1gPZsWGNosD3ZNUOmUQ2Rwnsr2YuQElIkMB16FYVArEYrUkhDWLhYJRFYW8ADYAAYEJ4djyCwLieLZPjMFwaljNIUypx-KzsCMwh7IoBcsCIOdelMAAZAh6EaJRnJs4c3I4qhaCC5TIAAPQIZ5yAQMAdC0bcCmQ8FUPI4JmFgCMVMYsDhQ0gJIKUWAoPEq0YMYKSJLwhq4VEPg-NgIhmoCVqAHULGyVyeFaucmtssBd1VWSezQjBEFUC9GqYhDQ0LcUprhKwmgIU9w3PIrcKW8DblFDKNBfOImAAgFpQqUyVnkDASB8csVnMChlIYg6SspMrNAWRxaSaWAMGGSB-gEfDwrB5ojiZcGGC6nglVpJ7V1A6rA0gmC4NO1wsrOnLYDWZ46SZNTTiwArFKVXx9sW76Qyx2Cn2ysiiYoUUhB8I4fiS4j6PA8mrWgXoImSBdeXW1N0yYTNs3uNk3m5Bh7vIFZSSZUlyVQ315BViw4CgpWKn19H7se57HFBrWGsgKVaSg8hhBowDFhqgJJKlzQ03pDMhHl3VFdlEhAV9gXVKa9SxvifoDmEcpKmqfRWms1zAjD5wxp4JDWEqEKBPC-G8a9uIfYZWX-ZxBWtn2JobuRJ2GCAha4SFn7o9EROakz8KeFr%2BuABUM5b4dQwQWgCC8e6CFNY5BriaZRQWE9FFnxGAiX%2Bwp-2BAAAtYDnrOF%2BYcenoBHf9%2BOI%2BJuHIuNDvvJOkMLpDFY3tlHmunNF0XeECaJRcbjW7DHAYQx3ZmAmFMGYWokQ5geECF49BtjeG4qyUQV9WZwihJ-JCz98C7g6EAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```typescript
error appear with an update angular (16) ans eslint to last version 
but i don't now how to reproduce without angular
```

### ESLint Config

```javascript
file .eslintrc.json

{
  "root": true,
  "ignorePatterns": [],
  "overrides": [
    {
      "files": [
        "*.ts"
      ],
      "parserOptions": {
        "project": [
          "tsconfig.json",
          "e2e/tsconfig.json"
        ],
        "createDefaultProgram": true
      },
      "extends": [
        "plugin:@angular-eslint/recommended",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],
      "rules": {
        "@angular-eslint/component-selector": [
          "off",
          {
            "type": "element",
            "prefix": "app",
            "style": "kebab-case"
          }
        ],
        "@angular-eslint/directive-selector": [
          "error",
          {
            "type": "attribute",
            "prefix": "",
            "style": "camelCase"
          }
        ],
        "@typescript-eslint/naming-convention": [
          "error",
          {
            "selector": "variable",
            "format": [
              "camelCase",
              "UPPER_CASE"
            ]
          }
        ],
        "brace-style": [
          "error",
          "1tbs"
        ],
        "object-curly-spacing": [
          "error",
          "always",
          {}
        ],
        "eqeqeq": [
          "error",
          "smart"
        ],
        "no-trailing-spaces": [
          "error",
          {
            "ignoreComments": true
          }
        ],
        "indent": [
          "error",
          2
        ],
        "max-len": [
          "error",
          {
            "code": 160,
            "ignoreComments": true,
            "ignoreUrls": true,
            "ignoreRegExpLiterals": true,
            "ignorePattern": "^import .*"
          }
        ],
        "no-console": [
          "error",
          {
            "allow": [
              "warn",
              "error",
              "devLog",
              "devWarn",
              "devError"
            ]
          }
        ],
        "quotes": [
          "error",
          "single"
        ],
        "semi-style": [
          "error",
          "last"
        ],
        "space-before-function-paren": [
          "error",
          {
            "anonymous": "never",
            "named": "never",
            "asyncArrow": "always"
          }
        ],
        "no-empty": "error",
        "eol-last": [
          "error",
          "always"
        ],
        "no-restricted-imports": [
          "error",
          "rxjs/Rx"
        ],
        "@typescript-eslint/prefer-for-of": "off",
        "prefer-arrow/prefer-arrow-functions": "off",
        "keyword-spacing": [
          "error"
        ],
        "@typescript-eslint/ban-types": [
          "error",
          {
            "extendDefaults": true,
            "types": {
              "{}": false
            }
          }
        ],
        "@typescript-eslint/member-ordering": [
          "error",
          {
            "default": {
              "memberTypes": [
                "static-field",
                "instance-field",
                "static-method",
                "instance-method"
              ]
            }
          }
        ]
      }
    },
    {
      "files": [
        "*.html"
      ],
      "extends": [
        "plugin:@angular-eslint/template/recommended"
      ],
      "rules": {}
    }
  ]
}
```

### tsconfig

```jsonc
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "paths": {
      "GuiUtilsLib": [
        "dist/gui-utils-lib"
      ]
    },
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2022",
    "module": "es2020",
    "lib": [
      "es2020",
      "dom"
    ],
    "resolveJsonModule": true,
    "useDefineForClassFields": false
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

### Expected Result

no error

### Actual Result

i obtain the error in ide (intellij) on first import, i take this error 

ESLint: Definition for rule '@typescript-eslint/ban-types' was not found.(@typescript-eslint/ban-types)
ESLint: Definition for rule '@typescript-eslint/member-ordering' was not found.(@typescript-eslint/member-ordering)
ESLint: Definition for rule '@typescript-eslint/naming-convention' was not found.(@typescript-eslint/naming-convention)

### Additional Info

 "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.0",
    "@angular-eslint/builder": "16.1.0",
    "@angular-eslint/eslint-plugin": "16.1.0",
    "@angular-eslint/eslint-plugin-template": "16.1.0",
    "@angular-eslint/schematics": "16.1.0",
    "@angular-eslint/template-parser": "16.1.0",
    "@angular/cli": "^16.2.0",
    "@angular/compiler-cli": "^16.2.1",
    "@types/accounting": "^0.4.2",
    "@types/jasmine": "~3.10.0",
    "@types/lodash": "^4.14.197",
    "@types/node": "^12.20.55",
    "@typescript-eslint/eslint-plugin": "^5.62.0",
    "@typescript-eslint/parser": "^5.62.0",
    "eslint": "^8.47.0",
    "eslint-plugin-import": "^2.28.0",
    "eslint-plugin-jsdoc": "^39.9.1",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "ng-packagr": "^16.2.0",
    "typescript": "~4.9.5"
  }

**Comment by JoshuaKGoldberg** [comment]
From the issue template you used:

> If either of the following holds true:
>
> * You can't reproduce the issue in the playground
> * Your issue requires some complex setup - such as multiple files or a specific folder structure.
>
> **_Please do not use this template._** Instead, select the
> ["Report a complex bug you encountered by providing an isolated reproduction repository" template](https://github.com/typescript-eslint/typescript-eslint/issues/new?template=08-bug-report-complex.yaml).
> **_Help us to help you!_**

Two .json files and a paste of a few errors isn't enough info to reproduce your lint failures. Especially if it involves other dependencies such as Angular with [angular-eslint](https://github.com/angular-eslint/angular-eslint).

Please file an issue with a link to a full reproduction, and we'd be happy to take a look.

**Comment by devildant** [comment]
Obviously I've been looking for a day, and now that I've posted, I've found a solution:
simply add the plugins as below, in the eslintrc.json
```
"plugins": [
        "@typescript-eslint"
],
```

in the previous version it did not seem to be a problem but now yes, just a hassle not possible to find
I found it by chance by random testing

**Comment by JoshuaKGoldberg** [comment]
FWIW that step is covered in the docs: https://typescript-eslint.io/getting-started. If you haven't yet read through, I'd recommend it.
