### ISSUE TITLE
Bug (?): [no-unused-vars] We have to use args in a abstract class constructor

### ISSUE THREAD

**Issue by HolgerJeromin** [typescript-eslint/typescript-eslint#7516]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.1-rc&fileType=.ts&code=IYIwzgLgTsDGEAJYBthjAgtgTwEJoFMBhVdBAbwFgAoBJAewDtIoBXeeqACgDN76AXAhYBLRgHMAlBRp06AenkIAvAD4EAcj70NCERgAmBHmIIGEIVokYEAbgSgJWYMwDpZCAL4fnwcQRUEHmBkFwBuGm9qFDQMHBJYhAIADwgCRgM4vEIE9CpaBmZodghOXn4hUQlpfLlhVgAHB3L6SQiChSUAEXphekwCCAALMXEEAHcRYaD%2BBCGHAg86WCYwemQCV2R6cRbJDyiomhWivSLgRlgA5QQbcaxsXLAuDVsQ1gINNpoxSAur1y%2BfyBYoEMJAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQHYHsBaWXWZRAE0IDcBDaVDSfAMxcgBpxtIABAFwCeABxQBjaAEth-QiniTc-APQFipclToN0URNGj5okbgF8QpoA&tsconfig=&tokens=false

### Repro Code

```typescript
abstract class myBaseClass {
  constructor(foo: string) {
    // => 'foo' is defined but never used.
  }
  usage = false;
}
class myClass extends myBaseClass{
  constructor(foo: string) {
    super(foo);
    // Do something with foo here
    console.log(foo)
  }
}

const instance = new myClass('value');
instance.usage = true;
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    '@typescript-eslint/no-unused-vars': ['error',
    {
        args: 'all',
        argsIgnorePattern: '^_',
    },
  ],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

I think an `abstract class` constructor do not need to handle all arguments by itself. 
In that case the abstract class only defines an API for the inherited classes.
So probably this rule should not report the argument in the base class constructor. 

Renaming to `_foo` is perhaps not optimal because the inherited controls should use the value in their constructor but they would want to copy the arguments name verbatim.

### Actual Result

All parameter have to be used, also on the abstract class constructor.

**Comment by JoshuaKGoldberg** [comment]
> We _have to_
> I think an abstract class constructor do not need to handle all arguments by itself.

Just remove the parameters from the abstract class constructor. They're unused - there's no need to have them!

https://typescript-eslint.io/play/#ts=5.2.1-rc&fileType=.ts&code=IYIwzgLgTsDGEAJYBthjAgtgTwEJoFMBhVdBAbwFgAoBJAewDtIoBXeeqACgEoKa6AXwEJWYYAHMCCALwIAZsGRgCAbhrDqKNBhwkdCAgA8IBRgBNdeQvvRVaDZtHYROXefXoAuBCwCWjBJ89nR0YKwADgTcPOoOdAD0CQgAIvS%2B9JgEEAAWARIIAO5%2BuQqeCDnRBCJ0sExg9MgEAHTI9BLunjwimpo0dU4IAZDAjLDScowEhVjYtmBcAOQAbkqsBIuxNMMQo%2BPNYpITCM5qQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQHYHsBaWXWZRAE0IDcBDaVDSfAMxcgBpxtIABAFwCeABxQBjaAEth-QiniTc-APQFipclToN0URNGj5okbgF8QpoA&tsconfig=&tokens=false

This is a common anti-pattern with abstract classes, and base->derived classes in general. Derived classes don't need to establish any particular shape for their constructor.

**Comment by HolgerJeromin** [comment]
My inheritance was a bit complex which confused me.
Thanks for your time and helpful comment!
