### ISSUE TITLE
Repo: Group jest versions in the renovate config?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7537]
### Suggestion

We just got a while bunch of Jest PRs pinning to 29.6.3:

* #7528
* #7529
* #7530
* #7531
* #7532
* #7533

Maybe we should group them in Renovate config, so they're all sent as one PR?

For reference, we already do this for a few other groups of related packages:

https://github.com/typescript-eslint/typescript-eslint/blob/1d26d87b3c6869da00ecadac6f68b3fc7c83208d/.github/renovate.json5#L59-L63

**Comment by bradzacher** [comment]
I was literally looking at this and wondering why it wasn't like this already. I remember looking at his last time and realising we do actually have this configured 

https://github.com/typescript-eslint/typescript-eslint/blob/1d26d87b3c6869da00ecadac6f68b3fc7c83208d/.github/renovate.json5#L76-L81

It's just that for some reason it isn't working.

**Comment by peanutenthusiast** [comment]
Hi, possible to work on a PR for this?

**Comment by auvred** [comment]
@peanutenthusiast Hi, yes, you can read more about issue claiming here: https://typescript-eslint.io/contributing/issues#issue-claiming

**Comment by peanutenthusiast** [comment]
Great. Submitted the PR: https://github.com/typescript-eslint/typescript-eslint/pull/7612
