### ISSUE TITLE
Error: Plugin "@typescript-eslint" was conflicted between ".eslintrc.js » plugin:@typescript-eslint/recommended-type-checked » ./configs/base" and ".eslintrc.js » @vue/eslint-config-typescriptBug: <short description of the issue>

### ISSUE THREAD

**Issue by laterdayi** [typescript-eslint/typescript-eslint#7569]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

eslint-plugin-tslint

### Repro Code

```typescript
Error: Plugin "@typescript-eslint" was conflicted between ".eslintrc.js » plugin:@typescript-eslint/recommended-type-checked » ./configs/base" and ".eslintrc.js » @vue/eslint-config-typescript
```

### ESLint Config

```javascript
require('@rushstack/eslint-patch/modern-module-resolution');

module.exports = {
  root: true,
  env: {
    node: true,
    es6: true
  },
  parser: 'vue-eslint-parser',
  plugins: ['standard-recommended'],
  extends: [
    'eslint:recommended',
    'plugin:vue/vue3-essential',
    'plugin:vue/vue3-strongly-recommended',
    'plugin:vue/vue3-recommended',
    '@vue/eslint-config-typescript',
    '@vue/eslint-config-prettier/skip-formatting',
    'plugin:@typescript-eslint/recommended-type-checked',
    // unplugin-auto-import
    './.eslintrc-auto-import.json'
  ],
  parserOptions: {
    project: true,
    tsconfigRootDir: __dirname,
    parser: '@typescript-eslint/parser',
    sourceType: 'module',
    ecmaVersion: 'latest',
    ecmaFeatures: {
      jsx: true
    }
  },
  noInlineConfig: true,
  reportUnusedDisableDirectives: true,
  // ignore 
  ignorePatterns: [
    '*.sh',
    'node_modules',
    '*.md',
    '*.woff',
    '*.ttf',
    '.vscode',
    '.idea',
    'dist',
    '/docs',
    '.husky',
    '.github'
  ],
};
```

### tsconfig

```jsonc
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue", "auto-imports.d.ts", "components.d.ts"],
  "compilerOptions": {
    "ignoreDeprecations": "5.0",
    "jsx": "preserve",
    "baseUrl": ".",
    "moduleResolution": "bundler",
    "paths": {
      "@unocss/preset-icons/browser": ["./node_modules/@unocss/preset-icons/dist/browser"],
      "@/*": ["./src/*"],
      "@c/*": ["./src/components/*"],
      "@v/*": ["./src/views/*"]
    },
    "lib": ["ESNext", "DOM"],
    "types": ["vite/client", "naive-ui/volar"]
  }
}
```

### Expected Result

[Error - 17:59:25] Error: Plugin "@typescript-eslint" was conflicted between ".eslintrc.js » plugin:@typescript-eslint/recommended-type-checked » ./configs/base" and ".eslintrc.js » @vue/eslint-config-typescript".
    at mergePlugins (E:\projects\stp-web\node_modules\.pnpm\@eslint+eslintrc@2.1.2\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:598:19)
    at createConfig (E:\projects\stp-web\node_modules\.pnpm\@eslint+eslintrc@2.1.2\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:701:9)
    at ConfigArray.extractConfig (E:\projects\stp-web\node_modules\.pnpm\@eslint+eslintrc@2.1.2\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:877:33)
    at CLIEngine.isPathIgnored (E:\projects\stp-web\node_modules\.pnpm\eslint@8.48.0\node_modules\eslint\lib\cli-engine\cli-engine.js:1001:18)
    at CLIEngine.executeOnText (E:\projects\stp-web\node_modules\.pnpm\eslint@8.48.0\node_modules\eslint\lib\cli-engine\cli-engine.js:910:38)
    at ESLint.lintText (E:\projects\stp-web\node_modules\.pnpm\eslint@8.48.0\node_modules\eslint\lib\eslint\eslint.js:593:23)
    at c:\Users\admin\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:24860
    at E (c:\Users\admin\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:19218)
    at e.validate (c:\Users\admin\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:24819)
    at c:\Users\admin\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:221494

### Actual Result

![264308326-b0a66b5f-f973-4b40-8976-dab341321822](https://github.com/typescript-eslint/typescript-eslint/assets/122137647/8f57b5d1-88f4-4d87-ab10-7d673976497f)

### Versions

all lastest

**Comment by bradzacher** [comment]
This occurs because you have multiple versions of our tooling installed.

https://typescript-eslint.io/linting/troubleshooting#how-do-i-check-to-see-what-versions-are-installed

**Comment by laterdayi** [comment]
@bradzacher  Then which tool version should I delete, looking forward to your help

**Comment by laterdayi** [comment]
pnpm list @typescript-eslint/eslint-plugin @typescript-eslint/parser
Legend: production dependency, optional only, dev only



devDependencies:
@typescript-eslint/eslint-plugin 6.5.0
@typescript-eslint/parser 6.5.0

**Comment by bradzacher** [comment]
according to your log line you have two versions of the plugin installed - one in the root and one underneath `@vue/eslint-config-typescript`.

you need to configure your package manager so that it forces just one version to be instaslled.

**Comment by laterdayi** [comment]
I use @vue/eslint-config-typescript' and @typescript-eslint in my project, can you tell me how to configure to use only one?  @bradzacher

**Comment by bradzacher** [comment]
https://pnpm.io/package_json#pnpmoverrides
