### ISSUE TITLE
Rule proposal: Avoid Using Object.values on Enums

### ISSUE THREAD

**Issue by ddubrava** [typescript-eslint/typescript-eslint#7574]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Using `Object.values` on enums can often lead to confusion, as it returns both the values and keys of the enum. To prevent this confusion, I recommend manually defining the exported constant with the enum values.

Please check these links for more information: [link 1](https://stackoverflow.com/questions/43100718/typescript-enum-to-object-array) and [link 2](https://stackoverflow.com/questions/56044872/typescript-enum-object-values-return-value), where people are trying to achieve the expected behavior of `Object.values`.

### Fail Cases

```typescript
enum Colors {
    WHITE = 0,
    BLACK = 1,
    BLUE = 3,
}

const colorsValues = Object.values(Colors);

enum Heterogeneous {
    StringValue = 'Hello',
    NumericValue = 42,
}

const heterogeneousValues = Object.values(Heterogeneous);
```

### Pass Cases

```typescript
enum Colors {
    WHITE = 0,
    BLACK = 1,
    BLUE = 3,
}

const colorsValues = [
    Colors.WHITE,
    Colors.BLACK,
    Colors.BLUE
]

enum Heterogeneous {
    StringValue = "Hello",
    NumericValue = 42,
}

const heterogeneousValues = [
    Heterogeneous.StringValue,
    Heterogeneous.NumericValue,
]
```

**Comment by JoshuaKGoldberg** [comment]
> Using `Object.values` on enums can often lead to confusion...

Agreed 😄 it can be confusing...

> ...as it returns both the values and keys of the enum

Nit just to be visibly precise for readers: that's only true for numeric enums. String-valued enums don't have the reverse map.

https://www.typescriptlang.org/play?#code/MYewdgziA2CmB0w4EMBOAKAlAbgFC4DMBXMYAFwEtwACaEAcwFEwiBbdWF1geQCMArWOQBc1EAKFlM1AN65qC6qEgwEdehy59B5HPMXKoceOvTbJ8AG7JoRWBE1tzuvQF98nNtQBybWKgpgADUbOwhZfQUCClQIMmoAXmoABgAaSOoIIXAAE0TqAEZ091x1ZjZ0X1Z-QJDbez1cT1ZqAGUyALB6OrCIxWpkAAdBuHyAIkAeDcA5fbH0-t5kMEXkcYnAGX2x3BKyrnR2zu7QhuwgA

Although enums are confusing, I don't know that this is something we really need in typescript-eslint core. Enums are hopefully going to change over the next few years (https://github.com/rbuckton/proposal-enum). But even if that takes many many years, it's not clear what the right behavior is. Why did the users want to get the values of the enums? Maybe they did want to log all the values?

I think we'd need to see some clear indication that in addition to `Object.values(enum)` being a _potential_ source of unexpected behavior (like those two StackOverflow questions), it's also a _consistent_ source of unexpected behavior. Like, that a supermajority of projects would want this rule.

**Comment by bradzacher** [comment]
Yeah that's where i was at as well - I definitely see value in this check - it's a solid correctness guarantee! However it also is such a rare thing to do that I don't think it's worth building a rule.

Such a rule would be expensive as well - it would need to calculate types for every single `Object.values`/`Object.keys` call to catch the super rare case that someone passes an enum in.

If there was a strong drive from the community, maybe? But even then - dubious, IMO.

**Comment by Josh-Cena** [comment]
There are many other similar things, including `Object.entries`, `{ ...enum }`, `for (const key in enum)`, etc.

**Comment by ddubrava** [comment]
Well, for instance, if you have an enum with all business entities and you would like to display these entities somewhere, you can call Object.values on this enum to retrieve all its values.

But I agree, there are various tricky cases. Perhaps it's better to use no-restricted-syntax and prohibit non-const enums, so people cannot call Object.values on them. 🤷‍♂️

```
json
{
  "rules": {
    "@typescript-eslint/no-restricted-syntax": [
      "error",
      {
        "selector": "TSEnumDeclaration:not([const=true])",
        "message": "Always use const enums due to unexpected behavior."
      }
    ]
  }
}
```
