### ISSUE TITLE
Docs: Out-of-date TS error codes in eslint-recommended.ts

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7582]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

https://github.com/typescript-eslint/typescript-eslint/blob/939e42f05afa9536e03923b8829f060cdf35ada0/packages/eslint-plugin/src/configs/eslint-recommended.ts includes comments referring to corresponding TS error codes for rules. Example:
https://github.com/typescript-eslint/typescript-eslint/blob/939e42f05afa9536e03923b8829f060cdf35ada0/packages/eslint-plugin/src/configs/eslint-recommended.ts#L11C17-L11C17

Some of those error codes are out of date: https://github.com/eslint/eslint/pull/17500#discussion_r1311685415. Someone should go through and update the TS codes to whatever they are now as of the latest stable version of Typescript.

### Affected URL(s)

https://github.com/typescript-eslint/typescript-eslint/blob/939e42f05afa9536e03923b8829f060cdf35ada0/packages/eslint-plugin/src/configs/eslint-recommended.ts

(Technically comments rather than website, but they're used by some as docs too)

**Comment by girishsontakke** [comment]
@JoshuaKGoldberg I would like to work on this fix, please assign this issue to me

**Comment by JoshuaKGoldberg** [comment]
https://typescript-eslint.io/contributing/issues#issue-claiming - but you're welcome to send a PR. Which I see you did 😄 thanks!
