### ISSUE TITLE
Docs: Added incorrect content to the example on the require-await page.

### ISSUE THREAD

**Issue by dsk52** [typescript-eslint/typescript-eslint#7609]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I would like to add an Example of Collect / Incollect to the `require-await` documentation, just like the other pages.

The Example section says `Examples of correct code for this rule`, but I think what is written as an Example is incorrect content.
I would like to add an example of Collect / Incollect like the other pages as it seems to be misleading.

### Affected URL(s)

https://typescript-eslint.io/rules/require-await

**Comment by bradzacher** [comment]
The reason that there aren't any invalid examples is because they're all [listed on the base rule's documentation](https://eslint.org/docs/latest/rules/require-await).

As mentioned at the top of the doc:

> This rule extends the base [eslint/require-await](https://eslint.org/docs/rules/require-await) rule. It uses type information to add support for async functions that return a Promise.

**Comment by dsk52** [comment]
Sorry! I guess I misunderstood a lot of things.
It looks fine, so I'll close it.
