### ISSUE TITLE
Docs: ts-config-strict tag for rules

### ISSUE THREAD

**Issue by sheam** [typescript-eslint/typescript-eslint#7611]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Could there be a tag called `ts-config-strict` that tags rules that enforce the equivilant of `"strict": true,` in the `.tsconfig` file? It appears that the 'strict' tag in the documentation goes way beyond what 'strict' means in the .tsconfig file.

**Context:**
We have a legacy typescript project which we have introduced eslint to. We only have the linter run on committed files (via husky hooks and lint-staged). This works great for getting code up to standards one commit at a time.

However, the problem we are having is that the `.tsconfig` file for the project as `"strict": false,` set. The project won't compile if it is set to `true`, and it will take a month to fix everything in one pass. 

What I would like to do is to add all the rules to our eslint config file which mimic the "strict" value in `.tsconfig` so that we fix things one commit at a time.

The problem is that there is no easy way to determine which typescript-eslint rules would help enforce this.  

### Affected URL(s)

https://typescript-eslint.io/rules/?supported-rules=strict

**Comment by bradzacher** [comment]
> all the rules ... which mimic the "strict" value

I'm not sure which rules you're thinking of - none of our eslint rules mimic TS errors. Quite the opposite, in fact, as we do our best to ensure there are no duplicated errors between the two.

Some of our rules work best with `strict: true`, or require certain strict options like `strictNullChecks: true`, but we don't mimic those options.

Could you provide some examples?

**Comment by JoshuaKGoldberg** [comment]
👋 Hey @sheam! Just checking in, is this still something you have time for? No worries if not - I just don't want to leave it hanging.

**Comment by sheam** [comment]
yes, I figured it out use another plugin. You can close this.
