### ISSUE TITLE
Parser errors on a file that is excluded in `tsconfig`

### ISSUE THREAD

**Issue by blordpluto** [typescript-eslint/typescript-eslint#7619]
Hi, I've been using this package extensively for years. Just now updating from 5.* to 6.6.0

Basically:
- I want to lint some `.js` build files in my project without type-aware linting.
- I also want to lint some `.ts(x)` files using type-aware linting.

I have followed the instructions at:

https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file

exactly 😅 . I have removed all rules requiring type information from the top-level configuration and only applied them to TypeScript files via an override.

I am getting the parser error:

```sh
  0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/some/config/file.js` using `parserOptions.project`: /users/thatguy/documents/repos/myApp/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file
```

**The first option** is not what I want. I want to lint `some/config/file.js`, just not with type-aware rules.

**The second option** is not what I want. There is no normal reason to include `some/config/file.js` in the tsconfig for the project. I do not want to typecheck these JS config files.

**The third option** seems excessive. I really don't want to introduce another `tsconfig` into the project. It will be necessary to maintain ongoing changes to multiple `tsconfig.eslint` files consistently parallel to changes to the existing `tsconfig`s. This really seems like a maintenance footgun. 😨 

On the linked page, it says that removing all rules requiring type information from the top-level configuration should work. But I have... and it doesn't...

Because it's not possible to specify a parser in an override, my understanding is that there is only ever a single parser per eslint config. (Also, there's no way to have multiple `eslintignore`s. )

So it seems like either:
- the CLI error is being triggered incorrectly
- or the CLI message is correct, in which case the site docs should probably be updated to reflect the requirement that that all linted files (of all types) _ALWAYS_ need to be included in the referenced `tsconfig`. This is a strong requirement, and if it's true, it would be helpful to be more up front about it with users. It's not the way we've done things up until now.

Thanks for an amazing tool!

### ESLint Config

```javascript
const memberOrderingConfig = require('./internals/eslint/member-ordering-config');

module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 'latest',
    project: true,
  },
  // These base rulesets apply to all files in the project, including root, build scripts,
  // and JavaScript files like `babel.config.js` etc.
  extends: [
    'eslint:recommended',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:prettier/recommended',
  ],

  plugins: [
    '@typescript-eslint',
    'import',
    'prettier',
    'react',
  ],
  rules: {
    // Override individual rules from the above configs.
    eqeqeq: 'error',
  },
  overrides: [
    {
      // These React, testing, and type-aware rulesets only apply to TypeScript files.
      extends: [
        'plugin:import/typescript',
        'plugin:@typescript-eslint/recommended-type-checked',
        'plugin:@typescript-eslint/stylistic-type-checked',
      ],
      files: ['./**/*.{ts,tsx}'],
      rules: {
        '@typescript-eslint/ban-types': [
          'error',
          {
            types: {
              Function: false, // allow Function type.
            },
          },
        ],
        '@typescript-eslint/ban-ts-comment': 'off',
        '@typescript-eslint/camelcase': 'off',
        '@typescript-eslint/consistent-type-imports': [
          'error',
          { fixStyle: 'inline-type-imports', disallowTypeAnnotations: false },
        ],
        '@typescript-eslint/explicit-function-return-type': 'off',
        '@typescript-eslint/explicit-module-boundary-types': 'off',
        '@typescript-eslint/no-explicit-any': 'off',
      },
    },
  ],
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": ".",
    "esModuleInterop": true,
    "importHelpers": true,
    "isolatedModules": true,
    "jsx": "react",
    "lib": ["dom", "es6", "ES2015.Iterable", "scripthost"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noImplicitAny": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "outDir": "./build",
    "preserveConstEnums": true,
    "pretty": true,
    "removeComments": true,
    "resolveJsonModule": true,
    "skipLibCheck": false,
    "sourceMap": true,
    "strict": true,
    "target": "es6",
    "typeRoots": ["node_modules/@types", "typings"],
    "types": ["node", "jest", "@testing-library/jest-dom", "hls.js"],
    "verbatimModuleSyntax": true
  },
  "include": ["*", "**/*", "typings/*.d.ts"],
  "exclude": [
    "build",
    "node_modules",

    "internals/**/*.js"
  ]
}
```

### Expected Result

see above

### Actual Result

see above

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `6.6.0` |
| `@typescript-eslint/parser`            | `6.6.0` |

**Comment by armano2** [comment]
```
      // These React, testing, and type-aware rulesets only apply to TypeScript files.
      extends: [
        'plugin:import/typescript',
        'plugin:@typescript-eslint/recommended-type-checked',
        'plugin:@typescript-eslint/stylistic-type-checked',
      ],
```

you are missing project field in override

**Comment by bradzacher** [comment]
You can do something like this to disable type-checking on just JS files.

https://github.com/typescript-eslint/typescript-eslint/blob/1bad83258dcb16d188da3c1a5015e903922c2109/.eslintrc.js#L212-L224

We should absolutely update our docs for this (v6 was the first version that had this new disable type check config)

**Comment by blordpluto** [comment]
Hey thanks @bradzacher Sorry, I think didn't make myself clear. You're answering the question: "**How do I disable typechecking on JS files?**"

What I am asking: "**How do I make the typescript-eslint parser not error on JS (build script) files that are excluded in a tsconfig?**"

I can delete every single `typescript-eslint` reference from my eslintrc (except for the parser), and the error still happens. In fact, I can delete all-but-one of the rules and the error still happens. It's not a rules problem. It's a parser problem.

Here is an ultra minimal eslintrc that reproduces the issue:

```javascript
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 'latest',
    // This tsconfig excludes some JS build script files
    // that are deliberately not eslintignored
    project: './tsconfig.json',
  },
  env: {
    browser: true,
    node: true,
  },
  rules: {
    // Look, no typescript-eslint rules!
    eqeqeq: 'error',
  }
}

**Comment by bradzacher** [comment]
https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file

**Comment by bradzacher** [comment]
There is no misunderstanding - I'm answering your exact question.

You're saying you don't want to lint `.js` files with type information. So the solution to your problem is to disable type-aware linting on your `.js` files as I showed above.

---

Based on the minimal config you showed - I think you might be unclear on what config actually turns on type-aware linting.

Have you read the docs on linting with type information? They will help you understand your config a better.
https://typescript-eslint.io/linting/typed-linting

**Comment by blordpluto** [comment]
Thanks for replying.

So, the ultraminimal config was just to demonstrate a point: that I'm get the type-aware-linting-CLI-error with JS files even when type-aware linting _is not even enabled_. 🤔 Selecting the parser is sufficient to generate the error.

I have able to get this working using the disable plugin as you've suggested, but I'm still baffled as to why I need to disable it for JS files when I haven't enabled it for JS files in the first place:

```javascript
 overrides: [
    // Turn type-aware linting on just for ts(x) files.
    {
      extends: [
        'plugin:@typescript-eslint/recommended-type-checked',
        'plugin:@typescript-eslint/stylistic-type-checked',
      ],
      files: ['./**/*.{ts,tsx}'],
      rules: {
        // A bunch of rule customizations omitted here.
    },
    // So why do I need to specify this additional disable-type-checked plugin
    // for js files, when I only ever enabled it for ts(x) files in the first place?
    // **The process errors without this.**
    {
      files: ['*.js'],
      extends: ['plugin:@typescript-eslint/disable-type-checked'],
      rules: {
        'no-console': 'off',
        // etc
      },
    },
  ],
```

**Comment by bradzacher** [comment]
Rules consume type information and are only one half or the type-aware linting equation.

The other half is the parser - and you must turn on type-aware parsing so that there is type information for the rules to consume.

You do this by setting `parserOptions.project` in your config. This is why I linked the docs, as it explains this in more detail.

Which is why I say you need to turn off type-aware linting on JS files. Not just the rules, but also `parserOptions.project`. Which is what our config does for you. You can inspect [the config](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/disable-type-checked.ts) to see what it does for you.

**Comment by JoshuaKGoldberg** [comment]
Oh do we want to keep this open as a docs issue?
