### ISSUE TITLE
Bug: [consistent-type-assertions] Requires parser services, but isn't categorized as such

### ISSUE THREAD

**Issue by alecmev** [typescript-eslint/typescript-eslint#7624]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

https://github.com/typescript-eslint/typescript-eslint/pull/6885#issuecomment-1699339630
https://github.com/typescript-eslint/typescript-eslint/issues/7615

```
Error: Error while loading rule '@typescript-eslint/consistent-type-assertions': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
```

### Reproduction Repository Link

https://github.com/alecmev/typescript-eslint-repro-7615

### Repro Steps

1) clone the repo
2) `npm i`
3) `npx eslint .`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `6.6.0` |
| `ESLint`                               | `8.49.0` |
| `node`                                 | `20.6.1` |

**Comment by bradzacher** [comment]
https://github.com/alecmev/typescript-eslint-repro-7615/blob/main/.eslintrc.js#L3

`parser: 'espree'` this is going to cause you a whole world of undefined behaviour. Our rules are not built to work with that parser, nor are they tested against it.

In particular this rule will not do anything ever with that parser (and ofc your lint process will crash on TS files).

The error message is wrong, for sure - it's not a typed rule, but it is consuming for the typescript AST information that's only provided by our parser.
For reference our parser parses with TS and them converts TS's AST to the ESTree AST - there are no types required to do this.

**Comment by alecmev** [comment]
I agree that this isn't clean, but until now all non-typed rules have been compatible with any parser, allowing this:

```yml
extends: ['plugin:@typescript-eslint/strict-type-checked']
overrides:
  - files: '*.yml'
    extends: ['plugin:@typescript-eslint/disable-type-checked', 'plugin:yml/standard']
```

I assume from what you're saying that it was just an accident that it didn't blow up?

**Comment by bradzacher** [comment]
> I assume from what you're saying that it was just an accident that it didn't blow up?

Not an accident - just lucky. We don't test our rules against any other parser at all - we run on the assumption that our users use our parser.

We access properties on the AST with these assumptions so it's possible to crash out very easily.

In this case, sure, it's likely that whatever yaml parser that's used will not emit nodes that match ESTree, so it's not likely to cause too much weirdness.

As another example you'll find that you run into issues with rules like `explicit-function-return-type` and `explicit-module-blundary-types` on non-ts files because ofc you can't annotate types in a non-ts file.

I'd just be turning the rule off files you're knowingly not using our parser.

**Comment by alecmev** [comment]
> I'd just be turning the rule off files you're knowingly not using our parser.

I agree with that! The docs are a little blurry on this issue, all examples put everything `typescript-eslint`-related at the top level of `.eslintrc`. `overrides` should maybe be recommended for most people then? Or is the assumption that few actually abuse ESLint for non-JS/-TS parsing?

**Comment by bradzacher** [comment]
> Or is the assumption that few actually abuse ESLint for non-JS/-TS parsing?

It's definitely the rarer case because eslint currently isn't well designed for non-js parsing. Gotta jump through various hoops to make it work.

**Comment by alecmev** [comment]
Ok, thank you!
