### ISSUE TITLE
Bug: [no-unsafe-enum-comparison] false negative with empty object union

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#7626]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.1.6&showAST=es&fileType=.tsx&code=KYOwrgtgBAsgngUXNA3gWAFBSgNQIYA2YwAjADSYC%2BmmALnAA7BQCWItUAvFMgEbAAnKADIoKSgG4aGACbAAxgTwDm8gPYgAzhwBmatSQBcPSPwFSMLHVAAUeg107d4SSADp8RUgEoxlKAD0AVAAKgIsAOYRgppQtAAWzARsHAJgBMBkUHixwAAeTPK0wDJu0nKKyqoa2lD2AEzGKRZWtg2OzojIHoTEJL7igcEAImrAsSBqHLThUTFxiVDJ7FBpGWUYQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZonpNYAW1pkOY4nyrIOTdFADucpeDABfEDqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

**Comment by Zamiell** [comment]
I guess this is similar to #7114.

**Comment by bradzacher** [comment]
I'd call it the same thing!
