### ISSUE TITLE
Bug: [prefer-nullish-coalescing] Default option will change runtime behavior

### ISSUE THREAD

**Issue by ide** [typescript-eslint/typescript-eslint#7628]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.2&showAST=ts&fileType=.tsx&code=MYewdgzgLgBAZiEAuG0BOBLMBzGAfGAVzABMBTOLMkmAXhgHIGYBDCVKTHfI0iqkgG4AUKEggANmQB0EkNgAUCEPgIMWHLtgYBKEUA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WlqYSNkAC1pkA9gEMkyMswDm6MAG1IvaOOiQANJnDYcleU02IAClQC2lfJQBuKJVgPZIyfFSaKMXackT6BgC%2BgWBBALr6IUFAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```typescript
const foo: string | undefined = '' as string | undefined;
console.log(foo || 'a string');
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/prefer-nullish-coalescing": ["error", {
      "ignorePrimitives": {
        "string": false
      }
    }]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

I expected no lint errors. The [docs](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md#ignoreprimitives) say this is correct code with `ignorePrimitives: { string: false }`:

```ts
const foo: string | undefined = 'bar';
foo || 'a string';
```

### Actual Result

Slightly modifying the definition of `foo` to be set to an empty string and adding an `as` cast (see the repro) causes the linter to suggest changing `||` to `??`, which would alter the code's behavior. The docs say the lint rule reports an error when the replacement is safe, which I read as that it won't change the behavior of the code.

### Additional Info

Looks related to https://github.com/typescript-eslint/typescript-eslint/issues/7055.

Are the docs backwards? Should the docs say `ignorePrimitives: true` lets `anyString || etc` always pass?

**Comment by JoshuaKGoldberg** [comment]
Ha, yes, I _think_ the docs are backwards. Thanks for pointing out! 

cc @omril1 / #6487 just to make sure I'm not missing something

**Comment by omril1** [comment]
Yes, I think the incorrect/correct examples should be swapped.
Faulty human error from double negative 🙃z

**Comment by ide** [comment]
Hi, I submitted a PR (linked above) to update the docs. It's a small PR but hope it is helpful nonetheless.

**Comment by JoshuaKGoldberg** [comment]
![Meme of a farmer captioned "It ain't much but it's honest work"](https://github.com/typescript-eslint/typescript-eslint/assets/3335181/3147f119-3d70-404f-b6ef-283aa5be8315)

**Comment by JoshuaKGoldberg** [comment]
Actually, I'm not sure that there's anything left to do here now that the docs PR is in? (note that today is Friday it'll go live on typescript-eslint.io on Monday)

**Comment by ide** [comment]
Thanks for reviewing the docs edit. For this issue at hand, my motivation for opening it came from expecting prefer-nullish-coalescing to suggest only changes that wouldn't modify the behavior of the code. To use the example in the original issue description, I'd expect the lint rule not to suggest changing `||` to `??`:

```ts
const foo: string | undefined = '' as string | undefined;
console.log(foo || 'a string'); // Prints "a string" with || and prints "" with ??
```

Changing the `ignorePrimitives` option to default to true would achieve this I believe.

This is just one data point of developer feedback, though, and I understand maintainers need to consider a wide range of use cases. Please feel free to close this issue.

**Comment by bradzacher** [comment]
A lot of codebases purposely don't rely on falsey coercion for primitives - so migrating these cases is technically unsafe, but is going to be fine for the majority of cases.

The other problem is that once you remove primitive cases you are pretty sparse on the remaining safe cases.

Finally the rule is safe to turn on as these potentially unsafe cases don't have autofixers, just suggestion fixers. So it's up to the user to manually fix it.

So the question is "do you want the default to only flag safe and autofixable cases, do you want the default to flag any possible case?"

**Comment by steverep** [comment]
> So the question is "do you want the default to only flag safe and autofixable cases, do you want the default to flag any possible case?"

I agree with @ide that the default config should not be suggesting changes that alter program logic (and the docs for stylistic rules state that exactly).  The fact of the matter is that `||` and `??` are not equivalent for primitives, so "prefer" is really a misnomer for the rule in these cases.  More precisely, the default should not be an error unless the types of the operands truly dictate that fixing to `??` is equivalent.  Whether or not the default for other cases is a warning or off is a judgement call.

Related  feedback in https://github.com/typescript-eslint/typescript-eslint/issues/8648#issuecomment-1989454940

**Comment by Josh-Cena** [comment]
Won't `ignorePrimitives` fix this case?

**Comment by JoshuaKGoldberg** [comment]
@Josh-Cena what do you mean? The OP does have `ignorePrimitives` enabled.

**Comment by Josh-Cena** [comment]
Sorry, didn't see that. I'm completely lost, then, why `ignorePrimitives: { string: false }` is specified yet we expect `string | undefined` to still be ignored. These options exist exactly to tell the rule that "the falsiness of these types cannot be ignored".

**Comment by bradzacher** [comment]
11 months later and this request has received 0 community reactions.
As per our [workflow guidelines](https://typescript-eslint.io/maintenance/issues#community-engagement-evaluation) - we are taking this as signal that this check is not important to the broader community and are thus rejecting the proposal. Thanks for filing!
