### ISSUE TITLE
Bug: [no-shadow] 'T' in static method is already declared in upper scope when class is in a factory function

### ISSUE THREAD

**Issue by yifanwww** [typescript-eslint/typescript-eslint#7664]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.2&fileType=.tsx&code=GYVwdgxgLglg9mABAWwIYGsCmBBAFASkQG8BYAKEUQCdMoQqkIAbVAZ1cWwB4AVAPmLlKlCAlZQqIaHCq4ADiABGTGBEQA3VExCYAXIh6EiiAL7khw8alhq0WXn1ybteg0YvDqtekjCYA7pwOTlo6%2BADcHqYWZmSx5KJg4pyIALwoGDgE5EA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1uQAsBDACYcA7uiiJo0DtEjgwAXxDygA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```typescript
function makeA() {
  return class A<T> {
    constructor(public value: T) { }

    static make<T>(value: T) {
      return new A<T>(value);
    }
  }
}

const A = makeA()
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-shadow": "error",
  },
};
```

### Expected Result

No lint errors.

### Actual Result

```
'T' is already declared in the upper scope on line 2 column 18. 5:17 - 5:18
```

**Comment by bradzacher** [comment]
This was fixed back in #3393 but it appears to have regressed?
