### ISSUE TITLE
Enhancement: [naming-convention] support array destruction

### ISSUE THREAD

**Issue by rikisamurai** [typescript-eslint/typescript-eslint#7665]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/naming-convention/#filter

### Description

I want to utilize the https://typescript-eslint.io/rules/naming-convention/#filter rule to ensure that all const variables are formatted in UPPER_CASE. However, when I apply it within array destructuring, it doesn't work as expected.
```js
      // Enforce that all const variables are in UPPER_CASE
      {
        selector: 'variable',
        types: ['boolean', 'string', 'number'],
        modifiers: ['const'],
        format: ['UPPER_CASE'],
      },
      {
        selector: 'variable',
        types: ['boolean', 'string', 'number'],
        modifiers: ['destructured'],
        format: null,
      },
```
when i write
```js
const [count, setCount] = useState(false);
```
It triggers an error, but I would like it to be ignored for array destructuring.

### Fail

```typescript
const url = 'http://github.com';
```

### Pass

```typescript
const [count, setCount] = useState(false);
const URL = 'http://github.com';
```

**Comment by bradzacher** [comment]
Could you please provide some information about why you want all `const`s to be upper case except for the array destructuring case?

The `destructured` modifier is there so that people can ignore object destructuring cases because destructured properties already have some name that already exists - so ignoring them saves people having to rename them.

However array destructuring has no such prior name limitation - so I don't see a good reason they should ever be exempt.

**Comment by rikisamurai** [comment]
I just want to use UPPER CASE for certain const variables because it signifies that these variables will never change. However, in the context of React:
```js
const [count, setCount] = useState(false);
```
the const variables within this array destructuring represent state variables that can change anytime. For such scenarios, I would still prefer to use camelCase. But i haven't found a modifier or workaround🧐

**Comment by bradzacher** [comment]
I think you've conflated a few concepts here.

State variables don't change at any time - they're constant for the lifetime of a render.
Their value will only ever change in a subsequent render - i.e. a future function call.

This is exactly the same as any other `const` variable defined within the function body.

For example imagine this:
```ts
function Component() {
  const TICK_VALUE = tick();
  const [tickValue, setTickValue] = useState(0);

  useEffect(() => { setTickValue(t => t + 1) }, []);

  return <></>;
}

let i = 0;
function tick() {
  return i++;
}
```

In this code `TICK_VALUE` changes every single render and `tickValue` also changes every single render.

---

I don't think there's broad applicability to this request.
Additionally the generally accepted pattern is to only use `UPPER_CASE` for `const` variables defined at the top-level (eg the `global` modifier).

For these reasons I'm going to close this.

**Comment by rikisamurai** [comment]
> I think you've conflated a few concepts here.
> 
> State variables don't change at any time - they're constant for the lifetime of a render. Their value will only ever change in a subsequent render - i.e. a future function call.
> 
> This is exactly the same as any other `const` variable defined within the function body.
> 
> For example imagine this:
> 
> ```ts
> function Component() {
>   const TICK_VALUE = tick();
>   const [tickValue, setTickValue] = useState(0);
> 
>   useEffect(() => { setTickValue(t => t + 1) }, []);
> 
>   return <></>;
> }
> 
> let i = 0;
> function tick() {
>   return i++;
> }
> ```
> 
> In this code `TICK_VALUE` changes every single render and `tickValue` also changes every single render.
> 
> I don't think there's broad applicability to this request. Additionally the generally accepted pattern is to only use `UPPER_CASE` for `const` variables defined at the top-level (eg the `global` modifier).
> 
> For these reasons I'm going to close this.

My apologies! I should use 'global' in this situation. Thanks!❤️
