### ISSUE TITLE
Support vue mustache expressions via `defineTemplateBodyVisitor`

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#767]
Following on from https://github.com/typescript-eslint/typescript-eslint/pull/760#issuecomment-515726428

For better interop with vue, we might want to look at implementing `defineTemplateBodyVisitor`.
https://github.com/mysticatea/vue-eslint-parser/blob/0f241279dc412ff4bb0faa9211233a944465f9b4/README.md#L93-L99

This will let plugins provide linting for vue expressions.

**Comment by uniqueiniquity** [comment]
FWIW, I'm not sure that this is a parser issue, but rather a plugin issue. From what I can tell, it has to be used in each rule. Would be curious to hear from @mysticatea why it's used instead of the built-in `visitorKeys` feature.

**Comment by mysticatea** [comment]
Because to not break the core rules.

Vue.js templates have interpolations, floating JavaScript expressions, then those confuse the core rules seriously. Therefore, we have to separate the template's AST from the script.

**Comment by bradzacher** [comment]
interesting, that makes sense.

Is this something we should ignore entirely then from our end, or are there some cases we could potentially be supporting from within our plugin?
