### ISSUE TITLE
Bug: on the Rules page of the website, clicking any of the filter scrolls the page to the top if #hash is present in the URL

### ISSUE THREAD

**Issue by andreww2012** [typescript-eslint/typescript-eslint#7684]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

website

### Repro Code

- Go to https://typescript-eslint.io/rules/ in the latest Firefox or Chrome on desktop.
- Click "Extension Rules" on the right.
- Activate any of the filters, for example click "Config Group" -> "recommended".
- Page scrolls to the top (but the chosen filter will be applied). This only happens when `#hash` is present in the URL. `#hash` can be any non-empty string, not specifically ID of the sections listed in the right column.

**Comment by artur-janik** [comment]
Small change is required to preserve hash during filter selection. I can drop PR if maintainers can triage this issue.

(Sorry for preemptive PR - didn't know it will get linked to issue when I make it to my fork, and not to original repo 😢)

**Comment by JoshuaKGoldberg** [comment]
Ah, shoot, sorry - missed this! I think this was solved by #7666 actually. So, this was a 👍 issue when it was filed, but was superseded by the removal of the second table.
