### ISSUE TITLE
Rule proposal: enforce consistent optional chaining

### ISSUE THREAD

**Issue by lifeiscontent** [typescript-eslint/typescript-eslint#7689]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I'd like to see a rule implemented that enforces consistent optional chaining rules on types that are defined as non-optional.

### Fail Cases

```typescript
type Example = {
  foo: {
    bar: {
      baz: boolean
    }
  }
}

const example: Example = { foo: { bar: { baz: true } } };

// error because type says its defined
if (example?.foo?.bar?.baz) {
}
```

### Pass Cases

```typescript
type Example = {
  foo: {
    bar: {
      baz: boolean
    }
  }
}

const example: Example = { foo: { bar: { baz: true } } };

// pass because type says its defined
if (example.foo.bar.baz) {
}
```

**Comment by JoshuaKGoldberg** [comment]
Looks like a duplicate of https://typescript-eslint.io/rules/no-unnecessary-condition, no?

**Comment by lifeiscontent** [comment]
@JoshuaKGoldberg ah, I didn't realize this rule existed, yes, this covers my case. Thank you!
