### ISSUE TITLE
Bug: [class-methods-use-this] Cannot detect a problematic case for private/protected members if `ignoreClassesThatImplementAnInterface` option is `true`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [typescript-eslint/typescript-eslint#7704]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.2&showAST=es&fileType=.ts&code=JYOwLgpgTgZghgYwgAgEJysg3sgUM5OACgEoAuZANwHtgATAblwF9dcEAbOAZ2%2BQEFkwALYAHDhGERwfdJhz5CpCjXrZkrAqKjBKcSMgBGyqrTrZWzIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6M%2BAQ2WVoFtE%2BABYB7ACa9YyRLWGVUGANqQA7p2hNIAGkzhsEVqyiUA5kxHREAeQBuiaFTGIAsoNET0YfHERa9%2ByFNzSwBhLh4UABUhTnwAST5iJAEWAEEmOJZ7ADNOMkRPb1hEfzAAXwBdPTKQMqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```typescript
interface Bar { 
  a(): void;
}

class A implements Bar { 
  a(): void { }
  private b(): void {}
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/class-methods-use-this": ["warn", {
      "ignoreClassesThatImplementAnInterface": true
    }]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

I think the rule should warn about the implementation of `A.b()` in the above code.
Because TypeScript's _interface_ feature does not have any `private`/`protected` member as a part of it.

So the rule enabling `ignoreClassesThatImplementAnInterface=true` should warn the case of that the implementation is not a part of interface.

### Actual Result

In the above code, the rule does not warn about implementation of `A.b()`.

**Comment by JoshuaKGoldberg** [comment]
👋 sorry for the delay on triaging this. The issue as reported makes sense, but the option does explicitly say to ignore _classes_ that implement an interface. As in, the entire class.

What do you think about either of:

* Making the option more granular: like `boolean | "public-fields"`?
* Swapping the option with a new one named `ignoreFieldsThatImplementAnInterface`?

cc @typescript-eslint/triage-team

**Comment by bradzacher** [comment]
I hate the entire rule personally so I'm not miffed either way 🙃

Technically, yes, interface members can only be implemented with public members - so the rule option could be more targeted without causing issues for people.

**Comment by tetsuharuohzeki** [comment]
@JoshuaKGoldberg 

Thank you for your response.

> Making the option more granular: like `boolean | "public-fields"`?

I think this option is simple.

I feel that the new option named like `ignoreFieldsThatImplementAnInterface` gives a impression to user that this rule uses a type information and works strictly.

And I'll update a work-in-progress changes in the pull request.

**Comment by JoshuaKGoldberg** [comment]
Ok coming back to this! Nobody's posted an opposing viewpoint so 👍 let's go with what you have now. Good stuff.
