### ISSUE TITLE
Docs: <a short description of my proposal>

### ISSUE THREAD

**Issue by dimauloagustin** [typescript-eslint/typescript-eslint#7725]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Incorrect and correct examples are the same

![image](https://github.com/typescript-eslint/typescript-eslint/assets/54478512/4f67c2d6-15c6-4e68-80c2-9d1932dfeada)
![image](https://github.com/typescript-eslint/typescript-eslint/assets/54478512/b970de8b-847c-4b44-abd9-7e24ff81b0b7)

### Affected URL(s)

https://typescript-eslint.io/rules/prefer-optional-chain

**Comment by bradzacher** [comment]
It's verbose but correct.
You can try it in the playground. When the options are on/off the code is invalid/valid.

---

Also please fill out issue title when filling an issue
