### ISSUE TITLE
Bug: [strict-boolean-expressions] autofix can be incorrect with allowNullableObject set to false

### ISSUE THREAD

**Issue by barroudjo** [typescript-eslint/typescript-eslint#7743]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.2&fileType=.tsx&code=LAKAxg9gdgzgLgAgGYQgIwIYCcEF4EYwCeUYCAFEgK6kD8AXBQJR4B8CUVANly7uwG9QCBJFiIkASygYuAMRplcwkckUIAPhpUjy5Pu048mAbhVYApnCpYoyabIWl9ZkAF8TQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYkACAXAngA4oDG0AlobgLQrzkB2uA9MrhSTQEYD2PSAQwa0AHoWgpk5Hg1QYA2pETRoPaJAA0mcBCgD48HgHcAyu0YBzdGABm%2B5Ig06IkfYaMA5WAFsuy63bwDk66egbGXgYCXEgA8lwAVoicAfaOzmHukfDRSABCfIIMqUHpoa7hngg5MYhmFAxWGIHBGRVZ1bmIXr7%2BzWkhuu0RnbUAogw%2BJa3lbsYAggz402VDc0YASgiIACo8WwwA6uS4ABY8sLj15JzZAMKnyQDWyACSANIMxoenAriv828ABEeJYVhkIABfAC6kJAkKAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```typescript
const foobar = async (func?: () => null) => {
  const finalFunc =
    func ||
    (() => null);
  return finalFunc();
};
```

### ESLint Config

```javascript
module.exports = {
  "rules": {"@typescript-eslint/strict-boolean-expressions": ["error", {
    "allowString": false,
    "allowNumber": false,
    "allowNullableObject": false,
    "allowNullableBoolean": false,
    "allowNullableString": false,
    "allowNullableNumber": false,
    "allowNullableEnum": false,
    "allowAny": false,
    "allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing": false
      }]}
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

The auto fix introduces a bug in this case, as it replaces `func || (() => null);` with `func != null  || (() => null);` which is now either a boolean or a function, when the original code was such that it always resulted in a function.

In this case there should be no auto fix, or the actual fix is to use nullish coalescing (`func ?? (() => null);`), but that seems a bit beyond the scope of this rule...

### Actual Result

The auto fix introduces a bug in this case, as it replaces `func || (() => null);` with `func != null  || (() => null);` which is now either a boolean or a function, when the original code was such that it always resulted in a function.

**Comment by bradzacher** [comment]
My comment still applies - the code you want is `func ?? (() => null)` 


but yes, there should not be an autofixer for this case.

**Comment by kirkwaiblinger** [comment]
This was fixed by changing the fix to a suggestion in https://github.com/typescript-eslint/typescript-eslint/issues/7312 / https://github.com/typescript-eslint/typescript-eslint/pull/7394

Closing as duplicate.
