### ISSUE TITLE
Rule proposal: Ensure yield on call to generator function

### ISSUE THREAD

**Issue by Bartel-C8** [typescript-eslint/typescript-eslint#7749]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

My suggested rule would check that every call to a generator, inside another generator is called with yield

### Fail Cases

```typescript
function* parentGenerator(){
  console.log("parentGenerator:: start");
  childGeneratorOne();
  yield* childGeneratorTwo();
  console.log("parentGenerator:: end");
}

function* childGeneratorOne(){
  console.log("childGeneratorOne:: start");
}

function* childGeneratorTwo(){
  console.log("childGeneratorTwo:: start");
}

const itr = parentGenerator();
console.log(itr.next());
```

### Pass Cases

```typescript
function* parentGenerator(){
  console.log("parentGenerator:: start");
  yield* childGeneratorOne();
  yield* childGeneratorTwo();
  console.log("parentGenerator:: end");
}

function* childGeneratorOne(){
  console.log("childGeneratorOne:: start");
}

function* childGeneratorTwo(){
  console.log("childGeneratorTwo:: start");
}

const itr = parentGenerator();
console.log(itr.next());
```

### Additional Info

In the failing case, the `childGeneratorOne` is never called, which you won't expect if you miss that `yield` is lacking...

Was suggested before https://github.com/eslint/eslint/issues/5193 but, as described in the issue, type info is needed to make this work.

**Comment by Bartel-C8** [comment]
Own (working for my code-base) attempt of creating this rule.
But this is my first eslint rule ever, so don't know about the quality of it...

Inspired by:

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/rules/require-await.ts
and
https://github.com/pke/eslint-plugin-redux-saga/blob/master/lib/rules/no-yield-in-race.js

```
const { AST_NODE_TYPES, TSESLint, TSESTree } = require("@typescript-eslint/experimental-utils");
const tsutils = require("tsutils");
const util = require("@typescript-eslint/eslint-plugin/dist/util");

module.exports = {
  meta: {
    type: "suggestion",
    docs: {
      description: "Disallow calling generator functions without `yield` expression",
      recommended: "error",
      requiresTypeChecking: true,
      extendsBaseRule: true,
    },
    hasSuggestions: true,
    schema: [],
    messages: {
      missingYield: "{{name}} has no 'yield' expression.",
    },
  },
  defaultOptions: [],
  create(context) {
    const parserServices = util.getParserServices(context);
    const checker = parserServices.program.getTypeChecker();

    const sourceCode = context.getSourceCode();
    let scopeInfo = null;

    function isGenerator(node) {
      const tsNode = parserServices.esTreeNodeToTSNodeMap.get(node);
      const type = checker.getTypeAtLocation(tsNode);
      const symbol = type.getSymbol();
      let gen = false;
      if (symbol?.getName() === "Generator") {
        gen = true;
      }
      return gen;
    }

    function checkExpression(node) {
      const expression = node.expression;
      if (!scopeInfo) return;

      if (scopeInfo.isGen) {
        let type = expression.type;
        if (type === "CallExpression") {
          const isGenExp = isGenerator(expression);

          if (!isEmptyFunction(expression) && isGenExp)
            context.report({
              node,
              loc: getFunctionHeadLoc(node, sourceCode),
              messageId: "missingYield",
              data: {
                name: "Generator function " + expression.callee.name,
              },
              suggest: [
                {
                  desc: "Add yield*",
                  fix: function (fixer) {
                    return fixer.insertTextBefore(expression, "yield* ");
                  },
                },
                {
                  desc: "Add yield",
                  fix: function (fixer) {
                    return fixer.insertTextBefore(expression, "yield ");
                  },
                },
              ],
            });
        }
      }
    }

    /**
     * Push the scope info object to the stack.
     */
    function enterFunction(node) {
      if (scopeInfo) scopeInfo.hasYield = false;
      scopeInfo = {
        upper: scopeInfo,
        hasYield: false,
        name: node.id?.name ?? node?.argument?.callee?.name ?? node.callee?.name,
        // hasAsync: node.async,
        isGen: node.generator || false,
        // isAsyncYield: false,
      };
    }

    /**
     * Pop the top scope info object from the stack.
     * Also, it reports the function if needed.
     */
    function exitFunction() {
      /* istanbul ignore if */ if (!scopeInfo) {
        // this shouldn't ever happen, as we have to exit a function after we enter it
        return;
      }
      scopeInfo = scopeInfo.upper;
    }

    return {
      FunctionDeclaration: enterFunction,
      FunctionExpression: enterFunction,

      ExpressionStatement: checkExpression,

      "FunctionDeclaration:exit": exitFunction,
      "FunctionExpression:exit": exitFunction,

      ReturnStatement() {
        // short circuit early to avoid unnecessary type checks
        if (!scopeInfo || !scopeInfo.isGen) {
          return;
        }
      },
    };
  },
};

function isEmptyFunction(node) {
  return node.body?.type === AST_NODE_TYPES.BlockStatement && node.body.body.length === 0;
}

// https://github.com/eslint/eslint/blob/03a69dbe86d5b5768a310105416ae726822e3c1c/lib/rules/utils/ast-utils.js#L382-L392
/**
 * Gets the `(` token of the given function node.
 */
function getOpeningParenOfParams(node, sourceCode) {
  return util.nullThrows(
    node.id
      ? sourceCode.getTokenAfter(node.id, util.isOpeningParenToken)
      : sourceCode.getFirstToken(node, util.isOpeningParenToken),
    util.NullThrowsReasons.MissingToken("(", node.type)
  );
}

// https://github.com/eslint/eslint/blob/03a69dbe86d5b5768a310105416ae726822e3c1c/lib/rules/utils/ast-utils.js#L1220-L1242
/**
 * Gets the location of the given function node for reporting.
 */
function getFunctionHeadLoc(node, sourceCode) {
  const parent = util.nullThrows(node.parent, util.NullThrowsReasons.MissingParent);
  let start = null;
  let end = null;

  if (node.type === AST_NODE_TYPES.ArrowFunctionExpression) {
    const arrowToken = util.nullThrows(
      sourceCode.getTokenBefore(node.body, util.isArrowToken),
      util.NullThrowsReasons.MissingToken("=>", node.type)
    );

    start = arrowToken.loc.start;
    end = arrowToken.loc.end;
  } else if (parent.type === AST_NODE_TYPES.Property || parent.type === AST_NODE_TYPES.MethodDefinition) {
    start = parent.loc.start;
    end = getOpeningParenOfParams(node, sourceCode).loc.start;
  } else {
    start = node.loc.start;
    end = getOpeningParenOfParams(node, sourceCode).loc.start;
  }

  return {
    start,
    end,
  };
}
```

**Comment by bradzacher** [comment]
The reason that there are rules around promises and floating promises is because forgetting to `await` or `catch` a promise can lead to various classes of bugs like out-of-order actions, missing side-effects, or unhandled promise rejections. There's also the possibility of memory leaks and things like that.

However plain old generators aren't async - they're just a function call that creates an object on the stack. If you don't `yield` them and don't store them anywhere - then the generator object is just discarded and GC'd. Really a generator is just a plain old function call - so it follows the same rules - they should be considered in the same class as "pure functions" and thus their return value must be used.

I can envision some usefulness behind a `no-floating-generator` rule where top-level function calls taht return generators must be `yield`ed or similar - but it's also kinda niche too - generators don't see a whole lot of use in the broad scope of userland code.

cc @typescript-eslint/triage-team

**Comment by Bartel-C8** [comment]
Thanks for your response.

The reason we use generator functions, quite much actually, is because of redux-saga: https://www.npmjs.com/package/redux-saga

With 1M downloads a week, I won't say it's that niche.


As shown in my example, the behaviour is the same as you describe: If I don't yield the generator function, it's never been executed.
And I think the rule I created does check that? 👎 

If, inside a generator function, a function is being called (CallExpression) I check whether the called function is a generator as well. If it is, a yield should be performed of it, if not: error.

**Comment by bradzacher** [comment]
1m per week is just 4% of our plugin's userbase (~23m)!
It's 2% of TS's total userbase (~42m).
It's ~5% of React's total userbase (~21m).

1m sounds like a lot but compared to the entire ecosystem it's pretty niche!

Of that 1m you also need to consider that the scope of users for the rule would be the intersection of "users that use redux-saga", "users that use typescript", and "users that use our plugin" - so it will be a smaller number than 1m.

Not saying it's not worth building - just providing some context and perspective!

**Comment by JoshuaKGoldberg** [comment]
Yeah. Usage of redux-saga, etc. is also falling over time as Redux is no longer as common of a recommendation for React apps as it used to be. https://npmtrends.com/redux-saga shows that it's held steady or slightly decreased over 2023. Packages that are still actively used generally grow instead of hold steady.

One of the reasons why redux-saga isn't recommended as much is that developers have a hard time with generators and iterators. It's a topic that's hard to get type safety in and easy to mess up. So most state tools have drifted away from the redux-saga approach of suggesting them.

Meanwhile, every rule added to typescript-eslint increases the maintenance cost of the project and increases the size of its documentation. Both of which are a little negative for users. So we're hesititant to add rules that don't have a wide user appeal.

All this is to say: the rule idea is good, but we suspect should exist in a third party plugin that you create using the docs we provide at https://typescript-eslint.io/developers/custom-rules. Adding `evaluating community engagement` to see if enough folks speak up to indicate we're wrong about that. 🙂

**Comment by Josh-Cena** [comment]
This looks very much like https://github.com/typescript-eslint/typescript-eslint/issues/1068. Can we call it a duplicate?

**Comment by JoshuaKGoldberg** [comment]
Oh! Nice spot @Josh-Cena. Yes.

Furthermore, #1068 has been open and accepting PRs for four years (long before the `evaluating community engagement` label was createed) and only has the one 👍. We don't have any hard interaction minimums for engagement, but less than one positive indicator per year is pretty low.

Closing as out-of-scope: but if common JS patterns shift to using generators more, we'd be happy to take this rule in. Cheers!

**Comment by Bartel-C8** [comment]
Thanks for the active and constructive discussion.

Will try to contribute it to the redux-saga eslint plugin then https://github.com/pke/eslint-plugin-redux-saga
