### ISSUE TITLE
Enhancement: [no-explicit-any] Option to disable rule for generic constraints (revisited)

### ISSUE THREAD

**Issue by ksandin** [typescript-eslint/typescript-eslint#7751]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-explicit-any/

### Description

I'd like to revisit [this issue](https://github.com/typescript-eslint/typescript-eslint/issues/642) for adding an option to the `no-explicit-any` rule that allows the use of `any` as generic constraint. That issue was seemingly closed by a bot, so I'm not even sure if that issue reached a real consensus. Also, I've written a few code examples that I think add some value to the discussion, which is why I'm opening this issue even if there's technically another existing (closed) issue.

> Disclaimer: Before anyone mentions it, I'm aware that [this PR in the typescript repo](https://github.com/microsoft/TypeScript/pull/26349) exists and would solve all problems below if merged, but It's been around since 2018 and it's unsure when or if it is going to get merged, so I still think this discussion is worth having.

## Example 1: Non-exported types in 3rd party packages

When integrating with 3rd party typescript packages, it's unfortunately common for packages to not expose all the types the consumer may need. While this is a fault in those packages, I think we have to be pragmatic and acknowledge that this is a common enough problem to justify a workaround.

Let's imagine the package `example-package` that doesn't export a generic constraint type:
```typescript
type Generics = { a: unknown; b: unknown; c: unknown; };
export type Foo<G extends Generics> = {
  generics: G;
}
```

This is what it would look like to consume this package:

### Strategy 1: Using `never` as generic constraint

Using `never` makes the constraint too specific and the function now only accepts `Foo<never>`

```typescript
import { Foo } from "example-package";

declare function useNever<T extends Foo<never>>(arg: T): void;
useNever({ generics: {a: 123, b: 123, c: 123} });
//            ^ Type '{ a: number; b: number; c: number; }' is not assignable to type 'never'.(2322)
```

### Strategy 2: Using `unknown` as generic constraint

Using `unknown` requires us to reconstruct the type used for the generic constraint while using `unknown` everywhere. 

```typescript
declare function useUnknown<T extends Foo<{a: unknown, b: unknown, c: unknown}>>(arg: T): void;
```

This actually works. Neither Typescript or typescript-eslint yields errors, but this is unnecessarily verbose when all I want is to tell typescript that `useUnknown` should accept any form of `Foo`. It's also brittle, since I have to redefine implementation details of the 3rd party package. If the package refactors their internal type definitions, I will have to refactor my code.

### Strategy 3: Using `any` as generic constraint

Finally let's try using `any`. It gives us the best developer experience. It applies the generic constraint we want, is terse and not brittle, and without yielding any typescript errors. However, unfortunately, typescript-eslint complains if you have `no-explicit-any` enabled.

```typescript
declare function useAny<T extends Foo<any>>(arg: T): void;
```

## Example 2: The same problem can still occur even if you own all the type definitions

Let's say we have this builder pattern:

```typescript
type GenericKeys = "a" | "b" | "c"
interface Generics<
  A extends unknown[],
  B extends unknown[],
  C extends unknown[]
> {
  a: A,
  b: B,
  c: C,
}

declare class Builder<Values extends Generics<unknown[], unknown[], unknown[]>> {
  readonly values: Readonly<Values>;
  add <AddTo extends GenericKeys, Added>(): Builder<{
    [K in GenericKeys]: K extends AddTo ? [...Values[K], Added] : Existing[K]
  }>
}

const builder = new Builder<{a: [], b: [], c: []}>()
  .add<"a", number>()
  .add<"a", string>()
  .add<"b", boolean>()
  .add<"b", null>()

// ^ Builder<{ a: [number, string]; b: [boolean, null]; c: []; }>
```

Now we want to define some functions that accepts generic variants of this Builder type. Observe that if we try the same strategies as in Example 1, we'll experience the exact same problems:

### Strategy 1: Using `never` as generic constraint

```typescript
declare function useNever<B extends Builder<never>>(builder: B): void;
useNever(builder);
// ^ Argument of type 'Builder<{ a: [number, string]; b: [boolean, null]; c: []; }>' is not assignable to parameter of type 'Builder<never>'
```

### Strategy 2: Using `unknown` as generic constraint

Once again, this works, but is as verbose and brittle as mentioned in Example 1.

```typescript
declare function useUnknown<B extends Builder<Generics<unknown[], unknown[], unknown[]>>>(builder: B): void;
useUnknown(builder)
```

### Strategy 3: Using `any` as generic constraint

Once again, `any` as generic constraint is the winner:

```typescript
declare function useAny<T extends Foo<any>>(arg: T): void;
```

# eslint test cases

### Fail

```typescript
// Using `any` outside of generic constraints should still be an error
const foo: any = 123;
function fn (arg: any) { }
```

### Pass

```typescript
// But using `any` inside a generic constraint should be valid
function fn<T extends any>(arg: T) { }
```

**Comment by bradzacher** [comment]
> That issue was seemingly closed by a bot, so I'm not even sure if that issue reached a real consensus.

No, it was locked by a bot.
It was closed by me. [Was my closing comment ambiguous?](https://github.com/typescript-eslint/typescript-eslint/issues/642#issuecomment-505063715)

The comments after closing were all people suggesting example of why you 100% had to use any, followed by us countering with ways to explicitly avoid the `any`.

----

For example 1 there exists a much, much simpler option - patch the package to export the type. Modern package managers support patching out of the box - so it's trivial to locally create a patch for your version and then create a PR for the package from that patch.

This avoids the need for any shenanigans or type gymnastics.

----

For example two - it depends what your goal is. If your goal is to have correct code - then strategy 2 is the correct option.

You have also skipped over an even better solution. You have clearly defined a type where the generics are optional - hence you're happy to pass `any` to "shut the checker up".

So if the generics are optional define them as such.

```ts
interface Generics<
  A extends unknown[] = unknown[],
  B extends unknown[] = unknown[],
  C extends unknown[] = unknown[]
> {
  a: A,
  b: B,
  c: C,
}

class Builder<Values extends Generics = Generics> {...}

declare function useBuilder<B extends Builder>(builder: B): void;
```

Now you no longer need to define any generics and can pass everything through concisely whilst still having the option to pass generics if required.

**Comment by bradzacher** [comment]
You have to be really careful with `any`. It's very easy to create constraints that allow much wider code than you intended.

In your specific example of "a builder type that only uses the generic as a mapped type" - sure there's a lot of implicit safety built in specifically in the way that things are structured.

However if you enable such an option you're opening the door to simpler usecases in your codebase and you can introduce unsafe code very easily.

For example your first example is COMPLETELY UNSAFE.

```ts
useAny({
  gemerics: 1,
// ts does not error here even though 1 clearly does not satisfy the generic object constraint.
});
```
[PLAYGROUND](https://www.typescriptlang.org/play?#code/C4TwDgpgBA4hB2EBOBLAxgZygXigbygEMAuKAV3gGt4B7Ad3gG4oAjUi6+pqNdq2hswC+jAFAQAHmBpJgUUJCgAxGjQA8MKJOAIAJljiJUmAHw58oqFADmCZOgykYYoaNG6IaADaEk0AGYUaMAoNPDkGBAAgvAgagAqWhI68PrKqmqEsSYmABS+1qTxAJSkAG40KLpiomSRMSC5eJZWNnbGjlAAjKJCxaJAA)

It is not safe to just enable the use of `any` in generic constraints. And as such you should only use it very, very sparingly. This usecase is covered - use a disable comment to expliclty opt-out of the rule in those specific cases and provide reviewers with context as to why using `any` in that specific case is safe.

**Comment by ksandin** [comment]
thanks @bradzacher That final playground is a super example of why even in generic constraints we shouldn't be using `any`. TIL! Thanks for the quick response and great insight!

**Comment by JoshuaKGoldberg** [comment]
Relevant for the exported types point: https://github.com/typescript-eslint/typescript-eslint/issues/7670
