### ISSUE TITLE
Enhancement: [lines-between-class-members] Add decorated class members as option

### ISSUE THREAD

**Issue by btxtiger** [typescript-eslint/typescript-eslint#7760]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/lines-between-class-members/

### Description

The base rule supports `method`, `field` and `*` as config options.
https://eslint.org/docs/latest/rules/lines-between-class-members

However this makes it impossible to target decorated typescript properties, which can get quite blocky in some cases.
So my suggestion would be to add the options `decorated_method`, `decorated_field`, `decorated_*`.

### Fail

```typescript
@Input() 
public param1: Subject<number> = new Subject<Number>;
@Input() 
public param2: Subject<boolean> = new Subject<boolean>;
@Input() 
public param3: Subject<string> = new Subject<string>;
```

### Pass

```typescript
@Input() 
public param1: Subject<number> = new Subject<Number>;

@Input() 
public param2: Subject<boolean> = new Subject<boolean>;

@Input() 
public param3: Subject<string> = new Subject<string>;
```

### Additional Info

Original issue: https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/issues/709

**Comment by JoshuaKGoldberg** [comment]
Hmm, https://github.com/tc39/proposal-decorators is still stage 3, and ESLint core won't add features for them until stage 4 (https://github.com/eslint/eslint#what-about-experimental-features). But I'm hesitant to add a feature here in the meantime that may conflict with what ESLint chooses...

Anyway, this is one of the rules noted with _We strongly recommend you do not use this rule or any other formatting linter rules. Use a separate dedicated formatter instead. See [What About Formatting?](https://typescript-eslint.io/linting/troubleshooting/formatting) for more information._. It might eventually be moved to https://eslint.style. So unless there's a strong documented user need for this option, we'll want to hold off I think. Adding `evaluating community engagement` to see if many folks want this.

Thanks for filing!

**Comment by bradzacher** [comment]
Hi there 👋!

As you may have heard [ESLint core is deprecating its formatting rules](https://eslint.org/blog/2023/10/deprecating-formatting-rules/). We are likewise moving in the same direction and deprecating our formatting rules.

Deprecated rules will be removed in the next major version as their new home is the [eslint-stylistic](https://github.com/eslint-stylistic/eslint-stylistic) project.

If this issue is important to you please consider filling an issue over at eslint-stylistic which will be the new home for stylistic/formatting rules.

Thanks!
