### ISSUE TITLE
Bug: [switch-exhaustiveness-check] Some cases for member names are not being fixed properly

### ISSUE THREAD

**Issue by StyleShit** [typescript-eslint/typescript-eslint#7768]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&showAST=es&fileType=.tsx&code=KYOwrgtgBAglDeAoKUBCUC8UCMAaZUA5AMIC0ATIZlOfigNoAGAIqQMyMC61bdUTAUVKIRKACxdqY-AF8RAE2ABjADYBDAE7AoSgPYgAzgBcoagFywRBgO4BLI0oAWUABRqAlAgJK1B7TAA6VAt4KCNHDV1rKBBgaIENSI0XQgA5XRNbCAAHFWAIUCNgeSgAT2AjC0D0Hz9CTzkZIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6ZAd0vzIAt6AHrwCGsZPkoA3RExTJafRGQDW6KImjQA9tEjgwAXxAGgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

Run the fixer and you'll notice the issue

### Repro Code

```typescript
enum A {
  B = 1,
  'C-2' = 2,
  [`D-3`] = 3,
  [`E-


  4`] = 4,
}

declare const a: A

switch (a) {
  case A.B: { throw new Error('Not implemented yet: A.B case') }
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/switch-exhaustiveness-check": ["error"],
  },
};
```

### Expected Result

Probably this?

```JS
switch (a) {
  case A.B: { throw new Error('Not implemented yet: A.B case') }
  case A['C-2']: { throw new Error('Not implemented yet: A[\'C-2\'] case') }
  case A['D-3']: { throw new Error('Not implemented yet: A[\'D-3\'] case') }
  case A[`E-


  4`]: { throw new Error('Not implemented yet: A[`E-


  4`] case') }
}
```

### Actual Result

```JS
switch (a) {
  case A.B: { throw new Error('Not implemented yet: A.B case') }
  case A['C-2']: { throw new Error('Not implemented yet: A['C-2'] case') }
  case A['D-3']: { throw new Error('Not implemented yet: A['D-3'] case') }
  case A['E-


  4']: { throw new Error('Not implemented yet: A['E-


  4'] case') }
}
```

**Comment by JoshuaKGoldberg** [comment]
Really, really amusing 😂. Nice spot. Thanks for investigating this thoroughly from #7691!
