### ISSUE TITLE
How to resolve TSTypeReference?

### ISSUE THREAD

**Issue by aloifolia** [typescript-eslint/typescript-eslint#781]
I am not sure where to post this question. So feel free to point me somewhere else. I am writing eslint rules for a Typescript-based project. Currently, I am stuck with trying to resolve Type Nodes. Specifically, if you have a Node with the type "TSTypeReference", how do you resolve this type? How do I find the type declaration node that is being referred? And what do I do if the type was imported, is it possible to get the declaration node from a different file?

**Comment by bradzacher** [comment]
What is your use case? Would the rules be something that could live within this repo as something more widely available?

----

There's no better place to look than our plugin source code.
The readme will show you which rules use type information, and you can investigate their source code for examples on consuming type information.

the basics:
```ts
if (
    !context.parserServices ||
    !context.parserServices.program ||
    !context.parserServices.esTreeNodeToTSNodeMap
  ) {
    /**
     * The user needs to have configured "project" in their parserOptions
     * for @typescript-eslint/parser
     */
    throw new Error(
      'You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.',
    );
}

const typeChecker = context. parserServices.program.getTypeChecker();
const typescriptNode = context.parserServices.esTreeNodeToTSNodeMap.get(node);
const type = typeChecker.getTypeAtLocation(typescriptNode);
```

> And what do I do if the type was imported, is it possible to get the declaration node from a different file

Essentially typescript types have no concept of what is local or imported. Once it's imported into a file, from the perspective of type datastructures, it's treated as if the definition was done locally.

---

As for the rest, I would spend some time reading the [documentation](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker), looking at our rules, and inspecting the type definitions included with typescript itself.

---

closing for housekeeping reasons because it's not an open bug, we can continue discussing though.

**Comment by aloifolia** [comment]
Thank you, that is a good starting point. For my purposes, the tsutils library was particularly helpful. The rules I am writing are something very project specific. They are intended to be used for writing opinionated Angular components. So this will not fit here.

Question: I was wondering, if it is possible to use the typescript inference mechanism in order to determine subtyping relationships conveniently. One of my rules tries to determine whether specific fields in classes are deeply immutable (as suggested [here](https://github.com/Microsoft/TypeScript/issues/13923)):

```ts
class MyComponent {
  // cannot be mutated
  public readonly field1: string;

  // can be mutated
  public readonly field2: { a: { c: number }};

  // cannot be mutated, the mapped type DeepReadonly enforces immutability
  public readonly field3: DeepReadonly<{ a: { c: number }}>;

  // cannot be mutated
  public readonly field4: { readonly a: { readonly c: number }};
```

Currently, I just check, whether the field types are some kind of primitive type. If that is not the case, I check whether the printed type is actually 'DeepReadonly' (in simplified terms - actually I check each part of a possible union type...).

Rather than examining each possible case separately, I would like to do something like this:

```
// project code
type DeepReadonly<T> = ...

// eslint code
const compiledDeepReadonlyType = ts.isSubType(fieldType, deepReadonlyType);
```

Any idea if there is some hidden api to achieve that?

**Comment by bradzacher** [comment]
If I'm understanding, you're looking for somethinglike: https://github.com/microsoft/TypeScript/issues/9879
If that's correct, then the answer is, nope - not yet unfortunately.

There is the https://www.npmjs.com/package/ts-simple-type library, which IIRC has duplicated typescript's code to expose the internal typescript APIs which do it.

Aside from that, I think you should be able to get the resolved type, and then recursively check the properties for mutability? That way you're not requiring that users have to use a specific type.

**Comment by aloifolia** [comment]
Good to know!

Recursive checks where also what I had in mind but gave up because I was unable to find any helper in the TS API to check for "readonly-ness" of arrays and object properties. IndexInfo has a field `isReadonly`. However, I struggle to get this info in the first place 🤷 (if this is even the right place to look).

**Comment by ajafff** [comment]
> IndexInfo has a field isReadonly. However, I struggle to get this info in the first place 🤷 (if this is even the right place to look).

There's more to it. There are dozens of ways a property can be readonly.

> I was unable to find any helper in the TS API to check for "readonly-ness" of arrays and object properties

That's because there is none, see https://github.com/microsoft/TypeScript/issues/31296

But there's an alternative in `tsutils`: https://github.com/ajafff/tsutils/blob/5ee2bd90fc8f2b703c13ce09b28245556b5f2d98/util/type.ts#L182-L183

> Recursive checks

Be careful with that. Types may expand infinitely. You need additional code to prevent infinite recursion.

**Comment by aloifolia** [comment]
So, as far as I understand, the tsutils function `isPropertyReadonlyInType` analyzes the type structure und tries to mimic the reasoning of the Typescript compiler. This approach seems to fail short for recursive mapped types (there might be other cases, as well). Suppose you have the following DeepReadonly definition:

```ts
export type DeepReadonly<T> = T extends object
    ? {
          readonly [Key in keyof T]: T[Key] extends object ? DeepReadonly<T[Key]> : T[Key];
      }
    : T
```

And you have this type: 

```ts
type t = DeepReadonly<{ a: { b: boolean } }>
```

Furthermore you have this function to determine whether nested properties are readonly:

```ts
function isEveryNestedPropReadonly(
    type: ts.Type,
    typeChecker: ts.TypeChecker,
): boolean {
  // ... code which catches other types like primitives omitted here

  return type.getProperties().every(property => {
        return (
            // this succeeds for 'a' but fails for 'a.b'
            isPropertyReadonlyInType(type, property.escapedName, typeChecker) &&
            isEveryNestedPropReadonly(
                typeChecker.getTypeAtLocation(property.declarations[0]),
                typeChecker,
            )
        );
    }); 
}
```
t.a will then be inferred to be readonly which is correct. However, for t.a.b, the function will state that it is not a readonly property, which is not correct.

There might be a problem with `typeChecker.getTypeAtLocation(property.declarations[0])` that I am not aware of, though.

**Comment by ajafff** [comment]
> There might be a problem with typeChecker.getTypeAtLocation(property.declarations[0]) that I am not aware of, though.

Indeed. `getTypeAtLocation` gives you the declared type and that is definitely not readonly.
You can try `typeChecker.getTypeOfSymbolAtLocation(property, node)` where `node` is `t` in your example.

**Comment by aloifolia** [comment]
Woah, that works, thank you! Now this is far better than checking for a specific type name (my first approach).
