### ISSUE TITLE
Repo: 'nohoist' is deprecated notice in Yarn

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7820]
### Suggestion

I just noticed this pops up in the top of the Yarn install logs:

```plaintext
joshgoldberg ~/repos/typescript-eslint $ .yarn/releases/yarn-3.6.4.cjs 
➤ YN0000: ┌ Project validation
➤ YN0057: │ @typescript-eslint/typescript-eslint: 'nohoist' is deprecated, please use 'installConfig.hoistingLimits' instead
➤ YN0057: │ website: Resolutions field will be ignored
```

https://yarnpkg.com/configuration/manifest#installConfig.hoistingLimits

**Comment by merceyz** [comment]
`deprecated` is probably the wrong word here as the field is ignored and has no effect so if everything works you can probably just remove it.
