### ISSUE TITLE
[naming-convention] support the auto-accessor syntax

### ISSUE THREAD

**Issue by MrHands** [typescript-eslint/typescript-eslint#7823]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.2&fileType=.tsx&code=KYDwDg9gTgLgBAYwDYEMDOa4FkCeBhVDOAbwFgAoASDCgEsA3FGYOAfSgFclgBJNAUQB2AM2gJgAEzgBeODE7AA3BQrUOAIyS0EcAObB4KBOIzR2XYK1ppWwEWMlwAFAEoSqylAMcoguQAtrADpzbj4hUShxCWUqAF8VKjANLR0jEzRoOABBQRwAJQtw%2ByjJAC44dQgIbhQ-WWEUJDQlCjigA&eslintrc=N4KABGBEAOCGBOBnApvSAuKABALgT2mUQGN4BLaHAWiIBsyA7HAejiVUgBpwppaBXAOaNEGMAG0eESLgJFSFanUY5IPALrdp8frSJjQEabMIlylGonpNmDWAFtGgqsQD2DAG7ImZd2MlGRpCo8K5oWoFghpHSKHrEOGFikMS0sIiiETGQAGZh9rCqmAExQQDKOOQJAArpxLC0AMLpyGqlYOpSRgC%2BWUbR2XHICUmYkLDExESISX2BufmF-l2DdgDWyAD69ShtpZ0xvStRx7HI8YloY-bI9gBGqAAyZBtcp1B58AVFEu-S9Tcmi09jFNO9IHpYAATJwAVQYUNQJDCrTGDVorgA7mUnHoAPLwAAirn4dz0IJ6cxO7UgQxGV1%2B7WkiJysF0qneYJpn2%2ByyZUAB52au05x26XQOYHF3SAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```typescript
export class MyClass {
	private _ruleIsEnforced = true;

	public get accessor_rule_is_enforced () {
		return this._ruleIsEnforced;
	}

	public accessor AnyRuleIsEnforced: boolean = false;
}
```

### ESLint Config

```javascript
module.exports = {
	'parser': '@typescript-eslint/parser',
	'plugins': [
		'@typescript-eslint'
	],
	'rules': {
		'@typescript-eslint/naming-convention': [
			'error',

			// classes
			{
				selector: 'class',
				format: ['StrictPascalCase'],
			},

			// accessor
			{
				selector: 'accessor',
				format: ['snake_case'],
			},

			// members
			{
				selector: 'memberLike',
				format: ['camelCase'],
				leadingUnderscore: 'allowSingleOrDouble',
			},

			// default
			{
				selector: ['default'],
				format: ['camelCase'],
			},
		],
	}
}
```

### Expected Result

Line 8 should report that the field must be snake_case (if caught by the accessor rule) or camelCase (if caught by the default rule).

### Actual Result

No errors are reported in this file.

**Comment by Josh-Cena** [comment]
I'm not sure if this should be `accessor` or `classProperty` or both, but we can discuss that in the implementation.
