### ISSUE TITLE
Repo: Sponsors job hasn't updated since July

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7824]
### Suggestion

https://github.com/typescript-eslint/typescript-eslint/commits/main/packages/website/data/sponsors.json: the last commit to `sponsors.json` was b1a23a9138c929f2d2ee885a945b0c19d3fbbb04 in July. It's October now. We should get that job running again.

**Comment by bradzacher** [comment]
this is running now
