### ISSUE TITLE
Docs: Add FAQs entry about running core ESLint rules on TypeScript code

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7827]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Surfacing discussion from https://stackoverflow.com/questions/77335691/custom-rule-for-typescript-eslint/77340147: there's nothing in the docs that explicitly states you don't need an extension rule for any core ESLint rule you want to use. I think the user in that thread has misconfigured their ESLint so that it's not running on TypeScript files. But the impression they got is that they need new extension rules

### Affected URL(s)

https://typescript-eslint.io/linting/troubleshooting. Maybe, specifically within https://typescript-eslint.io/linting/troubleshooting#one-of-my-lint-rules-isnt-working-correctly-on-a-pure-javascript-file.

**Comment by bradzacher** [comment]
> Hence, I thought of writing custom rule with help of ChatGPT

![sigh](https://media.tenor.com/isAU877x3g8AAAAC/neil-patrick-harris-sigh.gif)

**Comment by bradzacher** [comment]
Is such an FAQ necessary? If someone runs through the getting started guide I feel like this is pretty evident.

We recommend turning on eslint's recommended set which turns on core rules. Even if we don't explicitly state "hey you can use core rules just fine for the most part" it should be evident if they follow the steps. Eg they setup the config then run a lint run and core rules will report.

Additionally the (intentionally placed first) FAQ https://typescript-eslint.io/linting/troubleshooting#i-am-using-a-rule-from-eslint-core-and-it-doesnt-work-correctly-with-typescript-code again doesn't explicitly say so but implies that "rules will work unless they don't, and if they don't then do this".

This particular question feels like someone who didn't want to read the docs and used ChatGPT instead?

**Comment by bradzacher** [comment]
I guess also a FAQ answer should really be reserved for... **frequently**AQ - this is the first time ever I've seen this.

**Comment by JoshuaKGoldberg** [comment]
Maybe we can slightly change the wording of the existing answer to coincidentally answer this question? I anecdotally do feel that this has come up before.

**Comment by maqsudinamdar** [comment]
My question was more with specific rules not working with Typescript files, like below is my config file which giving only result of Javacript file for some rules, whereas I've many function above 20 lines. 

And, I had commented extends values in config file to only get output of specific rules.


```
module.exports = {
  extends: [
    // 'eslint:recommended', 
    // 'plugin:@typescript-eslint/recommended'
  ],
  parser: '@typescript-eslint/parser',
  plugins: [
    '@typescript-eslint'
  ],
  root: true,
  rules: {
    "max-lines-per-function": ["error", 20],
  },
};

```

Output:

```
$ npx eslint .
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.1.0

YOUR TYPESCRIPT VERSION: 3.1.6

Please only submit bug reports when using the officially supported version.

=============

/Users/maq5ud/Documents/sigtuple/mandara-ui/src/karma.conf.js
  4:18  error  Function has too many lines (41). Maximum allowed is 20  max-lines-per-function

✖ 1 problems (1 errors, 0 warnings)
```

**Comment by bradzacher** [comment]
By default eslint does not run on TS files - it only runs on JS files.
If you want it to run on TS files then you either need to use the `--ext` cli flag or use config `overrides` to select TS files. We do the latter for you automatically with our recommended config.

Also your TS version is way, way, way out of date and you're likely going to run into undefined behaviour unless you upgrade.

**Comment by JoshuaKGoldberg** [comment]
Closing as it's been a few months and this issue hasn't come up again. We can reopen if we get signal that we should. Thanks all!
