### ISSUE TITLE
Repo: File issues for any eslint-plugin-unicorn rules we should take into core

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7858]
### Suggestion

cc @sindresorhus - 👋 hi! I'm a big fan of https://github.com/sindresorhus/eslint-plugin-unicorn ❤️ and think some of the rules match this repo's minimum bars for inclusion (i.e. are logical and generally useful for most-to-all TypeScript codebases). It'd be nice to file issues for the rules

I don't have the time right now, but would encourage anybody reading this to go ahead and file an issue per rule using our [_✨ New Rule_ issue template](https://github.com/typescript-eslint/typescript-eslint/issues/new/choose). If you do, include a link to this issue so other folks reading this issue can more easily see it.

Separately, if there are rules in `eslint-plugin-unicorn` that are duplicates of rules in `typescript-eslint`, I'd encourage folks to file an issue over in `eslint-plugin-unicorn` asking about the duplication over there.

**Comment by JoshuaKGoldberg** [comment]
I went through with the criteria of finding logical rules that work differently in TypeScript ... and ended up just filing #8137 for this. If anybody is reading this and thinks another rule from `eslint-plugin-unicorn` would be good in typescript-eslint, please do file an issue. Cheers!

**Comment by bradzacher** [comment]
What's the goal with bringing this rule into our project? Can we make it better? Or is it just to centralise things? If it's just the latter - I don't think that's a good enough reason to fork/split things and churn the ecosystem.

**Comment by JoshuaKGoldberg** [comment]
I like the centralizing as a goal actually.

**Comment by JoshuaKGoldberg** [comment]
Whoops, meant to close with the comment.

For `typeof-undefined` specifically I was thinking we can use TypeScript-specific information to know whether the value is a global... but on second thought, that's just scope analysis. So it wouldn't be something we'd implement. I'll post in that issue.

For general centralization, I see typescript-eslint as the default since we have to be used with TypeScript - and Unicorn as an extra layer on top of ESLint core + typescript-eslint. So IMO if there's a rule that could exist in either, it would make sense to have that rule in core / typescript-eslint by default.
