### ISSUE TITLE
Bug: [consistent-indexed-object-style] Interface with recursive index signature autofixed to Record instead of mapped type

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7863]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.2&fileType=.ts&code=KYDwDg9gTgLgBDAnmYcCiICGBbMAbYAVQDsBLCYuAXjgCMIIDNKAfOYgV21uCgG4AUANCRYCZKgw58wAEoN4NKbgIlyrdFhXAA8rQBWwAMYxBw8NHiliMXgDNMRyVpl7DJuAG8BcOAG0Aa2BEAC44AGcYKGsAcwBdMOUZeQhTAQBfASA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6MgeyeUuX0Ra1mAE0QAPRMNocARgCtEZOn0JJ0URNGgdokcGAC%2BIA0A&tsconfig=&tokens=false

### Repro Code

```typescript
export type ExampleUnion = boolean | number;

export type ExampleRoot = ExampleUnion | ExampleObject;

export interface ExampleObject {
  [key: string]: ExampleRoot;
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/<rule-name>": ["error", ...<options>],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

This interface can be either be left as-is or auto-fixed to a mapped object type:

```ts
export type ExampleObject = {
  [key in string]: ExampleRoot;
};
```

### Actual Result

It's actually autofixed to `Record<string, ExampleRoot>`, which causes TypeScript to give complaints that `Type alias '(Example(Root|Object)' circularly references itself.`

https://typescript-eslint.io/play/#ts=5.2.2&fileType=.ts&code=KYDwDg9gTgLgBDAnmYcCiICGBbMAbYAVQDsBLCYuAXjgCMIIDNKAfOYgV21uCgG4AUANCRYCZKgw58wAEoN4NKbgIlyrdFhXAA8rQBWwAMYxBw8NHhIUm6QT2GT1OLOPQAJgB4AzjCiliAHMAGltteQgYAD5BIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6MgeyeUuX0Ra1mAE0QAPRMNocARgCtEZOn0JJ0URNGgdokcGAC%2BIA0A&tsconfig=&tokens=false

### Additional Info

I suspect this is in the same area as #4730 and #6598 but not quite the same.

Found while trying to enable the rule on typescript-eslint:

https://github.com/typescript-eslint/typescript-eslint/blob/4972ecd7ebf3ec1a74082607a2ad9d3e141d8ea9/packages/utils/src/json-schema.ts#L35-L38

**Comment by Josh-Cena** [comment]
The problem is, how do we detect if an interface is recursive? :(

**Comment by bradzacher** [comment]
You can detect the simple case easily enough using scope analysis. I.e. "if the type has a reference within its range - it's self referencing".

Its a bit more involved if you want to consider indirect cycles though as you need to follow all aliases. Doable but painful.

**Comment by JoshuaKGoldberg** [comment]
> Doable but painful

Story of half my bug reports or feature requests... marking as accepting PRs for cases that can be easily found with scope manager.
