### ISSUE TITLE
Website: Bump to Docusaurus v3

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7872]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

https://docusaurus.io/blog/releases/3.0

Whoohoo! Let's update 🥳 

### Affected URL(s)

_all of them_

**Comment by LeoDog896** [comment]
Unfortunately, bumping this also breaks the tabs and the internal plugin - HTML comments are no longer registered on the AST.

**Comment by Josh-Cena** [comment]
I would suggest migrating HTML comments to MDX comments, but maybe using the commonmark-compatibility mode would work. I haven't tried.

**Comment by LeoDog896** [comment]
MDX comments might work, but to get the tabs feature working again, it needs to be patched (the [author](https://github.com/mccleanp) seems to be inactive)
