### ISSUE TITLE
Docs: Mention import-no-unresolved as unnecessary in Performance Troubleshooting?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7894]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Spinning out of https://stackoverflow.com/questions/77435417/how-to-resolve-module-federation-import-paths-in-eslint-with-typescript: https://typescript-eslint.io/linting/troubleshooting/performance-troubleshooting/#eslint-plugin-import does not mention [`import/no-unresolved`](https://github.com/import-js/eslint-plugin-import/blob/6d34c88a91a9cb7556700b7cb83c8a27731ff302/docs/rules/no-unresolved.md). But it seems to me like `import/no-unresolved` is probably unnecessary when used with TypeScript, no? Perhaps we should add it to the list of avoidable rules?

### Affected URL(s)

https://typescript-eslint.io/linting/troubleshooting/performance-troubleshooting

**Comment by bradzacher** [comment]
It can be useful for some webpack setups so you can enforce css files and other assets exist. But by and large its no good yeah and super expensive due to the disk lookups.

At Canva though I whipped together a rule targeting just imports with asset extensions and it saved SO MUCH TIME

**Comment by JoshuaKGoldberg** [comment]
Great - let's add it in, with that caveat. https://github.com/import-js/eslint-plugin-import/blob/6d34c88a91a9cb7556700b7cb83c8a27731ff302/docs/rules/no-unresolved.md#ignore looks like it can be used to ignore extension-less imports?

**Comment by bradzacher** [comment]
@JoshuaKGoldberg I don't think so? Regexes aren't good for "negative" matchers. EG I don't think you can craft a regex that says "match all imports _without_ an extension". You can easily craft the opposite - but that doesn't work because it's an *ignore* option.

This is why `naming-convention` defined its regex config with a boolean to invert the regex result.

**Comment by Josh-Cena** [comment]
> EG I don't think you can craft a regex that says "match all imports without an extension"

You can definitely do that! 😄 `/$(?<![^\s.]\.[^\s.]+)/`

**Comment by bradzacher** [comment]
Yeah but negative lookaheads are disgusting to use for this exact purpose

**Comment by JoshuaKGoldberg** [comment]
#8926 is reworking the FAQs a bit. Marking as blocked in the meantime.

**Comment by JoshuaKGoldberg** [comment]
Ah, #8507 added a line:

https://github.com/typescript-eslint/typescript-eslint/blob/635133a293cbea63447f7b579e8c51306e01cd7f/docs/troubleshooting/typed-linting/Performance.mdx#L123

So this was done. ✅
