### ISSUE TITLE
Repo: Builds stalled and broken on main for the checkout phase?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7899]
### Suggestion

Example: https://github.com/typescript-eslint/typescript-eslint/pull/7835 -> https://github.com/typescript-eslint/typescript-eslint/actions/runs/6836523591/job/18591557573?pr=7835

```plaintext
Failing after 360m
```

Seems that installs have been broken on `main` for a few commits now? be2777c5338669836d786f9a7806f499fd566dcd is the first commit on `main` to fail. Doesn't look like that commit contains the culprit.

**Comment by kirkwaiblinger** [comment]
This may have resolved itself or at least been related to something separate from the source code? My builds in https://github.com/typescript-eslint/typescript-eslint/pull/7897 started off timing out but are no longer timing out, and I have not rebased the branch.

**Comment by JoshuaKGoldberg** [comment]
Yup, @JamesHenry fixed it - thanks for the note :)
