### ISSUE TITLE
Bug: [@typescript-eslint/padding-line-between-statements] when removing blank line between functions in ts interface, eslint is not working

### ISSUE THREAD

**Issue by hkaraoglu** [typescript-eslint/typescript-eslint#7909]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.2&fileType=.tsx&code=KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQFERMBbMAG2AGU0A3BXAKAG8m45sphNVizKwABTcAjgFdgAZxgBZCABNgFAFxxMSAJ4BKNQAUoEUginAAPBs0A%2BANxN2cAObAY-clSEIFamVGSPdOAMjE3NLW3sOZ1cSd2kRYAlpOUVlNUtA4ONTCy0Ih3EwBV5gN0EEpJl5JVV1LUzDbLC8uwcal1LY8q8fGD8kAP1G0LMAIwgIKg0IgF8gA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6RAD2MbMroDNYTMvkoB7JrWiJ8saJKKl0UMf36QANOGx5F5KjXrJGLdlx59aAWzEATBIloAjMUNsBDaIVp7UGSKrqWthQBCT61HQMzGxMYvTmlLx07kyEygFqmto4YaTIFJFGJmxO0O5kjshESMoA2jk6iNDQYtDZITju8PBWqR2dWJ1dPWIA7gDKzADmSAAyzIjK%2BHCIjRAAvo0AusE6eRGG0aYAjrBi%2BCj161DNre17IZDIM7WP2EPDkO4AbmKUtgAogV3EoMCtYGthlsQrtGrpwgUDFFjDFWIJhLQyN14LRkMQKjNrl87m0Bk8mIgfs1IDt3pBmLZECxiZ1IKSHjcACzvCCfNkAWUQViczUBXGkyBeEmUAEZeTpKNM4tJbAA5OxXDANYZPABiQhE4iY4uIkulTDAAD4wAA6AnlKzIOpMshtdz4NrIW1IJjTfAAC2tYAADNtybrIAbhKIJKbzcbg-bPO4ncG0H18GQAygABQAEUQbvKnugGjAaDi%2BFzaH4lGg1SxAco8FsAEo2xGvgBheDuKUAITshFtLlshGDAAVWqRoERC3WmHxjS6i%2B7S97ff6gzaw0mANaIdI3CDbG4w7BwinxKyUDiIWx4gmVZC0VKP-DuJx%2BUP0g5IopjlieJhRobwMSNGVtRudkWjJBV%2BSeHFxnqM9oTpeF-0KI5UVMOJaCEWBkAfWgfk8H8dTZDku0wE8oE8aZkAASWVNpEEnD1LnkDIAD0AH1aXQ2E-18bCURKVgTBQZwZDGRBmSxPspWsYVRQbVknmohVvngMZ3EIVAELo9kOEqGgAEF%2BC4qY-XmRZllWc8MOvawEFEbhHFAohaCkiiYK0m5EJ0PoODlBUcBCgcAHk9WUENwqgELARiuKnOE%2BF8JWdwWxmJ8Ki1MBKM0uDOWGIKcGQfdqAHPsmH3BZKR-CEoU6C9T3pAlbCZR8nHgMQyH3PySRKmjyqgXr%2BsGjJKWpUrIzIJTiJ-SAZppBLnjGPhswKlaqRpNLL3pRAxFxJT8A0poRu01b2mcnR8KsNzKDyl8LpwAKyuMpUVUQZK5m7MQrCsZl8CaxyhMO%2BExCcAArIs6DIOR4G8fFCT9N7biumDuj0gzBMvbQtg2IA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEk8sAJgK4YVRzz1EBWZANOBqQG6aKgCGmcQWJs8mJugE0omdPQBu6AMIJ46InjKV5i5UPXI8AEVGwpeewFl0ecQ2ni5CpYNroAD0QsZH1DcVRbOAd7YzBTXxVICNRYAHcAZQBPQwALV2RoWwAzcRY8AEkkeyNvMz8oN0wAc1c2SHQSACYABi6ARkhzWhT0gCk4hOGoElgmTGh0J3FEOsShOZtkTHaAOgB6BmQSPCGGyAAjcRJ0AFVMVD39s6TkImg1MLdHkx9pyBIAGtkIgADLIC7afLQQFrf4nTCFPAAORYqChokBcVKqBu-yIsCqiFQhSsAEEiFk2Di8ecEUiAEJvBjaFJkxDEqmUGnrWjFeyLXSkY54Ax4VkkN7NCpEABiaHQyPE%2BmxEVpSQJspSeFymDmzVyEs6MoyaSs0Fy1LV6wAvuYOgExEwRGwANrnAkiAD69GYGH45yOJxeQkQTAuJOgkEEAF17UYALSe9BsahCNQARyY2xTlHdKloRjgRGKyGaCcQ0lyJH2amaIqw0ZUMcENpANqAA&tokens=false

### Repro Code

```typescript
export interface IExampleService
{
  createExample(requestModel: CreateExampleRequestModel): Promise<CreateExampleResponseModel>;

  getExample(id: string): Promise<GetExampleResponseModel>;
  getExamples(requestModel: GetExamplesRequestModel): Promise<GetExamplesResponseModel>;

  updateExample(requestModel: UpdateExampleRequestModel): Promise<UpdateExampleResponseModel>;

  deleteExample(id: string): Promise<boolean>;
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "padding-line-between-statements": "off",
     "@typescript-eslint/padding-line-between-statements": [
       "error",
       {
        "blankLine": "always",
        "prev": "*",
        "next": ["interface", "type"]
       }
     ]
  }
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "allowJs": true,
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  },
  "exclude": [
    "node_modules",
    "dist",
    "public"
  ],
  "ts-node": {
    "require": ["tsconfig-paths/register"]
  }
}
```

### Expected Result

```
export interface IExampleService
{
  createExample(requestModel: CreateExampleRequestModel): Promise<CreateExampleResponseModel>;

  getExample(id: string): Promise<GetExampleResponseModel>;

  getExamples(requestModel: GetExamplesRequestModel): Promise<GetExamplesResponseModel>;

  updateExample(requestModel: UpdateExampleRequestModel): Promise<UpdateExampleResponseModel>;

  deleteExample(id: string): Promise<boolean>;
}
```

### Actual Result

```
export interface IExampleService
{
  createExample(requestModel: CreateExampleRequestModel): Promise<CreateExampleResponseModel>;

  getExample(id: string): Promise<GetExampleResponseModel>;
  getExamples(requestModel: GetExamplesRequestModel): Promise<GetExamplesResponseModel>;

  updateExample(requestModel: UpdateExampleRequestModel): Promise<UpdateExampleResponseModel>;

  deleteExample(id: string): Promise<boolean>;
}
```

**Comment by bradzacher** [comment]
Hi there 👋!

As you may have heard [ESLint core is deprecating its formatting rules](https://eslint.org/blog/2023/10/deprecating-formatting-rules/). We are likewise moving in the same direction and deprecating our formatting rules.

Deprecated rules will be removed in the next major version as their new home is the [eslint-stylistic](https://github.com/eslint-stylistic/eslint-stylistic) project.

If this issue is important to you please consider filling an issue over at eslint-stylistic which will be the new home for stylistic/formatting rules.

Thanks!
