### ISSUE TITLE
Repo: Add lint rules for using context wrappers

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7930]
### Suggestion

In #7914 I added wrapper methods so we can support multiple versions of ESLint, per https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/ -> https://github.com/typescript-eslint/typescript-eslint/issues/7816 -> https://github.com/typescript-eslint/typescript-eslint/pull/7812.

```diff
- context.getSourceCode()
+ getSourceCode(context)
```

The wrapper methods mean our rules will work on ESLint 7, 8, and even 9 once the old deprecated versions are removed. We should lint to make sure folks are using the wrappers and not the new, doesn't-exist-in-old-ESLint versions equivalents.

Unit tests will eventually capture this too but I think failing a lint rule -especially if it has an auto-fixer- would be much easier for contributors.

Aside: I did that PR without any review to quickly fix lint failures on the `main` branch. If there's some better way to approach this problem, we should consider it!

**Comment by bradzacher** [comment]
I don't think we need lint rules for this - once v9 releases we'll update the types to make the methods optional and we can add instructions to the JSDoc.
