### ISSUE TITLE
Repo: Move to GitHub Private Security Reporting

### ISSUE THREAD

**Issue by LeoDog896** [typescript-eslint/typescript-eslint#7932]
### Suggestion

This allows GitHub to handle the process as a neutral third party and automatically file CVEs with Mitre, streamlining the process for typescript-eslint whenever a security vulnerability is found.

Both options can still be available, but GitHub's private security reporting is easier to work with.

[Docs link](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability)

**Comment by bradzacher** [comment]
We already have a security policy which is just to privately email us at our (actively monitored) email address. https://github.com/typescript-eslint/typescript-eslint/security/policy
Is that not easy enough to work with?

**Comment by JoshuaKGoldberg** [comment]
As a not-security person I am curious on what the _benefits_ of GitHub's security reporting are. Like, what's the advantage of the dedicated channel over just a private email?

For example, the _"Start a temporary private fork"_ idea is interesting. Is that a strong positive?

**Comment by LeoDog896** [comment]
Ah, alright! Those concerns make sense - I've seen that private security reporting is generally easier to set up _than_ email (because of the whole manually registering CVEs), but given the security scope of this project, I can see why it may be better to just stay simple with reporting 👍
