### ISSUE TITLE
Enhancement: [max-params] options to ignore the constructor

### ISSUE THREAD

**Issue by CatsMiaow** [typescript-eslint/typescript-eslint#7934]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/max-params/

### Description

TypeScript frameworks (NestJS, AdonisJS ...) are using `Dependency Injection` of constructors utilizing [emitDecoratorMetadata](https://www.typescriptlang.org/tsconfig#emitDecoratorMetadata) of tsconfig.
Here, the order of the parameters injected into the constructor doesn't matter.

What do you think of the option to ignore only the parameters of the constructor in the `max-params` rule?
This suggestion was not accepted by eslint, but what about `@typescript-eslint`?
> https://github.com/eslint/eslint/issues/15745

### Fail

```typescript
class TestController {
  constructor(
    private store: StoreService,
    private config: ConfigService,
    private error: ErrorService,
    private util: UtilService,
  ) {}

  // The error should only occur in the method.
  public test(a, b, c, d, e) {}
}
```

### Pass

```typescript
class TestController {
  constructor(
    private store: StoreService,
    private config: ConfigService,
    private error: ErrorService,
    private util: UtilService,
  ) {}

  public test(a, b, c) {}
}
```

**Comment by bradzacher** [comment]
For extension rules we follow upstream unless the option is *specifically* for TypeScript.
We don't want to deviate from the core rule except in the ways that are necessary to support TypeScript features.

Thus if ESLint has rejected this option for the rule, thus we shall reject this option as well as it is not specifically about a TypeScript feature.
It may seem related to TS given all the examples are about parameter properties - however parameter properties are just syntactic sugar and you'd have the same number of parameters without parameter properties.

Reading through the linked issue - the OP provided a solution that would work for your usecase, I believe: [`eslint-plugin-max-params-no-constructor`](https://www.npmjs.com/package/eslint-plugin-max-params-no-constructor)
