### ISSUE TITLE
Repo: Use less inconvenient ways of enforcing our usage of TypeScript APIs than patching

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7956]
### Suggestion

Splitting out of https://github.com/typescript-eslint/typescript-eslint/pull/7923#discussion_r1398071314: we're finding it rather inconvenient to have to work with [`yarn patch`](https://yarnpkg.com/cli/patch) to apply our patches to TypeScript's `.d.ts` file.

For context, we want to enforce a few somewhat-specific-to-use ways of using TypeScript:

* Adding in removed fields as `@deprecated` optionals for backwards compatibility
* `@deprecating` fields not present in all our supported versions

Example patch: https://github.com/typescript-eslint/typescript-eslint/blob/8ec3800d6c4eef078ec20b5434805e731242a49d/.yarn/patches/typescript-npm-5.3.0-beta-33b1e90865.patch

Unfortunately, Yarn patching presents a couple inconveniences:
* https://github.com/yarnpkg/berry/issues/4441 gets in the way (though does not seem to fully block) patching TypeScript.
* Even ignoring ☝️, we have to manually re-apply patches every time there's a new TypeScript that changes the hash of the file. Ugh. 

I'd rather we did something less getting-in-the-way-of-tooling / needing-manual-work-every-TS-version-change, such as declaration merging and/or linting.

**Comment by bradzacher** [comment]
I think we might be able to do declaration merging for this?
Just means we need to ensure the local decls are included in every package.

**Comment by Josh-Cena** [comment]
We can use declaration merging to add nonexistent fields, but I don't think we can use it to add `@deprecated` or remove them. I believe the local declarations are processed _after_ the lib declarations, which means if we add an identical signature, it will have lower precedence:

```ts
declare function getDecorators(node: HasDecorators): readonly Decorator[] | undefined;

/**
 * @deprecated
 */
declare function getDecorators(node: HasDecorators): readonly Decorator[] | undefined;

getDecorators(node); // No deprecation
```

Of course that's just my suspection.
