### ISSUE TITLE
Enhancement: [no-extraneous-class] add an option to allow classes with private members

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#7959]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-extraneous-class/

### Description

Sometimes it can be useful to use a class as a namespace to group some public and private implementation details together.

```ts
export class Foo {
  private static privateValue = 1;

  static publicMethod() {
    this.privateMethod();
  }

  private static privateMethod() {
    // ... do the thing ...
    return this.privateValue++;
  }
}
```

An object doesn't work for this case because all object members are public - so in order to add private members one must hoist the members to the outer scope:
```ts
let privateValue = 1;
function privateMethod() {
  // ... do the thing ...
  return this.privateValue++;
}
export const Foo = {
  publicMethod() {
    return privateMethod();
  },
}
```

This approach works, but the problem is that it exposes the members to the entire scope - meaning you need to think about name clashes or accidental modifications/usages within the module (the latter of which is "impossible" with private members).

Another option is namespaces:
```ts
namespace Foo {
  let privateValue = 1;
  function privateMethod() {
    // ... do the thing ...
    return this.privateValue++;
  }
  export function publicMethod() {
    return privateMethod();
  }
}
```
These solve the problems of a POJO by encapsulating the private details - however:
a) in a lot of codebases they are banned entirely (for good reason)
b) they completely hide the private details, preventing you from mocking them during testing (if required)

I propose a new option - `allowWithPrivateMembers` which would allow a class with only static members if and it has at least one private static member.

### Fail

```typescript
export class Foo {
  static privateValue = 1;

  static publicMethod() {
    this.privateMethod();
  }

  static privateMethod() {
    // ... do the thing ...
    return this.privateValue++;
  }
}
```

### Pass

```typescript
export class Foo {
  private static privateValue = 1;

  static publicMethod() {
    this.privateMethod();
  }

  private static privateMethod() {
    // ... do the thing ...
    return this.privateValue++;
  }
}
```

**Comment by Josh-Cena** [comment]
I am +0.5 on this. I can see the rationale but I personally (a) have not ever used TS `private` since `#private` (b) would use an IIFE or namespace in this case. I'm sure many differ with me, so it makes sense as an option.

**Comment by bradzacher** [comment]
I usually wouldn't have thought this but I've found it's a really common pattern in the canva codebase.

JS natives wouldn't really do this - but there's a decent chunk of Java engineers that favour this pattern.

**Comment by JoshuaKGoldberg** [comment]
Yeah I'm -0.25 on this, it feels like a pattern we shouldn't encourage and ideally nobody should use (cough, sorry Canva folks). If we do add it I'd very much want a big splashy "don't do this" kind of mention in the docs.

**Comment by bradzacher** [comment]
I'm happy to close this and fork the rule in the monorepo.
It's clearly not a common pattern in the ecosystem considering this is the first ask for it in ~6y.
