### ISSUE TITLE
Bug: Unexpected node `TSAssertEntry`

### ISSUE THREAD

**Issue by fisker** [typescript-eslint/typescript-eslint#7960]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-estree

### Repro Code

```typescript
> require('@typescript-eslint/typescript-estree').parse('import json from "./foo.json" assert { type: "json", type: "bar" };').body[0].attributes
[
  {
    type: 'TSAssertEntry',
    name: {
      type: 'Identifier',
      decorators: [],
      name: 'type',
      optional: false,
      typeAnnotation: undefined,
      range: [Array],
      loc: [Object]
    },
    value: {
      type: 'Literal',
      value: 'json',
      raw: '"json"',
      range: [Array],
      loc: [Object]
    }
  },
  {
    type: 'TSAssertEntry',
    name: {
      type: 'Identifier',
      decorators: [],
      name: 'type',
      optional: false,
      typeAnnotation: undefined,
      range: [Array],
      loc: [Object]
    },
    value: {
      type: 'Literal',
      value: 'bar',
      raw: '"bar"',
      range: [Array],
      loc: [Object]
    }
  }
]
```

### Expected Result

Didn't see it mentioned in the changelog.

### Actual Result

See above.

### Versions

6.11.0 

Ref: https://github.com/prettier/prettier/pull/15695

**Comment by bradzacher** [comment]
Cc @JoshuaKGoldberg looks like a regression with the 5.3 beta support.
If you're using <=5.2 then you get this invalid AST node instead of the correct node.

**Comment by fisker** [comment]
i can upgrade ts at the same time. 😄

**Comment by bradzacher** [comment]
@JoshuaKGoldberg yeah that would be the expectation - we need to remain backwards compatible!
