### ISSUE TITLE
Docs: replace `file.ts`/`react.tsx` with `estree.ts`/`estree.tsx` in custom rules and RuleTester docs

### ISSUE THREAD

**Issue by loderunner** [typescript-eslint/typescript-eslint#7961]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Creating a `RuleTester` for my custom plugin, I follow the docs and created an empty `file.ts` and `tsconfig.test.json`.

**rule.test.ts**

```ts
const ruleTester = new TSESLint.RuleTester({
  parser: require.resolve('@typescript-eslint/parser'),
  parserOptions: {
    project: './tsconfig.test.json',
    tsconfigRootDir: path.join(__dirname, 'fixtures'),
  },
});
```

**tsconfig.test.json**

```json
{
  "include": ["file.ts"]
}
```

Running the tests gave me the following error:

```
    Message:
      A fatal parsing error occurred: Parsing error: ESLint was configured to run on `<tsconfigRootDir>/estree.ts` using `parserOptions.project`: /users/chrales/code/eslint-plugin-ordering/src/rules/__tests__/fixtures/tsconfig.test.json
    However, that TSConfig does not include this file.
```

I renamed `file.ts` to `estree.ts` and changed the `files` property in `tsconfig.test.json`, and it is now fixed.

If I understand correctly, the file name is determined by the [`getFileName`](https://github.com/typescript-eslint/typescript-eslint/blob/237259b2112d6b96dd4951a38e01b20efd0433ef/packages/typescript-estree/src/parseSettings/createParseSettings.ts#L163-L173) function, used in `createParseSettings`.

The docs should reflect this file name.

----

Additionally, ESLint now takes an absolute path for `parser` rather than a string. For RuleTester to work, I needed to replace `parser: '@typescript-eslint/parser'` with `parser: require.resolve('@typescript-eslint/parser')`. This could also be reflected in the docs.

### Affected URL(s)

* https://typescript-eslint.io/developers/custom-rules/#testing-typed-rules
* https://typescript-eslint.io/packages/rule-tester/#type-aware-testing

**Comment by bradzacher** [comment]
> new TSESLint.RuleTester

You didn't show the import you're using, but I am guessing you're using the `@typescript-eslint/utils` package based on the sample code.

The docs specify using our testing package `@typescript-eslint/rule-rester` - though this is a more recent change from v6 that you may have missed.

Could you please clarify how you're importing things? 

> If I understand correctly, the file name is determined by the getFileName function, used in createParseSettings.

This is correct if you are calling our parser directly - but is incorrect for rule tests.

If you are using our testing package instead the filename is configurable:
https://github.com/typescript-eslint/typescript-eslint/blob/9093e95f2baa0d81c589db99d4730f59e80a4c38/packages/rule-tester/src/types/RuleTesterConfig.ts#L22-L29

The config defaults to the names as specified in the docs.
