### ISSUE TITLE
Playground is broken as of the latest release

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#7962]
https://typescript-eslint.io/play/

Displays the error

```
Cannot read properties of undefined (reading 'collapsedSizePercentage')
```

Cc @armano2 likely caused by one of your changes that landed recently?

**Comment by JoshuaKGoldberg** [comment]
OH no this probably was me. #7937. Could have sworn it was working. Looking now.

**Comment by bradzacher** [comment]
Hmm looking at the preview link it's broken in the same way yeah

https://deploy-preview-7937--typescript-eslint.netlify.app/play/

**Comment by JoshuaKGoldberg** [comment]
It's sad, too, because I'm the one who removed the end-to-end tests.
