### ISSUE TITLE
Bug: Declaration Files Not Included from Built Package in Monorepo

### ISSUE THREAD

**Issue by daniel-nagy** [typescript-eslint/typescript-eslint#7969]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

Declaration files are not working when using bun workspaces and importing a module from another package in the workspace. Bun will create a **symlink** to the package in the **node_modules** folder. Note that importing the module using a relative path that reaches into the node_modules directory works. Also note that TypeScript is able to use the declaration files no problem.

I'm using the **eslint-plugin-expect-type** plugin. Not sure if the problem is in that package or in **typescript-eslint**.

### Reproduction Repository Link

https://github.com/daniel-nagy/eslint-repo

### Repro Steps

1. Clone the repo.
2. Install bun with `asdf install` or some other method. I observed the same issue with yarn workspaces if you would prefer to use yarn instead of bun.
3. Run bun install from the workspace root.
4. run `bun run --cwd packages/b typetest` and observe the typetest fails.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `6.12.0` |
| `@typescript-eslint/parser`            | `6.12.0` |
| `TypeScript`                           | `5.2.2` |
| `ESLint`                               | `8.54.0` |
| `node`                                 | `20.5.0` |

**Comment by bradzacher** [comment]
> Bun will create

Note that we do not test against bun (or deno). So we do not support them and essentially using our tooling with them is "no warranty provided".

Can you reproduce this using nodejs with yarn or similar?

**Comment by daniel-nagy** [comment]
> @bradzacher Can you reproduce this using nodejs with yarn or similar?

Yes, I've updated the repo to use node and yarn. Thanks.

**Comment by bradzacher** [comment]
Adding
```ts
/* eslint @typescript-eslint/no-unsafe-member-access: error */
_copy.length;
```
Works as expected.
This indicates that it's not a problem with our tooling, but is instead a problem with `eslint-plugin-expect-type`.

![screenshot of ide](https://github.com/typescript-eslint/typescript-eslint/assets/7462525/4dffae59-bfba-480b-bf5c-93f2b82be094)
