### ISSUE TITLE
Bug: @typescript-eslint/naming-convention Value {"selector":"import","format":["camelCase","PascalCase","UPPER_CASE"]} should match exactly one schema in oneOf.

### ISSUE THREAD

**Issue by G-H-G** [typescript-eslint/typescript-eslint#7970]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

Oops! Something went wrong! :(
ESLint: 8.54.0
Error: .eslintrc.json » plugin:@byted-lint/meta/typescript » @byted/eslint-config-standard-ts/no-type-checking:
	Configuration for rule "@typescript-eslint/naming-convention" is invalid:
	Value "import" should be array.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
        Value "import" should be equal to one of the allowed values.
	Value "import" should be equal to one of the allowed values.
	Value {"selector":"import","format":["camelCase","PascalCase","UPPER_CASE"]} should match exactly one schema in oneOf.
    at ConfigValidator.validateRuleOptions (/go/src/code.byted.org/ies/tcs-projects/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2039:23)
    at /go/src/code.byted.org/ies/tcs-projects/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2094:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (/go/src/code.byted.org/ies/tcs-projects/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2091:34)
    at ConfigValidator.validateConfigArray (/go/src/code.byted.org/ies/tcs-projects/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2217:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/go/src/code.byted.org/ies/tcs-projects/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3974:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/go/src/code.byted.org/ies/tcs-projects/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3780:21)
    at FileEnumerator._iterateFilesWithFile (/go/src/code.byted.org/ies/tcs-projects/node_modules/eslint/lib/cli-engine/file-enumerator.js:368:43)
    at FileEnumerator._iterateFiles (/go/src/code.byted.org/ies/tcs-projects/node_modules/eslint/lib/cli-engine/file-enumerator.js:349:25)
    at FileEnumerator.iterateFiles (/go/src/code.byted.org/ies/tcs-projects/node_modules/eslint/lib/cli-engine/file-enumerator.js:299:59)

### Reproduction Repository Link
.eslintrc.json
"@typescript-eslint/naming-convention": "off",

### Repro Steps

1) nvm use v16.19.0
2) npm install

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `^5.62.0` |
| `@typescript-eslint/parser`            | `^5.62.0` |
| `@typescript-eslint/scope-manager`     | `X.Y.Z` |
| `@typescript-eslint/typescript-estree` | `X.Y.Z` |
| `@typescript-eslint/type-utils`        | `X.Y.Z` |
| `@typescript-eslint/utils`             | `X.Y.Z` |
| `TypeScript`                           | `4.3.5` |
| `ESLint`                               | `8.54.0` |
| `node`                                 | `16.19.0` |

**Comment by G-H-G** [comment]
I checked https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/naming-convention.md, there is an example of `selector: 'import'`
![image](https://github.com/typescript-eslint/typescript-eslint/assets/46241807/bd8ed36c-b082-464d-8e8d-8e2653c1ca5e)

**Comment by bradzacher** [comment]
>  I have updated to the latest version of the packages 

You ticked this box and yet you listed

> @typescript-eslint/eslint-plugin	^5.62.0


Which is a many months old version from the last major version. The latest version is 6.12.0.

Update and it'll work.
