### ISSUE TITLE
Parsing error: __classPrivateFieldGet(...).at is not a function

### ISSUE THREAD

**Issue by anatoly-ivashov** [typescript-eslint/typescript-eslint#7971]
### Suggestion

Has anyone encountered this problem?
Please tell me how to solve it.

The problem appeared after updating all versions to the latest ones.
![image](https://github.com/typescript-eslint/typescript-eslint/assets/107929864/24fc2038-08c1-4d5e-97a2-9409553f08fe)

**Comment by bradzacher** [comment]
https://typescript-eslint.io/contributing/issues

Please use an appropriate issue template.
Please also file an issue with a reproduction.
Please also do not file issues with screenshots of code.
