### ISSUE TITLE
[RFC] Rename `parserOptions.project`

### ISSUE THREAD

**Issue by Teoxoy** [typescript-eslint/typescript-eslint#798]
From the perspective of a user I find `parserOptions.project` to be confusing.
Coming from alexgorbatchev/eslint-import-resolver-typescript#23, I think `tsconfigPath` is the best alternative.

This is an RFC. Let me know what you all think!

Keep in mind, this would be a breaking change!

**Comment by Timmmm** [comment]
This can easily be made to be a non-breaking change by falling back to `project`.

**Comment by bradzacher** [comment]
Project is the canonical term for what you are providing us a reference to.
It aligns with the naming used for [TypeScript's "Project References" feature](https://www.typescriptlang.org/docs/handbook/project-references.html).

If anything, I would say that renaming our `tsconfigRootDir` option to `projectRootDir` is actually the correct approach.

Based on this, I'm going to reject this proposal.
