### ISSUE TITLE
Repo: Many dev commands require a global nx command

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7987]
### Suggestion

Commands prefixed with `nx` (e.g. [`nx run ...`](https://nx.dev/nx-api/nx/documents/run)) require either something like `npx nx` in front or a global `nx` script, such as from `npm i -g npm`. If you don't then trying to run them gives an error:

```plaintext
josh ~/repos/typescript-eslint/packages/website $ yarn start
command not found: nx
```

Running a search for `": "nx ` in `package.json` files, we get 40 results in 18 files right now. 

I think we have two likely workarounds:

* Explicitly require dev machines have run something like `npm i -g nx`
* Prefix all those commands with something like `npx ` (e.g. instead of `nnx

**Comment by merceyz** [comment]
That is because that workspace (`website`) doesn't declare any dependencies that provide a `nx` binary, if you want to use the `nx` binary from the root workspace you need to use `yarn run -T nx` or `run -T nx` for short.

**Comment by JoshuaKGoldberg** [comment]
Ah thanks for bringing this up!

Per https://docs.npmjs.com/cli/v8/commands/npx:

> If any requested packages are not present in the local project dependencies, then they are installed to a folder in the npm cache, which is added to the `PATH` environment variable in the executed process. A prompt is printed (which can be suppressed by providing either `--yes` or `--no`).

When I run `npx npx --version` in `typescript-eslint`, no prompt is given, and it prints the locally installed version:

```plaintext
 $ npx nx --version
Nx Version:
- Local: v17.1.2
- Global: Not found
```
