### ISSUE TITLE
[prefer-const] Should typescript-eslint provide a replacement for prefer-const?

### ISSUE THREAD

**Issue by octogonz** [typescript-eslint/typescript-eslint#799]
**Repro**

```JS
{
  "rules": {
     "prefer-const": "error",  // ESLint's rule
  }
}
```

```TS
function getTimeInMs(): number {
  let seconds: number;
  let nanoseconds: number;
  // Error: 'seconds' is never reassigned. Use 'const' instead.
  // Error: 'nanoseconds' is never reassigned. Use 'const' instead.
  [seconds, nanoseconds] = process.hrtime();
  return seconds * 1000 + nanoseconds / 1000000;
}
```

**Additional Info**

Should `typescript-eslint` provide a TypeScript-aware extension for `prefer-const`?   Or is this a bug in the base ESLint rule?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.0.0-alpha.4` |
| `@typescript-eslint/parser`        | `1.13.0` |
| `TypeScript`                       | `3.5.3` |
| `ESLint`                           | `6.1.0` |

**Comment by bradzacher** [comment]
In this instance - how come you are using typed variable declarations?
`process.hrtime()` returns `number[]`, so `seconds` and `nanoseconds` would be automatically typed, so you could use
```ts
const [seconds, nanoseconds] = process.hrtime();
```

if for some reason you didn't have types for `hrtime`, you could also achieve this with
```ts
const [second, nanoseconds]: [number, number] = process.hrtime();
const [second, nanoseconds] = process.hrtime() as [number, number];
```

**Comment by octogonz** [comment]
Closing -- on further thought, I agree that `seconds` and `nanoseconds` /should/ be declared as `const` in this context.  Thanks!
