### ISSUE TITLE
Bug: [rule name here] <short description of the issue>

### ISSUE THREAD

**Issue by alex-Symbroson** [typescript-eslint/typescript-eslint#7990]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.0-dev.20231117&fileType=.tsx&code=LAKAxg9gdgzgLgAgIYILzJgTymBAKASjQD5kB3JAS0SgFMyEAFAJwgFtKZa9naYSEvGHgCMBAqFBIsOBADMArjjiVoCNlSiEEAb1AJyVREkIBuBAHoLCCAGt9yMwecGrN2wBoEAIwWIYABYQCgA2ACYIcAGsDLwAjgqUvAC0SBTUDpRy%2BHDMCrRElta0zKzMCFAQyZCwcEhQcNXQYdSqUA4GNTAQIbQAdCEQAOZ4aUaORKjoAEQATNME5m4UzFAItHEbG6AAvpIgGpRai6BAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKUQR333TAG1xscB3AQ2gDtIAaciyZAW1oBdIWwBdZqzoB7ALQBjEXWRdqdLpOkATAJZdV04rmjQR0Jnxj5Yq6IjHUa67Yl37eEAL4gnQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkAhqqrAO4BSZlemArugDTgaMABbpoAa3YUwXXgJpQisAJJJUyaMjwBBIgE9ps-oNokuGvADlujAMKiJHGT2MLI6AB51oeXAWIMAAqYsIhYeHoAKnphTkbyQuoARtIA2iZC6CQAbJB8UAAmCJAZALoJtHh0mADm6HjS7jklEAC%2BIK1AA&tokens=false

### Repro Code

```typescript
const a = async () => await new Promise(res => res(1))

async function main() {
  await a(); // ok
  a();       // ok, but should throw require-await
  if (true)  // error no-constant-condition
    console.log(await a() == "2"); // warn eqeqeq
}

main();
```

### ESLint Config

```javascript
{
  "rules": {
    "eqeqeq": [
      "warn",
      "smart"
    ],
    "no-constant-condition": "error",
    "require-await": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "exactOptionalPropertyTypes": true,
    "lib": [
      "es6", "dom"
    ],
    "target": "es6"
  }
}
```

### Expected Result

I want to get warned about the missing await statement 

### Actual Result

```
  7:9   error    Unexpected constant condition        no-constant-condition
  8:31  warning  Expected '===' and instead saw '=='  eqeqeq

✖ 2 problems (1 error, 1 warning)
```

### Additional Info

There is a very old issue that might be related but I'm not sure: https://github.com/eslint/eslint/issues/13567

**Comment by auvred** [comment]
Have you tried [`ts/no-floating-promises`](https://typescript-eslint.io/rules/no-floating-promises/)? [`ts/require-await`](https://typescript-eslint.io/rules/require-await/) basically has a different purpose:

> Disallow async functions which have no await expression

https://eslint.org/docs/latest/rules/require-await

**Comment by JoshuaKGoldberg** [comment]
See https://typescript-eslint.io/rules/require-await. Your ESLint config uses the core ESLint `require-await`, not the extension rule.

> - [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

The first FAQ there explains our extension rules 🙂
