### ISSUE TITLE
[no-lone-blocks] Should typescript-eslint provide a replacement for no-lone-blocks?

### ISSUE THREAD

**Issue by octogonz** [typescript-eslint/typescript-eslint#800]
**Repro**

```JS
{
  "rules": {
     "no-lone-blocks": "error",  // ESLint's rule
  }
}
```

```TS
function example(input: number, items: string[]): void {
  switch (input) {
    // Error no-lone-blocks: Block is redundant.
    case 1: {
      const value: string = items[5];
      console.log(value);
    }
    break;
    // Error no-lone-blocks: Block is redundant.
    case 2: {
      const value: string = items[3];
      console.log(value);
    }
    break;
  }
}
```

**Additional Info**

This lint error is asking to remove the `{` `}` blocks in the `case` statements. But if we do that, then the two `value` variables will conflict.  We could rename it to `value2`, but the other names will nonetheless pollute the IntelliSense set within that block (and I'm encountering this in `switch` statements with a large number of cases).

I believe the `no-lone-blocks` rule makes sense in JavaScript, where declaring variables inside a `case` statement is generally avoided due to the error-prone `var` hoisting issues.  But the TypeScript compiler prevents all these mistakes, so it's completely safe to declare local variables in a `case` statement in TypeScript. Thus, perhaps the problem/solution here are specific to TypeScript.

Should `typescript-eslint` provide a TypeScript-aware extension for `prefer-const`?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.0.0-alpha.4` |
| `@typescript-eslint/parser`        | `1.13.0` |
| `TypeScript`                       | `3.5.3` |
| `ESLint`                           | `6.1.0` |

**Comment by bradzacher** [comment]
In es6+ code that uses `let`/`const`, `no-lone-blocks` only really serves to make sure you're not declaring a useless block that declares no new variables.

According to eslint demo, your example shouldn't cause any errors:
```ts
/*eslint no-lone-blocks: "error"*/
/*eslint-env es6*/
function example(input, items) {
  switch (input) {
    // Error no-lone-blocks: Block is redundant.
    case 1: {
      const value = items[5];
      console.log(value);
    }
    break;
    // Error no-lone-blocks: Block is redundant.
    case 2: {
      const value = items[3];
      console.log(value);
    }
    break;
  }
}
```
[repl](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tbG9uZS1ibG9ja3M6IFwiZXJyb3JcIiovXG4vKmVzbGludC1lbnYgZXM2Ki9cbmZ1bmN0aW9uIGV4YW1wbGUoaW5wdXQsIGl0ZW1zKSB7XG4gIHN3aXRjaCAoaW5wdXQpIHtcbiAgICAvLyBFcnJvciBuby1sb25lLWJsb2NrczogQmxvY2sgaXMgcmVkdW5kYW50LlxuICAgIGNhc2UgMToge1xuICAgICAgY29uc3QgdmFsdWUgPSBpdGVtc1s1XTtcbiAgICAgIGNvbnNvbGUubG9nKHZhbHVlKTtcbiAgICB9XG4gICAgYnJlYWs7XG4gICAgLy8gRXJyb3Igbm8tbG9uZS1ibG9ja3M6IEJsb2NrIGlzIHJlZHVuZGFudC5cbiAgICBjYXNlIDI6IHtcbiAgICAgIGNvbnN0IHZhbHVlID0gaXRlbXNbM107XG4gICAgICBjb25zb2xlLmxvZyh2YWx1ZSk7XG4gICAgfVxuICAgIGJyZWFrO1xuICB9XG59Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo5LCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7ImpzeCI6dHJ1ZX19LCJydWxlcyI6e30sImVudiI6eyJjb21tb25qcyI6ZmFsc2UsIm5vZGUiOmZhbHNlfX19)

**Comment by octogonz** [comment]
> `/*eslint-env es6*/`

Thanks!  Setting `ecmaVersion` to `es6` fixed this problem.  Although the TypeScript compiler's /output/ is ES5, its input uses ES6+ semantics, so I think that was the trouble here.
