### ISSUE TITLE
Enhancement: [explicit-function-return-type] support parameter type checker

### ISSUE THREAD

**Issue by ChrisCho-H** [typescript-eslint/typescript-eslint#8005]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/explicit-function-return-type

### Description

In [official docs](https://typescript-eslint.io/rules/explicit-module-boundary-types#when-not-to-use-it), it states that explicit-function-return-type is intended to be a stronger type checker than explicit-module-boundary-types(and also in [issue2719](https://github.com/typescript-eslint/typescript-eslint/issues/2719))
The problem is while explicit-module-boundary-types(considered as a weaker alternative) has a type checker for all function arguments, explicit-function-return-type does not have it. In [issue2719](https://github.com/typescript-eslint/typescript-eslint/issues/2719) @bradzacher mentioned that it's not intended to be used together, but in this case explicit-function-return-type is weaker in terms of args, so makes it hard to use explicit-function-return-type to replace explicit-module-boundary-types for stronger type check(there seems no way for explicit-function-return-type itself to check argument types, the only way is to use both but that is not intended case).
Of course the name itself(explicit-function-return-type) does not include type-check for args, but if to replace explicit-module-boundary-types for stronger(or broader) type check, it would be much better to include type-check for args as explicit-module-boundary-types does.
Let me know if I miss something as I'm pretty new to this project.

### Fail

```TypeScript
// All arguments should be typed
export var arrowFn = (arg): string => `test ${arg}`;
export var arrowFn = (arg: any): string => `test ${arg}`;
```

### Pass

```TypeScript
// All arguments should be typed
export var arrowFn = (arg: string): string => `test ${arg}`;
export var arrowFn = (arg: unknown): string => `test ${arg}`;
```

**Comment by bradzacher** [comment]
There is no need for this because typescript already had a compiler option for this - `noImplicitAny`.

Return types are different because return types are inferred by TS and this are optional. With `noImplicitAny` any and all cases where TS cannot contextually infer the type - TS will error.

It's part of the `strict` compiler option and is something you should (or really must, IMO) turn on. In v6.0 the TS team is planning on making this the default.
