### ISSUE TITLE
Repo: Netlify PR deploys fail on latest Node.js 18.19.0

### ISSUE THREAD

**Issue by auvred** [typescript-eslint/typescript-eslint#8025]
### Suggestion

Logs: https://app.netlify.com/sites/typescript-eslint/deploys/656cda722b027400084ae549#L64-L91

This is because the latest version 18.x of Node.js (18.19.0) is being used. [It contains breaking changes](https://github.com/nodejs/node/releases/tag/v18.19.0) for `tsx` package used in deployment. It has been fixed on `tsx` side in the [`v4.6.1`](https://github.com/privatenumber/tsx/releases/tag/v4.6.1), but as I understand it, we can't just bump the `tsx` version, because `tsx@4` [doesn't support](https://github.com/privatenumber/tsx/releases/tag/v4.0.0) Node.js v16, although v16 it's still used in ci:
https://github.com/typescript-eslint/typescript-eslint/blob/cc2c6d3a4a515f7ccc23f10421a8db9c88345876/.github/workflows/ci.yml#L162

So we can:
1. Drop Node.js 16 support ([it's already unmaintained](https://github.com/nodejs/release?tab=readme-ov-file#nodejs-release-working-group)) and bump tsx
2. Pin Node.js version to 18.18.2 in Netlify
3. Use something other than `tsx`

I guess the 1 is the best option?

**Comment by JoshuaKGoldberg** [comment]
🤔 per https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript it looks like we've pinned Node to 16 in the UI... 

![Screenshot of Dependency management settings in Netlify showing Node 16](https://github.com/typescript-eslint/typescript-eslint/assets/3335181/c1b6c883-52bd-4223-ae17-be69816cd655)

We wouldn't be able to drop Node.js 16 support until our next major version, as that'd be a breaking change. So for now we can either use something other than `tsx` or pin the Node.js version in Netlify to <=18.18.2.

**Comment by JoshuaKGoldberg** [comment]
Ah but _environment variables_ are used instead - and `NODE_VERSION` was set to `18`. I switched it to `18.18.2` just now. So this _should_ be fixed. Thanks for filing!

If not, we can re-open and take another look.

**Comment by JoshuaKGoldberg** [comment]
Following #8045 -> #8048, we should be able to remove that env variable. I've set a reminder for January 3rd, just in case an older PR doesn't have the updated version of tsx.
