### ISSUE TITLE
[FEAT] Accept a glob pattern for `options.project`

### ISSUE THREAD

**Issue by Teoxoy** [typescript-eslint/typescript-eslint#803]
Original discussion started here: https://github.com/typescript-eslint/typescript-eslint/issues/624#issuecomment-517747335

**Comment by Teoxoy** [comment]
Following up from https://github.com/typescript-eslint/typescript-eslint/issues/624#issuecomment-518309864

> If you provide `project`, then it requires node because of the typescript compiler.
Otherwise it doesn't require node.
Hence astexplorer.net works without a project.
We'd have to do some work to make it work fine in the browser with a project.

@bradzacher
@uniqueiniquity

Should the glob functionality therefore go in the `parser` package because `typescript-estree` is independent of Node?

**Comment by bradzacher** [comment]
Unless I'm mistaken, `parser` doesn't actually care about the tsconfig, and just passes it down to `typescript-estree`.

I would put it into `typescript-estree` so that both packages can take advantage of the functionality.

**Comment by Teoxoy** [comment]
> Hence astexplorer.net works without a project.

I understood this wrong, I thought astexplorer.net uses `typescript-estree` but it uses `acorn` hence I asked the question.

> We'd have to do some work to make it work fine in the browser with a project.

Now this makes sense lol

---

So the bottom line is that Node independence might be something to be dealt with in the future and for now I will go ahead and add the glob pattern functionality in `typescript-estree`

**Comment by bradzacher** [comment]
> I thought astexplorer.net uses typescript-estree but it uses acorn hence I asked the question.

astexplorer.net does in fact use `typescript-estree`, though it is intrinsically via `parser` when you select our parser from the list.

it doesn't pass `project` in to `parser`, so `parser`/`typescript-estree` just parses the source code as given, as opposed to trying to use typescript to read the file from disk.

**Comment by Teoxoy** [comment]
Oh, I see. I overlooked the fact that the parser could be changed (I expected the place where it mentions the parser name to be a dropdown)

https://github.com/typescript-eslint/typescript-eslint/blob/39e41b56ca26047cc1a1fdf7330e0bee928dc720/packages/typescript-estree/src/parser.ts#L395-L400

I should have looked at the code.
Although `shouldProvideParserServices` means something else in my head. 😆
