### ISSUE TITLE
Configs: `no-unsafe-unary-minus` and `prefer-destructuring` are missed in the `disable-type-checked` config

### ISSUE THREAD

**Issue by auvred** [typescript-eslint/typescript-eslint#8034]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

`no-unsafe-unary-minus`: https://github.com/typescript-eslint/typescript-eslint/blob/ee158a6533778094cb78d8446d5ee29793b440d8/packages/eslint-plugin/src/rules/no-unsafe-unary-minus.ts#L15
`prefer-destructuring`: https://github.com/typescript-eslint/typescript-eslint/blob/ee158a6533778094cb78d8446d5ee29793b440d8/packages/eslint-plugin/src/rules/prefer-destructuring.ts#L71

Both rules require type information, but they aren't listed here: https://github.com/typescript-eslint/typescript-eslint/blob/ee158a6533778094cb78d8446d5ee29793b440d8/packages/eslint-plugin/src/configs/disable-type-checked.ts#L10-L56

### Impacted Configurations

`disable-type-checked`

### Additional Info

I've also noticed two additional things:
1. The `check-configs` tests don't check the `disable-type-checked` config ([source](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/tests/configs.test.ts))
2. It looks like the description of the `check-configs` and `check-docs` scripts got lost from the contributing guidelines [in this commit](https://github.com/typescript-eslint/typescript-eslint/commit/71d6ed7d140c13303a13f594c969bde4504bf81b#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055L72-L73). I think it'd great to bring them back (e.g mention them [here](https://typescript-eslint.io/contributing/local-development#proofreading)?)

I should open the issue for each of them?

**Comment by JoshuaKGoldberg** [comment]
> I should open the issue for each of them?

That would be great, yes please! If you don't have the time we can too 😄 but much appreciated at least bringing it up either way!
