### ISSUE TITLE
Bug: no-misused-promises ignores conversion of Promise to void for generic higher-order-functions with fixed type parameter

### ISSUE THREAD

**Issue by mx-bernhard** [typescript-eslint/typescript-eslint#8054]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.2&fileType=.ts&code=C4TwDgpgBAqgdgazgewO5wM4DECucDGUAvFABQB0lAhgE4DmGAXFHkmnANoC6AlMQHwtEKdAG4AUONCQoAJQjAcNTADVkASwAmxMnyKCAbhs0TxmiPgA2taPmSZgLDBADCVS5YBGVfAkbioKAAeABVcAmB1eygIAA9gCDhNDFhhdmw8fEFSADM4ZjDMyPs9QUKIqLhTcysbKDsHJ1d3Lx8EeUVldTg6NS1maQhkHKa3D29fII6lVWN%2BUxxnMdbfaa6evs1SUioMEAJdASgAbygAXx4eUSgAehv65BoaC2BJRebxtqmFGYxN-h2ewOpFKJ3OV1u9wwAAtkDhLNpPNBnmBHgltLsoKgIB5xEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oFtLlZkiACa1i0Dr0GoMAbXDYciaOOiQANPIVYF2SGQAWiMgGtkANQ6UhAJUT5Y0JujD44iTdgC%2BHgLrzvnkA&tsconfig=&tokens=false

### Repro Code

```TypeScript
type UnknownsFunc = (...args: unknown[]) => unknown;

type ReturnsVoid = () => void;

declare const useCallback:
  <TFunction extends UnknownsFunc> (fn: TFunction) => TFunction;

declare const useCallbackReturningVoid: typeof useCallback<ReturnsVoid>;

useCallbackReturningVoid((async () => { })); // correct

useCallback<ReturnsVoid>(async () => { }); // should be reported as well
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-misused-promises": [
      "error",
      {
        "checksVoidReturn": true
      }
    ]
  }
};
```

### tsconfig

```jsonc
{
}
```

### Expected Result

Line 14 should be reported as well since it is the exact same effective type as line 12 because the generic type parameter has been provided in both cases, thus restricting the functions to void returning functions.

### Actual Result

Line 14 is not reported.

### Additional Info

As a workaround, we will be using restricted types similar to `typeof useCallback<Fn>` in our code base.

**Comment by JoshuaKGoldberg** [comment]
Whoo, what an odd edge case. Thanks for filing. I took the liberty of modifying the code snippet in the OP to have a bit more descriptive variable names and succinct code. It took me a bit to parse this one. 😄
