### ISSUE TITLE
Repo: Docs should suggest how (and when) to continue a locked conversation

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8070]
### Suggestion

Right now, we have a GitHub bot that locks issues and PRs that have been resolved for a week:

https://github.com/typescript-eslint/typescript-eslint/blob/b2b8ce2bebb1327ff08ce3d98c7521cd1bdab74c/.github/workflows/lock.yml#L17-L25

We like this because most of the time there's no need to comment on a resolved discussion. Most comments we saw before setting that aggressive lock bot were misfiled ones that should have been new issues. For issues that was commonly folks arguing the conclusion without providing substantial new reasoning. For PRs it was often resultant bug reports or feature requests.

However! There are some cases where it makes sense to continue a discussion. If there is some big new piece of information that wasn't known when the issue was closed, it might be good to resume or restart the discussion. But we don't explain how to do that.

Example: https://discord.com/channels/1026804805894672454/1184872910293315704/1184872910293315704 was a thread on Discord asking about revisiting #906 >4 years after the issue was resolved. We'd prefer a new issue or GitHub Discussion as appropriate... but only if there's substantial new information to be brought up.

Proposal: let's fill out the `issue-comment` and `pr-comment` fields on the lock workflow with:

* A friendlier-phrased summary of why we lock
* When it's ok to restart the conversation (when there's significant new information)
* How to do so (the normal GH issue or discussion flow, with a back-reference to the previous one)

**Comment by bradzacher** [comment]
I don't think using the comment fields is a good idea. Comments create notifications which are just spam for all watchers (doubly so for us).

I'm 100% in favour of better docs but -1 on comment.

**Comment by Josh-Cena** [comment]
Maybe the bot can add a "locked due to age" label, which links to the docs?
