### ISSUE TITLE
consistent-type-imports

### ISSUE THREAD

**Issue by ph08n1x** [typescript-eslint/typescript-eslint#8071]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/consistent-type-imports

### Description

I saw in the code of this rules there is a disinfection between an import having:

- all imports are types 
- some of the imports are types

My team would like to only employ import type if all the imports are types. However if only some are then we would like to leave the import "as is". I see there is no option for this in the rule options. I was wondering if you guys would be open to this though?

If so, I don't mind submitting a PR

Let me know, thanks!

### Fail

```TypeScript
// typeA and typeB are types, valueA is not a type
import { typeA, typeB } from 'file.ts';
```

### Pass

```TypeScript
// typeA and typeB are types, valueA is not a type
import { typeA, typeB, valueA } from 'file.ts';
import type { typeA, typeB } from 'file.ts';
```

**Comment by bradzacher** [comment]
Thanks for the request.
The rule exists purely to enforce that specifiers only used in a type-location are always marked as such.

If you would like to use a divergent style where they only "sometimes" are then that is not a usecase we're looking to support. We aren't looking to satisfy all usecases - only the major ones.
