### ISSUE TITLE
Enhancement: [prefer-nullish-coalescing] Add autofix for safe cases known through type narrowing

### ISSUE THREAD

**Issue by park-jemin** [typescript-eslint/typescript-eslint#8077]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/prefer-nullish-coalescing

### Description

It would be nice to have some autofixing for relatively safe cases based on the type narrowing (such as through a ternary expression, or if using `||` on the falsy value associated with a primitive type). The rule appears to already have a dedicated message for it, but it would be a nice enhancement to have.

### Fail

```TypeScript
let currentValue: string
const defaultValue: string = 'some value';

// Ternary case for null check
const potentiallyNull: string | null = getStringOrNull(); // maybe from `localStorage.getItem`

currentValue = potentiallyNull !== null ? potentiallyNull : defaultValue;

// Ternary case for undefined check
const potentiallyUndefined: string | undefined = getStringOrUndefined();

currentValue = potentiallyUndefined !== undefined ? potentiallyUndefined : defaultValue;

// OR primitive cases with known falsy values
const stringNull: string | null = externalValue || '';
const stringUndefined: string | undefined = externalValue || '';
const stringNullish: string | null | undefined = externalValue || '';

const numberNull: number | null = externalValue || 0;
const numberUndefined: number | undefined = externalValue || 0;
const numberNullish: number | null | undefined = externalValue || 0;

const booleanNull: boolean | null = externalValue || false;
const booleanUndefined: boolean | undefined = externalValue || false;
const booleanNullish: boolean | null | undefined = externalValue || false;
```

### Pass

```TypeScript
let currentValue: string
const defaultValue: string = 'some value';

// Ternary case for null check
const foo: string | null = getStringOrNull(); // maybe from `localStorage.getItem`

currentValue = foo ?? defaultValue;

// Ternary case for undefined check
const bar: string | undefined = getStringOrUndefined();

currentValue = bar ?? defaultValue;

// OR primitive cases with known falsy values
const stringNull: string | null = externalValue ?? '';
const stringUndefined: string | undefined = externalValue ?? '';
const stringNullish: string | null | undefined = externalValue ?? '';

const numberNull: number | null = externalValue ?? 0;
const numberUndefined: number | undefined = externalValue ?? 0;
const numberNullish: number | null | undefined = externalValue ?? 0;

const booleanNull: boolean | null = externalValue ?? false;
const booleanUndefined: boolean | undefined = externalValue ?? false;
const booleanNullish: boolean | null | undefined = externalValue ?? false;
```

### Additional Info

It would also be nice to have an option to ignore primitive cases where the right hand value isn't associated with the falsy value of its type - seems tangentially related so I'm not sure if it's a separate issue.

```ts
const foo: string | undefined = '';
const bar: number | null = 0;

// let these be valid
console.log(foo || 'a value');
console.log(bar || 100);

// while still flagging these
console.log(foo || '');
console.log(bar || 0);
```

**Comment by bradzacher** [comment]
Your number cases aren't a safe fixer because
```ts
declare const x: number | null;
x || 0; // = 0 if Number.isNan(x)
        // = in all other cases
```

We have a suggestion fixer for this rule - but it's just not super easy for us to add an actual fixer for the rule - there are so many cases where we're making assumptions about code and potentially introducing unsafe fixes that change values.

For example imagine:
```ts
declare const x: Record<string, string | null>;
x[y] === null ? '' : x[y];
```
In this case if we autofix it to `x ?? ''` then we've changed the behaviour of the code because if `!(y in x)` then `x[y] === undefined`.

Ultimately I think that this is probably best left as suggestion fixers rather than us trying to codify what is and isn't safe to autofix - I'd rather not do it and get it wrong and break people's code.

**Comment by park-jemin** [comment]
Gotcha, thanks for explaining! Really insightful as usual
