### ISSUE TITLE
typings for "working with plugins" side of eslint

### ISSUE THREAD

**Issue by G-Rath** [typescript-eslint/typescript-eslint#808]
As part of converting `eslint-plugin-jest` to typescript, [I found that there are no typings]((https://github.com/jest-community/eslint-plugin-jest/pull/371)) for [the plugins side of eslint.](https://eslint.org/docs/developer-guide/working-with-plugins#processors-in-plugins)

Is that something `typescript-eslint` would be interested in covering?

**Comment by bradzacher** [comment]
having a look into the attached PRs - I see you're looking for processor types?

Sure thing!
Essentially the things that exist in `experimental-utils` is what was in the [DefinitelyTyped types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/eslint/index.d.ts).

We'd love to have types for any and all things eslint.

**Comment by G-Rath** [comment]
> We'd love to have types for any and all things eslint.

Awesome!

> having a look into the attached PRs

Woops sorry I was meant to link to that header specifically - the anchor tag seems to have gotten lost 😬 

> I see you're looking for processor types?

For now yes, but I'd love to have as much types as possible - the `index.ts` export is completely untyped :(

I'm happy to help try & provide these types - worst case it'll give you a strawman to encourage refinement.

I'll start w/ adding types for the object described in the "Processors in Plugins" section of that page.

**Comment by JamesHenry** [comment]
I believe this issue has been addressed through a mixture of enhancements to `experimental-utils` and updates to DefinitelyTyped, so closing for now
