### ISSUE TITLE
Repo: deprecate no-var-requires in favor of no-require-imports

### ISSUE THREAD

**Issue by Josh-Cena** [typescript-eslint/typescript-eslint#8092]
### Suggestion

I was discussing this with @bradzacher and @JoshuaKGoldberg.

`no-var-requires` is a strict subset of `no-require-imports`: the former only detects `require()` expressions in very limited contexts (including variable declarations, new expressions, call expressions, member expressions). The latter bans all `require` expressions and `import = require` declarations.

They were both imported from other plugins:

- `no-require-imports` comes from TSLint: https://github.com/typescript-eslint/typescript-eslint/pull/199
- `no-var-requires` comes from eslint-plugin-typescript: https://github.com/bradzacher/eslint-plugin-typescript/pull/114 => https://github.com/typescript-eslint/typescript-eslint/commit/470c2648ef861d36e081e4351c5281e951fe0e47 which in turn comes from TSLint!

Why TSLint has two rules remains unknown, but for the purpose of our maintenance I don't see why we need both. Let's implement `no-var-requires` as part of `no-require-imports` (an option called `allowAsImport`) instead.

**Comment by bradzacher** [comment]
> They were both imported from other plugins:
> ...
> no-var-requires comes from eslint-plugin-typescript:

Nitpick note: the rule didn't come from `eslint-plugin-typescript` - instead `eslint-plugin-typescript` became/was renamed to `@typescript-eslint/eslint-plugin`.

**Comment by bradzacher** [comment]
One note is that it is a nice feature to ban `require` but allow `import = require`.

I.e. It allows a codebase to function without CJS interop.

We'll need to take care of the rule options to ensure we don't lose coverage.

**Comment by Josh-Cena** [comment]
> it is a nice feature to ban require but allow import = require.

That's exactly the proposed `allowAsImport` option!
