### ISSUE TITLE
Docs: Document @typescript-eslint/type-utils

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8093]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

https://www.npmjs.com/package/@typescript-eslint/type-utils says:

> 👉 See https://typescript-eslint.io/packages/type-utils for documentation on this package.

https://typescript-eslint.io/packages/type-utils is a 404.

Additionally, #8089 raises a good point: it's not clear whether `@typescript-eslint/type-utils` is part of our public API...
* If it is: we should document it and fill in the 404 page
* If it isn't: we should change its README.md to mention it

### Affected URL(s)

https://typescript-eslint.io/packages/type-utils and/or https://www.npmjs.com/package/@typescript-eslint/type-utils

**Comment by bradzacher** [comment]
It is - we just didn't do a good job of documentation when it was created. The utils package is poorly documented as well. There's an issue for that somewhere too.

**Comment by JoshuaKGoldberg** [comment]
Adding to the v8 milestone to make sure we get to it by then. This isn't a breaking change at all, so it's fine to come in sooner.

**Comment by JoshuaKGoldberg** [comment]
There are enough functions in `utils` and `type-utils` that IMO we should autogenerate the docs - not hand-write them. I found two [TypeDoc](https://typedoc.org) plugins for Docusaurus that seem feasible:

* https://github.com/milesj/docusaurus-plugin-typedoc-api
* https://typedoc-plugin-markdown.org

The latter looks to be a pretty nice drop-in-and-work solution. Trying it out.
