### ISSUE TITLE
New rule: prevent parallel pending promises before await

### ISSUE THREAD

**Issue by ackvf** [typescript-eslint/typescript-eslint#8098]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-floating-promises/

### Description

In a situation like this, when a promise is awaited (and later fails), while another has already failed, it results in an uncaught error.
In the example below, the failed promise is at the line `const r2 = await p2`, when it throws, the following code never runs and therefore the remaining promises are **never awaited**.

More explanation https://stackoverflow.com/a/69644993/985454

```js
try {

  const p1 = Promise.resolve('p1:success')
  const p2 = Promise.reject('p2:failure')
  const p3 = new Promise((resolve, _) => {
    setTimeout(() => {
      console.log('p3 finished')
      resolve("p3:success")
    }, 3000)
  })
  const p4 = new Promise((_, reject) => {
    setTimeout(() => {
      console.log('p4 finished')
      reject("p4:failure")
    }, 1000)
  })
  

  const r1 = await p1
  const r2 = await p2 // p2 fails, following code never runs, therefore p3 throws uncaught error!
  const r3 = await p3 
  const r4 = await p4 // ❌ Uncaught promise error

  console.log('await:', [r1, r2, r3, r4]) // this doesn't run too


  // this would also throw ❌
  // Promise.all([p1, p2, p3, p4]).then((values) => { // ✅ error caught by no-floating-promises rule
  //   console.log('all:', values)
  // })


  // this would not throw ✅
  // await Promise.all([p1, p2, p3, p4]).then((values) => {
  //   console.log('all:', values)
  // })

} catch (e) {
  console.log('catch:', e)
}
```

My suggestion is that given a new rule or [`no-floating-promises`](https://typescript-eslint.io/rules/no-floating-promises/) rule, when an `await` is encountered AND there are more than one pending promises, the rule will suggest to use `await Promise.allSettled` or to append `.catch()` to prevent unexpected behavior that may result in uncaught errors.

Strangely enough, the `no-floating-promises` rule does not catch these cases
```
const p2 = Promise.reject('p2:failure') // ❌ no error given

const p4 = new Promise((_, reject) => { // ❌ no error given
  setTimeout(() => {
    console.log('p4 finished')
    reject("p4:failure")
  }, 1000)
})

Promise.all([p1, p2, p3, p4]).then((values) => { // ✅ error: Promises must be awaited, end with a call to .catch, ...
  console.log('all:', values)
})
```

### Fail

```TypeScript
const p1 = Promise.resolve('p1:success')
const p2 = Promise.reject('p2:failure')
const p3 = Promise.reject('p3:failure')

const r1 = await p1 // First promise is ok
const r2 = await p2 // ❌ Error: Promise may potentially throw. Use `Promise.allSettled` or append `.catch()` to each promise.
const r3 = await p3 // ❌ Error: Promise may potentially throw. Use `Promise.allSettled` or append `.catch()` to each promise.
```

### Pass

```TypeScript
const p1 = Promise.resolve('p1:success').catch(handlePromise)
const p2 = Promise.reject('p2:failure').catch(handlePromise)
const p3 = Promise.reject('p3:failure').catch(handlePromise)

// 1

const r1 = await p1
const r2 = await p2
const r3 = await p3

// 2

await Promise.allSettled([r1, r2, r3])
```

### Additional Info

Migrated from https://github.com/typescript-eslint/typescript-eslint/discussions/8097

**Comment by bradzacher** [comment]
This doesn't fit within `no-floating-promise` either - that rule is specifically about preventing cases where a promise is created but not stored anywhere or awaited - eg an expression statement (like a function call) whose return value is a promise and is not stored anywhere.

There isn't another rule wherein this check would really fit - if anything it likely belongs in a new rule.

---

I definitely understand the motivation behind -- though it is a bit of a rarer case overall, I think. It's not _super_ often that people need to work with multiple promises running in parallel.

I'm not sure if this sort of rarer usecase belongs in our project because it's so rare. I'll leave this open to evaluate engagement for now.

**Comment by JoshuaKGoldberg** [comment]
FWIW I'd think this should belong in a community plugin. It feels like a nebulous area that needs to "experiment in production" to stabilize.

**Comment by Josh-Cena** [comment]
Yeah, figuring out dependencies between asynchronous tasks is already very hard and analyzing their resolution order accurately sounds nearly impossible.

**Comment by bradzacher** [comment]
That's 3 members against adding this to the project for now.
So I'm going to close this now.
Feel free to build this as a new 3rd party plugin or consider adding it to an existing one.
