### ISSUE TITLE
Bug: [consistent-type-imports] Auto-fix doesn't enforce `type` keyword location

### ISSUE THREAD

**Issue by chrispader** [typescript-eslint/typescript-eslint#8163]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.2&showAST=types&fileType=.ts&code=PTAECEFMDMHsCdKgEQEMCuAXWBaaBLAD2QC5RUAbRVAEwE9QALVAZ1HwDsLOlM6AHJAGtIdAO4IaLAFD4AtvwSZQAb1B9BoACoDIARgA063dt0AmUAF9Q0eLDmgA5ADpgGyC0cBuadPegADVAAXlNBPT8TAE0QsMgzIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6MgeyeUuX0Ra0ipWpQC2xDtHyoMAbXDYciaNCmQANIqVYleyMWiIAZivRRhiURKkzN2vTmOUAHgGUiSc5GSJiAQ2h-fiESK3FJaVQHCABfBwBdRXjYoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
// Before "auto-fix": already has inline type keywords
import {type Type1, type Type2} from './types';

// Expected: after "auto-fix" should use "separate" type imports)
import type {Type1, Type2} from './types';

// Actual: "inline-type-imports" not replaced with "separate" and vice-versa
import {type Type1, type Type2} from './types';
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    '@typescript-eslint/consistent-type-imports': [
      'error',
      {
          prefer: 'type-imports',
          fixStyle: 'separate-type-imports',
      },
    ],
  },
};
```

### Expected Result

The auto-fix feature of `@typescript-eslint/consistent-type-imports` should also enforce type import style.

### Actual Result

Inline type imports are not automatically replaced by separate type imports and vice versa.

**Comment by bradzacher** [comment]
See the rule docs
https://typescript-eslint.io/rules/consistent-type-imports/#related-to

This section has some rules that will assist you.
