### ISSUE TITLE
Repo: codecov coverage reports are not longer uploaded

### ISSUE THREAD

**Issue by auvred** [typescript-eslint/typescript-eslint#8166]
### Suggestion

This PR https://github.com/typescript-eslint/typescript-eslint/pull/7567 pinned `PRIMARY_NODE_VERSION` variable in CI to `>=20.6.1`
https://github.com/typescript-eslint/typescript-eslint/blob/e566a5dda347470b8ced3cc301b7e4d3e7ed721b/.github/workflows/ci.yml#L16-L17

But this variable is also compared to `matrix.node-version` which van be `16` or `20`
https://github.com/typescript-eslint/typescript-eslint/blob/e566a5dda347470b8ced3cc301b7e4d3e7ed721b/.github/workflows/ci.yml#L194-L217

--- 

`'>=20.6.1' == '20'` -> `false`

Thus, the coverage isn't collected and uploaded

I think we can unpin it since the current version of Node.js is already `20.10.0`

**Comment by auvred** [comment]
Okay, it works with `PRIMARY_NODE_VERSION` set to `20`: https://github.com/typescript-eslint/typescript-eslint/pull/8167#issue-2062162535

**Comment by JoshuaKGoldberg** [comment]
🙃 lovely, thanks for filing. Good spot.
