### ISSUE TITLE
Docs: Document using debug package env variables to debug performance

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8189]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

There are few of debugging options commonly used with ESLint:

* [`eslint --debug`](https://eslint.org/docs/latest/use/command-line-interface#--debug): enabling all of ESLint's debug logs
* [`parserOptions.debugLevel`](https://github.com/typescript-eslint/typescript-eslint/blob/7ddadda10845bc53967eeec83ba6b7cdc71a079f/packages/typescript-estree/src/parser-options.ts#L36): a shortcut to set `eslint`, `typescript`, and/or `typescript-eslint`
* Directly setting the `DEBUG` environment variable for [`debug`](https://github.com/debug-js/debug)

Splitting out of https://github.com/typescript-eslint/typescript-eslint/discussions/8030#discussioncomment-8007051: it'd be good to document using these appropriately for performance investigations.

### Affected URL(s)

https://typescript-eslint.io/linting/troubleshooting/performance-troubleshooting, perhaps?

**Comment by cben** [comment]
* Also, mention `TIMING=1` env var to for breakdown by rules to help figuring out if this is even the relevant repo?
  From googling up as a newcomer (and I'll admit I haven't read most of the docs yet), I'm now bouncing between typescript-eslint <-> plugin-import, both of which IIUC tend to parse the whole transitive closure of imported files(?).  The https://typescript-eslint.io/troubleshooting/performance-troubleshooting/#eslint-plugin-import section was useful :+1: but could be great to include some advice / recommended DEBUG= values to confirm how much double/transitive parsing is happening.
