### ISSUE TITLE
Configs: Provide configs that only have type-checked rules

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8195]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

I've been researching how native speed linters compare to typescript-eslint in terms of features. For the most part the tradeoff is significantly improved performance but no type checking and reduced availability of community rules. Blog post here: https://github.com/JoshuaKGoldberg/dot-com/pull/143

One option that's been brought up is running _two_ linters - what I'm tentatively calling "dual-linting" in my head. https://github.com/JoshuaKGoldberg/dot-com/pull/143#discussion_r1436919543 -> https://github.com/withastro/adapters/pull/111#issuecomment-1866059732

We don't yet provide a way to enable _only_ the type-checked rules. Which is a little inconvenient for linting. Assuming all non-type-checked rules are implemented by a native speed linter, enabling only those ones would have to be done either:

* Manually: with hand-written or semi-automated changes with each typescript-eslint version
* Dynamically: by importing the typescript-eslint `*-type-checked` config object and removing the `extends` property

As a courtesy to users who want this, maybe we should export standalone configs that make it easier to achieve just enabling type-checked rules? `recommended-type-checked-only`, `strict-type-checkedonly`, and `stylistic-type-checked-only`, perhaps?

### Impacted Configurations

* `recommended-type-checked-only`
* `strict-type-checkedonly`
* `stylistic-type-checked-only`

### Additional Info

A downside of this would be adding more sections and vertical space to https://typescript-eslint.io/linting/configs that aren't useful for the majority of our users. Though, we can always put these configs under the _"Other Configurations"_ section so they don't take up space in the important, more-likely-to-be-read areas.

**Comment by bradzacher** [comment]
> We don't yet provide a way to enable only the type-checked rules.

We did have that!
But in v6 you made the swap to merging the configs so people didn't need to extend other configs and got everything for free with fewer lines of config! Heh

**Comment by JoshuaKGoldberg** [comment]
![Steve Urkel from Family Matters saying "did I do that?" in an amused manner](https://github.com/typescript-eslint/typescript-eslint/assets/3335181/9244fe2f-6891-4529-983f-8feb9f5340d9)

**Comment by JoshuaKGoldberg** [comment]
Adding to the v8 milestone to make sure we get to it by then. But this isn't a breaking change and can be done first.
