### ISSUE TITLE
Bug: Project service doesn't infer compilerOptions for files not included in a tsconfig.json

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8206]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

Moving https://github.com/typescript-eslint/typescript-eslint/discussions/8030#discussioncomment-8030825 into a standalone issue: users are going to want to be able to lint `.eslintrc.cjs` files without including them in the `tsconfig.json` `compilerOptions.allow` and `include`. But the project service as-is provides a "blank slate" set of default compiler options when a file isn't included in a loaded `tsconfig.json`.

Proposal: if a file is included in `allowDefaultProjectForFiles` (added in #7752) and isn't given compiler options from a loaded TSConfig, instead give it the compiler options for the nearest `tsconfig.json`?

### Reproduction Repository Link

https://github.com/JoshuaKGoldberg/repros/tree/ts-eslint-project-service-not-included

### Repro Steps

1) clone the repo
2) `npm install`
3) `npm lint`

### Versions

| package                                | version   |
| -------------------------------------- | --------- |
| `@typescript-eslint/parser`            | `6.18.0`  |
| `@typescript-eslint/typescript-estree` | `6.18.0`  |
| `TypeScript`                           | `5.3.3`   |

**Comment by bradzacher** [comment]
I dunno if we should magically infer the options like that. I kinda hate black-box magic like that.

I'd be happy with an option to set the tsconfig used for extra files - so people could configure it from their eslint config. Then if they wanted to explicitly use a specific config then they could `require` it in place.

As an example the closest tsconfig might be one for Web files and include like the DOM libs or have a really restricted es version. An explicit config would let someone tweak things for their node env

**Comment by mrazauskas** [comment]
Some `defaultTSConfig` option makes sense for me. It could take a path to `tsconfig.json` and use compiler options found there for inferred projects. Also the default value could be `'./tsconfig.json' | './jsconfig.json'`. This is some magic too, but with a possibility to opt out.
