### ISSUE TITLE
Enhancement: Prevent Promises from Being Compared With null or undefined

### ISSUE THREAD

**Issue by kevinMEH** [typescript-eslint/typescript-eslint#8207]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Currently, you are allowed to compare a Promise with undefined or null, but not any other value (other than another Promise). However, this behavior could potentially lead to unwanted behavior. Take this example:

Link: [Playground Link](https://typescript-eslint.io/play/#ts=5.3.3&fileType=.tsx&code=IYZwngdgxgBAZgV2gFwJYHsIwggtgIwFMAnAeWIFUIATQuVCQ6gCgDdgAbBQgLmzyLEAlHwAKxdLlQhCAHhwESMAD4wkteo2oA%2BGAG8AsACgYMVHBhtO3GAFIYAJhgBeVzAAMQmMULIExLHU6BiYAbmNTHz8AmHYuQnCjAF9jYyhMEGQYAAcJKRkXfkUyShpgrWYAZmqhRPNLXMlpQhc3IM0mL0MTGHSIEHQOQgA6DnQAc2YAIgA5ASVpGEJWQggpoWMkoA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

```
async function numberOrUndefined(value: number): Promise<number | undefined> {
  if (value % 2 === 0) return undefined;
  return value;
}

const promise = numberOrUndefined(333);
if (promise === undefined) {
  console.log("Number is even")
}
```

In the case above, the user is trying to check if the result of the Promise is undefined. However, the user forgot to put the keyword `await`, and is therefore trying to check if the Promise is undefined, which is always false, as a Promise is never equal to undefined.

A similar case arises if the return value of the function is `Promise<number | null>` and the user is checking for `null`.

In this case, it is obvious that the user needs to `await`; the function definition is 5 lines above and unless the user has amnesia, they would know that an `await` is necessary to properly compare the value of the Promise. However, sometimes it is not so obvious, with function definitions being hidden away in another file or inside another package.

I don't see a reason why this behavior would be allowed, especially since it is clear that any function with a return signature of `Promise<...>` will always return a Promise, an object that is not comparable to null or undefined. Even in a case where a Promise along with null or undefined is to be returned, the return type would now be different, and thus the check would not apply:
```
function numberOrNull(value: number): Promise<number> | null {
    if(value % 2 === 0) return null;
    return Promise.resolve(value);
}
```
In the function above, the return type is now `Promise<number> | null`, which is entirely different than `Promise<number | null>`, and thus the check would not apply.

(PS: I am surprised that this check hasn't been implemented yet. Does there exist some case where such behavior is valid, or is the lack of implementation the result of some oversight, or is there something particular about the type behaviors of null and undefined which makes implementation of such a rule difficult?)

### Fail Cases

```TypeScript
async function numberOrUndefined(value: number): Promise<number | undefined> {
  if (value % 2 === 0) return undefined;
  return value;
}

// Bad! Need await for proper evaluation. Type Promise has no overlap with undefined.
if (numberOrUndefined(222) === undefined) {
  console.log("Number is even")
}

function numberOrNull(value: number): Promise<number | null> {
  if (value % 2 === 0) return Promise.resolve(null);
  return Promise.resolve(value);
}

// Bad! Need await for proper evaluation. Type Promise has no overlap with null.
if (numberOrNull(222) === null) {
  console.log("Number is even")
}
```

### Pass Cases

```TypeScript
function numberOrUndefined(value: number): Promise<number> | undefined {
  if (value % 2 === 0) return undefined;
  return Promise.resolve(value);
}

// Correctly evaluated, as Promise<number> | undefined has an overlap with undefined.
if(numberOrUndefined(322) === undefined) {
  console.log("Number is even");
}
```

**Comment by bradzacher** [comment]
[playground](https://typescript-eslint.io/play/#ts=5.3.3&fileType=.tsx&code=IYZwngdgxgBAZgV2gFwJYHsIwggtgIwFMAnAeWIFUIATQuVCQ6gCgDdgAbBQgLmzyLEAlHwAKxdLlQhCAHhwESMAD4wkteo2oA%2BGAG8AsACgYMVHBhtO3GAFIYAJhgBeVzAAMQmMULIExLHU6BiYAbmNTHz8AmHYuQnCjAF9jYyhMEGQYAAcJKRkXfkUyShpgrWYAZmqhRPNLXMlpQhc3IM0mL0MTGHSIEHQOQgA6DnQAc2YAIgA5ASVpGEJWQggpoWMUoyA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oFtLlZkiACa0miAO7ooiaNA7RIAGnDY8RUsgrU6DZm061YTMWRTIAhtEK0yHJkMr5KdqZBlyFKgL4gvQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

Our `no-unnecessary-condition` rule does exactly what you want and will error if the types don't overlap.

---

TS will error if you drop the `=== undefined` check and will suggest awaiting. But TS will never ever error about an undefined check because it assumes they're there on purpose for safety reasons (eg missing keys in records or missing elements in arrays).

**Comment by JoshuaKGoldberg** [comment]
> I don't see a reason why this behavior would be allowed

```ts
declare function getPendingPromise(): Promise<string>;

const pending = getPendingPromise();

if (pending) {
  console.log("Work has started yet");
} else {
  console.log("Work hasn't started yet.");
}
```

Perhaps this warrants an FAQ page? Maybe a dedicated FAQ page for common rule requests? I anecdotally think this gets asked a few times a year (haven't exhaustively searched to see how often).

**Comment by kevinMEH** [comment]
Thanks, the `no-unnecessary-condition` indeed solves my problem. Perhaps there is a miniscule argument to be made here that a subset of the rule should be turned on by default for Promises, as it is almost always unwanted behavior when a Promise is being compared to null or undefined, and some people (like me) prefer explicit checks to null or undefined in conditionals rather than to type convert to a boolean inside a conditional.

---

As for the second comment, I'm afraid I don't see the point; won't "Work has started yet" always be printed? A Promise is a Promise object regardless of whether or not work has started or work has completed, and will thus always be considered a truthful value.

**Comment by JoshuaKGoldberg** [comment]
>  I'm afraid I don't see the point; won't "Work has started yet" always be printed?

Oh, shoot, typo in the post - I'd meant for the declared function to return `Promise<string | undefined>`. Edited. The general point was that sometimes code is written to intentionally use a nullish `Promise<...>` indicating whether something was created. This pattern is valid and so we can't lint against it by default.

**Comment by kevinMEH** [comment]
I'm afraid I still don't see the point here... Even if the Promise object holds the value `undefined`, the Promise will still be a truthful value. Please run the following program in Node or your console:

```
const maybe = Promise.resolve(undefined && "asdf"); // Promise<string | undefined>
await 1; // Next tick, so maybe now contains value of undefined.
console.log(maybe); // As you can see, maybe contains value of undefined, but maybe itself is still a Promise object.
if(maybe) {
    console.log("Not undefined... Surely?!"); // False; the maybe Promise object is always truthful.
} else {
    console.log("Undefined"); // Never executes
}
```

**Comment by kevinMEH** [comment]
Ok, but as I have mentioned above, `Promise<string> | undefined` is an entirely separate case from `Promise<string | undefined>`:

> ![image](https://github.com/typescript-eslint/typescript-eslint/assets/71391217/4b426fc3-13f9-4664-982b-055cad932cea)

I only suggested for a rule to be added for the latter case, not the `Promise<string> | undefined` case.

And unless you really meant that your declared function is to return `Promise<string | undefined>`:

> ![image](https://github.com/typescript-eslint/typescript-eslint/assets/71391217/5df96be3-e0f8-4a83-bf41-14c5602f0b59)

I would just like to mention that the return type of a function which returns `Promise<string | undefined>` is still guaranteed to be a Promise object, and is thus a truthful value regardless of whether or not the Promise holds an undefined or not.

I don't want to waste your time or anyone elses time here, so feel free to close this at any time, but I am still confused as to why my request is seen as a trivial one, worthy of being explained in an FAQ.

**Comment by bradzacher** [comment]
Ultimately there's not a whole lot of difference between `Promise<T | undefined> === undefined` or `T === undefined`. Ultimately they're the same thing - it's an unnecessary condition based on the types.

TS is very good at helping you figure out when you've forgotten an `await` - if you delete the `=== undefined` then TS will report an error:
```
This condition will always return true since this 'Promise<number | undefined>' is always defined.(2801)
Did you forget to use 'await'?
```

But they don't report on `=== undefined` because it's a common guard against incorrect types.

It might be worth asking TS if they'd extend their coverage specifically to handle promises of the form `Promise<T | undefined> === undefined` (and `Promise<T | null> === null`) as it's unlikely that in those cases someone actually meant to not await the promise.

**Comment by JoshuaKGoldberg** [comment]
> why my request is seen as a trivial one, worthy of being explained in an FAQ

😦 I think we have different understandings of what it means to be in an FAQ! My understanding is that it's because it's a good question that a lot of people ask. As in, this is the opposite of trivial. It's important!
