### ISSUE TITLE
Rule proposal: make declaration merging an error

### ISSUE THREAD

**Issue by danvk** [typescript-eslint/typescript-eslint#8208]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Stefan Baumgartner's _TypeScript Cookbook_ offers this terrifying example of accidental declaration merging:

```ts
interface FormData {
  name: string;
  age: number;
}

function process(data: FormData) {
  console.log(data.entries()) // type checks but crashes at runtime
}
```

The issue is that `FormData` is also a browser thing, so rather than declaring a new `interface`, you're actually merging into the existing `interface` from `lib.dom.d.ts`. This likely comes as a big surprise to you, the author of this code, and if you don't know what's going on it's likely to lead to some extremely confusing behavior.

Declaration merging is part of the language and certainly has some valid uses, even in user code. But you should know that you're doing it! My suggestion is to have a linter rule that bans declaration merging. If you know what you're doing, you can disable it on a case-by-case basis.

### Fail Cases

```TypeScript
// error: merges with declaration from lib.dom.d.ts
interface FormData {
  name: string;
  age: number;
}

interface Person {
  firstName: string;
}
// error: merges with previous declaration
interface Person {
  lastName: string;
}
```

### Pass Cases

```TypeScript
// eslint-disable:no-declaration-merging
interface FormData {
  name: string;
  age: number;
}


interface Person {
  firstName: string;
}
// eslint-disable:no-declaration-merging
interface Person {
  lastName: string;
}
```

### Additional Info

There are a few rules that seem related, so maybe this should be an option on one of them.

- #6441 — if you enable `no-redeclare`, set `ignoreVariableMerge: true` and `ignoreDeclarationMerge: false`, then maybe this would do what I want? The [docs for no-redeclare](https://typescript-eslint.io/rules/no-redeclare/) strongly suggest not using it, so I'd be reluctant to add an option to it unless this guidance were lifted.
- [no-unsafe-declaration-merging](https://typescript-eslint.io/rules/no-unsafe-declaration-merging/) — wow, this sounds like exactly what I want! But it bans merging between `interface` and `class`, which is definitely a bad idea, whereas I want to ban merging between `interface` and `interface`, which is less clearly unsafe.

The possibility of accidental declaration merging is often cited as a reason to use `type` rather than `interface`, but this always strikes me as something that could be caught by a linter. A rule like this could help make the case for `interface`.

**Comment by bradzacher** [comment]
If you're using ESM syntax then declaration merging with a global type shouldn't work. Eg your motivating example [reports a type error](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHsoFsAicxzIDeAUMsiHFhAFzIDOYUoA5gNxnJwu0UCuWAEbQOAXxIkYfEAjDB0IZAAco6JPXoAKACb44dDNjwEAlMU4IF9dABsIAOhvoWOvfYjhmELSbMB6P2QwAE8lFAQACwgEAGt6ZEE+MGQEKDh6KPj8ZChpOWoScRIIAA8lTGSicSA).

If you're not using ESM syntax then why not?

**Comment by danvk** [comment]
Looks like I misunderstood the scope in which you can accidentally declaration merge with a built-in. Nevermind, nothing to see here.
