### ISSUE TITLE
Website accessibility: syntax highlighting doesn't always match color contrast thresholds

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8213]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I ran the [axe browser dev tools](https://www.deque.com/axe/browser-extensions) on https://typescript-eslint.io/getting-started. The report indicated we don't have enough color contrast...

* In dark mode:
  * On block comments in code, such as `/* eslint-env node*/`: 3.23:1 (`#737373` on `#242529`) instead of 4.5:1
* In light mode:
  * On the command part of shell scripts, such as `npm install`: 2.76:1 (`#569cd6` on `#f6f8fa`) instead of 4.5:1

Maintaining color contrast for all text above the minimum AA threshold of 4.5:1 is important so that users who need to visually perceive the website can. Lower color contrasts are a potential impediment for folks with reduced vision and/or worse hardware and/or bad lighting conditions. https://dequeuniversity.com/rules/axe/4.8/color-contrast

Accepting PRs to use brighter block comments in dark mode and darker shell script color in light mode.

### Affected URL(s)

https://typescript-eslint.io/getting-started

**Comment by lucas-amberg** [comment]
I'll work on this
