### ISSUE TITLE
Bug: [no-confusing-void-expression] conflict with `return-await`

### ISSUE THREAD

**Issue by xsjcTony** [typescript-eslint/typescript-eslint#8215]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=MYewdgzgLgBAZiEMC8MCGECeZgwBQCUAXDAAoBOIAtgJYQCmAPAG4g0AmAfCt2gO5oasMPT5lKtBnnL0IIADbN6PGAygAVGlXogArlGmyFSgDQwAjAAZrBAgG4AUKEiwARmnIp0WHPmLjqOiZWDm5kbhExCkCpGTlFZXDVeg0tHX1DeNMLa0tbOyA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1rI6YDNYyZgHNaANw6UAJvQAexaCiG90YANrhskRNGgdokADSbsmE6aiVhnRQEFdHAO4BlABb78rgIZMpqvl7wyIjGFlpWNogAapJSAPKk0F74%2Bqr4cIjmEAC%2B5gC6oVoEJORUNPTIjCysiviw0Ey0Xo5elPiqatoOBoZQgS2EqHmaudlAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
const foo = async (): Promise<void> => await new Promise(resolve => setTimeout(resolve, 1000));
const bar = async (): Promise<void> => new Promise(resolve => setTimeout(resolve, 1000));
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-confusing-void-expression": [
    "error",
      {
        "ignoreArrowShorthand": false,
        "ignoreVoidOperator": true
      }
    ],
    "@typescript-eslint/return-await": ["error", "always"]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

`no-confusing-void-expression` should not report for `return await`

### Actual Result

They are conflicting

**Comment by bradzacher** [comment]
There's no conflict here - just two rules which enforce different things.

`no-confusing-void-expression`'s error message mentions how you can fix the error:
```
Void expressions returned from an arrow function shorthand must be marked explicitly with the `void` operator
```

I.e.
```ts
const foo = async (): Promise<void> => void await new Promise(resolve => setTimeout(resolve, 1000));
```

Another alternative is to not return the `void`:
```ts
const foo = async (): Promise<void> => {
  await new Promise(resolve => setTimeout(resolve, 1000));
};
```
