### ISSUE TITLE
Repo: reuse newly added "is builtin symbol like" logic from `type-utils`

### ISSUE THREAD

**Issue by auvred** [typescript-eslint/typescript-eslint#8234]
### Suggestion

Followup for https://github.com/typescript-eslint/typescript-eslint/pull/8011#discussion_r1417737352

We've added few utility functions to the `packages/type-utils/src/builtinSymbolLikes.ts`

Basically they contain the logic for determining whether a given type is a type from the TS default library or not

These files already contain similar logic, it'd be cool if we dedupe it!

https://github.com/typescript-eslint/typescript-eslint/blob/705370ac0d9c54081657b8855b398e57d6ea4ddb/packages/eslint-plugin/src/rules/no-implied-eval.ts#L82-L90 https://github.com/typescript-eslint/typescript-eslint/blob/705370ac0d9c54081657b8855b398e57d6ea4ddb/packages/eslint-plugin/src/rules/no-implied-eval.ts#L145-L153

Let's label this issue as `good first issue`? Ref: https://github.com/typescript-eslint/typescript-eslint/pull/8011#discussion_r1438375603

**Comment by nishit-prasad** [comment]
@auvred @JoshuaKGoldberg

New contributor here:
- I see a utility function defined for this called `isSymbolFromDefaultLibrary()`.

https://github.com/typescript-eslint/typescript-eslint/blob/920f909debc3eb394f5aef4e36568bdf6641e304/packages/type-utils/src/isSymbolFromDefaultLibrary.ts#L3-L20

Shall I use this instead or move this function to `packages/type-utils/src/builtinSymbolLikes.ts` and then use it?

**Comment by JoshuaKGoldberg** [comment]
Oop sorry, just seeing the question now - that does look like a good start! (#8287 continues the discussion)

**Comment by YutongZhuu** [comment]
Hey, I see arka1002 opened a PR but failed to merge it in. I wonder failed to understand why, but I would like to give it a try. However, I am new to open source projects, so I will certainly need some time and help.
