### ISSUE TITLE
Docs: Landing page incorrectly states that TypeScript is strongly typed

### ISSUE THREAD

**Issue by supermacro** [typescript-eslint/typescript-eslint#8241]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

TypeScript is a *statically* typed language, it also happens to be loosely typed.

e.g. TypeScript / JS allow for comparing and operating on values with different types. `1 + "1"` is a valid operation in a loosely typed language such as JS. Whereas in Python (which is strongly typed), that same operation is a runtime exception. 

https://github.com/typescript-eslint/typescript-eslint/blob/85ae4a8977149583b0c501e092a927b1435e68d2/packages/website/src/pages/index.tsx#L54

### Affected URL(s)

https://typescript-eslint.io/

**Comment by JoshuaKGoldberg** [comment]
![Meme clip of girl answering "why can't we have both?" and then her family lifting her happily in the air](https://github.com/typescript-eslint/typescript-eslint/assets/3335181/cd58f498-14c1-4a0b-bccb-42713c965152)

TypeScript describes itself as a strongly typed language. It's on its homepage:

![Screenshot of typescriptlang.org's h1 section. "TypeScript is JavaScript with syntax for types. TypeScript is a strongly typed programming language that builds on JavaScript, giving you better tooling at any scale."](https://github.com/typescript-eslint/typescript-eslint/assets/3335181/1e892dae-a555-453c-a0f2-ee19186f9909)

Closing as if the folks over at TypeScript feel comfortable referring to TypeScript as strongly typed, we are too.

If this distinction is one that is deeply important to you then I'd suggest raising it with the TypeScript project. If they change phrasing, we can change too.
