### ISSUE TITLE
Configs: [prefer-nullish-coalescing] change default for `ignoreConditionalTests` to `true`

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#8243]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

Ref: [#7955](https://github.com/typescript-eslint/typescript-eslint/pull/7955#pullrequestreview-1819739415)

IMO most codebases would prefer to avoid nullish coalescing in conditional tests.

Consider the downlevelled output:
```ts
if (x || y) { }

// vs

if (x ?? y) { } 
// downlevelled to
if (x != null ? x : y) { }
```
There's an extra check there that doesn't do anything.

The logic behind the latter is much harder to grasp exactly, IMO:
- If x is truthy, then true,
- If x is falsey and not nullish, then false,
- Else the boolean coercion of y 

vs the former:
- If x is falsey then false
- Else the boolean coercion of y

It's just A lot simpler to read and understand the non-nullish-coalescing form, IMO.

**Comment by JoshuaKGoldberg** [comment]
Hmm. _Hmm._ I see what you're saying but don't align with it myself. I still like the benefits of the rule for safer `null`/`undefined` logic in conditions... Seeing it in `if`s and the like was a little jarring for me at first, but now that I'm used to it I've come to prefer it this way.

Maybe this is an `evaluating community engagement` issue? cc @typescript-eslint/triage-team

**Comment by JoshuaKGoldberg** [comment]
Meh coming back to this, having tried the rule out on some larger codebases, I'm leaning more towards where you are @bradzacher. I say let's mark this as accepting unless someone has more to say on it.

**Comment by JoshuaKGoldberg** [comment]
#8872 was merged into the `v8` branch. ✅
