### ISSUE TITLE
Enhancement: [no-unsafe-enum-comparison] Disallow comparing enum values with union enums

### ISSUE THREAD

**Issue by RedGuy12** [typescript-eslint/typescript-eslint#8256]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-unsafe-enum-comparison/

### Description

Unions of enums are dangerous because comparisons look misleading and may not accurately narrow the value. See [this example in the playground](https://typescript-eslint.io/play/#ts=5.0.3&fileType=.ts&code=KYOwrgtgBAYg9nKBvAsAKClAglAvFARnQF91RIoAhAQwCdl1MsAjAYz0JPXVbhAGc4AG2AA6IXADmACgCW-Fq2nw4orAEp1AbnQB6XVAAqAC3lRawAC5haAqJdphgAGijNgramH7B7x30KylsC01EJQAG5hTlBwAGbYUNQgACbYbFBmlv5Q-NQQwNxocWAgrJayfJkKbNJxCMx0AFywCFAAPlR06gwY5lY2IFD1cI30uBNdtGpsOn36UAAKtHAADnA%2BaYJCYBV8TYxQCwAi8mESAO5QvBCrdLIgklDk0FE7wPxQF0HGUKWVQxe-C4aCAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZonpNYAW1pkOY4nyrIOTdFETRoHaJHBgAviB1A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false). `Foo.A` and `Bar.Abc` are both compiled to end up as `1` at runtime, and the comparison doesn't actually do anything.

I propose that `no-unsafe-enum-comparison` warns when comparing enum unions to enum values. Alternative solution: warn when defining enum unions (probably in a different rule). However, that would miss cases such as [this one](https://typescript-eslint.io/play/#ts=5.0.3&fileType=.ts&code=KYOwrgtgBAYg9nAKgTwA7CgbwLACgpQCCUAvFAIx4C%2BeokUAQgIYBOK6WeBhARgMakK1PHgAuaDPDiDMUcegBcsBO2AAaKAHoAVFDiiAFsBZRULOOhaiAlsADOUbZqg1c8jMxNlZ7pZ9UaOnqGxqbmljb2js6uIrgAZmAgfDZwIFDWdrx8ABTxCDysSlJQAD6MrACUnPhQLMCiYCzp%2BXCFLAB07qQkZP4SHdkA3FxazgAGre1dEuNQoAAmDmCoUDzA1iAA5lDjUqplFWyzo5rOiEb1%2BfVyBpkZDkxQfHAQqKyZaRkgAG5wADY-TY7JjpOjQJLWNIaYA-UC3OBgLYGKAAdwwC2sCygIH0UAWwHimwwaRJTTswEB9mEuCAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZonpNYAW1pkOY4nyrIOTdFETRoHaJHBgAviB1A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false).

### Fail

```TypeScript
function isAbc(foobar: Foo | Bar) {
  return foobar === Bar.Abc;
}

function isAbc(foobar: { type: Foo } | { type: Bar }) {
  return foobar.type === Bar.Abc;
}
```

### Pass

```TypeScript
function isAbc(foobar: Bar) {
  return foobar === Bar.Abc;
}
function isAbc(foobar: { type: Bar }) {
  return foobar.type === Bar.Abc;
}
```

### Additional Info

There's not an easy way to refactor code like this when it's already been written. Therefore, it's even more important to have a way to catch mistakes like these as they are written.

**Comment by bradzacher** [comment]
I'm not quite sure I understand - where is the unsafely here? Purely based on the types everything is correct and safe.

There's nothing inherently unsafe about overlapping enums in a union. And banning this comparison leads to reports that are completely unactionable for completely valid code.

For example in this repo we have two enums that are overlapping - `AST_NODE_TYPES` and `AST_TOKEN_TYPES`. And it's not uncommon for us to build functions that have a union argument that accepts both enum values - or accepts a union of `Node | Token`. Within the function itself - TS understands the overlap and if you do something like `if (node.type === AST_TOKEN_TYPES.Identifier)` then TS will correctly narrow this to `Node.Identifier | Token.Identifier`.

From what I can tell from your examples - theres no inherent unsafety here unless you are pairing it with already unsafe features like type-guards.

**Comment by RedGuy12** [comment]
My use case is when two unrelated enums are unintentionally overlapping, causing it to be an insufficient way to identify objects. But I see the valid use cases now, my apologies.
