### ISSUE TITLE
Docs: Explain typedef as a transitory rule, not an end recommendation

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#8268]
Currently, [the documentation for the `typedef` rule](https://typescript-eslint.io/rules/typedef/) has a big yellow warning that says to basically not use it. The warning is good, but I think we should go one step further and deprecate the rule.

Why? Well, I see `typescript-eslint` as a collection of industry best-practices. Having this rule exist at all is kind of like tacitly endorsing the style of explicitly annotating everything (as a personal code-base style decision). But is that a style that anyone uses anymore? I have not seen any codebases that use this rule, and would frankly be horrified if they did. =p

By deprecating the rule, it sends a slightly-stronger message of "don't use this".

**Comment by bradzacher** [comment]
https://sourcegraph.com/search?q=context:global+/%5B%22%27%5D%40typescript-eslint%5C/typedef%5B%22%27%5D:+%28%5C%5B%7C%5B%22%27%5Derror%7C%5B%22%27%5Dwarn%29/&patternType=standard&sm=0

Here is a few thousand cases that use it.

**Comment by bradzacher** [comment]
> Having this rule exist at all is kind of like tacitly endorsing the style of explicitly annotating everything

Is it though? The default options make the rule do absolutely nothing and we have that big banner that explicitly warns off using the rule. I think having this rule in this state explicitly shows the opposite - that we don't think this is a good style.

**Comment by bradzacher** [comment]
The rule is good to help people migrate onto better typescript codestyles. For example it can be useful as an interim step before turning on `noImplicitAny` or similar flags. Eg turn the rule on as a warning to not break CI and have people fix things over some window, and then turn it off for the compiler option.

That is how I have always seen the rule - as a rule to help people migrate to stricter things.

Honestly some of the options aren't _that_ bad - even if they do make code more verbose. For example always annotating parameter types or "member variable" types can make for stricter code without being needlessly obtuse.

**Comment by JoshuaKGoldberg** [comment]
Oh, hang on, the rule docs already mention this:

https://github.com/typescript-eslint/typescript-eslint/blob/86409083167bee4ba1ad3ebba22785b3a4a262ee/packages/eslint-plugin/docs/rules/typedef.mdx#L33-L40

Closing as this is a case of _"read the full docs"_.
