### ISSUE TITLE
@t-e/eslint-plugin 2.0.0-alpha.4 has an incorrect peer dependency on @t-e/parser

### ISSUE THREAD

**Issue by octogonz** [typescript-eslint/typescript-eslint#827]
When I install `@typescript-eslint/eslint-plugin@canary`, I get version `2.0.0-alpha.4` with this package.json:

```js
{
  "name": "@typescript-eslint/eslint-plugin",
  "version": "2.0.0-alpha.4",
  "dependencies": {
    "@typescript-eslint/experimental-utils": "2.0.0-alpha.4",
    "eslint-utils": "^1.4.0",
    "functional-red-black-tree": "^1.0.1",
    "regexpp": "^2.0.1",
    "tsutils": "^3.14.0"
  },
  "devDependencies": {
    "@types/json-schema": "^7.0.3",
    "@types/marked": "^0.6.5",
    "chalk": "^2.4.2",
    "marked": "^0.7.0",
    "typescript": "*"
  },
  "peerDependencies": {
    "@typescript-eslint/parser": "^1.9.0",  // <====== ?
    "eslint": "^5.0.0 || ^6.0.0"
  },
  . . . 
}
```
The `@typescript-eslint/parser` package depends on a bunch of other `@typescript-eslint` packages, which seemingly should all be the `2.0.0-alpha.4` version.  

However the peer dependency requires `@typescript-eslint/parser` to be `^1.9.0`, and if I try to do that then I end up with conflicting versions of `@typescript-eslint/experimental-utils`.

Suggested fix:  Change the `@typescript-eslint/parser` peer dependency to be the canary version.

@JamesHenry FYI

**Comment by JamesHenry** [comment]
Thanks, yeah - lerna doesn't update the peerDeps, so every major version we have to remember to change it

**Comment by JamesHenry** [comment]
@octogonz Please can you try out `2.0.0-alpha.5`

**Comment by octogonz** [comment]
That fixed it, thanks!

@JamesHenry  BTW could we get a canary release with PR https://github.com/typescript-eslint/typescript-eslint/pull/790?  That's still blocking some of our projects from moving off of TSLint.

**Comment by bradzacher** [comment]
(closing for housekeeping because the original issue is resolved)
