### ISSUE TITLE
Repo: "🐛 Bug With Another Package" issue template doesn't explicitly ask for an isolated reproduction

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8270]
### Suggestion

The current https://github.com/typescript-eslint/typescript-eslint/blob/01556f50376b87eff21c42d121b627e3a6f003f0/.github/ISSUE_TEMPLATE/06-bug-report-other.yaml never actually _explicitly_ states that reports need a full isolated reproduction. Although folks in theory should know that's required in any open source request, in practice some don't.

#8269 is an example where I wanted to say _"the form/template you filled out asked for this"_. But I couldn't point to a particular line in the form that actually did!

Suggestion: let's add a plain text line, before & similar to the _Note For Complex Issues_ that says something like:

> **All typescript-eslint bug reports need an isolated reproduction** we can clone locally and get running without other projects or existing knowledge of your project. If you can't provide one, your report will likely be closed without action.

**Comment by erikschul** [comment]
@bradzacher 

https://github.com/typescript-eslint/typescript-eslint/issues/8269#issuecomment-1899252117
You closed the issue so now I'm unable to write to you :)

Can you give an example of how I can make a reproducible project for CLI issues? I assume that most online sandboxes don't allow CLI?

**Comment by bradzacher** [comment]
@erikschul The issue template suggests the best way to provide a repro:

> Link to an isolated reproduction repository on GitHub

Best way is to create a github repo and fill it with an _isolated_ setup that reproduces your issue. Ideally we should be able to just checkout your repo, install, and run eslint to see the issue. The important part is making sure it's an isolated reproduction - don't add your whole project - you want just enough files/code to trigger the error.
