### ISSUE TITLE
Enhancement: [require-await] option to not treat `return <thenable>` as an await, and thereby avoid tyepcheck

### ISSUE THREAD

**Issue by benjaminjkraft** [typescript-eslint/typescript-eslint#8302]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/require-await/

### Description

`require-await` has two benefits, and one cost, relative to the eslint version:
1. benefit: it handles TS-specific syntax like `using`
2. benefit: it treats `return <thenable>` (e.g. `return Promise.resolve(1)`) as an `await`
3. cost: it requires type information (because of (2))

We like (1) but don't really need (2). Our codebase is large so typecheck is slow so we want to avoid (3) whereever possible. Let's have an option to avoid type information in that case!

### Fail

```TypeScript
n/a
```

### Pass

```TypeScript
n/a
```

### Additional Info

I'm not sure if there are any subtle implications for generators; I notice that the upstream eslint rule ignores them entirely. If I get a chance I will read the generator spec more carefully to see.

**Comment by bradzacher** [comment]
If you want this behaviour then you can jusy use the base rule.
Our extended version of the rule uses types to validate return statements.

If you use the base rule you don't get that and the rule works as desired.
