### ISSUE TITLE
Configs: consistent-type-definitions should have 'type' as default, not 'interface'

### ISSUE THREAD

**Issue by e-oz** [typescript-eslint/typescript-eslint#8316]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

Currently, rule @typescript-eslint/consistent-type-definitions has default 'interface', and it will encourage newbies to use `interface` instead of `type`, also it will be more difficult to explain why they should use `type`, when a linter says otherwise.

By using `import/export type`, you can avoid loading the whole library when you just need a few models because imports like this will be completely removed during the TypeScript compilation: [documentation link](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export).

Also, you will avoid implicit [interfaces declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-interfaces) and will use explicit [intersection types](https://www.typescriptlang.org/docs/handbook/2/objects.html#intersection-types) (if you want). There are no other significant [differences](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces), so type alias is the best choice.

**Comment by bradzacher** [comment]
The majority of the TS community still defaults to interfaces. The default for this rule isn't there to try and change opinions - unless there is a really good reason to do so.

Declaration merging is really rare overall - it requires two interfaces or classes with exactly the same name. It's usually only done consciously because such a case is hard to do accidentally.

Declaration merging from globals is impossible when using ESM.

You can use type-only exports and type-only imports with interfaces as well - so your point there is moot.

Interfaces are also easier for TS to name in type declarations - leading to smaller and more reusable types for downstream consumers. This gap is closing but still slightly in favour of interfaces.

---

Again - without any significant reason in favour of types - we won't be switching the default. Codebases are free to change the configuration if they prefer types though.

**Comment by e-oz** [comment]
> The default for this rule isn't there to try and change opinions

Until a rule is not on the list of recommended. 

> Declaration merging is really rare overall - it requires two interfaces or classes with exactly the same name

It's a pretty common situation when models located in different features have the same name.

**Comment by bradzacher** [comment]
> Until a rule is not on the list of recommended 

The rule isn't recommended - it's on our **stylistic** config. As the name of the config implies and as the docs state (https://typescript-eslint.io/linting/configs#stylistic) - it's an opinionated config.

So unless you opt-in to the opinionated stylistic config - you won't have the rule turned on.

> It's a pretty common situation when models located in different features have the same name.

This shouldn't matter though? You can't declaration merge across ESM - typescript will error if you do it accidentally ([playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nAwgZRwBSglVmBQGc4BfOAMyJDgCIoUBDAYxiYG4AoPsAB2MFFFqc0uAkRIwyldFT5A)).

**Comment by e-oz** [comment]
> The rule isn't recommended - it's on our stylistic config

You are right. Sorry for the confusion about that.

Out of a sudden, all the stylistic rules become active after updating to 6.20.0 (no changes in .eslintrc.json).
It took 2 hours of my life, so I had to add explicitly to .eslint.json

```json
        // <remove stylistic>:
        // https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/stylistic.ts
        "@typescript-eslint/adjacent-overload-signatures": "off",
        "@typescript-eslint/array-type": "off",
        "@typescript-eslint/ban-tslint-comment": "off",
        "@typescript-eslint/class-literal-property-style": "off",
        "@typescript-eslint/consistent-generic-constructors": "off",
        "@typescript-eslint/consistent-indexed-object-style": "off",
        "@typescript-eslint/consistent-type-assertions": "off",
        "@typescript-eslint/consistent-type-definitions": "off",
        "@typescript-eslint/no-confusing-non-null-assertion": "off",
        "no-empty-function": "off",
        "@typescript-eslint/no-empty-function": "off",
        "@typescript-eslint/no-empty-interface": "off",
        "@typescript-eslint/no-inferrable-types": "off",
        "@typescript-eslint/prefer-for-of": "off",
        "@typescript-eslint/prefer-function-type": "off",
        "@typescript-eslint/prefer-namespace-keyword": "off",
        // </remove stylistic>
```
