### ISSUE TITLE
Repo: Make utility for static member access

### ISSUE THREAD

**Issue by kirkwaiblinger** [typescript-eslint/typescript-eslint#8323]
### Suggestion

This is a refactoring opportunity that comes from https://github.com/typescript-eslint/typescript-eslint/pull/8216#discussion_r1471883984.

In short, it may be a common pattern to want to check for either code that looks like 
```
object.filter
```
or
```
const computedMember = "filter";
object[computedMember];
```
This could be extracted to a utility with approximate usage
```
declare const memberExpression: MemberExpressionComputedName | MemberExpressionNonComputedName,
const isFilterCall = isStaticMemberAccessOfValue(memberExpression, "filter");
```
An example implementation of this is https://github.com/typescript-eslint/typescript-eslint/pull/8216/commits/581e9ae553af227a1a9448d30c2b59d1089dedec#diff-5af06c156c2d34d6ea1d2b8f91d583d82d7e629cbd5226145c6c0b72449bcfb2R298, implemented in a way that did not aim to be more generic than the needs of that specific module. This might be possible to replace with a more general utility

**Comment by JoshuaKGoldberg** [comment]
Whew, what a list! +1 to this from me 🙂 thanks for filing + looking!

**Comment by kirkwaiblinger** [comment]
I believe these guys could similarly be replaced with a utility, as well as probably a few more places in that file

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages%2Feslint-plugin%2Fsrc%2Frules%2Fno-floating-promises.ts#L424-L446

**Comment by JoshuaKGoldberg** [comment]
So it doesn't get lost: #8412 has another one for `class-literal-property-style`. Would be nice to re-use in that rule too.

**Comment by auvred** [comment]
Noticed this while working on https://github.com/typescript-eslint/typescript-eslint/pull/8952:

`unbound-method` rule also needs more thorough handling of static member access: [playground](https://typescript-eslint.io/play/#ts=5.4.3&fileType=.ts&code=MYGwhgzhAEBiD29oG8BQ1oFcB2AjeOAJtALzQBmOwALgJbzYAUAlCgL6oerAMTXRhS0bAFMA7nEQsAdDnxFuvfriGiJCeCwDaAcjkFshHQF1oAejPQIACwIhiuEdABOIgA7xn1EcWqIAhEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6WJgIwHsOATWgFtE%2BABbc%2B6KImjRu0SODABfEMqA&tsconfig=&tokens=false)
