### ISSUE TITLE
Repo: Add a util for determining whether a node is a specific identifier

### ISSUE THREAD

**Issue by StyleShit** [typescript-eslint/typescript-eslint#8327]
### Suggestion

Splits from https://github.com/typescript-eslint/typescript-eslint/pull/8295#discussion_r1465225174

The proposal is to go over all of the places where we check if a node is a specific identifier and use a util for that. Here are a couple of examples of places we do this:

https://github.com/typescript-eslint/typescript-eslint/blob/82cb9dd580f62644ed988fd2bf27f519177a60bd/packages/eslint-plugin/src/rules/array-type.ts#L31-L34

https://github.com/typescript-eslint/typescript-eslint/blob/a54a60b5d00eb34f2b4053e785041c6ecaa46863/packages/eslint-plugin/src/rules/consistent-type-assertions.ts#L102-L105

https://github.com/typescript-eslint/typescript-eslint/blob/e77616b7c2fda1b5f74f91e74e7eb87427f59eca/packages/eslint-plugin/src/rules/no-explicit-any.ts#L110-L114

I think we can take inspiration from this existing function and extract it to a util:

https://github.com/typescript-eslint/typescript-eslint/blob/a54a60b5d00eb34f2b4053e785041c6ecaa46863/packages/eslint-plugin/src/rules/no-inferrable-types.ts#L73-L80

It might be a nice `good first issue` PR 😄

**Comment by bradzacher** [comment]
Personally - I don't think there's much value in extracting two logical expressions into a utility function.

Eg
```ts
if (
  node.typeName.type === AST_NODE_TYPES.Identifier &&
  node.typeName.name === 'Array'
) {...}

// vs

if (
  isIdentifierWithName(
    node.typeName,
    'Array',
  )
) {...}
```

I don't think you gain anything in terms of conciseness or readability, and I think such an abstraction costs you more here as there's a function call involved.

So I'm personally a -1 for this.

**Comment by Josh-Cena** [comment]
I'm -0.5, but I think `isIdentifierWithName(node.typeName, ['Array', 'ReadonlyArray'])` does look slightly more semantic than its expanded form. Still have no appetite for small utilities because most contributors aren't going to be aware of them and just write it again anyway.

**Comment by StyleShit** [comment]
I think it's nicer to read, but @Josh-Cena has a good point here. As a (fairly?) new contributor, I'm not aware of some utils. I always try to find the right ones (which is kinda guessing my way between all those files & functions), but it's pretty difficult.
So now I'm not sure that this change will be useful other than having a (subjectively) nicer code in some places...

**Comment by Josh-Cena** [comment]
There doesn't seem to be enough interest in this.
