### ISSUE TITLE
[array-type] propose to recommend array-simple

### ISSUE THREAD

**Issue by ValeryVS** [typescript-eslint/typescript-eslint#833]
Multiline "array" are harder to read than "generic".
"array-simple" is better than "array".

```typescript
export interface MyObject {
  a: {
    some: number;
    long: number;
    long: number;
    long: number;
    long: number;
    long: number;
    long: number;
    long: number;
    oh_it_was_an_array: number;
    look_there_are_two_tiny_braces: number;
    type: number;
  }[]
}
```

Of course, sybtype can be extracted, but this in a different story.

**Comment by bradzacher** [comment]
We're removing `array-type` from the recommended set in v2 because it's too opinionated.
People will be able to configure as they please!
