### ISSUE TITLE
Rules: Deprecate prefer-ts-expect-error in favor of ban-ts-comment

### ISSUE THREAD

**Issue by fregante** [typescript-eslint/typescript-eslint#8333]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

One line of code triggers two different rules:

- https://typescript-eslint.io/rules/prefer-ts-expect-error/
- https://typescript-eslint.io/rules/ban-ts-comment/

So if I must use `@ts-ignore-error` (due to flaky typescript errors) I have to disable two rules. 

Why are there two rules that do the same thing? Given that `prefer-ts-expect-error` already exists, I think it would make sense to drop the specific check from `ban-ts-comment`

### Impacted Configurations

I think one is in `recommended` and the other one is just in `strict`

**Comment by bradzacher** [comment]
I think that this behaviour is still correct. In most code any form of TS comment is a code smell.

So having an error to warn against using `@ts-expect-error` is good practice.

Having an error to warn against `@ts-ignore` is good too - because it doesn't error if it suppresses nothing.

Think of it this way: the rules are saying "hey 100% definitely do not use `@ts-ignore`, prefer `@ts-expect-error` but also you shouldn't use that unless you really mean it".

If you use the "correct" suppression you only need one disable comment to say "yeah I'm doing this on purpose". If you use the "incorrect" one you need two to say "I'm really, really doing this on purpose and I know I'm breaking the rules".

**Comment by fregante** [comment]
No, I mean the rules do exactly the same thing, they both warn on `@ts-ignore-error`.

`@ts-expect-error` is perfectly allowed by both rules

**Comment by bradzacher** [comment]
I see how that `ban-ts-comment` actually includes a special message to suggest using ts-expect-error if you use ts-ignore.

So you are indeed correct - by default `prefer-expect-error` is a subset of `ban-ts-comment`.

We should just remove the former entirely.

Cc @typescript-eslint/triage-team

**Comment by Josh-Cena** [comment]
I had the idea too; I just thought `prefer-expect-error` had a very educative and actionable error message/name.

**Comment by bradzacher** [comment]
Yeah the name is nice but `ban-ts-comment` has he same error message.

**Comment by JoshuaKGoldberg** [comment]
+1 to this: if there's anything `prefer-expect-error` does better around messaging, part of the deprecation should involve moving that over to `ban-ts-comment`.

**Comment by auvred** [comment]
Yep, `ban-ts-comment` basically does the same, with one difference: `prefer-expect-error` provides autofix, while `ban-ts-comment` provides editor suggestion, which I think is nicer!

But while looking through the `ban-ts-comment` code, I noticed one possibly blocking thing: it doesn't report on multiline block comments, while `prefer-expect-error` does:

Assume we have the following code: 
```ts
/**  some text here
   @ts-ignore */
const foo: string = 1
```

`@typescript-eslint/prefer-ts-expect-error` reports ✅ [playground](https://typescript-eslint.io/play/#ts=5.3.2&fileType=.tsx&code=PQKhAJwZwewWwKbgC4IB7PACwQJwQFCTgACyUAtAJYDmAdjPuCMAQMYx1SYBmMMALmjJcVOjXABecAEYgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0Wlv2T0AHqTJ1e0APbR0UCdMjgwAXxDKgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

`@typescript-eslint/ban-ts-comment` doesn't report ❌ [playground](https://typescript-eslint.io/play/#ts=5.3.2&fileType=.tsx&code=PQKhAJwZwewWwKbgC4IB7PACwQJwQFCTgACyUAtAJYDmAdjPuCMAQMYx1SYBmMMALmjJcVOjXABecAEYgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AIwEMnb9layAewC2wxC3RRE0aIOiRwYAL4glQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

I think `ban-ts-comment` should cover this case to completely replace `prefer-ts-expect-error`. 

Filed https://github.com/typescript-eslint/typescript-eslint/issues/8368
