### ISSUE TITLE
What is the diff bw plugin:@typescript-eslint/recommended and plugin:@typescript-eslint/eslint-recommended?

### ISSUE THREAD

**Issue by avalanche1** [typescript-eslint/typescript-eslint#835]
This is a curiosity question

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/src/configs#readme

eslint-recommended is for turning off a few rules on top of the eslint:recommended set that are automatically handled by the compiler.

recommended is a set of recommended rules (primarily from our plugin) that we think you should use (see #729 for what will be released in v2)
