### ISSUE TITLE
Repo: Drop 'T' from internal type parameters

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8365]
### Suggestion

Quite a few of the type parameters around rules use `T`-prefixed names such as `TMessageIds` and `TOptions`:

https://github.com/typescript-eslint/typescript-eslint/blob/16eba349cfa8e7bc90fdaa504feb9c5764bfa529/packages/utils/src/ts-eslint/Rule.ts#L176-L179

We don't generally use prefixes like `I`(nterface) or `T`(ype) anymore. Is there any reason to keep them around?

`TMessageIds` & co. are at least 5 years old (#425).

**Comment by Josh-Cena** [comment]
I don't think there are good reasons to keep them.
