### ISSUE TITLE
Docs: deprecated stylistic rules redirects to 404

### ISSUE THREAD

**Issue by Namchee** [typescript-eslint/typescript-eslint#8387]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

All links to [eslint-stylistic](https://eslint.style/) website are prefixed by extra `/ts` which causes it to navigate to 404. It will navigate correctly once we removed the prefix `/ts`. This can be fixed by modifying the `insertFormattingNotice` plugin.

### Affected URL(s)

- [`block-spacing`](https://typescript-eslint.io/rules/block-spacing/)
- [`brace-style`](https://typescript-eslint.io/rules/brace-style/)
- [`comma-dangle`](https://typescript-eslint.io/rules/comma-dangle/)
- [`comma-spacing`](https://typescript-eslint.io/rules/comma-dangle/)
- [`func-call-spacing`](https://typescript-eslint.io/rules/func-call-spacing)
- [`indent`](https://typescript-eslint.io/rules/indent)
- [`key-spacing`](https://typescript-eslint.io/rules/key-spacing)
- [`keyword-spacing`](https://typescript-eslint.io/rules/keyword-spacing)
- [`lines-around-comment`](https://typescript-eslint.io/rules/lines-around-comment)
- [`lines-between-class-members`](https://typescript-eslint.io/rules/lines-between-class-members)
- [`member-delimiter-style`](https://typescript-eslint.io/rules/member-delimiter-style)
- [`no-extra-parens`](https://typescript-eslint.io/rules/no-extra-parens)
- [`no-extra-semi`](https://typescript-eslint.io/rules/no-extra-semi)
- [`object-curly-spacing`](https://typescript-eslint.io/rules/object-curly-spacing)
- [`padding-line-between-statements`](https://typescript-eslint.io/rules/padding-line-between-statements)
- [`quote-props`](https://typescript-eslint.io/rules/quote-props)
- [`quotes`](https://typescript-eslint.io/rules/quotes)
- [`semi`](https://typescript-eslint.io/rules/semi)
- [`space-before-blocks`](https://typescript-eslint.io/rules/space-before-blocks)
- [`space-before-function-paren`](https://typescript-eslint.io/rules/space-before-function-paren)
- [`space-infix-ops`](https://typescript-eslint.io/rules/space-infix-ops)
- [`type-annotation-spacing`](https://typescript-eslint.io/rules/type-annotation-spacing)

**Comment by JoshuaKGoldberg** [comment]
Ah, thanks for the deep dive!

Sounds like you're about ready to send a PR for the fix? 😄
