### ISSUE TITLE
Bug: [no-unnecessary-type-assertion] problem with asserting querySelector result

### ISSUE THREAD

**Issue by HolgerJeromin** [typescript-eslint/typescript-eslint#8388]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=MYewdgzgLgBAZiEMC8MAmJgFcC2BTMKAOgCMQ0BPIgRyzwCcKBlPAGz2ChHoAoBYAFAwYAcgDEOCmzz5CMAHzoAlgDcRAGkEBKGAEMIMABIAVALIAZAKLtZsAD4wwWVqwDcgpXBg8EILYOFfImgKdiI0JQgAB1ZdChRREXcBQVBIWBJdegSMbFtScipaBmZpTm5%2BIVEJKRsCWEUItU0BLWTPb0z6fyqu4KhQvHDImLiEkSTBVPBoGEyALxzMXHqCyho6RhZ2cvoAHhMLaxl6%2BUrhcUlpWwVlZu12rx4FnuEF-sHh6Nj41AnkoA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUkACAXAngA4oDG0AlobgLQrzkB2uA9AwPbWwMOIkrIBDaPmoFi1AcmSJoucmwbooM6G2iQQ4MAF8Q2oA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
const foo = document.body.querySelector(
  '#myelement > div',
) as HTMLElement | null;  // This assertion is unnecessary since it does not change the type of the expression.

if (foo)
  foo.style.display = '';

const bar = document.body.querySelector(
  '#myelement > div',
);
if (bar)
  bar.style.display = ''; // failes because Element has no `style`

const baz = document.body.querySelector<HTMLElement>(
  '#myelement > div',
);
if (baz)
  baz.style.display = '';
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unnecessary-type-assertion": "error"
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

First example should not complain because the assertion changes the type.

### Actual Result

There is an error "This assertion is unnecessary since it does not change the type of the expression." at the first example.

**Comment by Josh-Cena** [comment]
Please see https://github.com/typescript-eslint/typescript-eslint/issues/7207, https://github.com/typescript-eslint/typescript-eslint/issues/518, and possibly others. A generic parameter that's only used in the return type can still be inferred, so you should simply use `querySelector<YourElement>()` instead.
