### ISSUE TITLE
Docs: Mention new typescript-eslint package more prominently in /packages page

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8403]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Following #8296: https://typescript-eslint.io/packages is just a list of packages at the moment. But now that `typescript-eslint` is the main driving package, it'd be good to explicitly emphasize that on the page, I think. Or at the very least mention the package there.

### Affected URL(s)

https://typescript-eslint.io/packages

**Comment by bradzacher** [comment]
It has been mentioned in the new docs `/packages` page - they just haven't shipped to the prod website yet!

**Comment by JoshuaKGoldberg** [comment]
D'oh, I swear I thought I was looking at the right one.

Renamed to retarget the issue on emphasizing the package a bit more.
