### ISSUE TITLE
eslint-disable-line doesn't work in JSX

### ISSUE THREAD

**Issue by hibikine** [typescript-eslint/typescript-eslint#841]
**What code were you trying to parse?**

### .eslintrc
```json
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": { "sourceType": "module" },
  "plugins": ["react"],
  "rules": {
    "react/no-array-index-key": 2
  }
}
```

### index.tsx
```tsx
import * as React from 'react';

export default () =>
  [1, 2, 3].map((v, i) => (
    <p
      key={i} // eslint-disable-line react/no-array-index-key
    >
      {v}
    </p>
  ));
```

The sample project is https://github.com/hibikine/typescript-test .

**What did you expect to happen?**
No error.

**What actually happened?**
`react/no-array-index-key` error happen.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `1.13.0` (`1.10.3-alpha.9` and above confirmed) |
| `TypeScript`                | `3.5.3` |
| `ESLint`                    | `5.16.0` |
| `node`                      | `10.16.0` |
| `npm`                       | `6.9.0` |

**Comment by bradzacher** [comment]
Known issue, will be fixed by #703

**Comment by hibikine** [comment]
OK, Thanks @bradzacher!

**Comment by bradzacher** [comment]
#703 has been merged into master. Closing this (I put the wrong issue num into the Fixes comment >.<)
