### ISSUE TITLE
Bug: Parsing variable declaration in method body raises `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by marcoroth** [typescript-eslint/typescript-eslint#8415]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

scope-manager via parser

### Playground Link

\-

### Repro Code

```javascript
// src/typescript-eslint-error.mjs

import { parse } from "@typescript-eslint/parser"

const code = `
  class c {
    b() {
      const a = 0
    }
  }
`

parse(code)
```

### ESLint Config

```javascript
Not using ESLint
```

### tsconfig

```jsonc
Not using TypeScript
```

### Expected Result

I expect that the `parse` function returns the parser result without throwing any errors.

### Actual Result

Running `node src/typescript-eslint-error.mjs` results in:

```
/Users/marcoroth/Development/stimulus-parser/node_modules/@typescript-eslint/scope-manager/dist/scope/FunctionScope.js:27
        const bodyStart = this.block.body?.range[0] ?? -1;
                                                ^

TypeError: Cannot read properties of undefined (reading '0')
    at FunctionScope.isValidResolution (/Users/marcoroth/Development/stimulus-parser/node_modules/@typescript-eslint/scope-manager/dist/scope/FunctionScope.js:27:49)
    at resolve (/Users/marcoroth/Development/stimulus-parser/node_modules/@typescript-eslint/scope-manager/dist/scope/ScopeBase.js:182:27)
    at /Users/marcoroth/Development/stimulus-parser/node_modules/@typescript-eslint/scope-manager/dist/scope/ScopeBase.js:195:18
    at /Users/marcoroth/Development/stimulus-parser/node_modules/@typescript-eslint/scope-manager/dist/scope/ScopeBase.js:279:43
    at Array.forEach (<anonymous>)
    at FunctionScope.close (/Users/marcoroth/Development/stimulus-parser/node_modules/@typescript-eslint/scope-manager/dist/scope/ScopeBase.js:279:28)
    at Referencer.close (/Users/marcoroth/Development/stimulus-parser/node_modules/@typescript-eslint/scope-manager/dist/referencer/Referencer.js:51:66)
    at ClassVisitor.visitMethodFunction (/Users/marcoroth/Development/stimulus-parser/node_modules/@typescript-eslint/scope-manager/dist/referencer/ClassVisitor.js:169:69)
    at ClassVisitor.visitMethod (/Users/marcoroth/Development/stimulus-parser/node_modules/@typescript-eslint/scope-manager/dist/referencer/ClassVisitor.js:193:18)
    at ClassVisitor.MethodDefinition (/Users/marcoroth/Development/stimulus-parser/node_modules/@typescript-eslint/scope-manager/dist/referencer/ClassVisitor.js:254:14)
```

### Additional Info

This patch fixes the issue locally for me:
```diff
diff --git a/packages/scope-manager/src/scope/FunctionScope.ts b/packages/scope-manager/src/scope/FunctionScope.ts
index 8e8b405cd..1bc234825 100644
--- a/packages/scope-manager/src/scope/FunctionScope.ts
+++ b/packages/scope-manager/src/scope/FunctionScope.ts
@@ -51,7 +51,7 @@ class FunctionScope extends ScopeBase<
       return true;
     }

-    const bodyStart = this.block.body?.range[0] ?? -1;
+    const bodyStart = this.block.body?.range?.[0] ?? -1;

     // It's invalid resolution in the following case:
     return !(
```

I tried to write a test in the `scope-manager` package, but it seems to parse it just fine. Not sure what I'm missing.

```ts
  it('should be able to resolve variable in class method body.', () => {
    const { scopeManager } = parseAndAnalyze(`
      class c {
        b() {
          const a = 0
        }
      }
    `);

    expect(scopeManager.scopes).toHaveLength(3); 

    const scope = scopeManager.scopes[2];
    const variables = getRealVariables(scope.variables);
  
    // ...
  })
```

Thank you for your help and for maintaining the project!

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/parser`            | `6.21.0` |
| `@typescript-eslint/scope-manager`     | `6.21.0` |
| `@typescript-eslint/typescript-estree` | `6.21.0` |
| `node`                                 | `20.11.0` |

**Comment by bradzacher** [comment]
`parser` is not intended to be consumed by users - it's intended for use *as an eslint parser*.
This means that if you do choose to use it - you need to call it [like ESLint calls it](https://github.com/eslint/eslint/blob/60b966b6861da11617ddc15487bd7a51c584c596/lib/linter/linter.js#L828-L841):
```ts
parse(code, {
  loc: true,
  range: true,
  tokens: true,
  comment: true,
});
```

Note that if you just want the AST - use our `typescript-estree` package instead (`parser` is just a wrapper on top of that package).
