### ISSUE TITLE
Enhancement: Add an exported utility to remove type info from parserOptions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8428]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

parser / typescript-estree

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

From @bradzacher's https://github.com/typescript-eslint/typescript-eslint/issues/8424#issuecomment-1937117103: 

> Oh @JoshuaKGoldberg we can fix that! https://github.com/import-js/eslint-plugin-import/blob/7a21f7e10f18c04473faadca94928af6b8e28009/utils%2Fparse.js#L80-L85
> 
> I'd forgotten that I'd added this to their setup. We just need to add more deletes. Perhaps we should add a util function to our project so we can control this without touching their code??

~Let's do it!~ Or, actually: `eslint-plugin-import` does not have a production dependency on any of our packages. And it features a long tail of backwards compatibility for Node.js versions that we don't support. My suspicion (cc @ljharb) is that even if we create & export this utility, `eslint-plugin-import` might not be able to use it directly.

~Filing an issue over there...~ https://github.com/import-js/eslint-plugin-import/issues/2962 -> https://github.com/import-js/eslint-plugin-import/pull/2963/files#r1485342911

**Comment by bradzacher** [comment]
Theres an implicit dep because it loads the users configured parser via the config that eslint provides. So could technically export a function and have it called conditionally - agree though that it is not hugely acceptable to do this - kinda funky.

**Comment by ljharb** [comment]
We can conditionally require it, though, and use it when available, so that would be fine.

It wouldn’t work for PnP users, but that model breaks the import plugin anyways.

**Comment by fpapado** [comment]
This issue seems to resurface now that `@typescript-eslint` rc-v8 is using a `projectService` option (i.e. a new key that has to be deleted). I filed https://github.com/typescript-eslint/typescript-eslint/issues/9223 for it, and I'd be happy to contribute a PR, either for the specific issue, or this more general utility 😌
