### ISSUE TITLE
Enhancement: [no-floating-promises] Don't check coincidentally Promise-like (Thenable) type values by default

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8433]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-floating-promises

### Description

Forwarding out from conversations with @mcollina, especially https://github.com/nodejs/node/issues/51292#issuecomment-1937792288: right now `no-floating-promises` will consider anything that _looks_ like a Promise (i.e. is "Promise-like") to be a potential floating value:

https://github.com/typescript-eslint/typescript-eslint/blob/5857356962060b19aa792bee778f9167ee54154b/packages/eslint-plugin/src/rules/no-floating-promises.ts#L353

But to my knowledge this hasn't been particularly helpful. If something _coincidentally happens_ to match the [`Thenable` interface](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#thenables) that doesn't necessarily mean it shouldn't float!

The historical context here is that it used to be common in JavaScript code to use alternative implementations of Promises, such as [Bluebird](https://github.com/petkaantonov/bluebird). Promises were only added to some browsers in ~2014 and Node & co in ~2015 or so. Many sites still had to support old versions of Internet Explorer. The `no-floating-promises` typescript-eslint rule was implemented in 2019 when it was still not-unheard-of to use alternative Promises or at least have Promise types provided by a polyfill: https://github.com/typescript-eslint/typescript-eslint/pull/495.

Now that the vast majority of projects are using built-in Promise values & types, I think the value of detecting those values automatically is no longer worth the pain of flagging general thenables. I propose we modify the rule to:

* _(non-breaking)_ Add in an option to specify types to be considered Promises - using the same standard format as #7008
* _(breaking, as a followup issue & PR for v8)_ Change the rule to no longer detect Thenables, and instead only look for the built-in `Promise` type
    * Nuance: should users be able to _remove_ the built-in `Promise` type from the list of checked types? I don't think so, but that's not a decision we'd need to make now...

I.e. this is the opposite of #7008. That issue is about adding an allowlist for types to be allowed to float. This one is adding a blocklist of types to _not_ be allowed to float - instead of always detecting Thenables.

### Fail

```TypeScript
declare function createPending(): PromiseLike<void>;

createPending();
```

### Pass

```TypeScript
declare function createPending(): Promise<void>;

createPending();
```

### Additional Info

After the proposed followup, if folks still want to detect floating `PromiseLike`s, they'd be able to use this option.

As to whether we'd want to give users a way to opt back into the current _"check anything that looks like a Thenable"_ behavior... I don't see why anybody would want that, but we could always make it an option if someone asks for it.

**Comment by JoshuaKGoldberg** [comment]
@Josh-Cena moving our comments from #9263 back over here for issue discussion:

> _@Josh-Cena:_
> I don't get the motivation for this, TBH. How can something "happen to be thenable" without noticing? Does `then` have any other meaning other than interoperating with promises? JavaScript itself resolves thenables, so if your thenable is not supposed to quack like a promise you will shoot yourself in the foot everywhere, like returning it from an async function, etc.

> _@JoshuaKGoldberg:_
> > How can something "happen to be thenable" without noticing?
> > https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e40cab53d9971a3e0b34e8fb18ece74240d9425d/types/bluebird/index.d.ts#L59: older projects that have polyfills which generally intentionally match something like Promises/A+.

> _@Josh-Cena:_
> The issue mentions `node:test`, but doesn't `test()` return a real promise?

> _@Josh-Cena:_
> the Node issue does, but our #8433 -> this PR isn't around that I don't think.

> _@Josh-Cena:_
> That issue doesn't mention a valid use case where you want a thenable to not be checked like a promise though. It just mentions polyfills but those are _why_ we check thenables.

Ah, I think I see what you're asking for - any reason why we would want to _not_ check a thenable at all? That's a good question.

I'd come into this assuming it was a generally-desirable feature, but now I'm questioning that. Maybe now that we have the [`allowForKnownSafePromises` option](https://typescript-eslint.io/rules/no-floating-promises/#allowforknownsafepromises) from #9186 we don't need this anymore?

Putting this issue into `evaluating community engagement`. If anybody can provide a real use case for not checking Thenables by default, please do - that would help us to justify adding #9263's `checkThenables` option. ❤️ 

Thanks for pressing @Josh-Cena!

**Comment by mcollina** [comment]
The reason for not checking `Thenable` by default is that anything with a `.then(res, rej)` method could be awaited correctly. However, the spec is quite lax on purpose to allow for `Thenable` that are _not_ Promise/A+ compatible.

If an object isn't a promise or promise-like, but it just has a `.then()` method, then it's already totally custom and __not__ a `Promise`. Why `Promise` rule should apply?

**Comment by Josh-Cena** [comment]
I'm not sure I understand the comment as the two paragraph say opposite things.

- The first part says anything with `then` can be awaited—that's true. This means you fully expect `then` to be used in the promise resolution process.
- The second part says it's "totally custom and not a `Promise`". Then why do you expect it to be awaitable?

Put another way, either you have something that quacks like a promise and it's a bug to not await it, or it's not supposed to be a promise and it's a bug that `await` is not an identity operation on it.

The only valid use case I can think of is if you treat `then` like an operator overload hook for custom `await` behavior, but I have yet to see that being done.

**Comment by mcollina** [comment]
We use it in Fastify quite extensively. In fact, we cannot write correct types for Fastify because of typescript-eslint. Your users would start plastering all their code of unneeded `await` and fill our issue tracker with question regarding this.

We have to resort to tricks like this:

https://github.com/fastify/fastify/blob/dda569960ef2d0961a887ead0e63f4e8671a920e/types/instance.d.ts#L173

instead of typing a .then() method into FastifyInstance.

**Comment by JoshuaKGoldberg** [comment]
@mcollina what would be useful for us here and in https://github.com/fastify/fastify/pull/5506#discussion_r1631225510 would be: _why_ does the `FastifyInstance` interface have a `.then()`? Can you share more on the design decision there?

For example, is it intentional that someone would `await` a value of type `FastifyInstance`? If so, why? If not, why the `.then()`?

_(to be clear: not imparting judgement on the code, just trying to understand the context)_

**Comment by mcollina** [comment]
Fastify has a rich plugin system, and all plugins load asynchronously.

We support an API like:

```js
const app = fastify()
await app
  .register(myPlugin1)
  .register(myPlugin2)
  .register(myPlugin3)
```

This is also supported:

```js
const app = fastify()
app.register(myPlugin1)
app.register(myPlugin2)
await app.register(myPlugin3)
```

Adding the `await` will call `.then()`, which will, in turn, start the plugins' loading.

Note that awaiting the instance is entirely optional:

```js
const app = fastify()
app.register(myPlugin1)
app.register(myPlugin2)
app.register(myPlugin3)
await app.listen({ port: 3000 })
```

There are also other methods on the app:

```js
const app = fastify()
app.get('/', ...).post('/', ...)

await app.listen({ port: 3000 })
```

The `FastifyInstance` type does __not__ have a `.then()` method because of the lack of this rule (and not being enabled by default).
According to `no-floating-promises`, if we added a `.then()` function, we would need to:

```js
const app = fastify()
await app.get('/', ...) // or void app.get('/', ...)
await app.post('/', ...)

await app.listen({ port: 3000 })
```

This would work, but it adds unnecessary overhead and worsens the framework's DX.

Note that our `Reply` object has a `then()` method that will resolve when `reply.send()` is called. This allow us to support:

```ts
const app = fastify()

app.get('/simple', async function (req, reply) {
  return { hello: 'world' }
})

app.get('/complex', async function (req, reply) {
  // calling `.then()` here is incorrect, as it will wait for the response to be sent
  // however no-floating-promises forces the user to add a `void`
  void reply.header('x-foo', 'bar')
  setImmediate(() => {
    // Note that this break the promise chain
    reply.send('something')
  })
  return reply // this will can reply.then()
})

app.get('/empty', async function (req, reply) {
  // this will return an empty response
})
```

**Comment by Josh-Cena** [comment]
I see. So you have a chaining API where each chained operation can be optionally awaited, but usually they are not necessary. Yes it would be tricky to design such checks. Won't the `allowKnownSafePromises` option fix this case though?

**Comment by mcollina** [comment]
> Won't the allowKnownSafePromises option fix this case though?

This would need to be enabled by the end users, and I would rather prefer if this wasn't needed at all. None of these are promises after all, and adding custom configs in every project is annoying.

**Comment by Josh-Cena** [comment]
Sure, I see the reasoning there. I think only checking native promises would be the least surprising behavior. `promise-function-async` has an option called `allowedPromiseNames` and maybe we can implement that instead of `allowThenables`? Thoughts @JoshuaKGoldberg?

**Comment by JoshuaKGoldberg** [comment]
> only checking native promises would be the least surprising behavior

Agreed, which is what I see this issue as trying to approach. I'm also wondering if instead of an _"all or nothing"_ boolean option value, we should turn `checkThenables` into an enum over:

* `'always'`: any value of a type with a `.then()`
* `'strict'`: any value of a type with a `.then(resolve, reject)` per the Promises/A+ spec
* `'never'`: never check on structural typing

...where maybe the `recommended-type-checked` config has it set to `'strict'`, and `strict-type-checked` config has it set to `'always'`?

We're going to have to think on this a bit. Context: as with `node:test` (https://github.com/nodejs/node/issues/51292) and RTK (https://github.com/reduxjs/redux-toolkit/issues/4101), the way these frameworks are exposing Promises is counterintuitive to how I've understood their accepted userland semantics. These are roughly the only three cases I think we've seen in the wild of frameworks intentionally using Thenable-returning functions for something other than _"call me to start some work that needs to be `await`ed"_. Part of the question for us is, how do we balance the needs of these not-typical-idioms vs. giving the intended effects for typical-idioms code?

> `promise-function-async` has an option called `allowedPromiseNames` and maybe we can implement that instead of `allowThenables`?

That's what [`allowForKnownSafePromises`](https://typescript-eslint.io/rules/no-floating-promises/#allowforknownsafepromises) is, no?

**Comment by mcollina** [comment]
Note that `.then(resolve, reject)` would not fix us (https://github.com/typescript-eslint/typescript-eslint/issues/8433#issuecomment-2156412327). In other words, `.then(resolve, reject)` cannot guarantee Promise/A+ spec. You'll likely have to use a different type for those edge cases.

**Comment by Josh-Cena** [comment]
Yeah, I don't think `"always"` / `"strict"` makes sense. Fastify is not "accidentally-thenable", it's very much on purpose. No one is going to implement `then` "by accident" and not expect it to work with `await`.

**Comment by JoshuaKGoldberg** [comment]
Ok so coming back to this: what is the consensus here? I'm:
* Still in favor of making checking thenables an opt-in a la #9263
* No longer suggesting we make it more granular than an always/never boolean

**Comment by JoshuaKGoldberg** [comment]
Also confirmed with @Josh-Cena 1:1 that we're good to continue. Great! 🚀
