### ISSUE TITLE
Enhancement: reexport plugin, parser, etc, through typescript-eslint submodules for legacy eslintrc use

### ISSUE THREAD

**Issue by jakebailey** [typescript-eslint/typescript-eslint#8445]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-eslint

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I really love the new `typescript-eslint` package, but, I'm not to the point of using flat config yet. So, I need to install the smaller packages, then do (per the website):

```js
module.exports = {
  extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended'],
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint'],
  root: true,
};
```

Given `typescript-eslint` pulls in all of the other packages, I think it might be cool to be able to just install the one package and have it reexport all of the others. Then, using it is:

```js
module.exports = {
  extends: ['eslint:recommended', 'plugin:typescript-eslint/recommended'],
  parser: 'typescript-eslint/parser',
  plugins: ['typescript-eslint'],
  root: true,
};
```

Similarly, in custom rules, one could write:

```js
const { AST_NODE_TYPES, ESLintUtils } = require("typescript-eslint/utils");
```

That being said, this may not be a good idea, because:

- I think that `plugins: ['typescript-eslint']` will make rule names change?
- `typescript-eslint` only depends on the plugind the parser, not the other packages.
- I honestly do not know the semantics of the string-based eslint configs. Really, that's a good reason to just use flat config; much more obvious.

Filing this after being suggested it in https://twitter.com/andhaveaniceday/status/1757192446520484014, but I'm not 100% sure after fleshing the idea out.

**Comment by JoshuaKGoldberg** [comment]
> I think that `plugins: ['typescript-eslint']` will make rule names change?

Yeah 😬 this old thing. There's no way for plugins to declare a canonical name.

Since it's been about half a year and no action, closing this issue out as not something to deeply investigate. Thanks for filing though!
