### ISSUE TITLE
[indent] Broken selectors docs link

### ISSUE THREAD

**Issue by burtek** [typescript-eslint/typescript-eslint#845]
In https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/indent.md, description of config option `ignoredNodes` has a link to documentation about selectors. The link doesn't work.

**Comment by bradzacher** [comment]
The documentation was copy pasted from eslint's base documentation when the rule was implemented.
We don't do that any more for this exact reason.

Happy to accept a PR to fix it!
