### ISSUE TITLE
Docs: getting started guide doesn't explain how to work for CJS

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#8455]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

the steps don't work because node defaults to CJS

### Affected URL(s)

<https://typescript-eslint.io/getting-started>

**Comment by bradzacher** [comment]
Personally I think we should trust that our users can understand that they should translate to CJS if their project is CJS.

We could explicitly state it if we think it needs clarification. The flat config docs do make the clarification at the start but after that all code samples are ESM. 

https://eslint.org/docs/latest/use/configure/configuration-files-new#configuration-file

**Comment by Zamiell** [comment]
I think we should add the line:

> The following guide assumes that your project is using ESM. In other words, it expects that you have a line of `"type": "module"` inside of your project's "package.json" file. If you are using the legacy CommonJS format (i.e. you have either a `"type": "commonjs"` or the "type" line omitted altogether), then you will need to convert the export lines accordingly. (Google for the differences in export statements between ESM and CJS.)

**Comment by JoshuaKGoldberg** [comment]
> passage

Good word - I think we could add something in... but ideally not quite so many sentences. If there's a first-party eslint.org doc I'd think it best to link to that one.
