### ISSUE TITLE
Docs: [no-unnecessary-type-assertion] incorrect examples don't report errors

### ISSUE THREAD

**Issue by teppeis** [typescript-eslint/typescript-eslint#8458]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

[Some incorrect examples](https://typescript-eslint.io/rules/no-unnecessary-type-assertion/#examples) for `no-unnecessary-type-assertion` don't report expected errors.

1. [reports an expected error](https://typescript-eslint.io/play#eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0UOdA7RI4MAF8QOoA&code=MYewdgzgLgBAZiEMC8MDMBuAUKSsBGAhgE4ryICEGQA)
2. [doesn't report errors!](https://typescript-eslint.io/play#eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0UOdA7RI4MAF8QOoA&code=MYewdgzgLgBAZiEMC8MA8BmAfBg3EA)
3. [doesn't report errors!](https://typescript-eslint.io/play#eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0UOdA7RI4MAF8QOoA&code=C4TwDgpgBAYg9nKBeKBmA3AKAMZwHYDOwUAZgslADzxwB8GQA)
4. [doesn't report errors!](https://typescript-eslint.io/play#eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0UOdA7RI4MAF8QOoA&code=C4TwDgpgBAYg9nKBeKBmA3AKAMZwHYDOwUAZgsmlAIYGwLpA)
5. [reports an expected error](https://typescript-eslint.io/play#eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0UOdA7RI4MAF8QOoA&code=GYVwdgxgLglg9mABMOcAUAPAXIsIC2ARgKYBOAlDnkWYgN4BQiipxUIpSGAhANyIB6AYnBhiEYgGdJAQ1IBPXAgC0eADZqGAXyA)

Should they report errors as expected?

### Affected URL(s)

https://typescript-eslint.io/rules/no-unnecessary-type-assertion/#examples

**Comment by auvred** [comment]
Interestingly, these "invalid" examples are literally present in the `valid` test cases.

https://github.com/typescript-eslint/typescript-eslint/blob/2b98ccd8672069af533002bc10978894b00eb4bc/packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts#L28-L31

Look like we should update the examples!

_+1 on https://github.com/typescript-eslint/typescript-eslint/issues/8382_

**Comment by teppeis** [comment]
That difference between testing and documentation seems to have existed since the first implementation (https://github.com/typescript-eslint/typescript-eslint/commit/38abc282ec03b907ae0eac9fae962cf262c9f885) five years ago.

I think this rule should report errors for the incorrect examples like `const foo = <3>3`, as documented.　
Because these "type assertions that do not change the type of an expression".
