### ISSUE TITLE
Docs: getting started guide causes type errors in eslint.config.js

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#8459]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

steps to reproduce:
```
mkdir test
cd test
npm init --yes
npm install --save-dev eslint typescript typescript-eslint
vim eslint.config.mjs
```
(paste in the code directly from the getting started guide)
```
code .
```
(open eslint.config.mjs inside vscode)
(observe the red squiggly)

Perhaps something is wrong with the published typescript definitions?

### Affected URL(s)

https://typescript-eslint.io/getting-started/

**Comment by JoshuaKGoldberg** [comment]
Tip @Zamiell: it's good to be precise in issue titles. _"does not work"_ is pretty vague and hard to search for. The guide _mostly_ works; it's just that it introduces type errors for users who check for that.
