### ISSUE TITLE
Enhancement: export flat rules from new typescript-eslint package

### ISSUE THREAD

**Issue by Techn1x** [typescript-eslint/typescript-eslint#8465]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-eslint

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Thanks for adding support for flat configs!

I've set my project up to pull in from the new `typescript-eslint` package, which seems to export `parser`, `plugin`, `configs` etc.

However, if one wants to apply the tseslint rules to filetypes other than what the "configs" suggest, they become less useful. I would like the flat rules objects exported too, so that I can apply them to varying filetypes (like `*.gts`)

I'd like to be able to do something like this;
```ts
import tseslint from 'typescript-eslint'
...
export default [
  {
    files: ['**/*.xts'], // or whatever filetype I want to apply tseslint to
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },
    languageOptions: {
      parser: tseslint.parser,
      globals: {
        ...globals.browser,
      },
    },
    rules: {
      // the rules export don't currently exist
      ...tseslint.rules.eslintRecommended,
      ...tseslint.rules.recommended, // or perhaps this already contains the eslintRecommended rules
    },
  }
]
```

Currently, what I'm doing to get the rules is reduce the config array to pull the rules out of each
```ts
const typescriptRules = {
  ...tseslint.configs.recommended.reduce((rules, item) => ({ ...rules, ...item.rules }), {}),
}
```

**Comment by bradzacher** [comment]
This is a usecase we purposely built into our tooling already!

https://typescript-eslint.io/packages/typescript-eslint#flat-config-extends

```ts
import tseslint from 'typescript-eslint'
...
export default tseslint.config([
  {
    files: ['**/*.xts'], // or whatever filetype I want to apply tseslint to
    extends: [
      ...tseslint.configs.recommended, 
    ],
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },
    languageOptions: {
      parser: tseslint.parser,
      globals: {
        ...globals.browser,
      },
    },
    rules: {
    },
  }
]);
```

We identified the need for this usecase ourselves and that's why we built

**Comment by Techn1x** [comment]
> it's up to you to compose configs together as you see fit.

That's exactly what I am trying to do, by importing the rules...

> Note that exporting just the rules is bad because you lose any extra config we have in our recommended set

I don't understand why that's bad, if I am handling that myself.

---

I'd be happy to use the tooling instead, but it's not making much sense to me. I have a large flat config array defining eslint for all kinds of filetypes, module vs script, JS/TS/GTS/GJS etc.

Am I supposed to wrap my entire config array in your `tseslint.config()` and export that? The docs seem to indicate it only takes a single config object. And that will handle extends in each config item? Or do I just wrap the individual config items that I want typescript for?

It might just be a case of the readme/docs not being clear enough on more advanced use cases, beyond linting just a single filetype configuration.

Feels a bit weird to have just gotten away from eslint's old config style into the nice new flat system, only to now need to use `extends` again and this whole other approach to config

**Comment by bradzacher** [comment]
> I don't understand why that's bad, if I am handling that myself.

Based on your example code - you aren't handling it though!

For example if we were to add some globals to our recommended config you wouldn't get them in your config because you're only extracting the rules. This would mean that you aren't using our recommended config and may be missing out on important config!

> Am I supposed to wrap my entire config array in tseslint.config() and export that?

You are, yes

> The docs seem to indicate it only takes a single config object.

Sorry there's a fine balance to strike in docs. Too many examples and people can get confused or distracted - so we try and be "short and sweet".

The `config` function is a variadic function. I.e.You can pass `1..n` flat config objects. This is vaguely implied by the spreads in both examples.

---

I think there's a bit of a misunderstanding here of the "correct" way to "extend" a flat config.

You're trying to pull apart our recommended config in order to extract certain parts of it - which isn't a usecase we explicitly want to support for the reason stated above.

Instead the intended use of our configs to apply them to a specific glob would instead be:
```ts
export default [
  ...tseslint.configs.recommended.map(conf => ({
    ...conf,
    files: ["**/*.xts"],
  })), 
  {
    files: ["**/*.xts"],
    //... Your custom config
  },
];
```

Which is [how it's documented in the ESLint docs](https://eslint.org/docs/latest/use/configure/configuration-files-new#using-predefined-configurations).

This is all that the `extends` property our tooling adds does (as shown in the above docs)!

**Comment by Techn1x** [comment]
Thanks for the explanation, I'll give it a go tomorrow. I may just do the manual "map" way you gave instead of the config function, to have less magic involved

**Comment by bradzacher** [comment]
If you use our config function it's easy to type-check your config! There's no need to use `extend` if you don't want. Without extend the function is just the identity function and there to provide types

**Comment by Techn1x** [comment]
Wrapping the whole config array didn't seem to work, just produced errors (regardless if I spread it in as args or not).

I managed to get it to work like below, only wrapping the TS specific items

Thanks for helping me out, hopefully others might find this example useful. I couldn't see the bigger picture of how to get the config function working in a more complex config example

```ts
export default [
  js.configs.recommended,
  /* other config items to do with JS */
  // TS / GTS common items
  ...tseslint.config({
    files: ['**/*.ts', '**/*.gts'],
    /* extends handled by tseslint.config() function. Applies standard rules, parser and plugin. */
    extends: [...tseslint.configs.recommended],
    plugins: {
      ember: eslintPluginEmber,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
      },
    },
    rules: {
      ...emberGTSConfig.rules,
      ...commonEmberRules,
      ...commonTypescriptRules,
    },
  }),
  // GTS uses the ember parser
  {
    files: ['**/*.gts'],
    languageOptions: {
      parser: emberParser, // ember-eslint-parser
    },
  },
  /* config items specific to tests, etc. */
  /* other config items for node script files, eslintignore, etc */
]
```
