### ISSUE TITLE
You have incorrect lint at getting-started page

### ISSUE THREAD

**Issue by art-wix** [typescript-eslint/typescript-eslint#8466]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Change localhost:3000 (which you can see at screenshot at left bottom corner) to /

<img width="898" alt="Screenshot 2024-02-14 at 09 52 22" src="https://github.com/typescript-eslint/typescript-eslint/assets/126492133/36a62bd2-9523-4568-9e72-e76fb9a348be">

### Affected URL(s)

https://typescript-eslint.io/getting-started

**Comment by auvred** [comment]
Thanks for posting, this issue has already been fixed in https://github.com/typescript-eslint/typescript-eslint/pull/8463

**Comment by bradzacher** [comment]
I published the latest commit to the website so the fix is live!
