### ISSUE TITLE
Website: inline `code` tags in links are incorrectly underlined

### ISSUE THREAD

**Issue by auvred** [typescript-eslint/typescript-eslint#8469]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I noticed this in Firefox (https://typescript-eslint.io/maintenance/issues/#-new-rules):

![inline code tags are incorrectly underlined](https://github.com/typescript-eslint/typescript-eslint/assets/61150013/2de51ba8-0231-4eb1-b2f1-824bb6d85024)

https://meta.stackexchange.com/a/362746 suggests adding `vertical-align: baseline` to inline children of `<a>` tag

So what if we add:

```css
.markdown a code {
  vertical-align: baseline;
}
```

---

#### On `main`

![firefox now](https://github.com/typescript-eslint/typescript-eslint/assets/61150013/12f1d152-9de6-4940-9c6f-5bd77caded94)

#### With `vertical-align: baseline`

![firefox with vertical-align baseline](https://github.com/typescript-eslint/typescript-eslint/assets/61150013/2eab0ac3-4f2d-43b8-9b95-7e736a4ddb6f)

#### On `main`

![chrome now](https://github.com/typescript-eslint/typescript-eslint/assets/61150013/a13249bb-69b0-421d-a8dd-1a56b7246167)

#### With `vertical-align: baseline`

![chrome with vertical-align baseline](https://github.com/typescript-eslint/typescript-eslint/assets/61150013/96a7dd55-3af4-4f50-9b2b-5926056eaf49)

### Affected URL(s)

`https://typescript-eslint.io/*`

**Comment by JoshuaKGoldberg** [comment]
I like it 😄 nice find!
