### ISSUE TITLE
Configs: Replace EXPERIMENTAL_useProjectService with useProjectService in v7

### ISSUE THREAD

**Issue by phuctm97** [typescript-eslint/typescript-eslint#8475]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

EXPERIMENTAL_useProjectService has been prefixed with `EXPERIMENTAL_` for the whole v6 and should be considered stable in v7.

It enables project references and more sophisticated typed linting.

**Comment by bradzacher** [comment]
There's still more work to be done on the feature before it can be considered truly ready - a number of edge cases and perf issues are known to us.

Rest assured that it is on our roadmap to be made stable as part of the next major release (v8).

For reference - we just release v7 this week.
https://typescript-eslint.io/blog/announcing-typescript-eslint-v7
