### ISSUE TITLE
Bug: [no-restricted-imports] Rule doesn't distinguish between package names that have a substring as a name

### ISSUE THREAD

**Issue by bengry** [typescript-eslint/typescript-eslint#8503]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.tsx&code=JYWwDg9gTgLgBAbzgM2gdwIZQCYCUCmycGAznNMAObAB2GANgGLpZ6FwC%2BKUEIcA5FHwYAxjH4AoUJFiIULHASKk4ICNmDJg%2BbMyiZF7Lsh59%2BAARABPALTRKAegCuMYPRIOho8RKA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1uhXyrPyIAJrUoBbYh2j5UGANrhsORNGhTIAGkVKsS7JGIBDfIOhNZYBXr27rSyAHM1sYukva79noYGQPngF0tT3txSWkAOUMxFDcrEPsAMykAd0NoIQAlRES-BIgg-ztIGORkQwdEN0gAVWREMA5YaDAiUlpyxIaU6ENiUhbEtTEwAB1IZI5xsGZkQUMhADo8kIBfIoKi9aUAxXXVoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
import { forwardRef as originalForwardRef } from 'react'
import { forwardRef as modifiedForwardRef } from '@my-org/utils/react'
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-restricted-imports": [
      "error",
      {
        "patterns": [
          {
            "group": [
              "react"
            ],
            "importNames": [
              "forwardRef"
            ],
            "message": "Use our type-safe wrapper from \"foo\" instead."
          }
        ]
      }
    ]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

`originalForwardRef` should error, while `modifiedForwardRef` shouldn't.

### Actual Result

Both `imports` error

### Additional Info

I tried changing the rule slightly, but to no avail.

Note that using this:
```json
{
  "name": "react",
  "importNames": ["forwardRef"],
  "message": "..."
}
```
Is not good enough since it now errors on all of these lines:
```tsx
import * as React from 'react';
```
Which, while technically correct (since you can then use `React.forwardRef`) is too much of an overhead, and not what I want to fix here. I'll prevent usage of `React.forwardRef` using another rule (`no-restricted-syntax maybe`).

**Comment by bradzacher** [comment]
[This is just how the base rule works.](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tcmVzdHJpY3RlZC1pbXBvcnRzOiBbXCJlcnJvclwiLCB7XG4gICAgICAgIFwicGF0dGVybnNcIjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIFwiZ3JvdXBcIjogW1xuICAgICAgICAgICAgICBcInJlYWN0XCJcbiAgICAgICAgICAgIF0sXG4gICAgICAgICAgICBcImltcG9ydE5hbWVzXCI6IFtcbiAgICAgICAgICAgICAgXCJmb3J3YXJkUmVmXCJcbiAgICAgICAgICAgIF0sXG4gICAgICAgICAgICBcIm1lc3NhZ2VcIjogXCJVc2Ugb3VyIHR5cGUtc2FmZSB3cmFwcGVyIGZyb20gXFxcImZvb1xcXCIgaW5zdGVhZC5cIlxuICAgICAgICAgIH1cbiAgICAgICAgXVxuICAgICAgfV0qL1xuXG5pbXBvcnQgeyBmb3J3YXJkUmVmIGFzIG9yaWdpbmFsRm9yd2FyZFJlZiB9IGZyb20gJ3JlYWN0J1xuaW1wb3J0IHsgZm9yd2FyZFJlZiBhcyBtb2RpZmllZEZvcndhcmRSZWYgfSBmcm9tICdAbXktb3JnL3V0aWxzL3JlYWN0J1xuIiwib3B0aW9ucyI6eyJlbnYiOnt9LCJydWxlcyI6e30sInBhcnNlck9wdGlvbnMiOnsiZWNtYUZlYXR1cmVzIjp7fSwiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoibW9kdWxlIn19fQ==)
Please file an issue upstream.

**Comment by bengry** [comment]
> [This is just how the base rule works.](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tcmVzdHJpY3RlZC1pbXBvcnRzOiBbXCJlcnJvclwiLCB7XG4gICAgICAgIFwicGF0dGVybnNcIjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIFwiZ3JvdXBcIjogW1xuICAgICAgICAgICAgICBcInJlYWN0XCJcbiAgICAgICAgICAgIF0sXG4gICAgICAgICAgICBcImltcG9ydE5hbWVzXCI6IFtcbiAgICAgICAgICAgICAgXCJmb3J3YXJkUmVmXCJcbiAgICAgICAgICAgIF0sXG4gICAgICAgICAgICBcIm1lc3NhZ2VcIjogXCJVc2Ugb3VyIHR5cGUtc2FmZSB3cmFwcGVyIGZyb20gXFxcImZvb1xcXCIgaW5zdGVhZC5cIlxuICAgICAgICAgIH1cbiAgICAgICAgXVxuICAgICAgfV0qL1xuXG5pbXBvcnQgeyBmb3J3YXJkUmVmIGFzIG9yaWdpbmFsRm9yd2FyZFJlZiB9IGZyb20gJ3JlYWN0J1xuaW1wb3J0IHsgZm9yd2FyZFJlZiBhcyBtb2RpZmllZEZvcndhcmRSZWYgfSBmcm9tICdAbXktb3JnL3V0aWxzL3JlYWN0J1xuIiwib3B0aW9ucyI6eyJlbnYiOnt9LCJydWxlcyI6e30sInBhcnNlck9wdGlvbnMiOnsiZWNtYUZlYXR1cmVzIjp7fSwiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoibW9kdWxlIn19fQ==) Please file an issue upstream.

Thanks, opened upstream: https://github.com/eslint/eslint/issues/18126.

Linking here for future reference.
