### ISSUE TITLE
@typescript-eslint/explicit-function-return-type is reported for JS files

### ISSUE THREAD

**Issue by limonte** [typescript-eslint/typescript-eslint#851]
After upgrading to 2.0.0, I'm getting the `Missing return type on function` warnings:

![image](https://user-images.githubusercontent.com/6059356/62981446-ebc8ef80-be31-11e9-8d04-afba9d5eb965.png)

These warnings are related to TS, but I'm not expecting them for vanilla JS

**Repro**

1. clone https://github.com/sweetalert2/sweetalert2
2. delete https://github.com/sweetalert2/sweetalert2/blob/master/.eslintrc.js#L21
3. run `npm run lint`

**Expected Result**

No warnings

**Actual Result**

Plenty of `@typescript-eslint/explicit-function-return-type` warnings

**Comment by bradzacher** [comment]
This is intentional.
Please read the docs here: https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.0.0

**Comment by ryami333** [comment]
@bradzacher sorry but I can't see any justification for this in the release notes you linked to. Care to shed some light here?

**Comment by bradzacher** [comment]
The justification is that no lint rules should care about file extensions.
Doing so forces all users to use those particular extensions.
This causes problems when frameworks like Vue come along and have users write typescript within files with a different extension (I.e. `.vue`).

Quite a while ago, eslint released a configuration option called `overrides`. This option lets you specify a new config to apply for a specific glob path (I.e. You can disable a spefici rule for all js files).
So there is no need for our rules to care about extensions, when the user can easily customise based on their environment.

**Comment by ryami333** [comment]
Cool thanks for clarifying 👍
