### ISSUE TITLE
Bug: slow formatting even on small files - `existingWatch.getProgram().getProgram()` taking very while (~10seconds)

### ISSUE THREAD

**Issue by taozhou-glean** [typescript-eslint/typescript-eslint#8510]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-estree

### Repro Code

```TypeScript
happens even on empty ts files
```

### ESLint Config

```javascript
not relevant as I can observe slowness with same config
```

### tsconfig

```jsonc
not relevant as I can observe slowness with same config
```

### Expected Result

fast save

### Actual Result

I would expect `existingWatch.getProgram().getProgram()` to be very fast

### Additional Info

this seems to be relevant to some code changes we have locally, can not copy the change, but its a change that moved a few generated ts files to a local pnpm subpackage, and I start observing the slowness after replacing all references to point to the new subpackage, something like:

```
"./lib/a.ts` -> `@local/generated/a.ts`
```

we have quite a lot references updated, a bit more than 1k, wondering if that messed up something somehow

I was able to track the slowness all the way down to

```
// getWatchProgramsForProjects

 if (fileList.has(filePath)) {
            log('Found existing program for file. %s', filePath);
            log(`existing watch ${!!existingWatch}`)
            updatedProgram ??= existingWatch.getProgram().getProgram();
            log('right before returning the program');
            // sets parent pointers in source files
            updatedProgram.getTypeChecker();
            return [updatedProgram];
        }
```

```
2024-02-19T22:48:41.167Z  Found existing program for file. /users/taozhou/workspace/scio/typescript/core/version.ts
2024-02-19T22:48:41.167Z  existing watch true
2024-02-19T22:48:47.304Z right before returning the program
```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/parser`            | `6.21.0` |
| `@typescript-eslint/typescript-estree` | `5.62.0` |
| `TypeScript`                           | `5.3.3` |
| `ESLint`                               | `8.56.0` |
| `node`                                 | `v21.6.1` |

**Comment by bradzacher** [comment]
Have you checked out our docs on these topics?
- https://typescript-eslint.io/linting/typed-linting#how-is-performance
- https://typescript-eslint.io/linting/troubleshooting/performance-troubleshooting

Also separately please read https://antfu.me/posts/why-reproductions-are-required
You've filed an issue with no reproducibility. We cannot fix that what we cannot reproduce.
Please consider creating a reproduction case.

Help us to help you.
