### ISSUE TITLE
Repo: Investigate use of `objectMapKey` in `objectIterators` file

### ISSUE THREAD

**Issue by peanutenthusiast** [typescript-eslint/typescript-eslint#8541]
### Suggestion

**Suggestion**

Per this comment

https://github.com/typescript-eslint/typescript-eslint/pull/8447#discussion_r1492811990

Investigate uses of the above function across the code base. 

A search through visual studio code doesn't reveal any other usages outside of the file itself, so it could be helpful to drop the function.

**Comment by Josh-Cena** [comment]
`objectMapKey` was _never_ used, even in its first creation in #848. However, considering this module also contains `forEach` and `reduce`, I find the existence of a `map` very intuitive.

**Comment by Josh-Cena** [comment]
Closing; I think it's good to have for the reason above, although util functions are generally underused in our repo.
