### ISSUE TITLE
Enhancement: Export type needed to construct tseslint.config arguments in flat config format

### ISSUE THREAD

**Issue by doberkofler** [typescript-eslint/typescript-eslint#8561]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-eslint

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I'm currently testing the migration to the eslint flat config format and am having problems when trying to compose the arguments for the new `config` api of typescript-eslint.
If I'm not wrong the `ConfigWithExtends` type is not exported and therefore it is impossible to type safely define an object that can later be used on `config` as shown in the following example:

```js
// @ts-check

import tseslint from 'typescript-eslint';

/** @type {import('typescript-eslint').ConfigWithExtends} */
/** @type any */
const eslintDefaultConfig = {
	languageOptions: {
		ecmaVersion: 2021,
		sourceType: 'module',
		globals: {
			...globals.es2021,
		}
	},
};

export default tseslint.config(eslintDefaultConfig, ...);
```

**Comment by bradzacher** [comment]
If you update to the latest you'll find you can use `import('typescript-eslint').Config`, which is a strict subset of `ConfigWithExtends`

You're correct though that it doesn't export `ConfigWithExtends` - this is an oversight.

**Comment by doberkofler** [comment]
Using `import('typescript-eslint').Config` works as described in your documentation but unfortunately this does not allow to compose the arguments for the `config` function. Exporting `ConfigWithExtends` would be needed to type the individual objects.
Thank you!
