### ISSUE TITLE
Docs: Add a guide to producing minimum reproductions from complex and/or proprietary code

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8569]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

We get the occasional situation where someone wants to report a bug but can't give us a minimum reproduction on the playground. Two common cases are:

* The code is very complex and doesn't fit easily into one file
* The code is proprietary and can't be shared publicly

...and oftentimes it's both.

My personal strategy when I've been a reporter in these cases is vaguely something like:

1. Create a new repository using the steps in https://typescript-eslint.io/getting-started/
2. Copy just the offending code into a file there
3. Copy anything that code needs (dependencies, other files, etc.) 
4. Repeat until the error is demonstratable

Failing that strategy, my more-reliable-but-more-work backup is:

1. Copy the repository all-up
2. Remove anything that is unrelated until it's as small as possible
3. Rename/rewrite anything proprietary to generalized equivalents

Proposal: let's write a guide to guide folks into how to do this? We can then include it in the issue templates & Discord `#help` channel pinned post.

### Affected URL(s)

Maybe https://typescript-eslint.io/troubleshooting or something within there.

Alternately, maybe a blog post?

**Comment by bradzacher** [comment]
https://antfu.me/posts/why-reproductions-are-required

which links to https://stackoverflow.com/help/minimal-reproducible-example

I like this line from stackoverflow:

> DO NOT use images of code. Copy the actual text from your code editor, paste it into the question, then format it as code.

**Comment by JoshuaKGoldberg** [comment]
Yeah, I've just been using the antfu post. It's fantastic. No need for us to do this I think!
