### ISSUE TITLE
Docs: [no-floating-promises] Include a `.catch().then()` → `.catch().finally()` refactor in docs

### ISSUE THREAD

**Issue by danvk** [typescript-eslint/typescript-eslint#8573]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I fixed a no-floating-promises error by changing:

```
- promise.catch(() => {}).then(() => {})
+ promise.catch(() => {}).finally(() => {})
```

I _think_ this is a good change! Since my `.catch()` handler couldn't reject, it's probably not even a change.

The `.catch().then()` form is [mentioned on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#chaining_after_a_catch) and triggers this rule ([playground]). So it would be helpful if the docs on this rule included an example of the suggested refactor.

[playground]: https://typescript-eslint.io/play#ts=5.3.3&fileType=.tsx&code=GYVwdgxgLglg9mABMOcAUBKRBvAUIxNAQwGcBPSQrAXgD4d8DEZhCBZIqACwDoAnImAAmcALaZEAHkQAGHgFYseJk2584Ad0RgAploCifdX0wBuRgQC%2BjSxkwXEPCJwhc0OxHQYqCEBCTgAGx0eHSM4Ex0McxVbHm4dMDQJL2UfPzAA4J5AuABzNAByIkDAxDgAa0Loh1tzayA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oDN4OBDfMwDmtYtA4BbSshTooiaBOiRwYAL4h1QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Affected URL(s)

https://typescript-eslint.io/rules/no-floating-promises/

**Comment by JoshuaKGoldberg** [comment]
Seems reasonable, thanks for filing!

I'm going to consider this a part of #8088. The messages and docs around this whole area need a good revamp.

If there's anything else you think we should add, please do post it. I'm hoping to get to #8088 this month or so!

**Comment by JoshuaKGoldberg** [comment]
Aside: `duplicate` feels kind of hostile here... `subset` would be a more precise term. This was a good issue to have filed. 🙃

**Comment by Josh-Cena** [comment]
@danvk Since you mentioned MDN: feel free to send an issue and/or PR to MDN if you think an example with `finally` should be mentioned on that page! I rewrote it not long ago but I didn't write with `finally` in mind.
