### ISSUE TITLE
@t-e/eslint-plugin 2.0.1-alpha.1 has an incorrect peer dependency on @t-e/parser

### ISSUE THREAD

**Issue by octogonz** [typescript-eslint/typescript-eslint#858]
When I install `@typescript-eslint/eslint-plugin@canary`, I get version `2.0.1-alpha.1` with this package.json:

```js
{
  "name": "@typescript-eslint/eslint-plugin",
  "version": "2.0.1-alpha.1"
  "dependencies": {
    "@typescript-eslint/experimental-utils": "2.0.1-alpha.1+ca3b6a5",
    "eslint-utils": "^1.4.0",
    "functional-red-black-tree": "^1.0.1",
    "regexpp": "^2.0.1",
    "tsutils": "^3.14.0"
  },
  "devDependencies": {
    "@types/json-schema": "^7.0.3",
    "@types/marked": "^0.6.5",
    "@types/prettier": "^1.18.0",
    "chalk": "^2.4.2",
    "marked": "^0.7.0",
    "prettier": "*",
    "typescript": "*"
  },
  "peerDependencies": {
    "@typescript-eslint/parser": "^2.0.0-alpha.0", // <==== ?
    "eslint": "^5.0.0 || ^6.0.0"
  },
  . . .
}

```
This is essentially the same problem as https://github.com/typescript-eslint/typescript-eslint/issues/827.

The `@typescript-eslint/parser` package depends on a bunch of other `@typescript-eslint` packages, which seemingly should all be the `2.0.1-alpha.1` version.  

However the peer dependency requires `@typescript-eslint/parser` to be `^2.0.0-alpha.0`, which is not SemVer-compatible with `2.0.1-alpha.1`.  

If I install the older version then I end up with conflicting versions of `@typescript-eslint/experimental-utils`.

**Suggested fix:**  Change the `@typescript-eslint/parser` peer dependency to be the latest canary version.

@JamesHenry FYI

**Comment by octogonz** [comment]
Diffing the tarballs, there doesn't seem to be any code changes between `2.0.0`, `2.0.1-alpha.0`, and `2.0.1-alpha.1`. 🤔 Maybe something's wrong with the automated publishing?

**Comment by bradzacher** [comment]
2.0.0 and 2.0.1-alpha.0 should be exactly the same version. This was just a test publish to make sure the automated canary was working.
2.0.1-alpha.1 will look the same because the commit that triggered it (ca3b6a57b589213c6761cc311127cf3aa7e42082) was only a documentation change.

---

Dang it. @JamesHenry 😭 we forgot to re-fix the dep after we manually changed it due to lerna not working correctly for #827.
