### ISSUE TITLE
Docs: Add section for troubleshooting "Definition for rule x was not found" when doing Local Linking

### ISSUE THREAD

**Issue by skondrashov** [typescript-eslint/typescript-eslint#8587]
- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

After performing the local linking steps, I am getting: `Definition for rule '@typescript-eslint/no-unused-vars' was not found` when running `npx eslint .`

It feels like the page might lack information on what the minimum requirements for a repository made to test a rule are, but if the steps on the page are in fact the only ones, they don't seem to work for me. I ran:
```
~/typescript-eslint (main)
$ for package in ./packages/*; do
    cd $package
    npm link
    cd ../..
done
```
which succeeded after adding a bunch of packages, then:
```
~/playground (main)
$ npm link @typescript-eslint/eslint-plugin @typescript-eslint/parser

added 2 packages, changed 1 package, and audited 386 packages in 4m
```
and then:
```
 ~/playground (main)
$ npx eslint .

  1:1  error  Definition for rule '@typescript-eslint/no-unused-vars' was not found  @typescript-eslint/no-unused-vars
```

My .eslintrc.json looks like this:
```
{
	"rules": {
		"@typescript-eslint/no-unused-vars": "error"
	}
}
```
and I'm pretty confident that's a real rule

### Affected URL(s)

https://typescript-eslint.io/contributing/local-development/local-linking

**Comment by JoshuaKGoldberg** [comment]
🤔 in order to add this FAQ we'd have to figure out why the thing wasn't working... I notice `yarn build` isn't mentioned anywhere in this issue and only in a _ℹ️ Note_ admonition in the page. Was that the issue @skondrashov?

**Comment by JoshuaKGoldberg** [comment]
Hmm, interesting. Can you provide a way for us to reproduce this on our ends? I'm not able to with a new blank repository.

**Comment by skondrashov** [comment]
```
git clone git@github.com:typescript-eslint/typescript-eslint.git
git clone git@github.com:skondrashov/playground.git
cd typescript-eslint
yarn install
yarn build
for package in ./packages/*; do
    cd $package
    npm link
    cd ../..
done
cd ../playground
npm install
npm link @typescript-eslint/eslint-plugin @typescript-eslint/parser
npx eslint index.ts
```

identical errors on 2 machines, one mac one windows

**Comment by skondrashov** [comment]
I think I figured it out in the process, the .eslintrc file needs to have
```
	"plugins": ["@typescript-eslint"],
```

probably makes sense to include:

```
{
	"parser": "@typescript-eslint/parser",
	"parserOptions": {
		"ecmaVersion": "latest",
		"sourceType": "module"
	},
	"plugins": ["@typescript-eslint"],
	"rules": {
		"@typescript-eslint/no-unused-vars": "error"
	}
}
```

**Comment by JoshuaKGoldberg** [comment]
Aha! 💡 

I think this can be solved best by a combination of three things:

* https://github.com/eslint/eslint/issues/17986 (what a good coincidence): ESLint having troubleshooting entries for this common `Definition for rule` issue, in addition to the `find the config` and `determine the plugin` issues already mentioned there
* https://github.com/typescript-eslint/typescript-eslint/issues/8587#issuecomment-1979185216: mentioning `yarn build` explicitly
    * Confirmed that wasn't the issue here, but I'm sure it will be for other folks
* Adding quick phrasing to [Local Linking](https://typescript-eslint.io/contributing/local-development/local-linking) that indicates trying our [Getting Started](https://typescript-eslint.io/getting-started), our [Troubleshooting & FAQs](https://typescript-eslint.io/troubleshooting), and the new ESLint FAQs

We wouldn't want to add a lot of sentences or code blocks to the page for this. Forgetting / not thinking the `plugins` is necessary is really a troubleshooting for ESLint in general. And it's less easy to trip up on it in flat configs.

Thanks for the added info - marking as blocked on https://github.com/eslint/eslint/issues/17986 for now.

**Comment by skondrashov** [comment]
I was expecting the page to be a guide for setting up a local development environment to create a rule in typescript-eslint, but it seems was written to be a guide for using a rule in a repository (one that is already using the parser and plugin) if it already exists. But It feels strange not to have a guide for my use case, essentially saying "do this, and you will be able to start writing a new rule". Are people writing the rules in the typescript-eslint repository itself using unit tests? The docs don't suggest that option, so I decided to create a small repository following that guide.

It seems if the guide is explicitly mentioning `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` it should also say how to use them. Those bits of information as well as that the repository should have `eslint` installed would complete it as a guide for my use case. Otherwise, it's not quite a generic linking guide, since it mentions specific things to link, and it's also not a guide for how to develop for this project, since it doesn't have all of the steps to start developing.

I feel like it's hard to understand why I would need this information because you've been working with these tools for so long, so when you say for example "forgetting/not thinking the plugins is necessary" you're assuming I had any idea that a plugins field exists or what it does. Probably most people who want to contribute are going to be eslint experts to some degree too, but I imagine your intent is to bring people in, and being explicit makes the barrier to entry lower.

**Comment by JoshuaKGoldberg** [comment]
> I think your combination of solutions could work if the page was at least explicit about saying that you need a repository with configuration that already works before you start following the guide, which probably again seems obvious but because I got there from the Local Development page, it was not.

Yes, exactly, this - I'm suggesting we explicitly tell people to go through those steps. That's what I meant by:

> * Adding quick phrasing to [Local Linking](https://typescript-eslint.io/contributing/local-development/local-linking) that indicates trying our [Getting Started](https://typescript-eslint.io/getting-started) ...

I think we're on the same page. 🙂

**Comment by JoshuaKGoldberg** [comment]
No longer blocked on https://github.com/eslint/eslint/issues/17986. 🚀
