### ISSUE TITLE
Rule proposal: prefer-readonly-interface

### ISSUE THREAD

**Issue by TotooriaHyperion** [typescript-eslint/typescript-eslint#8598]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

What:
To require properties declared in interface be read-only, so we can notify the user that all properties in an interface can't be modified directly by default.

Why:
In most cases, we don't allow dependent modules to modify properties directly.
Our team members sometimes forget to declare readonly properties for interfaces that to be exposed to external users.
So we want this pattern to be the default.

```typescript
module.exports = {
  "rules": {
        '@typescript-eslint/prefer-readonly-interface': [
          'error',
          {
            properties: true,
            arrowFunction: false,
          },
        ],
  }
};
```

### Fail Cases

```TypeScript
export interface IModel {
  count1: number;
  inc(): void;
  dec(): void;
}
```

### Pass Cases

```TypeScript
export interface IModel {
  readonly count1: number;
  inc(): void;
  dec(): void;
}
```

### Additional Info

Users should only modify count1 by calling inc/dec.

**Comment by bradzacher** [comment]
There's a rule for this already in another plugin

https://github.com/eslint-functional/eslint-plugin-functional/blob/main/docs%2Frules%2Ftype-declaration-immutability.md

This pattern isn't a common enough paradigm in typescript for us to consider implementing a rule in our project.

Additionally this does fall under this FAQ:
https://typescript-eslint.io/troubleshooting#how-can-i-ban-specific-language-feature
You are looking to ban `TSPropertySignature[readonly = false]`.
Which is another point against us adding a rule in this project.

For these reasons I am going to reject this request - thanks for filing!
