### ISSUE TITLE
Bug: [@typescript-eslint/array-type] <Definition for rule '@typescript-eslint/array-type' was not found>

### ISSUE THREAD

**Issue by AliceZhuZhu** [typescript-eslint/typescript-eslint#8601]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play#ts=5.3.3&showAST=es&fileType=.tsx&code=AYKARAAgLgngDgUwM4GMBOBLOUC0yA2GAdlAPQCGaa5MOsiYAXAAQDaIznzYCVA9mjAAaDlwDeortwAmCAGbkArvihNulajDCTmAX1EBdEcCA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tmUSWWS18iALbF4AQ2G1Gw6BPioMkRNGgdokcGAC%2BIHUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
run ng lint

angular.json:

"lint": {
          "builder": "@angular-eslint/builder:lint"
        }
```

### ESLint Config

```javascript
"overrides": [
    {
      "extends": [
        "plugin:@angular-eslint/recommended"
      ],
      "plugins": [
        "eslint-plugin-jsdoc"
      ],
      "rules": {
        "@typescript-eslint/array-type": [
          "error",
          {
            "default": "array"
          }
        ]
     }
  }
]
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
    "allowJs": true,
    "strictPropertyInitialization": false,
    "strict": false,
  }
}
```

### Expected Result

lint passed

### Actual Result

 1:1  error  Definition for rule '@typescript-eslint/array-type' was not found                   @typescript-eslint/array-type

### Additional Info

   error: 
```
    "@angular-eslint/builder": "17.1.0",
    "@angular-eslint/eslint-plugin": "17.1.0",
    "@angular-eslint/eslint-plugin-template": "17.1.0",
    "@angular-eslint/schematics": "17.1.0",
    "@angular-eslint/template-parser": "17.1.0",
```

work:
   ```
 "@angular-eslint/builder": "15.2.0",
    "@angular-eslint/eslint-plugin": "15.2.0",
    "@angular-eslint/eslint-plugin-template": "15.2.0",
    "@angular-eslint/schematics": "15.2.0",
    "@angular-eslint/template-parser": "15.2.0",
```

**Comment by bradzacher** [comment]
Please read through our getting started guide as I believe you've missed a number of steps in your setup.
https://typescript-eslint.io/getting-started/

**Comment by AliceZhuZhu** [comment]
> Please read through our getting started guide as I believe you've missed a number of steps in your setup. https://typescript-eslint.io/getting-started/

Hi @bradzacher , 

Thank you very much for your reply.
I think the key to this problem is the upgrade of V15 to V17.
With the same configuration, V15 works normally.
But I didn't find the reason in the version release.

Thanks,
Alice
