### ISSUE TITLE
Bug: [no-useless-template-literals] Comments are removed by auto-fix

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8609]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=AYQwJA3g9AVABAIzjKcDkBjNdZwCbJQC%2BApsANxA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tmUSWWS18iALbF4AQ2G1Gw6BPioMkRNGgdokcGAC%2BIHUA&tsconfig=&tokens=false

### Repro Code

```TypeScript
`a${/* b */ 'c' /* d */}e`;
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-useless-template-literals": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

The fix result should be... well, I'm not sure what. Maybe the comments should be moved to before the string?:

```ts
// b
// d
`ace`;
```

### Actual Result

```ts
`ace`;
```

### Additional Info

This is a common thing to look out for in rule reviews. Ref: #8549

**Comment by bradzacher** [comment]
*personally* I'm okay with removing the comments there.
I don't think there's much value in keeping them. I also would say that in a provably useless template literal the odds of having comments is very low.

**Comment by JoshuaKGoldberg** [comment]
```ts
`Hello, ${/* TODO: Switch to the user's name once the API works (GH-1234) */ 'user'}!`;
```

I think cases like this would be rare, but not impossible.

**Comment by bradzacher** [comment]
> I think cases like this would be rare, but not impossible.

Hence 😄

> the odds of having comments is very low
