### ISSUE TITLE
Docs: Explicitly say whether PR authors should merge from `main`

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8610]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I've noticed that authors of PRs sometimes take on the task of keeping the PR updated from `main`. This happens...

* For PRs that haven't been reviewed yet and even for ones that have `1 approval` added
* For PRs with and without merge conflicts

My personal opinion is that we shouldn't expect PR authors to continuously merge the latest `main` into their branch. Especially as we've been more actively recently, it can be a real tax on some PRs to continuously merge from `main`. The worst case scenario would be that someone's PR takes a wihle to get reviewed -at no fault of theirs- and they keep feeling a need to resolve introduced merge conflicts in the interim. 😬 

And, as @auvred mentions below, subscribed folks get notifications for each merge.

Proposal: let's establish the recommended practice as...

* By default, no need to merge from `main`
    * If you see merge conflicts or other intersections that worry you, then you can as a courtesy
* If we think merge conflicts need to be resolved in order to merge and/or review a PR, we might opt into that as a courtesy _if_ we have time - but may still ask you to
    * If a PR spent an unusually long time to get a review, we'll try to find the time 

...where _"unusually long"_ and _"try to find the time"_ are intentionally vague.

~Edit: GitHub lost the data from the submission, re-typing after I walk away from the computer for a few moments...~ ✔️ 

### Affected URL(s)

https://typescript-eslint.io/contributing/pull-requests

**Comment by auvred** [comment]
I +1 to this, since GitHub sends a notification about commits on the PR to everyone who watches the repository.
