### ISSUE TITLE
Bug: Unclear How to Use Custom Rules

### ISSUE THREAD

**Issue by incutonez** [typescript-eslint/typescript-eslint#8619]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

Hello!  I tried following the [Custom Rules docs](https://typescript-eslint.io/developers/custom-rules/) for using [array-bracket-newline](https://github.com/eslint/eslint/blob/337cdf9f7ad939df7bc55c23d953e12d847b6ecc/lib/rules/array-bracket-newline.js) but in TypeScript (as done [here](https://github.com/incutonez/eslint-plugin/blob/main/src/rules/array-bracket-newline.ts)).  I'm able to build this repo, and you can see the resulting lib [here](https://github.com/incutonez/eslint-plugin/blob/main/lib/index.js).

The problem I'm having is how do I use this rule?  I've seen a couple of examples online like this [SO answer](https://stackoverflow.com/questions/72619968/how-do-i-use-a-custom-eslint-rule-that-i-wrote-using-typescript-eslint-utils/74480885#74480885) and [this repo](https://github.com/ridedott/eslint-plugin/tree/master), but neither of them seemed to have helped... I'm probably just completely not understanding something.

Anyway, when I try to install my repo as a package locally through `npm i eslint-plugin`, and I try to use it in my eslintrc.json file, I get an error saying `ESLint: Definition for rule '@incutonez/array-bracket-newline' was not found.(@incutonez/array-bracket-newline)`.  I define the rule in my eslintrc.json as the same you would for array-bracket-newline, just with my package name prepended `"@incutonez/array-bracket-newline": ["error", "always"]`.

What am I doing wrong?

### Reproduction Repository Link

https://github.com/incutonez/eslint-plugin

### Repro Steps

1. Clone repo
2. `cd yourFavoriteProject`
3. `npm i ../clonedRepoName`
4. Change `eslintrc.json` to include `eslint-plugin-incutonez` in plugins and `"@incutonez/array-bracket-newline": ["error", "always"]` in rules.
5. Notice error from ESLint

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `^7.1.1` |
| `@typescript-eslint/parser`            | `^7.1.1` |
| `@typescript-eslint/utils`             | `^7.1.1` |
| `TypeScript`                           | `^5.4.2` |
| `ESLint`                               | `^8.57.0` |
| `node`                                 | `20.11.1` |

**Comment by bradzacher** [comment]
https://github.com/incutonez/eslint-plugin/blob/main/package.json#L2

Your package is called `eslint-plugin-incutonez`
ESLint essentially cuts out the `eslint-plugin-` and uses the remainder as the namespace.

So your namespace is `incutonez/` - without the `@`.

Read more in the ESLint docs
https://eslint.org/docs/latest/extend/plugins

**Comment by bradzacher** [comment]
Also as per our contributing guide
https://typescript-eslint.io/contributing/issues#questions-and-support-requests

We don't use issues as a Q&A channel.
Head to the above link for alternatives to get support - for example our discord is a great option.

**Comment by incutonez** [comment]
@bradzacher I swear I tried that, but thank you and sorry for doing Q&A here!
