### ISSUE TITLE
Docs: Put Discord and/or donation link(s) in header

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8627]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

@bradzacher and I were chatting on a Twitch stream yesterday, and noted that our header doesn't have a link to [our Discord](https://discord.com/invite/FSxKq8Tdyg). We should add one next to the GitHub link.

You can find Discord's branding assets here: https://discord.com/branding

### Affected URL(s)

_all of them_

**Comment by bradzacher** [comment]
I actually said "donation" link!
The discord would be nice too but it is available in the footer.

**Comment by JoshuaKGoldberg** [comment]
Ha, I was planning on starting a discussion for the donation link. My hunch -somewhat informed from time on growth teams- was that asking for money that soon isn't likely to be worth the space. But I'm open to being pursuaded.

**Comment by bradzacher** [comment]
I was just going by what other projects did.
Most have it in the header but we've **only** got it on the home page.

**Comment by JoshuaKGoldberg** [comment]
In that case, I think we can ease into this:

* Discord: to the header
* Open Collective: to the footer > More
