### ISSUE TITLE
Bug: [@typescript-eslint/no-unused-vars] Fails to detect certain unused imported interfaces

### ISSUE THREAD

**Issue by kenlyon** [typescript-eslint/typescript-eslint#8631]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

I expected the `@typescript-eslint/no-unused-vars` rule to identify all unused imports but certain ones seem to be ignored.

### Reproduction Repository Link

https://github.com/kenlyon/no-unused-vars-bug

### Repro Steps

1. Check out the repository.
2. Open it in VS Code
3. Run yarn install.
4. Open src/test.ts.
5. Wait for eslint to scan the file.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `7.1.1` |
| `@typescript-eslint/parser`            | `7.1.1` |
| `TypeScript`                           | `5.3.3` |
| `ESLint`                               | `8.57.0` |
| `node`                                 | `20.9.0` |

**Comment by bradzacher** [comment]
I am unable to reproduce this in the [playground](https://typescript-eslint.io/play/#ts=5.3.3&fileType=.tsx&code=FASwtgDg9gTgLgAgN7AQgggO3AQziKTAUQDcBTTOAGlQQGEALHTAczNIutroBsQIARlBwwAJh0o00dKJCgBnEPkISuaVQAlmonmRhSEAMSgBjAK7zVB4zDBXaASUwkcfceUm0AKjGaLlxB5qCACqDvYAvggAZjCyCABEMGQ4JnAJANzAwAD0OQhEAB4QZGlkogBcCF4MZAg4QuQIfJh18gxQZjyiCO1QAO4IcLVDIwACcACeJfImMPxwALRk8i1wOZhQi2aYFuWLLjDyCHpxMDGw9Tw8CJg4YOUI4NDw8gB0ufnoaWauVQDymB4k3oTFY7CCVAKQS0mB0eihNjsQXqcIQThcblUCDYrV8cDqp1g72AQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tidmUQAmtAG4BDaKgwBtcNhyJo0DtEgAaWXKxzskcQHNJUUfHhqN23dAMBJPZ2iIACqPz4FTdFAB6AfTPadMlFYPQALfABRRWVDXRN-AKggkPCopQlbeycXN2gPDEhfBIDIARR8ODJ8WAcBAEFFUUJM5WzXd09Cv3VEqDEMu1bndrzOop7EyEpBhwAlcoBlSgAjRiYDTwrYRHMIAF9zAF1ZA4OgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

**Comment by kenlyon** [comment]
@bradzacher Right, I used this template instead because it's not reproducible in the playground. It needs the type information from react. Please try again using the Reproduction Repository Link above.

**Comment by bradzacher** [comment]
The `no-unused-vars` lint rule does not use type information. It is a single-file, pure syntactic rule.

So the presence or absence of types should not change a thing.

**Comment by auvred** [comment]
It looks like ScopeManager gets different `lib` depending on the `project` parser option https://github.com/kenlyon/no-unused-vars-bug/blob/46ba82fa50d77871ca6d9daad54330689f9ac384/.eslintrc.cjs#L5

Without type-aware linting configured, the `lib` value is `["esnext"]` (the default one), but with `project` option set, the value of `lib` is `["lib"]`

`lib` lib includes `dom` lib that contains all unreported types `AnimationEvent`, `ClipboardEvent`, `CompositionEvent`, etc.

As far as I understand it, this is a bug. The rule should complain about unused imported typpes even if their names are shadow of some global types from the typescript lib.

**Comment by bradzacher** [comment]
@auvred if it was the lib types then you should be able to reproduce this in the playground by setting `lib` on the tsconfig. But it does not reproduce for me in doing that.

**Comment by bradzacher** [comment]
Oh I see. The missing piece is bad config actually.

https://github.com/kenlyon/no-unused-vars-bug/blob/46ba82fa50d77871ca6d9daad54330689f9ac384/.eslintrc.cjs#L6

You have `sourceType: script`. But you're writing modules. So you're in the land of undefined behaviour.

Change that and it'll work fine.
