### ISSUE TITLE
Enhancement: [prefer-reduce-type-parameter] handle `reduce` on tuple type

### ISSUE THREAD

**Issue by yeonjuan** [typescript-eslint/typescript-eslint#8639]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=MYewdgzgLgBAhgJwXAnjAvDA2gcjjgGhhwCMcBdAbgChRJYoBXABwBsBTALm2gQEswAcyK8Bg8hmx5CxMlWoLEyFADoE7ACaNg7ABS64wYEWCMEASgwA%2BGLoDeMFU8PHsphOW5QEjdgF9zIjs-eAgYACV2UAQNAB5RISISEBAOODArc0oYAHocmAAZAVgAUSQQBFsAeQBpcwUmNnY1TW09AyMTM0t0G3tHZ063M08Yb18CAKCQuDDI6LiE4Rhk1PZ0qwIs3PyAORAYMoQK2wAzOFYIdhgwdkE4KD4AN3ZzIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0Wls4AmsMolpFStYgENoUgLaJ8vdFF7QA9tEjgwAXxC6gA&tsconfig=&tokens=false

### Repro Code

```TypeScript
const array = ['a', 'b'];
const tuple: [string, string] = ['a', 'b'];


array.reduce((acc, cur) => ({ ...acc, [cur]: true}), {} as Record<string, boolean>); // Lint Error (OK)

tuple.reduce((acc, cur) => ({ ...acc, [cur]: true,}), {} as Record<string, boolean>,); // No Error (false negative)
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/prefer-reduce-type-parameter": ["error", ...<options>],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

Reports a lint error

### Actual Result

No error

### Additional Info

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/rules/prefer-reduce-type-parameter.ts#L75

**Comment by auvred** [comment]
Looks like an enhancement IMO :smile:
