### ISSUE TITLE
Enhancement: Display error count on tabs in playground

### ISSUE THREAD

**Issue by yeonjuan** [typescript-eslint/typescript-eslint#8641]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

website

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

In "Errors", "ESTree"... tabs in Playground, it would be nice to show the number of errors.
This way, even if we don't select the tab, we can aware that errors occurred.

| AS-IS | TO-BE |
| --- | --- |
| <img width="300" alt="as-is" src="https://github.com/typescript-eslint/typescript-eslint/assets/41323220/c8f5e780-710f-442c-9c29-4b5dc9c75f06">  | <img width="300" alt="to be preview" src="https://github.com/typescript-eslint/typescript-eslint/assets/41323220/af133c8a-198c-4421-8e20-bd9cdf48ac83"> |

**Comment by JoshuaKGoldberg** [comment]
_Oh_ I really like this!
