### ISSUE TITLE
Docs: add consistent-return warning

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#8657]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Last week, we introduced a new extension rule for `consistent-return`.
However, I think it is best practice in the ecosystem to use the `noImplicitReturns` TypeScript compiler flag in favor of this lint rule.
If so, the docs should explicitly advise users to not use this rule, preferably with a big red warning label or whatnot.
If not, the docs should include a discussion on the `noImplicitReturns` TypeScript compiler flag and the pros/cons of using the rule over the compiler flag.

### Affected URL(s)

https://typescript-eslint.io/rules/consistent-return/

**Comment by bradzacher** [comment]
I'm okay with this.
I personally think that the `consistent-return` rule is an anti-pattern.
There's multiple issues where people are trying to use it and are annoyed because it doesn't have TS's type-aware control-flow analysis.

But the `noImplicitReturns` compiler option has all that and more.
