### ISSUE TITLE
Bug: [no-unnecessary-template-expression] Auto fix will change meaning of code

### ISSUE THREAD

**Issue by rubiesonthesky** [typescript-eslint/typescript-eslint#8669]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play#ts=5.3.0-beta&fileType=.tsx&code=MYGwhgzhAECC0G8BQ1oQC5nQS2NAZgPYBOAtlgBQZYCuEAXItAHZikCmjGx2zA5tAA%2B0GswAm7fL3ZjoAXyEjxk6WICUXdD36LREqcxmIUqaMXboaxZmkyWIAfgB0rDtAfQABgBIE1ey5s7ELCAOShcp5OWtikFGrQjHoqhmIA3CZySHJAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYkACAXAngA4oDG0AlobgLQrzkB2uA9AwPbWzKJLLLW5EAW0LwAhoOr1B0MfFQZIiaNDbRIAXxAagA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYwAviNUA&tokens=false

### Repro Code

```TypeScript
class A {
  static format(status: { name: string | undefined } | undefined): string | undefined {
    return status?.name ? `${status.name || ''}`.trim() : undefined;
  }
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {"@typescript-eslint/no-useless-template-literals": "error"}
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {}
}
```

### Expected Result

```ts
class A {
  static format(status: { name: string | undefined } | undefined): string | undefined {
    return status?.name ? (status.name || '').trim() : undefined;
  }
}
```

I think the autofixer should have added parens when it removed the template literal. 

### Actual Result

```ts
class A {
  static format(status: { name: string | undefined } | undefined): string | undefined {
    return status?.name ? status.name || ''.trim() : undefined;
  }
}
```

### Additional Info

This seems to repro in Playground with or without `strictNullChecks`. I'm my project, I was not using `strictNullChecks`.

The autofix highlights that the original code is silly. 

I tested this also with minimal eslint config, and it still happens.

Edit: I changed Playground link to be most minimal rule set & tsConfig.

**Comment by bradzacher** [comment]
I'd guess the fixer isn't considering precedence and should be using our utils to conditionally include parentheses around the expression.
