### ISSUE TITLE
Enhancement: [no-unsafe-return] Disallow return Promise<any>

### ISSUE THREAD

**Issue by yeonjuan** [typescript-eslint/typescript-eslint#8674]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-unsafe-return

### Description

This proposal is to make `no-unsafe-return` disallow `Promise<any>` as well.
[playground](https://typescript-eslint.io/play/#ts=5.4.2&fileType=.ts&code=FAEwpgxgNghgTmABBA9gOwM4BdEAc4oC2AlhmAFyIAKBJZAPDGgJ4B8A3MMKpjgEbxEAXkQwMzNBEQAKAJTDWogO4xiOfEVJh2iAPS7EAUTgE4MlAGtZXHtkQCAXsNHjJM%2BUMUa62vQcQAwgCuJmBoWFDMADSIaoggKGAYiGgoOAi4KHA4YCZZGAB0XMBAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolrRE%2BWNCbooiaNA7RI4MAF8QKoA&tsconfig=&tokens=false)
```ts
declare const promise: Promise<any>;
const bar = async () => await promise; // Error (ok)
const baz = async () => promise; //  Currently, it does not report errors.
```

https://typescript-eslint.io/rules/no-unsafe-return

> Despite your best intentions, the any type can sometimes leak into your codebase. Returning an an any-typed value from a function creates a potential type safety hole and source of bugs in your codebase.

If a `Promise<any>` value is returned, the any type can leak into your code.

```ts

declare const promise: Promise<any>;
const baz = async () => promise;

function addOne(num: number) {
  return num + 1;
}

(async () => {
  addOne(await baz()); // no type error
});

```

### Fail

```TypeScript
declare const promise: Promise<any>;

const foo = () => promise;
const bar = async () => promise;
// ...
```

### Pass

```TypeScript
declare const promise: Promise<number>;

const foo = () => promise;
```

**Comment by bradzacher** [comment]
The rule doesn't check `T<any>` implicit return types at all - it only checks `T<any>` when the function is explicitly annotated as returning `T<U>`.

But given `Promise`'s special handling with async functions it probably makes sense to check it the same as with a raw `any` because the implied return type of an async function is `Promise<T>`, not `T`.

I don't think we should add special handling to the non-async usecase, however. I don't think it's right to add special meaning to promise in non-async contexts.
