### ISSUE TITLE
Bug: [no-unnecessary-template-expression] Inconsistent handling of escapes and quotes in autofixes.

### ISSUE THREAD

**Issue by kirkwaiblinger** [typescript-eslint/typescript-eslint#8677]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

[click here](https://typescript-eslint.io/play/#ts=5.4.2&fileType=.ts&code=AYEg3gRAOgrgDHAogVggX2AbgFAHpcAEAhjAC4D2AZgJYAeApgM4EUF6HTxKo7bAHhOCFOgJZ2xMlTpMW5NvjEEAp2MxA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tmUSWWS18iALbF4AQ2G1Gw6BPioMkRNGgdokADThskTt179B5CaXRRV6zboC%2BIW0A&tsconfig=&tokens=false)

### Repro Code

```TypeScript
`${"\u00E5"}`;
// autofixes to 
// "\u00E5";

` ${"\u00E5"} `;
// autofixes to 
// ` å `;
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-useless-template-literals": "error",
    "no-useless-escape": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

I expect that the autofixed strings should preserve the string type and the escaped characters as the author wrote them.
So, we should have 
```typescript
`${"\u00E5"}`;
// autofixes to 
// `\u00E5`;

` ${"\u00E5"} `;
// autofixes to 
// ` \u00E5 `;
```

### Actual Result

actual autofix results change user's input regarding template and and escaped characters.

### Additional Info

This can also result in multiline template literals instead of single line literals that include a `\n`. 

It doesn't impact correctness at runtime, but it isn't the purview of this rule to make these stylistic changes (with the caveat, of course, that obviously `$`s and backticks still need to be escaped in order to incorporate a string literal into a template string)

**Comment by JoshuaKGoldberg** [comment]
Fixed by https://github.com/typescript-eslint/typescript-eslint/pull/8688
