### ISSUE TITLE
Ban `errorOnTypeScriptSyntacticAndSemanticIssues` from being used within `parser`

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#8681]
Reference: https://github.com/import-js/eslint-plugin-import/issues/2980

`errorOnTypeScriptSyntacticAndSemanticIssues` is an undocumented parser option.
Specifically it's an option that's documented and accepted in `typescript-estree`, but is not documented in `parser`.

It was never intended for use within eslint runs and it only works as a `parserOption` purely because we're lazy and we don't validate the options a user passes in.

We never wanted to report TS semantic errors from within our parser, and we have been building out syntax errors by hand within the conversion logic. As such we should outright ban this from being passed as a parserOption.

**Comment by peanutenthusiast** [comment]
To clarify, are we removing it's consumption from the `parser` file?

**Comment by bradzacher** [comment]
We should specifically override the option within the `parseForESLint` function to force it to `false` so that it can never be set from a user's config.
