### ISSUE TITLE
Enhancement: requiresQuoting in type-utils support jsDoc

### ISSUE THREAD

**Issue by developer-bandi** [typescript-eslint/typescript-eslint#8690]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

type-utils

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

i'm write test case about requiresQuoting in type-utils but 
I immediately had a hard time understanding what this function was for.

Since the function appears to have a function that tells you whether quotation marks should be used in the name of the type property, it would be good to provide a description of the function parameters and whether it returns true or false.

**Comment by JoshuaKGoldberg** [comment]
I'd be curious to hear from other newer contributors. My general ideology with JSDoc comments is that they have a bad habit of getting out of date, so it's best to save them for cases where the behavior of the code isn't clear to a typical reader.

**Comment by bradzacher** [comment]
5 months later and this request has received 0 community reactions.
As per our [workflow guidelines](https://typescript-eslint.io/maintenance/issues#community-engagement-evaluation) - we are taking this as signal that this check is not important to the broader community and are thus rejecting the proposal. Thanks for filing!
