### ISSUE TITLE
Docs: Add ATA (Automatic Types Acquisition) to the playground

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8696]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

https://typescriptlang.org/play utilizies TypeScript's ATA to provide types for npm packages. That's really nice and useful for code snippets based on packages.

Our playground doesn't support ATA. Which is a little inconvenient for cases where we'd want to use our playground for code that includes packages. For example, I filed #8695 using the TypeScript playground because I wanted it to show using types from `@typescript-eslint/utils`.

Proposal: let's add [`@typescript/ata`](https://www.npmjs.com/package/@typescript/ata) (and/or however else one might add ATA to a Monaco editor) to our playground?

💖

### Affected URL(s)

https://typescript-eslint.io/play

**Comment by JoshuaKGoldberg** [comment]
Two 👍s so I'll mark as `accepting prs` 😄 thanks. To any prospective contributor: I don't know how easy or difficult this would be. It might be a straightforward API call... or it might be a huge rearchitecture of the playground. I would recommend tackling other playground issues first.

**Comment by armano2** [comment]
for reference if someone is going to work on it, all what we actualy have to do is enable it

https://github.com/typescript-eslint/typescript-eslint/blob/2db8f4ef0fd3e7d50843a0972f39b10746c47978/packages/website/src/components/editor/useSandboxServices.ts#L65
