### ISSUE TITLE
What is the right way to view the TSESTree for debugging?

### ISSUE THREAD

**Issue by octogonz** [typescript-eslint/typescript-eslint#870]
This is a general question.  

Lint rules operate on `node` trees using AST types from the `TSESTree` namespace.  To view the tree, I can add something like `node.parent.parent.parent.patch` to my debugger watch window, but this is pretty awkward to inspect.

Is there a standard way to dump the entire tree to a JSON file, so I can view it in a proper editor?  Or is there a cool tool for visualizing these trees?

My current workaround is to copy+paste a handcoded function that (1) deletes the back references such as `parent` fields, (2) calls `JSON.serialize()`, and then calls `fs.writeFileSync()`.  But this is pretty clumsy.

Just curious if there's a better approach that others are using.

**Comment by bradzacher** [comment]
https://astexplorer.net is your best friend for this.

We try to keep it updated with the latest version, but the maintainers can be pretty slow with merging dependency updates and doing releases.
Note that it's pretty straight-forward to run a version locally

You'll notice that it also lets you switch the parser, and supports typescript, babel, espree, as well as (of course) @typescript-eslint/parser.

This won't help you with figuring out type information, as this is not included, but it helps for figuring out the AST output!

**Comment by octogonz** [comment]
Would it make sense for the TSESTree API to include a diagnostic operation for dumping a subtree in JSON format?  That might help in situations where it's tedious to manually paste text into a website.  I would just use `JSON.serialize()`, but the graph cycles make that a little awkward.

**Comment by bradzacher** [comment]
Potentially.

But IMO it's easier to use the website.
astexplorer provides a really nice interface for inspecting the AST by automatically highlighting and revealing the relevant AST nodes as you, and has options to "trim the cruft" by removing location data and empty keys.

Also note the "transform" switch in the menu bar. Clicking this means you can actually prototype rules within the UI itself.
I find it is an invaluable tool for writing rules and debugging problems.

---

FYI - typescript-estree/parser does not add the `parent` prop to nodes, that's actually a function of eslint. It traverses the tree and adds that prop before it runs the rules.

Which means it's pretty trivial to write a little script to do this (I think this code is correct):
```
import { parse } from '@typescript-eslint/parser';
import fs from 'fs';

const contents = fs.readFileSync(inputFilePath, 'utf8');
const ast = parse(contents, parserOptions);
fs.writeFileSync(JSON.stringify(ast, null, 2), outputFilePath);
```

**Comment by octogonz** [comment]
Thanks, I'm happy with this answer.
