### ISSUE TITLE
Bug: PanelResizeHandle sometimes doesn't work

### ISSUE THREAD

**Issue by developer-bandi** [typescript-eslint/typescript-eslint#8731]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

website

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

In [playground](https://typescript-eslint.io/play/#ts=5.4.2&showAST=ts&fileType=.tsx&code=qKMnZGQsjMQ&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkAJutKgIabMHEVh6YCu6AGnA16jFmw5EAss0Rce-YQF8QSoA&tokens=false), PanelResizeHandle sometimes doesn't work. i reproduce this below flow

1. Write code in the code tab.
2. After that, PanelResizeHandle will not work.
3. If you click the Errors, ESTree, etc. tab on the right once or twice, PanelResizeHandle will operate.

The reproduced browser is Chrome (122.0.6261.69) and I am confused as to whether this problem is only happening to me.

**Comment by armano2** [comment]
looks like something broke in one of recent changes or during of dependency upgrade,
i ruled out most recent bug fix for overflow,
