### ISSUE TITLE
Rule proposal: [no-boolean-parameters] Disallow booleans in function parameters

### ISSUE THREAD

**Issue by yeonjuan** [typescript-eslint/typescript-eslint#8762]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

It is a proposal to add rule which prevent the use of boolean type function parameters.

Boolean parameters in function make the code hard to read. It make it difficult to figure out what the boolean does when we call the function.

Consider the following code:
```ts
search(input, true); 
search(input, false);
```

Compare with the following:
```ts
search(input, { caseSensitive: true });
search(input, { caseSensitive: false });
```

---
IMO, as an exception, boolean parameters should be allowed when there is only one parameter. This is useful when writing functions that change boolean type state.

```ts
class Foo {
   isSelected(selected: boolean) {
   }
}
```

### Fail Cases

```TypeScript
function foo(arg: number, flag: boolean) { }
function bar(arg: number, flag?: boolean) { }

class Foo {
   foo(arg: number, flag?: boolean) { }
}

interface Bar {
   foo(arg: number, flag?: boolean) { }
}
```

### Pass Cases

```TypeScript
// I think we should allow cases where only one boolean is in the parameter.
class Foo {

   setIsSelected(selected: boolean) {

   }
}

function foo(selected: boolean) { }

function foo(arg: number, options: { flag: boolean } ) { }
```

**Comment by Josh-Cena** [comment]
I think this can be addressed via no-restricted-syntax. It seems too opinionated and bug-prone to be enforced on a general level. FWIW, the TypeScript code base has a lint rule called `argument-trivia` that requires arguments of the literal values `true`, `false`, `null`, `undefined` to be preceded by a comment:

```ts
// Completely made up btw
visit(node, /* skipParens */ true);
```

I think that's a much more reasonable heuristic with performance and API compatibility in mind.

**Comment by JoshuaKGoldberg** [comment]
> too opinionated

+1, yeah. I personally _generally_ adhere to this rule in my code but not always. If we added it in `recommended` -or, I'd bet, even `strict`- then there would be some _very_ unhappy users.

> `argument-trivia`

Honestly, I'm surprised nobody's split that out into a separate plugin by now...

Either way, putting under `evaluating community engagement` for a bit in case someone has a strong argument in favor of it.

**Comment by bradzacher** [comment]
I personally think that this is definitely way too far into the "opinionated stylistic" world and thus fails the "broadly applicable" test.

I definitely understand the motivation - but with TS having [editor inlays](https://code.visualstudio.com/docs/typescript/typescript-editing#_inlay-hints) which show the parameter name when you use a raw value or your variable name doesn't match the parameter name - I think this case is covered pretty well.

WDYT @typescript-eslint/triage-team

**Comment by bradzacher** [comment]
Oh ha. I was slow to respond and my app didn't update..

It looks like 3 team members are against then? I'm going to close this.

I think JoshC is right - this is easily enforceable via NRS. So it fails the "broadly applicable" test and it fails the FAQ "I want to ban this syntax" test, and has 3 against / not in favour of. Closing.

**Comment by yeonjuan** [comment]
Thanks for the feedback!, everyone.
