### ISSUE TITLE
Bug: [prefer-readonly] Autofix adds `readonly` keyword in JavaScript files

### ISSUE THREAD

**Issue by bnichell** [typescript-eslint/typescript-eslint#8776]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.0.4&fileType=.js&code=MYGwhgzhAEDC5QOoEsAuALAogJ2we22gG8BYAKGmgGIA5TANUwCUB9WACQEEaBxTAEWgBeaAHI6jVh259%2Bo8pQD0i6MgB2wAtgCmwVCACe0YOjBqA5toAm0VHgBcC6Mug6wVvGsPUJzNl14BYTFfKQDZeTInS1RoNW0AN21sWFMLawAKAEpiJ0oMZAgAOloGP2lA-icAX3JaqIbQSBh4ZpQMPABXVBx8QlIKZwAqIegAATcPLyMhxSdSyX8ZIJFxMrDluSdo7Vj4pJS0yyts3MH89EKS0KXKmrqgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYkACAXAngA4oDG0AlobgLQrzkB2uA9IdIgGaLTXsCGAEwD2DePnRRu0IdEhgAviHlA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkAhqqrAO4BSZlemAruuGAF8QAoA&tokens=false

### Repro Code

```TypeScript
class ClassWithError {
  #NEVER_CHANGED = 'NEVER_CHANGED'
  // incorrectly changed to:
  // readonly #NEVER_CHANGED = 'NEVER_CHANGED'

  get neverChanged() {
    this.#NEVER_CHANGED
  }
}


class ClassWithoutError {
  /** @readonly */
  #NEVER_CHANGED = 'NEVER_CHANGED'
  
  get neverChanged() {
    this.#NEVER_CHANGED
  }
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: { "@typescript-eslint/prefer-readonly": "error" }
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "allowJs": true
  }
}
```

### Expected Result

Either no auto-fix is done for rule `"@typescript-eslint/prefer-readonly"` in JavaScript files, or `@readonly` is added in its JsDoc comment:

```js
class ClassWithError {
  /** @readonly */
  #NEVER_CHANGED = 'NEVER_CHANGED'

  get neverChanged() {
    this.#NEVER_CHANGED
  }
}
```

Alternatively, if this is [not possible](https://typescript-eslint.io/troubleshooting/#one-of-my-lint-rules-isnt-working-correctly-on-a-pure-javascript-file), a comment should be added in the [rules documentation](https://typescript-eslint.io/rules/prefer-readonly/), stating that the rule should be disabled for JavaScript files (like for [this](https://typescript-eslint.io/rules/explicit-module-boundary-types/#configuring-in-a-mixed-jsts-codebase) rule).

### Actual Result

The `readonly` keyword is being added in front of the property, leading to invalid JavaScript code:

```js
class ClassWithError {
  readonly #NEVER_CHANGED = 'NEVER_CHANGED'

  get neverChanged() {
    this.#NEVER_CHANGED
  }
}
```

**Comment by bnichell** [comment]
For anyone facing this issue, our current workaround is to only disable the rule for JavaScript files, when auto-fixing is active:

```js
const overrideForJavaScriptInFixMode = process.argv.some((arg) => arg === `--fix`)
    ? { rules: { '@typescript-eslint/prefer-readonly': `off` }, files: [`**/*.js`] }
    : undefined;
if (overrideForJavaScriptInFixMode) flatConfig.push(overrideForJavaScriptInFixMode);
```

**Comment by bradzacher** [comment]
This is expected. Our rules purposely do not inspect file types or extensions because we don't know what your codebase's frameworks, libraries, etc might do or support.

The onus is on you, the user, to turn off rules that you do not want to run on JS files.

Two other examples of rules that will report errors on `.js` files that can't be resolved: `explicit-function-return-type` and `explicit-module-boundary-types`.

---

Your suggested fix is not correct and leaves the door open for a lot of breakages, for example your IDE does not execute ESLint from the CLI - so it will never have `--fix` in the `argv`. Similarly custom ESLint wrapping scripts will not likely have `--fix` in the `argv`.

Instead of just disabling the combination on fix - you should instead always turn the rule off for `.js` files.
