### ISSUE TITLE
Bug(website): tsconfig is blank

### ISSUE THREAD

**Issue by abrahamguo** [typescript-eslint/typescript-eslint#8781]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

website

### Playground Link

https://typescript-eslint.io/play/#code=DYUwLgBAzgXNYCcCWA7A5gbgFBagOjAHsBVAB1JAQGEBDKEACgEoMg

### Expected Result

A TypeScript error should be reported: `Variable 's' is used before being assigned.`.

### Actual Result

No TypeScript error was reported.

### Additional Info

As first mentioned in #8659:
When arriving at the playground with _no hash_ (i.e. by clicking the `Playground` link in the header), the default `tsconfig` is `{ "compilerOptions": { "strictNullChecks": true } }`.
However, when arriving at the playground _with a hash that does not include_ the `tsconfig` parameter, the `tsconfig` is blank. This affects almost all `Open in Playground` links throughout the docs, because most of them do not include the `tsconfig` hash parameter.

### Versions

Latest live website

**Comment by kirkwaiblinger** [comment]
Related: https://github.com/typescript-eslint/typescript-eslint/issues/8659
