### ISSUE TITLE
Bug: no-floating promises ignores voided promises when resulting undefined is used

### ISSUE THREAD

**Issue by inga-lovinde** [typescript-eslint/typescript-eslint#8783]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.3&fileType=.ts&code=MYewdgzgLgBAhhAnmYAxAriqBLcMC88SKMAFAJQEB8MACgE4gC22EApgHT1sBWbwUUgCIQIAA4Qh5ANwAoWaEiwAZgEYCZSvhoBvWTBjco6emBgA3ENgAmRZGkwDcYCnIC%2B8xdBjKATBopqGD0DL1gADw1LGzsUDCxnV1kPBXBvZQBmAK1dfQsrWwR7eKdwJI8gA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oDN4OBDfMwDmtYtA4BbSshTowAbXDYciaBOiQANMpVYV2SJWGdoiAGodKAE3nd%2B8WbuwBfZwF0dKvEVLIK1HQMzGyctNLIsLLWYhIRchiQahqQym4uQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
const asyncFunction = async () => Promise.reject("oops");

const f1 = () => {
  return void asyncFunction();
}

const f2 = () => {
  const x = void asyncFunction();
}

const f3 = () => {
  void asyncFunction();
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-floating-promises": [
      "error",
      {
        "ignoreVoid": false
      }
    ],
    "@typescript-eslint/no-misused-promises": "error"
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

Errors on lines 4, 8 and 12: "Promises must be awaited, end with a call to .catch, or end with a call to .then with a rejection handler."

### Actual Result

There were no errors on lines 4 or 8, only on line 12.

### Additional Info

It seems natural that `void promise` should be considered a violation of no-floating-promises rule, regardless of whether the resulting undefined is ignored or returned / assigned. But no-floating-promises only produces an error when the resulting undefined is ignored.

**Comment by bradzacher** [comment]
This is expected.
`no-floating-promise` only checks expression statements.
If you choose to void-out a promise in a non-top-level location it is not the concern of `no-floating-promise`.

In particular `const unused = void fn()` is no worse than `const unused = fn()` - in either case it's not checked by the rule and in either case you have a promise that's assigned somewhere and not awaited.

I would say that in general this is a pattern you should just want to explicitly ban via `no-restricted-syntax`. For example `:not(ExpressionStatement) > UnaryExpression[operator = "void"]` would ban any non-top-level usages.

I could see this as a potential enhancement for `no-misused-promises` - but I don't think there's broad applicability here? Most codebases already see `void` as a code-smell and so these sorts of things are usually just not done.

Curious to hear @typescript-eslint/triage-team 's thoughts

**Comment by inga-lovinde** [comment]
You are right that assigning promises to unused variables is not currently considered an error, whether the promises in question are voided or not, so the `void` operator doesn't really make a difference in this case.

However, it does make a difference for returns: https://typescript-eslint.io/play/#ts=5.4.3&fileType=.ts&code=MYewdgzgLgBAhhAnmYAxAriqBLcMC88SKMAFAJQEB8MACgE4gC22EApgHT1sBWbwUUgCIQIAA4Qh5ANwAoWaEiwAZgEYCZcgC4YANxDYAJtRgBvWTBjco6emD0HjCZGkwDcYCnIC%2B8xdBhlACYNCh19IxNzS2tbe2cUDCwPL1lfIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oDN4OBDfMwDmtYtA4BbSshTowAbXDYciaBOiQANMpVYV2SJWGdoiAGodKAE3nd%2B8WbuwBfZwF0dKvEVLIK1HQMzGyctNLIsLLWYhIRchiQahqQym4uQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

```
const asyncFunction = async () => Promise.reject("oops");

const f1 = (): void => {
  return void asyncFunction(); // <-- does not produce linting error, even with `ignoreVoid: false`
}

const f2 = (): void => {
  return asyncFunction(); // <-- produces linting error
}
```

**Comment by bradzacher** [comment]
Slight correction - the return type case does not create a linting error - it creates a type error.

That case specifically is very, very easy to ban via `no-restricted-syntax`.

**Comment by inga-lovinde** [comment]
But your suggestion of `no-restricted-syntax` would ban all usages of `void` operator, not just when applied to promises?

**Comment by bradzacher** [comment]
It would - but realistically the `void` operator isn't used in modern TS.

That was the genesis of the addition of `void` support for the `no-floating-promise` rule - we noticed there was an operator that nobody used for anything outside of codegenned code and it enabled us to create a new coding pattern with a nice symmetry with `await` that allows the user to expressly indicate the inverse.

If it does flag non-promise usages of `return void` then those cases are easily rectified:
```ts
// before
return void foo();

// after
foo();
return;
```
And thus you've eliminated the false-positive case.

**Comment by JoshuaKGoldberg** [comment]
> That was the genesis of the addition of `void` support for the no-floating-promise rule

Heh, I believe it was actually just a bug in https://github.com/palantir/tslint/pull/1632 from me not knowing about the `void` operator. Then a bunch of folks got used to it and my feeble protest in https://github.com/palantir/tslint/issues/4653 was wontfixed. https://github.com/typescript-eslint/typescript-eslint/pull/495#issuecomment-493510176 is where typescript-eslint discussed it.

That being said, +1 on the nice symmetry with `await` and `void`. 🙂

**Comment by JoshuaKGoldberg** [comment]
I actually do think this is a bug in the realm of what the rule should catch. A `void` unary expression suppresses the floating Promise no matter what its parent is. If the user has explicitly configured `ignoreVoid: false` then they don't want that suppressing.

I can see a valid use case of a project migrating from a `void`-heavy style and being surprised that old `void`-heavy code isn't linted in this way. Maybe the project used to use `void` a lot in general, and/or maybe they used to use `allowVoid: true`?

My vote is in favor of this being a bug. But, admittedly, it is a pretty rare one. Adding `evaluating community engagement` to make sure we keep it open for a while.

**Comment by bradzacher** [comment]
> A void unary expression suppresses the floating Promise no matter what its parent is. If the user has explicitly configured ignoreVoid: false then they don't want that suppressing.

The only parent the rule checks is `ExpressionStatement` - all other parents are not checked by the rule.

So why would the rule look at other, non-`ExpressionStatement` locations for a `void` operator AND enforce the argument isn't a promise? To me that's outside the scope of the rule.

**Comment by kirkwaiblinger** [comment]
Just a thought, you can also use `no-restricted-syntax` and ban specifically `return void` expressions. ([playground link](https://typescript-eslint.io/play/#ts=5.4.3&fileType=.ts&code=MYewdgzgLgBAhhAnmYAxAriqBLcMC88SKMAFAJQEB8MACgE4gC22EApgHT1sBWbwUUgCIQIAA4Qh5ANwAoWaEiwAZgEYCZSvhoBvWTBjco6emBgA3ENgAmRZGkwDcYCnIC%2B8xdBjKATBopqGD0DL1gADw1LGzsUDCxnV1kPBXBvZQBmAK1dfQsrWwR7eKdwJI8gA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oDN4OBDfMwDmtYtA4BbSshTowAbXDYciaBOiQANMpVYV2SJWGdoiAGodKAE3nd%2B8WbuwBfZwF0dKvEVLIK1HQMzGyctNLIsLLWYhIRchiQahrazpBhZsj4VGT4iDHIhCz8AB7yCknqHJpamGDOOLJIudXykABKiPiw0EwAyviCiJKILGAAfGAAqkz80IQAoiXiKMiUHEwKHKTQgtUAvAA6kABuVtbH7qkGUCPIyPzCiG0A7gAWhGAvHAjWYIQ-MCIE5qMDWDhgfBvGQAfjAACkovgwFFEGB%2BGBZgBrfJgAAGZm6vQA3HiwMwsoh%2BLYGmAXO5lG4XEA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)) The selector you'd want is `ReturnStatement > UnaryExpression[operator=\"void\"]` (You can always toss in `ThrowStatement` and `YieldExpression` too for completeness... keep going with this, though, and eventually you'll just end up at Brad's original suggestion of `:not(ExpressionStatement) > UnaryExpression[operator = "void"]`)

**Comment by kirkwaiblinger** [comment]
> > A void unary expression suppresses the floating Promise no matter what its parent is. If the user has explicitly configured ignoreVoid: false then they don't want that suppressing.
> 
> The only parent the rule checks is `ExpressionStatement` - all other parents are not checked by the rule.
> 
> So why would the rule look at other, non-`ExpressionStatement` locations for a `void` operator AND enforce the argument isn't a promise? To me that's outside the scope of the rule.

_mayyybe_ within scope for `no-misused-promises` though?? (I still think a blanket ban on the `void` operator is still a better solution anyways, though)

**Comment by Josh-Cena** [comment]
If you want to ban `void` except in expression statements, you can just use `"no-void": ["error", { allowAsStatement: true }]`. Otherwise I think `void promise` is not any different from `typeof promise`, etc.

I agree with every word in the last comment of @kirkwaiblinger.

**Comment by bradzacher** [comment]
5 months later and this request has received 1 community reactions.
As per our [workflow guidelines](https://typescript-eslint.io/maintenance/issues#community-engagement-evaluation) - we are taking this as signal that this check is not important to the broader community and are thus rejecting the proposal. Thanks for filing!
