### ISSUE TITLE
Enhancement: [@typescript-eslint/member-ordering] Support AST selectors to OrderConfig

### ISSUE THREAD

**Issue by DerZyklop** [typescript-eslint/typescript-eslint#8791]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/member-ordering/

### Description

Lets take Angular as an example, but there might be other cases where this is usefull.

It is (or was) a core idea of Angular to use decorators heavily on e.g. components for `@Input()`, `@Output()`, etc. 

I love(d) `@typescript-eslint/member-ordering` to enforce to have all decorated properties of an Angular Component (`@Input()`, `@Output()`, etc.) to be on top, then constructor, then other stuff. You get the idea. Config was like this:

```json
	"@typescript-eslint/member-ordering": [
		"error",
		{
			"default": [
				["decorated-field", "decorated-get", "decorated-set"],
				["decorated-method", "decorated-field"],
				"constructor"
			]
		}
	],
```

Now Angular did a huge mind-shift and they are using signals. Which turns 
`@Input() headline ?: string;` into 
`headline : input<string>()`.

With this syntax change, enforcing to have inputs and outputs at the top gets impossible with `member-ordering`. This brought me to the idea that if `member-ordering` would support `AST selectors` like [no-restricted-syntax](https://eslint.org/docs/latest/rules/no-restricted-syntax) does it, then `member-ordering` would provide every advanced setup and would still be independent of such library design decisions like Angular did.

So a config could look like this: 

```json
	"@typescript-eslint/member-ordering": [
		"error",
		{
			"default": [
				"PropertyDefinition … <<AST to get  the input assignment here>>",
				"PropertyDefinition … <<AST to get  the output/model assignment here>>",
				"constructor"
			]
		}
	],
```

### Fail

```TypeScript
class MyComponent {
  constructor() {}
  onClick : model<boolean>()
  headline : input<string>()
}
```

### Pass

```TypeScript
class MyComponent {
  headline : input<string>()
  onClick : model<boolean>()
  constructor() {}
}
```

**Comment by JoshuaKGoldberg** [comment]
"Good" timing! Per #8792, we're feature freezing this rule. It's reached the point of complexity where we're having a hard time justifying working on it. 

If you'd like to see this option happen, I'd encourage you to add it to a community project such as [eslint.style](https://eslint.style) or [eslint-plugin-perfectionist](https://github.com/azat-io/eslint-plugin-perfectionist). Cheers! 💙

**Comment by karlhorky** [comment]
I also mentioned this just now over in my question to the ESLint Stylistic maintainers about potentially migrating this rule to ESLint Stylistic:

- https://github.com/typescript-eslint/typescript-eslint/issues/8792#issuecomment-2025344673
