### ISSUE TITLE
Bug: Parsing error: ESLint was configured to run on  <file>  using `parserOptions.project`

### ISSUE THREAD

**Issue by kuba-orlik** [typescript-eslint/typescript-eslint#8804]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

Eslint refuses to lint one of my files in the repository. It lints other files without a problem, just has a problem with one particular one. It throws this error:

```
/tmp/typescript-eslint-repro/src/back/routes/common/navbar.ts
  0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/src/back/routes/common/navbar.ts` using `parserOptions.project`: 
- <tsconfigRootDir>/tsconfig.json
- <tsconfigRootDir>/tsconfig-back.json
However, none of those TSConfigs include this file. Either:
- Change ESLint's list of included files to not include this file
- Change one of those TSConfigs to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file
```

the `src/back/routes/common/navbar.ts` file is imported from within `src/back/html.ts` file. If I edit html.ts to not import the navbar.ts file, then eslint lints navbar.ts without throwing that error - which leads me to believe that in this case the error message is wrong and it's not an issue with what is and what isn't included in tsconfig.

### Reproduction Repository Link

https://github.com/kuba-orlik/typescript-eslint-repro.git

### Repro Steps

1) `git clone https://github.com/kuba-orlik/typescript-eslint-repro.git`
2) `cd typescript-eslint-repro`
3) `npm install`
4) `npx eslint src/back/routes/common/navbar.ts`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `7.4.0` |
| `@typescript-eslint/parser`            | `7.4.0` |
| `@typescript-eslint/scope-manager`     | `7.4.0 |
| `@typescript-eslint/typescript-estree` | `7.4.0 |
| `@typescript-eslint/type-utils`        | `7.4.0` |
| `@typescript-eslint/utils`             | `7.4.0` |
| `TypeScript`                           | `4.9.5` |
| `ESLint`                               | `8.57.0` |
| `node`                                 | `21.6.2` |

**Comment by bradzacher** [comment]
If I had to guess - it's due to you using `tsconfig.json` instead of `tsconfig.frontend.json`.

We don't support project references, so we aren't loading the referenced tsconfigs automatically. And then because the tsconfig includes no other config TS does some odd things sometimes.

**Comment by JoshuaKGoldberg** [comment]
> project references

Indeed. If you want project references, use the `projectService` option stabilized in v8: https://typescript-eslint.io/blog/announcing-typescript-eslint-v8-beta#project-service.

Thanks for filing!
