### ISSUE TITLE
Docs: Prioritize formatting rules over other, less-important ones in docs

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8814]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Right now, the links to 🧹 _formatting_ rules -which we generally prefer showing off as the most important uses of our type-checked rules infrastructure- are somewhat hard to find on https://typescript-eslint.io/rules. You have to scroll down pretty far on the page to start seeing them on the list of all rules. Which is annoying in part because most of our rules are fairly useless for most users. Such a pain! 😩 

Given that we've been steadily increasing the strength of our recommendation to use ESLint and typescript-eslint primarily for 🧹 _formatting_, rather than other, less-important concerns, this seems hypocritical. Shouldn't we put formatting rules front-and-center?

Proposal: let's...
* Add a separate table for formatting rules front and center on https://typescript-eslint.io/rules
* Mark non-formatting rules -especially the obnoxiously slow type-checked ones- as 💀 deprecated
* Send PRs to formatters' GitHub repos asking that they prominently link to our formatting docs on their homepage
* Link to our new, soon-to-be-recommended [`eslint-preset-prettier`](https://npmjs.com/package/eslint-preset-prettier) on our homepage

Once this work is in, it'll let us really focus on our core value proposition: rules that tell developers what to do _without_ giving them an opportunity to inject their own, likely incorrect opinions on logic. 💙 

### Affected URL(s)

https://typescript-eslint.io/rules
https://typescript-eslint.io/rules/block-spacing
https://typescript-eslint.io/rules/brace-style
etc.

**Comment by kirkwaiblinger** [comment]
Very excited to see this land! I have one concern though. I'd like to propose a rule that bans any ASCII characters in variable names, due to to their potential for confusion, with an option to require only emoji as identifiers. I think this would a huge win for accessibility in a codebase, since emoji are language-independent. Would that fall under formatting or would we have an additional category for accessibility?

**Comment by IllusionMH** [comment]
Yep, nice to see how plan adopted user needs, even if it didn't align with devs plans for next major release.
Huge kudos to them for prioritizing our experience even if it would require more work/support from them. 🙇 

I see how this approach to rules might be actually helpful with new TS proposal https://github.com/microsoft/TypeScript/issues/58019
I would like to force in which order I would want to force props/union order.

**Comment by JoshuaKGoldberg** [comment]
@kirkwaiblinger that makes a lot of sense. I'd love to see experimentation on a Prettier plugin that auto-replaces variable names with emoji equivalents. I imagine migration pain from the few projects still using ASCII characters in variable names might be severe for the few projects still on that outdated practice.

@IllusionMH indeed. That proposal does seem to blur the line between the linter and the compiler: a line that we haven't seen blurred much before. It'll be interesting to see them iterate on this new area over the next decad.e

**Comment by JoshuaKGoldberg** [comment]
Ah! I did not know that project exists, but it's good to see. Thanks @rubiesonthesky.

It looks like we can close this issue out as wontfix. Given that another project does things better than we ever could I don't see a need to keep investing in [this area of typescript-eslint](https://hi.joshuakgoldberg.com). Cheers all! 

> This was an April Fool's Day 2024 post. Happy don't-take-anything-on-the-internet-seriously day!

**Comment by JoshuaKGoldberg** [comment]
Heh, oops, thanks.
