### ISSUE TITLE
Docs: Mention stylistic(TypeChecked) at end of 'getting started' docs?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8823]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I realized today that users who go through our basic 'getting started' docs and nothing else will never see a mention of the stylistic & stylisticTypeChecked preset configs. They might see it if they look at the rules docs page or individual rules, but that may be long after they consider their ESLint setup finished. This is probably a big part of why so few users in the wild enable the stylistic preset configs.

Proposal: let's add a section to the bottom of each of our 'getting started' guides mentioning the stylistic configs? The section can phrase it as an optional nice-to-have.

### Affected URL(s)

https://typescript-eslint.io/getting-started
https://typescript-eslint.io/getting-started/legacy-eslint-setup
https://typescript-eslint.io/getting-started/typed-linting

**Comment by bradzacher** [comment]
We don't promote any configs other than the recommended ones in the getting started guide.
We used to!!! But then we made the change to further simplify the getting started guide to try and streamline the setup experience.

I think there's definitely scope for an "advanced" section where we suggest some other best practices beyond the most basic ones (eg we recommend these configs or plugins and here's how to set them up).
