### ISSUE TITLE
Docs: The configuration value for "allowFunctionsWithoutTypeParameters" parameter is incorrect in the explicit-function-return-type rule. 

### ISSUE THREAD

**Issue by ToruKiyono** [typescript-eslint/typescript-eslint#8870]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

The correct value should be false instead of true.

like this: 
 Examples of code for this rule with { allowFunctionsWithoutTypeParameters: false }

### Affected URL(s)

https://typescript-eslint.io/rules/explicit-function-return-type

**Comment by auvred** [comment]
`false` is the default value for `allowFunctionsWithoutTypeParameters`. These examples show how the rule will behave with `allowFunctionsWithoutTypeParameters` enabled.

I don't understand why we should change it to `false` in these examples. Could you please elaborate on this?

**Comment by Josh-Cena** [comment]
Current text is correct.
