### ISSUE TITLE
Repo: type mismatch with `ESLint.Linter.FlatConfig`

### ISSUE THREAD

**Issue by juliusmarminge** [typescript-eslint/typescript-eslint#8877]
### Suggestion

> Wasn't sure where to post this, this felt like the "closest" match out of all the issue templates

There are some inconsistencies with your types compared to ESLint's:

### tseslint types

![CleanShot 2024-04-07 at 23 29 44](https://github.com/typescript-eslint/typescript-eslint/assets/51714798/cba74e6d-daa9-4225-949f-73215f004451)

### eslint types

![CleanShot 2024-04-07 at 23 30 23](https://github.com/typescript-eslint/typescript-eslint/assets/51714798/65a9894e-d7af-41f8-9697-26902d9303b9)

### resulting type mismatch:

![CleanShot 2024-04-07 at 23 27 48](https://github.com/typescript-eslint/typescript-eslint/assets/51714798/5fe47322-2e42-4f43-aa66-d3200db834b7)

## Suggestion

Remove the `Partial` from `tseslint.SharedConfig.RulesRecord`

**Comment by bradzacher** [comment]
What's the usecase that you have that is failing?
We are intentionally not compatible with the `@types/eslint` types in many places because the types have different philosophies.

You could point to any number of places that the types diverge and say "fix it" but without a motivating usecase we aren't going to change it.

Please help us understand your usecase with some code sample(s) that are currently broken.

**Comment by juliusmarminge** [comment]
I tried writing my config like this:

```ts
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";

/** @type {import("eslint").Linter.FlatConfig[]} */
export default [
  {
    ignores: [
      "**/*.config.js",
      "**/*.config.cjs",
      "**/.eslintrc.cjs",
      ".next",
      "dist",
      "pnpm-lock.yaml",
    ],
  },
  {
    files: ["**/*.js", "**/*.ts", "**/*.tsx"],
    rules: eslint.configs.recommended.rules,
  },
  ...[...tseslint.configs.recommended].map((conf) => ({
    files: ["**/*.js", "**/*.ts", "**/*.tsx"],
    rules: conf.rules ?? {}, // <-- this type-mismatches
  })),
  {
    languageOptions: {
      parserOptions: {
        project: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
];
```

**Comment by juliusmarminge** [comment]
Sure, I could do:

```ts
/** @type {import('typescript-eslint').Config} */
export default [
  ...
]
```
instead, but to me atleast i feel like i wanna type this using ESLint since tseslint is just a part of the config?

**Comment by bradzacher** [comment]
As per [our docs](https://typescript-eslint.io/packages/typescript-eslint#usage) we suggest not using the ESLint types for your config.

We have found many cases where the `@types/eslint` types are overly restrictive and can cause type errors where things should work fine. They have no tests to ensure compatibility with the ecosystem.

OTOH our types are intended to be more forgiving and we have integration tests in place to ensure we can accept all manner of plugins and parsers with many different tsconfigs.

**Comment by bradzacher** [comment]
As an example you could simplify your config with our tooling

```js
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      // some globally ignored files
      "pnpm-lock.yaml",
    ],
  },
  {
    files: ["**/*.js", "**/*.ts", "**/*.tsx"],
    extends: [eslint.configs.recommended],
  },
  {
    files: ["**/*.js", "**/*.ts", "**/*.tsx"],
    extends: [
      ...tseslint.configs.recommended,
      ...tseslint.configs.recommendedTypeChecked,
    ],
  }, 
  {
    languageOptions: {
      parserOptions: {
        project: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
); 
```
