### ISSUE TITLE
Bug: [member-ordering] getter signature matches "method" instead of "get"

### ISSUE THREAD

**Issue by rapPayne** [typescript-eslint/typescript-eslint#8890]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.3&fileType=.tsx&code=FASwdgLgpgTgZgQwMZQAQDED2nUG9gGqoDmUEqAzhAhAK4UDCmAJlABQCUAXBtgNyFUUAB4AHKEggBlanUYsoAFUwAhdlRr0mrHlkzdUAN0whmA4AF8gA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AW0XYCNFpaA9tAAmfZgHN0YANrhsOPtCGQANHPlZ52SKIBmAQwT4pmrds48%2BAFRIopss2cjFY3RmVrJ8%2B-JQ%2B7KRHhhVXVHHGIlfEQyaOFPb19-QODQ8PlnKgA3H0QEnz9aAKCQtXTtAGJIyhzo-KSilNKw8OdXd1pRMiFc%2BOLUsvKoSIFo2MR4rp64xpK0ocya3M6Y6YnZgZbHNrdC5i99JjI8-uah4aiYmf3vI5Om%2BfLF2rybw%2BONs4Wq7OW3u8%2Bj3SOw6%2Bm4Xmg%2BligMGTxGYxmYIhULopyBrRcu2Sc1hwPhV3WaNxGN%2BdSJWycPyWZIexO2Bwa5POkH%2BHyZCyR%2BEh0PZTymkJmvOBQtaDL2TEovn0jAAXgUBEx0dtMR1ukwIbBYso6U58eN4mqNVroErdaS8oauZr8NqKVpIJa4MbTfbkJRxEwfLBoIgXRkyNL4J53Z78N7fTr7SrCmKPFDjshkLbmXqZrHaPGUEmTZGMtUXvVCpnE8nvvnluni9m-dpox5%2Bb0M2QE9Xc7XLvqVt0Besq6W4eau2t4n2c3a8%2B1xQcAaOaxEO9d1bcPrO2-Pqa8l%2B88qvx5Vy3VWTvm1n%2B3jJ3HwVyUU2W2eSaMCSOr9y6LuUxfb6exymF72TyWP4LAex53kBTxUgW74LJWAGtnuOBHl%2BgFzlAnKvsh8HMg2iJwfe2zQXCn7puIiDGGuFyPp2JFkahzwVokhSkeRCFQJBDEFB4zF0XWQ49vE3EUZkVEzDh6yCax9F1GJAm0UJvFIRJv4iesilyZJIG0GpLHMuxh5bgCSnAZ%2B6E3kZA4qc%2ByLQuZ55YrQtkPgi4nqb%2BG4Oa5ZaDo59KMVxnlPNpdGmTZAXAjJHk6QsPm6sRfmeGFTlPoWHjIIlyqDumaVRRBmlZelsX2RF2U8X%2BkyrPxCU5Xig7FQVUafkhJXyWVWkGR8zUaYOTX1RkembtOHW9bWJkvjenXKc5VnXtCE3GfZc0WVNVWle5i3Av1K1Cfl1WtD1u0EWNs3DTgdUHU460YnFnG0Jw%2BAABYCF8S3Jemd2Pc9NVrfF71PXRm1vWRH08Z%2BEW-Z9SWdmDQN-S17nQw9sMaY17V5ODpWWW1g1ozDEMZe5SHo0Jm2E7jIP2SFdBE11mOU7dZPyZ%2B1OTclzPAYObO5RzDOSYDiN404pP88FR1Uzz2EVY26OsawrCQNL5QALptpAQiiCaGCQNKxD3WCZF%2BIGhC0AGaVY4g6qSjUvp2gAvlsdvyIrch2zbQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
interface Foo {


  get statusCode(): Foo;

  expectStatusCodeToBe(statusCode: Foo): void;

}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/member-ordering": [
      "error",
      {
        "default": {
          "memberTypes": [
            "public-static-field",
            "protected-static-field",
            "private-static-field",
            "#private-static-field",
            "public-decorated-field",
            "protected-decorated-field",
            "private-decorated-field",
            "public-instance-field",
            "protected-instance-field",
            "private-instance-field",
            "#private-instance-field",
            "public-abstract-field",
            "protected-abstract-field",
            "public-field",
            "protected-field",
            "private-field",
            "#private-field",
            "static-field",
            "instance-field",
            "abstract-field",
            "decorated-field",
            "field",
            "static-initialization",
            "public-constructor",
            "protected-constructor",
            "private-constructor",
            "constructor",
            "signature",
            "call-signature",
            "public-static-accessor",
            "protected-static-accessor",
            "private-static-accessor",
            "#private-static-accessor",
            "public-decorated-accessor",
            "protected-decorated-accessor",
            "private-decorated-accessor",
            "public-instance-accessor",
            "protected-instance-accessor",
            "private-instance-accessor",
            "#private-instance-accessor",
            "public-abstract-accessor",
            "protected-abstract-accessor",
            "public-accessor",
            "protected-accessor",
            "private-accessor",
            "#private-accessor",
            "static-accessor",
            "instance-accessor",
            "abstract-accessor",
            "decorated-accessor",
            "accessor",
            "public-static-get",
            "protected-static-get",
            "private-static-get",
            "#private-static-get",
            "public-decorated-get",
            "protected-decorated-get",
            "private-decorated-get",
            "public-instance-get",
            "protected-instance-get",
            "private-instance-get",
            "#private-instance-get",
            "public-abstract-get",
            "protected-abstract-get",
            "public-get",
            "protected-get",
            "private-get",
            "#private-get",
            "static-get",
            "instance-get",
            "abstract-get",
            "decorated-get",
            "get",
            "public-static-set",
            "protected-static-set",
            "private-static-set",
            "#private-static-set",
            "public-decorated-set",
            "protected-decorated-set",
            "private-decorated-set",
            "public-instance-set",
            "protected-instance-set",
            "private-instance-set",
            "#private-instance-set",
            "public-abstract-set",
            "protected-abstract-set",
            "public-set",
            "protected-set",
            "private-set",
            "#private-set",
            "static-set",
            "instance-set",
            "abstract-set",
            "decorated-set",
            "set",
            "public-static-method",
            "protected-static-method",
            "private-static-method",
            "#private-static-method",
            "public-decorated-method",
            "protected-decorated-method",
            "private-decorated-method",
            "public-instance-method",
            "protected-instance-method",
            "private-instance-method",
            "#private-instance-method",
            "public-abstract-method",
            "protected-abstract-method",
            "public-method",
            "protected-method",
            "private-method",
            "#private-method",
            "static-method",
            "instance-method",
            "abstract-method",
            "decorated-method"
            //"method"
          ],
          "order": "alphabetically-case-insensitive"
        }
      }
    ]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

I expected the sort ordering to be fine in the code sample with the configuration as shown with or without the catch-all "method" as the last entry in the list.

### Actual Result

The sort ordering is fine with "method" removed or commented out. But with "method" present, the sort ordering is erroneously flagged as in error.

### Additional Info

From this StackOverflow question: https://stackoverflow.com/questions/78228459/typescript-eslint-member-ordering-error-seems-incorrect

**Comment by Josh-Cena** [comment]
Your config can be reduced to this:

```json
{
  "rules": {
    "@typescript-eslint/member-ordering": [
      "error",
      {
        "default": {
          "memberTypes": [
            "get",
            "method"
          ],
          "order": "alphabetically-case-insensitive"
        }
      }
    ]
  }
}
```

The problem is that getters are also `TSMethodSignature` nodes. We need to also use `kind` to discern them, like we do for `MethodDefinition`.
