### ISSUE TITLE
Enhancement: `RuleTesterConfig#parser` should be optional

### ISSUE THREAD

**Issue by JounQin** [typescript-eslint/typescript-eslint#8897]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

rule-tester

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

https://github.com/typescript-eslint/typescript-eslint/blob/2db8f4ef0fd3e7d50843a0972f39b10746c47978/packages/rule-tester/src/types/RuleTesterConfig.ts#L9-L13

I'm using `@typescript-eslint/rule-tester` in my own eslint plugin, the `parser` has a default value `'@typescript-eslint/parser'` so it should be optional.

**Comment by JoshuaKGoldberg** [comment]
Oh hey I just came across this - we ended up making it optional in v8. Sorry for not following up!

https://typescript-eslint.io/blog/announcing-typescript-eslint-v8#flat-configuration-ruletester
