### ISSUE TITLE
Repo: Examine precedences in getOperatorPrecedence and getWrappingFixer

### ISSUE THREAD

**Issue by kirkwaiblinger** [typescript-eslint/typescript-eslint#8909]
### Suggestion

@Josh-Cena 
This is a followup to https://github.com/typescript-eslint/typescript-eslint/pull/8826#issuecomment-2052495726 

There are discrepancies between the operator precedences in our code and [those on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence#table). We might want to take a closer look at some of them in order to ensure our code that depends on it works as expected.

**Comment by bradzacher** [comment]
The ordering should be the same as is used in TS itself IIRC. We copy pasted the code way back when.

**Comment by Josh-Cena** [comment]
I will take a look but I might come back deciding nothing should be done

**Comment by bradzacher** [comment]
Compare it with eslint core and TS.
This is a pretty common thing amongst our ecosystem and there are multiple copies.

**Comment by JoshuaKGoldberg** [comment]
Closing out as a general investigation. If anybody finds specific issues/PRs from it then those would be great!
