### ISSUE TITLE
Enhancement: Raise minimum versions of dependencies for v8

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8929]
## Overview

Our `v8` release is coming soon, and with that comes the regular expected bumping of our minimum dependency versions! 🎉 

To recap, raising the minimum versions of ESLint, Node, and TypeScript allows us to support fewer divergent sets of available APIs. That lets us work faster, ship less code, and take up fewer resources in our own builds. See https://typescript-eslint.io/users/dependency-versions for what version ranges we support.

This issue tracks raising the minimum versions of those three dependencies. Expecting roughly a ~summer 2024 release of v8:

* ESLint: will remain supporting v8
* Node: will remain supporting ^18 and >=20
* TypeScript: will bump from >=4.7 to >=4.8

Overall, this should be a pretty small change that doesn't cause much disruption. We can expect very few users to still require TypeScript 4.7.

Putting in `triage` so other folks on @typescript-eslint/triage-team can make sure I got this right. 😄 

💖

**Comment by bradzacher** [comment]
> Node: will remain supporting ^18 and >=20

We should probably bump this to match ESLint again.
https://github.com/eslint/eslint/blob/main/package.json#L178-L180

They're using `"^18.18.0 || ^20.9.0 || >=21.1.0` (ours is just `^18.18.0 || >=20.0.0`)
I'm fine not explicitly encoding the v21 range (we don't care about odd majors) - but the v20 should probs update, I think.

**Comment by bradzacher** [comment]
> ESLint: will remain supporting v8

It's currently at `^8.56.0`. This should probably bump to `^8.57.0`.
Really hit home that "You should update your deps".
This also is the absolute final release of v8 and included a few QOL things to help with v9 compat. Doesn't impact us but it's a nice-to-have for users (eg it helps vscode interop between the two).

**Comment by bradzacher** [comment]
@rubiesonthesky https://typescript-eslint.io/users/dependency-versions#typescript

**Comment by iambumblehead** [comment]
found this issue when attempting to update typescript-eslint in tandem with the newest eslint 9 https://eslint.org/blog/2024/04/eslint-v9.0.0-released/

It would be great if typescript-eslint would use current eslint 9 rather than older eslint 8 🙏

**Comment by bradzacher** [comment]
@iambumblehead unrelated. This is minimum versions. Not maximum versions.

You want the pinned issue https://github.com/typescript-eslint/typescript-eslint/issues/8211

**Comment by JoshuaKGoldberg** [comment]
#8973 was merged into `v8`. ✅
