### ISSUE TITLE
Bug: [prefer-readonly-parameter-types] Doesn't work on `DeepReadonly` from `ts-essentials`, `utility-types`, and `type-fest`

### ISSUE THREAD

**Issue by emily61268** [typescript-eslint/typescript-eslint#8932]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.3&fileType=.tsx&code=JYWwDg9gTgLgBAbzgEQKarAJVQQwCYQB2ANgJ5wC%2BcAZlBCHAOQwDOAtKiy6oTMDsRaMA3AChRqAB6RYNAK6EAxnyJwW9VGhAQAYguXAiAClFw1MUsU3ADRHFFIAuFOiy4CJUgB4AyhavINiqE9qQAdADC0KgAfAA0pnAhIKjOLDBQwIQA5gkAlM4AcjgpeL4aAOJ0cmAxiIlQqDByUIRqGgDyMAAWqFB6SsEmZmYIiSNJJalwAAZ4qNoA9AAkCMmoFDMJE2bqKR0ARgBWqMpp-ta2IQ5he6hVEDUA2usAutsjFIl5Yl9AA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
export function someDemoFunction(
    styleDictionary: DeepReadonly<StyleDictionary.Core>,
    name: string,
): Named<SomeGroup> {
  return someOtherFunction(
      {
        name: `demo/${name}`,
        someObject: styleDictionary.someGroup[name],
      }
  );
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/prefer-readonly-parameter-types": [
        "error",  
        { ignoreInferredTypes: true },
    ],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

There shouldn't be any `eslint` errors.

### Actual Result

Returns the following error for `styleDictionary: DeepReadonly<StyleDictionary.Core>`.
`34:3  error  Parameter should be a read only type  @typescript-eslint/prefer-readonly-parameter-types`

### Additional Info

Data types in `StyleDictionary.Core`: https://github.com/amzn/style-dictionary/blob/main/types/index.d.ts#L59
ts-essentials DeepReadonly: https://github.com/ts-essentials/ts-essentials/blob/master/lib/deep-readonly/index.ts
utility-types DeepReadonly: https://github.com/piotrwitek/utility-types/blob/master/src/mapped-types.ts#L407
type-fest ReadonlyDeep (recommended in [this issue](https://github.com/typescript-eslint/typescript-eslint/issues/7179)): https://github.com/sindresorhus/type-fest/blob/main/source/readonly-deep.d.ts

**Comment by emily61268** [comment]
Also, how do I check which in `StyleDictionary.Core` is not covered by `DeepReadonly`? Thanks.

**Comment by bradzacher** [comment]
Considering this requires a number of different dependencies to reproduce - could you please create an isolated reproduction repo with the required setup to reproduce?

Either that or recreate the exact state in the playground. Note that our playground does not download dependencies so it cannot be run off imports.

**Comment by emily61268** [comment]
I was able to pinpoint the one data type that might have caused this error, which is `RegExp` in [`Parser[]`](https://github.com/amzn/style-dictionary/blob/main/types/index.d.ts#L73), so I decided to use the [`allow` option](https://typescript-eslint.io/rules/prefer-readonly-parameter-types/#allow) that you mentioned in [this issue](https://github.com/typescript-eslint/typescript-eslint/issues/7179) to ignore `RegExp`. However, when I tried to update `.eslintrc.js` file to include `allow` config for `@typescript-eslint/prefer-readonly-parameter-types`, I kept getting the following error:
```
Oops! Something went wrong! :(

ESLint: 8.54.0

Error: .eslintrc.js#overrides[0]:
	Configuration for rule "@typescript-eslint/prefer-readonly-parameter-types" is invalid:
	Value {"allow":[{"from":"lib","name":"RegExp"}],"ignoreInferredTypes":true} should NOT have additional properties.

    at ConfigValidator.validateRuleOptions (/Volumes/workplace/SamplePackage/src/SamplePackage/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2039:23)
    at /Volumes/workplace/SamplePackage/src/SamplePackage/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2094:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (/Volumes/workplace/SamplePackage/src/SamplePackage/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2091:34)
    at ConfigValidator.validateConfigArray (/Volumes/workplace/SamplePackage/src/SamplePackage/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2217:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Volumes/workplace/SamplePackage/src/SamplePackage/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3974:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Volumes/workplace/SamplePackage/src/SamplePackage/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3780:21)
    at FileEnumerator._iterateFilesWithFile (/Volumes/workplace/SamplePackage/src/SamplePackage/node_modules/eslint/lib/cli-engine/file-enumerator.js:368:43)
    at FileEnumerator._iterateFiles (/Volumes/workplace/SamplePackage/src/SamplePackage/node_modules/eslint/lib/cli-engine/file-enumerator.js:349:25)
    at FileEnumerator.iterateFiles (/Volumes/workplace/SamplePackage/src/SamplePackage/node_modules/eslint/lib/cli-engine/file-enumerator.js:299:59)
```

Here's my config for ESLint: [Link](https://typescript-eslint.io/play/#ts=4.9.5&fileType=.ts&code=JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIAOU6hAXMgM5hSgDmA3LgL666iSyIoDqUchQtBz5kUCHAAm6EABsAnlQCuAIwoZ0TAuKkyFydGAAW0AAolyVGvSatcAenvIe6KAGtKyFRARwllFA1kYE84WVl0AHcISVwYJRAEMGAZZBgQAEYACjgoOnVMAEocO0dnVw9kCAA3CBBkSJN6oJDkEAhqGKp0AFsIRugUUGRjFDB5IQAaBuBjA1GoIgtoZI6rYHCvCHpkBBMENxi4hKSU%2BvSAJhy8ij4BIShi7GYgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0Wls4CGAEwD2TeIVrEB0AQFtE%2BXrSKlUGANrhsOXtBHRIAGm06sO7JAHx4IgO7owWixfMudkLvrmPIjAEbGpu44TPKIvgBKiADmAKIAHsSQwS4AvqnYALomIZCUMUwGiACSTDzQnEIAKiQojvhwiJkZOlnaGWlAA&tsconfig=&tokens=false) (Go to `eslintrc` tab)
Can you please help why it doesn't work? Thank you.

**Comment by bradzacher** [comment]
If you can't repro in the playground - then likely your versions don't align.
Given your error message says `ESLint: 8.54.0` - that means you're definitely not on ESLint's latest version (8.57.0 for v8 or 9.0.0 for v9) or our latest version (because the latest version explicitly has a dependency on at least ESLint v8.56.0).

So update your deps.

**Comment by emily61268** [comment]
I just updated the version to 8.57.0, still getting the same error.

**Comment by bradzacher** [comment]
Of eslint, sure, what about our packages?

**Comment by emily61268** [comment]
Thank you for pointing this out. I realized that our `ts-eslint` packages were still 5.59.0, and `allow` config was added after 6.0.0. I updated our `ts-eslint` packages to 7.7.0 and the issue was resolved. Thank you very much for your help!
