### ISSUE TITLE
Configs: Please add consistent-type-imports and consistent-type-exports for stylistic-type-checked

### ISSUE THREAD

**Issue by faner11** [typescript-eslint/typescript-eslint#8945]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

Your blog has explained it well. And these two rules can help us avoid many code conflicts.

https://typescript-eslint.io/blog/consistent-type-imports-and-exports-why-and-how/

### Impacted Configurations

consistent-type-imports and consistent-type-exports for stylistic-type-checked

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/discussions/8914
