### ISSUE TITLE
Docs: Shared Configs doesn't back-link to explanations of its code

### ISSUE THREAD

**Issue by runspired** [typescript-eslint/typescript-eslint#8959]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Currently, the documentation for flat config only shows how to dangerously apply global overrides instead of scoping rules to specific files:

```ts
export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
);
```

this means that to construct a safe configuration object a user must inspect the contents of each `tseslint.configs.*` and carefully merge them together into one object.

When doing so, the surprising thing I found is that tseslint does not currently support flat config correctly, as it still uses `extends`, the old parser and parserOptions setup, and uses strings to declare the parser and plugins neither of which is supported by eslint anymore:

current parser config: https://github.com/typescript-eslint/typescript-eslint/blob/9e0d9f5833d7216cec83bf0de3ae6829c2c8c16c/packages/eslint-plugin/src/configs/base.ts#L1-L7

which is used by the tseslint recommended config here: https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/recommended.ts

docs for new config: https://eslint.org/docs/latest/use/configure/parser#configure-a-custom-parser

### Affected URL(s)

https://typescript-eslint.io/users/configs/

**Comment by bradzacher** [comment]
> When doing so, the surprising thing I found is that tseslint does not currently support flat config correctly, as it still uses extends, the old parser and parserOptions setup, and uses strings to declare the parser and plugins neither of which is supported by eslint anymore:

You've gotten to the wrong place. Those are the legacy configs consumed within legacy configs only. The flat configs are accessed via the `typescript-eslint` package and are thus located within that package:

https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/typescript-eslint/src/configs

You'll notice that these are flat configs.

**Comment by bradzacher** [comment]
Did you check out the docs for the `typescript-eslint` package...?

https://typescript-eslint.io/packages/typescript-eslint#advanced-usage

**Comment by Josh-Cena** [comment]
The configs page should mention at least once where `tseslint` is imported from.
