### ISSUE TITLE
Repo: Incorporate void check into isNullableType?

### ISSUE THREAD

**Issue by kirkwaiblinger** [typescript-eslint/typescript-eslint#8974]
### Suggestion

In https://github.com/typescript-eslint/typescript-eslint/pull/8912/files#r1572612158, the `void` type is treated as a nullable type for the purposes of no-unnecessary-type-assertion, the same as `null` and `undefined` would be. Consider whether checking for the `void` type should be incorporated into the helper method `isNullableType` already used for checking for the `null` and `undefined` type, and assess whether its impact on other rules that use that helper is a correct behavior change or not.

**Comment by Josh-Cena** [comment]
`void` should be the same as `unknown` in all regards WRT to assignability
