### ISSUE TITLE
Bug(utils): deprecated helpers for ESLint context are not exported

### ISSUE THREAD

**Issue by auvred** [typescript-eslint/typescript-eslint#8975]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

utils

### Repro Code

```TypeScript
n/a
```

### ESLint Config

```javascript
n/a
```

### tsconfig

```jsonc
n/a
```

### Expected Result

To be able to use `ESLintUtils.getAncestors`, `ESLintUtils.getCwd` and others

### Actual Result

These functions are not exported

### Additional Info

See https://github.com/typescript-eslint/typescript-eslint/pull/8192#discussion_r1567409231:

The import was removed in https://github.com/typescript-eslint/typescript-eslint/pull/8377, but wasn't restored in https://github.com/typescript-eslint/typescript-eslint/pull/8399

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/utils`             | `7.7.1` |

**Comment by JoshuaKGoldberg** [comment]
👍 we can remove these in the `v8` branch as a followup.
