### ISSUE TITLE
Rule proposal: Prefer array.at(...) over array[...] as T | undefined

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8979]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Array index lookups aren't type-safe without the often-overly-strict [`noUncheckedIndexedAccess`](https://aka.ms/tsconfig#noUncheckedIndexedAccess): they give back `T`, not `T | undefined`. A lot of TS code that predates [`Array.prototype.at()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at) had to look like `[index] as T | undefined` instead of `.at(index)`. Example in our repo:

https://github.com/typescript-eslint/typescript-eslint/blob/eef257ba5fdd97f56d0d8e42445be6e4c6bb1b60/packages/eslint-plugin/src/rules/prefer-optional-chain-utils/analyzeChain.ts#L97

Now that we have `.at()`, I think it makes sense to enforce that: if an array index lookup uses a type assertion to add `| undefined`, it should use `.at` instead.

### Fail Cases

```TypeScript
declare const values: string[];
declare const index: number;

values[index] as string | undefined;
```

### Pass Cases

```TypeScript
declare const values: string[];
declare const index: number;

values.at(index);
```

### Additional Info

This is vaguely familiar to the idea of [`@typescript-eslint/no-unnecessary-type-assertion`](https://typescript-eslint.io/rules/no-unnecessary-type-assertion). But it includes a runtime change.

**Comment by kirkwaiblinger** [comment]
big +1 ❤️ 

- Should this also have have any options around prohibiting `.at(i)!`, or preferring `[i]` or `.at(i)` in general? I'm thinking not since `.at(i)!` is much more useful (e.g. with negative indices), and changing to `[i]` is a bigger, less safe logic change than `[i] as T | undefined` to `.at(i)`. And as you noted, `noUncheckedIndexAccess`, already exists.

- Due to the runtime changes, let's be sure to provide a suggested fix, and not an autofix?

**Comment by bradzacher** [comment]
We didn't used to use this cos we supported old nodejs versions!
Up until our v7 release our min was just `v16.0.0` - but `.at` was only added in `v16.6.0`
But now that our min is v18 we can safely use this everywhere!

**Comment by ronami** [comment]
Some thoughts:

Would it make sense to generalize it to prefer `array.at(...)` over `array[...]` when the contextual type is `T | undefined`?

Should these also fail too?

```ts
declare const values: string[];
declare const index: number;

// assignment with an explicit type annotation
const a: string | undefined = values[index];

// explicit return type annotation
function foo(): string | undefined {
  return values[index];
}

// function argument
bar(values[index]);

function bar(s: string | undefined) {}
```

**Comment by OlivierZal** [comment]
Couldn't there be possible conflicts to handle somehow (through an option?) with `prefer-destructuring`?

Someone would want both options – which are not related each to the other – so that:
```ts
const item = array[0]
```

could be fixed either with:
```ts
const [item] = array
```

or:

```ts
const item = array.at(0)
```

**Comment by bradzacher** [comment]
@OlivierZal no because `const [e] = arr` is unsafe - it does not encode the possible `undefined`.

I would expect that the eventual implementation should flag the destructuring code and suggest using `.at`

**Comment by OlivierZal** [comment]
Sounds good, the other way also makes it.

**Comment by Josh-Cena** [comment]
> no because `const [e] = arr` is unsafe - it does not encode the possible `undefined`.
> 
> I would expect that the eventual implementation should flag the destructuring code and suggest using `.at`

I don't think it would, in the same sence that `const x = arr[0]` continues to be allowed with this rule. Only `const x: string | undefined = arr[0]` is flagged.

**Comment by bradzacher** [comment]
Heh okay. I only quickly glanced at the top and missed that it requires annotation.
This by itself isnt a super useful rule - it's very niche as it is - I'd probably want a more broadly applicable rule to use `.at` everywhere.

**Comment by Josh-Cena** [comment]
noUncheckedIndexedAccess by itself is a very contentious option since you are essentially shutting out all C-style for loops. This lint rule, without the contextual type, is marginally better than forcing people to turn on NUIA: it only forces you to use a less optimized alternative and creates a (IMO unnecessary) distinction between arrays and index signatures.

**Comment by Josh-Cena** [comment]
You are searching for indexing with a constant, but most indexing happens with a variable. Adding that gives you 1.7k—idk if that's better.

**Comment by bradzacher** [comment]
Frame it this way:

If we turned on this rule across the entirety of the public GitHub TypeScript code -- likely billions of lines of code -- there would be just 1.7k reports for this rule.

I ran the grep (with `\w+` instead of `\d+` at your suggestion) on our internal codebase at Canva -- 90k TS files and there was just 12 results. 10 of those results are for object keys. So there was just 2 hits.

Seems like it's niche enough that the cost:value proposition just isn't there.

**Comment by kirkwaiblinger** [comment]
eh, yeah, i'm ok with this being closed

**Comment by bradzacher** [comment]
@JoshuaKGoldberg @Josh-Cena thoughts?

**Comment by JoshuaKGoldberg** [comment]
Yeah I'd prefer it to exist but don't feel passionately. The lack of applicable code or public excitement tampered my enthusiasm.

**Comment by Josh-Cena** [comment]
No strong feelings from me

**Comment by JoshuaKGoldberg** [comment]
rip
