### ISSUE TITLE
[recommended] remove function-return-type in recommended.json

### ISSUE THREAD

**Issue by xiaoxiangmoe** [typescript-eslint/typescript-eslint#898]
https://github.com/typescript-eslint/typescript-eslint/blob/92e2b31c77bae0c8c541ef2ae5032e1f0a37aae9/packages/eslint-plugin/src/configs/recommended.json#L11

A good practice in development is to minimize the number of writing types. Because the results of type inference are often more accurate than the type written by beginners. For example:

```ts
/**
 * function getNumberName(x: number): string
 */
function getNumberName(x: number): string {
    return isNaN(x) ? 'NaN' : x > 0 ? 'positive' : x < 0 ? 'negative' : 'zero'
}

/**
 * function getNumberNameInference(x: number): "NaN" | "positive" | "negative" | "zero"
 */
function getNumberNameInference(x: number) {
    return isNaN(x) ? 'NaN' : x > 0 ? 'positive' : x < 0 ? 'negative' : 'zero'
}
```

**Comment by bradzacher** [comment]
IMO your statement is wrong.

Explicitly writing types helps beginners learn how to write types, and teaches them about creating strict contracts, which is best practice.

We recommend that you provide explicit types for functions.
