### ISSUE TITLE
Docs: Temporarily link to ESLint 9 tracking issue on README.md

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8985]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Idea courtesy of @pfumagalli (https://twitter.com/ianosh/status/1782860718045605953) in the context of our ESLint 9 planning:

> ... for some reason it didn't return when I searched GitHub).
>
> Might be a good idea to link it from the main README as I'm sure it'll pop up from time to time!

+1, search doesn't always work. Even if all users were trained to instinctively check pinned issues, it's inconvenient for them to do so.

Proposal: let's add a little line to our README.md, like maybe:

> Using ESLint 9? See: [ESLint v9 Support](https://github.com/typescript-eslint/typescript-eslint/issues/8211)

### Affected URL(s)

https://github.com/typescript-eslint/typescript-eslint

Co-authored-by: @pfumagalli

**Comment by kirkwaiblinger** [comment]
Makes sense to me!
