### ISSUE TITLE
Bug: eslint ignores property is not taken into account, and it displays <ESLint was configured to run ... However, that TSConfig does not / none of those TSConfigs include this file>

### ISSUE THREAD

**Issue by HatemMn** [typescript-eslint/typescript-eslint#8986]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

This issue happens despite following all the instructions in the FAQ for [ESLint was configured to run ... However, that TSConfig does not / none of those TSConfigs include this file](https://typescript-eslint.io/troubleshooting/#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file).

After trying, I see the problem might be caused because I am using a monorepo. Simply clone and check out the project I have provided, it is simple and pretty straightforward to understand.

That file called `fileIdoNotWantToLint.ts` exists within the subproject myFirstApp but I do not want to get it linted and neither list it in my TsConfig.

If you read the eslint config you can see the whole folder should be ignored yet it is not.

Quite curiously, when I pass the **SAME** argument in the cli, everything works as expected !

Thank you !

### Reproduction Repository Link

https://github.com/HatemMn/tsLintIssue

### Repro Steps

1) clone the repo
2) `npm install`
3) `npm run lint`

At this step, you will get the error indicated in the README.md : 

```error
  1:69  error  'e' is defined but never used                            @typescript-eslint/no-unused-vars
  2:7   error  'custom_event' is never reassigned. Use 'const' instead  prefer-const

✖ 2 problems (2 errors, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

4) run `npm run lint:ok`

You should get no error

### Versions

| package                                | version |
| -------------------------------------- | ------- |
    "typescript": "^5.4.5",
    "eslint": "^8.57.0",
    "@eslint/js": "^9.1.1",
    "typescript-eslint": "^7.7.0"

**Comment by JoshuaKGoldberg** [comment]
This fixes it for me:

```diff
-    ignores: ["app/myFirstApp/nestedProject/"],
+    ignores: ["app/myFirstApp/nestedProject/src/fileIdoNotWantToLint.ts"],
```

I think your issue might be with ESLint core - perhaps a docs clarification/correction to be made somewhere? typescript-eslint doesn't do anything different with `ignores`. `tseslint.config` doesn't modify them.

Additionally, we're planning on switching the recommendation from `project` to `useProjectService` (today, [`EXPERIMENTAL_useProjectService`](https://typescript-eslint.io/packages/parser/#experimental_useprojectservice)) in our upcoming v8 major. Which also fixes the issue.

Closing as not on our end, but if you can pinpoint a bug in our source, we'd be happy to fix it. Thanks!

**Comment by JoshuaKGoldberg** [comment]
What I mean by "fixing" it is that you no longer get the big _ESLint was configured to run ..._ complaint. That complaint comes from this project, typescript-eslint.

We (typescript-eslint) act as "just" a set of extensions on top of [ESLint](https://eslint.org). If you're having issues with _ESLint_'s ignores then that'd be the ESLint project, not us.

> tslint

Sorry to nitpick you, but because a lot of people get confused by this: "tslint" refers to an old linter that was deprecated a few years back. https://typescript-eslint.io/troubleshooting/tslint. We try to avoid that name because a lot of folks have a hard time understanding the difference between it and typescript-eslint. Just a heads up. 🙂

**Comment by HatemMn** [comment]
Thank you @JoshuaKGoldberg  for the clear response, and sorry if my questions seemed repetitive as this my first time with eslint on a repository !

In order to make to make sure if the problem arises from ESLint or from typescript-eslint, I simply deleted typescript-eslint from my packages and reproduced the same project and everything was fine and worked like their documentation stated. You can checkout [the new branch I made to try this out](https://github.com/HatemMn/tsLintIssue/tree/no-typescript-eslint) or simply read the [config file](https://github.com/HatemMn/tsLintIssue/blob/no-typescript-eslint/eslint.config.js).

Due to this, I would maintain that it's not core Eslint that is causing this problem. What do you think ?

**Comment by HatemMn** [comment]
Thank you for considering this and for `npx @eslint/config-inspector` idea, I did not know about it. I will use it to investigate the problem with you guys

**Comment by HatemMn** [comment]
I have tried this solution on my main repository, and it worked !

While I honestly still do not understand the sentence 
>  _Otherwise ignores only skips the files from the specific config object_

the solution you have provided solves the problem, thank you very much guys ! the documentation was quite confusing. If you have time you can mention it in the FAQ for future reference :) ( [here]( Otherwise ignores only skips the files from the specific config object) ). I do admit however that the problem is eslint related indeed

**Comment by JoshuaKGoldberg** [comment]
A good docs suggestion for ESLint core. 🙂
