### ISSUE TITLE
Rule proposal: Warn when deprecated APIs are used (eslint-plugin-deprecation)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8988]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Re-opening #1223: being able to lint against usage of an API marked as `@deprecated` is a common request for TypeScript developers. It was a [TSLint rule](https://palantir.github.io/tslint/rules/deprecation) back in those days, and now is provided primarily by https://github.com/gund/eslint-plugin-deprecation. `eslint-plugin-deprecation` existing is why #1223 was closed by a docs change pointing folks externally.

But! Since then:

* We've stabilized as a repository and IMO this is an important + often-useful enough rule to justify being included (so folks don't have to use a third-party plugin)
* `eslint-plugin-deprecation` isn't 100% actively maintained, and has an [issue template notice indicating its maintainer doesn't have the bandwidth to ramp up on it & actively fix issues](https://github.com/gund/eslint-plugin-deprecation/blob/ae8ca953b1b4cc2021525089f56ede97613e9311/.github/ISSUE_TEMPLATE/issue-template.md#L16-L17)

Proposal: let's write a new implementation of a `deprecation` rule in this repo?

### Fail Cases

```TypeScript
/** @deprecated */
declare function v1(): unknown;

v1();
```

### Pass Cases

```TypeScript
declare function v2(): unknown;

v2();
```

### Additional Info

Note that the licensing here is tricky. https://github.com/gund/eslint-plugin-deprecation includes the following README.md note:

> This rule was originally ported from the [SonarJS repository](https://github.com/SonarSource/SonarJS).

...and is licensed under the GNU Lesser General Public License.

We need to be very sure that if this issue is accepted, any code added to our project is _not_ based on the GNU license, and is at most licensed under MIT. If this is accepted, I think a member of the typescript-eslint team should work on it.

Other references of related licensed rules are:

* https://github.com/import-js/eslint-plugin-import/blob/f77ceb679d59ced5d9a633123385470a9eea10d9/src/rules/no-deprecated.js (MIT)
* https://palantir.github.io/tslint/rules/deprecation (Apache-2.0)

cc @gund - you've done a great job for a while of keeping `eslint-plugin-deprecation` afloat ❤️. If you have any thoughts here, that'd be great.

**Comment by Zamiell** [comment]
Josh, I see that back in June, [you wanted a core TSESLint member to work on this](https://github.com/typescript-eslint/typescript-eslint/pull/9346#issuecomment-2165107470). However, in the meantime, TSESLint 9 is released, and `eslint-plugin-deprecation` is no longer compatible, so the need to have this rule working is much greater nowadays.

In order to try and help, I implemented a short and sweet version of the rule, coming in at only 63 lines:
https://github.com/Zamiell/typescript-eslint/commit/4c44df0f1bf8ea9a90aa1298abdb25463ce50422

My short version probably doesn't cover as many cases as the [298 line version created by luca-script](https://github.com/typescript-eslint/typescript-eslint/pull/9346/files), but it might be easier to maintain. Ultimately, I would just like some version the rule to exist in TSESLint sooner than later. Any thoughts?

**Comment by JoshuaKGoldberg** [comment]
Yeah this is really painful 😬 I've had to disable the rule in my own projects and know a lot of other folks have had to choose between sticking with typescript-eslint 8 / ESLint v7 or losing the rule too, as you're saying.

I actually started prototyping a reimplementation of the rule myself last week, but haven't had the time to get it to completion. The v8 release and other ESLint v9 compatibility work did a number on our schedules. https://github.com/typescript-eslint/typescript-eslint/pull/9783 has the work so far. It's on my todolist for _this week_ to try to clean it up and get it in review.

**Comment by ST-DDT** [comment]
> Yeah this is really painful 😬 I've had to disable the rule in my own projects and know a lot of other folks have had to choose between sticking with typescript-eslint 7 / ESLint 8 or losing the rule too, as you're saying.

You can enable the rule using the eslint compatibility package.

https://github.com/faker-js/faker/blob/bb1a73ca3a0ac3b3cf7a0ec25740bf6e872887ae/eslint.config.js#L138

````js
import { fixupPluginRules } from '@eslint/compat';
import eslintPluginDeprecation from 'eslint-plugin-deprecation';

...

  {
    plugins: {
      deprecation:
        // https://github.com/gund/eslint-plugin-deprecation/issues/78
        // @ts-expect-error: Types aren't matching, but it works
        fixupPluginRules(eslintPluginDeprecation),
    },
    rules: {
      'deprecation/deprecation': 'error',
    },
  },
````

**Comment by karlhorky** [comment]
@JoshuaKGoldberg thanks for `@typescript-eslint/no-deprecated` in [`typescript-eslint@8.3.0`](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.3.0), just migrated from [`eslint-plugin-deprecation`](https://www.npmjs.com/package/eslint-plugin-deprecation) and we've observed it working 👍 

Feels quite a bit slower than `eslint-plugin-deprecation` in the first runs, but maybe that's a temporary problem.

**Comment by BurningEnlightenment** [comment]
I'm a bit late to the party, but would it be possible to add an option to differentiate between libraries and user code? I find it very useful to flag and address deprecated APIs during the dependency upgrade cycle, but if it flags deprecated APIs from my own code base the moment I annotate them as such, I'd effectively need to go ahead and remove the API entirely. Should I open a feature request for this?

**Comment by bradzacher** [comment]
As per our contributing guidelines please open new issues for feature requests or bug reports. Or if you'd like to chat with us please visit our discord.

https://typescript-eslint.io/contributing/issues
