### ISSUE TITLE
Docs: contributing docs should say how to update rule doc code example snapshots

### ISSUE THREAD

**Issue by kirkwaiblinger** [typescript-eslint/typescript-eslint#8997]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Since https://github.com/typescript-eslint/typescript-eslint/issues/8382, we have snapshots of the eslint output on the code examples in the rule docs. However, our documentation doesn't say how to update those snapshots; if you change the code examples, the tests just fail locally and in CI. 

I've been using `yarn test -- -u` to get them to update, but I'm not actually sure if that's the recommended way. (or should they just automatically update when running `yarn test` like our other snapshots do, in which case we should just make a code change?)

Ping @auvred 

### Affected URL(s)

https://typescript-eslint.io/contributing/local-development#validating-changes

**Comment by auvred** [comment]
I'm +1 on adding some docs about snapshots and how to deal with them! In addition to ESLint output snapshots, we have rule schema snapshots. It would be nice to mention them as well.

https://github.com/typescript-eslint/typescript-eslint/tree/4858afde147a5ff6fa20ac1e73bc1c04692cef7a/packages/eslint-plugin/tests/schema-snapshots

---

Btw, we can also explain how to work with `ast-spec` snapshots. This may seem non-trivial!
There is a great explanation from Brad: https://github.com/typescript-eslint/typescript-eslint/pull/7649#discussion_r1388899988 :+1: 

> * within [this folder](https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/ast-spec/src/statement/ForInStatement) create a folder called `fixtures`.
> 
> * within `fixtures` create a `_error_` folder
> 
> * within `_error_` create a folder with a name for your case - for example maybe `using-initializer`?
> 
> * within that folder, create a file called `fixture.ts`
> 
> * within that file add your test code (eg `for(using foo in {});`)
> 
> * `cd packages/ast-spec && yarn test` to run the fixture tests and generate the necessary snapshots.

**Comment by JoshuaKGoldberg** [comment]
Yeah I `cd eslint-plugin; yarn test schemas -u` to update snapshots. +1 to docs
