### ISSUE TITLE
Repo: Test rule-tester in CI

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9005]
### Suggestion

Splitting out from @auvred's https://github.com/typescript-eslint/typescript-eslint/pull/8995#issuecomment-2078970122:

> Oh, looks like `rule-tester` is not tested in CI:
> 
> https://github.com/typescript-eslint/typescript-eslint/blob/4858afde147a5ff6fa20ac1e73bc1c04692cef7a/.github/workflows/ci.yml#L168-L182

Whoops! We should... definitely test this in CI, I'd think?

Co-authored-by: @auvred

**Comment by auvred** [comment]
Note: we should run both `test` and `test-eslint-base` scripts.

Because for `test-eslint-base` the different test runner is used (Mocha instead of Jest). This is done so because `tests/eslint-base/eslint-base.test.js` is copied from upstream.
