### ISSUE TITLE
Bug: object-shorthand loses type parameters when auto-fixing

### ISSUE THREAD

**Issue by aldeed** [typescript-eslint/typescript-eslint#9008]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.5&fileType=.ts&code=MYewdgzgLgBFCm0DyAjAVjAvDA3gKBhgFsBPAWXigAsQATALhgB4AVAPgAoR1GWBKXlja4ChGACdKAV3FgY3NAG5RAXwA0eFcqA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQPYCMArRAYwBcBaZAC12jOoEMA7AE3TAG1xsdFpodSABoevSI3gB3RgE9Uo3hCxKcjAG64AlqwCiADwAO8LSS1kASojKxozAIIDcU1BjJxEY7AF8vAXR5fbyA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
const testObj = {
  myMethod: <T>(obj: T): T => {
    return obj;
  },
};
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "object-shorthand": [
      "error",
      "always",
      { avoidExplicitReturnArrows: true },
    ],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

The correct fixed code is:

```ts
const testObj = {
  myMethod<T>(obj: T): T {
    return obj;
  },
};
```

### Actual Result

```ts
const testObj = {
  myMethod(obj: T): T {
    return obj;
  },
};
```

(`<T>` parameter is missing)

**Comment by kirkwaiblinger** [comment]
@aldeed Yep! Thanks for the report!

**Comment by kirkwaiblinger** [comment]
> @aldeed Yep! Thanks for the report!

Whoops! I spoke too soon. `object-shorthand` isn't actually a typescript-eslint rule (or corresponding extension rule), so this would be an issue to try to take up with eslint core first

**Comment by kirkwaiblinger** [comment]
Mentioning this issue may help you in making a report to eslint core: https://github.com/eslint/eslint/pull/12260 🙂
