### ISSUE TITLE
Enhancement: [strict-boolean-expressions] Check truthiness assertion functions

### ISSUE THREAD

**Issue by alecmev** [typescript-eslint/typescript-eslint#9009]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/strict-boolean-expressions/

### Description

For example, `ok` from `node:assert` has the following shape:

```ts
function ok(value: unknown, message?: string | Error): asserts value;
```

It appears that currently the rule just looks at `value`, sees `unknown`, and moves on. So it's possible to write this:

```ts
const foo: string | undefined = 'bar';
if (foo) ... // Error
ok(foo); // Fine
```

Instead, it would be nice if it also looked at the return type and took `asserts value` into account, treating it as `if (!value) throw`. There's more to `asserts` than just checking truthiness, but handling the simplest case (no `is`) would already go a long way, as that covers all `ok`-like assertion functions out there.

### Fail

```TypeScript
const foo: string | undefined = 'bar';
ok(foo);
```

### Pass

```TypeScript
const foo: string | undefined = 'bar';
ok(foo !== undefined);
```

**Comment by kirkwaiblinger** [comment]
I'm +0.5 to this, since I've run into this as well, and been annoyed by it. The +0.5 rather than +1 is due to the fact that it's an easy and obvious place to use an`eslint-disable` comment, since I can only imagine this coming up in the first place in isolated, conspicuous scenarios. 

We'll see what others think!

**Comment by bradzacher** [comment]
I'd never really thought about it like this.
I guess that `asserts foo` is defined by the type system to mean `if not foo then throw` - regardless of the underlying implementation of the assertion function.
And it looks like TS does essentially treat it like a boolean context where the code after the call is the "condition was true" branch.

It may be a bit weird for people to think of assertions like this but I think there's value in it.

**Comment by kirkwaiblinger** [comment]
Question - do we think that we should check this context analogously in `no-unnecessary-condition`? @bradzacher @alecmev 
(can spin off a new issue it warrants nontrivial discussion)

([playground](https://typescript-eslint.io/play/#ts=5.4.2&fileType=.tsx&code=GYVwdgxgLglg9mABAQwM6oKYCcoAoAeAXIuANZhwDuYAlMWpjqovogN4BQiiA9D4hlQAbGGCgBaACYxUyAEZCM4sBnwSRKxAAEoATwAOgiFhj6JgjVB6ooJ6OLlw4i5GHGr9WQanhhUXRBhgRFwAQnwadgDuKAALLCpEFUpEAFEsBKxcAHIGbFgEbJoAbgCAXw4KjggEG0RbEDjdAGVbUQBzRABeRGybEzB27NKgkIam1oH2yLZEKuraqBQhVDgAFSxG2Ja2we7e-o7hjjycXGQV9c2J3emODiA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRRE0aB2iQANOGx4ipZBWp0GzNsnxUydAEYcOSIU3oAPYtEHymqDJGWr12gC%2BIIFAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false))
```ts
function assert(x: unknown): asserts x {
  // eslint-disable-next-line @typescript-eslint/strict-boolean-expressions
  if (!x) {
    throw new Error('assertion');
  }
}

const truthyString = 'string';
if (truthyString) { }
    ~~~~~~~~~~~~

const alsoTruthyString = 'string';
assert(alsoTruthyString)
```

I'm of the opinion that we should, though it's less easy of a call to make than for the `strict-boolean-expressions` case, and I think it might warrant an option in that rule. In any case, we can dig into that further after seeing what people's initial impressions are.

**Comment by bradzacher** [comment]
Sounds like a valuable thing yeah.
Part of me thinks it might want an option for that rule though - I could see people using assertion functions to enforce "always true" invariants.

**Comment by kirkwaiblinger** [comment]
> Sounds like a valuable thing yeah. Part of me thinks it might want an option for that rule though - I could see people using assertion functions to enforce "always true" invariants.

Yep, that's exactly my reservation as well, having used assertions myself to defend against regressions due to types at runtime not matching their declared types.  Will file dedicated issue for that.

Do you think there ought to be an option for this rule as well?

**Comment by bradzacher** [comment]
nah this rule is straight-forward. It's not going to ban an assertion - just ensure you're using it strictly.
