### ISSUE TITLE
Enhancement(rule-tester): FlatRuleTester -> RuleTester

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9017]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

rule-tester

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Splitting out of #8211 -> #8969: this issue tracks any updates we'll need corresponding to https://github.com/eslint/eslint/pull/17922.

**Comment by favna** [comment]
Hi, I have a question about this issue. Is there any current way _without_ the changes that will be made for this issue to test a flat config custom typescript-eslint rule? At the moment when using `RuleTester` from `@typescript-eslint/rule-tester` v7.11.0 I get the error:

```
FAIL  tests/rules/no-discard-result.test.ts [ tests/rules/no-discard-result.test.ts ]
Error: This method cannot be used with flat config. Add your entries directly into the config array.
 ❯ assertEslintrcConfig ../../node_modules/eslint/lib/linter/linter.js:1256:15
 ❯ Linter.defineRule ../../node_modules/eslint/lib/linter/linter.js:2164:9
 ❯ RuleTester.run ../../node_modules/@typescript-eslint/rule-tester/src/RuleTester.ts:400:18
 ❯ tests/rules/no-discard-result.test.ts:15:13
     13| 
     14| describe('ESLint plugin result', () => {
     15|  ruleTester.run('no-discard-result', noDiscardResult, {
       |             ^
     16|   valid: [
     17|    {
```

This is for https://github.com/sapphiredev/utilities/blob/feat/update-to-eslint-v9-flat-config/packages/eslint-plugin-result/tests/rules/no-discard-result.test.ts

**Comment by bradzacher** [comment]
Nope! The way they designed the rule tester it is one or the other. Hence there is two rule tester classes. Our fork came from the legacy config version (before flat config existed) so it doesn't support flat config properties.

But regardless - the only difference is a few property names. The functionality is all the same.

**Comment by favna** [comment]
Turns out if I update to the v8 rc then my tests work again so I'll just patiently wait for the typescript-eslint team to finish their work. Looking forward to it, keep up the awesome work!

**Comment by azat-io** [comment]
The same problem:

```
Error: This method cannot be used with flat config. Add your entries directly into the config array.
```
