### ISSUE TITLE
Bug: "Too many files (>8) have matched the default project" error triggers on every file after 8

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [typescript-eslint/typescript-eslint#9032]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

Split out from https://github.com/typescript-eslint/typescript-eslint/pull/8925 as I realized you requested an issue. As the title says, this error seems to trigger for every file after the 8th. With 9 files I get the error once, with 10 files I get the error twice, etc.

### Reproduction Repository Link

https://github.com/ehoogeveen-medweb/glob-too-wide.git

### Repro Steps

1) clone the repo
2) `npm ci`
3) `npx eslint --ext ts .`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `typescript-eslint`     | `7.8.0` |
| `TypeScript`                           | `5.4.5` |
| `ESLint`                               | `8.57.0` |
| `node`                                 | `20.12.2` |

**Comment by ehoogeveen-medweb** [comment]
[Workaround](https://github.com/typescript-eslint/typescript-eslint/discussions/8030#discussioncomment-9276535): Set `parserOptions.EXPERIMENTAL_useProjectService.maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING`  to some huge value like `Infinity`.
```js
{
  parserOptions: {
    EXPERIMENTAL_useProjectService: {
      maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING: Infinity,
    },
  },
}
```
(but note that `Infinity` isn't supported by JSON so you'll need to use a real number like `1e10` in JSON-based configs)

**Comment by ehoogeveen-medweb** [comment]
I've updated the reproduction to `typescript-eslint` version `7.9.0` and set `maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING: 0` to simplify the reproduction.

**Comment by ehoogeveen-medweb** [comment]
Looking at the code, I think the problem might be here:
https://github.com/typescript-eslint/typescript-eslint/blob/77fc366aa03f3cee1ebcf91a10dc0be8b669520e/packages/typescript-estree/src/useProgramFromProjectService.ts#L86

It unconditionally does
```ts
  defaultProjectMatchedFiles.add(filePathAbsolute);
```
so every file will be considered as matching the default project. If I understand the code correctly, it should be checking against `opened.configFilename`:
```ts
  if (!opened.configFileName) {
    defaultProjectMatchedFiles.add(filePathAbsolute);
  }
```

I've tried adding that check locally and no longer get the warnings (but I haven't checked to see if files that *actually* don't have a project still trigger it).

**Comment by JoshuaKGoldberg** [comment]
@ehoogeveen-medweb excellent find, thanks for pointing this out! Are you up for sending a PR to fix this? 😁

**Comment by ehoogeveen-medweb** [comment]
Technically I think the old title was more accurate if my diagnosis is correct, as it's in-project files getting reported as out-of-project files 😁 

I'll try to put together a pull request.

**Comment by JoshuaKGoldberg** [comment]
Haha fair point!
