### ISSUE TITLE
Enhancement: [consistent-type-imports] option to only enable for internal dependencies

### ISSUE THREAD

**Issue by kuba-orlik** [typescript-eslint/typescript-eslint#9047]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/consistent-type-imports/

### Description

The largest benefit I see in the consistent-type-imports rule is decreasing the amount of cyclic dependencies in the generated code.

I propose to add a new option to the `consistent-type-imports` rule that would only enable the checks for internal dependencies (where import path starts with a `.`).

### Fail

```TypeScript
import Shape from "./shapes.js"
import Container from "containers"

function create(): Container<Shape> | null{
    return null;
}
```

### Pass

```TypeScript
import type Shape from "./shapes.js"
import Container from "containers"

function create(): Container<Shape> | null{
    return null;
}
```

**Comment by bradzacher** [comment]
Whats the motivation here? What benefit is there to just using it like this as opposed to just being consistent and treating all imports the same?

I don't see how there's broadly applicable value in being inconsistent and special casing this.

**Comment by kuba-orlik** [comment]
> Whats the motivation here? What benefit is there to just using it like this as opposed to just being consistent and treating all imports the same?

If the rule is enforced for all imports, then we get linter warnings on lines like

```ts
import {a,b,c,d} from "some-package";
```

If only some of those imports are for the type, and others for value, then we have to change it to

```ts
import type {b,d} from "some-package";
import {a,c} from "some-package";
```

That's extra work for our team that gives benefits less important (to us!) than what was the intention behind enabling this rule: decreasing cyclic dependencies across our codebase

**Comment by bradzacher** [comment]
> That's extra work for our team 

But the rule has an autofixer for all cases - so you just run `--fix` and it fixes everything. So it's the same amount of work if it reports on one or one thousand imports.

---

The rule isn't intended to do anything around cyclic dependencies. If you're looking to reduce cyclic deps there are separate rules for that.

---

I don't see any broad applicability here and the motivation does not align with the intent of the rule. Thus I am going to reject this.
