### ISSUE TITLE
Rule proposal: prefer querySelector generic vs type cast

### ISSUE THREAD

**Issue by bschlenk** [typescript-eslint/typescript-eslint#9058]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

https://github.com/typescript-eslint/typescript-eslint/issues/9007 was closed before I could comment there. I wasn't aware that `querySelector` took a generic argument. It'd be nice if there was a lint rule that caught

```
document.querySelector('something') as HTMLElement
```

and recommended changing it to

```
document.querySelector<HTMLElement>('something')
```

And maybe this could be done in a more generic way, possibly catching all functions that accept a generic but are being cast instead?

### Fail Cases

```TypeScript
document.querySelector('div') as HTMLDivElement
```

### Pass Cases

```TypeScript
document.querySelector<HTMLDivElement>('div')
```

### Additional Info

It would help with these duplicates if this was enabled in the recommended ruleset

https://github.com/typescript-eslint/typescript-eslint/issues/8388, https://github.com/typescript-eslint/typescript-eslint/issues/7207, https://github.com/typescript-eslint/typescript-eslint/issues/5808, https://github.com/typescript-eslint/typescript-eslint/issues/5359, https://github.com/typescript-eslint/typescript-eslint/issues/528

**Comment by Josh-Cena** [comment]
Doesn't `no-unnecessary-type-assertion` do exactly that? Why do we need a specific rule to report this pattern? (Note that even if we do, it would not be specific to `querySelector`, but functions with the signature `f<T>(...args): T` in general.)

I do think we should add this pattern to the docs, but I'm not sure why any new feature is needed.

**Comment by Josh-Cena** [comment]
Closing because this is exactly what `no-unnecessary-type-assertion` does. https://github.com/typescript-eslint/typescript-eslint/issues/6951 will improve the error message
