### ISSUE TITLE
Docs: broken anchor links in "This rule accepts the following options, and has more strict settings in the strict and strict-type-checked configs."

### ISSUE THREAD

**Issue by dandv** [typescript-eslint/typescript-eslint#9070]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

The anchor links under "strict" and "strict-type-checked" in "This rule accepts the following options, and has more strict settings in the [strict](https://typescript-eslint.io/users/configs#strict)) and [strict-type-checked](https://typescript-eslint.io/users/configs#strict-type-checked)) configs." are broken by a closed paren.

The issue seems to be [in this line](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/website/plugins/generated-rule-docs/insertions/insertNewRuleReferences.ts#L175).

### Affected URL(s)

Multiple e.g. https://typescript-eslint.io/rules/restrict-template-expressions/#options

**Comment by kirkwaiblinger** [comment]
Nice. Marked as accepted!
