### ISSUE TITLE
Base rule extension: [accessor-pairs]

### ISSUE THREAD

**Issue by paulyoung** [typescript-eslint/typescript-eslint#9072]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+base+rule+extension%22) and found none that match my proposal.
- [X] I have searched the [current extension rule list](https://typescript-eslint.io/rules/?=extension#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the base rule

https://eslint.org/docs/latest/rules/accessor-pairs

### Description

It's possible to define a setter without a getter, and have everything type check successfully as if the getter exists.

The code in [this playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAsiAKAnA9mKBeKBvAsAKCigEMAubfQwgIzNwMsIGMyrlkAbCIgOwBoLKAX371h+QQG58+RuyIBnebBABhOYvL0wiAJYA3IsGgB9ALYIUYMnCSoMmhqQcMoNZy6jMoAMyLt5ECIeYvSEIWFSeAIA9NFQAOYQwFDmtmAAFACULGycPM6xlIhJAK6I3FDAABY68gB0ZhaokYSFgtL0AcmplukG7CUQ1k1gme6VNfWNafb9gy1Q7XhLMsjc8t0gAJLrwDyM0JjcEADuymoK8lmRq+scEHXsyPHp5jsb+w89qHVEdVR1RiZCRAA) errors at runtime but still type checks to due an apparent soundness issue with the type system.

The `eslint/accessor-pairs` rule appears to address this but it doesn't work for `typescript-eslint`

### Fail

```TypeScript
class MyClass {
  private _myProp: boolean = false;

  set myProp(value: boolean) {
    this._myProp = value;
  }
}
```

### Pass

```TypeScript
class MyClass {
  private _myProp: boolean = false;

  get myProp(): boolean {
    return this._myProp;
  }

  set myProp(value: boolean) {
    this._myProp = value;
  }
}
```

**Comment by kirkwaiblinger** [comment]
Hi @paulyoung!

Wow, what a strange behavior that typescript would allow that!

> The eslint/accessor-pairs rule appears to address this but it doesn't work for typescript-eslint

Could you elaborate on what about that rule doesn't work? It seems to work for me in the [typescript-eslint playground](https://typescript-eslint.io/play/#ts=5.4.2&showAST=es&fileType=.tsx&code=C4TwDgpgBAsiAKAnA9mKBeKBvAUFKAhgFzZ75QBGJu55AxiRcsgDYQEB2ANGfgL49%2BPPgG4cOOiwIBnabBABhKbNL4wiAJYA3AsGgB9ALYIUYEnCSoMq8sRu0q92lAZQAZgRbSIg5wN5Q-vxiZAD0oVAA5hDAUMaWYAAUAJSMzGycNuHkiDEArogcUMAAFhrSAHRGJqhi%2BNl84vjesfGmiToseRDmNWDJTqXlVW1WmJ3ddYE4jRLIHNKtIACSC8CcdNCYHBAA7vJKMtIpIXTz0qwQFSzIkYnGq4sbV6NgFQQVFBV0ySJAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQIYGN8VkB7aAWgAdcBLaVDSRaaMycMAXxE6A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false).

**Comment by paulyoung** [comment]
@kirkwaiblinger I tried adding it to my `.eslintrc.js` and I still didn't get any errors.

**Comment by paulyoung** [comment]
It looks like upgrading `@typescript-eslint/eslint-plugin` may not have actually worked. I'll confirm and report back.

**Comment by paulyoung** [comment]
This worked once the upgrade succeeded. Sorry for the trouble!

**Comment by kirkwaiblinger** [comment]
@paulyoung Yay!
Not to worry. I learned something new today. 
Cheers!
