### ISSUE TITLE
Docs: Better Callouts for `all` / `strict` / `strict-type-checked` Config Stability

### ISSUE THREAD

**Issue by bachmacintosh** [typescript-eslint/typescript-eslint#9073]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Currently on the Shared Configs page, there is a small blurb near the top of the page that reads:

> With the exception of `all`, `strict`, and `strict-type-checked`, all configurations are considered "stable". Rule additions and removals are treated as breaking changes and will only be done in major version bumps.

However, when a user visits a rule (e.g. [no-dynamic-delete](https://typescript-eslint.io/rules/no-dynamic-delete) ), and clicks on the [link to the config and how to add it to their ESLint config](https://typescript-eslint.io/users/configs/#strict), they are taken past this blurb, and may never see it.

The CAUTIONs under the `strict` and `strict-type-checked` configs, as well as the WARNING under the `all` config, could be updated, or a new admonishment of some kind (ie a CAUTION or WARNING) could be added to each one, to say essentially the inverse of the blurb at the top, with text such as:

> This configuration is not considered "stable" under Semantic Versioning (SemVer); its enabled rules and/or their settings may change even outside of major version updates.

This would better call out their not being considered "stable," especially being under an admonishment instead of a blockquote blurb, and make the wording visible as soon as a user arrives at the config from a rule, instead of relying on their scrolling to the top of the page to get the information. Optionally, the blurb could be removed as well.

### Affected URL(s)

- Shared Configs: https://typescript-eslint.io/users/configs

**Comment by JoshuaKGoldberg** [comment]
FWIW I think this is a good idea. We probably don't need to spend more than a single line for each of the configs.
