### ISSUE TITLE
Docs: Quickstart guide should be clear on type: module not being a requirement

### ISSUE THREAD

**Issue by moltco** [typescript-eslint/typescript-eslint#9094]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Improve the getting-started/Quickstart guide to mention that package.json must have "type":"module" otherwise the example will fail with import statement not being supported

### Affected URL(s)

https://typescript-eslint.io/getting-started/

**Comment by bradzacher** [comment]
The reason we didn't specify this is because we treated it as assumed knowledge for using NodeJS.
I.e. if you want to use ESM you need to have `type: module` in your package.json - as has been the way with ESM support in NodeJS since its release.

My question here would be - do we need to tell people the constraints of NodeJS? Or are we okay to assume that people know "if you don't use ESM then you must translate this to CJS".

cc @typescript-eslint/triage-team thoughts?

---

With the release of eslint 8.57.0 we could update this guide to use `.mjs` (prior to minor 57 - it was not supported by eslint).

**Comment by auvred** [comment]
Personally I'm +1 on recommending using `.mjs` config file with small note that it requires ESLint >= 8.57.0.

Also see the related conversation on Discord: https://discord.com/channels/1026804805894672454/1207049165079846962/1213212499713728553

**Comment by kirkwaiblinger** [comment]
+1 on calling out explicitly, and mentioning .mjs option.

**Comment by molt2020** [comment]
I think it's important to mention +add external references. 

A lot of people are just setting up the dev environment and may not be familiar with intricacies of the various stack options and are just setting up the environment at that point. Most how-to's start with do yarn add my-package so it's fair to point out anything that a noob will need.

Aim for bullet proof instructions for idiot users like me! 🙂

**Comment by JoshuaKGoldberg** [comment]
Yeah, we need to be very careful to note that it's not a _requirement_ to use a module type.

**Comment by ericmorand** [comment]
@bradzacher this is not true:

> I.e. if you want to use ESM you need to have type: module in your package.json

I understand that you mention the `.mjs` extension later in your post, but for the sake of correctness, I think you should update your comment to "**I.e. if you want to execute a file ending by `.js` as ESM, one of the solution is to have type: module in your package.json**".

A lot (and I mean a looooot) of people are convinced that the `module` declaration is mandatory to execute ESM modules. I think it is our duty to make it clear, as often as possible, that it is not.
