### ISSUE TITLE
Issue with the subDependencies of typescript-eslint

### ISSUE THREAD

**Issue by rajanmiddha001** [typescript-eslint/typescript-eslint#9112]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-eslint

### Repro Code

```TypeScript
I started to install the packages 
eslint: 9.2.0 ,
typescript-eslint: 7.9.0
but it gives me an error Conflicting peer dependency: eslint@8.57.0 because typescript-eslint has eslint in the package.json with fixed version "8.57.0"  so it throws an error
```

### ESLint Config

```javascript
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";
import sonarjs from "eslint-plugin-sonarjs";


export default [
  {
    languageOptions: { 
      globals: globals.node 
    }
  },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  sonarjs.configs.recommended,
  {
    "rules": {
      "complexity": ["error", 7],
      "@typescript-eslint/no-explicit-any": ["off"]
    }
  }
];
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": { "*": ["types/*"] },
    "target": "ES2021",                          
    "module": "commonjs",                     
    "sourceRoot": "src",
    "outDir": "dist",
    "noImplicitAny": false,
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "declaration": false,
    "listFiles": false
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "test/**/*",
    ".vscode",
    ".serverless",
    ".git",
    "node_modules/**/*",
    "dist",
    ".eslintrc.js"
  ],
  "compileOnSave": true,
  "buildOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

### Expected Result

so it shouldn't fixed the eslint version to 8.57.0

### Actual Result

it restricted me to install the npm packages.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@eslint/js`        | `9.2.0` |
| `@typescript-eslint`             | `7.9.0` |
| `TypeScript`                           | `5.4.5` |
| `ESLint`                               | `9.2.0` |

![eslint error](https://github.com/typescript-eslint/typescript-eslint/assets/162436830/268a3424-a0db-457a-acee-4afff2f1f21c)
![typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/assets/162436830/fc9a450c-1c07-4228-8928-edc81ab9e26a)

**Comment by auvred** [comment]
You've provided screenshots of the `devDependencies` section of the root `package.json`.

The actual place where `eslint` dependency is declared is https://github.com/typescript-eslint/typescript-eslint/blob/165d8f7a0de7fefdc16658c1161773b1bd5f3a2a/packages/typescript-eslint/package.json#L54-L56

---

> * [x]  I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.

Please see _**pinned issue**_ https://github.com/typescript-eslint/typescript-eslint/issues/8211:

> We are not accepting issues against v9 until we have official support - so please do not file issues with crashes or bugs for now and please do not comment on this issue telling us about crashes.

---

If you want to try using `typescript-eslint` with `eslint@9`, you can use the `v8` alpha version - https://github.com/typescript-eslint/typescript-eslint/issues/8211#issuecomment-2106427365
