### ISSUE TITLE
Allow manually overriding forced project inclusion of 2.0.0

### ISSUE THREAD

**Issue by bbugh** [typescript-eslint/typescript-eslint#915]
The 2.0.0 parser is a great new feature, glad to hear that you sorted out the performance issues in #389. 🌟 This project must be a huge undertaking and you're doing an awesome job with it.

**What code were you trying to parse?**

A file outside of my project files, manually.

For example, just now I wanted to lint my `.eslintrc.js` config one time. There doesn't seem to be a way to do that now. 

> ```
> yarn eslint --fix .eslintrc.js --no-ignore
> ```

**What did you expect to happen?**

The linter correctly understood that I was linting files outside of my project, and allow it to lint without issue.

Is there a flag we can pass to say "yes I know this file is outside of my project but I want you to lint it anyway"? Perhaps `@typescript-eslint` can use eslint's ignore flags internally somehow? I don't have any need for a special linting `tsconfig.eslint.json`, just occasional one-time lints.

**What actually happened?**

I had to remove `project: './tsconfig.json',` from my `package.json`. That then requires me to remove `plugin:@typescript-eslint/recommended-requiring-type-checking` because of this 2.0.0 change. 

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.0.0` |
| `TypeScript`                | `3.5.3` |
| `ESLint`                    | `6.2.2` |
| `node`                      | `10.15.3` |
| `npm`                       | `6.4.1` |
| `yarn`                       | `1.17.3` |

**Comment by bradzacher** [comment]
Going to close this as there's nothing we can do about this as per the previous comment.
