### ISSUE TITLE
Enhancement: [no-useless-template-literals] Delete in v8

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9163]
## Overview

Following #8544 -> #8821: we _renamed_ `no-useless-template-literals` to `no-useless-template-expression`. We couldn't _delete_ the old rule in v7 because that would be a breaking change. But now that the new rule has landed, we can delete the old one in v8.

So: let's delete `no-useless-template-literalls` in a PR targeting the `v8` branch! 🔪

**Comment by kirkwaiblinger** [comment]
merged into V8 branch!
