### ISSUE TITLE
typescript.git-eslint

### ISSUE THREAD

**Issue by markalzate13** [typescript-eslint/typescript-eslint#917]
**What did you expect to happen?**

**What actually happened?**

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/experimental-utils`  |  `X.Y.Z` |
| `TypeScript`                       | `X.Y.Z` |
| `node.js`                                  | `X.Y.Z` |
| `npme.`                                   | `X.Y.Z` |

**Comment by markalzate13** [comment]
:)

**Comment by bradzacher** [comment]
Did you have an actual issue? Why are you opening blank issues in our repo?
