### ISSUE TITLE
Enhancement: [await-thenable] Should check chained method calls

### ISSUE THREAD

**Issue by Aghassi** [typescript-eslint/typescript-eslint#9172]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/await-thenable/

### Description

We are using Playwright, and there are a number of functions that can be chained which all end in `Promise` types. For example `page.getByRole('button').hover()` would require an `await`. Currently, this check only applies to `AwaitExpression`, which would mean that the provided example won't get picked up since it will be registered by the AST as a `CalleeExpression`. While it is a more complicated solve, it would be nice to have this support.

Alternatively, given type data on nested calls can be sparse, an equally useful check would be for any method invoked, assert it has an `async` before it. This could be achieved by allowing users of this rule to configure a list of methods to check for in addition, and then the rule can fail those methods as well.

### Fail

```TypeScript
const button = page.getByRole('button') // <-- this is fine, this is a promise assigned to a variable

//... more test code

button.hover() // <-- this should fail as it is missing an `await` and `hover` returns a promise.
```

### Pass

```TypeScript
const button = page.getByRole('button') // <-- this is fine, this is a promise assigned to a variable

//... more test code

await button.hover() // <-- this should pass
```

**Comment by bradzacher** [comment]
Try this https://typescript-eslint.io/rules/no-floating-promises/
