### ISSUE TITLE
Rule proposal: Consider bringing back no-duplicate-imports

### ISSUE THREAD

**Issue by latin-1** [typescript-eslint/typescript-eslint#9212]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

The `no-duplicates` rule in `eslint-plugin-import` has been broken for over a year. There is an ongoing [PR](https://github.com/import-js/eslint-plugin-import/pull/2716), but it has been stale for about 10 months. The author of `eslint-plugin-import`, ljharb, is not particularly interested in TypeScript or Flow. I think we should bring it back into our plugin. There is also a clear advantage for us: we can resolve the imports using the project service rather than relying on `resolve` or `enhanced-resolve`.

### Fail Cases

```TypeScript
import { A } from "package";
import { B } from "package";
```

### Pass Cases

```TypeScript
import { A, B } from "package";
```

**Comment by bradzacher** [comment]
There are alternatives like `eslint-plugin-import-x` which is a fork and cleanup.

We do not want to concern ourselves with the politics of OSS - we made the decision long ago to go with the ecosystem and not duplicate rules.

 There are existing solutions and as such we will not be taking on this rule.
