### ISSUE TITLE
Website: Rules sidebar missing from "tombstone" pages

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9213]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Rules pages on the site normally have a left page sidebar based on https://github.com/typescript-eslint/typescript-eslint/blob/50cc96dc0bd5f8c6b4501c7c277365226be08095/packages/website/sidebars/sidebar.rules.js. But, that's not there at the moment for pages like `camelcase.md` that don't have an associated rule:

![Screenshot of https://typescript-eslint.io/rules/camelcase showing no left sidebar](https://github.com/typescript-eslint/typescript-eslint/assets/3335181/7eb8ae47-2992-4557-8fad-0d842bdfb331)

### Affected URL(s)

https://typescript-eslint.io/rules/camelcase & more

💖

**Comment by juank1809** [comment]
I will work on this issue!

**Comment by bradzacher** [comment]
This was an intentional choice - we didn't want the tombstones to noise up the sidebar and the rules table.

These pages work from a hard link and are searchable but otherwise are invisible.

**Comment by JoshuaKGoldberg** [comment]
Oh, I'm not suggesting we add any tombstone links to the sidebar. Just that it's inconvenient to not have the sidebar when visiting the tombstone pages.

**Comment by Josh-Cena** [comment]
For anyone working on this: you want to read https://docusaurus.io/docs/sidebar/multiple-sidebars

The front matter you want to add is `displayed_sidebar`
