### ISSUE TITLE
2.1.0

### ISSUE THREAD

**Issue by a-tarasyuk** [typescript-eslint/typescript-eslint#922]
Are there any issues that block the publication of stable version `2.0.1`?

cc @bradzacher

**Comment by bradzacher** [comment]
No reason, we just haven't cut one yet.
It will be 2.1.0 because there has been feat commits since 2.0.0.

**Comment by a-tarasyuk** [comment]
@bradzacher Oke. :+1:  When do you plan to release version `2.1.0`?

**Comment by JamesHenry** [comment]
2.1.0 has been released.

For the first time this was done based on a schedule. From now on, we will cut a release to `latest` every Monday at 1pm Eastern Time.

Our philosophy has always been that what goes into master is good enough to use and that is why we publish every single commit to master - folks should never be blocked.

We nevertheless continue to get issues like this one, so hopefully automated weekly "promotions" to `latest` should mitigate the need for this completely.

**Comment by a-tarasyuk** [comment]
@JamesHenry Thanks!
