### ISSUE TITLE
AST tightening: `TSExternalModuleReference#expression` must be a `StringLiteral`

### ISSUE THREAD

**Issue by Josh-Cena** [typescript-eslint/typescript-eslint#9220]
### Suggestion

In https://github.com/typescript-eslint/typescript-eslint/pull/9211: we are planning to enforce the following invariants in our AST for `TSExternalModuleReference` (used in `TSImportEqualsDeclaration`):

- `expression` must be a string literal, so the following is a parsing error:
  ```js
  import x = require(1);
  import x = require(1 + 1);
  ```

@sosukesuzuki @fisker Do these look safe to you?

**Comment by fisker** [comment]
Should be safe.
