### ISSUE TITLE
AST tightening: around init/definite combinations on let/var/const declarators

### ISSUE THREAD

**Issue by Josh-Cena** [typescript-eslint/typescript-eslint#9221]
### Suggestion

In https://github.com/typescript-eslint/typescript-eslint/pull/9211: we are planning to enforce the following invariants in our AST for `VariableDeclaration`, specifically the declarators in `declarations`:

- `definite` can only be true if `declare: false` and `kind: "let" | "var"`, so the following are all parsing errors:
  ```ts
  const x! = 1;
  declare let x!: string;
  ```
- If `definite: true`, then `init: null`, and the identifier has a type annotation:
  ```ts
  let x! = 1;
  let x!;
  ```
- If `declare: true` and `kind: "let" | "var"`, then `init: null`:
  ```ts
  declare let x = 1;
  ```
- If `declare: false` and `kind: "const"` then `init` is non-null:
  ```ts
  const x;
  ```

@sosukesuzuki @fisker Do these look safe to you?

**Comment by fisker** [comment]
> Do these look safe to you?

I don't think Prettier really care, should be safe to us.
