### ISSUE TITLE
Bug: rc-v8 projectService option leads to default project errors when used with eslint-plugin-import

### ISSUE THREAD

**Issue by fpapado** [typescript-eslint/typescript-eslint#9223]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

While trying out `@typescript-eslint@rc-v8`, with the `projectService` key and `eslint-plugin-import`, a number of unrelated files end up being included in the default project. This then leads to the "Too many files (>...) have matched the default project" error.

This has surfaced in the past, first in https://github.com/typescript-eslint/typescript-eslint/issues/8428, and then as a general issue in https://github.com/typescript-eslint/typescript-eslint/issues/8428.

The core issue is that the `projectService` key is not deleted in [the relevant `eslint-module-utils` call-site.](https://github.com/import-js/eslint-plugin-import/blob/6554bd5c30976290024cecc44ef1e96746cf3cf7/utils/parse.js#L132-L138), so files end up being parsed with the project service.

I'd be happy to contribute a PR, either for this specific key, or for [the more general issue of exporting a utility to do the deletion](https://github.com/typescript-eslint/typescript-eslint/issues/8428).

I filed this as a separate issue, in case it helps tracking, but feel free to move it around 😇 

### Reproduction Repository Link

https://github.com/fpapado/typescript-eslint-v8-with-plugin-import

### Repro Steps

1) clone the repo
2) `pnpm install`
3) `pnpm eslint .`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `8.0.0-alpha.25` |
| `@typescript-eslint/parser`            | `8.0.0-alpha.25` |

**Comment by JoshuaKGoldberg** [comment]
Indeed, `eslint-plugin-import` will need to remove the new `projectService` key from `parserOptions` too. This is similar to https://github.com/import-js/eslint-plugin-import/issues/2962 -> https://github.com/import-js/eslint-plugin-import/pull/2963. You'll want to file an issue over there.

Also, now that #8428 -> #9233 is merged, we export a nice `withoutProjectParserOptions` that projects can try to import and use. 🚀 

Thanks for filing!
