### ISSUE TITLE
Bug: Missing peer dependencies

### ISSUE THREAD

**Issue by latin-1** [typescript-eslint/typescript-eslint#9224]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-eslint

### Repro Code

```json
{
  "devDependencies": {
    "eslint": "9.4.0",
    "typescript": "5.4.5",
    "typescript-eslint": "8.0.0-alpha.25"
  }
}
```

```
Package @typescript-eslint/utils@npm:8.0.0-alpha.25 [a23fe] is requested to provide typescript by its descendants

@typescript-eslint/utils@npm:8.0.0-alpha.25 [a23fe]
└─ @typescript-eslint/typescript-estree@npm:8.0.0-alpha.25 [fd6b8] (via *)
   └─ ts-api-utils@npm:1.3.0 [e2004] (via >=4.2.0)

✘ Package @typescript-eslint/utils@npm:8.0.0-alpha.25 [a23fe] does not provide typescript.
```

```
Package @typescript-eslint/type-utils@npm:8.0.0-alpha.25 [47dfd] is requested to provide eslint by its descendants

@typescript-eslint/type-utils@npm:8.0.0-alpha.25 [47dfd]
└─ @typescript-eslint/utils@npm:8.0.0-alpha.25 [a23fe] (via ^8.57.0 || ^9.0.0)
   └─ @eslint-community/eslint-utils@npm:4.4.0 [fd6b8] (via ^6.0.0 || ^7.0.0 || >=8.0.0)

✘ Package @typescript-eslint/type-utils@npm:8.0.0-alpha.25 [47dfd] does not provide eslint.
```

```
Package typescript-eslint@npm:8.0.0-alpha.25 [14e3a] is requested to provide eslint by its descendants

typescript-eslint@npm:8.0.0-alpha.25 [14e3a]
├─ @typescript-eslint/eslint-plugin@npm:8.0.0-alpha.25 [a23fe] (via ^8.57.0 || ^9.0.0)
│  └─ @typescript-eslint/utils@npm:8.0.0-alpha.25 [a23fe] (via ^8.57.0 || ^9.0.0)
│     └─ @eslint-community/eslint-utils@npm:4.4.0 [fd6b8] (via ^6.0.0 || ^7.0.0 || >=8.0.0)
├─ @typescript-eslint/parser@npm:8.0.0-alpha.25 [a23fe] (via ^8.57.0 || ^9.0.0)
└─ @typescript-eslint/utils@npm:8.0.0-alpha.25 [a23fe] (via ^8.57.0 || ^9.0.0)
   └─ ...

✘ Package typescript-eslint@npm:8.0.0-alpha.25 [14e3a] does not provide eslint.
```

### Expected Result

Installed without any warnings. 

### Actual Result

`yarn install` reports unmet peer dependencies. 

### Versions

| package | version |
| - | - |
| `typescript-eslint` | `8.0.0-alpha.25` |
| `TypeScript` | `5.4.5` |
| `ESLint` | `9.4.0` |

**Comment by bradzacher** [comment]
This seems like a really weird constraint for yarn to enforce - to force a package to declare a peer dependency for its transient peer dependencies.

For the record the dependencies haven't changed since v7 AFAIK. So it should fail in the same way.

**Comment by Josh-Cena** [comment]
@bradzacher The requirement for Yarn is that every transitive peer dependency needs to either be "passed on" as peer dependency or declared as dependency (so all packages further up the chain don't need to)

**Comment by LFCavalcanti** [comment]
Hi,

Same problem here today but using NPM.

My dev dependencies versions:
```
"devDependencies": {
    "@typescript-eslint/eslint-plugin": "^7.12.0",
    "@typescript-eslint/parser": "^7.12.0",
    "eslint": "^9.4.0",
  }
```

When I try to run `npm Install`:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: project-name@0.1.0
npm ERR! Found: eslint@9.4.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^9.4.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^8.56.0" from @typescript-eslint/parser@7.12.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"^7.12.0" from the root project
npm ERR!   peer @typescript-eslint/parser@"^7.0.0" from @typescript-eslint/eslint-plugin@7.12.0
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     dev @typescript-eslint/eslint-plugin@"^7.12.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by bradzacher** [comment]
@LFCavalcanti youre using eslint v9 with typescript-eslint v7. That pairing is not valid - typescript-eslint v7 only supports eslint v8.

**Comment by LFCavalcanti** [comment]
> @LFCavalcanti youre using eslint v9 with typescript-eslint v7. That pairing is not valid - typescript-eslint v7 only supports eslint v8.

Yeah, I managed to fix that updating to this:
```
"devDependencies": {
    "@typescript-eslint/eslint-plugin": "^7.12.0",
    "@typescript-eslint/parser": "^7.12.0",
    "eslint": "^8.57.0",
  }
```
I already tried fixing the Eslint version to `^8.57.0` but the error persisted.

The catch was updating Eslint first, then the parser and finally the plugin.

Thanks!

**Comment by callmeberzerker** [comment]
> @LFCavalcanti youre using eslint v9 with typescript-eslint v7. That pairing is not valid - typescript-eslint v7 only supports eslint v8.

What's the meaning behind this statement? Does `typescript-eslint` plan to ever support ESLint 9 or? I see the documentation references flat config which is for ESLint 9 - but peer dependency says v8.x.x. Also aside from the warning everything works?

**Comment by JoshuaKGoldberg** [comment]
Flat config support !== ESLint 9 support. You can support one without the other.

Issues on our side:
* #7694: supported as of `v7`
* #8211: available only in the `v8` branch, currently in beta

**Comment by facucarbonel** [comment]
@bradzacher 
> @LFCavalcanti youre using eslint v9 with typescript-eslint v7. That pairing is not valid - typescript-eslint v7 only supports eslint v8.

current eslint version is v9, how do I use typescript-eslint if the current version is v7? is there an alpha version or something like that?

**Comment by JoshuaKGoldberg** [comment]
✨ https://github.com/typescript-eslint/typescript-eslint/issues/8211 -> https://typescript-eslint.io/blog/announcing-typescript-eslint-v8-beta ✨

**Comment by bradzacher** [comment]
I'm going to lock this issue as the conversation is going way off topic. We shall investigate the peer deps.

**Comment by scagood** [comment]
I am getting exactly the same thing when I use yarn in pnpm mode
```
p25f29 → ✘ `@typescript-eslint/type-utils@npm:8.3.0` [bf79f] doesn't provide eslint to `@typescript-eslint/utils@npm:8.3.0` [bc0f5] and 1 other dependency
pdf5ff → ✘ `@typescript-eslint/utils@npm:8.3.0` [8e893] doesn't provide typescript to `@typescript-eslint/typescript-estree@npm:8.3.0` [1e2f5] and 1 other dependency
p25b1b → ✘ `@typescript-eslint/utils@npm:8.3.0` [bc0f5] doesn't provide typescript to `@typescript-eslint/typescript-estree@npm:8.3.0` [1e2f5] and 1 other dependency
```

I first started seeing this in `@typescript-eslint/eslint-plugin@npm:8.0.0`.

My solution to this was to add this to my .yarnrc.yml:
```yml
packageExtensions:
  "@typescript-eslint/type-utils@*":
    peerDependencies:
      eslint: "*"
```

<details>
<summary>
In my case I got the following error when trying to run eslint:
```
</summary>

```javascript
Error: Cannot find module 'eslint/use-at-your-own-risk'
Require stack:
- /home/runner/work/node-stuffs/node-stuffs/node_modules/.store/@typescript-eslint-utils-virtual-1639fa6ec9/package/dist/ts-eslint/eslint/LegacyESLint.js
- /home/runner/work/node-stuffs/node-stuffs/node_modules/.store/@typescript-eslint-utils-virtual-1639fa6ec9/package/dist/ts-eslint/ESLint.js
- /home/runner/work/node-stuffs/node-stuffs/node_modules/.store/@typescript-eslint-utils-virtual-1639fa6ec9/package/dist/ts-eslint/index.js
- /home/runner/work/node-stuffs/node-stuffs/node_modules/.store/@typescript-eslint-utils-virtual-1639fa6ec9/package/dist/index.js
- /home/runner/work/node-stuffs/node-stuffs/node_modules/.store/@typescript-eslint-type-utils-virtual-b8b27d4b16/package/dist/isTypeReadonly.js
- /home/runner/work/node-stuffs/node-stuffs/node_modules/.store/@typescript-eslint-type-utils-virtual-b8b27d4b16/package/dist/index.js
- /home/runner/work/node-stuffs/node-stuffs/node_modules/.store/@typescript-eslint-eslint-plugin-virtual-54e9de6f23/package/dist/util/misc.js
- /home/runner/work/node-stuffs/node-stuffs/node_modules/.store/@typescript-eslint-eslint-plugin-virtual-54e9de6f23/package/dist/util/index.js
- /home/runner/work/node-stuffs/node-stuffs/node_modules/.store/@typescript-eslint-eslint-plugin-virtual-54e9de6f23/package/dist/rules/adjacent-overload-signatures.js
- /home/runner/work/node-stuffs/node-stuffs/node_modules/.store/@typescript-eslint-eslint-plugin-virtual-54e9de6f23/package/dist/rules/index.js
- /home/runner/work/node-stuffs/node-stuffs/node_modules/.store/@typescript-eslint-eslint-plugin-virtual-54e9de6f23/package/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/runner/work/node-stuffs/node-stuffs/node_modules/.store/@typescript-eslint-utils-virtual-1639fa6ec9/package/dist/ts-eslint/eslint/LegacyESLint.js:5:32)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:[10](https://github.com/scagood/node-stuffs/actions/runs/10188556353/job/28184924114?pr=283#step:6:11))
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:[12](https://github.com/scagood/node-stuffs/actions/runs/10188556353/job/28184924114?pr=283#step:6:13)33:19)
```

</details>

**Comment by KoljaFrahm** [comment]
I needed
`packageExtensions:
  typescript-eslint@*:
    peerDependencies:
      eslint: '*'
  '@typescript-eslint/type-utils@*':
    peerDependencies:
      eslint: '*'
  '@typescript-eslint/utils@*':
    peerDependencies:
      typescript: '*'
`
to make the error go away

**Comment by JoshuaKGoldberg** [comment]
I took a look and, yes, I get this too. Isolated reproduction here: https://github.com/JoshuaKGoldberg/repros/tree/repro-typescript-eslint-and-yarn-pnp
