### ISSUE TITLE
Docs: `@typescript-eslint/parser` page doesn't use flat config format

### ISSUE THREAD

**Issue by fudom** [typescript-eslint/typescript-eslint#9262]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Since the new eslint version and the new breaking change of configuration file (aka flat config), some typescript rules do not work. Now I get this error. Sorry if I overlooked the docs. But I spent countless hours on that migration.

```plaintext
Error: Error while loading rule '@typescript-eslint/require-await': 
You have used a rule which requires parserServices to be generated. 
You must therefore provide a value for the "parserOptions.project" 
property for @typescript-eslint/parser.
```

How? I cannot find docs about that...

**eslint.config.mjs** (snippet)

```js
import pluginJs from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import eslintPluginOnlyWarn from 'eslint-plugin-only-warn';

export default [
  {
    languageOptions: { globals: globals.browser },
  },
  {
    ignores: ['/*', '!/src', '**/*.spec.ts'],
  },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.ts'],
    plugins: {
      'only-warn': eslintPluginOnlyWarn,
    },
    rules: {
      'require-await': 'off',
      '@typescript-eslint/require-await': 'warn',
    },
  },
];
```

### Affected URL(s)

https://typescript-eslint.io/packages/parser

It's not `.eslintrc.json` anymore. It's the more complicated flat config.

**Comment by Josh-Cena** [comment]
Please see https://typescript-eslint.io/getting-started/typed-linting.

**Comment by bradzacher** [comment]
@fudom did you read the getting started guide at all..?
https://typescript-eslint.io/getting-started/
It walks you through what packages to install and how to setup your flat config. The page that Josh linked is the second page of the guide which walks you through the type-aware linting setup.
