### ISSUE TITLE
Enhancement: Remove getTokenAtPosition from type-utils

### ISSUE THREAD

**Issue by y-hsgw** [typescript-eslint/typescript-eslint#9292]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

type-utils

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

It appears that the `getTokenAtPosition` function is not being used. I think it's safe to delete.
target path: `packages/type-utils/src/getTokenAtPosition.ts`

**Comment by JoshuaKGoldberg** [comment]
Nice spot! Yes, let's remove this.

Note that it's a breaking change to remove any publicly exported function. So this is a breaking change. The PR to resolve this should target the `v8` branch, _not_ `main`.

**Comment by y-hsgw** [comment]
merged into V8 branch in https://github.com/typescript-eslint/typescript-eslint/pull/9444 !
