### ISSUE TITLE
[no-empty-interface] Add exception for circular references

### ISSUE THREAD

**Issue by davidje13** [typescript-eslint/typescript-eslint#930]
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-empty-interface": ["error"]
  }
}
```

```TS
interface RecursiveStrings extends Array<RecursiveStrings | string> {}
```

**Expected Result**

No error, because the recommended alternative `type RecursiveStrings = Array<RecursiveStrings | string>` is not valid. If the extended type contains the current type, the error should not appear.

**Actual Result**

> ```
> error: An interface declaring no members is equivalent to its supertype (@typescript-eslint/no-empty-interface)
> ```

**Additional Info**

This also applies to more complex circular structures which might be harder to detect, but the form demonstrated above is the most common.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.13.0` |
| `@typescript-eslint/parser`        | `1.13.0` |
| `TypeScript`                       | `3.5.3` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `12.9.1` |
| `npm`                              | `6.10.3` |

**Comment by bradzacher** [comment]
We could probably add support for simple cases, but for more complex ones it's probably better to just use an `eslint-disable-next-line` comment

**Comment by Validark** [comment]
This can probably be closed now.
