### ISSUE TITLE
[recommended-requiring-type-checking] Add no-floating-promise by default

### ISSUE THREAD

**Issue by EduardoRFS** [typescript-eslint/typescript-eslint#931]
I was looking at `recommended-requiring-type-checking` and did notice that it doesn't use `no-floating-promise` on it, but it seem weird, as it includes some rules of the same kind that make better usage of promises and avoid weird things. `await-thenable`, `no-misused-promises` and `require-await`.

Adding `no-floating-promise` would just continuous the idea of this and improve a better default for most use cases, especially when new developers who aren't experienced on JavaScript try to use the language.

**Comment by joeytwiddle** [comment]
Agreed, not handling promises is a common source of problems with inexperienced developers on our codebase. This rule helps a lot!

I think it would be useful to have this enabled by default. (Teams can always opt out if they want.)

**Comment by bradzacher** [comment]
See recommended discussion in #1423
