### ISSUE TITLE
Document rationale for allowNumber: false in restrict-template-expressions

### ISSUE THREAD

**Issue by danvk** [typescript-eslint/typescript-eslint#9311]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

The strict-type-checked configuration sets `allowNumber: false` for the restrict-template-expressions rule. This prohibits code like the following:

```ts
const userId = 123;
const url = `/users/${userId}`;
```

There is nothing wrong with this code. The official [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) on template literals contain code just like it. The [typescript-eslint docs](https://typescript-eslint.io/rules/restrict-template-expressions/#allownumber) for this rule offer no rationale of why interpolating numbers into a string in this way is problematic.

### Impacted Configurations

- strict
- strict-type-checked

### Additional Info

I'm totally bought into all the other options that `strict` enables for restrict-template-expressions (`allowAny`, `allowArray`, `allowBoolean`, `allowNullish`, `allowNever`). These seem potentially problematic since they could result in your inadvertently showing debug code to users. But `allowNumber`? I'm having trouble seeing any rationale for banning that.

My proposal would be to either change the default setting or add a clear explanation of why interpolating numbers into strings is dangerous.

Possibly related:
- #6758
- #5265

**Comment by Josh-Cena** [comment]
I think the rationale is not integers but floating point. For example `` `The result is ${0.1 + 0.2}` ``. You should probably use `toFixed()`.

**Comment by danvk** [comment]
That's a good point @Josh-Cena. If you're working with integers, this rule is pure noise. If you're working with floats, it's a helpful reminder. For the first time, I will say: it would be nice if TypeScript had an `int` type! :)

So I can see the rationale for this rule, though I think for most code it's going to be quite noisy compared to the other types that are disallowed by restrict-template-expressions. Including a rationale in the docs seems like a clear win, though.

**Comment by Josh-Cena** [comment]
Agreed!
