### ISSUE TITLE
Docs: add an FAQ section about eslint TIMING/`--stats` and type-aware rules being misleading

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#9315]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

ESLint allows you to profile your lint run with the TIMING=1 env var [^1]. Alternately it provides the `--stats` flag to do a similar thing in a JSON form [^2].

These flags are great debug tools for non-type-aware rules. But they're mostly useless for type-aware rules because types are computed lazily and cached. This means that the first type-aware rule that runs will bear the brunt of doing the "pre-cached" calculations and then folllowing rules mostly just read from the caches and do little work in comparison.

This can actually paint a misleading and harmful picture [because people will read the times and think a particular rule is much slower than it is in reality](https://x.com/public_ai000ya/status/1798771024512868671) and sometimes people will turn off a rule thinking it was the cause of slowness.

We should have an FAQ section about this so we can help inform people to not trust the output for type-aware rules.

[^1]: https://eslint.org/docs/latest/extend/custom-rules#profile-rule-performance
[^2]: https://eslint.org/docs/latest/extend/stats

### Affected URL(s)

Faq

**Comment by JoshuaKGoldberg** [comment]
Related area of docs: #8189
