### ISSUE TITLE
Security alert eslint-utils

### ISSUE THREAD

**Issue by NicoAiko** [typescript-eslint/typescript-eslint#932]
Dear repository contributors,

today I got an email by GitHub that one of my dependencies is vulnerable and thus should be updated.

I took a look and found out that `@typescript-eslint/parser` uses v1.3.1 of `eslint-utils` which has been found vulnerable.

Please update it to at least v1.4.1 as that version fixed the vulnerability.

Thanks!

**Comment by bradzacher** [comment]
We get the same security alerts on github.

See #916
