### ISSUE TITLE
Enhancement(typescript-estree): expose ProjectService logs through plugin

### ISSUE THREAD

**Issue by higherorderfunctor** [typescript-eslint/typescript-eslint#9321]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-estree

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I propose we expose `ProjectService` logs through this plugin using the `DEBUG` environment variable.

There are 3 log channels and the unused event handler, so I'm thinking something along the lines of below.  This would help trace `ProjectService` behavior and diagnose related issues.

```
typescript-eslint:typescript-estree:tsserver:err
typescript-eslint:typescript-estree:tsserver:info
typescript-eslint:typescript-estree:tsserver:perf
typescript-eslint:typescript-estree:tsserver:event
```

### Additional Info

Follow up issue from the discussion at https://github.com/typescript-eslint/typescript-eslint/issues/8835#issuecomment-2148431969.

**Comment by higherorderfunctor** [comment]
Question after starting the implementation.  Would it be better to:

1. Not share the `typescript-eslint` prefix (e.g., `DEBUG=typescript-eslint:*,tsserver:*`) and document the new prefix.
2. Use a common prefix and document how to filter (e.g., `DEBUG='typescript-eslint:*,-typescript-eslint:typescript-estree:tsserver:info`)

In the branch I am working on I currently have:

```
typescript-eslint:typescript-estree:tsserver:err
typescript-eslint:typescript-estree:tsserver:info
typescript-eslint:typescript-estree:tsserver:perf
typescript-eslint:typescript-estree:tsserver:event
```

**Comment by JoshuaKGoldberg** [comment]
#9337 was merged into the `v8` branch. ✅
