### ISSUE TITLE
Website: Playground is currently broken

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#9323]
As of this morning's release the playground is broken.

https://github.com/typescript-eslint/typescript-eslint/assets/7462525/82a80cc9-b60c-4133-abbe-5ffc833eac40

I believe the root cause was https://github.com/typescript-eslint/typescript-eslint/pull/9271

https://github.com/typescript-eslint/typescript-eslint/assets/7462525/906e65a4-4627-4f72-a61b-2a1cb8bbb7c9

cc @JoshuaKGoldberg

**Comment by JoshuaKGoldberg** [comment]
Oh, heck.

**Comment by JoshuaKGoldberg** [comment]
Fixed by #9327.
