### ISSUE TITLE
Docs: Release note of v7.12.0 contains critical misleading typo

### ISSUE THREAD

**Issue by xsjcTony** [typescript-eslint/typescript-eslint#9329]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Below can be very misleading since this will cause the plugin to crash if someone fully relies on the release note.

From
- eslint-plugin: [no-useless-template-literals] rename to `no-useless-template-expression`

To
- eslint-plugin: [no-useless-template-literals] rename to `no-unnecessary-template-expression`

### Affected URL(s)

N/A

**Comment by kirkwaiblinger** [comment]
Related: https://github.com/typescript-eslint/typescript-eslint/pull/8821#issuecomment-2146638645

**Comment by bradzacher** [comment]
I've updated the GH release body
