### ISSUE TITLE
Bug: no-unused-vars with for await...of loops

### ISSUE THREAD

**Issue by jamiebuilds** [typescript-eslint/typescript-eslint#9338]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.5&fileType=.tsx&code=KYDwDg9gTgLgBAbzgXwFABNgGMA2BDKYOAMwFcA7LGASwnLjwGcBPSgSRmCjxmgAoAlAC44AQRbtO3AEY5gAHgBuEaugB8qVMWgMA7nmrw%2Bc%2BAH04EYgwlYOXHvwEDEqOHCx1GEOQDocEAHM%2BACIaLABrYIFUNCA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tidmUQAmtAG4BDaKgyRE0aB2iRwYAL4hlQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYo4YAviLUA&tokens=false

### Repro Code

```TypeScript
export { }
declare function asyncIterator(): AsyncIterable<void>

// err: "'_' is assigned a value but never used. 4:16 - 4:17"
for await (let _ of asyncIterator()) {
  console.log("tick")
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unused-vars": "error"
  },
};
```

### tsconfig

```jsonc
{ "compilerOptions": {} }
```

### Expected Result

Should not report an error for the unused variable which is required for the `for await...of` syntax

### Actual Result

Reports an error `"'_' is assigned a value but never used. 4:16 - 4:17"`

### Additional Info

The syntax of `for await...of` requires a variable declaration or assignment target:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of

There is the option of using an empty object destructuring pattern which works with `undefined` but I'd wager most would be confused by what is happening there and would not naturally think to do that

```ts
for await ({} of asyncIterator()) {}
```

**Comment by bradzacher** [comment]
This is expected - the identifier is syntactically required - but semantically its still unused. In your case the variable is _intentionally_ unused because you don't care about the value from your iterator - but the rule does not encode such assumptions.

If you intentionally want to have an unused variable - consider a naming convention configured in the rule: https://eslint.org/docs/latest/rules/no-unused-vars#varsignorepattern

For example `varsIgnorePattern: '^_$'` would specifically allow just the single underscore name to be unused (or drop the `$` to allow underscore-prefixed names to be unused).

**Comment by bradzacher** [comment]
For additional reference - we align with the base eslint rule which also reports in this case [playground](https://typescript-eslint.io/play/#ts=5.4.5&fileType=.tsx&code=KYDwDg9gTgLgBAbzgXwFABNgGMA2BDKYOAMwFcA7LGASwnLjwGcBPSgSRmCjxmgAoAlAC44AQRbtO3AEY5gAHgBuEaugB8qVMWgMA7nmrw%2Bc%2BAH04EYgwlYOXHvwEDEqOHCx1GEOQDocEAHM%2BACIaLABrYIFUNFQgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQHYHsBaWXWZRAE0IDcBDaVDSRaafaSAGnG0gAEALgE8ADigDG0AJYiBhFPCm4BAegLFS5KnQbooLNhx4BfEMaA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYo4YAviLUA&tokens=false).
