### ISSUE TITLE
Bug: no-extraneous-class triggered on abstract class that does not contain any static methods

### ISSUE THREAD

**Issue by cowwoc** [typescript-eslint/typescript-eslint#9359]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.5&fileType=.ts&code=LAKA9AVBoAQTAVAFgUxgYwPYDsBmBLAcwFcAnAQwBd8cYBnJc0lAExgCMBPGcgG15gA3PvhZVMpOgDoYAYUbZCKOjwAOq3t0qYYKAB7461RTAkxsKAO5CRY7ZKmwIYUOXZGK6Shl7k6KgHFeTHY%2BWRwCEgpqWgBvWBhIaBAYVPgAJRRKMmwVSlRdbCwWfBM6YnUJSlYOLQLq0gBbUr5HFLSEuBgAAWZs0lyYfLQUIswSsorVKpquIfqUJpbeTucE1WJ2Xnx0HndKT28lSgBlKZmWBEXm7D4AUTGJwjoACgBKAC4YE6yAHmxiI12IsAHwAblACSSqxgmX6g2GGDIzGw3gaNz4hWKpUIbVScBhvSyOTyBXQyNGaOuyyx4xxMBeLBQuHIxF4lDyOkRrO0AFomdUvDVRtjFG9Vi52hstjs9h5yF4YMcrktbrwHqLCO8vgCgYsISAoVAYT8OfM0OiaSK6SZMLhzaZiJQNpQ8WkYL9VCCYchDBhyNgOGhiHQatoYLgJOgLQUQ2g7TAAIIAOROAEkMJhgpIYJZUIHhvhSPRzqRvH7sJhvAKUEKWG6Ce0ut1VExyI1aU8YLyHZROKp4-brV38lRe9S1SXKmW6IS%2BiT5oZCflSJhLCoEP2UHdSKvi-h7b9iigQcOcb8wMeQTA-cRsEyCBY2GYAfwJetNttdm55YrQ5QVQxdVHhxF4z0UHVAWBUhPhgIIQjCCIiDIKgaGwA0AF9IRAfRpjLGBYjg4JQl4cI8GQ6I0JgDCwSAA&eslintrc=N4KABGBEAOA2CuBzAlgOwM6QFzjAbVwkgAEAXAT2gFN0BjAJ2WlIFobY1SB6U9D1UpFwBdADS5I9eLBrYwoCETKUaDJq3acuqAPZsAHqXoBDVFR3x0LWrGPpMWKFXr0d9IRAC%2BIT0A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
/**
 * The configuration shared by all validators. Changes apply to existing or new validators.
 */
abstract class GlobalConfiguration {
  /**
   * Returns the encoding supported by the terminal.
   *
   * @returns the encoding supported by the terminal
   */
  public abstract getSupportedTerminalEncodings(): Set<number>;

  /**
   * Returns the current terminal encoding.
   *
   * @returns the current terminal encoding (defaults to the auto-detected encoding)
   */
  public abstract getTerminalEncoding(): number;

  /**
   * Sets the terminal encoding of the output.
   * <p>
   * This can be used to force the use of ANSI colors when their support is not detected.
   *
   * @param encoding - the type of encoding that the terminal supports
   * @returns this
   * @throws TypeError if <code>encoding</code> is undefined or null
   */
  public abstract setTerminalEncoding(encoding: number): GlobalConfiguration;
}

export { GlobalConfiguration };
```

### ESLint Config

```javascript
{
  "plugins":
  [
    "@typescript-eslint/tslint"
  ],
  "rules": {
    "@typescript-eslint/no-extraneous-class": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

No error

### Actual Result

Error claiming that the class only contains static properties, when in fact it does not contain even a single static property.

### Additional Info

"@eslint/js": "^9.4.0",
"@typescript-eslint/eslint-plugin": "^7.13.0",
"@typescript-eslint/parser": "^7.13.0",
"eslint": "^9.4.0",
"typescript-eslint": "^7.13.0",

**Comment by kirkwaiblinger** [comment]
@cowwoc Thanks for the report!

For anyone that wants to take this on - I think the oversight in the rule implementation is simply that abstract fields/methods, which have different AST Nodes from their concrete counterparts, are not counted as instance properties. So, the fix would probably be just to address that. We'd still want an abstract class to flag if it actually only has static properties.
