### ISSUE TITLE
Docs: v8 docs should point to v8 info instead of latest v7 release

### ISSUE THREAD

**Issue by kirkwaiblinger** [typescript-eslint/typescript-eslint#9361]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

In the upper right hand corner of the site, there is a link that points to the latest release notes. These are misleading for the v8 branch, since they point to a v7 release. Maybe we can point it to the v8 blog post or something instead?

### Affected URL(s)

https://v8--typescript-eslint.netlify.app/

**Comment by JoshuaKGoldberg** [comment]
That makes sense, +1 from me!

**Comment by Tobbe** [comment]
This also shows up in the left sidebar on the playground, making you think you're linting with an older TSEslint version
![image](https://github.com/user-attachments/assets/1483cc4b-9887-4e09-8cb2-ca3961687c63)
