### ISSUE TITLE
Bug: [prefer-nullish-coalescing] quick fix for ternary removes required parens

### ISSUE THREAD

**Issue by jakebailey** [typescript-eslint/typescript-eslint#9379]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.5&fileType=.tsx&code=CYUwxgNghgTiAEEQBd4DcoQK4gFzwGdkYBLAOwHN4AfeLM0AM3JGAG4BYAKG8frGQkA9mXgiwIABRp8RUpQCU8AN7d48OMiwxRGbAgCEAXiN0GIZmVbwA-Okw54%2BaQ4Sm0C7gF8gA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WlqYSNkAC1pkA9gEMkyMswDm6KL2jjokcGAC%2BILUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
declare let value: string | undefined;

function once(v: string) {
  return value !== undefined ? value : (value = v)
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/prefer-nullish-coalescing": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

Fix is:

```
declare let value: string | undefined;

function once(v: string) {
  return value ?? (value = v)
}
```

Or honestly, 

```
declare let value: string | undefined;

function once(v: string) {
  return value ??= v
}
```

Except that this rule doesn't understand `??=` at all, as far as I can tell (another issue).

### Actual Result

Fix is:

```
declare let value: string | undefined;

function once(v: string) {
  return value ?? value = v
}
```

**Comment by kirkwaiblinger** [comment]
@jakebailey Marked accepting prs 👍

**Comment by bradzacher** [comment]
> Except that this rule doesn't understand ??= at all, as far as I can tell (another issue).

There's a sordid history between the assignment operators and type information.

For assignments like `x ?? (x = y)` the types are quite clear about the nullishness of `x`. But for `x ??= y` the types can be quite muddy - TS reports the post-assignment types (intentionally so https://github.com/microsoft/TypeScript/issues/53303).

But for this rule it doesn't matter - the rule isn't looking to try and get you to use the compound assignment - just nullish coalescing.
