### ISSUE TITLE
Rule proposal: Disallow line comment inside type declarations

### ISSUE THREAD

**Issue by suyoungDev** [typescript-eslint/typescript-eslint#9381]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I often encounter developers using line comments inside type declarations. If the field name is complex, it becomes inconvenient to understand its meaning without digging into the file where the type declaration is written. Using block comments inside type declarations would solve this with just a mouse hover. In a collaborative project, especially when using type declarations with complex field names, what is the point of writing comments if you have to navigate through files to see them?

### Fail Cases

```TypeScript
interface PriceTick {
  delay?: number; // ms
  // how many people bought this
  volume: number;
  // current price
  close: number; // realtime
}
```

### Pass Cases

```TypeScript
interface PriceTick {
  /** ms */
  delay?: number;
  /** how many people bought this */
  volume: number;
  /** 
   * current price
   * realtime
   */
  close: number;
}
```

**Comment by kirkwaiblinger** [comment]
Hi @suyoungDev!

Believe me when I say I sympathize with you! I have said "pls convert to jsdoc" more times than I can count in code reviews. That said - I wonder whether this is something that belongs in (or already exists in) [eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc). At a glance, I see closely related functionality their [no-bad-blocks](https://github.com/gajus/eslint-plugin-jsdoc/blob/8603579b1f5f3aa3c8357949ed6b2b2d5265149a/docs/rules/no-bad-blocks.md#readme) rule. Have you tried looking through what that plugin offers?

**Comment by bradzacher** [comment]
I'm a -1 on this. Not everyone wants to use jsdoc and not every comment should be jsdoc. It's a stylistic preference and not something that we can broadly enforce.

**Comment by Josh-Cena** [comment]
I'm also -1 since you can easily say the same about classes/functions/etc.

**Comment by bradzacher** [comment]
Looks like we've got a general consensus here.
We shall not move forward with this proposal.
