### ISSUE TITLE
Bug: [no-floating-promises] Does not work on some basic functions

### ISSUE THREAD

**Issue by flashburst** [typescript-eslint/typescript-eslint#9401]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.5&showAST=types&fileType=.ts&code=MYewdgzgLgBBA2BTRAHGBeGBDCBPMwMAFALYQBcMYAriQEaIBOAlBgHwwDeAUDDI4ijVGYKogDuMAAqMQJAJYRERIgIgh4AN0St0HHnz4ChIuIIAq8kohDUoqxOq2IANDDLNeMAL6fv3blBIWHkAE0QwKHkoXAxsPAJiLEoaeiZdfS8scSxouCRUIgBGAAYyzy9jYVEsbn9A8GgYKEcoACY4nHxCIgyuLwB6AZgAWUUIeTAAcxgmWUYYQF4NwHEdyhk5RUc4AAtbeFCYBmwc6MRQryCmtWp4KCK4sIiomKIAZk8%2BS41EADp4ECmDggNzuFU%2BjVg11uHUw2VyIXCkWiuDeHxgXyQfwBQJBbT8ARa0DavS8Pyg2wiRAxv3%2BUzRP2AWCgwG2VMa3x%2BcxALG4QA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oDN4OBDfMwDmtYtA4BbSshTooiaBOiRwYAL4h1QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
const sleep = async (ms: number) => {
  return new Promise((resolve) => {
    return setTimeout(resolve, ms)
  })
}

const identity = async (a: number) => {
  await sleep(1000)

  return a
}

const test2 = async () => {
  // Missing error 👇: Promises should be awaited
  const result1 = identity(3)
  console.log(result1)

  const result2 = await identity(3)
  console.log(result2)
}

test2()
  .then(console.log)
  .catch(console.error)
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/no-floating-promises": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

Should error when calling identity() without await

### Actual Result

There is no error when calling a function that returns a promise without await

**Comment by bradzacher** [comment]
As per the docs https://typescript-eslint.io/rules/no-floating-promises/

> no-floating-promises only detects unhandled Promise statements. See no-misused-promises for detecting code that provides Promises to logical locations such as if statements.
