### ISSUE TITLE
Enhancement: naming-convention ignore imported types

### ISSUE THREAD

**Issue by adam-marshall** [typescript-eslint/typescript-eslint#9416]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/naming-convention/

### Description

Being able to set a rule to require camelCase for variables, class members, properties, interfaces, etc, whilst have that _not_ be applied to imports.

OR

Some other workaround such as allowing camelCase to not be required for imports which are to be used with `new`

**Scenario 1**

NgRx Generators.
The schematics out-of-the-box generate imports with PascalCase naming for actions and selectors.

```
import * as BananaActions from './bananas.actions';

@Injectable()
export class BananaEffects {
  loadBananas$ = createEffect(() =>
    this.actions$.pipe(
      ofType(BananaActions.languageUpdated),
```

This is easily resolved by converting to camelCase manually. ✅ 

**Scenario 2**

Importing from an external library e.g. https://www.highcharts.com/docs/getting-started/installation-with-esm

Sometimes aliasing can be used and this is fine.

Consider for example:

```
import Color from 'colorjs.io';
...

const myColor = new Color(hex);
```

If this is changed to:

```
import color from 'colorjs.io';
...

const myColor = new color(hex);
```

You may receive IDE errors, e.g. WebStorm prompts "Constructor names usually start with an uppercase letter. A typo?"

More importantly, it would clash with https://eslint.org/docs/latest/rules/new-cap

### Fail

N/A - this issue is about code which is errored on, undesirably.

### Pass

```TypeScript
import Color from 'colorjs.io';
```

### Additional Info

**Disclaimer**

I am aware that this was logged already (https://github.com/typescript-eslint/typescript-eslint/issues/6744), perhaps the checkbox

> I have searched for related issues and found none that match my proposal.

should be

> I have searched for related issues and found no open issues that match my proposal.

as I have an additional use case for the issue raised there but as it is closed I cannot contribute.

**Comment by kirkwaiblinger** [comment]
Hi @adam-marshall! Thanks for the issue.
At this time, the naming-convention rule is feature-frozen, so I'm going to close this. I'd refer to you the [rule docs page](https://typescript-eslint.io/rules/naming-convention/), and to https://github.com/typescript-eslint/typescript-eslint/issues/8792. 
Cheers!
