### ISSUE TITLE
Docs: add documentation on why there are so many alpha versions on npm, and what the differences are.

### ISSUE THREAD

**Issue by abrahamguo** [typescript-eslint/typescript-eslint#9425]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

On [the NPM page for typescript-eslint](https://www.npmjs.com/package/typescript-eslint?activeTab=versions), there are dozens and dozens of alpha versions listed. For example, version 7.13.2 has 12(!) alpha versions!
Can we document what the difference is between all of these, and why there are so many?

### Affected URL(s)

Unsure

**Comment by JoshuaKGoldberg** [comment]
> Can we document what the difference is between all of these, and why there are so many?

https://typescript-eslint.io/users/releases#canary:

> We release a canary version for each commit to `main` that passes all required checks.

Do we really need to add more docs than that? Maybe this is me being grumpy late at night, but I would think it apparent that they're the latest release from `main` between version bumps?

**Comment by abrahamguo** [comment]
This is exactly what I was looking for — sorry I missed that! I think this is good 👍🏻

**Comment by JoshuaKGoldberg** [comment]
Awesome, phew! Thanks for filing 🙂 glad the docs are helpful!
