### ISSUE TITLE
Deprecate return-await option "never"

### ISSUE THREAD

**Issue by kirkwaiblinger** [typescript-eslint/typescript-eslint#9433]
## Overview

Doc: https://typescript-eslint.io/rules/return-await#never

The "never" option really just enforces wrong and confusing behavior in error-handling scenarios. In https://github.com/typescript-eslint/typescript-eslint/pull/9364#discussion_r1651963801 / https://github.com/typescript-eslint/typescript-eslint/pull/9364#discussion_r1651965667 we're trying to update the docs in `return-await` and I'm finding it hard to say when you would want to use the option. @JoshuaKGoldberg and I are thinking this may be a reasonable time to just deprecate it rather than trying too hard to find something nice to say.

Note that 
  - the base rule no-return-await has unconditionally acted like "in-try-catch", not "never", since 2016 (see https://github.com/eslint/eslint/pull/7582) and eslint never added a "never" option
  - I can't find any issues in our repo related to "never"
  -  the original motivation was more of an "it's easy to code up" than a terribly intentional justification (see https://github.com/typescript-eslint/typescript-eslint/issues/994)

It looks like very few people are using this option: https://sourcegraph.com/search?q=context:global+file:.*eslint%7Cjs%7Cjson%7Cyaml%7Cyml%7Cyaml.*+/%40typescript-eslint%5C/return-await.*never/+-file:.*node_modules.*+-file:dist%5C/.*+count:200000&patternType=standard&sm=0

I propose we document it as deprecated (in #9364), to be removed in a future major version.

**Comment by kirkwaiblinger** [comment]
One thing to add - if anyone wants to prohibit _all_ `return await`, and prefers `const x = await foo; return x;`, I would recommend:
- use no restricted syntax selector: `ReturnStatement > AwaitExpression`;
- AND enable `return-await` with 'always'.

That way, neither `return promise` or `return await promise` will ever be legal, and you'll be forced to add an intermediate variable.

**Comment by Josh-Cena** [comment]
> As a side note, I sometimes wish there was page where you could see list of useful syntax to disallow with some examples.

https://github.com/typescript-eslint/typescript-eslint/issues/5863

**Comment by kirkwaiblinger** [comment]
> But just a feedback, I think it’s not been very clear what the options do and when you want to use which option. 

Fully agree! This and some of the other promise rules are an area of active focus for improving the docs, and clarity in general. 🙂
