### ISSUE TITLE
Docs: Broken links in /packages/eslint-plugin/docs/rules/README.md

### ISSUE THREAD

**Issue by justvamp** [typescript-eslint/typescript-eslint#9434]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Some of the links in [eslint-plugin README](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/README.md) are not working.

I've created a PR fixing this: _(coming later, after this issue will be labeled as "accepting prs"...)_

### Affected URL(s)

n/a

**Comment by Josh-Cena** [comment]
This is source code. It's not meant to be read on GitHub, but on our website. If there's any fix needed, it should be to add the same warning as https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/array-type.mdx and enforce it in CI.
