### ISSUE TITLE
eslint-plugin: Back-port new rules around empty object types from v8

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9437]
## Overview

Back in #8977 on the `v8` `branch`, we'd deprecated `ban-types` + `no-empty-interfaces` and split functionality into a new [`no-empty-object-type`](https://v8--typescript-eslint.netlify.app/rules/no-empty-object-type) rule. Yay!

Coming over from https://github.com/typescript-eslint/typescript-eslint/pull/8977#issuecomment-2079376537: there's no reason why we couldn't also add that rule in v7 too. We can leave it out of recommended rulesets for now, and just have it available if users want to use it in the meantime.

💖

**Comment by Vinccool96** [comment]
Leave this to me!

**Comment by JoshuaKGoldberg** [comment]
@Vinccool96 your enthusiasm is noted and appreciated 😄 thanks! But, we generally try to avoid "cookie licking" in the issue tracker: https://typescript-eslint.io/contributing/issues#issue-claiming. Sometimes folks will claim an issue and then drop out, leaving it hanging ("licked").

**Comment by Vinccool96** [comment]
Is it normal that, in the v8 version of the rule, this doesn't create an error?

```ts
interface Base {
  name: string;
}
interface Derived {
  age: number;
}
// valid because extending multiple interfaces can be used instead of a union type
interface Both extends Base, Derived {}
```

I know it says in the comment `valid because extending multiple interfaces can be used instead of a union type`, but (the default option of `allowInterfaces` is `never`, so why is this valid?

**Comment by JoshuaKGoldberg** [comment]
That would be a separate discussion or issue from this one 🙂. Off the top of my head I don't remember, and it would be good to have that as a standalone discoverable discussion/issue.

**Comment by Vinccool96** [comment]
How do I make the playground use v8 for the issue?

**Comment by JoshuaKGoldberg** [comment]
https://v8--typescript-eslint.netlify.app/play
