### ISSUE TITLE
Docs: Need example settings and projects for React

### ISSUE THREAD

**Issue by chrisl777** [typescript-eslint/typescript-eslint#9440]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

It'd be nice if there were more practical examples in the documentation, for what we're used to with the old way of setting up. 

For example, I'm used to setting up for React, and now all the examples I'm finding in blogs are outdated. 

-How to set up with React 
-How to use with other plugins: eslint-plugin-react-hooks

etc. 

It is also odd that there's no "examples" folder in the repo with a bunch of real-world examples. It would be super helpful! 

### Affected URL(s)

https://typescript-eslint.io/packages/typescript-eslint

**Comment by Josh-Cena** [comment]
There is nothing special you need to do to configure ts-eslint for React. The "configurations" you are looking for should come from eslint-plugin-react, eslint-plugin-react-hooks, etc., but none of those plugins support flat config yet. You should ask them for docs instead.

**Comment by bradzacher** [comment]
In addition to what Josh said - the only docs we provide are lightweight quickstart docs for how to use our specific tooling.

This is on purpose because:
- we do not own the flat config spec itself - that is owned by ESLint itself and is well documented in their docs (linked from our guide).
- we do not own other 3rd party plugins and so cannot speak to how they need to ve setup. Though at their core it is as Josh mentioned - their base is all the same, though there may be extra config required by the plugin as per their docs.

Our focus is how to get a user from 0 to "linting TS code with best practices" as quick as possible. Beyond that it is up to the user to read the extra docs we link to and learn.

**Comment by chrisl777** [comment]
Okay, that makes sense. 

In case anyone winds up here trying to use ESLint v9.0.0 and React, these were helpful links to getting up and running, especially if you're familiar with the legacy format: 

- https://github.com/facebook/react/issues/28313#issuecomment-2180984628 
- https://github.com/facebook/react/issues/28313#issuecomment-2192422024
- https://eslint.org/docs/latest/use/configure/migration-guide
- https://eslint.org/blog/2024/05/eslint-compatibility-utilities/

Based on the above references, this `eslint.config.js` worked for me: 

```
// @ts-check

import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import { fixupPluginRules } from "@eslint/compat";
import eslintPluginReactHooks from 'eslint-plugin-react-hooks';
import eslintPluginReact from 'eslint-plugin-react';

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  { files: ['**/*.{js,mjs,cjs,ts,jsx,tsx}'] },
  {
    ignores: [
      "eslint.config.*",
      "amplify-codegen-temp/models/models"
    ],
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      // eslint-disable-next-line
      // @ts-ignore
      "react-hooks": fixupPluginRules(eslintPluginReactHooks),
      "react": eslintPluginReact
    },
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        project: true,
      },
    },
    rules: {
      "no-unused-vars": "off", // Turn off this one in favor of @typescript-eslint/no-unused-vars. See: https://typescript-eslint.io/rules/no-unused-vars/#options
      "@typescript-eslint/no-unused-vars": [
        "off", 
        { 
          // Put an underscore in front of a variable to suppress the warning. 
          "argsIgnorePattern": "^_", 
          "varsIgnorePattern": "^_",
          "caughtErrorsIgnorePattern": "^_"
        }
      ],
      '@typescript-eslint/no-unsafe-argument': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-call': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      "@typescript-eslint/no-explicit-any": "warn",
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn"
    },
  },
);
```

In addition, I had to add this shim file `eslint-plugin-react-hooks.d.ts`: 

```
// This is only a type-shim and is not meant to be a perfect representation of eslint-plugin-react-hooks.

declare module 'eslint-plugin-react-hooks' {
	import type { ESLint } from 'eslint';
	const plugin: Omit<ESLint.Plugin, 'configs'> & {
		// eslint-plugin-react-hooks does not use FlatConfig yet
		configs: Record<string, ESLint.ConfigData>;
	};
	export default plugin;
}
```

After entering these files, in VS Code I had to restart the ESLint Server, with Shift+Command+P, then select "ESLint: Restart ESLint Server."
