### ISSUE TITLE
Repo: don't install dependencies for the entire repo in "Semantic Breaking Change PR" workflow

### ISSUE THREAD

**Issue by auvred** [typescript-eslint/typescript-eslint#9447]
### Suggestion

Is there any reason why we want to install deps before running the `breaking-pr-check` action? It does not import any repo-specific packages:

https://github.com/typescript-eslint/typescript-eslint/blob/40fed48b9ced4da9fd905790850c36907ae363a7/.github/actions/breaking-pr-check/index.js#L1-L4

Suggestion: let's remove this line?

https://github.com/typescript-eslint/typescript-eslint/blob/40fed48b9ced4da9fd905790850c36907ae363a7/.github/workflows/semantic-breaking-change-pr.yml#L18

---

I noticed this, because it takes ~2 mins to run `prepare-install` and ~0 seconds to validate PR title (https://github.com/typescript-eslint/typescript-eslint/actions/runs/9712997933/job/26808863383?pr=9444)

![prepare-install action took 2 minutes to run and breaking-pr-check finished instantly](https://github.com/typescript-eslint/typescript-eslint/assets/61150013/2a3571c3-82c7-435d-ae1b-afb0ac6b8704)

cc @yeonjuan

**Comment by JoshuaKGoldberg** [comment]
🤷. If removing them doesn't break anything, then great, let's remove them!
