### ISSUE TITLE
Docs: clarify how to fix "Too many files (>8) have matched the default project"

### ISSUE THREAD

**Issue by JavaScriptBach** [typescript-eslint/typescript-eslint#9450]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I have been unable to upgrade typescript-eslint past 7.5.0; doing so gives a "Too many files have matched the default project" whenever I try to lint.

My languageOptions are

```
languageOptions: {
    parser: tseslint.parser,
    parserOptions: {
      EXPERIMENTAL_useProjectService: true,
    },
  },
```

The error I'm getting:

```
common:lint: <redacted path>
common:lint:   0:0  error  Parsing error: Too many files (>8) have matched the default project.
common:lint: 
common:lint: Having many files run with the default project is known to cause performance issues and slow down linting.
common:lint: 
common:lint: See https://typescript-eslint.io/troubleshooting/typed-linting#allowdefaultprojectforfiles-glob-too-wide
common:lint: 
common:lint: Matching files:
common:lint: - /<redacted path>/node_modules/tinycolor2/esm/tinycolor.js
common:lint: - /<redacted path>/node_modules/date-fns/esm/endOfMonth/index.js
common:lint: - /<redacted path>/node_modules/date-fns/esm/lastDayOfMonth/index.js
common:lint: - /<redacted path>/node_modules/date-fns/esm/startOfDay/index.js
common:lint: - /<redacted path>/node_modules/date-fns/esm/startOfISOWeek/index.js
common:lint: - /<redacted path>/node_modules/date-fns/esm/startOfMonth/index.js
common:lint: - /<redacted path>/node_modules/date-fns/esm/subDays/index.js
common:lint: - /<redacted path>/node_modules/date-fns/esm/subMonths/index.js
common:lint: - /<redacted path>/node_modules/sinon/pkg/sinon-esm.js
common:lint: 
common:lint: If you absolutely need more files included, set parserOptions.EXPERIMENTAL_useProjectService.maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING to a larger value
```

I've read various issues and docs and none of them answer my question.

- The [FAQ](https://typescript-eslint.io/troubleshooting/typed-linting/#i-get-errors-telling-me-having-many-files-run-with-the-default-project-is-known-to-cause-performance-issues-and-slow-down-linting) tells me I've configured `allowDefaultProjectForFiles` with too wide a glob. This isn't true; I haven't configured the property at all and I can't find what its default is anywhere.
- I found https://github.com/typescript-eslint/typescript-eslint/issues/9032 but it was closed and the issue still persists when I try to use the latest 7.x.

I'm certainly open to the possibility that something is wrong with my linting configuration, but I couldn't find anything in the docs to help me investigate this. (Are `node_modules` files supposed to be opened by typescript-eslint?)

From my perspective, it looks like a breaking change was released and it would be nice to at least clarify in the docs how folks with a previously working v7 config can upgrade.

### Affected URL(s)

https://typescript-eslint.io/troubleshooting/typed-linting/#i-get-errors-telling-me-having-many-files-run-with-the-default-project-is-known-to-cause-performance-issues-and-slow-down-linting

**Comment by bradzacher** [comment]
> I'm certainly open to the possibility that something is wrong with my linting configuration

That's good - because your config is wrong.

Notice the file paths reported in the error?
They're all in `node_modules`! 

Your config is setup to lint your `node_modules` folder. This is (obviously) not correct.

---

The default allows all files - essentially an implicit `**/*.js`. But that's irrelevant here because your problem isn't to do with that.

**Comment by JavaScriptBach** [comment]
@bradzacher Thanks for the response! I did suspect that linting `node_modules` is incorrect, but I have a config object in my `eslint.config.js` that ignores `node_modules/**`. Where else do I have to ignore `node_modules/` to get typescript-eslint to ignore it?

**Comment by bradzacher** [comment]
It's hard to say without seeing your config.
The only thing I could do is link you to the relevant docs
https://eslint.org/docs/latest/use/configure/configuration-files#globally-ignoring-files-with-ignores

**Comment by JoshuaKGoldberg** [comment]
We should definitely rework the docs for the v8 launch. +1 that saying _"you've configured too wide a glob"_ when the user never explicitly configured that glob is a little off.

**Comment by JoshuaKGoldberg** [comment]
> it looks like a breaking change was released

Nit: no, the option is explicitly still an experimental one not covered by semver. It's mentioned in the name (`EXPERIMENTAL_*`) and docs (https://typescript-eslint.io/packages/parser#experimental_useprojectservice). We wanted it to be experimental and available in prod so awesome users can report awesome issues like this one. 😄

**Comment by JavaScriptBach** [comment]
Fair enough, thanks for your help. I'll work on getting a minimal repro for the node_modules issue.

Looking forward to v8!

**Comment by JavaScriptBach** [comment]
My issue has something to do with code that imports from `date-fns`. I'm not sure why ESLint is parsing those files because they should be ignored, but it also shouldn't be parsing ESM files because I'm on CJS. Anyways, I upgraded `date-fns` from v2 to v3, which should correctly export as a dual package, and the problem went away.

**Comment by bradzacher** [comment]
You're likely using eslint-plugin-import and you're using rules from it that do cross-file parsing
https://typescript-eslint.io/troubleshooting/typed-linting/performance#eslint-plugin-import

**Comment by JavaScriptBach** [comment]
@bradzacher right on the money! Turning off `import/no-named-as-default` fixed the issue. Thanks for your help and patience.

**Comment by TotomInc** [comment]
Hey, I've wanted to add a bit more to this issue. I have the same error, however I believe my ESLint setup is correct (using the popular Antfu ESLint config with a few tweaks).

I've wanted to use tsconfig project references by enabling `parserOptions.EXPERIMENTAL_useProjectService` and I've got the same error as @JavaScriptBach, but pointing out actual source-code files and not `node_modules` files:

```
/<redacted>/src/components/ui/VueSelect.vue
  0:0  error  Parsing error: Too many files (>8) have matched the default project.

Having many files run with the default project is known to cause performance issues and slow down linting.

See https://typescript-eslint.io/troubleshooting/typed-linting#allowdefaultprojectforfiles-glob-too-wide

Matching files:
- /<redacted>/src/App.vue
- /<redacted>/cypress/support/e2e.ts
- /<redacted>/cypress/support/commands.ts
- /<redacted>/src/components/faq-accordion/FaqAccordion.vue
- /<redacted>/src/views/HomeView.vue
- /<redacted>/src/components/faq-accordion/FaqAccordionSlideItem.vue
- /<redacted>/src/components/header/HeaderAwards.vue
- /<redacted>/src/components/SiteFooter.vue
- /<redacted>/src/components/header/HeaderStars.vue
- /<redacted>/src/components/header/HeaderBackground.vue
- /<redacted>/src/components/icons/AcademicCapIcon.vue
- /<redacted>/src/components/faq-accordion/FaqAccordionButton.vue
- /<redacted>/src/components/faq-accordion/FaqAccordionSlide.vue
- /<redacted>/src/components/icons/StarHalfFilledIcon.vue
- /<redacted>/src/components/icons/StarIcon.vue
- /<redacted>/src/components/ui/Logo.vue
- /<redacted>/src/components/ui/VueSelect.vue

If you absolutely need more files included, set parserOptions.EXPERIMENTAL_useProjectService.maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING to a larger value
```

I agree that using the following code works, but seems hacky and the official documentation is lacking about possible properties for the `EXPERIMENTAL_useProjectService` object:

```js
parserOptions: {
  EXPERIMENTAL_useProjectService: {
    maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING: 1000
  },
}
```

Is there a better workaround than setting `maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING` at the moment? Does it will affect _a lot_ the linting speed/performance?

Note: I cannot use a `tsconfig.eslint.json` for type-aware linting in my case, as it was causing an issue. I've noticed that using `EXPERIMENTAL_useProjectService` fixes the issue, that's why I'm using it.

**Comment by bradzacher** [comment]
@TotomInc have you checked out our FAQ
https://typescript-eslint.io/troubleshooting/faqs/frameworks/#i-use-a-framework-like-vue-that-requires-custom-file-extensions-and-i-get-errors-like-you-should-add-parseroptionsextrafileextensions-to-your-config

**Comment by TotomInc** [comment]
Sure, I've already explored the FAQ & typed-linting docs. I'll give more context as I can see it's a bit hard to understand (my bad!).

- I'm building a Flat ESLint Config (for Vue 3 + TS projects) on-top of the [popular Antfu's ESLint Config](https://github.com/antfu/eslint-config).
- This means the Vue setup is most probably already working well.
- The ESLint Config I'm working on, extends Antfu's config by providing Flat Config objects. Here's a quick example of what my custom ESLint config approximately looks like:

```ts
import antfu, { GLOB_SRC, GLOB_VUE } from "@antfu/eslint-config";
import prettier from "eslint-plugin-prettier";

// The config exported by the package & ready to be used on parent projects.
async function customEslintConfig(customConfig, ...userConfigs) {
  return antfu(
    {
      // ... here goes custom properties defined by Antfu's config.
      // We can pass extra TypeScript related options for the parser:
      typescript: {
        // This goes to a tsconfig.json that references multiple projects.
        tsconfigPath: customConfig.tsconfigPath,
        parserOptions: {
          EXPERIMENTAL_useProjectService: {
            maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING: 1000
          },
        }
      }
    },
    {
      // Overriding some rules, integrating Prettier.
      files: [GLOB_SRC, GLOB_VUE],
      plugins: { prettier },
      rules: {
        "prettier/prettier": ["error", { /* ... Prettier config */ }],
        // And a lot of extra rules goes here...
        "sort-imports": ["off"],
      }
    },
    // Allow user to pass extra configs.
    ...userConfigs,
  );
}

export { customEslintConfig };
```

- Custom file-extensions for the TypeScript parser [are already well configured](https://github.com/antfu/eslint-config/blob/main/src/configs/typescript.ts#L73). My VSCode ESLint extensions logs `['.vue']` are properly set as `parserOptions.extraFileExtensions`.

- The custom ESLint config is then consumed like this on a parent project:

```ts
// eslint.config.js
import { customEslintConfig } from "@my-org/my-custom-eslint-config";
export default customEslintConfig({ tsconfigPath: "tsconfig.json" });
```

```jsonc
// tsconfig.json -- uses project references (the default template from Vite + Vue 3 + TS)
{
  "compilerOptions": { "module": "NodeNext" },
  "references": [
    { "path": "./tsconfig.node.json" },
    { "path": "./tsconfig.app.json" }
  ],
  "files": []
}
```

I've noticed that the error message `Too many files (>8) have matched the default project.` only appears when running the command `eslint .`. It doesn't appear on the VSCode ESLint extension output.

Would you like a minimal reproduction repository (Vite + Vue 3 + TS + custom ESLint config w/ Antfu) if this is worth investigating?

Thanks a lot for your time @bradzacher

**Comment by alexey-koran** [comment]
Hi, I've got the same issue, investigated a bit and found that it's because wasn't deleted projectService from parserOptions here https://github.com/import-js/eslint-plugin-import/blobfc361a9998b14b9528d841d8349078a5af2da436/utils/parse.js#L136

@TotomInc please, also have a look here https://github.com/typescript-eslint/typescript-eslint/issues/9223

I deleted that property locally and it helps
As a temporary fix u can try to add to your eslint.config.js [import/ignore](https://github.com/import-js/eslint-plugin-import?tab=readme-ov-file#importignore):

```js
settings: {
  'import/ignore': 'node_modules',
}
```
