### ISSUE TITLE
Repo: "Open in Playground" does not report errors it should

### ISSUE THREAD

**Issue by kkmuffme** [typescript-eslint/typescript-eslint#9451]
### Suggestion

https://typescript-eslint.io/rules/no-unused-expressions/
If you click on "Open in Playground" for the "Incorrect" example, the playground says:
>All is ok!

But there should be an error in playground, as that's the "incorrect" example.

**Comment by kirkwaiblinger** [comment]
Hi @kkmuffme! 
When I click on it, I do see the "All is ok!" message briefly while the playground is loading, but then I see the errors. Could you double check if you're able to repro? And if so provide a bit more detail that might help us debug?
Thanks!

**Comment by bradzacher** [comment]
It works fine for me too.

![Screenshot_20240629-095938.png of working](https://github.com/typescript-eslint/typescript-eslint/assets/7462525/29877937-4fa0-4c7a-9abe-ad720d304d0c)
