### ISSUE TITLE
Rule "@typescript-eslint/return-await": ['error',"in-try-catch"] doesnt work properly

### ISSUE THREAD

**Issue by RadoslavMarinov** [typescript-eslint/typescript-eslint#9454]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.2&fileType=.tsx&code=FAQwzgngdgxgBAMwK6wC4EsD2U4FsTpQAUAlHAN7BxwD0NcAbiAE5wgDcVcqzEFX1ZgFNUSZjh4QA6gVREATAAZFJTtQC%2BcGCFQwAFhTjrgx4MjRYcAd1kBZMEVxgAXHChJcAIyHMylQSJiOFBCVnAACsyYuOhgQkREwmCYADYMQmQAvAB8cHGoACrouEKYSHJJqekANHhgJKomwGYoMBjY3Lwy6HJOru5ePn5ckvzUAaLicDY99o71akZaOvpwRD5RvobGpviEpJxAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6aRfWaJ2gQwDufSvnRgA2pETRoAe2iQANOGw5mtfNEK0yffGQAWkFRAC6KgL4gLQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
async function main() {
  // var a;
  try {
    return tryWait(200);
  } catch {}
}

function waitMs(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function tryWait(ms: number) {
  try {
    return waitMs(ms);
  } catch (error) {}
}

main();
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/return-await": ["error",
      "in-try-catch"
    ]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

I expect error on line 15 too

Returning an awaited promise is required in this context.ESLint[@typescript-eslint/return-await](https://typescript-eslint.io/rules/return-await)

### Actual Result

I dont see such error

### Additional Info
The function tryWait is not async but the same problem applies
_No response_

**Comment by Josh-Cena** [comment]
Inclined to say this is working as intended because this function is not async so you cannot possibly add `await` there. @kirkwaiblinger probably has better opinions here.

**Comment by kirkwaiblinger** [comment]
Hmm, yeah I've noticed this as well, and it has given me pause as well.

> Inclined to say this is working as intended because this function is not async so you cannot possibly add `await` there. 

Agreed - my knowledge isn't exhaustive here, but I haven't come across any hint that this rule has ever been intended to work on non-async functions (and several thoughts come to mind of why that wouldn't have been considered historically). So I am also inclined to believe this is working as intended.

As to whether that intention is correct, I am tentatively in agreement with the current behavior for two reasons
- like Josh mentioned, there isn't a clear recourse if the rule did flag in that case, since `await` cannot be added in a non-async function
- you can prevent this case coming up in the first place with [promise-function-async](https://typescript-eslint.io/rules/promise-function-async/) (which I would recommend enabling)

Personally, my opinion isn't set in stone on this yet, though, and it may be possible to convince me otherwise.

**Comment by kirkwaiblinger** [comment]
Actually - this was an explicitly changed as a bugfix, see https://github.com/typescript-eslint/typescript-eslint/issues/1930

**Comment by kirkwaiblinger** [comment]
For historical context, though, this was originally an extension of the (now-deprecated) eslint base rule [no-return-await](https://eslint.org/docs/latest/rules/no-return-await), which, _to this day_ does not _explicitly_ check for whether a function is async. The reason for that is that, without type information, they could only flag locations where the `await` keyword is present, which is only inside `async` functions to begin with; therefore, an explicit check for `async` would be redundant in the base rule. Given that context, the change in #1930 seems like very much the correct decision at the time in the name of parity with the base rule. 

_However_, now that `@typescript-eslint/return-await` is no longer being treated as an extension of eslint's `no-return-await`, and, therefore, parity with the base rule is not really a concern anymore, there _might_ be a possibility to revisit that intention. I'm open to hearing thoughts.

**Comment by bradzacher** [comment]
This is working as intended yeah.
`promise-function-async` will enforce you mark the function as `async`, which will then cause `return-await` to fire.
[playground](https://typescript-eslint.io/play/#ts=5.5.2&fileType=.tsx&code=FAQwzgngdgxgBAMwK6wC4EsD2U4FsTpQAUAlHAN7BxwD0NcAbiAE5wgDcVcqzEFX1ZgFNUSZjh4QA6gVREATAAZFJTtQC%2BcGCFQwAFhTjrgx4MjRYcAd1kBZMEVxgAXHChJcAIyHMylQSJiOFBCVnAACsyYuOhgQkREwmCYADYMQmQAvAB8cHGoACrouEKYSHJJqekANHhgJKomwGYoMBjY3Lwy6HJOru5ePn5ckvzUAaLicDY99o71akZaOvpwRD5RvobGpviEpJxAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6aRfWaJ2gQwDufSvnRgA2pETRoAe2iQANOGw5mtfNEK0yffGQAWkFRAC6y1XiKlkFanQbM2xOQFtKyRLQBmsJmXxKWV4%2BZEJ-MSkZeWMIAF8QOKA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)
