### ISSUE TITLE
Repo: add GitHub action to auto-close issues that have been resolved in the `v8` branch

### ISSUE THREAD

**Issue by auvred** [typescript-eslint/typescript-eslint#9458]
### Suggestion

Since `v8` is not the default branch, GitHub doesn't close the issue automatically when a linked PR is merged into `v8`. It's hard to always remember to close the issue manually when merging PRs into the `v8`.

What do you think about adding a GH action to do this automatically? I found a https://github.com/ldez/gha-mjolnir. It looks like this action should do the trick.

**Comment by StyleShit** [comment]
Oh, yeah... I just wondered why it didn't close an issue automatically when my PR was merged.

+1 from me 😄

**Comment by JoshuaKGoldberg** [comment]
dear heavens yes please 😭

**Comment by JoshuaKGoldberg** [comment]
Resolved by #9464 in `v8`. Amusingly, that didn't resolve this issue because it's into `v8`.

@auvred do you want to also send that into `main`?

**Comment by auvred** [comment]
The workflow doesn't seem to have the necessary permissions to work with issues: https://github.com/typescript-eslint/typescript-eslint/actions/runs/9743648807/job/26887562289. Here is the second attempt: https://github.com/typescript-eslint/typescript-eslint/pull/9466 :smile:
