### ISSUE TITLE
[prefer-readonly] doesn't recognize destructuring assignments

### ISSUE THREAD

**Issue by mysticatea** [typescript-eslint/typescript-eslint#946]
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/prefer-readonly": ["error"]
  }
}
```

```TS
class C {
    private value: number = 0

    update(config: any) {
        ({value: this.value} = config)
        return this.value
    }
}
```

**Expected Result**

No errors.

**Actual Result**

```
~\dev\sandbox> eslint test.ts

~\dev\sandbox\test.ts
  2:5  error  Member 'value' is never reassigned; mark it as `readonly`  @typescript-eslint/prefer-readonly

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.1.1-alpha.4` |
| `@typescript-eslint/parser`        | `2.1.1-alpha.4` |
| `TypeScript`                       | `3.6.2` |
| `ESLint`                           | `6.3.0` |
| `node`                             | `12.10.0` |
| `npm`                              | `6.11.2` |

**Comment by mysticatea** [comment]
And the autofix of that rule generates broken code.

**Comment by bradzacher** [comment]
Yup definite bug because that syntax is pretty rare.

I don't think I've ever seen someone use a destructuring assignment as a side-effect to update a class prop.
