### ISSUE TITLE
Docs: show importing configs in shared configs page

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9471]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Right now in https://typescript-eslint.io/users/configs, we never fully show how to use one of the preset configs. We show using them as a property of some `tseslint` object, but not how to actually create that object.

The configs page does link to other pages, but it's a little annoying & confusing to have to retain the convention & memory in your own. I'd suggest we include a little refresher blurb on the top:

```diff
## Getting Started

See [Getting Started > Quickstart](../getting-started/Quickstart.mdx) first to set up your ESLint configuration file.
[Packages > typescript-eslint](../packages/TypeScript_ESLint.mdx) includes more documentation on the `tseslint` helper.

+ ```ts
+ import tseslint from 'typescript-eslint';
+
+ export default tseslint.config(
+   // ...
+ );
+ ```

### Projects Without Type Checking
```

### Affected URL(s)

https://typescript-eslint.io/users/configs

💖 

This came out of a pairing with @Tobbe going over migrating Redwood from legacy config to flat config. Therefore:

Co-authored-by: @Tobbe

**Comment by yaodada123** [comment]
@JoshuaKGoldberg Hi, I think I can do this task. Can you assign it to me?

**Comment by JoshuaKGoldberg** [comment]
Hey, glad you're interested in the task! Per [our issue contributing guidelines](https://typescript-eslint.io/contributing/issues#issue-claiming), you can go ahead and do it. We don't assign issues. Have fun!

**Comment by yaodada123** [comment]
@JoshuaKGoldberg Hello, I have successfully submitted the pr, but it seems that the submission title is not perfect.Hoping for criticism and correction
