### ISSUE TITLE
Unmet Peer Dependency with "utils" when using ESLint v9

### ISSUE THREAD

**Issue by CxRes** [typescript-eslint/typescript-eslint#9488]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

utils

### Repro Code

```TypeScript
pnpm add eslint@9
pnpm add @typescript-eslint/utils@7.14.1
```

### Expected Result

No unmet peer dependency should happen when used with ESLint v9

### Actual Result

 @typescript-eslint/utils 7.14.1
  └── ✕ unmet peer eslint@^8.56.0: found 9.5.0

### Additional Info

I am actually using a project eslint-plugin-vitest which has @typescript-eslint/utils as a peer dependency (I am not even using TS). I get unmet peer dependency because I am using ESLint v9 and the package uses refers to "^8.56". See https://github.com/veritem/eslint-plugin-vitest/issues/477 which does not resolve even when the repo author has updated to latest version of @typescript-eslint/utils in the linked PR.

Seriously, this is one character change fix ^8.56 to >8.56 which I am unable to PR, because of the bureaucracy in this repo.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/utils`     | `7.14.1` |
| `ESLint`                               | `9.5.0` |
| `node`                                 | `22.3.0` |

**Comment by Vinccool96** [comment]
typescript-eslint v7 is not the one working with eslint v9. You want to install typescript-eslint rc-v8 (which is still in alpha)

**Comment by Vinccool96** [comment]
You might want to look at #8211

**Comment by bradzacher** [comment]
Please use the search - or just look to the pinned issues.
