### ISSUE TITLE
Try out v8 beta on various influential plugins

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9501]
V8 is ready for public testing (hooray! https://typescript-eslint.io/blog/announcing-typescript-eslint-v8-beta 🎉) and we want to make sure we try it out on lots of ESLint plugins. It'd be particularly valuable to try out plugins that are:

- Using typescript-eslint at least as a devDependency in its own ESLint config and to create rules
- Popular enough to get visibility for the v8 beta in front of many people _(think >100 GH stars)_
- Is a community-run free open source project (or run by a company that sponsors us)

I'm thinking to start, at least:

- ~[`@angular-eslint`](https://github.com/angular-eslint/angular-eslint)~ they're already on the betas! Nicely done @JamesHenry 😄 
- [`eslint-plugin-functional`](https://github.com/eslint-functional/eslint-plugin-functional): (blocked on https://github.com/RebeccaStevens/eslint-config-rebeccastevens/pull/1177)
- [`eslint-plugin-jest`](https://github.com/jest-community/eslint-plugin-jest): https://github.com/jest-community/eslint-plugin-jest/pull/1623
- [`eslint-plugin-jsonc`](https://github.com/ota-meshi/eslint-plugin-jsonc): https://github.com/ota-meshi/eslint-plugin-jsonc/pull/351
- [`eslint-plugin-perfectionist`](https://github.com/azat-io/eslint-plugin-perfectionist): _(blocked on https://github.com/azat-io/eslint-config/issues/7)_
- [`eslint-plugin-regexp`](https://github.com/ota-meshi/eslint-plugin-regexp): https://github.com/ota-meshi/eslint-plugin-regexp/pull/753
- [`eslint-plugin-vitest`](https://github.com/veritem/eslint-plugin-vitest): https://github.com/veritem/eslint-plugin-vitest/pull/479
- [`eslint-plugin-yml`](https://github.com/ota-meshi/eslint-plugin-yml): https://github.com/ota-meshi/eslint-plugin-yml/pull/346
- [`eslint-stylistic`](https://github.com/eslint-stylistic/eslint-stylistic): https://github.com/eslint-stylistic/eslint-stylistic/pull/452

For each of these projects, we should send them a draft PR updating to the latest beta. Filing this tracking issue to make sure we do this before releasing v8 as stable.

<details>
<summary>Projects we've tentatively omitted from this list</summary>

If you think any of these should be added to the list, let us know!
We're happy to learn we were wrong to omit one.

* [`eslint-plugin-es-x`](https://github.com/eslint-community/eslint-plugin-es-ex): only uses `@typescript-eslint/parser` for testing
* [`eslint-plugin-eslint-comments`](https://github.com/eslint-community/eslint-plugin-eslint-comments): does not use any typescript-eslint packages directly
* [`eslint-plugin-eslint-plugin`](https://github.com/eslint-community/eslint-plugin-eslint-plugin): only uses `@typescript-eslint/parser` for testing
* [`eslint-plugin-n`](https://github.com/eslint-community/eslint-plugin-n): only uses `@typescript-eslint/parser` for testing and `@typescript-eslint/typescript-estree` for a type
* [`eslint-plugin-promise`](https://github.com/eslint-community/eslint-plugin-promise): only uses `@typescript-eslint/parser` for testing
* [`eslint-plugin-security`](https://github.com/eslint-community/eslint-plugin-security): does not use any typescript-eslint packages directly

</details>

> If you've got a project that matches those criteria & want to get it added to the list, let us know! We'd be happy to work with you.

Sibling issue to try v8 out on end-user repositories: #9141

**Comment by antfu** [comment]
For reference, ESLint Stylistic has a beta branch that migrated to v8 already: https://github.com/eslint-stylistic/eslint-stylistic/pull/452

**Comment by SukkaW** [comment]
`eslint-react` project is currently on typescript v8 alpha: https://github.com/Rel1cx/eslint-react/issues/554, https://github.com/Rel1cx/eslint-react/pull/561

**Comment by EvgenyOrekhov** [comment]
Would be good to include [eslint-plugin-sonarjs](https://github.com/SonarSource/eslint-plugin-sonarjs) (1.2k GitHub stars, 1 million weekly downloads)

**Comment by SukkaW** [comment]
`eslint-plugin-import-x` is adapting v8 beta!

https://github.com/un-ts/eslint-plugin-import-x/pull/112

**Comment by JoshuaKGoldberg** [comment]
> [eslint-plugin-sonarjs](https://github.com/SonarSource/eslint-plugin-sonarjs)

Ah, that's a good idea - but it's run by a company that doesn't actually sponsor us. I've added a note to the OP description to exclude that case.

(if anybody from SonarSource is reading this, you're welcome to change the situation! 😉)

**Comment by JoshuaKGoldberg** [comment]
The checklist in the OP is full of created PRs and discovered issues have been filed on our end. We're gearing up for the v8 release Soon ™️ (🤞) so I'll close this issue out.

**THANK YOU** to everyone who participated on this thread and/or the PRs! We really appreciate it! ❤️

**Comment by SukkaW** [comment]
> The checklist in the OP is full of created PRs and discovered issues have been filed on our end. We're gearing up for the v8 release Soon ™️ (🤞) so I'll close this issue out.
> 
> **THANK YOU** to everyone who participated on this thread and/or the PRs! We really appreciate it! ❤️

Would you mind taking a look at https://github.com/un-ts/eslint-plugin-import-x/pull/112? We have faced a few difficulties here and there. Would you mind sharing a few suggestions?

**Comment by JoshuaKGoldberg** [comment]
For visibility: now that v8 is released, I'll go through and update the draft PRs I'd sent over the next couple of days.
