### ISSUE TITLE
eslint-plugin: Also backport no-unsafe-function-type and no-wrapper-object-types from v8 to main

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9505]
## Overview

Continuing #9437 -> #9443: two additional rules were split out of `ban-types` that we'll want to backport from the `v8` branch to `main`:

* https://v8--typescript-eslint.netlify.app/rules/no-unsafe-function-type
* https://v8--typescript-eslint.netlify.app/rules/no-wrapper-object-types

I'll take this on so we can get it in the weekly release in two days.

cc @Vinccool96 as FYI: your PR was excellent, so I'm going to do the same thing here. 🙂 

💖

**Comment by Vinccool96** [comment]
:)
