### ISSUE TITLE
Docs: treat return-await as a standalone rule, not an extension

### ISSUE THREAD

**Issue by kirkwaiblinger** [typescript-eslint/typescript-eslint#9517]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

1. First paragraph should no longer say that this is an extension rule. 
2. Instead, an info box or similar should be created to mention that this _used to be_ an extension rule, and link an issue or two on context (as well as a link to the base rule)
3. Options should _not_ say "See [eslint/no-return-await options](https://eslint.org/docs/rules/no-return-await#options)". There are no options for the base rule and (I'm pretty sure) there never were any.

### Affected URL(s)

http://typescript-eslint.io/rules/return-await

**Comment by kirkwaiblinger** [comment]
FYI - should probably be done _after_ https://github.com/typescript-eslint/typescript-eslint/pull/9364 is merged

**Comment by JoshuaKGoldberg** [comment]
👍 seems reasonable to me. Should it still link to the ESLint core rule somewhere in the doc as a reference?

I'm also wondering, should we send any docs issues over to ESLint core to clarify things in the base rule doc?

**Comment by kirkwaiblinger** [comment]
> Should it still link to the ESLint core rule somewhere in the doc as a reference?

Yep, I think so! (That's what I was trying to say with point no. 2 in the OP).

> I'm also wondering, should we send any docs issues over to ESLint core to clarify things in the base rule doc?

None immediately comes to mind. They already have a deprecation notice with (IMO) sufficient explanation. But maybe something to keep in mind for whoever works on this to file issues if something comes up that could be improved 👍.

**Comment by JoshuaKGoldberg** [comment]
I think it'd be reasonable to disable `no-return-await`, given that the rule doesn't make sense anymore and is deprecated as a result. Not critical but a nice-to-have. 🤷
