### ISSUE TITLE
Rule proposal: strict-variable-initialization

### ISSUE THREAD

**Issue by kirkwaiblinger** [typescript-eslint/typescript-eslint#9565]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

This rule would be the analog of TS's [strictPropertyInitialization](https://www.typescriptlang.org/tsconfig/#strictPropertyInitialization) but for variables. Spelling out the correspondence, we have:

property declaration  <==> variable declaration.
   - With property declarations both `x?: string` and `x: string | undefined` may be used to specify allow the property to remain uninitialized in the constructor. In this rule, only `let x: string | undefined` can be used to allow a variable to remain uninitialized (due to `let x?: string` not being valid syntax).
   
Definitely assigned in constructor <==> definitely assigned _in the scope in which the variable is declared_.
   - So, as with strict property initialization, assigning the variable in a method/function should _not_ count - only something definitely _literally_ assigned in all branches within the scope in which it's defined.
   - This also necessarily means that the rule will still permit unsoundness if a function is called that reads the value of the variable _before_ it is set (just like you can call a method that reads a property _before_ that property is set in the constructor with strictPropertyInitialization). That's perfectly ok, and explicitly _not_ a case this rule aims to address.

### Fail Cases

```TypeScript
// top-level of file/module

let x: string
//  ~ [strict-variable-initialization] 'x' is not definitely assigned in the scope in which it is declared.

function printX() {
  console.log(x.toLocaleString()); // TypeError: Cannot read properties of undefined
}

printX();

// EOF

// Also, in nested scopes.
function iAmAScope() {
  let uninitializedString: string;
//    ~~~~~~~~~~~~~~~~~~~ [strict-variable-initialization] 'uninitializedString' is not definitely assigned in the scope in which it is declared.
  function printUninitializedString() {
    console.log(uninitializedString.toLocaleString());
  }
}

// Should flag if the variable _ever_ escapes the scope without being set.

function maybeInitializedVariable() {
    let maybeUninitialized: string;
//      ~~~~~~~~~~~~~~~~~~ [strict-variable-initialization] 'maybeUninitialized' is not definitely assigned in the scope in which it is declared.
    if (Math.random() < 0.5) {
        maybeUninitialized = 'initialized!';
    }
    function printUninitializedString() {
      // 50% of the time will result in a TypeError at runtime, but does not cause a TS error.
      console.log(uninitializedString.toLocaleString());
    }
}
```

### Pass Cases

```TypeScript
// top-level of file/module

// Making the type possibly unassigned should resolve the report.
let x: string | undefined

function printX() {
  // no longer unsafe, since this is flagged by TS
  // TS Error - 'x' is possibly 'undefined'
  console.log(x.toLocaleString()); 
}

printX();

// EOF

// Also, in nested scopes.
function iAmAScope() {
  // initializing the variable should also resolve the report,
  // even in cases where it _could_ still be unsound!
  let uninitializedString: string;
  printUninitializedString(); // TypeError at runtime
  uninitializedString = 'initialized too late!';
  
  function printUninitializedString() {
    console.log(uninitializedString.toLocaleString());
  }
}
```

### Additional Info

Note that this would prevent/address bugs as seen in https://github.com/typescript-eslint/typescript-eslint/issues/4513

Note that, despite turning on TS's "strict" mode and the `strict-type-checked` preset, nothing flags the code in the examples for failing to initialize the variables (including `no-unused-var` - since it _is_ read 🙃). Therefore, I believe the area this rule aims to cover is not covered by existing tooling.

**Comment by kirkwaiblinger** [comment]
Well, now that I'm saying all this.... I wonder if this shouldn't just be proposed to TS directly 🤔

**Comment by Josh-Cena** [comment]
This is why you should just enable `init-declarations`—no more `let x: number` because ESLint will force you to add `= undefined` and then TS will force you to add `| undefined`

**Comment by kirkwaiblinger** [comment]
> This is why you should just enable `init-declarations`—no more `let x: number` because ESLint will force you to add `= undefined` and then TS will force you to add `| undefined`

Hmm. Ok, yeah, that certainly has overlap, though, I'd argue, you're still at unable to do useful things like this....

```ts
function useX() {
    console.log(x.toString());
}

let x: string
if (Math.random() < 0.5) {
   x = 'initialized in this branch';
} else {
   x = 'also initialized in this branch';
}

useX();
```

**Comment by Josh-Cena** [comment]
I reread the proposal and I think it's much more fit as a TS option rather than a rule, because it requires complex control-flow reasoning. It would be more linter-y if we just forbid uninitialized vars without `| undefined`, or require them to be initialized with `undefined`.

**Comment by kirkwaiblinger** [comment]
Gonna close for now and file an issue with TS. Might reopen or repurpose this depending on the outcome, but no sense in it inflating the issue count in the meantime!
