### ISSUE TITLE
Rule proposal: prefer-await

### ISSUE THREAD

**Issue by abrahamguo** [typescript-eslint/typescript-eslint#9572]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Prefer using `await` rather than `.then()`/`.catch()`/`.finally()`.
This rule would use type information to detect promises, which we already have precedent for in `typescript-eslint`.
This rule could probably sometimes provide suggestions (top-level await, or inside a function which is not already `async`) or otherwise autofix.
This rule would ignore placing `then`s directly inside the array of a `Promise.all()`/`.allSettled()`/`.any()`/`.race()`.
Ideally, it would also provide a way to allow a `then` inside the callback of React's `useEffect`, which is not allowed to be async. This might be accomplished via a name-based allowlist?

### Fail Cases

```TypeScript
fetch().then(() => {})
fetch().catch(() => {})
fetch().finally() => {})
useEffect(() => void fetch().then(res => res.json()).then(setData), [])
```

### Pass Cases

```TypeScript
await fetch()
try { await fetch() } catch {}
try { await fetch() } finally {}
useEffect(() => void fetch().then(async res => setData(await res.json()), [])

// Ignored cases
Promise.all([async1(), async2a().then(async2b)])
useEffect(() => void getData().then(setData), [])
```

### Additional Info

Related rules, and how they are different:

- [eslint-plugin-unicorn/prefer-top-level-await](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/rules/prefer-top-level-await.js): I would probably fork this rule to start. It provides a suggestion fixer, but only works on top-level `await`s, and does not account for the `Promise.all` case. It also obviously does not use type information.
- [eslint-plugin-promise/prefer-await-to-then](https://github.com/eslint-community/eslint-plugin-promise/blob/main/rules/prefer-await-to-then.js): Looks at all levels, not just the top level, but besides that, it is very rudimentary — does not handle any special cases, provide suggestions, use type information, or detect `catch` or `finally`.

**Comment by JoshuaKGoldberg** [comment]
This seems really complex to me 😬. I think it'd be out of scope for our plugin.

**Comment by Josh-Cena** [comment]
Yeah I can't imagine it being generally high-utility. TypeScript already offers a refactoring for turning promise chains into async-await, and I'd say a syntactic rule actually has very low rates of false-positive. Special cases are hard to encode and should not belong in our plugin.

**Comment by JoshuaKGoldberg** [comment]
I took a quick stab at trying to implement this, and ... _wow_ is it out of scope for what we could do 😭. Which is a pity, it really would be nice to have. But we can barely keep the lights on as it is.

Hopefully someone will see this issue, get motivated to write it as their own community plugin, and folks can try it out there. 🤞
