### ISSUE TITLE
Bug: [noUnusedParameters] rest props disable rule

### ISSUE THREAD

**Issue by evgeniyworkbel** [typescript-eslint/typescript-eslint#9581]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.2&fileType=.tsx&code=JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocpAD0ljmADsYkpN0k4AhAVxhgiMACjjABnODRaMAJhOToYAOl79BACQAqAWQAyAQX5RgAIz5IxAHi17VAxgFEANkhBJmAPjgBvAL6UaOng0QTF4O0E4AF44AApvODQnFDExADkUNwAaOBgATzAkHKUSiBgAC1YRCHE4XwAubj57avEASmivb3I4OCIYHihGOEszNWGklPTMpCjvSdSMt18fEqUyyqhWsRWAeg8KX1IgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkAhqqrAO4DKAnkXgBboHQARdADM6AV1R4AkkliY8ZSnkxj0AGnA1IeOpgDmfClHQkATAAYLkDTShiS6IcORF0AMTkBhVHRIk3yOioACaKYMqqNlqoyABGRgDamraQJhZWUSnBCNbJWtnwAHTIeFh0sRiQeQC6mVDwsMES6EapJK4AHni5KSQA1siIADJxnrzQfUYR6nmQJMrI0HgAchKoY%2BgTYdN1kESwAKpE9ujBQ7DQDNsqMyn7RyfBAAq6dPB8WNeqmgC%2BID9AA&tokens=false

### Repro Code

```TypeScript
import React from 'react';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {}

export const Button = ({ className, type, ...otherProps }: ButtonProps) => {
  return <button className={className} {...otherProps} />;
};
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {},
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "target": "es2020",
    "lib": [
      "es2020",
      "dom",
      "dom.iterable"
    ],
    "module": "esnext",
    "strictNullChecks": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true
  }
}
```

### Expected Result

I expected that unused parameter "type" will be highlighted on the 5th line. 

### Actual Result

Parser does not see that prop "type" is not used. This behaviour is different when I delete "restProps" from destructured parameter

**Comment by bradzacher** [comment]
The `noUnusedParameters` ***TypeScript compiler option*** is not part of our project. It's part of TS itself.

But it's working as intended. The `type` prop is not unused - it's existence means that your rest parameter will not include a `type` prop.
