### ISSUE TITLE
Docs: Eslint 8.x Uses export default [] Guide is out of date

### ISSUE THREAD

**Issue by jtillwickEA** [typescript-eslint/typescript-eslint#9588]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

The latest version of eslint 8 uses eslint.config.mjs using this format:

```
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";
import pluginReactConfig from "eslint-plugin-react/configs/recommended.js";


export default [
  {files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"]},
  { languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } } },
  {languageOptions: { globals: globals.browser }},
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  pluginReactConfig,
];
```

The documentation provided by this package uses tseslint.config() which is completely different. WHY? Why can't we just be consistent? Why do we have to change things every week? I just want to get this shit to work.

### Affected URL(s)

https://typescript-eslint.io/getting-started/

**Comment by Josh-Cena** [comment]
Please read our docs: https://typescript-eslint.io/packages/typescript-eslint#config:

> The config function is a [variadic](https://en.wikipedia.org/wiki/Variadic_function) [identity function](https://en.wikipedia.org/wiki/Identity_function) which is a fancy way of saying that it's a function with a spread argument that accepts any number flat config objects and returns the objects unchanged. It exists as a way to quickly and easily provide types for your flat config file without the need for JSDoc type comments.

It's not hard to see that what goes into the `tseslint.config` function and what goes into the array are exactly the same. You can of course just return an array, although that means you lose types.

The getting started guide tells you how to make things work. It doesn't tell you why these things work that way. You are responsible for reading other docs to figure out. It's even explicitly said on the getting started page:

> - `tseslint.config(...)` is an _optional_ helper function — [read more about it here](https://typescript-eslint.io/packages/typescript-eslint#config).

Please also familiarize yourself with our CoC, which includes being polite and respectful.

**Comment by jtillwickEA** [comment]
It's not hard to specifically explain it either.

**Comment by Josh-Cena** [comment]
We already have a link that says "read more about it here". It's not helpful to maintain the same explanation on every page.

**Comment by jtillwickEA** [comment]
btw, here is the default file for react and typescript: 

```
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";
import pluginReactConfig from "eslint-plugin-react/configs/recommended.js";


export default [
  {files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"]},
  { languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } } },
  {languageOptions: { globals: globals.browser }},
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  pluginReactConfig,
];
```

Your guide omits most of that. `pluginJs.config` is missing, for example, and no explanation is given.

This is hard enough as it is. Being different just because doesn't make it any easier to learn.

**Comment by Josh-Cena** [comment]
There's no "default". There's one core API and there's everyone's attempt to make it work better. We help you get better types by using a helper function. If you want to add other configs, including the core JS config and React config, it's your job to read their documentation.

**Comment by jtillwickEA** [comment]
npx eslint --init provides a "default".

**Comment by Josh-Cena** [comment]
The page you are reading is for "go from zero"—if you already have an init template, all you need is to add `...tseslint.configs.recommended`. That's just how you add configs for literally every plugin.

**Comment by jtillwickEA** [comment]
I give up. It sure seems like you make it confusing on purpose. I just want any documentation out there to be clear and concise and helpful and I'm trying to point out that this getting started guide isn't. I'm sure I'm not the only one struggling with making the jump to the flat config. Your hostility toward my frustration isn't helpful either. There is clearly a distinction between `export default tselint.config()` and `export default []` and not making that painfully clear up front just causes confusion and frustration.

**Comment by jtillwickEA** [comment]
Combine that with the fact that your documentation already deviates from the package's recommended setup steps: `npx eslint --init` is also frustrating.

**Comment by jtillwickEA** [comment]
> There's no "default".

Says default right here: https://eslint.org/docs/latest/use/migrate-to-9.0.0#flat-config
