### ISSUE TITLE
v8 Playground: Types are wrong for `node:fs` (ATA related)

### ISSUE THREAD

**Issue by Tobbe** [typescript-eslint/typescript-eslint#9594]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Trying out the new v8 playground with some `@typescript-eslint/no-unsafe-*` rules enabled I was getting weird warnings. 

Here's a link to a playground reproduction: https://v8--typescript-eslint.netlify.app/play/#ts=5.5.2&fileType=.tsx&code=JYWwDg9gTgLgBAKjgQwM5wGbo1CI4BEAdhACYCmAXFgQFC0DGERq8AnslEQArIwAWcALyZUAOijlkAGzB9%2BAZTZEGACgIcuBAJT0mLCNPJjpEAOaqA5Jp7zLAGjg3eA3UA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolp9oAc1gBbRC3RQA7qKaQANOGx4ipZBWp0GzNp269BwvsmSUxTabIyRF0ZWuxQCJclRr1kjFuxcPPxCtGR88PByjkqq6jge2ro%2BBgHGwWa00pIARojQImRkKKgOTsrqAL4glUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

This is what it looks like
![Playground screenshot of code and warnings](https://github.com/user-attachments/assets/7a5420c0-a4f7-4eb8-a7b1-57bd76e12bcf)

eslint config
```
{
  "rules": {
    "@typescript-eslint/no-unsafe-argument": "warn",
    "@typescript-eslint/no-unsafe-assignment": "warn",
    "@typescript-eslint/no-unsafe-call": "warn",
    "@typescript-eslint/no-unsafe-member-access": "warn"
  }
}
```

tsconfig
```
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

I was told this is likely related to "ATA" (Automatic Types Acquisition), which was recently added https://github.com/typescript-eslint/typescript-eslint/pull/9242

### Affected URL(s)

https://v8--typescript-eslint.netlify.app/play

**Comment by JoshuaKGoldberg** [comment]
Fixed by #9598.
