### ISSUE TITLE
Bug: `@types/eslint` causing `flat-config-types` integration test failure on `main`

### ISSUE THREAD

**Issue by abrahamguo** [typescript-eslint/typescript-eslint#9615]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

The `flat-config-types` integration test is currently failing on `main` because of a TypeScript error. This is because `yarn` is providing `@types/eslint@9.7.0` for `@stylistic/eslint-plugin`, when `@stylistic/eslint-plugin` is asking for `@types/eslint@8.56.11`.

### Reproduction Repository Link

https://github.com/abrahamguo/repro/tree/stylistic-integration

### Repro Steps

1) clone the repo
2) `yarn`
3) `npx tsc`
4) TS errors are reported from the declaration files in `@stylistic/eslint-plugin`, and `node_modules/@types/eslint/package.json` reports version `9.6.0`.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/integration-tests`     | integration test fails on `main`, version doesn't matter |
| `TypeScript`                           | `5.5.2`

**Comment by bradzacher** [comment]
We'll probably want to setup a regression test against both the v8 and v9 types so that we can ensure we maintain backwards compat whilst supporting the changes.

**Comment by abrahamguo** [comment]
Failure fixed by #9620
