### ISSUE TITLE
@typescript-eslint/utils@7.17.0" has incorrect peer dependency "eslint@^8.56.0"

### ISSUE THREAD

**Issue by JeffreyArts** [typescript-eslint/typescript-eslint#9617]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

ast-spec

### Repro Code

```TypeScript
package.json

{ 
  "devDependencies": {
    "eslint": "^9.7.0",
    "@typescript-eslint/eslint-plugin": "^7.17.0",
  }
}
```

### ESLint Config

-

### tsconfig

-

### Expected Result

No warning

### Actual Result

@typescript-eslint/eslint-plugin@7.17.0" has incorrect peer dependency "eslint@^8.56.0".
@typescript-eslint/eslint-plugin > @typescript-eslint/utils@7.17.0" has incorrect peer dependency "eslint@^8.56.0".
@typescript-eslint/eslint-plugin > @typescript-eslint/type-utils@7.17.0" has incorrect peer dependency "eslint@^8.56.0".
@typescript-eslint/parser@7.17.0" has incorrect peer dependency "eslint@^8.56.0".

### Additional Info

Solution would be:

 "peerDependencies": {
    "eslint": ">=8.56.0"
  },

Making this package suitable for everything from eslint version 8.56.0 and up (including 9.x.x, or even a future 10.x.x).

Same would apply for:
- `@typescript-eslint/utils@7.17.0`
- `@typescript-eslint/type-utils@7.17.0`
- `@typescript-eslint/parser@7.17.0`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `7.17.0` |
| `@typescript-eslint/parser`            | `7.17.0` |
| `@typescript-eslint/rule-tester`       | - |
| `@typescript-eslint/scope-manager`     | `7.17.0` |
| `@typescript-eslint/typescript-estree` | `7.17.0` |
| `@typescript-eslint/type-utils`        | `7.17.0` |
| `@typescript-eslint/utils`             | `7.17.0` |
| `TypeScript`                           | `5.5.4` |
| `ESLint`                               | `9.7.0` |
| `node`                                 | `20.10.0` |

@typescript-eslint/visitor-keys: 7.17.0

**Comment by bradzacher** [comment]
Please use the search and look at pinned issues before posting
https://github.com/typescript-eslint/typescript-eslint/issues/8211
