### ISSUE TITLE
Docs: errors following quickstart docs

### ISSUE THREAD

**Issue by Andrea-Risiglione** [typescript-eslint/typescript-eslint#9631]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Hello everyone, i'm trying to install "typescript-eslint" on my TypeScript project using typescript-eslint-getting-started link for ESLint's new "flat" config format. However, when I use the command you advice on documentation to install the devDependencies needed at step1 and then pass to step2 for the real configuration, the object of the file to paste to eslint.config.mjs drops me a .ts error related to @eslint/js module ("it doesn't found"). Looking to my package.json file i noticed that the command to install the devDepencies at step1, added to it eslint and @eslint/js with different versions. I supposed the error I received could be related to it.

### Affected URL(s)

[[typescript-eslint](https://typescript-eslint.io/getting-started)]

**Comment by bradzacher** [comment]
Could you give us a reproduction repo showing your state so we can better understand what you're seeing?

**Comment by Andrea-Risiglione** [comment]
Thanks @bradzacher but I solved with Legacy setup.
