### ISSUE TITLE
Repo: Website Invalid RSA Certificate

### ISSUE THREAD

**Issue by brendangoldberg** [typescript-eslint/typescript-eslint#9654]
### Suggestion

The website https://typescript-eslint.io has invalid RSA certificate.

![Screenshot 2024-07-28 at 12 27 53 PM](https://github.com/user-attachments/assets/491630dc-3527-4cbb-917a-9108e4eff0d7)

**Comment by Josh-Cena** [comment]
<img width="534" alt="image" src="https://github.com/user-attachments/assets/198833c8-646f-406d-8ac9-43f6c6cca5ae">

<img width="534" alt="image" src="https://github.com/user-attachments/assets/6643b81b-33bd-4a0c-a6d5-51e9fc3e6b51">

I believe our certificates are correctly configured and I don't know why you are getting that error. Does it happen with other browsers?

**Comment by brendangoldberg** [comment]
> <img alt="image" width="534" src="https://private-user-images.githubusercontent.com/55398995/352860153-198833c8-646f-406d-8ac9-43f6c6cca5ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxOTIzNzYsIm5iZiI6MTcyMjE5MjA3NiwicGF0aCI6Ii81NTM5ODk5NS8zNTI4NjAxNTMtMTk4ODMzYzgtNjQ2Zi00MDZkLThhYzktNDNmNmM2Y2NhNWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDE4NDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZGViMTY3MDMxOTAzZjM5YzU3YWM5YzUxZWI2OTZmNGE0MTNjZDg2ODZlNmI0YzJkYzFhNTExZWVkNjQ1YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RIuwK10IZO0plviLnmqRHlVr3uhnGPRw0jZsHs4hBOk"> <img alt="image" width="534" src="https://private-user-images.githubusercontent.com/55398995/352860407-6643b81b-33bd-4a0c-a6d5-51e9fc3e6b51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxOTIzNzYsIm5iZiI6MTcyMjE5MjA3NiwicGF0aCI6Ii81NTM5ODk5NS8zNTI4NjA0MDctNjY0M2I4MWItMzNiZC00YTBjLWE2ZDUtNTFlOWZjM2U2YjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDE4NDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZjE0NTUzY2M4YmFkOGIxZWRkM2NjYzdkMTMwYzZkNWE4YzY3YTQ3Mzk0OGI4MzQ5OGQzMjdlOGZhYjhhMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZToUJXq7-1iyRG_VcIluqZ4lYTYROQzbfSMyBwBat3Y">
> I believe our certificates are correctly configured and I don't know why you are getting that error. Does it happen with other browsers?

Yes, happens in the following browsers:

- Brave - Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (arm64)
- Safari - Version 17.2.1 (19617.1.17.11.12)
- Firefox - Version 128.0.3 (64-bit)


I also attempt with VPN and firewall turned off.

**Comment by Josh-Cena** [comment]
Are you using a public wifi, as the error message says?

**Comment by JamesHenry** [comment]
There doesn't appear to be an issue on our side.

![wifi hotspot](https://github.com/user-attachments/assets/a195b59d-d32a-443f-811a-e859a066ccda)
 
Maybe you are on a public hotspot or something? Have you tried other websites on the same connection?

**Comment by brendangoldberg** [comment]
> Are you using a public wifi, as the error message says?

Hm it might be how my computer is connecting to network. I'll investigate from my end. I apologize for the mix up and poor understanding of the problem, will close issue.
