### ISSUE TITLE
Bug: [Undefine Variable] variable is considered undefined even after has method check on map object

### ISSUE THREAD

**Issue by dineshchauhanAPP** [typescript-eslint/typescript-eslint#9695]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.2&fileType=.tsx&code=LAKANgpgLgBAhgLhgWTgBwDwGcoCcCWAdgOYA0MA3jGkjgSTAL4B8MAvDIRAO4roAUASgDcoUPgBmMfnAB0ACzhZ%2BAIjgrBgyqBgwAxgHtCOGGHbxZxaKvUidp2WnMqAjACYAzCuEwA9L5grWDAiWAhcXANcGChFYJh8LBgAV0IAEwgJIgg0sRBQRiA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
let a: Map<string, {p:string} > = new Map();

if (a.has("a")) {
  const l = a.get("a");
  l.p = "123"; // get lint error that l is undefined


}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/<rule-name>": ["error", ...<options>],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

variable l can be undefined as its key has been checked.

### Actual Result

variable l is shown that it could be undefined

**Comment by bradzacher** [comment]
Double check the message.

First - it's a typescript error, not an ESLint error.
Second - it says `'l' is possibly 'undefined'`

Check the type of your variable. Check the type of the `get` method. This is expected.

If you need more help - consider visiting the typescript website for links to their support forums.
