### ISSUE TITLE
Documentation: [strict-boolean-expressions] examples don't match their descriptions

### ISSUE THREAD

**Issue by scarf005** [typescript-eslint/typescript-eslint#9699]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play#eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6ZfKsugIwHs%2BSAIZN6AD2LQUySnyaoMkRNGh9okcGAC%2BILUA&code=PTAEDsFcBtoQwEbQKYUgWwcgTgZ1HNqgMYD24uAlgCY7LWiQVwBmqCAnqLS3DAC4AoFPzToAXGKzZQAH0bgelcPVABeUAAYA3IMotQACijoAlKADeg0KDIVSKAHTRSAc0MByE6Er4lK6g9TXQBfQUEQNFhEFFBcfmxlV3xCEnIqWiIGJlxWdi4ePmghETiEyXjE8Fc5KOh1Ot19IwBCSvMrGztcB2RnN09Kn3xkdAAHfg4g0PDIqGikdlJeuAoCIlt0mjps5jZQTm5kXgFBFiZifkpyUBZlwwRl6AB%2BSUeV8A7rHwMHp6%2BbDYEIRDMFvmEwhEwAADVYcaEAGgU3QScGUqlcyBUiWIKUUCmua1IBnQpA2-AAFqtQORUGNEuhKFcAG6oSZjVCpbi%2BOCwUgAd3oghRt2WDQAPAAVAB8hkIrkkkvMamlRnloGeoAAjKBJJowVCCNB%2BXAOLgALQJSCUrirBi8k1m828aC4Ljs5ApDbUHl8wXUYTIUSkBAAKwaFhCun5FMosUMIdDAJpYYamP4AHkw6CZoa4LhcDgrjdzuBLoT8PymRTSNaCOBQNDfND1ksPptwPxkAAPfi4RyCWjEeAbUvlm75wvYfiGZm8yDISRMADW4AFn0kk6L%2BDn0AXulK6FNWAAygkkg0ALJwSmObB20joUGgVWaRwAVg1oA8Hl1Cn89C6Fu06GEeHCnue1TBEAA&fileType=.ts

### Repro Code

```TypeScript
// nullable numbers are considered unsafe by default
let num: number | undefined = 0
if (num) {
  console.log('num is defined')
}
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/strict-boolean-expressions": "error"
  }
}
```

### Expected Result

I expected that as noted in docs as `// nullable numbers are considered unsafe by default` nullish number comparison  would be an error.

### Actual Result

tslint made an false negative on nullish numbers.

### Additional Info

![screenshot of playground](https://github.com/user-attachments/assets/8dbf5651-a3c2-45ac-a0bc-647fb3d0a522)

the playground link is directly copied from [official docs](https://typescript-eslint.io/rules/strict-boolean-expressions/#examples).

**Comment by bradzacher** [comment]
If you look at the types you'll see why this occurs.
TS does control flow analysis and can see that in the condition `num` cannot be `undefined` - so the type is not `number | undefined`, but is instead just `number`.

[playground](https://www.typescriptlang.org/play/?#code/PTAEDsFcBtoQwEbQKYUgWwcgTgZ1HNqgMYD24uAlgCY7LWiQVwBmqCAnqLS3DAC4AoFPzToAXGKzZQAH0bgelcPVABeUAAYA3IMotQACijoAlKADegkKFsA9APyDbZCqRQA6aKQDmhgOQmoJT4SirU-qa6AL5AA)

**Comment by scarf005** [comment]
but the wouldn't that mean the docs is using the weong example? i'm confused why this is marked as user error when it's literally from the official docs.

that said, i'm willing to open a PR that fixes the example in official docs.

**Comment by kirkwaiblinger** [comment]
@bradzacher is right that the rule is working as intended....

But @scarf005, you're right that the docs are misleading here - Note that if you change the example to 
```ts
// nullable numbers are considered unsafe by default
declare const num: number | undefined;
if (num) {
  console.log('num is defined');
}
```
the rule works as you expected. 

For context, I only knew that TS would narrow the type if you did `const num: number | undefined = 0;`; I had it in my head that it would _not_ do so if you used a mutable `let`. But this example shows otherwise! Perhaps TS used to behave differently and therefore the docs examples were once correct but have since regressed 🤷‍♂️ . See also https://github.com/typescript-eslint/typescript-eslint/issues/8721 for some deep subtleties about `const`/`let` and types. 

In any case, reopening for docs changes.
