### ISSUE TITLE
Repo: prettier V3 does not support automatic inline snapshots

### ISSUE THREAD

**Issue by scarf005** [typescript-eslint/typescript-eslint#9704]
### Suggestion

```
   ✖  nx run rule-tester:test
       PASS  tests/flat-config-schema.test.ts
       FAIL  tests/RuleTester.test.ts
        ● Test suite failed to run
      
          Jest: Inline Snapshots are not supported when using Prettier 3.0.0 or above.
          See https://jestjs.io/docs/configuration/#prettierpath-string for alternatives.
      
            at saveInlineSnapshots (../../node_modules/jest-snapshot/build/InlineSnapshots.js:101:15)
      
      Test Suites: 1 failed, 1 passed, 2 total
      Tests:       24 passed, 24 total
      Snapshots:   0 total
      Time:        3.515 s
      Ran all test suites.
      
      
   ✔  nx run eslint-plugin:test (1m)
```

https://github.com/typescript-eslint/typescript-eslint/blob/2761ca83becc0b8c6d76a14fb2d2465a1d9c45a5/package.json#L119

would need to either
- downgrade prettier to V2 or
- use regular snapshots for `tests/RuleTester.test.ts`

**Comment by JoshuaKGoldberg** [comment]
> would need to either

...or manually keep them up-to-date by hand. Which is what I've been (unhappily) doing.

#7112 tracks investigating moving over to Vitest, if anybody's interested.

**Comment by JoshuaKGoldberg** [comment]
Closing this out: we're stuck 🤷 Jest + Prettier v3 don't support _automatic_ inline snapshots, and that's the stack we're on. We're not going to downgrade to an older major version of Prettier. I'd rather see us move to the shinier, less-annoying-to-configure Vitest (#7112). Thanks for filing!
