### ISSUE TITLE
Bug: [no-unnecessary-type-parameters] ignoring reference in other type parameters

### ISSUE THREAD

**Issue by n0099** [typescript-eslint/typescript-eslint#9706]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.4&fileType=.tsx&code=JYOwLgpgTgZghgYwgAgIIAdgB4AqAlCAZ3QHsRCIAaZHARQFdoBPABTijgFtkBeZECADdoAPmQBvALAAoZMihFS5CAC4aBYmQqUZcgI6MordlzV1DxjpxkBfGWCboUAeQBGAKwCqIANYgSAO4gvMgECCRQACZYhGBQoADm1PS%2B-kEiANwy4eRgyPQUGMAA6sBgABYAwvRQhBEhWLo0RcgQAB6QIJGEaJi4GkraNAzMbFYiOrLqiloofDhFANoA5AqayssAupNy5qMm3O2d3chuXqmBwfNLywb7VlsiTQAUAJS8YuLINlnSQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWsRFCAtonyJoqDJCXQO0SODABfELqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
interface Api<TResponse, TQueryParam = never> {
  response: TResponse,
  queryParam: TQueryParam
}
type ObjUnknown = Record<string, unknown>;
const useApiWithCursor = <
  TApi extends Api<TResponse, TQueryParam>,
  TResponse = TApi['response'],
  TQueryParam extends ObjUnknown = TApi['queryParam']>
  () => { };
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/no-unnecessary-type-parameters": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

Not reporting.

### Actual Result

```ts
  TApi extends Api<TResponse, TQueryParam>,
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Type parameter TApi is used only once. 7:3 - 7:43
```

**Comment by bradzacher** [comment]
It's very hard to provide correct feedback here without seeing more info.
In your example your return type is missing and it takes no argument - so realistically you could rewrite your function as `useApiWithCursor = () => {}` and it would work exactly the same.

Could you please provide a more complete repro?

**Comment by n0099** [comment]
https://github.com/n0099/open-tbm/blob/83e82adb28f50270c7b0798e238b8218ead2a7be/fe/src/api/index.ts#L128-L173

**Comment by JoshuaKGoldberg** [comment]
Ok I was able to reproduce the issue down to the much smaller:

```ts
declare function $fetch<Response>(...args: unknown[]): Promise<Response>;

type ObjUnknown = Record<string, unknown>;

export const queryFunction = async <TResponse, TQueryParam extends ObjUnknown>(
  config: { beUrl: string },
  requestHeaders: Record<string, string>,
  endpoint: string,
  queryParam?: TQueryParam,
  signal?: AbortSignal
): Promise<TResponse> => {
  return (await $fetch<TResponse>(`${config.beUrl}/api/${endpoint}`, {
    query: queryParam,
    headers: {
      Accept: "application/json",
      ...requestHeaders,
    },
    signal,
  })) as TResponse;
};
```

...and, we can see more clearly that the rule is correct to report in this case. `TQueryParam` is only used once in `queryFunction` after it's defined, in the `queryParam?: TQueryParam`. You could change the function signature to `queryParam?: ObjUnknown` and get rid of the unnecessary type parameter.

By the way, @n0099, that file has a lot of types in it that we're not familiar with. Plus it has references to globals outside of the file, such as `$fetch` and `ObjUnknown`. As a general piece of advice: you'll get faster and more helpful help from maintainers if you can provide small, isolated reproductions. 

For visibility, https://antfu.me/posts/why-reproductions-are-required#why-reproduction explains more why we're asking for this.

Cheers all!

**Comment by n0099** [comment]
I've already realized that type param `TQueryParam` is not really useful and removed it in https://github.com/n0099/open-tbm/commit/219941b25ddb3ae453e40650aa1bbe854327468a
This issue is about `TApi` not `TQueryParam`
