### ISSUE TITLE
Bug: [no-unnecessary-type-parameters] Detects an error where there's none

### ISSUE THREAD

**Issue by lgenzelis** [typescript-eslint/typescript-eslint#9709]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.3&showAST=scope&fileType=.tsx&code=C4TwDgpgBAwg9gWzAV2BAPAQQHxQLxSZQQAeaAdgCYDOUAYsuQMbACWc5UA-IVAFxQA3lADaAaSitOAawgg4AM0IBdAfCSoMmcctwBfANwAoI6EhQAogEdkAQwA26ABoAaKAE1ceI1CgAKdAAVAEZsPwBKfFwQ4jIIKlp1FDRnXB5g-igAJkjSChooIKywyLxorNj8xMRkjE9uKAyBCp5gACdkaAEFB2oIYyMgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYUACAXAngA4oDG0AlobgLQrzkB2uA9AwPbWwMOIkrIBDaPmoFi1QkIEBbRLkTRUGSAuhtokAL4hNQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
type Compute<A> = A extends Function ? A : { [K in keyof A]: Compute<A[K]> };

type Equal<X, Y> =
  (<T1>() => T1 extends Compute<X> ? 1 : 2) extends <T2>() => T2 extends Compute<Y> ? 1 : 2 ? true : false;
```

### ESLint Config

```javascript
module.exports = {
  "rules": { "@typescript-eslint/no-unnecessary-type-parameters": "error"}
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

I wouldn't expect this to give any errors. As far as I can tell, there's no way to achieve the same functionality without adding `<T1>` and `<T2>`. 

### Actual Result

I'm getting two errors (one for each `T`):
- Type parameter T1 is used only once.ESLint [@typescript-eslint/no-unnecessary-type-parameters](https://typescript-eslint.io/rules/no-unnecessary-type-parameters)
- Type parameter T2 is used only once.ESLint[@typescript-eslint/no-unnecessary-type-parameters](https://typescript-eslint.io/rules/no-unnecessary-type-parameters)

### Additional Info

In all honesty, I don't understand how that `Equal` utility type works. But I know it does: it returns `true` if `X` and `Y` are assignable to one another (and if one is `any`, only if the other one is `any` as well). I have been using it in my codebase for a while.

**Comment by Josh-Cena** [comment]
This pattern relies on the _identity_ of the generic function type. It doesn't use the type itself, but treats it as an opaque entity for type comparison. This is a niche use case where it's perfectly fine to disable this rule for this specific case.

**Comment by kirkwaiblinger** [comment]
@Josh-Cena I don't have (even half) the brain power required to understand this one, but is there a nugget of wisdom here to add to https://github.com/typescript-eslint/typescript-eslint/issues/9680?

**Comment by Josh-Cena** [comment]
This is pretty much a thing on its own; I've only seen this pattern occur in this particular code of `Equal`. It's hard to generalize but fine if you want to mention this exact snippet.

(For reference, this code works because the function types here can't be reduced and therefore can only check for assignability via identity instead of structural compatibility.)

**Comment by lgenzelis** [comment]
I'm closing the issue then. Thank you both :)

FWIW instead of disabling the rule, I did this

```ts
type Equal<X, Y> =
  (<T1>(t1: T1) => T1 extends Compute<X> ? 1 : 2) extends <T2>(t2: T2) => T2 extends Compute<Y> ? 1 : 2 ? true : false;
```

It doesn't change the behavior of `Equal` and it spares me from adding `eslint-ignore` and feeling guilty about it. 

> For reference, this code works because the function types here can't be reduced and therefore can only check for assignability via identity instead of structural compatibility.

How much I'd love to know what this means 😅
