### ISSUE TITLE
Bug: [no-unnecessary-type-parameters] ignoring reference in `T[as keyof T] as ...`

### ISSUE THREAD

**Issue by n0099** [typescript-eslint/typescript-eslint#9723]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.4&fileType=.ts&code=MYewdgzgLgBA1gUwJ4wLwwOQEMMG4CwAUKJLCAEYBWaMA3jFgFwwCMMAvgceNDAOYJY6ADwAVAHwAKCpQD8zUQEo04ojBgzZAOgDaiFFgjxkIAGYxRAXQZGArmDhgQAdzBcgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWsRFCAtonyJoqDJCXQO0SODABfELqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
const key = 'a';
const obj = { a: 1 };
const get = <T>(obj?: T) =>
  obj?.[key as keyof T] as unknown;
//               remove ^^^^^^^^^^ will fix this, unknown can be any other types
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/no-unnecessary-type-parameters": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

Not reporting.

### Actual Result
```typescript
const get = <T>(obj?: T) =>
             ^
Type parameter T is used only once. 3:14 - 3:15
```

**Comment by bradzacher** [comment]
This is working as expected.
The parameter is only used once in the signature - in the argument - which means the signature can be rewritten without the parameter.

The usage in the body does not count as a usage as that style of usage is essentially usage as a type alias and can often be replaced with eg `typeof obj`.

**Comment by n0099** [comment]
If so
```
const get = <T>(obj?: T) =>
  obj?.[key as keyof T];
```
should also get reported.

**Comment by n0099** [comment]
And I'm getting ![image](https://github.com/user-attachments/assets/388aaa09-4766-422a-bea6-a3ba039ecee3)
```js
Unsafe argument of type `any` assigned to a parameter of type `Post | undefined`.
eslint[@typescript-eslint/no-unsafe-argument](https://typescript-eslint.io/rules/no-unsafe-argument)
```
at callers of a function like this after change https://github.com/n0099/open-tbm/blob/326ff198498e7347216e8f7a5e51db09ce40887b/fe/src/components/post/badge/Time.vue#L70-L71 to
```diff
-const getPostTime = <T extends TPost | TParentPost>(post?: T) =>
+const getPostTime = (post?: TPost | TParentPost) =>
-    post?.[props.postTimeKey as keyof T] as TPostTimeValue | undefined;
+    post?.[props.postTimeKey as keyof typeof post] as TPostTimeValue | undefined;
```

**Comment by Josh-Cena** [comment]
This rule only cares about the function signature. The implementation of the function does not care about the type parameter instantiation and using the type parameter in the function body does not give you extra type safety. If your function signature only uses the type parameter once, then the report is correct.
