### ISSUE TITLE
Docs: Consider having more formal "upgrade guide" indications for major releases

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9752]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I've had multiple experienced web tooling developers ask me if there are release notes and/or some kind of upgrade guide for v8. That includes folks who actually did read the blog post. They were still looking for something more formally positioned as that upgrade guide. This also happened for v6. I think that means we're not making it clear enough that the release blog post _is_ the upgrade guide.

Proposal: maybe we should explicitly call out in the CHANGELOG.md & top of the blog posts that the blog post _is_ the list of steps to take?

...is there anything else we can do to help folks here? 

### Affected URL(s)

https://typescript-eslint.io/blog/announcing-typescript-eslint-v8

💖

**Comment by bradzacher** [comment]
> That includes folks who actually did read the blog post

![press x to doubt](https://github.com/user-attachments/assets/a1d86629-48d8-415b-ac10-0fdebb952189)

The blog post includes things like:

![screenshot of blog post](https://github.com/user-attachments/assets/eb1d1693-5bb9-49a7-9795-67ae21fd5dc1)

Which is that exact thing they're looking for. If they read the post then they'd know those were throughout the blog post.

I'd guess that "read the blog post" means "skimmed the blog post at a high level"

Yes that's a user-hostile take but I'd say it's true. Source: It's exactly what I would do.

**Comment by JoshuaKGoldberg** [comment]
> Proposal: maybe we should explicitly call out in the CHANGELOG.md & top of the blog posts that the blog post is the list of steps to take?

Yeah I think we can get away with just this haha. I'll send a PR now.
