### ISSUE TITLE
Docs: Add FAQs and flesh out associated docs for project service

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9753]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Project service has been in the wild for a couple of weeks now and we're starting to see the common ways it's tripping folks up.

The most common question I've seen come up is around the new _"Parsing error: <file> was not found by the project service. Consider either including it in the tsconfig.json or including it in allowDefaultProject"_. We should explain how to fix this, such as:

* Cases where the file that's inside a directory with a `tsconfig.json` might not be in there: e.g. https://github.com/JoshuaKGoldberg/repros/tree/tseslint-project-service-non-included-nearest-tsconfig
  * ...and when to switch to `parserOptions.project` for now, which that case might be an example of.
* Cases where the file should be added to the default project

### Affected URL(s)

https://typescript-eslint.io/troubleshooting/typed-linting

💖

**Comment by Zamiell** [comment]
>  We should explain how to fix this

What about improving the error message? For example, if the error is on a .js file specifically, I would like to see a message saying something along the lines of:

> Tip: Try turning on the "checkJs" compiler flag in your TypeScript config file.

**Comment by JoshuaKGoldberg** [comment]
> What about improving the error message?

I like that idea too 😄. That'd be a good separate issue. It's often very difficult or outright not possible to know what folks wanted. For example, if it's on a `.js` file, the solution could be any of needing `checkJs`, or using the wrong TS config file, or the file accidentally being linted or, ...

**Comment by JoshuaKGoldberg** [comment]
Sourcing a couple cases from #9739:

* https://github.com/typescript-eslint/typescript-eslint/issues/9739#issuecomment-2296442418: If the sibling TSConfig to a file doesn't include that file, that file will have to come from the default project service 
  * It'd be nice if we could give a specialized error in this case...
* https://github.com/typescript-eslint/typescript-eslint/issues/9739#issuecomment-2296447765: that JS files must come from the default project unless `allowJs`/`checkJs` is enabled (deferring to typical TypeScript logic)
