### ISSUE TITLE
Bug: Cannot find module '@typescript-eslint/eslint-plugin'

### ISSUE THREAD

**Issue by d-balaskas** [typescript-eslint/typescript-eslint#9758]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://dev.to/jeanjavi/nuxt-eslint-9-typescript-prettier-configuration-guide-2024-4h2c

### Repro Code

```TypeScript
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "nuxt": "^3.12.4",
    "vue": "latest"
  },
  "devDependencies": {
    "@eslint/js": "^9.8.0",
    "eslint": "9.x",
    "@typescript-eslint/eslint-plugin": "^8.0.1",
    "eslint-config-prettier": "9.1.0",
    "eslint-plugin-vue": "^9.27.0",
    "globals": "^15.9.0",
    "prettier": "3.3.3",
    "typescript-eslint": "^8.0.1"
  }
}
```

### ESLint Config

```javascript
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";
import pluginVue from "eslint-plugin-vue";


export default [
  {files: ["**/*.{js,mjs,cjs,ts,vue}"]},
  {languageOptions: { globals: {...globals.browser, ...globals.node} }},
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginVue.configs["flat/essential"],
  {files: ["**/*.vue"], languageOptions: {parserOptions: {parser: tseslint.parser}}},
  {
    ignores: ['node_modules', 'dist', 'public', '.nuxt']
  },
  eslint-config-prettier
];
```

### tsconfig

```jsonc
{
  "extends": "./.nuxt/tsconfig.json",
}
```

### Expected Result

Expected eslint and prettier to run with basic config

### Actual Result

```
Oops! Something went wrong! :(

ESLint: 9.8.0

Error: Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:
- C:\...\node_modules\typescript-eslint\dist\index.js
  ...
```
I notice that @typescript-eslint/eslint-plugin exists in node_modules.

![Node Modules content](https://github.com/user-attachments/assets/2c54d21a-aca5-41a7-b8ab-a8a48d8baa98)

**Comment by bradzacher** [comment]
This is 110% going to be something wrong with your local install.
Try creating a repro repo and we can help - but without that we can't really provide much advice beyond "delete `node_modules` and install again"
