### ISSUE TITLE
Repo: Enable Publish Attestation (Provenance) [SECURITY]

### ISSUE THREAD

**Issue by elliot-huffman** [typescript-eslint/typescript-eslint#9763]
### Suggestion

I was going to make a PR to go with this issue, but I could not find the logic that is used to publish the built NPM package to the registry.

There are two things that need to happen, the --provenance flag needs to be issued (or a corresponding package.json config needs to be set) and the `ID token` needs to have its permission elevated to `write` to be able to do attestation of the build process.
I see that the canary build publish mechanism has the provenance flag present in the environmental variable but the ID token is not properly permissioned to be able to publish with the provenance metadata.

This is a non-breaking change that only adds metadata to the NPM published package that reduces risk of a supply chain attack.
Clients that don't support the provenance metadata ignore it safely.

NPM Docs:
https://docs.npmjs.com/generating-provenance-statements

I am happy to issue a PR enabling this behavior in the GitHub actions workflow(s) once I am educated on how the publish pipeline works.

**Comment by bradzacher** [comment]
> that reduces risk of a supply chain attack

Nit - it doesn't actually do that.

Someone could still (a) manually publish a build without an attestation (b) add malicious code to the repo and release it or (c) inject malicious code into our pipeline.

The attestation just makes it clear that a release was done from the package's repo's CI etc.

I.e. It gives you an avenue to more easily validate if there was a supply chain attack.

**Comment by bradzacher** [comment]
> I could not find the logic that is used to publish the built NPM package to the registry.

We purposely keep our release pipeline secured so that only the core team has access to it.

We did this on purpose as it gives the core team some utility and elevated permissions for things like triggering manual releases.

I'm not sure that we want to give up those just to provide a badge for the release.
Cc @typescript-eslint/core-team

**Comment by bradzacher** [comment]
> I see that the canary build publish mechanism has the provenance flag present in the environmental variable but the ID token is not properly permissioned to be able to publish with the provenance metadata.

What do you mean here? The canary builds are released with provenance metadata

Eg here's the provenance for the latest canary release of the plugin:

https://www.npmjs.com/package/@typescript-eslint/eslint-plugin/v/8.0.2-alpha.6#provenance

**Comment by JamesHenry** [comment]
I think this is well meaning but there's a little bit of confusion about the provenance mechanism and overstating its overall importance in terms of security.

1. How we use provenance already
2. Why we don't for our most important (latest) releases

1. As @bradzacher has shown, we are using provenance successfully for canary release, I am not sure what you are missing. The token permissions are set here: https://github.com/typescript-eslint/typescript-eslint/blob/07700dd7ce10e37b3b37317df8d2c0f177c9763a/.github/workflows/ci.yml#L274 and the provenance npm config is set here: https://github.com/typescript-eslint/typescript-eslint/blob/07700dd7ce10e37b3b37317df8d2c0f177c9763a/.github/workflows/ci.yml#L301

2. This bit is critical - security is a multi-faceted concern that is not as simple as "get a new security flavored feature, make sure it is enabled at all costs". Having the workflow for publishing to latest in the open repo would indeed have a huge potential cost.

We are an OSS project made up of team members that have mostly never (and possibly will never) meet in real life. Some of us (the core team) have been collaborating virtual for many, many years and there is a very high level of trust there, but others are newer and/or more transient and it would be a far bigger security risk for those folks to have the access to publish releases to `latest` for all our users to pull down (automatically in many cases). This is the reality of GitHub workflows right now: write access to code === right to run all workflows.

So this is the real way we can mitigate serious attacks as best we can: following the Principle of least Privilege with a kind of best-effort RBAC, albeit limited by the tools the GitHub gives us, taking into account the all important human trust element of security.

If GitHub _finally_ allows granular user permissions to be applied to workflow triggers then we could potentially reevaluate this stance but for now this is the most secure approach overall.
