### ISSUE TITLE
[lines-between-class-members] Add @typescript-eslint/lines-between-class-members

### ISSUE THREAD

**Issue by cafesanu** [typescript-eslint/typescript-eslint#977]
**Feature/rule request**

I'm truly sorry if this is on the roadmap, but I could not find anywhere a plan to add this. If that is not the case, then:

Currently, the eslint rule `lines-between-class-members` does not distinguish class members/fields from methods. This is due to the fact the class members feature is in stage 3 (https://github.com/tc39/proposal-class-fields), so the eslint folks have not implemented this yet until this reaches stage 4 (https://github.com/eslint/eslint/issues/11745).

Since this is not the case for typescript, I think it would make sense to add `@typescript-eslint/lines-between-class-members` to be able to apply different rules for members than methods. In my specific case I'd like members to not have an empty line among them, while for methods, I'd like to have an empty line among them. 

I think, it would make sense folr the rule to be something like
```JSON
{
  "rules": {
    "@typescript-eslint/lines-between-class-members": ["error", {
      "members" | "fields": "always" | "never",
      "methods": "always" | "never"
    }],
}
```

Thanks and sorry again if there is a plan to add this

**Comment by zhaoxuyll** [comment]
This is available https://eslint.org/docs/rules/lines-between-class-members

**Comment by Yegorich555** [comment]
> This is available https://eslint.org/docs/rules/lines-between-class-members

Eslint doesn't distinguish functions and ES6property-members. Guys want to use lines-between-functions and no-lines-between-class-properties

**Comment by Shinigami92** [comment]
I want to turn on this rule, but currently there is no option to turn the rule on only for member functions.  
We have many private, protected and public member properties that are grouped together and we dont want to place empty lines between each member property.

**Comment by bradzacher** [comment]
That's a request for the base rule.

When we create an extension rule, we only look to add support for TS syntax, or to enhance the rule with type information.

We do not want to be adding new options unrelated to those objectives.

**Comment by bschlenk** [comment]
It would be nice to also be able to disable this for method overrides. I like to group all method overrides together, but have space between actual different methods.

**Comment by Shinigami92** [comment]
> It would be nice to also be able to disable this for method overrides. I like to group all method overrides together, but have space between actual different methods.

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/lines-between-class-members.md#exceptafteroverload-true

**Comment by CatsMiaow** [comment]
- @typescript-eslint/eslint-plugin ^2.34.0
- @typescript-eslint/parser ^2.34.0
```json
"rules": {
  "lines-between-class-members": "off",
  "@typescript-eslint/lines-between-class-members": ["error", "always", { "exceptAfterOverload": true }]
}
```
![image](https://user-images.githubusercontent.com/1300172/82395318-41e45680-9a86-11ea-929b-ac58201a1fab.png)

**Comment by Shinigami92** [comment]
If you already havn't, pls open a bug issue and link it here. Thx

**Comment by mgenware** [comment]
@CatsMiaow 

ESLint's `exceptAfterSingleLine` could do the trick ([docs](https://github.com/eslint/eslint/blob/master/docs/rules/lines-between-class-members.md#options)):
```js
// rules
'lines-between-class-members': [
  'error',
  'always',
  { exceptAfterSingleLine: true },
]
```

It simply skips checking empty lines after a single-line class member.
