### ISSUE TITLE
`RuleTester` feat: a way to set up for a test case

### ISSUE THREAD

**Issue by RobinTail** [typescript-eslint/typescript-eslint#9770]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

rule-tester

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I'm developing a ESLint plugin, that needs to be aware of the user's `package.json` content.
I made it read the file similar to [how `eslint-import-plugin` does it](https://github.com/import-js/eslint-plugin-import/blob/09476d7dac1ab36668283f9626f85e2223652b37/src/rules/no-extraneous-dependencies.js#L23).

However, in order to test a rule of such a plugin, I need to run a lot of tests not only having different options, but also mocking different scenarios of user's `package.json` content.

I found it an excessive complication the suggestion on using fixtures in form of actual files within several directories and the requirement to maintain such a system, while it could be easier:

- just to allow keeping an environment data inside each test case,
- and let the test runner to call a customizible hook before each test,
- inside such a hook I could mock the involved methods.

And no extra files, no fixtures, no maintenance ever needed. All in one place.

Long story short — imagine you can do this:

```ts
import { mock } from "bun"; // or jest/vitest/etc

const readerMock = mock();

mock.module("node:fs", () => ({
  readFileSync: readerMock,
}));

const tester = new RuleTester({
  // proposed hook receives the test case that is about to be tested
  beforeEach: (testCase) => {
    readerMock.mockReturnValueOnce(
      // using the proposed prop to mock the returns of the file system method:
      JSON.stringify( testCase.env.packageJson )
    );
  }
});

tester.run("rule", rule, {
  valid: [
    {
      name: "some test",
      code: `some code`,
      options: ["some options"],
      // proposed property:
      env: {
        packageJson: { dependencies: { eslint: "^9.0.0" } }
      },
    },
    /* ...other cases with different env and options... */
  ],
  invalid: [ /* ... */ ]
});
```

### Additional Info

I believe this could be generally useful feature not only for my case, but could also simplify development for the community.

**Comment by RobinTail** [comment]
Or it can be only one new prop on the test case — `setup`:

```ts
tester.run("rule", rule, {
  valid: [
    {
      name: "some test",
      code: `some code`,
      options: ["some options"],
      // alternative proposed property, no hook needed in this case
      setup: () => {
        // ...
      },
    },
  ],
  invalid: [ /* ... */ ]
});
```

**Comment by JoshuaKGoldberg** [comment]
`RuleTester` currently hooks into the underlying test framework's `afterAll` and `it`. Would it be possible to get the desired results by using them directly?

```ts
// proposed hook receives the test case that is about to be tested
beforeEach: (testCase) => {
  readerMock.mockReturnValueOnce(
    // using the proposed prop to mock the returns of the file system method:
    JSON.stringify( testCase.env.packageJson )
  );
}

tester.run(/* ... */);
```

Our `RuleTester` is a fork of the core ESLint one, and we've tried to avoid adding any features not present in core. Every divergence we add makes it harder to maintain & conceptually more confusing for people coming over. It'd be preferable to avoid adding more typescript-eslint specifics if possible.

**Comment by RobinTail** [comment]
> `afterAll` and `it`. Would it be possible to get the desired results by using them directly?

No, not really.
Because `it` is not aware of the test case, it receives only the test name.
Theoretically, I could do:

```
const myIt = (name, fn) => {
  const before = mockEnvironmentDependingOnTheTestName( name );
  it(name, fn);
}
```

but THAT would mean storing the environment separately from the test cases.
What I'm suggesting allows to keep the environment details or preparation function right within each test case, next to options.

> Our RuleTester is a fork of the core ESLint one

I see. Should I address my request to ESLint repo instead, @JoshuaKGoldberg ?

**Comment by RobinTail** [comment]
> but THAT would mean storing the environment separately from the test cases.

Actually.... I've got an idea. Let me try something...

**Comment by RobinTail** [comment]
Yeah, I made it. The `Runner` class, wrapping around the `RuleTester`.
All it takes it a slightly different test cases declaration.
The `Runner` sets up the `RuleTester` with a custom `it` that finds and executes `before()` of each test case before running actual test.

```ts
// test.spec.ts

const readerMock = mock();
beforeAll(() => {
  mock.module("node:fs", () => ({
    readFileSync: readerMock,
  }));
});

const mockEnv = (env: object) =>
  readerMock.mockReturnValueOnce(JSON.stringify(env));

new Runner("dependencies", rule, {
  "test name": {
    code: `some code`,
    options: ["some options"],
    before: () => mockEnv({ /* package.json for the particular case */ }),
    // errors: can also be here for invalid cases (recognized by Runner)
  },
}).run();
```

```ts
// runner.ts

import { afterAll, describe, it } from "bun:test";
import parser from "@typescript-eslint/parser";
import {
  type InvalidTestCase,
  RuleTester,
  type ValidTestCase,
} from "@typescript-eslint/rule-tester";
import type { RuleModule } from "@typescript-eslint/utils/ts-eslint";

export class Runner<
  Options extends readonly unknown[],
  MessageId extends string,
> {
  constructor(
    protected title: string,
    protected ruleModule: RuleModule<MessageId, Options>,
    protected scenarios: Record<
      string,
      (ValidTestCase<Options> | InvalidTestCase<MessageId, Options>) & {
        before?: () => void;
      }
    >,
  ) {
    RuleTester.afterAll = afterAll;
    RuleTester.describe = describe;
    RuleTester.it = (...[name, ...rest]: Parameters<typeof it>) => {
      const { before } = scenarios[name];
      before?.();
      it(name, ...rest);
    };
  }

  public run() {
    const tester = new RuleTester({
      languageOptions: { parser },
    });
    const [valid, invalid] = Object.keys(this.scenarios).reduce<
      [ValidTestCase<Options>[], InvalidTestCase<MessageId, Options>[]]
    >(
      ([withoutErrors, withErrors], name) => {
        const { before, ...scenario } = this.scenarios[name];
        ("errors" in scenario ? withErrors : withoutErrors).push({
          name,
          ...scenario,
        });
        return [withoutErrors, withErrors];
      },
      [[], []],
    );
    tester.run(this.title, this.ruleModule, { valid, invalid });
  }
}
```

**Comment by RobinTail** [comment]
@JoshuaKGoldberg , so, I made it possible with a combination of the current arrangement and a wrapping solution having acceptable neatness for me.
Despite me believing that this should have been a built-in feature of `@typescript-eslint/rule-tester`, if it appears to you misaligned with the project concept, feel free to close the issue.

**Comment by bradzacher** [comment]
Yeah I agree with Josh here.
This doesn't seem like something exclusive to typescript lint rule testing as you mentioned the import plugin has similar infra.

And as we are trying to avoid adding many features beyond what's required to support TS linting - we wouldn't really want to take on something so large.

If this is valuable for you then the best path forward would be to submit it to eslint core. They might ask that you draft an RFC for the proposal.

Once it's accepted upstream we will gladly bring it in here to our fork!
