### ISSUE TITLE
https://github.com/outofambit/p5.js/runs/210129233#step:3:1

### ISSUE THREAD

**Issue by Rodion8888** [typescript-eslint/typescript-eslint#978]
**What code were you trying to parse?**

```ts
// Please put code here
```

**What did you expect to happen?**

**What actually happened?**

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `X.Y.Z` |
| `TypeScript`                | `X.Y.Z` |
| `ESLint`                    | `X.Y.Z` |
| `node`                      | `X.Y.Z` |
| `npm`                       | `X.Y.Z` |

**Comment by bradzacher** [comment]
I'm not sure what you're trying to tell us with this issue.
Please open a new issue with proper information
