### ISSUE TITLE
prevent definite-assignment-assertions

### ISSUE THREAD

**Issue by neilsoult** [typescript-eslint/typescript-eslint#9782]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

While there is a rule regarding the usage of non-null assertions, this rule does not cover a similar, but possibly more problematic feature: [definite assignment assertions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#definite-assignment-assertions)

definite assignment assertions can be quite problematic when abused, or simply used by developers to avoid strict null checks. It would be nice to have a rule that could prevent these assertions.

### Fail Cases

```TypeScript
class SampleClass {

    sampleProperty!: string;

}
```

### Pass Cases

```TypeScript
class SampleClass {

    sampleProperty: string = '';

}
```

### Additional Info

This may be an issue more common with framework developers, like Angular developers, as the most common usage for these might be for properties that are expected to be set during a lifecycle hook. However, even this usage is misguided and can lead to race conditions and problems that are hard to diagnose.

**Comment by bradzacher** [comment]
I think this falls under this FAQ
https://typescript-eslint.io/troubleshooting/faqs/general#how-can-i-ban-specific-language-feature

[playground](https://typescript-eslint.io/play#ts=5.5.2&fileType=.tsx&code=FAYwNghgzlAEDKEC2AHMBTAwpGsDewwssUya6ACgE4D2K6VALgJ4CMAhAFwmNUCWAOwDmAbkLFSqDNToMWAJm5RegobAC8sAERaxwAL7AgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQHYHsBaaFAF2gEsBjUxAE0OQE9dSBDAD3TAG1xsciaNHzRIAGn4DIABREAHIaSYARRADMKuCqQr5cPOhq07EYALxhysRAF1IUsLf4BfEC6A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

I don't see how a stand-alone rule could add value beyond this - eg there wouldn't be any options nor would there be a fixer.
