### ISSUE TITLE
Enhancement: [rule-tester] remove spurious dependency on `@eslint/eslintrc`

### ISSUE THREAD

**Issue by jakebailey** [typescript-eslint/typescript-eslint#9785]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

rule-tester

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

In https://github.com/microsoft/TypeScript/pull/59518 I was updating TS to use ESLint v9 and typescript-eslint v8. I noticed in the lockfile that `@eslint/eslintrc` was present even though I didn't depend on it. `npm why @eslint/eslintrc` gave me:

```
@eslint/eslintrc@3.1.0 dev
node_modules/@eslint/eslintrc
  peer @eslint/eslintrc@">=2" from @typescript-eslint/rule-tester@8.1.0
  node_modules/@typescript-eslint/rule-tester
    dev @typescript-eslint/rule-tester@"^8.1.0" from the root project
  @eslint/eslintrc@"^3.1.0" from eslint@9.9.0
  node_modules/eslint
    dev eslint@"^9.9.0" from the root project
```

My reading of this is that `eslint` itself still depends on this, so it can't go away, but I didn't realize this at the time and thought `@typescript-eslint/rule-tester` may be the only reason we had it. Searching though the package, I noticed that it never uses `@eslint/eslintrc`, so the dep could actually just be removed without any changes.

Filing an issue since I think you require one before sending a PR.

**Comment by auvred** [comment]
Yes, it looks like `@eslint/eslintrc` is no longer used after https://github.com/typescript-eslint/typescript-eslint/pull/9603. See https://github.com/typescript-eslint/typescript-eslint/pull/9603/files#diff-b88f39c4f2e3770e4f65307477b9eda24853b82aa30e678c28bf15d9202c5fc5L5
