### ISSUE TITLE
Docs: Next page navigation link pointing to current page

### ISSUE THREAD

**Issue by mattbrannon** [typescript-eslint/typescript-eslint#9799]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

The next page link at the bottom of https://typescript-eslint.io/troubleshooting/faqs/general points to the current url
It should probably point to https://typescript-eslint.io/troubleshooting/faqs/eslint

Bonus 

On [Github issues](https://github.com/typescript-eslint/typescript-eslint/issues/new/choose), the link to the FAQ points to https://typescript-eslint.io/linting/troubleshooting which redirects to https://typescript-eslint.io/troubleshooting/faqs/general

It should probably point to https://typescript-eslint.io/contributing/issues

### Affected URL(s)

https://typescript-eslint.io/troubleshooting/faqs/general

**Comment by kirkwaiblinger** [comment]
> The next page link at the bottom of https://typescript-eslint.io/troubleshooting/faqs/general points to the current url
> It should probably point to https://typescript-eslint.io/troubleshooting/faqs/eslint

When you've read the FAQs.... Read them again! 😂

> Bonus 
> 
> On [Github issues](https://github.com/typescript-eslint/typescript-eslint/issues/new/choose), the link to the FAQ points to https://typescript-eslint.io/linting/troubleshooting which redirects to https://typescript-eslint.io/troubleshooting/faqs/general
> 
> It should probably point to https://typescript-eslint.io/contributing/issues

How come you want to change it to the https://typescript-eslint.io/contributing/issues page? I would expect "FAQs" to take me to https://typescript-eslint.io/troubleshooting/faqs/general/, right?

**Comment by solana-hiro** [comment]
I wanna work with you.
