### ISSUE TITLE
Docs: Render backtick-ed text as code in blog titles

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9806]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

![Screenshot of https://typescript-eslint.io/blog/parser-options-project-true showing backticked-code in the "recent article" and main blog titles rendering as plain text with backticks](https://github.com/user-attachments/assets/8803de74-e5ba-413c-88bb-be9a9a942a55)

It'd be nice if we can render these as monospace `var(--ifm-font-family-monospace)` instead (though without a dark gray background color). Mocking in the dev tools:

![Screenshot of https://typescript-eslint.io/blog/parser-options-project-true showing backticked-code in the "recent article" and main blog titles rendering as monospace font](https://github.com/user-attachments/assets/2a96e727-ef69-46f5-844c-9f756ff93ff3)

### Affected URL(s)

https://typescript-eslint.io/blog/parser-options-project-true
#8031's blog post

💖

**Comment by Josh-Cena** [comment]
I think this is a Docusaurus limitation that they don't. H1 titles are used in many pure-text situations (most notably `<title>`) and we just simply don't support any markup in titles.

**Comment by JoshuaKGoldberg** [comment]
If it's relatively reasonable to override the components and use inline Markdown rendering, do you see any reason not to?

**Comment by Josh-Cena** [comment]
Nope I don't. Would be interesting to see how it goes.
