### ISSUE TITLE
Bug: [@typescript-eslint/no-unused-vars] falsely reports on generic type parameters used in declaration merging

### ISSUE THREAD

**Issue by lordnox** [typescript-eslint/typescript-eslint#9811]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.2&fileType=.tsx&code=PTAEEsFsEMHNwHYFNQGcD2kUBtwCMAnaAgTwkgAd0CAXAKERqQIDNoBjFAZUyQEkETVhyQAeACoARaDWigkADyYIAJqlABvAL4AaUOIBq0bAFckAPk11QoFggBcoABQqZ0R1LcBKUAF5LhsZmdFp0dCCgNAAW4OqoUegm2CqgCOg0ttDg2AyCzGycoDxYAkIFYp6y8kpIquraeoGmFlY2rrICKoqOBujgKgBiJgjsNODoCCFhEYgAbsb9kSQUSKjsBOAU9DN5woXF-LvlVhFtbp3doL39QyNjE%2BFgoWHsE6gZdn7OCgD8jgelfIiUTvDYIWB6UGIWDmHz%2BUAKOh2JxeIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tidmUQAmtAG4BDaKgwBtSImjQO0SAF1wYAL4h1QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
interface SomeInterface<TData extends {}, TValue> {
  fn: (data: TData) => TValue
}

interface SomeInterface<TData extends {}, TValue> {
  dataIndex: VoidFunction
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unused-vars": ["error"]
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

This should be fine without errors

### Actual Result

```
'TData' is defined but never used. 6:25 - 6:30
'TValue' is defined but never used. 6:43 - 6:49
```

### Additional Info

When removing the Generics we do end up with invalid typescript. I can not remove the generics as this is a library import.

```
// invalid typescript
interface SomeInterface {
  dataIndex: VoidFunction
}
```

These errors are valid and understandable:
```
2428: All declarations of 'SomeInterface' must have identical type parameters. 2:11 - 2:24
2428: All declarations of 'SomeInterface' must have identical type parameters. 6:11 - 6:24
2428: All declarations of 'SomeInterface' must have identical type parameters. 11:11 - 11:24
```

**Comment by Josh-Cena** [comment]
This is impossible to fix without making the rule type-aware. You should just use a disable comment here since it may be confusing to human readers too.

**Comment by kirkwaiblinger** [comment]
> ... it may be confusing to human readers too.

+1 😁

**Comment by bradzacher** [comment]
Yup this is working as intended. Or a known edge case limitation. A disable comment is the solution.

**Comment by lordnox** [comment]
Could I just ask where I could have found information about this? Just to prevent reporting bugs like this in the future.

**Comment by Josh-Cena** [comment]
When submitting a bug you would search for past bugs—that's how others could find this. If an issue is common enough it could be documented as a known limitation but I don't think it's big enough here.

**Comment by bradzacher** [comment]
Yup - issues searches first. Always search first (which is why it's a tick box in our issue form).

Eg searching for "no-unused-vars declaration merge" finds all of these https://github.com/typescript-eslint/typescript-eslint/issues/6720 and https://github.com/typescript-eslint/typescript-eslint/issues/4098 and https://github.com/typescript-eslint/typescript-eslint/issues/3573
