### ISSUE TITLE
Feature request - rule for circular imports

### ISSUE THREAD

**Issue by boris-petrov** [typescript-eslint/typescript-eslint#986]
I was just bit in our codebase by a file importing another and the other importing the first one. This leads to non-deterministic builds and hard-to-find bugs. A linter rule for that would be nice if it is possible.

Note that perhaps that should handle the case when one of the imports is a type-only one - that is, in that file the imported thing is only used as a type (which is fine and leads to no issues at runtime). Perhaps it should be configurable whether to allow such cases.

**Comment by bradzacher** [comment]
You should be able to do this via https://www.npmjs.com/package/eslint-plugin-import

**Comment by bradzacher** [comment]
You should be able to achieve this with `eslint-plugin-import`:

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-cycle.md

**Comment by opl-** [comment]
`eslint-plugin-import` does not support the case mentioned in the original issue: type only imports still result in an error, since the plugin is not aware that TypeScript ends up removing the import in the output.

**Comment by bradzacher** [comment]
well it depends on what you want.
If you want to eliminate _all_ cycles from your code, then `no-cycle` will do what you want.
If you instead want to eliminate all runtime cycles from your code, but allow type cycles, then no, it would require changes to that rule.

IMO you should endeavour to remove _all_ cycles from your codebase, but I can understand if you trust tsc to handle type cycles.

In either case, I'd suggest this as an enhancement to the rule in that plugin.
We don't have any infrastructure in place for analysing dependencies or the like, so adding it here would be a large piece of work, which we wouldn't be able to take on for quite some time.

**Comment by opl-** [comment]
Admittedly I kind of assumed that the import plugin wouldn't consider supporting TypeScript to be one of its goals, but it appears I might've been wrong.

This issue is already tracked under benmosher/eslint-plugin-import#1453

**Comment by bradzacher** [comment]
Looking at the linked issue, it seems like they're happy to have it implemented, as long as someone is willing to do the work. Just a matter of (re)implementing the logic babel uses to track scoped usages (non-trivial, but doable).

I'm going to close this, as we are not looking to implement this in this repo.
