### ISSUE TITLE
Bug: [no-unnecessary-type-parameters] False positive in function implementation (maybe this time?!)

### ISSUE THREAD

**Issue by eranhirsch** [typescript-eslint/typescript-eslint#9885]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.4&fileType=.tsx&code=GYVwdgxgLglg9mABOGBHEBTAQgTwDwAqANIgNIB8AFACYCGUtAXIgE4a3UIA2OiBA2gF0SAaww4AYuGjwwzSjCgYAtswIBKRAF5yZdWqGIA3gFgAUIkQQEAZyiIADmwBu8EDZ4BlDBiRbEYBgA7ojeUHgUlOoA3ObmlmxQICxIdAwAdMAwXEoslJTOtFyYmjrG8ZZWtvZivP61UpCwCAVFJbFmFZYwwIiUThiucO5ePmDpABa0NpS16pqmFpUJGEkpiMBFNhgdywC%2BcUuWA0MjON6%2B6RzUs%2BIxXayryUhQLJi7iHv3ZgedZqBNWTIMBoTC4AD6AAUAEoAeQIAFEAMKIgAihBIkTSTEeHG4vAEwkQDWkzTkfUUKjUpV0pH0fEMi0s1jAdkcLjcHnOY20AWCoVWESo3wqiWeiGxmWyuXyhWKGBp5SOVVZNXEvJJgJacvah2WPT6J05o0uUxmOoVCweKzWSE2XG2H0svweRuGXIu42utxw32WYvWr3eFS%2BHRd-1JQJQ6GwOHBWDhpARADlCFRscw2HiwDwGUTNTIEPJKao%2BIrwCIwHAgmB6YSlczquzBsbub5eYEQmE8BWqzXhR1RU91pKsjkMHlWvLFUzKiy2bUNeJGoWwFPdX99b1%2Bhz3Sbxmb15aG8tHraNlsdg9w8s3WdPVdqDc5k6z%2BKg1elqHzL8gA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWsRFCAtonyJoqDJCXQO0SODABfELqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
function uniqueBy<T, K>(data: readonly T[], keyFunction: (item: T) => K): T[] {
  const previouslySeen = new Set<K>();

  return data.filter((value) => {
    const key = keyFunction(value);

    if (previouslySeen.has(key)) {
      return false;
    }

    previouslySeen.add(key);
    return true;
  });
}

function uniqueBy_PROTECTED<T, K>(data: readonly T[], keyFunction: (item: T) => K): T[] {
  const previouslySeen = new Set<K>();

  return data.filter((value) => {
    const key = keyFunction(value);

    // @ts-expect-error [ts2345] - Wait... wat?! You can't change that, it would break
    if (previouslySeen.has(value)  /* was: previouslySeen.has(key) */) {
      return false;
    }

    previouslySeen.add(key);
    return true;
  });
}

function uniqueBy_BROKEN<T>(data: readonly T[], keyFunction: (item: T) => unknown): T[] {
  const previouslySeen = new Set<unknown>();

  return data.filter((value) => {
    const key = keyFunction(value);

    // welp now you can... :(
    if (previouslySeen.has(value) /* was: previouslySeen.has(key) */) {
      return false;
    }

    previouslySeen.add(key);
    return true;
  });
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-unnecessary-type-parameters": "error"
  },
};
```

### Expected Result

I don't think there is a type-safe way to remove the generic K without making the code vulnerable to unsafe changes.

### Actual Result

The rule claims that the generic K is redundant.

### Additional Info

This surfaced while migrating the [Remeda typescript library](https://github.com/remeda/remeda) to typescript-eslint v8. [PR #801](https://github.com/remeda/remeda/pull/801).

I know there have been several discussions of this already, but my typescript foo has left me defeated in finding a way around this, so I'm trying to divert the blame elsewhere...

**Comment by kirkwaiblinger** [comment]
Hi @eranhirsch! 

Would you mind reaching out to us on the discord for this? (see [docs for how to get help](https://typescript-eslint.io/contributing/issues#questions-and-support-requests))

This is difficult stuff (speaking for myself, at least 🙂) that I have a feeling will require some back-and-forth discussion to understand fully.

Thanks!

**Comment by eranhirsch** [comment]
From the discord discussion I realized I could have provided an easier example:

```ts
function uniqueBy<T, K>(
  data: readonly T[],
  keyFunction: (item: T, index: number, data: ReadonlyArray<T>) => K,
): T[] {
  const set = new Set<K>();
  return data.filter((value, index, arr) => {
    const key = keyFunction(value, index, arr);
    if (set.has(key)) {
      return false;
    }

    set.add(key);
    return true;
  });
}
```

**Comment by eranhirsch** [comment]
> IMO, you should just accept that the goal of generic functions is usually not safety within the function.

This is an internal implementation function: https://github.com/remeda/remeda/blob/main/src/uniqueBy.ts

I think it's problematic that a rule suggesting reducing type safety is added to the strict rule set. It makes sense for an optional rule to have these caveats, but once it's "canonical," especially in the strict rule set, it shouldn't have use cases where its result is less strict.

Generics are largely inferred automatically (at least they should be, as that is also what's recommended in the typescript handbook). I think the main goal for type-script is type-safety, and not ergonomics, so it makes more sense to err on the side of not suggesting these kinds of removals.

**Comment by kirkwaiblinger** [comment]
Discord conversation for reference: https://discord.com/channels/1026804805894672454/1277724313637617676

**Comment by kirkwaiblinger** [comment]
I'd say we've determined, using the simpler reproduction, that this _is_ definitely a "working as intended" report in terms of the generic not relating multiple types in the signature. Instead, the issue report concerns TS applying slightly more strict checking in the original form since generics are not cross-assignable (essentially treating the unconstrained generics as two different nominal types). Replacing one of the unconstrained generics, `K`, with `unknown`, the other unconstrained generic, `T`, becomes assignable to the locations where only `K` would have been assignable previously.

IMO it's _not_ a type safety loosening, however. It's purely a _logic_ error within the function body that the generic version coincidentally prevents. Note that that also may well be the _correct_ logic in other cases, where unnecessarily using a generic prevents intended cross-assignability.

So, for my money, this is fully working as intended (but yet another example of [very subtle behavior related to this rule](https://github.com/typescript-eslint/typescript-eslint/issues/9680))

**Comment by bradzacher** [comment]
I would agree too. This is a really cool and interesting usage to create a nominal type to avoid logic bugs - but by the definition of the rule it is reporting correctly.

For example. Your signature would allow this:
```ts
uniqueBy<number, 0 | 1>([], () => 1)
```
The user can pass "incorrect" types. Though in your example this thankfully won't impact the overall safety of the signature.

Using a disable comment here would be the correct thing to do - disable with a description mentioning why there's an intentionally unnecessary parameter.

**Comment by eranhirsch** [comment]
It makes sense to consider moving the rule from the `strict` config to the `stylistic` config and maybe reducing the level to "warn" instead of "error".

> [strict](https://typescript-eslint.io/users/configs#strict): a superset of recommended that includes more opinionated rules which may also catch bugs.
> [stylistic](https://typescript-eslint.io/users/configs#stylistic): additional rules that enforce consistent styling without significantly catching bugs or changing logic.

I can't think of a situation where it surfaces a runtime bug in the code (a bug that would happen in the transpiled JS). It only deals with how generics should be used, which is a stylistic concern as it's entirely removed in the transpiled code.

**Comment by JoshuaKGoldberg** [comment]
> and maybe reducing the level to "warn" instead of "error"

We don't generally do that for our configs, as we've found users tend to leave warnings around as noise. They can accidentally train devs to ignore the linter if around too long. 😬 

But, it sounds like you've got a lot of nuanced type-parameters-edge-case-y code that's tripping up the rule. I'd suggest for you or anybody reading this in a similar situation - you can always `"warn"` on your side a bit to get used to it / find any initial bugs.

> I can't think of a situation where it surfaces a runtime bug in the code (a bug that would happen in the transpiled JS). It only deals with how generics should be used, which is a stylistic concern as it's entirely removed in the transpiled code.

Answered in https://github.com/typescript-eslint/typescript-eslint/issues/9887#issuecomment-2312659614 - tl;dr is that the types declared in type system _are_ logical, not just stylistic.
