### ISSUE TITLE
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

### ISSUE THREAD

**Issue by JoezerSmaniotto** [typescript-eslint/typescript-eslint#9894]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

ast-spec

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

When updating my react-native application that uses expo from SDK version 49 to SDK 50, when running the command "npx expo install --fix" this message appeared
"
The following packages must be updated for better compatibility with the installed expo version:
typescript@5.1.6 - expected version: ^5.3.0
Your project may not work correctly until you install the correct versions of the packages.
› Installing 1 native module compatible with SDK 50.0.0 using npm

npm installation
"

I updated typescript to version 5.5.4 and when running lint I get this error
"
WARNING: You are currently running a version of TypeScript that is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works very well or not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0

YOUR TYPESCRIPT VERSION: 5.5.4

Please only submit bug reports when using the officially supported version.

"

What really happened?
When updating my react-native application that uses expo from SDK version 49 to SDK 50, when running the command "npx expo install --fix" this message appeared
"
The following packages must be updated for better compatibility with the installed expo version:
typescript@5.1.6 - expected version: ^5.3.0
Your project may not work correctly until you install the correct versions of the packages.
› Installing 1 native module compatible with SDK 50.0.0 using npm

npm installation
"

I updated typescript to version 5.5.4 and when running lint I get this error
"
WARNING: You are currently running a version of TypeScript that is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works very well or not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0

YOUR TYPESCRIPT VERSION: 5.5.4

Please only submit bug reports when using the officially supported version.

"

### Additional Info

When updating my react-native application that uses expo from SDK version 49 to SDK 50, when running the command "npx expo install --fix" this message appeared
"
The following packages must be updated for better compatibility with the installed expo version:
typescript@5.1.6 - expected version: ^5.3.0
Your project may not work correctly until you install the correct versions of the packages.
› Installing 1 native module compatible with SDK 50.0.0 using npm

npm installation
"

I updated typescript to version 5.5.4 and when running lint I get this error
"
WARNING: You are currently running a version of TypeScript that is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works very well or not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0

YOUR TYPESCRIPT VERSION: 5.5.4

Please only submit bug reports when using the officially supported version.

"

What really happened?
When updating my react-native application that uses expo from SDK version 49 to SDK 50, when running the command "npx expo install --fix" this message appeared
"
The following packages must be updated for better compatibility with the installed expo version:
typescript@5.1.6 - expected version: ^5.3.0
Your project may not work correctly until you install the correct versions of the packages.
› Installing 1 native module compatible with SDK 50.0.0 using npm

npm installation
"

I updated typescript to version 5.5.4 and when running lint I get this error
"
WARNING: You are currently running a version of TypeScript that is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works very well or not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0

YOUR TYPESCRIPT VERSION: 5.5.4

Please only submit bug reports when using the officially supported version.

"

**Comment by kirkwaiblinger** [comment]
Hi @JoezerSmaniotto, the errors you're seeing arise when you're not using a sufficiently recent version of the `@typescript-eslint/parser` package. Please update to the latest 🙂.

**Comment by JoezerSmaniotto** [comment]
Hi @kirkwaiblinger, 
I updated to a newer version, but it still gives me an error or bug
--------------------------------------------
============

WARNING: You are running a version of TypeScript that is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works fine, or it may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0

YOUR TYPESCRIPT VERSION: 5.3.3

Please only file bug reports when using the officially supported version.

=============

Oops! Something went wrong! ) C:\Users\joezer-pnt\Documents\PlugnTrade\mobileapp-v2\node_modules\@typescript-eslint\eslint-plugin\dist\rules\prefer-optional-chain-utils\gatherLogicalOperands.js:33:33) in gatherLogicalOperands (C:\Users\joezer-pnt\Documents\PlugnTrade\mobileapp-v2\node_modules\@typescript-eslint\eslint-plugin\dist\rules\prefer-optional-chain-utils\gatherLogicalOperands.js:204:21) in LogicalExpression[operator!="??"] \PlugnTrade\mobileapp-v2\node_modules\@typescript-eslint\eslint-plugin\dist\rules\prefer-optional-chain.js:152:107) in ruleErrorHandler (C:\Users\joezer-pnt\Documents\PlugnTrade\mobileapp-v2\node_modules\eslint\lib\linter\linter.js:1076:28)
at C:\Users\joezer-pnt\Documents\PlugnTrade\mobileapp-v2\node_modules\eslint\lib\linter\safe-emitter.js:45:58
at Array.forEach (<anonymous>)
at Object.emit (C:\Users\joezer-pnt\Documents\PlugnTrade\mobileapp-v2\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
at NodeEventGenerator.applySelector (C:\Users\joezer-pnt\Documents\PlugnTrade\mobileapp-v2\node_modules\eslint\lib\linter\node-event-generator.js:297:26) in NodeEventGenerator.applySelectors (C:\Users\joezer-pnt\Documents\PlugnTrade\mobileapp-v2\node_modules\eslint\ lib\linter\node-event-generator.js:326:22) in NodeEventGenerator.enterNode (C:\Users\joezer-pnt\Documents\PlugnTrade\mobileapp-v2\node_modules\eslint\lib\linter \node-event-generator.js:340:14) 
--------------------------------------- 

"npm i @typescript-eslint/typescript-estree" updated to 3 days ago it was updated to "@typescript-eslint/typescript-estree@8.3.0" and the installed version is "8.3.0" but it still has the same error described above.

**Comment by kirkwaiblinger** [comment]
Hmm. My money is still on a dependency issue. Guessing you'll need to dedupe your dependencies and/or use `npm list` (or equivalent depending on your package manager) to figure out why a rogue version is included.

Can you provide a minimal reproduction? Without a repro, there's not really much we can do. (why we ask for this: https://antfu.me/posts/why-reproductions-are-required)

For future reference, please [follow the directions in the contributing guide](https://typescript-eslint.io/contributing/issues/#questions-and-support-requests) for how to seek support.
