### ISSUE TITLE
Bug: [no-unnecessary-type-assertion] fixer produces incorrect code for ternary operator in parenthesis

### ISSUE THREAD

**Issue by yume-chan** [typescript-eslint/typescript-eslint#9897]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.4&fileType=.tsx&code=MYewdgzgLgBAhjAvDARCg3AWAFCkrAIwC4ZoAnASzAHMYAfGAVzABMBTAMyrZaRgAoEAfiatO3XiTgBKAITogA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0UOdA7RI4MAF8QOoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
const a = "";
const b: string | undefined = (a ? undefined : a)!;
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/no-unnecessary-type-assertion": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

Run fixer on line 2 should produce `const b: string | undefined = a ? undefined : a;`

### Actual Result

The fixer produces `const b: string | undefined = (a ? undefined : a;`, which is invalid code.

**Comment by kirkwaiblinger** [comment]
@yume-chan  yep! that's a 🐛 

From two seconds of playing, looks like it might be only the TSNonNullExpression fixer that has this problem, since the following fixed fine:
```ts
const a = "";
const b: string | undefined = (a ? undefined : a) as '' | undefined;
```

**Comment by kirkwaiblinger** [comment]
Looks like this was previously fixed for some report cases as part of https://github.com/typescript-eslint/typescript-eslint/pull/8143, see https://github.com/typescript-eslint/typescript-eslint/pull/8143#discussion_r1449164364, just not copied to all of them.
