### ISSUE TITLE
Enhancement: Need different style of project service determination for react-native mixed package

### ISSUE THREAD

**Issue by ToyboxZach** [typescript-eslint/typescript-eslint#9901]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-estree

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

This link suggested I open an issue explaining my use case:
https://typescript-eslint.io/troubleshooting/typed-linting/#allowdefaultproject-glob-too-wide

I have a problem enabling the project service in my eslint. 

I have a mixed directory of both react-native-web and native files ie:

lib/datePicker.tsx
lib/datePicker.ios.tsx

And have setup my React native and my web to correctly read only the correct files, which is the standard way suggested by react-native (or at least it was when I did it)

The problem with the typescript is I may have packages that are available on web, but not on a react-native or vice versa so I end up with two different typescript "packages" that I am building, my website and my app. The app lives under /app/tsconfig.json which prefers .ios files if it exists

and the web lives under /tsconfig.json which ignores .ios files

But for lint I am able to just have one eslint config that covers all of my files.

My problem with the project service is that it wants to use the closest tsconfig to my file, but my .ios files are scattered throughout my whole project so the closest tsconfig.json ends up being wrong one, and the includes don't map correctly.

So, my request is just to let me assign a glob of files to a specific project even though its not the closest, or even just have a default package that can include all of my .ios files that are scattered through my project.

I think this helpful for anyone who uses a system other than "closest file is the best tsconfig" so it could likely help out some monorepo cases too.

**Comment by bradzacher** [comment]
Quick drive by comment:
If you're looking for complex and customisable setup - could you use `project: string[]`?

**Comment by ToyboxZach** [comment]
That is what we are currently doing, but reading through issues, switching to the project service is in theory supposed to fix the OOM crash I am seeing, only on circleci. I wanted to take a stab at the project service to see if it does actually help, but this is blocking me from doing that.

**Comment by JoshuaKGoldberg** [comment]
Hmm, I'm wondering if this is matches the FAQ added in https://github.com/typescript-eslint/typescript-eslint/pull/9871 -> https://main--typescript-eslint.netlify.app/troubleshooting/typed-linting#id-like-to-use-tsconfigs-other-than-tsconfigjsons-for-project-service-type-information? (on our canary branch now, will be published as stable on Monday)

Could you please post a reproduction we can see? I _think_ I get what you're saying but we can't be certain without code to play with.

**Comment by JoshuaKGoldberg** [comment]
So, following up a couple weeks later:

> I think this helpful for anyone who uses a system other than "closest file is the best tsconfig" so it could likely help out some monorepo cases too.

I think this is resolved as _"you're holding it wrong"_. Which might seem kind of hostile at first 😅 but that's really the right direction for TSConfigs. `tsconfig.json` is your source of type information for editing and linting; any other TSConfigs are ancillary.

Closing this out as a previously-resolved docs issue, but someone let me know if we're going down a wrong path please. Cheers!
