### ISSUE TITLE
Bug: Project service should not load TypeScript plugins by default

### ISSUE THREAD

**Issue by aweber1** [typescript-eslint/typescript-eslint#9905]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

This is a bit of an odd issue, and to be honest I'm not sure if the problem lies with `typescript-eslint` or `gql-tada`. I'm opening the issue here because it's only reproducible when `projectService` is enabled for `typescript-eslint`.

I've left more detailed notes and repro steps in the linked repo readme.md.

Essentially, the problem is:
When `projectService: true` for `typescript-eslint` and the `gql-tada` TypeScript plugin is configured to load a GraphQL schema from a local file, the lint process does not exit when done.

When `project: true`, i.e. `projectService` is disabled, and the `gql-tada` TypeScript plugin is configured to load a GraphQL schema from a local file, the lint process exits as expected.

When the `gql-tada` TypeScript plugin is configured to load a GraphQL schema from a URL, everything works ok regardless of `projectService` or `project`.

`gql.tada`: https://gql-tada.0no.co/

### Reproduction Repository Link

https://github.com/aweber1/typescript-eslint-gql-tada-repro

### Repro Steps

1) clone the repo
2) `npm install`
3) `npm run generate:schema`
3) `npm run lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `8.3.0` |
| `@typescript-eslint/parser`            | `8.3.0` |
| `@typescript-eslint/scope-manager`     | `8.3.0` |
| `@typescript-eslint/typescript-estree` | `8.3.0` |
| `@typescript-eslint/type-utils`        | `8.3.0` |
| `@typescript-eslint/utils`             | `8.3.0` |
| `TypeScript`                           | `5.5.4` |
| `ESLint`                               | `8.57.0` |
| `node`                                 | `20.10.0` |

**Comment by aweber1** [comment]
> Note: when typescript-eslint `project` is `true` and the `gql-tada` `schema` property is set to a local file, the linter will run and exit as expected. The issue only occurs when `schema` is a local file _and_ `projectService` is `true`.

# Workarounds

## Option 1 - adjust `typescript-eslint` settings

* Adjust `eslint.config.mjs`:
  - Set `parserOptions.projectService` to `false` (or omit the property)
  - Set `parserOptions.project` to the path of the `tsconfig.json` file or `true`

* Run `npm run lint`

Observe that the linter will run and exit

## Option 2 - adjust the `gql-tada` configuration

* Change the `tsconfig.gql-tada.json` file:
  - Set the `schema` property to a GraphQL schema endpoint URL instead of a local file

* Run `npm run lint`

Observe that the linter will run and exit

**Comment by aweber1** [comment]
## Investigation notes

There seems to be some sort of conflict between the `typescript-eslint` `projectService` and the `gql-tada` "GraphQLSP" when `projectService` is enabled. Perhaps a conflicting file watcher or something to that effect?

I have tracked it down to where I think the conflict/issue stems from, and it's when the GraphQLSP loads a schema and attaches a watcher to it, i.e. `schema.autoupdate`:
https://github.com/0no-co/GraphQLSP/blob/1ef3b51b7c83bf3972d4cabf0f1b7b66e8472071/packages/graphqlsp/src/graphql/getSchema.ts#L152

When `projectService` is enabled, the lint process seems to hang after calling `ref.autoupdate()` in the linked code above. If I remove that `autoupdate` call manually, the process will exit as expected with `projectService` enabled.

When `projectService` is disabled, the lint process will exit as expected even with the `autoupdate` call in place.

**Comment by bradzacher** [comment]
> GraphQLSP loads a schema and attaches a watcher to it

That's likely what causes the issue, yeah.
If there's a file watcher attached then node will not exit as it sees an open handle and will wait till the handle is closed before exiting. This is why our tooling reconfigures TS so that it doesn't attach any watchers.

This isn't a bug with gql tada though - this is a bug with us. The project service should not load language service plugins. To do so is inviting these sorts of problems.

As an example where this errors - there is an LS plugin that allows you to show eslint checks via TS in your IDE. If we load that LS plugin then we'd get stuck in an infinite loop as we'd lint with eslint, it'd load the project service which would load the plugin which would lint with eslint...

**Comment by bradzacher** [comment]
Cc @JoshuaKGoldberg - this is a fun bug!

**Comment by JoshuaKGoldberg** [comment]
This is fun! Agreed, it does look like we'll need to disable plugins.

cc @jakebailey - I tried setting `allowLocalPluginLoads: false,` in the project service settings, as well as `service.allowLocalPluginLoads = false`, but that didn't stop it from loading this plugin. Is there a known good way to disable plugin loads altogether including node_modules/ ones?

**Comment by jakebailey** [comment]
Reading the code, plugins are loaded unconditionally in `ProjectService.loadConfiguredProject` by calling `project.enablePluginsWithOptions`; `allowLocalPluginLoads` is a different option entirely, intended to allow people to import plugins that _aren't_ in `node_modules` (generally not allowed for security reasons).

There isn't an official way to disable plugin loads, I don't think, however, I believe you could trick it into not loading plugins by ensuring the host you pass in does not have `require` or `importPlugin` props, which causes `enablePluginsWithOptions` to bail early.
