### ISSUE TITLE
Enhancement: [no-misused-promises] checksVoidReturn attributes granularity

### ISSUE THREAD

**Issue by htunnicliff** [typescript-eslint/typescript-eslint#9930]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-misused-promises/

### Description

I propose that the `no-misused-promises` rule configuration option `checksVoidReturn` be made more granular by supporting `attributes` by name, in addition to its existing boolean value.

```diff
interface ChecksVoidReturnOptions {
  arguments?: boolean;
- attributes?: boolean;
+ attributes?: boolean | string[]; 
  inheritedMethods?: boolean;
  properties?: boolean;
  returns?: boolean;
  variables?: boolean;
}
```

### Fail

```TypeScript
/*
// .eslintrc
{
  rules: {
    "@typescript-eslint/no-misused-promises": "error"
  }
}
*/

export function SomeComponent() {
  return (
    <form 
      onSubmit={async () => await Promise.resolve()} // Fails ❌
      onChange={async () => await Promise.resolve()} // Fails ❌ 
    />;
  );
}
```

### Pass

```TypeScript
/*
// .eslintrc
{
  rules: {
    "@typescript-eslint/no-misused-promises": [
      "error",
      {
        checksVoidReturn: {
          attributes: ["onSubmit"]
        }
      }
    ]
  }
}
*/

export function SomeComponent() {
  return (
    <form 
      onSubmit={async () => await Promise.resolve()} // Passes ✅
      onChange={async () => await Promise.resolve()} // Fails ❌
    />;
  );
}
```

**Comment by bradzacher** [comment]
I'm not sure I understand the usecase here.

The types are declared to accept a void returning function. So the rule is correct to report.
Why is passing an async function in spite of the types correct?

**Comment by htunnicliff** [comment]
Sorry if my description wasn't super clear.

The specific use case is that we want to have this rule fully enabled, with the one exception of `onSubmit` attributes in JSX. This is due to our project using React Hook Form, which provides a promise-returning function that we place into a `<form>` element's `onSubmit` attribute.

We'd like to whitelist the `onSubmit` attribute. Here's what I mean:

```jsonc
// Current technique
{
  "rules": {
    "@typescript-eslint/no-misused-promises": [
      "error",
      {
        "checksVoidReturn": {
          "attributes": false // Skips all attributes
        }
      }
    ]
  }
}
```

```jsonc
// Proposed technique
{
  "rules": {
    "@typescript-eslint/no-misused-promises": [
      "error",
      {
        "checksVoidReturn": {
          "attributes": ["onSubmit"] // Checks everything BUT onSubmit
        }
      }
    ]
  }
}
```

Does that make sense?

**Comment by bradzacher** [comment]
sorry to clarify: I understand what you want.
What I don't understand is the *why*.

Why should this special case allowed?

> which provides a promise-returning function that we place into a <form> element's onSubmit attribute.

Why is this "safe" when the types are not typed to accept a promise?

**Comment by bradzacher** [comment]
It has been over four weeks without response from OP.
Closing out.
