### ISSUE TITLE
Repo: Allow selecting eslint-plugin in "✨ Enhance Another Package" template

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9963]
### Suggestion

Coming over from https://discord.com/channels/1026804805894672454/1283088823298818079: right now, if you want to propose a structural improvement in `@typescript-eslint/eslint-plugin`, there's no template for you.

* The first four templates are all around rules, not the surrounding `eslint-plugin` package
* _✨ Enhance Another Package_ doesn't include `eslint-plugin` in the allowed packages

Proposal: let's add that do the _Relevant Package_ dropdown?

### Additional Info

💖

**Comment by kirkwaiblinger** [comment]
+1
