### ISSUE TITLE
Bug: type definitions for use-at-your-own-risk/eslint-recommended-raw are missing

### ISSUE THREAD

**Issue by CXuesong** [typescript-eslint/typescript-eslint#9967]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-eslint

### Repro Code

```TypeScript
// @ts-check
import { default as tseslintRecommendedRaw } from "@typescript-eslint/eslint-plugin/use-at-your-own-risk/eslint-recommended-raw"; // ts7016
import eslintPluginSvelte from "eslint-plugin-svelte";
import svelteEslintParser from "svelte-eslint-parser";
import tseslint from "typescript-eslint";

// This is a part of ESLint flat config.
export const svelteConfig = tseslint.config(
  ...eslintPluginSvelte.configs["flat/recommended"],
  {
    files: ["*.svelte", "**/*.svelte"],
    languageOptions: {
      parser: svelteEslintParser,
      parserOptions: {
        extraFileExtensions: [".svelte"],
        parser: "@typescript-eslint/parser",
      },
    },
    rules: {
      // Re-apply TSLint rules to svelte code blocks
      // to avoid ESLint false-positives on, e.g., no-undef.
      ...tseslintRecommendedRaw.default("minimatch").rules,
    },
  },
  {
    rules: {
      // override/add rules settings here, such as:
      // 'svelte/rule-name': 'error'
    },
  },
);
```

### ESLint Config

```javascript
N/A
```

### tsconfig

```jsonc
N/A
```

### Expected Result

I should be able to import `@typescript-eslint/eslint-plugin/use-at-your-own-risk/eslint-recommended-raw` without any typing error.

### Actual Result

I see TS7016.

> Could not find a declaration file for module '@typescript-eslint/eslint-plugin/use-at-your-own-risk/eslint-recommended-raw'. '.../node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended-raw.js' implicitly has an 'any' type.
>  Try `npm i --save-dev @types/typescript-eslint__eslint-plugin` if it exists or add a new declaration (.d.ts) file containing `declare module '@typescript-eslint/eslint-plugin/use-at-your-own-risk/eslint-recommended-raw';`ts(7016)

### Additional Info

Discord thread: https://discord.com/channels/1026804805894672454/1283088823298818079

I'm trying to set up eslint with typescript support for script blocks in svelte files. However, I saw eslint complaining about `no-undef` violations inside svelte files (ts files works well), which should have been disabled by `tseslint.configs.recommendedTypeChecked` per my configuration. After checking the definition of `recommendedTypeChecked`, it seems [these presets are only applied to .js/.ts files](https://github.com/typescript-eslint/typescript-eslint/blob/4d31ebe71ac26612a129ac4be98692b11387145e/packages/eslint-plugin/src/configs/eslint-recommended-raw.ts#L21).

So I guess this could be worked around if I can somehow re-apply the rules once more, with `*.svelte` as `files`, and that's why I'm resorting to the raw rules exported here.

By checking its package.json file, I believe the specified .d.ts files are actually missing from the package:

package.json: https://unpkg.com/browse/@typescript-eslint/eslint-plugin@8.5.0/package.json
root folder: https://unpkg.com/browse/@typescript-eslint/eslint-plugin@8.5.0/

As this is js file, and eslint won't check for typings when importing the file, there is no actual production impact, but there will be noise when in IDE.

Another possible workaround mentioned by Josh is
```ts
const tseslintPlugin = require("@typescript-eslint/eslint-plugin");

console.log(tseslintPlugin.configs['eslint-recommended'].overrides[0].rules);
```

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `8.5.0` |

**Comment by aryaemami59** [comment]
I have a fix for this, I know the issue doesn't have the "accepting PRs" label yet, but would the maintainers be okay if I put up a PR?

**Comment by JoshuaKGoldberg** [comment]
Oops, sorry for the delay - yes please!

**Comment by aryaemami59** [comment]
@JoshuaKGoldberg Awesome, thank you!
