### ISSUE TITLE
Bug: [prefer-promise-reject-errors (and other rules too)] Cannot convert Symbol to string (8.6.0 regression)

### ISSUE THREAD

**Issue by AviVahl** [typescript-eslint/typescript-eslint#9999]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.2&fileType=.tsx&code=KYDwDg9gTgLgBAYwDYEMDOa4FkVgErADmAlmjFAJ4A8A0gDRwAqAfHAN4BQccYArgEZJiCOMRjAAtpgC8cAHbAA7tly0GLABQBKANxceAoSIDaAZQoT%2BEJADoxwKChjQAutvb7uUYDF5Q5cDAAFqR24lJmFla29o7OUG66%2BgC%2BHKlAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0Wlo4D2AW0rJEtTgCtEZOr2gDoqDJHmLI4MAF8QWoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
export class MapRegistry<K, T> {
  public items = new Map<K, T>();
  public [Symbol.iterator]() {
    return this.items[Symbol.iterator]();
  }
}
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/prefer-promise-reject-errors": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

lint should pass

### Actual Result

`TypeError: Cannot convert a Symbol value to a string`

### Additional Info

8.5.0 works fine

**Comment by kirkwaiblinger** [comment]
Oh, this sounds like https://github.com/typescript-eslint/typescript-eslint/pull/9836, see also https://github.com/typescript-eslint/typescript-eslint/issues/8386

**Comment by kirkwaiblinger** [comment]
cc @abrahamguo

**Comment by kirkwaiblinger** [comment]
99% certain the root cause is that this code right here

https://github.com/typescript-eslint/typescript-eslint/blob/c11ca06f0042d2784de7e169f49d85aba4536d5a/packages/eslint-plugin/src/util/misc.ts#L253-L258

doesn't account for the fact that the static value can be a symbol, which will immediately throw when coerced to string

**Comment by JavaScriptBach** [comment]
I also get `TypeError: Cannot convert a Symbol value to a string` when running `@typescript-eslint/no-unnecessary-condition` on Typescript-ESLint 8.6.0, with ESLint 8.57.0. Here is a stack trace if it's helpful:


```
TypeError: Cannot convert a Symbol value to a string
Occurred while linting <redacted>
Rule: "@typescript-eslint/no-unnecessary-condition"
    at getStaticMemberAccessValue (<redacted>/node_modules/@typescript-eslint/eslint-plugin/dist/util/misc.js:207:43)
    at isArrayMethodCallWithPredicate (<redacted>/node_modules/@typescript-eslint/eslint-plugin/dist/util/isArrayMethodCallWithPredicate.js:44:69)
    at checkCallExpression (<redacted>/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-condition.js:339:59)
    at ruleErrorHandler (<redacted>/node_modules/eslint/lib/linter/linter.js:1076:28)
    at <redacted>/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (<redacted>/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (<redacted>/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (<redacted>/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (<redacted>/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
```

**Comment by abrahamguo** [comment]
Sounds good. This will be an easy fix, I will plan on opening a PR with the fix in the next 12 hours unless someone beats me to it 😄
